rstudio/rstudio

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
Address #10223
Use the correct localized string for this UI element
I believe there are existing tests that might be sensitive to this, but didn't check.
Simple visual check is sufficient. No known functionality problems with this bug, just a labeling issue.
> fix General tab label on global prefs

- CMakeGlobals.txt
- cmake/modules/FindLibR.cmake
>  Getting RStudio to build on Windows ARM native systems, with some extra info to help with debugging
> NA
> Adding compatibility for Windows ARM cmake builds + debugging statements

- src/cpp/core/file_lock/FileLock.cpp
- src/cpp/core/r_util/RUserData.cpp
adresses #10151
using hint from @kevinushey in #10151
I don't have access to a windows machine to test this, I just followed the suggestion. See https://github.com/rstudio/rstudio/issues/10151#issuecomment-981975010 for how to (no longer) reproduce the problem🤞.
> Error starting r win 10151

- src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RmdFrontMatter.java
adresses #10152
Using `new Date().toISOString().replace(/T.*$/, "")`
> format date as yyyy-mm-dd in new R markdown ui

- NEWS.md
- src/gwt/acesupport/snippets/snippets/r.js
Addresses issue #10009. Snippet is outdated, because (1) is based on the soft-deprecated style of writing shiny modules; (2) is not in line with the camelCase style used in shiny.
Risks: 
1. New snippet imposes new style of writing shiny module, but this new style is recommended since shiny 1.5.0 (released 2020-06-23). Taking this into account,this change shouldn't be surprise for users.
2. New snippet imposes camelCase (previously: snake_case), but this also shouldn't be surprise for users since this is style used in shiny.
No tests. Change is small and tests are out of my skills.
Snippet can be compare to the code in manual page of shiny modules: https://shiny.rstudio.com/articles/modules.html 
**Contributor agreement was signed and send to email address mentioned in Contributor …
> update snippet for shiny module (#10009)

- src/cpp/session/resources/dependencies/r-packages.json
addresses #10230 
reverts #9847 but then bump requirements induced by `rmarkdown` 2.10: https://github.com/rstudio/rmarkdown/blob/v2.10/DESCRIPTION
> Dial back shiny requirement

- src/cpp/session/modules/SessionDataViewer.R
Addresses https://github.com/rstudio/rstudio/issues/9771.
Match the column label based on the column name if possible, and the index if not.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/9771.
> ensure correct variable label chosen in data viewer

- NEWS.md
- src/cpp/session/modules/SessionTerminalShell.cpp
- src/cpp/session/resources/terminal/hooks
Addresses https://github.com/rstudio/rstudio/issues/10274.
> place conda utilities on PATH for windows

- src/node/desktop/forge.config.js
Small tweak, got the message "Should be notarizing, but environment variables APPLE_ID or APPLE_ID_PASSWORD are missing!" when I did "yarn start" on Windows, so made that code Mac-only.
> Only run notarization logic on osx

- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
Use dependency buckets for fetching Quarto during dependencies download.
Create upload script, update dependency paths.
N/A
Should be no observable change in behavior.
> Use Buckets for Quarto Dependency

- src/cpp/core/include/core/libclang/LibClang.hpp
- src/cpp/core/include/core/r_util/RToolsInfo.hpp
- src/cpp/core/r_util/RToolsInfo.cpp
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/modules/SessionClang.R
- src/cpp/session/modules/build/SessionBuildEnvironment.cpp
- src/cpp/session/modules/clang/RCompilationDatabase.cpp
- src/cpp/session/modules/clang/RCompilationDatabase.hpp
- src/cpp/session/modules/clang/SessionClang.cpp
- src/cpp/session/modules/clang/SessionClang.hpp
Support C++ diagnostics etc. on Windows when using R 4.2.x with rtools42.
Mostly straightforward updates (that are just a bit tough to run down).
N/A; no testing on Windows yet.
Test that C++ diagnostics work as expected on Windows.
> support C++ diagnostics etc with rtools42

- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
Follow up to #8884 after #10366
Once the command is executed, reset to previous input always, not just if it is empty
> Always display.setText()

- NEWS.md
- src/cpp/core/include/core/system/PosixSystem.hpp
- src/cpp/core/system/PosixSystem.cpp
- src/cpp/core/system/PosixSystemTests.cpp
- src/cpp/rstudio-tests.in
- src/cpp/shared_core/include/shared_core/system/PosixSystem.hpp
- src/cpp/shared_core/system/PosixSystem.cpp
OS companion for https://github.com/rstudio/rstudio-pro/pull/3215 
The OS side of the changes for the PR above.
* There were changes automated
The feature is not directly used by Workbench at this point
> Companion PR for Pro 3215

- NEWS.md
Per [this comment](https://github.com/rstudio/rstudio/issues/9344#issuecomment-1021624714), adding comparison to R's native grep functions
> Editing NEWS item for Find in File's move to extended grep

- package/osx/CMakeLists.txt
- package/osx/cmake/codesign-package-electron.cmake
- package/osx/cmake/codesign-package.cmake
- package/osx/scripts/codesign-package.sh
- package/osx/scripts/merge-electron.mjs
- src/gwt/CMakeLists.txt
- src/node/desktop/CMakeLists.txt
- src/node/desktop/forge.config.js
- src/node/desktop/package.json
Ensure that the macOS Electron package build is properly signed.
Implement our own helper script for codesigning, to ensure that we properly recursively sign everything in our created package. Also validate the signature after we finish the signature.
The build system is the automated test. :-)
N/A
> fixups for code signing on macOS

- src/cpp/session/modules/SessionFind.cpp
> Switch regex bitflags to perl flavor

- src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
- src/gwt/src/org/rstudio/studio/RStudioDesktopSuperDevMode.gwt.xml
- src/gwt/src/org/rstudio/studio/RStudioSuperDevMode.gwt.xml
This PR updates RStudio.gwt.xml , RStudioSuperDevMode.gwt.xml, and RStudioDesktopSuperDevMode.gwt.xml to allow the web & desktop apps to automatically detect the user's locale based on OS or browser settings.
cc …
> feat(i18n): update gwt.xml files

- src/cpp/rstudio-tests.in
fixes https://github.com/rstudio/rstudio/issues/10456
Skip the *DropPrivs tests in CI when we are running on MacOS
N/A
> Fix MacOS CI builds

- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.ui.xml
> fix duplicated locater id

- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
Addresses #10089
Check if `base::load` is masked. If yes, call `base::load` in console. If not masked, call `load` in console
> Check if load from base is masked before calling load workspace

- src/gwt/src/org/rstudio/studio/RStudioDesktop.gwt.xml
Speculative fix for https://github.com/rstudio/rstudio-pro/issues/3248.
> ensure desktop contains server sources

- src/cpp/session/modules/SessionConsole.cpp
Use `RSTUDIO_CLI_HYPERLIKNS` environment variable instead of `R_CLI_HYPERLINKS`
> use RSTUDIO_CLI_HYPERLIKNS env var

- src/node/desktop/src/assets/locales/en.json
- src/node/desktop/src/ui/connect/connect.ts
- src/node/desktop/src/ui/error/error.ts
- src/node/desktop/src/ui/loading/loading.ts
- src/node/desktop/src/ui/widgets/choose-r/load.ts
Fix some strings not showing up on the Electron Error HTML pages
Added variables to EN.json
None
None
Addresses #10554
> Fix rSessionFailedToStart i18n Translation

- src/cpp/r/R/Api.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
adresses #10521, follow up to #10411
> `.rs.api.documentOpen()` scrolls into view

- src/node/desktop/src/main/i18n-manager.ts
Disable debug logs when running the Electron App
Removed debug flag for i18next
None
None
Addresses #10553
> Removed Debug flag for i18next

- src/node/desktop/src/ui/connect/connect.ts
- src/node/desktop/src/ui/error/error.ts
- src/node/desktop/src/ui/loading/loading.ts
- src/node/desktop/src/ui/widgets/choose-r/load.ts
Fix an issue that would make some text not to be translated on extra HTML pages on electron.
Fixed an issue that was happening due to a search only for divs instead of a full search.
None
None
Addresses #10497
> Fixed issue that would make elements not get translated correctly on some pages

- dependencies/common/install-node
- dependencies/common/install-npm-dependencies
- dependencies/common/install-yarn
- dependencies/common/install-yarn-linux-aarch64
- src/cpp/session/SessionPandoc.cpp
- src/cpp/session/modules/panmirror/SessionPanmirror.cpp
- src/cpp/session/modules/panmirror/SessionPanmirror.hpp
- src/cpp/session/modules/panmirror/SessionPanmirrorBibliography.cpp
- src/cpp/session/modules/panmirror/SessionPanmirrorBibliography.hpp
- src/cpp/session/modules/panmirror/SessionPanmirrorCrossref.cpp
- src/cpp/session/modules/panmirror/SessionPanmirrorCrossref.hpp
- src/cpp/session/modules/panmirror/SessionPanmirrorDOI.cpp
- src/cpp/session/modules/panmirror/SessionPanmirrorDOI.hpp
- src/cpp/session/modules/panmirror/SessionPanmirrorDataCite.cpp
- src/cpp/session/modules/panmirror/SessionPanmirrorDataCite.hpp
- src/cpp/session/modules/panmirror/SessionPanmirrorPandoc.cpp
- src/cpp/session/modules/panmirror/SessionPanmirrorPandoc.hpp
- src/cpp/session/modules/panmirror/SessionPanmirrorPubMed.cpp
- src/cpp/session/modules/panmirror/SessionPanmirrorPubMed.hpp
- src/cpp/session/modules/panmirror/SessionPanmirrorUtils.cpp
- src/cpp/session/modules/panmirror/SessionPanmirrorUtils.hpp
- src/cpp/session/modules/zotero/SessionZotero.cpp
- src/cpp/session/modules/zotero/ZoteroBetterBibTeX.cpp
- src/cpp/session/modules/zotero/ZoteroCSL.cpp
- src/cpp/session/modules/zotero/ZoteroCollections.cpp
- src/cpp/session/modules/zotero/ZoteroCollectionsLocal.cpp
- src/cpp/session/modules/zotero/ZoteroCollectionsWeb.cpp
- src/cpp/session/modules/zotero/ZoteroUtil.cpp
Noticed some source files with out-of-date copyright headers.
Fixed them.
None
None, just tweaks to source file comments.
> fix source file copyright years

- src/node/desktop/.vscode/settings.json
Setting Relative Imports as Default on VSCode
Added VSCode Settings JSON to Electron Project for using relative imports as default
None
None
> Setting Relative Imports as Default on VSCode

- Jenkinsfile
- docker/jenkins/Dockerfile.rhel8-x86_64
Produce Electron builds for RHEL8. #10378 
Add to Jenkinsfile, add python3 dependency to dockerfile.
Build pipeline is the automated test.
Test we can download and install builds.
> Enable electron build for RHEL8

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update to latest stable Electron release:
https://www.electronjs.org/releases/stable#17.1.0
> update electron 17.1.0

- dependencies/common/install-soci
Missed a piece in the previous PR #10673
> add missing upgrade piece

- dependencies/linux/README
- dependencies/windows/install-boost.cmd
neither of these should matter for the build
Continuation of #10673
> Catching some more upgrade versions

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Latest Electron: https://www.electronjs.org/releases/stable#17.1.1
> upgrade Electron to 17.1.1

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Minor electron upgrade: https://www.electronjs.org/releases/stable?version=17#17.1.2
> upgrade to Electron 17.1.2

- src/cpp/session/modules/SessionFind.cpp
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialogBinderImplGenMessages_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialogBinderImplGenMessages_fr.properties
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/model/FindInFilesServerOperations.java
addresses follow up from #10529
Update text to `Files matched by .gitignore`
> Always use `git grep` when possible

- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionDiagnostics.R
Addresses [pro#3310](https://github.com/rstudio/rstudio-pro/issues/3310) -- only scan quarto docs for R package dependencies if any R code chunks are found, and if so, always add rmarkdown to the list of required packages so users can get the package install prompt. Follow up to #10767.
We have an extractRcode function, but it was a little broken. We use this to extract any R code chunks from a document (specifically Rmd and qmd, for .R files we extract the entire file) and since we're already checking the file contents for mentions of any packages we need to be installed, we add rmarkdown to the list -- but only if the R content is non empty.
That way users get the package install prompt if they have at least 1 R chunk, but if they have no code chunks, or only python chunks, we won't …
> Require rmarkdown for rmd and qmd if any R code chunks are found

- src/cpp/core/http/SocketProxy.cpp
- src/cpp/core/include/core/http/SocketProxy.hpp
- src/cpp/server/ServerSessionProxy.cpp
- src/cpp/server/auth/ServerAuthHandler.cpp
- src/cpp/server/include/server/ServerSessionProxy.hpp
- src/cpp/server/include/server/auth/ServerAuthHandler.hpp
companion to: https://github.com/rstudio/rstudio-pro/pull/3341
> OS changes to close shiny and vscode sockets after signout

- src/cpp/session/modules/build/SessionBuild.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/commands/CmdConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/CmdConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/commands/CmdConstants_fr.properties
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml.MD5
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildCommands.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildTab.java
adresses #10564.  
Removing the "Clean and Rebuild" button, but adding "Clean All" i.e. going from: 
to: 
> Update build pane for Makefile projects

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputFrame.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
See: https://github.com/rstudio/rstudio/issues/10836
And PR: https://github.com/rstudio/rstudio/pull/10852
**See the original PR for more details on the fix.**
Backport the fix in https://github.com/rstudio/rstudio/pull/10852 for https://github.com/rstudio/rstudio/issues/10836 to the PT branch.
Apply the changes from that PR to the head of the PT branch.
N / A
N / A
> Move where events are added on chunks to maintain scrolling fix on pages

- NEWS.md
News update for pro side adressing rstudio/rstudio-pro#3150
> News update for 3150

- src/node/desktop/src/main/app-state.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/test/unit/core/file-path.test.ts
Remove some unused code, and fix a broken Electron unit test.
Select unused code and delete it.
Delete the test that was verifying that a function was NYI, now that the function is I.
Fixes a test
Code cleanup, nothing to test.
> remove unused code and fix a unit test

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Upgrade from Electron 18.0.1 to 18.0.3.
https://releases.electronjs.org/release/v18.0.2
https://releases.electronjs.org/release/v18.0.3
Bump version, reinstall dependencies, build, test.
None
None
> upgrade to Electron 18.0.3

- src/cpp/session/modules/SessionRParser.cpp
https://github.com/rstudio/rstudio/issues/10757
> ignore '_' in diagnostics engine

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update to latest Electron.
https://releases.electronjs.org/release/v18.0.4
> update Electron to 18.0.4

- src/node/desktop/src/main/gwt-window.ts
Addresses https://github.com/rstudio/rstudio/issues/11016.
Clear history on navigate.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/11016.
> clear history on navigate

- src/cpp/session/SessionModuleContext.cpp
Addresses https://github.com/rstudio/rstudio/issues/10162. See inline comments for details.
> stop warning in findProgramOnPath

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Keep us on the latest stable release during development.
Updated to latest 18.x release. https://releases.electronjs.org/release/v18.1.0
Nothing specifically for this.
Nothing specific to test, just general usage.
> upgrade to Electron 18.1.0

- CMakeCompiler.txt
- dependencies/common/install-boost
- dependencies/common/install-qt.sh
- dependencies/linux/install-dependencies-jammy
- docker/jenkins/Dockerfile.jammy-amd64
- package/linux/CMakeLists.txt
- package/linux/install-dependencies
- src/cpp/desktop/DesktopMain.cpp
- src/cpp/tests/cpp/tests/vendor/catch.hpp
- version/news/NEWS-2022.02.3-prairie-trillium.md
Open source merge for https://github.com/rstudio/rstudio-pro/pull/3419.
> open-source merge for pro PR 3419

- Jenkinsfile
Open-source part of https://github.com/rstudio/rstudio-pro/pull/3423
> open-source merge for pro 3423 (build PT on Ubuntu Jammy)

- docker/jenkins/Dockerfile.fedora36-x86_64
Open-source merge for https://github.com/rstudio/rstudio-pro/pull/3439.
> Dockerfile for fedora 36 builds

- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
updated from the json this time.
> update uiLanguageTitle property to include a colon

- src/cpp/core/include/core/system/Win32RuntimeLibrary.hpp
- src/cpp/core/system/Win32RuntimeLibrary.cpp
- src/cpp/session/SessionMain.cpp
- version/news/NEWS-2022.02.3-prairie-trillium.md
Backport of https://github.com/rstudio/rstudio/pull/11207.
> use ucrtbase.dll with R 4.2.0 or newer (#11207)

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeMarkdownWriter.java
adresses #10078
Add an artificial "a" before going through `pandocAutoIdentifier()` and then remove it. 
> add "ref_" prefix for auto references

- src/node/desktop/src/main/main-window.ts
Open source merge for https://github.com/rstudio/rstudio-pro/pull/3470
> fix desktop title to use overlay function

- Jenkinsfile
Attempt to retry the whole windows build if something goes wrong. Tagging @jspiewak in case he has strong objections to this change.
Move the retry
Build system change.
N/A build system change
> Attempt to retry the whole windows build

- src/cpp/session/modules/SessionRSConnect.R
- src/cpp/session/modules/quarto/SessionQuarto.cpp
- src/cpp/tests/testthat/test-rsconnect.R
addresses #10995 
If a `_quarto.yml` file is found in the same directory as the `.qmd` file, then add it: 
```r
if (file.exists(file.path(dirname(quartoSrcFile), "_quarto.yml"))) {
file_list <- c(file_list, "_quarto.yml")
}
```
added this: 
```r
test_that(".rs.rsconnectDeployList() includes _quarto.yml file (#10995 )", {
dir.create(tf <- tempfile()); on.exit(unlink(tf, TRUE, TRUE))
target <- file.path(tf, "test.qmd")
writeLines("---\ntitle: quarto document\n---\n", target)
writeLines('project:\n  title: "test"\n', file.path(tf, "_quarto.yml"))
res <- .rs.rsconnectDeployList(target, FALSE, target)[[1L]]
expect_true("_quarto.yml" %in% res)
})
```
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be …
> include _quarto.yml if available

- src/cpp/session/modules/quarto/SessionQuartoPreview.cpp
adress #11096 
Also call `showInViewer()` when `QuartoPreview` is already running and needs a refresh. 
> quarto preview open in window

- src/cpp/tests/testthat/test-rsconnect.R
Reverts rstudio/rstudio#11292
Wrong approach
> Revert "If Quarto has been disabled, then disable the quarto test"

- src/cpp/session/modules/SessionCodeTools.R
Addresses https://github.com/rstudio/rstudio/issues/11303.
Check only the first element.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/11303.
> check only first element after calling as.character

- NEWS.md
- src/cpp/server/ServerMain.cpp
- src/cpp/session/include/session/projects/SessionProjects.hpp
- src/cpp/session/projects/SessionProjects.cpp
Reviewed in:
https://github.com/rstudio/rstudio-pro/pull/3479
> Companion for single-session project sharing 

- src/gwt/tools/locdiff/.eslintrc.cjs
- src/gwt/tools/locdiff/.gitignore
- src/gwt/tools/locdiff/README.md
- src/gwt/tools/locdiff/locdiff.js
- src/gwt/tools/locdiff/package-lock.json
- src/gwt/tools/locdiff/package.json
Addresses #10595 - generate a report showing UI strings that have been added or changed
Wrote a node.js command-line tool, `locdiff`, that uses two cloned rstudio repos (`old` and `new`) and generates a CSV showing all added/modified strings in the English GWT property files.
See the README.md file for usage instructions.
N/A
N/A
> localization diff tool

- src/cpp/session/modules/SessionConsole.R
- src/cpp/session/modules/SessionConsole.cpp
addresses #11271 
Support these (in addition to the same with `rstudio:` prefix: 
> ide agnostic links

- src/node/desktop/src/assets/locales/fr.json
Localize desktop specific strings for the Electron TypeScript code.
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual …
> i18n: desktop locales

- src/cpp/core/include/core/r_util/RActiveSessions.hpp
- src/cpp/session/SessionHttpMethods.cpp
The OS companion to:
https://github.com/rstudio/rstudio-pro/pull/3497
> Add destroy pending activity state and set to shutting_down on quit

- src/cpp/core/include/core/r_util/RActiveSessions.hpp
- src/cpp/session/SessionMain.cpp
https://github.com/rstudio/rstudio-pro/pull/3543
> Companion commit for slow session starting PR

- src/cpp/session/modules/SessionHelp.R
- src/gwt/src/org/rstudio/core/client/hyperlink/FileHyperlink.java
- src/gwt/src/org/rstudio/core/client/hyperlink/HelpHyperlink.java
- src/gwt/src/org/rstudio/core/client/hyperlink/HelpHyperlinkPopupHeader.java
- src/gwt/src/org/rstudio/core/client/hyperlink/HelpPreview.java
- src/gwt/src/org/rstudio/core/client/hyperlink/Hyperlink.java
- src/gwt/src/org/rstudio/core/client/hyperlink/HyperlinkConstants.java
- src/gwt/src/org/rstudio/core/client/hyperlink/HyperlinkConstants_en.properties
- src/gwt/src/org/rstudio/core/client/hyperlink/HyperlinkConstants_fr.properties
- src/gwt/src/org/rstudio/core/client/hyperlink/HyperlinkPopupHeader.java
- src/gwt/src/org/rstudio/core/client/hyperlink/HyperlinkResources.java
- src/gwt/src/org/rstudio/core/client/hyperlink/RunHyperlink.java
- src/gwt/src/org/rstudio/core/client/hyperlink/RunHyperlinkPopupHeader.java
- src/gwt/src/org/rstudio/core/client/hyperlink/UnsupportedHyperlink.java
- src/gwt/src/org/rstudio/core/client/hyperlink/VignetteHyperlink.java
- src/gwt/src/org/rstudio/core/client/hyperlink/WarningLabel.java
- src/gwt/src/org/rstudio/core/client/hyperlink/hyperlinkStyles.css
- src/gwt/src/org/rstudio/core/client/widget/ThemedPopupPanel.css
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/model/HelpServerOperations.java
Follow up for #11273 
inspired from @GCRev changes in https://github.com/rstudio/rstudio/issues/11273#issuecomment-1151664672
https://user-images.githubusercontent.com/2625526/173048572-d6fd42ca-a8e1-4044-9ffe-2c678d5556a6.mov
https://user-images.githubusercontent.com/2625526/173048733-71e51785-f2a4-4751-9998-49f0d49edee5.mov
> ui tweaks for hyperlinks

- src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsList.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsListJobsListUiBinderImplGenMessages_en.properties
Companion to [Pro#3553](https://github.com/rstudio/rstudio-pro/pull/3553)
> No jobs currently running -> No background jobs currently running

- src/cpp/session/modules/SessionPackages.R
- src/gwt/src/org/rstudio/core/client/hyperlink/RunHyperlink.java
Final follow up (hopefully) for #11273
Forbid packages base, stats, utils. 
```r
cli::style_hyperlink("show traceback ...", "ide:run:rm(list = ls())")
cli::style_hyperlink("show traceback ...", "ide:run:base::rm(list = ls())")
cli::style_hyperlink("show traceback ...", "ide:run:base::source('http://example.org/code.R')")
cli::style_hyperlink("show traceback ...", "ide:run:base::system('rm -fr /')")
cli::style_hyperlink("show traceback ...", "ide:run:rlang::last_error(); rm(list = ls())")
cli::style_hyperlink("show traceback ...", "ide:run:rlang::last_error(a = rm(list = ls()))")
cli::style_hyperlink("unsupported", "ide:foo")
```
> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change …
> forbid base, utils, stats in `ide:run` links

- src/node/desktop/src/main/gwt-callback.ts
Fixed issue that was breaking clipboard on Electron for Linux
Fixed an old change.
None
Refer to #11111
Addresses #11111
> Fixed issue that was breaking clipboard on Electron for Linux

- src/cpp/server/auth/ServerAuthHandler.cpp
This issue was found by @astayleraz in testing the session metadata feature. Prior to SW, we were never setting the posix user ID in the database. I added a feature that updates the UID if it's missing on first log in, but that didn't account for users who had valid auth sessions at the time of upgrade. Together with the Session Metadata DB feature, which relies on valid `user_id`s in the database, this would prevent sessions from starting.
This applies to both OS server and Workbench.
Check for the user in the database when doing a lookup user. This implementation may be a bit on the performance heavy side, so we may want to re-evaluate at a future date if a better solution is not possible now.
Our automated tests don't cover upgrade, AFAIK. 
This occurs on upgrade:
1. On a PT or older …
> Fix a bug with upgrading to SW and using DB session storage

- version/news/NEWS-2022.07.0-spotted-wakerobin.md
Adding missing NEWS references that Ron noticed. Mind just double checking I'm referencing the correct issue? 
- test_that : Romain
- glibc: Kevin
> Add missing issue references

- src/gwt/acesupport/acemode/r_code_model.js
adresses #11375
Recognize also `\` as an alias to `function`. 
> code outline includes lambda form

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Minor bug-fix update:
https://releases.electronjs.org/release/v19.0.6
> update to Electron 19.0.6

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Bumped up to latest version of TypeScript (and a couple other minor dev-only components). Comfirmed things build and run, and tests still pass.
> Use latest TypeScript for Electron project

- src/node/desktop/src/main/gwt-callback.ts
Address #11406 
Calls focus on main window
None
Some examples of when this is called:
* New project dialog
* Opening options
* Opening find in files dialog
> Implement desktop_bring_main_frame_to_front

- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
addresses #11503
based on keywords from the grammar: https://github.dev/r-devel/r-svn/blob/8df1c44dcfd3883e3dd5c6a1208de5274145c884/src/main/gram.y#L2116-L2140
> quote keywords on completion

- src/node/desktop/src/main/gwt-callback.ts
Addresses #11340 
same as #11557
> open pptx files rendered by rstudio

- src/cpp/core/system/PosixChildProcess.cpp
- src/cpp/core/system/PosixSched.cpp
- src/cpp/core/system/PosixSystem.cpp
- src/cpp/shared_core/system/PosixSystem.cpp
This is a resubmission of #11569 (now reverted due to breaking macOS builds) but with fixes from #11573.
> Gate various Linux-specific system calls with `__linux__` (v2)

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Updating Electron to latest release
Updating package.json and lock to 19.0.9
None
Unit tests pass and IDE starts successfully
> Update Electron to 19.0.9

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update to latest release
Unit tests passed and RStudio starts successfully
N/A
N/A
> Update Electron to 19.0.10

- src/gwt/src/org/rstudio/core/client/dom/ElementEx.java
- src/gwt/src/org/rstudio/studio/client/workbench/exportplot/clipboard/CopyPlotToClipboardDesktopDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/export/PlotsPanePreviewer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/export/DesktopExport.java
> Revert "avoid getClientLeft() / getClientTop()"

- src/cpp/session/SessionHttpMethods.cpp
- src/cpp/session/SessionHttpMethods.hpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/SessionOfflineService.cpp
- src/cpp/session/http/SessionHttpConnectionListenerImpl.hpp
- src/cpp/session/http/SessionPosixHttpConnectionListener.cpp
Reviewed in 
https://github.com/rstudio/rstudio-pro/pull/3676
> Companion to pro commit for verify request signature changes

- .github/ISSUE_TEMPLATE/backport-an-issue.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
Request from @ronblum to help track which new/incoming issues haven't yet been reviewed
Discussion here: https://rstudio.slack.com/archives/C7HT9GDB9/p1659971482870689
> Add automatic `new` tag to issues

- NEWS.md
- src/gwt/src/org/rstudio/core/client/RegexUtil.java
> Update for alphanumerics following underscore

- src/cpp/session/modules/SessionHelp.R
- src/cpp/session/modules/SessionHelp.cpp
- src/gwt/src/org/rstudio/core/client/hyperlink/Hyperlink.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
addresses #11664, #11588
Use a `Timer`
- when merely flying over a link, no popup is shown
- it only gets shown when the mouse stays there at least 400ms
- the popup disappear on mouse out
https://user-images.githubusercontent.com/2625526/183936192-ef68136a-f9ac-49f5-b4cc-a14255af7fed.mov
Same in the help page: 
https://user-images.githubusercontent.com/2625526/183936803-0af361a5-fa69-4830-be67-6647b7701496.mov
> hyperlink tweaks

- src/gwt/src/org/rstudio/core/client/RegexUtil.java
> fix underscore autocompletion

- src/node/desktop/src/core/user.ts
Followup to fix #11635 
Electron needs to resolve home path alias consistently with the backend.
See implementation in:    https://github.com/rstudio/rstudio/blob/d01feac78480189424d22c029dc97100701463f7/src/cpp/session/SessionOptions.cpp#L223
https://github.com/rstudio/rstudio/blob/8f85b6b8ed4e7db1ac167b2007d17e26c947e4fd/src/cpp/shared_core/system/User.cpp#L159-L176
> copy c++ implementation to resolve user home path using env vars

- src/node/desktop/src/main/detect-r.ts
Addresses #11672 in line with Qt approach to Windows registry keys
> add HKEY_CURRENT_USER in findRInstallations Electron

- src/cpp/core/Database.cpp
- src/cpp/core/include/core/Database.hpp
- src/cpp/server/auth/ServerAuthHandler.cpp
- src/cpp/server/include/server/ServerOptions.gen.hpp
- src/cpp/server/server-options.json
Reviewed in: 
https://github.com/rstudio/rstudio-pro/pull/3714
> Companion to database connection bugfixes pro PR #3714

- src/cpp/session/modules/SessionFind.cpp
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/model/FindInFilesServerOperations.java
> Handle special regex characters as escaped literals in Whole word mode

- NEWS.md
- version/news/NEWS-2022.07.2-spotted-wakerobin.md
> Update sw news

- src/cpp/session/modules/SessionFiles.R
- src/gwt/src/org/rstudio/core/client/hyperlink/FileHyperlink.java
- src/gwt/src/org/rstudio/core/client/hyperlink/Hyperlink.java
- src/gwt/src/org/rstudio/core/client/hyperlink/HyperlinkConstants.java
- src/gwt/src/org/rstudio/core/client/hyperlink/HyperlinkConstants_en.properties
- src/gwt/src/org/rstudio/core/client/hyperlink/HyperlinkConstants_fr.properties
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/SourceServerOperations.java
addresses #11697 
+ RPC method `fileExists`
+ `FileHyperlink.onClick()` only tries to open the file if it exist. Otherwise you get this; 
> Handle links to non existing files

- NEWS.md
- src/cpp/core/include/core/r_util/RTokenCursor.hpp
- src/cpp/session/modules/SessionDiagnosticsTests.cpp
- src/cpp/session/modules/SessionRParser.cpp
Addresses https://github.com/rstudio/rstudio/issues/11780.
Adds code in the diagnostic engine to handle namespace-qualified calls when walking pipelines.
Automated tests included.
Test via notes in https://github.com/rstudio/rstudio/issues/11780.
> improve pipeline diagnostics with namespace-qualified calls

- src/cpp/session/modules/SessionPackages.R
> get the first url only

- src/cpp/core/Database.cpp
Companion commit - reviewed in: https://github.com/rstudio/rstudio-pro/pull/3764
> Fix for database "not connected" error being treated as 'Success'

- docs/user/rstudio-pro/getting-started/overview.qmd
Set up the directory structure for the user guide @jthomasmock  is working on.
The user guide will be pulled into the Workbench User Guide upstream so this directory structure must match the rstudio-pro repo. Placeholder content is included because git doesn't like empty directories.  
N/A
N/A
> Add user guide doc structure

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorBackgroundLinkHighlighter.java
Follow up to #11553 
Allow the issue syntax shortcut to be highlighted in .md files so that they work on e.g. `NEWS.md` files. 
For example here in `dplyr` : 
> allow the (#123) syntax in md files, so that it works e.g. on NEWS.md

- NEWS.md
- src/cpp/session/SessionMain.cpp
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/ConsolePreferencesPane.java
Addresses https://github.com/rstudio/rstudio/issues/10391.
Straightforward addition of preference.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/10391.
> add 'discard pending console input' preference

- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
addresses #11881
Add the extension to always_shown_extensions property
> add .quartoignore to always_shown_extensions

- docker/jenkins/notarize-release.sh
Add logging result in ghost-orchid branch when notarization fails (change already exists in PT onward)
N/A
N/A
> Improve Logging of MacOS Notarization Failures

- src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceDiffGutter.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceDiffGutter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/ace-uncompressed.js
> [poc] show git diff information on the gutter

- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/ViewVcsConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/ViewVcsConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/ViewVcsConstants_fr.properties
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java
Addresses #11590
for now, hide text for the commit and diff buttons
> Manage toolbar space usage in the git pane

- src/gwt/acesupport/acemode/r_code_model.js
addresses #11997 
improve `this.getVariablesInScope()` so that it handles function calls too. 
> fix `this.getVariablesInScope()` in R code model

- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java
addresses #11590 again
Take into account the text of the branch switcher in the manage size strategy. Make sure the sizes are managed when the branch changes.  
> git pane size management taking the branch name into account

- src/gwt/src/org/rstudio/core/client/hyperlink/HelpHyperlink.java
addresses #11983 
regex tweak
```r
cli::cli_text("Clicking on {.topic [as table](base::as.table)} will not help.")
cli::style_hyperlink("help page", "ide:help:tidyselect::faq-selection-context")
```
should create links that are clickable:
> packages may contain `.`, topics may contain `.` and `-`

- package/win32/make-package.bat
Addresses https://github.com/rstudio/rstudio/issues/12003.
Adds a new flag, `multiarch`, to the `make-package.bat` script, which controls whether we build both 32-bit and 64-bit `rsession.exe` executables. On Jenkins, we still produce multiarch builds by default.
N/A
N/A
> use package single-arch builds by default on Windows

- src/cpp/session/modules/SessionPythonEnvironments.R
addresses #11725
What @kevinushey said on #11725
> python -Xutf8

- src/cpp/core/r_util/RVersionsPosix.cpp
The findClosest process will return the next higher patch version, even if an exact match exists. So if you have 4.0.1, 4.0.2, and 4.0.3 and are looking for 4.0.1, it will return 4.0.2 instead. The project stores just the version number, not the home dir so we don't get an exact match earlier on.
Might address: https://github.com/rstudio/rstudio-pro/issues/3822
This addresses a basic logic error in the selectVersion function, used to find a matching R version. It will only change the code path when the homeDir does not match. This case is used when restoring the R version from a project where we only have the version number, not the home dir. 
I think existing automation should test this pretty thoroughly. 
It would be good to have the cloud team see if this fixes their issue.
> Do an exact version match before resorting to findClosest

- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
> allow users to control 'text-rendering' preference

- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/BranchToolbarButton.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/events/BranchCaptionChangedEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java
addresses #12035 
+ new event `BranchCaptionChangedEvent` that is emitted by `BranchToolbarButton` and have `GitPane` call `manageToolbarSizes()`
> git pane resize when branch caption is changed

- src/gwt/src/org/rstudio/core/client/WordWrap.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
addresses (part of) #8378 
no word wrap when entering markdown in comments
> no word wrap markdown in comments

- src/cpp/core/system/PosixChildProcess.cpp
Addresses the same concern as https://github.com/rstudio/rstudio/issues/11736 for POSIX.
Read stdout / stderr after seeing the process has exited, just in case any output was produced in the interval between us checking for the process exit, and the last time we polled for stdout / stderr.
N/A
N/A
> read stdout, stderr on process exit for posix

- src/cpp/server/auth/ServerAuthHandler.cpp
Addresses: https://github.com/rstudio/rstudio-pro/issues/3874
One liner change of || to an && 
Let's add a test for reactivating users. We can do it by updating the postgres db directly to set last_sign_in time to an old date, then just try to login that user.
> Fixed test in code for reactivating users

- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishDocServicePage.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
Follow-up to https://github.com/rstudio/rstudio-pro/issues/3605
Add support for presentations
> Add presentation support

- src/cpp/session/modules/SessionHelp.R
- src/cpp/session/modules/SessionHelp.cpp
addresses #12104, #11336
Reworked `.rs.Rd2HTML()` based on `pkgload:::topic_write_html()` / `pkgload:::load_rd_macros()`
> `.rs.Rd2HTML()` loads Rd macros, with `tools::loadPkgRdMacros()`

- src/cpp/session/SessionClientInit.cpp
Fix RS_SERVER_URL environment variable having two copies of `/s/{session-id}` in the URL path.
https://github.com/rstudio/rstudio-pro/issues/3595#issuecomment-1275058183
I'm totally not sure if this is a good way to go about this, but I found `r_util::parseSessionUrl` which breaks the base URL apart into the pieces we need.
I don't have one
The Shiny for Python "Run App" button needs to be tested on both RS and RSW.
> Fix RS_SERVER_URL having double session paths

- src/node/desktop/src/main/gwt-callback.ts
Addresses #11912 (save dialog) and #11088 (open dialog)
use normalizeSeparatorsNative to get platform specific path separators
> fix initial save/open directory for windows

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update Electron
Update `package.json`
Run unit tests
@jonvanausdeln I checked Chromium and the version has not changed (`102.0.5005.167`)
> Update Electron to 19.1.3

- src/cpp/session/SessionAsyncRProcess.cpp
- src/cpp/session/include/session/SessionAsyncRProcess.hpp
- src/cpp/session/modules/SessionDependencies.cpp
Addresses https://github.com/rstudio/rstudio/issues/10945.
@Enchufa2, let me know if this looks okay to you.
> allow use of site profile in install dependencies

- src/gwt/src/org/rstudio/core/client/files/FileSystemItem.java
- src/gwt/src/org/rstudio/studio/client/projects/Projects.java
Follow-up/code-cleanup on #11824
Respond to code review
> fix up redundancies in file system item code changes for windows

- NEWS.md
Add to NEWS for Workbench changes related to code-server and the extension
Open file, press various keys on my fancy electronic typewriter.
N/A
N/A
> NEWS updates (code-server and vs code extension installation changes)

- src/cpp/session/resources/grid/dtviewer.js
- src/gwt/src/org/rstudio/core/client/widget/GridViewerFrame.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.ui.xml
addresses #8953
use `max_cols=-1` in the url to mean not setting it, and then just use cols.length
> data import preview showing all the preview columns

- src/cpp/r/R/Tools.R
Addresses https://github.com/r-lib/conflicted/issues/73.
`attach()` will replace active bindings with the function underneath those bindings, which we don't want here. Instead, just remove and restore the bindings in the `.conflicts` environment as appropriate.
N/A; to be tested by those affected in https://github.com/r-lib/conflicted/issues/73.
N/A
> avoid calling 'attach()' when hiding conflicts env

- Jenkinsfile
Issues with sentry uploads have been causing build failures much more consistently and have prevented a successful pro build for over a week. This change lowers the urgency of sentry upload failures so that builds are marked as unstable rather than failing out completely.
Wrap the sentry upload stage in a try-catch and set the build result to unstable on failure.
I replayed a previous build, making [these changes directly in the Jenkinsfile](https://build.rstudioservices.com/job/IDE/job/pro-pipeline/job/main/1084/replay/diff). This resulted in getting the builds past the sentry upload failures (as they are now just marked unstable).
One thing to note - the "upload debug symbols" stage is marked as a "pass" (green checkmark) in the [Blue Ocean …
> Reduce severity of sentry upload failures

- src/cpp/core/include/core/r_util/RSessionContext.hpp
- src/cpp/server/include/server/session/ServerSessionProxy.hpp
- src/cpp/server/session/ServerSessionProxy.cpp
reviewed in PR: https://github.com/rstudio/rstudio-pro/pull/3915/
> Companion to load balancing proxy changes

- src/cpp/core/include/core/r_util/RActiveSessions.hpp
- src/cpp/core/r_util/RActiveSessions.cpp
reviewed in PR: https://github.com/rstudio/rstudio-pro/pull/3992
> Companion to session status fixes for load balancing

- src/cpp/tests/testthat/test-api.R
Bandaid fix to #12275 to prevent unstable builds
Select tests in RStudio -> cmd + shift + c -> add comment linking to issue
> comment out failing tests

- src/cpp/core/include/core/r_util/RSessionContext.hpp
Open source companion commit to https://github.com/rstudio/rstudio-pro/pull/3942
> open source companion commit to rstudio/rstudio-pro#3942

- src/cpp/session/modules/SessionRCompletions.R
addresses #11749
just have them added sooner to `completions` in `.rs.rpc.get_completions`
```r
library(dplyr)
tab <- tibble(shotsOnTarget = 1)
tab %>% select(sho
```
> chain completions before search path completions

- src/gwt/acesupport/acemode/r_code_model.js
addresses #12289
Adapt `getVariablesInScope()` in the r code model. 
only getting `a` and `b` is correct in these cases:
> adapt `getVariablesInScope()` to take into account [

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
Addresses https://github.com/rstudio/rstudio/issues/12021. 
An earlier attempt to fix this bug, https://github.com/rstudio/rstudio/pull/12037, worked on the assumption that the visual editor's outline was always ordered by position, and took advantage of this ordering to discard duplicates efficiently.
Unfortunately, this assumption turned out to be false; in the presence of several consecutive indented chunks, the positions are not consecutive. 
Discard duplicates using a `TreeMap`. This results in a sorted set of outline items without incurring an O(n^2) cost for checking for duplicates.
N/A, this visual editor code doesn't have automation yet.
There are several example repros to try in the source bug; give those a shot to ensure that we didn't re-break the old issues while fixing the …
> Fix incorrect code capture in visual editor when indented chunks are present

- src/cpp/session/modules/SessionRCompletions.R
addresses #10538
Check that `names()` returns a character vector, bail otherwise. 
> chain completion handling `names()` method not returning a character vector

- src/cpp/session/modules/rmarkdown/NotebookQueue.cpp
> Check for nullptr before getting engine

- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
Follow-ups to QA feedback in https://github.com/rstudio/rstudio-pro/issues/3605#issuecomment-1313880675
> Fix connect account flow when connecting while publishing

- src/cpp/session/modules/SessionHelp.R
- src/cpp/tests/testthat/test-help.R
Minor changes to `.rs.getHelp()` to make `.rs.getHelp("<pkg>::<fun>")` work again
> `.rs.getHelp("<pkg>::<fun>")`

- version/news/NEWS-2022.12.0-elsbeth-geranium.md
Add missing news entries.
Add the entries
NEWS.md change only
NEWS.md change only
> Add missing news entries

- src/gwt/ant
> Revert changes to ant script

- src/cpp/session/modules/clang/RCompilationDatabase.cpp
Addresses https://github.com/rstudio/rstudio/issues/12382
> use discover systemincludepaths on windows instead of hardcoded

- Jenkinsfile.pull-request
- utils.groovy
Addresses rstudio/rstudio-pro#4120. Adds a new Jenkinsfile that will run on pull requests.
The pipeline is set up to run on a single architecture, Jammy amd64, compile a server build, and run all GWT and C++ unit test.
This pipeline will run on all pull requests in `rstudio`, but will only run a build and test if the PR has changes in:
- `src`
- `package/inux`
- `docker/jenkins`
- `cmake`
The configuration for the pipeline in Jenkins can be found [here](https://build.posit.it/job/IDE/job/open-source-pull-request/configure).
N/A
N/A
> Add pull-request Jenkinsfile

- NEWS.md
Provide a section in NEWS for listing accessibility improvements. This is very important as we need to demonstrate ongoing progress towards our goal of making our products WCAG 2.1 AA compliant.
Added a header.
N/A
N/A
Yes, yes it is.
> add "Accessibiilty Improvements" section to NEWS file

- NEWS.md
Update NEWS.md to include accessibility changes to homepage.
Companion OS-PR to https://github.com/rstudio/rstudio-pro/pull/4211
> Companion OS-PR to https://github.com/rstudio/rstudio-pro/pull/4211

- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
Addresses https://github.com/rstudio/rstudio-pro/issues/4216
> Enable Posit.cloud publishing by default

- NEWS.md
... that I forgot to add when merging the related pull requests 😬
> added some cherry blossom NEWS items

- src/node/desktop/src/ui/utils.ts
Minor source file commenting and style tweaks.
Add our standard comment block header to a source file and fixed TypeScript style warnings (single quotes around strings, a method that should have been marked as `async`.)
None
N/A
> add comment block and fix typescript warnings

- package/linux/CMakeLists.txt
Updates the Linux package description to match the user guide description per #12315. Note that this doesn't use the suggested message from the issue, but uses the latest user guide text.
```
Description: RStudio
RStudio is a set of integrated tools designed to help you be more productive with R. It includes a console, syntax-highlighting editor that supports direct code execution, as well as tools for plotting, history, and workspace management.
```
```
Description: RStudio
RStudio is an integrated development environment (IDE) designed to support multiple languages, including both R and Python. It includes a console, syntax-highlighting editor that supports direct code execution, and a variety of robust tools for plotting, viewing history, debugging and managing your workspace.
```
The …
> match linux package description to user guide

- NEWS.md
- src/cpp/session/resources/help_resources/index.htm
Noticed during accessibility auditing that the Help pane's home page uses a multi-column layout even when the help pane is narrow (or you zoom the UI font large enough). In either case, an accessibility issue.
Targeting Cherry Blossom just because this is a simple, safe fix.
#12643
When the pane is made narrow, the columns go away.
Did this by ripping out the table-based layout and using a simple responsive CSS layout.
Also ran the page through W3C HTML verification (it had numerous warnings) and now it verifies cleanly.
Wrapped page in a `main` element; another minor accessibility tweak.
Normal view:
Narrow view (before this fix):
Narrow view (after the fix):
None
This is a static HTML file bundled with the app (both for desktop and server/workbench) so very low risk.
I'm not using any …
> improve help pane display at narrow pane widths

- src/cpp/core/include/core/system/PosixGroup.hpp
- src/cpp/core/system/PosixGroup.cpp
Open Source Companion to rstudio/rstudio-pro#4255
> OS Companion to Pro 4255

- src/cpp/core/include/core/http/TcpIpAsyncConnector.hpp
Reviewed in https://github.com/rstudio/rstudio-pro/pull/4294
> Show address and port in onConnectTimeout messages

- src/cpp/shared_core/system/PosixSystem.cpp
need to make sure getpwuid is not called in 'onAfterFork' callback to avoid potential interaction with active directory libraries that override that call and use locking.
> Companion to https://github.com/rstudio/rstudio-pro/pull/4291

- docker/jenkins/publish-build.ps1
Bring over the windows portion of https://github.com/rstudio/rstudio/pull/12561 to fix current build pain
See original : https://github.com/rstudio/rstudio/pull/12561
Infra only
No QA
No Documentation
> Windows portion of rebuild fix

- NEWS.md
OS PR of https://github.com/rstudio/rstudio-pro/pull/4329
> OS PR of pro #4329

- src/gwt/tools/locdiff/README.md
One of the instructions in the README was incorrect (wrong command).
Correct the README, also include the git commit hash of the Elsbeth Geranium in the notes.
None, purely dev documentation
Nothing to test, purely dev documentation
Yes it is.
> small edits to locdiff README

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_fr.properties
addresses #12752. 
But I don't really know how to translate "fenced divs" in :fr: cc @cderv maybe you have an idea ?
> :fr: for rainbowParenthesesTitle and rainbowParenthesesDescription

- git_hooks/README.md
- git_hooks/hooks/pre-commit
- git_hooks/hooks/pre-push
- git_hooks/set-up-git-hooks
- src/node/desktop/.eslintignore
- src/node/desktop/.lintstagedrc
- src/node/desktop/.prettierrc
- src/node/desktop/README.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
- src/node/desktop/scripts/create-prettier-ignore-file.sh
This PR fixes the issues preventing `npm run format` from running and adds git hooks to lint/format pre-commit and prevent pushes to the main branch. Developers must install the git hooks by following the instructions in `git_hooks/README.md` ([preview here](https://github.com/rstudio/rstudio/blob/lint-format-git-hooks/git_hooks/README.md) while this PR is up).
- fixed failing `npm run format` by removing code referencing non-existent `.prettierignore` and using `.gitignore` for prettier's ignore path
- added prettier config `src/node/desktop/.prettierrc` based on sample from https://github.com/rstudio/rstudio/wiki/Coding-Standards-(js,-ts)
- added dev dependency `lint-staged` to run `eslint` and `prettier` on staged js/ts files
- added git hooks, hook setup script and documentation
- …
> fix `npm run format` and add git hooks

- src/cpp/r/include/r/session/RSession.hpp
- src/cpp/r/session/graphics/RGraphicsDevDesc.cpp
- src/cpp/r/session/graphics/RGraphicsDevDesc.hpp
- src/cpp/r/session/graphics/RGraphicsDevDescVersions.hpp
- src/cpp/r/session/graphics/RGraphicsUtils.cpp
- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/session-options.json
- version/news/NEWS-2023.03.0-cherry-blossom.md
Address #12751 
Changes made according to https://github.com/rstudio/rstudio-pro/wiki/RStudio-Graphics-Device#preparing-for-an-r-update
none
Rendering a plot will show in the Plots pane. Loading a library that uses the graphics engine like ggplot2 should not show a warning about the graphics engine version.
Updated README
> Support R graphics engine 16

- version/news/NEWS-2023.03.0-cherry-blossom.md
> only use New and Fixed headers

- version/news/NEWS-2023.03.0-cherry-blossom.md
Adds a news entry for rstudio/rstudio-pro#4064.
N/A
N/A
N/A
N/A
> Update news file for Kubernetes Support

- version/news/NEWS-2023.03.0-cherry-blossom.md
Add news entry for rstudio/rstudio-pro#4255
N/A
N/A
N/A
N/A
> Add NEWS Entry for rstudio/rstudio-pro#4255

- NEWS.md
OS-PR for https://github.com/rstudio/rstudio-pro/issues/4333
> OS-PR for rstudio-pro#4396, update NEWS

- version/news/NEWS-2023.03.0-cherry-blossom.md
This change pulls in relevant changes from the Launcher [NEWS.md](https://github.com/rstudio/launcher/blob/main/NEWS.md) file.
News.md for Cherry blossom was updated
> Add Job Launcher changes to Cherry Blossom News

- NEWS.md
- src/gwt/www/rstudio.css
- src/gwt/www/templates/encrypted-sign-in.htm
See https://github.com/rstudio/rstudio-pro/pull/4473
> open source merge for pro#4473

- dependencies/windows/install-dependencies.cmd
- src/node/desktop/envvars.bat
- src/node/desktop/src/main/detect-r.ts
- src/node/desktop/src/ui/widgets/choose-r.ts
- src/node/desktop/src/ui/widgets/choose-r/preload.ts
Attempting to get more information for https://github.com/rstudio/rstudio/issues/12452.
> add more startup diagnostics for R

- src/cpp/session/modules/SessionSource.cpp
Related to https://github.com/rstudio/rstudio/issues/12781.
> include path in error message

- jenkins/Jenkinsfile.linux
Disable bionic tests as per https://github.com/rstudio/rstudio-pro/issues/4467
N/A
N/A
N/A
N/A
> Disable bionic tests

- src/cpp/server_core/ServerDatabase.cpp
Open-Source companion PR for rstudio/rstudio-pro#4447
> Companion commit to rstudio/rstudio-pro#4447

- src/cpp/tests/testthat/test-source-progress.R
sourceWithProgress was renamed to `.rs.sourceWithProgress`. Updating the tests to match
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a …
> rename sourceWithProgress to fix failing test

- src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java
Changed Julia file extension from .julia to .jl  
related to #1798
> Julia file extension from .julia to .jl

- docker/jenkins/publish-build.sh
remove sha from create attempt
> Fix for first request attempt

- NEWS.md
- src/cpp/session/modules/SessionHelp.R
Addresses https://github.com/rstudio/rstudio/issues/12863.
> handle old versions of pillar

- NOTICE
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
- src/node/desktop/src/assets/locales/en.json
- src/node/desktop/src/core/system.ts
- src/node/desktop/src/main/activation-overlay.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/preferences/electron-desktop-options.ts
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
- src/node/desktop/src/vue-shim.d.ts
- src/node/desktop/test/unit/core/system.test.ts
- src/node/desktop/test/unit/main/utils.test.ts
- src/node/desktop/test/unit/native/desktop.test.ts
- src/node/desktop/tsconfig.json
- src/node/desktop/webpack.plugins.js
- src/node/desktop/webpack.renderer.config.js
- src/node/desktop/webpack.rules.js
open source companion to rstudio/rstudio-pro#4539
> open source companion to rstudio/rstudio-pro#4539

- docs/news/_ga-body-tag.html
- docs/news/_ga-header-tag.html
- docs/news/_quarto.yml
- docs/user/rstudio/_ga-body-tag.html
- docs/user/rstudio/_ga-header-tag.html
- docs/user/rstudio/_quarto.yml
Old GA universal tracking is being phased out by google in 7/23. We are switching to the new g4 method.
Issue #12840 
@kmasiello implemented this for solutions and it is live (they also use quarto so I piggy backed off of what she implemented).
https://github.com/rstudio/solutions.posit.co/pull/67/files
Companion PR for Pro: https://github.com/rstudio/rstudio-pro/pull/4519
This task has been handed down from our web dev team since the universal google analytics tracking code is …
> Adding g4 tracking to news and user guide

- NEWS.md
- src/cpp/core/StringUtils.cpp
- src/cpp/core/include/core/http/AsyncConnection.hpp
- src/cpp/core/include/core/http/AsyncConnectionImpl.hpp
- src/cpp/core/include/core/http/AsyncServer.hpp
- src/cpp/core/include/core/http/AsyncServerImpl.hpp
- src/cpp/core/include/core/http/LocalStreamAsyncServer.hpp
- src/cpp/core/include/core/http/Request.hpp
- src/cpp/core/include/core/http/SslAsyncServer.hpp
- src/cpp/core/include/core/http/TcpIpAsyncServer.hpp
- src/cpp/server/ServerInit.cpp
- src/cpp/server/ServerMain.cpp
- src/cpp/server/auth/ServerSecureUriHandler.cpp
- src/cpp/server/include/server/ServerOptions.gen.hpp
- src/cpp/server/server-options.json
- src/cpp/server/session/ServerSessionProxy.cpp
- src/cpp/server/session/ServerSessionRpc.cpp
- src/cpp/session/session-options.json
companion to PR: https://github.com/rstudio/rstudio-pro/pull/4555
> Http server statistics logging

- src/node/desktop/src/main/gwt-callback.ts
To help with investigation of the crash reported in https://github.com/rstudio/rstudio/issues/13007.
Crash dump shows a (native) exception happening in the node-system-fonts package, which crashes Electron. We haven't been able to repro internally.
`set RSTUDIO_QUERY_FONTS=0` or `set RSTUDIO_QUERY_FONTS=false` then RStudio will not query for fonts. This is to help confirm that the crash is indeed happening as a result of invoking the node-system-fonts package.
As part of this I also wrapped the font calls in a try/catch and logged any exception thrown. This likely won't help with an exception happening in native code but doesn't hurt.
N/A
No change expected for normal usage. Only changes if you set an environment variable, and is intended as a troubleshooting aid, not a feature for …
> RSTUDIO_QUERY_FONTS env var for bypassing font query

- NEWS.md
OS-PR for https://github.com/rstudio/rstudio-pro/pull/4582
Update NEWS.md
> OS-PR for rstudio/rstudio-pro/pull/4582

- NEWS.md
Update NEWS.md for https://github.com/rstudio/rstudio-pro/pull/4600
> OS-PR for https://github.com/rstudio/rstudio-pro/pull/4600

- docs/user/rstudio/_quarto.yml
- docs/user/rstudio/index.qmd
Update RStudio IDE User Guide to be more aligned with other RStudio/Workbench Guides
Issue #13067 (Alignment updates - title, subtitle, sections, etc.)
Issue #13056 (Posit icon update)
> Add additional information for QA on how to validate the change, paying special …
> User Guide alignment and standardization w/ rstudio-pro guides

- docker/jenkins/Dockerfile.focal
- jenkins/Jenkinsfile.linux
- jenkins/Jenkinsfile.nightly
- utils.groovy
Open source companion to rstudio/rstudio-pro#4630
> Open source companion to rstudio/rstudio-pro#4630

- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
Address #13116 
Update references to Quarto version and run `upload-quarto.sh`.
none
Quarto change log:
```
- Properly position margin elements ([#5289](https://github.com/quarto-dev/quarto-cli/issues/5289)).
- Improve chrome detection for MacOS ([#2214](https://github.com/quarto-dev/quarto-cli/issues/2214)).
- Correctly hide section numbers in responsive HTML view of books, when requested ([#5306](https://github.com/quarto-dev/quarto-cli/issues/5306)).
- Properly handle figures within lists ([#5317](https://github.com/quarto-dev/quarto-cli/issues/5317), [#5461](https://github.com/quarto-dev/quarto-cli/issues/5461)).
- Do not hide banner style title block when in responsive view ([#5296](https://github.com/quarto-dev/quarto-cli/issues/5296)).
- Ensure global environment is available to …
```
> Update to Quarto 1.3.353

- src/cpp/server/ServerMain.cpp
- src/cpp/server/include/server/session/ServerSessionManager.hpp
- src/cpp/server/session/ServerSessionManager.cpp
- src/cpp/server/session/ServerSessionProxy.cpp
Session start time messages, reviewed in 
https://github.com/rstudio/rstudio-pro/pull/4644
> Companion to rstudio-pro#4644

- jenkins/Jenkinsfile.nightly
Fix the monitor build.
Move monitor docker builds into dispatcher to shorten the monitor build.
Build system only.
Build system only.
Build system only.
> Bugfix monitor pipeline length

- jenkins/Jenkinsfile.nightly
Removes some stages that aren't needed in the OS repo
> Remove unneeded builds from dispatcher

- jenkins/Jenkinsfile.linux
- jenkins/Jenkinsfile.nightly
- jenkins/Jenkinsfile.pull-request
- jenkins/Jenkinsfile.windows
- utils.groovy
Moves docker tag logic into `utils.groovy`, as suggested by https://github.com/rstudio/rstudio-pro/pull/4697/files/86533e8e3ec70c09476a92ae51c02fe8a12cd8ad#r1207141524
> Specify which documentation has been added or …
> Move docker image tag logic to utils.groovy

- docker/jenkins/Dockerfile.bionic
- docker/jenkins/Dockerfile.centos7
- docker/jenkins/Dockerfile.focal
- docker/jenkins/Dockerfile.jammy
- docker/jenkins/Dockerfile.opensuse15
- docker/jenkins/Dockerfile.rhel8
- docker/jenkins/Dockerfile.rhel9
- docker/jenkins/Dockerfile.windows
This commit updates the panmirror cache check in our docker build images to use the mountain hydrangea branch.
We need to get this in before branching for release.
> Add additional information for QA on how to validate the change, paying special attention to the level of …
> Update panmirror cache check for MH

- src/cpp/shared_core/system/PosixSystem.cpp
Reviewed in https://github.com/rstudio/rstudio-pro/pull/4700 
although this also fixes a build problem on the mac from that branch.
> Fixed build problem for mac with gid types (and merging into OS)

- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/utils.ts
OS changes for detect license work rstudio/rstudio-pro#4703
Remove pro-only areas in GWT callback. Add error logging in utils.
none
none
none
> OS changes for detect license

- version/news/NEWS-2023.06.0-mountain-hydrangea.md
These are usually my own work or from Launcher. I've tried to reword the ones from Launcher especially to make them more understandable to Workbench users.
N/A
N/A
Yes.
> Add some missing NEWS items for 2023.06

- docs/news/index.qmd
Update release notes for 2023.06.0.
> Update Release Notes for 2023.06.0

- src/cpp/session/SessionMain.cpp
reviewed in https://github.com/rstudio/rstudio-pro/pull/4648
By making a getaddrinfo call on them main thread, it causes the nscd library to issue a getenv, caching the result. That allows the boost libraries to safely use that api off the main thread later, without conflicting with setenv calls made on the main thread.
> Avoid crash with nscd with workaround

- docs/news/index.qmd
> Add release notes for 2023.03.2+454.pro2

- src/cpp/session/modules/SessionDataViewer.R
- version/news/NEWS-2023.06.1-mountain-hydrangea.md
Backports
- #13188
Addresses
- #13241
Cherry-picked from `main`. Added NEWS file and entry for this fix.
none
simplest repro: https://github.com/rstudio/rstudio/issues/13188#issuecomment-1589910695
none
> Backport 13188 `cacheKey` bug fix and add NEWS.md

- src/cpp/core/include/core/http/AsyncConnection.hpp
- src/cpp/core/include/core/http/AsyncConnectionImpl.hpp
- src/cpp/core/include/core/http/AsyncServer.hpp
- src/cpp/core/include/core/http/AsyncServerImpl.hpp
- src/cpp/core/include/core/http/AsyncUriHandler.hpp
- src/cpp/core/include/core/http/LocalStreamAsyncServer.hpp
- src/cpp/core/include/core/http/Request.hpp
- src/cpp/core/include/core/http/SslAsyncServer.hpp
- src/cpp/core/include/core/http/TcpIpAsyncServer.hpp
- src/cpp/server/CMakeLists.txt
- src/cpp/server/ServerInit.cpp
- src/cpp/server/ServerMetrics.cpp
- src/cpp/server/ServerMetrics.hpp
- src/cpp/server/auth/ServerAuthHandler.cpp
- src/cpp/server/session/ServerSessionManager.cpp
Reviewed in PR: https://github.com/rstudio/rstudio-pro/pull/4679
Adds plumbing for metrics, but no real metrics at this point
> Companion to metrics PR

- src/cpp/session/SessionConsoleProcessInfoTests.cpp
Fix Windows terminal symlink test 
Add a symlink path for Windows
n/a
n/a 
n/a
> Fix terminal symlink test on Windows

- src/cpp/r/RExec.cpp
- src/cpp/r/ROptions.cpp
- src/cpp/r/RSexp.cpp
- src/cpp/r/include/r/RSexp.hpp
- src/cpp/r/session/graphics/RGraphicsPlotManager.cpp
- src/cpp/rstudio-tests.in
- src/cpp/session/modules/ModuleTools.R
- src/cpp/session/modules/SessionHTMLPreview.cpp
- src/cpp/session/modules/SessionHelp.cpp
- src/cpp/session/modules/SessionRParser.cpp
- src/cpp/session/modules/SessionRTests.cpp
This PR attempts to address a couple of issues where R objects aren't appropriately protected in certain cases.
See PR for details.
Should be covered by existing tests.
N/A
N/A
> address a variety of protection issues

- dependencies/common/install-panmirror
- dependencies/windows/install-panmirror/clone-quarto-repo.cmd
Pick up the latest fixes for the visual editor.
Switch to getting the visual editor from `main`.
n/a
Quite a few fixes since the version shipped with Mountain Hydrangea. JJ mentioned that they aren't critical but worth having included for Desert Sunflower. No new features.
Branch diff (274 commits)
https://github.com/quarto-dev/quarto/compare/release/rstudio-mountain-hydrangea...main
n/a
> Switch back to latest visual editor

- dependencies/linux/install-dependencies-bionic
- dependencies/linux/install-dependencies-focal
- dependencies/linux/install-dependencies-jammy
- docker/jenkins/Dockerfile.bionic
- docker/jenkins/Dockerfile.centos7
- docker/jenkins/Dockerfile.focal
- docker/jenkins/Dockerfile.jammy
- docker/jenkins/Dockerfile.opensuse15
- docker/jenkins/Dockerfile.rhel8
- docker/jenkins/Dockerfile.rhel9
- jenkins/Jenkinsfile.linux
- jenkins/Jenkinsfile.pull-request
Companion commit for rstudio/rstudio-pro#4807.
> OS Companion commit for rstudio/rstudio-pro#4807

- jenkins/Jenkinsfile.linux
- jenkins/Jenkinsfile.pull-request
> Describe briefly what problem this pull request resolves, or what new feature it introduces. Include screenshots of any new or altered UI. Link to any Github issues that are related.
Fixes failing rust unit tests on recent builds: https://build.posit.it/blue/organizations/jenkins/IDE%2FPro-Builds%2FPlatforms%2Flinux-pipeline/detail/main/270/pipeline/2501/
The rust target is only included on "Server" builds, so we shouldn't run rust unit tests on non-Server builds.
> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered by a test, …
> Only run Rust unit tests on Pro Server target

- src/node/desktop/src/core/user.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
- src/node/desktop/test/unit/core/wait-utils.test.ts
- src/node/desktop/test/unit/main/utils.test.ts
- version/news/NEWS-2023.06.2-mountain-hydrangea.md
Backports
- Issue #13105
- PR #13304
For
- #13305
Cherry-picked the commit. Minor formatting merge conflicts.
see #13304
see #13304
see #13304
~- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md`~ 
> [Backport] Handle trailing slashes in user's `HOME` path (#13304)

- src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
Backports
- PR: #13352
- issue: rstudio/rstudio-pro#4832
For
- rstudio/rstudio-pro#4834
Cherry-picked the commit. No merge conflicts.
see automation repo
none
rstudio/rstudio-pro#4629
> [Backport] remove connection status toolbar from electron (#13352)

- src/gwt/src/org/rstudio/core/client/widget/ModalDialogTracker.java
- src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
- src/node/desktop/src/main/app-state.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/context-menu.ts
- src/node/desktop/src/main/detect-r.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/main-window.ts
- src/node/desktop/src/main/menu-callback.ts
- src/node/desktop/src/main/modal-dialog-tracker.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
- src/node/desktop/src/ui/modal-dialog.ts
- src/node/desktop/src/ui/widgets/choose-r.ts
- version/news/NEWS-2023.06.2-mountain-hydrangea.md
Backports #12972, tracked by #13281 
Cherry-picked commits, resolved `NEWS.md`
n/a
n/a 
n/a
> Backport 13281 hide menubar

- src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
- version/news/NEWS-2023.06.2-mountain-hydrangea.md
Backports
- PR: #13350
- Issue: #13347 
For
- #13351 
Cherry-picked the commit. Fixed NEWS conflict.
none
- pre-req: Desert Sunflower is released
1. Open the IDE
2. Update Available dialog should show, to update to Desert Sunflower
3. Choose Ignore Update or Remind Later
4. Help > Check for Updates
5. Update Available dialog should show, to update to Desert Sunflower
none
> [Backport] Fix update available ignored update error (#13350)

- src/cpp/session/modules/SessionHelp.R
- src/cpp/session/modules/data/DataViewer.cpp
- version/news/NEWS-2023.06.2-mountain-hydrangea.md
Backport
- PR: #13327 
- Issue: #13291
For
- #13367
Cherry-picked the commit. Fixed NEWS conflict.
none
see #13327 
none
~- [] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)~
> [Backport] fallback to searching for object "anywhere" (#13327)

- jenkins/Jenkinsfile.pull-request
OS Companion for rstudio/rstudio-pro#4892
> OS Companion for rstudio/rstudio-pro#4892

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Address #13447 
Gets whitespace fix from semver 7.5.2
n/a
No functional changes.
n/a
> Upgrade semver package

- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PositCloudAccount.ui.xml
The dialog and link for creating a new Posit cloud account is a bit confusing
> update link and text for new account

- docker/jenkins/notarize-release.sh
Backport of altool to notarytool #11863
Cherry pick, no conflicts
n/a
n/a
n/a
> Switch from altool to notarytool (#13400)

- NEWS.md
- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionDataViewer.R
- src/cpp/session/resources/grid/dtstyles.css
- src/cpp/tests/testthat/test-dataviewer.R
Addresses https://github.com/rstudio/rstudio/issues/13215.
Adjust how we "flatten" nested `data.frame`s.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13215.
N/A
> improve handling of nested data frames in Data Viewer

- docs/news/index.qmd
- version/news/NEWS-2022.12.0-elsbeth-geranium.md
- version/news/NEWS-2023.06.0-mountain-hydrangea.md
Adds missing release notes found during support week for rstudio/rstudio-pro#3874 and rstudio/rstudio-pro#4258
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no …
> Add missing release notes

- NEWS.md
- src/cpp/session/modules/SessionHelp.cpp
- src/cpp/session/resources/R.css
Addresses https://github.com/rstudio/rstudio/issues/13474.
Ensure that the headers produced by R include a class, and use that to target the arguments table with our associated styling.
N/A
> ensure top alignment for argument names

- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/13500.
> only use Electron node for RStudio Desktop

- src/cpp/core/include/core/http/AsyncServerImpl.hpp
Addresses rstudio/rstudio-pro#4917. We need to support PATCH requests for the user service SCIM endpoint as we expect identity providers such as Okta to use PATCH requests to update users.
N/A
N/A
> Add additional information for QA on how to validate the change, paying …
> Allow PATCH requests for server uri handlers

- src/cpp/server/ServerMetrics.cpp
- src/cpp/server/ServerMetrics.hpp
- src/cpp/server/session/ServerSessionManager.cpp
Reviewed in PR: https://github.com/rstudio/rstudio/pull/4967
> companion to session count metric commit

- jenkins/Jenkinsfile.pull-request
- utils.groovy
Open-source companion commit for rstudio/rstudio-pro#4955
> Open-source companion commit for rstudio/rstudio-pro#4955

- src/cpp/shared_core/system/Crypto.cpp
Handles empty vectors for the `base64Encode` function. Related to https://github.com/rstudio/rstudio-pro/issues/4757. Open source commit for https://github.com/rstudio/rstudio-pro/pull/4975
> Specify which …
> Handle empty vector in base64Encode

- src/cpp/server_core/ServerDatabase.cpp
- src/cpp/server_core/include/server_core/ServerDatabase.hpp
Open-source companion for rstudio/rstudio-pro#4979
> Open-Source Companion commit for rstudio/rstudio-pro#4979

- src/cpp/conf/rsession-dev.conf
- src/cpp/session/SessionOptions.cpp
- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/include/session/prefs/UserStateValues.hpp
- src/cpp/session/session-options.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
Addresses https://github.com/rstudio/rstudio/issues/13527.
> disable copilot by default in RStudio Server

- src/cpp/session/modules/environment/SessionEnvironment.cpp
Follow up to https://github.com/rstudio/rstudio/pull/13544.
Because `INTEGER_OR_NULL` is not available for older versions of R, we try to dynamically load and use it if available, instead of asserting it's availability at compile time.
> load INTEGER_OR_NULL dynamically to support older R

- docs/news/index.qmd
- jenkins/Jenkinsfile.hourly
- jenkins/Jenkinsfile.nightly
- version/news/NEWS-2023.06.2-mountain-hydrangea.md
Add the release notes for mountain hydrangea (also catching this branch up with some changes made on others).
> Release notes for 2023.06.2

- NEWS.md
Add the NEWS updates for the Launcher go dependency update
> Companion NEWS update for rstudio/rstudio-pro#5021

- src/cpp/core/include/core/r_util/RActiveSessions.hpp
companion to: https://github.com/rstudio/rstudio-pro/pull/5009
> Added emptySession() method

- src/cpp/session/modules/SessionDataViewer.R
Addresses https://github.com/rstudio/rstudio/issues/13585.
Add some missing NA handling in the data viewer column formatting code.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13585.
N/A
> fixup handling of NA columns

- src/cpp/core/include/core/system/PosixSystem.hpp
- src/cpp/core/include/core/system/System.hpp
- src/cpp/core/system/PosixSystem.cpp
Reviewed in pr: https://github.com/rstudio/rstudio-pro/pull/5001
> Companion to processInfo 'populateUsername' speedup

- src/gwt/src/org/rstudio/studio/client/workbench/views/help/Help.java
Avoid redirect by providing the new link when clicking on the Browse Cheatsheets button.
Update the URL
NA
NA
NA
I have signed the contributor agreement.
> Update url to cheatsheet

- version/news/NEWS-2023.09.0-desert-sunflower.md
Explicitly state this is load balancing config setting so that users aren't confused about a changed default behavior in non load-balanced environments.
> Specify which documentation has been added or modified and …
> Clarify release notes

- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/ProjectCopilotPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.css
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.java
Addresses https://github.com/rstudio/rstudio/issues/13570.
> add preview blurb for copilot

- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/ProjectCopilotPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.java
Addresses https://github.com/rstudio/rstudio/issues/13580#issuecomment-1721544197.
> require restart when changing indexing pref

- src/gwt/src/org/rstudio/studio/client/workbench/copilot/Copilot.java
- src/gwt/src/org/rstudio/studio/client/workbench/copilot/ui/CopilotInstallDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/copilot/ui/CopilotInstallDialog.ui.xml
Addresses https://github.com/rstudio/rstudio/issues/13644.
> tweak copilot install dialog message

- docs/user/rstudio/ide/guide/tools/version-control.qmd
Addresses https://github.com/rstudio/rstudio/issues/13283.
Doc update
N/A Doc update
N/A Doc update
Doc update
> Add note for marking a directory as safe in git

- .github/ISSUE_TEMPLATE/1_bug_report.md
- CONTRIBUTING.md
- docs/news/_quarto.yml
- docs/news/index.qmd
- docs/user/rstudio/_quarto.yml
- docs/user/rstudio/ide/guide/accessibility/accessibility.qmd
- docs/user/rstudio/ide/guide/environments/r/managing-r.qmd
- docs/user/rstudio/ide/guide/productivity/add-ins.qmd
- docs/user/rstudio/ide/guide/tools/jobs-in-action.qmd
- docs/user/rstudio/index.qmd
- docs/user/rstudio/readme.md
- src/cpp/core/include/core/regex/RegexCommon.hpp
- src/cpp/core/system/Win32SystemTests.cpp
- src/cpp/session/modules/panmirror/SessionPanmirrorCrossref.cpp
- src/cpp/session/modules/panmirror/SessionPanmirrorPubMed.cpp
- src/cpp/session/resources/connections/drivers/README.md
- src/cpp/session/resources/help_resources/index.htm
- src/cpp/session/resources/templates/r_presentation.Rpres
- src/cpp/session/resources/templates/shiny/app.R
- src/cpp/session/resources/templates/shiny/server.R
- src/cpp/session/resources/templates/shiny/ui.R
- src/cpp/tests/testthat/test-renv.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/model/Link.java
- src/gwt/test/org/rstudio/core/client/StringUtilTests.java
- src/gwt/www/unsupported_browser.htm
Additional URL updates to support [#13626](https://github.com/rstudio/rstudio/issues/13626)
> Update posit urls

- NEWS.md
OS companion for https://github.com/rstudio/rstudio-pro/pull/5180
> OS-PR for https://github.com/rstudio/rstudio-pro/pull/5180 update NEWS

- src/cpp/session/SessionOptions.cpp
Addresses https://github.com/rstudio/rstudio/issues/13685.
> update pandoc path resolution

- src/cpp/session/SessionHttpMethods.cpp
- src/cpp/session/modules/quarto/SessionQuartoResources.cpp
Addresses https://github.com/rstudio/rstudio/issues/13711.
> handle requests for quarto preview

- src/gwt/src/org/rstudio/studio/client/rmarkdown/RmdOutput.java
Addresses https://github.com/rstudio/rstudio/issues/13252.
Really just a band-aid; we ought to resolve the underlying issue if possible.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13252.
N/A
> handle null outputFrame

- CMakeGlobals.txt
- cmake/modules/OsRelease.cmake
- package/linux/CMakeLists.txt
Addresses https://github.com/rstudio/rstudio/issues/13676#issuecomment-1740589971.
> don't include libpq in open-source builds

- src/cpp/core/system/file_monitor/FileMonitor.cpp
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/modules/SessionCodeSearch.cpp
- src/cpp/session/projects/SessionProjectContext.cpp
Closes https://github.com/rstudio/rstudio/issues/13744.
> tweaks for file indexer

- NEWS.md
- src/cpp/session/modules/SessionRmdNotebook.R
> convert dashes to dots in yaml style chunk options

- src/cpp/session/projects/SessionProjects.cpp
Merging this change into main as well
> ensure project file is written when updating project options

- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/session/modules/environment/SessionEnvironment.cpp
Addresses https://github.com/rstudio/rstudio/issues/13534.
Use a flag to track whether the global environment can be safely serialized, and update that flag on console prompt (which would occur after any computation has finished, and so the environment can be safely inspected for changes).
N/A
N/A
N/A
> avoid over-aggressively recomputing environment serializable state

- NEWS.md
- src/cpp/core/Database.cpp
Open source companion to rstudio/rstudio-pro#5258
> Fix database start up crash

- src/cpp/server/extras/conf/database.conf
- src/cpp/server_core/ServerDatabase.cpp
- version/news/NEWS-2023.09.1-desert-sunflower.md
Open Source companion for rstudio/rstudio-pro/pull/5279
> Open Source Companion for Pro 5279

- src/gwt/src/org/rstudio/studio/client/panmirror/theme/PanmirrorTheme.java
- src/gwt/src/org/rstudio/studio/client/panmirror/theme/PanmirrorThemeCreator.java
Set visual editor theme hrBackgroundColor.
No visible or behavioral changes (this just ensures that HR elements continue having the same appearance they always had when the latest version of the visual editor is used.
> visual editor theme variable for hr backround color

- package/linux/CMakeLists.txt
Addresses https://github.com/rstudio/rstudio/issues/13676. (doh.)
> fixup for postgres libs on RPM

- src/cpp/session/modules/SessionCopilot.R
- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/13821.
> fixups for copilot agent installation

- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
- src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RMarkdownServerOperations.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModePanmirrorContext.java
Addresses https://github.com/rstudio/rstudio/issues/12690.
> fix paths in image paste

- src/gwt/acesupport/acemode/r_highlight_rules.js
- src/gwt/acesupport/acemode/yaml_highlight_rules.js
Addresses https://github.com/rstudio/rstudio/issues/13828.
> improve handling of embedded YAML highlight

- src/node/desktop/src/native/desktop/desktop.cc
Follow-up to https://github.com/rstudio/rstudio/pull/13846.
> fixups for short path conversion

- src/gwt/src/org/rstudio/studio/client/workbench/model/Session.java
Just a little FYI for anyone using `SessionInfo` that the data stored may be stale if accessed anytime after session startup. Totally didn't run into this myself or anything 😜
> Note that `SessionInfo` may be out-of-date

- NEWS.md
- src/cpp/server/auth/ServerAuthHandler.cpp
- src/cpp/server/auth/ServerAuthHandlerOverlay.cpp
- src/cpp/server/include/server/auth/ServerAuthHandler.hpp
- src/cpp/server/include/server/auth/ServerAuthHandlerOverlay.hpp
OS Companion commit for rstudio/rstudio-pro#5306
> OS Companion commit for rstudio/rstudio-pro#5306

- src/cpp/session/modules/SessionCopilot.R
- src/cpp/session/modules/SessionCopilot.cpp
Follow-up to recent proxy URL work.
> allow setting of Copilot proxy URL from envvar

- src/cpp/core/include/core/http/AsyncServer.hpp
- src/cpp/core/include/core/http/AsyncServerImpl.hpp
- src/cpp/server/session/ServerSessionProxy.cpp
reviewed in https://github.com/rstudio/rstudio-pro/pull/5213
> Tweak to logging and refactor stats for use in workbench admin

- docs/news/styles/styles.scss
- docs/user/rstudio/styles/styles.scss
> Remove unnecessary styles - callouts scss

- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/session/session-options.json
Addresses https://github.com/rstudio/rstudio/issues/13901.
Straight-forward addition of session option; uses that when initializing the Copilot agent.
N/A
N/A (to be verified by users)
N/A
> add config for auth provider URL

- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/13911.
> avoid indexing files that might contain secrets

- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
Addresses https://github.com/rstudio/rstudio/issues/13752.
> include Ctrl+Space in label for completion shortcut

- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/13667.
> only subscribe to file monitor if indexing enabled

- dependencies/common/install-quarto
- dependencies/windows/install-dependencies.cmd
Addresses https://github.com/rstudio/rstudio/issues/13914.
> switch back to Quarto 1.3

- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/13972.
> detach copilot agent when running

- NEWS.md
- src/cpp/core/system/PosixSystem.cpp
Addresses: rstudio-pro#5485
Reviewed in https://github.com/rstudio/rstudio-pro/pull/5489
> Reset linux session keyring when dropping privs

- docs/user/rstudio/_quarto.yml
- version/news/NEWS-2023.12.0-ocean-storm.md
Related to #13618 
Enabled search breadcrumbs in RStudio IDE User Guide
Enabled search breadcrumbs in the `quarto.yml` for the guide by adding the following entry (only available in Quarto 1.4+)
```
search:
show-item-context: true
```
> Add additional information for QA on …
> Search breadcrumbs in IDE User Guide

- version/news/NEWS-2023.12.0-ocean-storm.md
Add launcher upgrade release notes
Releated to rstudio/rstudio-pro#5328 and rstudio/rstudio-pro#5431
Update NEWS.md
> add launcher release notes to NEWS.md

- src/gwt/src/org/rstudio/studio/client/application/ui/LauncherSessionStatusLauncherSessionStatusUiBinderImplGenMessages_fr.properties
Update French translations from rebranding
Update strings
n/a
none
none
> French string translations for rebrand

- docker/jenkins/Dockerfile.snyk
- jenkins/Jenkinsfile.pull-request
See: https://github.com/rstudio/rstudio-pro/issues/5606
Implement snyk code scanning in the PR pipeline.
Bring over the existing snyk Dockerfile from the pro repo for use in the OS repo, so that we can include it in the PR build pipeline for both OS and Pro. Create a new stage for the snyk code scan.
The theory behind the step is to "whitelist" the changed files so that snyk code does not upload every single file in the codebase for every PR. Snyk doesn't have a way to do this -- it only lets you ignore files or directories. I also wanted to avoid copying these files anywhere inside the existing build repo to avoid the chance that packaging will pull over a directory that we weren't expecting, even if the packaged build output is not uploaded. If we were to copy this stage into another …
> Add snyk code scanning to PR pipeline

- docs/news/index.qmd
- version/news/NEWS-2023.12.0-ocean-storm.md
Update NEWS to include Databricks integration.
> update OS news

- src/node/desktop/src/main/utils.ts
When building RStudio (via, for example, `cmake --build .`), it's possible that the directory mtime itself won't get updated -- instead, just some files within are. This PR tries to augment how we find the "newest" build of RStudio by looking for those build files instead.
Related to https://github.com/rstudio/rstudio/pull/14110#issuecomment-1886136165.
> check mtime of commonly updated build files instead

- NEWS.md
- docker/jenkins/Dockerfile.windows
Update NSIS tool we use to create the setup program for RStudio Desktop on Windows.
Bump pinned version in Window's dockerfile. I've done a local package build using this NSIS version and encountered no issues (NSIS updates are generally very safe).
None
Install RStudio on Windows. Uninstall RStudio on Windows.
None
> Update NSIS to latest

- src/gwt/test/org/rstudio/studio/client/workbench/views/terminal/TerminalLocalEchoTests.java
Tweak unit test so it isn't alarming to security scans.
> use less provocative text

- src/cpp/CMakeLists.txt
- src/cpp/core/system/Crypto.cpp
- src/cpp/session/include/session/SessionConsoleProcessSocket.hpp
Addresses https://github.com/rstudio/rstudio/issues/12550.
Addressed by existing automation -- if something went wrong with key signing, RStudio Server would not be functional / users would be unable to log in.
N/A
N/A
> remove usages of deprecated OpenSSL APIs

- src/cpp/core/system/Crypto.cpp
- src/cpp/core/system/PosixSystemTests.cpp
- src/cpp/session/modules/data/DataViewer.cpp
Also fixes one case where we were leaking an EVP_PKEY_CTX.
> simplify some usages of unique_ptr

- NOTICE
Part of https://github.com/rstudio/rstudio/issues/12855.
> update NOTICE re: OpenSSL 3 usage

- src/cpp/server/ServerMain.cpp
Addresses: https://github.com/rstudio/rstudio-pro/issues/5712
- if soft limit is high enough leave it alone
- increase desired limit to 8192 if hard limit supports it
- added diagnostics to make it clear what limit rserver is using
Automated load tests will ensure the file limit has increased
With debug logging enabled, check the rserver.log startup message to see what limit it is using, and what soft/hard limits it sees.  I have not been able to get the soft limit for rserver to increase above 1024 for some reason (i.e. setting it for both rstudio-server and root in /etc/security/limits.conf hasn't worked).  I suspect that root may be treated differently for some reason and rserver is initially running as root when it does this.
> Improved logic around managing open files limit

- src/cpp/core/system/Crypto.cpp
Fixes build failures with CentOS 7. Hopefully.
> be compatible with old OpenSSL for CentOS 7

- NEWS.md
- src/gwt/acesupport/acemixins/token_tooltip.js
- src/gwt/acesupport/acemode/r_highlight_rules.js
- src/gwt/acesupport/acemode/rmarkdown_highlight_rules.js
- src/gwt/acesupport/acemode/yaml_highlight_rules.js
- src/gwt/test/test-yaml-highlight.R
- src/gwt/test/test-yaml-highlight.qmd
- src/gwt/test/test-yaml-highlight.yaml
Addresses https://github.com/rstudio/rstudio/issues/13836.
> revamp YAML highlight rules

- jenkins/Jenkinsfile.pull-request
- utils.groovy
- vuln.js
See: https://github.com/rstudio/rstudio-pro/issues/5606
Pare down the output of the Snyk code scan for the OS repo.
Add in an extra check before posting the output and use a link to the Jenkins job instead.
> Add the IS_PRO switch to OS PR Jenkinsfile for snyk code check run

- git_hooks/hooks/pre-commit
- git_hooks/secrets/README.md
- git_hooks/secrets/run-detect-secrets
- git_hooks/secrets/test/README.md
- Follow-up to: #14131 
- Part of addressing: https://github.com/rstudio/rstudio-pro/issues/5605
- Remove the code duplication between `git_hooks/hooks/pre-commit` and `git_hooks/secrets/run-detect-secrets`
- the pre-commit hook now uses the `run-detect-secrets` wrapper instead of calling `detect-secrets` directly
- Dev docs fixes for `git_hooks/secrets/README.md` and `git_hooks/secrets/test/README.md`
none
Same as #14131, verify that the docs to install and run the detect-secrets tooling are actually sufficient.
Just dev docs.
~- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md`~ 
> enhancements for secret detection scripts and docs

- src/cpp/shared_core/system/User.cpp
Addresses: https://github.com/rstudio/rstudio-pro/issues/5652
Support a min and max size for the buffer, retry and resize up until max.
Although this api is used all the time, we've only seen this error in customer environments. 
To see how large the password entry is for a user:
```
getent passwd <user-name>
```
Compile and run this program to see the 'max buffer size' supported before this fix:
```
include <stdio.h>
#include <unistd.h>
int main() {
long result = sysconf(_SC_GETPW_R_SIZE_MAX);
if (result == -1) {
perror("sysconf");
return 1;
}
printf("Maximum buffer size for getpwnam_r and getpwuid_r: %ld\n", result);
return 0;
}
```
Save this file as `getpwmax.c` and run:
```
$ cc getpwmax.c -o getpwmax
$ ./getpwmax 
Maximum buffer size for getpwnam_r and getpwuid_r: 1024
```
> Handle ERANGE errors in getpw apis

- src/cpp/CMakeLists.txt
Potential resolution for yaml-cpp build failures on RHEL 9.
> use FetchContent to get yaml-cpp when available

- git_hooks/hooks/pre-commit
- git_hooks/hooks/pre-push
- git_hooks/secrets/run-detect-secrets
- git_hooks/set-up-git-hooks
See: https://github.com/rstudio/rstudio/issues/14207
Original script uses `sh`, which has some issues with the way `read` is invoked.
Switch to using bash to fix some of the conditionals and usage of `read`.
> Use bash for git hook set-up. Change to echo -e.

- src/cpp/session/modules/quarto/SessionQuarto.cpp
Addresses https://github.com/rstudio/rstudio/issues/14177.
> support qvm installations of quarto

- src/cpp/session/projects/SessionProjectContext.cpp
Part of https://github.com/rstudio/rstudio/issues/14237.
> add extra monitor exclusions

- NEWS.md
- src/cpp/session/modules/SessionHelp.R
Addresses https://github.com/rstudio/rstudio/issues/14273.
Check for errors when attempting to render help, and bail if an error occurs.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14273.
N/A
> improve handling of dev help topics

- src/cpp/session/modules/SessionRCompletions.R
Resolves the issues described in https://github.com/rstudio/rstudio/issues/8444#issuecomment-1935065363.
> ggplot2 autocompletion touch ups

- CMakeGlobals.txt
- NEWS.md
- dependencies/linux/README
- docker/jenkins/Dockerfile.windows
Addresses https://github.com/rstudio/rstudio/issues/14210.
> bump minimum required version of R

- docs/news/index.qmd
- version/news/NEWS-2023.12.1-ocean-storm.md
Slurm Fix: 
https://github.com/rstudio/rstudio-pro/issues/5857
PR: https://github.com/rstudio/rstudio-pro/pull/5859
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by …
> Updating release notes for slurm doc fix

- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
Companion to: https://github.com/rstudio/rstudio-pro/pull/5884
> Added initInProgress flag needed for feature in rstudio-pro

- NEWS.md
Issue: https://github.com/rstudio/rstudio-pro/issues/5614
Add news entry to updated copyright date ranges (PR capturing work in rstudio-pro repo is linked to the issue above)
Updated NEWS.md
> Add additional information for QA on how to validate the change, paying special …
> Update NEWS.md for Workbench and desktop pro copyright news

- docs/news/index.qmd
- version/news/NEWS-2023.12.1-ocean-storm.md
Issue: https://github.com/rstudio/rstudio-pro/issues/5925
PR: https://github.com/rstudio/rstudio-pro/pull/5927
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the …
> Ah/news debian10 5925 - add entry that we removed debian 10 from docs.

- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
Address #14377 
Update the install scripts and upload the archive to S3.
docs commit: https://github.com/rstudio/rstudio-pro/pull/5954
n/a
n/a
Pro repo will have another commit to update Quarto for docs. It fixes a nav bar issue for them.
> Update to Quarto 1.4.551

- NEWS.md
- src/cpp/session/modules/SessionFiles.cpp
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/model/FilesServerOperations.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/Mode.java
Addresses https://github.com/rstudio/rstudio/issues/14240.
With this PR, when pasting file paths into an R document (or the R part of a multimode document), we paste the files as valid R code, formatted as project-relative paths.
> support paste of multiple files

- src/cpp/session/modules/SessionCopilot.R
(Potentially) addresses https://github.com/rstudio/rstudio/issues/13868.
Newer builds of R default to using the `libcurl` downloader, which is nonfunctional in certain (mostly enterprise) environments where a default system proxy has been set up, but R has not been configured to use.
The "wininet" download method is deprecated, but still available, so use it when possible as a fallback.
N/A
N/A
> retry agent download with wininet on failure

- NEWS.md
- src/cpp/core/zlib/CMakeLists.txt
- src/cpp/core/zlib/adler32.c
- src/cpp/core/zlib/compress.c
- src/cpp/core/zlib/crc32.c
- src/cpp/core/zlib/deflate.c
- src/cpp/core/zlib/deflate.h
- src/cpp/core/zlib/gzclose.c
- src/cpp/core/zlib/gzguts.h
- src/cpp/core/zlib/gzlib.c
- src/cpp/core/zlib/gzread.c
- src/cpp/core/zlib/gzwrite.c
- src/cpp/core/zlib/infback.c
- src/cpp/core/zlib/inffast.c
- src/cpp/core/zlib/inffast.h
- src/cpp/core/zlib/inflate.c
- src/cpp/core/zlib/inftrees.c
- src/cpp/core/zlib/inftrees.h
- src/cpp/core/zlib/trees.c
- src/cpp/core/zlib/uncompr.c
- src/cpp/core/zlib/zconf.h.cmakein
- src/cpp/core/zlib/zlib.h
- src/cpp/core/zlib/zutil.c
- src/cpp/core/zlib/zutil.h
Updates our embedded `zlib` dependency to 1.3.1. Addresses rstudio/rstudio#5971.
Followed the instructions here: https://github.com/rstudio/rstudio/blob/3f57c83d18bbd7e23aae63cccf2bd5c39d36c761/src/cpp/core/zlib/CMakeLists.txt#L16
N/A
> Add additional information for QA on …
> Update embedded zlib to v1.3.1

- src/cpp/session/resources/roxygen_help.html
Update links and advice in roxygen quick reference
Edit documentation.
N/A 
Changes should show in Roxygen Quick Reference
N/A
I signed the contributor agreement
> Update Roxygen quick help reference

- src/cpp/session/modules/SessionPackages.R
Update link in template 
Changes in SessionPackages.R 
N/A
n/a
n/a
I signed the contributor agreement.
> Update links in template

- NEWS.md
OS commit for  rstudio/rstudio-pro#6024
> NEWS entry for rstudio/rstudio-pro#6024

- NEWS.md
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
Addresses https://github.com/rstudio/rstudio/issues/13900.
Straightforward escaping of single quotes within a path.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13900.
N/A
> escape single quotes in parentDir

- src/gwt/src/org/rstudio/core/client/StringUtil.java
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/core/client/widget/NumericValueWidget.java
- src/gwt/src/org/rstudio/core/client/widget/SelectWidget.java
- src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
- src/gwt/src/org/rstudio/studio/client/common/repos/SecondaryReposWidget.css
- src/gwt/src/org/rstudio/studio/client/common/repos/SecondaryReposWidget.java
- src/gwt/src/org/rstudio/studio/client/common/spelling/ui/SpellingLanguageSelectWidget.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectGeneralPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CompilePdfPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml
This PR implements a number of small UI changes recommended by Paul. Primarily, the changes are around:
- Using rounded borders consistently, and
- Extra spacing between text inputs and buttons where appropriate.
Some sample before and after:
Mostly straightforward CSS updates.
N/A
A quick pass through the UI on desktop + server for Windows + Linux + macOS at certification time would be sufficient; I don't think any explicit testing is required for now?
N/A
> modernize UI display in a number of places

- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/13432.
Check for, and remove, `-- !preview` lines from document contents before sending them to the Copilot agent.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13432.
N/A
> remove preview comments from SQL documents

- CMakeGlobals.txt
- src/cpp/conf/rdesktop-dev.conf
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.css
Addresses https://github.com/rstudio/rstudio/issues/13981.
> allow for resizable label in Copilot status

- src/cpp/session/modules/rmarkdown/NotebookQueueUnit.cpp
Addresses an issue where chunk execution could fail because (seemingly) the `doc_type` member on the `execute_notebook_chunks` request was missing.
Attempt a couple fallbacks when reading the document type, and use a default type of "r_markdown" if all else fails.
N/A
N/A -- to be verified by affected users.
N/A
> speculative workaround to missing doctype on chunk exec

- NEWS.md
This commit adds `NEWS` items for the upcoming release. These are all items that I've worked on personally, I haven't added anything from other contributors.
N/A
N/A
N/A
> Add some NEWS items for Chocolate Cosmos

- docs/user/rstudio/_quarto.yml
…ation issue
Related to #14489
It appears that something changed in quarto that now requires the index page to be added to the nav for the left nav to display from the root of the site.
> Add additional information for QA on how to validate the change, paying special …
> Fix side navigation (not displayed when viewing the "main page" of the site/guide

- docs/news/index.qmd
Adds mention of Workbench in the release notes w.r.t. rstudio-pro#5612.
Minimal changes adding workbench" in the "RStudio" section. Alternative would be a new bbullet point in the "Workbench" section.
NA
NA
Update release notes.
> Mention Workbench in RN w.r.t. #5612

- src/cpp/session/modules/SessionRCompletions.R
Addresses #14519  (https://github.com/rstudio/rstudio/pull/14394#issuecomment-2037650919)
Same as in #14394
NA
NA
NA
Signed contributor agreement
> Don't display "fake" aesthetics in ggplot2 completions

- src/cpp/core/CrashHandler.cpp
This makes it easier to disable the crash handler prompt when running automation tests.
> use envvar to override crash handler prompt

- src/cpp/session/modules/SessionRCompletions.R
Addresses https://github.com/rstudio/rstudio/issues/14524.
Only check for a custom help handler if the top-level context is a function call.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14524. 
N/A
> only trigger custom help handler on top-level function context

- src/cpp/session/modules/SessionCodeSearch.cpp
Be able to access WORDLIST from the Go to Files / Functions command
similar to the approach here: https://github.com/rstudio/rstudio/commit/cb7f275bfe6f290272b6eae6e6667852c1d51d59 used for https://github.com/rstudio/rstudio/issues/14313
NA
NA verify that WORDLIST appears.
NA
> Add WORDLIST to go to files / functions

- NEWS.md
> Add NEWS.md entry for rstudio-pro#6078

- version/news/NEWS-2023.12.1-ocean-storm.md
Fixes https://github.com/rstudio/rstudio-pro/issues/6051
> Fix pane layout release note to include Workbench

- src/gwt/build.xml
I've wanted to do this for a long time, since I always change it locally and it's always better to have this enabled for debugging purposes.
> Use pretty formatting for ant drafts (better for web debugging)

- version/news/NEWS-2024.04.0-rel-chocolate-cosmos.md
OS-PR for: https://github.com/rstudio/rstudio-pro/pull/6171
See: https://github.com/rstudio/rstudio-pro/issues/3385
Update `NEWS.md`
> OS-PR for rstudio/rstudio-pro#6171: Update NEWS.md

- docs/news/_quarto.yml
- docs/user/rstudio/_quarto.yml
Related to https://github.com/rstudio/rstudio-pro/issues/5637
Adding link to license guide and removing install guide
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by …
> Removing install guide, adding admin guide, adding licenses

- docs/news/index.qmd
- version/news/NEWS-2023.12.1-ocean-storm.md
Related to https://github.com/rstudio/rstudio-pro/issues/6178
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not …
> Add Ref Architectures entry to release notes

- version/BUILDTYPE
> Promote CC build type to Release

- version/news/NEWS-2024.04.0-rel-chocolate-cosmos.md
Update the link in the Chocolate Cosmos news entry for user provisioning after rstudio/rstudio-pro#6174 was merged.
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by …
> Update link to user provisioning docs in NEWS

- src/gwt/src/org/rstudio/core/client/BrowseCap.java
- src/gwt/src/org/rstudio/core/client/command/EditorCommandManager.java
- src/gwt/src/org/rstudio/core/client/command/KeyCombination.java
- src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java
- src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/application/Desktop.java
- src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
- src/gwt/src/org/rstudio/studio/client/common/DefaultGlobalDisplay.java
- src/gwt/src/org/rstudio/studio/client/projects/Projects.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModePanmirrorContext.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalConstants_fr.properties
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java
Open-source merge for https://github.com/rstudio/rstudio-pro/pull/6211
Removing Qt-specific code in GWT and some of the code related to deprecated RDP feature.
> open-source merge for rstudio-pro-pull-6211

- version/news/NEWS-2024.04.0-rel-chocolate-cosmos.md
> Minor fixes and add missing news entries

- version/news/NEWS-2024.04.0-chocolate-cosmos.md
Intention is to merge to main and then pull back to rel-chocolate-cosmos.
> Add Quarto 1.4 to NEWS

- version/news/NEWS-2024.04.1-chocolate-cosmos.md
Issue: https://github.com/rstudio/rstudio-pro/issues/4717
PR: https://github.com/rstudio/rstudio-pro/pull/6263
> OS PR for 6263 - Update NEWS.md

- src/cpp/CMakeLists.txt
Addresses https://github.com/rstudio/rstudio/issues/14629.
Re-organized CMake checks for yaml-cpp to first check value of that CMake variable.
N/A; build-only change.
N/A
N/A
> ensure RSTUDIO_USE_SYSTEM_YAML_CPP is honoured

- src/cpp/shared_core/system/PosixSystem.cpp
Closes https://github.com/rstudio/rstudio/issues/8890.
> include requisite headers

- NEWS.md
This commit adds `NEWS` items for the upcoming release. These are all items that I've worked on personally, I haven't added anything from other contributors.
N/A
N/A
N/A
> Adds some recent Workbench NEWS items

- dependencies/linux/install-dependencies-noble
First steps to getting builds on Ubuntu 24.04.
> add dependency script for noble

- NEWS.md
This commit adds `NEWS` items for the upcoming release. These are all items that I've worked on personally, I haven't added anything from other contributors.
N/A
N/A
N/A
> Adds some more recent Workbench NEWS items

- src/cpp/session/modules/automation/SessionAutomation.R
This PR makes it possible to run the automation tests associated with a particular commit of the RStudio repository, without needing to bundle those tests with the product itself. It makes use of the GitHub API to list the automation files available for a particular commit ref, downloads them, and then runs those tests.
The intention is to eventually use this machinery to allow retrieval of a particular release's automation test files, and run those, in a non-interactive way. (That is, `rstudio --run-automation` would retrieve the test files associated with the commit from which RStudio was built, and then run those.)
The alternative would be to just bundle the automation tests directly with RStudio, which also seems reasonable, but as a matter of hygiene it also makes sense if we exclude …
> use github api when retrieving test files

- CMakeGlobals.txt
- NEWS.md
- dependencies/common/patch-node
- dependencies/common/patch-node.cmd
- dependencies/tools/rstudio-tools.cmd
- dependencies/tools/rstudio-tools.sh
Addresses [Update node.js in Chocolate Cosmos #14731](https://github.com/rstudio/rstudio/issues/14731)
Updated scripts, uploaded node to cdn.
NA
This node is used by Copilot, so sanity-checking that functionality is recommended.
NA
> Node 18.20.3 for Chocolate Cosmos

- src/cpp/core/include/core/r_util/RActiveSessions.hpp
- src/cpp/core/r_util/RActiveSessions.cpp
- src/cpp/core/r_util/RSessionContext.cpp
- src/cpp/server/session/ServerSessionMetadataRpc.cpp
- src/cpp/session/SessionModuleContext.cpp
Remove checks that project directories exist for active sessions.
> Open source companion to rstudio/rstudio-pro#6312

- git_hooks/secrets/.secrets.baseline
- src/gwt/acesupport/acemode/sweave_highlight_rules.js
Ports relevant pieces of https://github.com/rstudio/rstudio/pull/14670 for the patch release.
> port sweave fixes

- jenkins/Jenkinsfile.linux
Fix the broken builds.
Update the gpg codesigning key to the version with the increased expiration date.
> Update the gpg codesign key

- NEWS.md
Add fixes to NEWS for patch 2.
> update patch2 news

- NEWS.md
- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
Addresses #14779
Bumped version numbers, uploaded artifacts via script, quick sanity test.
Existing tests
Verify via Help / About that Quarto 1.4.555 is being used.
NA
> Bundle Quarto 1.4.555

- NEWS.md
- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
Update quarto to v1.4.555 in chocolate-cosmos patch 2 to pick up some critical fixes.
Tracked by #14779
> update quarto to v1.4.555 for chocolate-cosmos patch 2

- src/cpp/core/include/core/Database.hpp
- src/cpp/server/auth/ServerAuthHandler.cpp
- src/cpp/server/auth/ServerAuthHandlerOverlay.cpp
- src/cpp/server/include/server/auth/ServerAuthHandler.hpp
- src/cpp/server/include/server/auth/ServerAuthHandlerOverlay.hpp
OS companion for rstudio/rstudio-pro#6394
> OS companion for rstudio/rstudio-pro#6356

- src/gwt/src/org/rstudio/core/client/widget/VirtualizedDataGrid.java
Addresses an issue with the recent PR in https://github.com/rstudio/rstudio/pull/14791.
> fix issue with first / last entry in Files pane not being drawn

- git_hooks/secrets/.secrets.baseline
- src/cpp/session/modules/SessionCopilot.R
- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/14800.
> update to Copilot 1.35.0

- .gitignore
- src/cpp/session/SessionMain.cpp
- src/cpp/session/modules/automation/SessionAutomation.R
Fixes an issue where automation could fail to run with a relatively undecipherable xml2 error.
> fixups for 'npm run automation'

- src/cpp/session/modules/SessionCopilot.cpp
This PR fixes an issue related to the most recent Copilot update. Newer version of Copilot require us to send an "initialized" notification before any other requests can be processed. However, we have code of the form:
```
if (ensureAgentRunning()) {
sendRequest(...)
}
```
And while `ensureAgentRunning()` will enqueue the "initialized" notification if necessary, it doesn't ensure the request created via `sendRequest()` is appropriately sequenced after that request.
This fix seemed like the most straightforward:
- Before initialization has happened, process only the initialization-specific requests;
- After initialization, process requests in the queue in order.
> ensure copilot init methods are processed before any other requests

- src/gwt/src/org/rstudio/studio/client/workbench/copilot/Copilot.java
Addresses https://github.com/rstudio/rstudio/issues/14845.
> execute completion handler on installation cancel 

- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
Addresses https://github.com/rstudio/rstudio/issues/14830.
Addresses https://github.com/rstudio/rstudio/issues/14827.
Not adding to NEWS yet; I assume we'll updated Quarto again once it's fully released?
> update to Quarto 1.5.45 RC

- src/node/desktop/src/renderer/desktop-bridge.ts
Addresses https://github.com/rstudio/rstudio/issues/14851.
> also create aliased paths when getting existing directory

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update to latest v30.x Electron.
Changes from 30.1.0: https://releases.electronjs.org/release/compare/v30.1.0/v30.1.2
> update from electron 30.1.0 to 30.1.2

- src/cpp/rstudio-tests.bat.in
- src/cpp/shared_core/FilePath.cpp
- src/cpp/shared_core/FilePathTests.cpp
- src/cpp/shared_core/include/shared_core/FilePath.hpp
> Fix build by implementing isWriteable for win32

- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
Bundle most recent quarto 1.5 RC build (1.5.47)
https://github.com/rstudio/rstudio/issues/14827
> update to Quarto RC 1.5.47

- src/cpp/session/SessionSourceDatabase.cpp
This happened in the load/stress tests when there was a race between one request updating the properties file and another trying to read it. Once in a while it would see it as empty and report that auto-save error to the user. We put in a quick retry in that case and it resolves the problem.
Reviewed in PR: https://github.com/rstudio/rstudio-pro/pull/6468
> Fixed intermittent bug with auto-save dialog error

- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
Addresses #14894
Picked up new Quarto RC 1.5.49 with fix.
Was caught by an automated test. Yay for the test.
Needs to be tested on a system with case-sensitive filesystem; any Linux, with Server, Desktop (or pro-equivalents).
NA
> Update quarto 1.5.49 to fix issue with mixed-case Quarto project names

- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
- version/news/NEWS-2024.04.3-chocolate-cosmos.md
Addresses https://github.com/rstudio/rstudio-pro/issues/6514
Update to quarto 1.4.557 (https://github.com/quarto-dev/quarto-cli/releases/tag/v1.4.557)
> update quarto to v1.4.557 in chocolate cosmos

- NEWS.md
- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
Addresses #14884 
Bundle release version of Quarto 1.5 (1.5.52) with the IDE
NA
NA
NA
> bundle Quarto 1.5.52

- NEWS.md
These are features or bugs that I've been directly involved in as well as translations of Launcher's own NEWS items to Workbench's perspective.
N/A
N/A
Yes.
> Add various `NEWS` items for Cranberry Hibiscus

- cmake/globals.cmake
A potential fix for automation failures in https://github.com/rstudio/rstudio-pro/issues/6477.
> fix QUARTO_ENABLED define in builds

- src/cpp/session/modules/SessionRCompletions.R
Addresses https://github.com/rstudio/rstudio/issues/14586#issuecomment-2112806827.
> handle ggplot2 completion attempts in console

- NEWS.md
- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
> update to quarto 1.5.53

- src/cpp/session/projects/SessionProjectContext.cpp
Addresses https://github.com/rstudio/rstudio/issues/14778#issuecomment-2195201860.
> resolve aliased paths for external scratch path

- NEWS.md
- src/cpp/session/modules/SessionRCompletions.R
Addresses https://github.com/rstudio/rstudio/issues/14566.
> handle assignments in ggplot2 aes completions

- NEWS.md
- src/node/desktop/src/main/application-launch.ts
Addresses https://github.com/rstudio/rstudio/issues/14695.
> unset initial working dir envvar after starting separate session

- src/cpp/core/include/core/Macros.hpp
- src/cpp/r/include/r/RSexp.hpp
- src/cpp/r/session/RSessionState.cpp
- src/cpp/r/session/RStdCallbacks.cpp
- src/cpp/session/modules/SessionDebugging.cpp
I don't currently have a Windows VM available, so I can't test if this resolves the issue, but I believe it should.
> fix import of symbols on win32

- NEWS.md
- src/cpp/session/modules/SessionDataViewer.R
- src/cpp/session/resources/grid/dtviewer.js
Addresses https://github.com/rstudio/rstudio/issues/14257.
> tweak formatting of data.frame in list columns

- NEWS.md
- src/cpp/session/resources/grid/dtviewer.js
Addresses https://github.com/rstudio/rstudio/issues/14509.
> use row index (rather than name) when building index call

- src/cpp/server/ServerOptions.cpp
- src/cpp/server/ServerOptionsOverlay.cpp
- src/cpp/server/include/server/ServerOptions.hpp
Companion OS commit for rstudio/rstudio-pro#6522
> add snowflake server option

- src/cpp/session/modules/NotebookConditions.R
Addresses https://github.com/rstudio/rstudio/issues/14553.
> revert changes to global condition handlers

- NEWS.md
- cmake/globals.cmake
- dependencies/tools/rstudio-tools.cmd
- dependencies/tools/rstudio-tools.sh
- dependencies/tools/upload-node.sh
- src/cpp/conf/rsession-dev.conf
- src/cpp/session/SessionOptions.cpp
Addresses #14898
Details on node.js 20.15.1 release: https://nodejs.org/en/blog/vulnerability/july-2024-security-releases
This is the node.js we install with RStudio for use by Copilot. In Workbench, it is also used by code-server.
> update to node.js 20.15.1

- src/gwt/src/org/rstudio/studio/client/panmirror/outline/PanmirrorOutlineWidget.java
Addresses https://github.com/rstudio/rstudio/issues/13159#issuecomment-2214835731.
> also display empty header labels in scope tree for visual mode

- src/cpp/core/system/Xdg.cpp
To preserve existing behavior.
> remove ensureDirectory call

- src/cpp/session/modules/SessionCopilot.R
- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/14850.
> stop copilot agent before installing new one

- NEWS.md
OS PR release notes commit for the managed credentials UX/UI additions.
> Add lines for managed credentials UI/UX

- NEWS.md
Add missing release notes for Cranberry Hibiscus. 
NEWS.md
> Add vs code updates to release notes

- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/14952.
> only try to start copilot on main thread

- version/news/NEWS-2024.07.0-cranberry-hibiscus.md
Adds NEWS entry for rstudio/rstudio-pro#6561.
> Add NEWS entry for rstudio/rstudio-pro#6561

- src/cpp/server/include/server/ServerOptions.gen.hpp
- src/cpp/server/server-options.json
Not to be merged until after the branch!
Addresses: https://github.com/rstudio/rstudio-pro/issues/6149
Update these defaults, based on load testing. 
Covered via automation. No manual testing required.
> Perf tuning params

- version/news/NEWS-2024.08.0-cranberry-hibiscus.md
Added NEWS entry for rstudio/rstudio-pro#6608.
> Add NEWS entry for rstudio/rstudio-pro#6608

- version/news/NEWS-2024.08.0-cranberry-hibiscus.md
Add news entry for https://github.com/rstudio/rstudio-pro/pull/6316
> add news entry for rstudio/rstudio-pro#6316

- version/news/NEWS-2024.08.0-cranberry-hibiscus.md
NEWS entries for rstudio/rstudio-pro#6529 and rstudio/rstudio-pro#6635, once they are merged in.
> NEWS entries for rstudio-pro#6529 and rstudio-pro#6635

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Addresses #14982
Update package.json, npm update, npm i
Confirmed unit tests and built-in automation passes.
Nothing specific to test.
NA
> update to electron 31.3.0

- jenkins/Jenkinsfile.linux
A typo was uploading the wrong file under the .tar.gz [ noble installer less section on the dailies page](https://dailies.rstudio.com/rstudio/cranberry-hibiscus/electron/noble-amd64-xcopy/). This corrects it
> …
> Upload tar file for noble

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Bump electron from 31.3.0 to 31.3.1.
update package.json, npm update, npm i, sanity testing
NA
NA
NA
> update to electron 31.3.1 from 31.3.0

- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/session/modules/automation/SessionAutomationRemoteObject.R
- src/cpp/tests/automation/testthat/test-automation-completions.R
So we can remain compatible with R 3.6.3.
https://github.com/rstudio/rstudio/issues/15021
> avoid using raw strings

- version/news/NEWS-2024.08.0-cranberry-hibiscus.md
Various NEWS entries for:
- rstudio/rstudio-pro#6591
- rstudio/rstudio-pro#6676
- rstudio/rstudio-pro#6657
I also added an "Upgrade Instructions" section which details upgrade instructions for customers coming from 2024.04 with user provisioning enabled.
N/A
N/A
> Add …
> Various NEWS updates for CH

- NEWS.md
- src/cpp/r/R/Tools.R
- src/cpp/session/modules/SessionDataViewer.R
- src/cpp/session/modules/data/DataViewer.cpp
- src/cpp/session/resources/grid/dtviewer.js
- src/cpp/tests/automation/testthat/test-automation-data-viewer.R
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/js/JsUtil.java
- src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
- src/gwt/src/org/rstudio/studio/client/dataviewer/DataTable.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTargetWidget.java
Addresses https://github.com/rstudio/rstudio/issues/9960.
This one was a little thorny to unravel, but the short version is:
- When generating the row names column, we differentiate between numeric column values, and character values.
- We also use the aforementioned row names type to control the type of indexing used for view.
Included with PR.
Test via notes in https://github.com/rstudio/rstudio/issues/9960, but this change would be worth smoke tests around the data viewer in general.
N/A
> data viewer: fix data / list view for filtered rows

- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
- version/news/NEWS-2024.09.0-cranberry-hibiscus.md
Addresses #15102
Update constant in various scripts. Upload quarto to tools bucket.
N/A
We are going from Quarto 1.5.54 to 1.5.57. Changes in these can be seen here:
https://github.com/quarto-dev/quarto-cli/blob/v1.5.57/news/changelog-1.5.md#in-this-release
https://github.com/quarto-dev/quarto-cli/blob/v1.5.56/news/changelog-1.5.md#in-this-release
https://github.com/quarto-dev/quarto-cli/blob/v1.5.55/news/changelog-1.5.md#in-this-release
The one related to the issue is https://github.com/quarto-dev/quarto-cli/issues/10573
N/A
> Update to Quarto 1.5.57

- src/cpp/core/system/PosixChildProcess.cpp
This fixes a (likely rare) memory leak that can occur if `runCommand` or `runProcess` were to fail and exit early.
> use unique_ptr to release memory on exit

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/assist/RChunkHeaderParser.java
- src/gwt/test/org/rstudio/studio/client/workbench/views/source/editors/text/assist/RChunkHeaderParserTests.java
- src/gwt/test/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/DefaultChunkOptionsPopupPanelTests.java
Addresses #15162
Include "-" as a valid label character in the regex used for parsing.
Added GWT unit tests.
Test as indicated in issue.
NA
> handle hyphens in RMD chunk labels

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
- version/news/NEWS-2024.09.0-cranberry-hibiscus.md
Pick up recent fixes in Electron.
https://releases.electronjs.org/release/compare/v30.2.0/v30.4.0
Update package.json and regenerate the lockfile. Did quick sanity testing on macOS.
Nothing specific to this.
Minor Electron update covered by desktop automation.
NA
> update Cranberry Hibiscus to electron 30.4.0

- docker/jenkins/Dockerfile.rhel9
- package/linux/make-package
Another tweak to try and understand why rhel9 builds are hanging.
> force rhel9 docker rebuild

- package/linux/make-package
More tinkering to diagnose ongoing rhel9 build failures.
> report file handle limits and add fakeroot timeout

- NEWS.md
- src/cpp/r/include/r/RSexp.hpp
- src/cpp/r/session/RClientMetrics.cpp
- src/cpp/r/session/graphics/RGraphicsDevDesc.cpp
- src/cpp/r/session/graphics/RGraphicsDevDesc.hpp
- src/cpp/r/session/graphics/RGraphicsDevDescVersions.hpp
- src/cpp/r/session/graphics/RGraphicsDevice.cpp
- src/cpp/r/session/graphics/RGraphicsDeviceContext.hpp
- src/cpp/r/session/graphics/RGraphicsHandler.cpp
- src/cpp/r/session/graphics/RGraphicsHandler.hpp
- src/cpp/r/session/graphics/RGraphicsUtils.cpp
- src/cpp/r/session/graphics/RShadowPngGraphicsHandler.cpp
Addresses https://github.com/rstudio/rstudio/issues/14613.
Fills in the stubs for the newer graphics engine methods.
N/A
N/A
> support new graphics device methods

- NEWS.md
- src/cpp/session/modules/SessionRCompletions.R
Add the same completion as `Sys.setenv()` and `Sys.getenv()`
Add it to the choices 
NA
NA
NA
Signed contributor agreement
> Add completion for `Sys.unsetenv()`

- NEWS.md
- src/node/desktop/src/main/detect-r.ts
Addresses https://github.com/rstudio/rstudio/issues/15044.
> forward LD_LIBRARY_PATH when detecting R installation

- src/node/desktop/package-lock.json
Ran `npm audit --fix` to address some vulnerabilities.
> npm audit fix of a high-sev vulnerability

- src/cpp/tests/automation/testthat/test-automation-rmarkdown.R
Uncomment and tweak previously-failing automation tests now that the fixes are in.
> enable some tests

- src/cpp/tests/automation/testthat/test-automation-quarto.R
Test for https://github.com/rstudio/rstudio/issues/15189
> add test for issue 15189

- src/cpp/tests/automation/testthat/test-automation-quarto.R
> add test for visual editor round trip of raw latex blocks

- src/cpp/session/modules/build/SessionBuild.cpp
Fixes https://github.com/rstudio/rstudio/issues/14564.
> work around lack of unicode in Boost

- NEWS.md
OS-PR for https://github.com/rstudio/rstudio-pro/pull/6793
> Update NEWS.md OS-PR for rstudio-pro/pull/6793

- NEWS.md
- package/osx/cmake/prepare-package.cmake
- src/cpp/session/CMakeLists.txt
Open source merge for https://github.com/rstudio/rstudio-pro/pull/6870
> open-source merge for pro 6870

- src/node/desktop/src/ui/utils.ts
- src/node/desktop/test/unit/ui/utils.test.ts
- version/news/NEWS-2024.09.1-cranberry-hibiscus.md
Addresses #15280
Backport fixes already made in Kousa Dogwood (2024.11.x).
Unit tests included (and confirmed to pass)
Verify scenario in [linked issue](https://github.com/rstudio/rstudio/issues/15280). Also consider re-testing these:
- https://github.com/rstudio/rstudio/issues/14963
- https://github.com/rstudio/rstudio/issues/14964
NA
> Backport UNC path handling fixes in Electron desktop code

- src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
Addresses https://github.com/rstudio/rstudio/issues/14589#issuecomment-2405580035.
> use separate templates for R Markdown vs. Quarto documents

- version/news/NEWS-2024.09.1-cranberry-hibiscus.md
OS-PR for
- rstudio/rstudio-pro#6753
- rstudio/rstudio-pro#6881
> Update NEWS for rstudio-pro#6753 & rstudio-pro#6881

- src/cpp/core/include/core/system/PosixSystem.hpp
- src/cpp/core/system/PosixSystem.cpp
- src/cpp/server/ServerMain.cpp
Cleans up https://github.com/rstudio/rstudio/pull/15285.
> use single thread to reap child processes on interrupt

- package/linux/CMakeLists.txt
Addresses https://github.com/rstudio/rstudio/issues/15229.
> suppress build id links for RPM builds

- NEWS.md
- src/gwt/acesupport/acemode/rmarkdown_folding.js
Addresses https://github.com/rstudio/rstudio/issues/15313.
Add / improve boundary detection when computing fold widget ranges.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15313.
N/A
> add boundary checks to rmd fold widget boundary detection

- src/cpp/r/R/Api.R
- src/cpp/r/R/Tools.R
- src/cpp/session/SessionModuleContext.cpp
Related to https://github.com/rstudio/rstudioapi/issues/280.
> add some API functions

- NEWS.md
- src/cpp/session/modules/environment/SessionEnvironment.cpp
Addresses https://github.com/rstudio/rstudio/issues/15330.
Handle null pointers, which can come from here:
https://github.com/rstudio/rstudio/blob/078b340227981ae43ac4e4f56b2f0c84302aeb59/src/cpp/session/modules/environment/SessionEnvironment.cpp#L1769-L1773
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15330.
N/A
> add missing null check for environment debug state

- version/news/NEWS-2024.09.1-cranberry-hibiscus.md
News PR for https://github.com/rstudio/rstudio-pro/pull/6932
> OS-PR for https://github.com/rstudio/rstudio-pro/pull/6932

- version/news/NEWS-2024.09.1-cranberry-hibiscus.md
News PR for https://github.com/rstudio/rstudio-pro/pull/6934
> OS-PR for https://github.com/rstudio/rstudio-pro/pull/6934

- src/node/desktop/src/ui/splash/splash.html
- src/node/desktop/src/ui/splash/splash_unversioned.html.in
On Windows and Linux (Ubuntu) I was seeing a scrollbar on the new splash screen. This should fix it.
> Fix splash scrollbar

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Addresses #14982
Latest release of Electron 31 with oodles of security fixes: https://releases.electronjs.org/release/v31.7.2
Ran local tests.
NA
NA
> Electron 31.7.2

- NEWS.md
I was unsure if some of the issues that I completed needed release notes entries and ultimately decided that they should.
This PR covers the following issues:
- [6069 - Docs: Workbench User Guide Intro page and guides to nav bar](https://github.com/rstudio/rstudio-pro/issues/6069)
- [6678 - Docs - Correct broken links](https://github.com/rstudio/rstudio-pro/issues/6678)
- [6151 - Documentation Guide Links and Release Notes link in nav bar aren't versioned](https://github.com/rstudio/rstudio-pro/issues/6151)
- [6967 - Posit WB User Guide - Posit Workbench Guide …
> Updating release notes - Several missed issues

- src/cpp/session/projects/SessionProjectContext.cpp
Addresses https://github.com/rstudio/rstudio/issues/15098.
Make sure we resolve potentially-aliased paths set for the user data directory.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15098.
N/A
> support aliased scratch paths

- src/cpp/server/include/server/session/ServerSessionManager.hpp
- src/cpp/server/session/ServerSessionManager.cpp
- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/modules/SessionSource.cpp
- src/cpp/session/session-options.json
This is a companion PR to https://github.com/rstudio/rstudio-pro/pull/7053
See other PR.
See other PR.
See other PR.
Options updated.
> Changes related to adding open files option.

- NEWS.md
- src/cpp/session/modules/SessionCodeTools.R
Addresses https://github.com/rstudio/rstudio/issues/15422.
Rather than iterating over the names and then accessing values via that name, just iterate over the vector object directly. (Iterating and accessing via names for non-hashed data structures like R lists / data frames is slow, since this requires a linear search of the requested name.)
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15422.
N/A
> iterate over values directly when getting labels

- src/cpp/server/include/server/ServerOptions.gen.hpp
- src/cpp/server/server-options.json
- src/cpp/server/session/ServerSessionManager.cpp
- src/cpp/session/modules/automation/SessionAutomation.R
- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/session/modules/rmarkdown/NotebookCache.cpp
- src/cpp/session/session-options.json
- src/cpp/tests/automation/testthat/test-automation-build-pane.R
- src/cpp/tests/automation/testthat/test-automation-completions.R
- src/cpp/tests/automation/testthat/test-automation-quarto.R
- src/cpp/tests/automation/testthat/test-automation-reformat.R
- src/cpp/tests/automation/testthat/test-automation-rmarkdown.R
- src/node/desktop/src/main/session-launcher.ts
> support test markers for automation

- NEWS.md
See: https://github.com/rstudio/rstudio-pro/issues/7025
Pro PR: https://github.com/rstudio/rstudio-pro/pull/7078
> NEWS PR for PRO-PR 7078

- NEWS.md
Add news items about API enhancements.
Added the items below.
> Add news update for workbench API enchancements.

- version/news/NEWS-2024.12.0-kousa-dogwood.md
NEWS entry for rstudio/rstudio-pro#6821.
> Add NEWS entry for rstudio/rstudio-pro#6821

- version/news/NEWS-2024.12.0-kousa-dogwood.md
> Add kdog release notes

- src/node/desktop/package-lock.json
Note: we need to discuss if we want this in the initial KD release (probably) or wait for the patch.
Addresses https://github.com/rstudio/rstudio-pro/issues/7120
run `npm audit` to update lockfile
Covered by existing tests
Nothing to specifically test
NA
> update desktop dependencies

- dependencies/common/install-panmirror
- dependencies/windows/install-panmirror/clone-quarto-repo.cmd
- docker/jenkins/Dockerfile.bionic
- docker/jenkins/Dockerfile.focal
- docker/jenkins/Dockerfile.jammy
- docker/jenkins/Dockerfile.opensuse15
- docker/jenkins/Dockerfile.rhel8
- docker/jenkins/Dockerfile.rhel9
- docker/jenkins/Dockerfile.windows
Addresses https://github.com/rstudio/rstudio/issues/15381
Pull panmirror from main in dockerfiles and dependency scripts. Opened https://github.com/rstudio/rstudio/issues/15447 to track re-pinning for mariposa-orchid release.
NA
NA
NA
> unpin panmirror during mariposa-orchid development

- version/news/NEWS-2024.09.0-cranberry-hibiscus.md
NEWS update from https://github.com/rstudio/rstudio-pro/pull/6665
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a new feature, indicate …
> Update news entry for vscode-server#17

- version/news/NEWS-2024.12.1-kousa-dogwood.md
News PR for https://github.com/rstudio/rstudio-pro/pull/7170
> News PR for https://github.com/rstudio/rstudio-pro/pull/7170

- version/news/NEWS-2024.12.1-kousa-dogwood.md
News update for https://github.com/rstudio/rstudio-pro/pull/7176
> OS-PR for https://github.com/rstudio/rstudio-pro/pull/7176

- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/15507#issuecomment-2536852441.
When indexing an untitled document, we need to check the recorded document type and explicitly allow documents with the (non-standard) R types that we support.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15507#issuecomment-2536852441.
N/A
> fixup file type inference for untitled docs

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
- src/node/desktop/src/main/gwt-window.ts
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Due to problems building Electron 33 on focal and opensuse15 (gcc version issues) and ongoing problems getting that resolved, I'm downgrading back to Electron 31 so we can get builds while I'm working on it.
> downgrade to electron 31 due to build issues with v32 and v33

- version/news/NEWS-2024.09.0-cranberry-hibiscus.md
> Add nginx update to 1.26.0 in NEWS

- version/news/NEWS-2024.12.1-kousa-dogwood.md
Also made previous entries consistent for verb tense.
> OS PR for https://github.com/rstudio/rstudio-pro/pull/7254

- src/cpp/session/modules/SessionCodeTools.R
Addresses #10869
Update the condition 
N/A 
N/A
N/A
I signed the Contributor agreement.
> Support dev help with F1 shortcut

- src/cpp/core/include/core/system/PosixSystem.hpp
- src/cpp/core/system/PosixSystem.cpp
Adds new hook to run code after fork, before exec
Reviewed in: https://github.com/rstudio/rstudio-pro/pull/7255
> Companion to PR: https://github.com/rstudio/rstudio-pro/pull/7255

- jenkins/Jenkinsfile.macos
Speculative attempt to fix #14588
Since replaying the builds usually fixes the issue, wrap the git pull step in a retry(5), with a 5 second pause before each try.
NA
NA
NA
> Retry failed git pull in Mac jenkinsfile

- jenkins/Jenkinsfile.macos
Another attempt at solving: #14588
Following advice here: https://issues.jenkins.io/browse/JENKINS-62249?focusedId=408066&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-408066
NA
NA
> Clean keychain before pulling (MacOS jenkinsfile)

- CMakeGlobals.txt
- dependencies/common/install-packages
- dependencies/osx/install-dependencies-osx
- dependencies/osx/install-dependencies-osx-jenkins
- jenkins/Jenkinsfile.macos
- package/osx/cmake/prepare-package.cmake
- package/osx/make-package
- src/cpp/rstudio-tests.in
- src/cpp/tests/testthat/test-jobs.R
- src/gwt/CMakeLists.txt
Use Mac AMI for building chocolate cosmos.
Backported from rel-kousa-dogwood
NA
NA
NA
> Backport Mac AMI changes to chocolate cosmos

- CMakeGlobals.txt
- dependencies/common/install-packages
- dependencies/osx/install-dependencies-osx
- dependencies/osx/install-dependencies-osx-jenkins
- jenkins/Jenkinsfile.macos
- package/osx/cmake/prepare-package.cmake
- package/osx/make-package
- src/cpp/rstudio-tests.in
- src/cpp/tests/testthat/test-jobs.R
- src/gwt/CMakeLists.txt
Use Mac AMI for Desert Sunflower builds
Backported from rel-kousa-dogwood.
NA
NA
NA
> Backport Mac AMI changes to Desert Sunflower

- version/news/NEWS-2024.12.1-kousa-dogwood.md
Adds NEWs entry for rstudio/rstudio-pro#7196
> NEWS entry for secure cookie key environment variable

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses #15634
Bump electron version in `package.json`, run `npm update` then `npm i`, and verify app launches and shows correct version.
Electron unit tests passed.
Nothing to specifically test, general usage and desktop automation should cover it.
NA
> update electron to 31.7.7

- package/linux/CMakeLists.txt
Addresses https://github.com/rstudio/rstudio/issues/15442; straightforward port.
> avoid using exec_program

- version/news/NEWS-2024.12.1-kousa-dogwood.md
Add news entry for rstudio/rstudio-pro#7324
> Add news entry for rstudio/rstudio-pro#7324

- NEWS.md
- jenkins/Jenkinsfile.windows
- package/win32/make-dist-packages.bat
- package/win32/make-install-win32.bat
- package/win32/make-package.bat
Addresses https://github.com/rstudio/rstudio-pro/issues/5772, and hopefully also #15609
(I didn't list 15609 in the NEWS, I'll add that if this actually solves it)
- Extract creating setup package and zip file out of `make-package.bat` into new `make-dist-packages.bat`
- In a Jenkins-based package build, `make-package` no longer produces the setup package and zip file (but it still will in a local dev build)
- In Jenkins, after doing the compiliation via `make-package`, sign the various rstudio executables, then invoke `make-dist-packages.bat` to create the setup with the signed binaries
- Got rid of unnecessary `matrix` in Jenkinsfile.windows
The build pipeline is the automated test.
After installing RStudio, right-click on each of the following, view Properties, Digital Signatures, and …
> Sign Windows binaries

- docs/news/index.qmd
- version/news/NEWS-2024.12.0-kousa-dogwood.md
Move part of https://github.com/rstudio/rstudio-pro/pull/7230 into OS where it belongs. 
Then copy changes into the release notes' `index.qmd`. This includes an earlier change in the KD release notes as well
> …
> Update KD news and index.qmd release notes file

- version/news/NEWS-2024.12.1-kousa-dogwood.md
Add news entry for rstudio/rstudio-pro#7305 and rstudio/rstudio-pro#7248
> Add news entry for rstudio/rstudio-pro#7305 and rstudio/rstudio-pro#7248

- src/cpp/core/http/UriHandler.cpp
- src/cpp/core/include/core/http/UriHandler.hpp
- src/cpp/core/system/file_monitor/FileMonitor.cpp
- src/cpp/r/session/RBusy.cpp
- src/cpp/server/session/ServerSessionManager.cpp
- src/cpp/session/modules/SessionRParser.hpp
- src/cpp/session/modules/automation/SessionAutomation.R
- src/tools/clang-tsan-build
- src/tools/clang-ubsan-build
- src/tools/gcc-tsan-build
Doesn't address any specific issue, but fixes some sanitizer issues caught by TSAN / ASAN / UBSAN.
> resolve a couple sanitizer issues

- .github/ISSUE_TEMPLATE/1_bug_report.md
- .github/ISSUE_TEMPLATE/2_feature_request.md
- .github/pull_request_template.md
Updating templates per our retro conversations.
> update where we store qa notes

- docker/jenkins/Dockerfile.windows
Start narrowing in on why installation of msvc failed in docker.
> (Windows Docker Debugging) split download and install for aid in debugging

- src/cpp/core/include/core/http/Message.hpp
> include stdint for uintmax_t

- docker/jenkins/Dockerfile.windows
Troubleshooting Windows docker changes.
> try server 2022 base image

- NEWS.md
- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
Addresses #15460 
Upload Quarto bundles to buildtools, update constants.
No new tests.
Test all the Quarto things.
NEWS updated
> quarto 1.6.40

- cmake/compiler.cmake
- src/cpp/CMakeLists.txt
- src/cpp/ext/fmt/support/cmake/cxx14.cmake
Addresses https://github.com/rstudio/rstudio-pro/issues/7479 by enable c++17
Switches the cxx version to c++17
Build issue. All tests should continue to pass
Build issue. All tests should continue to pass
Build issue
> Enable C++17

- cmake/compiler.cmake
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a new feature, indicate why. If documentation was added in a separate PR, link the …
> Revert Windows to use C++14 again

- NEWS.md
- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
Addresses #15460
Take latest release of Quarto 1.6. This does *not* fix the issue with autocomplete in #15737 but has several other fixes.
No new tests.
Test all things Quarto.
NA
> Update to Quarto 1.6.41

- NEWS.md
- dependencies/common/install-quarto
- dependencies/tools/upload-quarto.sh
- dependencies/windows/install-dependencies.cmd
Addresses #15737
Upgrade to quarto 1.6.42 which was released specifically to fix this issue.
That's a good idea!
Test per issue.
NA
> Fix quarto autocomplete

- docs/news/index.qmd
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Add missing entry for https://github.com/rstudio/rstudio-pro/issues/7369 - we'll need to pull this into main and rerun the release notes job once this is merged
> add missing release notes item for 2024.12.1 

- NEWS.md
related to issue: https://github.com/rstudio/rstudio-pro/issues/6098
Adds release notes entry to cover "major" documentation change.
> Specify which documentation has been added or modified and why (User Guide? …
> Adding SSL documentation update to news

- NEWS.md
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a new feature, indicate why. If documentation was added in a separate PR, link the …
> News entry for rstudio-pro#7195

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update to latest Electron 34.x.
Ran BRAT tests.
General usage.
NA
> update to electron 34.3.1

- docs/news/index.qmd
> Removing headings that contain empty fields from the Workbench release notes. Relevant issue can be found here: https://github.com/rstudio/docs.rstudio.com/issues/2071
> Workbench release notes: https://docs.posit.co/ide/news/
> Remove empty headings from Workbench release notes

- src/cpp/core/CMakeLists.txt
- src/cpp/core/include/core/system/Container.hpp
- src/cpp/core/system/Container.cpp
Companion PR for rstudio/rstudio-pro#7557,
> OS companion commit for rstudio/rstudio-pro#7557

- src/node/CMakeNodeTools.txt
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a new feature, indicate why. If documentation was added in a separate PR, link the …
> fix: don't hardcode `RSTUDIO_TOOLS_ROOT`

- src/cpp/core/include/core/r_util/RSessionContext.hpp
Companion PR to https://github.com/rstudio/rstudio-pro/pull/7649
This adds `kProjectScript`. I also pulled in some other constants that look missing from the file.
> Add project script.

- cmake/compiler.cmake
- dependencies/common/install-boost
- dependencies/common/install-soci
- dependencies/tools/rstudio-tools.sh
- package/osx/make-package
- src/cpp/CMakeLists.txt
Addresses https://github.com/rstudio/rstudio/issues/15766.
Set the deployment target in our tools helper script, and use that consistently.
N/A
N/A
N/A
> update and set macOS deployment target to 12.0

- dependencies/windows/Install-RStudio-Prereqs.ps1
Keep the powershell script for bootstrapping an RStudio dev machine on WIndows in sync with recent Dockerfile changes.
Install same version of Windows SDK and also add strawberryperl (required for building some dependencies).
Tested via building
NA
NA
> sync Windows bootstrapper script with dockerfile changes

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update to electron 34.3.4 (from 34.3.3).
https://releases.electronjs.org/release/compare/v34.3.3/v34.3.4
Routine update of the electron dependency.
Ran BRAT tests (passed).
NA
NA
> electron 34.3.4

- src/cpp/server/ServerMain.cpp
Reviewed in PR: https://github.com/rstudio/rstudio-pro/pull/7456
> Miss one file in last companion

- dependencies/osx/install-dependencies-osx
- src/gwt/src/org/rstudio/studio/client/RStudio.java
- src/gwt/src/org/rstudio/studio/client/application/DesktopHooks.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
- src/node/desktop/resources/electron-entitlements.mac.plist
- src/node/desktop/src/main/application-launch.ts
- src/node/desktop/src/main/window-utils.ts
Noticed and removed some Qt-related code/comments.
> remove some obsolete Qt-related code/comments

- NEWS.md
- src/cpp/r/R/Api.R
Closes https://github.com/rstudio/rstudioapi/issues/317.
> add missing API function

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update to latest Electron 34.x (34.5.0).
Bump version, build, sanity test.
Nothing specific.
NA
> electron 34.5.0

- dependencies/common/install-panmirror
- dependencies/windows/install-panmirror/clone-quarto-repo.cmd
- docker/jenkins/Dockerfile.al2
- docker/jenkins/Dockerfile.bionic
- docker/jenkins/Dockerfile.focal
- docker/jenkins/Dockerfile.jammy
- docker/jenkins/Dockerfile.opensuse15
- docker/jenkins/Dockerfile.rhel8
- docker/jenkins/Dockerfile.rhel9
- docker/jenkins/Dockerfile.windows
Addresses #15447 
- created branch `release/rstudio-mariposa-orchid` in panmirror repo (based on current `main`)
- updated RStudio scripts to reference that branch
- opened issue: https://github.com/rstudio/rstudio/issues/15856
NA
NA
NA
> pin panmirror to mariposa-orchid branch

- NEWS.md
Should be merged after https://github.com/rstudio/rstudio-pro/pull/7772 
> Add release notes entry for rstudio-pro#7468

- NEWS.md
Add news entry for rstudio/rstudio-pro#7850
This shouldn't me merged until that PR is approved and merged.
> update news.md for positron bootstrap extensions feature

- src/cpp/session/modules/SessionRSConnect.R
> use all envvar names for deployments

- version/news/NEWS-2025.04.0-mariposa-orchid.md
Add NEWS entry for config UI and launcher conf file behavior change
> Add NEWS entry for config UI and launcher conf file behavior change

- src/cpp/core/system/LinuxResources.cpp
Addresses: https://github.com/rstudio/rstudio-pro/issues/7926
> Need to fallback to linux memory provider if memory controller is not enabled

- dependencies/common/install-panmirror
- dependencies/windows/install-panmirror/clone-quarto-repo.cmd
- docker/jenkins/Dockerfile.al2
- docker/jenkins/Dockerfile.bionic
- docker/jenkins/Dockerfile.focal
- docker/jenkins/Dockerfile.jammy
- docker/jenkins/Dockerfile.opensuse15
- docker/jenkins/Dockerfile.rhel8
- docker/jenkins/Dockerfile.rhel9
- docker/jenkins/Dockerfile.windows
Addresses #15856
Mechanical change to dockerfiles and dependency scripts.
NA
NA
NA
> pull panmirror's main branch during sandyland-bluebonnet development

- version/news/NEWS-2025.04.0-mariposa-orchid.md
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a new feature, indicate why. If documentation was added in a separate PR, link the …
> update release notes for rstudio-pro#7970

- version/news/NEWS-2025.04.0-mariposa-orchid.md
Adds audited jobs entry to MO NEWS.
> Adds NEWS entry for audited jobs

- version/news/NEWS-2025.04.0-mariposa-orchid.md
Should be merged after https://github.com/rstudio/rstudio-pro/pull/7905
NA
NA
NA
NA
NA
> Add release notes for rstudio-pro#7621

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update some build components for Electron desktop (forge and typescript).
Bumped versions in package.json, `npm update`, `npm i`, do some sanity testing including running automation.
None
None
None
> update electron-forge to 7.8.0 and TypeScript to 5.8.3

- src/cpp/core/http/Ssl.cpp
- src/cpp/core/include/core/http/Ssl.hpp
Ensure we keep the shared files consistent. I'll need to do some merging after this.
Already validated on [the pro issue](https://github.com/rstudio/rstudio-pro/issues/6813), just getting OS in sync.
> Add SSL Changes from Pro back to OS

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update to Electron 36.0.1 for Sandyland Bluebonnet. Update to #15933.
> electron-36.0.1

- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionSource.R
- src/cpp/tests/testthat/test-codetools.R
Addresses https://github.com/rstudio/rstudio/issues/5160.
Rather than rely on the `codetools` package, just iterate over the R expression ourselves and detect / handle free variables.
Included.
Test via notes in https://github.com/rstudio/rstudio/issues/5160.
N/A
> revamp for detect free vars

- cmake/globals.cmake
- src/cpp/session/SessionClientEventQueue.cpp
- src/cpp/session/SessionConsoleOutput.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/modules/rmarkdown/NotebookExec.cpp
- version/news/NEWS-2025.05.1-mariposa-orchid.md
Backport of fix for https://github.com/rstudio/rstudio/issues/15979; see that issue for details.
> Backport "avoid recursion in event handlers #15980"

- NEWS.md
NEWS entry commit to https://github.com/rstudio/rstudio-pro/pull/8151
do not merge until that has been merged
> add bugfix news entry for rstudio/rstudio-pro#8151

- docs/news/_quarto.yml
- docs/user/rstudio/_quarto.yml
Related to issue #16015 
Updating the News Guide drop-down entries since they don't point to versioned docs. There was also a 404 because of a missed link to the old User Guide URL.
Updating the IDE docs Guide drop-down to point to the Workbench Docs landing page and updating "Workbench Licenses > Licenses" for standardization across the guides.
Related PR - Workbench docs: https://github.com/rstudio/rstudio-pro/pull/8125
> Indicate whether this change includes unit tests or …
> Docs navbar links

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Continuation of #15933
Bump version, run sanity tests.
Nothing to specifically test.
NA
> Electron 36.2.1

- src/node/desktop/src/ui/widgets/choose-r.ts
- src/node/desktop/src/ui/widgets/choose-r/preload.ts
Follow-up to https://github.com/rstudio/rstudio/pull/16047.
> tweak logic around default 32bit / 64bit R install

- version/news/NEWS-2025.05.1-mariposa-orchid.md
News entry for rstudio/rstudio-pro#8127.
> Add news entry for rstudio/rstudio-pro#8127

- version/news/NEWS-2025.05.1-mariposa-orchid.md
Add news entry for rstudio/rstudio-pro#8129.
> Add news entry for rstudio/rstudio-pro#8129

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
The never-ending saga of #15933, now at 36.3.1.
> electron 36.3.1

- version/news/NEWS-2025.05.1-mariposa-orchid.md
Accidentally merged in https://github.com/rstudio/rstudio-pro/pull/8240/files
> Pull in NEWS from pro

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Addresses #16085, and also an update to #15933
Update to latest electron, which includes a fix for the directory picking issue.
None, we currently have no way to automate testing using the native file dialogs in Electron.
Test scenario in issue (or any other scenario involving picking a folder). 
NA
> update electron to fix issue with directory picking

- Dockerfile.dispatcher
Builds were failing because focal is olde now
> Update dispatcher dockerfile to ubuntu 24.04

- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.ui.xml
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeployRSConnectDeployUiBinderImplGenMessages_en.properties
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeployRSConnectDeployUiBinderImplGenMessages_fr.properties
> add french localization for a couple strings

- docs/news/_quarto.yml
- docs/user/rstudio/_quarto.yml
Related to #16075
and
blocked by/dependent upon: https://github.com/rstudio/rstudio-pro/pull/8050
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation …
> Updates license links

- src/cpp/core/include/core/r_util/RSessionContext.hpp
- src/cpp/core/r_util/RSessionContext.cpp
- src/cpp/shared_core/FilePath.cpp
- src/cpp/shared_core/include/shared_core/FilePath.hpp
Reviewed in https://github.com/rstudio/rstudio-pro/pull/8321
Includes some other RSessionContext changes that might be useful here down the road for new IDEs.
> Companion to PR for project changes in pro repo

- src/cpp/core/r_util/RSessionContext.cpp
Reviewed in: https://github.com/rstudio/rstudio-pro/pull/8359/
> Fix for last commit to this file to parse url regex

- src/cpp/session/modules/SessionPackages.R
- src/cpp/session/modules/SessionRenv.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackageInfo.java
Addresses https://github.com/rstudio/rstudio/issues/16139.
> fixes for Packages pane in renv projects

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update to latest Electron (36.5.0). #15933
> electron 36.5.0

- src/cpp/server/ServerOptions.cpp
- src/cpp/server/include/server/ServerOptions.gen.hpp
- src/cpp/server/server-options.json
See https://github.com/rstudio/rstudio-pro/pull/8422.
> open-source merge for pro pr#8422

- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/PackageLinkColumn.java
Addresses https://github.com/rstudio/rstudio-pro/issues/8363.
> include stable class name for vuln icons

- docs/news/_quarto.yml
- docs/user/rstudio/_quarto.yml
Related to #16174
Related to previously worked issue:  #15988
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a new feature, …
> Correct issue with formatting of yml where cookie icon appears twice

- src/cpp/core/Database.cpp
- src/cpp/core/include/core/Database.hpp
- src/cpp/server/ServerMain.cpp
- src/cpp/server/ServerMainOverlay.cpp
- src/cpp/server/db/make-schema.sh
- src/cpp/server_core/DatabaseUtils.cpp
- src/cpp/server_core/DatabaseUtilsOverlay.cpp
- src/cpp/server_core/ServerDatabase.cpp
- src/cpp/server_core/ServerDatabaseOverlay.cpp
- src/cpp/server_core/include/server_core/DatabaseConstants.hpp
- src/cpp/server_core/include/server_core/DatabaseUtils.hpp
- src/cpp/server_core/include/server_core/DatabaseUtilsOverlay.hpp
- src/cpp/server_core/include/server_core/ServerDatabaseOverlay.hpp
Open source companion PR for https://github.com/rstudio/rstudio-pro/pull/8476
> open source companion rstudio-pro/feature/audit-db

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
- src/node/desktop/src/main/preferences/electron-desktop-options.ts
- src/node/desktop/tsconfig.json
Addresses  #15959
Newer `electron-store` is ESM only, but our project is CommonJS.
Switching the project over would be a significant undertaking, so using this workaround. This is all just to keep Typescript happy, should have no impact on the underlying code.
No new tests, passed existing BRAT and unit tests.
> Update electron-store component

- dependencies/common/install-panmirror
- dependencies/windows/install-panmirror/clone-quarto-repo.cmd
- docker/jenkins/Dockerfile.bionic
- docker/jenkins/Dockerfile.focal
- docker/jenkins/Dockerfile.jammy
- docker/jenkins/Dockerfile.opensuse15
- docker/jenkins/Dockerfile.rhel8
- docker/jenkins/Dockerfile.rhel9
- docker/jenkins/Dockerfile.windows
Freeze the panmirror bits for upcoming release.
> pin panmirror for 2025.08 release

- src/cpp/core/include/core/system/Resources.hpp
Fixes build broken in: https://github.com/rstudio/rstudio/pull/16230
> These set methods are only in linux

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
> electron 37.2.3

- NEWS.md
- src/cpp/server/ServerMain.cpp
- src/cpp/shared_core/FilePath.cpp
- src/cpp/shared_core/include/shared_core/FilePath.hpp
Closes https://github.com/rstudio/rstudio/pull/16266.
> let RStudio find xdg-open on PATH

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/common/debugging/ui/ConsoleError.ui.xml
Addresses https://github.com/rstudio/rstudio/issues/16217.
> fix wrapping of error message text

- NEWS.md
News entries for the following issues:
- rstudio/rstudio-workbench-vscode-ext#278
- rstudio/rstudio-pro#8504
- rstudio/vscode-server#202
- rstudio/rstudio-pro#8462
- rstudio/rstudio-workbench-vscode-ext#268
> News entries for:

- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java
Addresses https://github.com/rstudio/rstudio/issues/16297.
> add unique id to repository button

- src/cpp/session/modules/SessionPPM.R
Addresses https://github.com/rstudio/rstudio/issues/16299.
> improve handling when no repository set

- docs/user/rstudio/_quarto.yml
- docs/user/rstudio/assets/_version-toast.html
Adds a version warning to the IDE user guide 
Related to issue #16334 
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a new …
> Adding "viewing X version" warning

- src/cpp/core/CMakeLists.txt
- src/cpp/ext/CMakeLists.txt
> Fix Win32 build (gtest / pthread / library issue)

- src/gwt/www/docs/keyboard.htm
Fix broken link
Find file on github and use `y` to get a permalink.
NA
This is a comment in an HTML file, not and end-user facing thing.
NA
> fix broken link in comment

- version/news/NEWS-2025.09.0-cucumberleaf-sunflower.md
OS NEWS PR for the nginx version bump: https://github.com/rstudio/rstudio-pro/pull/8992
> NEWS PR for pro PR 8992

- jenkins/Jenkinsfile.linux
Builds are broken and need fixing!
I thought the previous PR would work and I stuck around at EOD long enough to see a successful build, but it turns out that the successful build had started before I merged the PR so the success didn't prove that the change worked.
It seems that none of us realized that `if` isn't syntactically valid inside of `steps` when we were reviewing it.
I'm going to see if I can kick off a manual run against this file while it's still on the branch instead of merging it and seeing if it fails...
> fix Linux Jenkinsfile

- docs/news/index.qmd
- Removes "RStudio" from heading but adds anchor IDs to the link still has "rstudio"
- Fixed the release name + date published formatting (this is all on a single line now)
- I found a duplicated anchor and fixed that as well.
_We will need maria to add a milestone for "doc backports at some point for issue tracking_
Relates to #16433
Once merged, I am not sure what needs to happen to get this rebuilt and then merged back into main.
@adamhigerd - tagging you because you are my "patch docs" human.
> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if …
> Release notes fixes

- NEWS.md
- src/cpp/session/modules/environment/SessionEnvironment.cpp
Addresses https://github.com/rstudio/rstudio/issues/16436.
ALTREP objects can apparently contain null pointers in some cases (to my surprise). Check for these cases defensively.
Included.
Test via notes in https://github.com/rstudio/rstudio/issues/16436.
N/A
> check and handle null pointers

- NEWS.md
NEWS PR for https://github.com/rstudio/rstudio-pro/pull/9168
> NEWS PR for https://github.com/rstudio/rstudio-pro/pull/9168

- src/cpp/session/modules/automation/SessionAutomationTools.R
- src/cpp/tests/automation/testthat/test-automation-pane-layout.R
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java
Before I start mucking with it, adding some tests for the pane layout preferences UI.
I will probably add more to this, such as for the source columns and to actually verify that settings made in this dialog take effect in the main UI, but getting this part in.
> BRAT tests for the pane layout options UI

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialogConstants.java
Addresses #16474
Adjust (or create) constants. Tried to reduce (or at least consolidate) magic numbers and key off the dialog size constants.
Purely visual change, but ran BRAT tests for this just in case.
See the issue for screenshots of the fix; as it says there this should be tested in Chrome/Safari/Firefox.
NA
> Fix "Pane Layout" layout

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
- version/news/NEWS-2025.09.2-cucumberleaf-sunflower.md
Addresses #16495
Bump version, built and quick sanity testing.
> update electron to 37.6.0

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update to latest Electron (38.2.1)
bumped version, built, and ran BRAT tests
> upgrade electron to 38.2.1
