rstudio/rstudio

- jenkins/Jenkinsfile.linux
- jenkins/Jenkinsfile.macos
- jenkins/Jenkinsfile.windows
Run the Update Daily Build Redirects stage
It seems that using `env.IS_PRO` was always false since it is set as a script variable instead of an environment variable. This was causing the stage to never run.
Updated the stage condition to run if `PUBLISH` and `DAILY` are set. In addition, it updates Desktop Pro to point to Qt and open source Desktop to Electron.
none
https://dailies.rstudio.com/links/ all the daily links, pro and open source, should update to the latest build
n/a
> Set logic to run updateDailyRedirects

- NEWS.md
- src/cpp/session/modules/SessionHelp.R
Addresses #12918.
Fixes error occurring when viewing help preview for data that contains `NA` character type values.
Includes last column of data in help preview (as long as it fits).
Use the `nchar()` `keepNA = FALSE` argument to handle when the character vector contains `NA` elements. The length of `NA` (2) will be returned instead of `NA` itself.
Use `<=` in the while loop to include the last element of the formatted column data.
none
Note that the error `Error in if (nchar(current) > nchars)...` is not reproducible anymore, because the errors from session help previews were suppressed (so they won't pop up anymore).
To verify this fix, source the following code:
```R
library(data.table)
library(pillar)
StartDateTime <- as.POSIXct("2023-01-01",origin="1970-01-01")
DateTime10 <- …
```
> fix help preview error by handling `NA` values

- NEWS.md
- src/cpp/r/R/Tools.R
- src/cpp/session/modules/SessionPackages.R
Addresses https://github.com/rstudio/rstudio/issues/12946.
Use `%in%`, which handles missing values more appropriately for our use case.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/12946#issuecomment-1548429747.
N/A
> handle NA values in 'repos' option on startup

- NEWS.md
- src/cpp/session/modules/quarto/SessionQuartoPreview.cpp
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
Address #12836 
Subscribe to the quit and suspend events and stop the preview.
none
This issue only affected Windows and the change only applies to Windows. 
none
> Fix hang during R shutdown after Quarto render

- jenkins/Jenkinsfile.linux
See: https://github.com/rstudio/rstudio-pro/issues/4470
Re-enable the arm builds for Ubuntu20 Focal. 
We wish to build OS Server and OS Electron Desktop and _NOT_ OS QT Desktop. The current excludes handle this, because we already cancel the entire `Desktop` flavor from building on _any_ arm64 architecture.
Currently this will also build Pro on Focal arm64. I don't necessarily see a problem with that considering our license manager is compatible with Focal arm64, but we may want to exclude all Pro Focal arm64 builds if it struggles.
> Remove the focal exclude for building arm

- docker/jenkins/Dockerfile.bionic
- jenkins/Jenkinsfile.linux
- jenkins/Jenkinsfile.nightly
- utils.groovy
addresses rstudio/rstudio-pro#4470
companion pr: rstudio/rstudio-pro#4674
Reenable bionic builds as they're used by Debian10
Build our focal/deb10/deb11 builds on bionic still, to allow for deb 10 compatibility
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a …
> Open Source Companion for 4470 reenable bionic for debian builds

- src/cpp/core/LoggingTests.cpp
- src/cpp/core/system/Win32SystemTests.cpp
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
These tests have been failing silently for over a year in some cases. They're now suddenly reporting failure, holding up Windows builds. We should fix them, and an issue to do so is here: https://github.com/rstudio/rstudio/issues/13165
However, since these have been failing anyways for so long, and this is holding up certification, I'm disabling them now.
Additionally, Sharon provided a fix for a failing test causing the script to return `-1073741819 ` which translates to `C0000005` = `STATUS_ACCESS_VIOLATION`
> Disable failing windows tests and fix memory access violation

- src/cpp/session/modules/SessionDataImportV2.R
- src/cpp/session/modules/SessionDataViewer.R
- src/cpp/session/modules/SessionHelp.R
- src/cpp/session/modules/data/DataViewer.cpp
- src/cpp/session/resources/grid/dtviewer.js
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanel.java
Addresses https://github.com/rstudio/rstudio/issues/12964.
- Introduce a new parameter `max_rows` when viewing an object with the Data Viewer, and use this to limit the size of datasets previewed in the completion popup.
- Avoid caching datasets used for the completion popup; we don't have a well-defined place where we can clean those cached data objects up.
- Minor patch to the data viewer to pass along `max_rows`.
N/A
https://github.com/rstudio/rstudio/issues/12964
N/A
> improvements to data preview in completion

- jenkins/Jenkinsfile.nightly
Building the monitor image in the nightly dispatcher has made the jenkins job too large. So now we'll just use the same image used to build the IDE to build monitor.
Companion Pro PR here: https://github.com/rstudio/rstudio-pro/pull/4694
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present …
> Don't build monitor image

- jenkins/Jenkinsfile.nightly
The new `getDockerTag()` is defined in `utils`, which needs to be loaded within the pull-build-push stage in order for new agents to have it. This PR changes the pipeline script to load `utils` and the env vars within a script block of the pull-build-push stage. Also removes a leftover call to `dockerTag()` function.
> bugfix/load utils for build-pull-push agents

- dependencies/common/install-panmirror
- dependencies/windows/install-panmirror/clone-quarto-repo.cmd
- docker/jenkins/Dockerfile.bionic
- docker/jenkins/Dockerfile.centos7
- docker/jenkins/Dockerfile.focal
- docker/jenkins/Dockerfile.jammy
- docker/jenkins/Dockerfile.opensuse15
- docker/jenkins/Dockerfile.rhel8
- docker/jenkins/Dockerfile.rhel9
- docker/jenkins/Dockerfile.windows
Address #13131 
Partly, this is required to trigger another nightly build but it also updates the Docker image cachebust. It has been updated to check the `release/rstudio-mountain-hydrangea` branch.
Also, the git revision is logged so it'll be easier to check the Docker image build logs to see which changes have been included. This will be useful once the code is switched back to `main` from `release/rstudio-mountain-hydrangea`.
none
none 
none
> Update panmirror cachebust

- jenkins/Jenkinsfile.windows
Fix Windows daily redirect
It was doubling up the base URL to S3. It just needs to pass the flavour and platform for the AWS S3 path.
none
none
none
> Fix Windows daily redirect

- src/node/desktop/src/main/utils.ts
- src/node/desktop/test/unit/main/utils.test.ts
open source companion to rstudio/rstudio-pro#4718 (already reviewed)
Util function that:
1. retrieves an env var we expect to be set to a numeric value
2. if the value is in fact a number, we return it as a `number`
3. if the value is not a number, then we return `undefined`
2  unit tests added
> add `getNumericEnvVar` util function and tests

- src/cpp/core/system/PosixGroup.cpp
- src/cpp/core/system/PosixSystem.cpp
and cleanup error handling for getting all of a user's groups
(reviewed in https://github.com/rstudio/rstudio-pro/pull/4647)
> Avoid calling 'get group' on all of a user's groups for userBelongsToGroup

- src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants_fr.properties
- src/gwt/src/org/rstudio/studio/client/workbench/commands/CmdConstants_fr.properties
This is not directly related to rstudio/rstudio-pro#4494 but it's a few strings related to the crash RStudio action. The translation is not really necessary but will be a simpler diff result when running `locdiff`. The action is only for diagnostic use.
Add fr strings to properties file
none
none
none
> Add new fr strings

- src/cpp/core/include/core/http/AsyncClient.hpp
Addresses: https://github.com/rstudio/rstudio-pro/issues/4764
Prepare is the way to tell the streambuf how much to read from the socket by default. Is 8K the right value?  I might have chosen larger but noticed nginx uses 4K. 
Covered by automation for regressions.  
Would be nice to compare download latency for > 100K downloads. You can do this with developer tools on the IDE or VS code and just look for the largest static js files downloaded. 
Use strace on rserver or other processes to check the value of the size parameter to recvfrom.
> Increase read buffer size from 512 to 8192

- NEWS.md
- src/cpp/session/modules/SessionDataViewer.R
Addresses #13188.
avoids hitting the following error:
```
Error in exists(cacheKey, where = .rs.WorkingDataEnv, inherits = FALSE) : 
invalid first argument
Error in assign(cacheKey, frame, .rs.CachedDataEnv) : 
attempt to use zero-length variable name
```
Backport issue: https://github.com/rstudio/rstudio/issues/13241
Wraps usages of `cacheKey` in `SessionDataViewer.R` with a zero-length check.
In particular, the usage in `assignCachedData` was problematic (causing #13188).
none
[Simplest repro steps](https://github.com/rstudio/rstudio/issues/13188#issuecomment-1589910695):
1. create a dataframe (any # rows/columns) eg. `df <- data.frame(matrix(rnorm(1), nrow=1, ncol=1))`
2. trigger autocomplete: type `df` + tab key
3. try to reassign the same variable eg. `df <- 'hi'`
4. see error
none …
> wrap `cacheKey` usages with zero length check

- src/cpp/session/resources/terminal/bash/.bash_profile
- version/news/NEWS-2023.06.1-mountain-hydrangea.md
Reverts rstudio/rstudio#13246 Probably moving to 2023.06.02 patch
> Revert "Backport/4584"

- src/gwt/www/expired.htm
OS-PR for: https://github.com/rstudio/rstudio-pro/issues/4776
~I think this should merge over without any conflicts with the pro repo, since the lines unique to each file -- name / logo differences between OS Server and Workbench -- were not modified directly.~ This will need a follow-up PR on pro to re-word, following the changes made in this PR.
Update the expired link to no longer reference rstudio.com -- point people to our support line instead
> Update license expired page - OS

- src/cpp/shared_core/system/Crypto.cpp
Addresses:  https://github.com/rstudio/rstudio-pro/issues/4757
> Avoid crash for empty input string in base64 decode

- src/cpp/core/system/PosixChildProcess.cpp
The Package Manager team[ initially noticed this](https://positpbc.slack.com/archives/C7312LBPY/p1663804027257349) when the Kubernetes Launcher plugin would hang indefinitely but never exit. @jeffvroom has [also found the symptoms of this](https://positpbc.slack.com/archives/C7312LBPY/p1677121768420139?thread_ts=1677023476.856099&cid=C7312LBPY) in some customer logs.
We already "force" an exit event after 30 seconds, this commit just piggybacks on that timer to send it `SIGKILL` at that point as well.
I don't think there are tests for this.
Please advise.
N/A
> Send `SIGKILL` to child processes during forced exit to avoid zombies

- src/cpp/session/modules/SessionDataViewer.R
Attempt to fix rsession-tests that are crashing
> Hoping to avoid deparse by not calling length on language objects

- src/cpp/session/modules/data/DataViewer.cpp
Backports
https://github.com/rstudio/rstudio/pull/13253 for #13188
Addresses
- #13241
Cherry-picked from `main`.
none
simplest repro: https://github.com/rstudio/rstudio/issues/13188#issuecomment-1595212093
none
~- [] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md`~ 
> Backport don't cache viewed datasets that lack a cache key

- NEWS.md
- src/cpp/session/modules/SessionDataViewer.R
- src/cpp/session/modules/SessionHelp.R
- src/cpp/session/modules/data/DataViewer.cpp
- src/cpp/session/resources/grid/dtviewer.js
- src/cpp/tests/testthat/test-dataviewer.R
- src/gwt/src/org/rstudio/studio/client/dataviewer/DataTable.java
Address #13220 
This will be backported to MH as part of https://github.com/rstudio/rstudio/issues/13244.
- only retrieve data for the visible slice of column data, not the entire data frame (helps us avoid slow loading for large data sets)
- search for `getColSlice`, `describeColSlice`
- separate the usage of `max_cols` and `max_display_columns` to avoid the confusing mixed usage
- `max_cols`/`maxCols` is for specifying the maximum number of columns we want to retrieve from a data frame
- e.g. sometimes we only want the first 100 columns, to avoid slow loading with large data sets
- `max_display_columns`/`maxDisplayColumns` is the maximum number of columns to display in a view of the data frame (in autocomplete/help or in the data viewer) and the user preference …
> fix data viewer column navigation bug

- NEWS.md
- src/cpp/session/SessionConsoleProcessInfo.cpp
- src/cpp/session/SessionConsoleProcessInfoTests.cpp
Address https://github.com/rstudio/rstudio-pro/issues/4027
Resolve the symlink when converting the process info to json. The symlink check will return the target and handles the case if `FilePath` isn't a symlink (returns itself).
Added a unit test to convert a `ConsoleProcessInfo` to json and back. The restored `cwd` should match the original when resolving the symlink.
The terminal should have the directory changed to something else. When the terminal fails to change to the current working directory on session resume, it would be in the same directory as opening a new terminal.
The terminal doesn't attempt to restore the working directory until the pane is shown for the first time after resuming the session.
none
> Fix setting working directory on session resume

- src/cpp/session/resources/grid/dtviewer.js
Follow-up fix to #13270 to address #13220
Backport issue: https://github.com/rstudio/rstudio/issues/13244
In #13270, we switched our data viewer approach to load and display only the visible slice of columns, instead of loading all of the columns in the data frame and then using the column offset to limit the view. With that change, we removed code that sets `window.dataTableColumnOffset`, since it seemed no longer relevant to the new approach.
However, the "jquery datatable magic" still has usages of this variable, and not setting it meant that we'd get `NaN` in places where we expect numeric values. This resulted in the column sorting no longer working.
To avoid doing a refactor of the jquery code, we can simply set `window.dataTableColumnOffset = 0` to prevent creating `NaN` values, …
> fix broken column sorting in data viewer

- src/cpp/session/modules/SessionDataViewer.R
- src/cpp/session/modules/SessionHelp.R
- src/cpp/session/modules/data/DataViewer.cpp
- src/cpp/session/resources/grid/dtviewer.js
- src/cpp/tests/testthat/test-dataviewer.R
- src/gwt/src/org/rstudio/studio/client/dataviewer/DataTable.java
- version/news/NEWS-2023.06.1-mountain-hydrangea.md
- Backports #13270 and #13275 for #13220
- Addresses #13244
Cherry-picked from `main`. Moved NEWS.md entry to the patch NEWS.md file.
WIP by QA team
Repro steps
- https://github.com/rstudio/rstudio/issues/13220#issuecomment-1602847194
none
> Backport data viewer column navigation bugfix

- src/cpp/core/include/core/http/TcpIpSocketUtils.hpp
Addresses https://github.com/rstudio/rstudio/issues/13272.
Set `FD_CLOEXEC` on socket handles after creation. Note that this PR changes this setting for _all_ sockets; are there any cases where this is _not_ the desired behaviour?
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13272.
N/A
> make sure socket handles aren't inherited

- src/cpp/rstudio-tests.in
CPP tests running on `aarch64` machines are not locating `libSegFault.so` because we haven't included the path in the locations we try to search. "WARNING: Could not find libSegFault.so"
This file is not necessary for our tests to run successfully, but if a seg fault occurs during a test and this file is not located by the tests, we will not be able to view detailed information about the failure.
On `aarch64` machines, `libSegFault` is located at `/lib/aarch64-linux-gnu/libSegFault.so` (if it is installed). Include this path in the list of locations we search.
none
- CPP tests on aarch64 machines that have libSegFault.so installed should no longer echo "WARNING: Could not find libSegFault.so" in the test output
none
~- [ ] If this PR adds a new feature, or fixes a bug in a previously …
> add `aarch64` `libSegFault.so` path

- jenkins/Jenkinsfile.hourly
- jenkins/Jenkinsfile.nightly
Increment the MH patch version to `.2` now that we've released the `.1` patch.
Update nightly and hourly Jenkinsfiles with the new patch version `2`.
none
new MH builds should now use the `.2` patch suffix instead of `.1`.
none
~- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md`~ 
~- [ ] This PR passes all local unit tests~
> Increment `RSTUDIO_VERSION_PATCH` to 2

- docs/news/index.qmd
Update release notes for IDE / Workbench 2023.06.1+524.pro1 release.
This change has been generated by the release script. Content is generated based on `version/news/NEWS-2023.06.1-mountain-hydrangea.md`. If this file was not in sync with Pro or did not include items from other sources (i.e. the vscode extension), then some items may be missing.  Please verify content/formatting is correct and make changes if necessary.
> Update release notes for 2023.06.1+524.pro1

- src/cpp/core/FileSerializer.cpp
- src/cpp/core/http/Util.cpp
- src/cpp/core/include/core/FileSerializer.hpp
- src/cpp/core/include/core/r_util/RActiveSessionStorage.hpp
- src/cpp/core/include/core/r_util/RActiveSessions.hpp
- src/cpp/core/r_util/RActiveSessionStorage.cpp
- src/cpp/core/r_util/RActiveSessions.cpp
Addresses part of https://github.com/rstudio/rstudio-pro/issues/4746 and 
part of https://github.com/rstudio/rstudio-pro/issues/4085
* Don't create the session directory as part of creating the storage object as this implicitly creates a session that's not valid just by looking to see if a session exists with a given id. We don't ordinarily do that in OS but for workbench, that happens occasionally for rworkspaces and that causes a delay while that session is determined to be invalid. 
* Don't use ensureDirectory for the properties directory on each property access. This adds overhead and improperly creates a session just by trying to read a property from it. Instead, catch the "no such file or directory" error when trying to write the first property and create the directory at that …
> Speedup and bugfix for rsession metadata

- src/cpp/core/system/PosixSystem.cpp
- src/cpp/server/ServerMain.cpp
- src/cpp/server/ServerOptions.cpp
- src/cpp/server/session/ServerSessionMetadataRpc.cpp
- src/cpp/server/session/ServerSessionProxy.cpp
- src/cpp/server/session/ServerSessionRpc.cpp
Make sure all getUser passwd entry database lookup calls use the cached api 
Addresses https://github.com/rstudio/rstudio-pro/issues/4800
- in processInfo call for looking up process owner (main issue)
- at startup time for the server-user
- session metadata rpc for authorizing metadata lookups
- for authorizing server session rpc requests
- for authorizing local stream requests authenticated by a uid
Found the rest of the places we make these getUserFromIdentifier calls and replaced them with the cached equivalent: either getUserFromUserId or getUserFromUsername. 
All of these code paths will be tested by automation. I don't think manual testing is necessary.
> Use cached api to lookup users in several more places

- src/node/desktop/src/main/context-menu.ts
- src/node/desktop/src/main/desktop-browser-window.ts
Address #13336 
The Electron 25.2.0 update stopped giving the `sender` in the context menu event. When the context menu is about to be displayed, it now needs the web contents to be retrieved from the window to build the action.
n/a
This should also fix issues with saving/copying images from the Plot pane. Also, this should work with editors that are pulled out into its own window.
n/a
> Fix context menu actions using webContents

- src/cpp/session/modules/data/DataViewer.cpp
- src/cpp/session/resources/grid/dtviewer.js
Addresses https://github.com/rstudio/rstudio/issues/13328.
We made some recent changes to the Data Viewer, such that only the data actually presented to the user is sent over the wire. This necessitated a number of changes to how column offsets were handled both on the server + client side. It looks like we might've missed a couple spots around sorting / filtering, and also in displaying column titles.
N/A
Test that sorting + filtering work even in paginated tables, when paginating to later columns. Here's an example to play with:
```
.rs.writeUiPref("data_viewer_max_columns", 15L)
data <- replicate(100, 0:9, simplify = FALSE)
for (i in seq_along(data)) {
data[[i]] <- (data[[i]] + i) %% 10
}
names(data) <- paste0("V", 1:100)
df <- as.data.frame(data)
View(df)
```
N/A
> fix a variety of sorting / filtering issues

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
Addresses: #13347 
Backport issue: #13351
- Ensure we initialize the `ignoredUpdates_` object
- Only run code to "ignore update" if we haven't already ignored the update
none
I will create custom builds so we can test this (because the dailies/hourlies are considered "up to date" already, and won't trigger the Update Available dialog).
The first released version we can test this in will be Desert Sunflower, as long as we backport this to the 2023.06.2 release.
none
`- [ ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)`
> Fix update available ignored update error

- src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
Addresses
- rstudio/rstudio-pro#4832
This is for pro electron. This menu item is already hidden in open source.
| current | this PR |
| ------- | -------- |
| <img width="300" alt="image" src="https://github.com/rstudio/rstudio/assets/25834218/6b79c35b-26d6-4e71-954e-320d2ee97b8a"> | <img width="300" alt="image" src="https://github.com/rstudio/rstudio/assets/25834218/dbcf264b-3e86-4016-bf1c-2eed43e69a39"> |
- only add the menu item for non-electron desktop IDE
none
no additional notes
already done in rstudio/rstudio-pro#4629
> remove connection status toolbar from electron

- src/node/desktop/src/main/utils.ts
- src/node/desktop/test/unit/main/utils.test.ts
Backports
- https://github.com/rstudio/rstudio/pull/13195
For
- rstudio/rstudio-pro#4732
Cherry-picked the commit. No merge conflicts. 
see #13195
see #13195
see #13195
> add `getNumericEnvVar` util function and tests (#13195)

- jenkins/Jenkinsfile.nightly
This PR fixes a race condition in the jenkins nightly pipeline where the `DOCKER_TAG` and `DOCKER_FILE` variables were defined as global variables, so parallel builds in the build matrix may end up using the values from another build cell, causing incorrect build images to be produced. See [this build](https://build.posit.it/job/IDE/job/OS-Builds/job/nightly-pipeline/job/main/328/pipeline-console/?selected-node=129) as an example of when this occurred.
Related to this Jenkins issue: …
> Fix race condition in build image pipeline

- src/cpp/core/system/PosixSystem.cpp
- src/cpp/session/SessionConsoleProcess.cpp
- src/cpp/session/SessionConsoleProcessInfoTests.cpp
Address rstudio/rstudio-pro#4027
Checking that the path exists prevents saving a bad path after the process has exited. The cwd poll happens often enough that it tried to update the cwd after the process exited.
Also, set the test to run on Linux only.
n/a
This fixes the first session suspend where it updated the cwd after the session exited. Subsequent session suspends will save the cwd properly and was fixed by https://github.com/rstudio/rstudio/pull/13268
n/a
> Fix cwd on first session suspend

- src/cpp/server/session/ServerSessionManager.cpp
- src/cpp/server/session/ServerSessionProxy.cpp
Addresses: https://github.com/rstudio/rstudio/issues/13369
Removes a recently added error that shows up during restart session process. The IDE sends a get_environment_state request right after the message to restart which will always generate an error and remove the pending launch. This eliminates the error part of the bug only.
Reproduces easily in server version.  See issue for details.
> Don't log pending launch errors for handleRpcError and handleContentError

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishDocServicePage.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishFilesPage.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishMultiplePage.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishReportSourcePage.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectAccountList.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeployDialog.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectPublishWizard.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PublishingPreferencesPane.java
Addresses [#12204](https://github.com/rstudio/rstudio/issues/12204)
Followup to publishing work in [rstudio/rstudio-pro#4541](https://github.com/rstudio/rstudio-pro/issues/4541)
when the user chooses a publishing service in PublishDocServicePage, that should get passed through to RSConnectAccountList via setPublishSource, so we can add some new params and check their values to filter the account list
Also fix a couple of outstanding bugs where we kind of ignore the global preferences for Connect enabled/Cloud enabled in the account list
No
Should be tested as part of the testing process for rstudio/rstudio-pro#4541
> filter accounts publishing

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/application/ApplicationUtils.java
- src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
- src/gwt/test/org/rstudio/studio/client/application/ApplicationUtilsTests.java
- `+` is used in the YYYY.MM.PATCH+COMMITS format since Ghost Orchid and `-` is used in the MAJOR.MINOR.X-Y format in Juliet Rose
- neither of these characters `+` / `-` are accounted for in the version comparison, so the numeric comparison fails
In the session log, the following error would show:
```
ERROR CLIENT EXCEPTION (rsession): For input string: "1+524";|||rstudio-0.js#-1::new zve|||com/google/gwt/emul/java/lang/Number.java#207::__parseAndValidateInt|||org/rstudio/studio/client/application/ApplicationUtils.java#45::compareVersions|||org/rstudio/studio/client/application/IgnoredUpdates.java#36::addIgnoredUpdate|||org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java#231::addIgnoredUpdate|||org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.j …
```
> fix bug in `compareVersions()` string splitting

- src/cpp/session/modules/SessionEnvironment.R
Currently, the IDE will silently trigger a python exception, overwriting `reticulate::py_last_error()`. This occurs while the IDE is introspecting the R session to determine if the session is suspendable. The `isSuspendalImpl` function already has an early check for reticulate objects, but it is too narrow currently, missing callable python objects that present in the R session as R functions, not R environments. 
update the check 
```r
if (is.environment(x) && inherits(x, "python.builtin.object))`
```
to
```r 
if (is.environment(value) || is.function(value)) && value, "python.builtin.object")
```
> identify callable python objects from reticulate as not suspendable

- src/gwt/src/org/rstudio/studio/client/application/ApplicationUtils.java
- src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
- src/gwt/test/org/rstudio/studio/client/application/ApplicationUtilsTests.java
- version/news/NEWS-2023.06.2-mountain-hydrangea.md
- Backports PR: #13386
- Main Issue: #13379 
- Backport Issue: #13380 
Cherry-picked the commit. Resolved NEWS merge conflict.
see #13386
When a release newer than 2023.06.2 is available (i.e. Desert Sunflower), we will be able to verify this fix in 2023.06.2. We may be able to verify this using the Desert Sunflower dailies?
none
> fix bug in `compareVersions()` string splitting (#13386)

- src/cpp/core/system/PosixSystem.cpp
- src/cpp/session/SessionConsoleProcess.cpp
- src/cpp/session/SessionConsoleProcessInfo.cpp
- src/cpp/session/SessionConsoleProcessInfoTests.cpp
- version/news/NEWS-2023.06.2-mountain-hydrangea.md
Address #13251 
Cherry picked commits
Updated readme for patch 2
n/a
none 
n/a
> Backport  for 4027 - terminal resume current working directory

- docker/jenkins/notarize-release.sh
Address #11863 
Change `notarize-release.sh` to call `notarytool`. Added the `team-id` option as it is now required. The id does not need to be private.
The command uses the `--progress` and `--wait` options so there is no need to poll the notarization service for updates.
When there is a team Apple ID account, the Jenkins credentials can be updated along with the new `team-id`.
Successfully built here: https://build.posit.it/job/IDE/job/OS-Builds/job/Platforms/job/macos-pipeline/job/macos-notarytool/3/
None. 
n/a
> Switch from altool to notarytool

- git_hooks/hooks/pre-commit
Fixes `✖ No valid configuration found.` error that arises when this pre-commit hook is run, but you're committing to a version of the project that doesn't have lint-staged set up (eg. when committing to the `rel-cherry-blossom` branch).
Check that `./src/node/desktop/.lintstagedrc` exists before running `lint-staged`. This file doesn't exist in some branches, so committing can fail.
none
Anyone using the `pre-commit` hooks should run `set-up-git-hooks` again to get this change, or copy the updated `pre-commit` hook changes to your `.git/hooks` directory. See `git_hooks/README.md` for instructions.
none
~- [ ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md`~ 
~- [ ] If this PR adds or changes UI, the updated UI meets …
> skip pre-commit hook if lint-staged not present

- src/cpp/session/modules/SessionRCompletions.R
- Addresses part of https://github.com/rstudio/rstudio/issues/13196
- Reverted commit 6786f041d98d214c4ed89f81aa45ef04c043ca95
none
When viewing the autocompletion / help for an R function that has a triple ellipses parameter `...`, a user should see the `...` parameter in the completions list and view the help text associated with it.
Steps
- `dplyr::left_join(` + tab
- `...` should show in the completion list as seen in the screenshot above
Note that the user will be able to "select" the `...` parameter which inserts `... = ` into their code. Although this is invalid code, we don't currently have a way to show completions/help text while also disabling the code insert when the completion is selected. See discussion in #13196 for more context.
none
~- [] If this PR adds or changes UI, …
> Re-enable completions for ellipses `...` parameter

- docker/jenkins/Dockerfile.rhel9
Adresses rhel9 build failures on all branches during the Build & Sign stage.
<details><summary>Error</summary>
<p>
```
2023-07-25 17:50:22  Buildfile: /tmp/jenkins-d32a18b1/workspace/IDE/Pro-Builds/Platforms/linux-pipeline/main/src/gwt/build.xml
2023-07-25 17:50:22  Caught an exception while logging the end of the build.  Exception was:
2023-07-25 17:50:22  java.lang.NoClassDefFoundError: Could not initialize class sun.util.calendar.ZoneInfoFile
2023-07-25 17:50:22  	at java.base/sun.util.calendar.ZoneInfo.getTimeZone(ZoneInfo.java:588)
2023-07-25 17:50:22  	at java.base/java.util.TimeZone.getTimeZone(TimeZone.java:577)
2023-07-25 17:50:22  	at java.base/java.util.TimeZone.setDefaultZone(TimeZone.java:682)
2023-07-25 17:50:22  	at …
```
> install tzdata-java in rhel9 dockerfile

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionGit.cpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/common/vcs/GitServerOperations.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_fr.properties
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPresenter.java
Address #1865 
Add a checkbox to the commit dialog to sign the commit. If the option is enabled, the commit cli call will add the git flag to sign the commit.
n/a
The commit dialog has a checkbox to sign commits. The user must have a GPG key already added to their key store and configured in git. `git config --global user.sigingkey <gpg key id>`. The git dialog will display an error if there is no signing key present when committing.
The docs will need an update to mention the option to sign commits.
> gpg signed commits

- NEWS.md
- src/cpp/r/session/REmbeddedWin32.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/tests/testthat/test-translations.R
Addresses https://github.com/rstudio/rstudio/issues/10308.
R uses [libintl](https://github.com/wch/r-source/tree/trunk/src/extra/intl) for message translation. The default domain for translations is "messages", but R normally tries to set the default domain to "R" here:
https://github.com/wch/r-source/blob/e3d6c3fdd8666ae96bee913e1c0edab7bbaa088d/src/main/main.c#L737
And that only gets called in a few places, e.g.
https://github.com/wch/r-source/blob/e3d6c3fdd8666ae96bee913e1c0edab7bbaa088d/src/gnuwin32/system.c#L1073
So we need to make sure to call `::cmdlineoptions()` so that the default text domain is set. Note that we previously had to avoid using this function as R would crash on startup when we tried to call this, but this issue has now been alleviated by virtue of the invalid …
> ensure default translation domain is set on startup

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/common/debugging/ui/ConsoleError.ui.xml
Addresses #13239.
Straightforward CSS update to ensure whitespace is preserved.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13239.
N/A
> preserve whitespace in error message text

- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanelBinderImplGenMessages_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanelBinderImplGenMessages_fr.properties
Address feedback for #1865 
Places the signing option in the section directly related to the commit. Add translated string for the option.
n/a
The option now appears under the commit message text area
none
> Move git sign commit option

- src/cpp/session/modules/SessionDataViewer.R
I encountered this somewhat puzzlingly just now:
```
Error in exists(cacheKey, where = .rs.CachedDataEnv, inherits = FALSE) : 
invalid first argument
Error in if (maxRows != -1 && nrow(data) > maxRows) data <- head(data,  : 
missing value where TRUE/FALSE needed
```
This PR addresses the latter error. It could conceivably be obviated by debugging the first error, but I'm clueless on that for now and this PR seems benign enough.
RStudio version info:
```
RStudio
2023.06.0 Build 421
© 2009-2023 Posit Software, PBC
"Mountain Hydrangea" Release (583b465e, 2023-06-06) for Ubuntu Focal
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) rstudio/2023.06.0+421 Chrome/110.0.5481.208 Electron/23.3.0 Safari/537.36
```
> Guard against missing edge case

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Address #13448 
Gets whitespace fix from semver 7.5.2 by upgrading semver explicitly. Nothing that we do depends directly on this package. It's pulled in because of Electron.
n/a
No functional changes from taking this newer package
n/a
> Upgrade semver package

- src/cpp/session/modules/NotebookPlots.R
- src/cpp/session/modules/rmarkdown/NotebookPlotReplay.cpp
Follow-up to https://github.com/rstudio/rstudio/issues/4330.
Instead of hard-coding the set of packages, try to infer what packages are required based on the registered S3 methods for makeContent and makeContext.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/4330.
N/A
> improve detection of required plotting packages

- jenkins/Jenkinsfile.hourly
- jenkins/Jenkinsfile.nightly
Need FORCE_BUILD=true for nightly builds but don't want to force docker rebuilds in that case so adding a new flag.
> Add separate flag to force docker step

- NEWS.md
- src/cpp/session/CMakeLists.txt
- src/gwt/CMakeLists.txt
Address rstudio/rstudio-pro#4943
Add exclude rules for cmake install. A separate PR will handle the part of the package that is pro only. https://github.com/rstudio/rstudio-pro/pull/4966
n/a
The package should not include `.gitignore` at all. This includes all platforms since any common parts like Quarto or GWT would have this unnecessary file included.
n/a
> Fix package build

- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java
Addresses https://github.com/rstudio/rstudio/issues/7287.
Adds a preference to allow users to control whether or not the R workspace is saved and reloaded when building a package.
N/A
Test that, when building an R package, R objects in the workspace are not saved when this preference is unset:
N/A
> add pref controlling whether workspace is saved / loaded on build

- NEWS.md
- src/cpp/session/modules/SessionRCompletions.R
Addresses https://github.com/rstudio/rstudio/issues/12577.
RStudio tries to determine whether an object can be successfully queried for column names, but was too restrictive in how it did so. This PR allows `tbl` objects to also be queried for table names.
For reference, all dplyr tables inherit from `tbl` as a "base" class; e.g. using the original issue's example:
```
> class(tbl)
[1] "tbl_SQLiteConnection" "tbl_dbi"              "tbl_sql"              "tbl_lazy"             "tbl"
```
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/12577.
N/A
> support DBI tbl objects for autocompletions

- src/cpp/r/RSexp.cpp
- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionRParser.cpp
Addresses https://github.com/rstudio/rstudio/issues/13512.
Since `dplyr::mutate.data.frame` uses `dplyr_quosures` for quasi-quotation and tidy evaluation, add that to our NSE primitives list.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13512.
N/A
> turn off symbol diagnostics in mutate()

- NEWS.md
- src/node/desktop/src/main/session-launcher.ts
Addresses https://github.com/rstudio/rstudio/issues/13085.
macOS SIP disallows inheritance of certain environment variables -- `DYLD_FALLBACK_LIBRARY_PATH` is one example. We need to explicitly forward it when launching the `rsession` for it to be visible.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13085.
N/A
> explicitly forward DYLD_FALLBACK_LIBRARY_PATH

- NEWS.md
- src/cpp/session/modules/SessionEnvironment.R
Addresses https://github.com/rstudio/rstudio/issues/13489.
RStudio somewhat eagerly tries to check if the session can be safely suspended, via `.rs.environment.isSuspendable()`. Unfortunately, this check is expensive for large `igraph` objects. Since we know a priori that such objects can be safely serialized, we skip recursing into their internals.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13489.
N/A
> igraph objects can be safely serialized

- src/cpp/session/modules/SessionReticulate.R
On startup, the IDE will attempt to infer what what Python installation reticulate would select to load.
Part of this inference routine may involve launching a subprocess that calls `reticulate::py_discover_config()`. 
`reticulate::py_discover_config()` may raise warnings or errors if it encounters a python installation that would be preferred, but is broken for some reason (e.g., a virtual environment where the python installation it is derived from has been removed).
The intent of this PR is to not present those warnings or errors to the user as part of the IDE session startup routine. In that context they are not actionable, and the text of the warning can be occasionally cryptic. 
The user will may still encounter the same error message if/when they attempt to use Python via …
> silence warning/errors from infering reticulate python

- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/session/modules/environment/SessionEnvironment.cpp
Addresses https://github.com/rstudio/rstudio/issues/13540.
When computing the dimensions for an R `data.frame`, check whether the `row.names` attribute is an ALTREP vector. If it is, then use ALTREP APIs for querying information about it.
N/A
Will be verified by duckdb users.
N/A
> avoid materializing duckdb data.frame rownames

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceTheme.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
Addresses https://github.com/rstudio/rstudio/issues/13532. As a side effect, we get a shiny new display for Ace annotations.
Ace now queries some information about the active theme via the `editor.renderer.theme` property when displaying different pieces of UI. To ensure that RStudio is compatible with those usages, we make sure to set that property when a theme is set or changed.
Note that we intentionally bypass the Ace APIs for setting themes and just set the theme object directly, as we manage Ace themes ourselves.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13532.
N/A
> ensure Ace theme property set when theme applied

- src/cpp/session/modules/quarto/SessionQuarto.cpp
- src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
- src/gwt/src/org/rstudio/studio/client/common/dependencies/model/Dependency.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/RSConnect.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/model/QmdPublishDetails.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PublishingPreferencesPane.java
Addresses https://github.com/rstudio/rstudio/issues/13555.
Wire in some special handling for publishing of Quarto manuscripts, and explicitly require rsconnect 1.0.2 in that scenario.
N/A
Test that publication of Quarto manuscripts (and only manuscripts!) requires rsconnect 1.0.2. All other publications should still require only rsconnect 0.8.24.
N/A
> require rsconnect 1.0.2 for publishing Quarto manuscripts

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
Addresses https://github.com/rstudio/rstudio/issues/13532.
Ensure that Ace is made aware of the current theme when Ace instances are created.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13532#issuecomment-1695930685.
N/A
> track and apply current theme on creation

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AceEditorPreview.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AceEditorPreview.js
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.R
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Addresses https://github.com/rstudio/rstudio/issues/13552.
Newer versions of Ace now try to apply a Textmate theme by default. We need to remove that theme from the preview when Ace is loaded.
I also tried to use a somewhat more relatable code example for the preview pane. We now show an R function computing the [five-number summary](https://en.wikipedia.org/wiki/Five-number_summary) of a vector, which is a basic and common set of descriptive statistics that almost everyone will be familiar with.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13552.
N/A
> remove textmate theme from Ace preview

- src/gwt/src/org/rstudio/studio/client/rsconnect/model/RSConnectPublishSource.java
Addresses #13535
Follow repro in issue, publish to Cloud, ensure that all pages load without 404. Download source and inspect manifest.json and ensure `"content_category": "site"` has been set.
> fix 404 site category bug for Rmd website publishing

- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/acesupport/acemode/auto_brace_insert.js
- src/gwt/acesupport/loader.js
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionPopupPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/PopupPositioner.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCopilotHelper.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceGhostText.java
Addresses https://github.com/rstudio/rstudio/issues/13446.
This PR gives the user some options controlling how GitHub Copilot's code suggestions will live + work together with the existing autocompletion system.
The intention here is that, for users who'd still like to get as-you-type autocompletions, they can enable the preference, and then when a user is in this state:
they can still use Tab to insert the Copilot code suggestion, rather than the selected completion from the list. (The Enter key can be used to insert that completion.)
> Add additional information for QA on how …
> allow user to control behavior of autocomplete + Tab key

- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/copilot/server/CopilotServerOperations.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCopilotHelper.java
Addresses https://github.com/rstudio/rstudio/issues/13547.
This PR adds a preference that controls whether RStudio will index project files with GitHub Copilot. When enabled, RStudio will tell GitHub Copilot about these files, which should (theoretically) allow it to provide better code suggestions within that project.
N/A
N/A
N/A
> allow indexing of project source files with copilot

- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/common/filetypes/CodeBrowserType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/EditableFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Addresses https://github.com/rstudio/rstudio/issues/13543.
Event handlers attached through the global EventBus are never automatically released, unless we use the three-argument `addHandler()` call. Make use of those in TextEditingTarget.
N/A
N/A
N/A
> ensure event handlers are cleaned up on detach

- src/cpp/session/modules/SessionHelp.cpp
- src/node/desktop/src/main/desktop-browser-window.ts
Addresses https://github.com/rstudio/rstudio/issues/13392.
R's help server makes use of redirects in some scenarios. For those cases, we need to re-write the Location header so that the Help requests are made to our Help proxy rather than the R help server directly.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13392. This code only affects redirects, which are somewhat rare for the help server, but I think it would be worth testing https://github.com/rstudio/rstudio/issues/13263 in a variety of scenarios.
N/A
> fix up handling of Help pane redirects

- src/node/desktop/.eslintrc.js
- src/node/desktop/src/core/expected.ts
- src/node/desktop/src/main/i18n-manager.ts
- src/node/desktop/src/main/menu-callback.ts
- src/node/desktop/src/main/modal-dialog-tracker.ts
- src/node/desktop/src/main/toolbar-manager.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/src/ui/connect/connect.ts
- src/node/desktop/src/ui/error/error.ts
- src/node/desktop/src/ui/loading/loading.ts
- src/node/desktop/src/ui/widgets/choose-r/load.ts
- src/node/desktop/src/ui/widgets/choose-r/preload.ts
- src/node/desktop/test/unit/main/context-menu.test.ts
Addresses: https://github.com/rstudio/rstudio/issues/13597
- remove or replace usages of `@typescript-eslint/no-implicit-any-catch` with the appropriate variable type or an alternative eslint rule applicable to the situation, such as `@typescript-eslint/no-explicit-any`
- fix up any linting errors by adding eslint annotations
none
Running the linter on the desktop typescript files should no longer output any errors.
```
cd src/node/desktop
npm run lint
```
none
> fix up eslint errors

- src/cpp/core/include/core/Log.hpp
- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/shared_core/Logger.cpp
- src/cpp/shared_core/include/shared_core/Logger.hpp
Addresses https://github.com/rstudio/rstudio/issues/13411.
Previously, we were logging all Copilot errors to the R console to make development simpler. This PR changes that so logging to the console only happens when one has explicitly opted in to Copilot debugging.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13411.
N/A
> don't log copilot errors to console by default

- src/gwt/src/org/rstudio/core/client/widget/SelectWidget.java
Addresses a regression tracked by https://github.com/rstudio/rstudio-pro/issues/4965. Working with a null string was causing GWT to crash and not complete the request for a new session.
Not including a NEWS.md entry since the regression happened during DS development
This was caught by automated tests
N/A
N/A
> Add null check to widget label

- NEWS.md
OS PR for https://github.com/rstudio/rstudio-pro/pull/5078
Update and format NEWS.md to be consistent with last release (how repos are labeled)
> OS PR for rstudio/rstudio-pro/pull/5078 - update NEWS

- src/cpp/core/include/core/r_util/RProjectFile.hpp
- src/cpp/core/r_util/RProjectFile.cpp
- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/session/projects/SessionProjectContext.cpp
- src/cpp/session/projects/SessionProjects.cpp
- src/gwt/src/org/rstudio/core/client/StringUtil.java
- src/gwt/src/org/rstudio/studio/client/projects/model/RProjectConfig.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPreferencesDialog.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/YesNoAskDefault.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/ProjectCopilotPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/events/CopilotEnabledEvent.java
Addresses https://github.com/rstudio/rstudio/issues/13580.
Introduces project-specific options for enabling Copilot, and also for project indexing. These are encoded into the project's `.Rproj` file, and so are set for all users of the project. (The intention being that some projects might not be appropriate to use with Copilot for any user.)
The UI here is somewhat duplicated from the Global Options version. To avoid confusion, if Copilot has been disabled in project-specific settings, we also display that in the global options.
N/A
N/A
N/A
> add copilot project-specific preferences

- src/cpp/session/modules/SessionRSConnect.cpp
- src/cpp/session/resources/dependencies/r-packages.json
Quarto Manuscripts, even when published statically, can include `qmd` files, which are included as downloadable source for qmd files which provided embedded plots, tables, or other resources for the manuscript. Prior to this change, when publishing to Connect, the presence of these `qmd` files would lead Connect to attempt to render the document (even for a static publish). 
This change uses a new argument in deployApp which allows us to specify that static manuscript publishes should be treated completely statically.
- This requires the most recent version of the reconnect package which is not yet published to CRAN
- Once published to CRAN, I will update package dependencies for RStudio to reflect that version
- A simple project which shows the behavior is attached …
> force appMode to 'static' for Quarto manuscript projects

- src/cpp/r/R/Api.R
- src/cpp/session/CMakeLists.txt
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionPackageProvidedExtension.R
- src/cpp/session/modules/SessionPackageProvidedExtension.cpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/events/RStudioApiRequestEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
Addresses https://github.com/rstudio/rstudio/issues/13278.
This PR adds two pieces:
1. An API for setting ghost text in a document;
2. A mechanism to allow R code to listen for document changes.
The second mechanism feels a bit dangerous, but this doesn't add anything that packages couldn't already do since package authors can already see files on the user's filesystem, and also view and modify text buffers in RStudio via functions in `rstudioapi`.
N/A
N/A; to be verified by community.
N/A
> expose document change events for package extensions

- package/osx/make-package
mac builds are still failing on `main`, and only on `main`. The installer disk image seems to run out of space
```bash
[2023-09-12T16:45:47.726Z] [I] Creating 'RStudio-2023.12.0-hourly-8.dmg ...'
[2023-09-12T16:46:03.310Z] could not access /Volumes/RStudio-2023.12.0-hourly-8/RStudio.app/Contents/Frameworks/Electron Framework.framework/Versions/A/Electron Framework - No space left on devicehdiutil: create failed - No space left on device
```
This is an attempt to fix that following what we did last time, though I'm not sure why other branches are okay. It seems to only affect electron builds, as [non-electron flavour](https://build.posit.it/blue/organizations/jenkins/IDE%2FPro-Builds%2FPlatforms%2Fmacos-pipeline/detail/main/445/pipeline) seems to build okay.
> Fix no space left on disk creating dmg

- src/cpp/core/r_util/RProjectFile.cpp
- src/cpp/session/SessionClientInit.cpp
- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/include/session/projects/SessionProjects.hpp
- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/session/projects/SessionProjectContext.cpp
- src/cpp/session/projects/SessionProjects.cpp
- src/gwt/src/org/rstudio/studio/client/projects/model/RProjectConfig.java
- src/gwt/src/org/rstudio/studio/client/projects/model/RProjectCopilotOptions.java
- src/gwt/src/org/rstudio/studio/client/projects/model/RProjectOptions.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPreferencesDialog.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/ProjectCopilotPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/events/ProjectOptionsChangedEvent.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/copilot/Copilot.java
- src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCopilotHelper.java
Addresses https://github.com/rstudio/rstudio/issues/13635.
Rather than serialize the Copilot project options as part of the project file, we instead serialize them to their own settings file within the `.Rproj.user` state folder. While there are a lot of changes required to make this happen, the changes are relatively straightforward.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13635. In particular, confirm that the `.Rproj` file is not updated when changing these project options.
N/A
> use private settings location for copilot settings

- src/cpp/session/modules/SessionPackages.R
Allow to visualize dev help automatically. Addresses #13460 
Before this PR: 
1. run devtools::document() in a package
2. Click on the link displayed in the console to the package
3. Press Enter to display dev help
**This PR suppresses step 3** of the workflow**
Add pkgload to allowed packages to automatic packages that can be run.  https://cli.r-lib.org/reference/links.html?q=usethis#security-considerations
When clicking on the output, it should run automatically, without having to press enter
After checking, I saw that clickable hyperlinks are not in RStudio User Guide.
Will open a PR in cli to update this page. https://cli.r-lib.org/reference/links.html?q=usethis#security-considerations
Edit: another way to do this would be to have devtools export this function and roxygen2 adding an …
> Allow pkgload links to run automatically

- dependencies/windows/install-boost/install-boost.R
- src/cpp/generate-options.R
Found during an exploratory {lintr} search: https://github.com/r-lib/lintr/issues/2183
Took a guess at what belongs in `%s`, PTAL to confirm.
> sprintf_linter() fixes

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
Addresses https://github.com/rstudio/rstudio/issues/13657.
Ensure that user preferences are loaded when the session is initialized.
As to why this change is needed... my only guess is that something changed with the order that GWT is trying to initialize some of the static / singleton classes we have, and now we're ending up in a state where the UserPrefs class is being initialized before the preferences are actually available, since the constructor seems to assume the preferences are already available:
https://github.com/rstudio/rstudio/blob/8f63e7b629740429f07d6683bdb9e13331f92f5a/src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java#L72-L75
There's an (unfortunately implicit) contract that anything which wants to make use of certain elements like user preferences …
> ensure satellite prefs are sync'ed on init

- src/cpp/session/modules/SessionPackages.R
Addresses #13460 
Visualize development pkgdown site in package development more easily.
Same as #13561 
None.
No longer to have pkgdown loaded to run links automatically.
I will create a PR for this in the cli documentation in time for the next RStudio release.
I have signed the Contributor agreement.
> Allow pkgdown links to run automatically.

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
Addresses https://github.com/rstudio/rstudio/issues/13662.
Because `_` is used for keyboard accelerators in the menu, we need to escape literal `_` in strings before applying it to the menu.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13662.
N/A
> fix menu mnenomics

- CMakeLists.txt
- package/osx/cmake/prepare-package.cmake
- src/CMakeLists.txt
- src/cpp/CMakeLists.txt
- src/cpp/desktop/CMakeLists.txt
- src/gwt/CMakeLists.txt
- src/node/CMakeLists.txt
- src/node/desktop/CMakeLists.txt
Part of https://github.com/rstudio/rstudio/issues/13577.
This is a fairly conservative change, since we already install a fairly new version of CMake where required:
https://github.com/rstudio/rstudio/blob/b7f159d0a210b1215f12a4786c6d900c53f8771a/package/linux/install-dependencies#L20-L37
> update minimum required CMake version

- src/cpp/session/SessionConsoleInput.cpp
- src/cpp/session/SessionHttpMethods.cpp
- src/cpp/session/SessionSuspend.cpp
- src/cpp/session/include/session/SessionSuspend.hpp
Addresses: https://github.com/rstudio/rstudio/issues/13534
Split the checkForSuspend method into two pieces:
1) run before processing each request (like today) to check for explicit suspension - it only
calls allowSuspend if the user requested suspension
2) another that's run to check for idle suspension that's run periodically.
The rsession waitForMethod, poll handler has a 50ms timeout for background processing while waiting for r console input.  Only if 20 of these go by now do we check for an idle session (i.e. 1/second).
Are there scenario where console input is being processed and we need to allow suspension?  Could use a timer here but trying to avoid extra system calls since this is an inner loop for running R code.
Or we could a check in the offline polling thread so it's done …
> Reduce number of calls to canSuspend/allowSuspend

- NEWS.md
- src/cpp/r/include/r/session/RGraphics.hpp
- src/cpp/session/modules/SessionFiles.cpp
- src/cpp/session/modules/SessionPlots.cpp
Addresses https://github.com/rstudio/rstudio/issues/13387.
When rendering plots for preview / display, use the display device pixel ratio in more scenarios. Note that on a high DPI display, these plots will generally be larger.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13387.
N/A
> use display DPI when rendering plots in more scenarios

- NEWS.md
- src/cpp/session/modules/SessionHelp.R
- src/cpp/session/modules/SessionRCompletions.R
Addresses https://github.com/rstudio/rstudio/issues/13526.
Adds some detours for help documentation generated by `devtools` / `pkgload`, for packages loaded via `devtools::load_all()`.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13526.
N/A
> support dev docs

- NEWS.md
- src/cpp/session/modules/SessionRmdNotebook.R
- src/cpp/session/modules/rmarkdown/NotebookQueueUnit.cpp
- src/cpp/session/modules/rmarkdown/NotebookQueueUnit.hpp
- src/gwt/src/org/rstudio/studio/client/rmarkdown/model/NotebookQueueUnit.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/NotebookQueueState.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/DocUpdateSentinel.java
Addresses https://github.com/rstudio/rstudio/issues/13326.
Addresses https://github.com/rstudio/rstudio/issues/13240.
Addresses https://github.com/rstudio/rstudio/issues/13525.
Addresses https://github.com/rstudio/rstudio/issues/13636.
Previously, we used a rather ad-hoc heuristic to try and guess whether inline chunk options were YAML or R code. This PR takes a more permissive approach, whereby we first attempt to parse the code as YAML, and then fall back to R code if that fails.
For reference, the associated knitr code: https://github.com/yihui/knitr/blob/768db6f45525e15399724451df4153e900461e12/R/parser.R#L301-L312
N/A
To be tested via community.
N/A
> tweak detection of YAML chunk options in R Markdown documents

- src/gwt/src/org/rstudio/studio/client/common/spelling/domain_specific_words.csv
This quick change adds the world "multivariable" to the list of domain-specific words RStudio accepts. Inspired by https://mastodon.online/@sims@fosstodon.org/111126223668522084.
> Add 'multivariable' as a domain specific word

- src/cpp/session/SessionConsoleInput.cpp
- src/cpp/session/SessionConsoleInput.hpp
- src/cpp/session/SessionOfflineService.cpp
Addresses: https://github.com/rstudio/rstudio-pro/issues/4922
In Posit Workbench, updating the 'executing' metadata property causes a file system write. If that happens too frequently it causes performance issues, especially with some customers that have network file systems that limit the number of writes to a file per second. 
In this PR the rate of writes it not controlled by the number of console-input statements but instead limited to a few times a second. The transition to the executing state happens right away, but the transition from executing to idle happens in the offline service at no more than 4X second, so no more than 8X/second.
I don't think we have any automated tests for the 'executing' state so that might be worth doing?  
Capture an strace of the rsession while running …
> Limit rate of writes to 'executing' property metadata

- docs/news/index.qmd
- jenkins/Jenkinsfile.hourly
- jenkins/Jenkinsfile.nightly
- version/news/NEWS-2023.09.0-desert-sunflower.md
Update release notes for IDE / Workbench 2023.09.0+463.pro11 release.
This change has been generated by the release script. Content is generated based on `version/news/NEWS-2023.09.0-desert-sunflower.md`. If this file was not in sync with Pro or did not include items from other sources (i.e. the vscode extension), then some items may be missing.  Please verify content/formatting is correct and make changes if necessary.
> Update release notes for 2023.09.0+463.pro11

- src/cpp/core/zlib/zlib.cpp
When `zconf.h` was removed in rstudio/rstudio#13641, it revealed an issue with the way we are including `zlib.h` in our `zlib.cpp` wrapper. We only want to use the local zlib.h if zlib is not installed on the system. This should only happen on Windows as we only build the embedded zlib _for_ Windows.
Otherwise, we were essentially including the local `zlib.h` file, even though the actual definitions would be defined by the system library (and in the case of centos7, was actually incompatible).
> Describe the approach taken and the tradeoffs involved if non-obvious; add an overview of the solution if it's …
> Prefer system zlib.h over local

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionPopupPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanel.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
Addresses https://github.com/rstudio/rstudio/issues/13674.
https://github.com/rstudio/rstudio/assets/1976582/4c25e56b-b644-4ded-b839-86911da26e6a
We had two pieces of code that tried to dismiss the Help popup:
1. Whenever the editor instance lost focus;
2. Whenever the click target was outside of the presented popups.
(1) was too aggressive, so it has been removed; (2) evidently was not functioning as intended, and so was fixed. In addition, now that users can interact with the Help text, we now display the appropriate mouse cursor.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13674.
N/A
> don't dismiss autocomplete target when clicking help text

- src/cpp/core/LoggingTests.cpp
- src/cpp/core/include/core/Log.hpp
- src/cpp/core/system/System.cpp
- src/cpp/shared_core/Logger.cpp
- src/cpp/shared_core/include/shared_core/ILogDestination.hpp
- src/cpp/shared_core/include/shared_core/Logger.hpp
Addresses: https://github.com/rstudio/rstudio-pro/issues/5095
Speedup for LOG_DEBUG_MESSAGE macro
Apis need by an admin page (in development) to turn on/off logging in workbench. 
Don't evaluate message unless debugging is enabled.  The macro now uses a ? operator to hide the logDebugMessage call while still making a valid statement.  I tried a few ways to do this and this turned out to be the only one that's robust inside of if/else statements.
Apis to get/set log level for file/stderr destinations
Exposed name to LogLevel mapping for an upcoming rserver admin to change levels on the fly
No new automation required. 
* With this fix, turning on "Session protocol debug" in a session should enable debug logging in ~/.local/share/rstudio/log/rsession-username.log.  
* Debug logging should be …
> Fix issue with session protocol debug

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
Addresses #13710
Due to other changes, the previous approach for checking the state of the screen reader flag at startup was no longer getting the current value (I believe it was getting the default value). This code is responsible for deciding if it should announce "screen reader not enabled" and for setting the menu text.
Code that checks the pref later was getting the correct value, hence the mismatches.
There was a second symptom of this problem, also related to accessibility. The "tab key moves focus" toggle (Help / Accessibility / Focus / Tab Key Always Moves Focus) was also not showing the correct state (via a checkmark).
Fixed by moving that startup code to the end of onSessionInit at which point preferences are happy.
None that I'm aware of; it would be nice to have a test to …
> fix "screen reader mode" toggle and "tab key always moves focus" toggle

- src/gwt/src/org/rstudio/studio/client/projects/Projects.java
The problem is that RStudio allows you to set a default project location, and it respects that location for Project|New, but it ignores it for Project|Open
I mentioned this previously in #12514 - although I think I choose the wrong code links and title there.
It was also previously requested in https://community.rstudio.com/t/change-default-location-for-open-project/41130 - Posit employee @kevinushey answered there that people should change their Home path...
I've copied the prefs code from project new to project open.
This preference is technically currently only for the NewProject wizard... and I think it is only settable by creating a new project - https://github.com/rstudio/rstudio/blob/e76b763f05f9934e4e10b178506c31cf49e99500/src/gwt/src/org/rstudio/studio/client/projects/Projects.jav …
> use default project folder for open project dialog

- NEWS.md
- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionEnvironment.R
Addresses https://github.com/rstudio/rstudio/issues/13719.
R uses so-called source references to record the origin of a function within an R session. This data structure records both the file name (as the user-requested path to the file), and the working directory used when the file was sourced. Because of this, we need to be careful when resolving the file path from a source reference; in particular, we need to take that recorded working directory into account.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13719.
N/A
> ensure paths are normalized when debugging

- src/node/desktop/src/main/detect-r.ts
Addresses (part of) https://github.com/rstudio/rstudio/issues/12585
On Desktop, with Electron, we use R to determine the value of `LD_LIBRARY_PATH` (and the Mac equivalent), which appends a user-defined environment variable to the end of the path generated by R. This is inconsistent with the behavior on Server/Workbench. There have been some other inconsistencies noted by QA, but they are not addressed here
See  https://github.com/rstudio/rstudio/issues/12585. We would like to get the same value in the Terminal and in the Console, and in server products and desktop products.
> prepend user-defined LD_LIBRARY_PATH var instead of appending to the end

- src/cpp/session/modules/SessionRMarkdown.R
Addresses https://github.com/rstudio/rstudio-pro/issues/5227.
The R `yaml` package attempts to conform to the YAML 1.1 specification, and chooses to emit `yes` and `no` for logical values. YAML 1.2 requires these constants to instead be called `true` and `false`. Since these constants are also recognized by YAML 1.1, we just choose to always emit `true` and `false` for logical vectors.
N/A
Test via notes in https://github.com/rstudio/rstudio-pro/issues/5227.
N/A
> prefer 'true' and 'false' for logical YAML values

- NEWS.md
- src/cpp/session/modules/quarto/SessionQuarto.cpp
Addresses #13637
We basically had two checks for locating metadata for (parts of) a Quarto book, manuscript, or website. One was looking at the output of `quarto inspect`, and the other was looking at the `_quarto.yml` file, which we locate by [looking for any config file in a parent of the target file](https://github.com/rstudio/rstudio/blob/b52a4c2ef54937226aec5c0d4c66b9810d0ce435/src/cpp/session/modules/quarto/SessionQuarto.cpp#L273-L299) until we get to the user's home. But we only actually use the metadata we get from the `_quarto.yml` file. And we don't need to be at the root of the quarto project in order to publish it. So this check basically seems to only throw unnecessary errors? 
I can publish both the standalone `about.qmd` file by itself, or the root `index.qmd` file and …
> Permit standalone Quarto file publishing non-root of project

- NEWS.md
- src/cpp/session/modules/SessionRmdNotebook.R
- src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.cpp
Addresses https://github.com/rstudio/rstudio/issues/13187.
- Make sure the `png` figure extension is set for chunks, since `knitr` seems to set that by default.
- Since the `dot` engine returns the path to an image file, treat the return value as an image.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13187.
N/A
> handle execution of 'dot' engine chunks

- src/cpp/session/projects/SessionProjects.cpp
Addresses https://github.com/rstudio/rstudio/issues/13757.
Unfortunately, this PR removed code it shouldn't have:
https://github.com/rstudio/rstudio/pull/13638/files#diff-5b7b325564515068ea9e8a5a18e1bee5cabf087aae172bf1f7fe9778a5883f65L721
This effectively means attempts to update project options won't have any effect. This PR adds it back in.
N/A
N/A
N/A
> ensure project file is written when updating project options

- src/cpp/session/resources/dependencies/r-packages.json
Addresses https://github.com/rstudio/rstudio/issues/9861.
The `markdown` package is no longer required by the `rmarkdown` package, so we removed it.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/9861.
N/A
> rmarkdown no longer requires markdown

- jenkins/Jenkinsfile.linux
- jenkins/Jenkinsfile.macos
- jenkins/Jenkinsfile.windows
The daily redirects for Desktop Pro on https://dailies.rstudio.com/links/#rstudio-desktop-pro-daily point to Qt builds, but should point to Electron RDP builds.
Use Electron for both open-source and RDP when updating daily links.
N/A
Test daily RDP downloads from that page and confirm they are Electron-based, not Qt-based.
N/A
> use Electron RDP for daily redirects

- src/gwt/src/org/rstudio/studio/client/application/Application.java
Addresses https://github.com/rstudio/rstudio-pro/issues/5093 (Desktop Pro, but entire fix is in open-source code).
Remove this command in Electron RDP but leave it alone for Qt RDP.
N/A
Check that the Session Server Settings command is gone in Electron RDP (under the Session menu and in the command palette). For bonus points, also check that it's still in Qt RDP.
N/A
> hide show session settings command in Electron RDP

- jenkins/Jenkinsfile.linux
Backport https://github.com/rstudio/rstudio/pull/12941 to unblock cherry-blossom builds.
Disable unit tests on opensuse15.
The underlying problem is that opensuse15 leap 15.3 installs R 3.5, which is too old for the `testthat` package to install.
We hope to be able to resume running the tests (for `main`, at least) once we do https://github.com/rstudio/rstudio/issues/13777 (assuming newer opensuse15 leap installs a newer R...).
N/A
N/A
N/A
> disable tests on opensuse15 for rel-cherry-blossom

- version/news/NEWS-2023.09.1-desert-sunflower.md
Update news to include details about the Copilot Preview that users can opt into for RStudio Desktop in 2023.09.1
> Update news to mention Copilot Preview in RStudio Desktop

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetPrefsHelper.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
Addresses #13593 and #7337
Ace has a flag that needs to be turned on for screen reader users. This change keeps that flag in sync with the IDE's "screen reader" mode flag.
Turning this on improves screen reader support for the editor, including better announcements of content as you navigate around a document.
It also enables a feature where hitting the ESC key moves focus outside the editor surface, allowing a keyboard-only user to break out of the inherent keyboard trap and use Tab to move elsewhere.
It also enables the ability to interact with controls in the editor gutter region such as expanding/collapsing regions of code, but that isn't quite working (something specific to the IDE, it works on the Ace kitchen sink). I will open a separate issue on that (#13787).
Finally, Ace now has …
> keep Ace's enableKeyboardAccessibility flag in sync with IDE's screen reader mode

- dependencies/common/install-packages
- docker/jenkins/Dockerfile.bionic
Trying out a couple potential fixes for Docker Build failures on `bionic` and `opensuse`.
We'll need to bring these changes into the `main` branch and any other branches that might rebuild the docker images.
> Fix bionic and opensuse builds

- docker/jenkins/Dockerfile.bionic
We don't need the `ppa` repo because bionic repos have `openjdk-8` now:
```
root@f806b68ea8c8:/# apt policy openjdk-8-jdk
openjdk-8-jdk:
Installed: (none)
Candidate: 8u372-ga~us1-0ubuntu1~18.04
Version table:
8u372-ga~us1-0ubuntu1~18.04 500
500 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages
500 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages
8u162-b12-1 500
500 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
```
> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be covered …
> Remove ppa repo that's no longer needed

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
Addresses #13789. 
See https://github.com/rstudio/rstudio-ace/commit/013ba30d29d8363d37e32f5e41593af902411d69 and https://github.com/rstudio/rstudio-ace/commit/d67ce4a80241a7a5ba75ee07a76ac5aa459ba6bb 
for the change that introduced this rename. 
QA testing details added to issue
> use renamed autocompletion options for threshold and delay

- src/cpp/session/modules/SessionEnvironment.R
Address #13799 
In PR #13723, we tried to get the value of `srcfile$wd` even before we knew we needed it, raising unnecessary errors in cases where `srcfile$filename` contains the absolute path and `srcfile$wd` is unset, which raises errors and makes it look like the debugger couldn't find the source code even when it did
> don't create wd until we know we actually need it

- src/cpp/session/modules/SessionRmdNotebook.R
Addresses the rest of https://github.com/rstudio/rstudio/issues/13240 including some regressions introduced in #13653 
Sorry for all the IDE whitespace changes, the changes are basically limited to L741-L755 and L804-L815 
Basically needed to test that all of the following in-body chunk option styles work when executing chunks inline:
~~~~
---
---
```{r setup-db}
library(DBI)
db = dbConnect(RSQLite::SQLite(), dbname = "sql.sqlite")
```
```{sql dash-and-yaml}
--| connection: db
SELECT 'test'
```
```{sql hash-and-yaml}
#| connection: db
SELECT 'test'
```
```{sql dash-and-equals}
--| connection=db
SELECT 'test'
```
```{sql dash-and-equals}
#| connection=db
SELECT 'test'
```
~~~~
Also checked that the following still works
~~~~
---
---
```{r setup} …
```
> add fixes to parsing of in-body chunk options in various styles

- NEWS.md
- src/cpp/session/modules/SessionGit.cpp
Address #9798
Remove using `master` as upstream branch. If this fails to get the upstream branch name then fallback to using the last commit id for the file. This would provide a url to the exact state of the file.
One case would still fail if the file has a commit that doesn't exist on the remote. Maybe it is better to always use `HEAD` as the branch name instead of the commit id? However, the commit id has the advantage of showing the exact state as seen in RStudio.
The repo url retrieval was changed to use `ls-remote` so that it doesn't need to query by the upstream name. This command was introduced in `git@1.7.5`.
none
The one case this would still fail is making a change to a file and committing it. Do not push the commit and try to use the view on github action. The commit doesn't …
> Fix constructing github url for file

- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
- src/gwt/build.xml
- src/gwt/src/org/rstudio/studio/client/panmirror/ui/PanmirrorUIContext.java
- src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RMarkdownServerOperations.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ImagePreviewer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModePanmirrorContext.java
Addresses https://github.com/rstudio/rstudio/issues/12690.
Adds the necessary callback for handling base64 image data. We take the base64 clipboard data, then write that to disk and return the resolved path.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/12690.
N/A
> add necessary callback for handling base64 images

- NEWS.md
- src/cpp/session/SessionConsoleProcess.cpp
- src/cpp/session/include/session/SessionConsoleProcess.hpp
- src/cpp/session/include/session/SessionTerminalShell.hpp
- src/cpp/session/modules/SessionTerminalShell.cpp
Addresses https://github.com/rstudio/rstudio/issues/13809.
- On macOS, `/bin/bash --login --posix` does not respect the `ENV` environment variable, so we have no choice but to use a non-login shell. Made this a macOS-only change just to avoid fallout in Workbench installations.
- Instead of using the opaque "Custom" shell type for custom shells, try to guess if the Shell is instead Bash or Zsh or another shell we provide specific support for.
We also use a slightly more portable prompt command for Bash. In my shells, it seems like `~` needs to be escaped in replacements, e.g.
```
$ NAME=kevin; echo ${NAME/kevin/~}
/Users/kevin
$ NAME=kevin; echo ${NAME/kevin/\~}
~
```
but because I don't know what affects this (Bash version? some other shell option?) I figure it's best to skirt the issue …
> fix handling of shell startup scripts on macOS with default Bash

- NEWS.md
- src/cpp/session/modules/tex/SessionPdfLatex.cpp
Currently we only support `pdflatex` and `xelatex` for compiling Rnw documents; `lualatex` should also be supported: https://tex.stackexchange.com/a/419885/9128
Simply adding `LuaLaTeX` to the array.
I think the change is simple and obvious enough.
Currently this `.Rnw` document won't compile in RStudio:
```
% !TeX program = LuaLaTeX
\documentclass{article}
\begin{document}
Test.
\end{document}
```
After this change, it will.
> Support LuaLaTeX for compiling Sweave (Rnw) documents

- dependencies/windows/Install-RStudio-Prereqs.ps1
- docker/jenkins/Dockerfile.windows
Fix Windows build node-gyp failures with error `ModuleNotFoundError: No module named 'distutils'`.
- [Python 3.12](https://docs.python.org/3/whatsnew/3.12.html) was just released on Oct 2 and deprecated `distutils` with [PEP 632](https://peps.python.org/pep-0632/)
- we don't pin our version of Python, so our containers are using 3.12 now
- node-gyp depends on distutils and now errors when running with Python 3.12
- node-gyp is [working on fixing the issue for Windows](https://github.com/nodejs/node-gyp/issues/2869)
Pin Python to 3.11 until the node-gyp issue is fixed.
- Will merge up to the MH, DS and main branches once the Windows build for CB passes
- Will open an issue to unpin our Python version once the node-gyp issue is fixed.
> pin Windows python to 3.11

- src/cpp/session/modules/quarto/SessionQuarto.cpp
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
- src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RMarkdownServerOperations.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModePanmirrorContext.java
Follows up on https://github.com/rstudio/rstudio/issues/12690.
Always use relative paths to the Quarto resource directory.
Also fixes an issue that could prevent previewing a rendered Quarto document if the project directory itself is non-canonical, e.g. the canonical path != canonical path.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/12690.
N/A
> always use relative paths for Quarto images

- src/cpp/r/RJson.cpp
- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/modules/SessionCopilot.R
- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/session/modules/SessionRMarkdown.R
- src/cpp/session/session-options.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.java
Allow Workbench system administrators to set a Copilot proxy URL for requests.
> allow administrators to set a proxy URL for Copilot

- NEWS.md
- src/cpp/session/prefs/UserPrefsLayer.cpp
Addresses #12974
Background: When saving user preferences fails due to permissions issues we show a custom error message, added in https://github.com/rstudio/rstudio/pull/7742.
However, if the folder containing the preferences file doesn't allow checking existence of the file (e.g. folder is owned by a different user and doesn't allow "anybody" access), we show a generic "File Not Found" error.
Show the custom error message even if we weren't able to detect whether the file exists.
Not aware of any.
To test this, you'll need to do something like:
```
chmod 0700 ~/.config/rstudio
chown ~/.config/rstudio SomeOtherUser
```
Then load RStudio and try to change and save a user preference via the options dialog. 
N/A
> show custom error message when prefs save fails even if file is completely unreachable

- NEWS.md
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/native/desktop.node.d.ts
- src/node/desktop/src/native/desktop/desktop.cc
Addresses https://github.com/rstudio/rstudio/issues/13835.
~Addresses https://github.com/rstudio/rstudio/issues/12467~ EDIT: Nope, that appears to affect macOS; this PR targets Windows only.
`shell.openExternal()` does not appear to handle Unicode paths correctly. Work around this the old fashioned way -- convert the path to a so-called "short" path name, and use that path instead.
N/A
Test via notes in the associated issues.
N/A
> handle non-ASCII characters in openExternal

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/node/desktop/envvars.bat
Addresses https://github.com/rstudio/rstudio/issues/13118.
We normally try to respect preference changes for editor instances here:
https://github.com/rstudio/rstudio/blob/main/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetPrefsHelper.java#L128-L132
However, this only applies to Ace instances in the Source pane; not in the Console pane. This PR makes sure we apply the preference for Ace instances in the Console as well.
N/A
N/A
N/A
> respect color preview pref in console

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.ui.xml
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeployRSConnectDeployUiBinderImplGenMessages_en.properties
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectPublishButton.java
Addresses https://github.com/rstudio/rstudio/issues/12707.
Always rebuild the publish button after attempting a deployment, even on failure. This is necessary because the user might've successfully (and intentionally) picked a particular deployment target, but saw that their deployment failed because of an error in the published code / document.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/12707.
N/A
> update publish list even on failure

- NEWS.md
- src/cpp/r/include/r/session/RConsoleActions.hpp
- src/cpp/r/session/RConsoleActions.cpp
Addresses https://github.com/rstudio/rstudio/issues/13857.
This PR adjust how we handle buffering of console outputs for console actions, which is used to populate the Console history when a suspended session is restored.
In particular, this PR makes a couple of changes:
1. We maintain a single `action_` action, which is used to accumulate outputs of the same type (imagine: lots of output fired into `stdout`);
2. As output is produced, we commit chunks of the `action_` buffer into the circular buffers that host the actual Console history.
This approach ensures that we always properly chunk console outputs, and avoids issues where a single-fire gigantic output was not properly chunked when committing that file to disk.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13857. …
> improve chunking / buffering of console actions

- src/cpp/core/Database.cpp
- src/cpp/server_core/ServerDatabase.cpp
Reviewed in PR: https://github.com/rstudio/rstudio-pro/pull/5211
- Max of 6 db connections. Plenty of parallel db activity for the limited uses and avoids overflow
- Better error when failing to populate connection pool
- Fixed typo in config option
> Tweaks to database config.

- NEWS.md
- src/cpp/core/include/core/FileSerializer.hpp
- src/cpp/session/modules/rmarkdown/NotebookCache.cpp
Addresses #13860.
Avoid treating an already-existing migration file as an error -- such files can exist if an R Markdown document is saved multiple times while a document is running.
N/A
N/A
N/A
> always overwrite chunk migration files

- src/cpp/core/include/core/system/Xdg.hpp
- src/cpp/core/system/Xdg.cpp
- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/13878.
With this PR, the XDG cache directory is computed as a directory within the user's LocalAppData directory.
N/A
N/A
N/A
> tweak location of XDG cache for Windows

- src/cpp/session/modules/quarto/SessionQuartoJob.cpp
- src/cpp/session/modules/quarto/SessionQuartoJob.hpp
- src/cpp/session/modules/quarto/SessionQuartoPreview.cpp
Addresses https://github.com/rstudio/rstudio/issues/13876.
This helps make it more clear what was actually executed, in the scenario where an error occurs.
> display executed command for Quarto jobs

- NEWS.md
- src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
- src/gwt/src/org/rstudio/core/client/widget/FastSelectTable.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/history/view/HistoryPane.css
Addresses https://github.com/rstudio/rstudio/issues/3219.
We have a custom GWT implementation called FastSelectTable governing the behavior of the table displayed in the History pane. Unfortunately, the extra customization around focus handling prevents copy from working in the default way.
This PR implements a custom copy handler that allows the table to handle copy events, in the case that it has focus and the user has selected one or more rows of data.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/3219.
N/A
> allow copy of text from History pane

- src/cpp/session/modules/data/DataViewer.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/DataViewChangedEvent.java
Addresses https://github.com/rstudio/rstudio/issues/13856.
This PR removes some logic that tried to transition views from Data Viewer => Object Explorer, when the associated type of the underlying object changed. The old implementation appeared to be overly-sensitive to changes in the underlying object's type.
We could consider adding this back in the future, but given that this is a relatively painful bug, I felt it was worth fixing.
N/A
N/A
N/A
> tweak how changes in viewed data are detected

- src/gwt/acesupport/acemode/r_code_model.js
Addresses https://github.com/rstudio/rstudio/issues/13831.
A recent PR enabled highlighting for YAML chunk options. Unfortunately, this interfered with some older code which expected the YAML text contents to be left tokenized as part of a comment.
This PR alleviates the issue by just pulling out the whole line for the matched token, rather than by looking at the token value.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13831.
N/A
> fix parsing of YAML chunk labels

- src/gwt/src/org/rstudio/core/client/files/filedialog/FileDialogStyles.css
- src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.css
Addresses https://github.com/rstudio/rstudio/issues/13895.
Update `.modalDialog` CSS.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13895.
N/A
> use clip overflow for modal dialogs

- src/cpp/session/modules/SessionCopilot.R
Addresses https://github.com/rstudio/rstudio/issues/13746.
Check the `TAR` environment variable; if it's set to an invalid `tar` executable, then try to find it ourselves on the PATH.
N/A
To test, try the following:
```
Sys.setenv(TAR = "/no/such/tar")
```
Then, use the Command Palette to run the Copilot: Install Agent command, and follow through the dialog. The Copilot agent should still install successfully.
N/A
> defend against invalid TAR envvars

- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/shared_core/Error.cpp
- src/cpp/shared_core/include/shared_core/Error.hpp
- src/gwt/src/org/rstudio/core/client/DialogOptions.java
- src/gwt/src/org/rstudio/core/client/MessageDisplay.java
- src/gwt/src/org/rstudio/core/client/widget/MessageDialog.java
- src/gwt/src/org/rstudio/studio/client/common/DefaultGlobalDisplay.java
- src/gwt/src/org/rstudio/studio/client/common/dialog/DesktopDialogBuilderFactory.java
- src/gwt/src/org/rstudio/studio/client/common/dialog/WebDialogBuilderFactory.java
- src/gwt/src/org/rstudio/studio/client/workbench/copilot/model/CopilotResponseTypes.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.css
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.java
- src/gwt/test/org/rstudio/studio/client/common/DummyGlobalDisplay.java
Addresses https://github.com/rstudio/rstudio/issues/13499.
Here's an example of the UI presentation, for an error that's captured when trying to start the Copilot agent. In this instance, I modified the `agent.js` script, adding `oops` to the start -- basically ensuring the process would quickly die when trying to run the `agent.js` script.
Check if an error occurred when attempting to launch the Copilot agent during the status invocation. If an error occurs, report that back to the client.
N/A
I'm not quite sure how to test this -- I'm not sure if there's a great way to simulate a failure to launch in the Copilot agent process?
N/A
> report errors when attempting to start Copilot agent

- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionHelp.R
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java
Addresses https://github.com/rstudio/rstudio/issues/13579.
Adds a user preference, and uses it!
N/A
A simple way to test is to type:
```
mt
```
and then press Tab. You should get an autocompletion popup like the following:
Whether or not you see the dataset preview should depend on the value of the preference here:
Note that you may need to restart the R session after changing this preference.
N/A
> add preference controlling dataset preview in Help

- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.css
- src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBaseResources.java
- src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogPaneBase.java
- src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
- src/gwt/src/org/rstudio/studio/client/projects/Projects.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
Addresses https://github.com/rstudio/rstudio/issues/13717.
Adds a user preference "default_open_project_location", which is accessible here:
The directory set here is then used as the default "starting" location when opening a new project.
N/A
To be verified by user.
N/A
> provide user pref for default open project location

- src/cpp/core/include/core/system/Process.hpp
- src/cpp/session/modules/SessionFind.cpp
- src/cpp/session/modules/SessionGit.cpp
- src/cpp/session/modules/SessionGit.hpp
Addresses https://github.com/rstudio/rstudio/issues/13015.
Use `runProgram()` rather than `runCommand()`, so that we can support UNC paths on Windows. This also helps us obviate the need to escape paths and other shell-specific characters.
To test locally, you can add 'localhost' (that is, your own machine) as a network location. To do this, open the File Explorer, click on "This PC" on the left bar, then use the More (...) dropdown and select Add a Network Location.
Then, as the network location, type `\\localhost\c$`:
Give that the default name. Now, when you use File -> New Project or File -> Open Project in RStudio, you can use that network location (which is really just your own machine). Then, try and test Find in Files in one of these projects, both …
> run search as program instead of command

- NEWS.md
- src/cpp/session/modules/SessionTerminalShell.cpp
Addresses #13918
Reverts the WSL-specific part of https://github.com/rstudio/rstudio/pull/10283 by not passing any arguments to `system32\bash.exe` when we try starting a WSL terminal pane.
The conda integration mentioned in that issue was aimedat git-bash based terminals. The technique used for that won't work with WSL terminals, plus they are running in a separate subsystem and operating system so even if the WSL terminal was starting the integration would never have worked, near as I can tell.
I doubt we have WSL-specific terminal automation (would require running the tests on Windows Desktop with WSL installed).
This change is very narrowly scoped to just the WSL terminal codepath, so test setting the terminal to use WSL, and see if you can start a terminal (you will need WSL …
> fix WSL terminals so they start

- NEWS.md
- src/node/desktop/src/main/desktop-browser-window.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/native/desktop.node.d.ts
- src/node/desktop/src/native/desktop/desktop.cc
Addresses https://github.com/rstudio/rstudio/issues/13886.
It appears that Electron's `shell.openExternal()` struggles with certain kinds of Windows paths. This PR falls back to using our trusty friend `ShellExecute()` to open these files.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13886.
N/A
> avoid using openExternal for file URIs on Windows

- src/cpp/session/modules/SessionEnvironment.R
Addresses https://github.com/rstudio/rstudio/issues/13799#issuecomment-1809305861.
Not all `srcfile` objects have a `wd` set; make sure we check it exists before trying to use it.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13799#issuecomment-1809305861.
N/A
> check for NULL 'wd' before using it

- src/cpp/core/r_util/RTokenizer.cpp
- src/cpp/session/modules/SessionDiagnosticsTests.cpp
Addresses https://github.com/rstudio/rstudio/issues/13157.
When parsing the closing delimiter for a raw string, we need to be able to restart parsing in case we fail to parse in the middle of the stream of characters marking the end of the raw string.
Included.
N/A
N/A
> fix handling of closing delimiter in raw strings

- NEWS.md
- package/win32/CMakeLists.txt
- package/win32/cmake/modules/NSIS.template.in.electron
Addresses #13936
When I tweaked our NSIS template to adjust for Electron having RStudio.exe in the root of the install folder (instead of in a bin subfolder), I didn't do it correctly. I directly created the RStudio shortcut on install instead of letting `CPACK_NSIS_CREATE_ICONS` handle it and didn't add an accompanying uninstall command.
Use the correct cmake/nsis magic incantations to install the shortcut correctly (and now it also uninstalls, which then allows the entire start menu "rstudio" folder to be deleted).
N/A
Test on Windows:
- install RStudio
- confirm RStudio is in the Windows Start Menu (in the UI and/or by looking at `C:\programdata\microsoft\windows\Start Menu\Programs\RStudio`
- confirm you can start RStudio with that icon
- uninstall RStudio
- confirm the …
> install shortcut correctly so it will uninstall

- dependencies/common/install-node
Addresses build failures like https://build.posit.it/job/IDE/job/Pro-Builds/job/nightly-pipeline/job/main/745/.
Use a similar hack for Ubuntu Bionic (which is used to produced Ubuntu Focal builds) as we do for CentOS 7.
N/A
N/A
N/A
> use node 16 on bionic

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetQuartoHelper.java
Addresses https://github.com/rstudio/rstudio/issues/12968.
We have some code logic that tries to determine if we can terminate a YAML chunk block after the user presses Enter. This PR tightens up that logic, so that we only do this in more specific circumstances.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/12968.
N/A
> tweak behavior of enter in YAML chunk options

- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/session/session-options.json
Addresses https://github.com/rstudio/rstudio/issues/13823.
This PR adds the session option `copilot-agent-helper`, which can be set by the administrator to a custom shell script. That shell script is then responsible for running Copilot, but can also perform other tests or diagnostics before running Copilot.
N/A
N/A
N/A
> allow for custom copilot agent helper script

- src/cpp/core/r_util/RProjectFile.cpp
Reviewed in PR: https://github.com/rstudio/rstudio-pro/pull/5456
- For large directories over nfs, this is a major speedup
> Reverse order of test to avoid isDirectory call for each file

- NEWS.md
- src/cpp/session/modules/SessionConnections.R
- src/cpp/session/modules/SessionConnectionsInstaller.R
- src/cpp/tests/testthat/test-connections.R
The connection pane allows for drivers with a duplicate name to be listed as a duplicate with the suffix of ` with RStudio Drivers`.
Currently duplicates are only allowed if the ODBC installation entries that have `Installer = RStudio`, which is set during the installation of drivers through Desktop Pro.
This change will allow duplicates to be listed with the following entries for `Installer`:
- `RStudio Pro Drivers`
- `Posit Pro Drivers`
- Change connection pane suffix to "with Posit Driver"
- Allow duplicate connection pane entries from pro drivers
- Find connection snippet by walking the directory
The original logic for determining the R snippet path was quite fragile.
We now walk up the directory tree from driver library until we find the `snippets` directory instead of using a simple …
> Update connection pane deduplication for Posit drivers

- NEWS.md
- src/cpp/core/LoggingTests.cpp
- src/cpp/r/include/r/RHelpers.hpp
- src/cpp/session/modules/SessionRUtil.R
- src/cpp/session/modules/environment/SessionEnvironment.cpp
- src/cpp/tests/testthat/test-environment.R
Addresses https://github.com/rstudio/rstudio/issues/13965.
- Move the logic for computing whether an object can be safely serialized into C++ land.
- Cache the results of these computations. The cache is refreshed on each use, so values removed from the global environment are also eagerly removed from the cache.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13965.
N/A
> use cache when tracking if objects in global environment can be serialized

- src/cpp/session/modules/SessionRSConnect.R
- src/cpp/tests/testthat/test-rsconnect.R
Addresses #13945
Failing test is fixed. 
To verify: Build, and then run `./rstudio-tests --filter rsconnect` from the build directory.
Or in RStudio,
```
Sys.setenv(QUARTO_ENABLED=TRUE)
testthat::test_file("src/cpp/tests/testthat/test-rsconnect.R")
```
To verify the actual behavior works as expected, see [comment](https://github.com/rstudio/rstudio/issues/13945#issuecomment-1830350860) in issue #13945 as per discussion in #11201
> fix failing test -- make sure all inputs are normalized first

- src/cpp/core/Database.cpp
- src/cpp/server/ServerMain.cpp
Reviewed in: https://github.com/rstudio/rstudio-pro/pull/5553
Init the secure cookie key before the database.  Add back the DB code that supported encrypted passwords.
> Companion commit to add back db password encryption

- version/news/NEWS-2023.12.0-ocean-storm.md
Add news entry for updating quarto to `1.3.450` (#13914).
- see https://github.com/rstudio/rstudio/blob/rel-ocean-storm/dependencies/common/install-quarto
- Added news for updating quarto to `1.3.450` 
- Removed docs breadcrumbs related entries which were based on quarto 1.4 (see rstudio/rstudio-pro#5561) -- these docs items were removed in pro, but not open source NEWS
- Grouped dependency version updates to the top of NEWS so it's easier to check dependency changes at a glance
> Add quarto version update news

- NEWS.md
- src/node/desktop/src/assets/locales/en.json
- src/node/desktop/src/assets/locales/fr.json
- src/node/desktop/src/main/gwt-callback.ts
Addresses #12965
The main problem is we weren't including a name for the extension filter in the Save As dialog, and when Windows is hiding known file extensions, that leaves nothing to display in the Types dropdown so it was blank.
Since we don't pass a friendly name to the save as callback, I just used the extension itself as the name.
Additionally I added the "All files (*)" filter; that should always be there in a Windows save-as dialog (it was in the Qt dialog).
Now the dialog looks like this when saving an untitled R file.
With file extensions visible in Windows:
With file extensions hidden in Windows:
None that I'm aware of.
Try saving a few different new files of varying types, with Windows file extensions visible, and again with them hidden, and make sure the types dropdown is no …
> fix save as dialog not showing types when known file extensions are hidden (Windows)

- src/cpp/session/modules/SessionEnvironment.R
User defined `length()` methods can return things other than a scalar integer. The IDE should guard against that when inspecting the environment with `isSerializable()`.
This was encountered with the IDE inspecting reticulate objects that intentionally raise an exception from `__bool__`(), and thus resetting the value presented by `reticulate::py_last_error()`
`isTRUE()` was added in R 3.5. If this is an issue, we can avoid using it.
> guard against `NA` length()

- src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/manipulator/ManipulatorControlSlider.java
Addresses #13962
This warning was introduced by https://github.com/rstudio/rstudio/pull/13883.
`@SuppressWarnings("deprecation")` doesn't prevent warnings when importing a deprecated class. This source file used to use a wildcard import to avoid this (not sure if that was on purpose), but it was changed to a specific import of the deprecated class.
Switched to using the full type and moved the @SuppressWarnings("deprecation") to a narrower scope.
I did look at changing to the recommended non-deprecated API, but didn't seem worth the non-trivial change required.
None
This is purely to suppress a warning message during compilation, the generated code isn't changed.
This touches the widget used for plot slider manipulator controls. If you wanted to test it, try something like this (click on …
> use full type for ChangeListener to avoid deprecation warning on import

- git_hooks/README.md
- git_hooks/set-up-git-hooks
A pre-cursor to https://github.com/rstudio/rstudio-pro/issues/5605 to prevent git hooks installed via the `git_hooks/set-up-git-hooks` script from overwriting existing git hooks with the same name (by backing up the existing hook).
If a git hook is being installed via `git_hooks/set-up-git-hooks` script, if there is already a git hook with the same name, back up the existing hook by 
none
I've tested this on my Mac, but should work the same on Linux and Windows (using Git Bash).
- expand the `.git/hooks` directory in your local rstudio project
- if you already have git hooks, you can back them up manually just in case, but running the `git_hooks/set-up-git-hooks` script should create a copy of the existing hooks (if they are the pre-commit or pre-push hooks) with the current timestamp …
> add handling for backing up existing git hooks

- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/ProjectCopilotPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.css
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.java
- version/news/NEWS-2023.12.1-ocean-storm.md
Addresses #14067
Remove the messaging in Global Options / Copilot and Project Options / Copilot. Also removed some unused code while I was at it.
None changed
Visually confirm the messages are gone in global options and project options.
None
> Remove Copilot preview label and disclaimer

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/ProjectCopilotPreferencesPane.java
Addresses #14064
The core problem was an exception being thrown in the Copilot Project Prefs pane due to trying to access a null `response.result`. This bypassed the rest of the code that would set the label.
I copied the pattern used in the Copilot Global Prefs Pane for checking this scenario. That code got out of sync with the project prefs code in #14064. I didn't port over the extra support for showing Copilot error details that were added in that PR; figure if a user is having trouble they can troubleshoot via global prefs.
None that I know of.
Should now see appropriate message when viewing Project Preferences / Copilot with Copilot disabled.
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a new feature, …
> avoid exception in copilot project options pane

- NEWS.md
This PR gives us a place to collect updated external dependencies in our NEWS file. This should make it easier to see at-a-glance what updates have been made, which should be useful both internally and for users of RStudio.
> add 'dependencies' section

- NEWS.md
- src/gwt/acesupport/acemode/r_code_model.js
Addresses https://github.com/rstudio/rstudio/issues/12674.
Remove the previous limit when assessing the size of a comment. Note that we do something similar when looking for matching parentheses, e.g.
https://github.com/rstudio/rstudio/blob/0b4b07ffd7b94e5ff38e00ae6051d4bc5f45e101/src/gwt/acesupport/acemode/r_code_model.js#L1606-L1611
> allow more aggressive lookbehind when determining indentation in pipe

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/DelegatingCompletionManager.java
Addresses #14074.
Changes to the way Quarto chunk options are tokenized appeared to have also modified how the document mode is inferred for YAML chunk options. As a workaround, we allow inference of a Quarto chunk context when the document mode appears to be Markdown.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14074.
N/A
> allow Quarto completions in Markdown mode

- src/cpp/session/modules/quarto/SessionQuartoJob.cpp
- src/cpp/session/modules/quarto/SessionQuartoPreview.cpp
Addresses https://github.com/rstudio/rstudio/issues/14027.
Allow for arbitrary Quarto document preview paths when parsing the location from the generated quarto output.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14027.
N/A
> be more permissive when parsing quarto preview URLs

- src/node/desktop/src/main/desktop-browser-window.ts
- version/news/NEWS-2023.12.1-ocean-storm.md
Addresses #14097 (regression in Ocean Storm).
Without this fix, you cannot open R Package help topics in a separate window, and attempting to open a data viewer in a separate window after a failed attempt to pop-out help results in a mostly blank window. There may be other symptoms, too, but this is the one I know about.
A return statement was in the wrong place, moved it up to the right place. Was introduced by this change: https://github.com/rstudio/rstudio/pull/13754
Going to guess "no" given we missed this! It is Electron desktop-specific.
See comments in issue on repro steps to try.
None
> fix showing help in separate window

- src/cpp/session/modules/SessionCopilot.cpp
- version/news/NEWS-2023.12.1-ocean-storm.md
Addresses https://github.com/rstudio/rstudio/issues/14106.
Avoid indexing binary / large files with Copilot.
Not included.
To test, try creating a new project, and enabling both Copilot + project indexing for that project.
Then, run this code:
```
writeLines("COPILOT_LOG_LEVEL = 1", ".Renviron")
saveRDS(mtcars, file = "mtcars.rds")
```
Then, restart the R session. You should see something like:
```
[onStarted]: Copilot agent has started [PID = 95126]
[sendRequest]: Sending request 'initialize' with id 'cc35b6a5-f5dd-4051-81d2-d6488d0a6ed6'.
[indexFile]: Indexing document: /Users/kevin/scratch/copilot-test
[indexFile]: Indexing document: /Users/kevin/scratch/copilot-test/copilot-test.Rproj
[onBackgroundProcessing]: Invoking continuation with id 'cc35b6a5-f5dd-4051-81d2-d6488d0a6ed6'. …
```
> avoid indexing large / binary files with Copilot 

- src/gwt/src/org/rstudio/core/client/layout/DualWindowLayoutPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/model/WorkbenchLists.java
I'm currently getting a "blank screen" on startup due to errors when trying to read workbench lists. This PR makes the IDE startup a bit more permissive, so we can handle the case where a particular workbench list is missing.
I'm not sure if we should be logging or reporting if this happens? I am a bit worried that this might be masking a different sort of error.
> improve handling of missing / empty workbench lists

- src/gwt/src/org/rstudio/studio/client/projects/ProjectMRUList.java
Addresses #14107
The culprit was ProjectMRUList.generateLabels(). Before project naming feature:
```java
protected ArrayList<String> generateLabels(ArrayList<String> mruEntries, boolean includeExt)
{
return DuplicateHelper.getPathLabels(mruEntries, true);
}
```
Note that it never used the `includeExt` parameter (which comes in as `false`), and passed `true` to `getPathLabels`' second parameter (which is also `includeExt`).
When I modified this method I started passing `includeExt` instead of hardcoding `true` and this caused it to strip anything after the final period.
So the fix was to change it back to `true`.
None
Try creating a project in a folder that has periods in the name and confirm that the full name shows in the project dropdown, the mru list, and the titlebar / browser tab. …
> fix display issue with project folders containing periods in name

- NEWS.md
- src/gwt/src/org/rstudio/core/client/files/FileSystemContext.java
- src/gwt/src/org/rstudio/studio/client/common/impl/DesktopFileDialogs.java
- src/gwt/src/org/rstudio/studio/client/workbench/model/RemoteFileSystemContext.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilePathToolbar.java
Addresses https://github.com/rstudio/rstudio/issues/14096.
We have a file system context class, which tries to maintain a working directory + the contents of that directory. I suspect the latter is primarily used for the Files pane; however, because that class is apparently shared in a couple places (e.g. preserving the default directory to be used when opening files) we end up unnecessarily listing files in the directory hosting the file we're opening.
The fix here is fairly narrow; in desktop file dialogs, when we open a document, we define and use a separate helper called `setwd()` rather than `cd()`, and allow `setwd()` to do less work.
An alternate fix would be to defer listing of a directory's contents until `ls()` itself is actually called. That might be preferable, but that also …
> avoid listing files in directory when opening a file

- src/cpp/session/modules/quarto/SessionQuartoPreview.cpp
Fixes an issue where the path to a viewed file was duplicated. Now that we can correctly parse the URL to be used for navigation from the generated Quarto output, we don't need to append any project-specific information about the URL to be used for preview.
cc: @aronatkins
> no longer need to append parsed quarto path

- src/gwt/src/org/rstudio/core/client/MessageDisplay.java
- src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/core/client/widget/DialogBuilder.java
- src/gwt/src/org/rstudio/core/client/widget/MessageDialog.java
- src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
- src/gwt/src/org/rstudio/studio/client/common/dialog/DialogBuilderBase.java
- src/gwt/src/org/rstudio/studio/client/common/dialog/WebDialogBuilderFactory.java
First draft of of a request by Workbench team: a message dialog that includes a link. The link is opened with target=_blank.
This MessageDialog variant only works on RStudio Server; the link won't be shown on Desktop.
New `showMessage` variant that takes a link label and destination (url), along with a message and dialog caption.
Example:
This was created with:
```java
globalDisplay_.showMessage(
GlobalDisplay.MSG_INFO,
"Window Caption",
"Here is a message that I am displaying because I need to display something here.",
"Go to Posit Website",
"https://posit.co/");
```
None
TBD
N/A
> Add MessageDialog variant box that shows a link after the message

- src/cpp/core/include/core/system/Crypto.hpp
- src/cpp/core/system/Crypto.cpp
- src/cpp/core/system/CryptoTests.cpp
So we can continue to build / work against older OpenSSL if necessary.
> retain backwards compatibility with older openssl

- src/cpp/session/modules/SessionDataViewer.R
- src/cpp/session/modules/data/DataViewer.cpp
- src/gwt/src/org/rstudio/studio/client/dataviewer/DataViewerResources.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java
Addresses #14082.
Check if the monitored `SEXP` object has changed, in addition to its type + structure. If it has, then update the view.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/14082. Also verify that https://github.com/rstudio/rstudio/issues/13856 hasn't been re-introduced.
N/A
> make sure we auto-refresh if object changes

- NOTICE
- src/cpp/core/include/core/Result.hpp
- src/cpp/ext/expected/README.md
- src/cpp/ext/expected/expected.hpp
* Incorporate backwards-compatible std::expected implementation.
* Add Posit-specific wrapper types that bind the error type of expected to core::Error.
Upstream `core::Result` from Launcher repo so it's available to a wider group of developers. No user-facing impact.
I did add `expected.hpp` directly to the repo instead of pulling it in as a git submodule. It's a single file and new versions are few and far between.
> Indicate whether this change includes unit tests or integration …
> Add core::Result and tl::expected

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/application/DesktopHooks.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindow.java
Addresses [CLIENT_EXCEPTION Errors when using ctrl + c shortcut in satellite window #14140](https://github.com/rstudio/rstudio/issues/14140
)
The problem was that the DesktopHooks were being injected into source satellite windows even for non-desktop (server/workbench). The constructor of DesktopHooks would setup a handler for copy and cut which tried to invoke something on the non-existent desktop object, throwing an exception.
The primary fix was to only create the DesktopHooks object when initializing the source satellite if running on Desktop.
I also patched the DesktopHooks itself to double-check and not install the copy/cut handler unless on Desktop (in case there's another case where DesktopHooks are being initialized in server/workbench; I couldn't find any). This exact thing was …
> don't use desktop hooks in source satellite for server

- git_hooks/secrets/run-detect-secrets
- Lil' follow-up to https://github.com/rstudio/rstudio/pull/14131 to use a secrets baseline file pattern to exclude the baseline file
- Part of addressing: https://github.com/rstudio/rstudio-pro/issues/5605
Running the secret detection in pro, the open source baseline was getting included in the results. Using a file pattern ensures that any files in the secrets directory starting with `.secrets.baseline` will be excluded.
> use pattern to exclude baseline files from secrets scan

- src/gwt/src/org/rstudio/core/client/MessageDisplay.java
- src/gwt/src/org/rstudio/core/client/jsonrpc/RpcRequest.java
Addresses https://github.com/rstudio/rstudio-pro/issues/5733
Fix a bug in an issue that Jeff noticed after we merged this feature. 
Add a global flag to the MessageDisplay that can disable all error messages, and use that to suppress errors instead. This allows us to keep the rest of the error handlers that would otherwise be managing state.
N / A - manual testing required
I'll have to spin up a new Fuzzbucket with a modified rsession to simulate the no response condition.
> Add a global error message suppression flag to address NPE for error

- src/cpp/session/modules/SessionHistory.cpp
Addresses https://github.com/rstudio/rstudio/issues/14167.
Fixes an Obi-Wan error; the end range in the `.subset()` call is exclusive, not inclusive, so we shouldn't try to subtract one.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14167.
N/A
> fix ob1 error when searching console history

- NEWS.md
- src/cpp/session/modules/SessionGit.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/diff/DiffChunk.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/diff/UnifiedEmitter.java
Addresses https://github.com/rstudio/rstudio/issues/2460.
Addresses https://github.com/rstudio/rstudio/issues/5476.
This was a thorny one! In the Review Changes dialog, users can manually stage and unstage lines via the presented UI. We do this by generating a diff, and then sending that to be applied via `git apply`. However, it appears we were generating incorrect ranges in some scenarios: most notably, when attempting to stage a single line change at the end of a document, we were generating a patch like this:
```
--- a/test.R
+++ b/test.R
@@ -1,5 +1,5 @@
print(1 + 1)
print(2 + 2)
print(3 + 3)
print(4 + 4)
print(5 + 5)
+456
```
However, the range `@@ -1,5 +1,5 @@` is incorrect -- because we're adding a line, this should be `@@ -1,5 +1,6 @@` instead; that is, the applied diff would have …
> fix issue with staging line / selections in Review Changes dialog

- NEWS.md
- src/gwt/acesupport/acemode/markdown_highlight_rules.js
Addresses https://github.com/rstudio/rstudio/issues/12862.
@cderv, can you think of any reason why we would want to continue supporting highlight of `\[ \]` and `\( \)` equations in R Markdown / Quarto documents? Or is it okay to enforce the usage of `$ $` and `$$ $$` here?
> stop highlighting \[ \] and \( \) Mathjax eqns

- src/cpp/session/modules/SessionRSConnect.R
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
Addresses https://github.com/rstudio/rstudio/issues/12708.
- Use `config_url` rather than `url` in the "Updated:" UI.
- Use `rsconnect::applications()` rather than `rsconnect:::getAppById()` as the latter does not provide `config_url`.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/12708.
N/A
> use config_url for redeployment

- src/cpp/session/CMakeLists.txt
- src/cpp/session/SessionClientInit.cpp
Addresses [Build option to disable automatic version check #13236](https://github.com/rstudio/rstudio/issues/13236)
Added cmake option `RSTUDIO_DISABLE_CHECK_FOR_UPDATES` to enable building RStudio Desktop without the automatic check for updates feature.
When generating the build via cmake, use `RSTUDIO_DISABLE_CHECK_FOR_UPDATES=1`, e.g.:
`cmake .. -GNinja -DRSTUDIO_DISABLE_CHECK_FOR_UPDATES=1`.
This leverages the existing feature for doing this via an environment variable.
None
Nothing to really test here unless you want to build your own RStudio without "check for updates" support.
You could sanity check that "check for updates " IS present in normal builds, I suppose.
None
> Add cmake option to disable check for updates feature

- docs/news/index.qmd
Update release notes for IDE / Workbench 2023.12.1+402.pro1 release.
This change has been generated by the release script. Content is generated based on `version/news/NEWS-2023.12.1-ocean-storm.md`. If this file was not in sync with Pro or did not include items from other sources (i.e. the vscode extension), then some items may be missing.  Please verify content/formatting is correct and make changes if necessary.
> Update release notes for 2023.12.1+402.pro1

- src/cpp/session/CMakeLists.txt
Getting linker errors building rsession on Windows:
```
[2024-01-31T00:39:58.391Z] [562/567] Linking CXX executable src\cpp\session\rsession-utf8.exe
[2024-01-31T00:39:58.391Z] FAILED: src/cpp/session/rsession-utf8.exe 
[2024-01-31T00:39:58.391Z] cmd.exe /C "cd . && "C:\Program Files\CMake\bin\cmake.exe" -E vs_link_exe --intdir=src\cpp\session\CMakeFiles\rsession-utf8.dir --rc="C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\rc.exe" --mt="C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\mt.exe" --manifests  -- "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\link.exe" /nologo @CMakeFiles\rsession-utf8.rsp  /out:src\cpp\session\rsession-utf8.exe /implib:src\cpp\session\rsession-utf8.lib …
```
> link yaml-cpp using static library to fix Windows build

- NEWS.md
- src/node/desktop/src/assets/locales/en.json
- src/node/desktop/src/assets/locales/fr.json
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/detect-r.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/src/ui/widgets/choose-r.ts
- src/node/desktop/src/ui/widgets/choose-r/load.ts
- src/node/desktop/src/ui/widgets/choose-r/preload.ts
- src/node/desktop/src/ui/widgets/choose-r/styles.css
- src/node/desktop/src/ui/widgets/choose-r/ui.html
Addresses #14180 (draft - we haven't decided if we're taking this for chocolate cosmos)
This is specifically for RStudio Desktop and Desktop Pro (Electron) on Windows.
At startup, if we don't find an R installation, we no longer show the "R Not Installed" dialog but instead show the Choose R dialog with a Download R... button added in the lower left region.
Clicking this button launches https://www.rstudio.org/links/r-project in the user's default browser (i.e. same thing the "R Not Installed" dialog would do) and closes RStudio. I could have left the dialog open, but most likely a user that goes this route is going to install R in a normal location, and then when they relaunch RStudio we'll find it.
Alternatively, a user can use Browse... to choose an R installation in a location we …
> change startup behavior on Windows when R not found

- docker/jenkins/Dockerfile.centos7
One step of implementing: #14157
Chipping away at this one platform at a time to make it easier to diagnose any unexpected build issues.
Install Java and JDK v11 instead of v8 in the dockerfile. The installation of `ant` on CentOS7 triggers installation of Java8, so have to then activate Java/Javac 11.
I built the image locally, started up the container, confirmed that `javac -version` and `java -version` both report v11, and also did a successful package build of Desktop in the container.
N/A
Nothing to manually test here.
N/A
> use Java11 for gwt builds on CentOS7

- docs/news/index.qmd
This one was added last-minute and slipped through. It's already in `version/news/NEWS-2023.12.1-ocean-storm.md` (because you have to update like three different files for news-related things).
> I am once again updating docs/news/index.qmd

- src/cpp/core/ConfigProfile.cpp
- src/cpp/core/ConfigProfileTests.cpp
- src/cpp/core/include/core/ConfigProfile.hpp
* Add isParamDefined method that returns true if the supplied parameter is defined.
* Add unit tests to cover new code.
The Job Launcher requires the ability to check if a `ConfigProfile` value is defined anywhere in a configuration file. This change adds a new method to that class that enables this check.
Add a new method, `bool isParamDefined(std::string paramName)`, to `ConfigProfile` that returns true if the supplied `paramName` names a parameter that's defined anywhere in the associated configuration file.
Added unit tests to cover new code.
Not a user-facing change, explicit QA not likely required.
Not a user-facing change; user-facing documentation update not strictly required.
> Add ability to check if a ConfigProfile value is defined

- docker/jenkins/Dockerfile.opensuse15
Part of implementing: https://github.com/rstudio/rstudio/issues/14157
Chipping away at this one platform at a time to make it easier to diagnose any unexpected build issues.
Install Java and JDK v11 instead of v8 in the dockerfile.
I built the image locally, started up the container, confirmed that javac -version and java -version both report v11.
N/A
Nothing to manually test.
N/A
> Update opensuse15 dockerfile to Java 11

- docker/jenkins/Dockerfile.focal
- docker/jenkins/Dockerfile.rhel8
Final batch of Linux dockerfile updates for #14157
With this all the Linux build environments will be using Java 11 (instead of Java 8). Note that Ubuntu Jammy and RHEL9 already use Java 11. This leaves Windows to be updated (Mac is already using Java 11).
Update dockerfiles, tested locally.
N/A
Nothing to manually test.
N/A
> Update Ubuntu Focal and RHEL8 Dockerfiles to Java 11

- dependencies/windows/Install-RStudio-Prereqs.ps1
- docker/jenkins/Dockerfile.windows
Final change for #14157
With this all build environments for RStudio/Workbench will be using JDK11. Some have been using JDK11 for a while, but several were still on JDK8.
Note that we don't currently REQUIRE jdk11, so dev machines with JDK8 will still be able to build GWT, but we need JDK11 to update to the latest build of elemental2 (https://github.com/rstudio/rstudio/issues/13924), currently slated for Cranberry Hibiscus (release after Chocolate Cosmos).
Updated Windows dockerfile to install JDK11 instead of JDK8.
Updated bootstrapping script (optional helper for setting up a dev machine) to install JDK11 instead of JDK8, plus a few small cleanups.
N/A
Nothing to manually test.
N/A
> use Java 11 in Windows build image

- NEWS.md
- src/cpp/session/SessionSourceDatabase.cpp
- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/session/modules/SessionRCompletions.R
- src/cpp/session/modules/SessionRCompletions.cpp
- src/cpp/session/modules/SessionRUtil.R
- src/cpp/session/modules/SessionSource.R
- src/gwt/src/org/rstudio/studio/client/common/codetools/CodeToolsServerOperations.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/CompletionContext.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/DocUpdateSentinel.java
Addresses https://github.com/rstudio/rstudio/issues/8444. Implements autocompletion of column names within `aes()` calls. For example:
We also support inline data + aesthetic mappings; for example, the (admittedly nonsensical example):
Finally, when available within the R session, we can also extract data attributes from `gg` objects as created via `ggplot2` calls, for plots which are built piece-by-piece.
This PR uses a small extension to the R completion context builder, and now attempts to capture the entirety of the current R expression. Then, from that expression, we can try to pull out details like the `data` argument in a `ggplot2` call.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/8444. This PR also necessitates smoke testing of other autocompletion …
> support completions for ggplot2 aesthetics

- NEWS.md
- src/gwt/src/org/rstudio/core/client/widget/MessageDialog.java
- src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
- src/gwt/src/org/rstudio/studio/client/common/dialog/WebDialogBuilderFactory.java
Addresses [go to files/function box is too large #14223](https://github.com/rstudio/rstudio/issues/14223)
Instead of adding the region for the optional anchor and removing it if not needed, only add it when known it is needed.
The problem was the original approach only worked for components that used `ModalDialogBase` via the `WebDialogBuilderFactory`, but there are some that use `ModalDialogBase` directly, and they didn't remove the unused region.
I did test that the Message dialog variant with a link in it (which we added but ended up not using in the ocean-storm patch) still works as expected.
None, purely a visual layout issue.
Layout of mentioned UI elements should be back to normal (no extra whitespace). There are likely other places that were impacted by this, but this change puts …
> Fix extra whitespace bug in some dialogs/popups

- NEWS.md
- src/cpp/r/R/Api.R
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/modules/ModuleTools.R
- src/gwt/src/org/rstudio/studio/client/application/model/SuspendOptions.java
Addresses https://github.com/rstudio/rstudio/issues/2841.
Addresses https://github.com/rstudio/rstudio/issues/11378.
Will need follow-up in https://github.com/rstudio/rstudioapi/issues/95 post-merge.
This adds a commonly-requested feature, and allows for users to restart the R session programmatically into a fresh / "clean" state.
For testing, one can confirm that using the "clean" version of a restart ensures that no packages or variables from the previous session are saved and restored.
```
> library(dplyr)
> loadedNamespaces()
[1] "methods"    "utf8"       "R6"         "tidyselect" "magrittr"   "glue"       "tibble"     "pkgconfig" 
[9] "dplyr"      "generics"   "lifecycle"  "utils"      "cli"        "fansi"      "vctrs"      "graphics"  
[17] "grDevices"  "stats"      "compiler" …
```
> add support for 'clean' restart

- package/osx/make-package
DRAFT until other build issues are resolved; don't want to add more variables.
Addresses [Official Mac builds seem confused about which node.js they are using #14236](https://github.com/rstudio/rstudio/issues/14236)
Put the node we install via dependency scripts on the path during package build. We already do this in the Linux `make-package` script: 
https://github.com/rstudio/rstudio/blob/be0a9d9d2482833e9bdf0a6909ee65bf1f0a77e6/package/linux/make-package#L181-L183
Build tweaks
Nothing to test here
N/A
> Ensure Mac package builds are using desired node.js version

- src/gwt/src/org/rstudio/core/client/widget/SearchWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/codesearch/CodeSearch.java
- src/gwt/src/org/rstudio/studio/client/workbench/codesearch/ui/CodeSearchWidget.java
This PR fixes a long-standing annoyance that I've had with the "Go to File / Function" search menu. A screencast will help explain:
https://github.com/rstudio/rstudio/assets/1976582/664f5eb9-9d90-49bf-8c8e-780eed62070f
In short, if the mouse cursor happens to lie where the code search menu is presented, the menu item at the cursor location will be selected, even though the user didn't explicitly act to select that item. This contends with the default behavior of selecting the first item in the search list, which users would reasonably expect to happen regardless of the cursor position when the menu is requested.
> fix selection buglet in suggestion menu

- NEWS.md
- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionRCompletions.R
- src/gwt/src/org/rstudio/studio/client/common/codetools/RCompletionType.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequesterResources.java
Addresses https://github.com/rstudio/rstudio/issues/14242.
Some R variables might be annotated with a "label" attribute. This PR bundles that information as part of the completion metadata when available, and uses that in the displayed completion list.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14242.
Not included; not sure if this is worth documenting.
> support display of labels in autocompletion popup

- NEWS.md
- src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetScopeHelper.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextToolbar.java
Addresses https://github.com/rstudio/rstudio/issues/14063.
We had previously disable rendering of the chunk toolbar for `dot` and `mermaid` engines. Now that they're executable, we should provide that UI.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14063.
N/A
> dot is now runnable

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
- src/node/desktop/src/main/desktop-browser-window.ts
- src/node/desktop/test/unit/main/minimal-window.test.ts
- src/node/desktop/test/unit/main/window-tracker.test.ts
Bump to latest v28.x Electron release.
Includes **Chrome/120.0.6099.276**
Also did `npm audit fix` to address flagged vulnerabilities. Noticed an exception being thrown during an Electron unit test (the test was still passing, the problem happened as things were tearing down), so fixed that.
Electron unit tests are passing; I tried on both both macOS and Linux.
Nothing to specifically test. Version bumps with a major Electron release are typically quite safe.
N/A
> Upgrade Electron to 28.2.2

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/yaml/YamlEditorContext.java
Part of https://github.com/rstudio/rstudio/issues/9895.
We use Quarto's bundled YAML intelligence tools for providing YAML autocompletion results. However, it doesn't appear to tolerate chunks which contain inline chunk options within the chunk header, which is still common in R Markdown documents. This PR alleviates that issue by stripping out those options before requesting completions.
N/A
Test that you can still receive autocompletion results within Quarto chunk's `#| ` YAML code comments, even if the chunk has a label specified in the chunk header.
N/A
> strip chunk header options before requesting YAML completions

- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/test/unit/main/utils.test.ts
Addresses https://github.com/rstudio/rstudio/issues/13994.
RStudio users can use `rstudioapi::selectFile(filter = <...>)` to open a file selection dialog with the associated filter. However, the `rstudioapi` package doesn't document how one should supply multiple extensions to the filter. This PR alleviates the issue by intentionally allowing extension parsing to be more permissive here, so that both internal and external usages of `selectFile()` can be functional.
Captured by existing unit tests.
> Specify which documentation has been added or …
> be more permissive when parsing file filter strings

- src/cpp/session/modules/SessionJobs.R
- src/cpp/session/modules/jobs/SessionJobs.cpp
Part of https://github.com/rstudio/rstudioapi/issues/144#issuecomment-1885585414.
Add an API method `listJobs`, and use existing tooling for retrieving that job information. Useful for addin authors who want the ability to list and manipulate running jobs.
N/A
Test that `.rs.api.listJobs()` will display information about any Background Jobs which have been run (note: not workbench jobs)
N/A
> add API for listing background jobs

- src/gwt/src/org/rstudio/core/client/command/AppCommand.java
Addresses https://github.com/rstudio/rstudio/issues/13321.
See:
https://github.com/rstudio/rstudio/blob/9fa21761dd070ed39aea7d18b63e207fb33b92ed/src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPresenter.java#L147-L160
The Viewer pane tries to toggle whether or not the UI for the "Clear" and "Clear All" buttons are enabled based on whether the R session is executing code. Unfortunately, this leads to trouble when users want to interact with the Viewer pane from `rstudioapi`, as:
- By executing code, the state of the "interrupt R" command is toggled;
- The Viewer pane then toggles the visibility of the "Clear" and "Clear All" commands;
- The executing code tries to execute the "Clear All" command;
- The execution request is discarded, as we don't allow "invisible" …
> allow execution of commands which are not visible

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialog.java
- src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.java
Addresses #14263
Displays the Quarto version (if Quarto is enabled) in the About dialog, appended to the user-agent information.
Additionally, if a custom version of Quarto is being used, show its path after the Quarto version.
Usually it will look like this (bundled Quarto).
If a custom Quarto is being used the path will be shown after the version:
None
Confirm About dialog shows the Quarto version, and the path if a custom version has been specified by the user (see issue for techniques for doing this).
Confirm that Copy Version button includes this additional information.
None
> Show quarto version in About dialog

- NEWS.md
- src/cpp/session/modules/SessionDataViewer.R
Addresses https://github.com/rstudio/rstudio/issues/14265.
If `variable.labels` is set, propagate it appropriately when subsetting data.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14265.
N/A
> preserve variable labels when subsetting data

- src/node/desktop/src/main/gwt-callback.ts
Addresses [File name doesn't include extension #14261](https://github.com/rstudio/rstudio/issues/14261)
Fix by having the Save dialog show the specific filter type (e.g. .R for an unsaved R file) instead of "All files" by default.
This is done by putting the specific type at the start of the filter array instead of the end.
Now you get this view by default when you save a new .R file (or any type with a known extension):
Compared to before (as reported in the issue):
None
Desktop-specific.
None
> Select specific file type filter by default in Save dialog (Desktop) instead of All Files

- NEWS.md
- src/cpp/session/modules/SessionShinyViewer.R
- src/gwt/src/org/rstudio/studio/client/shiny/ShinyApplication.java
Addresses https://github.com/rstudio/rstudio/issues/13394.
Rather than stopping the application via an interrupt, use an RPC which invokes `shiny::stopApp()`. Also add some tooling around suspending of interrupts, to help protect in case there are hooks that the user would like invoked on application end.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13394.
N/A
> use shiny::stopApp() when stopping applications

- src/node/desktop/test/unit/core/xdg.test.ts
Fix an Electron unit test that was failing on Windows if the user's profile folder had a different name than their user account. For example, on my PC my username is "gary" but the home folder is "gary_".
Use more reliable method (environment variable) to get profile folder name.
Unit test fix. Windows-only, and AFAIK we don't run these tests as part of our Windows build, only on Linux, so this shouldn't impact anything.
Nothing to verify.
N/A
> Fix Electron unit test on Windows

- jenkins/Jenkinsfile.daily
- jenkins/Jenkinsfile.hourly
- jenkins/Jenkinsfile.release
- src/cpp/server/DBActiveSessionsStorage.cpp
Split hourly and daily dispatchers for `main` into different Jenkinsfiles. Each dispatcher triggers a corresponding hourly or daily Builder Jenkins job that uses `Jenkinsfile.build`. This allows GitHub changes to be discovered independently by the Hourly Builder and Daily Builder, regardless of which Builder ran last.
The organization of Jenkinsfiles and Jenkins Jobs looks like below:
Hourly Builds are triggered by commits to `main`, and are rate-limited to build no more than once per hour
Daily Builds are triggered by a timer that builds binaries from `main` at 1am Eastern Time
Release Branches will build daily builds on commits, and are rate-limited to build no more than once per day
Release Branches will also build once per month on the first Sunday of every month at 1am Eastern Time
> …
> Restructure Jenkins to keep hourly and daily changes separate

- src/cpp/session/modules/viewer/SessionViewer.cpp
Addresses https://github.com/rstudio/rstudio/issues/13321.
When viewing a plain HTML file (as opposed to an HTML widget), clear the Viewer history. This makes the user experience more consistent, as we normally hide the Back + Forward buttons when viewing such files, implying the history has indeed been cleared.
The alternative here would be to also include these files in the Viewer history, but it seems like this decision was made rather intentionally in a number of places, e.g.
https://github.com/rstudio/rstudio/blob/f96fa983948a2d036e01ad8e8d06d8d07c403600/src/cpp/session/modules/viewer/SessionViewer.cpp#L71-L72
but unfortunately I lack the context to say whether this could be safely relaxed or not.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13321.
N/A
> clear Viewer history when navigating to non-widget

- NEWS.md
- docs/news/_quarto.yml
- docs/user/rstudio/_quarto.yml
Issue #14078 
After speaking with Amanda/legal, we were directed to add date ranges for the copyright date for each guide. The date should be creation of the product.
> Add additional information for QA on how to validate the change, paying special attention to the level …
> Updating copyright ranges

- docker/jenkins/Dockerfile.windows
Fix build error caused by windows interpolation syntax error when passing the R version.
I haven't tested this but I think the fastest way is to do so through Jenkins. Merging without review due to broken build.
> Fix windows builds 

- src/cpp/session/modules/ModuleTools.R
Addresses #14332
Use condition on pandoc version to use correct options, suggested from pandoc 2.19. 
N/A
Test the example in issue in pandoc < 2.19 and pandoc > 2.19
May be hard to test for older pandoc versions since RStudio bundles 3.1.1,1 (with Quarto currently) , but nothing should change for previous pandoc versions.
I tested with ‘3.1.11’
N/A minor
Signed community agreement.
> Avoid deprecated options for recent pandoc

- src/cpp/r/RCntxt.cpp
- src/cpp/r/RCntxtUtils.cpp
- src/cpp/r/include/r/RCntxt.hpp
- src/cpp/r/include/r/RCntxtInterface.hpp
- src/cpp/r/include/r/RCntxtUtils.hpp
- src/cpp/r/include/r/RIntCntxt.hpp
- src/cpp/session/modules/environment/SessionEnvironment.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
Addresses https://github.com/rstudio/rstudio/issues/14306.
Instead of always using the first function context, if there is a CTXT_BROWSER on the stack, prefer using the CTXT_FUNCTION it's associated with. We already do this elsewhere, e.g.
https://github.com/rstudio/rstudio/blob/66ea74b4422c2442bf6c1ad985407930bf16971c/src/cpp/r/RCntxtUtils.cpp#L58-L90
So this seems reasonable.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14306.
N/A
> handle tryCatch without srcrefs

- NEWS.md
- src/cpp/session/prefs/PrefLayer.cpp
Previously, we would parse these files even if we knew they were empty. This commit fixes an oversight from rstudio/rstudio-pro#4371 and should eliminate confusing errors like the following:
2024-02-26T17:00:32.155458Z [rsession-Trevor] ERROR pref_error error 1 (Error occurred while loading preferences.); OCCURRED AT rstudio::core::Error rstudio::session::prefs::PrefLayer::loadPrefsFromFile(const rstudio::core::FilePath&, const rstudio::core::FilePath&) src/cpp/session/prefs/PrefLayer.cpp:145; CAUSED BY: json-parse error 1 (An error occurred while parsing json. Offset: 0); OCCURRED AT virtual rstudio::core::Error rstudio::core::json::Value::parse(const char *) src/cpp/shared_core/json/Json.cpp:669; LOGGED FROM: rstudio::core::Error rstudio::session::prefs::Preferences::readLayers() …
> Skip parsing of empty `rstudio-prefs.json` files

- NEWS.md
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/detect-r.ts
Addresses [RStudio Desktop exits silently if started without R installed (Linux/Mac) #14343](https://github.com/rstudio/rstudio/issues/14343)
A message was "almost" being shown but code didn't wait for it and terminated before it ever displayed. Now we wait for it.
Linux (appearance will vary by desktop manager, etc.):
Mac (the real build will have the RStudio icon not the electron icon):
Also fixed another code path where multiple error dialogs would attempt to be shown. A failure in `prepareEnvironment()` would display the above dialog, then the caller would display the following somewhat broken dialog. It reused text from a Windows-only dialog (it has yes/no buttons and would navigate to the R for Windows download site if you clicked Yes). The below dialog didn't do that. Now we show …
> Show error message when starting RStudio on Mac/Linux without R installed

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
Addresses [Next/Prev find in topic buttons in Help pane don't have accessible labels #14347](https://github.com/rstudio/rstudio/issues/14347)
Use the existing `title` text for `aria-label` on these buttons.
- "Find previous"
- "Find next (Enter)"
None
Test per notes in issue.
None
> accessible labels for next/prev find in Help topic pane

- src/cpp/shared_core/FilePath.cpp
- src/gwt/src/org/rstudio/core/client/files/FileSystemItem.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java
This enables Snakemake files to be recognized as Python text. See #11677 (closed as stale before resolving Snakemake part).
Identical approach to #11988. No special consideration is given to Snakemake-specific keywords; this merely registers Snakemake files (.smk and Snakefile) to be treated as Python text.
None.
N/A
N/A
I have signed the Posit ICA.
> Support Snakemake files as Python

- NEWS.md
- src/cpp/session/SessionMain.cpp
Addresses the macOS part of https://github.com/rstudio/rstudio/issues/9815.
Previously, RStudio was attempting to initialize the PATH environment variable as part of the regular R initialization step. However, this happens too late -- we need to initialize the PATH early on in the session startup, so that modifications from `.Renviron` and `.Rprofile` can persist over whatever else we might want to do.
N/A
Test that setting the PATH environment variable within `~/.Renviron` is persisted in the session. This is a macOS-only change.
N/A
> initialize PATH from /etc/paths earlier on in session init

- NEWS.md
- src/cpp/r/RCntxt.cpp
- src/cpp/r/RSexp.cpp
- src/cpp/r/RUtil.cpp
- src/cpp/r/include/r/RCntxt.hpp
- src/cpp/r/include/r/RCntxtInterface.hpp
- src/cpp/r/include/r/RIntCntxt.hpp
- src/cpp/r/include/r/RUtil.hpp
- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/session/modules/SessionRUtil.cpp
- src/cpp/session/modules/environment/EnvironmentUtils.cpp
- src/cpp/session/modules/environment/SessionEnvironment.cpp
- src/cpp/tests/debugger/debugging-14276.R
- src/cpp/tests/debugger/debugging-14306.R
- src/cpp/tests/debugger/debugging-example.R
- src/cpp/tests/debugger/debugging-nested.R
- src/cpp/tests/debugger/debugging-no-srcrefs.R
- src/cpp/tests/debugger/debugging-package-code.R
- src/cpp/tests/debugger/debugging-slider-example.R
- src/cpp/tests/testthat/test-environment.R
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
- src/gwt/src/org/rstudio/studio/client/workbench/codesearch/model/SearchPathFunctionDefinition.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/CodeBrowserHighlightEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/CodeBrowserNavigationEvent.java
Addresses https://github.com/rstudio/rstudio/issues/10664, which appears to have regressed.
Addresses https://github.com/rstudio/rstudio/issues/14306.
Addresses https://github.com/rstudio/rstudio/issues/14276.
QA note: it's possible that this issue may only occur with the latest release of R; perhaps older versions of R are fine?
Similar to the last fix, tighten up the checks on whether two contexts can be considered equal.
N/A
This PR adds a number of files for manual testing of the debugger, located in the RStudio repository at `src/cpp/tests/debugger`. The intention here is that these files can be opened in RStudio, and one can follow the instructions in each file to test various debug cases.
N/A
> check callflag when comparing contexts

- NEWS.md
- src/cpp/tests/debugger/debugging-cmd-enter.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
Addresses https://github.com/rstudio/rstudio/issues/13925.
When code is executed via Cmd + Enter, its original source file is lost. However, the function definitions themselves do retain source references so we can retain the original textual definition of that code. When such code is available, we now try matching that against code available in documents already open in RStudio. If we find a match, we choose to open that document as the debug context, instead of using the code browser with a separate read-only view of the debugged code.
In the example below, I execute code via Cmd + Enter, and then step through the debugger with `n` in the usual way.
https://github.com/rstudio/rstudio/assets/1976582/2af78e54-29be-4c59-8440-4bd5acc31cc1
Not included. …
> infer document source from debugged srcref

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCopilotHelper.java
Addresses https://github.com/rstudio/rstudio/issues/13686.
Addresses https://github.com/rstudio/rstudio/issues/13987.
Addresses https://github.com/rstudio/rstudio/issues/13432.
Copilot will occasionally include chunk end markers as part of its completion results. When produced, we now just trim those indiscriminately, under the assumption that users would only ever want completion results specific to the current chunk / context.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13686.
N/A
> trim chunk markers from copilot completions

- docs/news/_quarto.yml
Following on from the quarto features for the IDE User Guide, enable the copy-button and breadcrumbs in search of the news / release notes page.
See #14069 and #13618
Update the _quarto.yml file to enable these search features for news / release notes.
N/A
Review the Release Notes search results once this is deployed.
Implementing requested features for search in the Release Notes docs site.
> Add search copy-button and breadcrumbs to News site

- jenkins/Jenkinsfile.pull-request
There's a bunch of Slack threads about this since we added code scanning. I think I've figured it out.
There's a big in the snyk code scan where it'll diff against main indiscriminately, which means it picks up and scans files that it shouldn't if main has changed since opening the commit. It should actually be diffing against the commit ancestor of main and HEAD in order to avoid this.
It looks like this triple dot syntax `{branch}...HEAD` is a shorthand for `git merge-base {branch} HEAD`. My testing indicates that this is the case. I've purposely branched off from an older commit to see if this will work.
> Fix snyk code scan scanning irrelevant files

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/quarto/QuartoConnection.java
Addresses https://github.com/rstudio/rstudio/issues/14325.
Some versions of Quarto fail to expand the `inputFile` template parameter. Since we know the source file in these instances, use that for the resulting navigation.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14325.
N/A
> work around un-expanded quarto template

- NEWS.md
- src/cpp/session/modules/SessionPackages.R
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/Packages.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackagesServerOperations.java
Addresses https://github.com/rstudio/rstudio/issues/14282.
We had a few code paths which used `available.packages()` when attempting to build a package's set of recursive dependencies. However, strictly speaking, that is not the correct approach as the currently-installed packages might not match whatever is currently available in the user's `getOption("repos")`. Instead, we resolve a package's recursive dependencies by looking at what packages are actually loaded, and what packages are explicitly imported by that package.
For reference, using the test from the original issue:
```
> options(internet.info = 1)
> install.packages("R6", headers = c(Authorization = "Bearer test123"))
Installing package into '/Users/kevin/Library/R/arm64/4.3/library'
(as 'lib' is unspecified)
* WARNING: failed …
```
> avoid using available.packages() when checking loaded dependencies

- src/cpp/session/modules/SessionRCompletions.R
Follow-up to #14199 
Avoid showing 'fake' aesthetics. ggplot2 uses this internally to specify that the geom only accepts one or the other.
Remove aesthetics containing `|` from completions.
I have sourced the file in my R session, and with this patch, I don't see the x|y completion.
N/A
Should not show aesthetics with  `|` 
NA 
I have signed the agreement.
> Exclude aes names containing `|` from completion

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Pick up the latest fixes for Electron 28. This will be the last Electron update we do for Chocolate Cosmos unless something really nasty gets found and fixed in Electron that we absolutely need to take.
https://releases.electronjs.org/release/compare/v28.2.2/v28.2.6
Bump version, install, build, run tests, play with program.
Nothing specific to Electron version.
Chromium version is `120.0.6099.291`.
N/A
> update electron 28.2.2 to 28.2.6

- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectGeneralPreferencesPane.java
Addresses #14390 
Set textbox's ID to `rstudio_proj_display_name`. I confirmed that the label references the new id correctly via `for`.
N/A
N/A
N/A
> provide a fixed id for the project display-name textbox

- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/modules/quarto/SessionQuartoPreview.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/quarto/QuartoConnection.java
Addresses https://github.com/rstudio/rstudio/issues/14277.
- Make sure `sourceFile` is propagated for website projects as well.
- Use this to expand the template item in `srcFile_` where appropriate.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14277.
N/A
> Quarto: expand inputFile template when used / assigned

- src/cpp/session/SessionHttpMethods.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/include/session/SessionConstants.hpp
- src/cpp/session/modules/SessionPackages.R
- src/gwt/src/org/rstudio/studio/client/workbench/model/SessionOpener.java
Addresses https://github.com/rstudio/rstudio/issues/14404.
My previous PR inappropriately made use of `getNamespaceInfo()`, which requires the associated package to be loaded (and loads the package if not -- quite undesirably in the case of `install.packages()`!)
The fix here uses the package's installed metadata to learn about the package's dependencies instead.
Captured by existing automation tests.
Test via notes in https://github.com/rstudio/rstudio/issues/14404.
N/A
> avoid loading namespace when computing dependencies

- NEWS.md
- src/cpp/core/terminal/PrivateCommand.cpp
- src/cpp/core/terminal/PrivateCommandTests.cpp
Addresses #9833
Read the zsh manual page for `HIST_IGNORE_SPACE`. Do what it says.
When the terminal is idle, a "hidden" command is executed to capture and save the shell's environment so it can be restored if the session is suspended and later resumed. Terminal shells run as children of the session, so they go away when the session is suspended.
This hidden command isn't intended to show up in the terminal's command history (e.g. when you hit the up-arrow), and we do this for `zsh` by passing the `-g` flag (to enable HIST_IGNORE_SPACE). This causes commands with a leading space to be omitted from command history.
However from the man page, which apparently I didn't read closely:
> HIST_IGNORE_SPACE (-g)
> Remove command lines from the history list when the first character on the line is …
> stop showing hidden command in terminal history when using zsh

- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/session/session-options.json
Addresses https://github.com/rstudio/rstudio/issues/13718.
Add a session option allowing for the use of a custom certificates file with Copilot, via the `NODE_EXTRA_CA_CERTS` environment variable. Note that this is documented here: https://nodejs.org/api/cli.html#node_extra_ca_certsfile
N/A
Not sure -- do we have an environment with custom certificates wherein we could test this?
Documentation to be added separately.
> allow for custom certificates file for use with copilot

- src/cpp/r/include/r/session/RSession.hpp
- src/cpp/r/include/r/session/RSessionState.hpp
- src/cpp/r/session/RInit.cpp
- src/cpp/r/session/RSessionState.cpp
- src/cpp/r/session/RStdCallbacks.cpp
- src/cpp/r/session/RSuspend.cpp
- src/cpp/session/SessionConsoleInput.cpp
- src/cpp/session/SessionConsoleInput.hpp
- src/cpp/session/SessionMain.cpp
- src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java
- src/gwt/src/org/rstudio/studio/client/application/events/SuspendAndRestartEvent.java
- src/gwt/src/org/rstudio/studio/client/application/model/SuspendOptions.java
- src/gwt/src/org/rstudio/studio/client/common/dialog/DesktopDialogBuilderFactory.java
- src/gwt/src/org/rstudio/studio/client/workbench/model/SessionOpener.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/Packages.java
- src/gwt/test/org/rstudio/studio/client/common/r/RTokenizerTests.java
Addresses https://github.com/rstudio/rstudio/issues/14404.
Addresses https://github.com/rstudio/rstudio/issues/2656.
Previously, when attempting to execute a command after restart, this would be issued by the client after it had received a signal from the new session that it had come alive. This meant that the timing of the execution of that command was somewhat non-deterministic, but it would happen after the vast majority of RStudio's session initialization had completed.
This is problematic for restart commands which install packages, because the act of restoring the old search path could also imply reloading the package which we wanted to install. The fix here is to instead move the responsibility of after restart command execution from the client to the session, and to allow the …
> invoke restart command before restoring search path

- NEWS.md
- src/node/desktop/src/main/detect-r.ts
Addresses https://github.com/rstudio/rstudio/issues/13184.
Conda installations of R include a patch which effectively disables the `etc/ldpaths` script, which causes issues for RStudio when loading `libR.so`.
Depending on whether https://github.com/conda/conda/issues/1679 is still a problem or not, we might need to unset `LD_LIBRARY_PATH` after starting R, so that attempts to run tools like `/bin/sh` don't run into trouble when loading libraries from the Conda environment... but let's just solve one bug at a time.
The alternate solution here, I think, would be to set `LD_PRELOAD` to point at the appropriate `libR.so` that we want to load.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13184.
N/A
> ensure LD_LIBRARY_PATH set when starting conda R

- src/cpp/r/R/Tools.R
- src/cpp/r/include/r/session/RSessionUtils.hpp
- src/cpp/r/session/RSearchPath.cpp
- src/cpp/r/session/RSearchPath.hpp
- src/cpp/r/session/RSessionState.cpp
- src/cpp/r/session/RStdCallbacks.cpp
- src/cpp/session/SessionHttpMethods.cpp
- src/cpp/session/modules/jobs/ScriptJob.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/model/SessionOpener.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java
Addresses https://github.com/rstudio/rstudio/issues/14419.
The restart command got lost in the refactor here; this PR brings it back.
Also fixes an issue that cropped up due to the change in sequencing of restart commands -- since a restart command might load a package, and that load will happen before the search path is restored, we need to ensure that the loaded package is not later unloaded via the attempt to restore the search path.
Captured by existing automation.
N/A
N/A
> ensure restart command passed along from Build pane

- .dockerignore
- dependencies/common/install-node
- dependencies/common/install-node.cmd
- dependencies/common/install-npm-dependencies
- dependencies/common/install-npm-dependencies.cmd
- dependencies/common/patch-node
- dependencies/common/patch-node.cmd
- dependencies/osx/install-dependencies-osx
- dependencies/windows/install-dependencies.cmd
Addresses https://github.com/rstudio/rstudio-pro/issues/6002
Copilot doesn't need the `npm` that's bundled with `node`, so remove it. See the issue for more details.
This happens during dependency installation. We want to be sure the "patch" step always runs against a consistent starting point when installing dependencies so the dependency scripts always delete and redownload `node` before running the patch step. This ensures that official builds will always pick up any patches (e.g. if we add new ones in the future).
None
Confirm that the folder `node/lib/node_modules/npm/` in the node.js we install with the product (desktop and server) is absent, and sanity check that Copilot is still functioning.
N/A
> Strip out unused npm from node.js used by Copilot

- NEWS.md
- src/cpp/r/session/RStdCallbacks.cpp
Addresses #14420.
When console input is truncated, warn the user. We explicitly write directly to stderr, instead of using R `warning()`, just to avoid potentially stepping on existing calling handlers or affecting any R runtime state.
N/A
To test, try sending this to the console in RStudio:
```
"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa …
```
> warn user when console input would be truncated

- NEWS.md
- src/cpp/session/modules/SessionHelp.R
Addresses https://github.com/rstudio/rstudio/issues/13344.
Validate that we do indeed have an R function before attempting to retrieve its arguments. This is necessary as not all help topics are associated with functions -- some might instead by S4 classes, or be unrelated to any R object at all.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13344.
N/A
> validate we have a function before attempting to get signature

- scripts/clean-rstudio
- scripts/clean-rstudio.bat
Update `clean-rstudio` (Mac/Linux) and `clean-rstudio.bat` (Windows) to delete Copilot cache and publishing connections.
These are purely for manual use, possibly only by me, but I use them frequently.
> clean-rstudio utility script: delete publishing connections and Copilot

- src/cpp/session/SessionHttpMethods.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/SessionOfflineService.cpp
- src/cpp/session/include/session/SessionConstants.hpp
- src/gwt/src/org/rstudio/studio/client/workbench/model/SessionOpener.java
Addresses https://github.com/rstudio/rstudio/issues/14432.
When enabled, the offline service thread might attempt to service RPC requests while the session is shutting down. This can lead the the offline service thread handling a "ping" request from the client that is actually intended for the next incoming R session.
This PR just makes sure we stop the offline service thread whenever the session is about to be suspended.
N/A
N/A
N/A
> stop offline thread when suspending sessions

- NEWS.md
- src/cpp/session/modules/SessionObjectExplorer.R
Bug fix of #14439 
Use custom viewer without errors.
no new test added
How to validate the change.
- Define custom class object
```
test_obj <- new.env(parent = emptyenv())
test_obj$a <- "b"
test_obj$c <- "d"
class(test_obj) <- "CustomViewerObj"
as.list.CustomViewerObj <- function(x, ...) {test <- as.list.environment(x, ...); test$c <- NULL; test}
```
- Define custom viewer for this class 
```
rs$.rs.explorer.inspectorRegistry[["CustomViewerObj"]] <- function(object, context = .rs.explorer.createContext()) {
result <- .rs.explorer.inspectObject(as.list(object), context)
result
}
```
No new documentation added
> Fix validation logic in isValidInspectionResult.

- dependencies/common/patch-node
- dependencies/common/patch-node.cmd
Fix build break on macOS.
Broken symbolic link `npx` causes signing step to fail on Mac builds.
N/A
N/A
N/A
> delete npx artifacts referencing deleted folders

- jenkins/Jenkinsfile.pull-request
This goes into OS first and then merges into pro.
See: https://github.com/rstudio/rstudio-pro/issues/5978
And: https://github.com/rstudio/rstudio-pro/issues/2464
And allegedly: https://github.com/rstudio/rstudio-pro/issues/5618
I have a memory of these tests running at some point because we used to get failures from them. I'm not sure if we want to also add these back into the main builds as well. I think that we can get away with just running them here since there isn't anything platform specific about them.
There was already a script to run the tests in a CI context, so all I had to do was copy one of the existing test steps, change the working directory, and run the script.
> Add homepage tests to the PR pipeline.

- src/node/desktop/src/main/gwt-callback.ts
Addresses [Choose R dialog from global options not showing when R was installed in non-standard location #14456](https://github.com/rstudio/rstudio/issues/14456)
Allow "Choose R Installation" dialog to display from Global Options even if no R installations are found in standard locations. That is allowed during startup (via changes in https://github.com/rstudio/rstudio/pull/14197) but I missed this case from Global Options.
None
Per the issue instructions, you need a Windows machine without any remnants of previous R installations and no previous selection of R in RStudio). If you do an uninstall of R from Add/Remove, check to make sure the actual folders were deleted (e.g. `C:\Program Files\R`) as RStudio may find those and not trigger this scenario.
None
> allow browsing non-standard R installs from global options

- CMakeCompiler.txt
- src/cpp/core/include/core/r_util/RToolsInfo.hpp
- src/cpp/core/r_util/RToolsInfo.cpp
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/modules/ModuleTools.R
- src/cpp/session/modules/SessionBuild.R
- src/cpp/session/modules/build/SessionBuildEnvironment.cpp
- src/cpp/session/modules/build/SessionInstallRtools.R
- src/cpp/session/modules/build/SessionInstallRtools.cpp
- src/cpp/session/modules/clang/RCompilationDatabase.cpp
- src/cpp/session/prefs/UserStateComputedLayer.cpp
Addresses https://github.com/rstudio/rstudio/issues/14453.
Also drops support for the older versions of Rtools used with older versions of R which we no longer support.
Mostly straightforward plumbing of Rtools 4.4 code, which is fortunately very similar to Rtools 4.3.
N/A
Test that you can install R packages from sources when using RStudio with a recent version of R-devel on Windows. (Development builds of R for Windows are available at https://cran.r-project.org/bin/windows/base/rdevel.html)
N/A
> add support for Rtools 4.4, for R 4.4.x

- src/cpp/core/system/Win32System.cpp
Addresses https://forum.posit.co/t/rstudio-cannot-connect-to-r-tried-several-versions/181677.
- Return the computed FilePath even if the `ensureDirectory` request failed.
- Use a fallback in case the Windows API call failed.
N/A
N/A
N/A
> implement fallback when computing user session directory

- NEWS.md
- src/cpp/r/session/RStdCallbacks.cpp
- src/cpp/session/SessionMain.cpp
Addresses https://github.com/rstudio/rstudio/issues/14258.
We were erroneously passing in R's `SA_TYPE` save action into our `setSaveAction()`, which instead requires our own alternate encoding of R's "save workspace on exit" option.
Also ensure we synchronize this setting on startup, after the session has finished initialization.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14258.
N/A
> fix issue with sync of R save action

- jenkins/Jenkinsfile.pull-request
It looks like I introduced a bug in the homepage tests script runner in the PR build. I'm not sure why it worked fine on the pro repo when I was testing it and now it's not, but I suspect it's because the deps weren't installed. I'm hoping that installing the node deps will resolve it.
> Add `npm ci` before homepage tests script to attempt to fix

- src/cpp/session/modules/environment/SessionEnvironment.cpp
Addresses https://github.com/rstudio/rstudio/issues/14222.
Because we're attempting to iterate through the R global environment directly, we need to guard against immediate bindings. Note that we do something similar here as well:
https://github.com/rstudio/rstudio/blob/dfa5825c5129cc88ccaebfdbcfa61c25a6c018b3/src/cpp/r/include/r/RHelpers.hpp#L43-L59
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14222.
N/A
> guard against immediate bindings

- src/node/desktop/src/native/desktop/desktop.cc
Addresses https://github.com/rstudio/rstudio/issues/14470.
Straight-forward conversion of `\r` to `\n` when converting UTF-16 data on the pasteboard to UTF-8.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14470.
N/A
> convert '\r' to '\n' when fixing up pasteboard

- NEWS.md
- src/cpp/session/modules/SessionPackages.R
Addresses https://github.com/rstudio/rstudio/issues/12648.
- Try to infer the appropriate package NEWS URL based on the repository that the package is actually available from.
- Re-route PPM to CRAN for now, as PPM doesn't support NEWS URLs.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/12648. Also test that the NEWS check works in the Update Packages dialog on Posit Cloud.
N/A
> improve heuristics for inferring package NEWS url

- src/cpp/session/SessionClientEvent.cpp
- src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp
- src/cpp/session/modules/SessionGit.cpp
- src/cpp/session/modules/SessionRSConnect.cpp
- src/gwt/src/org/rstudio/studio/client/application/events/DeploymentRecordsUpdatedEvent.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectPublishButton.java
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
Addresses https://github.com/rstudio/rstudio/issues/13855.
Use the project file monitor to detect changes to files in the `rsconnect` directory. Upon change, fire a (debounced) client event triggering an update of the publish button and its cached deployment list.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13855.
N/A
> rebuild publish button when deployment records updated

- src/cpp/r/R/Tools.R
Suppress an unnecessary warning on startup with a non-installed package. I couldn't reproduce this very reliably, but I am confident this produces warnings where they are not needed.
It happened during load time with a package that was not installed for me.
An alternative would be to try to use `pkgload::pkg_version()`
```r
.rs.addFunction("getPackageVersion", function(packageName)
{  
version <- suppressWarnings(utils:::packageDescription(packageName, 
fields = "Version"))
if (!is.na(version)) {
return(package_version(version))
}
if (requireNamespace("pkgload", quietly = TRUE)) {
return(tryCatch(pkgload::pkg_version(), error = function(e) NA))
}
NA
})
```
Suppress warning 
As a background
```r
utils::packageDescription("notinstalled")
#> Warning in  packageDescription("notinstalled") : …
```
> Suppress package version warning

- src/cpp/session/modules/SessionCopilot.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/copilot/model/CopilotResponseTypes.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCopilotHelper.java
- Don't allow Copilot to see hidden / "secret" files, even if they're open in an editor buffer.
- Don't attempt to request completions in hidden / "secret" files either.
> further restrict Copilot completion requests in hidden documents

- jenkins/Jenkinsfile.pull-request
Alright here we go again. I'm trying this by moving the tests after the build because the build also installs the `npm` dependencies for the homepage. We definitely can't run `npm` before the test script because we don't have access to `npm` without doing path acrobatics. The script does the necessary path acrobatics.
> third time's the charm

- src/gwt/src/org/rstudio/core/client/JsVector.java
- src/gwt/src/org/rstudio/core/client/JsVectorBoolean.java
- src/gwt/src/org/rstudio/core/client/JsVectorInteger.java
- src/gwt/src/org/rstudio/core/client/JsVectorNumber.java
- src/gwt/src/org/rstudio/core/client/JsVectorString.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
Addresses https://github.com/rstudio/rstudio/issues/14510.
Explicitly exclude "spelling" lint from the gutter annotations we prepare.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14510.
N/A
> don't include spellcheck items in gutter

- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
Addresses #14514.
The intention in this code was to perform a fuzzy search based on the first line of `currentBrowseSource_`, but we ended up subsetting the wrong variable. Doh.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14514.
N/A
> fix thinko when searching for approximate debug location

- src/cpp/session/modules/SessionRCompletions.R
Have these functions only display directories, like `.list.files()` and friends.
What you get when completing the first argument of `setwd()`
Added the prefixed `fs::` to make it work with and without prefixing. 
Add functions to list of dir only functions (both prefixed and not prefixed to make sure it works.
Used those functions as a baseline (except for `dir_create()` https://fs.r-lib.org/articles/function-comparisons.html#directory-functions
NA
Check that they complete as expected
Seems minor?
Signed contributor agreement.
> Enable directory only autocompletion for fs dir functions

- src/gwt/acesupport/acemode/r_highlight_rules.js
- src/gwt/acesupport/acemode/utils.js
- src/gwt/acesupport/acemode/yaml_highlight_rules.js
Addresses https://github.com/rstudio/rstudio/issues/14544.
Addresses https://github.com/rstudio/rstudio/issues/14545.
For R Markdown documents (and other multi-mode documents), when we embed the highlight rules for a particular language in a chunk, we did so under the assumption that only one single set of language highlight rules could exist in that chunk. This was no longer true with some of the changes we made to support Quarto YAML highlight rules, since we now have:
Markdown => R => YAML
And so if we encountered a chunk end marker while we were in the YAML highlight state, we would only pop a single state, hence placing us back into the R state (rather than the top-level Markdown state).
The fix here is fortunately straightforward: save the state we were in when we entered the chunk, …
> support exit from nested state in chunk

- src/gwt/src/org/rstudio/core/client/JsVectorBoolean.java
- src/gwt/src/org/rstudio/core/client/JsVectorInteger.java
- src/gwt/src/org/rstudio/core/client/JsVectorNumber.java
- src/gwt/src/org/rstudio/core/client/JsVectorString.java
Address recently introduced GWT compilation warnings introduced by [don't include spellcheck items in gutter #14512](https://github.com/rstudio/rstudio/pull/14512).
These were also being flagged as a warning in VSCode (yellow underline).
```
[javac] /Users/garyritchie/rstudio/src/gwt/src/org/rstudio/core/client/JsVectorString.java:75: warning: [unchecked] unchecked call to test(T) as a member of the raw type Predicate
[javac]          if (predicate.test(value))
[javac]                            ^
[javac]   where T is a type-variable:
[javac]     T extends Object declared in interface Predicate
[javac] /Users/garyritchie/rstudio/src/gwt/src/org/rstudio/core/client/JsVectorInteger.java:75: warning: [unchecked] unchecked call to test(T) as a member of the raw type Predicate
[javac] …
```
> fix GWT compilation warnings

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
Addresses a JavaScript exception that can be emitted when a document contains spelling mistakes, as well as other diagnostic errors.
Recent changes in this code separated out lint that we wanted to display in the gutter, versus lint that we wanted to display inline with Ace markers. However, the loop here assumed that both 'lint' and 'annotations' were still congruent, which they were not. See:
https://github.com/rstudio/rstudio/commit/bba6d24eb6c08516e4a8db9acfe05209e2c15832#diff-5e04b14bd6bfc6ef2e66daaf607100cdfe1a4c4e96edacfec1352316a4d6dff0R1221-R1231
N/A
Double-check that this change does not affect the display of spelling errors, or R diagnostics, within the editor.
N/A
> fix issue with iterating over lint items

- src/cpp/session/modules/SessionRCompletions.R
Addresses https://github.com/rstudio/rstudio/issues/14586.
Instead of just discarding aesthetics separated via `|`, split on that delimiter and then include + drop duplicates after.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14586.
N/A
> avoid potentially discarding aesthetics

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
This is to work around an issue where our Desktop Pro version numbers break the Windows build. See https://github.com/rstudio/rstudio-pro/issues/6242 for more details.
> pin electron-forge and electron-packages to older versions

- docs/news/index.qmd
As part of the release process, we were supposed to remove the "doc only release" icon `<i class="bi bi-info-circle-fill" title="Documentation change since last release/patch."></i>` from the news file.
We should add this to the release checklist if it can't be automated. …
> Remove doc-only release icon from release notes

- .github/ISSUE_TEMPLATE/1_bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- CONTRIBUTING.md
- README.md
- src/cpp/session/resources/help_resources/index.htm
Forum domain changed from community.rstudio.com to forum.posit.co, update links as necessary. All links tested through VS Code clicks
> Switch forum references to forum.posit.co

- package/win32/make-package.bat
Addresses [obsolete npm usage in Windows build #14599](https://github.com/rstudio/rstudio/issues/14599)
Remove the failing call to `npm set msvs_version 2019` as it is no longer supported or necessary. This gets rid of the (non-fatal) error message during Windows builds.
NA - purely a build-time thing
NA - purely a build-time thing (it works or it doesn't work)
NA
> remove obsolete set msvs_version 2019

- NEWS.md
- src/gwt/src/org/rstudio/core/client/files/filedialog/PathBreadcrumbWidget.java
- src/gwt/src/org/rstudio/studio/client/application/Desktop.java
Addresses [Go to directory... not opening Go to folder dialog #14501](https://github.com/rstudio/rstudio/issues/14501)
On Linux desktop the IDE defaults to using the web-based file dialogs (e.g. for choosing files and folders) due to a long-standing Electron bug where file dialogs sometimes open behind the main window: https://github.com/electron/electron/issues/32857. There is a user preference for changing this back to the native dialogs under General/Advanced:"Use native file and message dialog boxes".
The handler for the "..." button at the end of the path breadcrumb component wasn't aware of the possibility of desktop using web-based dialogs, so added a check for that.
On desktop, with web-based dialogs selected, clicking that button will now bring up this dialog (same as on Server): …
> fix go-to-directory button in web-based file dialogs

- docker/jenkins/Dockerfile.bionic
- docker/jenkins/Dockerfile.focal
- docker/jenkins/Dockerfile.jammy
- docker/jenkins/Dockerfile.opensuse15
- docker/jenkins/Dockerfile.rhel8
- docker/jenkins/Dockerfile.rhel9
A couple of changes were made to the Dockerfiles on the pro-side, but not on the open-source side.
* [Feature/replace lib user calls #6075](https://github.com/rstudio/rstudio-pro/pull/6075)
* [add safe directory config to dockerfiles](https://github.com/rstudio/rstudio-pro/commit/8c3765e8366e8882d91af71a7cf88928c7c78773)
Confirmed with @MariaSemple that these changes are fine to be in open-source, and copied them over.
The build pipeline would be happy to test this change for us.
NA
NA
> keep dockerfiles in sync between open-source and pro

- src/cpp/core/include/core/http/AsyncClient.hpp
- src/cpp/core/include/core/http/LocalStreamAsyncClient.hpp
Seen in load tests, there seems to be a race condition where the local stream returns permission denied errors once in a long while.
This PR changes the code so it will retry a permission denied error once.
Reviewed in: https://github.com/rstudio/rstudio-pro/pull/6245
> Fix for very intermittent error when connecting using local stream

- docker/jenkins/rstudio-version.sh
A default PATCH value in the script was causing the versioning script to ignore the value in `version/PATCH`, causing CC builds to continue building with 2024.04.0 instead of 2024.04.1 versioning. Removing the default value fixes this.
> rstudio-pro git:(rel-chocolate-cosmos) $ ./docker/jenkins/rstudio-version.sh
2024.04.1+743.pro4
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent …
> Remove PATCH default value in versioning script

- src/cpp/session/modules/SessionRCompletions.cpp
- version/news/NEWS-2024.04.1-chocolate-cosmos.md
Surgical fix for https://github.com/rstudio/rstudio/issues/14625, intended for patch release.
Avoid using the wrong `alnum()` defined in StringUtils.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14625.
N/A
> avoid accidental usage of wrong isalnum

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
Addresses [Refresh find button is not disabled when stop replace is visible, allowing the user to crash RStudio #13873](https://github.com/rstudio/rstudio/issues/13873)
`view_.setStopReplaceButtonVisible(true);` is hiding the refresh button, but `stopAndClear()` puts it back. So, reverse the order of these calls.
None.
When running a "Replace All" in the find-in-files pane, the refresh button (the circular arrow) will now be hidden.
I couldn't reproduce the reported crash when clicking this button during a replace-all, perhaps because the replace operation was too quick for me to click it in time. Now the button is hidden, so can't be clicked, so don't know that it's worth trying to reproduce the actual crash.
NA
> Hide refresh button while replace-all operation is running in Find in Files pane

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
- src/node/desktop/test/unit/native/desktop.test.ts
Bump electron from 30.0.1 to 30.0.2 to pick up latest bug and security fixes.
Update version, build, run unit test, quick sanity tests.
This Electron includes Chromium 124.0.6367.91.
A unit test that I had to change when I upgraded to 30.0.1 now goes back to behaving the way it was before, which seems like a good thing.
Electron unit tests are passing.
General usage is sufficient for testing (which is why I like to get these minor electron updates in as early as possible).
NA
> update to electron 30.0.2

- NEWS.md
- src/cpp/session/modules/SessionFiles.cpp
Addresses [RStudio copyTo operation removes file if src = target and 'overwrite' is true #14525](https://github.com/rstudio/rstudio/issues/14525)
If the source and destination are the same (after paths have been canonicalized) treat the "copy to" as a successful no-op rather than deleting the file!
None
Test as described in issue. Also try creating a link (symbolic or hard) to the file and make sure it is still a no-op (i.e. recognizes that these are actually the same file).
NA
> Prevent file deletion when attempting to copy a file over itself in File pane

- src/cpp/core/MiscellaneousTests.cpp
- src/cpp/core/include/core/Truncating.hpp
- src/cpp/core/system/LinuxResources.cpp
- src/cpp/session/modules/SessionRCompletionsTests.cpp
Addresses a Snyk-reported issue in https://build.posit.it/job/IDE/job/OS-Builds/job/open-source-pull-request/job/PR-14644/3/pipeline-console/?selected-node=45.
This PR takes inspiration from https://wiki.sei.cmu.edu/confluence/display/c/INT32-C.+Ensure+that+operations+on+signed+integers+do+not+result+in+overflow, and tries to wrap the compiler builtins described in https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html into a C++ class that we can use more readily.
> guard against potential overflow

- src/gwt/src/org/rstudio/studio/client/application/model/RVersionsInfo.java
- src/gwt/src/org/rstudio/studio/client/application/ui/RVersionSelectWidget.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewProjectWizard.java
Adds machinery to control the default R version shown in the version dropdown widget.
> Open source companion to rstudio/rstudio-pro#5905

- jenkins/Jenkinsfile.linux
This PR intends to hook up our desktop automation tests to the regular build + automation pipeline.
https://build.posit.it/job/IDE/job/rstudio-ide-automation-desktop/job/desktop-ide-ec2-automation/
> run desktop automation tests on build

- src/cpp/core/ProgramOptions.cpp
- src/cpp/r/RSexp.cpp
- src/cpp/r/include/r/RSexp.hpp
- src/cpp/rserver-automation.in
- src/cpp/session/SessionOptions.cpp
- src/cpp/session/modules/automation/SessionAutomation.R
- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/session/modules/data/DataViewer.cpp
- src/cpp/tests/automation/testthat/test-automation-data-viewer.R
- src/cpp/tests/automation/testthat/test-automation-sweave.R
- src/cpp/tests/automation/testthat/test-automation-syntax-highlighting.R
Addresses https://github.com/rstudio/rstudio/issues/14643.
Now that we try to introspect the contents of the observed R object shown in the data viewer, we need to protect that object from the GC.
A basic automation test is included, but unfortunately is not sufficient to capture the underlying crash due to the stochastic nature of the problem.
N/A
N/A
> protect R objects cached for data viewer

- src/cpp/session/modules/SessionAbout.cpp
- src/cpp/session/modules/automation/SessionAutomation.R
- src/cpp/session/projects/SessionProjectContext.cpp
- src/cpp/tests/automation/testthat.R
With this, you can use `.rs.automation.run(ref = "<hash>")` to run the automation tests associated with a specific commit against the currently-running instance of RStudio.
The most common usage will be to use the commit that RStudio was actually built against, e.g. for CI, but being able to customize this may also be helpful locally and in development scenarios.
> provide tools for checking out and running automation tests from ref

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Address #14697
Bumping to latest 30.x Electron release to pickup bug fixes: https://releases.electronjs.org/release/compare/v30.0.2/v30.0.6
> Fixed an inconsistent crash on maximizing window and relayout in Ubuntu. [#42145](https://github.com/electron/electron/pull/42145)
None (yet). I'm going to do that right after this gets merged.
Try the scenario in the issue.
FWIW, I was able to reproduce the crash on the first try on Ubuntu 22 (in Parallels on an M1 Mac), with build `rstudio-2024.07.0-daily-133-arm64.deb`. I was unable to repro with this change built on that same VM.
NA
> upgrade electron from 30.0.2 to 30.0.6

- src/cpp/session/CMakeLists.txt
- src/cpp/session/SessionMain.cpp
- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/modules/SessionDebugging.R
- src/cpp/session/modules/SessionDebugging.cpp
- src/cpp/session/modules/SessionDebugging.hpp
- src/cpp/shared_core/include/shared_core/Error.hpp
This is intended as an internal-use tool, for introspecting running R sessions. Here's a screencast to show the intended use, simulating a "busy" session in some state.
https://github.com/rstudio/rstudio/assets/1976582/22762f53-f71f-486a-84df-1cbf3f939f1c
Effectively, it allows us to drive an `rsession` from LLDB, and capture certain kinds of output in a separate Terminal. This can be useful is the session is frozen or busy, and so console output isn't being reflected in the Console pane in the IDE.
> provide tools for debugging active session remotely

- src/cpp/core/r_util/RActiveSessionsStorage.cpp
Addresses https://github.com/rstudio/rstudio/issues/14734.
I sort of wonder if we should be creating the `storagePath_` in the constructor here, though:
https://github.com/rstudio/rstudio/blob/5a7d837c69879fcc925af346de91101ef8edaa7e/src/cpp/core/r_util/RActiveSessionsStorage.cpp#L118-L123
We do that here:
https://github.com/rstudio/rstudio/blob/5a7d837c69879fcc925af346de91101ef8edaa7e/src/cpp/core/r_util/RActiveSessionsStorage.cpp#L61-L67
> don't attempt to migrate without active sessions dir

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Address #14732 (chocolate cosmos)
Update Electron from 28.2.6 to 28.3.1 to pick up the latest fixes.
Bump version in package.json, regenerated lock file.
Confirmed that the Electron unit tests pass.
Nothing specifically to test; automation and general usage.
NA
> update electron from 28.2.6 to 28.3.1

- package/linux/debian-control/postinst-electron.in
Addresses https://github.com/rstudio/rstudio/issues/14336.
Not sure if we should update NEWS just yet; "opens on Ubuntu 24.04" doesn't quite mean "officially supported on Ubuntu 24.04"?
> set suid bit for chrome-sandbox

- NEWS.md
- dependencies/common/install-mathjax
- dependencies/windows/install-dependencies.cmd
Addresses https://github.com/rstudio/rstudio/issues/11535.
The new MathJax bundle was made by hand with the following steps:
- Download the MathJax release from https://github.com/mathjax/MathJax/releases/tag/2.7.9,
- Use [this script](https://github.com/rstudio/rstudio/blob/feature/mathjax-2.7.9/dependencies/tools/prune-mathjax) to trim out the pieces we don't need,
- Upload to S3,
- Use that download archive where appropriate.
We'll have to double-check that this is sufficient to trigger a rebuild of our Docker images + dependencies so that the newer MathJax is picked up, but I think it should work.
> point dependency scripts at new mathjax

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Update to latest Electron v30 release
Bump version, update lockfile.
Changes from last version: https://releases.electronjs.org/release/compare/v30.0.6/v30.0.8
Confirmed Electron unit tests still pass.
Nothing specific to test.
NA
> update electron from 30.0.6 to 30.0.8

- cmake/globals.cmake
- src/cpp/rstudio-tests.in
- src/cpp/session/modules/quarto/SessionQuarto.cpp
Addresses https://github.com/rstudio/rstudio/issues/14505.
cc: @Enchufa2
The `QUARTO_ENABLED` CMake variable now only controls whether we bundle a Quarto installation with RStudio. We keep the "regular" Quarto machinery turned on, but provide a warning in the situation where someone is running a Quarto-less RStudio but attempts to take some action that requires Quarto.
N/A; to be verified externally.
N/A; to be verified externally.
N/A
> support Quarto enabled without embedded Quarto

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/common/filetypes/CppFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/PlainTextFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/PreviewableFromRFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/PythonFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/RFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/RWebContentFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/ScriptFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/SweaveFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/TexFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/WebContentFileType.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
Addresses https://github.com/rstudio/rstudio/issues/10940.
Use the existing "wrap R source files" preference, but allow it to apply to all of the other editable text file types we support.
I added an enum for the WordWrap value to be set for a particular document, but I can't think of a reason why we might want to force enable or disable wrapping for a particular document type.
Not included; automated testing would likely be challenging since it would depend on things like font size, window size, pane size, and so on.
Test that other files (e.g. `.py`) respect the "Soft wrap source files" preference.
N/A
> enable soft wrapping for other file types

- NEWS.md
- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/tests/automation/testthat/test-automation-quarto.R
- src/gwt/acesupport/acemode/rmarkdown_folding.js
Addresses https://github.com/rstudio/rstudio/issues/14699.
The way editor states are handled when entering + exiting chunks had changes in a way that broke our custom fold rules. The fix here is to instead rely on the token types + values, and explicitly try to detect `codebegin` / `codeend` chunk boundaries, and `heading` Markdown headers.
TODO
Test via notes in https://github.com/rstudio/rstudio/issues/14699.
N/A
> fix issue with end fold widgets

- src/cpp/session/modules/automation/SessionAutomation.cpp
- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/session/modules/automation/SessionAutomationRemoteObject.R
- src/cpp/tests/automation/testthat/test-automation-data-viewer.R
- src/cpp/tests/automation/testthat/test-automation-sweave.R
- src/cpp/tests/automation/testthat/test-automation-syntax-highlighting.R
This PR makes it easier to interact with Javascript objects from R. In particular, this PR introduces a `jsObject` object, which wraps a remote JavaScript object in the current Chromium session, which can then be interacted with via the "regular" R operators. For example:
This lets us write R code that "mimics" the underlying JavaScript code we would normally need to write by hand.
> use wrapper API for interacting with JS objects

- src/cpp/session/modules/SessionHistory.cpp
- src/cpp/session/modules/SessionHistoryArchive.cpp
- src/cpp/session/modules/SessionHistoryArchive.hpp
- src/cpp/session/modules/rmarkdown/NotebookExec.cpp
- src/cpp/session/modules/rmarkdown/NotebookExec.hpp
- src/cpp/session/modules/rmarkdown/NotebookOutput.cpp
A collection of potential resolutions for https://github.com/rstudio/rstudio/issues/14619.
- When executing a chunk, avoid checking for and creating the console output file on each line of output; instead, just create the file once on the first piece of chunk output intended for that file.
- Buffer writes into the history database, using an in-memory buffer that gets flushed 1 second after any output is received.
Should be covered by existing automation.
Would be nice if we could find an environment for testing (proejct living on a slow NFS / CIFS server?)
N/A
> optimize filesystem access in chunk execution

- NEWS.md
- src/cpp/r/R/Api.R
- src/cpp/r/session/RSessionState.cpp
- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/session/modules/build/SessionBuild.cpp
- src/cpp/tests/automation/testthat/test-automation-restart.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/Packages.java
Addresses https://github.com/rstudio/rstudio/issues/14636.
This PR implements support for an '@' prefix in restart commands. Any command with an '@' prefix will be executed "eagerly" (before the search path is restored); other commands will be executed "deferred" (after the search path is restored). This effectively reverts the default behavior for restart commands to the prior RStudio release, but gives us a path to support eager commands as required for package loading + installation.
I chose to encode this information in the restart command itself just to reduce the amount of code churn. Let me know if that feels too gross.
Included.
Test via notes in https://github.com/rstudio/rstudio/issues/14636.
N/A
> support 'eager' and 'deferred' restart commands

- NEWS.md
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/modules/SessionConsole.cpp
- src/cpp/session/modules/build/SessionBuild.cpp
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.hpp
- src/node/desktop/src/assets/locales/en.json
- src/node/desktop/src/assets/locales/fr.json
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/src/ui/error/error.html
- src/node/desktop/src/ui/error/error.ts
Addresses https://github.com/rstudio/rstudio/issues/13088.
The underlying fix here is very simple -- set `R_CLI_NUM_COLORS = 256`, as supported via https://github.com/r-lib/cli/blob/71fd2a58b79b63672d0d52fc69982fd3a6913952/R/num-ansi-colors.R#L45-L47.
The rest of this PR mostly improves the ergonomics of the development cycle on Windows. In particular, this PR lets us rebuild the RStudio R session even while a development instance of RStudio is running. This is accomplished by copying the `rsession.exe` executable to a new location in the same directory, then running that executable instead. This allows us to rebuild and update the original `rsession.exe` while RStudio is running, and then that updated executable will be picked up on session restarts.
In essence, this allows us to rebuild …
> ensure testthat test output is colored appropriately

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/export/ViewerPaneSaveAsImageDesktopOperation.java
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
Addresses https://github.com/rstudio/rstudio/issues/14702.
Since desktop frame invocations are no longer synchronous, we need to sequence their invocations via callbacks.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/14702. Note that the issue is likely to reproduce only stochastically, so it may take a number of tries to reproduce.
N/A
> ensure desktop frame callbacks are properly sequenced when saving page region as image

- NEWS.md
- src/node/desktop/src/main/main.ts
- src/node/desktop/src/main/utils.ts
Addresses https://github.com/rstudio/rstudio/issues/14641.
Check for files at these locations:
- `~/.config/rstudio/electron-flags.conf`
- `~/.config/electron-flags.conf`
Use the first one that exists, and then read lines and apply flags.
Not included; testing was done manually.
One way to test is to do something like this from the terminal (on macOS or Linux)
```
echo "--disable-gpu" > ~/.config/rstudio/electron-flags.conf
```
Then, start RStudio, and check Help -> Diagnostics -> Show GPU Diagnostics. You should see something like:
Next, remove that file, and then restart RStudio. You should see something like:
The specifics may differ from platform to platform; the main thing to note is you shouldn't see any "Hardware accelerated" output with `--disable-gpu` set.
> support electron-flags.conf

- NEWS.md
- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/automation/SessionAutomation.R
- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/tests/automation/testthat/test-automation-completions.R
Addresses https://github.com/rstudio/rstudio/issues/14784.
Check for active bindings in `.rs.getNames()`, and avoid triggering those bindings when requesting object attributes.
Test via notes in https://github.com/rstudio/rstudio/issues/14784.
N/A
> avoid triggering active bindings when completing names in environment

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorMonitor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
Addresses https://github.com/rstudio/rstudio/issues/14664.
Tweak how we check and synchronize the editor scroll speed when the monitor DPI changes.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/14664.
N/A
> fix handling of editor scroll speed

- NEWS.md
- src/gwt/src/org/rstudio/core/client/widget/VirtualizedDataGrid.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesListDataGridStyle.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/view/ObjectExplorerDataGrid.java
Addresses https://github.com/rstudio/rstudio/issues/13426.
A while ago, we built a virtualized GWT data grid for the object explorer. This PR makes use of that same class for the Files pane, allowing us to virtualize the display of a large number of file entries.
This allows the IDE to remain performant even if one attempts to view a directory containing a very large number of files (although the initial file list call may be slow).
TODO: Include some basic interactions with the Files pane.
Test via notes in https://github.com/rstudio/rstudio/issues/13426.
N/A
> use virtualized data grid for Files pane

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
Doesn't fix any specific issues, except that not all things that can be thrown will inherit from Exception (e.g. `assert` gives an `AssertionError` which wouldn't be caught here).
This just helps make sure we do always correctly unset the flag we set here.
> tidying up in Ace change handler

- NEWS.md
- src/cpp/session/modules/SessionDiagnostics.cpp
- src/cpp/session/modules/SessionRParser.cpp
- src/cpp/session/modules/SessionRParser.hpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/LintManager.java
Addresses https://github.com/rstudio/rstudio/issues/9692.
With this change, we no longer attempt to automatically load packages when diagnosing calls of the form `dplyr::mutate()`.
I'm a bit on the fence on what we should do for "explicit" diagnostics requests -- should we inform the user that the package isn't loaded, or should we just load it on their behalf in this scenario, so we can provide accurate diagnostics?
Mostly straightforward changes to the diagnostics engine.
For explicit diagnostics requests, e.g. those triggered via this menu item:
we will provide an "info" diagnostic saying we couldn't provide function diagnostics.
TODO
Test via notes in https://github.com/rstudio/rstudio/issues/9692.
N/A
> avoid loading packages when running diagnostics

- src/cpp/tests/automation/testthat/test-automation-data-viewer.R
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTargetWidget.java
This avoids issues with running this test, where the element could fail to be resolved due to obfuscated GWT classes.
> add (and use) a unique element id for data viewer

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Bump to latest 30.x Electron release.
Changes since last version: https://releases.electronjs.org/release/compare/v30.0.8/v30.1.0
Confirmed that Electron unit tests and the integrated tests pass.
Nothing to specifically test.
> Electron 30.1.0

- NEWS.md
- src/cpp/tests/automation/testthat/test-automation-syntax-highlighting.R
- src/gwt/acesupport/acemode/utils.js
Addresses https://github.com/rstudio/rstudio/issues/14592.
Adjust regex; add automation test.
Included.
Test via notes in https://github.com/rstudio/rstudio/issues/14592.
N/A
> use strict regex for quarto comment prefix

- NEWS.md
- git_hooks/secrets/.secrets.baseline
- src/cpp/session/modules/SessionPlots.cpp
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlotConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlotDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/exportplot/SavePlotAsImageDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/exportplot/SavePlotAsImageOperation.java
- src/gwt/src/org/rstudio/studio/client/workbench/exportplot/clipboard/CopyPlotToClipboardDesktopMetafileDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/exportplot/model/ExportPlotOptions.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/plots/model/PlotsServerOperations.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/export/PlotsPaneSaveAsImageOperation.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/export/ViewerPaneSaveAsImageDesktopOperation.java
Addresses https://github.com/rstudio/rstudio/issues/14727.
This PR introduces a new option for plot generation, "Use device pixel ratio". Here's how the dialog looks, with hover text included.
Not included.
On a machine with a high DPI display, try creating a basic plot with e.g. `plot(1)`. Then, in the Plots pane, use Export -> Save as Image..., and try saving two versions of the plot: one with "Use device pixel ratio" checked, and the other without.
If the checkbox is set, the Plot dimensions should be scaled according to the device pixel ratio (so the inherent width / height of the plot will be increased). If the viewer used to observe the plot is decreased in size, it should then appear as a crisp "high DPI" plot.
N/A
> provide checkbox for using device pixel ratio on plot save

- NEWS.md
- src/cpp/session/modules/SessionFind.cpp
Addresses https://github.com/rstudio/rstudio/issues/14796.
Detect what newlines are used in a file before starting the Find and Replace operation, and use those newlines when running the replace.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/14796.
N/A
> detect and use line endings from file when performing replace

- NEWS.md
- src/cpp/session/modules/SessionPackages.R
Addresses https://github.com/rstudio/rstudio/issues/13399.
When unloading a package prior to installation, also make sure to unload any of its loaded DLLs.
Not included.
On Windows, open a package project, using a package which contains some C / C++ sources. https://github.com/r-lib/rlang is a good example. In that project, try to use the Packages -> Install button to install the package. Try to do this two times in a row -- both attempts should succeed, whereas previously the second attempt would have failed.
N/A
> unload a loaded package DLL if necessary

- NEWS.md
- src/cpp/session/modules/SessionBreakpoints.R
Addresses https://github.com/rstudio/rstudio/issues/14815.
The way R tags expressions with source references appears to have changed in R 4.4.0, in a way that trips up the Shiny debugger. This PR ensures that we ignore source references that aren't relevant to our attempts to add debug breakpoints.
Not included, but this would be nice to have.
With this Shiny application:
```r
library(shiny)
ui <- fluidPage(
titlePanel("Old Faithful Geyser Data"),
actionButton("debugButton", "Debug")
)
server <- function(input, output) {
observeEvent(input$debugButton, {
1 + 1
2 + 2
3 + 3
4 + 4
5 + 5
})
}
shinyApp(ui = ui, server = server)
```
Put this into a file called `app.R`, and save it. Then, try placing breakpoints on the lines like `2 + 2`, and run the application via the Run App button. In the …
> avoid recursing into srcrefs not associated with a body / expression

- NEWS.md
- src/cpp/session/modules/SessionBreakpoints.R
- src/cpp/session/modules/SessionBreakpoints.cpp
Addresses https://github.com/rstudio/rstudio/issues/14682. I suspect this regressed as part of the work in https://github.com/rstudio/rstudio/pull/14360, although I'm not sure of the exact change.
Re-implement the in-sync checks in R, using the tools built for reading and parsing source references in https://github.com/rstudio/rstudio/pull/14360. I wanted to avoid changing `environment::functionDiffersFromSource` just to keep risk of regression lower.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14682. In particular, I believe the issue here is that if you:
1. Source a file, and then
2. Attempt to add breakpoints to the function after-the-fact
then RStudio will complain that the function needs to be sourced first. This PR fixes that behavior.
N/A
> fix check for 'in-sync' function when adding breakpoints

- NEWS.md
- src/node/desktop/src/renderer/desktop-bridge.ts
Addresses https://github.com/rstudio/rstudio/issues/14851.
This PR resolves a small infelicity from the port to Electron. We weren't creating aliased paths in 'getOpenFileName', leading to "full" paths when selected in dialogs like the following:
This PR ensures that such paths are properly aliased, as they were in the Qt builds of RStudio.
https://github.com/rstudio/rstudio/blob/ce38002964824bf3cfdc7f0cbd9c42173f91147f/src/cpp/desktop/DesktopGwtCallback.cpp#L248
Mostly straightforward use and resolution of user home path, using existing IPC methods.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14851.
N/A
> resolve aliased paths in getOpenFileName

- NEWS.md
- src/cpp/session/modules/SessionRParser.cpp
Addresses https://github.com/rstudio/rstudio/issues/14713.
The diagnostics system needs to evaluate symbols and calls in certain scenarios in order to provide diagnostics. Avoid evaluating `_`, since that's only ever used in pipebind expressions (which RStudio currently does not support).
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14713.
N/A
> avoid evaluation of pipe placeholders

- NEWS.md
- src/cpp/r/R/Tools.R
- src/cpp/session/modules/ModuleTools.R
- src/cpp/session/modules/SessionGit.cpp
- src/cpp/session/modules/SessionPythonEnvironments.R
- src/cpp/session/modules/SessionUserPrefs.cpp
Addresses https://github.com/rstudio/rstudio/issues/14861.
Addresses https://github.com/rstudio/rstudio/issues/14659.
When "Automatically activate project-local python environments" was set, we were putting Python on the PATH even if it wasn't a project-local Python. This PR adjusts that behavior, and also adjusts the precedence of Python usage. The precedence is now:
1. An explicitly-configured project Python instance,
2. When enabled, an implicitly-discovered project Python environment,
3. An explicitly-configured global Python instance.
Note that environment variables like `RETICULATE_PYTHON` remain as overrides.
N/A
In addition to the notes in the associated issues, you can test that:
```
Sys.getenv("PATH")
```
reports the same value before and after building a package in an R package …
> only put Python on PATH when explicitly configured by user

- src/cpp/session/SessionPandoc.cpp
- src/cpp/session/include/session/SessionModuleContext.hpp
To help support builds of RStudio on e.g. Fedora which use external builds of Quarto / pandoc.
Possibly related to https://github.com/rstudio/rstudio/issues/10823.
> use pandoc from PATH if not bundled

- src/cpp/session/projects/SessionProjectContext.cpp
- src/cpp/session/projects/SessionProjects.cpp
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
- src/gwt/src/org/rstudio/studio/client/projects/StudioClientProjectConstants.java
- src/gwt/src/org/rstudio/studio/client/projects/model/RProjectConfig.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectGeneralPreferencesPane.java
This PR allows users to customize the project scratch path used by RStudio for any projects they open. (Typically, this is the `.Rproj.user` folder within a project.)
Addresses: https://github.com/rstudio/rstudio/issues/14778, https://github.com/rstudio/rstudio/issues/7131, https://github.com/rstudio/rstudio/issues/14619
This is implemented by allowing for a file located at:
```
.Rproj.user/<userContextId>/scratch-path
```
This path contains a file, which itself is the external location of the `.Rproj.user` directory. Conceptually, it's a symlink, but we handle the path resolution by hand to avoid platform-specific concerns.
This file is read on start-up when resolving the scratch path, and can be set by the user via the project options dialog.
Note that both the user-specific and shared …
> allow customization of project scratch path location

- src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.ui.xml
Addresses #14886
Add a word (and two commas) to a string.
NA
Stare at the About dialog for at least 3 seconds and make sure the new text doesn't vanish.
NA
> include Quarto in about dialog trademark list

- docs/user/rstudio/ide/guide/tools/copilot.qmd
Addresses [Docs: GitHub Copilot free for students and faculty #14302](https://github.com/rstudio/rstudio/issues/14302)
Added same text in two places: (1) prerequisites near beginning of page and (2) "support and terms of service" near end of page.
> Students and faculty can use GitHub Copilot for free as part of the GitHub Education program. For more information, see the [GitHub Education page](https://education.github.com/).
NA
Copilot page in user guide
Yes it is
> document GitHub Education program for Copilot

- src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleInterpreterVersion.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleInterpreterVersion.java
Addresses https://github.com/rstudio/rstudio/issues/11613. Adds a dropdown arrow next to the interpreter selection button.
> add a dropdown arrow

- src/cpp/r/RExec.cpp
- src/cpp/r/include/r/RExec.hpp
- src/cpp/r/session/RSessionState.cpp
Addresses https://github.com/rstudio/rstudio/issues/14636#issuecomment-2165908592.
Previously, restart commands were executed via a basic "send to console" RPC request. However, now that we're trying to sequence command execution (and output) during session restore, we need to more manually take control of console input + output presentation in the console. This PR attempts to accomplish that.
This PR makes use of:
- `base::try()`, which allows us to catch R errors and avoid longjmps past our C++ stack frames;
- `base::withVisible()`, which captures an R result with a "visible" flag which lets us know if R would have printed that result in a "regular" REPL execution.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/14636#issuecomment-2165908592.
N/A
> ensure output from restart commands is printed appropriately

- src/cpp/server_core/system/Pam.cpp
Addresses: https://github.com/rstudio/rstudio/issues/12116
It's up to the PAM system to decide to accept or reject the PAM operation and returning error fails the login, even if there's an optional (sufficient) step that returns an error
See the issue for a test case.  On the rhel8 system, the rserver-pam caused a segfault and on ubuntu20, it just did not allow the login. We should make sure to test this on both rhel8 and debian just because it's so system specific. 
Look in /var/log/auth.log and /var/log/{syslog,messages}
> PAM callback should not return error for error msg

- src/cpp/core/system/PosixSystem.cpp
- src/cpp/core/system/User.cpp
- src/cpp/core/system/Xdg.cpp
- src/cpp/session/SessionClientInit.cpp
- src/cpp/session/modules/SessionCopilot.cpp
- removed error for EPERM when resetting keyring: https://github.com/rstudio/rstudio-pro/issues/6444
- removed user cache and xdg debug messages since they show up at weird times like in rserver-launcher that go to stderr and look like errors in the application
For the XDG messages, I believe we should log the location of the config file once it's found, rather than the search process.
- Added debug messages for the all important client_init request
- The session copilot messages are useful, but only log them once by keeping track of whether we've initialized it or not.
removed one error, added two new debug logs, and removed a number of debug logs. No code logic changes. 
Automation should cover these changes
> Clean of some diagnostics in OS

- NEWS.md
- src/node/desktop/.vscode/settings.json
- src/node/desktop/src/core/file-path.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/preferences/electron-desktop-options.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
- src/node/desktop/src/ui/utils.ts
- src/node/desktop/test/unit/core/file-path.test.ts
- src/node/desktop/test/unit/main/desktop-options.test.ts
Addresses [Cannot save files to certains paths that worked in previous release #14764](https://github.com/rstudio/rstudio/issues/14764)
Note, this has been broken since the move to Electron.
Our test to see if a path was in the user's home folder relied on a `startsWith()` check that didn't take into account the possibility of something like:
- home folder: `/Users/gary`
- folder containing files to save/load: `/Users/garywashere`
When asked to alias `/Users/garywashere` our old code would return `~washere` leading to i/o errors.
As part of the fix I consolidated duplicate implementations; we had some in `FilePath` class (which uses node.js thus can't be used from the renderer process), and some in `ui/util.ts` and `desktop-bridge` (both of which cannot use node). Moved the common …
> Fix file save/load issues in Desktop with certain folder combinations

- src/cpp/session/resources/R.css
Addresses https://github.com/rstudio/rstudio/issues/13204.
> use more prominent background highlight color

- NEWS.md
- src/gwt/acesupport/acemode/r_scope_tree.js
Addresses https://github.com/rstudio/rstudio/issues/14906.
As far as I can see, this change resolves the above issue, and (from some manual testing) doesn't regress anything. The provided code example in comments also seems to function as expected.
Do we think we have enough runway to try merging this and see if any issues fall out?
> don't reset 'end' when adding node

- NEWS.md
- src/cpp/session/modules/SessionBreakpoints.R
Addresses #14499.
For S3 methods, R will place a separate copy of that function within the `.__S3MethodsTable__.` table for the package's namespace. Unfortunately, because it's a copy, mutating the function body for the version that lives in the package namespace doesn't also mutate the version in the methods table. It seems like this might be something that's changed in recent versions of R, given that this code hasn't changed in many moons.
Not included.
Test via notes in #14499.
N/A
> propagate source references into s3 methods

- jenkins/Jenkinsfile.linux
- jenkins/utils.groovy
First half of https://github.com/rstudio/rstudio-pro/issues/6566
After uploading the jammy build to AWS and dailies page, the jammy build will make another entry for noble on the dailies page. Notably, this does not re-upload the same binary to S3. The noble link on the dailies page will instead point to the jammy build already in S3.
N/A Build change
N/A for now. Build change
N/A Build change
> Publish noble builds under their own OS on the dailies page

- NEWS.md
- src/node/desktop/src/ui/utils.ts
- src/node/desktop/test/unit/ui/utils.test.ts
Addresses:
- [Cannot save new file to a UNC path on Windows #14963](https://github.com/rstudio/rstudio/issues/14963)
- [Creating a new project on a UNC path stores it in the wrong location #14964](https://github.com/rstudio/rstudio/issues/14964)
The bug was that calling `normalizeSeparators()` on a UNC path that used forward slashes (i.e. Posix) instead of backslashes would strip off one of the leading slashes. Fixed to handle either type of leading slash.
Added more unit tests around this code.
Test on Windows as described in the issues.
N/A
> UNC path handling fixes in Electron desktop code

- package/win32/make-package.bat
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Addresses [Pro versioning scheme breaks builds for Desktop Pro (Windows) with latest electron-forge version #6242](https://github.com/rstudio/rstudio-pro/issues/6242)
Updated electron-packager to most recent, and tweaked the Windows make-package script to strip off the ".pro#" suffix, if present, to avoid tripping up electron-packager on Windows.
This doesn't impact the version number shown in About dialog or elsewhere; only place impacted is the file version info for binaries such as rstudio.exe, but they cannot store the full version due to limitations with Windows versioninfo resources (hence this issue).
Build-time thing.
Verify that the product version in Help / About is correct on RStudio for Windows for both open-source and pro.
None
> update electron-packager and fix rdp windows build issue

- NEWS.md
- src/cpp/session/prefs/UserPrefsComputedLayer.cpp
Addresses #14683
On Linux Desktop, default to using the native file and message dialogs instead of the web-based ones.
This can still be changed via Global Options / General / Advanced: "Use native file and message dialog boxes"; just the default (for Linux) has been changed.
None, but we are keeping the option to use web-based dialogs largely because they are used by desktop automation, which cannot drive the native dialogs.
Confirm that on Linux desktop you now get the native desktop file and message dialogs (e.g. try opening a file), but can still switch back to the web-based ones if you so desire.
Also be sure these native dialogs are opening above the main RStudio window and not behind it (this was what motivated us to use the web dialogs on Linux: …
> use native dialogs by default on Linux desktop

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Addresses #14982
Update from electron 30 to 31.
This bumps Chromium to `126.0.6478.127`
NA
Verify Electron version in Help / About, otherwise covered by general usage / automation.
NA
> update to electron 31.2.1

- NEWS.md
- src/cpp/session/modules/SessionBuild.R
- src/cpp/session/modules/build/SessionBuild.cpp
Addresses https://github.com/rstudio/rstudio/issues/5793.
When executing R for build pane actions, forward the current repositories. This is done by generating an R script with the requisite code to set the `repos` option, as well as the primary command to be executed. Includes a paranoid fallback just in case script generation fails for some reason (R temporary directory not writable / accessible?)
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/5793.
N/A
> forward repos during build

- package/linux/install-dependencies
Addresses #14994
Add the letter 's'.
This is used in our build pipeline to install cmake in docker images used for building on various Linux distros, so if it fails the build pipeline will tell us.
Nothing to validate.
NA
> use https when downloading cmake in build images

- src/cpp/server/ServerInit.cpp
- src/cpp/server/include/server/ServerOptions.gen.hpp
- src/cpp/server/include/server/ServerOptions.hpp
- src/cpp/server/server-options.json
This PR adds the option `www-socket` to allow `rserver` to listen on a unix socket. 
It extends `httpServerCreate(..)` to create an instance of `http::LocalStreamAsyncServer` beside `http::TcpIpAsyncServer` if `rserver` is asked to connect through a unix socket.
n/a
n/a
n/a
> Adds socket option to rserver

- dependencies/common/install-panmirror
- dependencies/windows/install-panmirror/clone-quarto-repo.cmd
Addresses #15004
I created branches off `main` in quarto-dev/quarto named `release/rstudio-chocolate-cosmos` and `release/rstudio-cranberry-hibiscus`. 
Then update dependency scripts for chocolate-cosmos to use corresponding branch instead of main.
When I merge this change and pull it forward into cranberry-hibiscus, I will change it to point to `release/rstudio-chocolate-cosmos`, and when I merge into `main`, I will leave it pulling from `main`.
Build-time stuff. At this point the two branches (and main) are identical in quarto-dev/quarto, so this is more to cover us once I start making Visual Editor changes (i.e. so they aren't unintentionally pulled into a patch release).
Nothing to specifically test; this should be a no-op in terms of what is actually built and if it isn't should fail …
> pin visual editor for chocolate-cosmos and cranberry-hibiscus

- jenkins/Jenkinsfile.pull-request
If the snyk code scan returned an exit code indicating that no files were scanned, post "skipped" status to the GH check.
> Post skipped status to snyk code scan

- src/cpp/server/db/README.md
- src/cpp/server/db/build-version-dump.sh
Added a script to create the database dump files that are used to ensure each version can be upgraded against each new alter script.
No code changes so no testing required. Not needed for CH.
> Updated instructions for database migration tests

- src/cpp/core/include/core/system/PosixSystem.hpp
- src/cpp/core/system/PosixSystem.cpp
Reviewed in PR: https://github.com/rstudio/rstudio-pro/pull/6658
- Call getUser in the parent process, before the fork and pass in the User object to the child
- after the fork, before the exec, libraries like libnss can misbehave due to locking and other odd behavior when running in a copy of the parent processes memory image.
Reviewed in PR: https://github.com/rstudio/rstudio-pro/pull/6658
> Avoid getCurrentUser call after fork

- src/gwt/src/org/rstudio/core/client/AnsiCode.java
- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
Addresses https://github.com/rstudio/rstudio/issues/14941.
Add support for [CSI escape sequences](https://en.wikipedia.org/wiki/ANSI_escape_code#CSI_(Control_Sequence_Introducer)_sequences); specifically, only for the "cursor forward" and "cursor backward".
Not included.
Try executing `writeLines("Hello world!\x1b[10DLL\x1b[4CRL")`. You should see:
```
> writeLines("Hello world!\x1b[10DLL\x1b[4CRL")
HeLLo woRLd!
```
and this should be the same both in "vanilla" R and in RStudio.
N/A
> support cursor backward, forward CSI codes

- src/cpp/session/modules/automation/SessionAutomation.R
- src/cpp/tests/automation/testthat/test-automation-build-pane.R
- src/cpp/tests/automation/testthat/test-automation-completions.R
- src/cpp/tests/automation/testthat/test-automation-data-viewer.R
- src/cpp/tests/automation/testthat/test-automation-reformat.R
- src/cpp/tests/automation/testthat/test-automation-restart.R
- src/cpp/tests/automation/testthat/test-automation-sweave.R
- src/cpp/tests/automation/testthat/test-automation-syntax-highlighting.R
Resolves a few issues seen when trying to run embedded automation tests on Linux.
> explicitly check for launch failure when running automation

- src/cpp/r/session/RSession.cpp
Fixes an issue where RStudio would crash on startup with recent builds of R-devel.
RStudio was using the `Rf_countContexts()` function to determine if the R debugger was active, but that function is no longer available for us to use as of https://github.com/wch/r-source/commit/7b578a76195292af7577cb13b6d50832ec172a1d.
So instead, we use our own local equivalent.
N/A
N/A
N/A
> Rf_countContexts is now hidden

- jenkins/Jenkinsfile.pull-request
- jenkins/utils.groovy
I noticed we're building on PR whenever there are changes only in version/news. Since that doesn't get compiled into the product, it should be excluded.
1. Add an option to `util.hasChangesIn` that sets `-P` (perl regex) on the grep command when true.
2. Add version/news to the exclude list.
N/A - build system change
N/A - build system change
N/A - build system change
> also skip files in version/news for rebuilding

- NEWS.md
- src/cpp/r/R/Tools.R
- src/cpp/session/SessionSourceDatabaseSupervisor.cpp
- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionPackages.R
- src/cpp/session/modules/automation/SessionAutomation.R
This PR allows RStudio to read and use some of the `usethis` options described in https://usethis.r-lib.org/articles/usethis-setup.html#store-default-values-for-description-fields-and-other-preferences.
The features are mostly bolted on to RStudio's existing package skeleton, to retain support for creating projects with existing source files.
N/A
N/A
> support usethis description + person objects in package skeleton

- src/cpp/session/modules/SessionBreakpoints.R
- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/session/modules/automation/SessionAutomation.R
- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/session/modules/environment/SessionEnvironment.cpp
- src/cpp/tests/automation/testthat/test-automation-debugger.R
Addresses https://github.com/rstudio/rstudio/issues/15072.
- Make sure we handle cases where `linepref` is a zero-length vector, or negative.
- Re-implement the computation of where source references are copied for traced functions.
Automated test included.
Test via notes in https://github.com/rstudio/rstudio/issues/15072.
N/A
> fix debugger in braced expressions

- src/gwt/src/org/rstudio/studio/client/common/r/roxygen/RoxygenHelper.java
This is the template that gets inserted if you call this to insert a skeleton roxygen2 template
This change is because `@return` is superseded by `@returns` in roxygen2. Source: https://roxygen2.r-lib.org/reference/tags-rd.html#ref-usage:~:text=%40return%20%24%7B1%3Adescription%7D%3A%20Describe%20the%20function%27s%20output.%20Superseded%20in%20favour%20of%20%40returns.
Update the template
NA
NA
NA
I signed the CLA.
> Update roxygen skeleton function doc template

- src/cpp/session/modules/SessionPackages.R
Addresses https://github.com/rstudio/rstudio/issues/15086.
Some recent changes were causing RStudio to generate an invalid `DESCRIPTION` file when creating a new package project, leading to RStudio failing to read that file and so failing to determine that the project was an R package project. This PR resolves that.
N/A
N/A
> fix indent for 'authorsDefault'

- package/osx/scripts/package-lock.json
- package/osx/scripts/package.json
Update the package used for creating the Mac universal distribution. The only changes are bumping up the minimum node.js requirement to v16 (we're using v20, so that's fine) and a bug fix to "[ignore differences caused by merged machO files](https://github.com/electron/universal/pull/66)."
I went looking to see if I could find a solution to our intermittent build problem ([Intermittent Mac Desktop build failures due to different SHAs on non-binary files #14773](https://github.com/rstudio/rstudio/issues/14773)). Based on the description of the fix, I don't think this will make a difference, but I am still taking the update since it was missed the last time I updated packages.
Increase package version, `npm update`, `npm i`. Did a test package build locally and it passed.
N/A
Nothing to …
> upgrade @electron/universal package from 1.5.1 to 2.0.1

- src/cpp/core/system/PosixChildProcess.cpp
- src/cpp/session/include/session/SessionQuarto.hpp
- src/cpp/session/modules/quarto/SessionQuarto.cpp
- src/cpp/session/modules/quarto/SessionQuartoXRefs.cpp
Addresses https://github.com/rstudio/rstudio/issues/10823.
This PR fixes two issues:
- The path to Quarto's `pandoc` has changed over time. This PR allows us to search the various locations it can be found.
- When running a child process, if the call to `::exec()` fails, we originally tried to quit using `::exit()`. This is problematic, as it implies that things like static destructors in the parent process will be run -- something we definitely don't want! Instead, we can use `::_exit()` unconditionally.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/10823.
N/A
> improve resolution of quarto's pandoc

- NEWS.md
- src/gwt/www/js/signin.js
Addresses rstudio/rstudio-pro#5392.
I spent some time trying to identify if this issue could have possibly been a regression, but it looks to me like persisting login will have _never_ worked for any login type except for PAM, and only when encrypting the login password via `auth-encrypt-password`. 
The server auth code _should_ pick up the `staySignedIn` form element directly that is present in the existing login forms (no need to set a `persist` attribute in the login form like …
> Don't disable staySignedIn when verifying login form

- NEWS.md
- src/cpp/r/R/Tools.R
- src/cpp/session/SessionClientEvent.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp
- src/cpp/session/modules/SessionRCompletions.R
- src/cpp/session/modules/automation/SessionAutomation.R
- src/cpp/session/modules/automation/SessionAutomation.cpp
- src/cpp/session/modules/automation/SessionAutomation.hpp
- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/tests/automation/testthat/test-automation-completions.R
- src/cpp/tests/automation/testthat/test-automation-sweave.R
- src/gwt/acesupport/acemode/r_code_model.js
- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/application/events/ApplicationEventHandlers.java
- src/gwt/src/org/rstudio/studio/client/application/events/RunAutomationEvent.java
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
- src/node/desktop/src/main/session-launcher.ts
Addresses https://github.com/rstudio/rstudio/issues/13611.
We have some internal logic that attempts to find the lead "data" object from a piped expression. However, this lookup was short-circuiting if the head of the pipe happened to be the first token in the document, but didn't exist at the very first row / column.
Included.
Test via notes in https://github.com/rstudio/rstudio/issues/13611.
N/A
> fix handling of piped completions near start of doc

- NEWS.md
- src/cpp/session/modules/SessionDiagnosticsTests.cpp
- src/cpp/session/modules/SessionRParser.cpp
The recently-released `dotty` R package implements support for destructuring assignments; e.g.
```
.[nr, nc] <- dim(cars)
```
defines variables `nr` and `nc` pulled from the result produced by `dim(cars)`.
For example:
Mostly straightforward extension to existing diagnostics tooling.
Included unit tests.
N/A
> support dotty assignments

- src/cpp/session/modules/automation/SessionAutomation.R
- src/cpp/session/modules/automation/SessionAutomation.cpp
- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/session/modules/automation/SessionAutomationRemoteObject.R
- src/cpp/session/modules/automation/SessionAutomationTools.R
- src/cpp/tests/automation/testthat/test-automation-rmarkdown.R
Learn how to use our built-in automation by writing a test.
Load RMarkdown with several chunks, then verify that the expected widgets are present and have correct visibility.
- Added methods for fetching a list of nodes based on a selector
- Install "styler" package since I didn't have it installed and format tests require it
- Add a place for general automation tools and a method for testing state of `aria-hidden`
Yes
Added a test, nothing else.
NA
> test for chunk widgets displaying in RMarkdown source editor

- NEWS.md
- src/cpp/session/modules/SessionRCompletions.R
- src/cpp/tests/automation/testthat/test-automation-completions.R
Addresses https://github.com/rstudio/rstudio/issues/15115.
When invoking a `.DollarNames` method (if any) for requesting completions on an object, we were incorrectly forcing types on the completion results in all scenarios -- we should only do this in the special case where a completion item contains a trailing parenthesis.
Included.
Test via notes in https://github.com/rstudio/rstudio/issues/15115.
N/A
> fix issue with completion type inferrence with .DollarNames methods

- src/cpp/tests/automation/testthat/test-automation-rmarkdown.R
- src/gwt/src/org/rstudio/core/client/ClassIds.java
- src/gwt/src/org/rstudio/core/client/widget/LatchingToolbarButton.java
- src/gwt/src/org/rstudio/studio/client/dataviewer/DataTable.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/MarkdownToolbar.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Add Tests for switching RMarkdown docs into and out of Visual Mode.
Added some unique IDs, wrote tests.
Yes.
Automation-only change.
NA
> Tests for toggling visual mode

- src/cpp/tests/automation/testthat/test-automation-quarto.R
Add some integration tests for Quarto.
Start with copying the rmarkdown tests; comment out a test that is currently failing due to a known issue.
Yes
Tests only
NA
> quarto variant of rmarkdown tests

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/DefaultChunkOptionsPopupPanel.java
- src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
- src/gwt/test/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/DefaultChunkOptionsPopupPanelTests.java
We have at least two places that implement chunk header parsing:
- `class RChunkHeaderParser`
- `DefaultChunkOptionsPopupPanel.parseChunkHeader()`
I'm not ready to attempt consolidation, but this PR puts some unit tests in place for `DefaultChunkOptionsPopupPanel.parseChunkHeader()` (the other one already has some).
Make the method `public static` and pass in the info needed instead of relying on the class, and return all info instead of setting class members.
Then added tests, essentially identical to those running against  `class RChunkHeaderParser`.
Yes
Refactoring to expose code for unit testing and added such tests.
NA
> refactoring for better testability

- NEWS.md
- git_hooks/secrets/.secrets.baseline
- src/cpp/r/session/RConsoleActions.cpp
- src/cpp/rserver-dev.in
- src/cpp/session/modules/SessionRSConnect.R
- src/cpp/session/modules/SessionRSConnect.cpp
- src/cpp/session/resources/dependencies/r-packages.json
- src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
- src/gwt/src/org/rstudio/core/client/widget/SelectWidget.java
- src/gwt/src/org/rstudio/studio/client/common/HelpLink.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/RSConnect.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/RsconnectConstants.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/model/RSConnectApplicationInfo.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/model/RSConnectApplicationResult.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/model/RSConnectPublishResult.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/model/RSConnectPublishSettings.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/model/RSConnectServerOperations.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.css
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.ui.xml
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectPublishButton.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetRMarkdownHelper.java
Addresses https://github.com/rstudio/rstudio/issues/13032.
Recent releases of `rsconnect` include support for publishing environment variables alongside a particular deployment. This is typically useful for secrets / API keys which the application might need in order to access external web services. This PR adds some basic UI to make this possible. Example:
Note the new `Add environment variables...` button. Clicking that brings up a simple modal dialog:
The names of environment variables are pulled from either the project's `.Renviron`, or from the user `.Renviron`. Currently, names are filtered to those which "look like" secret keys; we might reconsider this design in the future if needed.
After selecting some environment variables and clicking Ok, we add a small blurb to indicate these …
> allow inclusion of environment variables during deployment

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Addresses https://github.com/rstudio/rstudio/issues/11995.
The helper function `isRChunk()` was put together in the old days, before `rmarkdown` and `knitr` supported declaring the engine name directly at the start of a chunk. Because it specifically tried to pull out a chunk option set via `engine =`, it fell to the default behavior of assuming everything was an R chunk.
Note that non-R chunks are still not executed in this mode; I think we're still advocating that users who want all chunks to be executed (even non-R chunks) will need to enable inline chunk outputs?
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/11995.
N/A
> 'Run All' now runs only R chunks in console output mode

- NEWS.md
- src/cpp/core/include/core/r_util/RProjectFile.hpp
- src/cpp/core/r_util/RProjectFile.cpp
- src/cpp/server/include/server/ServerOptions.gen.hpp
- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/projects/SessionProjectContext.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/cpp/session/session-options.json
- src/gwt/src/org/rstudio/core/client/CoreClientConstants.java
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
Addresses https://github.com/rstudio/rstudio/issues/15098.
This PR augments each project's `.Rproj` file with a new ProjectId entry. This entry is just a GUID, but it's used to map to an external `.Rproj.user` folder when the user or administrator has enabled this.
Users can set a default "project user data directory" within Global Options... -> General -> Advanced:
If this value is set, then the project's state is then written to a folder at the path:
```
<projectUserDataDir>/<projectId>
```
instead of just the project's `.Rproj.user`.
The project ID above is generated on demand as a GUID, and stored as part of the project's `.Rproj` file.
Not included.
Using the new UI mentioned above, try setting this directory to some value, e.g. `/tmp/rstudio-data`. Try creating a new project. After …
> allow user, admin to configure default .Rproj.user path

- NEWS.md
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/studio/client/workbench/ui/ConsoleTabPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleInterpreterVersion.css
Addresses https://github.com/rstudio/rstudio/issues/15106.
Untabbed view:
Tabbed view:
Threw some more gross CSS into the pile.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15106.
N/A
> fixups for layout in untabbed console view

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/panmirror/outline/PanmirrorOutlineWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/RMarkdownPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/SweavePreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocumentOutlineWidget.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocumentOutlineWidget.java
Addresses https://github.com/rstudio/rstudio/issues/6887.
Example with font size of 12:
Mostly straightforward addition of preference, tweak of UI, and applying of font size preference in the appropriate locations.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/6887. Note that the source editor and visual editor use different document outline implementations under the hood, so it's a good idea to check both.
N/A
> allow customization of document outline font size

- NEWS.md
- rstudio.Rproj
- src/cpp/tests/automation/testthat/test-automation-completions.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
Addresses https://github.com/rstudio/rstudio/issues/15046.
In our completion manager, we had some places where we attempted to insert a literal tab instead of indenting. This PR fixes that.
Integration tests provided in PR.
Test via notes in https://github.com/rstudio/rstudio/issues/15046.
N/A
> ensure Tab keypresses indent instead of literal tabbing

- dependencies/common/install-soci
Set up a couple of Mac IDE dev machines from scratch recently and both failed to build SOCI via the dependency scripts with the error: `ninja: error: unknown warning flag 'dupbuild=warn'`
Remove that option. Confirmed can now build SOCI with ninja on Mac (and one Linux that I tried it on).
NA
Build-time stuff.
NA
> remove dupbuild from soci ninja build

- NEWS.md
- src/gwt/acesupport/acemode/rmarkdown_highlight_rules.js
- src/gwt/acesupport/acemode/utils.js
- src/gwt/src/org/rstudio/core/client/regex/Match.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java
Addresses https://github.com/rstudio/rstudio/issues/10079.
- Updated our Ace highlight embed rules to also take into account the size of the chunk header, and use that to require that the closing rule matches a chunk of the appropriate length.
- Also use similar logic in our background chunk highlighter, which is implemented on the GWT side.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/10079.
N/A
> improve highlight of nested chunks in R Markdown documents

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextUi.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/DefaultChunkOptionsPopupPanel.java
- src/gwt/test/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextUiTests.java
- src/gwt/test/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/DefaultChunkOptionsPopupPanelTests.java
Addresses #15156
Improve RMD chunk header popup to understand a comma after the engine, e.g.:
`{r, label, echo=TRUE}`
in addition to the already supported:
`{r label, echo=TRUE}`
Specifically, enhanced existing `extractChunkLabel()` method to understand this and to also return a hint about where to continue parsing the rest of the chunk header to the caller.
Added lots of unit tests around this change.
Test various chunk types in RMarkdown, where you put a comma after the engine (language specifier, e.g. "r"). Try with and without a label.
It is expected that if you use the chunk option popup and hit Apply it will remove the comma.
NA
> fix RMD chunk label parser to handle comma before label

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/ModuleTools.R
- src/cpp/session/modules/SessionRCompletions.R
- src/cpp/session/modules/SessionUserPrefValues.R
- src/cpp/session/modules/SessionUserPrefs.cpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/cpp/tests/automation/testthat/test-automation-completions.R
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CodePreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
- src/gwt/tools/generate-prefs.R
Addresses https://github.com/rstudio/rstudio/issues/13065.
Adds a user preference, which controls whether all function arguments are provided as part of the completion list.
If set, then we no longer filter arguments which have already been matched in the function invocation. For example:
This PR also includes some auto-generated code to make preference management easier from R, and uses that in the automation tests.
Automation tests included.
Test via notes in https://github.com/rstudio/rstudio/issues/13065.
N/A
> add pref for requesting all available argument completions

- NEWS.md
- src/cpp/tests/automation/testthat/test-automation-completions.R
- src/gwt/acesupport/acemode/r_code_model.js
Addresses https://github.com/rstudio/rstudio/issues/15161.
Completions within `dplyr` pipelines are handled specially -- the raw names are taken from tokens in the source document. However, because those names can be quoted, we need to unquote them when returning those as completion items. (The completion manager will take care of re-quoting those names if required.)
Included.
Test via notes in https://github.com/rstudio/rstudio/issues/15161.
N/A
> unquote quoted variable names in dplyr pipes

- jenkins/utils.groovy
Addresses #15167 plus fix the broken focal build.
We no longer support debian 10, thus no longer need to build our focal release in a bionic container. This was breaking the build because panmirror (visual editor) recently had a change that makes it no longer build with node 16, and bionic doesn't support node > 16.
So, switching to building in a focal container.
NA - build related
Confirm we are getting usable focal builds of IDE/Server/Workbench.
NA
> build focal using focal image (fix build break)

- jenkins/Jenkinsfile.build
- jenkins/utils.groovy
Cranberry-hibiscus fix for #15167
We no longer support debian 10, thus no longer need to build our focal release in a bionic container. This was breaking the build because panmirror (visual editor) recently had a change that makes it no longer build with node 16, and bionic doesn't support node > 16.
So, switching to building in a focal container.
Backport of fix made to main. This change has been in pro for many months, so should be a no-op when merged into pro repo.
NA
NA
NA
> build focal on focal instead of bionic

- src/cpp/core/include/core/http/AsyncClient.hpp
- src/cpp/core/include/core/http/TcpIpAsyncClient.hpp
- src/cpp/core/include/core/http/TcpIpAsyncClientSsl.hpp
(on the same client connection)
Addresses: rstudio/vscode-server#108
Reviewed in PR: https://github.com/rstudio/rstudio-pro/pull/6790
This affects SocketProxy that sets up concurrent callbacks on the same AsyncClient connection
> Use a strand to prevent concurrent callbacks

- dependencies/common/install-panmirror
- dependencies/windows/install-panmirror/clone-quarto-repo.cmd
- docker/jenkins/Dockerfile.bionic
- docker/jenkins/Dockerfile.focal
- docker/jenkins/Dockerfile.jammy
- docker/jenkins/Dockerfile.opensuse15
- docker/jenkins/Dockerfile.rhel8
- docker/jenkins/Dockerfile.rhel9
- docker/jenkins/Dockerfile.windows
Addresses #15169
Kousa Dogwood uses the `main` branch of the visual editor/panmirror repo, but the Dockerfiles were checking the `mountain-hydrangea` branch for changes. So the only time panmirror changes were pulled was when a docker image was rebuilt.
Note that Issue #15006 tracks pinning panmirror to a branch for Kousa Dogwood release.
NA
NA
NA
> ensure pulling latest panmirror for Kousa Dogwood

- NEWS.md
- src/cpp/tests/automation/testthat/test-automation-syntax-highlighting.R
- src/gwt/acesupport/acemode/tex_highlight_rules.js
Addresses https://github.com/rstudio/rstudio/issues/15019.
The TeX highlight rules we included were not appropriately structured for embedding, and we also (🤦 ) used the wrong name when trying to refer to these rules when embedding them.
Included a basic test.
Test via notes in https://github.com/rstudio/rstudio/issues/15019.
N/A
> fix handling of tikz highlight rules

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
Addresses https://github.com/rstudio/rstudio/issues/14594.
Raw HTML chunks evidently do not have a single line chunk header of the form `{<engine>}`. Detect and handle that appropriately. The heuristic here isn't perfect, but should hopefully be good enough since a line starting and ending with `{}` should be rare, especially for HTML chunks.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14594.
N/A
> treat chunks without headers as raw chunks

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunks.java
Purely an internal / developer nicety. Allows Help -> Diagnostics -> Toggle Editor Token Information to function in visual mode documents.
> allow enabling of token diagnostics in visual mode editors

- src/cpp/tests/automation/testthat/test-automation-syntax-highlighting.R
- src/gwt/acesupport/acemode/markdown_highlight_rules.js
Addresses https://github.com/rstudio/rstudio/issues/12161.
Apologies for the noisy PR; most of the changes are just white-space related. Note that we were technically embedding highlight rules for other languages in our plain Markdown documents, but as far as I can see those were never actually used -- the "plain" GitHub highlight rules always took precedence. R Markdown / Quarto documents perform their own embedding of highlight rules for supported languages.
Not sure if we want to bring back support for regular code highlighting in GitHub chunks for plain Markdown documents; maybe worth filing as a separate issue?
Handle nested GitHub-style code chunks in Markdown (and, by extension, R Markdown / Quarto) documents.
Included. …
> improve handling of nested "plain" GitHub chunks

- NEWS.md
- src/cpp/tests/automation/testthat/test-automation-quarto.R
- src/gwt/acesupport/acemode/rmarkdown_folding.js
- src/gwt/acesupport/acemode/utils.js
Addresses https://github.com/rstudio/rstudio/issues/15191.
This PR specifically targets the fold rules for R Markdown documents. Previously, the rules checked only for chunk headers with three backticks; this PR generalizes that to any number of backticks.
Basic automation included.
Test via notes in https://github.com/rstudio/rstudio/issues/15191.
N/A
> improve support for folding of variable-width chunk headers

- NEWS.md
- src/cpp/tests/automation/testthat/test-automation-quarto.R
- src/gwt/acesupport/acemode/markdown_highlight_rules.js
Addresses https://github.com/rstudio/rstudio/issues/14552.
In our Markdown highlight rules, allow the rule matching headers to be more permissive.
Included.
Test via notes in https://github.com/rstudio/rstudio/issues/14552.
N/A
> allow empty labels for markdown headers

- NEWS.md
- src/cpp/tests/automation/testthat/test-automation-python.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
Addresses https://github.com/rstudio/rstudio/issues/14560.
The R completion manager also handles autocompletion results generated by reticulate, when the Python REPL is active. In this scenario, because R and Python have different rules for what is a "syntactic" variable name, we need to suppress the regular quotation rules when using a Python completion result.
Included.
Test via notes in https://github.com/rstudio/rstudio/issues/14560.
> only quote non-syntactic variable names for non-Python completions

- NEWS.md
- src/cpp/session/modules/build/SessionBuild.cpp
- src/cpp/session/modules/build/SessionBuild.hpp
- src/cpp/session/modules/build/SessionBuildErrors.cpp
Addresses https://github.com/rstudio/rstudio/issues/14564.
Drop the Results section from testthat output, when parsing for testthat test outputs.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/14564.
N/A
> omit Results section when parsing for testthat errors

- src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java
- src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/DocUpdateSentinel.java
Addresses (part of) https://github.com/rstudio/rstudio/issues/11932.
Attempts to auto-save open documents while the session is preparing to quit or suspend are likely to fail. Ensure RStudio doesn't perform auto-saves in that state, or if it does for some reason, don't log those errors to the user (since the document would quickly become up-to-date again soon after working in the IDE).
Note that these auto-saves are only related to RStudio's internal source database buffer of open tabs, not attempts to update the actual files on disk being edited by the user.
Not included.
N/A
> avoid logging auto-save errors during restart / quit

- package/linux/make-package
Fix hanging rhel9 builds. 
This is a workaround for fakeroot hangs in docker taken from https://github.com/moby/moby/issues/27195. Worth a shot...
> attempt to work around fakeroot hang in rhel9 build

- package/linux/make-package
Ongoing work to isolate why rhel9 builds are hanging.
> disable set -e before testing fakeroot for timeout

- docs/news/index.qmd
- version/news/NEWS-2024.09.0-cranberry-hibiscus.md
Update release notes for IDE / Workbench 2024.09.0+375.pro3 release.
This change has been generated by the release script. Content is generated based on `version/news/NEWS-2024.09.0-cranberry-hibiscus.md`. If this file was not in sync with Pro or did not include items from other sources (i.e. the vscode extension), then some items may be missing.  Please verify content/formatting is correct and make changes if necessary.
> Update release notes for 2024.09.0+375.pro3

- src/cpp/session/SessionConsoleInput.cpp
- src/cpp/session/SessionHttpMethods.cpp
- src/cpp/session/modules/SessionSystemResources.cpp
Addresses https://github.com/rstudio/rstudio/issues/15221.
Don't log warnings in forked sessions; just quietly discard the requests it cannot handle.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15221.
N/A
> avoid logging warnings in forked sessions

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceMouseEventNative.java
Addresses https://github.com/rstudio/rstudio/issues/15226.
Ace installs a default gutterdown mouse handler, which always gets a chance to fire. Override that by setting our own default handler, but saving and invoking that handler if appropriate (ie: if we didn't try to toggle a breakpoint).
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15226.
N/A
> avoid line selections when toggling breakpoints

- NEWS.md
- src/cpp/session/modules/SessionBreakpoints.R
- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/tests/automation/testthat/test-automation-debugger.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
Addresses https://github.com/rstudio/rstudio/issues/15201.
- The 'match.length' attribute is set on the `pos` vector, not the individual elements, so we need to grab that from `pos` before subsetting when constructing `endpos`.
- Improve check for "fuzzy" matching of source references in a document. In particular, we first check all documents for an exact match before doing a more fuzzy match later.
TODO
Test via notes in https://github.com/rstudio/rstudio/issues/15201.
N/A
> fix checks for function-in-sync

- src/cpp/r/include/r/session/RSession.hpp
- src/cpp/r/include/r/session/RSessionState.hpp
- src/cpp/r/session/RSessionState.cpp
- src/cpp/r/session/RSuspend.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionBuild.R
- src/cpp/session/modules/SessionUserPrefValues.R
- src/cpp/session/modules/build/SessionBuild.cpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/cpp/shared_core/FilePath.cpp
- src/cpp/shared_core/FilePathTests.cpp
- src/gwt/src/org/rstudio/studio/client/application/model/SuspendOptions.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/BuildToolsPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/events/BuildCompletedEvent.java
Addresses https://github.com/rstudio/rstudio/issues/13399.
On Windows, it's common for package installation to fail with errors of the form:
> ERROR: cannot remove earlier installation, is it in use?
typically because (as the error message states) the package is currently loaded; possibly in a totally separate R session. This PR seeks to alleviate the issue by:
- Installing the package into its own unique build library path,
- Performing the regular suspend + restart,
- On restart, we attempt to move the installed package to the intended install location,
- If that fails, we just add that directory to the library paths, and notify the user.
This way, even if the package is already in use by a separate R process, the user will still be able to install and test the package.
I'd like to add …
> use separate build library path when installing package

- NEWS.md
- src/cpp/session/modules/SessionRCompletions.R
Addresses https://github.com/rstudio/rstudio/issues/15238.
When we detect that `readline()` is active, we try to provide completions based on options within an `(a/b/c)` string. This PR adjusts that so that we only provide completions if more than one alternative is provided, to guard against things like `readline("Do you want to do the thing? (You can't undo this).")`.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15238.
N/A
> tweak to readline completions

- src/cpp/rserver-automation.in
- src/cpp/session/modules/automation/SessionAutomation.R
- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/tests/automation/testthat/test-automation-debugger.R
Addresses some unit test failures in the debugger tests.
- Make sure that environment variables set by the RStudio launcher are used by the `rserver-automation` script. This is necessary so that we can pre-populate the config file used by the automated instance of RStudio.
- Add some sleeps to help better sequence changes when tests are running.
> fixups for server automation

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/common/filetypes/events/RenameFileInitiatedEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Addresses https://github.com/rstudio/rstudio/issues/15242.
When a "renameFile" action is initiated, fire an event first to allow any available text editing targets to attempt a save first.
TODO
Test via notes in https://github.com/rstudio/rstudio/issues/15242. Note that the save happens as soon as the "Rename" command is initiated.
N/A
> save before renaming source files

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
Addresses https://github.com/rstudio/rstudio/issues/14507.
Allow the base completion manager (which is used for all completions except for plain R mode documents) to handle Tab, and use that to insert ghost text when any is available.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14507.
N/A
> allow ghost text insertion in all parts of rmd doc

- src/cpp/session/modules/quarto/SessionQuarto.cpp
- src/cpp/session/projects/SessionProjects.cpp
Addresses https://github.com/rstudio/rstudio/issues/15222.
Recent changes now require the project's `.Rproj` file to be created before the project scratch path can be computed. This PR resolves the issue by ensuring the project file is created before first run docs are added.
Captured by existing automation.
Test via notes in https://github.com/rstudio/rstudio/issues/15222.
N/A
> write project file before adding first run docs

- version/news/NEWS-2024.09.1-cranberry-hibiscus.md
Fixes #15253 
Update the NEWS and hope some random AI will code the fix. One of these days...
The actual fix comes from the panmirror repo (`quarto-dev/quarto`) via: https://github.com/quarto-dev/quarto/pull/559
Once the quarto PR is merged into `main` I will backport it to the `release/rstudio-cranberry-hibiscus` branch, which is what gets pulled via the dependency scripts. The build dockerfiles watch for changes to this branch and should pull down the updated bits.
I'll author a test once this is merged and pulled forward to `main`.
See issue for repro steps.
NA
> fix raw latex block roundtripping in Visual Editor

- docker/jenkins/Dockerfile.opensuse15
FileLock tests were failing because `ps` wasn't installed in the opensuse docker image.
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). If no documentation was added for a …
> Install ps in opensuse dockerfile

- src/cpp/tests/testthat/test-rsconnect.R
Noticed this when running the cpp unit tests:
```
── Skipped tests (3) ───────────────────────────────────────────────────────────
• Not run when Quarto disabled (1): test-rsconnect.R:54:4
```
This was broken with some re-jiggering of the `QUARTO_ENABLED` value, which is no longer set as an environment variable by the test script. AFAIK we include Quarto in all our builds now, so shouldn't need to be disabled.
Confirmed it passes locally on MacOS. Hopefully passes everywhere.
NA
NA
> reenable a unit test that was incorrectly disabled

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/yaml/YamlEditorToolsProviderQuarto.java
This allows the Quarto completions provider to give completions within `_brand.ya?ml` files.
@cscheid is there any other sort of sanity checking I should do here?
> support Quarto YAML completions in '_brand.yml'

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Addresses #14982 (again)
Minor Electron update to get on latest 31.x. Probably last update before we ship unless specific reasons arise (security, bugs, etc).
Changes from 31.5 -> 31.6: https://releases.electronjs.org/release/compare/v31.5.0/v31.6.0
NA
Nothing to specifically test other than Electron version number in About dialog.
NA
> Update to Electron 31.6

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Related to https://github.com/rstudio/rstudio/issues/2563.
This PR makes sure that the Code Transform menu uses the current preference value as the default for formatting a document. Adjusting this option here still only modifies the preference for that specific document.
> use global pref value as default for magic wand menu

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Addresses https://github.com/rstudio/rstudio/issues/15303.
Set `isSaving_ = true` flag in more Save code paths; respect that when checking if we can autosave on blur.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15303.
N/A
> avoid autosaving on blur if save in progress

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
This reverts commit adcdcb6fe9a88fe7c16d95d54d796f799f343a6c.
Builds were failing on opensuse15 and rhel8 with Electron 31.6. Downgrading to unblock builds, will investigate separately.
> Downgrade electron from 31.6 to 31.5

- src/cpp/r/R/Api.R
- src/cpp/r/R/Tools.R
- src/cpp/r/session/RSearchPath.cpp
- src/cpp/tests/automation/testthat/test-automation-suspend.R
Addresses https://github.com/rstudio/rstudio-pro/issues/3074.
- Re-write the session suspend / resume code in R, so that it can be more readily debugged and tested.
- Ensure that all loaded namespaces, not just attached packages, are included in the 'package_paths' file we generate.
We now use a two-pass approach when loading and attaching packages:
- First, use `loadNamespace()` to load all the package namespaces from the previous session, with leaf packages being loaded first.
- Then, use `library()` to attach packages, preserving the order of the search path as it was before suspend.
TODO
Test via notes in https://github.com/rstudio/rstudio-pro/issues/3074.
N/A
> ensure all loaded namespaces are serialized on suspend / resume

- src/cpp/server/include/server/ServerOptions.gen.hpp
- src/cpp/server/server-options.json
So that we don't generate documentation for this option.
Also allow an implicit 'true' value, so that `./rserver-dev --run-automation` works without giving an explicit value.
> hide run-automation server option

- src/cpp/core/LogOptions.cpp
- src/cpp/core/LoggingTests.cpp
- src/cpp/core/include/core/Log.hpp
- src/cpp/shared_core/Logger.cpp
- src/cpp/shared_core/include/shared_core/Logger.hpp
* Add new "trace" log level that's a superset of "debug" level.
* Add appropriate logger methods and macros.
To better separate debug messages from messages meant to trace the internal execution of a process, add a new log level "Trace".
Approach is straightforward: replicate what we do for debug logging, but call it trace logging. The new `TRACE` level is one above `DEBUG` so that it captures all log messages.
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and …
> Add Trace log level support

- src/cpp/r/include/r/session/RConsoleHistory.hpp
- src/cpp/r/session/RConsoleHistory.cpp
- src/cpp/r/session/RStdCallbacks.cpp
- src/cpp/session/modules/SessionHistory.cpp
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/history/events/HistoryEntriesAddedEvent.java
Addresses https://github.com/rstudio/rstudio/issues/15345. NEWS not required since this was only ever broken in the development builds.
The console history maintained in the RStudio front-end, and the history file `.Rhistory` used by R, are handled differently in a few places. In particular, in a live session, we keep the "complete" submitted command, to allow for multi-line commands in the console history.
This means that things in the console history could be coming from different sources:
1. Added by us, when a command is executed;
2. Added by R, when the "addhistory" C callback is invoked.
This PR tries to ensure that versions of (2) which might also necessitate updating the console history maintained in the front-end do also happen.
N/A …
> use flag when updating console history from added history entries

- src/node/desktop/src/main/application.ts
The new splash screen is dismissable via keyboard.
On RDP we [show the splash screen on top of the Manage License dialog](https://github.com/rstudio/rstudio-pro/issues/6962) at startup. It has been this way since RDP moved to Electron.
I plan to fix that, but noticed that if you close the splash screen in this scenario, then select a license, the app closes and you have to re-run it to startup. Essentially the same as https://github.com/rstudio/rstudio-pro/issues/6062 except not specific to Windows.
Keep app alive during startup even if there are moments with no windows on all platforms, not just Windows.
None
This bug has only been possible for a day (since adding the new splash screen) so don't have an issue for it. A fringe case, currently, but once I fix the issue with showing the …
> keep app alive during startup on all platforms not just windows

- NEWS.md
- src/node/desktop/src/main/session-launcher.ts
Addresses https://github.com/rstudio/rstudio-pro/issues/6962
(entire fix lives in open-source but only impacts desktop pro)
Don't start the timer for splash screen until after we have (potentially) shown the Manage License dialog at startup.
None
To test you'll need a system where the trial period has expired, remove your unexpired license file (if any), and start RStudio Desktop Pro. Shouldn't see the splash screen until after you have entered a license.
Also, confirm you still see the splash screen when starting another session via Session / New Session.
NA
> don't show splash screen before RDP license dialog

- src/cpp/session/modules/automation/SessionAutomation.R
- src/cpp/tests/automation/testthat/test-automation-editor.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Addresses https://github.com/rstudio/rstudio/issues/15254.
Recent changes in the daily builds broke 'strip trailing whitespace'; this PR fixes that and adds a test.
Test via notes in https://github.com/rstudio/rstudio/issues/15254.
N/A
> fix issue with whitespace trim

- src/node/desktop/src/ui/splash/splash.html
- src/node/desktop/src/ui/splash/splash_unversioned.html.in
Adjustment to #6876
The splash screen SVG was using an unavailable font, and a serif font was being substituted.
Changed font specification to `font-family: Arial, Helvetica, sans-serif;` and slightly reduced size. Here's how it looks:
None
Stare at it for at least 25 minutes.
NA
> Adjust font used in splash screen

- src/cpp/core/system/PosixSystem.cpp
* Rarely proc_pidinfo() fails to get process info.
* Need to check for failure so as not to pass invalid data to a recursive call to getChildProcesses.
This issue manifested as unit test failures where we infinitely recursed getting the child processes of PID 0.
Address unit test failures on MacOS that initially presented as seg faults. Further investigation revealed the cause to be an infinite recursion while getting information about child processes of a given process.
Add an additional check when getting more detailed process info to ensure the operation succeeded. If not do not recurse for the process.
Covered by existing unit tests.
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected …
> Handle case where getting proc info on MacOS fails

- src/cpp/core/system/PosixSystem.cpp
Follow up tweaks, inspired by https://github.com/rstudio/rstudio/pull/15361.
Check our usages of `proc_pidinfo` and validate we're checking the return value correctly in each case. Much of this was gleaned by looking at usages within the xnu sources at https://github.com/apple-oss-distributions/xnu.
N/A
N/A
> tweaks to proc_pidinfo return value handling

- src/gwt/src/org/rstudio/studio/client/application/Application.java
Works around a sporadic GWT miscompilation where `GWT.runAsync()` could fail with JS exceptions like:
> 2024-10-28T21:20:02.457618Z [rserver] ERROR CLIENT EXCEPTION (rsession-kevin): (TypeError) : this.val$callback1_0_g$.onSuccess_150_g$ is not a function;|||rstudio-0.js@27#17290::execute|||rstudio-0.js@40#19468::executeScheduled|||rstudio-0.js@9#19130::runScheduledTasks|||rstudio-0.js@5#19236::flushPostEventPumpCommands|||rstudio-0.js@23#19405::execute|||rstudio-0.js@19#19094::execute|||rstudio-0.js@28#18727::apply|||rstudio-0.js@16#18789::entry0|||rstudio-0.js@14#18767::anonymous|||rstudio-0.js@45#19151::callback_0_g$|||Client-ID: 48315d4a-564a-420b-931e-f30fb68723c7|||User-Agent: Mozilla/5.0 (Macintosh  Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 …
> remove unnecessary runAsync call

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
Addresses https://github.com/rstudio/rstudio/issues/3520.
The changes here are entirely on the front-end, and the idea is:
- When chunk execution begins, we start buffering any console input;
- When chunk execution ends, we collect any received console input, and submit it as a single entry.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/3520. It would be worth checking the sanity of the console history with:
- Execution of a single chunk's contents (via the Run button),
- Execution of a subset of code in a chunk (via Cmd + Enter),
- Execution of all chunks in a document (via Run All or similar)
N/A
> include executed chunk code as single multi-line console history entry

- NEWS.md
- src/cpp/tests/automation/testthat/test-automation-completions.R
- src/gwt/src/org/rstudio/core/client/RegexUtil.java
Addresses https://github.com/rstudio/rstudio/issues/13290.
Tweak the way we detect syntactic identifiers. Roughly speaking, they should not start with `_` or a number, but should consist of 1 or more word characters there-on (including `.` and `_`).
Automation included.
Test via notes in https://github.com/rstudio/rstudio/issues/13290.
N/A
> tweak identification of syntactic r identifiers

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Addresses #14538.
- Mark the whole container of console inputs + outputs as 'contenteditable', so that the right click context menu includes "Paste" as an option.
- Implement a paste handler that drives paste attempts to the Console.
I am a bit worried about potential side effects of marking the whole element as 'contenteditable' here, but I'm hoping they're limited since we're doing this only briefly.
One downside is that "cut" is also erroneously set as enabled in this scenario, but the pro's of having paste work as the user expects probably outweighs the con's.
N/A
Test via notes in #14538.
N/A
> handle paste requests / attempts outside of console input line

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java
Addresses https://github.com/rstudio/rstudio/issues/13441.
Tweak the regular expression used to decide whether snippet completions are appropriate in the current context.
De-emphasize snippet completions in function + subset contexts, but still make them available.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13441.
N/A
> allow snippets in function calls

- src/gwt/src/org/rstudio/studio/client/JavaScriptEventHistory.java
- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Addresses https://github.com/rstudio/rstudio/issues/14538.
The 'paste' event generated after clicking Paste in the context menu seems to have an unexpected event target;
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/14538.
N/A
> paste workarounds from Windows

- NEWS.md
- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/session/modules/SessionObjectExplorer.R
Addresses https://github.com/rstudio/rstudio/issues/15369.
Use `lobstr::obj_size()` if available; and `utils::object.size()` if not, when computing the size of an R object.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15369.
N/A
> use lobstr for object size when available

- docs/news/index.qmd
- version/news/NEWS-2024.09.1-cranberry-hibiscus.md
Update release notes for IDE / Workbench 2024.09.1+394.pro7 release.
This change has been generated by the release script. Content is generated based on `version/news/NEWS-2024.09.1-cranberry-hibiscus.md`. If this file was not in sync with Pro or did not include items from other sources (i.e. the vscode extension), then some items may be missing.  Please verify content/formatting is correct and make changes if necessary.
> Update release notes for 2024.09.1+394.pro7

- src/node/desktop/src/main/gwt-callback.ts
Addresses https://github.com/rstudio/rstudio/issues/15396.
The node native module we use for querying fonts appears to be buggy on Linux. Avoid using it there when possible.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15396.
N/A
> use fc-list when querying fonts on Linux

- src/cpp/core/r_util/RProjectFile.cpp
- src/cpp/session/projects/SessionProjects.cpp
Addresses https://github.com/rstudio/rstudio/issues/15405.
Make sure we bring along a previously-existing project ID when writing project options.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15405.
N/A
> make sure project IDs are not lost when writing project options

- src/cpp/core/r_util/RProjectFile.cpp
- src/cpp/session/projects/SessionProjects.cpp
I accidentally reverted a previous change [here](https://github.com/rstudio/rstudio/commit/5f72005f9f73bb58c93f66c797dd738de4ccb5f3). 
This should reapply the change that I reverted: https://github.com/rstudio/rstudio/pull/15408
Reapplying the same change.
N/A
N/A
N/A
> Fix revert.

- NEWS.md
- src/cpp/session/CMakeLists.txt
- src/cpp/session/SessionCRANOverlay.cpp
- src/cpp/session/SessionCRANOverlay.hpp
- src/cpp/session/SessionMain.cpp
OS companion to https://github.com/rstudio/rstudio-pro/pull/6973.
We need to handle session CRAN repo default settings a bit differently in the Pro code. This PR attempt to address that by introducing an overlay that will allow Pro to do it's extra processing when required.
Once both these PRs are approved, I will merge this one and sync to Pro, and then handle any conflicts before merging the Pro PR.
Adds the new ServerCRANOverlay.cpp and header files, with the open source implementation doing no extra mapping of the user prefs default, and returning the existing default of `https://cran.rstudio.com/` in the fallback scenario.
We shouldn't need changes to any existing tests here, as the behaviour should be the same.
We'll want to make sure that `https://cran.rstudio.com/` is still used …
> Add overlay methods to handle session CRAN repo defaults

- src/cpp/tests/automation/testthat/test-automation-debugger.R
These tests have been failing 100% of the time for me for a while, including a VERY long timeout making it painful to run all the automation.
- Removed `on.exit(remote$documentClose(), add = TRUE)` from the first test; if I leave this in I get the following error
```
✔ | F W  S  OK | Context
✖ | 1        2 | automation-debugger [13.0s]                                    
───────────────────────────────────────────────────────────────────────────────────────
Error (test-automation-debugger.R:9:1): (code run outside of `test_that()`)
Error: invalid state
Backtrace:
▆
1. └─remote$documentClose() at test-automation-debugger.R:9:1
2.   └─self$consoleExecute("invisible(.rs.api.documentClose())") at modules/R/SessionAutomationRemote.R:207:4
3.     └─self$client$DOM.getDocument() at …
```
> fixes to BRAT debugger automation

- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/tests/automation/testthat/test-automation-build-pane.R
- src/cpp/tests/automation/testthat/test-automation-completions.R
- src/cpp/tests/automation/testthat/test-automation-data-viewer.R
- src/cpp/tests/automation/testthat/test-automation-debugger.R
- src/cpp/tests/automation/testthat/test-automation-editor.R
- src/cpp/tests/automation/testthat/test-automation-history.R
- src/cpp/tests/automation/testthat/test-automation-python.R
- src/cpp/tests/automation/testthat/test-automation-quarto.R
- src/cpp/tests/automation/testthat/test-automation-refactoring.R
- src/cpp/tests/automation/testthat/test-automation-reformat.R
- src/cpp/tests/automation/testthat/test-automation-restart.R
- src/cpp/tests/automation/testthat/test-automation-rmarkdown.R
- src/cpp/tests/automation/testthat/test-automation-suspend.R
- src/cpp/tests/automation/testthat/test-automation-sweave.R
- src/cpp/tests/automation/testthat/test-automation-syntax-highlighting.R
- We're doing some stuff that's not typical for the regular `test_that()` workflow.
- It's shorter.
> use '.rs.test' for automation test cases

- src/cpp/session/modules/rmarkdown/NotebookCache.cpp
This PR addresses an intermittent issue that popped up when running automation tests, seemingly related to a failure to copy notebook chunk definitions.
For reference, the error:
> 2024-11-14T18:43:25.742005Z [rsession-kevin] ERROR system error 2 (No such file or directory) [path: /tmp/RtmpLqA3oL/rstudio-automation-state-e2d33db9a6ca/data-home/notebooks/7DF203A4-document-e2d3283e6349/1/9DA86720a9cea511/chunks.json, target-path: /tmp/RtmpLqA3oL/rstudio-automation-state-e2d33db9a6ca/data-home/notebooks/7DF203A4-document-e2d3283e6349/1/s/chunks.json]; OCCURRED AT Error rstudio::core::FilePath::copy(const FilePath &, bool) const src/cpp/shared_core/FilePath.cpp:819; LOGGED FROM: void rstudio::session::modules::rmarkdown::notebook::(anonymous …
> tweak copy of notebook chunk defns

- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/tests/automation/testthat/test-automation-suspend.R
- src/gwt/src/org/rstudio/studio/client/common/shell/ShellDisplay.java
- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
This ensures that `consoleExecute()` and `consoleExecuteExpr()` do not return until the code submitted has actually finished executing.
The Shell widget now sets an `rstudio-console-busy` CSS class when busy, and unsets it when waiting for input in the prompt.
N/A
N/A
N/A
> wait for code execution to finish in automation APIs

- src/cpp/session/modules/automation/SessionAutomation.R
- src/node/desktop/src/main/session-launcher.ts
We can rely on `.rs.automation.applicationPath(mode)` to return the correct path for us.
> no need for RSTUDIO_AUTOMATION_EXE

- src/cpp/session/modules/automation/SessionAutomation.R
- src/cpp/tests/automation/README.md
Add testthat and devtools to the packages installed for the BRAT automation. Start documenting how to run the tests against an official build.
> add missing packages, readme tweaks

- NEWS.md
- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/15434.
- Use a queue when processing Copilot file changes, to avoid potentially swamping the R session on startup.
- Avoid using `module_context::isTextFile()`, as the fallback involves invoking `/usr/bin/file`, which is much too slow.
The main downside with this change is that we're no longer indexing some files that the user might have expected (e.g. `.csv` files?). I'm not sure if we should allow indexing of those files in any case, though -- feels like it should be opt-in?
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15434.
N/A
> use queue + batch for processing file changes

- version/news/NEWS-2024.12.0-kousa-dogwood.md
OS PR for https://github.com/rstudio/rstudio-pro/pull/7148
> Update "Positron" to "Positron Pro" in Workbench context

- src/cpp/core/r_util/RTokenizer.cpp
- src/cpp/core/r_util/RTokenizerTests.cpp
NOTE: We can probably hold this for next release.
Addresses https://github.com/rstudio/rstudio/issues/15316.
The `std::isw*` functions on macOS don't appear to work as expected. Fall back to the Core Foundation APIs, which apparently do.
N/A
N/A
> use CF APIs when checking alnum characters

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
> [!CAUTION]
> Targets Kousa Dogwood patch 1, don't merge until KD.0 has released.
Addresses https://github.com/rstudio/rstudio-pro/issues/7167
Updated `vue` to latest, and removed obsolete `vue-template-compiler`.
Note, `vue` is only used by RStudio Desktop Pro, but we use the same `package.json` for both open source and pro so the fix needs to happen in open-source.
NA
Test the "Manage License" dialog in RStudio Desktop Pro, both at first-run without a license (or trial), and via Help / Manage License.
NA
> remove unused vue-template-compiler

- src/cpp/server/ServerMain.cpp
- src/cpp/server/ServerMainOverlay.cpp
Addresses workbench issue: https://github.com/rstudio/rstudio-pro/issues/7173
companion to: 
- stop the http server before killing sub-processes
- provide a startShutdown hook for the overlay
- additional debug messages for the stop process
This should only affect the OS server configuration. The only real change there is that the http server gets stopped before we start terminating sessions so it could change the behavior, particularly what errors are logged while the server is shutting down.  Additional debug messages exist to provide more diagnostics.
> Stop http server before shutting down, make processes to send interrupt to pluggable in the overlay

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Update electron from 33.2.1 to 33.3.0
Changes: https://releases.electronjs.org/release/compare/v33.2.1/v33.3.0
Updated electron in `package.json`, `npm update`, `npm install`, sanity testing.
Also did drive-by minor upgrades of a couple other packages.
BRAT passed, unit tests passed.
General testing.
NA
> Upgrade to Electron 33.3.0

- src/node/desktop/package-lock.json
Fix issues flagged by `npm`:
```
path-to-regexp  <0.1.12
Severity: moderate
Unpatched `path-to-regexp` ReDoS in 0.1.x - https://github.com/advisories/GHSA-rhx6-c78j-4q9w
fix available via `npm audit fix`
node_modules/path-to-regexp
express  4.0.0-rc1 - 4.21.1 || 5.0.0-alpha.1 - 5.0.0-beta.3
Depends on vulnerable versions of path-to-regexp
node_modules/express
2 moderate severity vulnerabilities
```
`npm audit fix`
NA
NA
NA
> fix 2 med-sev vulnerabilities

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
- version/news/NEWS-2024.12.0-kousa-dogwood.md
> [!WARNING]
> Don't merge, conversation ongoing about whether to take this for Kousa Dogwood.
Update electron from 31.7.5 to 31.7.6 to pickup latest fixes. https://releases.electronjs.org/release/v31.7.6
Update package.json, `npm update`, `npm i`, build and run tests.
Passed (locally, unit tests, BRAT)
No specific impact, this is covered by automation and general usage.
NA
> update to electron 31.7.6

- src/cpp/session/modules/SessionHelp.R
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses https://github.com/rstudio/rstudio-pro/issues/7063.
In older versions of R, the invocation of `httpd()` could (unintentionally) return the generated error page as an _n_-length character vector. This was fixed here:
https://github.com/wch/r-source/commit/e22517c9036a2a06d8778b2a782d393224e355af
but we add this as a workaround for those still using older releases of R.
N/A
Test that you don't see any warning when you execute this. Please verify with R 4.0.4 as well as a recent release of R.
```
invisible(.rs.rpc.get_help("oops", ".GlobalEnv", 1L))
```
N/A
> work around issue with error help page

- dependencies/common/install-quarto
When re-running dependency installation on a dev machine, the Quarto installation script always asks for elevation (possibly twice on a Mac, depending on sudo configuration), even if the correct version is already installed.
Fix by moving the elevation check after determining that quarto actually needs to be installed/upgraded.
> don't elevate if quarto is already installed

- package/osx/scripts/package-lock.json
Original issue as reported by `npm audit`:
```
npm audit report
cross-spawn  7.0.0 - 7.0.4
Severity: high
Regular Expression Denial of Service (ReDoS) in cross-spawn - https://github.com/advisories/GHSA-3xgq-45jj-v275
```
The impacted components are build-time tooling and not shipped to customers so I don't think we need to bother doing this in `rel-kousa-dogwood` but might as well for `2024.12.1`.
Fixed via `npm audit fix` and also did `npm update`.
> update macOS packaging dependencies

- src/gwt/tools/locdiff/package-lock.json
Fix [vulnerability that was flagged by Github dependabot](https://github.com/rstudio/rstudio/security/dependabot/109) in the `locdiff` tool. `locdiff` is a tool only run manually by developers on their local machine, typically once per release, so not an actual product issue.
Cleaning up to reduce noise and stay current.
> update locfix dependencies

- src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
- src/gwt/src/org/rstudio/core/client/widget/VirtualizedDataGrid.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses https://github.com/rstudio/rstudio/issues/15502.
GWT will attempt to reset focus on a cell after scrolling, as per:
https://github.com/gwtproject/gwt/blob/c2229e7557450cd2842269f5fe9cb8586e90b50c/user/src/com/google/gwt/user/cellview/client/AbstractHasData.java#L320-L325
We want to avoid this behavior, so we implement our own `resetScrollOnFocus()` method here which handles that behavior but just does nothing.
https://github.com/rstudio/rstudio/blob/e8d795d0098578eb696aa105124dd2213b388b2c/src/gwt/src/org/rstudio/core/client/widget/VirtualizedDataGrid.java#L152-L160
Unfortunately, we were further overriding that override in the constructor for the Files list, so we need to remove the (unnecessary, incorrect) override.
The name + return value for this method confused me at first …
> fix issue with scroll position being reset on scroll

- src/cpp/session/modules/SessionGit.cpp
- src/gwt/src/org/rstudio/studio/client/common/vcs/GitServerOperations.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ChangelistTable.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/model/VcsState.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitChangelistTablePresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/model/GitState.java
Addresses https://github.com/rstudio/rstudio/issues/15492.
When `vcs_autorefresh = false` is set, only perform a "minimal" refresh when the Git pane is activated -- that is, just list remote branches; avoid calling `git status`. This provides us the information needed to populate the Git toolbar buttons, without needing to populate information on changed files.
Also tweaks the background color of the Git pane to avoid white flashing during refresh (just use a transparent background).
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15492.
N/A
> avoid expensive status call when autorefresh is false

- src/cpp/session/modules/automation/SessionAutomation.R
- src/cpp/tests/automation/testthat/test-automation-reformat.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetReformatHelper.java
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses https://github.com/rstudio/rstudio/issues/5425.
For a brief background, RStudio's code formatter acts upon a tokenized representation of the user's code. It performs two passes; one pass where it builds up metadata about the structure of the code being formatter, and another where it manipulates tokens to add whitespace and newlines where appropriate.
This PR resolves https://github.com/rstudio/rstudio/issues/5425 by forcing the formatter to use newlines after `,`, `(` and before `)`, to avoid scenarios where a closing bracket might incorrectly be collapsed onto the same line as a line comment.
A simple automated test was included.
Test via notes in https://github.com/rstudio/rstudio/issues/5425.
N/A
> improve handling of inline comments

- src/cpp/session/projects/SessionProjectContext.cpp
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses https://github.com/rstudio/rstudio/issues/15514.
The `computeUserDirectory()` now also creates the default project directory, which causes us to avoid an older code path where we also would have marked the project directory as hidden. This PR ensures we unconditionally mark the `.Rproj.user` directory as hidden on Windows, even if it was already created before.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15514. Windows only.
N/A
> fix regression where .Rproj.user folder not marked hidden

- docs/news/index.qmd
Update release notes for IDE / Workbench 2024.12.0+467.pro1 release.
This change has been generated by the release script. Content is generated based on `version/news/NEWS-2024.12.0-kousa-dogwood.md`. If this file was not in sync with Pro or did not include items from other sources (i.e. the vscode extension), then some items may be missing.  Please verify content/formatting is correct and make changes if necessary.
> Update release notes for 2024.12.0+467.pro1

- dependencies/common/install-hosts
- src/cpp/rserver-dev.in
Primarily for development scenarios where we want to simulate http connections from a non-localhost domain, since browsers might apply different security restrictions in this scenario.
> use rstudio-localhost for dev server

- src/node/desktop/src/main/args-manager.ts
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses #15536 and #15457.
Instead of telling the first available window to open a file, ensure the window used is capable of opening files by checking for desktop hooks.
The problem was the splash screen was the first window opened, so if the "open file" message arrived while the splash screen was still showing, the splash screen could receive the "open file" message, and this would fail to do anything.
I also added an environment variable, `RS_SPLASH_LINGER` for overriding the minimum length of time the splash screen stays visible. The default is `1300` (1.3 seconds). For testing this issue, recommend setting a longer time, e.g. `RS_SPLASH_LINGER=8000` for 8 seconds.
Tough to automate.
Test various combinations, starting RStudio via double-clicking a source file, double-clicking a …
> Open files at launch fix

- src/gwt/src/org/rstudio/core/client/theme/ThemeFonts.java
- src/node/desktop/src/main/gwt-callback.ts
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses https://github.com/rstudio/rstudio/issues/15547.
- Add "Noto Sans" to the proportional font fallback list.
- Also use sans-serif as the default proportional fallback font on desktop. (We already were on server.)
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15547. (In particular, check that RStudio uses a sans-serif font for UI elements in a fresh Fedora 41 instance.)
N/A
> include Noto Sans in default font list

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses #15561 (regression in Kousa Dogwood initial release)
Check that the publishing button exists before referencing it. 
Pending; will work on that separately
Test as described in the issue.
NA
> check that publishing UI exists before trying to operate on it

- src/node/desktop/src/main/app-state.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/main-window.ts
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses https://github.com/rstudio/rstudio-pro/issues/7259
The code that was setting a message handler on `gwtCallback` to deal with opening files after launch didn't work in Desktop Pro because `gwtCallback` wasn't set at the time it tried to use it.
In open-source, `gwtCallback` is already set when `this.sessionLauncher.launchFirstSession(...);` returns, but on Desktop Pro the licensing code delays creation of the main window (where `gwtCallback` is assigned) such that it **isn't** set when `launchFirstSession` returns.
This has never worked since we moved Desktop Pro to Electron.
Fixed by moving setting of the callback to the same place as other similar code (where the `gwtCallback` is guaranteed to be set for both open-source and pro).
None
This change is entirely in open-source and …
> fix files not opening when used to launch RDP

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses https://github.com/rstudio/rstudio/issues/15568.
`withSavedDoc()` only saves the document to RStudio's source database; it does not update the actual file on disk being edited by the user. Use `save()` instead here so that we do indeed update the document before formatting here.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15568. 
N/A
> save file before formatting document

- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/tests/automation/testthat/test-automation-sweave.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses https://github.com/rstudio/rstudio/issues/15574.
A recent PR added support for variable-width chunks, intended primarily for R Markdown and Quarto documents. This change relied on the capture length for the highlighter regular expressions, under the assumption that the start and end chunk would use an equal-length prefix.
This, of course, is not true for Sweave documents. Fortunately, the fix is simple -- don't use a capturing regular expression in that scenario.
This PR also brings a brown-bag fix -- some objects might report a missing value for `length()`, so we only try to compute that for character vectors (which should never do that).
Included in this PR.
Test via notes in https://github.com/rstudio/rstudio/issues/15574.
N/A
> fix regression with Sweave background highlight

- src/cpp/core/include/core/http/AsyncClient.hpp
- src/cpp/core/include/core/http/AsyncConnection.hpp
- src/cpp/core/include/core/http/AsyncConnectionImpl.hpp
- src/cpp/core/include/core/http/TcpIpAsyncClient.hpp
- src/cpp/core/include/core/http/TcpIpAsyncClientSsl.hpp
- src/cpp/server/session/ServerSessionProxy.cpp
Addresses: https://github.com/rstudio/rstudio-pro/issues/7264
Need to ensure the client to rserver connection, i.e. AsyncConnectionImpl uses the same strand as the AsyncClient for rserver to backend for websocket connections that are "full duplex", i.e. emit traffic at the same time on both sides. When using openssl, boost::asio requires that handlers run on a single thread. Previously AsyncClient itself got a strand to fix part of the problem but this fixes the other side.
I did not start out using a pointer for the setStrand method in AsyncClient but ended up there because:
1) The strand class is not copyable and requires an io_service as a constructor arg that's also a constructor param.
2) The AsyncClient is extended by several other classes with default params 
3) Most callers don't …
> Single-thread proxy connections for openssl

- docs/user/rstudio/ide/guide/documents/quarto-project.qmd
Adds a short description of the `Preview Images and Equations` and `Show Previews Inline` options when in source-mode and editing markdown.
Addresses https://github.com/rstudio/rstudio/issues/15416
Please review for style and accuracy.
> Add summary of markdown preview options

- src/cpp/tests/testthat/test-jobs.R
Get builds working (on Mac AMI) by skipping a troublesome test, at least for now.
Skip test on Mac, the failure is:
```
[2025-01-09T16:51:10.322Z] Failure (ine = 210:col = 4;file:///private/var/lib/jenkins/workspace/IDE/OS-Builds/Platforms/macos-pipeline/rel-kousa-dogwood/src/cpp/tests/testthat/test-jobs.Rtest-jobs.R:210:4cript jobs run and can be replayed
[2025-01-09T16:51:10.322Z] file.exists(the_file) is not TRUE
[2025-01-09T16:51:10.322Z] 
[2025-01-09T16:51:10.322Z] `actual`:   FALSE
[2025-01-09T16:51:12.223Z] `expected`: TRUE 
```
> skip test on Mac

- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionUserPrefValues.R
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_fr.properties
Related to #15571
Change preference text from "Submit crash reports to RStudio" to "Submit crash reports to Posit".
NA
NA
NA
> change RStudio to Posit in command

- src/cpp/session/modules/SessionCodeTools.R
Address a edge case of #10869 
Remove leading `?` from `token` and we are able to press F1 and it works if function is fully typed out.
NA
NA
NA
Signed contributor agreement
> Support F1 if leading `?`

- docs/news/_quarto.yml
- docs/user/rstudio/_quarto.yml
- src/cpp/tools/generate-cdp-client.R
- src/gwt/tools/generate-prefs.R
- src/node/desktop/src/ui/splash/splash.html
Addresses open-source side of #15580; I'll make a separate PR for any pro-only instances I find.
Most displayed copyright years are dynamically generated at build time, these are the ones I found that are not.
- release notes
- user guide
- the comment block header for some source files generated at build time
- the splash screen (dev builds; set automatically in real builds)
NA
If you find any other places in the UI or docs that use 2024 as an upper bound, please add to this issue.
NA
> bump hardcoded copyright 2024 -> 2025

- src/cpp/session/modules/quarto/SessionQuarto.cpp
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.hpp
- src/cpp/session/modules/tex/SessionRnwWeave.cpp
Addresses part of https://github.com/rstudio/rstudio/issues/15562. Intentionally targeted to main; I don't think this meets the bar for the patch release + feels a bit risky.
Update the regular expression used for parsing; in particular, allow an optional capture for the `[chunk name]`.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15562.
N/A
> allow for chunk name when parsing knitr errors

- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/event-bus-types.ts
- src/node/desktop/src/main/main-window.ts
Addresses https://github.com/rstudio/rstudio-pro/issues/7259
Another startup timing issue where, on some "faster" systems, Desktop Pro was still not loading the file that was double-clicked to launch RStudio.
The problem was that the main window may not have finished loading and initializing by the time the application got the 'load-file' message and entered the ready state, such that `gwtCallback` was still `null`. The old code then tried setting an event handler on `gwtCallback` to wait for things to be ready, but since `gwtCallback` was null, that was a no-op.
Fixed by checking if `gwtCallback` and `gwtCallback.initialized` are set when handling `open-file`, and if not, wait for a message from the main-window using the global event bus to open the file.
None
As before, the change is …
> ensure main window loaded before opening a file

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeLintSource.java
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses https://github.com/rstudio/rstudio/issues/15592.
In Visual Mode, code diagnostics are applied by supplying the contents of that chunk to the diagnostics system directly. However, we weren't accounting for the (optional) chunk header displayed for evaluated versus unevaluated / verbatim code chunks. This PR rectifies that by removing the chunk header if it exists.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15592.
N/A
> fix up diagnostics for unevaluated code chunks in visual mode

- cmake/globals.cmake
- dependencies/common/install-packages
- dependencies/osx/install-dependencies-osx
- dependencies/osx/install-dependencies-osx-jenkins
- jenkins/Jenkinsfile.macos
- package/osx/cmake/prepare-package.cmake
- package/osx/make-package
- src/cpp/rstudio-tests.in
- src/cpp/tests/testthat/test-jobs.R
- src/gwt/CMakeLists.txt
Use Mac AMI for Cranberry Hibiscus (2024.09) builds.
Backported changes from rel-kousa-dogwood.
NA
NA
NA
> Backport mac ami changes to rel-cranberry-hibiscus

- jenkins/Jenkinsfile.macos
Simplify the Mac jenkinsfile by removing unnecessary `matrix`, and enable simultaneous builds of open-source and pro on different build agents (we now have two Mac agents for use by IDE builds).
> [!NOTE]
> Most of this change is just un-indenting a bunch of lines without any other changes, plus a few deleted lines. Suggest the ignore whitespace option in github diff!
The primary change is to remove `lock('synchronous-matrix-ami')` as this will prevent builds from running simultaneously on different agents. As part of this I removed the `matrix` since we weren't actually using that (i.e. we had only a single axis).
We still have `disableConcurrentBuilds()` in the Jenkinsfile, so we won't be able to run (for example) two open-source builds simultanously on separate agents, but this change …
> remove unnecessary matrix and stage lock

- NEWS.md
- src/cpp/session/modules/SessionHelp.R
Addresses the last bits of #10869. The idea behind stripping the package is that it is not very helpful to retrieve help from `importFrom things`
Basically, the bit didn't search in the correct place before
NA
I will continue to test to make sure everything is working smoothly
NEWS
Signed contributor agreement
> Fully support F1 shortcut for dev help

- NEWS.md
- src/gwt/acesupport/acemode/r_code_model.js
Addresses https://github.com/rstudio/rstudio/issues/12501.
Discovery of column names in dplyr pipe completions is done on the client side. The code doing this was inadvertently skipping an extra token, due to the need to check for an `=` following an identifier name.
This PR resolves the issue by moving the cursor back following a missing `=`.
TODO
Test via notes in https://github.com/rstudio/rstudio/issues/12501.
N/A
> fix issue with missing completion after select

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
- src/node/desktop/src/main/app-state.ts
- src/node/desktop/src/main/application-launch.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
Addresses https://github.com/rstudio/rstudio/issues/15409.
- After `client_init` has finished, forward the project directory to the desktop application.
- Use that project directory when launching new instances of RStudio via "Open in New Window".
- Fall back to home directory rather than root directory if no project is open.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15409.
N/A
> use project directory / home directory for new RStudio sessions

- NEWS.md
- src/cpp/core/json/JsonRpc.cpp
With a current boost version (tested with 1.86.0) rstudio does not build because of
```
rstudio-2024.12.0-467/src/cpp/core/json/JsonRpc.cpp: In member function bool rstudio::core::json::JsonRpcResponse::hasAfterResponse() const:
rstudio-2024.12.0-467/src/cpp/core/json/JsonRpc.cpp:196:11: error: cannot convert const boost::function<void()> to bool in return
196 |    return afterResponse_;
|           ^~~~~~~~~~~~~~
|           |
|           const boost::function<void()>
```
Function returning a `bool` requires an explicit cast in newer boost versions.
This has been added.
none
> …
> cast to bool (fix current boost)

- jenkins/Jenkinsfile.macos
Addresses https://github.com/rstudio/rstudio-pro/issues/7286.
Use single-quoted strings, so that Groovy string interpolation doesn't expand keys in the string itself (let that expansion happen in the shell instead).
The build system is the automated test.
N/A
N/A
> avoid groovy string interpolation

- src/node/desktop/.vscode/settings.json
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/native/desktop.node.d.ts
- src/node/desktop/src/native/desktop/desktop.cc
Addresses https://github.com/rstudio/rstudio/issues/13007.
Instead of using node-system-fonts to enumerate fonts on Windows, just use Windows APIs directly. We still keep node-system-fonts around for macOS, but we're pretty close to removing our dependence on it.
N/A
Test that installed fixed-width fonts are still listed and available in the Tools -> Appearance -> Editor Font list. It's also worth comparing the fonts that get displayed in that list for older RStudio installations versus this one.
N/A
> use Windows APIs for enumerating fonts

- package/win32/codesign.bat
- package/win32/make-install-win32.bat
- package/win32/make-package.bat
Cleanup indentation of `make-package.bat` and `make-install-win32.bat` (4 spaces instead of 6, get rid of stray hard-tabs).
This is prep work for some refactoring to support signing the executables.
Also deleted unused and obsolete `codesign.bat` (that logic was moved into the Jenkinsfile a few years ago).
Tested by the build pipeline.
> cleanup batch file indentation (Windows packaging scripts)

- jenkins/Jenkinsfile.windows
Followup to https://github.com/rstudio/rstudio/pull/15647.
I noticed we are not timestamping our signatures on Windows. Without this Windows can't be sure the app was signed while the signature was still valid.
Fix by adding the switch to apply a timestamp.
NA
Test via Digital Signatures in file properties and see if there's a timestamp.
NA
> use timestamp when signing Windows binaries

- cmake/globals.cmake
- docker/jenkins/Dockerfile.al2
- jenkins/utils.groovy
- src/cpp/CMakeLists.txt
Putting the check for enabling Quarto and Crashpad in the `make-*` package scripts accidentally broke several other builds. Moving the check for AL2 into cmake should fix the builds
> Specify which documentation has …
> Move disabling Quarto and Crashpad for AL2 check into cmake files

- NEWS.md
- src/node/desktop/src/main/application.ts
Addresses #15554
The problem here is that the code that tries to remove the "path to current executable" from the list of command-line arguments sent via the `second-instance` event didn't work if the second instance was in a different location than the first.
The fix is to remove the first entry from argv sent to `second-instance`, as it will always be the executable path.
None that I know of. Tricky to automate since it requires multiple versions of RStudio installed in different locations and running at the same time.
Test as described in issue. The easier repro is to put two copies of RStudio on your system, such as RStudio1.app and RStudio2.app and:
- launch RStudio1.app and wait for it to load
- launch RStudio2.app (without this fix this will reproduce the issue)
NOTE: this is not …
> Fix problem with launching multiple instances of RStudio installed in different locations

- src/cpp/core/r_util/RProjectFile.cpp
- src/cpp/session/modules/automation/SessionAutomationRemote.R
- src/cpp/session/modules/automation/SessionAutomationToolsProjects.R
- src/cpp/session/projects/SessionProjectContext.cpp
- src/cpp/tests/automation/testthat/test-automation-projects.R
- version/news/NEWS-2024.12.1-kousa-dogwood.md
- Only add the ProjectId field to the .Rproj file if it is required.
- Preserve it, if it already exists within the file.
Mostly straightforward changes; the main bit is adding a project id to the "default" project configuration, but only if it appears to be required (e.g. via user prefs or admin setting).
Included in the PR.
- Create a new RStudio project. Check that the .Rproj file does not contain a ProjectId field (use a text editor).
- Use Tools -> Global Options..., and set a custom user data directory. The project should now contain a ProjectId entry.
N/A
> only generate project id if required

- docker/jenkins/Dockerfile.opensuse15
Addresses https://github.com/rstudio/rstudio-pro/issues/7342
Changed `5` to `6`.
I did test builds using the Dockerfile of both Workbench and Desktop Pro, and confirmed they built and were installable and runnable on OpenSUSE Leap/15.6.
NA
General coverage on OpenSUSE will suffice. Nothing to specifically test.
NA
> use Leap 15.6 (up from 15.5) on build image

- src/cpp/r/RExec.cpp
- src/cpp/r/session/RInit.cpp
- src/cpp/server/session/ServerSessionManager.cpp
- src/cpp/session/SessionConsoleInput.cpp
- src/cpp/session/SessionInit.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/http/SessionHttpConnectionListenerImpl.hpp
- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/modules/environment/SessionEnvironment.cpp
- src/cpp/session/modules/rmarkdown/NotebookExec.cpp
- src/tools/clang-tsan-build
- version/news/NEWS-2024.12.1-kousa-dogwood.md
Addresses https://github.com/rstudio/rstudio-pro/issues/7322.
The `onConsoleOutput` signal is actually emitted from a separate thread. The code wherein it's emitted even points this out:
https://github.com/rstudio/rstudio/blob/137c91db80581e808e9f7305245badc8b54178e9/src/cpp/session/SessionModuleContext.cpp#L2214-L2229
but unfortunately, it's easy to miss that implicit requirement. To handle this, I've added a recursive mutex to code paths which access shared data structures from an `onConsoleOutput` signal.
This PR also includes some switches from plain global variables to atomic versions where the thread sanitizer was able to "see" them being accessed by multiple threads.
N/A
Test via notes in https://github.com/rstudio/rstudio-pro/issues/7322. For what it's worth, I found the issue …
> synchronize concurrent accesses with mutex in more places

- NEWS.md
- src/cpp/r/include/r/session/REventLoop.hpp
- src/cpp/r/session/REmbeddedPosix.cpp
- src/cpp/r/session/REmbeddedWin32.cpp
- src/cpp/r/session/graphics/RGraphicsPlot.cpp
- src/cpp/r/session/graphics/RShadowPngGraphicsHandler.cpp
Addresses https://github.com/rstudio/rstudio/issues/11856.
RStudio processes RPCs via its polled event handler, which gets called whenever R tries to process events via R_ProcessEvents. However, this can be called recursively in some cases, and so we can end up in situations where RPCs get handled while a different RPC is currently being handled.
This can lead to issues when those RPCs manipulate the same data structures; e.g. if we delete the graphics device while another one is in the middle of generating plots. Hence the crash in https://github.com/rstudio/rstudio/issues/11856.
This PR resolves the issue in a narrow way, specifically by disabling the polled event handler temporarily while writing plots to disk.
N/A; not easily amenable to automated testing. …
> don't process RPCs while rendering plots

- src/cpp/core/include/core/system/Interrupts.hpp
- src/cpp/core/system/PosixInterrupts.cpp
- src/cpp/core/system/Win32ChildProcess.cpp
- src/cpp/core/system/Win32Interrupts.cpp
- src/cpp/r/session/RSession.cpp
- src/cpp/session/SessionAsyncRProcess.cpp
- src/cpp/session/include/session/SessionAsyncRProcess.hpp
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
- src/gwt/src/org/rstudio/studio/client/rmarkdown/RmdOutput.java
Addresses https://github.com/rstudio/rstudio/issues/12109.
For the classes we use to handle child processes, we often signal a process should be terminated via returning `false` in the `onContinue()` handler. This termination is done by sending a `SIGTERM` signal to the process (or equivalent on Windows).
Unfortunately, terminating an R process in this way implies that exit handlers won't get executed, which is problematic for code which needs to perform cleanup tasks on quit. This PR attempts to remedy the issue by first sending an interrupt when termination is requested, and then later forcefully terminating if the interrupt is not respected.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/12109.
N/A
> interrupt R sessions before termination

- NEWS.md
- src/cpp/core/include/core/r_util/RProjectFile.hpp
- src/cpp/core/r_util/RProjectFile.cpp
- src/cpp/session/projects/SessionProjects.cpp
Addresses #15524
If and when future versions of RStudio add new fields to the .Rproj file, this version of RStudio will now preserve those fields when rewriting the file.
This places a new constraint on the .Rproj file: all new fields added in the future **must** be added to the final section of the file (i.e. after all currently-known fields, separated by a blank line).
For example, "Great" and "Super" were added to this .Rproj file in the correct location:
```
Version: 1.0
ProjectId: cc66b902-21c6-48a1-8759-90d1f47ffe97
RestoreWorkspace: Yes
SaveWorkspace: No
AlwaysSaveHistory: No
EnableCodeIndexing: No
UseSpacesForTab: Yes
NumSpacesForTab: 4
Encoding: GB2312
RnwWeave: knitr
LaTeX: XeLaTeX
RootDocument: NAMESPACE
LineEndingConversion: Native
BuildType: Package
PackageCleanBeforeInstall: …
```
> Preserve unknown fields in .Rproj files

- NEWS.md
- src/cpp/core/include/core/Thread.hpp
- src/cpp/core/include/core/system/ChildProcess.hpp
- src/cpp/core/system/Win32ChildProcess.cpp
Addresses https://github.com/rstudio/rstudio/issues/13222.
When reading output from a child process, do so in a child thread, since `::ReadFile()` can evidently hang in certain scenarios.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/13222.
N/A
> fix hang when invoking 'git' in some contexts

- NEWS.md
- src/cpp/core/http/ProxyUtils.cpp
- src/cpp/core/http/ProxyUtilsTests.cpp
- src/cpp/core/include/core/http/NoProxyRules.hpp
- src/cpp/core/include/core/http/ProxyUtils.hpp
- src/cpp/session/SessionHttpMethods.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/include/session/http/SessionRequest.hpp
Addresses https://github.com/rstudio/rstudio/issues/15530.
There is some functionality within RStudio that relies on the session being able to send session requests to itself. This can fail in scenarios where the session has also been configured with an `http_proxy` that doesn't handle this, or if that proxy doesn't even exist.
Included in the PR.
Test via notes in https://github.com/rstudio/rstudio/issues/15530. Note that (I suspect) this issue only affects RStudio Desktop, since RStudio Server will typically use a domain socket instead for requests.
N/A
> avoid proxy when sending session requests

- NEWS.md
- src/cpp/session/SessionConsoleProcess.cpp
- src/cpp/session/include/session/SessionConsoleProcess.hpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressDialog.java
Addresses https://github.com/rstudio/rstudio/issues/6471.
When stopping a console process (e.g. git) via the Stop button in UI, we now send a proper interrupt to the process rather than just directly terminating the process with SIGTERM. We still ensure that a SIGTERM is later sent if the user clicks the Stop button 3 or more times.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/6471.
N/A
> send SIGINT when first stopping console processes

- NEWS.md
Adds a news entry for the SELinux policy module.
Relates to https://github.com/rstudio/rstudio/issues/4937
Documentation for this feature was included in the implementation PR.
> Add SELinux to news

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java
- src/gwt/src/org/rstudio/studio/client/application/LoggedOutDialog.java
- src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants.java
- src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants_fr.properties
Addresses #15698
It was originally assumed that this dialog would only appear in Posit Workbench so the strings were hardcoded and mentioned "Posit Workbench".
It can display in open-source Server as well, so made the strings localizable and show slightly different message in open-source vs. Workbench.
NA
Test as described in issue on open-source Server. Should also do a sanity check of the dialog on Workbench, so I've marked this for both projects.
NA
> Change Workbench to RStudio Server in logged-out dialog title

- docs/news/index.qmd
Update release notes for IDE / Workbench 2024.12.1+563.pro5 release.
This change has been generated by the release script. Content is generated based on `version/news/NEWS-2024.12.1-kousa-dogwood.md`. If this file was not in sync with Pro or did not include items from other sources (i.e. the vscode extension), then some items may be missing.  Please verify content/formatting is correct and make changes if necessary.
> Update release notes for 2024.12.1+563.pro5

- NEWS.md
- src/cpp/session/modules/SessionRCompletions.R
Addresses https://github.com/rstudio/rstudio/issues/15706.
Invoking an S3 method directly can interfere with dispatch done by `NextMethod()`; to avoid this, invoke the `.DollarNames` generic instead of the method we discover. (We still use the presence of such a method as an indication that we should use `.DollarNames` for requesting object names.)
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15706. Note that the issue will only reproduce with R6 2.6.0.
N/A
> avoid issue with S3 dispatch by calling .DollarNames generic

- src/cpp/core/include/core/system/ChildProcess.hpp
- src/cpp/core/system/PosixChildProcess.cpp
- src/cpp/core/system/Win32ChildProcess.cpp
Fixes a failure in file locking tests; related to https://github.com/rstudio/rstudio/issues/13222.
https://github.com/rstudio/rstudio/pull/15692 made a change that allowed us to read stdout + stderr in a non-blocking way, by using separate threads to read output on these threads. However, the POSIX side of this code could potentially close any open pipes (including those reading stdout / stderr) after seeing a process had exited.
This PR re-arranges that code so that we join the stdout + stderr read threads before attempting to close any open pipes.
N/A
N/A
> fixup for sync child process stdout, stderr read

- NEWS.md
- jenkins/Jenkinsfile.linux
Addresses https://github.com/rstudio/rstudio-pro/issues/7445
Keeping up-to-date with Electron is increasingly expensive on some Linux distros so we are reducing the platform matrix.
Exclude desktop builds on opensuse15, focal, rhel8.
If we are running desktop tests on these platforms they will need to be disabled; I've pinged the appropriate person.
https://github.com/rstudio/rstudio-pro/issues/7475
> Reduce Desktop build matrix

- NEWS.md
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
Addresses https://github.com/rstudio/rstudio/issues/15579.
Redo the parsing of R Markdown render outputs, to handle alternate ways that an error might be presented.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15579.
N/A
> handle new-style rmarkdown render error format

- cmake/compiler.cmake
Lets us build RStudio on Windows with C++17 support.
> keep older deprecated C++ tools around for now

- src/cpp/shared_core/FilePath.cpp
- src/cpp/shared_core/FilePathTests.cpp
- src/cpp/shared_core/include/shared_core/FilePath.hpp
OS companion to https://github.com/rstudio/rstudio-pro/pull/7512
Adds ability to retrieve the owner of a file.
Added the `getFileOwner` function to retrieve the username of the file owner using POSIX functions.
Added a unit test case to verify the functionality of the `getFileOwner` method. This test creates a temporary file, retrieves its owner, and compares it with the current user.
N/A
N/A
> OS companion to Audited Job Details Store

- src/cpp/session/SessionServerRpc.cpp
By default run will exit if there's no work but the guard will keep that from happening.
> Need the work guard to keep run() from returning

- NEWS.md
- src/cpp/shared_core/FilePath.cpp
Addresses https://github.com/rstudio/rstudio-pro/issues/7521 by setting an explicit type for `.bib` files.
I think it's worth hard coding it since the number of commas in the file shouldn't determine if the file can be opened by RStudio if the file still contains ascii
> Add mime type for .bib files

- NEWS.md
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Updates #15450
Update electron from 34.2.0 to 34.3.0.
https://releases.electronjs.org/release/compare/v34.2.0/v34.3.0
Ran BRAT tests successfully
Routine usage.
NA
> update to electron 34.3.0

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleInterpreterVersion.java
Addresses #15757 
The UI widget that uses this image is not implemented to support keyboard or screen reader use. Marking the image as cosmetic so it doesn't show up in screen readers.
None currently.
Added notes to the issue.
NA
> fix unlabeled image in console toolbar

- src/cpp/session/resources/themes/material.rstheme
addresses #15753
the current material theme has no selected word or text highlighting (or rather, they were set to the same as the background colour). 
I just stole the settings from idle_fingers.rstheme.
No tests. Small style change which works fine on my pc. 
n/a
none
- [ no] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md`
- [ yes] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [ no] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ not tested] This PR passes all local unit tests
I have signed the contributor aggreement.
> Update Material theme selected word and line highlighting

- NEWS.md
- src/cpp/session/SessionSourceDatabase.cpp
- src/cpp/session/modules/SessionSource.cpp
Addresses https://github.com/rstudio/rstudio/issues/15767.
When checking how many documents are in the source database, instead of attempting to _read_ each source document, just list the document paths themselves, and take that length.
Test via notes in https://github.com/rstudio/rstudio/issues/15767.
N/A
> improve performance when reading number of source documents

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCopilotHelper.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
Addresses part of https://github.com/rstudio/rstudio/issues/13427.
Extend the existing Copilot integration to visual editor code chunks; mostly by checking for visual mode + an active visual editor in the TextEditingTargetCopilotHelper, and doing some magic to compute the equivalent source editor cursor position when requesting Copilot completions.
N/A
Test that Copilot completions are offered within R code chunks of the visual editor.
N/A
> support copilot in visual editor code chunks

- src/gwt/src/org/rstudio/core/client/AnsiCode.java
- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
Addresses https://github.com/rstudio/rstudio/issues/15777.
Tweak how we detect incomplete CSR escapes. In particular:
- Check for single `\033` escapes up-front, and buffer those.
- Parse SGR escapes as just a special case of a CSI escape.
- Check for an incomplete CSI escape before ANSI escapes, and continue parsing those.
Tests included.
Test via notes in https://github.com/rstudio/rstudio/issues/15777.
N/A
> tweak parsing of incomplete CSI escapes

- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants.java
- src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants_fr.properties
- src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java
- src/gwt/src/org/rstudio/studio/client/application/ui/serializationprogress/ApplicationSerializationProgress.java
Addresses https://github.com/rstudio/rstudio/issues/14511.
- Use an alternate message when restoring R.
- Try to be more careful about how we handle and dismiss serialization messages.
- Try to be more careful in how we manage the suspend UI state.
This PR doesn't actually change anything around how suspend / resume is performed; it just changes how it's reported to the user. In particular, we now properly report "Restoring R session..." while the session is being restored, instead of "Backing up R session...", which surely caused some confusion.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/14511.
N/A
> use alternate message when restoring R

- cmake/compiler.cmake
- src/cpp/CMakeLists.txt
Addresses build issues on macOS, where `-std=gnu++11` is mysteriously appended to the compilation command line.
Also removes an old workaround for a no-longer-used and no-longer-supported version of Boost.
> use CMAKE_CXX_STANDARD to set default C++ standard

- src/cpp/core/include/core/collection/Tree.hpp
We were using a relatively old version of tree.hh; this PR pulls in an updated version. This also resolves compilation warnings related to deprecated declarations when using this with the C++17 standard.
> update bundled tree.hh

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Addresses https://github.com/rstudio/rstudio/issues/15734.
If a formatter has been configured, and the document is configured to auto-format on save, then always allow the save command to run (since we don't know if the format-before-save action might mutate a "clean" document).
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15734.
N/A
> always allow save when formatter is enabled

- NEWS.md
- src/cpp/core/r_util/RTokenizer.cpp
- src/cpp/core/system/PosixSystem.cpp
- src/cpp/ext/CMakeLists.txt
Addresses https://github.com/rstudio/rstudio/issues/15801.
Use an alternate, safer macOS API when testing if a `wchar_t` maps to an alphanumeric Unicode code point.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15801.
N/A
> fix crash on macOS with R files containing binary data

- NEWS.md
- src/cpp/session/modules/build/SessionInstallRtools.R
Addresses https://github.com/rstudio/rstudio/issues/15803.
- If the current repository doesn't appear to be an actual CRAN mirror, then fall back to the default cloud mirror.
- Add links for rtools44 and rtools45 installers. Those have been uploaded.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15803.
N/A
> tweaks for rtools installation

- NEWS.md
- src/cpp/session/modules/NotebookConditions.R
Fixes an issue where no newline was printed between messages emitted by `rlang::inform()` when executed as part of a Notebook chunk.
> add newline to rlang messages

- src/cpp/session/CMakeLists.txt
The copilot-language-server was not being found when running a dev build (desktop or server) on macOS (and presumably also on Linux).
Get rid of reference to `COPILOT_ENABLED`; I had removed that but missed an instance.
NA
Dev environment only.
NA
> fix problem finding copilot in dev builds

- src/node/desktop/src/renderer/desktop-bridge.ts
Fix build break in desktop pro (i.e. after this gets merged to pro).
> trailing comma so pro build doesn't have a syntax error

- src/cpp/core/json/JsonRpc.cpp
- src/cpp/core/system/PosixSystem.cpp
- src/cpp/shared_core/include/shared_core/system/SyslogDestination.hpp
- src/cpp/shared_core/system/SyslogDestination.cpp
Companion to: https://github.com/rstudio/rstudio-pro/pull/7456
Includes a "safeLogToSyslog" message for linux - used for situations you need to log an error when the logging system is not available, e.g. after the fork, before the exec, or before the log has been initialized.
> Companion to pro support for improvements to PAM auth

- NEWS.md
- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/modules/SessionCopilot.R
- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/session/session-options.json
Addresses #15823
Use the recommended approach (`workspace/didChangeConfiguration`) for setting proxy information (and github-enterprise server URL) instead of the deprecated `setEditorInfo` message. See the issue for details on what the new message (json) looks like.
As part of this change I added the option for setting a Kerberos Service Principal value for GitHub Copilot proxy settings. This defaults to blank, but a string value can be set with one of:
- `COPILOT_PROXY_KERBEROS_SERVICE_PRINCIPAL` (environment variable)
- `copilot-proxy-kerberos-service-principal` (rsession.conf setting)
- `rstudio.copilot.proxyKerberosServicePrincipal` (R option)
I also tweaked the Copilot logging macros to avoid name clashes with "message" and "formatted", and added debug-level logging of messages sent …
> Use workspace/didChangeConfiguration notification to set GitHub Copilot Proxy and auth server settings

- docs/news/index.qmd
- version/news/NEWS-2024.12.0-kousa-dogwood.md
Related to: [`rstudio-pro` #7709](https://github.com/rstudio/rstudio-pro/issues/7709)
- adds table to show previous configuration values
- moves information on configuration values into Upgrade section
Can move the content (back) to the New - Workbench section if deemed more appropriate. 
Built locally
> [DOC] Backport - Updating release notes with previous configuration values

- src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java
- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/ShellPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
In R, users will often emit leading and trailing newlines for certain outputs (e.g. messages) to help make them visually distinct from other pieces of output. Because we're now managing that sort of display ourselves via sections for output in the console, we can trim those leading + trailing newlines.
We now clean up newlines within a section when:
- A new type of console output is started;
- Execution is finished (e.g. for an R Markdown chunk),
- The console prompt is displayed.
Each of the above signals that the previous section is "complete" and cannot be re-opened, and so it's an opportunity for us to normalize its output.
N/A
N/A
N/A
> more robust newline trimming implementation

- src/cpp/session/SessionMain.cpp
- src/cpp/session/SessionModuleContext.cpp
Fixes an issue from the recent condition highlight work. Now that console actions and events are emitted when output is processed in the event queue, we no longer need to fire those events here.
https://github.com/rstudio/rstudio/blob/04820b29de92c83dcb3a863b4dcd37ae0395bee9/src/cpp/session/SessionClientEventQueue.cpp#L438-L453
Also, using this to give a banner to the "Restarting R session..." message.
> fix issue with duplicated restart message

- dependencies/common/install-soci
- src/cpp/ext/CMakeLists.txt
`brew install cmake` is now installing cmake 4.0, which causes some build failures (soci during dependency step, and yaml-cpp during build step).
We should support building even with latest & greatest cmake.
Add ` -DCMAKE_POLICY_VERSION_MINIMUM=3.5 ` for SOCI and yaml-cpp, as suggested by cmake's error message.
Build-time
Nothing to test.
NA
> enable building with cmake 4.x

- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/session/modules/SessionUserPrefValues.R
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_fr.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.java
Add-on to #15848
Added a user preference to control whether Copilot messages (sent by Copilot) are shown or not. These are shown in a modal dialog, so this serves as an escape hatch if Copilot starts spamming us with a bunch of messages.
Currently the only known message is the one shown when you've used up all 200 free completions for the month with a free Copilot account.
None
See notes in issue.
None
> add a user preference to suppress Copilot message dialogs

- NEWS.md
- src/cpp/session/SessionMain.cpp
Addresses https://github.com/rstudio/rstudio-pro/issues/7732.
Straightforward setting of environment variable.
N/A
N/A; I believe this will be verified externally?
N/A
> set SPARK_CONNECT_USER_AGENT on startup

- src/gwt/src/org/rstudio/core/client/VirtualConsole.css
This also ensures that the contrast for the colours used meet the WCAG AA requirements.
> improve contrast for colors

- NEWS.md
- src/cpp/session/modules/SessionCopilot.cpp
Addresses #15858
Prevent `startAgent()` (which we call at least twice on startup) from starting multiple copilot processes.
None
Test per issue description.
NA
> Prevent Copilot process from starting multiple times

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionCopilot.cpp
- src/cpp/session/modules/SessionUserPrefValues.R
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_fr.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.java
Addresses #15816
If RStudio has a project open, and the new user preference ("Use RStudio project folder as a Copilot workspace") is set to true (the default), pass the project folder to Copilot as the "workspace folder" when initializing Copilot.
None
[The documention](https://github.com/github/copilot-language-server-release?tab=readme-ov-file#workspace-folders-synchronization) says "Workspace folders are optional but highly recommended as they greatly improve the quality of suggestions." Otherwise, no information on what, exactly, this does.
Good luck testing that.
You can turn on logging by adding `COPILOT_LOG_LEVEL=3` to `~/.Renviron` then check that we pass the correct information to Copilot when initializing it.
For example, with no project folder, and/or the feature is off, should …
> Use RStudio project folder as GitHub Copilot Workspace Folder

- src/cpp/session/modules/SessionCopilot.cpp
With the newer `copilot-language-server`, was often getting an error after opening a source file in RStudio, saying "Copilot: Request getCompletions failed with message: Illegal value for lineNumber".
We were not passing the text of the document via `textDocument/didOpen` in response to `onDocAdded`, but we were via `onDocUpdated`. So when Copilot thinks the file is empty it complains about the current line number being out of range.
Fixed by passing the document contents in both cases.
None
Routine usage.
None
> Prevent "illegal value for lineNumber" from Copilot

- src/cpp/ext/CMakeLists.txt
Prevent pro commit hooks from worrying that a commit hash on a public repo is a Big Secret.
> pragma to avoid commit hash being treated as a secret

- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ChangelistTable.java
Addresses https://github.com/rstudio/rstudio/issues/15877.
The DOM structure of the console output history will differ depending on whether console virtualization is enabled or not. This affects how the extended error widget should be inserted. Accommodate those differences.
See https://github.com/rstudio/rstudio/issues/15877.
N/A
> fix handling of extended errors w/virtualized console

- src/cpp/ext/CMakeLists.txt
All Builds are currently broken with the error:
```
[2025-04-09T13:55:28.228Z] [1/9] Creating directories for 'websocketpp-populate'
[2025-04-09T13:55:28.228Z] [1/9] Performing download step (git clone) for 'websocketpp-populate'
[2025-04-09T13:55:28.228Z] Cloning into 'websocketpp-src'...
[2025-04-09T13:55:28.228Z] fatal: reference is not a tree: a11fa6fe4937ca251753e90b1836a68bf57768a9
[2025-04-09T13:55:28.228Z] CMake Error at websocketpp-subbuild/websocketpp-populate-prefix/tmp/websocketpp-populate-gitclone.cmake:49 (message):
[2025-04-09T13:55:28.228Z]   Failed to checkout tag: 'a11fa6fe4937ca251753e90b1836a68bf57768a9'
[2025-04-09T13:55:28.228Z] 
[2025-04-09T13:55:28.228Z] 
[2025-04-09T13:55:28.228Z] FAILED: websocketpp-populate-prefix/src/websocketpp-populate-stamp/websocketpp-popula …
```
> Update websocketpp revision to latest

- package/linux/make-package
This is primarily to help support faster development builds with RStudio Workbench.
We can set `RSTUDIO_BUILD_PACKAGE=0` to build RStudio Workbench without actually building the `.deb` installer (which is very slow), and instead manually install components ourselves (much faster).
> allow skipping cpack step

- git_hooks/secrets/.secrets.baseline
- src/cpp/session/modules/SessionCopilot.cpp
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/copilot/server/CopilotServerOperations.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCopilotHelper.java
Part of #15861 -- notify Copilot when we display a completion
Send `textDocument/didShowCompletion` notification to Copilot when we display a completion (i.e. ghost text) that was returned to us by Copilot.
See https://github.com/github/copilot-language-server-release?tab=readme-ov-file#inline-completions for more details.
None
Will add notes to issue once it is complete.
None
> notify copilot when we show a completion

- jenkins/Jenkinsfile.windows
The smksp_cert_sync.exe tool stopped working on the latest update of Windows. An alternate method to achieve the same is to use smctl.exe directly.
Attempt to fix the Windows builds.
Use a different method to sync signing certs during build signing.
Normal tests for Windows installers, assuming this addresses the build issue.
> Use a different method of syncing certs on windows

- src/cpp/session/modules/SessionCopilot.cpp
Addresses https://github.com/rstudio/rstudio/issues/15910
Log all messages from `didChangeStatus` at Debug level. Note that in prior releases we did not log this at all, so having it at Debug level gives us extra diagnostic possibilities without spamming the logs with non-helpful errors.
None
See issue.
NA
> log messages from didChangeStatus at Debug level

- dependencies/windows/install-soci/install-soci.R
- docker/jenkins/Dockerfile.windows
This is the Windows-specific fix for what I fixed on Mac and Linux here: https://github.com/rstudio/rstudio/pull/15844
The tweak to the Dockerfile was to remove a previous tweak I used to force an image rebuild (to again force an image rebuild).
> Fix SOCI build on Windows w/newer Cmake versions

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCopilotHelper.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
Addresses #15912
Revert commit 734b74870aebaeda04382c74b00e9c39406679bd and re-add the overlapping changes from https://github.com/rstudio/rstudio/pull/15885.
Reopened https://github.com/rstudio/rstudio/issues/13427 and assigned to backlog.
NA
Ensure completions not showing up in Visual Mode code chunks, sanity checking of completions in source mode.
NA
> Revert Copilot support in Visual Mode code chunks

- src/cpp/session/modules/SessionRSConnect.R
Addresses #15883
Instead of passing along all env-vars from the current environment, only pass those found in the .Renviron file (with no additional filtering).
None added
See issue
NA
> populate env vars for publishing from .Renviron instead of passing entire environment

- src/cpp/session/modules/SessionRSConnect.R
Fix for the fix for #15883
Method was not returning a vector as the caller expects. Now it does.
None
Rinse and repeat.
NA
> Fix return type from env-var detection

- src/cpp/ext/CMakeLists.txt
CMake project name of this dependency is [`tl-expected`](https://github.com/TartanLlama/expected/blob/master/CMakeLists.txt#L2), not `expected`.
> fix: CMake package name

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/include/session/prefs/UserStateValues.hpp
- src/cpp/session/modules/SessionUserPrefValues.R
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/cpp/session/resources/schema/user-state-schema.json
- src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_fr.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/preferences/electron-desktop-options.ts
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
- src/node/desktop/src/ui/splash/splash.html
- src/node/desktop/src/ui/splash/splash_unversioned.html.in
Addresses #15945 and #15614
Added a user preference for disabling the splash screen (i.e. so it doesn't display at all). Also made the splash screen close when clicked with the mouse.
None added
See original issues for details.
None
> Add option to disable splash screen, close splash screen when clicked

- NEWS.md
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
Addresses #15955
This is an issue with the web-based file dialogs, so RStudio Server and Workbench, and Desktop when not using native file dialogs (the default on Linux desktop).
The "Save As" popup had a z-index of 1000, but it was being invoked from a popup with a z-index of 1001, thus was hidden from view. The 1001 value is set here: https://github.com/rstudio/rstudio/blob/f31e2b74eacb2d55eb544d529fe56375ca92f9d1/src/gwt/src/org/rstudio/core/client/widget/FullscreenPopupPanel.java#L60
Fixed by increasing the dialog to use 1002.
None
Test per scenario in issue.
None
> Ensure Save As dialog is visible when invoked from a popup panel

- git_hooks/secrets/.secrets.baseline
- jenkins/utils.groovy
A bunch of enhancements and changes were made directly to the pro version of `utils.groovy`. This PR syncs those changes upstream back to the OS repo.
Now seems like a good time to do this since we haven't started work on SB yet.
> Copy changes to utils.groovy from pro repo

- dependencies/tools/rstudio-tools.cmd
- dependencies/windows/Install-RStudio-Prereqs.ps1
- dependencies/windows/tools.R
- docker/jenkins/Dockerfile.windows
- docker/win-docker-build-image.cmd
- jenkins/Jenkinsfile.windows
Fixes the Windows Docker builds.
For whatever reason, the `vs_buildtools.exe` tool fails to install Visual Studio tools in C:/Program Files (86)/, but succeeds in other locations. So, put our installation in C:/Program Files instead.
Confirmed that a local win-docker-compile works.
N/A
N/A
N/A
> more MSVC tweaks

- src/cpp/server_core/system/Pam.cpp
Reviewed in: https://github.com/rstudio/rstudio-pro/pull/8041
For pro issue: https://github.com/rstudio/rstudio-pro/issues/8039
Avoid LOG_ERROR since it uses mutexes that can hang if running after-fork/before-exec when the child process is a clone of the parents.
> Avoid LOG_ERROR in code run after fork/before exec

- NEWS.md
- jenkins/Jenkinsfile.build
- jenkins/Jenkinsfile.linux
- jenkins/utils.groovy
Addresses #15940
Remove focal from lists of things to build. For hourly builds, do an x86_64 Server build on jammy instead of focal.
Pro-specific changes will be made when I merge this to pro, tracked with https://github.com/rstudio/rstudio-pro/issues/8042.
Once this is in, I will remove already-created focal builds so they don't show up on the dailies site. Tracked with https://github.com/rstudio/latest-builds/issues/190.
NA
NA
NA
> stop builds for Ubuntu Focal

- NEWS.md
- cmake/globals.cmake
- src/cpp/session/SessionClientEventQueue.cpp
- src/cpp/session/SessionConsoleOutput.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/modules/rmarkdown/NotebookExec.cpp
Addresses https://github.com/rstudio/rstudio/issues/15979.
We use events (signals) to notify other modules when console output of different types is received. As part of the work to support annotated console outputs, I moved some the event firing into the console output queue. However, this can cause an issue:
- Events are flushed from the queue (lock acquired here),
- If a console event is flushed, we signal to other modules that console output was emitted,
- Those receivers might themselves try to add other client events,
- We then attempt to acquire the same aforementioned lock again. Deadlock!
The fix here is to signal console output as it's emitted, not as its processed.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15979.
N/A
> avoid recursion in event handlers

- .gitignore
- .vscode/launch.json
- .vscode/tasks.json
- cmake/compiler.cmake
Mainly so that we get default build + debug tasks to use in VSCode, when opening the repository from the root.
> include vscode launch / tasks

- docs/news/index.qmd
Update release notes for IDE / Workbench 2025.05.0+496.pro5 release.
This change has been generated by the release script. Content is generated based on `version/news/NEWS-2025.05.0-mariposa-orchid.md`. If this file was not in sync with Pro or did not include items from other sources (i.e. the vscode extension), then some items may be missing.  Please verify content/formatting is correct and make changes if necessary.
> Update release notes for 2025.05.0+496.pro5

- NEWS.md
- src/cpp/conf/rsession-dev.conf
- src/cpp/server/ServerMain.cpp
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/modules/SessionFiles.cpp
Addresses https://github.com/rstudio/rstudio/issues/15133.
Introduces a new `/show` endpoint, which allows a user to view files located at arbitrary file paths on the filesystem, as long as that path is considered "viewable". See `isPathViewAllowed()` for more details. Note that file access is still restricted based on the filesystem permissions vs. the session's user.
If we wanted to make this more intentional, we could further restrict this endpoint -- any strong feelings?
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15133.
N/A
> allow view of files within 'allowed-directories'

- src/cpp/r/R/Tools.R
- src/cpp/r/RCntxt.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/modules/NotebookErrors.R
- src/cpp/session/modules/SessionErrors.R
- src/cpp/session/modules/rmarkdown/NotebookErrors.cpp
- src/cpp/tests/automation/testthat/test-automation-rmarkdown.R
- src/cpp/tests/debugger/debugging-14276.R
- src/gwt/src/org/rstudio/studio/client/application/ApplicationInterrupt.java
- version/news/NEWS-2025.05.1-mariposa-orchid.md
Addresses https://github.com/rstudio/rstudio/issues/16000.
Addresses https://github.com/rstudio/rstudio/issues/16002.
I had made some changes to error handling in RStudio that had caused us to skip running the error reporter if it appeared we did not have any stack frames. This change in behavior unfortunately also meant that R Markdown chunk execution was never notified when an error occurred, so it didn't know to stop execution following an error.
Automated tests included.
Test via notes in issues.
N/A
> ensure that code execution stops upon error in R Markdown chunks

- src/cpp/core/http/Request.cpp
- src/cpp/core/include/core/http/Request.hpp
- src/cpp/core/include/core/http/Response.hpp
- src/cpp/core/include/core/json/JsonRpc.hpp
- src/cpp/core/json/JsonRpc.cpp
- src/cpp/core/r_util/REnvironmentPosix.cpp
- src/cpp/core/r_util/RVersionsPosix.cpp
- src/cpp/core/system/PosixSystem.cpp
- src/cpp/core/system/Xdg.cpp
- src/cpp/server/auth/ServerAuthHandler.cpp
- src/cpp/server/include/server/auth/ServerAuthHandler.hpp
- src/cpp/server/session/ServerSessionProxy.cpp
- src/cpp/server_core/http/SecureCookie.cpp
- src/cpp/server_core/include/server_core/http/SecureCookie.hpp
Note: some internal JSON RPC error messages have more detail. Now instead of just "Protocol error" or "Invalid request", it will include the error summary that includes error properties.
1) Improve request/response debugging info so JSON RPC errors are displayed if present
2) Expose more info in JSON RPC errors to make it easier for API developers to identify problems.
3) Debug info to troubleshoot logout failures
4) More info around reading config files
5) Diagnostics around automatic detection of R versions (r-versions file)
(reviewed in PR: https://github.com/rstudio/rstudio-pro/pull/8119)
Improve diagnostics for debug messages and api errors. 
Should be covered by automation. Some internal debug logs and api errors will have changed but hopefully no tests are checking for specific …
> Companion commit with some diagnostics improvements

- src/cpp/r/R/GlobalCallingHandlers.R
- src/cpp/session/modules/automation/SessionAutomationToolsConsole.R
- src/cpp/tests/automation/testthat/test-automation-console.R
- src/gwt/.gitignore
- version/news/NEWS-2025.05.1-mariposa-orchid.md
Addresses https://github.com/rstudio/rstudio/issues/16031,
The new global warning handler we added was incorrectly handling warnings when `options(warn = 2)` was set. Don't do that.
Test via notes in https://github.com/rstudio/rstudio/issues/16031.
N/A
> ensure options(warn = 2) is handled properly

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCopilotHelper.java
- version/news/NEWS-2025.05.1-mariposa-orchid.md
Addresses #16023 
Fix how we compute the ghost text; namely, use the suggestion text minus any common prefix matching existing text in the document.
The old way was flat-out busted. Who wrote that? Oh right, it was me.
Ron has added some tests around this (currently failing).
Try every possible combination of text throughout space and time. Twice.
NA
> Fix suggestion display when copilot suggestion matches some existing text at the start of the suggestion

- src/cpp/tests/automation/testthat/test-automation-console.R
- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- version/news/NEWS-2025.05.1-mariposa-orchid.md
Addresses https://github.com/rstudio/rstudio/issues/16038.
- Null check for an element which might be `null`.
- Handle the scenario where we're starting a new output group when the cursor isn't located at the end of the line. In this scenario, trim the relevant parts of output.
Test via notes in https://github.com/rstudio/rstudio/issues/16038.
N/A
> fix \r handling with annotation of messages

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/core/client/widget/ModalDialogTracker.java
Addresses https://github.com/rstudio/rstudio/issues/16042.
Addresses https://github.com/rstudio/rstudio/issues/15992.
Use the modal dialog tracker to manually adjust the z-index of any displayed modal dialogs, so that newly-presented ones are always on top.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/15992, and confirm also that https://github.com/rstudio/rstudio/issues/15955 did not regress.
N/A
> use alternate strategy for ensuring stacked modals are visible

- dependencies/tools/.gitignore
- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Addresses https://github.com/rstudio/rstudio/issues/16045.
Try harder when searching for an error span element. (Sometimes the error elements are disjoint.)
Also, instead of trying to explicitly remove parent elements from a common parent, just remove them from their own parent (whatever that might be).
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/16045.
N/A
> try harder when searching for groupError span elt

- NEWS.md
- src/cpp/session/resources/schema/user-state-schema.json
- src/node/desktop/src/main/detect-r.ts
- src/node/desktop/src/main/preferences/electron-desktop-options.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/src/ui/widgets/choose-r.ts
- src/node/desktop/src/ui/widgets/choose-r/preload.ts
Addresses https://github.com/rstudio/rstudio/issues/12545.
- When the user selects "use default 32bit / 64bit version of R", save that in the Electron desktop options.
- On startup, consult those options; if set, then attempt to use the default versions of R.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/12545.
N/A
> ensure "use default" options read current registry value on startup

- src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
- src/gwt/src/org/rstudio/studio/client/rsconnect/RsconnectConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/rsconnect/RsconnectConstants_fr.properties
During GWT builds there is a warning:
``` 
[WARN] Plural form 'one' unknown in com.google.gwt.i18n.client.impl.plurals.DefaultRule: ignoring
```
Fixed by removing the `default` locale as it does not support plurals. We define `en` as the fallback so don't need/want `default`. This is described under "The Default Locale" section of this page: https://www.gwtproject.org/doc/latest/DevGuideI18nLocale.html.
The clue that this was the problem came from https://code.google.com/archive/p/google-web-toolkit/issues/5979.
Also added FR localizations for this string. Sanity tested as follow (other non-French in French UI, and layout issues, are preexisting problems):
None
Screenshots show what you'd want to test, if you want to test it.
NA
> fix gwt build warning "Plural form 'one' unknown..."

- src/cpp/r/R/Tools.R
- src/cpp/session/modules/SessionPackageHooks.R
- src/cpp/session/modules/SessionRUtil.cpp
- src/cpp/tests/testthat/test-download.R
Part of https://github.com/rstudio/rstudio-pro/issues/8155.
- Create our own `download.file` hook, that eventually calls the original `download.file` implementation.
- Use that hook to read login + password information from a user's `.netrc`, and pass those as headers.
N/A
Test via notes in https://github.com/rstudio/rstudio-pro/issues/8155.
N/A
> use download hook and add auth headers

- docs/user/rstudio/ide/guide/tools/copilot.qmd
Docs change: addresses #15676
Added a list of file types supported by Copilot; didn't include everything that Copilot understands, just types that seem likely to be relevent to most users.
NA
The page is: https://docs.posit.co/ide/user/ide/guide/tools/copilot.html
Yes it is.
> Update documentation on file types indexed by Copilot

- src/cpp/core/system/LinuxResources.cpp
Addresses: https://github.com/rstudio/rstudio-pro/issues/8319
> Close the /proc dir when getting child process memory

- NEWS.md
- src/cpp/session/modules/SessionCopilot.cpp
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/ProjectCopilotPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CopilotPreferencesPane.java
Addresses #16128, #16129
For #16128, mitigate by prompting to restart when Copilot was started (or restarted) while the preferences dialog was displayed AND a project is open AND project-indexing is enabled. This is simpler than handling re-indexing during the current session.
For #16129, send `textDocument/didChange` instead of `textDocument/didOpen` for all but the initial opening of the document. For now sending the full document text with didChange (as we were always doing with didOpen) instead of the incremental approach (that's covered in separate issue, not yet implemented, #15901).
None, but be a good idea. I'll look at writing some BRAT tests in this area, separately.
Test per the issue descriptions.
None
> Prevent sending didOpen more than once, and suggest a restart if project indexing enabled and Copilot was started

- src/cpp/session/modules/SessionPackages.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackageInfo.java
Addresses https://github.com/rstudio/rstudio/issues/16149.
A recent PR had renamed some of the fields from the RPC used to list installed packages. Unfortunately, I overlooked that this RPC is also used by the Insert Citation API, to figure out what packages (and what citations) are available. Revert those name changes.
> restore old names for list packages API

- NEWS.md
- src/cpp/session/modules/SessionUpdates.cpp
- src/node/desktop/src/main/gwt-callback.ts
Addresses #15444
Electron message box was ignoring the specified "cancel" and "default" button values we were passing, causing it to associate ESC with the wrong button.
The fix is to actually tell Electron about these.
None
> [!NOTE]
> To aid in debugging / testing, you can now have RStudio impersonate a different version when performing the update check via the environment variable `RSTUDIO_UPDATE_VERSION`, e.g. `RSTUDIO_UPDATE_VERSION=2022.07.2+576`.
> `~/.Renviron` is a handy place to set this.
Electron may display the buttons in a different order than before as a result of this change, varying by platform conventions.
NA
> Properly handle hitting ESC key in "Update Available" dialog box

- src/cpp/session/modules/SessionDependencies.cpp
Fixes #16169.
Debugging `rsession` revealed the issue:
```
Thread 1 "rsession" received signal SIGSEGV, Segmentation fault.
0x0000aaaae8eaa420 in rstudio::core::Error::operator= (this=0xffffcf743650) at /workspace/rstudio-pro/src/cpp/shared_core/include/shared_core/Error.hpp:178
178 class Error : public virtual ErrorLock
```
Which happened in the following code:
https://github.com/rstudio/rstudio-pro/blob/7ec3029abb4f14a72796757db86a4a37692f0c8d/src/cpp/session/modules/SessionDepende …
> Fix segfault with use-after-free of Error object

- src/cpp/core/include/core/system/Resources.hpp
- src/cpp/core/system/LinuxResources.cpp
- src/cpp/core/system/MacResources.cpp
* Export getProcessSize() so library client processes can get their memory footprint.
* On Linux it's a simple wrapper around the preexisting version that takes a PID as an argument.
* On MacOS it's a wrapper but around the more full-featured getProcessMemoryUsed().
> …
> Export getProcessSize function

- src/cpp/session/modules/environment/SessionEnvironment.cpp
- src/cpp/tests/testthat/test-environment.R
Addresses https://github.com/rstudio/rstudio/issues/16202.
Validate we still have a pairlist-like object while iterating through pairlists when computing an object's size.
Added.
Test via notes in https://github.com/rstudio/rstudio/issues/16202.
N/A
> fix crash when querying object size for ALTREP objects

- git_hooks/secrets/.secrets.baseline
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
- src/node/desktop/src/main/gwt-callback.ts
Addresses https://github.com/rstudio/rstudio/issues/12545.
We added new options indicating if the default version of 32-bit R, or 64-bit R, is in use. These options weren't being respected when showing the current version of R being used in the Global Options UI. Now we are.
N/A
N/A
N/A
> ensure current R version in UI respects defaults

- src/cpp/server_core/include/server_core/DatabaseUtils.hpp
- src/cpp/session/modules/SessionPPM.R
- src/cpp/session/modules/SessionPackages.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/Packages.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackageState.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/PackageManagerSelectRepositoryModalDialog.java
Addresses a unit test failure (large repository URL pushing buttons off screen).
> use smaller button label for repository

- dependencies/common/install-gwt
- dependencies/linux/install-dependencies-yum
- src/cpp/ext/CMakeLists.txt
- Make the GWT installer idempotent.
- Install our RHEL dependencies in one invocation, to speed the whole process up.
- Also add cmake and sqlite-devel so that SOCI builds succeed.
> dependency installer tweaks

- src/gwt/src/org/rstudio/core/client/files/filedialog/OpenFileDialog.java
File Open dialog (web version) is throwing an exception when loading.
Null check
I'll look at adding a BRAT test for this (desktop also has this bug when using web-based file dialogs).
Make sure File Open dialog loads correctly on Server/Workbench.
N/A
> Prevent exception in OpenFileDialog

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionUserPrefValues.R
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_fr.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
- src/node/desktop/src/renderer/preload.ts
Addresses #16226 (also previously closed issue #11595)
- Added a "Zoom with Mouse Wheel" user preference to Global Options / General (off by default), only in Desktop
- Added a numeric preference "Mouse wheel zoom debounce delay" to control the speed of the zoom (this preference is only editable via the command-palette; default is 100ms, a higher number slows the scrolling, lower number will speed it up)
- When enabled, Ctrl (Linux/Windows) / Cmd (macOS) plus mouse-wheel fires existing Zoom In / Zoom Out events
None specifically for mouse-wheel
Test that the feature is off by default, and works as described when enabled. Ultimately the Ctrl/Cmd+Mouse Wheel action is firing the same zoom in / zoom out commands as the keyboard shortcuts.
This is a desktop-only feature.
None (but user …
> Mousewheel zoom feature for RStudio desktop

- NEWS.md
Add a NEWS entry for:
- rstudio/rstudio-pro#7599
- rstudio/rstudio-pro#8186
Also include upgrade instructions for positron conf files that will be backed up during the upgrade process.
> Add news and upgrade entry for rstudio/rstudio-pro#7599 and rstudio/rstudio-pro#8186

- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/PackagesDataGrid.css
Addresses https://github.com/rstudio/rstudio-pro/issues/8658.
Tweak the css selector to make it more specific.
No tests for this currently.
The "R" icon can only be tested with Server, but the others such as toolbar icons can be tested in desktop or server.
NA
> fix issue with icons darkening when hovered

- README.md
Addresses #16263
Removed the broken link from the README. I couldn't find a suitable substitute for this old article.
> remove outdated server documentation reference from README

- dependencies/tools/rstudio-tools.sh
This commit bumps the Go toolchain used in RStudio and downstream Workbench components to address vulnerability scanning issues.
Go 1.24.5 is the latest at time of writing.
Part of https://github.com/rstudio/rstudio-pro/issues/8732.
N/A
N/A
N/A
> Bump the Go compiler version

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
Speculatively addresses https://github.com/rstudio/rstudio/issues/16157.
We have some code that tries to manually resize the chunk output widget after code execution has finished. My hypothesis is that, in some rare cases, the chunk output finished event might be received before we have finished rendering all error text into the chunk output widget, thereby causing us to resize the widget before we know the actual intended size.
As a band-aid, defer sync-ing the height after execution has finished, to give other machinery a chance to finish updating the chunk output.
N/A
N/A
N/A
> defer setting height on chunk output

- src/gwt/src/org/rstudio/core/client/prefs/SectionChooser.java
Bring over a change made only on the pro-side to open-source side, getting this file back in sync. The change was made 2 years ago thus has shipped many times in Workbench and Desktop Pro without ending the universe.
> sync minor SectionChooser.java change from pro back to open-source

- NEWS.md
Adds entries to the best of my ability, and with appropriate restraint, for the new homepage work and relevant fixes to launcher UI behavior.
> Add news entries for new homepage and several related fixes

- src/node/desktop/package-lock.json
- src/node/desktop/package.json
- version/news/NEWS-2025.08.0-cucumberleaf-sunflower
Upgrade from electron 37.2.4 to 37.2.5:
https://releases.electronjs.org/release/compare/v37.2.4/v37.2.5
> upgrade to Electron 37.2.5

- src/cpp/r/R/Tools.R
So I think this is at least part of the fix for the repo display issue.
In furtherance of https://github.com/rstudio/rstudio-pro/issues/8802
Idea here is to adjust the regex to leave a `/` when it pulls out the `/__linux__/jammy/` section of the url. I think this requires re-installation of the package to fixup the `DESCRIPTION` file.
None.
None.
None.
> Binary regex fix.

- git_hooks/secrets/.secrets.baseline
- jenkins/utils.groovy
Tries to address some of the authentication errors we are seeing on long-running jenkins jobs by acquiring the GH token every time we push a check. I don't think the retry logic was correctly updating the global GITHUB_LOGIN environment variable before. This approach is more straightforward.
> Fix GH token acquisition for GH PR checks #8844

- src/cpp/core/include/core/Thread.hpp
Intent
Addresses: https://github.com/rstudio/rstudio-pro/issues/8922
Approach
The condition variable ensures the mutex is locked, but when it is separated out into its own method, the mutex unlocks letting someone else grab the connection.
> fix misused condition variable

- src/cpp/core/include/core/Thread.hpp
Changes to threadsafequeue had caused a regression with the file pane refreshing on file changes
Found that we did not return properly from timed out dequeue, so return on timeout added
NA
NA
NA
> 8933 bugfix regression with file pane refreshing on file changes

- NEWS.md
- src/cpp/session/SessionClientEventQueue.cpp
- src/cpp/session/SessionConsoleOutput.cpp
- src/cpp/tests/automation/testthat/test-automation-console.R
- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Addresses https://github.com/rstudio/rstudio/issues/16337.
Previously, we tried to annotate error output in all kinds of output, even if an error hadn't already been signaled by R. This PR pulls that behavior back, so that we only highlight error output when an uncaught R error has occurred.
Test via notes in https://github.com/rstudio/rstudio/issues/16337.
N/A
> only annotate error output when we know an error has occurred

- NEWS.md
- src/cpp/session/modules/SessionSource.cpp
Addresses https://github.com/rstudio/rstudio/issues/15963.
Allow the dirty flag on a document to be 'sticky' across background saves.
Note that a background save might be triggered not by changes in the in-editor buffer, but instead by changes in document properties -- for example, the chunk outputs associated with an R Markdown document. In this scenario, the save might be performed with no document changes, but this does not imply that the document on-disk will now be in-sync with our source database.
With this change, once a document is 'dirty', it will remain dirty until the user explicitly saves the document, which would tell RStudio to write the document's contents out to disk. This will cause us to incorrectly consider a document as 'dirty' after e.g. inserting a character, waiting …
> let dirty flag be 'sticky' across background saves

- dependencies/tools/rstudio-tools.sh
- package/linux/make-package
- package/linux/scripts/upload-debug-symbols
- scripts/upload-debug-symbols
Addresses https://github.com/rstudio/rstudio-pro/issues/8889.
- Create a new script that automatically finds debug symbol files (suffixed with `.debug`) in a build directory, then uploads those to S3.
- Use the various parameter names we get from Jenkins when computing the destination path for uploads.
N/A
N/A
N/A
> upload debug symbols to S3

- dependencies/common/install-aws-cli
- dependencies/common/install-common
- dependencies/tools/rstudio-tools.sh
- package/linux/scripts/upload-debug-symbols
- Install the AWS CLI tools in our Docker images, so we can use them from shell scripts for interacting with AWS where required. (It's a lot easier to do this in our shell scripts than in Jenkins.)
- Instead of uploading symbols all separately, collect them into an archive. We can save a lot of space given the large amount of duplication in shared code between different executables.
> install aws cli; upload compressed archives of debug info

- dependencies/linux/install-dependencies-focal
- dependencies/linux/install-dependencies-jammy
- dependencies/linux/install-dependencies-noble
The debian dependency scripts were broken by https://github.com/rstudio/rstudio/pull/16336.
Fix
> fix dependency scripts

- src/node/desktop/src/main/main.ts
Part of https://github.com/rstudio/rstudio-pro/issues/5914.
Use newer flag, been in Chromium / Electron for several years.
This flag is used when "Use GPU exclusion list" is unchecked:
NA
> use newer flag variant

- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionUserPrefValues.R
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_fr.properties
Noticed we still have a setting related to crash reporting. It is unused.
Shows up in the command palette:
Remove it
NA
Confirm the "Submit crash reports for Posit" setting no longer shows up in the command palette.
NA
> remove the unused setting for automatically submitting crash report

- src/cpp/r/R/Tools.R
- src/cpp/tests/testthat/test-download.R
There are inconsistent build failures that look like this:
```
2025-09-09 07:26:54  Error (ine = 46:col = 4;test-download.R:46:4ile:///tmp/jenkins-ad98536b/workspace/IDE/Pro-Builds/Platforms/linux-pipeline/rel-cucumberleaf-sunflower/src/cpp/tests/testthat/test-download.Rtest-download.R:46:4>): download.file hooks work as expected
2025-09-09 07:26:54  Error in `destfile %||% {
2025-09-09 07:26:54      .rs.mapChr(seq_along(url), function(i) tempfile())
2025-09-09 07:26:54  }`: could not find function "%||%"
2025-09-09 07:26:54  Backtrace:
2025-09-09 07:26:54      ▆
2025-09-09 07:26:54   1. └─expect_download(url) at ine = 46:col = 4;39m">file:///tmp/jenkins-ad98536b/workspace/IDE/Pro-Builds/Platforms/linux-pipeline/rel-cucumberleaf-sunflower/src/cpp/tests/testthat/test-download.Rtest-downlo …
```
> use portable R idiom in test-download.R

- jenkins/Jenkinsfile.linux
- package/linux/make-package
- package/linux/scripts/upload-debug-symbols
- package/linux/scripts/vars.sh
We're getting some build failures based on AWS token expiration:
https://build.posit.it/job/IDE/job/Pro-Builds/job/Platforms/job/linux-pipeline/job/main/2568/pipeline-overview/?start-byte=11062074&selected-node=378#log-378-412
This seems flaky because it depends on how long the build took.
Ideally we shouldn't be using `withAWS` around a build process because tokens are hard-limited to a single hour. But since we're using S3 for sccache, we sort of have to. However, it doesn't seem to be a problem for the token to expire during the build, so that's not a problem in and of itself.
The debug symbols need to be uploaded after the build is completed, so we should refresh the token when we do that.
There's not really a good way to test this other than running it in Jenkins.
> Upload debug symbols separately to refresh the AWS token

- NEWS.md
- src/cpp/r/R/Tools.R
- src/cpp/tests/testthat/test-download.R
Addresses https://github.com/rstudio/rstudio/issues/16446.
Fixed an issue wherein we could set an empty Authorization header, which can cause downloads to fail in certain contexts.
Added a test.
Test via notes in https://github.com/rstudio/rstudio/issues/16446.
N/A
> avoid setting empty Authorization header in requests

- NEWS.md
- src/node/desktop/src/main/gwt-callback.ts
Addresses #16444
Work around electron issue on macOS by setting the extension directly when saving a new file.
NA - we don't have ability to automate file dialogs.
Check the issue's scenario, and also test other cases where we prompt for a filename, including "save as".
NA
> Fix C++ file extension truncation on macOS in save dialog

- src/node/desktop/src/main/gwt-callback.ts
- version/news/NEWS-2025.09.1-cucumberleaf-sunflower.md
Backport fix for #16444 from `main`.
> backport fix for issue #16444 (truncated .cpp extension on macOS)

- src/cpp/core/include/core/http/SocketAcceptorService.hpp
Where if errno is set to 34 this exception is thrown: "config out of range"
Addresses: https://github.com/rstudio/rstudio-pro/issues/9107 
(boost issue: https://github.com/chriskohlhoff/asio/issues/1588)
This might come up randomly for our customers in 2025.05 and 2025.09 - Boost 1.87... if something the process does before initializing the http server gets a ERANGE error, that process throws this unexpected exception.
I tested this code and if you set errno = 34 -  it gets that error.  So setting it to 0 should avoid the problem.
> Works around boost bug in 1.87

- src/cpp/tests/automation/testthat/test-automation-quarto.R
- src/gwt/acesupport/acemode/utils.js
- version/news/NEWS-2025.09.1-cucumberleaf-sunflower.md
Addresses https://github.com/rstudio/rstudio/issues/16463.
NEWS will be added to the patch release after backporting.
The saved state used in Quarto highlights might need to be re-used as a rule is applied multiple times against a single line. Avoid deleting the context information in this scenario.
Included.
Test via notes in https://github.com/rstudio/rstudio/issues/16463.
N/A
> fix quarto syntax highlight issues

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCopilotHelper.java
Addresses #16471
Before showing a Copilot message in the editor status bar, check if copilot is enabled and if not, hide all copilot messages.
None
I was not able to repro this issue, but this should handle whatever scenario caused it to happen.
None
> Don't show copilot status messages when disabled

- NEWS.md
- src/cpp/session/modules/SessionCopilot.cpp
Addresses #16423
We don't notify Copilot about following files when opened in RStudio, but we were telling it when they closed and it gave an error about closing a file it didn't know about.
- binary files
- hidden files (e.g. `.Renviron`)
- `Renviron.site`
- files in hidden folders (`.foo/...`)
- `.Rproj` files
If a closing file isn’t indexable, don’t report it as closed to Copilot.
None
Test per issue.
None
> Don't tell copilot when closing a file we didn't tell it about in the first place

- NEWS.md
- src/gwt/src/org/rstudio/core/client/theme/WindowFrame.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
Addresses https://github.com/rstudio/rstudio/issues/16485
Only show min/max widgets in the regular source pane, not in source columns.
None
Verify widgets don't show in source columns but continue to show in the main source pane.
NA
> don't show min/max buttons for full-height source columns

- version/news/NEWS-2025.09.1-cucumberleaf-sunflower.md
Simply adds a news item:
> - Positron Pro sessions are now supported on RHEL 8
> Add a news item for Positron Pro support on RHEL 8

- docs/news/index.qmd
- version/news/NEWS-2025.09.1-cucumberleaf-sunflower.md
Update release notes for IDE / Workbench 2025.09.1+401.pro2 release.
This change has been generated by the release script. Content is generated based on `version/news/NEWS-2025.09.1-cucumberleaf-sunflower.md`. If this file was not in sync with Pro or did not include items from other sources (i.e. the vscode extension), then some items may be missing.  Please verify content/formatting is correct and make changes if necessary.
> Update release notes for 2025.09.1+401.pro2

- NEWS.md
- src/cpp/session/modules/NotebookData.R
- src/cpp/tests/automation/testthat/test-automation-rmarkdown.R
Addresses https://github.com/rstudio/rstudio/issues/16483.
Our paged table print tooling relies on us injecting S3 method overrides for various classes. This PR gives us a mechanism for delegating back to the original method, in cases where `print()` appears to have been explicitly invoked by the user, as opposed to being synthesized by R for an auto-printed object.
Included with PR.
Test via notes in https://github.com/rstudio/rstudio/issues/16483.
N/A
> only use paged tables for auto-printed data

- src/node/desktop/.ncurc.json
- src/node/desktop/package-lock.json
- src/node/desktop/package.json
Electron unit tests were failing to run on Linux, giving error:
```
ERROR: Unexpected module status 0. Cannot require() ES Module /tmp/jenkins-e148c0d3/workspace/IDE/OS-Builds/Platforms/linux-pipeline/rel-cucumberleaf-sunflower/src/node/desktop/node_modules/chai/chai.js because it is not yet fully loaded. This may be caused by a race condition if the module is simultaneously dynamically import()-ed via Promise.all(). Try await-ing the import() sequentially in a loop instead. (from /tmp/jenkins-e148c0d3/workspace/IDE/OS-Builds/Platforms/linux-pipeline/rel-cucumberleaf-sunflower/src/node/desktop/test/unit/core/array-utils.test.ts)
```
Bump version of `mocha` package to match what's in `main`. This is only used for running unit tests so low risk.
The `.ncurc.json` file is copied over from …
> fix issue with electron unit tests failing to run on Linux after upgrading Electron
