- src/cpp/session/modules/SessionDataViewer.R
This change addresses two issues reported on the RStudio support forum:
- When an object is named literally `x`, the viewer can behave strangely (or not at all). This is because when searching for the object to view, it starts in the wrong environment, and picks up the variable `x` from the function hooking `View`. We now locate `View` in the callstack and begin searching in the environment from which it was called.
- When a data frame contains only a single column, filtering that column can result in errors. This happens because the filter operation can replace the frame with its column, turning it from a frame into a flat list. We now re-cast to a dataframe and restore column names after filtering (only if we've lost them, of course).
> Address issues viewing objects named "x" and single-column frames

- src/gwt/acesupport/acemode/markdown_folding.js
This fixes the errors seen in Markdown modes.
> fix a bug in the 'Utils' require for markdown folding

- src/cpp/r/R/Api.R
@jjallaire, I think this is intended to be scalar? (I was getting jsonrpc errors after merging master into the lint branch)
> ensure 'messageHTML' is scalar

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/ambiance.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/chaos.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/chrome.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/clouds.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/clouds_midnight.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/cobalt.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/crimson_editor.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/dawn.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/dreamweaver.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/eclipse.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/idle_fingers.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/katzenmilch.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/kr_theme.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/merbivore.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/merbivore_soft.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/mono_industrial.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/monokai.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/pastel_on_dark.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/solarized_dark.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/solarized_light.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/textmate.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/tomorrow.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/tomorrow_night.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/tomorrow_night_blue.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/tomorrow_night_bright.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/tomorrow_night_eighties.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/twilight.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/vibrant_ink.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/xcode.css
- src/gwt/tools/compile-themes.R
This PR softens the background color on matching brace highlights.
> better background colors for matching brackets

- src/cpp/desktop/DesktopRVersion.cpp
Hi,
I use R-studio with a portable installation of R on our university computers. Currently to change the detected version I have to manually change the R version in configuration and restart R-studio which gets mildly tedious.
This patch would allow using a one-time batch file like the one pasted below to override the old R installation (without requiring admin rights): 
REG ADD HKEY_CURRENT_USER\Software\R-core\R /V "Current Version" /D 3.1.2
REG ADD HKEY_CURRENT_USER\Software\R-core\R /V InstallPath /D E:\PortableApps\R-Portable\App\R-Portable
REG ADD HKEY_CURRENT_USER\Software\R-core\R\3.1.2 /V InstallPath /D E:\PortableApps\R-Portable\App\R-Portable
> Added checks for installed R version under HKEY_CURRENT_USER.

- src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/DiagnosticsBackgroundPopup.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/DiagnosticsBackgroundPopup.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/Markers.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/Range.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/Renderer.java
NOTE: not quite ready for merge.
This PR will provide a mechanism for us to display a diagnostics popup if the user leaves their cursor idle within a marker for long enough.
> diagnostics background task

- src/gwt/acesupport/snippets/snippets/markdown.js
- src/gwt/src/org/rstudio/core/client/StringUtil.java
- src/gwt/src/org/rstudio/studio/client/workbench/snippets/SnippetHelper.java
- src/gwt/src/org/rstudio/studio/client/workbench/snippets/ui/EditSnippetsDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/snippets/ui/EditableSnippets.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
This PR will encompass our own custom Markdown snippets. The set of snippets we want to include is still a TODO here.
> Add custom markdown (RMarkdown) snippets

- INSTALL
Just a few typos I found going through INSTALL.
> Fix typos in INSTALL

- NEWS.md
- src/cpp/core/include/core/json/Json.hpp
@kevinushey Could you review and merge as a sanity check?
> fix compilation errors that occur as a result of GCC concept checks

- src/cpp/core/BoostErrors.cpp
- src/cpp/core/Thread.cpp
- src/cpp/core/include/core/Macros.hpp
- src/cpp/core/include/core/Thread.hpp
- src/cpp/core/include/core/json/Json.hpp
- src/cpp/core/json/JsonRpc.cpp
- src/cpp/desktop-mac/GwtCallbacks.mm
- src/cpp/r/RErrorCategory.cpp
- src/cpp/r/session/graphics/RGraphicsErrorCategory.cpp
- src/cpp/server/ServerErrorCategory.cpp
- src/cpp/session/SessionClientEventService.cpp
- src/cpp/session/http/SessionHttpConnectionListenerImpl.hpp
@howarthjw, can you confirm that this branch builds with the updated `libc++` / Boost 1.58? I imagine your motivation is that you want RStudio added to the `fink` project -- is that correct?
@jjallaire, do you think this trimmed down PR would be okay to merge, or would you prefer not? (Eg. if the motivation here was that a version of RStudio might be released built against an untested toolchain, should we prefer to avoid that?)
> Allow successful compilation with libc++ (C++11) / boost 1.58

- src/gwt/acesupport/acemode/rhtml.js
Previously, none of the outdenting behaviour was used in the R mode for `.Rhtml` documents.
Are there any other embedded modes that we should support for `.Rhtml` documents?
> enable outdenting in .Rhtml documents

- src/cpp/session/modules/SessionHelp.cpp
- src/cpp/session/resources/roxygen_help.html
- src/gwt/src/org/rstudio/studio/client/common/filetypes/RFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/RWebContentFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/WebContentFileType.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/Help.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpTab.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Adds an `roxygen` + `.Rd` quick-ref guide to the IDE, and adds it to a `?` button for R source files (when within an R package project).
> add roxygen quickref

- src/cpp/session/SessionSourceDatabase.cpp
- src/cpp/session/SessionSourceDatabaseSupervisor.cpp
- src/cpp/session/SessionSourceDatabaseSupervisor.hpp
PR for review (not yet for merge).
> preserve mru list of source documents on quit

- src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
- src/gwt/src/org/rstudio/core/client/widget/MiniPopupPanel.java
- src/gwt/src/org/rstudio/core/client/widget/ThemedCheckBox.java
- src/gwt/src/org/rstudio/core/client/widget/TriStateCheckBox.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOptionsPopupPanel.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOptionsPopupPanel.java
Not quite ready for merge, but represents an initial bit of work implementing some of the suggestions we had re: the chunk options popup.
> revise chunk popup options

- src/cpp/core/system/Win32OutputCapture.cpp
This change is a third attempt to correct an issue observed for the 2nd and following users on Remote Desktop installations.
It's similar in spirit to the last attempt (https://github.com/rstudio/rstudio/pull/452). The difference is that, instead of attempting to get `QProcess` to connect `stderr`/`stdout`, this change detects the case where `stderr` and/or `stdout` are disconnected and "creates" them (by creating a stream for the standard descriptor and assigning it directly). 
This allows us to tolerate the error case without any changes in behavior in the non-error case (i.e. if `stdout` and `stderr` have real file descriptors, the logic works exactly as before). 
This change has been tested on Windows 2012 R2 (both on desktop and over RDP with another RStudio session active), on …
> Create missing stdout/stderr streams if necessary

- NOTICE
- src/gwt/acesupport/snippets/snippets/stan.js
- src/gwt/src/org/rstudio/studio/client/workbench/snippets/SnippetHelper.java
- src/gwt/src/org/rstudio/studio/client/workbench/snippets/ui/EditSnippetsDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/snippets/ui/EditableSnippets.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceResources.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/ext-language_tools-uncompressed.js
- src/gwt/tools/build-ace
Note that this PR isn't ready for merge yet. Needs two things:
1) Contributor agreement from original author of snippets.stan
2) The snippets aren't currently getting registered correctly.
> snippets for stan mode

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
This PR helps avoid race conditions that could occur in `runPreviousChunks` when multiple chunks were sequentially (but independently) executed.
The solution here is to collect all of the chunk text as a single string of code, and fire that off to the console (after the pre-requisite document preparation has been done).
The console output helps illustrate how the chunk output is sent + executed in the console (we add a comment header to show which chunk text belongs to what chunk)
> run multiple chunks as single code string

- NEWS.md
- src/gwt/src/org/rstudio/core/client/JsArrayUtil.java
- src/gwt/src/org/rstudio/studio/client/application/ui/GlobalToolbar.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneConfig.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
@kevinushey This builds on some of the recent pane layout work. Let me know if the implementation looks okay to you.
> add console on left/right layout commands

- src/gwt/src/org/rstudio/core/client/js/JsArrayEx.java
This PR fixes an issue where JavaScript objects containing arrays would not be properly serialized by GWT -- primarily due to the fact that those arrays inherited from the Array prototype belonging to a separate window.
The fix is to re-generate all objects and arrays, ensuring that the current window is used.
As an example, this fixes an issue where breakpoint arrays serialized from a satellite window would be serialized as objects -- e.g. instead of
```js
{
"0": { ... },
"1": { ... },
...
}
```
we get (as expected)
```js
[
{ ... },
{ ... },
...
]
```
@jjallaire, @jmcphers, can you please review this very carefully? This routine gets called whenever events need to cross window boundaries so it's very important that we get it right.
> fix cross-window passage of JS objects

- src/cpp/desktop-mac/GwtCallbacks.h
- src/cpp/desktop-mac/GwtCallbacks.mm
- src/cpp/desktop-mac/MainFrameController.h
- src/cpp/desktop-mac/MainFrameController.mm
- src/cpp/desktop-mac/WebViewController.h
- src/cpp/desktop-mac/WebViewController.mm
- src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java
- src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
Fixes crash observed with Safari 9 / El Capitan
> OSX: open/switch projects in new RStudio instances

- src/cpp/session/modules/SessionGit.cpp
This PR makes a number of improvements to the detection of msysgit on Windows:
1) Examines both the Git Bash and Git GUI shortcuts for hints to where Git is located;
2) Correctly parses newer variations of msysgit shortcuts that don't use cmd.exe
3) Implements a fallback that automatically detects e.g. C:\Program Files\Git\bin\git.exe
> improve detection of mysysgit on windows

- src/gwt/src/org/rstudio/core/client/dom/DomMetrics.java
- src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
- src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptions.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportScript.java
- src/gwt/tools/editor-settings/codetemplates.xml
This completes a very-basic import from csv files and urls. Feature is now usable for the most basic scenario but not customizable and live previews are now implemented yet. Will keep improving in subsequent PRs.
> Data import

- src/cpp/server/pam/PamMain.cpp
Note: This PR is rooted off the v0.99-1000 branch and will merge into it.
> rserver-pam takes an optional service argument

- src/cpp/session/modules/SessionDataImportV2.R
- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportColumnTypesMenu.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptions.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUi.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsv.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsv.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiJdbc.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiJson.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiMongo.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiOdbc.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiSav.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXml.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsXls.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/model/DataImportPreviewResponse.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/res/DataImportStyles.css
- Add support to import data from Excel using readxl
- Add support to display a subset of column-type changes in data preview
- Enable passing column information to data preview in r-session to support column operation from readxl
> Add support to import data from Excel

- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefs.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java
Bring back profiler work to continue development with `.rs.writeUiPref("show_profiler", TRUE)`
> Bring back profiler entry points under show_profiler feature flag

- src/cpp/session/modules/SessionRCompletions.R
This PR ensures that lazy-loaded datasets also become part of the `::` completion set.
(Leave for post-release merge)
> provide 'lazydata' completions

- src/cpp/session/modules/SessionDataImportV2.R
- src/cpp/session/resources/grid/gridstyles.css
- src/cpp/session/resources/grid/gridviewer.js
- src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportColumnTypesMenu.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportColumnTypesMenu.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportFileChooser.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsv.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsv.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.ui.xml
- Design fixes to data import dialog: Alignment, menus, cursors, prevent menu text selection, etc.
- Disable CSV elements that are not used to generate import code.
- Fix case where table contains no data.
- Fix case where operations are performed over columns with no names.
- Coping code now supports multiple lines.
- Prevent user from performing operation over columns that are not names. Menu displays "Only named columns support column operations."
- Assign focus to location textbox to ease importing data.
> data import usability improvements and corner cases in csv import

- src/cpp/session/include/session/SessionScopes.hpp
This change fixes an issue which occurs when users open projects that belong to other users, but which are not actually shared -- that is, they don't use the project sharing features, but can still be opened due to ordinary filesystem permissions.
The problem has to do with the project ID mapping table. When we detect that we're opening another user's project, we attempt to clean out any local knowledge of the project ID so that we can insert a shared project ID. If, however, there is no shared project ID (and there won't be in this case since the project has not been shared), a new local ID is generated. Without a stable local ID, the project cannot be opened.
The fix is to avoid stomping on the local ID of a project unless there actually exists a shared ID with which to replace it. …
> Fix 'project not found' issue with other users' unshared projects

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java
minor fix to support full-paths fix in toolbar button
> add support for go-to profile sources using full path

- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
This PR does two things:
1) Allows Ctrl (and Meta, on OS X) + Enter to confirm the current commit, and
2) Allows Cmd (on OS X) for the various scrolling hotkeys.
A nice-to-have for users who don't want to touch the mouse when done writing their commit message.
> allow {Ctrl / Cmd} + Enter to confirm commit

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefs.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java
Remove `show_profiler` and add profiler changes to `NEWS.md`
> enable profiler by default

- src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Two profiler related fixes:
1. Trigger `profvis` install from profile-this-code command
2.  Add support to upgrade embedded packages based on their version
> Add support to upgrade embedded packages with version

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Prevent profvis call to be executed within a notebook chunk, instead, execute always in the console.
> execute profile-this-code command in console instead of chunk

- src/cpp/session/modules/NotebookHtmlWidgets.R
- src/cpp/session/modules/rmarkdown/NotebookOutput.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkOutputUi.java
--force-yes is necessary for installing libssl-dev
> add parameter --force-yes for installing ubuntu dependencies

- INSTALL
- src/cpp/server/CMakeLists.txt
- src/cpp/server/extras/admin/rstudio-server.mac.in
- src/cpp/server/extras/launchd/com.rstudio.launchd.rserver.plist.in
The admin script is missing for mac, this PR adds support for Mac OX.
> add Mac OSX launchd plist and admin script

- src/cpp/server/extras/admin/rstudio-server.mac.in
> mac server admin script: fix path to rserver

- src/cpp/server/extras/admin/rstudio-server.mac.in
sorry for not testing the previous PRs well enough.
> mac server admin script: show correct version number

- src/cpp/session/modules/SessionDataImportV2.R
- src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportFileChooser.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsCsv.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsSav.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsv.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsv.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiSav.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiSav.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsXls.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesPane.java
Data import improvements:
- Moved "Data Import" menu from "Tools" to "File".
- Added contextual menu for data import files to "Import Data" from the files pane. Opening a file will load the file in the import dialog and preview the data.
- Added "Open Data Viewer" checkbox to CSV, XLS and Statistical files.
- Changed variable name generation to maintain source file casing.
- Made changes in code viewer persistent.
- Fix to "Error trying to import csv from url on Windows".
> Data import improvements from feedback

- src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesPane.java
use ... in import dataset popup
> use ... in import dataset popup

- src/cpp/session/modules/SessionFind.cpp
This PR fixes an issue where attempting to search through files with long lines (e.g. base64 encoded content) would cause a quadratic re-computation of the number of UTF-8 characters in the line as matches were discovered in the line.
Rather than computing the number of UTF-8 characters from start to end on each match, we cache and update the size as we go along.
> cache decoded line's size rather than recomputing at each stage

- src/gwt/acesupport/acemode/markdown_highlight_rules.js
- src/gwt/acesupport/acemode/rmarkdown_highlight_rules.js
- src/gwt/acesupport/acemode/sql.js
- src/gwt/acesupport/acemode/sql_highlight_rules.js
- src/gwt/src/org/rstudio/studio/client/common/reditor/EditorLanguage.java
Support sql highlighting in chunks for knitsql integration:
> add support for sql chunk highlights

- src/cpp/session/modules/SessionDataImportV2.R
fix to "data import fails when path contains non-ASCII characters".
> fix encoding for dataimport operations

- src/cpp/server/ServerMain.cpp
- src/cpp/session/CMakeLists.txt
- src/cpp/session/modules/NotebookData.R
- src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.cpp
- src/cpp/session/modules/rmarkdown/NotebookData.cpp
- src/cpp/session/modules/rmarkdown/NotebookData.hpp
- src/cpp/session/modules/rmarkdown/NotebookExec.cpp
- src/cpp/session/modules/rmarkdown/NotebookOutput.cpp
- src/cpp/session/modules/rmarkdown/NotebookOutput.hpp
- src/cpp/session/modules/rmarkdown/NotebookQueue.cpp
- src/cpp/session/modules/rmarkdown/SessionRmdNotebook.cpp
- src/cpp/session/modules/rmarkdown/SessionRmdNotebook.hpp
- src/cpp/session/resources/pagedtable/pagedtable.css
- src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RmdChunkOutputUnit.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetChunks.java
Opening this PR to discuss styling and take additional feedback. @jjallaire @jmcphers.
Notice that the style does not 100% match rmarkdown's since that one was derived from the existing kable which is based on bootstrap. Rather than bringing bootstrap to the ide, I think it makes more sense to choose whichever styling works best for the ide, let me know.
> Use paged tables for notebook data chunks

- src/cpp/session/modules/NotebookData.R
- src/cpp/session/modules/SessionConnections.R
- src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.cpp
- src/cpp/session/resources/pagedtable/pagedtable.css
1. Fixing `max-print` for SQL chunks
2. Ensure SQL chunk directory exists before saving chunk data
3. Style improvements to data chunks
@jmcphers: Quick review appreciated, thanks!
> Improvements to sql data chunks

- src/cpp/session/modules/rmarkdown/NotebookOutput.cpp
Improvement for 6064 and might fix 6015
> avoid caching in html chunk requests to avoid rendering blank pagges

- src/cpp/session/modules/SessionRmdNotebook.R
This PR ensures that we respect the `tidy` chunk option in R notebooks. Note that the `formatR` package is installed as a dependency of `knitr`, so I don't think we need to do explicit checks around its existence here.
> respect 'tidy' knitr option

- src/cpp/session/modules/NotebookHtmlWidgets.R
This PR attempts to improve the sizing of HTML widgets in generated R notebooks, to ensure that the generated widgets more closely match what would be generated in a regular render of an html notebook.
This change feels pretty risky so I don't think we want it for v1.0.
> better respect knitr options when sizing htmlwidgets

- src/cpp/session/modules/SessionRMarkdown.R
Second part of https://github.com/rstudio/rmarkdown/pull/827.
> mark injected 'params' object with class

- src/cpp/session/modules/SessionDataImportV2.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsv.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsvLocale.java
Adding help link and some CR feedback:
> add help link for csv locales dialog and feedback

- src/cpp/session/resources/pagedtable/pagedtable.css
- src/cpp/session/resources/pagedtable/pagedtable.js
Minor fix here, pushing to v1.1, also `rmarkdown` change: https://github.com/rstudio/rmarkdown/pull/845
> fix long pagedtable column name ellipsis

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
This PR resolves an issue where attempting to execute the 'Restart and Run All Chunks' command could occasionally fail with the dialog:
(To reproduce locally, try executing 'Restart R and Run All Chunks' multiple times -- you'll likely see the error come up after a few attempts.)
IIUC, the error occurs because we attempt to execute the command too eagerly -- this PR resolves that by waiting until 'deferred init' has finished instead.
Any thoughts about whether this is a candidate for v1.0?
> invoke restart command after deferred init

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputFrame.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
A null-check and nit cr comment for https://github.com/rstudio/rstudio/pull/856
/cc @kevinushey
> null check for notebook html chunk themes fix

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/DefaultChunkOptionsPopupPanel.java
This PR resolves an issue where the chunk header parser (and hence the dialog for editing that chunk) would fail for chunk headers of the form:
```{r message=TRUE}
In such a case, we incorrectly parse the first option as the label, as we had expected to see a `,` separating the engine + (optional) label and the chunk option list.
> better handle chunk headers with no label + no delimiting comma

- src/cpp/core/r_util/RToolsInfo.cpp
> Use Rtools 3.3 for R 3.2 and Rtools 3.4 for R >= 3.3

- src/cpp/server/CMakeLists.txt
- src/cpp/server/extras/pam/mac/rstudio
As title.
PS: I have signed the contributor agreement.
> perpare pam profile for mac

- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTab.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java
Implement command to kill the current terminal. Helpful when the terminal is misbehaving.
> implement close-current-terminal command

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTab.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java
Commands for switching active terminal.
> add commands for navigating between terminal tabs

- src/cpp/r/R/Api.R
- src/cpp/session/SessionModuleContext.cpp
See https://github.com/rstudio/rstudioapi/issues/32
> rstudioapi functions for simple persistent key/value store

- src/cpp/session/modules/SessionCodeTools.R
This PR ensures that `devtools` shims are used when attempting to view function help. This should ensure that the development version of documentation is used when working on an R package with `devtools::load_all()` active.
The extra `capture.output()` and `suppressMessages()` bits are to ensure that `devtools` isn't chatty at the console about what's going on.
> use devtools help shim when available

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Verified these are unique in their contexts on Windows desktop IDE.
> Add shortcuts to terminal menu items for alt-key navigation

- src/cpp/core/include/core/system/System.hpp
- src/cpp/core/system/Win32System.cpp
Noticed a build break on my Windows dev box. This does the bare minimum to get it building; I haven't actually exercised the impacted code on Windows.
> Fix Windows build

- src/gwt/acesupport/acemode/r_highlight_rules.js
This PR adds highlighting for the Markdown constructs supported in the new release of Roxygen (6.0.0).
> implement highlighting for markdown in roxygen

- src/cpp/session/modules/data/DataViewer.cpp
A couple of customers have asked about the size of their data viewer cache folders. These cache entries get created when data viewer tabs are opened, and destroyed when those tabs are closed.
However, since closing a tab interactively is the *only* way the cache entries ever get cleaned up, there are pathological scenarios in which they could become orphaned or persist indefinitely.
This change seeks to address the issue in two ways:
1) Use a session-specific folder to store the viewer cache. This does imply that the 1.0 - 1.1 upgrade will invalidate your old viewer cache, but this is okay since we've already taken a change to 1.1 which uses a wholly different source database folder, so no tabs referring to the old cache will open.
2) After RStudio starts up, take a look at all of the …
> Clean up orphaned data viewer cache entries

- src/cpp/session/modules/rmarkdown/NotebookPlotReplay.cpp
While refreshing multiple satellite chunks, as in:
Not all chunks were being resized, in general, satellite chunks:
1. First, they get refreshed with the output from the notebook, which usually does not match the right resolution.
2. Each satellite chunk requests a render of the plot with the right resolution.
The problem was not in (1) but rather than in (2), since multiple chunks request a plot render and the plot renderer was static, only one was successfully rendering.
> Use a plot reaply object for each unique satellite chunk

- src/cpp/session/modules/SessionDataImportV2.R
Spotted by @kevinushey: https://twitter.com/polesasunder/status/832356635246944257
> Provide relative paths while importing data

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/Help.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpTab.java
This PR updates the Help menu with new cheat sheets:
- Data Import with readr
- Data Wrangling -> Data Transformation with dplyr
- Interfacing Spark with sparklyr
The cheat sheets are also re-arranged a bit.
> add new cheat sheets

- src/gwt/test/org/rstudio/core/client/StringUtilTests.java
- src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
Wrote a few unit tests for some StringUtil members on the Java side; primarily to get setup and acquainted with JUnit.
> Unit tests

- src/cpp/session/modules/SessionGit.cpp
This PR fixes an issue where paths containing multibyte characters were not handled correctly when received from Git on Windows.
By default, Git for Windows uses a so-called 'quoted octal encoding' for paths not representable in the ASCII character set, as described in https://github.com/msysgit/msysgit/wiki/Git-for-Windows-Unicode-Support#Disable_quoted_file_names. Since we never discover / re-encode those names, we use them incorrectly.
The fix here involves disabling `core.quotepath`, and relying on Git to return UTF-8 encoded paths (note that Git does indeed print paths using UTF-8 encoding here, even on Windows).
> avoid git's octal encoding for paths with non-ASCII chars

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/studio/client/common/debugging/ui/ConsoleError.ui.xml
Couple 2x icon visual fixes for environment pane and debugging/traceback.
> Couple 2x icon visual fixes

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocsMenu.java
This PR disambiguates names in the tab overflow menu.
The de-duplication logic is naive, but since we never plan to have a huge number of tabs open it should still suffice.
> disambiguate names in tab overflow panel

- NOTICE
- src/gwt/src/com/sksamuel/gwt/GwtWebsockets.gwt.xml
- src/gwt/src/com/sksamuel/gwt/LICENSE.txt
- src/gwt/src/com/sksamuel/gwt/README.md
- src/gwt/src/com/sksamuel/gwt/websockets/Base64Utils.java
- src/gwt/src/com/sksamuel/gwt/websockets/BinaryWebsocketListener.java
- src/gwt/src/com/sksamuel/gwt/websockets/CloseEvent.java
- src/gwt/src/com/sksamuel/gwt/websockets/Websocket.java
- src/gwt/src/com/sksamuel/gwt/websockets/WebsocketListener.java
- src/gwt/src/com/sksamuel/gwt/websockets/WebsocketListenerExt.java
- src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
I had been writing something almost identical to this; this one has been meeting my needs so adding it in for use by the terminal websockets work.
> Client side library for websockets

- src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
Case-typo in reference to GwtWebsockets.xml.
> build fix, case-sensitivity typo in gwt inherits reference

- Jenkinsfile
a groovy script approval is required which is slightly broken, causing the builds to randomly fail.
> remove use of Groovy minus.

- src/cpp/r/session/graphics/RGraphicsDevDesc.cpp
@kevinushey I'm hitting this build error, looks to me like `pDev` needs a cast.
> Cast pDev for DevDescVersion12

- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionConnections.R
- src/cpp/session/modules/connections/ConnectionsIndexer.cpp
> Add support for icons in connections dialog and bug fixes

- src/gwt/src/org/rstudio/core/client/theme/RStudioDataGridStyle.css
- src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
- src/gwt/src/org/rstudio/studio/client/application/ui/impl/header/HeaderPanel.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilePathToolbar.java
A few more tweaks to flat theme and fixes for desktop mode.
> Improvements to flat theme under desktop mode

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
Couple improvements to tabs from feedback:
1. Symmetric tab borders and
2. make it easy to find the selected tab by changin…g colors
> Couple improvements to flat theme tabs

- src/gwt/src/org/rstudio/core/client/AnsiCode.java
- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalLocalEcho.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
- src/gwt/test/org/rstudio/core/client/AnsiCodeTests.java
- src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
- src/gwt/test/org/rstudio/studio/client/VirtualConsoleTests.java
AnsiCode.java is not terminal-specific; moved it to same location as VirtualConsole.
> move AnsiCode.java to a more general location

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/core/client/widget/ThemedButton.css
> Make buttons flat for flat theme

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/core/client/widget/SmallButton.css
- src/gwt/src/org/rstudio/core/client/widget/ThemedButton.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarWidget.ui.xml
A few improvements to buttons and dialogs from Paul: Bolded default action button, square bottom corners in dialogs, flat theme for small buttons, darker button borders, etc.
> Flat theme button improvements

- src/cpp/r/R/Api.R
Called by https://github.com/rstudio/rstudioapi; PR on that coming shortly.
> add function for checking if console supports color or not

- Jenkinsfile
it is now managed in a global [jenkins shared library](https://github.com/rstudio/jenkins-pipeline-libraries)
> remove pull_build_push code.

- Jenkinsfile
> remove ref to old pull_build_push method

- src/gwt/src/org/rstudio/core/client/theme/RStudioCellTableStyle.css
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectGrid.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectList.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectList.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutput.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/PackagesDataGridCommon.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java
> Implement flat theme on remaining panes

- Jenkinsfile
@jmcphers this *should* fix the broken builds from the last couple of nights.
> specify dockerfile, continue using default context

- src/cpp/session/resources/grid/gridstyles.css
- src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/core/client/widget/RStudioFrame.java
- src/gwt/src/org/rstudio/core/client/widget/Toolbar.java
- src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
- src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteWindow.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionExplorer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionsPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilePathToolbar.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesListDataGridStyle.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceSatelliteWindow.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTargetWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/material.css
> Flat themes for data viewer and other improvements

- Jenkinsfile
@jmcphers sorry (yet again) for the bug. I knew I should have tested that last fix.
this one has actually been tested in jenkins though, so the build fails I've been causing will actually be resolved :) Thanks!
> use proper container ref

- src/cpp/r/R/Api.R
- src/cpp/session/SessionConsoleProcess.cpp
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/model/ConsoleServerOperations.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java
I had a version of this in a previous iteration but convinced myself it wasn't needed. Then I tried to write an RStudio add-in to exercise the terminal APIs and quickly changed my mind!
> getVisibleTerminal API

- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.ui.xml
@jennybc the `NA`s as textbox change you suggested, double checking before the merge.
> Use textbox for NAs while importing data from Excel

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesListDataGridStyle.css
> Apply dark theme to latched button and dirty tabs

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.java
> Apply dark theme to scrollbars

- src/gwt/src/org/rstudio/core/client/layout/AnimationHelper.java
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/history/view/Shelf.css
Couple minor fixes under themes spotted by Kevin.
> Fixes minimized tab panel state and history search under themes

- src/cpp/session/modules/SessionCodeTools.R
I also simplified excludeBaseClasses functionality by relying on `mode`.
> Make getDollarNamesMethod find super classes

- src/cpp/session/modules/rmarkdown/NotebookHtmlWidgets.cpp
HTML widgets within notebooks no longer render.
This was a regression caused by the upgrade to `boost 1.63.0`. The problem is that their implementation of `recursive_directory_iterator` now assumes that the directory where one iterates does not change. I looked throught the server codebase and was only able to find that HTML widgets is the only moving/delete files between folders, which breaks the assumption of this function.
Fix is to, instead of moving the files, copy them first followed and then we delete the source directory.
> Boost now assumes files won't change during recursive_directory_iterator

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/ambiance.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/chaos.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/chrome.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/clouds.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/clouds_midnight.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/cobalt.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/crimson_editor.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/dawn.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/dreamweaver.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/eclipse.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/idle_fingers.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/katzenmilch.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/kr_theme.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/merbivore.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/merbivore_soft.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/mono_industrial.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/monokai.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/pastel_on_dark.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/solarized_dark.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/solarized_light.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/textmate.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/tomorrow.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/tomorrow_night.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/tomorrow_night_blue.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/tomorrow_night_bright.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/tomorrow_night_eighties.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/twilight.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/vibrant_ink.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/xcode.css
- src/gwt/tools/compile-themes.R
> Allow line margin to be visible in code chunks

- src/cpp/session/modules/connections/Connection.cpp
> Use default icon for drivers icon group

- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Regression I caused where regular (non-error) output was going into a separate span before any error output. See example below.
Fixed by tracking all elements created during a single error output call (i.e. if ansi codes are causing multiple spans as part of a single error), instead of only one, for the purpose of replacing normal error with extended error widget.
My previous approach was wrapping all errors in a single parent span, but that was messing up the VirtualConsole's expectations. As part of this, I reverted back to providing a "forceNewRange" flag to VirtualConsole.submit so each distinct error submitted to VirtualConsole doesn't get blended with a previously output error, which would also mess up the extended error replacement.
test5 <- function () {
message(1)
message(2) …
> Fix regression with regular and error console output intermixed

- src/gwt/src/org/rstudio/core/client/theme/ThemeColors.java
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
Requesting feedback by mail so possible the Sky take will take more color tweaks, but in the meantime, this change improves on the baseline.
Before...
After...
> Color improvements for Sky theme

- src/cpp/core/system/PosixSystem.cpp
- src/cpp/core/system/Win32System.cpp
before we were only killing direct children, now we will kill all levels of child processes
> made child process termination on windows recursive like on posix

- src/gwt/src/org/rstudio/core/client/widget/ToolbarButton.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/BranchToolbarButton.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/HistoryBranchToolbarButton.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java
Fixes an issue where the Git Branch dropdown menu flowed offscreen in the Review Changes panel.
> alignment fixes for git branch dropdown

- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
New close terminal button hard to see under dark theme
> Invert close terminal icon in dark theme

- src/cpp/session/modules/SessionGit.cpp
Newer versions of `git` include PGP signatures in the log output (for `git log --pretty=raw`), e.g.
```
commit fc64a7db2a55643bbd54ba4789d197f36c4c813c
tree c718c9160f9123bde71ea49f150f04213995def5
parent 6b2861ac3d35a23b57e07f0a349b92bfb357dce2
author Jonathan McPherson <jonathan@rstudio.com> 1496700668 -0700
committer Jonathan McPherson <jonathan@rstudio.com> 1496700668 -0700
gpgsig -----BEGIN PGP SIGNATURE-----
Version: GnuPG v2
iQIcBAABCAAGBQJZNdcgAAoJEHVXp41qocafR0oQAMBPOQwGyKcT4M8jqieI5SRb
QFBUKFs6cKgkEXRShFzS0uXnIxFfzNUwTZ36ENxinvMrzSxu6b12nDSyL0oUJq8d
+uMfprM1/WK+b/F2FUnykD2Tgy9RkYH1uNVjw8Zk9GHHcCGqv0B7hLyjL+EhKGMf
bEIDJ85q4+xACSEQ9YmQ2mfKdE1Sz8tagXOTGUskkjAUatng4lhT0MCUHdnNEUux
4fi8YWUD6grE9/T6d35igqtC/5woFHh6R1Y42fb84OxOFYYJhdGbRICckVQVrZeG …
```
> handle PGP signatures in git log output

- src/gwt/tools/editor-settings/eclipse-code-style.xml
Import into Eclipse via: **Preferences/Java/Code Style/Formatter Import...**
> update eclipse code style line lengths from 80 to 100

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateOptionsDialog.java
- src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateOptionsWidget.java
- src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateOptionsWidget.ui.xml
> Correct positioning of tab panel and spacing for chunk settings dialog

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
> Fix off by 1px search textbox in packages, history, help

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
> Fix popup dialog for manipulate under flat theme

- src/cpp/session/modules/SessionRMarkdown.R
This PR fixes the transformation of YAML containing code of the form `!r expr`. We accomplish this by registering a custom tag handler for `!r` that just returns the code entry as-is with the original `!r` preserved, and use the placeholder trick for tagged content in general.
> handle '!r expr' in input/output of yaml

- Jenkinsfile
trigger tests after we've finished building, if pro.
cc @dfalty
> trigger qa-autotest on successful pro builds

- src/cpp/session/SessionSourceDatabaseSupervisor.cpp
Updated PR for https://github.com/rstudio/rstudio/pull/1389
@jmcphers @kevinushey
> fixed bug where multi session test was broken from one of my earlier commits

- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java
Helpful when debugging terminal buffer
> debugging aid for switching buffer dump mode

- src/cpp/session/modules/SessionConnections.R
Request to change new connections order from:
```
```
```
```
> Request to change connection creation order

- src/cpp/session/modules/SessionConnections.R
Currently, generic `odbc` drivers don't work in windows since we expect the `Driver` attribute to be present in `odbcinst.ini`; this is required in Linux and OS X; however, in Windows, this information is stored in the Windows Registry and therefore, not provided by the `odbc` package. The fix is to enhance `odbcListDrivers()` whenever we are in Windows with the Windows registry information.
> Add support to use generic drivers in Windows under `odbc` package

- src/cpp/session/resources/grid/gridstyles.css
https://support.rstudio.com/hc/en-us/community/posts/115008598108-Filter-in-View-not-showing-values-in-Rstudio-Preview-1-1-331
> Support for dark themes under viewer filters

- src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionNavigationPage.java
> Change title of connections dialog

- src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
TOC not rendering properly... https://twitter.com/tjmahr/status/895712793101344769
Improve code in help from...
to...
> Remove `<pre>` to format code correctly in help and add TOC

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
with no selection, splits chunk into two chunks at the cursor. with selection, splits chunk into three chunks (before selection, selection, and post selection)
Example:
> changed insert chunk behavior when already in a chunk

- src/gwt/tools/build-xterm-README.md
Mention need to manually tweak Dracula.css.
> Update xterm update instructions for Dracula theme

- src/cpp/session/SessionClientInit.cpp
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/include/session/SessionModuleContext.hpp
- src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackageLibraryUtils.java
Seems like a simple change but I might be missing something. Also first time I have written code to execute R functions so let me know if that was done incorrectly.
> Made package pane treat libs in R_LIBS_USER as user libraries

- src/cpp/core/system/Win32ChildProcess.cpp
When closing a terminal in Windows desktop IDE, via the [x] in upper-right of pane, the rsession log would accumulate errors of following form. Though no harm, adds a lot of noise to the log. Problem is that during the `AsyncChildProcess::poll`, `TerminalProcess` could end up being called multiple times on the same process, because the process exit may not happen immediately and polling will continue until it does. Added a flag to only call TerminateProcess one time.
```
21 Aug 2017 22:00:44 [rsession-gary_] ERROR system error 5 (Access is denied); 
OCCURRED AT: virtual rstudio::core::Error rstudio::core::system::ChildProcess::terminate() C:\Users\gary_\rstudio\src\cpp\core\system\Win32ChildProcess.cpp:282; 
LOGGED FROM: void rstudio::core::system::AsyncChildProcess::poll() …
```
> Reduce noise in Windows session log (access-denied)

- src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.cpp
- src/cpp/session/modules/rmarkdown/SessionExecuteChunkOperation.hpp
This PR fixes various issues where execution of alternate chunks could fail on Windows.
> fix alternate chunk execution on Windows

- src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/RDSDataType.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
This PR adds a small feature-let for loading `.rds` files when clicked on from the Environment pane:
> provide UI for opening '.rds' files

- Jenkinsfile
@jmcphers 
1. referring to a parameter variable by its local name appears to be broken on the first build in a branch. `params.<parameter_name>` seems clear this up as it properly uses the defaults.
2. remove `RSTUDIO_VERSION_PATCH` completely and reference `env.BUILD_NUMBER` since param re-assignment is iffy.
> use params hash instead of impliciting env variables

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Change the title of the Build and Reload command, as suggested by Hadley. Also cleans up some invalid XML in this file.
> Change "build and reload" to "install and restart"

- src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchTabPanel.java
> Prevent min/max buttons overlap in panels

- src/cpp/desktop/CMakeLists.txt
- src/cpp/desktop/DesktopActivationOverlay.cpp
- src/cpp/desktop/DesktopActivationOverlay.hpp
- src/cpp/desktop/DesktopMain.cpp
Refactoring to follow pattern I used on Mac desktop, based on feedback. I will deal with the merge into rstudio-pro.
> Open Source overlay for Qt activation

- src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchTabPanel.java
See https://github.com/rstudio/rstudio/issues/1565.
> Fix regression on utility pod min-max buttons to fix #1565

- src/gwt/src/org/rstudio/studio/client/rsconnect/model/PlotPublishMRUList.java
See https://github.com/rstudio/rstudio/issues/1585
> Fix retina icon while republishing rsconnect plot to fix #1585

- src/cpp/r/session/RSession.cpp
> namespace qualify call to q for quitting session

- src/cpp/desktop/DesktopActivationOverlay.cpp
- src/cpp/desktop/DesktopActivationOverlay.hpp
- src/cpp/desktop/DesktopMain.cpp
- src/cpp/desktop/DesktopSessionLauncher.cpp
- src/cpp/desktop/DesktopSessionLauncher.hpp
Some rearrangement of startup flow to faciliate async behaviors before session / main window are shown.
> companion checkin for https://github.com/rstudio/rstudio-pro/pull/214

- src/cpp/core/CMakeLists.txt
> Fix debug Linux desktop build

- src/gwt/.idea/.gitignore
- src/gwt/.idea/artifacts/Client_war_exploded.xml
- src/gwt/.idea/inspectionProfiles/profiles_settings.xml
- src/gwt/.idea/libraries/gin.xml
- src/gwt/.idea/libraries/gwt.xml
- src/gwt/.idea/misc.xml
- src/gwt/.idea/modules.xml
- src/gwt/gwt.iml
2.5 years since these were modified. I'm giving the JetBrains toolset a try.
> Update IntelliJ files for latest gwt, gin, etc.

- src/cpp/core/http/Response.cpp
emit Content Security Policy for ALLOW-FROM
> companion checking for https://github.com/rstudio/rstudio-pro/pull/227

- src/cpp/r/include/r/RRoutines.hpp
- src/cpp/session/SessionConsoleProcess.cpp
- src/cpp/session/SessionConsoleProcessApi.cpp
- src/cpp/session/include/session/SessionConsoleProcess.hpp
Some other minor C++ 11 tidying while I was in there.
> Cleanup ConsoleProcess constructors (somewhat) with default values

- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalHelper.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalLocalEcho.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTab.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/ActivateNamedTerminalEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/AddTerminalEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/ClearTerminalEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/CreateTerminalEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/RemoveTerminalEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/ResizeTerminalEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/SendToTerminalEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/SwitchToTerminalEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/TerminalBusyEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/TerminalCwdEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/TerminalDataInputEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/TerminalSessionStartedEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/TerminalSessionStoppedEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/TerminalSubprocEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/TerminalTitleEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/XTermTitleEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
Automated changes, only the string compares have any expected potential for behavioral changes (and should be in the direction of correct behavior).
- lambdas
- string comparisons via equals instead of ==
- remove unnecessary return statements
- remove unnecessary types in <>
- silly comparisons (!foo instead of foo == false, etc)
- comment typos
- string appends in a loop switched to stringbuilder
> Minor Java style refactorings via IntelliJ (terminal code)

- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java
- src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
- src/gwt/src/org/rstudio/studio/client/projects/Projects.java
- src/gwt/src/org/rstudio/studio/client/projects/events/SwitchToProjectEvent.java
Companion checkin for https://github.com/rstudio/rstudio-pro/pull/264.
> companion commit for Pro work (openProj API)

- src/cpp/session/projects/SessionProjects.cpp
- src/gwt/src/org/rstudio/studio/client/application/model/ApplicationServerOperations.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
Open source side of change to autopick .Rproj via openProj tutorial api. No expected runtime impact on Open Source product.
> Companion to https://github.com/rstudio/rstudio-pro/pull/266

- src/cpp/desktop/CMakeLists.txt
- src/cpp/desktop/DesktopMainWindow.cpp
- src/cpp/desktop/DockTileView.cpp
- src/cpp/desktop/DockTileView.hpp
- src/cpp/desktop/DockTileView.mm
Ported over from cocoa Mac desktop.
Resolves #1954
> Show project in dock icon (Mac/QtWebEngine)

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/r/SignatureToolTipManager.java
Was seeing Javascript exceptions due to tooltipPosition_ being null
> Added a null check

- src/cpp/desktop/DesktopWebPage.cpp
Resolves #1942
When RStudio UI contains an anchor with target=_blank, the goal is to launch it in the system browser. This happens in at least two places: the terminal, and the About dialog. Right now they launch, then RStudio crashes.
Locations where links are loading via JavaScript aren't impacted.
In QtWebView, an `acceptNavigationRequest` was sent to the view that was clicked, where we handled it. In QtWebEngine the order of messages has changed, and a new QWebEngine page is first created and then sent an `acceptNavigationRequest` message, where we intercept the _blank and send to browser. This meant a new RStudio browser window was created, which was being displayed, then crashing upon its immediate destruction. Now I make that window hidden, and let it trigger the external load. …
> Avoid crash with native target=_blank links

- dependencies/linux/install-qt-sdk
- dependencies/osx/install-qt-sdk-osx
- dependencies/windows/install-dependencies.cmd
- docker/jenkins/Dockerfile.centos7-x86_64
- docker/jenkins/Dockerfile.debian9-x86_64
- docker/jenkins/Dockerfile.precise-amd64
- docker/jenkins/Dockerfile.trusty-amd64
- docker/jenkins/Dockerfile.windows
- src/cpp/desktop/CMakeLists.txt
Essentially search and replace in various scripts, plus a tweak to CMakeLists.txt for Win32.
> Bump to using Qt5.10.0

- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionRmdNotebook.R
- src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.R
handle warnings involved by Chinese Characters under Windows OS
> handle warnings involved by Chinese Characters

- src/cpp/desktop/DesktopActivationOverlay.cpp
- src/cpp/desktop/DesktopActivationOverlay.hpp
- src/cpp/desktop/DesktopBrowserWindow.cpp
- src/cpp/desktop/DesktopChooseRHome.cpp
- src/cpp/desktop/DesktopDownloadHelper.cpp
- src/cpp/desktop/DesktopGwtCallback.cpp
- src/cpp/desktop/DesktopInputDialog.cpp
- src/cpp/desktop/DesktopMain.cpp
- src/cpp/desktop/DesktopMainWindow.cpp
- src/cpp/desktop/DesktopMenuCallback.cpp
- src/cpp/desktop/DesktopOptions.cpp
- src/cpp/desktop/DesktopPosixApplication.cpp
- src/cpp/desktop/DesktopPosixApplicationLaunch.cpp
- src/cpp/desktop/DesktopPosixDetectRHome.cpp
- src/cpp/desktop/DesktopSatelliteWindow.cpp
- src/cpp/desktop/DesktopSecondaryWindow.cpp
- src/cpp/desktop/DesktopSessionLauncher.cpp
- src/cpp/desktop/DesktopSubMenu.cpp
- src/cpp/desktop/DesktopSynctex.cpp
- src/cpp/desktop/DesktopURLDownloader.cpp
- src/cpp/desktop/DesktopUtils.cpp
- src/cpp/desktop/DesktopUtils.hpp
- src/cpp/desktop/DesktopWebPage.cpp
- src/cpp/desktop/DesktopWebProfile.cpp
- src/cpp/desktop/DesktopWebView.cpp
- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
Mostly cleanup, some messagebox API tweaks
> companion to https://github.com/rstudio/rstudio-pro/pull/325

- src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ObjectBrowser.java
This change works around an issue in the Connections pane wherein clicking "Show more" to show additional objects caused the scroll position to jump to the top of the list.
In 1.2, this change makes the pane paged into 512 object chunks, as the current 1.2 behavior is to show all the objects (no matter how numerous). It won't affect most users, but will prevent very large databases from overwhelming the DOM. 
In 1.1, where this will be backported pending additional builds, the pane currently begins paging at 25 objects (see the original issue for an explanation of why this occurs). This change makes that 512 objects to accommodate most databases without paging, and fixes the original scroll bug. 
Fixes #2211.
> Scroll down after clicking Show More in Connections pane

- src/cpp/session/modules/shiny/SessionShiny.cpp
> avoid use of boost::regex when trimming comments

- dependencies/linux/install-qt-sdk
- dependencies/osx/install-qt-sdk-osx
- dependencies/windows/install-dependencies.cmd
- docker/jenkins/Dockerfile.centos7-x86_64
- docker/jenkins/Dockerfile.debian9-x86_64
- docker/jenkins/Dockerfile.precise-amd64
- docker/jenkins/Dockerfile.trusty-amd64
- docker/jenkins/Dockerfile.windows
- docker/jenkins/windows/qt-noninteractive-install.qs
- src/cpp/desktop/CMakeLists.txt
Uploaded Mac/Linux/Windows Qt5.10.1 packages to S3, tweaked scripts.
> Update to Qt 5.10.1

- src/cpp/r/session/RInit.cpp
- src/cpp/r/session/RStdCallbacks.cpp
- src/cpp/r/session/RStdCallbacks.hpp
Candidate fix for build issue on Windows.
> Move image dirty callbacks to protected location

- src/cpp/desktop/DesktopGwtCallback.cpp
- src/cpp/desktop/DesktopGwtCallback.hpp
- src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
A lingering TODO from the QtWebEngine switchover.
Fixes #2297
> Restore R version selection option for Win desktop

- src/gwt/acesupport/acemode/markdown_highlight_rules.js
- src/gwt/acesupport/acemode/rmarkdown_highlight_rules.js
- src/gwt/acesupport/acemode/sh.js
- src/gwt/acesupport/acemode/sh_highlight_rules.js
- src/gwt/src/org/rstudio/studio/client/common/reditor/EditorLanguage.java
> import + patch sh highlight rules for heredocs

- src/cpp/session/SessionConsoleProcessSocketTests.cpp
I broke the websocket tests with #2369.
> Fix rsession unit tests (SocketTests)

- src/cpp/desktop/DesktopWebView.cpp
With this PR, we build the context menu ourselves rather than requesting that Qt do it for us. In particular, this ensures that we can add Cut, Copy and Paste actions as appropriate.
Reload and Inspect Element are kept out of the menu, except in debug configurations.
> implement own handling of context menus

- src/cpp/session/modules/SessionReticulate.R
This PR overrides `matplotlib.show()` such that plots are captured and shown in the Plots pane instead.
There are some TODOs that we might want to think about; potentially for this PR or future PRs:
> show matplotlib plots in Plots pane

- src/cpp/session/modules/build/SessionBuild.cpp
Fixes https://github.com/rstudio/rstudio/issues/2299.
> improve reporting of package DESCRIPTION parse errors

- src/cpp/desktop/DesktopMain.cpp
- src/gwt/www/index.htm
> disable user zoom gestures

- src/cpp/desktop/DesktopGwtCallback.cpp
> don't resolve symlinks when requesting file name

- src/cpp/desktop/DesktopBrowserWindow.cpp
> Fix syntax error in embedded JavaScript

- src/cpp/desktop/DesktopGwtCallback.cpp
This provides an escape hatch for users being hit bit slowness when RStudio's clipboard monitoring enabled, as per https://github.com/rstudio/rstudio/issues/2068.
One can launch RStudio with something like:
```
RSTUDIO_NO_CLIPBOARD_MONITORING=1 rstudio
```
to activate this feature (pending extra UI for toggling this).
> allow users to disable X11 clipboard monitoring

- src/cpp/desktop/DesktopWebPage.cpp
- src/cpp/desktop/DesktopWebPage.hpp
> don't rely on NavigationType when handling navigation requests

- src/cpp/desktop/DesktopWebPage.cpp
Closes https://github.com/rstudio/rstudio/issues/2554.
> handle file download requests (e.g. from Shiny applications)

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java
Add support to open a file from D3, used to detect errors and allow opening back error location...
> Add support to open files from d3 error

- src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java
- src/gwt/src/org/rstudio/studio/client/htmlpreview/HTMLPreviewPresenter.java
Minor follow up to support line highlighting while hitting error from external D3 window.
> Support line highlighting while opening files from satellites

- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
Fixes #2665 
Another RStudio Console rendering corner case with mixture of colors, and overwriting existing text via carriage return.
This code is feeling uglier than it needs to be, but not going to try any ambitious cleanup in 1.2, just patch 'em as we find 'em and add unit tests.
Intentionally leaving in some diagnostic aids in VirtualConsole (not being called) in the highly unlikely case more of these sorts of issues need to be investigated in the future.
> Console issue with mixed colors, CR, and changing range lengths

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Fixes https://github.com/rstudio/rstudio/issues/2691
> Save document when running test file to fix #2691

- src/cpp/session/SessionHttpMethods.cpp
- src/cpp/session/SessionOptions.cpp
- src/cpp/session/SessionSuspend.cpp
- src/cpp/session/include/session/SessionConstants.hpp
- src/cpp/session/include/session/SessionOptions.hpp
> Added new option  to control if the session is suspended after timeout, or simply exited.

- src/cpp/desktop/DesktopWebPage.cpp
- src/cpp/desktop/DesktopWebProfile.cpp
- src/cpp/desktop/DesktopWebProfile.hpp
This PR ensures that `iframe`s requested in the main window are loaded in RStudio, rather than a separate browser window.
Closes #2756.
> correctly detect and handle attempts to load iframes

- src/cpp/session/modules/SessionDataPreview.R
Minor request to increase SQL preview to 1K rows.
> Increase sql preview to 1K rows

- src/cpp/core/spelling/hunspell/affentry.hxx
- src/cpp/core/system/Process.cpp
- src/cpp/session/modules/SessionCodeSearch.cpp
Should hopefully close these issues:
https://github.com/rstudio/rstudio/issues/2373
https://github.com/rstudio/rstudio/issues/2289
> fix compilation issues for clang-6.0

- src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
> specify plumber package dependencies

- src/cpp/session/http/SessionPosixHttpConnectionListener.cpp
- src/cpp/session/include/session/SessionInvalidScope.hpp
- src/cpp/session/include/session/SessionLocalStreams.hpp
- src/cpp/session/include/session/http/SessionRequest.hpp
Added back SessionLocalStreams file into session directory.
> Fixed build error

- src/gwt/src/org/rstudio/core/client/widget/GridViewerFrame.java
- src/gwt/src/org/rstudio/core/client/widget/GridViewerStyles.java
- src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/data/DataOutputPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTargetWidget.java
https://twitter.com/hrbrmstr/status/1000048188580093952
Fix,
> Support themes in sql preview

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
Fixes https://github.com/rstudio/rstudio/issues/2860
> Allow deletion of secondary repos to fix #2860

- src/cpp/session/modules/SessionConnectionsInstaller.R
Fix for https://github.com/rstudio/rstudio-pro/issues/446.
> Add support for header comments in odbcinst.ini

- dependencies/common/.gitignore
- dependencies/common/install-packages
- dependencies/common/install-packages.cmd
- src/cpp/session/CMakeLists.txt
- src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
plumber 0.4.6 is now on CRAN so stop embedding it
> Use plumber package from CRAN

- src/cpp/session/modules/SessionConnections.R
Fix for https://github.com/rstudio/rstudio/issues/1754
> Make use of odbc timeout parameter

- src/cpp/core/include/core/r_util/RProjectFile.hpp
- src/cpp/core/r_util/RProjectFile.cpp
- src/cpp/session/modules/SessionFiles.cpp
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
@jmcphers I had reverted this work last week b/c I thought it was no longer necessary.
I was wrong. This brings back the code with a couple of tweaks. I am going to merge but pls give a quick code review when you can next week.
> preview for articles below the root in websites

- src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
Fix for https://github.com/rstudio/rstudio/issues/2024
> Disable themes for help under classic to fix #2024

- src/cpp/session/modules/SessionObjectExplorer.R
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/ObjectExplorerEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/ObjectExplorerServerOperations.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/view/ObjectExplorerEditingTargetWidget.java
> discover new object definitions on explorer refresh

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/view/ObjectExplorerDataGrid.java
This PR further refines the fix to https://github.com/rstudio/rstudio/issues/2932. The intention is to make sure that any handled KeyUp event had a corresponding KeyDown event prior.
The situation here is a bit dicey: for whatever reason, the DataGrid event handler does not receive KeyPress events; rather, it receives repeated KeyDown events. Fortunately, we can differentiate the initial KeyDown event from repeated KeyDown events with the `repeat` flag set on the Event.
To wit, before handling a KeyUp event, we ensure that we received a non-repeated KeyDown event prior.
> refine enter handling in object explorer

- dependencies/windows/Install-RStudio-Prereqs.ps1
- dependencies/windows/README.md
- as recommended by @kevinushey, dramatically improves speed of incremental builds
> Install ninja on Windows dev machines

- src/cpp/core/system/file_monitor/Win32FileMonitor.cpp
This PR fixes an issue where attempts to install R packages in a Packrat project could be very slow, due to the file monitor attempting to process file changes detected in the `packrat` folder. (This is especially true with the `BH` package which contains over 10,000 header files!)
> don't process file changes in packrat dir (#1864)

- src/cpp/desktop/DesktopSessionLauncher.cpp
This PR ports the 'wait and retry' code from macOS to be used on all platforms, ensuring that we don't attempt a reload until we know the server is ready to respond to our request.
Closes https://github.com/rstudio/rstudio/issues/2898.
> wait for server ready before reload

- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
> windows requires 'file:///' prefix for files

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
Fix regression from https://github.com/rstudio/rstudio/pull/3050 which removed some code that was not dead.
> Fix regression caused by dead code removal #3050

- src/cpp/desktop/DesktopWebView.cpp
This PR adjusts the context menus displayed in RStudio. In particular, on macOS, most applications capitalize each word within a context menu entry; on other OSes only the first word is capitalized. This PR makes sure to handle that, and also adjusts some of the labels + mnemonics (currently done to match what Chrome does, but we could consider our own set)
> handle case in context menu; tweak context items

- src/cpp/desktop/DesktopMain.cpp
This is a stop-gap fix for https://github.com/rstudio/rstudio/issues/3148.
> disable GPU for AMD FirePro graphics cards

- src/cpp/desktop/DesktopOptions.cpp
> avoid saveGeometry / loadGeometry

- src/cpp/session/modules/build/SessionBuild.cpp
- src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
Closes https://github.com/rstudio/rstudio/issues/3208.
> require devtools for testthat tests

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetJSHelper.java
Show an error message when the JavaScript previewer requested by the user is not an understood previewer:
As we expand support for other previewers, we can expand the whitelist / set of messages (or even define some kind of contract for packages that want to register themselves as knowing how to preview JavaScript)
> require 'r2d3' name when previewing JavaScript (closes #3205)

- src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPresenter.java
> provide short timeout (give HTTP server time to initialize)

- src/cpp/session/modules/SessionDataViewer.R
> suppress warnings when calling hist()

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
> suppress default checkbox style on Firefox

- src/cpp/desktop/DesktopGwtCallback.cpp
- src/cpp/desktop/DesktopGwtWindow.cpp
- src/cpp/desktop/DesktopGwtWindow.hpp
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
> fixups for setting desktop zoom level

- src/cpp/session/modules/SessionThemes.cpp
- src/cpp/session/modules/SessionThemes.hpp
- src/cpp/session/modules/data/DataViewer.cpp
> Fixes an issue where the grid data viewer is unthemed

- src/cpp/desktop/DesktopPosixApplicationLaunch.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java
Associated Qt bug report: https://bugreports.qt.io/browse/QTBUG-70151
> fix handling of bare Ctrl / Meta keypresses (closes #3363)

- src/cpp/desktop/CMakeLists.txt
- src/cpp/desktop/DesktopMainWindow.cpp
- src/cpp/desktop/DesktopMainWindow.hpp
- src/cpp/desktop/DesktopRCommandEvaluator.cpp
- src/cpp/desktop/DesktopRCommandEvaluator.hpp
- src/cpp/desktop/Info.plist.in
- src/cpp/desktop/RStudio.sdef
- src/cpp/desktop/ScriptCommand.h
- src/cpp/desktop/ScriptCommand.mm
Not the most beautiful way to do it, but it works.
close #3354
> AppleScript support

- src/gwt/src/org/rstudio/studio/client/server/ServerErrorCause.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/DocUpdateSentinel.java
> don't warn when failing to revert a deleted file

- src/cpp/server/ServerMain.cpp
- src/cpp/session/modules/SessionReticulate.cpp
- src/cpp/session/modules/SessionThemes.cpp
> Add URI handlers for the Python Help Pane theme.

- src/cpp/session/modules/SessionHelp.cpp
- src/cpp/session/modules/SessionReticulate.cpp
This PR completes #3413 and closes #3410.
> Finish PR #3413.

- src/cpp/r/R/Api.R
See also: https://github.com/rstudio/rstudioapi/pull/110
> add API functions for build tool installation

- docker/docker-compile.sh
This change makes it possible to produce a debug build from the `docker-compile` script by setting `CMAKE_BUILD_TYPE` appropriately.
> Add mechanism for triggering debug compiles on docker

- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
Closes https://github.com/rstudio/rstudio/issues/3270.
> properly form path to pdf for bookdown books

- src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
- src/gwt/src/org/rstudio/core/client/theme/MinimizedWindowFrame.java
- src/gwt/src/org/rstudio/core/client/theme/ModuleTabLayoutPanel.java
- src/gwt/src/org/rstudio/core/client/theme/RStudioDataGridStyle.css
- src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/core/client/widget/FindTextBox.ui.xml
- src/gwt/src/org/rstudio/core/client/widget/SearchWidget.ui.xml
- src/gwt/src/org/rstudio/core/client/widget/SecondaryToolbar.java
- src/gwt/src/org/rstudio/core/client/widget/ThemedPopupPanel.css
- src/gwt/src/org/rstudio/core/client/widget/Toolbar.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchTabPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionExplorer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilePathToolbar.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/PackagesDataGrid.css
This PR exposes the GWT CSS classes as requested in #3368. (See https://github.com/rstudio/rstudio/issues/3368#issuecomment-418568294).
Closes #3368.
> Exposes GWT CSS classes as requested.

- src/cpp/session/modules/SessionRmdNotebook.R
To reproduce the issue, try running all chunks in this notebook:
`````
---
title: "R Notebook"
output: html_notebook
---
```{r setup}
knitr::opts_chunk$set(custom = 1)
```
```{r}
knitr::opts_chunk$get("custom")
```
`````
You should see the following output:
The issue here is that, when we attempt to do our dance around chunk options when learning what the default chunk options for a Notebook session are, we fail to restore the user-set chunk options in the current R session (even though we do cache them as needed for our own purposes).
Closes https://github.com/rstudio/rstudio/issues/3493.
> ensure chunk options set in setup chunk are persisted appropriately

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/r/SignatureToolTipManager.java
This PR fixes an issue where a signature tooltip could get stuck on the screen. The issue here was in this sequence of events:
1. Signature tooltip is currently showing;
2. User types a new function call (e.g. `identity(`), triggering a new tooltip to show,
3. A new anchor is set for the newly-inserted function call,
4. The old tooltip is hidden, and erroneously detaches the newly-attached anchor (!)
5. The new tooltip is shown, but with no accompanying anchor and so is not closed on regular cursor navigation.
The fix here is to relax where anchor detach occurs.
> avoid over-zealous anchor detach (closes #3504)

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
> work around Mojave vs. Chromium bug

- src/cpp/session/modules/sql/SessionSql.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/SqlCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/SqlCompletionParseContext.java
Closes https://github.com/rstudio/rstudio/issues/3593.
> improve support for schemas with SQL autocompletion

- src/cpp/session/modules/sql/SessionSql.R
It looks like there is some impedance mismatch between the DBI and odbc APIs. This PR checks specifically for odbc connections, and attempts to call the requisite APIs to retrieve the objects we need for autocompletion.
> handle autocompletion with odbc connections (#3597)

- src/gwt/acesupport/acemode/markdown_highlight_rules.js
Closes https://github.com/rstudio/rstudio/issues/1699.
> fix some regressions in markdown highlight rules

- src/gwt/src/org/rstudio/core/client/StringUtil.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/SqlCompletionManager.java
re: https://community.rstudio.com/t/new-sql-autocompletion-feature-doesnt-work-with-schemas-e-g-postgresql-public-any-table/15610
> ensure quoted SQL identifiers are handled

- src/cpp/session/modules/SessionProfiler.cpp
- src/cpp/session/modules/SessionThemes.cpp
This solution is starting to feel a bit messy, given that we've had to add 3 extra prefixes so far. Any ideas for cleaning it up are very welcome.
> Make themes work with Profiles documents.

- src/cpp/session/modules/SessionHelp.cpp
This PR improves detection of the error pages returned by the R help system, and marks them as 404 not found errors.
> improve handling for R help error pages

- src/cpp/desktop/DesktopMain.cpp
Kind of a gross hack but it seems to reliably fix the issue and I can't think of anything more clever to do here!
> call processEvents twice (#3728)

- src/cpp/desktop/DesktopMain.cpp
This should be a more reliable fix for #3728.
> run event loop on startup to pump OpenFile events

- src/cpp/session/modules/SessionDataViewer.R
- src/cpp/session/resources/grid/dtviewer.js
Closes #3734 (see associated issue for discussion).
> side-step JSON serialization issue with large numbers

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
> Fixes a bug where the theme flickers when changing it

- src/cpp/desktop/DesktopWebPage.cpp
Closes https://github.com/rstudio/rstudio/issues/3809.
> bind Ctrl+W to close window for satellites

- src/cpp/r/RSexp.cpp
- src/cpp/r/include/r/RSexp.hpp
- src/cpp/session/modules/SessionSource.cpp
Closes https://github.com/rstudio/rstudio/issues/1868.
> handle encodings with UTF-8 filepaths

- src/cpp/core/http/ChunkParser.cpp
There are a bunch of these to fix in Pro; this was the only one in Open Source.
> fix copyright date

- src/cpp/session/modules/SessionRParser.cpp
> handle use of '.' in magrittr pipes

- src/cpp/core/libclang/LibClang.cpp
Closes https://github.com/rstudio/rstudio/issues/3820.
> discover + use Xcode system headers with libclang

- src/cpp/desktop/DesktopGwtCallback.cpp
- src/cpp/desktop/DesktopGwtCallback.hpp
- src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
- src/gwt/src/org/rstudio/studio/client/application/DesktopWebAction.java
- src/gwt/src/org/rstudio/studio/client/workbench/exportplot/clipboard/CopyPlotToClipboardDesktopDialog.java
> use builtin copy action for plot copy

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
> Fix a bug where the query in the URL is treated like a path element

- src/cpp/session/modules/SessionRSConnect.R
- src/gwt/src/org/rstudio/studio/client/rsconnect/model/RSConnectServerOperations.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectPublishButton.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
Closes #3497. Suggestions on language tweaks appreciated.
> add option for forgetting deployments

- src/gwt/src/org/rstudio/core/client/files/filedialog/FileSystemDialog.java
> allow 'All Files (*)' filter

- src/gwt/src/org/rstudio/studio/client/workbench/views/choosefile/ChooseFile.java
> support file.choose(new = TRUE)

- src/cpp/session/resources/templates/ace_theme_template.css
> include highlight rule for whitespace characters

- src/cpp/desktop/DesktopInfo.cpp
This should further improve performance on systems containing a large number of installed fonts, where `fontconfig` (and the associated utilities) are installed.
> use fontconfig database to list monospace fonts

- src/cpp/r/R/Options.R
- src/cpp/session/modules/rmarkdown/NotebookExec.cpp
> set 'rstudio.notebook.executing' option during notebook exec

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
Closes https://github.com/rstudio/rstudio/issues/3912.
> fix notebook event handler + 'removeContentUrl()' error

- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
> fix detection when knitting website pages

- src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobProgress.java
> hide status label for ranged jobs

- src/cpp/session/modules/SessionRCompletions.R
- src/cpp/session/modules/SessionRMarkdown.R
- src/gwt/src/org/rstudio/studio/client/common/codetools/CodeToolsServerOperations.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/MarkdownCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/PythonCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/SqlCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/StanCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
> re-implement markdown completions with new completion engine

- src/cpp/r/R/Api.R
- src/cpp/r/include/r/RRoutines.hpp
- src/cpp/session/modules/SessionSpelling.cpp
To support https://github.com/rstudio/rstudioapi/issues/123.
> make dictionary paths user-accessible

- src/gwt/tools/compile-themes.R
> remove unnecessary requirement of highlight package.

- src/cpp/desktop/DesktopPosixApplicationLaunch.cpp
Closes https://github.com/rstudio/rstudio/issues/4086.
> work around blank windows on first show

- package/win32/cmake/modules/NSIS.template.in
- src/cpp/desktop/rstudio.rc.in
- src/cpp/desktop/synctex/rsinverse/rsinverse.rc.in
- src/cpp/desktop/urlopener/urlopener.rc.in
- src/cpp/diagnostics/diagnostics.rc.in
- src/cpp/session/consoleio/consoleio.rc.in
- src/cpp/session/rsession.rc.in
- src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.ui.xml
About dialog, version resources on Windows.
> Bump visible copyright dates to 2019

- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectPublishButton.java
> save + use app path for forgetDeployments action

- src/cpp/session/modules/environment/SessionEnvironment.cpp
> limit recursion by tracking visited SEXPs

- src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobItem.java
Fixes #4153
Also fixes the same issue for Pro job-launcher jobs.
> Fix bug where job stop button was switching views

- src/cpp/session/modules/SessionDataPreview.R
> properly report errors when parsing SQL preview command

- src/gwt/src/org/rstudio/core/client/widget/Wizard.java
- src/gwt/src/org/rstudio/core/client/widget/WizardNavigationPage.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewProjectWizard.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionNavigationPage.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionWizard.java
Fix for https://github.com/rstudio/rstudio-pro/issues/705
Also some code cleanup in here too.
> LayoutPanel divs to overflow visible in Wizards

- src/cpp/session/modules/SessionThemes.cpp
This change fixes a crash that can occur when restarting R after loading the tidyverse. These packages request the RStudio theme colors when they're reattached after the restart, with the result that we try to use a waitformethod before the session deferred init is complete.
The fix here is to just return no colors until we can use the client to resolve them. A better fix would be to load the colors in a different way, and/or to be more general about waitformethods (we could for example forbid all use of waitformethod before the session is fully initialized), but both are too broad for 1.2.
Fixes #4178.
> Avoid calling WaitForMethod until session init is complete

- src/gwt/src/org/rstudio/studio/client/shiny/ShinyApplicationPresenter.java
Closes #4207.
Might be worth diving in more deeply to figure out a root cause but given that we want to get v1.2 out the door this should hopefully suffice.
> listen for both 'beforeunload', 'unload' events

- src/cpp/session/modules/SessionGit.cpp
> use HEAD: prefix in refspec

- src/gwt/acesupport/acemode/r_matching_brace_outdent.js
Fixes https://github.com/rstudio/rstudio/issues/4260.
> perform outdenting for ']'

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
> don't trim trailing whitespace on save for Python scripts

- src/cpp/session/modules/SessionRmdNotebook.R
Notebook execution can break when options which we expect to be logical, aren't actually logical. This PR sanitizes such chunk options (and also parses `T` and `F` short-hands as `TRUE` and `FALSE`). 
We could also consider explicitly evaluating language objects in the chunk options, but that feel far too dicey for v1.2 and we've been otherwise happy with the current implementation for some time.
Closes #4129.
> sanitize certain chunk options before execution

- src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionShinyHost.java
Fix for https://github.com/rstudio/rstudio/issues/4359, could we get this into RStudio 1.2? Thanks!
> Prompt to install shiny when using connections with shiny extension

- src/cpp/server/extras/admin/rstudio-server.in
Fixes https://github.com/rstudio/rstudio-pro/issues/913
> Prompt the user to stop the service before running verify-installation

- dependencies/common/install-gwt
- dependencies/windows/install-dependencies.cmd
- src/gwt/build.xml
Fixes #4142 
Latest release, relatively minor changes/bugfixes.
I ran gwt unit tests, and very quick sanity check of both desktop and server built with 2.8.2.
http://www.gwtproject.org/release-notes.html#Release_Notes_2_8_2
> Update gwt to 2.8.2

- dependencies/windows/install-qt-sdk-win.cmd
- dependencies/windows/qt-noninteractive-install-win.qs
Qt installer script wasn't updated so was still installed 5.12.0.
> install Qt 5.12.1 on Windows

- src/gwt/src/org/rstudio/studio/client/common/filetypes/StanFileType.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Requested here: https://community.rstudio.com/t/feature-request-re-stan-support-in-rstudio-1-2/25272
This change should be small and safe enough but I understand if we'd rather get this in for v1.2-patch or v1.3.
> enable reindent, soft-wrap for Stan

- src/gwt/www/expired.htm
- src/gwt/www/index.htm
- src/gwt/www/offline.htm
- src/gwt/www/progress.htm
- src/gwt/www/projectnotfound.htm
- src/gwt/www/templates/encrypted-sign-in.htm
- src/gwt/www/unsupported_browser.htm
- src/gwt/www/webkit.nocache.html
- this is an accessibility requirement for even the lowest level (A) compliance with WCAG 2.0
- this is chipping away at a mountain with a (small) feather duster but have to start somewhere
- also fixes a couple incorrectly closed style elements
Fixes #4411
> set html language

- src/cpp/server/ServerMain.cpp
- src/cpp/session/modules/SessionSpelling.cpp
> fix realtime spelling working with non bundled dictionaries bug #4408

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
This PR follows in the footsteps of the [VSCode issue tracker](https://github.com/Microsoft/vscode/issues/new/choose), providing separate templates for bug reports and feature requests. We also use a place-holder 'Ask a Question' template to redirect users to the community website.
> provide separate templates for bugs / features / questions

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
Fixes part of https://github.com/rstudio/rstudio/issues/4448.
> enforce spaces when indentation detected

- src/cpp/session/modules/SessionPackages.R
> handle empty-repos case

- src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
Closes https://github.com/rstudio/rstudio/issues/4358.
> bump version of rstudioapi

- src/cpp/desktop/DesktopMain.cpp
This PR augments the check for Windows remote session, using the advice in https://docs.microsoft.com/en-us/windows/desktop/termserv/detecting-the-terminal-services-environment.
Closes https://github.com/rstudio/rstudio/issues/4466.
> augment check for windows remote sessions

- src/cpp/desktop/DesktopSessionLauncher.cpp
Will also be merged to 1.2-patch
> companion to https://github.com/rstudio/rstudio-pro/pull/971

- src/cpp/desktop/Info.plist.in
> provide messages when R asks for permissions

- src/cpp/session/modules/SessionEnvironment.R
This PR rewrites the `"editor"` function we supply to R for calls to `utils::edit()` and `utils::file.edit()`.
The previous implementation had a major issue: it attempted to parse the file as edited by `utils::file.edit()` as though it was R code, even though that is not really part of the contract for `utils::file.edit()` (it's just for editing a file).
The fix here is to just check early on whether we're only attempting to edit a file (ie: `name` is missing) and take the short edit path in that case; and do the longer `edit()`-style action otherwise.
> tidy up editor option def'n

- src/cpp/session/SessionConsoleProcess.cpp
- src/cpp/session/SessionConsoleProcessApi.cpp
- src/cpp/session/SessionConsoleProcessInfo.cpp
- src/cpp/session/SessionConsoleProcessInfoTests.cpp
- src/cpp/session/SessionConsoleProcessTable.cpp
- src/cpp/session/SessionConsoleProcessTests.cpp
- src/cpp/session/SessionUserSettings.cpp
- src/cpp/session/include/session/SessionConsoleProcess.hpp
- src/cpp/session/include/session/SessionConsoleProcessInfo.hpp
- src/cpp/session/include/session/SessionTerminalShell.hpp
- src/cpp/session/include/session/SessionUserSettings.hpp
- src/cpp/session/modules/SessionTerminalShell.cpp
- src/cpp/session/modules/SessionTerminalShellTests.cpp
- src/cpp/session/modules/SessionWorkbench.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java
enum to "enum class", plus some other minor cleanup.
> Refactor shell type enum to be an enum class

- src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
Title says it all; fixes https://github.com/rstudio/rstudio/issues/4628.
> Remove unnecessary rprojroot dependency

- src/cpp/desktop/DesktopMain.cpp
Title says it all; we need to always use the `--no-sandbox` Chromium flag when the user is root. 
Fixes https://github.com/rstudio/rstudio/issues/4631.
> Use --no-sandbox when effective user is root

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
Closes https://github.com/rstudio/rstudio/issues/4622.
> properly handle Ace editor focus w/RStudio Server

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
Closes https://github.com/rstudio/rstudio/issues/4257.
> fix gutter styling for executing lines in .Rmd

- src/cpp/core/FilePath.cpp
- src/cpp/core/include/core/FilePath.hpp
- src/cpp/session/modules/SessionCodeSearch.cpp
> don't index files with '.q' extension; skip large files

- src/cpp/session/modules/SessionRmdNotebook.R
Closes https://github.com/rstudio/rstudio/issues/2364.
> remove ANSI escapes during notebook preview

- NEWS-1.2-patch.md
- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
Fixes #4777
I think this is reasonably safe to take for 1.2-patch. This code is finicky but does have good unit test coverage.
> VirtualConsole bug when rewriting same line with certain color range pattern

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
Closes https://github.com/rstudio/rstudio/issues/4674.
> scroll cursor into view when jumping to matching

- src/cpp/session/modules/SessionHelp.cpp
This PR fixes `help.search()` for R 3.6.0. Candidate for v1.2 backport.
> avoid changing port in query params (closes #4819)

- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectList.css
Fixes https://github.com/rstudio/rstudio/issues/4840.
> Ensure resize column doesn't take up space in layout row

- src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Saw https://github.com/rstudio/rstudio/issues/4237 pop up this morning and it seemed like a fun little thing to implement, so I did.
> Simple Word Count feature

- src/cpp/r/R/Tools.R
Fixes another check related to `_R_CHECK_LENGTH_1_LOGIC2_=true`.
> fix repos check (#4751)

- src/cpp/desktop/DesktopBrowserWindow.cpp
This should fix an issue where text can appear blurry / fuzzy when an RStudio window is transitioned between a regular DPI display to a high DPI display, and vice versa.
> force window re-render when moved to new screen

- src/cpp/desktop/DesktopOptions.cpp
A number of users have reported that RStudio seems to fail to launch on Windows. The specific symptoms are:
1. RStudio launches, but no window shows on the screen;
2. In the Taskbar, the RStudio icon displays, but the window preview is just a white screen. Clicking it seems to do nothing.
In fact, what has happened in these configurations is that RStudio has restored the window position off-screen (likely because the user's screen configuration has changed since the last time the screen geometry was saved -- e.g. they removed an external monitor on which RStudio had been displaying before).
This PR alleviates the issue by sanity-checking the restored geometry against the user's current window geometry. If restoring the geometry would display the window off-screen, then we just re-position …
> sanity-check window geometry after restore

- src/gwt/src/org/rstudio/core/client/command/impl/DesktopMenuCallback.java
- regression from #4790
- fixes #4906
> modal dialogs not showing from satellite windows on Desktop IDE

- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Closes https://github.com/rstudio/rstudio/issues/4894.
> handle PageDown when console has focus

- src/cpp/desktop/DesktopGwtCallback.cpp
This PR improves the plain printing of code, so that page boundaries are properly respected during print (regardless of page orientation).
Closes https://github.com/rstudio/rstudio/issues/4815.
> improve text formatting during print

- src/cpp/session/modules/SessionCodeSearch.cpp
Should help resolve crashes of this form: https://sentry.io/organizations/rstudio/issues/1070768710/?project=1379214&referrer=slack&statsPeriod=14d
Note that we use this pattern fairly liberally and it hasn't caused us too many issues. I believe because it delays object construction to first-use, which makes destruction order well-defined (and ensures our objects get destructed before the pieces they use under-the-hood)
> use Meyer's singleton for project indexer

- src/cpp/core/CrashHandler.cpp
- src/cpp/core/FileUtils.cpp
- src/cpp/core/include/core/CrashHandler.hpp
- src/cpp/core/include/core/FileUtils.hpp
- src/cpp/session/SessionClientInit.cpp
- src/cpp/session/modules/SessionWorkbench.cpp
- src/cpp/session/projects/SessionProjectContext.cpp
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/Workbench.java
- src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java
- src/gwt/src/org/rstudio/studio/client/workbench/model/WorkbenchServerOperations.java
Closes https://github.com/rstudio/rstudio/issues/4963
> Now prompting for explicit permission for opt-in of crash handling

- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java
> wrong icon for parent folder in files pane

- src/gwt/src/org/rstudio/core/client/widget/RStudioDataGrid.java
Fixes https://github.com/rstudio/rstudio/issues/4662.
The issue here: DataGrid makes use of CustomScrollPanel widgets, which attempt to create and draw their own scrollbars. They do this by hiding the native scrollbars, and then adding their own divs that draw scrollers as appropriate.
https://github.com/gwtproject/gwt/blob/724f696ee01c7374a01741b3bee2ae13440c9da9/user/src/com/google/gwt/user/client/ui/CustomScrollPanel.java#L448-L457
The code we added to hide the errant scrollbars (normally seen when e.g. resizing panes, as in https://github.com/rstudio/rstudio/commit/3c61cd27e855f82a434a8e872774b69a63a0cc2c#diff-d8c9d190556b0a17a26366934efb62c0) was too aggressive. In addition to the rogue scrollbars, it was also adjusting the overflow on the parent 'scroller' container, and that was …
> avoid hiding real GWT scrollbars

- src/gwt/src/org/rstudio/core/client/RegexUtil.java
Closes https://github.com/rstudio/rstudio/issues/4983.
> fix regex check for non-syntactic identifiers

- src/cpp/core/gwt/GwtFileHandler.cpp
- src/gwt/www/index.htm
> only set user-scalable=no viewport on desktop app

- src/cpp/session/modules/SessionThemes.R
- src/cpp/session/modules/SessionThemes.cpp
> Fix an issue where theme files with special URL characters cannot be removed.

- src/cpp/core/FilePath.cpp
- src/gwt/src/org/rstudio/core/client/files/FileSystemItem.java
I'm frankly unsure if this PR will fix the issue I reported in #5064 . I am unfamiliar with RStudio's codebase and found it was really difficult to build / test locally.
If this PR is not sufficient, please decline it. If it's "almost there", please give me some guidance on what else needs to be done.
Thanks!
> Added support for opening rst files (fixes #5064)

- src/gwt/src/org/rstudio/core/client/cellview/ImageButtonColumn.java
- src/gwt/src/org/rstudio/core/client/resources/ImageResource2x.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/CheckForUpdatesDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/CleanUnusedDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/PackageActionConfirmationDialog.java
Add labels to checkboxes and image buttons in packages pane, update packages dialog, and the clean unused packages dialog.
> add labels to checkboxes, image buttons, in packages grids

- src/cpp/session/modules/clang/RCompilationDatabase.cpp
Should help alleviate https://github.com/rstudio/rstudio/issues/4972.
> better handle custom OBJECTS in Makevars

- src/gwt/src/org/rstudio/studio/client/common/mirrors/model/CRANMirror.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
Fix for https://github.com/rstudio/rstudio/issues/5054, regression from https://github.com/rstudio/rstudio/pull/2980.
> Avoid overriding repos.conf when settings do not change to fix #5054

- src/cpp/desktop/DesktopMain.cpp
Fixes #3068
The code invoking the URL (happens inside the `prepareEnvironment` call) depends on options.scriptsPath being initialized but it wasn't at this early stage of startup. Rearranged so it is, which has nice side effect of consolidating several Windows-only blocks of code into one.
> fix launching R site when no R installed at startup on Windows

- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/application/ApplicationTutorialEvent.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
companion to https://github.com/rstudio/rstudio-pro/pull/1105
> companion to https://github.com/rstudio/rstudio-pro/pull/1105

- src/cpp/session/modules/build/SessionBuild.cpp
Closes https://github.com/rstudio/rstudio/issues/5129.
> prefer module_context::resolveAliasedPath

- src/cpp/desktop/DesktopPosixApplicationLaunch.cpp
Closes #5107. See diff for comments + rationale.
> fix for malformed Qt mouseevent

- src/cpp/r/session/RStdCallbacks.cpp
Closes https://github.com/rstudio/rstudio/issues/5108. See inline comments for rationale.
This may be worth considering for backporting, but it is a very low-level change so we'll have to think through whether we really did rely on `R_ProcessEvents()` being run here.
> call Rf_onintr directly when handling interrupts

- src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
Fixes https://github.com/rstudio/rstudio/issues/5136.
> Update required version of rsconnect

- src/cpp/session/modules/SessionErrors.cpp
- src/cpp/session/modules/SessionErrors.hpp
- src/gwt/src/org/rstudio/studio/client/common/debugging/events/ErrorHandlerChangedEvent.java
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
Fixes https://github.com/rstudio/rstudio/issues/5165.
> Use error handler type strings from user state

- src/cpp/core/include/core/r_util/RSourceIndex.hpp
- src/cpp/core/r_util/RSourceIndex.cpp
Fixes https://sentry.io/organizations/rstudio/issues/1132489057/?project=1379214.
> use lazily-initialized statics for indexer

- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectGeneralPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/BuildToolsMakefilePanel.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/BuildToolsPackagePanel.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/BuildToolsPanel.java
- associate dropdown lists in Project / General prefs pane with labels
- associate labels for various project build option textboxes
> fix labeling of controls in project options panes

- src/gwt/gwt.iml
- src/gwt/src/com/google/gwt/updatepatches.sh
- src/gwt/src/com/google/gwt/updatesources.sh
- src/gwt/src/com/google/gwt/user/client/ui/RadioButton.java
- src/gwt/src/com/google/gwt/user/client/ui/RadioButton.java.diff
- src/gwt/src/org/rstudio/core/client/widget/FieldSetPanel.java
- src/gwt/src/org/rstudio/core/client/widget/FormLabel.java
- src/gwt/src/org/rstudio/core/client/widget/HorizontalRadioPanel.java
- src/gwt/src/org/rstudio/core/client/widget/SelectWidget.java
https://github.com/rstudio/rstudio-pro/pull/1158
> companion to https://github.com/rstudio/rstudio-pro/pull/1158

- src/cpp/CMakeLists.txt
This is a follow up to the discussion this commit: 4193329
> Only disable system boost if we're not using system boost.

- src/gwt/src/com/google/gwt/updatepatches.sh
- src/gwt/src/com/google/gwt/updatesources.sh
- src/gwt/src/com/google/gwt/user/cellview/client/DataGrid.java
- will be modifying to support ARIA grid pattern, be easier to see the
changes if I first checkin the unmodified baseline (wish I had done
this with other modified GWT sources)
> capture initial snapshot of GWT 2.8.2 DataGrid.java

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetRMarkdownHelper.java
Fixes https://github.com/rstudio/rstudio/issues/5248.
> Initialize user state for R Markdown helper

- src/cpp/session/modules/SessionThemes.cpp
The variable `RS_THEME_LOCAL_HOME` specifies the path to local (per user) themes. In 1.3, we prefer the XDG paths, but this isn't strictly correct since the environment variable is more specific.
This change causes us to prefer the path set by `RS_THEME_LOCAL_HOME` over the XDG paths, if it's set. 
Fixes https://github.com/rstudio/rstudio/issues/5259, and some unit tests.
> Prefer RS_THEME_LOCAL_HOME if set

- src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java
Closes https://github.com/rstudio/rstudio/issues/5300.
> depend on roxygen2 for documentation building

- src/cpp/session/SessionMain.cpp
> remove DYLD_INSERT_LIBRARIES on session init

- src/cpp/r/include/r/RExec.hpp
- src/cpp/session/modules/SessionRUtil.cpp
Closes https://github.com/rstudio/rstudio/issues/1866.
> diagnose R code in .Rmd as UTF-8

- src/cpp/core/r_util/RTokenizer.cpp
- src/cpp/session/modules/SessionDiagnosticsTests.cpp
> do not allow newlines in user operators

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
> ignore empty lines at start, end of selection for doCommentUncomment

- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java
Closes https://github.com/rstudio/rstudio/issues/5181.
> better handle + silence 'scroll into view' errors

- src/cpp/r/R/Tools.R
- src/cpp/session/modules/SessionPackages.R
- remove an unused `keepOriginal` argument
- add in a couple `PACKAGE = "(embedding)"` usages in SessionPackages.R
> minor fixups

- src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/LintManager.java
Closes https://github.com/rstudio/rstudio/issues/5346.
> run R code diagnostics for R Markdown documents

- src/cpp/session/prefs/PrefLayer.cpp
This is a speculative fix for a Sentry crash. I couldn't reproduce the crash, but it's clear that what's happening is that pref validation is happening before prefs are read. Towards that end, the following preventative measures have been added:
1. Mutex guards around validation to ensure that a race condition can't allow this to occur.
2. Double-check that the prefs cache is loaded before we validate; if it isn't, log a warning.
Fixes #5381.
> Ensure prefs read before validation

- src/cpp/core/Error.cpp
- src/cpp/core/include/core/Error.hpp
- src/cpp/session/prefs/PrefLayer.cpp
Fixes https://github.com/rstudio/rstudio/issues/5435.
> Check for both file not found and path not found on Windows

- src/gwt/acesupport/acemode/markdown_highlight_rules.js
> tweak rule used to match horizontal rules

- src/gwt/src/org/rstudio/core/client/a11y/A11y.java
- src/gwt/src/org/rstudio/core/client/widget/ToolbarMenuButton.java
Small tweak to remove unnecessary helper method.
> use GWT setAriaExpandedState instead of doing it manually

- src/cpp/session/modules/SessionHelp.cpp
> Fixed bug where R.css was being overwritten.

- src/gwt/src/org/rstudio/core/client/widget/ScrollableToolbarPopupMenu.java
- src/gwt/src/org/rstudio/core/client/widget/ThemedPopupPanel.java
I like this better than what I did. OOP is a headache. 🥇 
https://github.com/rstudio/rstudio/pull/5588 for reference
fixes #1760, fixes #1794, fixes #2330
> simplified version of scrolling panel fix

- src/cpp/core/include/core/Algorithm.hpp
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/tex/SessionCompilePdf.cpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CompilePdfPreferencesPane.java
Closes https://github.com/rstudio/rstudio/issues/2788.
> use tinytex to compile .tex files

- src/cpp/session/modules/SessionCodeTools.R
> pass along HTTPUserAgent when installing dependencies

- src/cpp/session/modules/SessionRParser.cpp
> handle glue strings in diagnostics system

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
> add access keys to main menu commands that don't have them

- src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
- src/gwt/src/org/rstudio/core/client/polyfill/FastestSmallestTextEncoderDecoder.java
- src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java
Because ScriptInjector is unreliable. (hat tip to @gtritchie for pointing this out)
> add helper for loading JavaScript from resource

- src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
Closes #5629.
See comments for rationale on the somewhat surprising gymnastics done to make this work.
> save + restore Help Pane scroll position

- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/studio/client/application/ui/GlobalToolbar.java
- src/gwt/src/org/rstudio/studio/client/application/ui/ProjectPopupMenu.java
- src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
- ProjectPopupMenu exists in both the toolbar, and in the menubar (server only)
- Only one is ever visible at a time depending on toolbar visiblility
- I added the same ID to both in previous change, causing an accessibility
violation
- Made the IDs unique, also misc. Java cleanup (Lambdas, indenting,
removing wildcard imports)
> fix duplicate element IDs on Project dropdown

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
> save doc before re-opening with encoding

- NEWS.md
- src/cpp/session/modules/SessionRMarkdown.R
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
> use output path directly for self-contained books

- NEWS.md
- src/gwt/acesupport/acemode/r.js
> Continue Plumber comment blocks on successive lines

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java
Closes https://github.com/rstudio/rstudio/issues/3317.
> enable comment / uncomment for YAML documents

- src/gwt/src/org/rstudio/core/client/patch/SubstringDiff.java
Closes https://github.com/rstudio/rstudio/issues/5689.
> ensure head, tail align properly on UTF-8 characters

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Closes https://github.com/rstudio/rstudio/issues/5696.
> only use Meta (Command) for xcv actions on macOS

- src/cpp/core/gwt/GwtLogHandler.cpp
- src/cpp/shared_core/Error.cpp
- src/cpp/shared_core/Logger.cpp
- src/cpp/shared_core/include/shared_core/Logger.hpp
> Make implementation of Error.asString match the old implementation

- src/cpp/core/file_lock/FileLock.cpp
- src/cpp/core/include/core/FileLock.hpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/SessionSourceDatabaseSupervisor.cpp
> allow for link-based session locks on desktop

- Jenkinsfile
- docker/jenkins/Dockerfile.centos8-x86_64
> Change RHEL8 builds from fedora28 to centos8

- src/cpp/r/RSexp.cpp
> check for overflow when casting JSON to R integer vector

- src/gwt/src/org/rstudio/core/client/MessageDisplay.java
- src/gwt/src/org/rstudio/studio/client/common/impl/WebTextInput.java
- src/gwt/src/org/rstudio/studio/client/common/vcs/AskPassManager.java
Closes https://github.com/rstudio/rstudio/issues/4058.
> avoid hiding input for username in askpass

- src/cpp/session/modules/SessionDataImportV2.R
Closes https://github.com/rstudio/rstudio/issues/5265.
> fix viewer data subsetting

- NEWS-1.2-patch.md
- src/cpp/r/include/r/session/RSession.hpp
- src/cpp/r/include/r/session/RSessionState.hpp
- src/cpp/r/session/RSessionState.cpp
- src/cpp/r/session/RSuspend.cpp
- src/cpp/session/SessionOptions.cpp
- src/cpp/session/SessionSuspend.cpp
- src/cpp/session/include/session/SessionConstants.hpp
- src/cpp/session/include/session/SessionOptions.hpp
> Backport env-var save blacklist 

- src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneConfig.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialTab.java
Brings the Tutorial tab to life, albeit currently with no content. Only displayed in devmode for now.
> implement initial for Tutorial pane

- src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
- Fixes #3449
- Simplest fix, just fire equivalent command for next/prev tab as those already handle this problem
- Side effect, previously mousewheel didn't wrap, now it behaves the same as the keyboard doc tab navigation, subject to the user preference "Wrap around when navigating to previous/next tab"
- Had this marked as an accessibility issue, but it isn't, really, since the keyboard navigation was already working correctly
> fix mousewheel scrolling of document tabs for reordered tab

- src/cpp/session/resources/dependencies/r-packages.json
> install binary keyring package

- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRdDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRdDialog.ui.xml
- also add "..." to label for command that brings up this dialog
> associate labels and controls in NewRdDialog

- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobQuitControls.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobQuitControls.ui.xml
- Associate listbox with label
- Include item count in listbox label
> Fix accessibility of job-quit-warning dialog

- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/widget/DirectoryChooserTextBox.java
- src/gwt/src/org/rstudio/core/client/widget/FileChooserTextBox.java
- src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
- src/gwt/src/org/rstudio/studio/client/common/vcs/ignore/IgnoreDialog.java
- src/gwt/src/org/rstudio/studio/client/projects/model/ProjectTemplateWidget.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/ExistingDirectoryPage.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewDirectoryPage.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/VersionControlPage.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectCompilePdfPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectEditingPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/BuildToolsCustomPanel.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/BuildToolsPanel.java
- src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdFileOption.java
- src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PublishingPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/SourceControlPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionPreInstallOdbcHost.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileUploadDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobLauncherControls.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/InstallPackageDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewPlumberAPI.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewShinyWebApplication.java
Open source companion to https://github.com/rstudio/rstudio-pro/pull/1382
> add uniqueIds for TextBoxWithButton widgets

- src/cpp/session/CMakeLists.txt
> Install supporting tutorial files

- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
- logo in upper-left of UI which serves as a link to homepage in Pro
- addresses a TODO in the Selenium automation
- FYI @rich-rstudio
> assign unique-id to the RStudio Logo anchor

- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/modules/SessionDependencies.cpp
- src/cpp/session/modules/SessionRenv.cpp
> install dependencies with renv::install() in renv projects

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java
> remove fold check for background highlighter

- src/cpp/session/prefs/Preferences.cpp
This change fixes an issue in which changing the Shiny viewer type in the UI did not always result in a corresponding change to the actual viewer type.
The problem is somewhat fundamental; we rely on pref change events to let us know when users have changed prefs. These events fire consistently when a pref has changed value *in a particular layer*. However, prefs can also "change value" by being added or removed in a particular layer (exposing or obscuring the value in the layer beneath). The fix is to fire events for these kinds of value changes too. 
Fixes https://github.com/rstudio/rstudio/issues/6165.
> Emit change events for added/removed prefs

- src/cpp/core/FileInfo.cpp
- src/cpp/core/include/core/FileInfo.hpp
- src/cpp/core/system/file_monitor/Win32FileMonitor.cpp
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/include/session/projects/SessionProjects.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/projects/SessionProjectContext.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
> don't monitor renv / packrat libraries

- src/cpp/tests/testthat/test-environment.R
Be good for someone to double-check that this is happening for everyone, or if it's a quirk of my environment.
- Fixes #5776
- Caused by https://github.com/rstudio/rstudio/commit/832214a489e8442c6bd885de36f230612021dd9e#diff-2fa9f27b5678b24e1b9f78bfd9aa7771
> fix failing R environment unit test

- src/cpp/core/system/PosixSystem.cpp
- src/cpp/core/system/file_monitor/MacFileMonitor.cpp
- src/cpp/shared_core/include/shared_core/system/PosixSystem.hpp
- src/cpp/shared_core/system/PosixSystem.cpp
This PR fixes a build issue introduced in a recent change to shared_core (#6132) on OSX.
> Fixes the IDE build on OSX

- src/cpp/session/resources/schema/user-prefs-schema.json
Fixes #6215 
Seems to have done the trick.
> fix warning about missing default

- src/cpp/session/modules/SessionUserPrefsMigration.cpp
In RStudio 1.2, user preferences (such as themes) were stored alongside internal per-user state values. RStudio 1.3 includes code to migrate user preferences, but not user state. 
While most user state values are not worth writing migration code for, there's a major exception -- the context identifier (context ID). This value is used (among other things) as a key for storing the set of open files, so not migrating it means that an upgrade will cause you to start all new project sessions with no open files. 
The fix is to read the context ID from the old settings file and write it to the new user state system. Since I was in the code I added migration for a handful of other lower-value (but useful) user state values, too. 
Fixes https://github.com/rstudio/rstudio/issues/6227.
> Migrate user state, including context identifier

- src/cpp/session/modules/SessionDependencies.cpp
We currently pass `lock = TRUE` to `install.packages` when installing packages in the background. Unfortunately this option is only valid for some kinds of package installations (depending on the underlying function used to install the package), and results in errors otherwise.
This change uses an option to change the locking behavior, which will just be ignored safely when it isn't supported. 
Fixes https://github.com/rstudio/rstudio/issues/6223.
> Lock via option when installing packages in the background

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/www/docs/keyboard.htm
> adjust main menu shortcuts to fix conflicts

- src/cpp/session/modules/clang/RCompilationDatabase.cpp
Closes https://github.com/rstudio/rstudio/issues/4873.
> ensure quiet output when calling find.package

- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Closes https://github.com/rstudio/rstudio/issues/6231.
> fix issue where console history scrolled on focus

- src/cpp/desktop/DesktopPosixApplicationLaunch.cpp
> don't re-fire mouse events with no main button

- src/cpp/session/modules/SessionBreakpoints.R
- src/gwt/.gitignore
Closes https://github.com/rstudio/rstudio/pull/5761.
> fix typo in unquote invocation

- src/cpp/session/modules/connections/ConnectionHistory.cpp
Band-aid for https://github.com/rstudio/rstudio/issues/6336.
Given that we don't have a reproducible example and (AFAIK) I'm the only one who's hit the problem, it may be better to take this for v1.4.
> drop nulls in connection history db

- src/cpp/session/SessionModuleContext.cpp
Closes https://github.com/rstudio/rstudio/issues/6376.
> better handle error when adding tinytex to PATH

- src/cpp/session/resources/dependencies/r-packages.json
Closes https://github.com/rstudio/rstudio/issues/6418.
> tutorials depend on rstudioapi

- src/gwt/acesupport/acemode/rmarkdown_highlight_rules.js
> Highlight C and cpp code as C

- src/cpp/session/modules/SessionErrors.R
Closes https://github.com/rstudio/rstudio/issues/6464.
> avoid using deparse when checking call

- src/gwt/panmirror/src/editor/src/api/basekeys.ts
Remove repetition in basekeys.ts
> DRY basekeys.ts

- src/cpp/r/R/Diagnostics.R
Part of https://github.com/rstudio/rstudio/issues/6483.
> fix diagnostics report for Windows

- NEWS.md
- src/cpp/session/SessionModuleContext.cpp
Closes https://github.com/rstudio/rstudio/issues/2597.
> check for fork in package event callbacks

- src/cpp/session/modules/SessionShinyViewer.R
- src/cpp/session/modules/SessionShinyViewer.cpp
Closes https://github.com/rstudio/rstudio/issues/6509.
> refresh potentially stale viewer fn definitions

- NEWS-1.3.md
If and when we do another 1.3 build.
> acknowledgments in NEWS

- src/cpp/desktop/DesktopMain.cpp
Fixes https://github.com/rstudio/rstudio/issues/6501.
> opt-in to Qt AltGr detection

- src/cpp/session/modules/SessionRenv.R
Closes #6522.
Note: candidate for backport to v1.3.
> invoke renv::init() in subproc

- src/cpp/session/modules/SessionFind.cpp
Fixes #6519 
Updated error handling so that one json array of error strings is sent per every result found, even if no errors were found.
> Fix bug where replace errors did not appear with the correct file

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
> add menu access key to rename in scope command

- dependencies/common/install-pandoc
- dependencies/tools/upload-pandoc.sh
- dependencies/windows/install-dependencies.cmd
- src/cpp/session/CMakeLists.txt
Addresses https://github.com/rstudio/rstudio/issues/6548
> Update Pandoc to v2.9.2.1

- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
> fix scroll for multiline console input

- src/cpp/desktop/DesktopMain.cpp
Closes https://github.com/rstudio/rstudio/issues/3781.
> force software rendering when using nouveau driver w/ older Qt

- src/cpp/monitor/events/Event.cpp
- src/cpp/monitor/include/monitor/events/Event.hpp
- src/cpp/server/CMakeLists.txt
- src/cpp/server/ServerLoginPages.cpp
- src/cpp/server/ServerLoginPages.hpp
- src/cpp/server/ServerPAMAuth.cpp
- src/cpp/server/ServerPAMAuthOverlay.cpp
- src/cpp/server/auth/ServerAuthCommon.cpp
- src/cpp/server/auth/ServerAuthHandler.cpp
- src/cpp/server/include/server/auth/ServerAuthCommon.hpp
- src/cpp/server/include/server/auth/ServerAuthHandler.hpp
- src/gwt/www/templates/encrypted-sign-in.htm
Extract non-PAM related logic to other files
> Authentication Refactoring

- src/cpp/core/system/System.cpp
Fixes https://github.com/rstudio/rstudio-pro/issues/1562.
> Fix issue with checking logger type

- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Closes https://github.com/rstudio/rstudio/issues/6604.
> further refine Ace behavior in shell widget

- src/gwt/src/org/rstudio/core/Core.gwt.xml
- src/gwt/src/org/rstudio/core/client/theme/ThemeFonts.java
- src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
- src/gwt/src/org/rstudio/studio/RStudioTests.gwt.xml
- src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
Fixes https://github.com/rstudio/rstudio/issues/6613.
> Use test mock font loader; re-enable JobsList tests

- src/cpp/shared_core/Logger.cpp
Based on feedback from Karl in https://github.com/rstudio/rstudio-launcher-plugin-sdk/pull/11.
> Add braces for LOCK blocks in Logger

- src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java
Fixes #6594
User found another dictionary that causes load issues.
> add lt_LT_new to dictionary blacklist

- NEWS.md
- src/cpp/r/session/graphics/RShadowPngGraphicsHandler.cpp
Closes https://github.com/rstudio/rstudio/issues/2214.
> ensure plot directory before creation

- src/gwt/src/org/rstudio/core/client/theme/WindowFrameButton.java
> prevent double-click from triggering weird panel behavior

- src/cpp/session/modules/rmarkdown/NotebookPlots.cpp
Speculative fix for https://github.com/rstudio/rstudio/issues/6349.
> Do not attempt to read device list after error

- src/cpp/core/r_util/RToolsInfo.cpp
> ensure RTOOLS40_HOME is set

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
This is a better version of the previous fix for styling in https://github.com/rstudio/rstudio/pull/6733.
While this seems to be a bug in IE11 / Edge, I haven't been able to distill a reproducible example.
> work around IE CSS styling issue

- src/cpp/tests/testthat/test-codetools.R
Fixes https://github.com/rstudio/rstudio/issues/6773.
> don't depend on exact format of deparsed expression

- src/gwt/src/org/rstudio/core/client/events/HighlightEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/UserInterfaceHighlighter.java
Closes #6650
This PR adds a parameter `callback` to `rstudioapi::highlightUi`  to accept a R function. When focus is moved to the highlighted area, the R function is executed.
> Callback for rstudioapi::highlightUi

- src/gwt/src/org/rstudio/studio/client/workbench/UserInterfaceHighlighter.css
- src/gwt/src/org/rstudio/studio/client/workbench/UserInterfaceHighlighter.java
Closes #6651 
This PR updates the styles used by `rstudioapi::highlightUi` to increase the animation and noticeability of highlight boxes. It include a static option used when User Preferences are set up for Reduced Motion.
> Make highlights more noticeable

- src/cpp/CMakeLists.txt
> Cause a compile error for missing return statements

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/DocUpdateSentinel.java
Closes https://github.com/rstudio/rstudio/issues/6895. See associated issue for discussion.
> suspend change detection handlers during document init

- src/cpp/r/R/Tools.R
Closes https://github.com/rstudio/rstudio/issues/6946.
> ensure package attached before registering replace hook

- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionRCompletions.R
Closes https://github.com/rstudio/rstudio/issues/6942.
> ensure masked function objects are resolved correctly

- src/cpp/session/modules/SessionCodeTools.R
Closes https://github.com/rstudio/rstudio/issues/6989.
As a bonus, this will mean that function lookup for RStudio's internal functions (e.g. `.rs.foobar`) will work again.
> fix function lookup for objects on search path not within namespace

- src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenu.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/cpp/CppCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/cpp/CppCompletionPopupMenu.java
Closes https://github.com/rstudio/rstudio/issues/6971.
~Candidate for v1.3-patch backport.~ Affects v1.4 only; not a candidate for backport.
> cpp completion manager needs to explicitly handle keys

- src/gwt/src/org/rstudio/core/client/BrowseCap.java
- src/gwt/src/org/rstudio/core/client/Version.java
- src/gwt/src/org/rstudio/core/client/command/KeyCombination.java
Closes https://github.com/rstudio/rstudio/issues/6129.
Candidate for v1.3-patch backport.
> don't use key property for older Qt

- src/gwt/panmirror/src/editor/src/api/widgets/select.tsx
- src/gwt/panmirror/src/editor/src/api/widgets/text.tsx
- src/gwt/panmirror/src/editor/src/behaviors/insert_symbol/insert_symbol-styles.css
-> Text & Select Input properly handle themed colors
-> Height of search box and category filter match
> Fix Appearance Bugs in Insert Symbol

- src/gwt/src/org/rstudio/studio/client/palette/ui/CommandPalette.java
Fixes https://github.com/rstudio/rstudio/issues/7056.
> Prevent Enter from leaking out of the Command Palette

- src/cpp/session/modules/SessionRmdNotebook.R
Closes #6932.
Previously, we somewhat eagerly read content within the Notebook cache, with the expectation that we might need it when forming Notebook output. Now, we only read files which we have a known output handler for.
(Some handlers do rely on data within sidecar files, but those handlers always re-read the data from disk anyhow and so we don't need to eagerly read those here either.)
> avoid readChar warnings when generating HTML notebook

- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/StanCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/r/SignatureToolTipManager.java
Closes https://github.com/rstudio/rstudio/issues/7154.
> fix issue with Stan tooltips showing in R chunks

- src/cpp/session/SessionConsoleInput.cpp
- src/cpp/session/resources/dependencies/r-packages.json
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java
Closes https://github.com/rstudio/rstudio/issues/5904.
> further refine Python execution semantics

- src/cpp/session/modules/SessionPatches.R
Band-aid for https://github.com/rstudio/rstudio/issues/6692.
> ensure sequential setup for parallel clusters

- src/gwt/acesupport/acemode/r_highlight_rules.js
- src/gwt/acesupport/acemode/rainbow_paren_highlight_rules.js
- src/gwt/acesupport/acemode/token_cursor.js
Closes https://github.com/rstudio/rstudio/issues/7212.
> disable paren token merging

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Closes https://github.com/rstudio/rstudio/issues/7223.
> fix active document check

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
This is a second attempt to fix https://github.com/rstudio/rstudio/issues/6268. The first attempt jiggled the z-index, which QA found didn't reliably invalidate the region (so it still didn't paint reliably). This updated version uses a no-op `translate` instead, and defers the invalidation until the end of the event loop. 
Fixes https://github.com/rstudio/rstudio/issues/6268.
> Use a transform instead of z-index to invalidate preview

- src/cpp/r/RSexp.cpp
Speculative band-aid for #7231.
> check for nullptr in isCallToNSEFunction

- NEWS.md
- src/gwt/acesupport/acemode/python.js
- src/gwt/acesupport/acemode/rmarkdown.js
> tweak Python indentation rules + enable in R Markdown documents

- src/cpp/r/include/r/session/RSession.hpp
- src/cpp/r/session/graphics/RGraphicsDevDesc.cpp
- src/cpp/r/session/graphics/RGraphicsDevDesc.hpp
- src/cpp/r/session/graphics/RGraphicsDevice.cpp
- src/cpp/r/session/graphics/RGraphicsUtils.cpp
- src/cpp/session/include/session/SessionOptions.gen.hpp
Closes https://github.com/rstudio/rstudio/issues/7253.
> support R graphics engine version 13

- src/gwt/panmirror/src/editor/src/marks/cite/cite-popup.css
- src/gwt/panmirror/src/editor/src/marks/cite/cite-popup.tsx
-> Preserve hanging indent class name
-> Only apply margin to links that we add to citation (otherwise we may mangle CSL specified formatting of links)
> Cite Popup Formatting Tweaks

- src/cpp/session/modules/SessionDataViewer.R
Closes https://github.com/rstudio/rstudio/issues/6869.
> further refine formatting of integer64 columns

- src/cpp/session/modules/NotebookPlots.R
Closes https://github.com/rstudio/rstudio/issues/7313.
Note: use https://github.com/rstudio/rstudio/pull/7315/commits/e6c23c5c3a617fde988de5844a6570836937f7d4 for cleaner diff.
> properly open ragg graphics device in notebooks

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java
> Update rainbow paren colors, move setting in pref pane

- src/cpp/session/modules/SessionPackrat.R
- src/cpp/session/modules/SessionTutorial.R
Closes https://github.com/rstudio/rstudio/issues/7265.
> avoid loading rmarkdown, packrat packages when unnecessary

- scripts/README.md
- scripts/clean-rstudio
- scripts/clean-rstudio.bat
Adding utility scripts I use all the time for blowing away RStudio state on Posix or Windows.
Do you think these are appropriate to live in the repo? I have been keeping them in my own repo and cloning from there, but these seem useful to have widely available.
> utility scripts for cleaning up RStudio state (desktop and server)

- src/cpp/desktop/CMakeLists.txt
- src/cpp/desktop/synctex/rsinverse/CMakeLists.txt
- src/cpp/desktop/urlopener/CMakeLists.txt
> use documented CMake APIs for declaring win32 executables

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
Closes https://github.com/rstudio/rstudio/issues/7317.
> scroll cursor into view on SetSelectionRanges event

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/MainSplitPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
Adds `Ctrl + F7` as a shortcut to create a new source column.
> Add shortcut to create new source column

- src/cpp/shared_core/FileLogDestination.cpp
Fixes a bug where failing to rotate a log file could cause a crash. We had plumbed up the `rotateLogFile` to return a `bool` indicating whether or not it was safe to actually log after the call, but were never checking the return code.
Fixes https://github.com/rstudio/rstudio-pro/issues/1779
> Fix log file rotation failure crash

- src/gwt/acesupport/acemode/r_highlight_rules.js
This PR adds highlight rules for R's raw strings.
We accomplish this via "permissive" regular expressions, which capture all forms that could be used to begin or end an R raw string. When the start of an R raw string is matched, we compute the suffix required to finish that raw string; when the end of an R raw string is matched, we validate that it is the expected raw string end.
Closes https://github.com/rstudio/rstudio/issues/6845.
> support tokenization of raw R strings

- src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.R
Closes https://github.com/rstudio/rstudio/issues/3731.
> trim common indent in indented chunks

- src/cpp/r/session/graphics/RGraphicsPlotManager.cpp
- src/cpp/r/session/graphics/RGraphicsUtils.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlotSizeEditor.java
Closes https://github.com/rstudio/rstudio/issues/6679.
> support saving plots with agg

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
> Add missing menu access keys

- src/cpp/shared_core/system/User.cpp
Ran across this in support ticket 50567; currently if a user mistypes their username, it appears in the logs as a permission denied error. 
```
ERROR system error 13 (Permission denied) [description: Failed to get user details., user-value: <user>
```
This is very misleading as it suggests that the problem is that we don't have access to the user's details, and also makes it impossible for us to distinguish between this problem and an actual permissions error. 
This change logs these errors as more benign `ENOENT` instead, and uses a different error message so that we can distinguish between "user not found" and "permission denied" errors.
> Don't log missing user as "permission denied"

- dependencies/common/install-crashpad
- e.g. via `sudo ./install-crashpad osx`
> fix install-crashpad so it can install pre-built macOS binaries

- src/gwt/www/templates/encrypted-sign-in.htm
> remove duplicate element IDs on sign-in page

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBar.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarElement.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarElementWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarPopupMenu.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarPopupRequest.java
Resave source files I'm about to edit, plus some mechanical cleanup via IntelliJ. To reduce noise in upcoming PR diff.
IntelliJ refactorings/strip whitespace on save.
Purely source-code cleanup, nothing to test.
> mechanical cleanup of code I'm about to touch

- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
- Fixes #7584
Terminal would become unresponsive (not responding to typing) after another tab was opened or closed in the Console panel (e.g. Jobs, Find in Files). This was a regression in 1.4 caused by #7275.
The core problem was that when another tab is added or removed from the Console region, the Terminal widget gets temporarily unloaded (then reattached), and I had added code in `onUnload` to remove the event handler for dispatching typing. This was not necessary, so I have removed it.
Additionally, there is a Javascript exception being thrown in this situation (not new, been around a while); turns out it wasn't causing any known problems, but taking the opportunity to prevent it by making sure I don't try to resize the terminal when it's not in a sizable state.
Create some terminal …
> Prevent terminal from becoming unresponsive after console panel tabs added or removed

- src/cpp/server/ServerPAMAuth.cpp
Port of https://github.com/rstudio/rstudio/pull/7628
See PR above.
> v1.3 port of auth-none fix

- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneConfig.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
- mechanical source cleanup
Source code cleanup
While reading some source, cleaned up some string comparisons flagged by Intelli-J.
Nothing to test.
> change some string comparisons to use StringUtil.equals

- src/gwt/src/org/rstudio/studio/client/common/filetypes/events/OpenSourceFileEvent.java
> Fix regression where opening a source file wouldn't move the cursor

- src/cpp/core/system/file_monitor/Win32FileMonitor.cpp
RStudio occasionally crashes after a UI refresh (Right Click -> Reload), which we would prefer not doing.
The crash appears to occur in the file monitor's completion routine, likely running after the associated context was deleted. The fix here is to more carefully manage the lifetime of the context object, and to allow the completion handler itself to delete the context if necessary.
Follow steps in https://github.com/rstudio/rstudio/issues/7637 to reproduce, but note that the issue is quite finicky -- in my cases, I could only reproduce maybe 20% of the time.
Closes https://github.com/rstudio/rstudio/issues/7637.
> be more careful when cleaning up file monitor contexts

- src/cpp/server/ServerSessionProxy.cpp
- src/cpp/server_core/UrlPorts.cpp
- src/cpp/server_core/UrlPortsTests.cpp
- src/cpp/server_core/include/server_core/UrlPorts.hpp
Bring changes to open source.
N/A
N/A
> open source companion commit for rstudio/rstudio-pro#1910

- src/gwt/www/templates/encrypted-sign-in.htm
1.4 backport for https://github.com/rstudio/rstudio-pro/pull/1825
N/A
N/A
> open source companion commit for rstudio/rstudio-pro#1925

- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputCodec.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindResultContext.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/events/FindInFilesEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/events/ReplaceProgressEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/model/FindResult.java
Minor source code cleanup via Intelli-J of some files related to the Find in Files feature
Let IntelliJ make some simple cleanup changes.
Purely source-code cleanup, nothing specific to test here other than regular usage of the Fine in Files feature.
> minor mechanical cleanup of some find-in-files Java sources

- src/cpp/session/modules/SessionRenv.R
- src/cpp/tests/testthat/test-document-apis.R
- src/cpp/tests/testthat/test-renv.R
Unit tests were broken.
Make them not broken.
No QA notes.
> unit test fixups

- NEWS.md
- src/cpp/core/include/core/r_util/RPackageInfo.hpp
- src/cpp/core/r_util/RPackageInfo.cpp
- src/cpp/session/modules/SessionHelp.cpp
Closes https://github.com/rstudio/rstudio/issues/6871.
Straightforward read + pass-through of `RdMacros` from package `DESCRIPTION` file.
Test via notes in https://github.com/rstudio/rstudio/issues/6871.
> support use of RdMacros in preview

- src/cpp/core/r_util/RSessionLaunchProfile.cpp
> open source companion commit for rstudio/rstudio-pro#1956

- src/cpp/server/auth/ServerAuthCommon.cpp
> open source companion commit for rstudio/rstudio-pro#1957

- src/cpp/server_core/ServerDatabase.cpp
- src/cpp/server_core/include/server_core/ServerKeyObfuscation.hpp
> open source companion commit for rstudio/rstudio-pro#1972

- NEWS.md
- src/cpp/core/r_util/RUserData.cpp
- src/cpp/core/system/Xdg.cpp
Open source companion to https://github.com/rstudio/rstudio-pro/pull/1955
> Specify config and data paths directly with RSTUDIO_DATA_HOME, etc.

- src/cpp/core/http/Response.cpp
> companion commit for rstudio/rstudio-pro#1991

- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
Fixes #7880 
`Focus Next/Prev Pane` should be able to navigate to the Console pane even when the console is the only tab open in that pane. It should also skip over a tab panel if there are no tabs open in that panel.
When Console is the only panel within its pane it doesn't follow its typical convention of being a WorkbenchTab. This panel cannot be closed but makes the panel appear empty. Instead of an exception, we need to default to displaying the Console.
In fixing this I realized that attempting to run these commands to navigate to an empty tabset threw a similar exception. I updated the code so it will now skip over empty tabsets and focus on the next/prev pane in reference to that the empty panel. 
Text the Focus Next/Prev Pane command with a variety of different tabs open and …
> Prevent exceptions when attempting to focus a pane without tabs

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Remove extra white space that was preventing our java code from building.
> Remove extra white space

- src/gwt/src/org/rstudio/core/client/command/BaseMenuBar.java
- Fixes #6197
For a keyboard-only user (including screen reader users) it is very inconvenient that after invoking and using the RStudio Server main menu via keyboard shortcuts, keyboard focus is usually left on the page body or some other location unrelated to where it was when menu was invoked.
Behavior should be more like a desktop application, where once main menu is dismissed, focus returns to where it was before.
When Server main menu is opened via keyboard shortcuts, capture the current focus location. Detect if the one of the following happens to restore focus to that location:
- a command is fired by picking an item from the menus OR by using a keyboard shortcut while the menus were displayed
- user cancels out of the menus via ESC key (each expanded submenu requires an ESC press …
> Restore keyboard focus after invoking main menu via shortcuts

- src/gwt/acesupport/acemode/r_code_model.js
- src/gwt/test/autoindent_test_r.html
Closes https://github.com/rstudio/rstudio/issues/7904.
Handle nested control flow statements in the indentation engine.
Test via cases described in https://github.com/rstudio/rstudio/issues/7904.
> handle nested, braceless control flow statements

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
#7969 caused build issue because of an error in `UserPrefsAccessor.java`. Rerunning `generate-prefs` fixed the issue.
> Run generate-prefs

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Closes https://github.com/rstudio/rstudio/issues/8032.
Check for active selection, and either replace selection or insert text based on that state.
Test via notes in https://github.com/rstudio/rstudio/issues/8032.
> only replace selection if there is an active selection

- src/cpp/session/modules/SessionReticulate.R
Previously, RStudio defined a function called `View()` in the Python main module, that could be invoked to view objects using RStudio's object explorer / data viewer. This unfortunately caused the issue described in https://github.com/rstudio/rstudio/issues/8065, where calling `reticulate::source_python()` would effectively overwrite R objects in the session with those from the Python module -- including the View hook.
Rather than implement `View()` via a function in the main module, instead use a REPL hook to detect calls to `View()` and route those to the right place. (Note that this implies that "clever" usages of View will not work, but since this is purely an RStudio concept and cannot work in a regular R session I think that is okay.) …
> avoid defining View function in Python main module

- src/cpp/session/modules/SessionHelp.R
- src/cpp/session/modules/SessionRCompletions.R
Fixes https://github.com/rstudio/rstudio/issues/7060#issuecomment-712319468.
Ensure `package` is resolved properly in calls to `.rs.getHelp()` that don't provide it.
Test via notes in https://github.com/rstudio/rstudio/issues/7060#issuecomment-712319468.
> fix-up autocompletion + help regressions from recent PR

- src/cpp/session/modules/SessionDataViewer.R
Closes https://github.com/rstudio/rstudio/issues/8170.
Adapt call of `rs_jumpToFunction` to new signature, from https://github.com/rstudio/rstudio/commit/bdf94052c87d8de2db4dd529a4ee5fe0db6fa7f9.
Test via notes in https://github.com/rstudio/rstudio/issues/8170.
> adapt to change in rs_jumpToFunction signature

- src/cpp/server/ServerSessionManager.cpp
- src/cpp/session/SessionClientInit.cpp
- src/cpp/session/session-options.json
> commit for rstudio/rstudio-pro#2100 and rstudio/rstudio-pro#2101

- src/gwt/panmirror/src/editor/src/behaviors/find.ts
This change addresses an issue in which the editor doesn't scroll to reveal the current match during a Find operation. 
Fixes https://github.com/rstudio/rstudio/issues/8298.
There are two major challenges here:
1. The search result may not be present in the DOM yet (the Ace editor doesn't render it until its next render loop)
2. The search result may not be a direct child of container we need to scroll
So, to address them:
1. If the search result hasn't surfaced in the DOM yet, use a `MutationObserver` to wait for it to appear, then scroll to it.
2. If the search result is not a direct child of the scroll container, compute its position inside the container and use that as an offset.
Test via notes in #8298.
> Ensure current find result/match is visible in visual mode

- src/gwt/panmirror/src/editor/src/editor/styles/styles.css
Fixes https://github.com/rstudio/rstudio/issues/8343. 
Amend the CSS style rules for the code editor to ensure that it clears floats.
Test via notes in #8343.
> clear floats around code editor

- src/gwt/panmirror/src/editor/src/marks/cite/cite-commands.ts
When we insert the citation, this will now check whether a cite mark is already active. If it is, we will skip inserting the wrapper (e.g. `[` and `]`) and cite mark. Note that we skip inserting the wrapper even if the user requests it since it is nonsensical to nest cite marks in that way.
fixes @rstudio/issues#8337
If the user uses in the Insert Citation command from within an existing citation, we should not insert the wrapping `[]` and cite mark. 
Look to see whether a cite mark is active and skip the wrapper and cite mark if we're already inside a cite.
Originated here:
https://community.rstudio.com/t/mechanism-to-check-for-duplicate-citations-while-adding-citations-in-the-preview-releases/87335/4
> Support Insert Citation inside Existing Citation

- docker/jenkins/notarize-release.sh
Fixes https://github.com/rstudio/rstudio/issues/8367.
Retry after receiving this status from Apple instead of giving up.
Internal build tooling affected only; no QA necessary on this change.
> Tolerate notarization status -1011

- src/gwt/acesupport/acemode/python.js
Use auto-outdent to fix the indentation of certain lines as the user types -- in particular, when insertion of `else` would require out-denting to match the indentation of a matching `if`. Similarly for `except` and `try`.
Check for outdenting on `:` insertion and space insertion, and handle outdent by replacing that line's indent with the matching previous line's indent.
Test that outdenting works as expected. Try typing some of the sample code at:
https://docs.python.org/3/tutorial/errors.html
https://docs.python.org/3/tutorial/controlflow.html
Closes #8178. Not for 1.4.
> implement python auto-outdent

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java
Closes https://github.com/rstudio/rstudio/issues/8407.
Surround code selections that contain comments or newlines with newlines.
Test via notes in https://github.com/rstudio/rstudio/issues/8407.
> handle comments when profiling selection

- src/gwt/panmirror/src/editor/src/api/emojis-all.ts
- src/gwt/panmirror/src/editor/src/behaviors/insert_symbol/insert_symbol-emoji-skintone.tsx
- src/gwt/panmirror/src/editor/src/behaviors/insert_symbol/insert_symbol-grid-cell.tsx
- src/gwt/panmirror/src/editor/src/editor/editor-theme.ts
- src/gwt/panmirror/src/editor/src/marks/emoji/emoji-completion.tsx
- src/gwt/panmirror/src/editor/src/marks/emoji/emoji.ts
- src/gwt/panmirror/src/editor/tools/generate-symbols.ts
Visual mode renders text (including emoji) using a proportional font. This allows emoji to render at varying width, which can cause issues for certain emoji (e.g. the keycap emoji):
This fix switches rendering to use of a fixed width font which should make the spacing consistent:
The visual editor uses a fixed width font to render the emoji. In addition, I've updated other UI that displays emoji (completion, insert emoji dialog) to also use the fixed width font. Review the emoji rendering and exclude any emoji that don't render well using the new fixed width font (just a few).
This fix should address rendering of emoji in visual mode as well as the supporting UI. It also switches the rendering of symbols in the insert symbol dialog to use a fixed width font (since the grid is shared …
> Fix Inconsistent Emoji Spacing

- src/gwt/panmirror/src/editor/src/api/rmd.ts
This change addresses an issue in which accidentally pasting a whole chunk (delimiters and all) into an existing visual mode chunk can corrupt the document.
Closes #8452.
Ideally we'd have more fault tolerance in the parser (so the document could not become corrupt), but that would involve a much more ambitious change than is possible at this point in the release. So, instead, we treat the symptoms: when we're generating Markdown, we skip over chunk delimiters inside chunks to avoid the problematic nesting.
Note that this change *only* addresses the easiest way to get yourself into this situation (pasting chunk delimiters into a visual mode chunk). It does not address the underlying issue, and you will still see trouble if you start off with a document that *already* contains …
> Remove unintended chunk delimiters from visual chunk code

- src/gwt/panmirror/src/editor/src/api/wrap.ts
Fixes https://github.com/rstudio/rstudio/issues/8561
> don't perform sentence wrapping for bookdown text references

- src/cpp/session/modules/tex/SessionCompilePdf.cpp
We added the ability to use [tinytex](https://yihui.org/tinytex/) a while back, when compiling standalone `.tex` files. This PR extends that to also work with the `.tex` files rendered from a Sweave (`.Rnw`) document.
Relatively straight-forward application + use of the existing `runTinytex()` function; now used to render the `.tex` file generated after weave.
Ensure that the `tinytex` R package is installed and in use:
```
options(timeout = 3600)
library(tinytex)
tinytex::install_tinytex()
```
Ensure that you've configured RStudio to use tinytex when rendering `.tex` files:
Then try creating a `.Rnw` document, and then rendering it. For example:
`````
\documentclass{article}
\begin{document}
<<>>=
print(1 + 1)
@
\end{document}
`````
Confirm that the rendered PDF is opened after …
> also use tinytex when compiling .Rnw-generated .tex files

- src/cpp/server/ServerSessionManager.cpp
Fix RStudio Server development builds on macOS.
Pass along `DYLD_INSERT_LIBRARIES` when launching the `rsession` process in development server builds, as we do on desktop.
No QA testing required; developer only.
> fix macOS server dev builds

- src/cpp/session/modules/SessionCodeTools.R
Resolves comment in https://github.com/rstudio/rstudio/issues/8423#issuecomment-731424049.
Fall back to resolving methods from objects, as opposed to package namespaces or environments. (Unfortunately the `.rs.rpc.get_args()` does not capture whether the "source" object is a package or some other object in the global environment, so we just have to try both)
With this code:
```
library(R6)
Test <- R6Class(
"Test",
public = list(
initialize = function(x, y, z) {},
dothething = function(a, b, c) {}
)
)
test <- Test$
```
check that you get an argument tooltip when completing `new()` from `Test$`:
> better handle function tooltips for R6 methods

- src/gwt/panmirror/src/editor/src/nodes/rmd_chunk/rmd_chunk-capsule.ts
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
Fixes https://github.com/rstudio/rstudio/issues/8617
> Don't switch to visual mode if there are unprocessed source capsules

- src/gwt/panmirror/src/editor/src/nodes/image/image-events.ts
Fixes https://github.com/rstudio/rstudio/issues/8665
> don't process image paste from excel sheets (prefer html)

- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Don't autoscroll when giving focus to the console when Virtualized. This makes sense when not Virtualized but it feels bad when you're scrolled a bunch of blocks up and focus away and click back in.
Also added null checks on the prefs accessors in the ShellWidget constructor as there are injected contexts where it is null (Git committing for example).
Fixes #8568 
Fixes #8669 
Add a flag in the `onClick` private class to disable when Virtualized is on.
8568: Nothing special here, just verify that it doesn't scroll when "Limit console visible" is turned on.
8669: Verify that you can do a Git commit
> Virtualscroller autoscroll disable

- .github/pull_request_template.md
Adds a section to the Pull Request Template giving consideration to automated tests.
> Add automated tests section to pull request template

- src/cpp/session/modules/SessionPythonEnvironments.R
Addresses https://github.com/rstudio/rstudio/issues/8805, https://github.com/rstudio/rstudio/issues/8784.
Support the lookup of Python installations within the `~/.pyenv` folder, as installed by [pyenv](https://github.com/pyenv/pyenv) -- or similarly, `reticulate::install_python()`.
First, run the following code to install Python 3.7.7 with pyenv:
```
remotes::install_github("rstudio/reticulate")
reticulate::install_python(version = "3.7.7")
```
Then, check that this installation is found when looked up. For example, I see it here on my system (among other discovered Python installations):
> support lookup of pyenv python; filter some conda envs

- NEWS.md
This PR updates the NEWS file, and re-organizes sections a bit to highlight changes that are specific to R and Python.
> update + rearrange NEWS

- .github/pull_request_template.md
Adds a checklist to the PR template.
Make a list of things we should verify before submitting a PR for review, and add them to the special Github PR template.
None needed, no code change.
No QA needed.
> Add checklist for PRs

- NEWS.md
- src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.cpp
Addresses https://github.com/rstudio/rstudio/issues/8900.
Straight-forward fix -- ensure SQL code is submitted as UTF-8 to avoid transcoding errors.
None included.
Test via notes in https://github.com/rstudio/rstudio/issues/8900.
> ensure code submitted as UTF-8 on Windows

- INSTALL
Addresses https://github.com/rstudio/rstudio/issues/6112.
Remove superflous vars. 
None, doc-only change.
None, doc-only change.
> Remove superfluous dirs from INSTALL

- NEWS.md
Update NEWS.md for https://github.com/rstudio/rstudio-pro/pull/2340.
N/A
N/A
N/A
> Add note for removing Slurm job steps

- src/cpp/shared_core/include/shared_core/system/Crypto.hpp
- src/cpp/shared_core/system/Crypto.cpp
See https://github.com/rstudio/rstudio-pro/pull/2342
> open source companion to rstudio/rstudio-pro#2343

- src/gwt/src/org/rstudio/core/client/theme/res/ThemeResources.java
Fix build issues after #9009 merge
Remove references to handCursor. 
None.
See original
> remove no longer needed calls

- .devcontainer/devcontainer.json
Work in progress on defining a usable RStudio dev environment via visual studio code's dev container system.
Will provide more details once satisfied with the results, but getting in the initial skeleton for further experimentation.
> initial dev-container definition

- .devcontainer/Dockerfile
- .devcontainer/devcontainer.json
- .editorconfig
WIP on devcontainer definition, helpful to have in master
> more work on dev container

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
I asked Garrett, maintainer of the cheat sheets rstudio repo about the spelling of `Cheat Sheets` vs `Cheatsheets` and which one we should use. 
> we are trying to go with "cheat sheet"
Related: https://github.com/rstudio/cheatsheets/pull/163
These two menu items should have their spelling changed.
No tradeoffs?
> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will …
> Change menu 'Cheatsheet' to 'Cheat Sheet'

- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewDirectoryPage.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewPackagePage.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewProjectWizard.java
Addresses https://github.com/rstudio/rstudio/issues/9063. 
Add element IDs for the various pages of the New Project wizard.
None, these changes are intended as support for future automated testing.
You can verify this change by inspecting the elements (right click -> Inspect Element).
> Add automation IDs for New Project Wizard

- src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesUpload.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/model/FileUploadToken.java
Minor fixes that should have been included in #9231
> Minor spelling and type fixes

- src/cpp/OPTIONS.md
- src/gwt/src/com/sksamuel/gwt/README.md
> Make corrections to minor typos in project documentation.
>n/a
> n/a
> None/put second set of eyes on
> fix(docs): Corrected typos in project documentation

- src/cpp/r/RExec.cpp
- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/session/modules/SessionObjectExplorer.R
Addresses https://github.com/rstudio/rstudio/issues/9299. Regressed in https://github.com/rstudio/rstudio/commit/c3959eb9d0c594a154429adb850298dc20d81fec#diff-acb7e18d1d539ae9118a0fa5da125619159028eef4c76661553b87b2f968f30b; bug was never part of a public release.
Explicitly handle `NULL` return values (avoid assignment with `NULL` as that removes a list column)
None included.
Test via notes in https://github.com/rstudio/rstudio/issues/9299.
> debugger: handle NULLs in function calls appropriately

- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/tests/testthat/test-environment.R
Addresses https://github.com/rstudio/rstudio/issues/9328.
Explicitly check for + handle potentially missing arguments.
Unit test included.
Test via notes in https://github.com/rstudio/rstudio/issues/9328.
> improve handling of missing arguments in Environment pane when debugger active

- src/node/prototype/src/main/main.ts
- src/node/prototype/src/main/r.ts
Implements basic R version scanning, so that the version of R on the PATH is located and used by default. (This will eventually be extended with UI for selecting versions of R on Windows; this is just to help ease development for now.)
> implement basic R version scanning

- src/node/desktop/.mocharc.json
- src/node/desktop/package.json
- src/node/desktop/src/main/app.ts
- src/node/desktop/src/main/desktop-utils.ts
- src/node/desktop/src/main/main.ts
- src/node/desktop/test/main/app.spec.ts
- src/node/desktop/test/main/desktop-utils.spec.ts
- src/node/desktop/tsconfig.json
- src/node/desktop/yarn.lock
Current setup for unit testing via mocha doesn't work if Electron APIs are involved, because mocha is running tests via node, not electron.
Switch to electron-mocha, which runs the tests in Electron itself.
Found a bug when writing a test, I meant for `Main.getComponentVersions()` to return JSON (in string form), but it wasn't. Fixed that.
Moved mocha settings to `.mocharc.json`, and made the tsconfig.json be based off node14 baseline from [@tsconfig/bases](https://github.com/tsconfig/bases/)
In order to run tests again code in `main.ts`, had to move the initial startup to a separate `app.js` (which is how I did it in the prototype, turns out there was a reason for it). Otherwise we end up starting RStudio when we're trying to run tests.
This does mean we can't unit test stuff in …
> run electron unit tests in electron, not node

- NEWS.md
- src/cpp/conf/rsession-dev.conf
- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/session-options.json
changed timeouts to 200 millis for each
> enable async and handle offline by default

- src/node/desktop/test/core/xdg.test.ts
Fill out missing portion of win32 test
N/A
N/A
N/A
> Filled out Windows portion of desktop SHGetKnownFolderPath test

- src/node/desktop/src/main/desktop-callback.ts
- src/node/desktop/src/main/main-window.ts
- src/node/desktop/src/main/menu-callback.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
- src/node/desktop/test/unit/main/detect_r.test.ts
Fix all eslint issues in Electron code.
Run lint, fix, mostly function return types, a few unused things to remove or annotate.
NA
Purely dev-side
> fix eslint warnings in Electron project

- src/node/desktop/NOTICE.electron
- src/node/desktop/package.json
- src/node/desktop/src/core/system.ts
- src/node/desktop/src/main/app-state.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/desktop-callback.ts
- src/node/desktop/src/main/detect_r.ts
- src/node/desktop/src/main/main.ts
- src/node/desktop/src/main/menu-callback.ts
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/test/unit/core/system.test.ts
- src/node/desktop/test/unit/main/application.test.ts
- src/node/desktop/test/unit/main/session-launcher.test.ts
- src/node/desktop/yarn.lock
Resolve TODOs for generating launcher token and port (currently hardcoded in the Electron app).
- Pull in `uuid` and `crc` packages, add to NOTICE
- Hook up in code, write unit tests
- Other code changes not directly related:
- grouped imports
-  added `--trace-warnings` to yarn `start` and `start-diag` commands
- did `yarn upgrade` to pull in Electron v13.1.3
Added unit tests for this new code.
Internal detail covered by unit tests.
> resolve TODOs: generate launcher token and port for Electron desktop

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Addresses #9523
Remove the duplicate entry from commands.cmd.xml.
None specifically for this change.
Verify that selecting `File / Import Dataset / From SPSS...` triggers the same action as before this change.
> remove duplicate entry for importDatasetFromSAV command

- src/node/desktop/package.json
- src/node/desktop/test/unit/core/console-logger.test.ts
- src/node/desktop/yarn.lock
Create fake version of `console.log` for the `ConsoleLogger` unit tests, so we can (1) verify the expected behavior and (2) not spit out a bunch of stuff to console during the tests.
Using `Sinon.JS` to fake `console.log` and verify output. See https://sinonjs.org/ for details.
This improves the unit tests for `ConsoleLogger` class.
Purely a unit-test change.
> use Sinon.JS to fake console.log in logging tests

- src/node/desktop/docs/ElectronWindowClasses.puml
- src/node/desktop/docs/QtWebEngineInstance.puml
- src/node/desktop/src/main/desktop-browser-window.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/gwt-window.ts
- src/node/desktop/src/main/main-window.ts
- src/node/desktop/src/main/main.ts
- src/node/desktop/src/main/minimal-window.ts
- src/node/desktop/src/main/satellite-window.ts
- src/node/desktop/src/main/secondary-window.ts
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/test/unit/core/logger.test.ts
- src/node/desktop/test/unit/main/desktop-browser-window.test.ts
- src/node/desktop/test/unit/main/gwt-window.test.ts
- src/node/desktop/test/unit/main/secondary-window.test.ts
- src/node/desktop/test/unit/main/window-tracker.test.ts
WIP on the core window classes.
Port code from the Qt desktop.
Unit tests.
Internals
> put back toolbar flag, more base window implementation

- src/gwt/src/org/rstudio/studio/client/application/ApplicationInterrupt.java
Fixes the "click interrupt three times to get the abort dialog. " part of #8865 after it was broken with async rpc. 
With this PR, only finish the interrupt when the console busy is actually set to false
TBD - I could build an automated test to trigger the abort dialog if anyone thinks it's worth the effort
Test the two ways to block the R console - both interruptible and non-interruptible and press the "Interrupt" button. 
Interruptible ops like system("sleep 30") should just return
Non-interruptible ops like the hang() example in #8865 should display the "abort R" dialog on the 3rd click in 10 seconds. 
- [x ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md`
> call finishInterrupt only when session has really been interrupted

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
Addresses https://github.com/rstudio/rstudio/issues/9476.
Check the engine associated with the chunk that's about to be executed, and use that to determine if we should enter Python mode (or not).
N/A
In an R Markdown notebook, try executing a Python chunk multiple times. You should no longer see something like:
```
quit
reticulate::repl_python()
``` 
on each invocation.
> avoid un-necessary reticulate REPL toggles

- src/cpp/core/system/PosixSystem.cpp
- src/cpp/core/system/PosixSystemTests.cpp
- src/cpp/core/system/System.cpp
- src/cpp/core/system/Win32System.cpp
- src/cpp/core/system/Win32SystemTests.cpp
Addresses https://github.com/rstudio/rstudio/issues/9608.
- Use separate POSIX + Windows implementations
- On POSIX, verify the requested file is executable
- On Windows, search for a default set of "executable" extensions (if the supplied program appears to have no extension)
N/A
> tweaks to findProgramOnPath implementation

- src/cpp/server/ServerSessionManager.cpp
- src/cpp/server/ServerSessionProxy.cpp
- src/cpp/server/include/server/ServerSessionManager.hpp
https://github.com/rstudio/rstudio-pro/pull/2728
contains additional debug messages and clean out pending launches
after a few minutes so they don't pile up
> companion commit for load balancer fix

- NEWS.md
- src/cpp/session/modules/zotero/ZoteroCollections.cpp
- src/cpp/session/modules/zotero/ZoteroCollectionsLocal.cpp
- src/gwt/panmirror/src/editor/src/api/bibliography/bibliography-provider_zotero.ts
- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/source_panels/insert_citation-source-panel-list-item.tsx
Visual editor bibliography related bug fixes.
Fix a pair of issues related to insert bibliography.
N/A
N/A
> Visual Editor Bugfixes

- src/gwt/panmirror/src/editor/src/api/bibtex/bibtex.ts
- src/gwt/panmirror/src/editor/src/api/bibtex/characters.ts
- src/gwt/panmirror/src/editor/src/api/csl.ts
- src/gwt/panmirror/src/editor/src/marks/cite/cite-completion.tsx
- src/gwt/panmirror/src/editor/src/marks/cite/cite.ts
Address a few internally discovered issues with our Bibtex encoding.
Small, simple fixes.
N/A
N/A
> Minor Bibtex Bugfixes

- src/node/desktop/src/core/file-path.ts
Use the nifty new `Expected<>` type for functions that can return a result OR an Error.
Used it. Also shows that it can work with a custom Error subclass.
They still pass (and found a bug in my initial change).
Code internals.
> use Expected return type in file-path

- src/node/desktop/src/main/main-window.ts
- src/node/desktop/src/main/session-servers-overlay.ts
- src/node/desktop/test/int/session-restart.test.ts
Implement commented-out bits of MainWindow.closeEvent.
Convert to TypeScript.
None specifically, did tweak a test's timeouts.
None
> implement MainWindow.closeEvent (Electron)

- src/node/desktop/src/main/main-window.ts
When session is slow to load, don't keep reloading the "Loading..." page because it causes flashing.
Addresses: #9627
Wait for the sessions URL to be responsive, then reload the page.
This is covered by an existing integration test, as well as unit tests for the underlying mechanism.
Test by running rstudio with --session-delay-seconds=5, then observe that the loading screen doesn't flash, and the session ultimately loads.
> Don't reload "loading" page while waiting for session (Electron)

- src/node/desktop/yarn.lock
Upgrade to latest Electron (13.2) and Playwright (1.14.0) releases.
https://github.com/electron/electron/releases/tag/v13.2.0
https://github.com/microsoft/playwright/releases/tag/v1.14.0
On Mac:
* `yarn upgrade`
* ensure app builds and runs
* run unit tests
* run integration tests
* create dev package build (`scripts/mac-package`) and run it
No new tests, existing tests pass.
Updating dependencies.
> Update dependencies: electron 13.2, playwright 1.14.0

- Jenkinsfile
Add missing suffix to windows build
Set the environment variable
N/A build system change
All builds should have build numbers
> Add suffix to windows build

- src/cpp/core/Database.cpp
- src/cpp/server/auth/ServerAuthHandler.cpp
- src/cpp/server/db/20210712182145921760944_Ghost-Orchid_AlterTables.sqlite
- src/cpp/server/db/CreateTables.postgresql
- src/cpp/server/db/CreateTables.sqlite
Addresses [Pro #2978](https://github.com/rstudio/rstudio-pro/issues/2978)
Add column lists to all queries, or a comment explaining why the statement does not include them.
Any test that logs a user in or out should cover these.
* We should re-verify that upgrade still works for PostgreSQL & SQLite
* Open source side of this change only impacts the revoked cookie table (besides upgrade), so testing logout should be sufficient.
> Future proof SQL for schema changes

- Jenkinsfile
- docker/jenkins/publish-daily-binary.sh
- url encode the + sign in the URLs before putting into .htaccess
- add missing publish-daily-binary.sh for windows latest desktop exe
> two changes to hopefully fix latest daily links

- docker/jenkins/publish-daily-binary.sh
Look for daily link in .htaccess and if not found append it.
I tested this locally to be sure it replaces and appends URLs for some example OS and pro links.
> append the daily link if it's not found

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
Addresses https://github.com/rstudio/rstudio/issues/9108.
Code execution in the visual editor works by mapping the selection into the source editor and then executing the code there. For indented chunks, however, this mapping doesn't work correctly because the chunk in the visual editor's content is missing the leading spaces in the source editor. 
The fix is to examine the chunk's preamble (the line typically beginning with three backticks) to see if it's indented; if it is, we use the indent level to correct the mapping back to the source editor. 
N/A (automated tests not yet available for visual editor)
Test via notes in #9108.
> Fix code execution via selection in indented visual chunks

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
Addresses https://github.com/rstudio/rstudio/issues/9892. 
Straightforward style adjustment.
None, style change only.
Test via notes in https://github.com/rstudio/rstudio/issues/9892.
> ensure Ace is not visible when collapsed

- docker/jenkins/Dockerfile.opensuse-x86_64
Backport of SLES Build Fixes from `main`
Backport of SLES Build Fixes from `main`
N/A build system
N/A build system
> Update sles build

- src/gwt/src/org/rstudio/core/client/ClassIds.java
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/widget/ToolbarButton.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleInterpreterVersion.java
Open-source merge for https://github.com/rstudio/rstudio-pro/pull/3087
> open-source changes for pro PR #3087

- docker/jenkins/publish-daily-binary.sh
Looks like the rsp-session will have the daily in the path now so I will delete that other PR.
> changed + to - in regex to fix latest links

- Jenkinsfile
Attempt to fix failures with windows docker pull by using pbp, which retries.
Also increase number of times we will retry
N/A - build system only
N/A - build system only
> Use pullBuildPush for windows as well

- src/gwt/panmirror/src/editor/src/api/mark.ts
(fix related to behavior 1 of #9993)
```
- Enter one citation, e.g. @entry1
- Place the cursor to the left of the @ of the entry
- Start another citation by typing space (so the @ isn't directly adjacent to the subsequent one) and then back arrow and type @, then complete the entry, e.g. @entry2, @entry1
- (note that two `@``@` next to one another is not a valid citation, so typing that is expected 'break' the citation highlighting)
- The original entry is considered text, not a citation, while the new citation works
```
Improve Visual Editor handling of spaces at the start of lines that begin with a citation or raw LaTeX elements.
Strip the space from the front of the range and remove any marks from that prior to processing.
n/a
See case above. This doesn't directly fix behavior 1 of …
> Remove leading space when splitting invalid marks
