rstudio/rstudio

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ScopeManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ScopeTreeManager.java
This PR fixes a token OB1 error where we could accidentally re-commit a brace to the scope tree, leading to duplicated elements in the document outline.
The fix here ensures that the token iteration occurs _after_ the last-parsed position, rather than on it.
Note that this bug only affects Stan, as this is the only programming language using the newly-implemented (code-model decoupled) scope tree thus far.
=> fix duplication of scope tree elements

src/cpp/session/modules/SessionRAddins.R, src/cpp/session/modules/SessionRAddins.cpp, src/gwt/src/org/rstudio/core/client/BrowseCap.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/addins/Addins.java, src/gwt/src/org/rstudio/studio/client/workbench/addins/AddinsServerOperations.java
Closes #3602.
Note that while I would've preferred to do this entirely in the front-end, cross-site origin rules disallow us from modifying the Shiny gadget window (as its running on a different port, and so a different origin).
=> work around Mojave bug with invisible inputs in addins

src/cpp/core/include/core/Algorithm.hpp, src/cpp/session/modules/SessionHelp.cpp
Encode URL components used for links within R help pages, as some links will contain invalid characters (e.g. the `seq()` help page contains a link to `:`, but does not URL encode it).
Closes #3648.
=> encode URL components in R help

src/cpp/session/modules/SessionCodeTools.R
`shQuote()` will quote arguments using double quotes on Windows by default, but this unfortunately doesn't work as expected when we construct our R command invocations.
Avoid this by explicitly quoting pieces with single-quotes.
=> avoid double quotes in repos option string (closes #3686)

dependencies/common/install-boost
Since installing from SourceForge can occasionally be slow.
=> install boost from copy on AWS

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
One part of https://github.com/rstudio/rstudio/issues/3699.
=> use generic 'build package documentation' language for roxygenize

src/gwt/src/org/rstudio/core/client/widget/ModifyKeyboardShortcutsWidget.java
We use GWT's DataGrid control for the Modify Keyboard Shortcuts dialog. This has some known issues with flashing scrollbars in unexpected places under Chromium. 
As part of an earlier fix, I created the RStudioDataGrid class, which is effectively just a DataGrid plus some DOM surgery to clean up the elements that cause the issue. This change uses that class for the Modify Keyboard Shortcuts dialog.
Fixes #3707.
=> Use modified data grid for keyboard shortcuts to avoid scroll flashing

src/cpp/session/modules/SessionHelp.cpp
Ensure that search queries are HTML escaped before display.
=> normalize search query in help page

src/cpp/session/modules/SessionHelp.cpp
RStudio v1.1 still needs to build with C++98, which precludes the use of lambdas. Use a functor here instead.
=> use functor instead of lambda

src/cpp/session/modules/SessionConnectionsInstaller.R
In OS X, iODBC takes precedence over unixODBC and therefore, ODBC drivers should be hinted that unixODBC should be used to get DSN to work properly.
=> Add odbcinstlib entry in OS X for ODBC drivers

src/cpp/session/modules/SessionRCompletions.R
This PR should help alleviate issues seen in https://community.rstudio.com/t/diagnosing-a-non-responsive-rstudio-console/4601, where attempts to retrieve file completions on a slow NFS can cause the RStudio console to hang.
We enforce a time limit of 1 second on the file listing attempt, and just return an empty list if it takes longer than that.
=> set timeout when retrieving file completions

src/cpp/session/modules/SessionThemes.R
If you tried to delete the current theme, it would try to call `.rs.applyTheme` with only one argument when it requires two.
=> Fix a bug in removeTheme when deleting the current theme.

src/gwt/src/org/rstudio/core/client/widget/ProgressPanel.java, src/gwt/src/org/rstudio/core/client/widget/ProgressSpinner.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/ToolbarPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
This PR fixes an issue where any progress spinners generated would animate in the background, even when not visible.
The issue here: we schedule a timer to run relatively frequently for every progress spinner, but never actually stop / detach those (except in the case of Notebook chunk outputs, where detach was done explicitly).
Rather than place the onus of remembering whether these things should be detached / stopped to the clients of ProgressSpinner, this PR makes ProgressSpinner keep track of its own animation -- starting and stopping it as appropriate when it's focused, and also ensuring the animation stops when the widget is detached.
Part of fix for #3757.
=> avoid animating progress spinners when not visible

src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishReportSourcePage.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
Timing issues when trying to dismiss publish wizard in scenarios described in #3752.
In one case the wizard dialog is shown in an incomplete state while an error message is displayed to user, then goes away when the error message is dismissed. In the other case, the dialog fails to dismiss via `indicator.onCompleted()`.
Fixed by using nested timers; not very satisfying, but fixes both cases in my testing on on desktop and server.
Secondary wording fix; change "Publish Source Code" in this dialog (which doesn't match the intent of the dialog) to "Publish to RStudio Connect".
BEFORE:
AFTER:
Fixes #3752
=> Fixes for attempting to publish unrendered Rmd as final document

src/cpp/core/markdown/sundown/buffer.c, src/cpp/core/markdown/sundown/buffer.h, src/cpp/core/markdown/sundown/html.c, src/cpp/core/markdown/sundown/html.h, src/cpp/core/markdown/sundown/markdown.c, src/cpp/core/markdown/sundown/markdown.h
Inline math in this Shiny app fails, but only when tested on RStudio Server.
The correct behavior is for the math to be formatted by MathJax, but on
RStudio Server you see latex markup surrounded by $. The issue seems to be
that the copy of Sundown in rstudio is overriding the copy of Sundown in
the Markdown package, and only the latter contains the logic required to
process inline latex math. @jjallaire said that the intention was to keep
the two in sync, so this commit copies the relevant files over from markdown.
https://github.com/rstudio/shiny-examples/tree/master/020-knit-html
**NOTE:** I'm not set up with an rstudio dev environment right now so I don't know if this compiles, let alone works. Sorry.
=> Fixes inline latex math rendering

src/cpp/session/modules/SessionRSConnect.cpp, src/gwt/src/org/rstudio/studio/client/rsconnect/RSConnect.java, src/gwt/src/org/rstudio/studio/client/rsconnect/events/RSConnectDeploymentCancelledEvent.java, src/gwt/src/org/rstudio/studio/client/rsconnect/model/RSConnectServerOperations.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/rsconnectdeploy/RSConnectDeployOutputPresenter.java
This small change makes it possible to terminate the R process hosting the Publish operation. 
It's helpful for two cases:
1. When you accidentally click Publish, and realize it right away (i.e. while the application is still being bundled and uploaded)
2. When something has gone awry and you need to kill a publish process that won't terminate on its own (otherwise the only way to kill it is to restart the IDE)
Ideally it would function as a Cancel button for Connect, too; in other words, if the deployment task has already started, it would tell Connect to stop the task. Right now however there's no API that will allow us to do this, and the IDE also currently doesn't know what phase the deployment is in. For now, then, we just show a dialog to ensure that you know that you're cancelling …
=> Make publish cancellable

src/cpp/CMakeLists.txt, src/cpp/core/include/core/BoostSignals.hpp, src/cpp/r/include/r/session/RConsoleHistory.hpp, src/cpp/r/include/r/session/RGraphics.hpp, src/cpp/r/session/graphics/RGraphicsPlotManager.cpp, src/cpp/r/session/graphics/RGraphicsPlotManager.hpp, src/cpp/r/session/graphics/RGraphicsPlotManipulatorManager.cpp, src/cpp/r/session/graphics/RGraphicsPlotManipulatorManager.hpp, src/cpp/server/include/server/ServerSessionManager.hpp, src/cpp/session/SessionMain.cpp, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/cpp/session/include/session/SessionModuleContext.hpp, src/cpp/session/include/session/SessionSourceDatabase.hpp, src/cpp/session/include/session/SessionUserSettings.hpp, src/cpp/session/include/session/projects/SessionProjects.hpp, src/cpp/session/modules/SessionPlots.hpp, src/cpp/session/modules/SessionRAddins.cpp, src/cpp/session/modules/SessionWorkbench.cpp, src/cpp/session/modules/build/SessionSourceCpp.cpp, src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.cpp, src/cpp/session/modules/rmarkdown/NotebookCapture.cpp, src/cpp/session/modules/rmarkdown/NotebookExec.cpp, src/cpp/session/modules/rmarkdown/NotebookExec.hpp, src/cpp/session/modules/rmarkdown/NotebookPlots.cpp, src/cpp/session/modules/rmarkdown/NotebookPlots.hpp, src/cpp/session/modules/rmarkdown/NotebookQueue.cpp, src/cpp/session/modules/rmarkdown/SessionRmdNotebook.hpp
This PR makes it possible to build RStudio against either Boost.Signals or Boost.Signals2. When using Boost 1.69.0 or greater, RStudio uses and builds against Boost.Signals2.
Will likely require similar work in the Pro repository.
re: https://github.com/rstudio/rstudio/issues/3760
=> support both Boost.Signals and Boost.Signals2

src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/JobManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/JobsServerOperations.java
Due to mismatch of Gwt side's expectation (Void) vs. what the rsession RPC returns (String), getting a message in Javascript console when starting a session job:
FWIW, the return value being ignored is the new job ID; leaving it in the RPC (but continuing to ignore it).
=> prevent javascript console message when starting session job

src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java, src/gwt/src/org/rstudio/core/rebind/command/ShortcutsEmitter.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
Fixes #3790.
The completion managers we define for languages that support snippet insertion already handle Shift + Tab for snippet insertion; see e.g.
https://github.com/rstudio/rstudio/blob/master/src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java#L490-L499
Because of this, we no longer need the global command binding as this ultimately causes issues with double-insertion of snippets.
I also discovered that the 'handlesEventPropagation' item doesn't work as expected -- `Event.getCurrentEvent()` doesn't actually return the current live event, because the command is executed in response to a GWT-generated _preview_ event, which GWT unfortunately doesn't make available. (https://developer.mozilla.org/en-US/docs/Web/API/Window/event does …
=> avoid global binding for snippet insertion

src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.css, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
Fixes https://github.com/rstudio/rstudio/issues/1925. Some notes:
1. `@def` within conditions does not appear to be supported anymore (?). In the generated CSS, I saw the actual variable names (rather than their substituted values) meaning that we were assigning 'garbage' for the widths. Unless that's a devmode-only quirk, but to the best of my knowledge this did work before.
2. The browser-specific styling seems to no longer be necessary now that we're using Chromium in the desktop products.
=> remove desktop-specific dialog sizing bits

src/cpp/session/modules/rmarkdown/NotebookExec.cpp, src/cpp/session/modules/rmarkdown/NotebookExec.hpp, src/cpp/session/modules/rmarkdown/NotebookQueue.cpp
This change fixes a crash that can occur when there's an error evaluating chunk options. When this happens, the object that manages the associated chunk's execution context (`ChunkExecContext`) can leak event handlers. Executing these leaked handlers when the underlying object has been cleaned up can cause a crash.
There are two lines of defense added here:
1. As chunk option evaluation errors are intended to be tolerable, we now track them with a separate error variable (and log them to the chunk, not to the log file). The chunk is still executed.
2. When all of the notebook chunks are done executing, we double-check that our current execution context gets safely shut down.
=> Ensure chunk execution context cleanup on parse error

src/cpp/core/system/Crypto.cpp
Fairly minimal change to allow compilation against OpenSSL 1.1. If I'm reading the documentation at https://www.openssl.org/docs/man1.1.0/crypto/ERR_load_crypto_strings.html correctly, explicit initialization here is no longer necessary.
=> support compilation with OpenSSL 1.1

src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopInfo.cpp, src/cpp/desktop/DesktopInfo.hpp, src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopOptions.cpp, src/cpp/desktop/DesktopOptions.hpp, src/cpp/desktop/DesktopUtils.cpp, src/cpp/desktop/DesktopUtils.hpp, src/gwt/src/org/rstudio/core/client/widget/SelectWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
This PR should alleviate https://github.com/rstudio/rstudio/issues/1889 a little more safely, and without introducing issues around caching (+ cache invalidation; + interacting with the filesystem) that could be frustrating.
This PR effectively moves font database generation to a separate thread, which communicates the set of discovered fonts back to the main thread when the font database is ready. If the user navigates to the Appearance dialog before fonts have been enumerated, they'll see:
with the currently-selected font displayed, but the font list otherwise empty. I felt that keeping the UI minimal here is fine since this is a condition that will only ever be seen by a very small subset of users (those who choose to install many many fonts on their system)
We could in theory also try …
=> build font database on startup in separate thread

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCommentHeaderHelper.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetJSHelper.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetRHelper.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetSqlHelper.java
This change fixes a couple of issues I ran into with magic `!source` comments.
1. Magic comments worked with Source on Save, but not with the regular Source command. I'm not sure if this was intentional, but it seems very counter-intuitive, so I've updated the Source command to use the magic comment if it's present.
2. A JS exception can occur if you delete the magic comment and then save the file; this happens because the comment header is gone but we still think the file's type is `XT_CUSTOM_SOURCE`. The fix is to fall back on executing the ordinary `source()` command if we fail to locate the magic comment header, even if we think it should be there.
=> Fix issues with magic source comments

src/cpp/session/modules/SessionHelp.cpp, src/cpp/session/modules/SessionProfiler.cpp, src/cpp/session/modules/SessionThemes.cpp, src/cpp/session/modules/SessionThemes.hpp, src/cpp/session/modules/data/DataViewer.cpp, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
This PR fixes the handling of theme link elements when they are added to nested documents generally by using `../` for each extra path element introduced by the nested document. It also removes the now unnecessary theme URI handlers on the backend.
Closes #3844.
=> Fix handling of theme URLs in nested documents.

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/files/filedialog/FileSystemDialog.java, src/gwt/src/org/rstudio/core/client/theme/ModuleTabLayoutPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/DelayLoadWorkbenchTab.java
This change adds predictable element IDs to workbench tabs and panels, as well as common file dialog actions such as "save" and "cancel", to ease test automation of these features.
=> Add unique IDs to workbench tabs, panels, and file dialog actions

dependencies/common/install-packages, dependencies/common/install-packages.cmd, src/cpp/session/CMakeLists.txt, src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
We've been embedding rsconnect for a while, since we [introduced a new parameter to `deployApp`](https://github.com/rstudio/rsconnect/commit/91cc3c7a33dc81182d90594c50bc98353fd062c8) that wasn't in the CRAN version of rsconnect. 
rsconnect 0.8.11 is now on CRAN. It includes this new parameter and a few other important changes (modernizes dependencies, adds pre/post deploy hooks). This change removes our embedded copy in favor of the CRAN version.
Fixes #3499.
=> Install rsconnect from CRAN

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/JobsPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/JobsTab.java
We won't prevent closing Jobs tab if there are launcher jobs (those are not tied to the session, and will show again if you re-open the jobs tab). Also, don't want to prevent closing the tab if there are only completed jobs.
Also added command for showing Jobs tab to View menu. Without this, the only way to get the Jobs pane back is to restart the UI, or start another job with the Tools / Jobs menu (part of #3743).
=> only warn when closing job tab if there are running session jobs

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputGallery.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
Chunk output height has always been a little problematic. There are basically three choices, and each has significant drawbacks that result in bugs. 
1. If we allow it to grow without constraint, it can take over the editor surface, with unpleasant results. See #2174. 
2. If we constrain its height with a scrollbar, you wind up with two vertical scrollbars right next to each other, which is unpleasant and almost unusable.
3. If we constrain its height with no scrollbar (just clip it), users can't see all the content. This is what we currently do; see #3536. 
Since we originally clamped the height to avoid HTML widget iframes from consuming the whole editor surface, this change creates a compromise between (1) and (3) that preserves the clamping behavior for HTML widgets while letting …
=> Only clamp notebook chunk output height for HTML widgets

src/cpp/session/resources/grid/dtstyles.css, src/cpp/session/resources/grid/dtviewer.js
This is another attempt to improve data viewer performance when viewing tables containing a large number of columns.
Most of the overhead during scrolling is due to browser layout computation, which unfortunately includes recomputing things like text overflow (even though in theory scrolling the table shouldn't trigger that at all since we're not resizing any inner cells).
This PR helps to paper over the problem a little bit. Now, we only apply overflow styles to 'big enough' cells. This should ensure that existing large cells are resized as needed (with the associated performance hit) while small cells won't.
To help support this, we disallow shrinking the initial column width of small-ish cells beyond the initial width (since that would run afoul of our now disabling overflow in those …
=> only apply overflow styles to 'large' cells

src/cpp/session/modules/build/SessionBuild.cpp
Follow up on https://github.com/rstudio/rstudio/pull/3629, ugh, not sure exactly how this worked or maybe I checked-in the wrong fix, tried to look for changes in `devtools`, `pkgload`, `rprojroot`, etc, but couldn't spot.
Currently, testing a package file triggers:
```
==> Testing R file using 'testthat'
Error in path.expand(path) : invalid 'path' argument
Calls: <Anonymous> ... rprojroot_find_root -> get_start_path -> normalizePath -> path.expand
Execution halted
Exited with status 1.
```
=> Fix test file in testthat integration

src/cpp/session/include/session/jobs/Job.hpp, src/cpp/session/include/session/jobs/JobsApi.hpp, src/cpp/session/modules/SessionJobs.R, src/cpp/session/modules/jobs/Job.cpp, src/cpp/session/modules/jobs/JobsApi.cpp, src/cpp/session/modules/jobs/ScriptJob.cpp, src/cpp/session/modules/jobs/ScriptJob.hpp, src/cpp/session/modules/jobs/SessionJobs.cpp, src/cpp/tests/testthat/test-jobs.R, src/gwt/src/org/rstudio/core/client/widget/ProgressBar.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/Job.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/JobManager.java
While I'm waiting for my power to come on so I can use my Pro VM... taking the opportunity to reduce drift between pro and open-source code.
- move Job.hpp and JobsApi.hpp into a location where they can be used by the launcher-jobs code
- support returning tags (array of strings) as part of Job metadata; will potentially be used for sorting launcher jobs
- ability to add Job object (C++) with a pre-determined id (launcher id) instead of auto-creating one
- tweaks to remove only local jobs, only check local jobs when deciding if local jobs are running, and so on; should be no-ops in open-source but important for Pro
- avoid a divide by zero in Javascript code for ProgressBar that was being hit with launcher jobs (probably no longer important with pane UI changes, but might as well put it …
=> sync Jobs plumbing tweaks between pro and open-source

src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/JobsPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsPane.java
If you close the Jobs tab, the next time you start the IDE the tab will not be shown. This is same model as the Terminal Tab. Allows a user who never uses the feature to hide it once and not see it again.
To get Jobs tab back, use "View/Show Jobs" or run a script as a job via editor drop down "Source / Source as Job" or "Tools/Jobs/Start Job".
Fixes #3743
=> Persist visibility of Jobs tab

src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java, src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java
Fixes #3893
Worst case you will be told about running jobs, agree to killing those, then see warning about busy terminals, and have to agree to that. On the plus side, if you cancel out of the second step, the jobs will not be killed, either.
Suggests that busy terminals might show up as session jobs in this context. This paradigm would also translate to 1.3 concept of having terminals survive their session being closed (these style of terminal jobs would correspond conceptually to launcher jobs).
For 1.2, just doing the two stage warning to avoid users losing work in a way they weren't expecting.
=> warn before killing session jobs when restarting R or building package

src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesListDataGridStyle.css
In RStudio's Classic theme, the checkboxes in the Files pane disappear when you click on them. This is a known issue in Chromium, and this change works around it by applying an infinitesimal zoom to the checkboxes when we're using the Classic theme.
=> Work around Chromium bug affecting checkbox rendering

src/cpp/session/modules/jobs/ScriptJob.cpp, src/cpp/session/modules/jobs/ScriptJob.hpp, src/cpp/session/modules/jobs/SessionJobs.cpp, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/events/JobRunSelectionEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/JobLaunchSpec.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/JobManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobLauncherControls.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobLauncherDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
This change makes it possible to run any selected R code as a background job. It works by much the same mechanism as running an entire script, but allows running pieces of scripts as well as R code from unsaved and untitled scratch buffers.
=> Add "run selection as job" command

src/gwt/src/org/rstudio/studio/client/common/Timers.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetThemeHelper.java
This PR ensures that the global handler used by theme helpers is cleaned up when the associated document is detached.
Also adds a `Timers` utility class, since the `Timer` class in GWT play quite as well with Java 8 tools (e.g. lambdas).
=> clean up handler registrations on dismiss

src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/JobProgressPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/JobConstants.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobItem.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobProgress.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobProgress.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsPane.java
This change makes a few minor improvements to the toolbar when viewing a job.
1. If the job does not have ranged progress, no progress bar is shown. Instead we show the job's descriptive status text (if it has it), or its status (if it doesn't).
2. When the job is complete, the completion state (succeeded, failed, etc.) are now shown in its toolbar, along with the elapsed runtime.
=> Show status rather than progress bar for non-ranged jobs

src/cpp/desktop/DesktopChooseRHome.cpp, src/cpp/desktop/DesktopChooseRHome.hpp, src/cpp/desktop/DesktopChooseRHome.ui, src/cpp/desktop/DesktopRVersion.cpp
This PR makes it possible for users to customize the rendering engine used by RStudio in the choose R version dialog:
The intention is that this could be used as an escape hatch for users with rendering issues on Windows that make the IDE unusable; e.g. as described in https://community.rstudio.com/t/rstudio-preview-ide-rstudio-1-2-1139-screen-is-black/18819/3. The intention is that, with this feature, we could instruct such users to launch RStudio by holding down <kbd>Ctrl</kbd> when RStudio is launched, and then they could try changing the rendering engine used in this dialog.
Note that the user will technically still need to restart the IDE once more (since these settings are applied too late; ie, after GPU-related things are initialized in the QApplication object). Is there a clean …
=> allow users to customize rendering engine in choose R version dialog

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Closes #3727.
Users can still rebind these commands locally if they prefer these keybindings on their Linux machines.
=> avoid binding conflict for Ctrl+Page{Up/Down}

src/cpp/desktop/DesktopBrowserWindow.cpp, src/cpp/desktop/DesktopBrowserWindow.hpp
This PR fixes an issue seen when building RStudio against Qt 5.12 RC, where windows are blank when first shown, and remain blank until resized.
=> work around Qt 5.12 issue (?) where window blank when first shown

src/cpp/core/r_util/RSessionContext.cpp
1. Open an session on RStudio Server Pro
2. Remove the trailing slash from the URL, e.g. `https://rstudio-server.example/s/003f08241028fde4b4e02`
3. Open the new URL
This returns a 404. 
This URL should work. We've found that some proxies strip trailing slashes from URLs (perhaps as a form of canonicalization?); these consequently don't work with Server Pro because it requires a trailing slash.
This change fixes the issue by making the trailing slash optional (but only at the end of the URL). Targeted for 1.3 since messing with URL routing carries some risk.
=> Allow session URLs to work without trailing slashes

src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
Note that MiKTeX no longer provides the complete version. There is only the basic installer now.
https://github.com/rstudio/rmarkdown/issues/39#issuecomment-443383258
=> Mention TinyTeX in the message when LaTeX is not installed

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/JobManager.java
RSP will have other types of jobs, and we want to make a clearer distinction between them in the UI.
The "Clear jobs" command will be going away, so not bothering to rename it.
Fixes #4001
=> rename jobs as "Session Jobs" in the UI

src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.java, src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.ui.xml
The Help -> About dialog currently has a paragraph that opens:
>  Unless you have received this program directly from RStudio pursuant to the terms of a commercial license agreement...
This is redundant in RStudio Pro, since it is by definition received directly from RStudio pursuant to the terms of a commercial license agreement.
=> Remove GPL notice in RStudio Pro

src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java
I believe we need to split the Preview SQL dependencies into:
- Creating a SQL File: In this case, we want to suggest `DBI` and `RSQLite` for the preview to work.
- Previewing a SQL File: In this case, we don't really need `RSQLite` for the preview to work.
I hit this while using `sparklyr` in a cluster, which shouldn't need `RSQLite` installed, same for ODBC drivers, some users might actually have restrictions to install the `RSQLite` package so I don't think we should enforce this.
=> Allow previewing SQL files without RSQLite

src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
This change picks up a new version of the rsconnect package. The previous version had a bug which affected a small portion of users on HTTP/2. 
Fixes #3947.
=> Update to rsconnect 0.8.12

src/cpp/session/modules/NotebookData.R
(Fixes yihui/knitr#1637)
Currently, RStudio always uses `dbFetch()` (directly or via `dbGetQuery()`) to execute SQLs, but it should use `dbExecute()` for SQLs that don't return result sets.
This PR brings the changes made on the same source code in knitr's repo.
=> Use dbExecute() for SQLs that don't produce the results

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkHtmlPage.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
After HTML widgets load in R Notebooks, we inject a few key theme colors into them so that they match the editor theme. 
However, when HTML widgets in chunks are detached and reattached to another point in the DOM, the `<iframe>` reloads its URL. We don't currently have a mechanism to detect this, so the newly reloaded page doesn't get its styles re-injected, and looks unthemed.
This change fixes that by reapplying colors every time the frame loads its URL.
Fixes #3882.
=> Reapply theme after chunk HTML widgets load

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
The "Enable drag and drop of text" preference -- intended to disable the text drag and drop feature of Ace that some users find annoying -- actually makes the whole editor surface read-only. This change makes it affect only text drag and drop. 
Fixes #3992.
=> Set drag enabled state from preference

src/cpp/session/include/session/jobs/Job.hpp, src/cpp/session/include/session/jobs/JobsApi.hpp, src/cpp/session/modules/jobs/JobsApi.cpp, src/cpp/session/modules/jobs/SessionJobs.cpp, src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/JobsPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/JobConstants.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/JobManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsPane.java
Fixes #4005 
Fixes #4001 
This now includes renaming various UI from "Session Jobs" to "Local Jobs", which we decided makes more sense for users, and softened the language a bit in the "remove local jobs" confirmation dialog.
New **Hide Previously Completed Jobs** command shows up on More dropdown in Jobs pane, and Tools / Job menu. It is a toggle, with a persistent boolean pref. "Previously Completed" refers to fact that jobs which finish after the option is toggled on will remain visible. Otherwise running jobs would disappear from the pane as they complete. Also added a status message that appears at the top of the Jobs Pane when showing the list of jobs, indicating when the "Hide Jobs" toggle is on. I imagine we might add additional job sorting/filtering commands to this More dropdown …
=> Add More menu to Jobs pane with new Hide Completed Jobs toggle

src/cpp/server/extras/systemd/rstudio-server.redhat.service.in, src/cpp/server/extras/systemd/rstudio-server.service.in
At my organization, during a reboot of one of our RStudio hosts (the load balancer), we encountered a race condition where the server would not be able to resolve hosts defined as load balancing targets, and would therefore fail to ~start~ load balance to hosts it was supposed to.
Can't the RStudio unit just be configured to use `network-online.target`, and refuse to start if that is not the case? I could see potential issues with e.g. running on a system that is not online, but at the same time it seems like this makes a lot more sense.  That is what this PR does.
=> systemd: Require network-online.target in the [Unit] section

src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobOutputPanel.java
Fixes #4014
Also ignore showOutput calls with empty output. Launcher jobs are doing this (that will be fixed separately), but might as well handle it, otherwise the "Job has not emitted output" message is prematurely hidden.
=> Fix output pane when moving between jobs with and without output

src/cpp/session/SessionClientInit.cpp, src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/SessionConsoleProcessApi.cpp, src/cpp/session/SessionConsoleProcessInfo.cpp, src/cpp/session/SessionConsoleProcessInfoTests.cpp, src/cpp/session/SessionConsoleProcessTable.cpp, src/cpp/session/SessionConsoleProcessTable.hpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/cpp/session/include/session/SessionConsoleProcessInfo.hpp, src/cpp/session/modules/SessionDependencies.cpp, src/cpp/session/modules/SessionGit.cpp, src/cpp/session/modules/SessionSVN.cpp, src/cpp/session/modules/SessionTests.cpp, src/cpp/session/modules/SessionVCS.cpp, src/cpp/session/modules/connections/SessionConnections.cpp
This change fixes a regression introduced by the port obscuration feature. Terminal websockets don't work with this feature since they create websocket URLs using raw port numbers, which are no longer supported.
The fix is to distinguish between the two different types of serialization we use for console processes:
1. **Client** serialization, in which we need to replace the port with an obscured equivalent (used for sending process information to the front end), and
2. **Persistent** serialization, in which we need to save the raw port itself (used for saving process information to disk).
Anywhere that we serialize processes to JSON now requires an explicit opt-in to the appropriate behavior.
=> Obscure ports when connecting to terminal via websocket

src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/JobProgressPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobProgress.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsPane.java
This change simplifies the job progress presenter slightly: it no longer requires an explicit invocation to enter completed mode; instead, it enters it automatically when given a completed job. 
Fixes https://github.com/rstudio/rstudio-pro/issues/748.
=> Pass completed job instead of separate completed flag

src/cpp/session/modules/SessionSource.cpp, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
This PR enforces a UTF-8 encoding for R Markdown documents. The document-preferred encoding overrides:
1. A previously-known encoding for the document; I believe this is necessary since we'll want to convert pre-existing R Markdown documents to UTF-8 as appropriate;
2. The default encoding preference.
The `encodingOverride` argument will still take precedence.
Closes #4028.
NOTE: We may need to also to enforce UTF-8 when reading R Markdown documents; or at least 'guess' if the document is UTF-8 versus the system encoding.
=> prefer UTF-8 for .Rmd documents

src/cpp/session/modules/ModuleTools.R
This PR fixes an issue where RStudio would not update `BINPREF` (as required for newer Rtools) if it saw that the Rtools bin folder was already on the `PATH`.
Part of #3563.
=> check for BINPREF set when adding Rtools to PATH

src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteApplication.java, src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteWindow.java
This change fixes an issue with theme application in satellite windows. A request log reveals that satellite windows perform an unnecessary load of the default theme before loading the actual theme.
The problem is that satellite windows are registering their theme change event handlers too soon -- before they have received a SessionInfo with the UiPrefs that contain the correct theme. The fix here is to move the event handler registration to after the UiPrefs are initialized.
Fixes https://github.com/rstudio/rstudio/issues/3884.
=> Wait for session info to arrive in satellite before loading theme

src/cpp/session/modules/SessionCodeTools.R, src/cpp/session/modules/SessionDataPreview.R, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/sql/model/SqlServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetSqlHelper.java
With this PR, errors during SQL preview are reported to the user, e.g.
Closes https://github.com/rstudio/rstudio-pro/issues/633.
=> report SQL preview errors to user

src/gwt/src/org/rstudio/core/client/dom/DomUtils.java, src/gwt/src/org/rstudio/core/client/widget/RStudioDataGrid.java
Currently, we scan the DOM tree recursively for DataGrid scroll helper elements (see #2808 and #3707 for the unhappy history). When the DataGrid is large, however, this can take a Long Time and possibly overflow the stack.
This change fixes the issue by limiting the recursive depth at which these elements are searched (they are predictably in the first three levels). 
Fixes #4023. Note however that this doesn't necessarily make the Files pane performant when there are many thousands of files.
=> Limit recursion depth when eliminating DataGrid cruft

src/cpp/session/SessionConsoleProcessPersist.cpp, src/cpp/session/include/session/projects/SessionProjects.hpp, src/cpp/session/projects/SessionProjectContext.cpp
On RStudio Desktop, and on Server when in single-session mode, we currently persist console process information (such as history and environment values) inside RStudio project folders, in the hidden `.Rproj.user` folder.
This change creates a new "external storage" folder for projects, which lives in e.g. `~/.rstudio/projects`. It uses the project ID mapping table (formerly dormant outside server multi-session mode) to create a persistent map of projects to unique IDs, and uses those IDs to make unique folder paths. Console process information is stored in the external storage folder instead of inside the project.
Note that this doesn't fix any of the subtle issues which result from the impedance mismatch between project and session storage for terminals (e.g. when you have two sessions …
=> Persist console processes outside project folder

src/cpp/r/R/Api.R, src/cpp/session/SessionClientInit.cpp, src/cpp/session/SessionMain.cpp, src/cpp/session/SessionPersistentState.cpp, src/cpp/session/SessionUrlPorts.cpp, src/cpp/session/include/session/SessionPersistentState.hpp, src/cpp/session/include/session/SessionUrlPorts.hpp
This change adds an API method which makes it possible to transform localhost URLs like these:
http://localhost:1234/
into URLs which are externally accessible on RStudio Server, like these:
http://servername/s/003f0cfc78a31de4b4e02/p/c6237f97/
It was previously possible for this transformation to be done without an API call, since you could just put the raw port number right into the URL, but this isn't possible any more; see https://github.com/rstudio/rstudio-pro/pull/738 for a longer discussion of the rationale. 
Part of a fix for https://github.com/rstudio/rstudio/issues/4054.
=> Add API method for transforming localhost urls

dependencies/common/install-boost, dependencies/linux/README, dependencies/linux/install-qt-sdk, dependencies/osx/install-qt-sdk-osx, dependencies/windows/install-qt-sdk-win.cmd, dependencies/windows/qt-noninteractive-install-win.qs, docker/jenkins/Dockerfile.centos7-x86_64, docker/jenkins/Dockerfile.debian9-x86_64, docker/jenkins/Dockerfile.opensuse15-x86_64, docker/jenkins/Dockerfile.windows, docker/jenkins/Dockerfile.xenial-amd64, package/osx/make-package, src/cpp/CMakeLists.txt, src/cpp/desktop/CMakeLists.txt, src/cpp/desktop/DesktopBrowserWindow.cpp, src/cpp/desktop/DesktopBrowserWindow.hpp, src/cpp/desktop/DesktopMain.cpp, src/cpp/desktop/DesktopWebView.cpp, src/cpp/desktop/DesktopWin32ApplicationLaunch.cpp
This PR upgrades RStudio to Qt 5.12.0. Some notable changes:
1. We now explicitly specify a platform target on macOS; targeting macOS Sierra (10.12). This appears necessary to work around some Qt bugs that seem to appear only when no macOS target is specified; at least as seen in my local development builds on Mojave.
2. Some of the workarounds we had included for Qt 5.11.1 are no longer necessary.
=> upgrade to Qt 5.12.0

src/cpp/r/R/Api.R, src/cpp/session/SessionClientEvent.cpp, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp, src/cpp/session/modules/SessionThemes.cpp, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/application/ApplicationThemes.java, src/gwt/src/org/rstudio/studio/client/application/events/ApplicationEventHandlers.java, src/gwt/src/org/rstudio/studio/client/application/events/ComputeThemeColorsEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/model/ThemeServerOperations.java
The R2D3 package (and perhaps others) is able to adapt to the active RStudio theme by reading its foreground and background colors from rstudioapi (a new feature in 1.2). Unfortunately, this adaptation was short-lived; later in 1.2 we had to remove the fore/background color accessors when we did the custom theme work, as RStudio no longer has any knowledge of the theme colors (it just applies CSS).
This change adds the accessors back, in such a way that they work without a priori knowledge of the theme and without CSS parsing of any kind. Instead, we now ask the browser (using a client event) for the theme colors, and it reads them from a dummy element. 
Fixes https://github.com/rstudio/rstudio/issues/4055.
=> Restore foreground/background colors to themes API

src/gwt/www/templates/encrypted-sign-in.htm
Suggested input form changes to the RStudio Server login form to suppress all the "helpful" things iOS and Android OS try to do on web pages so it's less frustrating for end-users (these rly aren't bad defaults anyway IMO but I totally grok if this is an undesired PR).
=> Dislable autocomplete/capitalize/etc for rstudio server login form

dependencies/common/install-boost, dependencies/linux/README, dependencies/linux/install-qt-sdk, dependencies/osx/install-qt-sdk-osx, docker/docker-compile-all.sh, docker/jenkins/Dockerfile.centos7-x86_64, docker/jenkins/Dockerfile.debian9-x86_64, docker/jenkins/Dockerfile.opensuse15-x86_64, docker/jenkins/Dockerfile.xenial-amd64, src/cpp/desktop/CMakeLists.txt, src/cpp/desktop/DesktopMain.cpp, src/cpp/desktop/DesktopWebView.cpp
This change partially rolls back the Qt 5.12 update (see https://github.com/rstudio/rstudio/pull/4015/files) on MacOS and desktop Linux, due to the following problems:
- Qt 5.12 causes significant issues on MacOS. https://github.com/rstudio/rstudio/issues/4086
- Qt 5.12 cannot be compiled on CentOS 7. https://bugreports.qt.io/browse/QTBUG-71945?jql=text%20~%20%22compile%20gcc%204.8%22%20ORDER%20BY%20created%20DESC
We expect that both of these (or at least the last one) will be (as usual) resolved in the *next* update of Qt, so will wait for that one to do our next upgrade. 
This change also adds a new `docker-compile-all` script which can be used to programmatically compile all Linux desktop and server images. This should make it easier for us to do fire-and-forget local testing of …
=> Downgrade to Qt 5.11.1

src/cpp/session/resources/themes/compile-themes.R
This change fixes the compile-themes script so that it can handle the following edge cases:
- Themes with no `ace_keyword` rule
- Themes which use named CSS colors rather than RGB values
Fixes #3907.
=> Tolerate missing keyword color; decode CSS named colors

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ImagePreviewer.java
This change addresses an issue which prevents Markdown images from showing when they don't have any attributes; it simply adds a `null` check so that these images can be correctly previewed.
Fixes https://github.com/rstudio/rstudio/issues/4087.
=> Allow for attribute-free Markdown images

src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobProgress.java
Ensures that the job's completion status is visible when the job is finished running.
Fixes https://github.com/rstudio/rstudio/issues/4110.
=> Always show status for completed jobs

src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/JobManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobLauncherDialog.java
This change addresses an issue in which selecting a different script doesn't update the name of the job in the Jobs pane. The fix is to delay the generation of the job name until the dialog has been dismissed.
Fixes https://github.com/rstudio/rstudio/issues/4114.
=> Delay job name computation until file choice is final

src/cpp/desktop/DesktopWebPage.cpp
Closes #4045 by ensuring that our `target="_blank"` workaround only fires when an IDE-surfaced window is opening a link. This effectively allows for `window.open()` to work as expected in Shiny applications; this is required for e.g. the reactlog.
=> allow reactlog windows to open (closes #4045)

src/cpp/session/modules/SessionPackages.R
Closes #4083. There was confusion in my refactoring of the old `.rs.listInstalledPackages()` routine around loaded vs. attached packages; we use the name 'loaded' here but are referring to attached packages.
We also make sure we properly handle the case where a package is installed in multiple libraries by checking the attached package's path explicitly.
=> properly report attached packages in Packages pane (#4083)

src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
This PR is a bandaid for https://github.com/rstudio/rstudio/issues/4075.
The issue here is a bit ugly. When we want to run an asynchronous R process, we generate a command line invocation of the form:
R -e <command>
This implies that `<command>` needs to be encoded in the 'right' encoding if it contains multibyte characters. What is the correct encoding? Currently, `utf8ToSystem()` attempts to match the encoding associated with the current R locale, but that may not be the actual default encoding used by the system, or the command console.
Fortunately, we can sidestep the issue: R knows how to interpret unicode escapes, so if we replace any multibyte characters by their unicode escape equivalent, the command string should be plain ASCII and will "just work" regardless of the current …
=> band-aid for encoding issues in rmarkdown render

src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PublishingPreferencesPane.java
This change adds a help link to the Publishing preferences pane which contains instructions for resolving various common publishing issues.
=> Add link to deployment troubleshooting doc

src/cpp/session/modules/SessionDataImportV2.R
This PR fixes an issue caused by the latest version of `tibble`.
Previously, we relied on the ability to set the names of a `data.frame` to NULL, e.g.
``` r
> names(unname(mtcars))
NULL
```
This is now disallowed by `tibble`, and instead names are filled with `NA`s:
``` r
> names(unname(tibble::as_tibble(mtcars)))
[1] NA NA NA NA NA NA NA NA NA NA NA
```
The solution is to unclass the data object before calling `unname()`. Since we want to treat the `data.frame` like a list, we just convert it to a list first.
Note that this issue also affects v1.1, unfortunately.
```
> packageVersion("tibble")
[1] '2.0.0'
```
=> handle tibbles in data import (#4138)

src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java
This PR fixes an issue where RStudio could seem to accumulate lag after session restarts, if the library paths had changed between each session.
The issue occurs because we re-generate the package table somewhat eagerly here:
https://github.com/rstudio/rstudio/blob/6018fb82c4df77d9af39e0ade4982219b70662e3/src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java#L107
but we never unbind the old `packagesTable_` element from the data display. This means that, as time goes on, we will eventually have a single data provider attempting to update the display of multiple (invisible) package panes, with the cost of building the HTML for package tables that are never actually attached to the DOM.
=> unbind old packages display from data provider

src/cpp/session/modules/SessionJobs.R, src/cpp/session/modules/jobs/SessionJobs.cpp
This small change makes it possible to specify a job name when running a script job via the API. The job name was formerly derived from the name of the script (and still is, if you don't specify a name explicitly).
Closes #4176.
=> Allow for supplying job name when running a script as a job via API

src/cpp/r/R/Api.R, src/cpp/session/SessionClientEvent.cpp, src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp, src/cpp/session/modules/SessionSource.cpp, src/gwt/src/org/rstudio/studio/client/server/model/RequestDocumentCloseEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/SourceServerOperations.java
This change makes it possible to close documents using the rstudioapi (just as it's possible to save them). Documents are saved before closing by default, but this can be overridden by passing `save = FALSE`.
=> Add rstudioapi method for closing documents

NEWS.md, src/cpp/core/include/core/r_util/RVersionInfo.hpp, src/cpp/r/CMakeLists.txt, src/cpp/r/RVersionInfo.cpp, src/cpp/r/include/r/RSxpInfo.hpp, src/cpp/r/include/r/RVersionInfo.hpp, src/cpp/session/modules/SessionEnvironment.R, src/cpp/session/modules/environment/EnvironmentUtils.cpp
Currently, ALTREP objects (new in R 3.5.0) are fully materialized by RStudio's environment pane, since it calls `object.size()` on them. This change protects these objects from premature evaluation by avoiding the environment pane's size/length inspection on objects with the `alt` flag set (indicating an ALTREP). 
Note that this does not protect the objects from any type of materialization at all; the first few elements will still be materialized by `str()`, which we continue to call. 
Fixes #4171.
=> Avoid early materialization of ALTREP objects

Jenkinsfile, docker/jenkins/Dockerfile.bionic-amd64
Ubuntu Bionic includes a newer libssl than its predecessor. This isn't a problem for RStudio Desktop 1.1 (which does not link libssl), but it is for RStudio Desktop 1.2 (which does). This change adds a Docker container in which to build bionic-compatible releases, and instructs Jenkins to add desktop and server builds in the new container.
Fixes https://github.com/rstudio/rstudio/issues/4196.
=> add builds for Ubuntu Bionic

Jenkinsfile
This change adds RStudio Server for OpenSUSE 15 to our build matrix. It was not formerly possible to compile on this platform because of a third-party header library we use; I've added a workaround to make it possible to do this in https://github.com/rstudio/rstudio/commit/66a8428397ace06c2be0e1da445c01f3c9f1abaa. See #3146 for further discussion. 
Fixes https://github.com/rstudio/rstudio/issues/3146.
=> Compile RStudio Server for OpenSUSE 15

src/gwt/src/org/rstudio/studio/client/rsconnect/RSConnect.java
This change fixes a regression in which R Notebooks could not be published to RPubs; the change is just to add `.nb.html` to the whitelisted extensions to publish.
Fixes https://github.com/rstudio/rstudio/issues/4234.
=> Allow R Notebooks to be published to RPubs

src/gwt/src/org/rstudio/studio/client/rsconnect/RSConnect.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
Currently, trying to publish websites from RStudio when not using a website project results in some unexpected behavior. The worst of this is that if you try to publish the website as rendered content, you'll get an indecipherable error. 
This change does not make it possible to publish static websites conveniently from the IDE. However, it does make the scenario less broken in two ways:
- Clicking Publish on an R Markdown document in a website folder now works the same whether you're in a website project or not.
- If we ever get into a situation where we're collecting files to deploy but have no actual folder to collect them from, we bail earlier with a more useful error.
Fixes https://github.com/rstudio/rstudio/issues/3754.
=> Fix error when attempting to publish rendered website from non-website project

dependencies/windows/Install-RStudio-Prereqs.ps1
Bumped up jdk8 version installed by bootstrapper; the one previously installed is no longer available for download.
=> Update jdk8 version on Windows

src/cpp/core/http/Response.cpp, src/cpp/session/modules/SessionFiles.cpp
This is corrected by setting the correct content type, and if the content type indicates compression, not recompressing the content in the output stream. Fixes #4270
=> Fixed a bug where tar.gz files would be corrupted when downloaded from Firefox

src/cpp/core/MiscellaneousTests.cpp, src/cpp/core/include/core/collection/LruCache.hpp
Before, updating or removing an entry from the cache required a linear search on keys to be performed. Now, the operation completes in constant time (simply updating some pointers)
=> Improve LruCache implementation

src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
This change fixes an issue in which paths containing characters that are representable in the C locale but aren't in the lower ASCII set cause the Knit command to fail. It extends the work done in https://github.com/rstudio/rstudio/pull/4126 so that applies not only to characters not representable in the C locale but to any character not in the first 127 (7-bit) ASCII set. 
Fixes https://github.com/rstudio/rstudio/issues/4254.
=> Apply Unicode escaping to high ASCII characters

NEWS.md, dependencies/windows/install-dependencies.cmd, src/cpp/session/CMakeLists.txt
This change upgrades to the latest version of Pandoc, 2.6, on Windows (only), primarily to mitigate a large number of user-reported crashes with Pandoc 2.5.
Fixes https://github.com/rstudio/rstudio/issues/4072.
=> Upgrade to Pandoc 2.6

dependencies/common/install-dictionaries, dependencies/windows/install-dependencies.cmd
The `rstudio-dictionaries` S3 bucket is using a *very* disproportionate amount of bandwidth. There's no obvious reason for this, but it could be that something's decided to use it as a source, or that its publicly enumerable status is attracting lots of spiders and indexers.
Either way, since our intent is not to be the world's dictionary host, this change moves our dictionaries into the `rstudio-buildtools` bucket, where it is publicly accessible but not enumerable. Once it's been in place for a few weeks, we'll remove the dictionaries from the old location.
=> Install dictionaries from buildtools

src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
This PR improves the default behavior of Copy To, making it a bit easier to ensure that one doesn't accidentally recursively copy a folder into itself.
When attempting to copy a directory, we now initialize the file picker from the parent directory of the associated directory.
Closes #3071.
=> better defaults when invoking Copy To w/directory (#3071)

src/cpp/session/modules/SessionEnvironment.R, src/cpp/session/modules/environment/EnvironmentUtils.cpp, src/cpp/session/modules/environment/EnvironmentUtils.hpp, src/cpp/session/modules/environment/SessionEnvironment.cpp
RStudio is already aware of ALTREP objects and avoids attempts to compute their size (which cause them to materialize). However, ALTREP objects can be inside of other objects, and we need to avoid computing the size of those, too. A good example is data frames generated by the vroom package (https://github.com/jimhester/vroom), which are not ALTREP objects themselves but which contain ALTREPs. 
This change implements a simple form of recursive scanning for ALTREP objects. It is intentionally limited to vectors (e.g. data frame columns), and the reentrancy, depth and breadth of the search are also constrained to avoid accidental traversal of large or pathological objects.
Fixes https://github.com/rstudio/rstudio/issues/4171.
=> Scan for nested ALTREP objects

src/cpp/session/postback/CMakeLists.txt
The `rpostback` executable currently has a dependency on OpenSSL from Homebrew. This change replaces that dependency with one on our bundled copy of OpenSSL (as we do for the other binaries we ship on MacOS). 
Fixes https://github.com/rstudio/rstudio/issues/4297.
=> Reroute OpenSSL libraries for rpostback

src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/ShellPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressWidget.java
A while back, we fixed https://github.com/rstudio/rstudio/issues/2264 by adding a short delay from the time you click in the output in the Console to the time that we send focus to the input element, so that we have time to receive a second (double) click if it occurs. 
This delay is widely reported as being much more irritating than the issue it addresses, so this change hides it behind a preference that defaults to off (so that folks who are fond of double-clicking to extract words from the console output can still do so).
Ideally we'd have our cake and eat it too, by detecting double-clicks retroactively, but this is very difficult to do and certainly more bug prone than we'd want to take at this point in the release.
=> Make console double-click selection optional

src/cpp/session/SessionConsoleProcessSocket.cpp, src/cpp/session/SessionOptions.cpp, src/cpp/session/include/session/SessionConsoleProcessSocket.hpp, src/cpp/session/include/session/SessionConstants.hpp, src/cpp/session/include/session/SessionOptions.hpp
This was motivated by some symptoms reported by a customer and should hopefully help us understand this and other websocket failures we've hit in the wild.
- added another rsession config option so our websocket library will emit diagnostics to the R console when terminal websockets are being used. Intended for troubleshooting tricky customer scenarios when they are getting their installations configured (outputs to R console, so not something that will be left enabled for long!).
- lengthen the previously implicit websocketpp handshake timeout from 5 seconds to 15 seconds
- catch and log websocketpp fail handler; may help us identify some failure modes we aren't currently aware of
Have another PR to update the RSP admin guide to mention this new option, plus two other terminal websocket …
=> additional diagnostic tools for terminal websockets

src/cpp/session/modules/SessionPackages.R
Attempts to access `mtime` may be unreliable -- in some cases, they can return `NA` if the modification time is either unknown or not available to the user for some reason.
To avoid this, we now serialize the current time as reported by `Sys.time()` when the directory is created, and use that in lieu of the `mtime` if it is unreadable for some reason.
Closes #4312.
=> defend against unreliable mtime

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
Fixes #2740. It appears that the clipboard-related commands are unreliably when not executed through a menu item; instead, we use the APIs directly to read / write clipboard text.
=> fix for emacs-style kill / yank

src/cpp/desktop/DesktopMain.cpp
Prefers the software render mode over Remote Desktop due to known issues trying to use the accelerated render engine; fixes https://github.com/rstudio/rstudio/issues/4313.
=> Use software rendering on Windows remote desktop

src/cpp/session/modules/SessionPath.cpp
Previously, we were constructing regular expressions based on entries within files located within `/etc/paths.d`, and this could cause failures to launch if files with entries that were not valid regular expressions were present.
The fix here is to avoid the use of regular expressions and just handle the path entries as regular strings.
=> avoid using regex when building PATH (closes #2079)

src/cpp/session/modules/SessionCodeTools.R
Rather than hack together our own deparser, we just rely on the R deparser to give us something useful and then clean up the output afterwards.
Closes #4324.
=> use R deparser when deparsing download options (#4324)

docker/jenkins/Dockerfile.windows
no rush on this, and it can land wherever makes the most sense -- we'll start setting it using the env variable when building the image as soon as we need it!
=> set default jenkins swarm version to 3.15 for win builder

src/cpp/session/modules/rmarkdown/NotebookPlots.cpp
Closes https://github.com/rstudio/rstudio/issues/1795. The underlying issue, IIUC, is that `FilePath.children()` does not return files in lexically-sorted order; rather, it just uses whatever ordering the underlying inodes have on the filesystem.
Since we construct lexically-ordered names for these files, pre-sorting should resolve the behavior.
=> ensure ordering of files when processing plots

src/gwt/src/org/rstudio/core/client/widget/WidgetListBox.css, src/gwt/src/org/rstudio/core/client/widget/WidgetListBox.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PublishingPreferencesPane.java
This change reduces the height of the publishing account list in Global Options to fix https://github.com/rstudio/rstudio/issues/4346.
The change also ensures that the "No accounts connected" text is correctly centered in the box (it was previously set with 30% margin, which could be very off-center depending on the parent's height).
=> Rreduce size of publish account list to fix options overflow

src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
This change fixes a long-standing issue in which a cancelled file open (for example, because the file is too big) makes it impossible to open any more files.
The problem is that the file open queue processing doesn't proceed unless success or failure to open occurs (and cancellation is neither); the fix is simply to keep processing after a cancellation (as we already do after a failure). 
Fixes https://github.com/rstudio/rstudio/issues/4341.
=> Continue processing open file queue after cancellation

dependencies/common/install-boost
When attempting to produce a package build on the (newly-coming) Vagrant build machine, the following compiler warnings are emitted during link:
```
[ 61%] Linking CXX executable RStudio.app/Contents/MacOS/RStudio
ld: warning: object file (/opt/rstudio-tools/boost/boost_1_63_0/lib/libboost_system.a(error_code.o)) was built for newer OSX version (10.14) than being linked (10.12)
ld: warning: object file (/opt/rstudio-tools/boost/boost_1_63_0/lib/libboost_filesystem.a(operations.o)) was built for newer OSX version (10.14) than being linked (10.12)
ld: warning: object file (/opt/rstudio-tools/boost/boost_1_63_0/lib/libboost_filesystem.a(unique_path.o)) was built for newer OSX version (10.14) than being linked (10.12)
ld: warning: object file …
```
=> enforce macOS 10.12 minimum version for Boost

src/cpp/session/modules/SessionThemes.cpp
Today, themes do not work in RStudio if their filenames contain URL-escaped characters. 
This happens because the theme filenames are not URL-encoded, but they are URL-decoded. Consequently, any character in the filename that could be interpreted as URL-encoded causes a replacement, after which the filename is incorrect.
The fix is simply to URL-encode the filename before passing it to the client.
Fixes https://github.com/rstudio/rstudio/issues/4372
=> URL encode theme names for client

src/cpp/session/modules/SessionDataViewer.R
This small change addresses an issue on Windows in which characters that cannot be represented in the system encoding are not shown correctly in the data viewer.
The problem is that R's `format()` method mangles these characters, and the fix is to not call `format()` on character columns -- `format()` is, as its docs state, typically used for numerics. 
A possible downside is that, since `format()` is a generic, it's no longer possible for packages to provide their own formatters (pretty printers) for non-numeric data hosted in the data viewer.
Fixes https://github.com/rstudio/rstudio/issues/4193.
=> Only format numeric values when preparing data for viewing

src/cpp/session/modules/sql/SessionSql.R, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/SqlCompletionManager.java
This PR improves the display + ordering of completions in the following ways:
1. In contexts where tables are expected, tables (and schemas) are shown;
2. In other contexts, we assume field names are most useful and show those first;
3. For fields with a known source, we also display that source in the completion list.
Examples:
One downside is that, for field names which exist in multiple databases, we don't properly complete / disambiguate the completions in the shown completion list, but I don't think that's worth fixing for v1.2.
=> improve ordering + display of SQL completions (#4377)

src/cpp/session/projects/SessionProjects.cpp, src/gwt/src/org/rstudio/studio/client/projects/ProjectOpener.java, src/gwt/src/org/rstudio/studio/client/projects/model/ProjectsServerOperations.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
This change improves the "open directory as project" feature introduced in https://github.com/rstudio/rstudio/pull/1030. Formerly, we always created an .Rproj file in the directory if one matching the directory name was not found; this can result in multiple .Rproj files in the directory (which cause a good deal of confusion downstream). Now, we use an .Rproj in the directory if we can, regardless of its name.
There's probably a separate bug here regarding dealing with two or more .Rproj files in a directory gracefully, but it's less like we could make a scoped fix for that. This change only touches code that runs when opening a directory as a project.
Fixes https://github.com/rstudio/rstudio/issues/4382.
=> Use existing .rproj file (if any) when opening directory

dependencies/common/install-boost, dependencies/linux/README, dependencies/linux/install-qt-sdk, dependencies/osx/install-qt-sdk-osx, dependencies/windows/install-qt-sdk-win.cmd, docker/jenkins/Dockerfile.bionic-amd64, docker/jenkins/Dockerfile.centos7-x86_64, docker/jenkins/Dockerfile.debian9-x86_64, docker/jenkins/Dockerfile.opensuse15-x86_64, docker/jenkins/Dockerfile.windows, docker/jenkins/Dockerfile.xenial-amd64, package/osx/make-package, src/cpp/desktop/CMakeLists.txt, src/cpp/desktop/DesktopMain.cpp
This PR updates us from 5.11.1 to 5.12.1 (on Linux + macOS), and 5.12.0 to 5.12.1 (on Windows).
The associated SDKs for Linux and Windows have been generated and uploaded to S3, so hopefully build machines should be ready to go after this PR.
Older Linux desktop environments with old dbus will remain on Qt 5.10.1 as we don't have any clean mechanism for bringing them to Qt 5.12.1.
We'll want to wait until the macOS build machine has been updated to Mojave before merging this as well.
=> update to Qt 5.12.1

src/cpp/core/ExponentialBackoff.cpp, src/cpp/core/include/core/ExponentialBackoff.hpp
Also ensure callback is only run up to and never more than max tries. Also reworked calculation of exponential timer so that it works for any time duration, not just milliseconds, and made it resilient to overflow. Fixes https://github.com/rstudio/rstudio-pro/issues/918
=> Improved ExponentialBackoff to be thread safe

src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/LauncherJobsPaneWidgets.java
Even though this UI is never shown, it still needs to return a valid widget or some upstream code will throw a null exception.
Fixes #4400
=> fix javascript exception at startup by returning a valid widget

src/cpp/desktop/DesktopGwtCallbackMac.mm
This should (🙏 ) fix the rendering issues seen on Sierra / High Sierra when using Qt 5.12.1 on macOS.
Can confirm at least it fixed things on my macOS High Sierra VM.
Closes https://github.com/rstudio/rstudio/issues/4409.
=> only attempt to change titlebar color on Mojave

src/gwt/src/org/rstudio/core/client/cellview/ScrollingDataGrid.java, src/gwt/src/org/rstudio/core/client/widget/RStudioDataGrid.java, src/gwt/src/org/rstudio/studio/client/packrat/ui/PackratActionDialogContents.java, src/gwt/src/org/rstudio/studio/client/packrat/ui/PackratResolveConflictDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionsPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java
This PR augments what was done in https://github.com/rstudio/rstudio/pull/3078 to find and hide rogue `<div>` elements that would cause scrollbars to render in the IDE unnecessarily.
The main changes here are:
1. Use `RStudioDataGrid` rather than `DataGrid` throughout;
2. Use `getElementsByTagName()` to retrieve the list of `<div>`s that might need surgery.
Closes #4431.
=> perform more extensive surgery on GWT DataGrid

src/gwt/src/org/rstudio/core/client/dom/DomUtils.java, src/gwt/src/org/rstudio/core/client/widget/RStudioDataGrid.java
This refines the previous PR #4436, avoiding the potential need to iterate over a large number of elements in JavaScript.
(This of course does still ask Chromium to iterate through all child elements of the DataGrid, but it's far faster to do that through the `querySelectorAll()` API than manually in JavaScript)
Some profiling suggests that the time spent drawing rows of a DataGrid dwarfs the time spent enumerating these elements so I think this should be good enough.
=> use query selector to avoid capturing too many divs

src/gwt/build.xml
Get rid of `ant superdevmode` for running the Java-based classic devmode that has been deprecated for years now. We use `ant devmode` to run the modern browser-based "superdevmode" so this still being there is a bit confusing.
=> remove the deprecated classic superdevmode target

src/gwt/src/org/rstudio/core/client/StringUtil.java, src/gwt/src/org/rstudio/core/client/TextCursor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitChangelistTable.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPresenter.java, src/gwt/test/org/rstudio/core/client/StringUtilTests.java
One of the fixes listed for GWT 2.8.2 is `Missing bounds check in String.charAt`.
Sure enough this is causing some exceptions in our code where we try to get chars off the end of a string (or before in one case, i.e. -1).
Fixes #4416 
Also fixes case where typing with cursor at column zero of the Console would throw an exception.
I did a quick survey of the uses of `charAt` and put in some preventative measures, but certainly possible there are things I missed so we should keep an eye out for this.
=> fix exceptions caused by gwt 2.8.2 checking charAt bounds

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
When the URL ends with a "file" (e.g. grid.html) the "file" part should not be counted when determining how many levels to go up (with "../") for the theme link element.
Fixes #3295.
=> Fix an issue where themes are sometimes not loaded due to incorrect relative paths.

dependencies/linux/install-dependencies-bionic, dependencies/linux/install-dependencies-debian
Setting up a new Ubuntu Bionic dev VM, and discovered that `install-dependencies-debian` script doesn't quite work for it. Openssl, among other things.
Maybe we could/should fix our debian script to handle all permutations and the new 1.3 dependencies, but instead I created a new bionic-specific script, based on installing the same stuff as the bionic Dockerfile.
I didn't try to separate out Pro-only stuff, so this script can be used to configure a machine for both open source and Pro development. It doesn't seem worth the effort or the minor disk-space savings to figure out what's Pro-only.
Unlike our other scripts, this also installs R (if not already installed), and the java-8 openjdk.
You can get a Linux dev environment up and running with the following:
- Install Ubuntu Bionic …
=> Bionic dev bootstrapper script

src/cpp/session/modules/SessionRCompletions.R
Closes #4480. This issue reproduces all the way back to v0.99 and requires an uncommon bit of R code in the user's file so no need to take it for v1.2 I think.
=> validate object size when introspecting for completions

src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
Fixes #4478 
This is a regression introduced June 2018 via https://github.com/rstudio/rstudio/commit/468c41cd36431b16ae0c6b3b155e94243145d51c#diff-fd534b720e83ffa9ff478c434ab1c039
- dialogState_ can be null, as seen in onInit()
- in that case, cannot dereference it (but .cast() is ok on a null JavaScriptObject; and this is what the code used to do)
Once the exception is triggered, will keep happening due to ongoing attempt to persist the settings (which is interrupted by the exception).
Presumably once you've done an actual Find in Files search, this field is no longer going to be null, so the problem stops happening.
=> Fix javascript exception triggered by showing Find in Files dialog

src/gwt/src/org/rstudio/studio/client/workbench/views/BusyPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/JobsPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/JobsTab.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/LauncherJobsPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/LauncherJobsTab.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/events/JobsPresenterEventHandlers.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/events/JobsPresenterEventHandlersImpl.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/JobState.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/markers/MarkersOutputPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/markers/MarkersOutputTab.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/renderrmd/RenderRmdOutputPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/renderrmd/RenderRmdOutputTab.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTab.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java
I was wondering why the Launcher tab was triggering deferred tab loading on Open Source, where it shouldn't ever need to. Some investigation revealed quite a few tabs doing this, defeating the purpose of the deferred mechanism's use of GWT code splitting.
The goal is that the presenter and all related goo shouldn't be downloaded and instantiated until a given tab is made visible. Just having the tab present at startup, but unselected, shouldn't be loading that stuff. Same, of course, with tabs that are not even shown.
This fixes Jobs, Launcher (I may need to do additional tweaks in Pro when I merge this in), Terminal, and Markers.
They key is not talking to the Shim unnecessarily, whether from the Tab itself or via an event such as SessionInit; instead the Tab should only pass these along …
=> Fix unnecessary deferred tab triggering for Jobs, Launcher, Terminal and Markers tabs

src/gwt/src/org/rstudio/core/client/StringUtil.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java, src/gwt/test/org/rstudio/core/client/StringUtilTests.java
GWT 2.8.2 added range check + exception to String.charAt (standard Java behavior, but was previously missing).
Per advice from @kevinushey in prior round of fixes, added a "safe" StringUtil.charAt that can be used in places where it isn't trivial to accommodate the new behavior.
This particular instance was being hit by autocomplete code when typing near first column of the R Console.
=> more fixes for new behavior of String.charAt in GWT 2.8.2

src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneConfig.java
Fixes #2101 
Fixing in 1.3, but this also seems like a good candidate for a 1.2 patch release.
This bug is triggered if you move the Viewer pane to the same pane as the Presentation pane (the upper-right pane, by default). It goes on the end of the tab list for that tabset, triggering failure of pane layout validation here:
https://github.com/rstudio/rstudio/blob/c7879dedea8421c6d27dbab2ba3b7f08cfa90111/src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneConfig.java#L214-L223
Easy fix.
=> fix bug where pane layout customization lost if Viewer moved to other pane

src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackageLibraryUtils.java
This PR renames the title used in the Packages pane from Packrat Library to Project Library.
This is primarily for `renv`, since the private library as created by `renv` is discovered within the project and so called a Packrat library by RStudio.
I think 'Project Library' is still clear enough that it makes sense for both the Packrat + renv cases.
@jmcphers it would be nice to get this in for v1.2 now that we've made `renv` public; let me know what you think.
=> switch title for project library

dependencies/windows/Install-RStudio-Prereqs.ps1, docker/jenkins/Dockerfile.windows, package/win32/cmake/modules/NSIS.template.in
- installs NSIS via Chocolately, and gets us on the latest version
- installing newer NSIS does replace older one so if we're using single container image for 1.2 and 1.3 builds this should wait until they are separated
- the tweak to NSIS.template.in matches change made in template included with more recent CMakes ("recent" being several years old at this point)
=> update to latest NSIS installer tool on Windows

src/gwt/src/org/rstudio/core/client/command/AppCommand.java, src/gwt/src/org/rstudio/core/client/command/ApplicationCommandManager.java, src/gwt/src/org/rstudio/core/client/command/EditorCommandManager.java, src/gwt/src/org/rstudio/core/client/command/KeyCombination.java, src/gwt/src/org/rstudio/core/client/command/KeyMap.java, src/gwt/src/org/rstudio/core/client/command/KeySequence.java, src/gwt/src/org/rstudio/core/client/command/KeyboardShortcut.java, src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java, src/gwt/src/org/rstudio/core/client/command/UserCommandManager.java, src/gwt/src/org/rstudio/core/client/dom/EventProperty.java, src/gwt/src/org/rstudio/core/client/widget/ModifyKeyboardShortcutsWidget.java, src/gwt/src/org/rstudio/core/rebind/command/ShortcutsEmitter.java, src/gwt/src/org/rstudio/studio/client/application/events/SetEditorCommandBindingsEvent.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/common/vcs/ShowPublicKeyDialog.java, src/gwt/src/org/rstudio/studio/client/server/Bool.java, src/gwt/src/org/rstudio/studio/client/workbench/addins/AddinsCommandManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionPopupPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceCommandManager.java
**NOTE: do not merge**; this PR unfortunately runs afoul of a Qt bug (https://bugreports.qt.io/browse/QTBUG-69442) and so cannot be merged until that issue is fixed upstream.
---
This PR intends to fix https://github.com/rstudio/rstudio/issues/2712.
For background: RStudio maintains its own key maps, attempting to map key codes to key names (and vice versa). Unfortunately, this mapping is not unique. As an example, German keyboards (QWERTZ) contain keys for insertion of both <kbd>,</kbd> and <kbd><</kbd>, and they both map to the same key code (`188`). (This is perhaps an artifact of <kbd>,</kbd> and <kbd><</kbd> sharing the same physical key on a QWERTY keyboard, with the <kbd>Shift</kbd> modifier controlling which of the two keys is actually inserted.)
Because of this, we erroneously …
=> show key as appropriate for current keyboard layout

dependencies/windows/install-boost.cmd, dependencies/windows/install-boost/install-boost.R, src/cpp/CMakeLists.txt, src/cpp/core/http/CSRFToken.cpp, src/cpp/desktop/DesktopComUtils.hpp
This PR makes a couple fixes needed for Boost 1.69.0 on Windows:
1. We need to explicitly request `signals2` when building our Boost bundle;
2. We need to update the library suffixes used with Boost in CMake.
Also made some tweaks to build the tarball that we actually want to push to S3, and fixed a couple compile errors I saw when testing Boost.
=> update Boost installer scripts

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceTheme.java
=> Fix an issue caused by old versions of RStudio saving themes with a leading slash.

dependencies/windows/Install-RStudio-Prereqs.ps1, docker/jenkins/Dockerfile.windows
Requires rebuilding the Windows build docker image.
- on a dev box setup with the prereqs powershell script, you'll need to uninstall cmake 3.12.1 via `choco uninstall cmake` then run the updated powershell script
=> install latest cmake on Windows to fix a build break caused by recent boost tweaks

docker/jenkins/Dockerfile.windows
Doesn't seem to be necessary for the Windows build. I was able to build in docker without this (but my test build doesn't do the Jenkins-based signing and upload steps so don't know for sure).
=> cygwin doesn't install cleanly in dockerfile so remove it

src/cpp/core/json/JsonTests.cpp, src/cpp/monitor/metrics/Metric.cpp, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/modules/SessionAgreement.cpp, src/cpp/session/modules/SessionErrors.cpp, src/cpp/session/modules/SessionGit.cpp, src/cpp/session/modules/SessionProjectTemplate.cpp, src/cpp/session/modules/build/SessionBuild.cpp, src/cpp/session/modules/build/SessionSourceCpp.cpp, src/cpp/session/modules/data/DataViewer.cpp, src/cpp/session/modules/environment/EnvironmentUtils.cpp, src/cpp/session/modules/presentation/PresentationState.cpp, src/cpp/session/modules/rmarkdown/RMarkdownPresentation.cpp, src/cpp/session/modules/tex/SessionSynctex.cpp
- triggered by the pattern of returning a `json::Object` from a method declared to return `json::Value`
- because the types don't match (Object is a subclass of Value), RVO is not applied so use `std::move` to suggest move semantics
=> eliminate batch of new c++ warnings from latest macOS compiler

src/cpp/core/http/CSRFToken.cpp, src/cpp/core/include/core/http/CSRFToken.hpp, src/cpp/session/SessionClientInit.cpp, src/cpp/session/SessionHttpMethods.cpp
Currently, session RPCs have implicit CSRF validation via client ID validation. This change adds additional explicit validation. 
Fixes https://github.com/rstudio/rstudio-pro/issues/865; see that issue for further details.
=> Add explicit CSRF validation to all session RPCs

dependencies/windows/Install-RStudio-Prereqs.ps1, dependencies/windows/install-dependencies.cmd, dependencies/windows/install-openssl/install-openssl.R, src/cpp/CMakeLists.txt, src/cpp/core/CMakeLists.txt, src/cpp/desktop/CMakeLists.txt, src/cpp/desktop/synctex/rsinverse/CMakeLists.txt, src/cpp/desktop/urlopener/CMakeLists.txt
My main motivation was to get rid of the hundreds of PDB-related warnings when building (openssl made fixes for this in the 1.1+ series). Plus, probably good to have linked with more complete PDB info for our new crash reporting system.
It's also good to be on a recent openssl build (1.1.1 is the current LTS, supported until 2023, whereas the version we are currently using goes out of support later this year).
I tweaked the build script, rebuilt and uploaded to S3, and made necessary cmake changes.
Note that building 1.1.1 requires a qualified path for the `--prefix`, and requires specifying `--openssldir` (which used to default to a path based on the prefix). Also, newer openssl introduces a dependency on system crypt32.
Developers will need to re-run `install-dependencies.cmd` to pull …
=> upgrade to openssl 1.1.1b for Windows

src/gwt/src/org/rstudio/core/client/widget/SatelliteFramePanel.java, src/gwt/src/org/rstudio/studio/client/shiny/ShinyApplicationPresenter.java, src/gwt/src/org/rstudio/studio/client/shiny/ShinyDisconnectNotifier.java, src/gwt/src/org/rstudio/studio/client/shiny/ui/ShinyApplicationPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPresenter.java
Currently, the _Reload App_ button for Shiny applications does not work in Firefox. 
This is because, unlike Chrome, Firefox allows Shiny to broadcast its `disconnected` PostMessage when it is being torn down during a reload, and RStudio responds to this message by treating the app as stopped.
The fix is to ignore the `disconnected` PostMessage during a reload, which we do by suppressing the notification (for that specific app URL only) from the time that the reload is initiated until the frame hosting the app has loaded.
Will be backported to 1.2-patch.
Fixes https://github.com/rstudio/rstudio/issues/4527.
=> In Firefox, ignore disconnect event during reload

src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
This PR fixes an issue where our attempts to register a middle-click handler would fail.
IIUC the `click` event is normally only emitted for a mouse's primary button; for non-primary buttons we need to manage the "click" ourselves.
In theory, "auxclick" will be a new event for handling non-primary button clicks (https://developer.mozilla.org/en-US/docs/Web/API/Element/auxclick_event) but it looks like that is not yet standardized.
Closes https://github.com/rstudio/rstudio/issues/4379.
=> fix for closing tabs with middle-click

src/cpp/session/modules/environment/EnvironmentMonitor.cpp, src/cpp/session/modules/environment/SessionEnvironment.cpp
This PR fixes an issue where the RStudio UI could fail to load if the user `.Rprofile` opened an R debugger. It appears that `getMonitoredEnvironment()` can, in some occasions, return `R_NilValue` (as opposed to a regular C `NULL`) which we weren't properly handling. Since we attempt to list the monitored environment on client init, if that failed due to an R error, it would inhibit RStudio launch.
I'm not exactly sure what changed to cause this to be an error, but I think the extra safety checks are safe.
Closes https://github.com/rstudio/rstudio/issues/4443.
=> validate we have a 'real' environment before listEnv

src/cpp/core/spelling/hunspell/CMakeLists.txt, src/cpp/core/tex/synctex/CMakeLists.txt, src/cpp/core/zlib/CMakeLists.txt
Crusty old C and C++ third-party code we use; don't want to muck around with it directly, so just turn off the noisy warnings.
=> eliminate another 150 or so Windows build warnings in third-party code

docker/jenkins/Dockerfile.bionic-amd64, docker/jenkins/Dockerfile.centos6-x86_64, docker/jenkins/Dockerfile.centos7-x86_64, docker/jenkins/Dockerfile.debian9-x86_64, docker/jenkins/Dockerfile.opensuse-x86_64, docker/jenkins/Dockerfile.trusty-amd64
Noticed while doing file-diffs across open-source and pro that the dockerfiles are slightly different. 
Additional dependencies are installed for Pro, but it seems unnecessarily complex to have these files be different just to save installing a couple packages.
Also, added what is needed to Dockerfile.centos7 to build server (pro), not just desktop. In case we need to do that eventually.
=> make open-source and Pro dockerfiles the same

src/cpp/session/modules/SessionThemes.cpp
Fixes #4553.
When the theme had no "name" comment, `boost::regex_search` still returned 4 sub_matches. The first had `matched == false`. Since the first element of a `boost::smatch` is the status of the full regex match, we check that value and ignore the rest if it's false. Additionally, this code should now handle when the name comment exists, but the name is empty as well.
=> Fix an issue importing themes without names.

src/gwt/acesupport/acemode/markdown_highlight_rules.js, src/gwt/src/org/rstudio/studio/client/common/spelling/TypoNative.java, src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java
Load the dictionary data in GWT before loading Typo.js to avoid synchronous GET requests. I tried other approaches here and I'm jumping through hoops a bit to avoid modifying Typo.js and, while I think it's still worth it, we're probably pretty close to wanting to fork it for our own purposes as soon as we want to do something just a touch fancier. Considering the library hasn't been touched in any substantial way in over a year this is probably safe to do anyway, it's just the burden of ownership that we'll be taking on.
Markdown parsing rule update: I was originally doing fancier stuff that touched the spelling system and DocDisplay itself to try to be more comprehensive but I think leaning more on our existing rules will keep things simple and we have enough tools to get by. This will …
=> Asynchronous loading for Typo.js, updated markdown link parsing

src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java
Fix for https://github.com/rstudio/rstudio/issues/4563
Looks like events are triggering slightly different between 1.1 and 1.2, in 1.1 importing a file for the first time triggers:
While in 1.2,
Regardless, a better fix is to not trigger both events to update preview when the import preview is launched from the files menu, we don't need to update the preview if we have a path while initializing the dialog.
Notice that this only triggers from the files pane, the "Import Dataset" menus work just fine. The workaround is to click once "Update" in the dialog and this only happens after restarting the R session.
The fix is safe; however, I would encourage significant testing around previewing datasets since this code has not changed in more than a year.
=> Ensure import preview runs from files pane to fix #4563

src/cpp/desktop/Info.plist.in
Closes #4559.
In theory, this is worth considering for v1.2-patch as we don't want RStudio to suck too much battery life using the GPU, but I'm a little worried about making _another_ GPU-related (/ rendering-related) change so close to release, so I think we should make this v1.3-only.
=> enable automatic graphics switching

src/cpp/core/CrashHandler.cpp, src/cpp/rstudio.bat.in
Closes #4499. It looks like `crashpad_handler.exe` launches without issue in package builds, so we now direct RStudio to use that version in those cases.
I also noticed that our package builds were selecting `/subsystem:console` when linking `rstudio.exe`, but (to my surprise) avoiding that and enforcing `/subsystem:windows` didn't seem to make a difference. Fortunately, this does and `crashpad_handler.exe` does seem to launch without issue.
=> prevent creation of crashpad console window

src/cpp/CMakeLists.txt
Provide support for building RStudio with Address Sanitizer support on Mac and Linux (works with clang, including Xcode's, or recent gcc's). Diagnostic tool for runtime detection of various C++ memory misuses. To use, run CMake with RSTUDIO_ASAN defined and rebuild. For example, in CLion I do my debug generation via:
In a perfect world we'd have massive automated code coverage with fuzzing, and would run it in conjunction with an address-sanitizer build. For now, I'm just doing my development with it enabled to see if anything crops up in routine usage.
I did confirm this was working by putting in some temporary badness and observing the output (writes oodles of details to stderr and terminates).
To get more details on a problem, will be necessary to have `llvm-symbolizer` in the path or …
=> support for building with address-sanitizer (ASAN)

dependencies/windows/install-dependencies.cmd
Addresses crash issues described in https://github.com/jgm/pandoc/issues/5037. Closes https://github.com/rstudio/rstudio/issues/4618, and will be backported to 1.2-patch.
=> Update to Pandoc 2.7.2 on Windows

src/gwt/src/org/rstudio/core/client/widget/RStudioDataGrid.java
Closes #4529.
@jmcphers, to the best of my knowledge we don't ever actually want horizontal scrolling for any of the GWT DataGrids we use; we always show and resize columns such that they fill their container. For that reason, I think this PR should be safe, but can you think of any cases where this might not be true?
=> disable horizontal overflow for DataGrid

src/cpp/core/Error.cpp, src/cpp/core/include/core/Error.hpp, src/cpp/core/include/core/json/Json.hpp, src/cpp/core/json/Json.cpp, src/cpp/core/json/JsonTests.cpp
This change lays some groundwork necessary for future user configurability improvements (see #1607), but it's useful on its own. It contains the following improvements to our core JSON library:
**Richer parsing errors** -- there is now an overloaded version of `parse()` that returns an `Error`. It also accepts an error location, so that the parse error can be traced from the point where the parse was attempted rather than from inside the JSON routine itself. The errors returned are part of a new error enum that maps RapidJSON parse errors into a Boost error code for easy routing through the rest of our error management code.
In most cases we'll prefer this to the current version of `parse()` that only tells you whether or not the parse worked (without any diagnostic information about the …
=> JSON parsing and validation improvements

dependencies/linux/install-qt-sdk, dependencies/osx/install-qt-sdk-osx, dependencies/windows/install-qt-sdk-win.cmd
Qt updated the online installer, and broke the previous installer in the process. The new one doesn't work with our existing scripted install.
So, switched to scripting the offline installer. This means a bigger initial download, but should be more reliable and (hopefully) not breakable by Qt changes.
Offline installers pushed to S3.
This will also need to go into 1.2-patch.
=> Qt install fixes

package/linux/CMakeLists.txt
On Linux/X11, Qt depends on libxkbcommon, which typically (but not always) installed. This change adds a dependency on the package on both RPM and DEB based systems.
Fixes https://github.com/rstudio/rstudio/issues/4610 and will be backported to 1.2-patch.
=> Add dependency on libxkbcommon

NEWS.md, src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/include/session/SessionTerminalShell.hpp, src/cpp/session/modules/SessionTerminalShell.cpp, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalShellInfo.java
Fixes #4596
Fixes #4592 
- Detect PowerShell Core (v6) and offer as a shell type
- 1.1 and 1.2 didn't allow specifying a custom shell on Windows, now it does
- add file picker for selecting custom shell instead of just a text field
- if shell exits with non-zero return code, don't close the session pane (helps with troubleshooting)
- if shell startup fails in a way that was logging an error, show the error message via error dialog as well; otherwise these errors look like no-ops in the UI
=> Support PowerShell core and Custom for Windows terminal

src/gwt/src/org/rstudio/core/client/widget/RStudioDataGrid.java
Closes https://github.com/rstudio/rstudio/issues/4662.
Note for testing: I wasn't able to reproduce the bug when working with my laptop's builtin display + builtin trackpad, but was able to reproduce when using an external display + mouse. It may be worth figuring out what the common element is (e.g. is it related to having a mouse plugged in, or having an external display)
=> be more selective in hiding scrollbars

src/cpp/server/ServerPAMAuth.cpp, src/cpp/server_core/http/SecureCookie.cpp, src/cpp/server_core/include/server_core/http/SecureCookie.hpp
This isn't strictly necessary since there's no value to secure, but "always mark cookies as secure when serving over HTTPS" is a rule enforced by many auditing tools, even when the cookie is being cleared.
Fixes https://github.com/rstudio/rstudio-pro/issues/964.
=> Set secure flag when removing cookies over https

src/gwt/www/rstudio.css, src/gwt/www/templates/encrypted-sign-in.htm
This is a much (MUCH) more comprehensive accessibility evaluation, and depth of fixes than we are going to get to for the whole product in 1.3; doing it primarily as a self-education exercise both in performing the evaluation, making and evaluating the fixes.
Fixes #4709
I did not do anything about failure of screen readers on macOS to read JavaScript alerts(). That would require a more significant reworking of the page's client-side form validation technique (a good idea, but not critical and more feature-ish than I wanted to get for this change). We'd probably call this out as an exception in our 1.3 VPAT (assuming we don't fix it).
Also did not do anything about the text boxes and button not showing their focus rectangles; fixing this issue will be a product-wide effort, likely …
=> Accessibility fixes to Server sign-in page

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/ChunkOptionsPopupPanel.java
When selected, this adds `cache = TRUE` (equivalent to `cache = 3`) to the current chunk.
Closes #4704.
=> Includes a chunk caching toggle for RMarkdown chunks

src/gwt/www/templates/encrypted-sign-in.htm
Additional accessibility improvements to the sign-in page. I will update #4709 to reflect this.
- don't use `alert()`, it is not consistently supported by screen readers; instead just leverage the page's existing error reporting mechanism and show "You must enter a username" and so forth directly and trigger screen reader to say it (see below)
- switch the error message live-region to be role="alert" since that's more semantically correct
- add `aria-atomic="true"` to the alert div to improve screen reader behavior as recommended https://www.w3.org/TR/WCAG20-TECHS/ARIA19.html
=> fix alerts/errors shown on sign in page

src/cpp/r/ROptions.cpp
This change fixes an issue causing RStudio to fail to start when the `error` option is set in .Rprofile.
The problem is that, when temporarily disabling a user error handler to execute our own code, we set the `error` option to NULL (`R_NilValue`). In R 3.6.0 this became illegal; the option should be removed, not set to NULL. 
Fixes https://github.com/rstudio/rstudio/issues/4723; fixes https://github.com/rstudio/rstudio/issues/4441.
=> Fix startup failure when using R 3.6.0 and options(error) in .Rprofile

src/cpp/session/resources/themes/dracula.rstheme
Related to issue #3420, where margin isn't set correctly for some dark
themes. Highlight color is based on [Dracula BBEdit theme](https://draculatheme.com/bbedit/).
=> Improve margin and highlight color settings for Dracula theme.

docker/jenkins/Dockerfile.windows
Need to use single-quotes around path, not double-quotes. Confirmed this fixes the image build and successfully ran a package build using the image.
Suspect could also have used \\".
With double-quotes, the regsvr32 call fails during image build:
```
Step 12/15 : RUN regsvr32 /s "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\DIA SDK\bin\msdia140.dll"
---> Running in 6f8e8eb5f7c6
x86 : The term 'x86' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path
was included, verify that the path is correct and try again.
At line:1 char:31
+ regsvr32 /s C:\Program Files (x86)\Microsoft Visual Studio\2017\Build ...
+                               ~~~
+ CategoryInfo          : ObjectNotFound: (x86:String) …
```
=> Fix quoting of path in windows dockerfile

dependencies/windows/Install-RStudio-Prereqs.ps1, src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/cpp/session/include/session/SessionConsoleProcessConnectionCallbacks.hpp, src/cpp/session/include/session/SessionConsoleProcessSocket.hpp
The websocketpp headers spit out quite a few build-warnings, noticed during Windows build that source files that shouldn't care less about websockets were generating these warnings.
SessionConsoleProcess.hpp was pulling these in via SessionConsoleProcessSocket.hpp, just to get at the ConsoleProcessSocketConnectionCallbacks struct. Refactored that struct into a separate header.
This takes the Windows build warning count (debug) from 144 to a mere 96. Almost respectable. Kinda a hobby at this point.
Also unpinned the git version number in the bootstrapper script; the dockerfile doesn't specify a version, so neither should this script.
=> reduce unnecessary inclusion of websocketpp headers

docker/jenkins/Dockerfile.windows
Windows docker image builds started failing with:
```
`CreateComputeSystem .......... The operating system of the container does not match the operating system of the host`
```
This is due to the version of server-core we build with no longer being supported by the image we pull: https://github.com/dotnet/announcements/issues/105
Short-term fix is to specify server-core 1709 instead of letting it pickup default OS for the .NET image. Eventually we'll want to spend quality time with Docker on Windows getting updated to a newer base image.
=> pin server-core 1709 in windows dockerfile

src/cpp/session/modules/SessionPackages.R
RStudio 1.21335 fails to start if `_R_CHECK_LENGTH_1_LOGIC2_=true` is set.  The error message is:
>     The R session had a fatal error.
>     
>     ERROR r error 4 (R code execution error) [errormsg=Error in !is.null(repos) && repos != "@CRAN@" :
>       'length(x) = 5 > 1' in coercion to 'logical(1)'
>     ]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::{anonymous}::evaluateExpressionsUnsafe(SEXP, SEXP, SEXPREC**, rstudio::r::sexp::Protect*, rstudio::r::exec::{anonymous}::EvalType) /var/lib/jenkins/workspace/IDE_open-source-pipeline_v1.2/src/cpp/r/RExec.cpp:171
Setting `options(rstudio.errors.suppressed = FALSE)` in `~/.Rprofile` is _not_ sufficient to workaround this.
=> RStudio 1.21335 fails to start if `_R_CHECK_LENGTH_1_LOGIC2_=true` is set

src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
The version of the `shinytest` package we currently depend on does not work on RStudio Server; this change causes us to depend on a new version shinytest that does work on RStudio Server.
Fixes https://github.com/rstudio/rstudio/issues/4565.
=> Depend on new Shinytest package

src/cpp/session/modules/SessionEnvironment.R
Currently, objects containing ALTREPs cannot be expanded in the Environment pane. This is because we treat them as empty to avoid prematurely unrolling the ALTREPs (which will happen if we try to compute the size of the objects).
This change refines the behavior such that, for data frames containing ALTREP columns (e.g. from sequences or lazy-load packages like vroom), the Environment pane will show the objects as expandable, but not actually ask for data unless the user manually expands the object. This is the same behavior we have today for very large objects.
Fixes https://github.com/rstudio/rstudio/issues/4758.
=> Allow previewing altrep objects

dependencies/windows/Install-RStudio-Prereqs.ps1, dependencies/windows/install-dependencies.cmd, docker/jenkins/Dockerfile.windows
Ant was failing to install the JRE (which is already installed via
the JDK). Use -i to have ant not worry about dependencies, and
stop requesting specific version of ant and 7zip (while we're at it)
because having latest version of these tools is fine.
Still having problems getting msdia140.dll to regsvr32 inside the
container so moved it to the install-dependencies script.
=> fix failure installing ant in windows dockerfile, registing msdia140.dll

docker/jenkins/cloudwatch-config.json
This change adds a CloudWatch configuration file to be used with the Windows build instance. The configuration file collects the logs emitted during instance setup, which are otherwise stored only locally on the machine. 
See: https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/create-cloudwatch-agent-configuration-file.html
=> Add CloudWatch monitor config (for Windows build instance)

src/gwt/src/org/rstudio/studio/client/projects/Projects.java
Looks like #4784 was just caused by a missing error handler, which I've added here.
=> Add missing error handler when creating a new project. Fixes #4784

src/cpp/r/ROptions.cpp
This change completes the (unintentionally) incomplete work in https://github.com/rstudio/rstudio/commit/78e10db4675bad47b5e0c8cc4da3b164e4d4b1cb. Now that we're removing the `error` option entirely when setting it to NULL, we also need to allocate a new options entry when restoring the option. 
Fixes https://github.com/rstudio/rstudio/issues/4787.
=> Add error option if necessary

src/cpp/desktop/DesktopMenuCallback.cpp, src/cpp/desktop/DesktopMenuCallback.hpp, src/gwt/src/org/rstudio/core/client/command/impl/DesktopMenuCallback.java, src/gwt/src/org/rstudio/core/client/widget/ModalDialogTracker.java
- When a GWT-based "modal dialog" is shown, the main menu is now disabled.
- When the last modal dialog is closed, the main menu is reenabled
Fixes #2481 
Fixes #2482
=> Disable desktop main menu when modal GWT dialog is shown

src/cpp/session/modules/SessionEnvironment.R
Variable size should be represented by units from modern standards (i.e., `MB` instead of `Mb`). This pull request by @Qjammer and I addresses issue #1704 by switching from the legacy representation to the SI representation. It also replaces the combination of `capture.output` and `print` with a simple `format` call.
=> Switch environment variables format to SI standard

src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionListPopupPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HistoryCompletionManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/editor/InputEditorDisplay.java
This change makes three ergonomic improvements to the Cmd/Ctrl+Up behavior:
- Pressing Cmd+Up now searches only on characters to the left of of the cursor. 
- After a search, your cursor remains at the point where you initiated the search. This makes it possible for the search to be idempotent; that is, if you search again you'll get the same results.
- Pressing Up while your cursor is not at the beginning or end of a line now implicitly searches for matching commands that begin with the text to the left of the cursor. 
Closes https://github.com/rstudio/rstudio/issues/2771; see that issue for a more detailed description of the behavior.
=> Improve incremental history search by prefix

src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectGrid.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectList.css, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.css, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentStyle.java
This change makes it possible to adjust the the width of the columns in the Environment pane, useful when you're working with data that has long names (or, conversely, long values).
Closes https://github.com/rstudio/rstudio/issues/4020.
=> Allow column resize in Environment pane

src/cpp/conf/rserver-dev.conf
We currently time out after 30 minutes of inactivity, which is more secure in real-world installations but not necessary when running the server in dev mode. This change allows developers to stay signed in for longer.
=> Don't timeout dev RStudio Server sessions

src/gwt/src/org/rstudio/core/client/widget/RStudioDataGrid.java
It seems the prior PR was actually insufficient in resolving this issue. Since we don't ever actually use horizontal scrolling with our DataGrids (we just manage the width of columns visible to the user) I think we can just disable horizontal scrollbars entirely.
Candidate for 1.2 backport.
Closes #4529.
=> disallow horizontal scrollbars for DataGrid

src/cpp/session/modules/NotebookData.R
Closes https://github.com/rstudio/rstudio/issues/3163.
=> remove RGui escapes leaked in with R 3.6

src/cpp/server/extras/admin/rstudio-server.in
Adds ` 2>/dev/null` to kill rsession commands, so that rstudio-server "restart" and "stop" type commands exit successfully when no sessions are actively running
=> Redirect kill rsession error

src/cpp/session/modules/SessionBreakpoints.cpp, src/cpp/session/modules/SessionPackages.cpp
This PR fixes the return types for a couple R functions we define. In particular, this fixes a crash that occurs when:
```
.Call("rs_packageLibraryMutated")
```
is invoked directly. (Miraculously, this still worked somehow where we made calls as e.g. `on.exit(.Call("rs_packageLibraryMutated"))`, but that seems like it was just dumb luck?
Candidate for v1.2 backport.
=> fix incorrect return value for some rs_ functions

src/cpp/desktop/DesktopWebPage.cpp
This PR removes an unneeded (and conflicting) binding for closing windows in satellites. These bindings are already defined by GWT so this should be unneeded.
https://github.com/rstudio/rstudio/blob/48e906ecceb606f7287deab7131d95282faccbb0/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L716-L717
Closes https://github.com/rstudio/rstudio/issues/4727.
=> remove unneeded close window binding for satellites

src/cpp/core/include/core/type_traits/TypeTraits.hpp, src/cpp/r/include/r/RRoutines.hpp, src/cpp/session/modules/SessionPackages.cpp
This PR augments `RS_REGISTER_CALL_METHOD()` to validate the types used in the registered functions, making sure that only `SEXP` arguments are passed through or returned.
The goal is to have a compile-time check on the methods we register to catch issues like https://github.com/rstudio/rstudio/pull/4845 in the future.
=> validate types of registered .Call methods

src/cpp/core/SyslogLogWriter.cpp, src/cpp/core/include/core/FileLogWriter.hpp, src/cpp/core/include/core/LogWriter.hpp, src/cpp/core/include/core/StderrLogWriter.hpp, src/cpp/core/include/core/SyslogLogWriter.hpp, src/cpp/core/system/System.cpp, src/cpp/monitor/MonitorClient.cpp
Fixed bug where additional (programmatic) loggers that were set at a lower priority than the configured loggers would not be logged to due to not taking into account the additional logger levels in the lowest log level calculation
=> Fix additional logger level bug

src/cpp/session/resources/themes/material.rstheme
The material theme's editor max-width column's color is modified to subtly distinguish it from the background and makes it visible, where it previously was not.
partially addresses #3420
=> Modify material theme editor margin color to make it visible

NEWS.md, src/gwt/src/com/google/gwt/user/README.md, src/gwt/src/com/google/gwt/user/client/ui/MenuBar.java, src/gwt/src/com/google/gwt/user/client/ui/MenuBar.java.diff, src/gwt/src/com/google/gwt/user/client/ui/MenuItem.java, src/gwt/src/com/google/gwt/user/client/ui/MenuItem.java.diff, src/gwt/src/com/google/gwt/user/updatepatches.sh, src/gwt/src/com/google/gwt/user/updatesources.sh, src/gwt/src/org/rstudio/core/client/command/AppCommand.java, src/gwt/src/org/rstudio/core/client/command/AppMenuItem.java, src/gwt/src/org/rstudio/core/client/command/BaseMenuBar.java, src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java, src/gwt/src/org/rstudio/core/client/widget/ShortcutInfoPanel.java, src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenu.java, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/workbench/Workbench.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/events/ShowMainMenuEvent.java, src/gwt/www/docs/keyboard.htm
Fixes #4855 
A11y fixes to server main menu, so it can be used with keyboard and screen readers:
- aria roles, states, and properties to permit screen reader access
- keyboard focus fixes to allow navigation of menus with keyboard
- new server-only commands and shortcuts to access main menu via keyboard (desktop already has native techniques for getting to main menu with keyboard)
- null `alt` attribute on cosmetic menu graphics (icons, expando-arrows)
- mark menu layout tables as role=presentation to avoid having rows/columns read out and/or screen readers entering table-navigation mode
I followed the example of Google Docs, and used following keyboard shortcuts:
File - Ctrl+Alt+F
Edit - Ctrl+Alt+I ("i")
Code - Ctrl+Alt+C
View - Ctrl+Alt+V
Plots - Ctrl+Alt+P
Session - Ctrl+Alt+S
Build - …
=> A11y for RStudio Server main menu

src/cpp/r/RSexp.cpp, src/cpp/session/modules/SessionCodeTools.R
A segfault was reported to Sentry here: https://sentry.io/organizations/rstudio/issues/1050032194
It looks like we don't guard well against failures to create the primitive wrapper functions used by the diagnostics engine. This PR adds the necessary guards and handles failure more appropriately.
We also no longer rely on `capture.output()` as that may be brittle if the user already has their own sinks set up.
=> guard against errors when building primitive wrappers

src/cpp/core/libclang/LibClang.cpp, src/cpp/session/modules/clang/RCompilationDatabase.cpp
Should fix some issues with C++ diagnostics on macOS.
Candidate for v1.2-patch since I think this implies C++ autocompletion / diagnostics can be broken if Xcode is also installed in addition to command line tools.
=> tweaks for C++ diagnostics on macOS

src/cpp/r/session/RSession.cpp, src/cpp/r/session/graphics/RGraphicsDevice.cpp, src/cpp/r/session/graphics/RGraphicsPlotManipulatorManager.cpp, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/SessionRpc.cpp, src/cpp/session/modules/SessionAskPass.cpp, src/cpp/session/modules/SessionAskSecret.cpp, src/cpp/session/modules/SessionAuthoring.cpp, src/cpp/session/modules/SessionBreakpoints.cpp, src/cpp/session/modules/SessionCodeSearch.cpp, src/cpp/session/modules/SessionConsole.cpp, src/cpp/session/modules/SessionHistory.cpp, src/cpp/session/modules/SessionPackrat.cpp, src/cpp/session/modules/SessionPlumberViewer.cpp, src/cpp/session/modules/SessionShinyViewer.cpp, src/cpp/session/modules/build/SessionBuild.cpp, src/cpp/session/modules/build/SessionSourceCpp.cpp, src/cpp/session/modules/clang/SessionClang.cpp, src/cpp/session/modules/data/DataViewer.cpp, src/cpp/session/modules/environment/SessionEnvironment.cpp, src/cpp/session/modules/presentation/SessionPresentation.cpp, src/cpp/session/modules/shiny/SessionShiny.cpp, src/cpp/session/modules/viewer/SessionViewer.cpp, src/cpp/session/projects/SessionProjectContext.cpp
This PR ports all of our `.Call()` method registration to use `RS_REGISTER_CALL_METHOD()`.
`RS_REGISTER_CALL_METHOD()` is preferred for a couple reasons:
1. It validates that the registered function accepts and returns only SEXPs;
2. It automatically computed the number of arguments accepted by the function. (it's easy to forget to update the argument count if you change the signature of a registered function)
Fortunately all of our existing registrations look correct. The only minor change was the renaming of an internal function `createGD` -> `rs_createGD`, for consistency.
=> use RS_REGISTER_CALL_METHOD for .Call method registration

src/cpp/session/modules/SessionCodeTools.R
This PR removes some of the old code that attempts to briefly load + unload a package's DLL to figure out what native symbols were exported by the package. Because that attempt to load the DLL also implies running the package's `R_init_*` routine, packages may run arbitrary code that can do things like unexpected load the package namespace. This can occur in a context where the package is not able to be loaded, leading to crashes like https://github.com/rstudio/rstudio/issues/4873.
These symbols are only used in the project indexer:
https://github.com/rstudio/rstudio/blob/70ebffc005132c33a573b1b5e9cec3e0c51b289c/src/cpp/session/modules/SessionCodeSearch.cpp#L2539-L2553
and so omitting those symbols when they're not available shouldn't be a big loss.
=> remove DLL load/unload code

src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/www/index.htm
Working on noise-reduction by cleaning violations flagged by automated tools (Lighthouse audit in Chrome, axe from deque).
I had the body element marked as role=application, but axe gives best-practice violation on that, "ARIA role must be appropriate for the element".
Both Lighthouse and axe give best-practice violation for lack of a top-level main landmark (i.e. a main landmark not inside another landmark).
Both give MUST fix WCAG level A violations from lack of a "skip navigation" link ("page must have means to bypass repeated blocks" from axe, and "The page does not contain a heading, skip link, or landmark region" from Lighthouse).
These latter two are fixed by introduction of the "main" landmark.
=> tweak a11y landmarks to fix violations

src/gwt/src/org/rstudio/core/client/widget/ToolbarButton.java, src/gwt/src/org/rstudio/core/client/widget/ToolbarMenuButton.java, src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenuButton.java, src/gwt/src/org/rstudio/studio/client/application/ui/GlobalToolbar.java, src/gwt/src/org/rstudio/studio/client/application/ui/ProjectPopupMenu.java, src/gwt/src/org/rstudio/studio/client/application/ui/addins/AddinsToolbarButton.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewPanel.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectPublishButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionsPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileCommandToolbar.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/markers/MarkerSetsToolbarButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/PlotsToolbar.java, src/gwt/src/org/rstudio/studio/client/workbench/views/presentation/PresentationPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/BranchToolbarButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/CommitFilterToolbarButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java
Mechanical refactoring to extract ToolbarMenuButton class from ToolbarButton, and change call sites to use the appropriate one. There were a small number of pro-specific uses as well, so this is a companion to that change. https://github.com/rstudio/rstudio-pro/pull/1055
=> companion to https://github.com/rstudio/rstudio-pro/pull/1055

src/cpp/desktop/DesktopMenuCallback.cpp, src/cpp/desktop/DesktopMenuCallback.hpp
Closes https://github.com/rstudio/rstudio/issues/4677.
Candidate for v1.2-patch backport.
=> handle 'duplicated' actions / shortcuts in Qt

src/gwt/src/org/rstudio/core/client/dom/ElementEx.java, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/clipboard/CopyPlotToClipboardDesktopDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/clipboard/CopyPlotToClipboardDesktopMetafileDialog.java
Closes #4864. Candidate for v1.2-patch backport.
=> hide size gripper when copying plot as metafile

src/cpp/r/R/Api.R, src/cpp/r/R/Options.R, src/cpp/r/R/Tools.R, src/cpp/session/SessionModuleContext.cpp
Closes #4826.
With this change, the user agent is reported as:
```
> getOption("HTTPUserAgent")
[1] "RStudio Desktop (99.9.9); R (3.6.0 x86_64-apple-darwin15.6.0 x86_64 darwin15.6.0)"
```
but only if the user hasn't explicitly configured their own user agent.
IIUC, this could be a candidate for backport to v1.2 since we might need this change for RStudio Cloud.
@jmcphers let me know if you think we should be including other fields.
=> provide default RStudio HTTP user agent

src/gwt/src/com/google/gwt/user/client/ui/MenuItem.java, src/gwt/src/com/google/gwt/user/client/ui/MenuItem.java.diff, src/gwt/src/org/rstudio/core/client/a11y/A11y.java, src/gwt/src/org/rstudio/core/client/widget/ToolbarButton.java, src/gwt/src/org/rstudio/core/client/widget/ToolbarMenuButton.java, src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenu.java
- fixes #4899 to enable button click via enter or space key
- if menu is opened but nothing yet selected, allow enter key and space key to close it
- sets focus on popup menu so screen reader sees it
- when menu button is collapsed, remove aria-expanded altogether instead of aria-expanded=false per w3c recommendation
=> a11y fixes for toolbar buttons and menubuttons

src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
Fixes #4829.
I'm guessing that the update to Chromium changed the way URIs are passed around on Linux / macOS Desktop; now, they're always encoded and so we do not need to attempt to re-encode the URI.
(As an aside, I believe the bug arose because we weren't successfully detecting that the URI component "graphical%20parameters.html" was already HTML encoded)
=> re-encoding of Help pane URIs no longer necessary

src/gwt/src/org/rstudio/core/client/jsonrpc/RpcResponse.java, src/gwt/src/org/rstudio/core/client/resources/ImageResourceUrl.java, src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.java, src/gwt/src/org/rstudio/studio/client/projects/model/ProjectTemplateIconImageResource.java
These are easy to find later, and will be the least of our problems if we ever go to a major new release of GWT
=> Fix / suppress current GWT compile-time deprecation warnings

src/gwt/src/com/google/gwt/updatesources.sh, src/gwt/src/com/google/gwt/user/client/ui/MenuBar.java, src/gwt/src/com/google/gwt/user/client/ui/MenuBar.java.diff, src/gwt/src/com/google/gwt/user/client/ui/MenuItem.java, src/gwt/src/com/google/gwt/user/client/ui/MenuItem.java.diff, src/gwt/src/org/rstudio/core/client/command/AppCommand.java, src/gwt/src/org/rstudio/core/client/command/AppMenuBar.java, src/gwt/src/org/rstudio/core/client/command/AppMenuItem.java, src/gwt/src/org/rstudio/core/client/widget/CheckableMenuItem.java, src/gwt/src/org/rstudio/core/rebind/command/CommandBundleGenerator.java, src/gwt/src/org/rstudio/studio/client/common/ImageMenuItem.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Fixes #4911 
Menu items for checkable commands are now marked with `role=menuitemcheckbox` and the `aria-checked` property is set to match.
Menu items that are checkable and part of a mutually exclusive set (only one can be selected) are now marked with `role=menuitemradio` and `aria-checked` is set to match state.
For testing, recommend NVDA on Windows (VoiceOver doesn't currently distinguish between regular and radio-variations).
Try out checkable items on the main menu (RStudio server only; the main menu on desktop is native code and not impacted by these changes), including regular checkable items and, for example, this menuitemradio set under Debug / On Error:
Also test non-main-menu checkable items, as those involve different code paths and are on both server and desktop. For …
=> Annotate checkbox and radio menuitems so a11y tools can see the state

src/cpp/session/modules/SessionPackrat.R, src/cpp/session/modules/SessionPackrat.cpp
Fixes #1864.
This PR does a couple things:
1. Rather than respond to file changes immediately, we wait until the next console prompt event to process any pending changes (e.g. recomputing hashes) as required. This allows us to avoid aggressively re-computing hashes of the library state as a flurry of file change events come in.
2. Instead of recursively listing files within the user's library when looking for DESCRIPTION files, we just look for DESCRIPTION files at the 'known' locations. This helps avoid crawling large sub-directories (e.g. with BH).
=> avoid excessive filesystem activity w/Packrat

src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopMenuCallback.cpp, src/cpp/desktop/DesktopMenuCallback.hpp
Closes https://github.com/rstudio/rstudio/issues/4677.
The previous version of the PR failed to account for actions associated with previous RStudio session (e.g. if the page had been reloaded, or similar). This PR ensure the QAction pointers we work with are non-null, and also ensures that null actions get pruned after a page finishes loading.
There may well be a better place to handle the 'pruning' of commands -- let me know if you have an idea, but this overall seemed the safest way forward.
=> properly toggle duplicated commands in menus

src/gwt/src/org/rstudio/core/client/widget/HyperlinkLabel.java, src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java, src/gwt/src/org/rstudio/core/client/widget/ModifyKeyboardShortcutsWidget.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/application/ui/support/SupportPopupMenu.java, src/gwt/src/org/rstudio/studio/client/common/DiagnosticsHelpLink.java, src/gwt/src/org/rstudio/studio/client/common/HelpLink.java, src/gwt/src/org/rstudio/studio/client/common/PackagesHelpLink.java, src/gwt/src/org/rstudio/studio/client/common/rstudioapi/RStudioAPI.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/CommitDetail.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/DiffFrame.java
Fixes #4927 
You can now put focus on HelpLinks (e.g. via Tab key), they show a focus rectangle, and can be activated via Enter key or Spacebar.
The question-mark graphic is marked as being cosmetic so won't be seen by screen readers. `HelpLinks` are these controls found in a wide variety of dialog boxes:
There are probably instances of the lower-level `HyperlinkLabel` object being used (looks like a hyperlink, but doesn't have the preceding question mark icon) that aren't fixed by this due to keyboard interferences from the container. I will open issue(s) when I encounter those.
=> Keyboard support for HelpLinks

src/cpp/session/modules/SessionCodeTools.R
Closes https://github.com/rstudio/rstudio/issues/4916.
```
> .rs.CRANDownloadOptionsString()
[1] "options(repos = structure('https://cran.rstudio.com', .Names = 'CRAN'), download.file.method = 'libcurl')"
```
```
> .rs.CRANDownloadOptionsString()
[1] "options(repos = c(CRAN = 'https://cran.rstudio.com'), download.file.method = 'libcurl')"
```
The output still differs, but is now at least correct in both cases.
=> use deparse more carefully when forming repos string

src/cpp/session/SessionModuleContext.cpp
The official configuration file for CircleCI 2.x is `.circleci/config.yml` ([source](https://circleci.com/docs/2.0/configuration-reference/)). It is inconvenient to edit this file in RStudio because it is ignored by default in the Files pane.
I whitelisted the `.circleci` directory using the same strategy to whitelist `.github` used in commit d35d41a36bd77177c889e1618b0c0acaef545c51.
xref: #2293
=> whitelist '.circleci' directory

src/cpp/desktop/DesktopMain.cpp
This PR fixes an issue where single-clicks with a Tablet pen would actually be registered as double-clicks.
See e.g. https://community.rstudio.com/t/rstudio-1-2-1335-on-ubuntu-18-04-2-with-wacom-intuos-small-tablet
=> disable synthetic tablet events

src/cpp/r/session/RScriptCallbacks.cpp, src/cpp/r/session/RScriptCallbacks.hpp, src/cpp/r/session/RSession.cpp
This change fixes an issue that occurs when the R session unit tests are run on a machine where RStudio is configured to ask the user whether to save the workspace on exiting.
The fix is to skip our usual interactive session cleanup routines when we're running a test script, and instead to invoke R's own cleanup handler directly without saving the workspace. 
Fixes #4867.
=> Fix hang when running R session unit tests

src/cpp/core/CrashHandler.cpp, src/cpp/core/config.h.in
This change adds the RStudio release version as an annotation to the crash upload, so that crashes can be paired with version numbers.
> [...] to support this, the annotations from all the CrashpadInfo structures found in the crashing process are merged to create the Breakpad “crash keys” as form data. 
https://chromium.googlesource.com/crashpad/crashpad/+/HEAD/doc/overview_design.md
> You can add more information to crash reports simply by adding more fields to the upload HTTP request. [...] For example, to set the release and add a tag, send: `-F 'sentry[release]=1.0.0'`
https://docs.sentry.io/platforms/minidump/#minidump-additional
=> Annotate crash with Sentry release

src/cpp/core/include/core/libclang/SourceIndex.hpp, src/cpp/core/libclang/SourceIndex.cpp, src/cpp/session/modules/clang/RCompilationDatabase.cpp, src/cpp/session/modules/clang/RCompilationDatabase.hpp, src/cpp/session/modules/clang/SessionClang.cpp
When the package library is mutated, we signal that files will need to be re-indexed in packages. This is necessary for LinkingTo dependencies -- if we build the compilation index while a required package is not installed, we'll end up missing a required compilation include path.
Without this change, a package with a broken compilation database would not get updated even if the required package was later installed. Only a forceful eviction of the cached compilation arguments (delete `.Rproj.user`; trigger by editing e.g. `src/Makevars`) would cause that to happen.
=> rebuild compilation database when library mutated

Jenkinsfile.macos
This change does two things:
a) it sets the release version formatting to match the version format we use in RStudio's _About_ dialog (and files, etc.); and
b) it adds commits from the repo to the release in Sentry.
=> Use canonical release formatting; send commits to sentry

src/gwt/src/org/rstudio/core/client/files/filedialog/FileDialog.java, src/gwt/src/org/rstudio/core/client/files/filedialog/FileSystemDialog.java, src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.java, src/gwt/src/org/rstudio/core/client/widget/MessageDialog.java, src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java, src/gwt/src/org/rstudio/core/client/widget/SlideLabel.java, src/gwt/src/org/rstudio/core/client/widget/TextEntryModalDialog.java, src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialog.java, src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.java, src/gwt/src/org/rstudio/studio/client/common/rpubs/ui/RPubsUploadDialog.java, src/gwt/src/org/rstudio/studio/client/common/rstudioapi/ui/AskSecretDialog.java, src/gwt/src/org/rstudio/studio/client/common/vcs/ignore/IgnoreDialog.java, src/gwt/src/org/rstudio/studio/client/notebook/CompileNotebookOptionsDialog.java, src/gwt/src/org/rstudio/studio/client/notebookv2/CompileNotebookv2OptionsDialog.java, src/gwt/src/org/rstudio/studio/client/shiny/ui/ShinyGadgetDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/codesearch/ui/CodeSearchDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlotDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/SavePlotAsImageDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/snippets/ui/EditSnippetsDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/unsaved/UnsavedChangesDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/edit/ui/EditDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/InstallPackageDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/export/SavePlotAsPdfDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewPlumberAPI.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewShinyWebApplication.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRdDialog.java
- replace my initial hack of hidden focusable controls (in ModalDialogBase) with a more automatic approach
- the hidden controls were, themselves, flagged as accessibility violations (allowing hidden controls to get focus); plus they made some screen-readers stutter as focus was bounced from them to visible controls
- now the code makes a reasonable determination of what focusable elements are first and last instead of requiring each dialog subclass to define it and overrides Tab and Shift+Tab to move focus to them
- provides hooks for dialogs to override the default behavior for initial focus, and defining/updating "first" and "last" controls in the dialog, and to refresh the default choices if UI is changed
- probably some individual dialogs will need to use those hooks for best …
=> automatically keep keyboard focus in modal dialogs when tabbing

src/cpp/session/modules/clang/RCompilationDatabase.cpp
Fixes https://github.com/rstudio/rstudio/issues/4724.
This one was a bit tricky to unravel, but here's the story...
With R 3.6.0, the default C++ compiler is now C++11. R accomplishes this on macOS by setting the CXX Make variable in `etc/Makeconf`, as:
```
CXX = clang++ -std=gnu++11
```
However, when working with a package project, one might request a different C++ standard -- for example, by setting `CXX_STD = CXX14`, or `SystemRequirements: C++14`. There is machinery in R (and RStudio) to ensure these compilation options are respected.
The problem: RStudio tries to generate precompiled headers (PCH) for packages, to speed up compilation for diagnostics. These PCH are also sensitive to the C++ standard used during compilation. However, rather than reusing the previously-computed and …
=> enforce required '-std=' argument when generating precompiled headers

src/cpp/session/SessionMain.cpp, src/cpp/session/http/SessionHttpConnectionUtils.cpp
This will perform a similar exit (no destructors run) without generating an exception. 
Fixes IDE-BACKEND-13, Fixes IDE-BACKEND-V, Fixes IDE-BACKEND-3C, Fixes IDE-BACKEND-2W, IDE-BACKEND-1Q, IDE-BACKEND-25
=> No longer stop processes with ::abort, instead use std::_Exit

dependencies/common/install-packages
This change installs the `testthat` package when setting up dev/build machines. The `r` unit tests require this package, so installing it during the build is a prerequisite to successfully running those tests at build time.
=> Install testthat during machine setup

src/gwt/src/org/rstudio/studio/client/dataviewer/DataTable.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTargetWidget.java
Closes #4944. Also ensures other shortcuts (like move to next tab, move to previous tab) work as expected if a Data Viewer frame has focus.
=> forward keydown events to shortcut manager

src/cpp/core/ExponentialBackoff.cpp, src/cpp/core/include/core/ExponentialBackoff.hpp, src/cpp/server/auth/ServerAuthHandler.cpp
Made Exponential backoff support recursive locking to enable this particular usage, fixed a return bug where we were running code we shouldn't on error, and made it so that the server user becomes the directory owner of the revocation list dir so that file locking works properly when we give up root privilege. 
Fixes #4976
=> Fixed a few bugs in the revocation list code

src/gwt/src/org/rstudio/core/client/files/FileSystemContext.java, src/gwt/src/org/rstudio/core/client/files/FileSystemItem.java, src/gwt/src/org/rstudio/core/client/files/PosixFileSystemContext.java, src/gwt/src/org/rstudio/core/client/files/filedialog/DirectoryContentsWidget.java, src/gwt/src/org/rstudio/core/client/widget/ToolbarFileLabel.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/BrowserType.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/EditableFileType.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/FileIcon.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/FileIconRenderer.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/FileIconResourceCell.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/FileIconResources.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/FileType.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/RDataType.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/RProjectType.java, src/gwt/src/org/rstudio/studio/client/common/viewfile/ViewFilePanel.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/DirEntryCheckBox.java, src/gwt/src/org/rstudio/studio/client/workbench/codesearch/CodeSearchSuggestion.java, src/gwt/src/org/rstudio/studio/client/workbench/model/RemoteFileSystemContext.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilePathToolbar.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/CppCompletion.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/CommitFilterToolbarButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/CommitTocRow.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/DiffFrame.java
Give file icons alt-text matching their type. This applies to the Files pane, and other locations that use these icons such as the Open File / Folder web-dialogs.
These icons convey useful information (e.g. knowing that something is a folder versus a file, which can't always be known purely from the filename), so opted to plumb in useful alt-text instead of making them decorative.
The key part of this change is building and passing around `FileIcon` objects, which encapsulate both the `ImageResource` and the textual description, where only the `ImageResource` was being passed before.
To test this, either use a screen reader to navigate the File pane's icon column, or examine source and look at the shiny new alt text.
Fixes #4988
=> Provide alt-text descriptions for file icons

src/cpp/r/RSexp.cpp, src/cpp/r/include/r/RSexp.hpp, src/cpp/session/CMakeLists.txt, src/cpp/session/SessionMain.cpp, src/cpp/session/include/session/SessionModuleContext.hpp, src/cpp/session/modules/SessionPackages.cpp, src/cpp/session/modules/SessionPackrat.R, src/cpp/session/modules/SessionRenv.R, src/cpp/session/modules/SessionRenv.cpp, src/cpp/session/modules/SessionRenv.hpp, src/cpp/session/projects/SessionProjects.cpp, src/gwt/src/org/rstudio/studio/client/workbench/projects/ProjectContext.java, src/gwt/src/org/rstudio/studio/client/workbench/projects/RenvContext.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/Packages.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackageInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackageState.java
This PR brings in the initial bits of `renv` integration -- primarily, just making sure that the Packages pane updates and responds if `renv` is activated for a project.
Fortunately, it was straightforward to reuse the existing codepaths. Because much of the behavior of the packages pane is drawn off of `.rs.listPackagesPackrat()`, we mostly just needed to implement our own facade (`.rs.renv.listPackages()`) to get similar integration set up.
=> initial work on renv integration

src/gwt/src/org/rstudio/core/client/cellview/AriaLabeledCheckboxCell.java, src/gwt/src/org/rstudio/core/client/cellview/LabeledBoolean.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java
The checkboxes in first column of FilesList instances such as Files tab were not labeled, so screen readers couldn't say anything other than "checked/unchecked checkbox".
Now they are labeled (not visibly, but for screen readers via aria-label) with the name of the file.
Implemented by creating a LabeledBoolean class to replace instances of simple Boolean used by checkbox cells, and a new AriaLabeledCheckboxCell following example of GWT's CheckboxCell.
Note, plenty more work to do to make Files lists fully usable via keyboard/screen reader, but this step meets a basic a11y requirement (and gets rid of a lot of automatically detected failures): "form controls (including checkboxes) need a label".
Fixes #4993
=> Label File tab checkboxes with the filenames

src/gwt/src/org/rstudio/core/client/dom/DomUtils.java, src/gwt/src/org/rstudio/core/client/widget/DataTableColumnWidget.java, src/gwt/src/org/rstudio/core/client/widget/FixedTextArea.java, src/gwt/src/org/rstudio/core/client/widget/MultipleItemSuggestTextBox.java, src/gwt/src/org/rstudio/core/client/widget/SearchWidget.java, src/gwt/src/org/rstudio/core/client/widget/TextBoxWithCue.java, src/gwt/src/org/rstudio/studio/client/common/rpubs/ui/RPubsUploadDialog.java, src/gwt/src/org/rstudio/studio/client/common/vcs/ShowPublicKeyDialog.java, src/gwt/src/org/rstudio/studio/client/projects/model/ProjectTemplateWidget.java, src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewDirectoryPage.java, src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/BuildToolsPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewPlumberAPI.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewShinyWebApplication.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/AddRemoteDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/CreateBranchDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/commit/SVNCommitDialog.java
Created DomUtils.disableSpellcheck() and replaced all setAttribute("spellcheck", "false") calls with it. Has both element and widget variations.
=> refactor: create and use DomUtils.disableSpellcheck()

src/gwt/src/com/google/gwt/user/client/ui/LabelBase.java, src/gwt/src/com/google/gwt/user/client/ui/LabelBase.java.diff, src/gwt/src/org/rstudio/core/client/dom/DomUtils.java, src/gwt/src/org/rstudio/core/client/widget/FormLabel.java, src/gwt/src/org/rstudio/core/client/widget/SearchWidget.java, src/gwt/src/org/rstudio/core/client/widget/TextBoxWithCue.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewPlumberAPI.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewShinyWebApplication.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/ChunkOptionsPopupPanel.java
- create and use `DomUtils.setPlaceholder()` with comment that placeholders are not recommended due to accessibility concerns (additional fixes coming on that in a future PR)
- tweak to FormLabel (and LabelBase) to stop using literal "placeholder" string during construction with target ID not yet known (not related to other "placeholder" fix other than it showed up when I did a search I had meant to fix that previously)
- tweak FormLabel to always create unique IDs instead of using label to create ID (which has high likelihood of creating duplicate HTML ids, another accessibility violation and generally a bad idea)
https://www.deque.com/blog/accessible-forms-the-problem-with-placeholders/
https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Placeholder_Research
=> consolidate setting of textbox placeholder into a helper function, other small tweaks

docker/jenkins/Dockerfile.windows
- Requires the host to also be based on Server 2019 (e.g. on Google Cloud, I used "Windows Server 2019 Datacenter Core for Containers", one of my favorite catchy product names)
=> update Windows dockerfile to Server Core 2019 LTSC base image

dependencies/windows/Install-RStudio-Prereqs.ps1, docker/jenkins/Dockerfile.windows
- we already do this in master, but 1.2-patch dockerfile was still installing an older version
- confirmed on dev machine that 1.2-patch fails in same way that the official build did when I downgrade to that older version of cmake (and works with the newer version)
Requires yet-another dockerfile regen (unless we want to connect and manually upgrade cmake)
=> use latest cmake on Windows otherwise 32-bit build fails

src/gwt/src/org/rstudio/core/client/theme/MinimizedModuleTabLayoutPanel.java, src/gwt/src/org/rstudio/core/client/theme/ModuleTabLayoutPanel.java
- basic a11y requirement, no duplicate element IDs on page
- this doesn't fix all of them, just the ones related to the tabs (Environment, Files, and so forth)
- adds "_minimized" to the IDs of minimized tabs, such as "rstudio_workbench_tab_minimized_environment"
- fixes #5011
=> assign different IDs to minimized tabs vs regular tabs

src/gwt/src/org/rstudio/core/client/Mutable.java, src/gwt/src/org/rstudio/studio/client/application/ui/RequestLogVisualization.java, src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java
On startup, we attempt to load dictionaries once for each document tab that gets opened. If a large number of documents are restored into the user's workspace, a new request for dictionary files will be made for every document that gets opened on startup (since `typoLoaded_` doesn't get flipped to `true` until after a response has been received, and that takes some time).
This PR fixes the issue by keeping track of the 'active' request for dictionary-related files, and avoids making the same request if one is already in flight. It also ensures that the request log entries are updated when a successful response is received.
Closes #5012.
=> avoid sending duplicate dictionary requests (closes #5012)

src/cpp/core/include/core/r_util/RPackageInfo.hpp, src/cpp/core/r_util/RPackageInfo.cpp, src/cpp/session/projects/SessionProjectContext.cpp
This PR fixes a performance regression in the diagnostics system.
I was surprised to see the indexer taking a long time to run when working with `shiny`:
```
> system.time(.Call("rs_lintRFile", "R/shiny.R"))
user  system elapsed 
1.439   0.028   1.468 
```
It turns out this was due to some aggressive calls to `r_util::isPackageProject()`, e.g.
https://github.com/rstudio/rstudio/blob/ad749d1029688931e00034ea0b295822d161258f/src/cpp/session/modules/SessionRParser.cpp#L373
This gets called quite often when the indexer runs, and that check involves re-reading and re-parsing the project DESCRIPTION for each time it's called.
The fix here caches the parsed package information and uses the project file monitor to update that cache as required.
```
> system.time(.Call("rs_lintRFile", …
```
=> cache package information using indexer

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/CheckBoxHiddenLabel.java, src/gwt/src/org/rstudio/core/client/widget/CheckboxLabel.java, src/gwt/src/org/rstudio/core/client/widget/FormLabel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.css, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilePathToolbar.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java
- Fix a batch of violations flagged by automated tools on default first-run IDE configuration (plus some others not visible in initial UI configuration)
- the sort-by-file-type column in Files pane had no label, now it has one visible to screen readers
- the select-all-files checkbox in Files pane had no label, now it has one visible to screen readers
- the message "Environment is empty" in background of Environment pane had very low contrast; bumped up contrast and tied color to theme so it remains visible in dark themes
- the current-directory label in upper-left corner of Console pane had very low contrast; bumped up contrast (only looking at text contrast, not icons)
- noticed that "CheckboxLabel" class used for multiple checkboxes in editor pane and find/replace sub-pane wasn't …
=> assorted a11y fixes to contrast and unlabeled controls

src/gwt/src/org/rstudio/core/client/theme/ModuleTabLayoutPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/findreplace/FindReplaceBar.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarElementWidget.java
- images without alt-text are flagged by automated a11y tests
- tab close-icons now say, for example, "Close terminal tab" (if you point at them with a screen reader, they are not keyboard accessible otherwise)
- Find pane close says "Close find and replace" (it's a button, so is keyboard accessible, though there are other issues to address in this pane)
- Little arrows on the popup menus at bottom of editor are now marked as cosmetic (empty `alt`)
- this PR doesn't address the "close document tab" icon; doing that separately
=> add a11y labels to close tab icons, close Find pane icon, text editor double-arrows

src/gwt/src/com/google/gwt/updatepatches.sh, src/gwt/src/com/google/gwt/updatesources.sh, src/gwt/src/com/google/gwt/user/cellview/client/AbstractHeaderOrFooterBuilder.java, src/gwt/src/com/google/gwt/user/cellview/client/AbstractHeaderOrFooterBuilder.java.diff
- these now have alt-text "Ascending sort" and "Descending sort" (visible to a screen reader); couldn't find a hook to do this via public overrides, so injected in the guts of GWT's implementation
=> add labels to sort-order icons in Files pane

src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java, src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/FileIcon.java, src/gwt/src/org/rstudio/studio/client/workbench/model/UnsavedChangesItem.java, src/gwt/src/org/rstudio/studio/client/workbench/model/UnsavedChangesTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/unsaved/UnsavedChangesDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocsMenu.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourcePane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceShim.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/ObjectExplorerEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/DocTabsChangedEvent.java
Add labels to the file-type icon in editor tab and the unsaved-changes dialog by using FileIcon instead of plain ImageResource in various calls.
Add label to the close icon in editor tab reading "Close document tab".
=> add labels to editor tab icons and unsaved changes file icons

src/gwt/src/org/rstudio/studio/client/common/shell/ShellDisplay.java, src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/src/org/rstudio/studio/client/common/vcs/ignore/IgnoreDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsolePane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/edit/ui/EditDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
- added aria-abels to several Ace instances including "console" and "text editor"
- this fixes accessibility violations for unlabled focusable controls
- actual benefit is that when focus goes to, for example, the Console, a screen reader will now say something like "Console Edit Text has keyboard focus" instead of just "Edit text has keyboard focus"
- there remain some unlabeled Ace instances, but those will get caught when I get to evalauting those UI pieces
=> add aria-label to some instances of Ace editor control

src/gwt/src/org/rstudio/studio/client/workbench/ui/unsaved/UnsavedChangesDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectGrid.java
Add aria-labels to the checkboxes in these tables using support classes I created when I did the same for the Files pane:
=> label checkboxes in unsaved files dialog and environment pane grid view

src/gwt/src/org/rstudio/studio/client/workbench/snippets/SnippetHelper.java
- caused by charAt()'s behavior change in GWT 2.8.2 (throws when out-of-bounds per Java spec, instead of returning a null character)
- also deleted two unused class variables
=> fix exception when typing Shift+Tab on whitespace-only editor line

src/cpp/core/gwt/GwtFileHandler.cpp
Followup to https://github.com/rstudio/rstudio/pull/5034
Without this you'll see a message on the GWT compilation screen, not sure if there were any other consequences.
=> set empty viewport_tag when running on server

src/cpp/server/extras/admin/rstudio-server.in, src/cpp/server/extras/admin/rstudio-server.mac.in
Use /bin/bash to maintain parity with RSP and prevent some subtle scripting bugs.
=> Fix server admin script

src/cpp/core/http/Request.cpp, src/cpp/core/include/core/http/Request.hpp, src/cpp/session/include/session/http/SessionRequest.hpp, src/cpp/session/modules/rmarkdown/NotebookQueue.cpp
This change fixes an issue in which R Markdown chunks didn't run on RStudio Server. The problem is that the loopback session-to-session HTTP request which submits chunk code for execution was being rejected due to a missing CSRF token (we added CSRF token validation to all requests for additional security in 1.3).
The fix is to just generate and submit a CSRF token with the request. It'd also be possible to exempt these loopback requests from CSRF requirements in some way, but that would probably require some more complicated trust mechanism (there's no shared secret in this scenario). 
Regression from https://github.com/rstudio/rstudio/commit/e1f76cd905e9603600ee7511b0b45bf914ae31a1; fixes #5041.
=> Fix execution of R Markdown chunks on RStudio Server

src/gwt/src/org/rstudio/studio/client/application/ui/appended/ApplicationEndedPopupPanel.java, src/gwt/src/org/rstudio/studio/client/application/ui/appended/ApplicationEndedPopupPanel.ui.xml, src/gwt/src/org/rstudio/studio/client/application/ui/appended/FancyButton.css
Several a11y fixes to application-ended popup pane. Now meets both automated and manual testing requirements.
- Fix button contrast to meet requirements (now using same colors as the login-page's button)
- Mark images as decorative so they don't read their internal names
- Mark popup as an alert dialog so it reads the message when displayed
- Use `ModalDialogTracker` to make rest of UI inert so user can't tab to background controls
- Unlike regular modal dialogs, I'm not preventing Tab from leaving this pane, so hitting Tab or Shift+Tab will send focus to the browser; this seems reasonable in this particular scenario
Examples of this app-ended popup pane (after fixes):
=> accessibility fixes for application-ended popup pane

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/cpp/CppCompletionUtils.java
- switch to using StringUtil.charAt, which does not throw
- regression caused by GWT 2.8.2 which switched charAt to throw on out-of-bounds index instead of returning (essentially) a null character
- may still go through and replace other uses of charAt that aren't obviously safe, but not as part of this PR
=> javascript exceptions being thrown by charAt in cpp completion code

src/gwt/src/org/rstudio/core/client/widget/WizardNavigationPage.java
Using a method reference causes an issue where gwt devmode throws away WizardPageSelector class, so going back to a lambda.
This manifested when I touched WizardPageSelector.java and tried to reload the page and use a wizard. It failed and even reverting the file wouldn't fix it (some order-of-operation thing in the GWT compiler, it appears).
This is the error I saw in the UI, and the warning in the console:
```
[WARN] Some stale types ([org.rstudio.core.client.widget.WizardNavigationPage$1]) were not reprocessed as was expected. This is either a compiler bug or a Generator has legitimately stopped creating these types.
```
=> work around GWT devmode bug involving method references

src/gwt/src/com/google/gwt/updatepatches.sh, src/gwt/src/com/google/gwt/updatesources.sh, src/gwt/src/com/google/gwt/user/client/ui/FormPanel.java, src/gwt/src/com/google/gwt/user/client/ui/FormPanel.java.diff, src/gwt/src/org/rstudio/core/client/widget/ResizeGripper.java, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/clipboard/CopyPlotToClipboardWebDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileUploadDialog.java
Fixed some automatically detected issues in CopyPlotToClipboardWebDialog and FormUploadDialog. Both these dialogs have serious usability issues (via keyboard and/or screen reader); this is just part of a sweeping "make things run cleanly in Axe" pass.
- decorative images not marked as such
- improperly associated labels
- iframe used by forms not marked as aria-hidden
=> misc dialog axe a11y fixes

src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.css, src/gwt/src/org/rstudio/core/client/widget/DirectoryChooserTextBox.java, src/gwt/src/org/rstudio/core/client/widget/WidgetListBox.css, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdDiscoveredTemplateItem.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewPlumberAPI.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewShinyWebApplication.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/TemplateMenuItem.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/CommitDetail.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/commit/SVNCommitDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/commit/SVNCommitDialog.ui.xml
Unlabeled controls, images without alt-text, layout tables not marked as presentation role, and contrast fixes in assorted dialogs/panes. Also added some explicit `outline:nones` to make it easier to track down things needed focus outlines when we get to that. Gets several more dialogs in a clean passing state via axe plugin.
=> More general a11y fixes detected by axe

src/gwt/src/org/rstudio/core/client/widget/LabeledTextBox.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml
Enables declaring a labeled textbox as one component in UiBinder files, instead of having to declare separate `FormLabel` and `TextBox` and then associating them from Java code via `setFor`.
=> create LabeledTextBox widget and use in a couple places

src/cpp/session/resources/help_resources/index.htm, src/cpp/session/resources/markdown_help.html, src/cpp/session/resources/roxygen_help.html, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/FindTextBox.java, src/gwt/src/org/rstudio/core/client/widget/FindTextBox.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobItem.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobItem.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobOutputPanel.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsList.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTargetWidget.css, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/findreplace/FindReplaceBar.java
Assortment of text contrast, image alt-tag, HTML lang, labels, and temporary settings of outline:none (for easier future searching).
=> you guessed it, more simple a11y fixes

src/cpp/session/modules/SessionReticulate.R, src/cpp/session/modules/SessionReticulate.cpp
This PR uses a new mechanism in `reticulate` for adding Python module load hooks, as per https://github.com/rstudio/reticulate/commit/8ff8c3c2c1d8c981d3cb07f74d86384f99e1602e.
The idea is that we can use these load hooks to run code after a Python module is loaded, in case we need to customize some functionality in that module so it can better run within RStudio. This ensures that attempts to generate Python plots directly from `reticulate` can still succeed.
Closes https://github.com/rstudio/rstudio/issues/4182.
=> use load hook to override matplotlib show

src/cpp/core/system/file_monitor/MacFileMonitor.cpp
Closes https://github.com/rstudio/rstudio/issues/4755.
This PR takes inspiration from https://developer.apple.com/documentation/coreservices/1455376-fseventstreamcreateflags/kfseventstreamcreateflagwatchroot?language=objc, which suggests:
> If you want to track the current location of a directory, it is best to open the directory before creating the stream so that you have a file descriptor for it and can issue an F_GETPATH fcntl() to find the current path.
One potential worry: this change implies double-checking that the root path hasn't changed and the associated handle is 'valid' every time a filesystem event comes in. While this is cheap, it's still more expensive than the pure event-driven approach.
=> guard against spurious root-changed FS events

src/gwt/src/org/rstudio/core/client/resources/styles.css, src/gwt/src/org/rstudio/core/client/widget/HelpButton.java
Now that HelpLinks and HelpButtons accept keyboard focus, they were showing default focus indicators.
We will be doing a UI-wide effort on styling focus indicators tracked by #4982, so suppressing these so they're easier to find later by searching for `outline: none`.
Also moved HelpButton's overall styling from code into css, and made indents consistent in style.css.
=> suppress focus indicator on HelpLinks and HelpButtons

src/cpp/desktop/DesktopGwtCallback.cpp
Fixes #3663 
Explicitly set HOME when launching external shell via Tools/Shell on Windows for all types except WSL (which lives in a separate Windows subsystem and takes care of setting home by itself).
=> set HOME when using git-bash via tools/shell on Windows

src/cpp/session/projects/SessionProjectContext.cpp
Closes #5092. Also fixes a potential issue where the package directory actually lives as a sub-directory of the project (a practice that is much less common now, but used to be more standard)
=> only attempt to detect DESCRIPTION changes in package project

src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.java, src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogPaneBase.java, src/gwt/src/org/rstudio/core/client/prefs/SectionChooser.java
- implemented as a vertical Tab control per the ARIA pattern
- when selector (left column) of preferences pane or project preferences pane has focus (not currently visually indicated), up and down arrows (plus HOME and END keys) can be used to switch panels
- see https://www.w3.org/TR/wai-aria-practices/#tabpanel for details on this pattern
=> Keyboard support for switching preference panes

src/gwt/src/com/google/gwt/updatepatches.sh, src/gwt/src/com/google/gwt/updatesources.sh, src/gwt/src/com/google/gwt/user/client/ui/TabLayoutPanel.java, src/gwt/src/com/google/gwt/user/client/ui/TabLayoutPanel.java.diff, src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.java, src/gwt/src/org/rstudio/core/client/prefs/SectionChooser.java, src/gwt/src/org/rstudio/core/client/resources/styles.css, src/gwt/src/org/rstudio/core/client/theme/DialogTabLayoutPanel.java, src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java, src/gwt/src/org/rstudio/core/client/theme/ModuleTabLayoutPanel.java, src/gwt/src/org/rstudio/core/client/theme/VerticalTabPanel.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateOptionsWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
This is the tab control as used in some preferences panes, the main UI quadrant tabs, editor tabs, and the "Edit R Markdown Document Options" dialog.
This fully hooks up keyboard and screen-reader/ARIA support for the preference pane instances, and keyboard support (and a subset of the screen-reader/ARIA support) for the other instances.
When focus is placed on the active tab, the left/right arrow keys move between the tabs. Home goes to the first, End goes to the last.
The non-preferences uses will have the remaining ARIA attributes hooked up in a subsequent PR. Even with this PR, it makes the tabs reasonably usable via screen-reader (versus unusable before this change).
Also a fix to the previous work on the Pref dialog section chooser; it wasn't setting focus on new tab when selected …
=> keyboard and screenreader support for tab control

src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionNavigationPage.java
Enable use of keyboard for selecting a data source type by making the list elements behave like buttons. Also other minor a11y fixes.
=> enable keyboard interface for New Connection Wizard first page

src/gwt/src/org/rstudio/studio/client/application/ui/serializationprogress/ApplicationSerializationProgressLabel.java, src/gwt/src/org/rstudio/studio/client/application/ui/serializationprogress/ApplicationSerializationProgressLabel.ui.xml
Various session actions trigger a toast message; mark it as role=status so it is read by screen readers.
"Loading workspace"
"Saving workspace image"
"Backup up R session..."
"Resuming R session..."
=> mark app serialization toast message as role=status

src/gwt/src/org/rstudio/core/client/files/filedialog/DirectoryContentsWidget.java
Markup the DirectoryContentsWidget (table) used in File dialogs as a single-select listbox via ARIA.
Because of prior work to give the icons meaningful alt text, this now reads the file type (or "Folder" for a directory), followed by the name, and then the size and date (if shown).
For example, VoiceOver reads the following selection as "Text file, test.txt, 6 B, July 12, 2019, 9:26 AM". Basic testing also done with NVDA/Firefox and JAWS/Chrome.
=> Accessibility for DirectoryContentsWidget (File dialogs)

src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/cpp/session/SessionConsoleProcessInfo.cpp, src/cpp/session/SessionConsoleProcessPersist.cpp, src/cpp/session/modules/SessionTerminal.cpp, src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java, src/gwt/src/org/rstudio/studio/client/workbench/model/TerminalOptions.java
Change #5069 introduced human-readable identifiers for terminal shell types, and removed knowledge of the enum from most parts of the UI. However, there were still a couple of places where the string is supplied but the enum is expected. This change covers those remaining cases.
Note that since one of them is persistent, it also bumps the version of the console persistent storage folder. 
Fixes https://github.com/rstudio/rstudio/issues/5157.
=> Use string-based terminal shell type

src/cpp/CMakeLists.txt, src/cpp/core/include/core/json/Json.hpp, src/cpp/core/json/JsonTests.cpp
Also try to prevent CMake from using non-RStudio installations of boost.
=> Fixes a bug where json::Object and json::Array iterators only take position into account during comparisons. 

docker/jenkins/Dockerfile.fedora28-x86_64, docker/jenkins/sign-release.sh
On RedHat, we currently supply a passphrase for the build signature using `expect` (since the passphrase prompt happens in a plain tty). This does not work on more recent versions of Fedora (since 25), so this change introduces a new mechanism for supplying the passphrase there.
Of course, this new mechanism does not work on CentOS, so we have to keep both. :-) 
Fixes https://github.com/rstudio/rstudio/issues/5169 (again).
=> Perform noninteractive signature on Fedora

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/InfoBar.java, src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java, src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.ui.xml
WCAG 2.1 AA contrast fixes:
- Selected main menu (server) 
- Session count (pro)
Warning Bar (shown at bottom of IDE):
These warning bars are often shown as the IDE is first loading, during which time the accessibility tree is going through massive updates and giving assistive tech a mild nervous breakdown, so pause before updating the hidden live region, at which point it will be read.
Also marked the warning icon as decorative, and the hidden region in both warning bar and the info bar as atomic (so the entire message is always read). Example screenshot from a Pro-only scenario.
=> contrast tweaks, live region for warning bar

src/cpp/session/modules/SessionGit.cpp
If the user is specific in their .gitignore file and uses repo-absolute paths, they’ll add `/.Rproj.user` instead of `.Rproj.user`.
RStudio shouldn’t try to add the latter if the former exists.
=> Accept `/.Rproj.user` in .gitignore

src/gwt/src/org/rstudio/core/client/widget/FieldSetPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.ui.xml
For accessibility, radio buttons need to be in a fieldset, ideally with a legend as the label (or, if necessary, use ARIA role=radiogroup and then implement keyboard support). In this dialog, was easy to wrap in a `FieldSetPanel`, and use styling to get the original visual appearance.
=> wrap "Default Output Format" radio buttons in New R Markdown dialog in fieldset

src/gwt/src/org/rstudio/core/client/a11y/A11y.java, src/gwt/src/org/rstudio/core/client/widget/FieldSetPanel.java, src/gwt/src/org/rstudio/core/client/widget/HorizontalRadioPanel.java, src/gwt/src/org/rstudio/core/client/widget/ModifyKeyboardShortcutsWidget.css, src/gwt/src/org/rstudio/core/client/widget/ModifyKeyboardShortcutsWidget.java, src/gwt/src/org/rstudio/core/client/widget/VerticalRadioPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewShinyWebApplication.css, src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewShinyWebApplication.java
- Wrap related radio buttons in a fieldset with a legend
- Make legend visually hidden and and mark existing visible label as aria-hidden to avoid duplicate announcements from screen readers (needed in cases where existing visual layout is tough to replicate using native legend element, e.g. when we are using tables for layout)
=> accessibility fixes for radio buttons in a couple more dialogs

src/gwt/src/org/rstudio/core/client/files/filedialog/FileDialogStyles.css
When I switched from Anchor to HyperlinkLabel I didn't update the styling correctly, especially noticeable in dark themes. Also reverts some unintended padding changes.
Fixes #5193
=> fix themed styling of file pane breadcrumb text

src/gwt/src/org/rstudio/core/client/widget/FormLabel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.ui.xml
Fix a visual layout regression in the Git Diff window, introduced by https://github.com/rstudio/rstudio/commit/f4a95b6b
When I switched from generic Label to FormLabel, it went from display:inline to display:block, so need to set it appropriately in this case.
Broken
Fixed
=> fix regression in layout of git diff window

src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java, src/gwt/tools/generate-prefs.R
This change fixes the integer JSNI type boxing for JavaScript objects in prefs.
Fixes https://github.com/rstudio/rstudio/issues/5194.
=> Fix JS exception when exporting plots

src/cpp/session/modules/SessionPlumberViewer.R, src/cpp/session/modules/SessionPlumberViewer.cpp, src/cpp/session/modules/SessionShinyViewer.R, src/cpp/session/modules/SessionShinyViewer.cpp, src/cpp/session/modules/SessionShinyViewer.hpp
This change fixes a few places that were missed when updating the Shiny and Plumber viewer types from an enum to string values (for ease of use in preference files). 
Fixes https://github.com/rstudio/rstudio-pro/issues/1142.
=> Complete transition of viewer type values from enum to string

docker/docker-compile.sh, docker/jenkins/publish-daily-binary.sh, docker/jenkins/rstudio-version.sh, docker/jenkins/sign-release.sh
Hello!
I was looking at your Jenkins setup today to see if there was anything interesting I could learn for my own projects. While doing that, I noticed that several of the scripts in `docker/` do not use `set -e` to ensure early stopping if something breaks.
In this PR, I propose that they _should_. Since these scripts contain imperative code that has side effects (e.g. hitting S3 with `aws s3 cp`), I think it would be valuable to know they'll immediately stop if anything goes wrong.
I've also removed a few unnecessary empty lines at the end of these files. If you prefer that I revert those whitespace-only changes please let me know and I'd be happy to.
Thanks in advance for your time and consideration!
=> added early stopping to Jenkins scripts

src/cpp/session/SessionDirs.cpp
This change fixes an issue in default working directories. The default working directory is stored with an alias (i.e. as `~/foo`), but never resolved, and consequently never used. The fix is to resolve the alias before use.
Fixes https://github.com/rstudio/rstudio/issues/5159.
=> Resolve aliased working directories in prefs

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/widget/CanSetControlId.java, src/gwt/src/org/rstudio/core/client/widget/FieldSetPanel.java, src/gwt/src/org/rstudio/core/client/widget/FormLabel.java, src/gwt/src/org/rstudio/core/client/widget/FormListBox.java, src/gwt/src/org/rstudio/core/client/widget/FormPasswordTextBox.java, src/gwt/src/org/rstudio/core/client/widget/FormTextBox.java, src/gwt/src/org/rstudio/core/client/widget/LabeledTextBox.java, src/gwt/src/org/rstudio/studio/client/common/rstudioapi/ui/AskSecretDialog.java, src/gwt/src/org/rstudio/studio/client/common/rstudioapi/ui/AskSecretDialog.ui.xml, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/ImportFileSettingsDialog.css, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/ImportFileSettingsDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/ImportFileSettingsDialog.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.ui.xml
- support declarative setting of control IDs (in UiBinder) and used that technique in this dialog
- switched a few other places over to this technique
- eliminates need to call `setFor` on labels to associate them with their target control
- provides stable IDs for controls, which will be useful in automation
- on the negative side, will result in a gigantic list of IDs in `ElementIds.java`, be nice to come up with a less centralized approach that can still ensure uniqueness
=> a11y fixes to control labeling in ImportFileSettingsDialog, declarative IDs/labeling

src/gwt/src/org/rstudio/core/client/widget/FieldSetWrapperPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlot.css, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlotResources.java, src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/export/SavePlotAsPdfDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewShinyWebApplication.java
- labeled fieldset around PDF size controls
- labeled fieldset around orientation radio buttons
- fix contrast of "inches"
- use multiplication symbol instead of "x" for dimensions
- use readonly textbox (with aria-label) to show currently selected directory instead of a static label
- enables tabbing to the control, selection and copy, and is more consistent with other RStudio directory-picker UI
- associate File Name label with textbox
- fix visual layout of the "View plot after saving" checkbox
- created templated fieldset FieldSetWrapperPanel that eliminates need for separate Horizontal/Vertical fieldset classes
- removed the VerticalRadioPanel and switched to FieldSetWrapperPanel
- left HorizontalRadioPanel as-is; that is only used in Pro-only code, so will clean it up there
Before: …
=> accessiblity fixes to Save Plot as PDF dialog

src/cpp/session/SessionHttpMethods.cpp
Candidate fix for #5222.
The goal is to sidestep the issue by ensuring the file monitor thread is stopped before quitting the R session, which should avoid issues with concurrent access between the file monitor thread's data structures by the runtime and the file monitor thread itself.
=> explicitly stop file monitor on close

NEWS.md, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.css, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.ui.xml
This change adds a small character counter to the commit message entry box. It is visible only if you've entered a commit message, and intended to help keep commit messages shorter than some limit if desired. 
Closes https://github.com/rstudio/rstudio/issues/5192.
=> Show number of characters when typing a commit message

src/gwt/src/org/rstudio/core/client/a11y/A11y.java, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/DecorativeImage.java, src/gwt/src/org/rstudio/core/client/widget/FilterWidget.java, src/gwt/src/org/rstudio/core/client/widget/FormLabel.java, src/gwt/src/org/rstudio/core/client/widget/ImageButton.java, src/gwt/src/org/rstudio/core/client/widget/SearchWidget.java, src/gwt/src/org/rstudio/core/client/widget/SearchWidget.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.css, src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.java
- improvements to SearchWidget class
- make the "clear text" button an actual button that can be tabbed to and used via keyboard/screen reader
- make the hidden-label optional (for cases where the search control has an actual visible label)
- set focus back to textbox after invoking the "clear text" button
- put a visible label on the filter control in BrowserAddinsDialog and get rid of the placeholder text
- improvement to DecorativeImage to fix weird cases where macOS VoiceOver would allow selection of images without alt-text via VoiceOver cursor (and would say nothing about it)
- another constructor variation for FormLabel class
- improvements to ImageButton
- mark underlying button as type="button" to avoid browser variations
- more setters and no-argument constructor to allow use …
=> a11y improvements to SearchWidget and Browser Addins dialog

src/gwt/src/org/rstudio/core/client/StringUtil.java, src/gwt/src/org/rstudio/core/client/a11y/A11y.java, src/gwt/src/org/rstudio/core/client/widget/FilterWidget.java, src/gwt/src/org/rstudio/core/client/widget/SearchWidget.java, src/gwt/src/org/rstudio/core/client/widget/SearchWidget.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
- use live-region to announce results in SearchWidget after a delay to avoid speaking over typing
- created global constant for that delay, also put in GitReviewPanel's character count announcement timer
- hooked up for BrowseAddinsDialog only (for now)
- note that announcement includes the typed query, with letters separated by spaces, so it doesn't try to read the query as a word, and also so the live region trigger an announcement when the query changes, not just when the number of results changes (live regions don't announce unless their text changes from previous value)
=> speak results when filtering addins (dialog-only)

Jenkinsfile.macos, docker/jenkins/notarize-release.sh, package/osx/CMakeLists.txt, package/osx/entitlements.plist, src/cpp/session/CMakeLists.txt
This change ports the changes from PR https://github.com/rstudio/rstudio/pull/5196 to the v1.2-patch branch, so that we can have Apple notarize the 1.2-patch release.
=> Perform release notarization for RStudio 1.2

src/cpp/session/modules/data/DataViewer.cpp
Speculative fix for Sentry crash.
Fixes https://github.com/rstudio/rstudio/issues/5220.
=> Don't invoke STRING_ELT on non-STRSXP S-expressions

src/cpp/session/SessionHttpMethods.cpp, src/cpp/session/SessionMain.cpp
This PR moves the file monitor thread stopper to the right place, so it properly gets invoked for all types of quits that can be requested.
=> ensure file monitor stopped for all forms of quit

src/cpp/session/prefs/UserPrefsLayer.cpp
This change fixes a subtle JSON value issue that causes a crash when reloading a preference file that has changed on disk.
Fixes https://github.com/rstudio/rstudio/issues/5184.
=> Fix crash when reloading preferences

src/cpp/session/modules/SessionRenv.R, src/gwt/src/org/rstudio/core/client/StringUtil.java, src/gwt/src/org/rstudio/core/client/command/AppCommand.java, src/gwt/src/org/rstudio/studio/client/renv/model/RenvServerOperations.java, src/gwt/src/org/rstudio/studio/client/renv/ui/RenvActionDialog.java, src/gwt/src/org/rstudio/studio/client/renv/ui/RenvActionDialogContents.css, src/gwt/src/org/rstudio/studio/client/renv/ui/RenvActionDialogContents.java, src/gwt/src/org/rstudio/studio/client/renv/ui/RenvActionDialogContents.ui.xml, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/projects/RenvAction.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/Packages.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java
This PR adds dialogs for performing an `renv::snapshot()` / `renv::restore()`.
Note that we deviate from the Packrat behavior a bit here: when using Packrat, we tried to infer if the user desired a snapshot or a restore based on the diff between the lockfile and library state, with this PR, the onus is on the user to understand whether they want to snapshot or restore.
Support for some form of diffing could come in a separate PR.
=> implement snapshot / restore dialogs for renv

src/cpp/diagnostics/DiagnosticsMain.cpp, src/cpp/r/R/Diagnostics.R
This change includes the user and system preference files (from the new prefs system) in the diagnostics report, with the goal of making it easier to replicate a configuration that's causing problems.
=> Include user and system prefs in diagnostics

src/gwt/src/org/rstudio/core/client/prefs/SectionChooser.java
Fixes #5120 
Supply the list of tabs controlled by the tablist via the `aria-owns` attribute so FireFox can give correct tab count.
_Shouldn't_ need this because the tabs are nested under the tablist in the DOM, however... an example of needing to test for quirks with multiple browser and screen reader combinations.
=> fix preference pane tab count reported by screen readers with FireFox

src/gwt/src/org/rstudio/core/client/widget/InfoBar.java, src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java
The Infobar and WarningBar widgets use a visually hidden live region to announce their message; this region contains the same text as the visible label (after a small delay).
This change marks visible labels as aria-hidden, otherwise virtual cursor navigation with screen reader "sees" both, which is redundant.
=> small fix: info and warning bars expose duplicate messages to screen readers

src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/BuildToolsRoxygenOptionsDialog.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlotSizeEditor.java
- remove border around fieldset in BuildToolsRoxygenOptionsDialog
- make it visually consistent with previous versions despite switch to fieldset in 1.3 (for accessibility)
- fix checkbox styling in ExportPlotSizeEditor widget (long-standing visual glitch)
Before this change:
After this change (matches appearance of 1.2 and earlier)
Before (notice checkbox label smooshed against the checkbox):
After:
=> two minor visual tweaks

src/cpp/desktop/DesktopGwtCallbackMac.mm
Fixes #5115
- Mac desktop specific
- also unrelated change of NULL to nullptr since I was touching the file anyway
For example, this can now be dismissing via Enter or ESC:
=> support dismissing single-button Mac desktop alert via ESC or Enter

src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ConnectionsPresenter.java
Regressed in the prefs overhaul. This value is really a 'last used' rather than a preference, so it was moved into the state object. 
Fixes https://github.com/rstudio/rstudio/issues/5244.
=> Use state to supply last used connection method

src/cpp/session/resources/schema/user-state-schema.json, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/SavePlotAsImageDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/model/ExportPlotOptions.java
Moves the plot export defaults into the schema. This properly populates the default set to avoid missing values that can cause warnings later. 
Fixes https://github.com/rstudio/rstudio/issues/5253.
=> Formalize defaults for export plot options

src/cpp/r/R/Api.R, src/cpp/session/CMakeLists.txt, src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/modules/ModuleTools.R, src/cpp/session/modules/SessionApiPrefs.cpp, src/cpp/session/modules/SessionApiPrefs.hpp, src/cpp/session/modules/SessionUserPrefs.cpp, src/cpp/session/modules/data/DataViewer.cpp, src/cpp/session/prefs/Preferences.cpp, src/cpp/session/prefs/UserPrefValues.cpp, src/cpp/session/resources/grid/dtviewer.js, src/cpp/session/resources/schema/user-prefs-schema.json, src/cpp/tests/testthat/test-prefs.R, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
Currently, the rstudioapi package has two preference-related methods, `readPreference` and `writePreference`. These methods, however, do not allow access to any of the IDE's actual preferences. Instead, they are a mechanism for R code to save and load arbitrary key/value pairs into the IDE's preference store under the `rstudioapi` namespace. 
This isn't ideal for a few reasons. The first is that it's useful to access the IDE's preferences from rstudioapi, especially now that they are formalized. The second is that the core preference system is not a great place to store arbitrary values from R code due to different semantics (overriding/defaults, possibility for corruption, etc).
This change does three things:
1. Creates a new mini pref system that stores *only* values from rstudioapi, in …
=> Store rstudioapi prefs separately; enable access to IDE prefs

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java
Currently, the Save All command, somewhat non-intuitively, saves only the files in the current window. This change makes it save all unchanged files in all windows.
We also currently make the Save All command enabled or disabled based on whether or not there are any unsaved targets in the current window. Aggregating this information correctly (and reacting to changes) across all windows is difficult to get right, so we take the conservative approach here of just leaving the command enabled if there are source windows open. 
Fixes https://github.com/rstudio/rstudio/issues/5023.
=> Make Save All command work across satellites

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/NewShinyWebApplication.java
Requested by QA for automation (tracked in a pro issue, which should have been in the open-source repo: https://github.com/rstudio/rstudio-pro/issues/1173)
- Name textbox: `rstudio_new_shiny_app_name`
- Single file radio: `rstudio_new_shiny_app_single_file`
- Multi file radio: `rstudio_new_shiny_app_multi_file`
- Create within directory textbox: `rstudio_textboxbutton_text`
- Browse button: `rstudio_textboxbutton_button`
- Create button: `rstudio_dlg_ok`
- Cancel button: `rstudio_dlg_cancel`
Radio buttons are compound controls. The unique ID is attached to the outer span which contains the input (radio) and label.
The create and cancel buttons already had unique ids, just including here for completeness.
The read-only textfield and browse button are part of a compound control, …
=> add unique IDs to New Shiny Web App dialog box

src/cpp/session/CMakeLists.txt, src/cpp/session/include/session/SessionConstants.hpp, src/cpp/session/modules/SessionUserPrefs.cpp, src/cpp/session/modules/SessionUserPrefsMigration.cpp, src/cpp/session/modules/SessionUserPrefsMigration.hpp, src/cpp/session/prefs/UserPrefsComputedLayer.cpp
This change contains the last essential piece of the new prefs work: it migrates user preferences from RStudio 1.2 (and earlier) to the new 1.3 system. It does this by reading the `user-settings` file written by these older versions and translating preferences from the file itself as well as the JSON blob of UI prefs it contains into the new system.
The migration is only done if there are no 1.3 preferences. Since 1.3 preferences are written at the end of the migration, the migration will only be done once unless the 1.3 preferences are removed.
=> Import preferences from RStudio 1.2

src/cpp/desktop/Info.plist.in, src/cpp/desktop/resources/freedesktop/rstudio.xml, src/cpp/session/modules/SessionCodeSearch.cpp, src/cpp/session/modules/tex/SessionCompilePdf.cpp, src/cpp/session/modules/tex/SessionSynctex.cpp, src/gwt/src/org/rstudio/core/client/files/FileSystemItem.java
Drive-by change; fixes https://github.com/rstudio/rstudio/issues/5076. Completes the work started in #653. 
Note that `utils::Sweave` does not recognize `.Rtex` files as Sweave, so you will need to use `knitr` as your Sweave engine to be successful with this file extension.
=> Complete registration of .Rtex files

src/cpp/session/modules/SessionSpelling.cpp
This change makes it possible to install system-wide languages and dictionaries for the spelling engine, useful to e.g. pre-download and install languages for all users on the system.
=> Check system XDG folders for spelling dictionaries/languages

src/cpp/session/resources/R.css, src/gwt/src/org/rstudio/core/client/BrowseCap.java, src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.java
The Help pane looks terrible in macOS Catalina. Due to what appears to be a bug in QtWebEngine, the generic CSS font classes `serif`, `sans-serif`, `monospace`, etc. all render in some sort of tiny Times New Roman font on MacOS Catalina in the Help pane.
This change works around the problem by specifying the macOS default fonts (Helvetica and Courier) for the limited HTML used by the Help pane, so that the appearance matches that of prior releases. Just to be cautious, we only do this when on macOS. 
Fixes https://github.com/rstudio/rstudio/issues/5066. Candidate for 1.2-patch backport since it's affected, too.
=> Fix help pane fonts on macOS Catalina

src/cpp/core/system/file_monitor/MacFileMonitor.cpp
This fixes an issue on MacOS Catalina with the file monitor. It's somewhat speculative as the issue is intermittent.
Catalina has a new `/System/Volumes/Data/` root which is, confusingly, the same as `/` in most contexts. Based on error messages, it looks like what's happening is that we're being notified that the root path has changed into or out of this system tree, even though the actual directory we're watching has moved and we don't need to take any action.
The proposed fix is to check to see if the filesystem object is actually referring to the same thing (vs. having the same path). In this case, `/System/Volumes/Data/Users/foo/bar` is really the same path as `/Users/foo/bar`, even though the paths are different strings.
Fixes https://github.com/rstudio/rstudio/issues/4755.
=> Check for filesystem (not string) equivalence

src/cpp/session/modules/SessionBreakpoints.R
Reprex (interactive, tested on RStudio Desktop):
```r
Sys.setenv("_R_CHECK_LENGTH_1_LOGIC2_" = "verbose")
shiny::runGadget(div(), function(input, output){})
```
What's a good way to hot-patch my RStudio installation to include this? Can't seem to make it work from `.Rprofile`.
=> Avoid _R_CHECK_LENGTH_1_LOGIC2_ warning

src/cpp/session/SessionModuleContext.cpp
SourceHut provides a Travis (et al)-like CI builder service. If a `.build.yml` file exists in the repo dir the project will be auto-built on commit+push. This PR modifies the same C++ file I modified earlier to support GitLab build YAML files.
=> Add support for editing sourcehut builds YAML

src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java
- only supposed to show in SuperDevMode builds
- started happening in build 1.2.243 (Jan 11, 2018)
- fixed by hiding this command in same location other command-hiding takes place
- tested:
- fixes issue on Desktop build (only tried Mac)
- command still shows up and works on a dev-server config 
Fixes #5337
=> fix suspend session command showing up in production desktop IDE

src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/JobsPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/LauncherJobsPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
Fixes #1599
The terminal scenario had gotten worse with upgrade to xterm3 -- the terminal pane must be visible before xterm3 can be initialized, so without this fix the scenario resulted in an unusable terminal pane.
Also fixed Jobs and Launcher panes so they will also un-minimize the console pane when activated via their respective View commands.
=> restore console pane when activating terminal or jobs panes

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
The terminal pane displays whatever title string is reported by the underlying shell (via escape sequences). On git-bash (Windows desktop), the shell title includes a leading colon which only makes sense if there's a $TITLEPREFIX set, which isn't.
So, on Windows, strip the colon if the string starts with ":/", leaving the Cygwin-style path. If user has tweaked things to include something at the start of titles, then leave it alone.
Fixes #3472
=> remove leading colon from git-bash reported terminal title

src/cpp/core/include/core/http/TcpIpAsyncConnector.hpp, src/cpp/ext/websocketpp/transport/asio/connection.hpp, src/cpp/ext/websocketpp/transport/asio/endpoint.hpp, src/cpp/ext/websocketpp/transport/asio/security/none.hpp
This PR patches RStudio + websocketpp to allow compilation with Boost 1.70. (We don't attempt to upgrade Boost explicitly right now; we just want to support compilation for distributions that need it)
Closes https://github.com/rstudio/rstudio/issues/4636.
=> support compilation with Boost 1.70+

src/cpp/session/modules/SessionUserPrefs.cpp, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/PrefsServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
This change adds a few handy diagnostics commands for working with preferences.
"Edit" opens a modal editor with the user prefs file loaded, which makes it easy to see what all your raw preference values are.
"View" opens a data viewer tab showing all active preference values and where they came from.
"Clear" deletes user preferences, after making a backup, then restarts R and reloads the UI. 
These commands will ideally never be used in day-to-day practice, which is why they're on the Diagnostics menu. They are inspired by issues like https://github.com/rstudio/rstudio/issues/5296, where the resolution is "go to this deeply nested folder and delete this secret file", and can now be "clear your prefs from the diagnostics menu".
=> Add view/clear/edit prefs diagnostics commands

src/cpp/r/session/graphics/RGraphicsPlotManager.cpp
Closes https://github.com/rstudio/rstudio/issues/3117.
Note that we do something similar here:
https://github.com/rstudio/rstudio/blob/c5ce1c591869e69c7e70d05e50392ffc3b3b2cf8/src/cpp/r/session/graphics/RGraphicsPlotManager.cpp#L449-L457
but `onDeviceNewPage()` is typically called before `render()`, and requires access to the graphics path.
=> ensure graphics path exists when device requests new page

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermNative.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
Fixes #5354 
Previous versions of xterm.js used 'terminal' css class for styling, and we have styles based on that.
Xterm3 switched to 'xterm' instead of 'terminal', and an API-based styling technique, but they left in 'terminal' class on root element. This causes our styles (which are still in the css so we can get them at runtime and pass to the API) to bleed through when using DOM-based renderer.
Fix by removing the unnecessary 'terminal' class.
=> prevent legacy terminal css styles from bleeding into xterm3 styling

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
- seeing this occasionally, haven't been able to nail down the exact timing that results in this happening
- appears benign from user standpoint, but want to avoid and perhaps expose any other (perhaps more helpful) issues lurking after it
=> guard against an occasional null-access exception during terminal start

docker/jenkins/Dockerfile.bionic-amd64, docker/jenkins/Dockerfile.centos6-x86_64, docker/jenkins/Dockerfile.centos7-x86_64, docker/jenkins/Dockerfile.debian9-x86_64, docker/jenkins/Dockerfile.fedora28-x86_64, docker/jenkins/Dockerfile.opensuse-x86_64, docker/jenkins/Dockerfile.opensuse15-x86_64, docker/jenkins/Dockerfile.xenial-amd64
- when building images using docker-compile.sh, the Dockerfile command to COPY scripts under dependencies/common into the image was pulling in content of subfolders (i.e. dependencies installed on the host machine as part of dev build environment)
- the use of trailing asterisk caused subfolder contents to be flattened into the destination directory instead of preserving the folder structure
- in the case of the renv package dependency, this left files in a state where the installation script would fail, preventing image creation
Fix by not using the trailing asterisk. This will be a no-op in the official builds, since those run against a clean repo where dependencies/common has no subfolders, and on a dev machine, preserves the folder structure of already-installed dependencies. …
=> fix issue when generating docker images from developer machine

src/cpp/desktop/CMakeLists.txt
Necessary if devs want to create and run debug builds on macOS due to Qt 5.12.5 bug: https://bugreports.qt.io/browse/QTBUG-78239
To use this, must not have Qt 5.12.5 installed. Alternatively, can do release builds with debug info.
Any Qt 5.12.5-specific changes need to be conditionally wrapped, see existing examples of QT_VERSION_CHECK in the source code.
=> support building with Qt 5.12.1 on macOS

src/cpp/r/R/Api.R
These pref names were missed when the prefs system was overhauled; this change switches to the new theme prefs names so that the `getThemeInfo()` API works correctly.
Fixes https://github.com/rstudio/rstudio/issues/3532.
=> Update theme API preference names

src/gwt/src/org/rstudio/studio/client/projects/model/ProjectTemplateWidget.java, src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectGeneralPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.ui.xml
- Grid is used for layout here, and thus the resulting tables need to be marked as role=presentation so they aren't read as tabular data
- two cases via UiBinder, showing you can do it declaratively instead of at runtime
- one obscure case for custom project templates where template adds text field(s) to the UI (for an example, see https://github.com/rstudio/ptexamples)
=> replace Grid with LayoutGrid in three more locations

src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java, src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewDirectoryPage.java
- the dialog creates several TextBoxWithButton-based controls, before adding them to the DOM, so the code for detecting duplicate IDs wasn't working (I had added the dup-removal in https://github.com/rstudio/rstudio/pull/5276)
- thus, ended up with a bunch of duplicate IDs causing validation to fail, and VoiceOver on Mac ended up reading all of the labels for a single instance of the control's textbox when you tabbed into it
- small tweak to mark the Project Name text field as required
=> duplicate element IDs in New Project wizard confusing screen readers

src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionCodePanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionShinyHost.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionSnippetDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionSnippetHost.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/GridEx.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/ChunkOptionsPopupPanel.java
- several more instances of Grid replaced with LayoutGrid
- associate labels with controls in Connections dialog
=> use LayoutGrid instead of Grid for proper accessibility annotation

src/cpp/session/modules/SessionBreakpoints.R, src/cpp/session/modules/SessionPackages.R
These almost-trivial changes fix a couple of problems that surface when `_R_CHECK_LENGTH_1_LOGIC2_` is enabled.
`
Fixes https://github.com/rstudio/rstudio/issues/5268
Fixes https://github.com/rstudio/rstudio/issues/5363
=> Fix a couple of _R_CHECK_LENGTH_1_LOGIC2_ issues

package/linux/debian-control/postinst.in, package/linux/rpm-script/postinst.sh.in
Fixes #5464
Accomplished by implicitly creating the `rstudio-server` group in the `useradd` command itself, instead of hoping that the default group policy structure causes this to magically work like it does on some Linux systems.
=> Make sure rstudio-server user is added to the rstudio-server group on install

src/cpp/server/ServerPAMAuth.cpp, src/gwt/www/templates/encrypted-sign-in.htm
Closes #5449 
The following screenshot shows the updated visual that users will see when `auth-timeout-minutes` is in effect (greater than 0).
=> Show the auth timeout for users on the home page when using new auth timeout mode to hopefully reduce confusion

src/cpp/session/SessionAsyncRProcess.cpp, src/cpp/session/include/session/SessionAsyncRProcess.hpp, src/cpp/session/modules/RStudioAPI.R, src/cpp/session/modules/RStudioAPI.cpp, src/cpp/session/modules/SessionRUtil.cpp
Re: https://github.com/rstudio/rstudio/issues/4490. See https://github.com/rstudio/rstudioapi/pull/155 for more discussion.
This PR allows RStudio to read and respond to requests made by child R processes, as made through the `rstudioapi` package.
Note that this PR does potentially open the door to allowing child processes to execute arbitrary R code in the main R session, so we may want to consider if we need to shut that door at all. My gut reaction is that it's fine (the main R session already has that access, so it's fine if it launches a child process that shares that access) but I wanted to raise this in case I might be missing anything.
=> allow for IPC from child processes through rstudioapi

NEWS.md, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
- in Safari on iPadOS, can now use Ctrl+[ to cancel long-running code, or to get out of continuation mode (e.g. unmatched quotes or parentheses), or dismiss autocomplete popups in console, on an iPad keyboard that doesn't have an Esc key
- the underlying problem is that Ctrl+[ on iPadOS behaves more like pressing Ctrl+Esc
- also some minor gratuitous Java style cleanup
- Fixes #4663
=> support use of Ctrl+[ as Esc in console on iPadOS (for keyboards lacking Esc key)

src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ObjectBrowser.java
We currently try to restore the exact state of the Connections pane after it's refreshed -- i.e. which objects were open, your scroll position, etc.
This is a nice thing to do, but doesn't work correctly, and after some investigation it'd be difficult to make it do the right thing (as we'd need to hit the server multiple times to refresh each layer individually). A refresh that leaves you looking at exactly the same content might not feel like a refresh, too, so there's some argument to be made for cleaning the slate as a cue that you're looking at fresh data.
Fixes https://github.com/rstudio/rstudio/issues/2136.
=> Don't attempt to restore connection object expansion state after refresh

src/cpp/r/R/Tools.R, src/cpp/r/session/REmbeddedWin32.cpp
Closes https://github.com/rstudio/rstudio/issues/4986.
This is a pretty dangerous change, but I can't think of any safer way of accomplishing this.
In theory, all we want to do is set `R_max_memory`. Unfortunately, it's not an exported symbol. The exported R function that does allow us to change it, only allows us to raise it -- not lower it. And, by default, R initializes it as R_SIZE_T_MAX:
https://github.com/wch/r-source/commit/24fc04760afdca9edc52afeb4dfb1f5bf50ffd6e
Since `cmdlineoptions()` is the only API we can call that allows us to set the memory limit at R initialization time, the PR sets out to call that with the minimal amount of action taken by R (since we ultimately need to override any of the default startup behaviors with our own startup structs and function pointers).
The …
=> call cmdlineoptions() to set memory limit

src/cpp/session/modules/SessionPackageProvidedExtension.cpp
This change adds installations from the `remotes` package to those watched for to trigger a reindex. It also makes the trigger more broad (to catch both devtools and remotes usages of `install_git`, `install_bitbucket`, `install_gitlab`, etc.)
=> Check for usage of remotes package-based installation

src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/cpp/desktop/DesktopUtils.cpp, src/cpp/desktop/DesktopUtils.hpp, src/cpp/desktop/DesktopUtilsMac.mm, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/SessionModuleContext.mm, src/cpp/session/include/session/SessionModuleContext.hpp, src/cpp/session/modules/SessionGit.cpp, src/cpp/session/modules/SessionSVN.cpp, src/cpp/session/modules/build/SessionBuild.cpp
Closes #5481.
If the Xcode license has not been agreed to, and RStudio attempts to take some action with Git / SVN, then RStudio will print the following warning:
This should hopefully help users struggling with "where's my Git pane?" after macOS / Xcode updates.
This PR also cleans up some usages of isOSXMavericks that we had from before. Now that we only support macOS 10.12 and above and the old days of `llvm-gcc-4.2` are behind us, we can drop some of the old code and simply check if we're running on macOS.
=> warn when Xcode license has not been accepted

src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
- in alert dialogs (e.g. Yes / No dialogs), focus was being put on the first focusable control in the dialog, then being moved to the default button via a deferred setFocus
- if the default button isn't the first control, this rapid-fire change of focus when opening the dialog causes screen readers to often stop reading the dialog's alert text
- remove that secondary just-in-case focus setting; it is doing more harm than good; better off discovering cases where focus isn't being set and fixing them than confusing the screen readers
For example, in this dialog, often all the screen reader would say when the alert displays is "No, button", instead of having the whole dialog read out, especially with VoiceOver on macOS.
=> prevent focus bounce in modal dialogs (was confusing screen readers)

src/gwt/src/org/rstudio/core/client/files/filedialog/FileDialogStyles.css, src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.css, src/gwt/src/org/rstudio/core/client/resources/styles.css, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/ShortcutInfoPanel.ui.xml, src/gwt/src/org/rstudio/core/client/widget/WidgetListBox.css, src/gwt/src/org/rstudio/core/client/widget/Wizard.css, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.css, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputGallery.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/xterm.css, src/gwt/www/css/focus-visible.css
Fixes #5460 
@MariaSemple Lmk if I'm doing anything wrong with the CSS here, it seems like doing CSS3 selectors can be a bit tricky with GWT's parser (https://stackoverflow.com/questions/3479636/how-to-get-gwt-cssresource-to-parse-not-selectors/7647867 couldn't get this to work though) so I pared down my changes to things that didn't throw errors.
=> A11y: fix focus selectors overriding focus-visible

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/studio/client/application/ui/GlobalToolbar.java, src/gwt/src/org/rstudio/studio/client/application/ui/ProjectPopupMenu.java, src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java
- terminal pane dropdown
- main toolbar, (new file, mru, vcs, pane layout, projects)
- build pane (build bookdown, more...)
- fixed bug in regex for generating unique IDs based on labels; "terminal #" was being stripped of the "#" instead of including it
- fixes #5520
=> add unique ids to several toolbar popup menu buttons for automation

src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
This small change ensures that we update the character count when clearing the commit message checkbox during a commit. 
Fixes https://github.com/rstudio/rstudio/issues/5521.
=> Update character count when committing

src/cpp/core/include/core/system/Xdg.hpp, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/include/session/SessionModuleContext.hpp, src/cpp/session/modules/SessionRMarkdown.R, src/cpp/session/modules/tex/SessionCompilePdf.cpp, src/gwt/src/org/rstudio/core/client/widget/InfoBar.java, src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCompilePdfHelper.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/WarningBarDisplay.java
Closes #2788.
This PR adds some UI for installing the `tinytex` package, and uses that to call `tinytex::install_tinytex()`.
After running that, documents that need to be compiled to PDF (both `.Rnw` and `.Rmd`) should be able to be compiled successfully.
Some open thoughts:
1. Should we provide a modal dialog before starting the install? It could be a place where we could explain "what is tinytex?" and also provide a help link or similar.
2. We might also want to ensure this warning bar shows up when using an R Markdown document that will be compiled to PDF.
=> add support for installing tinytex

dependencies/linux/install-dependencies-debian
=> fix debian dependency script to pass along exclude-qt-sdk arg

src/cpp/r/R/Tools.R
This PR improves the performance of `.rs.restoreGraphics()`, which also improves performance when navigating the plot history.
The primary issue with the old code was that it attempts to iterate over a pairlist by index; this is an O(N^2) operation since each iterator requires re-scanning from the start to the requested element. The fix then is to convert to a regular R list, and convert back to a pairlist at the end if required.
This PR also removes some of the R 2.14-specific code.
=> improve performance of plot replay (#5531)

src/gwt/src/org/rstudio/core/client/files/filedialog/FileDialogStyles.css, src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.css, src/gwt/src/org/rstudio/core/client/resources/styles.css, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/ShortcutInfoPanel.ui.xml, src/gwt/src/org/rstudio/core/client/widget/WidgetListBox.css, src/gwt/src/org/rstudio/core/client/widget/Wizard.css, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.css, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputGallery.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/xterm.css, src/gwt/www/css/focus-visible.css
The GWT CSS parser is old and glitchy. Its support for CSS3 selectors in particular is very, very shaky. The story can be followed by poor dankurka's adventures trying to get it to work 4 years ago and it seems like they still haven't fixed it: 
https://github.com/gwtproject/gwt/issues/5770
Currently running `ant unittest` will output a barrage of `[WARN] Line 1315 column 25: encountered ".". Was expecting one of: <IDENT> ` errors when trying to parse the `:not` selectors I added yesterday. The CSS worked just fine in the application itself but the unit test harness very much does not like it.
I tried every permutation and suggested workaround in the myriad threads referencing this problem but couldn't think of any other reliable solution.
I'm removing the `not` selectors and proposing …
=> Remove 'not' selectors and add important to focus-visible outlines

src/cpp/desktop/DesktopWebPage.cpp
Closes https://github.com/rstudio/rstudio/issues/5525.
Candidate for v1.2-patch backport.
=> fix sans-serif font usage in doc outline

NOTICE, src/cpp/session/modules/SessionAbout.cpp, src/gwt/src/org/rstudio/core/client/widget/HyperlinkLabel.java, src/gwt/src/org/rstudio/studio/client/application/model/ApplicationServerOperations.java, src/gwt/src/org/rstudio/studio/client/application/model/ProductNotice.java, src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.java, src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.ui.xml, src/gwt/src/org/rstudio/studio/client/application/ui/AboutOpenSourceDialog.java, src/gwt/src/org/rstudio/studio/client/application/ui/AboutOpenSourceDialog.ui.xml, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- the 3400+ line NOTICE for open-source components was bogging down
screen readers when opening the About dialog
- moved into a new dialog, with a link to it from the About dialog
- new dialog puts the text into a `<pre>` instead of a `textarea`; this is much faster and does not slow down screen readers
- marked that area as role="document", and made it able to get focus and be selected / copied
- fixes #5533
=> Move open-source NOTICE from About dialog to new dialog

src/cpp/session/modules/ModuleTools.R
=> don't call user-defined print methods for signature

dependencies/common/install-packages
This should fix an issue I was seeing when trying to install dependencies. Because testthat couldn't be installed, the script exits and the other dependencies afterwards don't get installed.
=> sudo to provide access to /usr/local/lib/R/site-library

src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/prefs/UserPrefValues.cpp, src/cpp/session/resources/schema/user-prefs-schema.json, src/gwt/src/org/rstudio/core/rebind/command/ShortcutsEmitter.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
Some users find our auto-complete a little over-eager and wish they could disable tab-based auto-completion. This PR adds a user preference that lets user disable tab for auto-complete so that pressing tab will always insert a tab character. Unless the user in emacs mode, pressing `ctrl-space` will still initiate auto-completion, and pressing `shift-tab` after the start of a snippet will still initiate snippet completion.
Fixes #2766 and part 1 of #5387.
=> Support the ability to disable tab-based autocompleted in user preferences.

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.java
- Need this for some accessibility automation I'm working on
- Also some gratuitous reformatting of lambdas given our style decision
=> add uniqueId for top-level div of Global Options dialog for automation

src/cpp/core/include/core/Macros.hpp, src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopSessionLauncher.cpp
This avoids an issue where, if an error is shown while attempting to load an error page, a recursive cascade of errors windows will be popped up.
While this doesn't fix the underlying issue, it's still worth guarding against even post-fix.
=> guard against recursive error pages

src/cpp/session/modules/SessionThemes.R, src/cpp/session/modules/SessionThemes.cpp
There are currently multiple locations in which we check for the existence of a local custom theme, and depending on which one you look at a particular theme may or may not be found. Global themes, custom or default, are working correctly - we only have issues with local custom themes.
In [getAllThemes](https://github.com/rstudio/rstudio/blob/master/src/cpp/session/modules/SessionThemes.cpp#L283-L307) we get:
1. default global themes (the ones we ship with)
2. custom global themes, from either
a. the default custom location (/etc/rstudio/themes on linux), OR
b. the env variable custom location (`RS_GLOBAL_THEME_HOME`)
3. the local custom themes, either from:
a. the current default custom location AND the legacy custom location, OR
b. the env variable custom location …
=> Fix an issue where the configured local path is sometimes ignored.

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
This is a bandaid for https://github.com/rstudio/rstudio/issues/5518. We limit the number of CSV lines processed in our console output to 10000 entries, to guard against somewhat pathological cases where the user has printed many lines of console output.
=> avoid IDE hang with excessive console output (#5518)

src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/MarkdownCompletionManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/PythonCompletionManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/SqlCompletionManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/StanCompletionManager.java
This PR fixes an issue where attempts to insert a literal tab could fail in Markdown documents.
The Markdown completion manager can only provide completions in certain contexts; however, the interface for `getCompletions()` did not allow completion managers to signal when they are unable to complete. That information is necessary for tab-triggered completions, as we then want to insert a literal tab in that case.
=> fix issue with Tab insertion in Markdown documents

src/cpp/desktop/DesktopMenuCallback.cpp, src/cpp/desktop/DesktopWebView.cpp, src/gwt/src/org/rstudio/core/client/KeyboardTracker.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/events/EditEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
Closes https://github.com/rstudio/rstudio/issues/2409.
This PR makes it possible to control whether code is indented on paste, based on whether the Shift key is held down during the paste event.
The implementation here is a bit odd (using a global event tracker for the keyboard state) but this is somewhat necessitated by the way the browser event is handled and bubbled up by Ace, and the myriad of ways that a paste event can be triggered. It also gives us an implementation that works transparently on both desktop and the browser.
In effect, the Shift key is now used to "reverse" the behavior of the "indent on paste" preference. If the preference is off, then holding the shift key down will re-enable indent on paste, and vice-versa.
We might want to consider adding explicit menu items …
=> toggle whether indent occurs on paste with Shift

src/cpp/r/session/RSession.cpp
This PR fixes an issue where we would erroneously mis-encode the R `tempdir()` (and hence, files or directories within the R `tempdir()`) when that directory contained non-ASCII characters.
The primary issue is that:
1. We always keep paths encoded as UTF-8 internally;
2. We convert those paths to the system encoding on demand; especially when required by R functions.
Since we were not doing (1) when retrieving `tempdir()`, but were doing (2) in places like this:
https://github.com/rstudio/rstudio/blob/963422a13182ad8f36a2248b7a1e2594ad95fba3/src/cpp/r/session/graphics/RGraphicsDevice.cpp#L646-L647
we were effectively sending mis-encoded paths to R, and then things would fail.
Closes https://github.com/rstudio/rstudio/issues/5576, https://github.com/rstudio/rstudio/issues/2056.
NOTE: This …
=> tempdir() path uses UTF-8 encoding internally

src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopMainWindow.hpp, src/cpp/desktop/DesktopSessionLauncher.cpp
We currently show the "R failed to launch" error screen whenever R barfs (and it wasn't a quit). This is overly aggressive since R may very well have started up fine but then barfed while running.
To distinguish these cases, this change keeps track of whether the workbench was initialized since the most recent session launch. Once the workbench has initialized, we no longer treat an R crash/failure as a launch failure.
=> Only show the session launch failure page when workbench doesn't init

src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.java
- Fixes #5573
- When a control with a roving tabstop is first (or last) in a modal dialog,
it must notify the dialog when the selection moves to or from the first
(or last) tab, otherwise the tab wrapping is broken
- Fixes the two tests marked as xfail in this automation PR: https://github.com/rstudio/rstudio-ide-automation/pull/25
=> Fix tabstop wrapping in preferences dialogs when section selection changes

src/cpp/core/system/PosixSystem.cpp
On rare occasions, usually when using the rstudio terminal pane in cruel and unusual ways, I see an error logged of the form:
```
21 Oct 2019 19:04:42 [rsession-gary] ERROR system error 12 (Cannot allocate memory); LOGGED FROM: rstudio::core::FilePath rstudio::core::system::currentWorkingDirMac(PidType) /Users/gary/rstudio/src/cpp/core/system/PosixSystem.cpp:1230
```
This always seemed... unlikely, so tweaked the error handling of the proc_pidinfo call to match the pattern used in the open-source code for Mac lsof command. Next time this happens maybe I'll get a more useful error code.
https://opensource.apple.com/source/lsof/lsof-62/lsof/dialects/darwin/libproc/dproc.c.auto.html
=> Refine error handling used to get cwd of a pid on mac

src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.java
Drive-by regression fix: currently, R Markdown templates appear in the order we discovered them (which is filesystem-dependent and therefore apparently random). This change sorts them predictably.
Fixes https://github.com/rstudio/rstudio/issues/4929.
=> Sort R Markdown templates by package/name

src/cpp/session/modules/SessionConnectionsInstaller.R
See https://github.com/rstudio/odbc-install/issues/95, some drivers require setup parameter in windows registry.
CC: @blairj09 
Notice that this PR still requires proper testing in the right environment, with the particular driver, etc. which I'd suggest we do after it's merged and follow up if needed.
=> Some drivers require setup parameter in windows registry

src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java
In some contexts, `beginSuggest` returns false to indicate that we shouldn't be attempting to auto-complete (such as in the comments of a Stan document) so it doesn't even pop up a `(No matches)` message, but `onTab()` returns true regardless of the result of `beginSuggest`. This PR causes `onTab()` to return the result of `beginSuggest` which correctly allows tabs to be inserted when we shouldn't be auto-completing.
Fixes #5387.
=> Fixes an issue where neither auto-complete nor tab-insertion is taking place.

src/cpp/session/modules/SessionPackages.R
=> delegate to utils::install.packages() when pkgs not specified

src/cpp/rstudio-tests.in, src/cpp/tests/testthat/run-tests.R
Fixes #5472
The `testthat::test_dir` call is wrapped in a script that writes the number of failures to `${CMAKE_CURRENT_BINARY_DIR}/testthat-failures.log`. The unit test script checks the file and returns a non-zero exit code if there were any failures.
=> Make R unit test failures cause rsession-tests to return a non-zero exit code

src/cpp/session/modules/clang/RCompilationDatabase.cpp, src/cpp/session/modules/clang/RCompilationDatabase.hpp
Ensure that we call `R CMD SHLIB` on a `.c` file rather than a `.cpp` file when appropriate.
NOTE: This does imply that packages which mix `.c` and `.cpp` files may not get correct diagnostic output, as we maintain a single compilation cache (whereas we might instead consider having a separate one for C and C++ files). But this at least fixes issues for "pure" C packages.
The location of the compilation database is changed, to ensure that any old databases can be ignored.
Closes #5418.
=> detect packages using C rather than C++

src/cpp/shared_core/Logger.cpp, src/cpp/shared_core/system/SyslogDestination.cpp
Also moves the special formatting for syslog from Logger.cpp to SyslogDestination.cpp.
=> Log syslog messages to stderr if there's a TTY attached

src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.java
- Fixes #5609
- Don't refreshFocusableElements when the first selection is made
because the dialog isn't fully constructed yet and nothing is
actually focusable at that point
- Fix bug where I was only refreshingFocusableElement when moving from
or to the first tab; needs to happen with any tabs or the original
bug that motivated this change still happens!
- Updated Selenium accessibility test to check this case (https://github.com/rstudio/rstudio-ide-automation/pull/27)
=> prevent GWT warning message when opening Prefs dialog

src/cpp/session/modules/SessionClang.R, src/cpp/session/modules/clang/RCompilationDatabase.cpp, src/cpp/session/modules/clang/RCompilationDatabase.hpp
This is necessary as, otherwise, the precompiled headers may effectively
be incompatible with the to-be-compiled translation units used in the
package.
As an example, if the precompiled headers are generated without
'-fopenmp', but C++ files within the package are compiled with
'-fopenmp', then attempts to include precompiled headers will fail and
diagnostics will not work as expected.
Part of #4685.
=> use common compilation args when generating precompiled headers

src/gwt/src/org/rstudio/core/client/a11y/A11y.java, src/gwt/src/org/rstudio/core/client/layout/DelayFadeInHelper.java, src/gwt/src/org/rstudio/core/client/layout/FadeInAnimation.java, src/gwt/src/org/rstudio/core/client/widget/FieldSetPanel.java, src/gwt/src/org/rstudio/core/client/widget/ImageButton.java, src/gwt/src/org/rstudio/core/client/widget/InfoBar.java, src/gwt/src/org/rstudio/core/client/widget/SearchWidget.java, src/gwt/src/org/rstudio/studio/client/RStudio.java, src/gwt/src/org/rstudio/studio/client/application/ui/LauncherSessionStatus.java, src/gwt/src/org/rstudio/studio/client/application/ui/LauncherSessionStatus.ui.xml, src/gwt/src/org/rstudio/studio/client/application/ui/RTimeoutOptions.java, src/gwt/src/org/rstudio/studio/client/application/ui/RTimeoutOptions.ui.xml, src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java, src/gwt/src/org/rstudio/studio/client/application/ui/serializationprogress/ApplicationSerializationProgressLabel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
- Open-source grey spinner gave screen reader users no idea anything
was happening; now it says "Loading session" via aria-live after 3
seconds of waiting
- The spinner image has no alt-text, so would read it's internal name, made it cosmetic via empty `alt`
- If the 30 second timeout is hit, the "R is taking longer to start than
usual" message will then be read (previously was saying nothing)
- Fixed the button and message contrast for that 30-second timeout UI
- Fix issue where the button wrapper element was aria-hidden and
thus buttons were unavailable to screen readers because FadeInAnimation class wasn't
removing that attribute on completion of fadein
- For launcher sessions (Pro), will read existing "Waiting for session to start",
after three seconds, and read any intermediate …
=> Fix assorted accessibility issues with session-loading screens

src/gwt/build.xml
This allows one to access a development version of RStudio Server on
machines other than the host machine. This is useful when e.g. you are
running a dev. server locally, but need to connect from (say) a Windows
guest.
=> use 0.0.0.0 for -bindAddress in devmode

src/cpp/session/modules/SessionPackages.cpp
When the secure CRAN mirror preference is set to false, we edit the CRAN mirror preference to remove `https` from the URL. This triggers a loop (and stack overflow) since setting the CRAN mirror URL causes us to re-evaluate the aforementioned preference.
The fix is to avoid no-op edits of the preference. 
Fixes https://github.com/rstudio/rstudio/issues/5594.
=> Fix re-entrancy when disabling secure CRAN mirror

src/cpp/session/modules/SessionGit.cpp, src/cpp/session/postback/CMakeLists.txt
Closes https://github.com/rstudio/rstudio/issues/3805.
There is a bit of risk in this PR, as it looks like the original implementation (using the program name + modifying the PATH) was intentional:
https://github.com/rstudio/rstudio/commit/58dd0deacf1ac6b9f9c7173bbfa7d2c70fdcb3fe
However, it's quite possible that things have changed enough in 8 years that we can use full paths for GIT_ASKPASS / SSH_ASKPASS.
=> use absolute path for rpostback-askpass

NEWS.md, src/cpp/session/modules/SessionRCompletions.R, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
Comments starting with `#*` will provide autocomplete for the Plumber
keywords (extracted these from the latest Plumber sources).
Fixes #2220
=> add autocomplete support for Plumber keywords

NEWS.md, src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/cpp/desktop/DesktopGwtCallbackMac.mm, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Closes https://github.com/rstudio/rstudio/issues/2443.
I think changing the keybinding (and causing some short-term pain for users who are accustomed to this shortcut) is going to be less painful than getting to the bottom of why our custom monitor crashes in certain user configurations.
Let me know if you disagree and we should invest the time to see if we can get the crash under control.
=> rebind reflow comment on macOS

NEWS.md, src/cpp/session/modules/SessionHelp.R
This PR implements fuzzy matching for help topic searches. This effectively allows case-insensitive matching, as well as the omission of some characters in the string during search.
Closes #3316.
=> use fuzzy matching for help topic search

NEWS.md, src/cpp/core/include/core/r_util/RTokenizer.hpp, src/cpp/session/modules/SessionDiagnosticsTests.cpp, src/cpp/session/modules/SessionRParser.cpp, src/cpp/session/modules/SessionRParser.hpp, src/cpp/tests/testthat/themes/.gitignore
This PR improves how the diagnostics system handles missing expressions in things like:
```
local({
if (TRUE)
})
```
Previously, the closing bracket `}` was parsed as though it was part of an (invalid) expression for the `if (TRUE)` statement, ultimately leading to a parse state with mismatched parentheses causing a slew of unhelpful diagnostics to be emitted.
The fix, then, it to ensure that the token discovered after the `if (TRUE)` can actually start a new expression, and to handle the cases where it cannot more gracefully.
Closes https://github.com/rstudio/rstudio/issues/5660.
=> improve handling of missing expressions in diagnostics engine

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/widget/InlineFormLabel.java, src/gwt/src/org/rstudio/core/client/widget/ProgressBar.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateOptionsWidget.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobItem.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobLauncherControls.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobProgress.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobProgress.ui.xml
- add aria progressbar role and metadata to the ProgressBar widget
- label progressbars in Jobs tab (and Console tab) views with name 
of the job
- mark the spinner in Jobs tab as cosmetic since the progressbar (or 
the status text in case of indefinite jobs) gives sufficient feedback 
- create `InlineFormLabel` class to use in UiBinders instead of `InlineLabel`
in cases where label needs to be associated with another control, and use
in a couple places that needed it
- tweak contrast of the status text shown after a local job completes to
meet minimum requirement
=> Annotate ProgressBar with aria, contrast fixes, misc labelling fixes

src/gwt/src/org/rstudio/core/client/js/JsWindow.java, src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java, src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
Currently ModalDialogBase objects don't think too much about where and how they're set. Similarly to what was done in PR #5597 this adds logic to a base UI object class to get a little more intelligent about displaying the object.
This fix will apply to a huge number of modals in our application so I spent a lot of time testing making sure it applied as generically and unobtrusively as possible. Some dialogs aren't compatible with it but in the case where it isn't there are no side effects (that I've been able to find). If any bugs fall out of this fixing them will be as easy as special casing it just like the other PR.
Note: Ideally only the central content would scroll and the header and buttons would be pinned but due to how our modals are laid out and differ this isn't generically …
=> Resize and set overflow of ModalDialogBase

NEWS.md, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Keyboard shortcuts for these commands may now be customized (tested all of them, at least in R code):
- Execute next line
- Continue Execution
- Stop Debugging
- Step Into Function
- Finish Function/Loop
These debugging commands already supported customization (included here
as a reference):
- Toggle Breakpoint on Current Line
- Clear All Breakpoints
Fixes #3539
=> Support customization of debugging command keyboard shortcuts

src/cpp/core/FilePathTests.cpp, src/cpp/shared_core/FilePath.cpp
The new security restrictions on `completeChildPath` currently cause child paths not to be completed if the parent path has a trailing slash. This is because:
/foo/bar/
is lexically normalized to
/foo/bar/.
and, when comparing path components, we deduce that `/foo/bar/baz` is not within `/foo/bar/.` since `.` != `baz`. 
The fix is to stop comparing path components once we reach a `.`, which signals the end of a lexically normal path.
Fixes https://github.com/rstudio/rstudio/issues/5674.
=> Enable completion of paths with trailing slashes

src/cpp/core/json/JsonTests.cpp, src/cpp/session/include/session/prefs/PrefLayer.hpp, src/cpp/session/modules/SessionApiPrefs.cpp, src/cpp/session/prefs/PrefLayer.cpp, src/cpp/session/prefs/Preferences.cpp, src/cpp/session/prefs/UserPrefsComputedLayer.cpp, src/cpp/session/prefs/UserPrefsComputedLayer.hpp, src/cpp/session/prefs/UserPrefsDefaultLayer.cpp, src/cpp/session/prefs/UserPrefsDefaultLayer.hpp, src/cpp/session/prefs/UserPrefsLayer.cpp, src/cpp/session/prefs/UserPrefsLayer.hpp, src/cpp/session/prefs/UserPrefsProjectLayer.cpp, src/cpp/session/prefs/UserPrefsProjectLayer.hpp, src/cpp/session/prefs/UserPrefsSystemLayer.cpp, src/cpp/session/prefs/UserPrefsSystemLayer.hpp, src/cpp/session/prefs/UserStateComputedLayer.cpp, src/cpp/session/prefs/UserStateComputedLayer.hpp, src/cpp/session/prefs/UserStateDefaultLayer.cpp, src/cpp/session/prefs/UserStateDefaultLayer.hpp, src/cpp/session/prefs/UserStateLayer.cpp, src/cpp/session/prefs/UserStateLayer.hpp, src/cpp/shared_core/include/shared_core/json/Json.hpp, src/cpp/shared_core/json/Json.cpp
We currently load prefs in two steps:
1. The prefs are loaded from a file.
2. The preferences are validated, and a warning is logged if the prefs don't validate.
However, the invalid prefs are still used in a sort of best-effort way, since we don't want to discard the whole object. This can lead to runtime errors if the type or value of a preference doesn't match the schema expected by the code.
To address this, I've made two changes:
1. There is a new JSON helper function called `coerce`. It takes a schema and attempts to remove parts of an object that are invalid according to the schema. This makes it possible for us to selectively ignore the invalid preference values without throwing prefs away if the object doesn't match the schema as a whole. 
2. We no longer have a second "validate" …
=> Skip invalid preferences during load

src/cpp/session/SessionMain.cpp
Re: https://community.rstudio.com/t/mouse-click-return-error-navigating-to/43908
I still don't know why some users are reporting HOME / R_USER with a trailing slash, but the issue is becoming prevalent enough that it's worth working around.
=> remove trailing slashes from HOME / R_USER

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkConditionBar.ui.xml
This icon's image file is sized at 2x, but displayed in its native resolution, causing it to be too large and fuzzy on Retina displays (and just plain too large on others).
The fix is to specify the image dimensions.
Fixes https://github.com/rstudio/rstudio/issues/5697.
=> Specify dimensions for notebook condition icon

src/cpp/core/include/core/system/Environment.hpp, src/cpp/core/system/Environment.cpp, src/cpp/session/modules/SessionGit.cpp
From @jcheng5:
> jcheng 6:38 PM
> Maybe that change was there for a reason... I just upgraded to 1.3.565 on my Windows machine, and now I got this when trying to create a new project from a GitHub repo:
> 
> >>> C:/Program Files/Git/bin/git.exe clone --progress git@github.com:jeroen/curl curl
> Cloning into 'curl'...
> ssh_askpass: exec(C:/Program Files/RStudio/bin/postback/rpostback): No such file or directory
> git@github.com: Permission denied (publickey).
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> And sure enough, adding C:/Program Files/RStudio/bin/postback/ to the path and using rpostback-askpass as the GIT_ASKPASS and SSH_ASKPASS fixed it.
So it looks like the PATH munging is required for …
=> always place postback dir on PATH

src/cpp/session/resources/CITATION.in
=> missing 'Environment' in citation

src/.gitignore, src/cpp/shared_core/CMakeLists.txt, src/cpp/shared_core/Logger.cpp, src/cpp/shared_core/ReaderWriterMutex.cpp, src/cpp/shared_core/include/shared_core/ReaderWriterMutex.hpp
Using a reader-writer lock because most of the logging work will be "read" only (writing logs is read only, adding/removing log destinations is write). The R/W lock implementation is write-preferring because writing should happen so much less often than reading. Some cursory profiling on Windows and OSX show there's no appreciable impact on performance by the logging code.
Fixes #5634
=> Make the new logger implementation threadsafe.

src/cpp/core/system/System.cpp, src/cpp/desktop/synctex/rsinverse/RsInverseMain.cpp, src/cpp/desktop/urlopener/UrlOpenerMain.cpp, src/cpp/diagnostics/DiagnosticsMain.cpp, src/cpp/monitor/MonitorClient.cpp, src/cpp/monitor/include/monitor/MonitorClient.hpp, src/cpp/server/ServerMain.cpp, src/cpp/server/crash-handler-proxy/CrashHandlerProxyMain.cpp, src/cpp/server/pam/PamMain.cpp, src/cpp/session/SessionMain.cpp, src/cpp/session/postback/PostbackMain.cpp, src/cpp/shared_core/FileLogDestination.cpp, src/cpp/shared_core/Logger.cpp, src/cpp/shared_core/StderrLogDestination.cpp, src/cpp/shared_core/include/shared_core/FileLogDestination.hpp, src/cpp/shared_core/include/shared_core/ILogDestination.hpp, src/cpp/shared_core/include/shared_core/Logger.hpp, src/cpp/shared_core/include/shared_core/StderrLogDestination.hpp, src/cpp/shared_core/include/shared_core/system/SyslogDestination.hpp, src/cpp/shared_core/system/SyslogDestination.cpp
This matches behaviour we had before the refactor of logging. There is a branch prepared on the Pro repo which resolves compile issues caused by this change.
=> Allow a log level to be set per destination.

src/cpp/monitor/MonitorClient.cpp
- On macOS was getting:
```
MonitorClient.cpp:33:7: warning: field 'programIdentity_' will be initialized after base 'rstudio::core::log::ILogDestination' [-Wreorder]
programIdentity_(programIdentity),
^
```
=> Fix C++ compiler warning about initialization order

src/gwt/src/org/rstudio/core/client/widget/ThemedPopupPanel.java
- Fixes #3395
- Keeps build book dropdown in window when build pane is in left column
Before
After
=> prevent popuppanels from going off left of browser window

src/cpp/session/modules/clang/RCompilationDatabase.cpp, src/cpp/session/modules/clang/RCompilationDatabase.hpp
- Rather than recomputing the compilation arguments for precompiled headers, we just pass along all of the arguments that were inferred from the appropriate context.
- `commonCompilationArgs()` is really package-centric; rename it as appropriate and don't use it for `sourceCpp()` configuration.
Closes https://github.com/rstudio/rstudio/issues/5707.
=> pass inferred completion config to precompiledHeaderArgs

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/command/AppCommand.java, src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java, src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectPublishButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionsPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ObjectBrowser.css, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarWidget.java, src/gwt/test/org/rstudio/core/client/ElementIdsTests.java, src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
Assorted element IDs were being duplicated with each document tab opened in the editor so make sure they go through our de-dupping code, and that it happens after the element is added to the DOM.
Added alt-text to images shown in editor context status area (function, lambda, etc).
Mark image in connections tab as decorative, and fix contrast of the (No Tables) message to match other "no content-ish" labels in various panes.
Some drive-by source reformatting to match our decided-upon lambda brace style
=> prevent duplicate IDs in editor, fix couple more unlabeled images

src/cpp/core/include/core/http/AsyncServerImpl.hpp, src/cpp/core/include/core/http/TcpIpAsyncServer.hpp, src/cpp/server/ServerInit.cpp, src/cpp/server/ServerInit.hpp, src/cpp/server/ServerMain.cpp, src/cpp/server/ServerOptions.cpp, src/cpp/server/include/server/ServerOptions.hpp
This change gives the user the ability to configure arbitrary headers to add to all rserver responses by using the new multi-option `server-add-header`, giving it the form `HeaderName:HeaderValue`.
This will allow users to easily stamp arbitrary headers on responses without having to mess with a reverse proxy (or in the RSP case, modifying the nginx template).
Fixes https://github.com/rstudio/rstudio-pro/issues/1205.
=> Add the ability to stamp arbitrary headers on all server responses

src/cpp/session/modules/SessionBuild.R, src/cpp/session/modules/build/SessionBuild.cpp, src/cpp/session/modules/build/SessionBuildErrors.cpp
The IDE currently assumes that shinytest scripts live in a folder called `tests`. A recent version of shinytest has changed the location of this folder to `tests/shinytests`, with the result that the IDE can't find the tests from the app, nor the app from the tests.
Unfortunately, we need to be compatible with both layouts, so this change attempts to do so. It's possible to ask shinytest itself to locate the tests folder given the app folder (but not the other way around, so we use a heuristic there). 
Fixes https://github.com/rstudio/rstudio/issues/5703
Fixes https://github.com/rstudio/rstudio/issues/5677
=> Use ./shinytests/tests instead of ./tests for newer shinytest

src/gwt/src/org/rstudio/core/client/widget/FullscreenPopupPanel.java, src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenuButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionSnippetHost.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobItem.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobItem.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourcePane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/cpp/CppCompletionSignatureTip.java
- Close icon on the FullscreenPopupPanel
- ToolbarPopupMenuButton used in two places in source editor
- Warning icon in connections snippet UI
- Tweaked JobItem spinner to use DecorativeImage instead of adding empty
alt text to a regular Image
- next/prev arrows shown in C++ signature completion tooltip
- chevron shown in source tabs when they don't all fit
=> add accessible text to several more UI images

src/cpp/core/include/core/r_util/RToolsInfo.hpp, src/cpp/core/r_util/RToolsInfo.cpp, src/cpp/session/modules/build/SessionBuildEnvironment.cpp, src/cpp/session/modules/clang/RCompilationDatabase.cpp
Previously, an error when attempting to scan the registry for Rtools would inhibit any further discovery of installed copies of Rtools. Now, such failures are logged as appropriate, but further scanning of Rtools will still occur.
=> be more permissive when scanning for rtools

src/gwt/src/org/rstudio/core/client/theme/ModuleTabLayoutPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/ConsoleTabPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchTabPanel.java
- previously the source pane's tablist had "Documents" label, but the other three were all labeled as "Pane"
- changed so they are now "Documents" (unchanged), "ConsoleTabSet", "TabSet1" and "TabSet2"
- minor accessibility tweak, but also handy when reading the HTML
=> give each pane's tablist a unique label

NEWS.md, src/gwt/src/org/rstudio/studio/client/common/debugging/BreakpointManager.java
Quick fix for a long-standing debug issue. When we hit a breakpoint, we step past it into the user's R code; unfortunately, that step is executed from every RStudio window, so we can wind up stepping more than we meant to.
The fix is to step only from the main window. 
Fixes https://github.com/rstudio/rstudio/issues/3683.
=> Only emit debug step commands from main window

NEWS.md, src/gwt/src/org/rstudio/studio/client/workbench/views/plots/Plots.java, src/gwt/src/org/rstudio/studio/client/workbench/views/plots/PlotsPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/plots/PlotsSurface.java, src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/manipulator/ManipulatorManager.java
It's not currently possible to copy plots to the clipboard using the context menu. This problem exists because there's a layer over the plot we use to draw manipulation UI, and that layer intentionally masks mouse clicks. 
The fix is to disable/hide the plot surface overlay unless we are actually showing a manipulator.
Note that there's a comment that indicates that the plot surface overlay serves a second purpose: keeping mouse events from getting lost during workbench splitter resize. As far as I can tell this is no longer a problem under Chromium, and was probably specific to the older QtWebKit browser. 
Fixes https://github.com/rstudio/rstudio/issues/3142 (which I discovered independently when looking at https://github.com/rstudio/rstudio/issues/5712).
=> Enable copying plot images to the clipboard from context menu

dependencies/linux/install-qt-sdk, dependencies/osx/README, dependencies/osx/install-qt-sdk-osx, dependencies/windows/install-qt-sdk-win.cmd, dependencies/windows/qt-noninteractive-install-win.qs, docker/jenkins/Dockerfile.bionic-amd64, docker/jenkins/Dockerfile.centos7-x86_64, docker/jenkins/Dockerfile.centos8-x86_64, docker/jenkins/Dockerfile.debian9-x86_64, docker/jenkins/Dockerfile.opensuse15-x86_64, docker/jenkins/Dockerfile.windows, docker/jenkins/Dockerfile.xenial-amd64, src/cpp/desktop/CMakeLists.txt
- Debug builds work again on Mac, so removed support for 5.12.1
- switched to downloading and mounting the official dmg on Mac, instead of extracting and repackaging it in a tarball
- offline installers for Mac/Windows/Linux uploaded to S3
=> Update to Qt 5.12.6

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/theme/MinimizedModuleTabLayoutPanel.java, src/gwt/src/org/rstudio/core/client/theme/ModuleTabLayoutPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/DelayLoadWorkbenchTab.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsolePane.java
- put id of feature tabs (e.g. Console, Terminal, History, etc) on the actual role=tab element instead of a layout element nested inside it
- fix code that was supposed to give the panes of each feature tab a unique id (workbench_pane_terminal, etc.) but wasn't ever being executed
- give the feature panels the aria tabpanel role since they are controlled by tabs
- provide aria-labels for the tabpanels so they can be identified via screen reader
- delete unreachable code in DelayLoadWorkbenchTab (likely some abandoned approach from early days of the codebase)
- unique id and tabpanel role for the Console pane (special case)
=> annotate tabs and panes properly for improved screen reader navigation

src/cpp/desktop/DesktopBrowserWindow.cpp, src/cpp/desktop/DesktopMain.cpp
- tweaks based on work-in-progress by Qt team to improve VoiceOver support
for QtWebEngine: https://codereview.qt-project.org/c/qt/qtwebengine/+/281210
- this change only includes the application changes (versus changes to
Qt itself) and provides some improvement in behavior, though far from
what we'd call usable
- Mac desktop only, and only if screen-reader support is turned on in RStudio
- Also removing the check for RSTUDIO_ACCESSIBILITY environment variable as a way to enable QtWebEngine's screen-reader support; potential for disconnect between the desktop code's understanding of accessibility mode vs. the GWT code's understanding and is unnecessary given new preferences system and accessibility preferences
=> improve ability of VoiceOver to see focus changes in Mac Desktop IDE

src/cpp/shared_core/FilePath.cpp
- `.level()` -> `.depth()`, as per https://github.com/rstudio/rstudio/issues/5742.
- remove `BOOST_FILESYSTEM_NO_DEPRECATED`, as we don't want to break users who want to build RStudio against future versions of Boost if possible.
=> avoid (but allow) use of deprecated Boost filesystem APIs

src/cpp/core/include/core/http/TcpIpAsyncClientSsl.hpp
TLS v 1.3 now requires SNI on requests.
This PR needs to be cherry picked to v1.2-patch.
=> Set the server name indication so we can work with TLS v 1.3.

CMakeCompiler.txt, src/gwt/src/org/rstudio/core/client/dom/WindowEx.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorMonitor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
On Windows, the Ace editor scroll speed seems to scale with the device pixel ratio, so that systems with higher display scaling (e.g. high DPI displays) will see the editor scroll more lines than expected -- e.g. one might see 12 lines per tick when scrolling with a mousewheel and 300% zoom.
The (simple) solution is to just re-scale Ace's scroll speed based on the device pixel ratio.
Closes https://github.com/rstudio/rstudio/issues/5098.
=> adjust scroll speed if device pixel ratio changes

src/cpp/session/modules/SessionBreakpoints.R
Fixes an issue where attempts to set breakpoints within functions whose names are quoted would fail. The fix ensures those quotes are removed when attempting to find the requested function.
Closes #5760.
=> unquote function names during lookup

src/cpp/session/modules/SessionConnectionsInstaller.R
When installing ODBC drivers in Linux, seems like a better option to use `~/odbcinst.ini` to avoid permissions issues since it would otherwise require `sudo` to be modified.
=> Use home dir odbcinst.ini file in linux since users don't need sudo

NEWS.md, src/cpp/r/include/r/session/RSession.hpp, src/cpp/r/include/r/session/RSessionState.hpp, src/cpp/r/session/RSessionState.cpp, src/cpp/r/session/RSuspend.cpp, src/cpp/session/SessionOptions.cpp, src/cpp/session/SessionSuspend.cpp, src/cpp/session/include/session/SessionConstants.hpp, src/cpp/session/include/session/SessionOptions.hpp
Use to prevent specific environment variables from being saved (and thus restored) when a session suspends. Specify as a colon-separated list in rsession.conf:
`session-env-var-save-blacklist=FOO:BAR:ETC`
Will add to admin guide once ported over to Pro repo.
Candidate for backporting to 1.2-patch.
Fixes #5769
=> added session config option for blacklist of env vars when saving/restoring session

src/gwt/src/org/rstudio/core/client/HandlerRegistrations.java, src/gwt/src/org/rstudio/core/client/widget/HyperlinkLabel.java
- control is used in File pane (breadcrumbs), preferences panes,
about dialog, handful of other locations, potentially preventing a
fair amount of JavaScript garbage collection
=> release handlers when HyperlinkLabel control unloads

src/cpp/session/include/session/prefs/PrefLayer.hpp, src/cpp/session/include/session/prefs/Preferences.hpp, src/cpp/session/modules/SessionUserPrefs.cpp, src/cpp/session/prefs/PrefLayer.cpp, src/cpp/session/prefs/Preferences.cpp
Currently, the file monitor that watches for user preference changes gets unregistered very late in session shutdown, when the static objects storing the preference layers are freed. This has been observed to create problems, so this change moves preference layer destruction (including freeing and unregistering file monitoring) into code run during a clean session shutdown. 
Fixes https://github.com/rstudio/rstudio/issues/5222.
=> Destroy preference layers during session shutdown

src/cpp/shared_core/FileLogDestination.cpp, src/cpp/shared_core/include/shared_core/FilePath.hpp, src/cpp/shared_core/include/shared_core/PImpl.hpp, src/cpp/shared_core/include/shared_core/ReaderWriterMutex.hpp, src/cpp/shared_core/json/Json.cpp
These are some minor issues I found in shared_core while integrating these classes with the RStudio Launcher Plugin SDK. Mainly whitespacing, spelling, or include issues.
=> Fix some issues with shared_core

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Fix silly mistake. I broke several cheatsheet commands a while back when I was adding hotkeys; put the underscores in the IDs instead of the menuLabels, so on Server the menu displayed as this:
Now back to this:
=> fix cheatsheet commands to avoid empty cheatsheet menu items

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/ChooseEncodingDialog.java
- multi-select serves no purpose in this dialog, and the code only looks at first-selected item
- also give listbox an aria-label of "Encodings"
Example of multi-select (after this change only supports single-select):
=> remove multi-select capability from choose encoding dialog listbox

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml
On my previous pass through this dialog I missed the controls that are shown when you select "Custom Filter". This fixes issues with those:
- contrast of the text showing examples was too low (bumped up contrast)
- no accessible label for the custom pattern textfield (added `aria-label`)
- example shown below textfield was not associated with the textbox (associated with `aria-description`)
- behavior varies by screen reader, but on VoiceOver/macOS, when you tab to the text field it will now read it's label ("Custom Filter Pattern"), then the contents of the field, then after a brief pause, the description ("Example: *.R, *.r, *.csv...")
=> fix accessibility of Find in Files when custom pattern option is selected

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/widget/FormTextArea.java, src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.java, src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.ui.xml
Associate "RStudio Pro License Status" label with textbox. This is only shown in Pro desktop, but code is identical in Open Source so making the change there.
=> associate label with field in About dialog (pro license status)

src/cpp/session/modules/SessionTests.R, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/shiny/model/ShinyTestResults.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/TestServerOperations.java
This change fixes a couple more places where we implicitly presumed that (a) test directories were child directories of the Shiny app folder, and (b) the name of the test directory was "tests". Unfortunately both of these are no longer true with the latest version of shinytest, and we need to be compatible with both formulations, so the logic has become more complex.
Fixes https://github.com/rstudio/rstudio/issues/5677. (again)
=>  Look in correct paths for shiny tests/app for 'compare results'

NEWS.md, src/cpp/core/BrowserUtils.cpp, src/gwt/www/unsupported_browser.htm
This change updates (often dramatically) the minimum browser version for RStudio for each of the four browsers we support. 
The version numbers are not based on the lowest version RStudio works with but rather on the lowest version the browser vendor supports at time of writing, as we could not otherwise feasibly obtain an older version to test with, and customers using older versions are already out of support from the browser vendor. 
Closes https://github.com/rstudio/rstudio/issues/5593.
=> Update supported browser versions

NEWS.md, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/diff/LineTableViewCellTableStyle.css
It is not currently possible to select and copy text from VCS diffs. This is a regression from 1.1 and annoying for people (I certainly don't know any) who copy selectively from VCS diffs to restore snippets of deleted code. 
The fix is to just use a slightly more aggressive CSS rule to make the text selectable. The rule already existed, but stopped working in newer Chromium builds (possibly because it was vendor prefixed). 
Fixes https://github.com/rstudio/rstudio/issues/4734.
=> Allow user selection of text in VCS diffs

NEWS.md, src/cpp/session/resources/sumatrapdfrestrict.ini
Small change to our Sumatra .ini configuration to pick up the ability to preview in fullscreen. I compared the current version of this ini file against the one on Sumatra's Git repo and added one additional comment line.
Fixes #4301.
=> Allow fullscreen mode in SumatraPDF

NEWS.md, dependencies/common/install-pandoc, dependencies/tools/upload-pandoc.sh, dependencies/windows/install-dependencies.cmd, src/cpp/session/CMakeLists.txt
This change updates Pandoc to 2.7.3 on all platforms. This isn't, strictly speaking, the latest version of Pandoc. However, it is the last release in the 2.7 series, and 2.8 was released very recently with lots of churn so probably not safe to pull it in yet. 
It also adds a script to upload new versions of Pandoc to the build tools folder, which will save seconds and seconds of developer time. 
We have been using 2.7.2 on Windows for a while without incident, so we don't expect any trouble. 
Closes #4512.
=> Update to Pandoc 2.7.3

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- Fixes #5811 (at least partially)
In places where we show read-only text boxes, most commonly in file/directory pickers, make background the same as the dialog color to give a hint of its read-only-ness. Can still get keyboard focus allowing selection and copying (and screen reader ... reading).
Making these editable is deemed too much work at this stage due to need to revisit each usage and potentially relocate validation code, etc.
Here's an example of an editable picker, for contrast.
=> change background of read-only textboxes

src/cpp/session/modules/clang/RCompilationDatabase.cpp, src/cpp/session/modules/clang/RCompilationDatabase.hpp
This PR forces RStudio to rebuild precompiled headers (as well as the cached compilation arguments) when `~/.R/Makevars[.win]` has changed.
Closes #5806.
=> rebuild pre-compiled headers when Makevars changes

src/gwt/src/org/rstudio/studio/client/common/vcs/ignore/IgnoreDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
- Tab and Shift+Tab will now always move focus out of the text editor for gitignore files; ability to indent/outdent seems unnecessary in this particular Ace instance
=> fix tab-trap in gitignore edit field

src/gwt/src/org/rstudio/studio/client/common/rstudioapi/ui/AskSecretDialog.java, src/gwt/src/org/rstudio/studio/client/common/rstudioapi/ui/AskSecretDialog.ui.xml, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.ui.xml
Switched to using HyperlinkLabel to get full keyboard + mouse support. Prior to this you couldn't get focus on these links or activate them with keyboard.
In the Publish dialog, the Add New Account "link" can now be used via keyboard.
In the Ask Secret dialog, the UI state when keyring package wasn't installed was awkward for screen readers (in addition to not working with keyboard), had low contrast, and a checkbox (always disabled) that failed automated accessibility tests because it had no associated label. Also, the hyperlink "keyring" didn't provide any context to explain what it is for (another a11y violation).
So changed this:
to this:
=> fix links in Ask Secret and RS Connect dialogs to work with keyboard

src/cpp/core/include/core/json/JsonRpc.hpp, src/cpp/core/json/JsonRpc.cpp, src/cpp/session/SessionModuleContext.cpp
Otherwise, calls like `pResponse->setError(error, "a message")` will
have the const char* string implicitly converted to bool, unexpectedly
selecting the overload `setError(Error, bool)`.
Also fix an issue where RStudio would fail to open certain JSON files --
specifically, those detected as 'application/json' as opposed to
'text/json'. renv.lock is one such file that is sometimes detected in
this way.
=> provide string overloads when setting error

src/cpp/r/R/Tools.R
Closes #5848. See inline comment for justification in the change.
=> set library paths before loading package on restore

NEWS.md, src/cpp/session/modules/build/SessionBuild.cpp
This PR fixes an issue where library paths set in e.g. a `.Rprofile` are not respected during a package build (in the roxygenize stage).
Note that we also forward R_LIBS for the actual build here:
https://github.com/rstudio/rstudio/blob/ac3f63134911ff61451e6159997c0b87f3e3732d/src/cpp/session/modules/build/SessionBuild.cpp#L692-L695
so I believe it makes sense to forward `R_LIBS` for both stages of the build.
(We could also consider forwarding `R_LIBS` universally, but that's a larger change that I didn't feel comfortable making)
=> forward R_LIBS during roxygenize

src/cpp/core/include/core/system/PosixSystem.hpp, src/cpp/core/include/core/system/System.hpp, src/cpp/core/system/PosixSystem.cpp, src/cpp/core/system/ProcessTests.cpp, src/cpp/core/system/System.cpp, src/cpp/core/system/Win32System.cpp
This change adds a recursion depth when killing child processes to ensure we don't blow the stack. 
Also, refactored some of the child process code out of PosixSystem and Win32System and into the base system file for more code re-use.
Closes #5478.
=> Added recursion depth limits when killing child processes

src/cpp/desktop/DesktopInputDialog.cpp, src/gwt/src/org/rstudio/core/client/widget/NumericTextBox.java
- all browsers we care about support input type=number; probably wasn't the case when this code was written (https://caniuse.com/#feat=input-number)
- better accessibility support by using the native html control, and makes it more obvious you can use up/down arrows to change numbers (bet hardly anybody knew it supported that, I didn't until I read the code)
- for desktop, associate textbox with label in native-Qt prompt-for-text messageboxes
Places the NumericTextBox control is used:
(prompting for a number, Server-only):
(rmd numeric options)
The desktop dialog used to prompt for strings and numbers:
=> use html input type=number instead of emulating in JavaScript

src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
- accessibility tweaks in shared code made it necessary to request horizontal layout
- couldn't find any other instances impacted by this change in behavior
=> fix layout of "save workspace" preference control

NEWS.md, src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileUploadDialog.java
While evaluating accessibility of the Upload Files dialog, noticed that there was orphaned code indicating an intent to supporting choosing target folder from the dialog.
As it stands, the target folder is set to match Files Pane location when the dialog is shown.
Relatively easy to swap in our DirectoryChooser control. One small tweak was needed (setting type="button" on a `<button>`) to prevent the Browse button from causing form submission on some browsers.
I considered also working on accessibility of the "File to upload" part of the dialog, but captured that in #5856 for future consideration.
=> enable target directory selection in Upload Files dialog

src/cpp/session/modules/SessionDependencies.cpp, src/cpp/session/modules/jobs/ScriptJob.cpp, src/cpp/session/modules/jobs/ScriptJob.hpp, src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java, src/gwt/src/org/rstudio/studio/client/common/dependencies/model/DependencyList.java, src/gwt/src/org/rstudio/studio/client/common/dependencies/model/DependencyServerOperations.java, src/gwt/src/org/rstudio/studio/client/projects/Projects.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
This change causes dependencies to be installed using a job instead of a modal dialog:
This applies to the two areas where we most frequently install R packages on demand:
- When we detect missing packages in R scripts/R Markdown documents
- When we detect missing packages needed for IDE functionality
The primary motivation for this change is to make it possible to see what's gone wrong if a package installation fails, which is currently almost impossible since the modal disappears once the installation exits (regardless of success). A secondary benefit is that you can do other work while packages install. 
A downside is that because there's no longer a modal, the action that occurs when the packages are done installing may feel unexpected, especially if the packages take time to install. …
=> Install package dependencies using a script job

src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java
- Also enables running selection-as-job from code-browser tabs
- Fixes #5863
=> hide "Run Selection as Job" commands on Code menu when not supported

src/cpp/session/prefs/PrefLayer.cpp, src/cpp/session/prefs/Preferences.cpp
We currently clean up pref layers during shutdown, but this turns out to introduce some ordering problems because in some situations prefs are read *during shutdown*, so we need to keep them around for the whole shutdown process.
The motivation for destroying prefs during shutdown was to clean up the file monitor at the right point in the shutdown sequence; this change preserves that behavior while leaving the layers otherwise intact.
Fixes https://github.com/rstudio/rstudio/issues/5872.
=> Keep pref layers around during shutdown

src/cpp/session/modules/SessionPlots.cpp
=> avoid invalid with/height redirects & increase maximum plot size

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/spelling/SpellingDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/spelling/SpellingDialog.ui.xml
Associate labels with the two textareas, and provide an aria-label for the unlabeled select control.
=> associate labels with controls in spelling dialog

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNResolveDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNResolveDialog.ui.xml
An example of a simple-looking dialog with a remarkable number of accessibility problems. Fixed by brute force in code. If I come across more examples following this same pattern I might consider creating a standard control that hides the gory details, but this does the trick for this case.
Problems:
- contrast too low on descriptions (bumped up contrast)
- radio buttons not associated with their labels (gave labels IDs, then associated radio buttons via `for`) 
- radio buttons not associated with their descriptions (gave descriptions IDs, then associated buttons with `aria-describedby`); a screen reader will typically read the label, pause, then read the description (depending on screen reader verbosity settings)
- group of radio buttons not associated with heading ("Resolve the selected …
=> fix accessibility of SVN Resolve dialog

NEWS.md, src/gwt/src/org/rstudio/core/client/MathUtil.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermTheme.java
- essentially shortcuts for dragging vertical splitter all the way to left or right, and will toggle back to previous position if you select command again
- doesn't change zoom state of panes within the left/right column
- especially handy for keyboard-only users
Partially addresses #5498 but that issue is also requesting ability to switch to Source/Console only view from any other configuration, which this doesn't quite address (e.g. if Console was zoomed, this command wouldn't unzoom it).
=> add commands for zooming left/right UI columns

src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/SessionConsoleProcessInfo.cpp, src/cpp/session/include/session/SessionConsoleProcessInfo.hpp, src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/prefs/UserPrefValues.cpp, src/cpp/session/resources/schema/user-prefs-schema.json, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcessInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
- previously, there was a boolean option to either keep the pane open, or close it, but behind the scenes was another check that would keep the pane open if shell exited with non-zero code, and the user had no way to override that (this was added in 1.3)
- new option has three choices, always close, never close, close if shell exits cleanly; this gives user control over this new behavior I added in 1.3 (checking exit code)
- I didn't bother migrating the old setting forward, if user had changed it, they will need to do so again on 1.3 upgrade
- Here's what an exited, non-closed terminal pane shows (this isn't new, but just FYI):
- Also simplified setting of another recently added terminal preference in the UI (I was setting state via bruce force if/then/else instead of letting the …
=> add more control over terminal behavior after shell exits (user pref)

src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/header/MenubarPanel.css
- was hardcoded to white, which is almost invisible in light themes
- now it is black in light themes, white in dark themes (same as it is when toolbar is visible)
- Fixes #5651
- also added invisible aria-label of "Username" so screen reader has something to describe this text
Tested on light and dark themes:
=> fix text color of username when toolbar hidden

src/gwt/www/css/focus-visible.css, src/gwt/www/templates/encrypted-sign-in.htm
Fixes #5557 
- import the same polyfill used in the main IDE
- tweaked focus style for the Sign In button; it is solid blue and very hard to see our standard focus rectangle, so put in an offset
- fixed various html / css issues:
- `align="center"` is deprecated on `<table>` so use css, instead
- collapse padding-left/right/top/bottom to single-line form
- added `<body>` to the page
- removed duplicate `autocomplete` attribute on password `<input>`
- fix nesting of `<p>` in another `<p>` (not allowed), replaced outer one with `<div>` and correct closing tags which were messing with the nesting (confusing to look at because this file isn't indented consistently, but same tool that saw the busted HTML nesting now confirms it is correct); after this checkin I may run an auto-indent on this …
=> use focus-visible polyfill on sign-in page

src/gwt/src/org/rstudio/core/client/a11y/A11y.java, src/gwt/src/org/rstudio/core/client/widget/AriaLiveStatusWidget.java, src/gwt/src/org/rstudio/core/client/widget/FilterWidget.java, src/gwt/src/org/rstudio/core/client/widget/LiveRegionWidget.java, src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java, src/gwt/src/org/rstudio/core/client/widget/SearchWidget.java, src/gwt/src/org/rstudio/core/client/widget/SearchWidget.ui.xml, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/application/ApplicationView.java, src/gwt/src/org/rstudio/studio/client/application/events/ApplicationEventHandlers.java, src/gwt/src/org/rstudio/studio/client/application/events/AriaLiveAnnouncementEvent.java, src/gwt/src/org/rstudio/studio/client/application/events/AriaLiveClearStatusEvent.java, src/gwt/src/org/rstudio/studio/client/application/events/AriaLiveStatusEvent.java, src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java, src/gwt/src/org/rstudio/studio/client/application/ui/GlobalToolbar.java, src/gwt/src/org/rstudio/studio/client/application/ui/LauncherSessionStatus.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/application/ui/serializationprogress/ApplicationSerializationProgressLabel.java, src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
New command on accessibility menu for sending keyboard focus to main toolbar.
Fixes #5458
Also adds a framework to the main window so you can cause an aria-live polite announcement by firing an `AriaLiveStatusEvent` with the string you want spoken.
Hooked that up when main toolbar visibility is changed, and also to announce when main toolbar is hidden and thus cannot get focus. None of these are terribly important scenarios, mainly doing to test the new mechanism. Will be using in a bunch of other places in the future.
Also provided this mechanism in modal dialogs so same event can be used to announce things from a modal dialog.
=> Accessibility command to put focus on main toolbar

NEWS.md, src/cpp/core/system/Crypto.cpp
Note: worth considering making this configurable, but that's a larger change.
=> bump RSA key size to 2048

src/gwt/src/org/rstudio/core/client/widget/NumericTextBox.java, src/gwt/src/org/rstudio/core/client/widget/NumericValueWidget.java, src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectEditingPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesPane.java
- provides native spin-button UI and range-checking
- needs slightly more horizontal space due to spin-button UI
- moved tracking of min/max into the NumericValueWidget control so it can be supplied via constructor
- if there is a validation error when "OK-ing" the preferences, attempt to put focus on the offending control after error message (limitation, if error is on a different property page, won't change back, just leave focus on the OK button)
=> Use html numeric textfield for integer input in preferences panes

src/gwt/www/css/focus-visible.css
- Fixes #5456
- Focus rectangles aren't needed on menus; they already indicate keyboard focus
=> remove focus rectangles around menus

src/gwt/src/org/rstudio/core/client/a11y/A11y.java, src/gwt/src/org/rstudio/core/client/widget/InfoBar.java, src/gwt/src/org/rstudio/studio/client/RStudio.java, src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java
- alerts default to atomic and assertive, no need to set
- also, status defaults to atomic and polite
=> (cleanup) use GWT roles for alerts instead of custom code

src/cpp/session/modules/SessionErrors.cpp, src/cpp/session/modules/SessionPlumberViewer.cpp, src/cpp/session/modules/SessionShinyViewer.cpp, src/cpp/session/prefs/Preferences.cpp, src/cpp/tests/testthat/test-shiny.R
This change fixes an issue in which changing the Shiny viewer type preference does not actually change the Shiny viewer type. The cause is a typo-level problem; the preference change handler was accidentally bound to the preference layer name instead of the preference key name, with the result that the preference was never detected as changed. 
Also opportunistically fixes a couple other instances of this problem, and adds a unit test to ensure the problem does not regress. 
Fixes #5920.
=> Fix disconnect between Shiny viewer type and associated pref

NEWS.md, src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/modules/SessionConsole.cpp, src/cpp/session/prefs/UserPrefValues.cpp, src/cpp/session/resources/schema/user-prefs-schema.json, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
Inspired by https://community.rstudio.com/t/more-than-1000-lines-output-in-r-studio-console/3288 and a parallel conversation with @alandipert; this is a drive-by change which makes it possible to adjust the size of the console scrollback buffer, either down for performance on slow systems or up for capturing very long outputs. Obviously the best thing to do would be to virtualize the console entirely so performance isn't an issue, but that change won't make this release. 
This setting is intended for use only by power users who understand the implications of changing it, so it does not have UI.
=> Make console max line limit configurable

src/cpp/core/include/core/terminal/PrivateCommand.hpp
- Fixes #2267
- Many variables here, so possible some combination of complex dynamic prompts and a slower machine could still result in a duplicate prompt after environment capture command finishes; the ultimate end-user fix is to turn off saving and restoring environment variables, but this change should fix it for many users
- See also #1454 for an earlier example of this issue
=> reduce chances of duplicate terminal prompt with complex dynamic prompt

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/studio/client/common/vcs/CreateKeyDialog.java, src/gwt/src/org/rstudio/studio/client/common/vcs/ShowPublicKeyDialog.java
- give the overall dialog a description, and provide a label for the text area
- other minor source style cleanup
=> associate label with text area in ShowPublicKeyDialog

src/gwt/src/org/rstudio/studio/client/workbench/ui/unsaved/UnsavedChangesDialog.java
- Provides immediate info to screen reader user about how many files are involved
Before, always read "The following files have unsaved changes" for any number of files (including 1). Now:
=> Include count of unsaved files in unsaved files alert dialog

src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/ShinyDocumentWarning.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/ShinyDocumentWarning.ui.xml, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/ShinyDocumentWarningDialog.java
- mark image as decorative
- read the message when dialog is shown
- set initial focus on the Ok ("Yes, Once") button
=> Fix accessibility issues in Shiny Document Warning dialog

src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlot.css, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/ExportPlotResources.java, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/SavePlotAsImageTargetEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/export/SavePlotAsPdfDialog.java
- grey background for selected directory read-only textbox in "Save Plot as PDF" dialog (matching other similar controls)
- fix layout of "View plot after saving" checkbox in "Save Plot as PDF" dialog
- use read-only text for selected directory instead of label in "Save Plot as Image" dialog, matching behavior of "Save Plot as PDF" dialog
=> Fix assorted visual consistency issues with export plot dialogs

src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdChoiceOption.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdFileOption.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdFloatOption.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdNullableOption.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdStringOption.java
- in addition to the standard case of using a label and associating with its control via "for", have to also deal with "nullable" controls, which consist of a checkbox with a label, followed by a control; visually the label applies to both the checkbox and the subsequent control, so mimic this for screen readers by using aria-label with the checkbox's label text
Typical example (this dialog is dynamically generated in many different configurations):
=> Associate labels and controls in Rmd Options dialog

src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateOptionsWidget.java
- aria annotation to identify tabpanels and their controlling tabs, used by screen readers
=> Annotate and associate tabpanel with controlling tabs in RmdTemplateOptions dialog

src/gwt/src/org/rstudio/core/client/command/AppCommand.java
- see these "AppCommand executed but nobody was listening" exceptions from time to time and often not sure what command I triggered to cause it; add the command's ID to the message
29 Dec 2019 04:50:58 [rserver] ERROR CLIENT EXCEPTION (rsession-gary): AppCommand executed but nobody was listening;
29 Dec 2019 04:53:42 [rserver] ERROR CLIENT EXCEPTION (rsession-gary): AppCommand executed but nobody was listening: **showAboutDialog**;
=> Show AppCommand's Id when "nobody was listening"

src/gwt/src/org/rstudio/core/client/widget/ToolbarButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java
- Git pane and Text pane set labels to empty string on some toolbar buttons depending on width of the pane; this resulted in no accessible text for these buttons making them unusable via screen reader
- Provide a helper that either sets the label normally, or sets it to blank but puts the text into an aria-label
Example (git pane):
=> Provide aria-label for toolbar buttons whose labels are hidden

src/cpp/desktop/html/connect.html, src/cpp/desktop/html/error.html, src/gwt/www/404.htm, src/gwt/www/error.htm, src/gwt/www/expired.htm, src/gwt/www/offline.htm, src/gwt/www/progress.htm, src/gwt/www/projectnotfound.htm, src/gwt/www/unsupported_browser.htm
- remove unnecessary type="text/javascript"
- remove unnecessary type="text/css"
- ensure trailing script is inside body, not after it
- add missing alt to images
- mark cosmetic svg images with aria-hidden=true, also gave them titles though that's redundant in these cases, but for future copy/pasting...
- remove css units on 0 dimensions (0 vs 0px)
- replace obsolete `tt` element with `samp` element
- add missing DOCTYPE html
- add missing charset="utf-8"
- fix color contrast on text
- replace obsolete align="center" with css
=> cleanup static HTML for accessibility, valid HTML

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
- when starting IDE with multiple documents already loaded in editor, those editors are created before they are attached to the DOM, so it is necessary to assign element IDs in onAttach so they can be de-dup'd
- including Kevin as FYI reviewer since he added this ID recently
=> Prevent duplicate element IDs when multiple source files are open

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/widget/CaptionWithHelp.java, src/gwt/src/org/rstudio/core/client/widget/WidgetListBox.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdTemplateChooser.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.java
The listbox on the left (which should probably be marked-up as a tab control instead of a listbox, but not going to mess with that now) didn't have a label, so added one via `aria-label`.
The templates listbox was associated with a label via `for=` on the label, but that pattern isn't supported for listboxes, so have to give the label itself an element ID, and reference it from the listbox via aria-labelledby.
Also, when switching via the listbox on the left, focus was being placed back in the area on the right, making it very painful to switch via keyboard, so stop doing that.
=> associate labels with listbox controls in New RMarkdown dialog

src/cpp/r/RCntxt.cpp, src/cpp/r/RCntxtUtils.cpp, src/cpp/r/include/r/RCntxtUtils.hpp, src/cpp/r/include/r/RInterface.hpp
This change fixes a crash that occurs every time RStudio's debugger is used in R 4.0. The R team introduced a new item in the middle of the context stack data structure, so our memory offsets are wrong. 
The fix is pretty simple, and we've had to do this several times before: we now detect R 4.0 and use an updated version of the RCNTXT structure if it's present. 
Fixes https://github.com/rstudio/rstudio/issues/5888. Candidate for 1.2-patch backport.
=> Update RCNTXT copy for R 4.0

NEWS.md, src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/prefs/UserPrefValues.cpp, src/cpp/session/resources/schema/user-prefs-schema.json, src/gwt/src/org/rstudio/studio/client/application/DesktopHooks.java, src/gwt/src/org/rstudio/studio/client/workbench/WorkbenchContext.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
Fixes #1817
Added desktop-only option to General / Advanced / OS Integration / "Show full path to project in window title". Off by default, which more closely matches behavior of RStudio Server
On Windows, and some Linux desktops, makes the taskbar labels more useful when working with projects, e.g.:
=> option to show only project name instead of full path in desktop window title

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/widget/FormLabel.java, src/gwt/src/org/rstudio/core/client/widget/TextBoxWithCue.java, src/gwt/src/org/rstudio/studio/client/common/rpubs/ui/RPubsUploadDialog.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectAccountList.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.ui.xml, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectLocalAccount.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectLocalAccount.ui.xml
Associate labels with custom listbox controls, mark images as cosmetic, and make the "Create New" hyperlink keyboard accessible.
The list of files in the left column of RSConnect publishing (when publishing all files in a directory) is not keyboard / screen-reader accessible, I opened #5951 to track that.
UI examples:
=> Fix basic accessibility issues with RSConnect / RPubs dialogs / wizards

src/gwt/src/org/rstudio/core/client/widget/FormTextArea.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectCloudAccount.ui.xml
Labelled text area with "ShinyApps Token and Secret" which will be read as description of this text area by screen readers (and avoid an accessibility violation from automated tests).
=> add aria-label to textarea in ShinyApps.Io connection dialog

src/gwt/src/org/rstudio/core/client/widget/LeftRightToggleButton.css, src/gwt/src/org/rstudio/core/client/widget/LeftRightToggleButton.java, src/gwt/src/org/rstudio/core/client/widget/LeftRightToggleButton.ui.xml
Fixes #5899 
Made keyboard and screen reader accessible by using actual `<button>` elements (thus obtaining keyboard and focus handling for free), and use the aria-pressed attribute to let screen readers know which button is pressed. Tested on IE11, FireFox, Chrome, Safari.
FYI to @melissa-barca  since we discussed this before the break.
I originally thought I would make behave like a tab control, but that would require reworking the fundamental way this control is used. Every visible instance of this control is actually two separate concrete instances, one set to having left button pressed, one with right button pressed. Clicking on one hides that instance and shows the other. Making this a fully functioning tab control (especially the keyboard behavior) would be difficult. Fact it is …
=> Make LeftRightToggleButton accessible using html buttons and aria-pressed

src/cpp/session/resources/dependencies/r-packages.json
This change updates the version of the rsconnect package to the newest one on CRAN. 
Closes https://github.com/rstudio/rstudio/issues/5839.
=> Update rsconnect dependency to 0.8.16

src/cpp/session/SessionModuleContext.cpp, src/cpp/session/include/session/SessionModuleContext.hpp, src/cpp/session/modules/SessionFilesListingMonitor.cpp, src/cpp/session/projects/SessionProjectContext.cpp, src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/ExistingDirectoryPage.java
This change fixes an issue in which R sessions can hang around eating CPU for unreasonably long after they should have been terminated. 
The problem is that when the R session is bound to a giant, unindexed directory (which occurs if you e.g. try to create a project from your home directory), the file indexing threads can keep running for a long time. These threads try to retrieve preferences related to object file hiding, which results in exceptions once the main thread is unwound and the preferences don't exist any more. These exceptions then trigger expensive exception handling and logging code which further slows the termination process. 
The fix is to pass the pref values in using functional value binding (once) instead of hitting the pref for every single file test, which is more …
=> Fix excessive CPU usage in pathological R session closure

src/cpp/desktop/DesktopMain.cpp
This change makes it possible to discover RStudio Desktop's version at the command line with `rstudio --version`. 
Closes https://github.com/rstudio/rstudio/issues/3922.
=> Implement version check with --version

src/cpp/session/modules/SessionDependencies.cpp
We've gotten some feedback that it's not clear enough when the package installation job is done running. This change adds a message when the job is done to make it easier to notice. 
See also: https://github.com/rstudio/rstudio/issues/3960
Closes https://github.com/rstudio/rstudio/issues/5966.
=> Emit message at end of package installation script

src/gwt/src/org/rstudio/studio/client/common/filetypes/CppFileType.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/RFileType.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java, src/gwt/src/org/rstudio/studio/client/common/spelling/domain_specific_words.csv, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetSpelling.java
Previously we were spellchecking String types by default which caused myriad issues particularly in Rmd files. As part of removing that I refactored the token predicate function as well to make more sense.
Fixes #5009
Fixes #5242
Fixes #5393
=> Break out the token specificity in FileType for spellcheck

src/cpp/session/modules/SessionCodeTools.R, src/cpp/tests/testthat/test-pkg-deps.R
This change extends the package dependency scanner for R Markdown documents so that it looks in the YAML header in addition to the R code in the body of the document.
It currently understands three types of dependencies:
- A dependency on an output format supplied by an R package, given as `pkg::output_format`
- An explicit dependency on the `shiny` package via `runtime: shiny` or similar
- An implicit dependency on the `shiny` package via parameterization
Also adds unit tests for this feature. 
Closes https://github.com/rstudio/rstudio/issues/4779.
=> Scan R Markdown YAML header for dependencies

src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/include/session/prefs/UserStateValues.hpp, src/cpp/session/prefs/UserPrefValues.cpp, src/cpp/session/prefs/UserStateValues.cpp, src/cpp/session/resources/schema/user-prefs-schema.json, src/gwt/src/org/rstudio/core/client/widget/BannerWidget.java, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/header/MenubarPanel.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
- the application role preference setting was an experiment, after further discussions with accessibility experts, removing altogether
- don't put alt="RStudio" on the logo in upper-left of the IDE, it's a distraction when using screen readers
- give the logo the banner role; if it has a link (i.e. on server-pro) then it will show up as a landmark
- give the menu and toolbar areas the navigation role
- give the tab panel area the main role, instead of the entire page
- mark a layout table used only when the toolbar is hidden as role=presentation
=> apply banner, nav, and main landmarks to IDE main window, remove application role

src/gwt/src/org/rstudio/core/client/widget/ProgressSpinner.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionCodePanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionExplorer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/common/CompileOutputPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ChangelistTable.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitChangelistTablePresenter.java
- connection code editor not labeled in pane instance, and incorrectly labeled in dialog instance
- tab traps in connection code editor in connection dialog and pane
- contrast too low on "(Not connected)" message in pane
- animation when showing/hiding git infobar wasn't obeying reduced motion setting
- toolbar class used in CompilePDFOutput, RenderRmdOutput, RSConnectDeployOutput, and TestsOutput panes had the same name in all of them ("Compile Output Tab", now it has a name representative of the tab
- using aria-label on the username in toolbar was not valid and not useful in screen readers
- progress spinner canvas control used in "busy" tabs now read as "Busy", so a tab will read "R Markdown Busy Tab" (for example) in screen reader when spinner is showing
=> fix assorted accessibility issues in build output toolbars, connections UI

src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java, src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.css, src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java, src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.ui.xml, src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
Give main and nav landmarks labels so they are more useful in screen readers. Put the warning bar occasionally shown at bottom of the UI in a contentinfo landmark, and fix its close [x] button so it's a real button that can be used via keyboard, not just mouse.
Here's an example of landmarks exposed in the NVDA screen reader. The warning-bar wasn't visible, so it isn't showing here. This list allows screen-reader user to understand big-picture layout of the page, and navigate to those regions.
=> label nav and main landmarks, give warningbar a role and make its close btn accessible

NEWS.md, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Fixes #4892
- avoids a clash with commonly used shortcuts on Windows
- issue reported it on Dell XPS, I was also seeing the same problem on my Lenovo IdeaPad
- tested the next shortcuts on those, macOS Desktop, and Server on Mac and Windows in Chrome
=> change keyboard shortcuts for next/prev terminal to use Shift instead of Ctrl

src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
Workaround for Qt issue described here: #5833 
- on Windows desktop, Qt has a bug preventing screen readers from knowing if a menu item has a checkbox so a blind user can't tell current state of the "Help / Accessibility / Screen Reader Support" menu item
- this is particularly bad because the other way to see this state is in the accessibility preferences pane (via a regular checkbox), but this isn't accessible until screen reader support is on
- append (enabled) or (disabled) to the menu item to provide an additional indication of state
- not making Windows-desktop specific, doesn't do any harm to have this extra information in all cases
- not implementing a generic fix for all checkable menu items, will consider on a case-by-case basis
=> include screen reader state in menu text to workaround Qt bug

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/layout/LogicalWindow.java, src/gwt/src/org/rstudio/core/client/theme/MinimizedModuleTabLayoutPanel.java, src/gwt/src/org/rstudio/core/client/theme/MinimizedWindowFrame.java, src/gwt/src/org/rstudio/core/client/theme/PrimaryWindowFrame.java, src/gwt/src/org/rstudio/core/client/theme/WindowFrame.java, src/gwt/src/org/rstudio/core/client/theme/WindowFrameButton.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
- the controls to the right of tabs for minimizing, maximizing, and restoring each quadrant can now be operated by screen reader and/or keyboard (in addition to mouse, of course), and report distinctive names indicating both which quadrant they are in, and their current state (min/max/restore)
- also gave each a unique, stable elementId
Visual reminder of the controls (none of this is change by this PR, just FYI). Note the different appearance for Console and Source quadrants when minimized (they hide all tabs and just show the name "Console" or "Source"), whereas the other two quadrants ("TabSet1" and "TabSet2") continue showing just the tabs when minimized.
=> make min/max/restore quadrant controls fully accessible

src/gwt/src/org/rstudio/core/client/a11y/A11y.java, src/gwt/src/org/rstudio/core/client/widget/AriaLiveStatusWidget.java, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/application/events/AriaLiveStatusEvent.java, src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteWindow.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocumentOutlineWidget.css, src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocumentOutlineWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceShim.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/ObjectExplorerEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTargetWidget.java
- when document outline is visually hidden also make it invisible to screen readers
- markup document outline splitter as a splitter
- give document outline a label for accessibility tools
- increase contrast of message shown when document outline is empty
- option to read aria-status messages with no delay
- clear prior aria-live status message after 4 seconds (this is to allow a repeated message to be read and so it doesn't show up again when navigating page with screen reader cursor)
- new command "Speak text editor location" (Ctrl+Shift+B) that reads out current row, col, scope, file type and filename via aria-live; command hidden if screen reader support disabled
- annotate the panels for each tab in editor pane with role=tabpanel and a label (had to be done for text editors, data …
=> Accessibility improvements to editor pane

src/gwt/src/org/rstudio/core/client/widget/LatchingToolbarButton.java, src/gwt/src/org/rstudio/studio/client/dataviewer/DataTable.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
- in one use of this control (for showing/hiding document outline), the accessibility text is changed to indicate the state of the button; in that situation it is NOT appropriate to use aria-pressed as the text is sufficient to tell screen readers what is going on
- in the other use, the Filter button in the data viewer, the text does not change, so aria-pressed is required to indicate that this is a toggle button and to indicate what state it is currently in
=> use aria-pressed to make LatchingToolbarButton a toggle button

NEWS.md, src/gwt/src/org/rstudio/core/client/command/KeyboardHelper.java, src/gwt/src/org/rstudio/core/rebind/command/ShortcutsEmitter.java
- Tested with my full Mac keyboard which includes F13 to F19
- Also works with Windows/Linux if you have a keyboard with these keys
- Helpful when using screen readers, where unused keyboard shortcuts are hard to come by
Here's a full Mac keyboard:
- Keys up to F24 are defined, hard to find these days, but they do exist, so why not:
=> support F13 - F24 for custom keyboard shortcuts

src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/CallFramePanel.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectList.java
- image for expandable object, traced object, and current frame of callstack didn't have labels
=> provide alt-text for images in Environment pane

src/gwt/src/org/rstudio/core/client/theme/WindowFrame.java
- provides another way to get to the 4 quadrants of the UI via screen-reader navigation
For example in VoiceOver rotor:
=> mark tabset quadrants as named regions

src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
- don't bother trying to hide "speak" accessibility commands based on state of screen reader enabled flag; the technique I was using to hide them is Server specific (desktop uses a different flag, which requires an async call to the desktop executable to read and isn't worth the complexity)
=> announce when Console is cleared via aria-live

src/gwt/src/org/rstudio/core/client/a11y/A11y.java, src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
- this property causes problems with certain screen reader / browser combinations including Safari / VoiceOver that can prevent the dialog from behing fully announced
- was seeing this happen consistently with Yes/No dialogs, and removing this fixed the problem
- article that discusses this: https://developer.paciellogroup.com/blog/2018/06/the-current-state-of-modal-dialog-accessibility/
=> stop using aria-modal property on modal dialogs

src/gwt/src/org/rstudio/core/client/theme/MinimizedModuleTabLayoutPanel.java, src/gwt/src/org/rstudio/core/client/theme/MinimizedWindowFrame.java
- this provides some visibility to screen readers about what's happening when a quadrant has been minimized, and surfaces the minimized quadrant as a region (e.g. "TabSet1 minimized region")
=> annotate minimized quadrant as a region and as a tabpanel

src/cpp/r/CMakeLists.txt, src/cpp/r/config.h.in, src/cpp/r/session/REmbeddedPosix.cpp
This is the minimal change required to get RStudio building against R 4.0+. In R 4.0, the field `R_Slave` was removed from `structRstart` and replaced with `R_NoEcho`. 
https://github.com/wch/r-source/commit/f1ff49e74593341c74c20de9517f31a22c8bcb04#diff-178cb445c6da1cdb9d55c898b6118256R70
Since RStudio references this field, and we would like to be able to build against both R 4.0 and R 3.x (largely for ease of development and testing), we need to refer to the field by the appropriate name.
The irony of using `--slave` to determine whether we need to use `R_Slave` or `R_NoEcho` is not lost. R 4.0 (currently) only soft-deprecates `--slave`, whereas `R_Slave` has been simply removed.
Related to https://github.com/rstudio/rstudio/issues/5923. We will need to make another (significantly more …
=> Use R_NoSave over R_Slave for R 4.0+

src/cpp/desktop/DesktopWebPage.cpp, src/cpp/session/modules/SessionUserPrefs.cpp, src/cpp/session/prefs/PrefLayer.cpp
This change fixes a problem wherein corrupting the user prefs file causes RStudio to fail to boot. As far as we can tell this can't happen in normal use, but since the prefs now advertise as at least marginally hand-editable we need to be more tolerant to errors.
The problem is that in some failure modes for loading prefs from a file, we wind up with a prefs cache and in others we don't. The fix is to ensure that as a postcondition of loading prefs from a file we always end up with a prefs cache (even if it's a empty as a result of the prefs file failing to load for some reason such as parse errors).
Also includes a drive-by fix for #6027, and another issue I discovered in which the startup diagnostics added in #5509 do not show up in release builds, the fix for which is to always allow …
=> Tolerate invalid user prefs data, with a warning

src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/DiffFrame.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/DiffFrame.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/graph/GraphLine.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/dialog/SVNReviewPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/dialog/SVNReviewPanel.ui.xml
- dynamically generated branch graphic, announce depth of the commit (0-based)
- separator, mark as decorative
- in SVN UI, associate "Context" label with its dropdown control
=> accessibility labels for images used in Git history UI

src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPresenter.java
The tutorial URL currently is presumed to be at the root of the host, which is only true when running dev mode or open source without a proxy. This change makes the URL relative so that it also works for Server Pro or open source behind a non-root URL.
Fixes https://github.com/rstudio/rstudio-pro/issues/1401
=> Fix tutorial home page on Server Pro

src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobItem.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobItem.ui.xml
Fixes #5739 
When you hover over a job's progress bar it will now display the pointer cursor to indicate it can be selected - selection will open the job's output.
=> Enable the job's progress bar to be clicked to open the job output

src/gwt/src/org/rstudio/core/client/widget/ProgressDialog.java
- tested on Safari, Chrome (Mac/Windows), FireFox (Mac/Windows), Edge and IE (Windows), and layout is the same without this browser check so whatever it was working around appears to not be an issue now
- Fixes #4485
=> fix layout of ProgressDialog on Safari

src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
While doing basic accessibility check of ConsoleProgress dialogs (seen in cases such as switching branches in the Git pane, example below), noticed JavaScript exceptions when I tabbed through the dialog.
- prefs_ is passed in as null in ConsoleProgressDialog constructor super()
- the check for tabKeyMovesFocus wasn't checking for this, thus throwing an exception
- if it is null, we assume we want to allow tabbing to escape the AceEditor instead of inserting tabs
=> prevent JavaScript exception when tabbing through ConsoleProgressDialogs

src/gwt/src/org/rstudio/core/client/widget/Toggle.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/ChunkOptionsPopupPanel.java
- also associate labels/controls in the ChunkOptionsPopupPanel
=> enable use of Toggle tri-state checkboxes via keyboard and screen reader

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/widget/ProgressDialog.java, src/gwt/src/org/rstudio/studio/client/common/debugging/ui/ConsoleError.ui.xml, src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionPreInstallOdbcHost.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkConditionBar.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkHtmlPreview.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/NotebookProgressWidget.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressWidget.java
- many of these are images pretending to be buttons, so would require work in the future to implement keyboard support, but at least having names makes them usable via screen reader
- for ProgressDialog and ConsoleProgressWidget, annotate the progressbar as a progressbar, make the log region a log, and announce when the task is completed
=> label assorted images missed on previous passes and annotate ProgressDialog

src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocumentOutlineWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Editor's document outline uses a Tree control, which contains an element with tabindex=0. If document outline is not visible, set that to -1 so normal tabbing doesn't give it focus while hidden.
=> remove document outline from tab sequence when hidden

src/gwt/src/org/rstudio/core/client/BrowseCap.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- on macOS, Safari and Firefox show their own preferences when Cmd+comma is pressed so make the shortcut Cmd+Option+comma when running on those browsers
- Cmd+comma works as desired on Chrome and Edge on Mac, so leave as-is for users who were already using it on Chrome
Fixes #6015
=> use different keyboard shortcut for Global Options on Safari/Firefox

src/gwt/src/org/rstudio/core/client/widget/ProgressDialog.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewProgressDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressDialog.java
- The ProgressDialog abstract class, in `core`, was referencing code in non-core in order to perform aria-live announcements
- Fixed by making that an abstract method that concrete subclasses of ProgressDialog must implement
- Will make some planned future work a bit tidier as well as avoid adding yet-another circular reference between core and studio
=> fix reference to 'studio' from 'core' in ProgressDialog abstract class

src/cpp/session/modules/SessionConfigFile.cpp, src/cpp/session/modules/SessionFind.cpp, src/cpp/session/prefs/PrefLayer.cpp, src/cpp/shared_core/Error.cpp, src/cpp/shared_core/include/shared_core/Error.hpp
JJ reported this bug earlier this week. Because `boost::system::error_code`s can be implicitly converted to `int`, sometimes `Error(int code, std::string name, ErrorLocation location)` was being invoked instead of `Error(boost::system::error_code, std::string message, ErrorLocation location)`, resulting in the name (category) of the error being set to the intended message. This PR resolves that issue by swapping the name and code parameters. It also revealed the need for `Error(boost::system::error_condition)` constructors.
There's also a minor change to SessionFind errors.
=> Fixes a bug where some Error constructors are ambiguous.

src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java, src/gwt/src/org/rstudio/core/client/theme/DocTabSelectionEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
This change fixes an annoying issue with focus while debugging, which is that the cursor jumps into the Source pane a lot more than most people expect. 
The reason this occurs is somewhat involved (see #6039 for details). The short version is that we open tabs to view source code while stepping through instructions, then automatically close those tabs when we are done stepping. The problem is that closing a tab always causes us to open _and then immediately focus_ the adjacent tab -- regardless of where focus was before. 
The fix is to use a custom selection event that carries information about whether we had focus when the tab was closed, and to only restore focus if we had it in the first place. 
Fixes https://github.com/rstudio/rstudio/issues/6039.
=> Avoid stealing focus when closing tabs

src/cpp/session/modules/SessionCodeTools.R, src/cpp/tests/testthat/test-pkg-deps.R
There have been a few reports of the following error with 1.3:
```
Error in yaml.load(string, error.label = error.label, ...) : 
Scanner error: while scanning a simple key at line 2, column 1 could not find expected ':' at line 8, column 1
```
It is fairly clear that this is a regression caused by https://github.com/rstudio/rstudio/pull/5973. The problem is mostly that we look for a YAML header in all kinds of files to see if it has any interesting dependencies. This is normally harmless, but if an R script contains something that _looks_ like a pair of YAML demarcators, an attempt will be made to parse everything inside them as YAML, with predictable results.
The fix is to only do this kind of scan in R Markdown files, and to swallow any errors we do find (as they are both harmless and …
=> Be more resilient to YAML load errors in dependency scan

src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/prefs/UserPrefValues.cpp, src/cpp/session/resources/schema/user-prefs-schema.json, src/gwt/src/org/rstudio/core/client/widget/CheckBoxList.css, src/gwt/src/org/rstudio/core/client/widget/CheckBoxList.java, src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java, src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewProgressDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/ShellPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
Motivation: a new user may want more verbose behavior, but as experience is gained many announcements can become annoying, so providing a way to toggle them off.
- also added new announcement for console output (via role="log") and toggling the Tab Key Always Moves Focus setting
- put the checkboxes in a scrolling region so it remains usable via keyboard as the list grows
- although the checkboxes are in a labelled group ("Announcements") most screen readers only announce when focus goes to first checkbox, so included "Announce" in label of each checkbox for better understandability
=> add user prefs to disable individual aria-live announcements

src/gwt/src/org/rstudio/core/client/widget/InfoBar.java, src/gwt/src/org/rstudio/core/client/widget/InfoBar.ui.xml, src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java, src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java, src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java, src/gwt/src/org/rstudio/studio/client/application/ui/serializationprogress/ApplicationSerializationProgress.java, src/gwt/src/org/rstudio/studio/client/application/ui/serializationprogress/ApplicationSerializationProgressLabel.java
- some existing announcements I forgot about when I added the preferences
- also made InfoBar close "button" into a real button (had previously done the same for WarningBar)
- InfoBars are used in editor (e.g. if file is read-only and you try to save), in Git Pane if you need to push/pull, and so forth
- WarningBar appears at bottom of main window, e.g. for license warnings
- Session State announcements are those toasts at top of window, such as "Backup up R session" when it suspends
=> add user prefs to control warning bar, info bar, and session state announcements

src/gwt/src/org/rstudio/core/client/widget/AriaLiveStatusReporter.java, src/gwt/src/org/rstudio/core/client/widget/AriaLiveStatusWidget.java, src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java, src/gwt/src/org/rstudio/core/client/widget/ModalDialogTracker.java, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/application/ApplicationView.java, src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java, src/gwt/src/org/rstudio/studio/client/application/events/AriaLiveStatusEvent.java, src/gwt/src/org/rstudio/studio/client/application/ui/ApplicationWindow.java, src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteWindow.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewProgressDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java
A user running RStudio Server via screen reader won't know that there is an option to enable full screen reader support, nor how to get to it.
Added a keyboard shortcut to the command <kbd>Ctrl+Shift+/</kbd>, and issue an alert announcement at startup if the setting is off including description of the shortcut. Most things work in RStudio Server even if the setting is off, but over time more behaviors may be gated by this so want to have it enabled for screen reader users.
Also fixed an issue where immediate announcements in main window were being delayed using the debounce delay.
Rest is plumbing to support differentiating between status announcements (polite) and alerts (assertive). The latter should be very rare, not many alerts that are only relevant to screen reader users.
=> emit aria-live alert at startup if screen reader support not enabled (Server only)

src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java, src/gwt/src/org/rstudio/core/client/VirtualConsole.java, src/gwt/src/org/rstudio/studio/client/common/shell/AriaLiveShellWidget.java, src/gwt/src/org/rstudio/studio/client/common/shell/ShellDisplay.java, src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/events/ScreenReaderStateReadyEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/ShellPane.java, src/gwt/test/org/rstudio/core/client/ConsoleOutputWriterTests.java, src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
Goal is to have screen-reader announce new output as it appears in the RStudio Console.
Previous attempt to simply mark the entire console as role="log" did not work as hoped, especially on Chrome where it would re-announce the entire console with each new line of output.
This new approach uses similar pattern to xterm.js. Text output to the console (minus all formatting) is added to a separate aria-live region. This region tracks  number of lines output, and cuts it off at 25 lines (currently a constant, may make into a user-preference) at which point it announces "Too much output to announce in console" and stops updating the live region. Screen-reader users can still navigate the entire output via screen-reader commands, it just won't be announced automatically.
The live-region and …
=> Console output screen-reader announcement implementation

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java
Frees up more space for future preferences, and easier screen-reader/keyboard navigation.
=> move announcements preferences to separate pref pane tab

src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/Toolbar.java
Dropdown toolbar button control used just in these two places. Prior to this didn't support keyboard or screen-reader use; now it does.
=> keyboard and screenreader support for dropdown in slides and help panes

src/gwt/src/org/rstudio/core/client/a11y/A11y.java, src/gwt/src/org/rstudio/core/client/widget/Toolbar.java, src/gwt/src/org/rstudio/core/client/widget/ToolbarMenuButton.java
- Fixes #6106
- Also follow best-practice from Aria guidelines and remove aria-expanded altogether when the menu is closed, instead of setting it to false (otherwise screen readers may read some additional and not-helpful information when buttons get focus)
- Some duplicate code due to two similar implementation of toolbar menu buttons; consolidating this is a future chore
=> ensure menu buttons have correct expanded state after menu closes

NEWS.md, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/Help.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpTab.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/search/HelpSearch.java
- Fixes #5149
- Added "Search R Help" command to Help menu; shows Help pane if not visible and puts focus in the search field; shortcut is Ctrl+Alt+F1 (editable as "Help Search" command)
- Shortcut for previous help page now Alt+Shift+F2 (editable as "Help Back" command)
- Shortcut for next help page now Alt+Shift+F3 (editable as "Help Forward" command)
- Using next/prev shortcuts while Help pane is not visible will make it visible
- Added missing menu accelerator and trailing "..." to Manage License command (Desktop Pro)
=> add keyboard shortcuts for next/previous help page, and for searching R Help

src/gwt/src/org/rstudio/core/client/AnsiCode.java, src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
Fixes #6092 
The ANSI reset was ignored for color 255 (foreground or background) due to range-check bug.
=> fix resetting of ANSI console color 255 (foreground or background)

src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/SpellingPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetSpelling.java
Reported in issue #6041 there are some dictionaries that Typo.js has severe issues loading. In fact, due to the size of these dictionaries in memory for most tested spellchecking libraries (6GB for Lithuanian in a tested Python package), some serious problem solving will have to go into this issue at some point.
The discussed stopgap to implement was to add a blacklist for the known incompatible dictionaries and not allow them to be loaded for real time spellchecking. Due to how preferences are saved and handled there was a fair amount of funny business making sure that [hopefully] all weird edge cases would be caught to prevent the user from getting into a bad state.
On the plus side I found and fixed a bug with turning real time spellchecking off and then on again.
=> Blacklist for Typo.js unsupported dictionaries

src/gwt/src/org/rstudio/core/client/widget/ShortcutInfoPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/www/docs/keyboard.htm
I broke this when I added <kbd>Ctrl+Shift+B</kbd> as shortcut for reading editor info via screen reader; I checked for that shortcut existing as <kbd>Ctrl+Shift+B</kbd> but I didn't look for <kbd>Cmd+Shift+B</kbd> (which ends up being the same thing on Windows).
Changed the accessibility shortcut to <kbd>Ctrl+Alt+Shift+B</kbd>. Also changed "toggleScreenReader" to <kbd>Ctrl+Alt+Shift+/</kbd> for consistency.
Added a group for accessibility shortcuts and put them on the shortcuts reference popup.
Noticed and fixed incorrect shortcuts for terminal next/prev in the static keyboard.htm page, and logged an issue #6117 to work on making that page be automatically generated (or at least update it manually) for 1.3.
Fixes #6115
=> fix broken "build" keyboard shortcut

src/gwt/www/docs/keyboard.htm
This static, manually edited page (see #6117) is not very accessible to screen readers. Plan is to expose this page to screen reader users via #6118. Mostly mechanical and lots of search and replace. Still need to check for changes to shortcuts in 1.3, will do that separately.
Sorry, didn't notice editor had reindented the HTML until I had done all the work. Makes very difficult to review, but I have tested the resulting page with all browsers we care about, validated the HTML (strictly compliant), and re-ran accessibility tests (100% passing).
Details:
- use separate tables (with headings) for each section, instead of one table with headings inside the table
- allows screen readers to see individually named tables
- properly associate headings with columns so screen readers can announce …
=> Improve screen reader accessibility of "All Keyboard Shortcuts" page

src/gwt/src/org/rstudio/core/client/command/ShortcutViewer.java, src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
- Fixes #6118
- Also emit an announcement if user brings up the Vim help pane (:help in editor) warning it isn't screen reader accessible (see #6123)
- Noticed that keyboard shortcut read to help enable screen reader was hardcoded and already wrong (I changed it yesterday) so get the actual shortcut at runtime
- Not impossible to make the ShortcutViewer panel accessible, but not trivial, either; needs to do the things a modal dialog does (make rest of UI inert, provide a way to close with keyboard and mouse that isn't simply "click anywhere, type anything", then ensure the content of the panel is reasonably accessible)
=> Show accessible keyboard shortcut help when screenreader enabled

src/gwt/www/docs/keyboard.htm
Going to push this in without review as it's just WIP on static content, but for the record:
- Use actual Mac keyboard characters (instead of entities) in the htm (search and replace).
- Put Mac shortcuts in the standard order (Ctrl+Opt+Shift+Foo)
- Added accessibility shortcuts
- Added a few other shortcuts
=> tweaks to keyboard shortcuts page

src/cpp/session/resources/schema/user-prefs-schema.json
At rstudio::conf 2020, two people individually asked me if we would add a feature that would make the Previous/Next source tab gestures wrap around instead of stopping at the end. This is also a common request here on Github (e.g. https://github.com/rstudio/rstudio/issues/5539).
Of course, we already have this feature, and have for years, but you need to turn it on via an option, and even though that option is on the first page of Global Options it's difficult for people to find. 
This change turns it on by default since empirically most people appear to consider it the most useful behavior.
=> Wrap around editor tabs by default

src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobProgress.ui.xml
- Use the normal text color instead of a hardcoded color
- Fixes #6144 (just the main issue, didn't address the mentioned inefficient space usage in the status bar; that can be opened as a separate issue if desired)
=> fix color of job status in dark mode

src/cpp/session/modules/SessionTutorial.cpp, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPresenter.java
This PR fixes two issues:
1. The tutorial index was not being refreshed after indexing was completed; this is because of the path check here:
https://github.com/rstudio/rstudio/blob/9679854e04ab6b1358e4798250d535ef82b9f9e3/src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPresenter.java#L171
2. Always run the default tutorial on startup -- at least to make testing easier for now.
=> fix for refresh when indexing complete; always run default tutorial on startup

src/cpp/session/modules/SessionGit.cpp, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/CommitListTable.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/DiffFrame.java
Git SHAs were being truncated session-side, which is undesirable in locations where we might want to display the full hash. Avoid truncating on the session side and instead truncate client-side if appropriate.
Closes #6155.
=> display full SHA in git history

src/cpp/desktop/DesktopWebView.cpp, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
As these commands will interfere with attempts to cut / copy / paste in things that happen outside of the GWT context (e.g. in desktop-generated dialogs).
Closes #5894, #5936.
=> don't bind cut / copy / paste commands on desktop

src/cpp/session/modules/SessionFind.cpp, src/cpp/shared_core/FilePath.cpp, src/cpp/shared_core/include/shared_core/FilePath.hpp
Fixes #6048 
Global replace functionality works by copying the contents of the initial file to a temporary file while replacing every occurrence of the specified value - it then overrides the original file with the new file by performing a `move`. This caused the replace to work even when RStudio didn't have write permissions for that file. 
This PR tests if the original file can be written to before starting the replace process and immediately before performing the move. This will prevent the process from going forward with replace logic when it fails on the first check, and ensure the permissions were not changed by an outside process immediately before the `move`. 
This PR also fixes a, possibly impossible with the current UI, bug that was discovered while writing R unit tests where …
=> Check for write permissions before performing a global replace

src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
Fixes #6085 
This PR fixes an issue where the find result count was being cleared on initialization of the Find In Files dialog, causing this information to be lost from the state when a new rsession started. 
It also prevents any calls to clear the result count from causing an exception when the result count is null.
=> Exception in Find in Files dialog

src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/core/client/a11y/A11y.java, src/gwt/src/org/rstudio/core/client/widget/ModalDialogTracker.java, src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteWindow.java
- When modal dialog is shown, make the main window hidden to screen readers via aria-hidden (the inert polyfill we use doesn't do this automatically; other polyfills do, but don't want to switch at this stage)
- Also support making satellite windows inert by giving root panel an ID to use for searching
- When modal dialogs are stacked and unstacked, make covered dialog inert otherwise it is reachable via tab key (from outside browser) and screen readers
- Fixes #6075
=> fix issues with modal dialogs and screen readers

src/cpp/r/R/Api.R, src/cpp/session/modules/RStudioAPI.cpp
Makes it possible to get the identity (and system username) for the current user. 
Part of a fix for https://github.com/rstudio/rstudioapi/issues/166.
=> Add API functions for getting user identity

src/cpp/session/CMakeLists.txt, src/cpp/session/SessionMain.cpp, src/cpp/session/modules/SessionCRANMirrors.cpp, src/cpp/session/modules/SessionCRANMirrors.hpp, src/cpp/session/modules/SessionPackages.cpp
This change addresses an issue in which changing the CRAN mirror in Preferences is not reflected immediately in the R session. 
The fix is to listen for changes to the CRAN mirror preference, and to change the R option to reflect it. (If you're wondering how this ever worked, it was a lint item lost in the preference overhaul -- so an artifact of moving to the new system). 
The change is much smaller than it looks; while I was in the code I took the opportunity to move the CRAN-related bits from SessionPackages into a smaller module. The only new code is in `onUserSettingsChanged`. 
Fixes https://github.com/rstudio/rstudio/issues/6137.
=> Set CRAN mirrors option to reflect user prefs

src/cpp/session/modules/SessionDataViewer.R
This change fixes an issue in which columns named `x` were sometimes incorrectly relabeled (when the column was part of an object that was not a data frame but had to be coerced to one for viewing). 
The faulting code is supposed to restore incorrectly labeled columns but has not worked correctly for some time; in commit https://github.com/rstudio/rstudio/commit/a58944bf2ddd0a190d6ad1e3237c79e333c46299 we gave the name `coerced` to the object instead of `x`, but continued to look for `x` when relabeling. 
The fix is to (a) use a random name for the object we coerce, and (b) fix the column relabeling so it finds the random object name (which is now vanishingly unlikely to appear as a real column name). 
Fixes https://github.com/rstudio/rstudio/issues/3304.
=> Use random column name for relabeling in data viewer

src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/prefs/UserPrefValues.cpp, src/cpp/session/resources/schema/user-prefs-schema.json, src/gwt/src/org/rstudio/core/client/widget/NumericValueWidget.java, src/gwt/src/org/rstudio/studio/client/common/shell/AriaLiveShellWidget.java, src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectEditingPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java
- Remove hardcoded limit of 25 lines and let user configure via Accessibility Preferences
- Tweaked NumericValueWidget to track its own label to use in validation messages instead of callers having to pass it in twice
=> user preference to control console output announcement limit

src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java, src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/ShellPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressWidget.java
Wasn't announcing the echoed prompt/command. For example, this:
> cat("Hello")
Hello
was being announced as "Hello".
Now it is announced as "> cat("Hello")  Hello", with an option to go back to the previous behavior (not announce the prompt/command). I can imagine some users preferring one model over the other.
=> optionally announce echoed prompt and command in console

src/cpp/session/SessionMain.cpp, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/include/session/SessionModuleContext.hpp, src/cpp/session/modules/SessionReticulate.R, src/cpp/session/modules/SessionReticulate.cpp
When Python is initialized, it injects its own console control handler:
https://github.com/python/cpython/blob/5807efd4c396d5718325e21f5a14e324a77ff77c/PC/launcher.c#L787-L789
https://github.com/python/cpython/blob/5807efd4c396d5718325e21f5a14e324a77ff77c/PC/launcher.c#L730-L734
On Windows, processes have a stack of console control handlers. When a console control event is generated (e.g. by `Ctrl + C`), Windows will execute each in turn until one returns `TRUE`. Because Python is initialized lazily, this handler goes on top of the stack, and then effectively swallows any console control event before we get to see it with our own handler.
The solution is to re-initialize RStudio's console control handler after Python has been initialized, effectively placing it back on top of the stack. …
=> re-initialize Ctrl + C handler after Python initialized

src/cpp/session/SessionConsoleProcess.cpp
MacOS Catalina users who still use the old bash bundled with macOS will no longer see the warning suggesting switching to zsh when they start a terminal.
- Fixes #6182
=> suppress macOS Catalina warning about old system bash

src/gwt/src/org/rstudio/core/client/command/BaseMenuBar.java, src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenu.java
In RStudio Server, keyboard shortcuts are usable when main menu drop-downs are active, but the menu was staying open even though keyboard focus has potentially gone elsewhere (e.g. Ctrl+2).
Same was true in both server and desktop with dropdown menus on toolbar buttons.
Fix by closing if a command was fired via keyboard shortcut. Also removed some more cases of spaces before semicolons (source formatting).
- Fixes #6080
=> close main menu (server) and toolbar menus when keyboard shortcut used

NEWS.md, src/cpp/core/terminal/PrivateCommand.cpp, src/cpp/r/R/Api.R, src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/include/session/SessionTerminalShell.hpp, src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/modules/SessionTerminalShell.cpp, src/cpp/session/modules/SessionTerminalShellTests.cpp, src/cpp/session/resources/schema/user-prefs-schema.json, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalShellInfo.java
- new Zsh option in terminal shell dropdown, but only if zsh found in /etc/shells
- fixes core of #5587 (but decided not to select zsh by default even on Catalina; maybe in a future release)
- one quirk of Zsh, it doesn't use the HISTCONTROL setting we rely on in bash to keep "hidden" commands used to capture environment variables from showing up in history, it uses a shell option, which we set via -g; we don't try to detect if this has been unset so if a user has a configuration that unsets this they will see weird commands in history unless they turn off Capture Environment Variables
=> add Zsh as a supported terminal on Mac, Linux, and Server

src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java
Fixes #6194 
`Search these files` was being set to `All Files` whenever the directory being searched was not a package directory. This PR fixes this issue so it only gets reset to `All Files` when the package option is selected and the directory is not a package directory.
=> Bug fix for 'Search these files' resetting to 'All Files'

src/cpp/r/R/Api.R, src/cpp/session/modules/RStudioAPI.cpp
This small change fixes two small issues with the nascent user identity APIs:
1. It corrects the method name for system username to `systemUsername` (which is what rstudioapi calls)
2. It checks the environment variable `RSTUDIO_USER_IDENTITY_DISPLAY` for user identity on RStudio Server Pro (see https://github.com/rstudio/rstudio-pro/pull/1431)
=> Check env var for RStudio Server Pro user identity

CMakeGlobals.txt, dependencies/common/install-packages, dependencies/common/install-packages.cmd, src/cpp/session/resources/dependencies/r-packages.json
rstudioapi 0.11 is now on CRAN; it is no longer necessary for us to embed rstudioapi.
=> stop embedding rstudioapi

dependencies/common/install-qt.sh, dependencies/linux/install-qt-linux, docker/jenkins/Dockerfile.bionic-amd64, docker/jenkins/Dockerfile.centos7-x86_64, docker/jenkins/Dockerfile.centos8-x86_64, docker/jenkins/Dockerfile.debian9-x86_64, docker/jenkins/Dockerfile.opensuse15-x86_64, docker/jenkins/Dockerfile.xenial-amd64
This is due to Qt's recent change to require entering Qt account credentials in the online and offline installers, breaking our ability to rebuild docker images for the build machines.
Uses `install-qt-sh` script as-is from Qt: https://code.qt.io/cgit/qbs/qbs.git/tree/scripts/install-qt.sh which can install minimal SDK bits needed for building, without going through the installer (and also avoids need to install Qt Creator, documentation, etc.). Much faster.
This script is driven by `install-qt-linux` script which selects which version of Qt, which components, and where to extract them. The extraction is done via 7z so needed to ensure that was installed in the images.
Our Windows build is still ok; it downloads and extracts an archive (making the installer-scripting robust had previously …
=> Install Qt via shell script in Linux Docker containers

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/findreplace/FindReplaceBar.java
Fixes #6216 
- remove setting tab indexes > 0 on controls (this should never be done)
- don't set buttons to tab index -1; they are now able to show keyboard focus, not all of them have equivalent keyboard shortcuts, and those shortcuts are not discoverable to a keyboard/screen reader user without letting focus get to the buttons
- add tooltip to replace-all button to disambiguate the generic "All" button label
=> Fix editor find / replace bar keyboard tab sequence

src/cpp/session/modules/SessionCodeTools.R, src/cpp/session/modules/SessionTutorial.R
This PR installs any required R packages before running the tutorial.
UI example:
Packages are installed with a regular `install.packages()`, which implies hooks on `install.packages()` (e.g. from `renv`) are used as appropriate. Installation happens in the main R session as we need to block the process from proceeding until all packages have been installed.
Closes https://github.com/rstudio/rstudio/issues/6206.
=> install tutorial dependencies before run

src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
=> allow Tab key to move focus normally in Help pane secondary toolbar

src/cpp/session/modules/SessionTutorial.cpp
Closes https://github.com/rstudio/rstudio-pro/issues/1401; and also ensures that tutorials will run properly in any context where RStudio Server is served behind a proxy.
=> use relative tutorial run URI in link

src/cpp/session/modules/SessionFind.cpp
This PR fixes two bugs that caused global replace to not work on Windows and a bug that prevented the correct error message from being displayed when this happened. 
I updated the call to `completeFileReplace` to include an `errorMessage` set so it not only returns the system error, but also the errors we are using to send to the backend to be displayed in the Find in Files tab. With this the Windows error was properly displayed. The second issue is that the `testWritePermissions` function always failed on Windows after we opened `inputStream_` (even though it's only used for reading) - to prevent this from happening I only call this function for the second time on non-Windows systems.
=> Fix global replace on Windows

src/gwt/src/org/rstudio/studio/client/common/repos/SecondaryReposDialog.java, src/gwt/src/org/rstudio/studio/client/common/rstudioapi/DialogHtmlSanitizer.java, src/gwt/src/org/rstudio/studio/client/workbench/codesearch/CodeSearchOracle.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/diff/UnifiedParser.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitStatusRenderer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNStatusRenderer.java
JavaScript exception related to charAt; don't know exact repro, taking opportunity to fix that call stack and defensively change a few other instances of charAt to use safer StringUtil.charAt.
For more context:
* fix exceptions caused by gwt 2.8.2 checking charAt bounds #4451
* more fixes for new behavior of String.charAt in GWT 2.8.2 #4489
* fix exception when typing Shift+Tab on whitespace-only editor line #5036
* javascript exceptions being thrown by charAt in cpp completion code #5052
Callstack:
```
15 Feb 2020 00:03:26 [rserver] ERROR CLIENT EXCEPTION (rsession-gary): Index: -1, Size: 226;
rstudio-0.js@10#639::Throwable.createError
rstudio-0.js@48#703::Throwable.initializeBackingError
rstudio-0.js@8#535::Throwable.Throwable
rstudio-0.js@18#808::Exception.Exception …
```
=> Replace more instances of String.CharAt with StringUtil.CharAt

src/cpp/session/modules/SessionFiles.cpp
This one was caught by the `_GLIBCXX_ASSERTIONS` flag on Fedora.
=> fix STL access undefined behaviour

src/cpp/shared_core/include/shared_core/system/SyslogDestination.hpp, src/cpp/shared_core/system/SyslogDestination.cpp
When the program ID passed to the SyslogDestination constructor had a lifetime which was shorter than the lifetime of the SyslogDestination itself, log messages would be written to syslog with nonsensical program IDs. This PR ensures that the program ID string will exist as long as the SyslogDestination exists.
=> Persist Program ID in Syslog

src/cpp/session/modules/SessionFind.cpp, src/cpp/session/modules/SessionFindTests.cpp
Fixes #6240 
Previously the regex used to parse `git grep` results for Find in Files included a wildcard to handle a pattern that included a colon. When the resulting line contained a colon, the regex was unable to properly parse the line and would crash RStudio. This PR makes this regex more specific so it can process lines with colons and adds a unit test for this process. It has been tested with a variety of Find in Files searches.
=> Fix issues with find in files and colons

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/LineWidgetManager.java
On some occasions, RStudio will attempt to add the same line widget twice in quick succession. This is not handled well by Ace, and can place the editor into an infinite Javascript loop when Ace attempts to re-render line widgets in the document.
For pinned line widgets, there are two places where we add line widgets:
https://github.com/rstudio/rstudio/blob/dcc58c299d097ca419068723d9f67e3f56dacf50/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/PinnedLineWidget.java#L137
https://github.com/rstudio/rstudio/blob/dcc58c299d097ca419068723d9f67e3f56dacf50/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/PinnedLineWidget.java#L217
If the Ace render were to finish immediately after our call to `syncEndAnchor()`, we could end up adding the same …
=> avoid attempt to add same line widget twice

NEWS.md, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/SessionOptions.cpp, src/cpp/session/include/session/SessionOptions.hpp
This feature was previously always on; it is now on only optionally (for hardening) -- see linked Pro issue for rationale. 
Fixes https://github.com/rstudio/rstudio-pro/issues/1455.
=> Add toggle for enabling/disabling directory view restrictions

src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java, src/gwt/src/org/rstudio/studio/client/common/spelling/ui/SpellingCustomDictionariesWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/SpellingPreferencesPane.java
Fixes #6045 
The list of custom dictionaries comes from the server and is set in the context. It's not dynamically updated after adding/removing a dictionary so force a restart when doing this. This is actually ok because it perfectly dovetails into the next issue (which requires a restart anyway).
Fixes #6047 
We were not using custom dictionaries. I was very confident that I had this working at some point but looking at the code it's possible it never actually worked and I was only testing that I preserved the functionality of the old spellcheck while implementing the new feature. Was a little worried when I caught this but implementing it turned out to be easier than I expected due to the nice loading infrastructure that Kevin helped with (and I jerry rigged a touch here). …
=> Spellcheck custom preferences fixes

src/cpp/session/modules/SessionFind.cpp, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml
After some user testing, we determined it makes more sense to separate the `Search in: Package Source` option into two options: `Package Source (/R, /src)` and `Package Tests (/tests)`.
This PR also updates the `git grep` command to override any global git configurations the user may have set up on their computer. This could've led to rstudio mis-parsing output received from the command. 
It also removes `.Rd` from the `Search in: R Common Source Files` option based on feedback that the majority of users have these files autogenerated.
=> Update Find in Files Package option

src/cpp/session/modules/SessionPackages.R, src/cpp/session/modules/SessionTutorial.cpp, src/cpp/session/resources/dependencies/r-packages.json, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackagesServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.css, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.java
This PR provides a small, clickable link / button for installing `learnr` from the main landing page when we detect it is not yet installed.
This makes it easy for users to immediately get started with the Tutorial pane. After clicking the button, `learnr` will be installed, and then the Tutorial pane will automatically refresh and show the newly-installed tutorials.
@gtritchie, let me know if this is an acceptable implementation of a "link that behaves like a button". I took a different approach than what's done in HyperlinkLabel. The element itself is an anchor element, but has its ARIA role set as a button and has the requisite handlers for Space + Enter so that it responds like a normal button would. (Re-using the anchor element just means we get consistent styling with other anchors; …
=> provide "Install learnr" link in Tutorial pane

src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml
Fixes #6255 
When running RStudio Server, the browser takes care of making sure disabled elements appear disabled as well as being disabled. In Desktop mode, the disabled Find in Files include/exclude options looked the same as the enabled options. This PR adds CSS code to make disabled options obviously disabled.
=> Update Find in Files CSS so disabled elements will be obvious is desktop mode

src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
The UI animations are not useful or necessary to a screen-reader user and may confuse screen reader software, so enable the "reduce motion" setting automatically when screen-reader is enabled, and turn it off when screen reader is disabled.
Potentially annoying to a user who frequently switches between screen-reader on / off and prefers no animations in both cases; they will have to manually turn animations back off after disabling screen reader. But fancier handling of this (expected to be) very rare case specially seems like overkill.
=> When screen reader support enabled, reduce UI animations

src/cpp/r/R/Diagnostics.R, src/cpp/session/SessionModuleContext.cpp
This PR revamps the diagnostics script used by RStudio, and now also writes:
- The library paths,
- Loaded packages (and from where they were loaded),
- Installed packages,
- Any site / user profiles / environs,
- The R session temporary directory path + contents,
- A bit more extra information about the system / platform (as reported by R).
Would be nice to take this for v1.3 so we have some extra debugging tools at our disposal with the release, but understand if we should instead target for v1.4.
=> revamp RStudio diagnostics script

package/linux/CMakeLists.txt
On SuSE based systems, the package that supplies `libxkbcommon-11` (needed by Qt on desktop Linux releases) is named `libxkbcommon-11-0`. RStudio will run if this dependency is installed, but it has the wrong package name in `Requires`, so it will complain about an unmet dependency even if the binaries are where they need to be. 
See https://forums.opensuse.org/showthread.php/538588-Naming-of-packages-libxkbcommon-x11 for details.
Fixes https://github.com/rstudio/rstudio/issues/5554.
=> Supply correct name of libxkbcommon-11 on SuSE

src/cpp/session/modules/SessionDependencies.cpp, src/cpp/session/modules/jobs/AsyncRJobManager.cpp, src/cpp/session/modules/jobs/AsyncRJobManager.hpp, src/cpp/session/modules/jobs/ScriptJob.cpp, src/cpp/session/modules/jobs/ScriptJob.hpp
This change causes the Packages pane to reload its state after we're done installing dependencies in a background job, so that the newly installed packages can be clearly shown.
Fixes https://github.com/rstudio/rstudio/issues/6274.
=> Reload packages pane state after installing dependencies

src/gwt/www/unsupported_browser.htm
This change adds Edge to the baked-in list of supported browsers. Edge uses Chromium (Chrome's browser engine) and also pretends to be Chrome in its user-agent string, so RStudio thinks it's a compatible version of Chrome. Which -- thankfully -- it is, for all intents and purposes.
Here's Edge's UA string on MacOS:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.116 Safari/537.36 Edg/80.0.361.57
(Favorite part: deliberate misspelling of `Edge` as `Edg`, probably to avoid UA detection of the old rendering engine)
Closes https://github.com/rstudio/rstudio/issues/6146.
=> Add Edge to supported browser list

src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/ShellPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressWidget.java
- The console output element shows up as a region landmark named "Console Output"
- Fixes #6292
=> annotate console output element for easier screen-reader access

src/cpp/session/modules/SessionTutorial.cpp, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.css
- Wrap `[No description available]` text in `<p>` tag so that it gets correct margins
- Use flexbox to improve wrapping behavior at smaller widths
Before:
After:
=> tweak tutorial pane styles

src/cpp/session/modules/SessionTutorial.R
Not all user-defined tutorials will set a title or description, even though (in theory) they should. This PR guards against the case where these fields are missing.
Closes #6322.
=> explicitly coerce NULL to empty string

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/r/SignatureToolTipManager.java
Closes #5405. We were checking the preference for explicitly-completed function names, but not implicitly-completed functions -- e.g. where you manually type `rnorm(` or similar.
=> check user preference when displaying tooltip

src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/prefs/UserPrefValues.cpp, src/cpp/session/resources/schema/user-prefs-schema.json, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteApplication.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/HTMLPreviewApplication.java, src/gwt/src/org/rstudio/studio/client/plumber/PlumberAPISatellite.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/RmdOutputSatellite.java, src/gwt/src/org/rstudio/studio/client/shiny/ShinyApplicationSatellite.java, src/gwt/src/org/rstudio/studio/client/vcs/VCSApplication.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceSatellite.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkSatellite.java
- I had removed this a while back, thinking it was unnecessary, but a screen-reader user who is helping test out 1.3 requested I put it back
- Changed default to false (off)
- When this role is assigned, there will be Axe violations due to some landmark roles being nested inside it
- Also assigned the role on satellite windows, which I had originally missed
- Overall purpose of this is to potentially change some default behavior of certain screen readers on Windows (whether they are in forms/focus mode or regular browsing mode)
=> put back option to set global application role (a11y)

src/gwt/src/org/rstudio/studio/client/RStudio.java
The A11y.setVisuallyHidden call relies on a ThemeStyles style that isn't injected until later in the boot sequence. Apply the same styles directly in code, instead.
This is an experiment (but a valid change on its own) related to #6201.
=> apply visually hidden style in code during boot screen

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/spelling/CheckSpelling.java
Fixes #6298 
This was something I added to give the manual spellchecking a little extra visual clarity but it's currently unreliable and not necessary so I'm removing it.
=> Remove DocDisplay debug highlighting from manual spellcheck

src/cpp/shared_core/FilePathTests.cpp
Ensures we aren't gutting the filepath on copy and that we can handle empty file paths correctly.
=> Add FilePath unit tests for possible crash coniditions

src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdOutputPresenter.java, src/gwt/src/org/rstudio/studio/client/shiny/ShinyApplicationPresenter.java, src/gwt/src/org/rstudio/studio/client/shiny/ShinyDisconnectNotifier.java, src/gwt/src/org/rstudio/studio/client/shiny/ui/ShinyApplicationPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPresenter.java
It looks like this was broken by some of the work I was doing on tutorials. Quick summary of changes:
- Fix typos in refactoring of Shiny disconnect message handler
- Avoid using window methods as they're likely to fail due to CORS restrictions
- Avoid checking window name when handling event (checking URL is sufficient)
=> fixes around handling of Shiny interrupts

src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java, src/gwt/src/org/rstudio/studio/client/common/shell/ShellDisplay.java, src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java, src/gwt/www/docs/keyboard.htm
- Intended for screen-reader users as a way to quickly get screen-reader onto the console output
- Goes to the last chunk of output, which is usually the last entered command all its output (if console has been reloaded e.g. by closing and reopening the browser then all previous output is in a single chunk)
- Group focus-related accessibility commands into a Help / Accessibility / Focus submenu; there will be more commands here in the future (e.g. 1.4)
- marks the console output region as having document role which hints to screen readers that they could use browse mode instead of focus mode
=> new command for putting focus on the last chunk of console output

package/osx/entitlements.plist
Closes https://github.com/rstudio/rstudio/issues/4579. Looks like some of these must've been newly added in Catalina.
=> add required entitlements for camera + microphone access

src/gwt/src/org/rstudio/studio/client/application/ui/RequestLogDetail.java
Since we disallow user selection in the `<body>` by default, we need to explicitly add it here.
=> allow user select in request log details

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/Help.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpTab.java
- Fixes #6013
- Article is a stub at the moment but will be written in next few days
=> add links to accessibility support article in options and menu

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/www/docs/keyboard.htm
- I was using the same shortcuts on all platforms, based on what Google Docs uses on Mac
- These were less appropriate on Windows due to increased likelihood of clashes, so switched to be Alt+Shift based instead of Ctrl+Alt based (i.e. same as Google Docs main menu shortcuts)
- Fixes #6353
=> use main menu shortcuts more in line with Google Docs on Windows

src/cpp/session/modules/SessionSource.cpp
This change fixes a problem that occurs when creating a new source document *could* use a template, but no template is installed. We currently show an error in this case; the correct behavior is to just create an empty document.
Fixes https://github.com/rstudio/rstudio/issues/6351.
=> Use an empty source template if none found

src/cpp/session/resources/grid/dtviewer.js
We currently render data viewer cells as inline elements (`<span>`). This prevents alignment from working correctly, so this change renders the cells using block elements instead.
Fixes https://github.com/rstudio/rstudio/issues/6314.
=> Render dataviewer cells with block elements

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/www/docs/keyboard.htm
- to reduce clashes with application shortcuts on Windows (Ctrl+Alt+?), change focus console output and focus main toolbar shortcuts to Alt+Shift+?
- also changed focus console output on Mac to use Ctrl+Alt+2 for better symmetry with Ctrl+2 (focus console); also avoids Ctrl+Alt+J which is commonly used to start JAWS on Windows
- added focus main toolbar to static keyboard help
=> change toolbar and console output shortcuts on Windows and Linux

src/cpp/diagnostics/CMakeLists.txt, src/cpp/session/CMakeLists.txt, src/cpp/session/postback/CMakeLists.txt
This change fixes a boot failure when RStudio is built on a macOS Catalina machine with homebrew OpenSSL 1.1, and then installed on a machine which doesn't have that library.
The general approach we take to this problem is to bundle OpenSSL with RStudio, and to rewrite the library paths of the compiled binaries so they point to the bundled copies (`@executable_path/...`) instead of the homebrew copies in `/usr/local/opt`. 
This isn't working any more with the latest homebrew OpenSSL 1.1 because of path canonicalization issues. The library path that is ultimately compiled into the binary is partially versioned but includes some symlinks. 
The fix is not pleasant. There is no deterministic way to determine the library path that will be compiled into the binary (as far as I can tell), so we …
=> Fix up libssl paths when building on macOS Catalina/libssl 1.1+

src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java
For makefiles which are gmake-only, [CRAN package guidance includes](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Writing-portable-packages): "If you only need GNU make for parts of the package which are rarely needed (for example to create bibliography files under vignettes), use a file called GNUmakefile rather than Makefile as GNU make (only) will use the former."
Rstudio should recognize the default GNU [make search names](https://www.gnu.org/software/make/manual/html_node/Makefile-Names.html) -- `GNUmakefile`, `makefile`, `Makefile` -- as Makefiles. This already happens for `Makefile`; this PR adds it for the other two filenames, as well `*.make` as requested in #4232.
I have attempted to test this by building Rstudio on my machine, but I'm not able to get all the cmake …
=> register default GNU make names as makefiles & address #4232

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/www/docs/keyboard.htm
Command that enables/disabled screen reader support had a 4-finger shortcut (Ctrl+Alt+Shift+/). Any shortcut requiring 4 fingers is unpleasant, but especially one that is so integral to bootstrapping the use of a screen reader in RStudio.
Changed to Alt+Shift+/ (but also left in the other mapping since it's been published on the blog). Will go back and update the blog to just reference the shorter one once a preview contains it.
=> simplify screen reader toggle shortcut

src/cpp/r/RExec.cpp, src/cpp/r/session/graphics/RGraphicsDevice.cpp, src/cpp/r/session/graphics/RShadowPngGraphicsHandler.cpp
Potential fix for https://sentry.io/organizations/rstudio/issues/1551321276/?project=1379214&referrer=slack.
Also fixes some more cases where we were passing arbitrary messages to R format strings.
=> check for null pointers in shadowDevOff

src/cpp/session/modules/SessionFind.cpp, src/cpp/session/modules/presentation/SlideRequestHandler.cpp, src/tools/clang-ubsan-build
Closes https://github.com/rstudio/rstudio/issues/6391.
Also updates the `clang` UBSAN script (used to generate sanitizer builds of RStudio locally on macOS)
=> fixes for UBSAN warnings + potential crashes

src/cpp/shared_core/Logger.cpp
We are seeing some crashes during static object deconstruction that seem to be caused by attempts to write logs after the log object has been deconstructed. This PR attempts to address those crashes by intentionally leaking the logger object. This means log destinations will not be able to rely on their destructors to flush their streams. Existing log destinations already flush (if necessary) after each message is logged.
Fixes #6282. There are other reports in sentry, but I can't seem to find associated git issues.
=> Intentionally Leak Logger Object

src/cpp/desktop/DesktopWebProfile.cpp
Candidate fix for https://github.com/rstudio/rstudio/issues/6201.
Note: merely sharing the web profile across different pages (RStudio windows) was surprisingly not sufficient; I was still able to reproduce cache load failures when opening multiple satellite windows at the same time. It looks like forcing HTTP resources to be cached in-memory helps avoid this issue, at least as far as I can see in testing.
=> share web profile across different pages

src/cpp/r/session/RInit.cpp, src/cpp/r/session/RQuit.cpp, src/cpp/r/session/RSearchPath.cpp, src/cpp/r/session/RSession.cpp, src/cpp/r/session/RSessionState.cpp, src/cpp/r/session/RStdCallbacks.cpp, src/cpp/r/session/graphics/RGraphicsDevice.cpp, src/cpp/r/session/graphics/RGraphicsUtils.cpp, src/cpp/session/SessionMain.cpp
This should fix some family of crashes; e.g.
https://sentry.io/organizations/rstudio/issues/1549458141/?project=1379214&referrer=slack
In many places, we were calling `Rprintf()` and `REprintf()` with the message provided directly to the function. This is dangerous, since user-defined input might contain arbitrary text -- including strings which might be interpreted for formatting!
The fix here is to always use an explicit format string, and then pass in user-defined input as an argument to the printf routine.
=> avoid passing user input to printf format strings

src/gwt/src/org/rstudio/studio/client/application/ui/RVersionSelectWidget.java
This fixes an issue in which you can't change the default version of R from Global Options (in RStudio Pro). 
The problem is subtle. It turns out that GWT implements its own `String.split` method, which doesn't have the same semantics as JavaScript's; in particular, `foo,bar,` splits to two elements instead of three. 
The fix is to use JavaScript's native string splitting method. 
Introduced by https://github.com/rstudio/rstudio/commit/489ded0ebf093ecc025cc28a4e7d3fd4f4b7b901; fixes https://github.com/rstudio/rstudio-pro/issues/1470.
=> Fix inability to change default R version

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
Spotted by @hadley. In RStudio v1.3, indented lines that are soft-wrapped are also indented; this behavior is undesired by default as it becomes less clear what indents are "real" and what are "not".
Before:
After:
Realize this is coming in pretty late for v1.3 but since this is just toggling an already-there Ace option to revert behavior it should be safe.
=> disable indented soft wrap

src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java, src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/test/org/rstudio/core/client/ConsoleOutputWriterTests.java
- Fixes #6413
- Was caused by #6341
- This change removes the extra div that was put around the console output `pre` element; that div was providing a named landmark around the console output and is what messed up this paste scenario
- The command for focusing the console output is still in place and makes a landmark around the console output largely redundant, so safer to remove that div rather than giving it a paste handler
- Moved the aria-label from the landmark down to the pre element
- This will require a small edit to the accessibility blog post since it mentions the console output landmark removed in this change
=> fix regression with right-click pasting into console on RStudio Desktop

src/cpp/session/modules/SessionHelp.cpp
Fixes #6425 
This PR fixes the issue where all text in the Help Pane was not being adjusted according to the selected size in the User Prefs.
=> Apply help panel font size selection to all text

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/www/docs/keyboard.htm
Change the letter used to access the Accessibility submenu to "A" and the letter used for About to "B". Keyboard users will be more likely to use the Accessibility submenu than the About dialog, so having the most memorable key be used is ideal.
Based on user feedback, changing several accessibility keyboard shortcuts to be 3-finger instead of 4-finger:
- Toggle Tab Key Moves Focus is now Alt+Shift+[ on Windows and Linux, and Ctrl+Option+[ on Mac
- Speak Editor Location is  now Alt+Shift+1 on Windows and Linux, and Ctrl+Option+1 on Mac
- These are the last planned accessibility-related shortcut tweaks for 1.3 (barring discovery of conflicts)
=> simplify several accessibility-related shortcuts

src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.java
Closes https://github.com/rstudio/rstudio/issues/6418.
This was missed because we normally install tutorial dependencies here:
https://github.com/rstudio/rstudio/blob/d539bdbca79261d237f5350fd392ab416e95bb51/src/cpp/session/modules/SessionTutorial.R#L226-L280
However, this code path does not check package versions (and that's something to be addressed separately; I need to confirm whether there's an official mechanism for a `learnr` tutorial to declare that it requires a specific set of packages).
=> use dependency manager for tutorial dependencies

src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/PackageActionConfirmationDialog.java
Fixes #6375
Regression introduced by accessibility work (early summer 2019); I enabled keyboard-selection in this dialog's cell table, but that alone wasn't sufficient to make this dialog fully keyboard usable, and caused a nasty regression when using via mouse, so reverting. Didn't see any other instances where I used this pattern. Regression was introduced in 8bf99466.
=> fix regression in update packages dialog

src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.java
This change fixes an issue in which the Tutorial pane didn't load or work correctly on non-local instances of RStudio server. 
The problem was that the Tutorial pane loads non-local URLs with a very restrictive sandbox that keeps them from using the origin of the hosting page, with the result that CORS denied all the AJAX requests originating on the page. The fix is to give them the `allow-same-origin` privilege (along with a couple other that tutorials are likely to need down the road). 
Fixes #6362.
=> Allow same origin for Tutorial pane sandbox

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
This change fixes a couple of disruptions caused by autosave. These are in turn caused by the fact that we reload some parts of the editing system every time we save, because sometimes content changes in the file need to trigger different editor behavior. 
For example, if you paste a Shiny app.R file into an ordinary R script and save it, RStudio's editor adapts and gives you the Run App button.
Unfortunately this has some side effects, including losing some vim state and (more importantly) knocking down autocompletion popups. So this change causes us to be just a little more conservative about reloading those parts of the editing system. We now avoid refreshing them unless the incoming file type and/or extended type are different than the ones we already know about.
Fixes …
=> Reduce disruptions caused by autosave

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/www/docs/keyboard.htm
- Fixes #6447
- Shortcut now follows the same pattern as others in terms of Mac vs. Windows (not sure why I didn't do this the first time...)
- Also make the "Toggle Screen Reader Support" command's shortcut user-customizable
- Remove original shortcut (Ctrl+Alt+Shift+/) as it is no longer mentioned in blog post or keyboard reference
=> change toggle screenreader shortcut on Mac to avoid clash with intl keyboards

src/cpp/desktop/DesktopWebView.cpp
Closes https://github.com/rstudio/rstudio/issues/6395.
I had tried to implement support for Paste vs. Paste with Indent in a previous PR, but backed that out after running into trouble in having it work properly in different contexts. Unfortunately, this part was left in and caused the previously-referenced issue.
=> remove 'paste with indent' desktop-level binding

src/cpp/session/modules/SessionTutorial.R, src/gwt/src/org/rstudio/studio/client/common/DefaultGlobalDisplay.java, src/gwt/src/org/rstudio/studio/client/common/GlobalDisplay.java, src/gwt/src/org/rstudio/studio/client/common/impl/WebWindowOpener.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialUtil.java, src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/events/TutorialCommandEvent.java
This PR fixes a number of issues with the Tutorial pane.
- Tutorials can now be stopped after a browser refresh, regardless of whether RStudio Server is proxying URLs or not. This is accomplished by tagging running tutorials with both the underlying Shiny URL, as well as the proxied URL. This also allows us to avoid maintaining any extra state client-side -- as long as we have the tutorial URL, we can find the underlying running tutorial.
- Popped-out tutorials now have their underlying tutorial stopped when the associated window is closed.
- If a user pops out a tutorial, leaves that window open, and later tries to restart that tutorial, we will bring that popped-out window to the front rather than attempt to launch a second instance of that tutorial.
=> tutorial pane bugfixes

src/cpp/session/modules/SessionFind.cpp
Fixes #6048 
This PR fixes the global replace functionality so it no longer changes the file permissions where the replace takes place. Since we are using a temporary file to perform the replace, we save the permissions of the original file while initializing the replace, and set these permissions after overwriting the original file with the one containing the replace.
=> Maintain file permissions while performing replace

src/cpp/session/modules/SessionSpelling.cpp, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/spelling/CheckSpelling.java
Fixes #5242  - I had missed updating the token for non-realtime spellchecking. This works now.
Hopefully Fixes #6047 
I cannot reproduce what @rich-rstudio is seeing but this will help reduce errors for custom dictionaries. I suspect something else is going on in rich's environment still but this is worth a shot.
=> Match realtime and not realtime token predicates, allow missing aff files

src/cpp/r/session/graphics/RGraphicsPlot.cpp
On Windows, we seem to get occasional crahses when invoking `writeToPNG` that appear to be due to invalid or corrupt file paths:
https://sentry.io/organizations/rstudio/issues/1560024620/?project=1379214&referrer=slack
It's not clear to me why this could occur, but we also observed a similar issue with R Presentations, where crashes appeared to occur when FilePaths were used as rvalues:
https://github.com/rstudio/rstudio/pull/6392/commits/91e15dbc8bd074c79815d9cd4c147e035c5f373a
This fix does the same thing as above, hoisting the file paths into their own variables rather than passing them directly into `saveSnapshot()`.
=> speculative fix for writeToPNG errors

src/cpp/core/include/core/http/TcpIpAsyncClientSsl.hpp
OpenSSL does not support the use of the Windows certificate store out-of-the-box, so some additional programming is needed to get this working.
Fixes https://github.com/rstudio/rstudio-pro/issues/1522
=> Make openssl verification work on windows by importing windows cert store certificates

src/cpp/shared_core/include/shared_core/json/Json.hpp, src/cpp/shared_core/json/JsonTests.cpp
Supports calling json::readObject with sets, as well as optional vectors and optional sets.
=> Add support for json::readObject with sets

src/cpp/shared_core/include/shared_core/system/User.hpp, src/cpp/shared_core/system/User.cpp
Also need this for the Launcher Plugin SDK.
Two users are the same if they have the same user ID. Also implements move constructor and operator for User.
=> Add equality and inequality operators to User

src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java
Unfortunately, it appears that the Italian dictionary that we ship with is also subject to the loading issues that we found a few weeks ago. I spent a little more time looking into what's causing Typo.js to struggle so much but this would obviously be out of scope for 1.3.
Fixes #6483
=> Add Italian to realtime spellcheck blacklist

src/cpp/session/SessionDirs.cpp
This change fixes an issue in which the `session-default-working-dir` setting was always ignored in `rsession.conf`. 
The problem was that we were trying to respect the new user preference for this value, but doing so by immediately resolving the path set in the preference. Because `resolveAliasedPath` resolves to the home folder when given an empty string (behavior we should probably consider changing), the user preference was treated as though it were set to the home directory even though it was actually unset. 
Fixes https://github.com/rstudio/rstudio-pro/issues/1556.
=> Only use user pref for default working dir if defined

src/gwt/.gitignore, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Closes https://github.com/rstudio/rstudio/issues/6501.
Candidate for backport to v1.3, as we are stuck with a Qt issue that makes it impossible for us to differentiate between <kbd>Ctrl + Alt + M</kbd> and <kbd>AltGr + M</kbd>.
Fortunately, removing or renaming the binding is a way out.
=> make global VCS commands rebindable

src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/ObjectExplorerEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetVisualMode.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java
This PR adds an argument to the  `EditingTarget.onActivated()` method that indicates whether the editor tab is being activated for the purpose of user interaction (during startup `onActivated()` is called for each tab being restored irrespective of whether it will actually end up active at the end of startup). 
The motivation is that panmirror does some potentially expensive (depending on the platform) work at startup (calls pandoc twice). On Linux/OSX these calls take sub 10ms however on Windows they can take 100ms+. If a user has dozens of tabs w/ panmirror to be restored, the cost of doing panmirror initialization eagerly could become prohibitive. With this change we can defer this work until the user is actually going to interact with the document.
I could have "fixed" `onActivated()` …
=> Add parameter to EditingTarget.onActivated indicating whether it's being activated for user interaction

src/cpp/core/http/URL.cpp
Fixes #5724
Update the URL constructor to parse out `file://` and `ftp://`. This will allow users to access and download packages from a Windows fileshare system.
=> Update URL constructor to handle paths beginning with file:// or ftp://

src/cpp/r/R/Tools.R, src/cpp/r/include/r/session/RGraphics.hpp, src/cpp/r/include/r/session/RGraphicsConstants.h, src/cpp/r/session/graphics/RGraphicsUtils.cpp, src/cpp/session/CMakeLists.txt, src/cpp/session/SessionClientInit.cpp, src/cpp/session/SessionMain.cpp, src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/modules/SessionGraphics.R, src/cpp/session/modules/SessionGraphics.cpp, src/cpp/session/modules/SessionGraphics.hpp, src/cpp/session/prefs/UserPrefValues.cpp, src/cpp/session/resources/schema/user-prefs-schema.json, src/gwt/src/org/rstudio/core/client/ElementIds.java, src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
This PR makes it possible to configure some parameters of the graphics device created by RStudio. In particular:
1. The backend (ie: Quartz vs. Windows vs. Cairo);
2. Whether anti-aliasing is used for the generated plots.
This will primarily be useful on Windows, where users have often wished they could use Cairo as opposed to the default Windows graphics backend.
Closes https://github.com/rstudio/rstudio/issues/2142.
=> allow configuring graphics device type, antialias

src/cpp/core/include/core/system/System.hpp, src/cpp/core/system/System.cpp
This is required for a bug fix in the pro repo.
=> Add function to get the type of logger for a log section

src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
This change returns the user to the Console pane after implicit dependency installation in the Jobs tab (see associated issue for justification). 
Fixes https://github.com/rstudio/rstudio/issues/6535
=> Switch away from Jobs pane after successful package installation

dependencies/common/install-boost
=> force clang-darwin toolset when building boost on macOS

dependencies/common/install-qt.sh, dependencies/linux/install-qt-linux, dependencies/osx/install-dependencies-osx, dependencies/osx/install-qt-macos, docker/jenkins/Dockerfile.bionic-amd64, docker/jenkins/Dockerfile.centos7-x86_64, docker/jenkins/Dockerfile.debian9-x86_64, docker/jenkins/Dockerfile.fedora28-x86_64, docker/jenkins/Dockerfile.opensuse15-x86_64, docker/jenkins/Dockerfile.xenial-amd64
- use script from Qt to download and install SDK without involving the Qt installer (which now requires a sign-in)
- impacts macOS, and all Linux flavors that were using 5.12.1
- Windows and older Linux variants continue using direct download from S3 of a pre-built Qt image
=> backport new qt install technique to 1.2 patch

src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Visual mode might be active (and have un-synced edits) when an rstudioapi client retrieves the EditingContext. This PR ensure that edits are synced and the text editor is made active before returning the context to the client.
=> ensure that the text editor is active when rstudioapi retreives the editor context

src/cpp/core/system/PosixShellUtils.cpp, src/cpp/core/system/PosixShellUtilsTests.cpp
This PR improves the way we escape arguments for shell commands.
Previously, we tried to escape arguments with double-quoted strings, and then backslash-escaped any special inner characters within. Unfortunately, that solution doesn't always work, since whether `!` is treated as a special character (ie: performs history expansion) is dependent on the shell, and how that shell is configured.
Using single quotes is much safer, as within single quotes only another single quote is 'special' (it ends the string) and so that is the only entity that needs escaping.
Closes https://github.com/rstudio/rstudio/issues/6160.
(Note: I'm not sure what the most appropriate label for this is)
=> use single quotes to escape strings for shell

src/cpp/r/RExec.cpp, src/cpp/r/include/r/session/RGraphics.hpp, src/cpp/r/session/graphics/RGraphicsUtils.cpp, src/cpp/r/session/graphics/RShadowPngGraphicsHandler.cpp, src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/modules/SessionGraphics.R, src/cpp/session/resources/dependencies/r-packages.json, src/cpp/session/resources/schema/user-prefs-schema.json, src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
This PR adds support for the AGG renderer as provided by the `ragg` package.
The implementation here is fairly simple -- rather than using `grDevices:::png()`, we use `ragg:::agg_png()` to open the graphics device, and let our shadow graphics device operate as usual.
See https://ragg.r-lib.org/ for some documentation on `ragg`.
=> add support for ragg renderer

src/cpp/session/resources/themes/README.md, src/cpp/session/resources/themes/ambiance.rstheme, src/cpp/session/resources/themes/chaos.rstheme, src/cpp/session/resources/themes/clouds_midnight.rstheme, src/cpp/session/resources/themes/cobalt.rstheme, src/cpp/session/resources/themes/dracula.rstheme, src/cpp/session/resources/themes/gob.rstheme, src/cpp/session/resources/themes/idle_fingers.rstheme, src/cpp/session/resources/themes/kr_theme.rstheme, src/cpp/session/resources/themes/material.rstheme, src/cpp/session/resources/themes/merbivore.rstheme, src/cpp/session/resources/themes/merbivore_soft.rstheme, src/cpp/session/resources/themes/mono_industrial.rstheme, src/cpp/session/resources/themes/monokai.rstheme, src/cpp/session/resources/themes/pastel_on_dark.rstheme, src/cpp/session/resources/themes/solarized_dark.rstheme, src/cpp/session/resources/themes/tomorrow_night.rstheme, src/cpp/session/resources/themes/tomorrow_night_blue.rstheme, src/cpp/session/resources/themes/tomorrow_night_bright.rstheme, src/cpp/session/resources/themes/tomorrow_night_eighties.rstheme, src/cpp/session/resources/themes/twilight.rstheme, src/cpp/session/resources/themes/vibrant_ink.rstheme, src/gwt/tools/sync-ace-commits
Also update material, which needs to be maintained manually, and add a README in the themes folder to explain how to generate themes and which themes are maintained manually. Currently, only material is made manually because ACE added Dracula to their set of CSS themes.
=> Update dark themes based on the new default node-selector color

src/cpp/desktop/DesktopBrowserWindow.cpp, src/cpp/desktop/DesktopGwtCallbackMac.mm, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/modules/build/SessionBuild.cpp
The trick for ignoring the leading newline in raw string literal generates below warning so stopped doing it. Also comment out some unused parameters.
```
/Users/gary/rstudio/src/cpp/session/SessionModuleContext.cpp:2633:24: warning: adding 'int' to a string does not append to the string [-Wstring-plus-int]
const char* msg = 1 + R"EOF(
~~^~~~~~~~
/Users/gary/rstudio/src/cpp/session/SessionModuleContext.cpp:2633:24: note: use array indexing to silence this warning
```
=> fix C++ warnings related to raw literals and unused parameters

src/cpp/desktop/CMakeLists.txt, src/cpp/desktop/DesktopMain.cpp, src/cpp/desktop/DesktopOptions.cpp, src/cpp/desktop/DesktopRVersion.cpp
- turn on deprecation warnings (this is on by default starting with Qt 5.13)
- QString::null has been deprecated since Qt 5.9, replace with QString() as recommended
- QtAlgorithms::qSort has been deprecated since Qt 5.2, replace with std::sort as recommended
- comment out more unused parameters to reduce warnings
Note there are additional things we use that are deprecated starting with Qt 5.11 and will give warnings when building with Qt 5.12; once we've stopped building anything with Qt 5.10 I'll clean those up as well, see #6585.
=> cleanup (some) deprecated Qt usage

src/cpp/session/include/session/prefs/UserPrefValues.hpp, src/cpp/session/prefs/UserPrefValues.cpp, src/cpp/session/projects/SessionProjects.cpp, src/cpp/session/resources/schema/user-prefs-schema.json, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
Today, if an R session crashes, the next session that starts will be in the empty project. This is an intentional safety feature that allows users to escape a crash loop: if the contents of a directory cause RStudio to crash when started there, there would be no escape if we kept restarting RStudio in that directory.
However, most crashes are not startup crashes, and so this behavior is usually unwanted. In some configurations it can also lead to data loss because of source database detachment.
This change allows the R session to keep starting in the same directory even after a crash, presuming that the session was alive for a suitable period of time after startup. It does this by writing the `last-project-path` setting (formerly written only on a clean quit).
Fixes …
=> Restore project if it starts successfully

src/cpp/session/modules/SessionCodeTools.R, src/cpp/tests/testthat/test-codetools.R
This PR fixes an issue where single quotes within R strings were not correctly escaped when constructing the download file options.
Closes #6597.
=> fix handling of single quotes in download option

src/cpp/core/FilePathTests.cpp, src/cpp/shared_core/FilePath.cpp
This PR fixes an issue where attempts to modify files within the home directory, when that directory is referenced with a UNC path, could fail.
Background: On Windows, while `\` is the canonical path separator, most Windows APIs still accept `/` and translate all forward slashes to backslashes behind the scenes. However, we do not normalize separators up-front when creating `FilePath` objects, and some Boost filesystem APIs are indeed sensitive to mismatched separators -- presumedly because `\` is a legal path component on POSIX.
So, when we accept and create `FilePath` objects, we create it with the underlying path as-is. On Windows, we probably should normalize separators (e.g. always use `/` or `\`), but making that change is somewhat aggressive.
So, as a slightly smaller change, this …
=> improve handling of UNC paths on Windows

NEWS.md, src/gwt/src/org/rstudio/core/client/widget/ScrollableToolbarPopupMenu.java
Closes https://github.com/rstudio/rstudio/issues/5941.
=> disable focus on hover for cpp completions

src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
Closes https://github.com/rstudio/rstudio/issues/6593.
Note that these commands are now handled as regular shortcuts, and we have a dispatch mechanism here:
https://github.com/rstudio/rstudio/blob/f70874ee337814ee547103bb17f31bd0cb8418bf/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorCommandDispatcher.java#L75-L81
The idea here is that the command is fired to all Ace instances, and only the one which is currently focused will take any action in response to the shortcut. Since the console is ultimately just another Ace instance, we can just rely on this dispatch and avoid hard-coding the shortcuts here.
=> remove hard-coded console shortcuts

src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
=> disable JobsListTests GWT unit test due to slowness

docker/jenkins/Dockerfile.windows
- use Windows decompression tools instead of 7zip
Worth a try; works on my Dockerfile build (but the original ways was also working so...).
=> windows dockerfile tweaks

src/cpp/session/resources/grid/dtviewer.js
Made the resize callbacks work on the `body` and not just the header. 
Fixes #1665
Fixes #2642
Fixes #4361 
I'm going to be reworking the global variable state and probably even more than that in the 1.4 release so the _step backwards_ in encapsulation and variable naming will be improved as this is iterated on.
Apologies for the whitespace reformatting, please review with ignore whitespace turned on. It's still imperfect and I'm going to run Prettier on it in the next change. It had awkward 2 and 3 space formatted scattered about and still has a few blemishes left. https://github.com/rstudio/rstudio/pull/6633/files?w=1
=> Allow resizing without the mouse being on the header

src/cpp/shared_core/include/shared_core/json/Json.hpp
Previously, the optional value would be set to an empty list/vector if the value wasn't found instead of an empty optional.
=> Fixes a bug in json::readObject for optional sets and vectors

src/cpp/shared_core/system/User.cpp
This was a type (`-1` -> `1`), but I just changed it so we allocate a reasonable buffer size if we get any negative integer from the OS.
=> Fix an issue were we might try to allocate negative buffers

src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Fixes #6637 
The Yes/No call for opening large files was not clearing the file from `openFileQueue_` when the user chose to not open it. This was preventing future files from being opened.
=> bug fix for opening large files 

src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsolePane.java
PR #6428 broke 'Move focus to Console' by calling the ActivatePaneEvent for it when this command doesn't work properly for the Console Pane. This fix prevents the event from being fired.
=> Fix "Move Focus to Console"
