- src/cpp/core/BrowserUtils.cpp
- src/cpp/core/http/Response.cpp
Chromeframe was an Internet Explorer plugin that allow hosting Chromium inside IE window. This was retired in 2014 and should not be used by anyone at this point, so we don't need to detect it.
https://www.chromium.org/developers/how-tos/chrome-frame-getting-started
> remove detection of chromeframe plugin

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/core/client/StringUtil.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java
This is a small improvement suggested by @mine-cetinkaya-rundel; the Files pane now sorts filenames naturally, preserving ascending sequences. There is a new pref so that this can be turned off by people who really don't like it, but it defaults to on and doesn't have any UI for toggling since we expect most people will prefer natural ordering.
Closes https://github.com/rstudio/rstudio/issues/5766.
> Sort file names naturally in the Files pane

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesTab.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileCommandToolbar.java
> add command to Files Pane More menu to copy path to clipboard

- src/cpp/core/StringUtils.cpp
- src/cpp/core/include/core/StringUtils.hpp
- src/cpp/session/SessionConsoleInput.cpp
- src/cpp/tests/python/test-code-submit.py
This PR fixes an issue where attempts to submit blocks of Python code with inconsistent indentation (e.g. blank lines between statements) to the `reticulate` REPL would fail. To fix this, we attempt to fix the indentation of blank lines post-hoc when code is submitted to the console.
This, admittedly, feels like a kludge. However, we have one major constraint: `reticulate` relies on R's `readline()`, which reads a single newline-buffered line at a time. Ultimately, that implies the fix needs to occur before the code is submitted to `reticulate`. And since an empty line submitted to `reticulate` is normally treated as the end of a block, we need to explicitly side-step that behavior by adjusting the code indent.
An alternative approach would be to use some sort of special encoding for …
> improve handling of multiline Python blocks in console

- src/cpp/r/R/Tools.R
- src/cpp/session/modules/SessionAuthoring.R
- src/cpp/session/modules/SessionBreakpoints.cpp
- src/cpp/session/modules/SessionPackages.R
Now that RStudio requires R >= 3.0.1, we can remove some of these older version checks.
> remove checks for older, unsupported R

- src/cpp/session/SessionMain.cpp
- src/cpp/session/include/session/prefs/UserPrefs.hpp
- src/cpp/session/prefs/UserPrefs.cpp
- src/cpp/session/projects/SessionProjectContext.cpp
- src/cpp/session/projects/SessionProjects.cpp
This change fixes an issue in which the very first boot of RStudio 1.3 does not show any of the document tabs that were open in a project in RStudio 1.2.
The problem is that the document tabs are stored beneath a folder scoped using a context identifier. The context identifier is correctly migrated from RStudio 1.2 to RStudio 1.3, but this migration happens later in the boot process. Consequently, the very first boot doesn't have the right ID.
The fix is to slightly alter the boot order as follows:
1. Break the dependency on project initialization by separating the project pref init from the session/user pref init.
2. Initialize the session/prefs before the project. This causes the old ID to be migrated before we attempt to use it. 
3. Initialize the project-level prefs and recompute …
> Ensure RStudio document tabs are reopened on first boot from 1.2 -> 1.3 

- src/cpp/core/include/core/r_util/RToolsInfo.hpp
- src/cpp/core/r_util/RToolsInfo.cpp
- src/cpp/r/session/REmbeddedWin32.cpp
- src/cpp/session/modules/build/SessionBuildEnvironment.cpp
- src/cpp/session/modules/build/SessionInstallRtools.cpp
- src/cpp/session/modules/clang/RCompilationDatabase.cpp
NOTE: Not quite ready for merge; pending confirmation on the URL to use for the Rtools installer.
---
The PR adds support for Rtools 4.0, the toolchain used to build packages for the R 4.x.x series.
Note that there are two installers: one for users on 32bit Windows (providing only a 32bit toolchain), and one for 64bit Windows (providing both 32bit and 64bit toolchains). While RStudio itself is now a 64bit application (and hence should only be used with 64bit Windows), I did add indirection for the Rtools installer in any case.
> add support for Rtools 4.0

- src/cpp/core/r_util/RToolsInfo.cpp
I think we can take this and also apply to v1.3. (Looks like the move happened a bit more quickly than I expected!)
> update Rtools URL

- src/cpp/session/resources/grid/dtviewer.js
- src/gwt/src/org/rstudio/studio/client/dataviewer/DataTable.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTargetWidget.java
Fixes #1819
(and possibly some other filed issues)
Currently we are just reloading the data and trying to keep the visible state as much intact as possible when the underlying data changes. Unfortunately this leaves the Dataviewer in a very weird state. Things like tooltips, paging, filters can all get out of sorts and can get very confused when the "fire and forget" HTML gets partially out of sync with the data. With the way that it's currently set up (no id's on headers, no objects tied to the HTML directly) we can't just put new data into the rows without a full refresh. I tried to fix just the issue filed in the bug but I found quite a few other things wrong with this. If this feature is worth the bugs it causes I think its worth an enhancement discussion.
I'm considering options for …
> Always refresh data viewer when source data changes

- src/cpp/session/modules/SessionFind.cpp
This PR fixes a bug where we would occasionally try to access the wrong iterator.
> Prevent replace exception

- package/linux/debian-control/postinst.in
- package/linux/debian-control/postrm.in
- package/linux/rpm-script/postinst.sh.in
- package/linux/rpm-script/postrm.sh.in
Fall back on installing rstudio service scripts at `/usr/lib/systemd` if `/lib/systemd` does not exist.
Fixes https://github.com/rstudio/rstudio-pro/issues/1612
> Fall back rstudio service installation path to /usr/lib/systemd

- src/cpp/core/http/URL.cpp
- src/cpp/core/http/URLTests.cpp
- src/cpp/core/http/Util.cpp
- src/cpp/core/include/core/http/URL.hpp
Closes #1495
This PR adds a protection against path traversal in some scenarios.
The core of this change is the implementation of `core::http::Path::cleanup()`.
Goal: Pair each occurrence of `../` with a removal of an item from the path.
Before: If there was no matching pair (it was already on the "root") the `../` was preserved.
Now: If there's no matching pair, the `../` is discarded.
The new behavior is similar to how NGINX handles relative paths.
That was detected when comparing open source and pro.
With the change above, `core::http::URL::complete()` will start to discard extraneous `../`.
The `boost::test` gig present in `URL` was included in `core/http/URLTests.cpp` to be sure we keep testing these changes.
The second part of this change is exposing `core::http::URL::cleanupPath()` …
> Prevent path traversal: Ignore relative URL path referencing past root

- src/cpp/server/ServerMain.cpp
- src/cpp/server/extras/conf/database.conf
- src/cpp/server_core/ServerDatabase.cpp
- src/cpp/server_core/include/server_core/ServerDatabase.hpp
Let me know if you think this indeed does need the XDG treatment. Reading through the spec it looked to me like there was only a concept for a user data dir, not a system data dir, so I've forgone the XDG treatment.
Fixes #6706
> Change default sqlite database path from /var/run to /var/lib to ensure it is not deleted on reboot

- src/cpp/session/modules/SessionSource.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/DocUpdateSentinel.java
Closes https://github.com/rstudio/rstudio/issues/6709.
This PR bundles a few changes together:
1. We disable the autosaver when first initializing a document, as we want to avoid "spurious" document saves when the document is first opened. This is especially important for the case where the document has been opened with an incorrect encoding (and so the repesentation of that document within the RStudio editor is incorrect).
2. We handle exceptions that occur when attempting to save a document diff, since `.replace()` can throw an exception here.
3. When attempting to re-open a document with a different encoding, we no longer attempt a save before re-opening the document. This is for the same reason as in (1) -- if the user is attempting to re-open a document in a particular encoding, it's …
> better handle attempts to save / re-open mis-encoded documents

- src/cpp/core/http/URL.cpp
- src/cpp/core/http/URLTests.cpp
- src/cpp/core/include/core/http/URL.hpp
Quick change to move URL tests from BOOST_ASSERT to testthat like the rest of our tests.
> Move URL::test to testthat

- src/gwt/src/org/rstudio/core/client/theme/WindowFrameButton.java
- Fixes #6721
- I believe this meets the bar as a ship-stopper (sorry...)
- Caused by missing event suppression when I refactored window frame button click handler into a shared UI component; note that the keyboard handler path was doing this, and continued working properly
- While investigating discovered essentially the same problem exists with double-click, and repros in 1.1, 1.2, and 1.3 (#6724); since that's not a regression and obviously hasn't caused much grief, not fixing in 1.3
- QA notes: please test various pane max/min/restore behaviors, both with and without the reduced UI animation accessibility setting checked; some of this behavior is a bit unintuitive, so best to compare against 1.2 behavior (goal is for it to behave the same way)
> fix pane max/min behavior

- src/cpp/session/SessionSourceDatabase.cpp
- src/cpp/session/include/session/SessionSourceDatabase.hpp
- src/cpp/session/modules/SessionRUtil.cpp
- src/cpp/session/modules/SessionSource.cpp
- src/cpp/session/modules/customsource/SessionCustomSource.cpp
- src/cpp/session/modules/preview/SessionPreview.cpp
- src/cpp/session/modules/rmarkdown/NotebookCache.cpp
For files which have an unknown / "text" file type, attempt to infer an appropriate source filetype based on the shebang in the file (if any).
Closes https://github.com/rstudio/rstudio/issues/5643.
> use shebang to infer filetype when appropriate

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Closes https://github.com/rstudio/rstudio/issues/6703.
Also bundles a brown-bag CSS fix for IE11 -- the empty space in a tab panel was not being styled for dark themes.
> fix ensure visible behavior

- src/cpp/diagnostics/DiagnosticsMain.cpp
- src/cpp/session/include/session/prefs/UserState.hpp
- src/cpp/session/prefs/UserStateLayer.cpp
We currently store RStudio's per-user state in `~/.local/share/rstudio/rstudio-state.json`. This means that both desktop and server share per-user state, which can cause conflicts when RStudio Desktop and RStudio Server are both used with the same account. 
The fix is to store them in separate files in the same folder (`rstudio-desktop.json` and `rstudio-server.json`). This causes them to use different context IDs, which in turn gives them different source databases. 
Fixes https://github.com/rstudio/rstudio/issues/6742.
> Use separate state files for desktop and server

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
This change fixes an issue in which the Publish button doesn't treat a file as saved if it was unsaved when the file was first opened.
The problem is that we notify the Publish button that the file has been saved through an oblique path that relies on a side effect of an extended type change; the fix is to restore this path even when the type hasn't actually changed.
A more complete (and better) fix would be to listen for changes to the path in the DocUpdateSentinel and sync the publish button to those changes. That would eliminate this class of bugs entirely and probably get rid of our manual `syncPublishPath` invocations. However as we're very late in 1.3 it's saner to simply restore the existing behavior. 
Fixes https://github.com/rstudio/rstudio/issues/6711.
> Sync publish path even when type has not changed

- src/cpp/session/SessionConsoleInput.cpp
Potential fix for crashes of this form:
https://sentry.io/organizations/rstudio/issues/1629008167/?project=1379214&query=_platform_memmove%24VARIANT%24Haswell&statsPeriod=14d
My hypothesis: if an attempt to read console input fails, we still attempt to pop an RConsoleInput object off of the (currently empty) buffer of pending inputs. This basically gives us a pointer to garbage memory, and we later see a crash when attempts to use that memory fail (evidently, occurring within a Boost signal handler).
That said, it seems equally unlikely that we could get an invalid `console_input` RPC request, so this is mainly speculative.
> avoid popping console input on failure to read

- src/cpp/session/modules/SessionFindTests.cpp
Fixes #6747
Prior to this PR the incorrect `matchOn` and `matchOff` variables were being provided for the 'Replace regex case sensitive' unit tests, causing them to fail on Windows. In RStudio these values are generated by the `grep` command so there were no bugs outside of the tests. The outcomes differed per OS due to the unique default behavior of `grep` on Windows.
> Fix SessionFind tests on Windows

- src/cpp/session/prefs/UserStateLayer.cpp
- src/cpp/session/prefs/UserStateLayer.hpp
We recently moved to separate state files for desktop and server (see https://github.com/rstudio/rstudio/issues/6742). However, they were both new files, which means that if you used an older version of the 1.3 preview you'll lose your context ID and therefore your open tabs.
This change fixes that issue by migrating the old state file if it exists. 
(note: user preferences tag is because this is closely related to the preference system)
Will be backported to 1.3.
> Read old RStudio 1.3 state file if it exists

- docker/win-docker-compile.cmd
This finishes a script I started ages ago. You can now build RStudio for Windows on a Windows-10 Pro machine using the same Dockerfile we use for official builds. Simply clone the rstudio repo, then go into rstudio\docker folder (in command prompt) and run `win-docker-compile.cmd`.
Obviously you need Docker installed on your Windows machine, and configured to use Windows containers.
For best results, use a clean repo (no installed dependencies or previous build outputs); can achieve this via cloning new repo copy or "git clean -ffdx".
Was previously blocked due to MSVC 2017 issues with building source mounted into the container as a volume when using Hyper-V based Docker (the only mode supported on Windows-10). Windows-Server also supports process-isolation, which doesn't have this bug. …
> Script for local Docker-based Windows builds

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/common/filetypes/RWebContentFileType.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/RMarkdownPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/EditSession.java
This is a quick feature that adds two new capabilities:
- Some users (a minority) prefer not to use wrapping with their R Markdown documents. This change adds a new global preference so that this behavior can be changed.
- It is now possible to toggle soft wrapping mode off and on for any file. This setting sticks with the file (using document properties), and overrides the file type's default wrap mode if present. This makes it possible to quickly switch into and out of soft wrap mode without changing global preferences, and can be bound to a keyboard shortcut.
Closes https://github.com/rstudio/rstudio/issues/2341.
> Add toggle for soft wrap mode

- docker/win-docker-compile.cmd
Would be more elegant to do this by parsing last line of build output (as we do on Linux), but for now this does the trick.
> tweak win-docker-compile script to also work with Desktop Pro building

- src/cpp/session/modules/SessionThemes.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
We now call setCacheWithRevalidationHeaders when serving theme css to make sure that the browser doesn't use an older copy of the theme (now at a minimum the browser must get back a 304 to use a cached copy).
There are several other places in the codebase where a similar change is likely warranted.
Note that we also add a do-nothing URL parameter ("refresh=1") to the theme request to work around any existing cached themes.
> Ensure that we always serve the latest theme css

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
This change makes it possible to discover dependencies in untitled buffers; this regressed when we started doing this in a background job that required a job name derived from the path of the buffer. 
Fixes https://github.com/rstudio/rstudio/issues/6762.
> Allow for package dependency discovery in untitled buffers

- src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/core/client/widget/ShowContentDialog.java
- Fixes #6771
- Came from a customer request for RSP (see bug)
- ShowContentDialog is only used for this particular scenario (and for the obsolete agreement dialog being removed in #6774)
Before (with a long string I injected for testing):
After showing wordwrap and ability to select text (and thus copy it):
> enable wordwrap and selection of message in RSA key creation error dialog

- src/gwt/src/org/rstudio/core/client/StringUtil.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetChunks.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextToolbar.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextUi.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkOutputUi.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/DefaultChunkOptionsPopupPanel.java
- src/gwt/test/org/rstudio/core/client/StringUtilTests.java
- src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
- src/gwt/test/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextUiTests.java
This PR implements items 1-3 of #6652 
It adds `getCssIdentifier` to `StringUtil` which builds a string valid as a CSS id, replacing invalid characters with an 'x'. This function is invoked to add an `id` to chunks so their child elements can be easily referenced. The `id` is set to the chunk's label and adds the prefix `output_` to the chunk's output.
In particular this can be used with to highlight buttons and output associated with a chunk. 
Running `>rstudioapi::highlightUi("#pressure [title='Run Current Chunk']")` will yield:
Running `>rstudioapi::highlightUi("#output_pressure")` will yield:
> Add class attributes to chunks

- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/modules/SessionHelp.cpp
- src/cpp/session/modules/viewer/SessionViewer.cpp
In RStudio Desktop, we currently use R's HTTP server to serve files from the session temp folder, including HTML widgets. There appears to be a bug in this server in R 4.0 for Windows, which causes the widgets not to display and burns a bunch of CPU until R is restarted. See #6737 for the gory details.
This change is a minimal fix for the issue which is intended to work around this specific problem; it is intended for the RStudio 1.3 release. Consequently it only touches this specific combination (R 4.0, Windows). Since we already have a mechanism for serving these files in RStudio Server, we just use it in desktop mode when necessary.
We might consider a follow-up to change (for RStudio 1.4) which simplifies all this code by using our internal server all the time; I don't see any …
> Fix HTML widget viewing on R 4.0 for Windows

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- See #6805 which I will resolve once I've back-ported this to 1.3-patch
- Regression caused by: 2f3255d6
- Will break automation; fix for that is: https://github.com/rstudio/rstudio-ide-automation/pull/49
> Restore correct element ID for console's input field

- src/cpp/session/resources/grid/dtstyles.css
Fixes #6469 
Large cells still had `inline-block` which doesn't play nicely with text-align. Removing this attribute also makes column resizing feel a bit nicer.
> Remove inline-block attribute from largeCells

- NEWS-1.3-patch.md
- src/cpp/session/modules/SessionTerminalShell.cpp
- Fixes #6696
- Fixes #6809
- Stop directly invoking the MSYS2 bash.exe installed with Git for Windows, and instead use the wrapper bash.exe (also installed by Git for Windows) which correctly sets up the environment
- Doing so allows RStudio terminal to use Git-Bash even if RTools4 has been installed and is on the path (as recommended by RTools4 docs); without this fix the path is wrong and can try to use Posix tools from both environments leading to runtime errors
Test notes for QA
-----------------
- Windows-desktop only codepath
- Must have git-for-windows installed
- Confirm that Terminal detects git-bash by default and loads it
- Also double check Tools / Shell (should launch same type of shell as selected for terminal)
- The bug repros only if you install Git for Windows AND …
> Fix coexistence of git for windows and rtools4

- src/cpp/r/RExec.cpp
- src/cpp/session/modules/SessionRTests.cpp
This PR fixes an issue where a failed invocation of `R_tryEval()` could return null pointers on failure.
This is likely the root cause of the crash that was fixed here:
https://github.com/rstudio/rstudio/commit/6572d9c46d97b5f4c4389ec2ec8ad0493c045c6b
and is also likely the underlying cause of some Data Viewer crashes we had in the past.
I think the invariant we should satisfy here is:
1. On success, we set a `SEXP` output argument;
2. On error, we don't touch the output result.
Here's another example where we use this sort of pattern:
https://github.com/rstudio/rstudio/blob/cc35e89f4eba237c7fc00ff100ee97a57cf4faee/src/cpp/session/modules/environment/SessionEnvironment.cpp#L246-L250
Fortunately, we do seem to check for null pointers anywhere that result value is used, but IMHO it'd be …
> avoid setting null pointer on R_tryEval error

- src/gwt/src/org/rstudio/core/client/ClassIds.java
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
- src/gwt/src/org/rstudio/core/client/theme/MinimizedWindowFrame.java
- src/gwt/src/org/rstudio/core/client/theme/WindowFrame.java
- src/gwt/src/org/rstudio/core/client/theme/WindowFrameButton.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/DocumentOutlineWidget.java
Fixes #6817
You can now discover via Tools / Diagnostics / Show DOM Elements (and thus highlight) the overall source panel, the min/max buttons within the source panel, and the outline, using class-based CSS selectors. For example:
```R
rstudioapi::highlightUi(
list(
list(query = ".rstudio_doc_outline_container", parent = 0L),
list(query = ".rstudio_source_panel", parent = 0L),
list(query = ".rstudio_panel_min_btn_source", parent = 0L)
)
)
```
Added the `ClassIds.java` file, which conceptually parallels the existing `ElementIds.java` as the place to define unique and stable DOM class names for elements.
Using classes allows elements that can have multiple instances, including most UI in the source editor (because you can open multiple documents), to have the same selector, and by …
> Add unique rstudio_foo classes to some source panel elements

- dependencies/common/install-qt.sh
- dependencies/linux/install-qt-linux
The Qt 5.12.8 release folders have two versions of the libraries; a pre-release version and the correct version. The installation script used in our Dockerfiles is pulling in the wrong one and it doesn't have the glibc Chromium fix that is the whole reason we're switching to this version!
Also added qtimageformats component as its absence in Docker build images cause 4 image filter files not to be installed with RStudio that were included when building against a Qt SDK installed via online installer. Don't know if this matters in any way but just trying to reduce all differences between known-good local builds and "official" builds.
Fixes #6782
Will also be ported to master (1.4).
> Install correct Qt libs on Linux

- src/gwt/src/org/rstudio/studio/client/common/spelling/domain_specific_words.csv
Added a set of common statistical terms to RStudio spellchecker.
It'd be a treat for these to be automatically in there.
> Add common statistics terminology to spell checker

- src/cpp/session/modules/SessionFind.cpp
- src/cpp/session/modules/SessionFind.hpp
- src/cpp/session/modules/SessionFindTests.cpp
Fixes #6819
This PR updates the global find and replace code to be fully functional across different encodings and adds additional tests so that this issue will not repeat itself (I plan on adding more but want to get this looked at for 1.3). Replaces in certain languages were only working as regular expression replaces and even then the green highlight wasn't displaying properly. They can now be performed as literal replaces across encodings already supported by RStudio, and the highlights will properly match the outcome.
I coded this against v1.3-patch so want to merge there first, but believe this should also go into v1.3.
> Fix issue with global replace

- src/gwt/src/org/rstudio/core/client/patch/SubstringDiff.java
This PR fixes an issue where spurious diffs could be emitted for documents that haven't changed. The issue with spurious diffs is caused by the adjustment done for UTF-8 characters here:
https://github.com/rstudio/rstudio/blob/42f759ccd4adb0c74550e47f154f7983088017db/src/gwt/src/org/rstudio/core/client/patch/SubstringDiff.java#L77-L95
In particular, if the two strings are identical (or the original string is a subset of the new string), then the `head` index will point at the end of the original string. When we index that, we get `undefined`, which compares improperly here:
```
if (ch < 128 || ch >= 192)
break;
```
This PR fixes that issue, and also adds a precautionary check for empty diffs before UTF-8 adjustment is done.
Closes https://github.com/rstudio/rstudio/issues/6846.
> defend against 'undefined' ch at boundary of string

- NEWS-1.3-patch.md
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/www/docs/keyboard.htm
- added Ctrl+` in addition to existing shortcut
- leaving existing shortcuts because some keyboards (e.g. Italian) don't have a backtick key
- changed shortcut for showing request log to Ctrl+Alt+`
- Fixes #6850
> add additional keyboard shortcut for Focus Console Output command

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/history/History.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/history/HistoryTab.java
- Remove command whose sole purpose (currently) is to display a modal dialog saying "onSearchHistory"
- Noticed while playing with new command palette feature (in a branch)
> remove unimplemented Search History command entry

- src/cpp/session/SessionMain.cpp
- src/cpp/session/include/session/projects/SessionProjects.hpp
- src/cpp/session/projects/SessionProjectContext.cpp
- src/cpp/session/projects/SessionProjectFirstRun.cpp
- src/cpp/session/projects/SessionProjectFirstRun.hpp
- src/cpp/session/projects/SessionProjects.cpp
First project template just needed code similar to what exists in workspaces.
Default open docs were broken because the scratch path is incorrect during `ProjectContext::startup` and is later correct during `ProjectContext::initialize`.
Fixes #6865
Fixes https://github.com/rstudio/rstudio-pro/issues/1668
> Fix default open docs and first project template.

- src/gwt/src/org/rstudio/core/client/command/AppCommand.java
- src/gwt/src/org/rstudio/studio/client/application/ui/AppCommandPaletteEntry.java
- src/gwt/src/org/rstudio/studio/client/application/ui/CommandPalette.java
- src/gwt/src/org/rstudio/studio/client/application/ui/CommandPaletteEntry.java
- src/gwt/src/org/rstudio/studio/client/application/ui/CommandPaletteEntry.ui.xml
- src/gwt/src/org/rstudio/studio/client/application/ui/RAddinCommandPaletteEntry.java
This change makes two improvements to the command palette:
- It now is symmetric with menus, which means it includes disabled commands ("greyed out") but hides invisible commands. It is debatable how much value a disabled command adds to the palette, but arguably it's good for discovery and helps you know what's possible (plus if you are looking for a command that's disabled it helps you not feel crazy. It was there an hour ago!). 
- Commands with no handlers are now treated as disabled. Technically speaking it's bad for a command to be visible and enabled but have no handlers (which is why this case is a debug assertion), but it is possible for the palette to deal with this gracefully, so we do. 
Fixes https://github.com/rstudio/rstudio/issues/6874.
> Improve command palette UX for disabled commands

- src/gwt/src/org/rstudio/core/client/widget/BannerWidget.java
- small tweak to use semantic HTML for banner instead of applying role to the div
- prompted by conversation in #6863 but doesn't directly address that issue
- the banner is the RStudio logo in upper-left of IDE; on open source is doesn't have any interactive behavior and will generally be ignored by screen readers, on Pro it contains a link back to the RStudio Server Pro home page
> use html5 header element instead of role=banner

- src/gwt/src/org/rstudio/studio/client/workbench/views/history/view/HistoryTable.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/diff/LineTableView.java
This applies the the user-selected font to a couple of places I missed in the initial implementation of editor fonts for RStudio Server (https://github.com/rstudio/rstudio/pull/6592).
> Apply themed font to history and VCS panes

- src/cpp/session/modules/SessionConfigFile.cpp
This change fixes an issue that arises when there's a global configuration JSON file but no accompanying user configuration JSON file. When this is the case, an attempt is made to merge the global JSON file with nothing, which goes about as well as you'd expect.
Fixes https://github.com/rstudio/rstudio/issues/6870.
> Use system config alone when user config is missing

- dependencies/osx/install-dependencies-osx
- src/cpp/rstudio-tests.in
Tests now relying on timeout command, which isn't on macOS. Use gtimeout from brew coreutils, instead
Fixes #6888
> fix cpp unit tests on macos

- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/tests/testthat/test-environment.R
This change works around a bug in R in which `deparse()` returns an incorrect copy of a function when it uses source references and the function contains backslashes. This bug has been reported upstream to R. 
https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17800
The workaround is to read the source references from the function directly, if they are present, rather than going through `deparse()`. 
Fixes https://github.com/rstudio/rstudio/issues/6854 and will be backported to 1.3-patch.
> Work around R bug in function deparse

- src/gwt/src/org/rstudio/core/client/command/EditorCommandManager.java
Fixes an issue where some GWT components depending on Ace could fail to initialize due to their attempt to run before Ace itself had been loaded.
This is a somewhat hacky fix -- a more appropriate fix, I think, would be to eschew the use of the Ace loaders altogether and instead just include Ace (+ our other polyfills) into a single `.js` bundle that we load on startup. However, I wanted to get something in quickly to at least fix builds (+ releases!)
Closes https://github.com/rstudio/rstudio/issues/6913.
> ensure Ace loaded before initializing command manager

- NEWS-1.3-patch.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteApplication.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java
- Additional research and usage testing by @jooyoungseo has confirmed we should always set this, and there is no reason to present this (extremely hard to explain) option to screen reader users.
- Very safe fix, removes a checkbox from Accessibility options pane, and always sets a role that was previously conditional
- Fixes #6863
> always set role=application on entire page and remove user option

- NEWS-1.3-patch.md
- src/cpp/core/include/core/http/AsyncClient.hpp
- src/cpp/core/include/core/http/LocalStreamAsyncClient.hpp
- src/cpp/core/include/core/http/NamedPipeAsyncClient.hpp
- src/cpp/core/include/core/http/TcpIpAsyncClient.hpp
- src/cpp/core/include/core/http/TcpIpAsyncClientSsl.hpp
Fixes https://github.com/rstudio/rstudio-pro/issues/1681
> Stamp a default host header on outgoing connections to make them HTTP compliant

- src/cpp/session/modules/SessionRmdNotebook.R
Closes https://github.com/rstudio/rstudio/issues/6932.
Candidate for v1.3-patch backport as the warning is emitted any time an R Notebook file containing image outputs is saved.
> ignore .snapshot files when creating notebook

- src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
Currently, the Enter key clicks the default button in web dialogs (which can be different than the button with keyboard focus). This matches behavior of MacOS desktop dialogs, and (I think) dialogs in Windows many versions ago, but not current Windows desktop apps and not web applications, where enter or spacebar clicks the focused button even in a dialog with a specified default button.
Change allows buttons in RStudio web dialogs to handle the enter key instead letting the dialog do it. The "default" behavior still kicks in when focus is on other controls, but buttons are now clickable with spacebar or enter key.
Note this also matches aria recommended keyboard handling for buttons, too.
Fixes #6928
> allow enter key to click active button in web dialogs

- src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java
- Work around an issue with JAWS
- Fixes #6884
- Note to QA: the reported issue was only reproducing part of the time for me, and I could not isolate why behavior varied, but with this fix I haven't been able to reproduce
> set document role on focusable console output spans

- NEWS-1.3-patch.md
- src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java
- Fixes #6963
- Update 1.3-patch news with this change and a prior one I forgot to add
> fix inverted logic for enabling/disabling warning bar announcements

- src/gwt/src/org/rstudio/core/client/widget/InfoBar.java
- src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java
- src/gwt/src/org/rstudio/studio/client/application/ui/WarningBar.java
- Fixes #6965
- Warningbar was already doing this so applied same stragegy to infobar (plus moved the highly distasteful timer length into a shared constant)
- Shortened delay from 1.5 to 1 second, still plenty of time for this to work in my testing
> pause a bit before updating infobar status text so JAWS sees the change

- NEWS-1.3-patch.md
- src/cpp/core/include/core/r_util/RVersionsPosix.hpp
Setting it empty will generally break the default system-wide setting in `/etc/R/Renviron`.
Fixes #6982.
> Only set R_LIBS_SITE if it is not empty

- src/cpp/session/modules/SessionTests.R
- src/cpp/session/modules/build/SessionBuild.cpp
The shinytest has made another change to where it stores tests, so we need to adapt the IDE to the change. Fixes https://github.com/rstudio/rstudio/issues/6960.
Will be backported to 1.3-patch.
> Update shinytest folder location

- src/cpp/core/include/core/r_util/RTokenizer.hpp
- src/cpp/core/r_util/RTokenizer.cpp
- src/cpp/core/r_util/RTokenizerTests.cpp
Part of https://github.com/rstudio/rstudio/issues/6788.
Note that this only updates the backend tokenizer, not the front-end tokenizer. This implies that while code won't be "colored" directly in the Ace editor instance, the diagnostics should nonetheless be correct.
Note: R's raw string literals are described within `?Quotes`. Here's an example:
```
r"---(abc)---"
```
R's raw string literals basically have the following format:
- Can start with `r` or `R`,
- Can be quoted via `'` or `"`,
- Can have an optional number of hyphens,
- Can have an opening bracket `(`, `[` or `{`,
- Raw string literal text,
- Closing complement for opening bracket,
- Same number of hyphens,
- Matching closing quote.
cc: @adamconroy, in case this is relevant for the front-end tokenizer.
> handle raw strings in backend tokenizer

- src/gwt/src/org/rstudio/core/client/ClassIds.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextToolbar.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextUi.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkOutputUi.java
Closes #6897 
This feature standardizes the logic for assigning chunks and their pieces class names that can easily be used by the API. It adds `rstudio_` to the front of each class name so that the names are available when using the `Show DOM Elements` feature. 
The class names are as follows:
Chunks are assigned `rstudio_chunk` or `rstudio_chunk_<name>` where name is the name assigned in the editor. For example ` ```{r plot} ` is assigned `rstudio_chunk_plot`.
Chunk output: `rstudio_chunk_output` or `rstudio_chunk_output_<name>`
Chunk modify button: `rstudio_modify_chunk`
Run chunk button: `rstudio_run_chunk`
Preview chunk button: `rstudio_preview_chunk`
> Standardize chunk class names

- src/gwt/panmirror/src/editor/src/api/event-types.ts
- src/gwt/panmirror/src/editor/src/api/events.ts
- src/gwt/panmirror/src/editor/src/editor/editor.ts
- src/gwt/panmirror/src/editor/src/marks/math/math-preview.ts
- src/gwt/panmirror/src/editor/src/nodes/image/image-view.ts
- src/gwt/panmirror/src/editor/src/polyfill/custom-event.ts
- src/gwt/panmirror/src/editor/src/polyfill/index.ts
Modify event system to allow events to (optionally) have additional
data attached. The definitions of the different types of events are
now in event-types.ts; see DispatchEvent for an example of an event
type that needs additional data (a Transaction object in this case).
> Refactor editor events

- src/cpp/core/LogOptions.cpp
This is done via via environment variable `RS_LOG_CONF_FILE`.
Closes #7016
> Make /etc/rstudio/logging.conf file configurable

- dependencies/linux/install-dependencies-focal
Tested on a clean focal machine. After running was able to build and install RStudio Server (open source).
Side note, I did this on an Ubuntu 20 machine in WSL2. Worked nicely.
> create dependency script for Ubuntu 20 (focal)

- src/cpp/CMakeLists.txt
- src/cpp/core/system/PosixChildProcessTracker.cpp
- src/cpp/core/system/PosixOutputCapture.cpp
- src/cpp/core/system/PosixSystem.cpp
Boost 1.73 is about to land in Fedora rawhide, and we are rebuilding packages, including RStudio, with this new version. Placeholders were removed from the global namespace in Boost 1.73 to avoid clashes with `std::placeholders`. This patch retains the old behaviour, but note that this is deprecated.
* enable BOOST_BIND_GLOBAL_PLACEHOLDERS to retain placeholders in the global namespace
* add some missing includes of <boost/bind.hpp>
> add support for boost 1.73

- src/gwt/panmirror/src/editor/src/behaviors/insert_symbol/insert_symbol-grid.tsx
When the component unmounts, cancel the preview timer. This fixes:
which is caused by the timer calling back when the component has been closed (reproduces by mousing over the grid, then closing the popup immediately).
> Correctly cancel the preview timer

- NEWS-1.3.md
- src/gwt/src/org/rstudio/core/client/widget/MiniPopupPanel.java
Fixes #7045
- Regression introduced via "add API for highlighting arbitrary UI in RStudio" #5867
- eager singleton causing a hidden MiniPopupPanel to be created at startup and that class had a quirk where it would intercept the first ESC keypress and swallow it
- fix is to only attached its key previewer when the panel has been displayed, and remove it when hidden (following existing pattern for drag handler)
> fix first ESC key press being ignored

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/www/docs/keyboard.htm
- shortcut for "Move Focus to Terminal" is now Alt+Shift+M
- shortcut for activating Tools menu on Server is now Alt+Shift+T on Windows/Linux, Ctrl+Alt+T on Mac
- shortcut for "Save All Source Docs" no longer supports Ctrl+Alt+S variation on Mac, only Command+Alt+S; it previously supported both but has always been shown as Command+Alt+S in menu and keyboard help
- shortcut for activating Session menu on Server is now Alt+Shift+S on Windows/Linux, Ctrl+Alt+S on Mac
- added commands for focusing Terminal, Console, Source pane, and Help pane to the Accessibility / Focus submenu
- Fixes #6929
- Fixes #6924
> accessibility improvements for main menu shortcut keys

- src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/spelling/CheckSpelling.java
We use Typo.js for even non-realtime spellchecking now but we were trying to over-optimize loading the dictionaries and an edge case was missed.
Fixes #7057
Fixes #7018
I also fixed non-realtime checking working with custom dictionaries so those will be synced.
> Dictionary check error

- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/tests/testthat/test-pkg-deps.R
The logic which extracts the YAML header to find R package dependencies in R Markdown files is currently very naive, and can be fooled by `---` ... `---` anywhere in the document (@jjallaire noted this happens easily with HTML comments). 
The fix is to use R Markdown's own YAML partitioner instead as suggested in #6997.
Fixes https://github.com/rstudio/rstudio/issues/6997.
> Ensure HTML comments don't get treated like YAML

- src/cpp/session/resources/pagedtable/pagedtable.css
- src/cpp/session/resources/pagedtable/pagedtable.js
This change fixes an issue in which the new header for paged tables (which shows grouping information; see https://github.com/rstudio/rstudio/pull/6688) can be duplicated when paging through columns in wide datasets.
The fix is to take this metadata out of the table header (which has a somewhat complicated re-rendering and appending situation going on) and to place it in a separate section above the table instead.
Fixes https://github.com/rstudio/rstudio/issues/7048.
> Fix double-rendering of paged table header

- src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogBase.java
- src/gwt/src/org/rstudio/studio/client/projects/Projects.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPreferencesDialog.css
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPreferencesDialog.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPreferencesDialogResources.java
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSAccountConnector.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.css
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialogResources.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/OptionsLoader.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
- Fixes #6847
- General mechanism for global options or project options dialogs to display a single-pane by hiding section chooser
- Currently only used for Help / Accessibility / Accessibility Options entry-point
> enable options dialog to show a single preference pane

- src/gwt/src/org/rstudio/studio/client/common/mathjax/display/MathJaxPopupPanel.css
- src/gwt/src/org/rstudio/studio/client/common/mathjax/display/MathJaxPopupPanel.java
This was likely needed for QtWebKit but seems unnecessary for QWebEngine
@kevinushey Two other small things I noticed which you may want to look at:
1. The background color of the popup is unthemed (it's always white). Not sure if this was intentional though?
2. There is now a rectangular border around the math which I didn't see previously. This to me doesn't look ideal.
> don't increase size of mathjax popup font on windows

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetChunks.java
Text editing targets were being marked as initialized too early and therefore the buttons to manage the chunks were not appearing until the toolbar was refreshed. This PR sets the initialized variable properly.
> Fix bug where rmd files were not properly initialized

- src/cpp/session/modules/SessionRMarkdown.R
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
Closes https://github.com/rstudio/rstudio/issues/6945.
This issue occurs because of the way we end up munging the output file path here:
https://github.com/rstudio/rstudio/blob/275964ec5f5c338daf848168e161922fdd14f627/src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp#L1178-L1179
Because this is occurring, the right fix here is to point the output file path to the website root, e.g. as `file.path(websiteDir, "index.html")`. Which is awkward, since that path is later munged to point at the "correct" currently knitted file, which is _not_ at the root of the website.
tl;dr: There's something going on here that I don't quite understand, so this PR bears some extra scrutiny. There is probably a more appropriate fix.
> return path to website index, even when output is not the index

- src/cpp/core/libclang/LibClang.cpp
Closes https://github.com/rstudio/rstudio/issues/6977.
In theory, we allow the use of an optional installation of LLVM, but in practice that seems to never work (and orchestration of include paths etc. to make that work and compatible with what R does isn't worth the effort when users will normally have macOS command line tools installed anyhow).
Given that we're now always binding to the macOS version of libclang, setting up the extra system include paths seems to be no longer necessary.
Candidate for v1.3 backport.
> require system libclang on macOS

- src/cpp/core/include/core/http/AsyncConnectionImpl.hpp
- src/cpp/core/include/core/http/SocketUtils.hpp
In the development terminal I frequently see EPROTOTYPE errors logged:
This of course makes it much more difficult to see if there are actual errors or problems occurring. 
This is already partially addressed from this particular call site by suppressing error logging if `http::isConnectionTerminatedError()` returns true: https://github.com/rstudio/rstudio/blob/master/src/cpp/core/include/core/http/AsyncConnectionImpl.hpp#L518
This function in turn ignores a wide variety of errors: https://github.com/rstudio/rstudio/blob/3fdda38e9a78a984a25c44e1672cf0869fad19cd/src/cpp/core/include/core/http/SocketUtils.hpp#L66-L84
This PR adds a new helper function to suppress EPROTOTYPE errors from just the call site that I am seeing the extra logging occur at. It is purposely scoped that narrowly b/c I …
> Don't log wrong_protocol_type (EPROTOTYPE) when handling write errors

- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
- src/gwt/src/org/rstudio/core/client/widget/NumericTextBox.java
- src/gwt/src/org/rstudio/core/client/widget/SelectWidget.java
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditAttrWidget.java
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditAttrWidget.ui.xml
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditCodeBlockDialog.java
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditImageDialog.java
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditLinkDialog.java
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditListDialog.java
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditListDialog.ui.xml
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditRawDialog.java
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditRawDialog.ui.xml
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorHRefSelect.java
- Fixes #7080
- Fixes #7081
- Fixes #7082
- Fixes #7083
- Fixes #7084
- Fixes #7085
Details:
- make sure controls have properly associated labels
- use `focusInitialControl` instead of `focusFirstControl` to prevent breaking Tab order
- refresh dialog tab focus order when switching Tabs
- some controls have multiple labels which requires a slightly different approach not previously used in the IDE codbase (aria-labelledby with multiple IDs).
- annotate extended description in Format List dialog so additional information about Pandoc support for custom number delimiters in HTML is read as part of the control
> fix various accessibility issues in Visual Editor dialogs

- NOTICE
Closes https://github.com/rstudio/rstudio/issues/7102.
Note that the current Ace license lives here:
https://github.com/ajaxorg/ace/blob/master/LICENSE
and only marks the date from 2010.
Also not sure if we should mark this license for Ace explicitly or just list the contents of the BSD-3-Clause license.
> update Ace Editor license

- src/gwt/panmirror/src/editor/src/marks/math/math-transaction.ts
- src/gwt/panmirror/src/editor/src/marks/math/math.ts
This is a potential fix for #7107 
The proposal is to not be so finicky about removing display math marks when the user edits them directly. This allows them to easily repair the mark after inadvertently removing a delimiter:
Note that there is some feedback that the mark is broken b/c the equation preview now thinks that it's an inline mark.
If the mark continues to be broken when the user saves (or switches to source view) then it will in fact no longer be a display math equation. This is consistent w/ the behavior of source mode (where removing a dollar sign from a display math delimiter causes pandoc to no longer render it as math).
> don't break display math marks on delimiter edit (wait until save)

- src/cpp/session/SessionConsoleProcess.cpp
- src/cpp/session/SessionConsoleProcessInfoTests.cpp
- src/cpp/session/include/session/SessionConsoleProcessInfo.hpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
- Fixes #7112
The Twisted Tale:
When I fixed how we launch Git-Bash in #6828 that gave us one "bash.exe" launching a second "bash.exe" as a child process (which was intentional). This is then caught by the subprocess-detection and flagged as always busy. Previously, git-bash was a single process.
The crux of this PR is that we never intended to support subprocess detection for Terminals on Windows Desktop, so fully disabling it. It's never been possible for git-bash or WSL because commands run in those environments aren't actually Win32 processes, so can't be detected. It does work (somewhat) on Command Prompt or PowerShell, but the intention was to simply be consistent and not support it. Now that is actually the case.
I've made this change in the safest way I can think of, and it is …
> Fix perpetually busy Git-Bash terminal on Windows

- src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourcePane.java
In RStudio 1.3, we made a change (#6056) which prevents the Source tabs from stealing input focus. This is largely an improvement but, but it turns out that sometimes we _want_ this behavior; in particular when creating new files we want to grab focus and send it to the new file. 
Fixes https://github.com/rstudio/rstudio/issues/7103.
> Allow focus stealing for new tabs

- src/gwt/src/org/rstudio/studio/client/common/mirrors/model/CRANMirror.java
This change addresses an issue in which a missing `secondary` value for the CRAN repros value could keep the Options dialog from opening due to a JavaScript exception. This is rare (in fact we just have one user report of it occurring) and we don't know how the state in which it arises, but it's easy enough to tolerate. 
Fixes https://github.com/rstudio/rstudio/issues/7116.
> Tolerate missing secondary repos in user prefs

- src/cpp/r/RUtil.cpp
- src/cpp/r/include/r/RUtil.hpp
- src/cpp/session/SessionModuleContext.cpp
This change refines a change introduced in https://github.com/rstudio/rstudio/pull/6804. That change added a workaround for a bug in R, which has since been fixed. Unfortunately the workaround also had a couple of side effects (see related bugs).
The fix is to only use the workaround with the exact version of R that has the bug.
Fixes https://github.com/rstudio/rstudio/issues/6893
Fixes https://github.com/rstudio/rstudio/issues/7046
> Use help server unless R is exactly 4.0.0

- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/SourceDocument.java
This change fixes an issue in which modifying the YAML header to change `html_document` to/from `html_notebook` in an R Markdown document doesn't trigger the right updates to the toolbar. 
The issue is that we no longer rebuild the toolbars on every file save (https://github.com/rstudio/rstudio/pull/6442). We used to do this but in addition to being wasteful it also made autosave very unpleasant to use. 
We _do_ rebuild the toolbars when the extended type changes, though, so the fix is to give Notebooks their own extended type. This causes us to rebuild the toolbars when a document is switched into or out of Notebook mode. 
Fixes https://github.com/rstudio/rstudio/issues/6643.
> Ensure toolbar updates when changing YAML to notebook

- src/gwt/src/org/rstudio/studio/client/workbench/ui/MainSplitPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Commands utilizing the Source Panel and Editing Target are now only enabled on one column at a time. These commands most commonly appear under the `Code` menu list. Whenever the active editor changes, we iterate over the commands for each column and enable/disable them as needed.
This PR also fixes an issue where the panel state was not being saved properly between start ups. It also includes some code clean up.
> Target active column with commands

- src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java
I had forgotten that I changed the manual spellchecker to also use Typo.js when I had to blacklist some dictionaries and that broke manual spellchecking for those dictionaries entirely. Bringing back the old CPP Hunspell until we can fix 6116.
Fixes #7018
> reenable legacy spellchecker due to blacklisted dictionaries

- src/gwt/src/org/rstudio/core/client/prefs/PreferencesDialogPaneBase.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
This change is a workaround for a bug in QtWebEngine in which the iframe that hosts the theme preview in the Appearances pane fails to paint when switching tabs.
The fix is to force a repaint by changing the z-index of the iframe when the tab switches. This has no visible impact but is enough of a style change to trigger a repaint. We must do this every time the tab becomes visible since Qt will continue to fail to repaint the region again if we don't. 
Fixes https://github.com/rstudio/rstudio/issues/6268.
> Jiggle z-index of theme preview to force paint

- src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/spelling/CheckSpelling.java
Use the async suggestions callback when Typo.js isn't/can't be loaded. Crossing fingers that this is the final thorn for dotting the i's on all the blacklisting fallout.
Fixes #7018 (finally)
> Legacy spellcheck suggestions

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
Certain file types (including RMarkdown) would not force the source pane open when created or opened. This PR ensures the source pane is visible.
> Fix issue preventing some documents from being visible when opened

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetRMarkdownHelper.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Change https://github.com/rstudio/rstudio/pull/7051 removed the generic `rmarkdown` extended type and replaced it with two more specific types. However, it missed a couple of instances of the old type that were present in the code as hardcoded strings (didn't use the `XT_RMARKDOWN` constant). 
The fix is to use the appropriate `XT_RMARKDOWN` constant. 
Fixes https://github.com/rstudio/rstudio/issues/7166.
> remove remaining hardcoded Rmd extended types

- src/gwt/src/org/rstudio/core/client/command/KeyCombination.java
- src/gwt/src/org/rstudio/core/client/command/KeyboardHelper.java
> normalize hyphen keycode used by Firefox

- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
Fixes #7186
Fixes a bug where the placeholder hidden tabset pane was added to `PaneManager panes_` causing its null variables to be accessed and throw an exception.
> Remove the hidden tab set from the panes list

- package/osx/entitlements.plist
Presumptive fix to #5148. I haven't been able to properly test this since I haven't been able to reproduce the issue.
More information on this entitlement can be found here: https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_automation_apple-events
> Add Apple Event Entitlement to enable knitting to word

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/PinnedLineWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetChunks.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetScopeHelper.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkOutputUi.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
This PR makes two changes:
1. When updating chunk toolbars, we use the most recent set of edits in the editor to decide which toolbars need to be updated. This is necessary since a document might not necessarily be mutated at the cursor position -- for example, when inserting text via the `rstudioapi` package.
2. We no longer defer adding line widgets according to the next Ace render. It looks like this was responsible for some of the challenging-to-reproduce behaviors around chunk toolbars occasionally failing to show up, or showing up "slowly", or even in some cases sticking around after a chunk was deleted.
Closes https://github.com/rstudio/rstudio/issues/7067.
Note for (2): this behavior was added a while ago, as part of efforts to eliminate "floating" Ace line widgets. However, I …
> improve handling of chunk toolbars in modified documents

- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/modules/SessionHelp.cpp
Closes https://github.com/rstudio/rstudio/issues/7152.
IIRC, the main issue here was that the version check in SessionHelp.cpp wasn't updated when we changed this code to check for an exact version.
I also updated the code checking whether we're using the R help server for requests to just use a lazily-initialized static boolean rather than a boost optional as it's (IMHO) cleaner.
> tweaks for request handling on Windows w/help server

- NEWS-1.3.md
- src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenu.java
- Fixes #7215
- Regression caused by #6190
As @kevinushey noted, code was making the menu invisible instead of actually invoking hide, putting it in an unsupported state and preventing it from working on future attempts to display it. Fix is simply to hide() it; also no need to check if it is visible before doing this (the handler is only hooked up while the menu is visible).
Test wide variety of drop-downs in main toolbar, pane toolbars, and in other windows (popup out source editors, git, etc). Focus on closing the drop-downs by executing commands with keyboard shortcuts, then re-opening the popup and make sure it displays (again) and functions correctly (can invoke commands on the menu, or close it via Esc or clicking outside the menu).
> fix dropdowns that don't repopulate when closed via keyboard shortcut

- src/cpp/core/include/core/system/Environment.hpp
- src/cpp/core/libclang/SourceIndex.cpp
Closes https://github.com/rstudio/rstudio/issues/6977.
> set SDKROOT envvar so libclang can find system headers

- src/cpp/session/modules/SessionRmdNotebook.R
This PR again removes some unneeded code that was attempting to read files that were otherwise unused in the Notebook generating process. Was unfortunately missed as part of https://github.com/rstudio/rstudio/issues/6932.
For context, I think I originally read in almost all of the files within the chunk cache folder, under the assumption that I'd need to sue them directly to render the final document. However, these dependencies get automatically picked up and used when we render HTML, and that's handled by `rmarkdown` + `htmlwidgets`.
> don't read un-needed library files

- src/cpp/server/ServerSessionManager.cpp
- src/cpp/session/SessionMain.cpp
The verify installation command was producing some directory creation errors because the server user that the session runs as in this case does not usually have a home directory. Fixed this by specifying a tmp dir for verify installation home directory. 
Also fixed a verify hang in pro by not doing first project template copying if in verify mode - otherwise, a project would be set, and project sharing initialization would run which would cause a hang as it connects back to rserver, which is not listening in verify mode.
Fixes #7221
> Fix verify installation errors

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetSource.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java
This PR fixes a somewhat long-standing issue, where calling `getDefaultNamePrefix()` could cause the instantiation of a separate, standalone EditingTarget; separate from the one actually used. See https://github.com/rstudio/rstudio/issues/7066#issuecomment-650363848 for extra investigation.
If I understand correctly, the assumption we were making was that, for a single `Provider<Foo> foo` instance, calling `foo.get()` would return a reference to the _same_ `Foo` instance. This appears to not be the case; each invocation of `get()` may return a reference to a separate instance entirely.
We resolve this issue by de-coupling name provision from the editing target source class. Instead, we create a simple interface that takes an EditingTarget, and returns a default name prefix given that …
> avoid accidental duplication of editing target impls

- src/gwt/src/org/rstudio/studio/client/dataviewer/DataTable.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTargetWidget.java
I'm not exactly sure what the cause is, but it seems like GWT's JSNI gets upset if you try to use a GWT Integer to "box" a JavaScript number (even though this should've worked in the past).
Also switches to using GWT's type inference, rather than just plain Java objects.
Stumbled upon this while looking at https://github.com/rstudio/rstudio/issues/7066 (but doesn't fix that issue)
> use Double rather than Integer to avoid GWT cast issues

- src/cpp/shared_core/FilePath.cpp
- src/gwt/src/org/rstudio/core/client/files/FileSystemItem.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ImagePreviewer.java
This change adds very basic support for WebP images in R Markdown. WebP images are now correctly identified as images in the Files pane, and are displayed inline while editing R Markdown documents.
> Preview WebP images in R Markdown

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java
Fixes  #7066 
Really good find by Kevin noticing that onActivate isn't actually setting isActive_ on the DataEditingTarget. The DataViewer actually updates with this change. This is so trivial I think we should sneak it into Water Lily still.
> Set isActive in onActivate in DataEditingTarget

- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermDimensions.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermNative.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermOptions.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermTheme.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
- removed extra logging in terminal diagnostics dialog I had added while upgrading xterm.js last year (no real value to showing it)
- no longer checking XTermDimension for NaN (this was fixed in xterm.js a couple years ago; could track down the issue if anybody cares)
- still need to convert the `XTermNative` class but wanted to get first part in
> convert some xterm.js support code from jsni to jsinterop

- src/cpp/core/CrashHandler.cpp
Ensure that crash handler permissions file parent directory is automatically created if it doesn't already exist to help mitigate issue where users cannot get the prompt to go away. Closes #7243
> Speculative fix for persistent crash reporting dialog

- src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
The attached issue was partially fixed - buttoning up another place where `openWindow` does not work with RSP->RSP mode. See issue's first PR for more detail.
Closes https://github.com/rstudio/rstudio-pro/issues/1625
> Fix bug where you cannot open HTML file in browser in RDP->RSP session

- NEWS.md
- src/cpp/session/modules/SessionDataViewer.R
With this change, if a package author has defined a (well-behaved) format method for their particular object, we'll try and use it.
This PR also reformats this file to use our standard 3-space indent.
Closes #7239.
> use format method (when available) when formatting data viewer columns

- src/gwt/acesupport/acemode/r_code_model.js
- src/gwt/acesupport/acemode/utils.js
With the Ace tokenizer, rules that make use of line-specific metadata (via the "stack" parameters) can cause Ace to emit a temporary state `#tmp`:
https://github.com/ajaxorg/ace/blob/2ccda8c1ba350415de0e949abd50888abb6645fe/lib/ace/tokenizer.js#L354-L357
Normally, that temporary state is only resolved later, in response to `getLineTokens()`:
https://github.com/ajaxorg/ace/blob/2ccda8c1ba350415de0e949abd50888abb6645fe/lib/ace/tokenizer.js#L229-L237
It's not completely clear to me why this `#tmp` state is used; the only documentation I can see is the associated commit:
https://github.com/ajaxorg/ace/commit/7a3a84c8583d49f6acf5948ad6a386737fa7ee17
It _seems_ like it's some implicit way of indicating that state management is being done through the `stack` variable, as opposed to other …
> fix issue with Ace '#tmp' state from tokenizer

- src/cpp/r/RSexp.cpp
- src/cpp/r/include/r/RSexp.hpp
- src/cpp/r/session/RSearchPath.cpp
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.cpp
- src/cpp/session/modules/rmarkdown/NotebookQueueUnit.cpp
Closes https://github.com/rstudio/rstudio/issues/6254.
Note that this raises a somewhat larger issue. Normally, code in RStudio using `std::string` assumes that string is UTF-8 encoded. However, this isn't true for calls to `r::sexp::asString()`, which returns strings in the native encoding, which (e.g. on Windows) will correspond to whatever the active code page is.
This implies that there are a lot of spots in the codebase where we might want to consider switching from `asString()` to `asUtf8String()`, but such changes would need to be done carefully since some R APIs do require strings to be in the native encoding as opposed to UTF-8.
> ensure chunk output from alternate engines is UTF-8

- docker/jenkins/notarize-release.sh
About once a week we have to investigate a build failure on MacOS that turns out to be due to an intermittent notarization failure, which presents itself as a failure on Apple's side to locate a request UUID that it just told us it created 30 seconds ago. This change attempts to eliminate these failures by adding a retry step, under the presumption that the request UUID just isn't ready yet.
A concern here is that the request UUID will never in fact be ready in some cases (i.e. Apple just dropped it on the floor). We don't want the build to hang in this case, so this change also caps the time spent in notarization at an hour. 
Fixes https://github.com/rstudio/rstudio/issues/5693.
> Increase tolerance to notarization delays

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Fixes #7274 
The SwitchToDoc event handler needed to be moved from `Source` to `SourceColumnManager` and updated to select the tab on the active column.
This won't work perfectly with the additional source column code. That will be included in a different PR.
> Fix tab overflow selection

- docker/jenkins/Dockerfile.windows
- package/win32/make-install-win32.bat
- package/win32/make-package.bat
This PR changes our make program from `nmake` to `ninja` in our windows builds to allow use to compile multiple files in parallel. It also sets the Windows SDK version to ensure we're building with the desired SDK version (based on the Dockerfile).
> Parallelize Windows Builds

- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/dialog/SVNReviewPanel.ui.xml
Fixes #7254
Use consistent plurals in vcs dropdown for number of lines of context. I confirmed that the layout expands based on the content of the dropdown (temporarily put something really long in one of them to check).
Not an absolute slam-dunk, I mentioned in the issue that: 
> You could read "Context: 5 line" as shorthand for either "show a 5-line context" or "show 5 lines of context". In any case there's an inconsistency due to the "All lines" being there. :-)
> Fix consistency of context-lines dropdown plurals

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceAppCommand.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/PopoutDocEvent.java
Enable Changed and Visibility Changed events on `CommandSourceColumnToolbarButton` were being passed to the `AppCommand` handlers rather than their own handler causing buttons to appear when they shouldn't. Their visibility is now properly assigned.
> Fix toolbar buttons being set to visible when they shouldn't be

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceAppCommand.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
This PR adds some functionality #7305 missed when managing command icons across source columns. Specifically, it allows a button to not be synced with its command and the `SourceColumnManager`. 
`SourceAppCommand` now saves whether the button(s) for the command are visible or not so that the buttons can be properly set on attachment if the command was managed before the event handlers were added.
> Fix up toolbar buttons and commands

- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/test/org/rstudio/core/client/ConsoleOutputWriterTests.java
- Fixes #7278
Another edge case with ANSI codes and rewriting lines via `\r`.
> Fix VirtualConsole handling of specific line rewriting boundary case

- NEWS.md
- src/gwt/src/org/rstudio/core/client/dom/IFrameElementEx.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java
This is a drive-by fix for https://github.com/rstudio/rstudio/issues/6967. The bug is effectively that navigating in the Viewer pane causes the pop-out button to not work (it pops out the URL that initially loaded in the pane, not the one you're looking at). 
The reason we don't pop out the current URL is that the current URL has a bunch of goo on it that we don't want to include in the popped out URL (`&viewer_pane=1`, etc. etc). There are also circumstances where we can't read the current URL. 
So the fix is a little more subtle than just using the current URL. We now attempt to figure out whether you've navigated based on whether or not the current URL has changed from the original one. If it has, we show you the new URL instead of the one you were originally looking at.
Fixes …
> Pop out navigated URL if known

- src/cpp/rstudio-tests.bat.in
We used to expect a subdirectory that matched the build type for package builds on windows. With the change to Ninja, it's not being generated anymore. This PR removes the expectation for the subdir in run-tests.bat.in.
> Remove subdir from run-tests.bat

- src/cpp/.gitignore
- src/cpp/core/system/PosixFileScanner.cpp
- src/cpp/core/system/Win32FileScanner.cpp
- src/cpp/core/system/file_monitor/Win32FileMonitor.cpp
When RStudio is initialized with a project, it registers a file monitor for that project. This entails scanning the files used within that project recursively, which can be slow for projects with many files (e.g. RStudio itself).
When we try to stop the file monitor, we were previously forced to wait for an in-flight registration to complete (or for 3 seconds, after which we just detached the thread and continued trying to exit).
This PR instead allows us to eagerly clean up and delete the context when a stop is requested. In case any completion requests are made after the context has been removed, we just check to see if the operation was aborted before attempting to access the associated context.
It seems like a lot of care was put into making sure the completion handler is the one to …
> fix issue with file monitor taking long time to shut down

- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java
- Suggested by @daattali
- Tweak to fix for #7242, which said "Show focus rectangles"
- Better represents what this option does (i.e. when off, not **_all_** focus outlines are suppressed)
> Change focus rectangle option description to "Always show focus outlines"

- src/cpp/session/modules/SessionDiagnostics.cpp
Fixes a small code issue where we were constructing a `std::string` directly from a `std::wstring`, without properly converting it. Noticed the issue on Windows with the associated compiler warning.
> fix error in constructing string from wstring

- src/cpp/desktop/DesktopGwtCallback.cpp
Closes #7327.
Note: this also re-fixes #2476. It looks like this may have regressed as part of a Qt update? The documentation in https://doc.qt.io/qt-5/qfilesystemmodel.html#resolveSymlinks-prop states, surprisingly:
> This property holds whether the directory model should resolve symbolic links
> 
> This is only relevant on Windows.
> 
> By default, this property is true.
Whereas, no such caveat holds for the `DontResolveSymlinks` flag (https://doc.qt.io/qt-5/qfilesystemmodel.html#Option-enum).
Regardless, it seems like the right solution is to disable resolution of symlinks on non-Windows via the file dialog option.
> resolve shortcuts in file dialogs on Windows

- src/cpp/r/RExec.cpp
- src/cpp/r/include/r/RExec.hpp
- src/cpp/session/modules/SessionRParser.cpp
Closes https://github.com/rstudio/rstudio/issues/7372.
> suppress warnings during evaluation of code in r parser

- src/cpp/desktop/CMakeLists.txt
- src/cpp/desktop/launch.vs.json.in
- src/cpp/session/modules/SessionEnvironment.R
Closes https://github.com/rstudio/rstudio/issues/6877.
Finally, users will be able to view UTF-8 strings within the Environment pane on Windows. :-)
> avoid re-encoding character inputs for environment pane display

- src/cpp/r/R/Diagnostics.R
As some users, by convention, might use `_UID` and `_PWD` to indicate user IDs and passwords.
> redact UID, PWD from diagnostics

- src/cpp/session/modules/SessionLists.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/WorkbenchListManager.java
- Removed the long-obsolete addins_mru constant that was triggering client-side attempt to index a map using a non-existent key
- Also made the code more resilient so it logs an error instead of throwing an exception
- Fixes #7395
This exception also happens in 1.3, but don't know of any specific problems it causes, so targeting master/1.4.
> Fix Javascript exception on first-run related to obsolete addins_mru

- NEWS-1.3.md
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneConfig.java
- Fixes #7246, probably some other quirky problems with pane layouts not sticking or otherwise misbehaving
- this affects anything related to the pane layouts (console on left or right, moving tabs between quadrants, etc)
- try using RStudio 1.3 (pre-goldenrod) and making pane layout changes that don't work such as described in the issue
- then upgrade to 1.3 goldenrod, and see if changes now behave properly
- try variations with and without the presentations tab showing
- try moving the Tutorial tab to TabSet2 (from Pane Layout options dialog)
- Tutorial tab wasn't listed in default pane layout schema, causing it to be added to the end of TabSet1, which violates checks in PaneConfig and can prevent pane layout changes from sticking due to them resetting in the middle of some layout …
> Include Tutorial tab in default pane schema, autocorrect incorrect order

- NEWS-1.3.md
- src/cpp/core/system/PosixGroup.cpp
Fix bug where user group enumeration was not properly checking return code of `getgrouplist` to resize the buffer when needed. 
Fixes https://github.com/rstudio/rstudio-pro/issues/1796
> Properly resize buffer during group enumeration

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
This PR fixes an issue where we were attempting to select the last active source tab before we restored the source documents. It also persists the last active column's name so we can select the active tab on the correct column.
> Persist last active tab on start up

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/test/test-multiline-expr.R
This PR improves the heuristics used to find the extent of an R statement, via:
- Checking for lines that end with something like `) +`, and using the right bracket to motivate a search for the "start" of the associated expression;
- Performing a one-time check for the current line, to see if it matches the aforementioned state (only done once since we normally want to look at previous lines to see if they end with a binary operator / something that would require more input and hence attach to the current line)
Closes https://github.com/rstudio/rstudio/issues/6248.
Note: if we ever want to delve into this code again, I think we ought to just build a proper R parser in the client side that tracks source references, because this code is getting pretty funky...
> better handle certain usages of pipe operators

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunks.java
This change disables Ace's built in YAML completers for embedded Ace editors in visual mode, which are too aggressive in the YAML front matter in R Markdown docs.
> Disable completions in YAML frontmatter

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
The code previously attempted to retrieve the name of a source column before any columns had been created. This fixes that change.
> Prevent crash on startup

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceAppCommand.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetToolbar.java
This fix creates the `Source Navigate Forward` and `Source Navigate Back` buttons as traditional command toolbar buttons rather than source command buttons, because whether they are enabled or visible is the same across all columns. Previously we were attempting to enable/disable traditional buttons instead of column buttons so the buttons were not displayed at all. 
If people think it's for the best, I'm open to updating this so that the buttons only appear on the main source column.
This also fixes a terminology issue where `SourceAppCommand` had variables with the word visible instead of enabled and was basing whether to an enable a button on attachment off of the visibility.
> Fix issues with source navigation buttons

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Fixes #6649 
When a NewDocumentWithCodeEvent is fired, before opening the new document, check to make sure the handler is executing in the most recently active source window and only open a new document when this is true.
> Check Window ID in onNewDocumentWithCode

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Fixes this issue, in which "parentheses" doesn't match the casing of the other commands in the menu.
> Capitalize "Parentheses" for consistency

- NEWS.md
- src/cpp/r/R/Api.R
- src/cpp/r/R/Options.R
- src/cpp/r/R/Tools.R
- src/cpp/r/include/r/ROptions.hpp
- src/cpp/session/modules/SessionBuild.R
- src/cpp/session/modules/SessionPlumberViewer.R
- src/cpp/session/modules/SessionProfiler.R
- src/cpp/session/modules/SessionProfiler.cpp
- src/cpp/session/modules/SessionRParser.cpp
- src/cpp/session/modules/SessionReticulate.R
- src/cpp/session/modules/SessionShinyViewer.R
This PR fixes an issue where saving options, e.g. via:
```
ops <- options()
save(ops, file = tempfile())
```
would emit an R warning, typically of the form:
```
Warning in save(ops, file = tempfile()) :
'package:stats' may not be available when loading
```
This is caused by us placing helper functions within the R options list, which themselves inherit from the RStudio tools environment. Because that environment lives on the search path, it also "depends" on the environments which come after it, e.g. `package:stats`:
```
> search()
[1] ".GlobalEnv"        "tools:rstudio"     "package:stats"    
[4] "package:graphics"  "package:grDevices" "package:utils"    
[7] "package:datasets"  "local:rprofile"    "package:methods"  
[10] "Autoloads"         "package:base"    
```
There are three main …
> avoid warnings when saving R options

- src/cpp/session/modules/SessionSource.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/SaveFailedEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/DocUpdateSentinel.java
This PR tweaks the reporting of save and autosave errors.
When an autosave error occurs, a one-time dialog is shown indicating roughly that "something bad happened".
After this point, RStudio will no longer report subsequent autosave errors to the user.
Attempts to explicitly save files will still be reported, with a somewhat clearer error message:
This "An internal error occurred" message indicates that we were unable to retrieve the document from our source database. (not sure if we want to surface more information here?)
Note that this PR doesn't do anything to recover from this state; it just adjusts how this state is reported to the user.
Small bandaid for https://github.com/rstudio/rstudio/issues/7427.
> tweak reporting of autosave errors

- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
**Exactly** the sort of change I would have directly committed if I hadn't JUST argued that everything should be a PR...
> Fix source indentation, use StringUtil.equals instead of ==

- src/gwt/src/org/rstudio/core/client/layout/LogicalWindow.java
Fixes #7457 Removed a method added in #7408 that was not actually needed and was causing a null exception.
> Fix exception from creating a new Terminal menu

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Implements Shift + F6 to navigate focus to the previous pane. Previously we were using "Shift + F6" for `finishDebug`. I changed this to Shift + F7 as using F6 to navigate between panes is typically standard. 
This PR also fixes a few issues with source columns. Columns were not being properly synced between sessions and stored in a different order on refresh than they were originally added.
> Add command focusPreviousPane

- src/gwt/www/docs/keyboard.htm
This is the keyboard shortcut help shown when screen reader mode is enabled or you click the "Show all shortcuts" link in upper-right of regular keyboard shortcuts help pane.
Ideally we'd generate this automatically but this isn't going to get done in 1.4 so I occasionally update it.
> update static html keyboard shortcut help

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java
Closes #7441 
Several tab types in the Source panel did not handle focus and prevented focusNextPane from moving to those panels when they were active. This implements `focus()` for `ProfilerEditingTarget`, `UrlContentEditingTarget`, `DataEditingTarget`, and `ObjectExplorerEditingTarget`, with the ladder two inheriting from `UrlContentEditingTarget`.
> Implement focus() for missing editing targets

- NEWS.md
- src/gwt/src/org/rstudio/core/client/command/AppCommand.java
- src/gwt/src/org/rstudio/studio/client/RStudio.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
This change fixes a long-standing issue which created a number of quirky bugs. 
The symptom is effectively that certain actions which open windows in RStudio Desktop cause various commands and menu items to mysteriously disappear, never to return until RStudio is restarted. For example, running a Shiny app or viewing your Git diff can cause all of your recent files and projects to disappear.
See https://github.com/rstudio/rstudio/issues/3968, https://github.com/rstudio/rstudio/issues/4852, and https://github.com/rstudio/rstudio/issues/7126 for examples.
The underlying issue is that we have a global menu in desktop mode, but every window (including satellite windows) writes state to the global menu, in a sort of free-for-all that causes the global state to not really reflect any one …
> Don't propagate visible/enabled command state from satellites to main window commands

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Begins to address #7471 
This is a temporary failsafe to prevent the IDE from getting into a state where it tries to access a "phantom column" that is not visible to the user. This needs to be addressed more completely so that we don't have these types on invisible columns in the first place but this will prevent the IDE from essentially shutting down. 
`public SourceColumn getActive()` already existed within SourceColumnManager to return the active column or set the main column to active if there was no active column. I updated this to check the widget's presence as well and expanded the places where it's used.
> Prevent access to invisible columns

- src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
- src/gwt/src/org/rstudio/studio/client/workbench/codesearch/ui/CodeSearchDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
This PR fixes a couple issues when returning focus to the visual editor from a modal dialog (e.g. the fuzzy file finder dialog, opened via <kbd>Ctrl + .</kbd>).
1. Normally, cancelling (closing) a modal dialog will explicitly attempt to return focus to the last-focused element. However, this caused issues in the visual editor, as that focus attempt will cause the document to scroll back to the top of the document. To alleviate this, we now have the notion of custom "return focus handlers" -- if the element to be focused lives within a Source pane, rather than focusing it directly, we execute the `activateSource` command which should then ensure the proper machinery is run during focus.
2. In addition, "accepting" an entry from the fuzzy file finder normally implies a pending navigation …
> implement custom return focus behavior for Source pane elements

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Adjustment to #7476 which prevented access to phantom columns by refusing to access unattached columns. There are a few times we want to access columns _before_ they are attached, this PR adds an additional check before changing the active column to see if the main column itself has been attached. If not, it proceeds with the requested active column.
> Do not reset active column before start up

- src/cpp/r/R/Options.R
Fixes regression from https://github.com/rstudio/rstudio/commit/03287064cb4d50de4b71b10122a53a4727f02c69#diff-60f4e7f40cb9dcaeaa38ed192bf4b469R102-R105.
> add missing default argument for .rs.restartR

- NEWS.md
- rstudio.Rproj
- src/cpp/session/modules/SessionRUtil.R
- src/cpp/session/modules/SessionRenv.R
- src/cpp/tests/testthat/test-renv.R
This PR ensures that the current R repositories are propagated to the child process used to run `renv::init()`. This is necessary so that the right repositories are encoded in the newly-created lockfile.
This PR also adds a small bit of infrastructure to run R functions in child processes.
Closes https://github.com/rstudio/rstudio/issues/7136.
> propagate repos when running renv::init()

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
- src/gwt/tools/generate-prefs.R
This PR is a bandaid against unexpected `null` preference values. If the associated preference is not defined or does not exist for some reason, we instead return the default value defined for the preference (if any), or the "zero" value for the associated type.
> set defaults in JSNI accessors for prefs

- src/gwt/src/org/rstudio/studio/client/workbench/ui/MainSplitPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
Previously all vertical splitters being displayed had their state's position saved as the width of the column in front of it. This worked for the first splitter but none of the following ones. This fix determines the splitter's position by adding the splitter position of the previous column to the column on it's right's width. 
For example, given four columns and three splitters the equation would look like the following:
```
splitterPos[0] = rightColumnWidth
splitterPos[1] = splitter[0] + rightColumnWidth2
splitterPos[2] = splitter[1] + rightColumnWidth3
```
This PR also adds an additional safety check to the logic used to select a tab on start up. Before it was possible to attempt to select a tab with iterator position of -1.
> Save accurate splitter positions

- src/gwt/src/org/rstudio/core/client/files/FileSystemItem.java
- src/gwt/src/org/rstudio/studio/client/workbench/codesearch/CodeSearch.java
- src/gwt/src/org/rstudio/studio/client/workbench/codesearch/ui/CodeSearchDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
This PR fixes an issue where attempting to navigate using the fuzzy finder would sometimes not send focus to the opened document.
> ensure focus on navigate when using fuzzy finder

- src/cpp/core/LogOptions.cpp
- src/cpp/desktop/DesktopUtils.cpp
- src/cpp/diagnostics/DiagnosticsMain.cpp
We currently still expect to find RStudio Desktop logs in the old `.rstudio-desktop/log` folder in some places. This location is now configurable and defaults to `.local/share/rstudio/log`, so this change updates the remaining references. 
Fixes #7367.
> Standardize XDG log file locations on desktop

- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/SessionRpc.cpp
- src/cpp/session/SessionRpc.hpp
This PR makes it possible to force a delay when executing RPCs, via:
```
.Call("rs_setRpcDelay", <delay>)
```
The primary intention is to help debugging bugs that appear timing related -- for example, I've seen issues where the autocompletion results are not properly inserted in high-latency environments, and having this makes it easier to reproduce and understand the issue locally.
> provide hook for simulating RPC delays

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java
This PR fixes an issue where attempting to navigate to a file that currently has a visual editor open would open that file, but not send focus to the document within.
> delegate focus requests to panmirror when visual mode active

- src/gwt/src/org/rstudio/core/client/PreemptiveTaskQueue.java
- src/gwt/src/org/rstudio/core/client/PriorityTaskQueue.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
This PR attempts to mitigate some of the expensive startup cost incurred per IDE tab that has an activated visual editor. 
For each visual editor tab to initialize, a number of things need to occur:
1) Initialize the visual editor 
2) Call the server to render pandoc markdown into the pandoc AST (this involves 3 calls to pandoc, all fast/cheap but it is 3 process launches)
3) Render the pandoc AST into the visual editor
4) Initialize embedded Ace editor instances (this is currently done on a queue that prioritizes currently visible editors)
All of these operations are asynchronous (except the first) so don't in principle "block" use of the IDE. In practice though they are tying up cycles on the server (using multiple cores) and the client (using the single core dedicated to the UI …
> priority task queue for initializing visual editor contents

- src/cpp/shared_core/FilePath.cpp
On Centos7 (Desktop), unit tests were failing because global static initialization was causing access to an uninitialized string.
Fix by wrapping the static strings in functions.
The trigger is here: https://github.com/rstudio/rstudio/blob/e6fd9fd85f9088c13e8b2c5b78176111b4f2b485/src/cpp/core/LogOptions.cpp#L61
The crash stack was:
```
#0  0x000055ed09fbbdbe in std::string::size (this=0x55ed0b7d5188 <rstudio::core::(anonymous namespace)::s_homePathLeafAlias>)
at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:3817
#1  0x000055ed09fdc60c in std::operator==<char> (__lhs="~/.local/share", __rhs=<error reading variable: Cannot access memory at address 0xffffffffffffffe8>)
at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/basic_string.h:6007
#2  0x000055ed0a97ce4c in …
```
> fix static-initialization order dependency leading to rsession unit test segfault

- src/cpp/r/R/Tools.R
- src/cpp/session/modules/SessionPatches.R
- src/cpp/session/modules/SessionPythonEnvironments.R
- src/cpp/session/modules/SessionPythonEnvironments.cpp
- src/cpp/session/modules/SessionReticulate.R
This PR fixes an issue where user calls to e.g.
```
reticulate::use_python(..., required = TRUE)
```
were being ignored. This is because `RETICULATE_PYTHON` overrides any other existing Python requests. We want the version of Python set via global options to act as a default version of Python, but it should still be possible for users to override this if required (either via `RETICULATE_PYTHON` or their own calls to `reticulate::use_python()` and friends).
> prefer use_python to RETICULATE_PYTHON

- src/gwt/src/org/rstudio/core/client/theme/DialogTabLayoutPanel.java
- src/gwt/src/org/rstudio/core/client/widget/FocusHelper.java
- src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditCodeBlockDialog.java
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditImageDialog.java
- src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditLinkDialog.java
Fixes #7098
This relates to any modal dialog where the first focusable control is a Tab Panel, and you select a tab other than the first then try to Shift+Tab past the beginning of the dialog.
Focus should remain in the dialog and wrap to the end, but was leaving the dialog and stepping through controls in the main UI (essentially "under" the modal dialog). This was because the first tab was still marked as the first control (via a class), but not capable of receiving focus (via no tabindex), so browser had to pick some other element.
Some dialogs were managing this manually, e.g. the Visual Editing dialogs such as insert image:
Others, like the standalone Accessibility preferences pane, were not, and exhibited the problem.
Other known dialogs to check are the Visual Editor's "edit link" …
> improve DialogTabLayoutPanel to manage focus loop automatically

- src/gwt/src/org/rstudio/core/client/AnsiCode.java
- src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
- Fixes #7250
- Fixes #7557 
Looks like I had not completed the implementation of handling ANSI "invert" back when I added console ANSI support in RStudio 1.1.
Specifically, when invert is active, setting foreground or background colors and resetting foreground or background colors were not being inverted (e.g. setting foreground should actually set background and so on).
We have pretty extensive unit testing of this code, and I wrote several new tests to cover this. To exercise it, recommend using the Crayon package and trying examples like the one in the issues themselves and/or issuing escape sequences directly.
Reference: https://en.wikipedia.org/wiki/ANSI_escape_code
> Fix issues with Console handling of inverted color mode

- src/cpp/session/resources/grid/minify.sh
The IDE data viewer uses javascript that needs to be minified, and we didn't have a script or instructions on how we perform this.
Added a bash script `minify.sh` to the folder where the Javascript lives, which minifies via the Closure compiler we use in other similar situations. For now a no-op, since I didn't actually modify the Javascript files.
Nothing to see here. This is a manually executed script used by developers after they modify some source code, and that source code was not modified. Just making it easier in the future.
> add script for minifying the data viewer JS

- src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleResources.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/consoleStyles.css
- Fixes #6518
When selecting text from the Console output region, keyboard focus rectangles were being shown if you pressed a key (e.g. using Shift to extend the selection; these could be quite ugly and don't serve any real purpose, so this change gets rid of them.
It gets much uglier if you turn off the (relatively new) accessibility option "Always show focus outlines". Then just clicking on it was enough to trigger focus outlines.
Use CSS to suppress focus rectangles. Sometimes focus was being placed on the `div` that wraps the entire output region, sometimes it was being placed on the individual spans used to wrap each output "chunk" so the css needed to handle both.
Generate some console output, then click on it, then tap Shift key (or any key). Previously you'd see something like …
> suppress focus outlines for console output regions

- dependencies/common/install-pandoc
- dependencies/tools/upload-pandoc.sh
- dependencies/windows/install-dependencies.cmd
- src/cpp/session/CMakeLists.txt
- src/gwt/panmirror/src/editor/src/api/pandoc.ts
- src/gwt/panmirror/src/editor/src/api/pandoc_format.ts
This PR updates the embedded version of pandoc to [v2.10.1](https://pandoc.org/releases.html#pandoc-2.10.1-2020-07-23) (we are currently at 2.9.2.1). The 2.10 series isn't likely final, but since we are close to entering preview mode I think it would be good for us to get 2.10.1 in front of our preview testers so any issues can be identified and resolved before we release.
Note that this release of pandoc adds support for `--number-sections` to docx output, which will be great for bookdown users that want to create MS Word output. @yihui If you plan on adding an MS Word output option to bookdown let us know and we will try to make sure we hookup Bookdown preview of MS Word book outputs.
> update to pandoc 2.10.1

- src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenu.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserContextWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/cpp/CppCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/cpp/CppCompletionPopupMenu.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarPopupMenu.java
- Fixes #7070
Fix a regression in 1.4 (due to change I made in #6576), whereby popup menus that don't receive keyboard focus would no longer respond to keyboard (e.g. up/down arrows, Enter). One instance of this was previously noticed and fixed here (C/C++ autocompletion popups): #6976
There were three separate instances of this, found via code inspection. Rather than duplicating the fix already made for the C++ completion manage, I put handling of this situation directly into the base ToolbarPopMenu class, enabled via new `setReceivesFocus(YES/NO)` method. The default is YES, as most uses of this class are in situation where it does receive keyboard focus, which enables handling of these keys by GWT's `MenuBar` class. When set to `NO`, then the behavior I had previously removed (and now …
> fix keyboard operation of unfocused ToolbarPopupMenus

- docker/jenkins/Dockerfile.windows
The NSIS Chocolatey package (https://chocolatey.org/packages/nsis and https://chocolatey.org/packages/nsis.install) are currently hosted on a site with an expired certificate, causing our Windows builder to fail to install NSIS, preventing Windows builds from being generated.
We now install NSIS from the same executable as the prior Chocolatey package, but we now grab it from our S3 bucket instead, as that is expected to be a stable URL.
No QA necessary - this is a build change only
> Install NSIS from S3

- src/gwt/src/org/rstudio/core/client/ClassIds.java
- src/gwt/src/org/rstudio/core/client/theme/WindowFrameButton.java
- src/gwt/src/org/rstudio/core/client/widget/ToolbarButton.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetToolbar.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Create a way to predictably identify toolbar buttons, specifically to be used with `rstudioapi::highlightUi`. This will close pro issue 1848 (https://github.com/rstudio/rstudio-pro/issues/1848).
Add a toolbar button prefix to `ClassIds` and update the `ToolbarButton` constructor to always append the button's text to this prefix and use that value as the class id. The button's text was used instead of the title because although it's more verbose, some buttons are missing titles. Update `EditingTargetToolbar` to make the class id even more specific by appending the editing target's id. 
1. Open a few text files in the IDE
2. Set up the IDE to display DOM class names: Help >> Diagnostics >> Show DOM Elements
3. Scroll over toolbar buttons and confirm they have descriptive class names
4. …
> Assign unique ClassIds to toolbar buttons

- NEWS.md
- src/gwt/src/org/rstudio/core/client/widget/FontSizer.css
- src/gwt/src/org/rstudio/core/client/widget/FontSizer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermOptions.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermTheme.java
- Fixes #6382
The newer xterm.js taken in RStudio 1.3 required a switch from using css to style the terminal to passing it information via an API.
For setting the font-size, it turns out I was missing an adjustment causing it to have a font somewhat larger than the console. 
For the line-spacing, I wasn't passing this at all and the terminal lines were generally showing up with less spacing than the console.
For the font-size, apply the `BrowseCap.getFontSkew();` adjustment before passing to xterm.js.
For the line-spacing, pass a value based on the same rules used by the console.
The terminal has two rendering modes; controlled by the "Hardware acceleration" setting in Global / Terminal preferences.
When this option is off, rendering is done via the DOM, and with this fix in place it …
> reduce font-size differences between Console and Terminal

- src/gwt/panmirror/src/editor/src/api/basekeys.ts
This PR changes the way our custom home/end logic detects the start of the next line or end of the previous line. Previously, the top of the bounding boxes were compared, if they were within 2 pixels of each other then it'd be considered the same line. Now, we check if the bounding boxes vertically overlap at all, if so then it's considered the same line.
However there still seems to be an issue with the custom logic. With a paragraph like this:
1. Place cursor anywhere on the first line, and press End. Instead of the end of the first line, the cursor ends up at the beginning of the second line.
2. Place cursor somewhere in the middle of the second line, and press Home. Instead of before `sv_required`, the cursor ends up one position to the right of that (between the `s` and `v`).
These …
> Refine Home/End logic for Mac

- src/gwt/src/org/rstudio/core/client/a11y/A11y.java
- src/gwt/src/org/rstudio/studio/client/application/ui/GlobalToolbar.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchPane.java
- Fixes #6619
The "Focus Main Toolbar" command is intended for keyboard users so focus rectangle should always show on the selected toolbar button after using, but sometimes it wasn't. Timing related, so was inconsistent (varying by whether keyboard shortcut was used, or the menu itself).
Rather than relying on the focus-visible polyfill to correctly deduce that focus should be displayed, do it explicitly in code.
Also changed a couple of unrelated string comparisons to the preferred `StringUtil.equals` approach while I was in there.
Ensure the focus rectangle is shown after using the Help / Accessibility / Focus / Focus Main Toolbar command, whether via keyboard shortcut or the main menu (desktop or server). Note there are known cosmetic issues with this focus rectangle, see #7604.
Also …
> Always show focus rectangle after using Focus Main Toolbar command

- src/cpp/r/R/Api.R
- src/cpp/session/modules/environment/SessionEnvironment.cpp
- src/gwt/src/org/rstudio/studio/client/common/filetypes/events/OpenSourceFileEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/events/JumpToFunctionEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/NavigableSourceEditor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/ScrollToPositionEvent.java
The goal of this PR is to enhance `rstudioapi` with a call to scroll to a line in the current editor without stealing the cursor's position. It closes pro issue 1850 (https://github.com/rstudio/rstudio-pro/issues/1850). The associated API PR is found here: https://github.com/rstudio/rstudioapi/pull/187. 
`rstudioapi::navigateToFile` is enhanced to make the `file` argument optional so that when a file is not provided, the IDE scrolls to the requested position in the file of the most recently used source window. If no arguments are provided to the call, then it does nothing. 
Rather than modifying the existing logic in the `JumpToFunction EventHandler` I added a new event `ScrollToPosition` to fire from the handler when a file name isn't provided. The previous logic executes a fair amount …
> Scroll to a specified position in an unknown file

- src/gwt/src/org/rstudio/studio/client/workbench/UserInterfaceHighlighter.java
Fixes #7607 
On a highlight event, elements were being highlighted even when they were hidden by a parent scrollable widget. 
I added an additional check before the highlight is displayed to check the bounds of the element to be highlighted against the bounds of its parent elements.  If the element is outside of any of its parent's bounds then its highlight is hidden.
See reproduction steps in #7607.
> Make sure element isn't hidden before highlighting

- NEWS-1.3.md
- src/cpp/server/ServerPAMAuth.cpp
Closes #7575 
This PR allows `auth-none` to work along with the several changes and fixes made in the authentication by making it close as possible of the usual authentication flow.
Cookies like `user-id` and `csrf-token` are required throughout the server for several operations. Previously, the CSRF cookie would be set in the first load of the main page route (`"/"`) and the `user-id` cookie would not be set at this point (surprisingly, we never saw problems because of this). Eventually, the missing cookie would be set by a `refreshAuthCookies` event.
With this change, an initial visit to the main page route (`"/"`) will force a redirect to `/auth-sign-in` which then will verify for `auth-none` and redirect back to with the proper cookies set. The rest of the logic now work like usual …
> Make auth-none work like any other auth

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
Fix code navigation commands so they move the cursor as well as display the desired position.
In #7596 I broke this code by setting the new `restoreCursorPosition` to true instead of false in one of the calls to `navigateToPosition`. This change switches it to false to preserve the original behavior.
> Fix navigateToPosition to by default move the cursor

- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
Fixes #7532 (See Aug 25 comment)
If a user leave RStudio with the main source pane minimized and an edited untitled document, the source pane should be restored with the state set to `MINIMIZED` instead of `HIDE`. This is consistent with previous releases.
On restoration, there was a rare case where a document wouldn't be counted when its column was found but the window for that column was not found. This change assumes the window is the main source window, which should always be the case.
From original PR #7617: 
The logic for how panes are configured at startup is fragile and allowing additional source columns further complicates things. I tested restarting RStudio in a variety of ways with the main source window minimized without any documents (e.g 1-3 columns, columns have untitled …
> Persist minimized state for main source pane

- src/cpp/session/modules/SessionRMarkdown.R
Fix https://github.com/rstudio/rstudio/issues/7615.
Properly validate that the TinyTex installation directory contains the directories we expect it to have.
Test by installing tinytex; e.g.
```
install.packages("tinytex")
tinytex::install_tinytex()
```
And then try removing the `bin` directory; e.g.
```
rootDir <- tinytex:::tinytex_root()
binDir <- file.path(rootDir, "bin")
unlink(binDir, recursive = TRUE)
```
and then follow repro steps in https://github.com/rstudio/rstudio/issues/7615.
> guard against missing bin directory in tinytex install

- Jenkinsfile
Open-source build pipeline keeps failling, killing all the jobs with what looks like memory errors.
Reduce parallel build number to see if that gets us some working builds while we investigate a better solution such as serializing the Java and C++ portion of the builds.
Purely a build issue; if builds stop failing, this worked.
> Reduce number of cores used for official build

- NEWS-1.3.md
- src/cpp/core/system/file_monitor/Win32FileMonitor.cpp
We thought this crash only manifested in very obscure scenarios such as forcing the Windows Desktop IDE to reload the embedded browser but users are hitting it via routine use of the Files pane so are now backporting it from master to next 1.3 patch.
See #7641 for more details.
Fix crashes in Windows Desktop sessions when reloading the embedded browser or changing directories in the Files pane.
Backported fix from master. #7641
This is a Windows-desktop specific issue. Test by trying scenarios in #7637, #7652, #7665.
> cherry-pick file-monitor crash fix from master

- .gitignore
- src/cpp/core/include/core/r_util/RActiveSessions.hpp
- src/cpp/core/r_util/RActiveSessions.cpp
When many sessions are being started simultaneously, the `std::sort` of an  `std::vector<boost::shared_ptr<ActiveSession> >` inside `ActiveSessions::lists` segfaults due to a bad memory access. The method is single threaded and the vector being sorted is created on the stack within the method. 
[A valgrind log of the crash](https://github.com/rstudio/rstudio/files/5139040/rsession-diagnostics-maria-6a3f32b2.log.memcheck.txt)
~Many different solutions to this problem were tried, including using `std::shared_ptr` or even raw pointers instead of boost pointers. The only change that seems to have worked is this method of creating the `ActiveSession` objects on the stack instead of the heap, sorting that vector, and then transforming the sorted vector to a vector of `shared_ptrs`~
Once we …
> Fixes an occasional sessions start-up crash

- src/cpp/core/system/PosixFileScanner.cpp
- src/cpp/core/system/System.cpp
- src/cpp/r/session/RStdCallbacks.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/shared_core/Error.cpp
- src/cpp/shared_core/Logger.cpp
- src/cpp/shared_core/include/shared_core/Error.hpp
Fix an issue where noisy file monitor errors could be logged on session restart.
Mark file monitor errors as expected; suppress logging of expected errors.
This is an issue that reproduces purely in development builds -- nothing to verify for QA.
> don't log monitor interrupt errors

- NEWS.md
- src/cpp/core/r_util/RSourceIndex.cpp
- src/cpp/session/modules/SessionCodeSearch.cpp
Add R6Class method definitions to the fuzzy finder (Ctrl + .), making them more easily navigable in large projects.
The R source indexer is augmented specifically to allow indexing of function definitions found within an `R6Class()` call.
Try creating your own `R6Class()` definitions, and testing how the fuzzy finder locates those functions. You may need to install the R6 package via:
```
install.packages("R6")
```
You can also read the documentation in `?R6Class` for more details.
It would be worth validating that previously-indexed results are still available (ie: I didn't accidentally break indexing of other types of objects).
> index R6 class method definitions; add to fuzzy finder

- src/cpp/session/modules/SessionPlumberViewer.R
- src/cpp/session/modules/SessionPlumberViewer.cpp
Fixes https://github.com/rstudio/rstudio/issues/7702
Related: https://github.com/rstudio/plumber/pull/658/files#diff-336a56f6c4950b52b1c80583d5070e64R96
The new version of plumber would like to listen to `plumber.docs.callback` (vs `plumber.swagger.url`). Currently it works for both, but I'd like to eventually stop support for `plumber.swagger.url`.
Setting both options doesn't seem like it should hurt anything.  This would allow for both legacy support and moving forward.
Set both …
> Update `plumber.swagger.url` option to `plumber.docs.callback`

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/application/Application.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
Provide ability to go directly to each pane in the Global Options dialog from the command palette.
Fixes #7678
Added new commands for panes that didn't already have one (terminal, accessibility, and pane layout already had such commands). The command are:
- Global Options (goes to General pane)
- Code Options...
- Console Options...
- Appearance Options...
- Pane Layout Options...
- Packages Options...
- R Markdown Options...
- Sweave Options...
- Spelling Options...
- Git/SVN Version Control Options...
- Publishing Options...
- Terminal Options...
- Accessibility Options... (note this is a special case as it opens JUST the accessibility pane, no other panes available, this is on purpose to reduce potential confusion for screen reader users)
- Python Options...
Verify that each commands …
> Add commands for showing each Global Options pane directly

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Fixes #7688, #7653 
1. When closing a column the active column was not being reset in some cases, causing the command buttons on all active columns to be disabled.
2. A few toolbar buttons were not taking their column into account when executing their command.
1. When the active column is closed, set the active column to the main source column. We were already doing this in other cases.
2. Whenever a button is selected in an editor, reset the active column to itself before executing the command. Again, we were already doing this for most buttons but a few were missing.
See original issues.
> Fix issue with column buttons

- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
- Fixes #7649
- Another case where overwriting previous output (via carriage-return) messes up in complex case involving ANSI codes
- Created a unit test that catches this specific issue, then debugged and fixed the underlying problem
- To trigger, the original output (before the carriage-return) must have a span with one style (e.g. color) that gets partially overwritten (at its beginning) with output with a different style; this results in the origin span being marked for a move (to compensate for it being shortened and "pushed right"), but the code was setting the wrong destination index causing it to mess up subsequent output
- Test the new case as described in the issue, make sure output now matches
- This code has extensive unit testing, and thus regression of existing behavior …
> Fix console handling of a carriage-return / partial overwrite scenario

- src/cpp/core/include/core/Thread.hpp
Fix a windows compile error (caused by an MSVC bug) and add the class to the OS version of Thread.hpp.
Prior to Visual Studio Tools 2019 16.6 MSVC has problems correctly deducing template arguments in some scenarios. As a work-around, I've set the second and third template parameters of `std::set` to what they should be if MSVC had deduced them correctly.
After this merges, I'll pull to pro and resolve the conflicts.
No QA needed on this one.
> Add ThreadsafeSet class that compiles on Windows

- src/tools/valgrind-suppressions
Memcheck is identifying the following comparison in the for-loop as a conditional branch on an uninitialised value but this is the intended use of the iterators.
```
boost::filesystem::directory_iterator end;
for (boost::filesystem::directory_iteratory it(m_impl->Path); it != end; ++it) { ... }
```
Add a suppression file that can be passed to valgrind to help reduce noise in the log file.
This is not part of our released product and doesn't need to be QA'd.
> Add valgrind supression file with false positives

- src/cpp/session/modules/SessionEnvironment.R
- src/gwt/src/org/rstudio/studio/client/common/SimpleRequestCallback.java
- src/gwt/src/org/rstudio/studio/client/common/debugging/BreakpointManager.java
- src/gwt/src/org/rstudio/studio/client/common/debugging/ErrorManager.java
- src/gwt/src/org/rstudio/studio/client/server/ErrorLoggingServerRequestCallback.java
- src/gwt/src/org/rstudio/studio/client/server/QuietServerRequestCallback.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/model/EnvironmentServerOperations.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/JobManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkSatelliteWindow.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java
Packages and user code might mask the `save.image()` function, which interferes with the Save action in the Environments pane.
Detect this state, and emit `base::save.image()` when masked, and `save.image()` otherwise.
Try running the following code:
```
save.image <- function(...) { stop("oh no") }
```
Then using the Save icon in the Environment pane to save the global environment. You should see an error; e.g.
Closes https://github.com/rstudio/rstudio/pull/7073.
---
This PR also adds in the helper classes `ErrorLoggingServerRequestCallback` and `QuietServerRequestCallback`, capturing some of the more common `ServerRequestCallback` implementations. It also makes `onResponseReceived()` from `ServerRequestCallback` abstract, so that IDE autocompletion will automatically fill in the method …
> use 'save::save.image()' if 'save.image()' is masked

- src/cpp/core/ConfigProfile.cpp
- src/cpp/core/http/Request.cpp
- src/cpp/core/system/ProcessTests.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/modules/SessionDiagnostics.cpp
- src/cpp/session/modules/SessionProjectTemplate.cpp
- src/cpp/session/modules/SessionUserPrefs.cpp
- src/cpp/session/modules/presentation/SlideMediaRenderer.cpp
- src/cpp/session/modules/rmarkdown/NotebookCache.cpp
- src/cpp/session/modules/rmarkdown/NotebookDocQueue.cpp
- src/cpp/session/modules/rmarkdown/NotebookPlotReplay.cpp
- src/cpp/session/modules/rmarkdown/NotebookQueue.cpp
- src/cpp/session/modules/rmarkdown/NotebookQueueUnit.cpp
- src/cpp/session/prefs/Preferences.cpp
- src/cpp/session/prefs/UserPrefsLayer.cpp
- src/cpp/shared_core/include/shared_core/json/Json.hpp
- src/cpp/shared_core/json/Json.cpp
Resolve compiler warnings from `-Wrange-loop-analysis`, introduced in the newest version of Clang.
Look at and respond to compiler warnings. Mostly fixed via adding reference qualifier `&` or, in some cases, using `auto&&` (e.g. for `std::vector<T>` where binding to potential proxies for e.g. `std::vector<bool>` could be necessary).
No QA notes / testing required.
> fix range analysis warnings in newest clang

- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPythonPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonInterpreter.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPaneBase.java
As a result of the recent Python PR (https://github.com/rstudio/rstudio/pull/7656) the IDE was restarting every time the Project Options dialog was used. This was caused by an erroneous attempt to detect changes to project preferences; I was previously under the impression that the `onApply(RProjectOptions options)` method received the _old_ project preferences, but it in fact receives a _blank_ set of project preferences (and so it is nonsensical to compare values in that object).
Cache the 'initial' Python path set when the dialog is opened, and then compare that to the 'new' value set by the user when the dialog is closed.
Try changing project options. The IDE should not restart if nothing has changed.
> avoid unintentional IDE restarts

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Fixes #7723 
Fixes 1.4 regression where multiple data viewer tabs could be opened for the same object. Instead, the open tab should refresh.
Use for loop instead of forEach.
See original ticket.
> Fix issue where multiple data viewers were displayed for one object

- docker/docker-compile.sh
Safe default for number of cores used for build parallelization on macOS when using the docker-compile.sh utility script.
- The default was equalling number of cores on the machine, but Docker for Mac defaults to half that value (and can be adjusted via preferences)
- Set to -j2 as a safe default; edit the script if you want a higher value
- Also reversed order of the `nproc` vs `sysctl` check; a Mac with `coreutils` installed also has the `nproc` command and want the Mac branch to be used on the Mac to reduce confusion
Purely a developer utility, not used for official builds or anything impacting customers.
> set default -j value lower on Mac for local docker builds

- docker/jenkins/Dockerfile.windows
RStudio for Windows installer is built using the NSIS toolkit. Version we are using (3.05) is a couple minor releases out of date so updating to the most recent for 1.4.
Uploaded newer NSIS toolkit installer to S3, updated Dockerfile.windows to use it. I did a test build using Docker and confirmed the resulting setup exe was installable/uninstallable.
Basic sanity test for RStudio Desktop for Windows install/uninstall process. Should see no difference other than the version number shown on some of the setup wizard screens.
> Update to NSIS 3.06.1

- src/cpp/desktop/DesktopMain.cpp
Depending on where cmake generation is run, the folder structure of the build directory may have more layers. In that case the`FilePath::safeCurrentPath` call ([here](https://github.com/rstudio/rstudio/blob/fe8d018b122fb7dc91a76ef8ead64669833d3d0a/src/cpp/desktop/DesktopMain.cpp#L778)) is returning a folder higher in the structure than where `rstudio` was run from. In `gdb` printing `pwd` gives the correct current directory, but calling `p boost::filesystem::current_path().string()` returns the incorrect value.
This prevents `./rstudio-dev` from launching correctly. 
Whether `conf/rdestkop-dev.conf` exists in the install location or the current directory, we probably want to read it and run `rstudio` in dev mode. This PR falls back to install location if `conf/rdesktop-dev.conf` cannot be …
> Add a fallback to the install path for dev Desktop Launches

- src/gwt/src/org/rstudio/core/rebind/command/CommandBundleGenerator.java
- src/gwt/src/org/rstudio/core/rebind/command/MenuEmitter.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
RStudio Desktop on Windows (and possibly some Linux desktop managers), shows menu-access keys on the main menu. These are the underlined characters you can use to quickly select a command via keyboard.
We devs often forget to add these to new commands, and have relied on them being noticed as missing after the fact.
Adding them is a pain because they are only visible on Windows Desktop, and figuring out what letters are unused on a given menu is tedious. Plus some commands are only visible on the menu in certain scenarios, so even more likely to miss those.
Added code at GWT build time to check that every menu command has an access key defined, and write warnings that show which commands are missing access keys, which menu they are on, and what letters remain available for use on a given …
> added gwt build-time check for menu access keys

- src/gwt/src/org/rstudio/studio/client/common/filetypes/events/OpenSourceFileEvent.java
The currently-debugged line was not being highlighted when the debugger was active.
A parameter was not being passed along as expected. (https://github.com/rstudio/rstudio/commit/b134c4b11e8ad527356990767fb2c9707acd4530#diff-91600fcd8b751bc5240ddf738ee9605fR54)
Test via notes in https://github.com/rstudio/rstudio/issues/7749.
> pass along navMethod when invoking ctor

- dependencies/osx/install-dependencies-osx
- src/cpp/rstudio-tests.in
When unit tests timeout (5 minutes), getting a stack trace of the hang on macOS wasn't working.
- brew install pidof and gdb, and write necessary goo to .gdbinit needed on macOS
- pidof doesn't support fully qualified paths on macOS, so pass the basename only
Purely a dev/build environment thing. No product or customer impact.
> fix unit test hang analysis on macOS

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/common/vcs/AskPassManager.java
When a password is requested from the user via e.g. `.rs.askForPassword()`, we choose to mask user input based on whether "username" is located in the prompt string. This fails for cases in https://github.com/rstudio/rstudioapi/issues/195 where both "password" and "username" are mentioned in the prompt.
If "password" is contained in the prompt, treat it as a password entry, regardless of whether "username" is present.
Test with `rstudioapi::askForPassword("Enter password for username USER:")` -- input should be masked.
---
Closes https://github.com/rstudio/rstudioapi/issues/195.
> mask user input if prompt contains 'password'

- src/gwt/panmirror/src/editor/src/api/scroll.ts
- src/gwt/panmirror/src/editor/src/api/ui.ts
- src/gwt/panmirror/src/editor/src/optional/ace/ace.ts
- src/gwt/src/org/rstudio/studio/client/panmirror/ui/PanmirrorUIChunkCallbacks.java
- src/gwt/src/org/rstudio/studio/client/panmirror/ui/PanmirrorUIChunks.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkOutputPanmirrorUi.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunks.java
This change fixes a couple of issues in which the cursor and/or output of code execution could be offscreen in embedded Ace editors in visual mode. 
Fixes https://github.com/rstudio/rstudio/issues/7739.
- When the cursor moves in an embedded Ace editor, we compute whether the cursor element is sufficiently visible using bounding boxes, and scroll it into view if it isn't. This computation is somewhat expensive, so we only do it when moving to a new row (i.e. it won't fire while typing in a line) and only after releasing the mouse/keyboard. 
- When a chunk finishes executing, we ensure that the output it created is visible. This is handled on on the panmirror side via zenscroll, and invoked from GWT-land. 
The intent here is for you to always be able to see what you're typing and …
> Improve cursor and output visibility in embedded editors

- NEWS.md
- src/cpp/session/modules/SessionRCompletions.R
Allow the autocompletion system to provide completion results for Python virtual environments, normally referenced via `use_virtualenv()`.
Relatively straight-forward addition to the autocompletion system.
Check that the completion results in `use_virtualenv(|` reflect the available Python virtual environments located at `~/.virtualenv`.
> auto-complete virtual environment names

- NEWS.md
- src/cpp/desktop/DesktopMenuCallback.cpp
- Fixes #6524
Since RStudio 1.2 we've been showing the wrong symbol for the <kbd>Return</kbd> key in the Mac desktop IDE's menus. We were showing the symbol for <kbd>Enter</kbd>, instead.
On Mac desktop only, notify Qt that we _really_ meant the <kbd>Return</kbd> key so it shows the expected symbol.
Check that any command on Mac Desktop shows the expected symbol for commands using "Enter" in their shortcut, and that these keyboard shortcuts still work. In my testing with a full Mac keyboard, both the Enter and Return keys work as expected, but mainly we care about the Return key (the one on Mac laptops).
The code change is in Mac-only desktop code, and only impacts the main menu.
> show correct symbol for Return key on Mac menus

- src/cpp/.gitignore
- src/cpp/session/SessionConsoleProcessInfoTests.cpp
Minor dev-only tweaks; gitignore the default build location used by VSCode for the cpp project (rstudio/src/cpp/build) and remove some unused variables in unit test source to get rid of the warnings.
Fixed the things.
> gitignore default vscode output dir, remove some unused vars

- src/gwt/panmirror/src/editor/src/optional/ace/ace.css
- src/gwt/panmirror/src/editor/src/optional/ace/ace.ts
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetFindReplace.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunks.java
A substantial number of editor commands are currently disabled in the visual editor and hidden in the toolbar when the visual editor is active. Some are disabled because they don't may any sense in visual mode (e.g. Go To Line), but most are disabled because we hadn't yet done the work to hook them up / make them do the right thing in visual mode.
This change implements all the remaining editor commands that make sense for visual mode, including notebook commands (clearing output, switching inline/console mode), code execution commands (various execution gestures), commenting (toggle/reflow), refactoring (extracting functions/vars), etc. 
Fixes https://github.com/rstudio/rstudio/issues/7581.
Most of the commands follow one of two forms:
1. Execution-oriented commands work by synchronizing …
> Implement all relevant editor commands in the visual editor

- Jenkinsfile
- Jenkinsfile.macos
- Fixes #6890
We are running a subset of unit tests on macOS; we should be running the same set we do on Windows and Linux.
Tweak the Mac Jenkinsfile to run all the tests. Also removed an obsolete command from the Linux/Windows Jenkinsfile.
This is a build-time thing. At worst (famous last words) we'll discover we still have issues running these tests on Mac in the official build, resulting in builds marked as "Unstable" and will have to investigate why.
> enable all unit tests for macOS build

- dependencies/osx/install-dependencies-osx
Needed on build machines to run rsession unit tests which were just enabled via #7775
Install via macOS dependency script.
Nothing to test here, purely build-time to get unit tests passing on macOS during official builds.
> Install openssl on macOS via dependency script

- scripts/clean-rstudio
- scripts/clean-rstudio.bat
Utility script (`clean-studio` / `clean-rstudio.bat`) for resetting a machine to a first-run RStudio state; noticed I wasn't being prompted for sending crash reports after running this script, and keyboard shortcuts and add-ins customized in pre 1.4 version weren't going away.
Delete these, too.
Nothing to test (but if you've been using these scripts for anything be sure to grab new copies).
> cleanup additional legacy state

- src/cpp/session/modules/SessionPythonEnvironments.R
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/python/PythonInterpreterSelectionDialog.java
Currently, RStudio only discovers Python interpreters called `python` (or `python.exe`) on the PATH. However, multiple Python interpreters with versioned names (e.g. `python3.7`) may be available on the PATH as well. This PR makes sure such interpreters are discovered by RStudio.
Rather than hardcoding the Python interpreter name, we list files in each directory on the PATH that match an appropriate regular expression.
Note that, in theory, one downside of this approach is that it could be slow when attempting to list files within a very large directory.
Test that versioned Python executables are discovered in the Python dialog here:
> look for versioned python interpreters (e.g. pythonx.y) on PATH

- Jenkinsfile.macos
- Due to problems finding openssl in package build; tracked via (reopened) #6890
- Will investigate this locally instead of continuing to mess around on the build machine
Nothing to see here. We weren't running most unit tests on macOS build, then we tried, and it didn't work, so reverting to not trying pending further investigation.
> re-disable rsession-based unit tests for macOS build

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/shiny/ShinyApplication.java
Addresses an issue in which the Reload App button can cause a script error. Fixes https://github.com/rstudio/rstudio/issues/7762.
Ensure that the parameters defining the window to activate on reload are supplied.
If you're having trouble reproducing, try using the Chrome browser + RStudio Server (the window reload/reactivation requires us to close and reopen the window there).
> Specify window to activate when reloading

- .github/ISSUE_TEMPLATE/bug_report.md
- src/.gitignore
Tweak the display of the bug report template for GitHub. Right now, some of the checked lines overflow, giving an awkward presentation -- e.g. note the period sitting on its own line.
Tweak the text content so that lines are a little shorter.
Worth validating that the new bug report template fits the available space better.
> tweaks for bug report template

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/ui/MainSplitPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Fixes #7687 
The main purpose of this PR is to fix an issue affecting the `Zoom Left Column` and `Zoom Right Column` commands when user has additional source columns open. The issue is primarily caused by the fact that the "left column" is no longer the left column with additional source columns. 
This also fixes and issue where`WindowEnsureVisibleEvent` was never updated to handle multiple source windows but was being initiated by source columns.
This PR only ensure both commands work as they used to (zooming on the right column or left/center column). Another one will need to be created to have the wording of the commands updated and commands to zoom on the additional source columns.
The majority of the new logic is to ensure clean animation when transitioning to/from a zoomed state. …
> Fix issue with zoom column commands

- src/cpp/server/include/server/ServerOptions.gen.hpp
- src/cpp/server/server-options.json
Restore the default values as used in 1.3.
Make the default value for the option that add HTML content to the sign in page be the same as 1.3
> open source companion commit for rstudio/rstudio-pro#1951

- src/gwt/panmirror/src/editor/src/api/ui.ts
- src/gwt/panmirror/src/editor/src/optional/ace/ace.ts
- src/gwt/src/org/rstudio/studio/client/panmirror/ui/PanmirrorUIChunkCallbacks.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
Prior to this change, gestures that navigated to a specific location in a source file (e.g., navigating to R Markdown render issues) always used source mode. This change allows source navigation to take place inside the embedded editors in visual mode when appropriate.
Fixes https://github.com/rstudio/rstudio/issues/7603.
There are three possibilities for navigation to cover:
1. Source mode - when the document is in source mode, the behavior is unchanged (we don't ever switch to visual mode in order to navigate)
2. Navigating to code - when in visual mode and navigating to a location inside a code chunk, we stay inside visual mode and navigate to the location inside the chunk
3. All other cases - in all other situations (the document isn't open, the location isn't in a code chunk, etc.) …
> Navigate inside visual source editor if available

- src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefs.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
- Fixes #7788
When virtual scrolling feature was added, it broke the "Focus Console Output" command, which is used by screen-reader users to quickly get focus on and read console output. It broke it whether or not the virtual scrolling feature was enabled.
Undid the change that was breaking "Focus Console Output" when virtual scrolling was disabled.
When user toggles on screen reader mode, we now disable the virtual scrolling mode, as the way it dynamically structures the HTML presents potential problems to screen reader users (including breaking the focus output command).
Finally, if screen reader mode is on and virtual scrolling also happens to be on, give a live announcement warning when an attempt is made to use the unusable "Focus Console Output" command.
- Start screen reader and …
> Disable virtual scrolling when screen reader mode toggled on

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceVimCommands.java
This PR ensures that the Vim command `:qa!` sends focus to the Console after all tabs have been closed.
Pass along an appropriate onCompleted command to be executed after closing all tabs.
Test via notes in https://github.com/rstudio/rstudio/issues/7810.
> send focus to console after closing all tabs

- src/gwt/panmirror/src/editor/src/optional/ace/ace-render-queue.ts
- src/gwt/panmirror/src/editor/src/optional/ace/ace.ts
Currently, opening a large R Markdown document with many code chunks causes RStudio to become sluggish for a while until the document is fully rendered. This change improves responsiveness, especially while typing.
Fixes https://github.com/rstudio/rstudio/issues/7791.
There are two main changes here:
- We avoid rendering while the user is actively updating the document. This ensures that typing/editing performance feels snappy even when there's still rendering to do.
- If the editors to be rendered are relatively far from the viewport, we trickle them in every second or so instead of pushing them through on every event loop. 
These changes will only be noticeable in large documents with many code chunks. One such document is linked in #7791. Note also that this change doesn't actually …
> Improve responsiveness in complex documents in the visual editor

- src/cpp/session/modules/SessionFind.cpp
Fixes #7736 
If a user was outside of a project and didn't specify an encoding via Global Options, global replace would update files to include pieces of the color encodings from the grep command. used to find the pattern. 
Some pieces of code were written under the impression that if no encoding was provided, there wasn't a need to decode the line. Decoding is not just for encodings different from UTF8, but is also used to parse the grep command.
This specific issue occurred when the `Default text encoding` option was set to [Ask], but making changes to this code has a chance of affecting behavior on different operating systems. The changes here shouldn't affect the way global find/replace works for different encodings but it may be worth testing some anyways.
Note there is an existing …
> remove grep color encodings when contents is not encoded

- src/gwt/src/org/rstudio/studio/client/common/spelling/TypoSpellChecker.java
Fix some of the dictionary woes that our users are currently encountering. Accompanying this PR is a new `all-dictionaries.zip` file that will get uploaded to S3.
Fixes #7218 
Fixes #6999 
Go through dictionaries one by one and try to find replacements for bad/slow/incompatible ones. This is a slow process and there aren't many options online for hunspell dictionaries. I looked for a good while for a new Italian dictionary but it seems they're all derived from the same base one from 2001 and just slightly patched. I feel like non-english spell checking is an under-served market right now.
Czech and German New I was able to find newer dictionaries for that were able to be loaded by Typo.js. I only hope that they are equal to or superior than the older ones being used by the backend …
> remove Czech and DE_new from dictionary blacklist

- NEWS.md
- src/cpp/core/libclang/SourceIndex.cpp
On macOS, one can customize the "default" compiler toolchain to be used, via e.g.
```
sudo xcode-select -s <...>
```
Unfortunately, when Xcode's own developer tools are activated, RStudio's C++ diagnostic machinery breaks -- seemingly due to a mixture of CLT paths and Xcode paths.
Use `DEVELOPER_DIR` to force the use of macOS command line tools.
Note that this issue only affects macOS, and so should be tested on a macOS machine. To test, you can try running the following in the terminal:
```
sudo xcode-select -r
xcode-select -p
```
You should see:
```
$ xcode-select -p
/Applications/Xcode.app/Contents/Developer
```
Then, try to open an R package project including C++ code (for example, https://github.com/thomasp85/euclid). Check that you don't see erroneous C++ diagnostics when opening …
> set DEVELOPER_DIR when retrieving diagnostics

- src/cpp/session/modules/data/SessionData.cpp
Addresses an error that happens whenever CSV import is performed from Import Dataset. Fixes https://github.com/rstudio/rstudio/issues/7814. 
The background R process which reads the data calls a method that uses `.rs.tryCatch`, but doesn't source the R file which defines this utility function, so this change just sources that file in the background process.
No impact outside of verifying that #7814 is fixed.
> Fix broken CSV import preview

- src/cpp/r/R/Api.R
- src/gwt/src/org/rstudio/studio/client/events/RStudioApiRequestEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Users of the `documentId()` API may want to be able to target the last-focused source document, even when the console is currently focused.
The `documentId()` function gains the `allowConsole` parameter. When set, if the console is currently focused, then a pseudo-id `#console` is returned; if not set, then we always return the ID of the last-active source document.
Test that:
```
.rs.api.documentId(allowConsole = FALSE)
```
returns the ID of a source document, even if the Console is focused.
> add 'allowConsole' param

- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
Fixes #7809 
#7796 introduced an issue where column widgets were being double stored which led to columns not being fully removed until the user refreshed RStudio. It also caused new columns to open with two blank documents. 
Remove duplicates. 
Source columns should close completely when the last source doc is closed. They should also open with a single document.
> remove duplicate columns

- src/gwt/panmirror/src/editor/src/optional/ace/ace-render-queue.ts
Fixes https://github.com/rstudio/rstudio/issues/7852, in which chunks sometimes don't highlight immediately after the user scrolls to them.
This can happen when the render queue contains a lot of orphaned chunks (i.e. NodeViews which are no longer part of the document). We don't try to render orphaned chunks, but they do consume a work unit, and because they are perpetually at the "top" of the document, they often get priority over chunks that actually do need to render. The result is that the render queue doesn't do anything for a long time until these orphaned chunks have trickled out of the queue.
The fix is to skip past orphaned NodeViews when we are doing a unit of render work. 
This bug doesn't repro 100% of the time; you need a fairly long document (so the render queue takes time …
> Fast-forward past orphaned items in Ace render queue

- src/cpp/session/modules/rmarkdown/SessionRmdNotebook.cpp
`htmlCallback` was returned empty if the chunk name or code had unescaped characters. This update escapes the characters before they are passed to `executeChunkCallback`. 
Escape the characters before the html callback is created.
Register a callback function and then run chunks with various odd names include characters like `,<>&-\/`
> Escape chunk name and code before passing to executeChunkCallback

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/DocTabDragParams.java
Fixes #6475 
Fixes issue where `Save / Save As...` was disabled after a viewer object was popped out from main source. Also fixes an issue that was found while testing that prevented data viewers from being returned to the source window.  
When a document is popped out from the main column, reset the active editor to the next viewable one if one exists. 
Issue #6475 has step-by-step repro instructions. Also make sure that the popped out data viewer can be returned to the main window.
> Reset active column after a document pop out 

- src/gwt/src/org/rstudio/core/client/widget/ThemedPopupPanel.java
- src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenu.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNPane.java
- Fixes #7859 for both Git and SVN panes
Created a helper method to calculate position of context menu so it displays above the clicked location if there isn't enough room below it. Same with left/right, if you click close to the right edge of window, it will now display to the left instead of being pushed out of the visible window.
Follow steps in issue, confirm the menu now fully appears even when Git or SVN pane is in bottom region, and you are clicking close to the bottom of it.
> Keep VCS context menu visible

- src/gwt/src/org/rstudio/core/client/ElementIds.java
- Fixes #7850
- Accessibility validation fix; we were getting same elementID on "C++ File" and "C File" in the new file menu
- Substitute CPP for C++ when created element ID based on a label
- No direct user impact, just one less validation error
- You can either inspect the HTML and look for the IDs `rstudio_label_cpp_file_command` and `rstudio_label_c_file_command` or run Axe validation as described in the issue
> fix duplicate elementID on new file submenu

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/core/client/layout/LogicalWindow.java
- src/gwt/src/org/rstudio/core/client/theme/MinimizedWindowFrame.java
- src/gwt/src/org/rstudio/core/client/theme/WindowFrame.java
- src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java
- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AccessibilityPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
- Fixes #6225
Provides optional support (off by default) for indicating which panel has keyboard focus via a dotted outline. Someone will presumably have a better visual treatment, but for 1.4 this seems sufficient. "Panel" in our terminology refers to the main regions of the page (formerly each of the 4 quadrants, but now also includes source columns).
Enable in accessibility options via new "Highlight focused panel" checkbox.
Screenshot showing source panel having focus:
Screenshot showing console panel having focus:
Uses the `focusin` DOM event which is fired whenever focus changes in the page, then (if the option is enabled) checks if the currently focused element belongs to a panel and adds or removes the CSS style `focusedWindowFrameObject`. The CSS adds an outline.
So this …
> Optional highlight around focused panel

- src/gwt/src/org/rstudio/studio/client/common/satellite/Satellite.java
- Fixes #7882
- Shows focus rectangles in satellite windows, not just main window (via focus-visible polyfill)
When I implemented #7351 I made loading of the focus-visible polyfill conditional on the "Always show focus outlines" user preference and moved the load call to Workbench.java since it required user preferences to be available. This path isn't hit when loading satellite windows, so added the same call in Satellite.java.
Test as described in #7882.
> load focus-visible polyfill in satellite windows

- src/cpp/r/R/Api.R
- src/gwt/src/org/rstudio/studio/client/events/RStudioApiRequestEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/events/SuppressNextShellFocusEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceVimCommands.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/NewDocumentWithCodeEvent.java
Currently, there is no synchronous way for a user to open a document using RStudio. In particular, it is challenging to:
1. Create a new document in the IDE;
2. Receive an ID for that newly-created document;
3. Interact with that document.
This PR introduces an explicit API for opening a document on the user's filesystem. If that file does not already exist, then it will be created first.
Nothing notable; implementation is mostly straightforward.
Try opening various documents with `.rs.api.documentOpen()`, and see what happens when you specify "normal" paths, and perhaps also "weird" paths.
> add explicit document open API

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
- src/gwt/test/test-multiline-expr.R
Fixes an edge case in RStudio's "find current expression" heuristics. Closes https://github.com/rstudio/rstudio/issues/6248.
Treat lines ending with `(`s as continuations (and so they should be included as part of the "current" expression).
Test via cases in https://github.com/rstudio/rstudio/issues/6248.
> handle more pipe styles in "execute current statement" heuristics

- src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java
- Fixes #7902
- Prevent a warning in the Javascript console when using "Speak Text Editor Location" command
- Most live announcements can be enabled/disabled, but on-demand announcements cannot; the code that tests if an announcement is "known" wasn't accounting for these on-demand announcements.
- Created a second list for this type of announcement to check against
- Test the symptoms as described in issue; no end-user impact other than this warning going away
> Don't log warning when using speak text editor location command

- src/cpp/session/modules/jobs/ScriptJob.cpp
Fixes #6701 
`Source as Local Job` was failing on Windows when the file's path had a non ASCII character in it on Windows. This PR executes the source as it does on other operating systems today. 
Rather than attempting to source from the file the user is working in, copy the contents of that file to a temporary file. This avoids us needing to encode and re-encode files paths.
The original ticket gives a good repro. We should also make sure functionality hasn't regressed on other OSes. We should also ensure that non-ascii encoded characters run without issue (they may produce a warning which is ok).
> Copy code to temporary file during Source as Local Job

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
Fixes https://github.com/rstudio/rstudio/issues/7886, in which code-related commands are enabled even when outside a code editor. This change allows the same shortcut to do different things inside a code editor and the prose editor; e.g., Cmd+I will now reindent inside a code editor *and* italicize inside the prose editor.
The idea here is pretty simple:
1. We disable code-related commands by default in the visual editor.
2. When focus enters a code editor, the commands are enabled.
3. When focus re-enters the prose region, the commands are disabled again.
This affects a lot of commands (the PR diff has an easy to read list). Of particular interest is commands that have bindings that overlap with the visual editor's.
> Enable code commands only when a code editor is focused

- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
Fixes #7864 
When `Find in Files` was performed in a project on any OS errors would appear in the console "Cannot read property 'path' of null". Instead, we now return from `getValue()` if a state hasn't been set.
It looks like at one point I accidentally changed a `!=` to `==` which caused this issue. 
See repro steps in original ticket. Note this was happening with all OSes, not exclusively Linux.
> Fix null reference in Find in Files pane 

- src/gwt/panmirror/src/editor/src/marks/emoji/emoji.ts
There is no concept of a misspelling emoji (they are single character representations that are always considered properly spelled).
In addition, spellcheck can mutate the html inside the mark (e.g. adding a span to indicate the misspelling) which can transform the rendering of the emoji (e.g. the ✏️ emoji will be rendered differently with realtime spellcheck enabled vs disabled)
Disable spellcheck for Emoji marks.
I was able to reproduce the issue using the '✏️' emoji and enabling real time spell checking. In this case, the pencil would be rendered not as an emoji, but as the unicode pencil character. If you disable real time spell checking, the emoji is properly rendered. 
The fix should render the pencil properly no matter whether spell checking is enabled or not.
> Disable Spellchecking on Emoji Marks

- src/gwt/src/org/rstudio/studio/client/workbench/ui/MainSplitPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Fixes #7785 
We should only send `set_client_state` when a state has actually changed. This PR fixes two bugs where we were updating the workbench splitter position's state and the active source column's state when they hadn't actually changed. 
One of the logic statements for checking the splitter position was reporting a change after it confirmed no change had occurred - it was missing a `!` in front of the check. 
`SourceColumnManager` was creating a new state every time it checked for a change in the active column, rather than when the active column changed. 
See repro notes on original issue.
> Prevent excessive set_client_state calls

- src/cpp/session/modules/SessionGit.cpp
Closes https://github.com/rstudio/rstudio/issues/7912.
`git show` doesn't show a diff in some cases. Since we ultimately just want a diff, let's ask for a diff.
Check the Git History tab (as described in https://github.com/rstudio/rstudio/issues/7912) to confirm that changes files (and those changes) are properly shown.
> use 'git diff' rather than 'git show' when showing diff

- src/cpp/session/modules/SessionGit.cpp
- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/insert_citation.tsx
- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/source_panels/insert_citation-source-panel-crossref.tsx
- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/source_panels/insert_citation-source-panel-datacite.tsx
When typing search terms in the crossers search, the search list would begin showing 'no items' prior to the user hitting the search button. The user has not yet searched, so the status should remain the default status.
In addition, both DataCite and Crossref didn't properly display the 'No Results' message when there were no matching results.
Finally, if the search was taking a long time and the user navigated away from a DataCite and Crossref search, we weren't ignoring the response/search results when they finally appeared.
The selectedPanelProvider wasn’t being passed to a memoized callback, which means that the provider was captured at the time the callback was memoized. Instead, pass the provider so it reflects the current state.
(in this case, what this meant was that the wrong the …
> Improved status, no results, and cancellation of Datacite and Crossref Searches in Insert Citation

- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequestContext.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
In some cases (especially in high-latency environments), attempts to insert completions would produce a "wrong" completion result. For example:
- The text would be duplicated; producing `stats::ac` -> `stats::acacf()` rather than `stats::acf()`;
- The wrong portion of text would be replaced; e.g. `stats::rn` -> `stats:rnorm()` rather than `stats::rnorm()`.
In particular, the issue normally occurs when:
1. The user requests completions (either automatically, or explicitly via TAB);
2. The user immediately begins typing new characters,
3. The completion response is received, and the popup is shown.
In particular, the completion engine was not handling the new characters added (or removed) in (2) cleanly.
The issue was caused by some incongruences in the autocompletion context being used. …
> fix issues with completion insertion in high-latency environments

- NEWS.md
- src/cpp/session/modules/SessionRCompletions.R
Autocompletion of function argument names could fail when piping in an object to an S3 generic function.
We normally try to retrieve function arguments from two locations:
1. The S3 method that would normally be dispatched to, if we can determine which method that is;
2. The S3 generic itself.
However, in the case where our attempts to find a method in (1). fail, we would end up with no completion results at all. This PR alleviates that by falling back to (2) when (1) fails.
Test via example described in https://github.com/rstudio/rstudio/issues/7060. Be sure that the `tidyr` package is installed and loaded when testing.
> fix autocompletion of formals for piped-to S3 generics

- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/src/org/rstudio/core/client/virtualscroller/VirtualScrollerManager.java
- src/gwt/src/org/rstudio/core/client/virtualscroller/VirtualScrollerNative.java
- src/gwt/src/org/rstudio/core/client/virtualscroller/virtualscroller.js
Fixes #7712 
Currently, only in Desktop mode as far as I can tell, the server doesn't always accurately prune the data as per the 1000 line single element hard cap that it thinks it's doing. This difference can be observed by watching the `set_client_state` updates. Even when the server is being overzealous in Desktop mode the VirtualConsole will prune this information so it matches the server.
The VirtualScroller will now prune elements as they're added as well as after a full submit loop in the VirtualConsole is run.
Ensure that we're only seeing roughly 1000 lines within a single element as per the example in the issue above. This should match the functionality of having the VirtualConsole disabled as well ("Limit console output to a subset of content" setting).
> Prune overflow data in Virtual Scroller

- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/src/org/rstudio/studio/client/common/CommandLineHistory.java
- src/gwt/src/org/rstudio/studio/client/common/debugging/ui/ConsoleError.java
Fix traceback showing up while the VirtualScroller is turned on. Also fix an out of bounds error that existed before the VirtualScroller was added.
Fixes #7928 
The ConsoleError element is its own VirtualConsole that cannot and should not be virtualized. Luckily the flag that I added for disabling that functionality came through in a pinch here. 
I also found an out of bounds error that would cause the traceback to be added to a floating element outside of the error message itself or, in the case where there was not later element to be found, throw a null pointer error and not display at all. This was unrelated to VirtualScroller.
Ensure that the traceback shows properly when the VirtualScroller is both on and off, as shown in the issue linked above.
> Show debug traceback while VirtualScroller is turned on

- src/gwt/panmirror/src/editor/src/optional/ace/ace.css
Fixes https://github.com/rstudio/rstudio/issues/7925.
We can't actually unselect content in Ace when it blurs (we may need to act on the selection later), but we do need to hide it, which we do here with CSS. 
CSS-only change, visual impact only.
> Hide selected word outline when not focused

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
Closes https://github.com/rstudio/rstudio/issues/7932.
Avoid using the integer key code property, as the actual underlying key may differ depending on the user's selected keyboard layout.
Test via notes in https://github.com/rstudio/rstudio/issues/7932.
> fix insertion of ':' when completion popup showing w/AZERTY keyboards

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextCodeUi.java
Fixes https://github.com/rstudio/rstudio/issues/7936. 
Ensure that the pinned line widget (which is how we get Ace to draw the toolbars on chunks in source mode) always has a host.
Low-risk change. Note that the repro is fairly sensitive to initial conditions; I was able to reproduce reliably with the exact steps in #7936, but not when I altered the steps even a little (e.g., had more than one chunk or if I ran the chunk).
> Ensure line widget for toolbar in source mode always has a host

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputGallery.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
Fixes pro-issue #2007 https://github.com/rstudio/rstudio-pro/issues/2007
The height used for the iframe displaying html from a chunk callback should be based on the entire document.
Previously this height was based on the html body which was leading to the callback displaying with too short of a height.
> Fix height for html chunk callbacks 

- src/cpp/r/R/Api.R
Closes https://github.com/rstudio/rstudio/issues/7965.
Set missing arguments to `NULL`, to avoid issues with testing the type of such arguments.
Test via the blogdown -> Insert Image addin.
> properly handle missingness of arguments

- src/gwt/src/org/rstudio/studio/client/common/CommandLineHistory.java
- Fixes #7945
- Caused by #7942, thus started with build 1.4.893 (any platform, desktop or server)
Backed out one line of that change, a range-check on command line history that was added. Unclear to me why it was added though there was a comment saying "I also found an out of bounds error that would cause the traceback to be added to a floating element outside of the error message itself or, in the case where there was not later element to be found, throw a null pointer error and not display at all. This was unrelated to VirtualScroller."
Validate scenarios in both issues (#7945 and #7928)
> fix navigation of console history with arrow keys

- src/cpp/session/modules/SessionPackages.R
- src/cpp/session/modules/SessionProjectTemplate.R
- src/cpp/session/projects/SessionProjectContext.cpp
- src/cpp/session/projects/SessionProjects.cpp
A previous PR (https://github.com/rstudio/rstudio/commit/05f2af6940f12df057f0094690c35ebdecff810a) refactored the way first-run documents were added, but the associated changes did not propagate to the R-level API usages of those functions.
Adapt the R methods to the recent refactor.
Test via notes in https://github.com/rstudio/rstudio/issues/7940.
Closes https://github.com/rstudio/rstudio/issues/7940.
> fixups for rs_addFirstRunDoc

- src/gwt/panmirror/src/editor/src/marks/emoji/emoji.ts
This fixes rstudio/rstudio#7950
Mark was being applied only to the first emoji in a string of identical emoji when fixups occurred.
iterate through until all matching characters have proper mark applied
Good catch, thanks!
> Properly note all instances of a single emoki (not just the first one)

- src/gwt/src/org/rstudio/core/client/ClassIds.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java
The term quadrant is now out-dated because users can have multiple source columns. 
Functions, variables, ect. including the word `quadrant` will remain as is. We agreed to use "panel" as the public facing word, but this word is already heavily used behind the scenes.
> Remove public facing use of "quadrants"

- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
The JS + CSS diagnostics systems bundled with RStudio are fairly old at this point, and provide false positives when using more modern idioms. Since we're too late in the release cycle to update these components, we should just disable them.
Flip the default preference for these settings from `true` to `false`.
Validate that 'Show diagnostics for Javascript HTML, and CSS' is off by default:
and that diagnostics are not shown in JS / CSS / HTML files.
> disable JS / CSS diagnostics by default

- src/cpp/session/modules/SessionSVN.cpp
- Fixes #7959
- On Windows, an SVN commit message containing non-ASCII characters was being mangled by a Windows encoding conversion.
- NOTE: this appears to have always been broken, so if we have any concerns about risk (or testing cost) we could consider punting this to 1.5
- svn works internally in utf-8, and we don't do any conversion of the (utf-8) string we get from the user, so make sure it doesn't get converted to another locale on Windows by specifying that it is already utf-8
Test scenario described in issue. I used https://tortoisesvn.net/ to install svn on Windows (be sure to include the command-line tools, which aren't installed by default).
Note that this change doesn't fix previously mangled commit messages, only new ones. Try a variety of characters in commit messages and …
> fix svn commit message encoding issue

- src/gwt/panmirror/src/editor/src/api/navigation.ts
- src/gwt/panmirror/src/editor/src/api/outline.ts
- src/gwt/panmirror/src/editor/src/api/rmd.ts
- src/gwt/panmirror/src/editor/src/behaviors/outline.ts
- src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorWidget.java
- src/gwt/src/org/rstudio/studio/client/panmirror/outline/PanmirrorOutlineItem.java
- src/gwt/src/org/rstudio/studio/client/panmirror/outline/PanmirrorOutlineWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextPanmirrorUi.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeNavigation.java
This change does a couple of things.
First, it provides a visual mode implementation of the status/navigation bar in visual mode, and the accompanying *Jump To* command. This makes it possible to jump quickly to different parts of the document without using the outline. 
It also makes the document outline chunk-aware in visual mode. Prior to this change, the document outline only showed headings in visual mode. It now respects the same preference that source mode does, and can show headings only, headings and named chunks, or everything.
Closes https://github.com/rstudio/rstudio/issues/7891.
Most of the work here is on the GWT side, where we use the VisualMode to supply an outline for the navigation widget. There's also a new `sequence` property on navigation items over on the panmirror …
> Implement missing status/nav bar and chunk navigation in visual mode

- src/gwt/panmirror/src/editor/src/api/event-types.ts
- src/gwt/panmirror/src/editor/src/editor/editor.ts
- src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorEvent.java
- src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorWidget.java
- src/gwt/src/org/rstudio/studio/client/panmirror/events/PanmirrorBlurEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
Note that moving focus into an embedded code chunk counts as "blur". While this is mildly inconsistent I don't think it's objectionable and removing this inconsistency would be IMO not be worth the time/effort/added complexity..
> enable auto save on blur for visual mode

- src/gwt/acesupport/acemode/rmarkdown.js
- src/gwt/acesupport/acemode/rmarkdown_highlight_rules.js
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/DelegatingCompletionManager.java
Older versions of RStudio allowed the R completer to provide completions within inline R code chunks. Losing that functionality was not intentional; this PR brings it back.
Properly delegate to the R completion manager if we detect the cursor is within an inline R code chunk.
Create an R Markdown document, and then test that R code completions are popped up for text of the form:
```
`r st|`
```
Also comes with R highlighting of inline R code chunks, because ... why not.
Closes https://github.com/rstudio/rstudio/issues/8013.
> allow R completion manager in inline R code chunks

- src/cpp/session/modules/SessionHelp.R
Currently, UTF-8 encoded help is not displayed correctly in autocompletion tooltips. It would be neat if it did.
Ensure that HTML help retrieved for a package is marked with the encoding declared in that package's DESCRIPTION file.
Test with the package at https://github.com/kevinushey/nihao -- install it with:
```
remotes::install_github("kevinushey/nihao")
library(nihao)
nihao::
```
and confirm that Help documentation is displayed as expected. Note that this needs to be tested on Windows.
> infer appropriate encoding when reading HTML help documentation

- src/cpp/session/modules/SessionReticulate.R
Closes https://github.com/rstudio/rstudio/issues/7999.
The 'detect changes' code maintains a cache of known objects in a Python module, and updates when that changes; however, we need to initialize that cache when the environment pane is first populated.
Test via notes in https://github.com/rstudio/rstudio/issues/7999.
> update detect changes cache when reading environment state

- NEWS.md
- src/cpp/r/RExec.cpp
- src/cpp/r/include/r/RExec.hpp
- src/cpp/r/session/RStdCallbacks.cpp
- src/cpp/session/http/SessionHttpConnectionUtils.cpp
- src/gwt/src/org/rstudio/studio/client/application/ApplicationInterrupt.java
- src/gwt/src/org/rstudio/studio/client/application/model/ApplicationServerOperations.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionInstallOdbcHost.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/model/ConsoleServerOperations.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/model/DataImportServerOperations.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressDialog.java
Currently, when R requests input from the user via `readline()` or `readLines(stdin())`, there is no way to interrupt the read -- the R session is effectively stuck and the user is forced to restart the session.
This PR makes it possible to exit that state.
Closes https://github.com/rstudio/rstudio/issues/3448.
Previously, we tried to "guess" whether the appropriate action was to send a "true" process interrupt, or to try and send a "console" interrupt, based on the state of the prompt. This fails when R attempts to read input from the user without setting a prompt, as in `readLines(stdin())`.
To properly handle this, we now:
1. Always send a so-called "interrupt" RPC;
2. If the R session appears to be busy, then we interrupt it; if not, then we send a console-level interrupt.
Test that …
> make it possible to interrupt readLines(stdin())

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/dialog/SVNReviewPanel.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/dialog/SVNReviewPanel.java
- Fixes #6031
- The "Discard All" button on the Subversion diff view was almost completely hidden and only reachable if you used Tab key to move focus to it
- Has been broken this way since RStudio 1.1
- Tweaked CSS layout to match how this was displayed in RStudio 1.0
- As per the issue, you'll need an RStudio project using Subversion for source control, then in the SVN tab click on "Diff" and look at the toolbar area between the upper and lower panes
- Should now look like this with the Discard All button to the right of the Context dropdown
> Fix layout of Subversion diff viewer secondary toolbar

- src/cpp/r/RCntxt.cpp
- src/cpp/r/include/r/RCntxt.hpp
- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/session/modules/environment/SessionEnvironment.cpp
When R byte-compiles a function, the context that is placed on the stack is slightly different in form. In particular, the `srcref` field associated with the context is replaced with an `<in-bc-interp>` marker, and the "true" source references need to be resolved separately.
Detect byte-code contexts, and resolve their contexts by finding the associated R system call + function on the stack, and retrieve the source reference from the matching call object.
Test via notes in https://github.com/rstudio/rstudio/issues/6922, but also worth running the "regular" debugger test suite to ensure this doesn't regress elsewhere.
Closes https://github.com/rstudio/rstudio/issues/6922.
> properly resolve sourcerefs for bytecode contexts

- src/cpp/session/resources/dependencies/r-packages.json
Fixes https://github.com/rstudio/rstudio/issues/7935.
Removes packages that are no longer dependencies of R Markdown.
The primary use of this package list is to ensure everything is installed correctly for R Markdown to work correctly, so a good test would be to start with an empty R package library, create a new R Markdown doc, and make sure it can knit after all the packages are auto-installed.
> Remove superfluous R Markdown package deps

- src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorWidget.java
Increase the delay when changing themes so that visual mode doesn't try to sync before the main editor is finished loading. I noticed that the MathJax icons weren't showing up only when I changed themes. After increasing this delay I was no longer able to repro the issue. I would prefer if we weren't just setting arbitrary delays but this small tweak to what we have right now is the safest option.
~~Fixes https://github.com/rstudio/rstudio/issues/7947~~ Edit: I had a shower thought that this actually just fixes a different bug I found while investigating 7947. I'm going to request more information from the bug reporter to confirm. 
Ensure that when switching from a light to a dark theme without a restart properly loads the colors with visual mode open and that you can see the inline math …
> increase the delay for syncing the pan theme with the editor

- src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
Addresses an issue in which the visual editor becomes blank when changing the pane layout. Fixes https://github.com/rstudio/rstudio/issues/7952.
The problem is that the visual editor widget tears down the underlying Panmirror editor `onDetach` -- that is, when its widget is detached from the DOM by GWT, which happens during a re-layout. When the widget is later reattached, it no longer has any underlying editor.
The fix is to avoid doing anything special `onDetach`, as it may be temporary; instead, we only destroy the Panmirror editor instance when the tab is closed. 
This is a slightly less robust way of ensuring that the editor gets cleaned up, so worth testing briefly around various switch/close scenarios to ensure that there isn't an obvious leak, esp. with larger documents.
> Preserve visual editor widget when changing layouts

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.ui.xml
Fixes https://github.com/rstudio/rstudio/issues/7984.
In source mode, the font size is set in chunk outputs via a `FontSizer` CSS class applied to the outer editor. No such class is applied in visual mode, so we apply this class to each individual chunk output to ensure it gets the correct font size.
This change only affects CSS styles used in visual mode, so verification of correct appearance is all that's needed here.
> Use normal font size for chunk outputs in visual mode

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
Fixes https://github.com/rstudio/rstudio/issues/7991.
Code-related commands (like Execute Selection) are disabled in visual mode (unless you're in an embedded editor), but were not always enabled immediately when switching back to source mode. This change ensures they're turned back on when re-entering source mode.
This code runs on mode switch and when deactivating the edit surface entirely (e.g., for a tab switch), so ensure that code-related command state tracks those actions.
> Enable code commands when leaving visual mode

- dependencies/common/install-packages
- dependencies/common/install-packages.cmd
When embedding R packages, we use the old-style `Github*` fields for indicating the package source. Those are not supported by `renv`, and `devtools` and friends have supported the `Remotes*` syntax for some time now, so use that instead.
Straightforward use of new `Remotes*` syntax.
No test required.
> use new-style remotes format for embedded packages

- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/PythonCompletionManager.java
Closes https://github.com/rstudio/rstudio/issues/8037.
Detect and remove `\` line continuations when building a completion context for Python completions.
Test with Python code of the form:
```
import numpy as np
np. \
a<TAB>
```
You should see:
> handle '\' continuations in help, completions

- src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java
- src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java
When working in Python mode, the prompt is set to `>>> `. Upon restart, we return to "R" mode, but we don't reset the prompt, giving the indication that the user is still in Python mode.
Allow the Shell widget to listen for restart events, and reset the prompt after a restart has occurred.
Test by:
1. Activating Python mode, e.g. by running code in a Python script,
2. Restarting the session.
Closes https://github.com/rstudio/rstudio/issues/8011.
> reset prompt on session restart

- src/cpp/r/R/Tools.R
When the `cpp11` package is loaded, it places an environment on the search path that causes a segfault when one attempts to serialize it.
Don't serialize it.
Test via notes in https://github.com/rstudio/rstudio-pro/issues/2052.
Closes https://github.com/rstudio/rstudio-pro/issues/2052. Note that ultimately I believe this needs to be fixed in `cpp11` somehow, but this is at least an interim solution.
> avoid serializing cpp11 preserve env

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Fixes https://github.com/rstudio/rstudio/issues/7833, in which the editor toolbar does not update fully when changing the output format of an R Markdown document.
We avoid reloading the editor toolbar every time you save because when that happens during autosave it's very disruptive (due to side effects, not the toolbar itself). However this also means that the editor toolbar doesn't adapt to the finer points of the current document without being reloaded; only big changes in file types (e.g. R to Shiny R or Rmd to Notebook) are detected.
However, there's no need to run in this lean mode when autosave is disabled (and anecdotally autosave is popular with only a small minority of users), so this change re-introduces the full reload as long as autosave is off. 
There is still a scenario …
> Always adapt to extended type when not autosaving

- src/cpp/session/modules/SessionReticulate.R
Closes https://github.com/rstudio/rstudio/issues/8010.
Use non-standard evaluation to evaluate a call of the form `View(<name>)`, so that the RStudio viewer can infer the appropriate object name in the viewer.
Test via notes in https://github.com/rstudio/rstudio/issues/8010.
> ensure nice title given to viewed DataFrames

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorMixins.java
On Linux, when a selection is made within an Ace editor instance, the "primary" clipboard selection (tracking the last-selected text in any application) typically receives a truncated copy of the selection, as per notes in https://github.com/rstudio/rstudio/issues/1667#issuecomment-708069511.
We had a fix for this particular issue, but it attempted to set the clipboard selection too eagerly -- we would set the clipboard contents, and then get overwritten by the wrong / truncated version (likely by the window manager detecting and setting the clipboard selection itself). The fix, then, is to just defer setting the clipboard text.
Test via notes in https://github.com/rstudio/rstudio/issues/1667#issuecomment-708069511 -- in particular, try using middle-click pasting to select and paste text …
> defer setting of global mouse selection

- src/cpp/session/resources/dependencies/r-packages.json
We recently took a new drop of the rmarkdown package to get Pandoc 2.11 support. This release comes with some new supporting package version requirements, which we need to ask the IDE to install. 
Fixes https://github.com/rstudio/rstudio/issues/8063.
Update the version these packages in the dependency installer and docs.
The best way to test this is to start with an old version of xfun installed; ensure that RStudio prompts you to update it if you try to create/preview a notebook.
> Update package versions for new rmarkdown

- src/cpp/session/modules/rmarkdown/NotebookQueue.cpp
Closes #8076.
Validate `execContext_` is not `nullptr` when we use it.
Test that execution of inline R chunks works.
> check for null execContext when executing chunk

- src/gwt/acesupport/acemode/rmarkdown_highlight_rules.js
The [cpp11] package provides a new way to use C++ code within R packages. This PR allows us to support highlighting of `cpp11` chunks.
Tweak the engine regex to allow for arbitrary digits after the engine name. (future-proof ourselves for the release of `cpp2050`)
Test that R Markdown chunks of the form:
`````
```{cpp11}
#include <cpp11.hpp>
```
`````
are highlighted as though they are C++ code.
> allow digits after rcpp / cpp engine name

- src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputGallery.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
Fixes #8008 
Prior to this fix scrolling over chunk callback output would do nothing and interrupt scrolling occuring on the editor. Now the iframe will forward `mousewheel` or `wheel` events to the editor so it can handle the scrolling.
Since the iframe was not triggering the scroll event, the iframe forwards wheel events to the editor -- ace editor was coded to trigger scroll events from these. Due to browsers handling the wheel events differently, we need to check which event is supported to set the listener. I ran into an issue with Chrome where if listeners were set for `wheel` or `wheel` and `mousewheel` the scroll wasn't triggered so `mousewheel` is used as the preferred event.
A similar approach can be used to fix #2202 but since that would require some additional logic I didn't …
> Forward scrolling from chunk callback to editor

- src/cpp/session/projects/SessionProjectContext.cpp
Instruct the file monitor to ignore the larger `revdep` folders, as well as files and folders marked as `.noindex`.
Add these as ignored components for the set of ignores used when listing files.
No testing required; this is a "Hadley feature".
Closes https://github.com/rstudio/rstudio/issues/8090.
> file indexer ignores revdep, .noindex files / folders

- src/cpp/session/modules/SessionDiagnosticsTests.cpp
- src/cpp/session/modules/SessionRParser.cpp
- src/cpp/session/modules/SessionRParser.hpp
Closes https://github.com/rstudio/rstudio/issues/6886.
Quoted tokens were not being properly de-quoted in some of the diagnostics system's parse routines.
Test via notes in https://github.com/rstudio/rstudio/issues/6886.
> properly extract symbol names from quoted symbols

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Fixes #7861 
The `Close Other Documents` command was broken by the multiple columns code -- if the user was prompted to save any other document prior to closing, the wrong document was left open.
The code existed to save the editor prior to executing commands that could reset the active editor, but it wasn't actually being used.
See original ticket.
> Fix 'Close All Except Current' command

- src/cpp/session/SessionMain.cpp
Currently, the "abnormal end" (abend) flag is set somewhat late in the process, and so doesn't catch all cases wherein the R session might fail to start. Notably, it doesn't catch failures to launch that occur while attempting to deserialize session state, or load RStudio's own session modules.
Set the abend flag just before running R.
Not quite sure how to test this with QA...
Closes https://github.com/rstudio/rstudio/issues/7983. Note that we don't necessarily need to take this for 1.4.
> set abend flag before running R

- src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java
Packages which display content in the Viewer pane might want to be able to refresh the current page being shown by the viewer. Currently, a refresh implies reloading the initially-opened page, which means navigation done within the Viewer is lost.
Attempt to reload the page as-is, and fall back to setting the frame URL if that fails (e.g. because of CORS).
I believe @yihui and @cderv will be able to verify this independently. Note that this will only work on RStudio Server, and this works because we use proxy URLs (and so don't fall victim to CORS restrictions there).
Note that if this PR is accepted, you should be able to test via `rstudioapi::executeCommand("viewerRefresh")`.
> attempt to reload Viewer page on refresh

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java
Fixes #8088 
When a document was created before a new source column and later had its mode changed, the highlighted background indicating a chunk was properly aligned with the chunk. 
Layout changes for additional columns require existing source columns to detach and re-attach. Prior to this fix, the highlighter's event handlers were removed when detached but never added back since this wasn't necessary prior to 1.4. 
See original ticket.
> Fix chunk highlighting issue

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Fixes #8102 , #8103 
#8095 broke the `Close All` command by accessing a variable the could be null. This PR adds the null check. 
Only check the variable when it is null; in this case we do not want to exclude any editors from being closed. 
Clear steps to reproduce are on tickets mentioned.
> Fix issues with Save All command

- src/cpp/CMakeLists.txt
Mac package builds should include the postgreql dependencies in the generated bundle, otherwise the application may not run on a non-developer machine.
On some configurations this was not happening, and cmake was deciding these libraries are part of the system and not including them. Specifically, find_library was resolving to:
`PQ_LIB:FILEPATH=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/lib/libpq.tbd`
Hardcode path to library on macOS only. Confirmed with a local build that this results in all dependencies going into the resulting package build.
Dev / build thing, nothing to test
> hardcode location for POSTGRES librarys on macOS

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Fixes #6475 
The continuation of #7861, containing the fix for Windows. Fixes issue where `Save / Save As` could be disabled after popping out a document. 
Consolidated similar `disownDoc` functions so that they both reassign the active editor after a document is disowned. This resets which commands are enabled based on the active editor's type.
Repro steps are in #6475 - behavior should be consistent across all OSs.
> Windows: Reset active column after document pop-out

- src/cpp/shared_core/FileLogDestination.cpp
Fixes #7898.
Ensure that we are able to log to a file from the server even after we daemonize.
It's not enough to test the goodbit/state of the output stream because even it doesn't know it's in a bad state until a real write has been attempted. Writing an empty string is not sufficient.
To resolve this, each time we write a log to the stream, we check the goodbit on the stream. If the goodbit is not set, we re-open the stream and re-attempt the write operation. Most of the time, the goodbit is good and the stream will not be re-opened.
This issue only affects the rserver process. If the logger for the rserver process is configured as described in #7898, the log should contain more messages than just `20 Oct 2020 00:16:28 [rserver] INFO Reading rserver configuration from …
> Ensure log file gets reopened if needed

- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/source_panels/insert_citation-source-panel-list-item.tsx
A user reported that they expected shift+click to result in adding a citation to the basket (which makes sense given that this is a frequently a multiselect gesture). This change will make that happen.
A small change to check the shift on the click event and use that to determine what to do.
This change is low risk as the code path for adding an item to the basket it already used extensively, so this is just calling that code path when shift clicking.
> Add support for shift click

- src/cpp/desktop/Info.plist.in
Added LSApplicationCategoryType key to Info.plist.in so RStudio Desktop is identified in the Developer Tools category (e.g. for Screen Time reports)
> Added LSApplicationCategoryType key to Info.plist.in

- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
Closes #8107 
Adding or removing a column should not affect other instances of RStudio the user is running. Previously any changes made to the `additional_column_count` in `global-prefs.json` were made immediately, but now changes are only made on startup and when the IDE is writing to the preference file. This allows the column state to be saved between sessions, while preventing columns being added/removed in an active session without user prompt.
I removed the `panes` user preference handler that was syncing the two instances. Now the column count is only updated when requested by the user in that session.
If the user ends a session with three columns, their next session should start with three columns. However, when running two instances of RStudio, the column counts should not be in …
> Unsync source column count 

- src/cpp/session/modules/SessionCodeTools.R
Closes https://github.com/rstudio/rstudio/issues/8123.
Use `[[` rather than `$` to avoid partial matching on R object names.
Test that other YAML headers of the form `runtime_*` don't trigger warnings on save.
> avoid partial matches when accessing front matter

- src/cpp/r/R/Diagnostics.R
Travis API keys are currently not redacted in the diagnostics report. This fixes #8134 
Add the TRAVIS to the list of key words. 
As `_` are removed from the [contents](https://github.com/rstudio/rstudio/blob/291c992854e1c8372dfde650e2813aea5cd17699/src/cpp/r/R/Diagnostics.R#L75), I've removed `_` from the list of key words
---
Agreement completed as requested.
> Redact Travis API keys

- src/cpp/session/modules/SessionFind.cpp
Global replace was silently failing when the file was on a different machine than RStudio. This was reported in #7736 which I'm leaving open until we can get confirmation from the user that it is fixed as there has been lots of back and forth. 
Pass the `overwrite` flag to the move command when performing the replace; otherwise cross-machine moves that overwrite a file are prevented. 
Perform find and replace where the file containing the replace is not on the same machine as the IDE.
> Fix cross-device global replace

- NEWS.md
- src/cpp/r/RCntxt.cpp
- src/cpp/r/RCntxtUtils.cpp
- src/cpp/r/include/r/RCntxt.hpp
- src/cpp/r/include/r/RCntxtInterface.hpp
- src/cpp/r/include/r/RIntCntxt.hpp
- src/cpp/r/include/r/RInterface.hpp
- src/cpp/r/include/r/session/RSession.hpp
- src/cpp/r/session/RStdCallbacks.cpp
- src/cpp/session/SessionConsoleInput.cpp
- src/cpp/session/SessionConsoleInput.hpp
- src/cpp/session/http/SessionHttpConnectionUtils.cpp
- src/cpp/session/modules/SessionConsole.hpp
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/events/ConsoleInputEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/model/ConsoleServerOperations.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
Currently, it is not possible for R scripts to read user input via `readLines()`, as RStudio doesn't provide any mechanism for sending an EOF.
Make that possible, by:
- Allowing `Ctrl + D` in the console to send a special "EOF" console input,
- Refactor the various console input classes to accept a set of flags, rather than an implicit "cancel" action.
Test that multi-line input can be read via `readLines()`, e.g. by executing the following:
```
readLines()
Hello!
Pleased to meet you.
<Ctrl + D>
```
---
Closes #3448.
> use Ctrl + D to send EOF when readLines active

- src/gwt/panmirror/src/editor/src/editor/editor.ts
- src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorSetMarkdownResult.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
Addresses a variety of intermittent off-by-one errors reported when executing code in visual mode. Fixes https://github.com/rstudio/rstudio/issues/7946.
The underlying problem is that when switching to the visual editor, we create the visual editor's contents from the source editor's markdown as-is.... then we re-write the source editor's markdown to be canonical. This can move chunks to different lines, and as we don't do another AST -> markdown conversion on execution (technically it's unnecessary) the usual method used to enforce sync before execute doesn't run. 
When changing the contents of the source editor into canonical format, perform the work that's usually done when we change the markdown in the source editor: get the outline from Panmirror and synchronize it with the new scope …
> Synchronize scope tree after setting canonical source

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
Fix multine expr case documented in https://github.com/rstudio/rstudio/issues/8156.
When finding the 'start' of the current expression, don't step back off the current row when looking for a right bracket.
Test via notes in https://github.com/rstudio/rstudio/issues/8156. See also test cases in https://github.com/rstudio/rstudio/blob/master/src/gwt/test/test-multiline-expr.R.
Closes #8156.
> check that we didn't step off row when building range for multiline expr

- src/cpp/desktop/DesktopMainWindow.cpp
- src/cpp/desktop/DesktopMainWindow.hpp
- src/cpp/desktop/DesktopSessionLauncher.cpp
- src/cpp/r/session/RStdCallbacks.cpp
Fix the issue that @kfeinauer raised when verifying #7742, as well as a second issue that we found while diagnosing the first.
1st issue: The "Cannot connect to R" page is displayed instead of "Error Starting R" because the session exits before the "Cannot connect to R" page has been displayed.
2nd issue: The R Suicide message is not sent to stderr, which means the real reason that the session failed (cannot access `~/.local/share/rstudio`) is not displayed on the "Error Starting R" page.
* Use a mutex and a flag to ensure the race condition always resolves as we desire (once the Error page is displayed, don't load another over top of it).
* Write the R exit reason string to `std::cerr` before exiting the session so the `rstudio` process can retrieve and display the message.
This is what …
> Fix a race condition when displaying the R error page

- src/cpp/desktop/DesktopOptions.cpp
Restore RStudio's appearance on MacOS + Qt 5.15. Fixes https://github.com/rstudio/rstudio/issues/8157. 
This appears to be broken because Qt isn't detecting any fonts on MacOS (no known cause). When we detect no fonts, we fall back on `sans-serif`, which renders poorly with our UI. As a temporary measure, this change allows us to use Lucida Grande (our preferred font) even if it isn't detected. 
You could uninstall Lucida Grande if you really want to be evil with this one. This should result in the display of a system sans-serif font like Helvetica (as it did before the change).
> Use Lucida Grande as a fallback on macOS

- src/gwt/acesupport/acemode/c_cpp_matching_brace_outdent.js
Fix https://github.com/rstudio/rstudio/issues/8165.
The C++ outdent check tried to search for an opening bracket of type `paren.keyword.operator`; however, rainbow parentheses drop the `keyword.operator` types. In this case, we really should just look for a token with the `paren` type.
Test that outdenting of C++ code works as expected, both with rainbow parentheses enabled and disabled.
Closes https://github.com/rstudio/rstudio/issues/8165.
> handle rainbow paren tokens in C++ outdent

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/SpellingPreferencesPane.java
When the dictionary language is changed (particularly, if new languages are downloaded and installed), one can get into a state where the set of dictionaries available on the client are then out-of-sync with what is actually available to the session.
The simplest fix to this is to just request the user restart their session if they've changed the spellchecker language.
Fixes part of https://github.com/rstudio/rstudio/issues/7218#issuecomment-713770620.
Request that the user restarts after changing the dictionary language.
Check that you are prompted to restart after changing the dictionary language.
> require restart after changing spelling language

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java
Reverts rstudio/rstudio#8093
See comments on #8088. This fix seems to have done more harm than good as now there are issues happening with the standard editor in a single column. I'm reverting this  for now and will work on a new fix.
> Revert "Fix chunk highlighting issue"

- src/gwt/panmirror/src/editor/src/api/bibliography/bibliography.ts
- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/insert_citation.tsx
Addresses 2 issues with insert citation. 
1) Fuzzy search weighting - we elevate the weight of the citation key and move other less important fields into a secondary bucket. This results in better search matches in most scenarios.
2) Fix a bug whereby empty brackets could be inserted into document when user doesn't select a citation and presses 'insert' in the insert citation dialog.
Adjust weights, wrap the actual insert work of the insert citation dialog with a conditional that requires a selection.
I was only able to reproduce the bug in desktop, the steps to repro are outlined in the commit message.
> Visual Mode Insert Citation Fixes

- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectEditingPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/ProjectPrefs.java
The line ending preference was not properly converted from its internal integer code to the front-end string value on load.
Implement the (mirror) mapping for these integer values to String preference values.
Test via notes in https://github.com/rstudio/rstudio/issues/8169.
Closes #8169.
> properly convert line ending pref on read

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java
To properly highlight chunks before and after adding or removing a column, the Ace Editor needs to retain its `AceBackgoundHighlighter` handlers while the object detaches. 
With a single column the editor widget does not detach until it is closed so we used the `onAttachOrDetach` function to clear out any handlers. With multiple columns we will attach, detach, and reattach the widget but never want to detach the handlers. I removed the handler clean up and the attach handler as it was only responsible for clean up.
We want to try different orderings of editing markdown files, adding columns, and switching between visual and standard source mode and confirm that chunks are properly highlighted.
> Fix issues with chunk highlighting with multiple columns

- src/cpp/session/prefs/UserPrefsComputedLayer.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefUtils.java
The default PDF previewer had unintentionally been set to (No preview) with RStudio 1.4 on macOS. This was actually caused by us attempting to request a desktop synctex viewer; however, we do not bundle any such viewer on macOS.
When computing the PDF previewer preference, choose the RStudio viewer on macOS, and the default synctex viewer otherwise.
Test that, for a brand new RStudio 1.4 on macOS, that the default previewer is not set to (No preview).
Closes https://github.com/rstudio/rstudio/issues/8124.
> default to RStudio PDF viewer on macOS

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Closes https://github.com/rstudio/rstudio/issues/8186.
Ensures the `isSaving_` flag is set to `false` when a save is canceled.
Test via notes in https://github.com/rstudio/rstudio/issues/8186.
> unset isSaving_ flag on save cancel

- src/cpp/desktop/DesktopWebPage.cpp
Qt 5.14 added a new type of navigation, [NavigationTypeRedirect](https://doc.qt.io/qt-5/qwebenginepage.html#NavigationType-enum), which we were disallowing in requests to `acceptNavigationRequest()`. This PR allows us to accept redirects.
In addition, prior releases of RStudio needed to work around a Qt bug in `acceptNavigationRequest()`, which basically required us to infer the navigation type in a roundabout way. That workaround is no longer required.
**NOTE**: We should consider whether we want to always allow redirects. If a host is considered "safe", do we also want to consider their redirects (even to a separate host / origin) as safe? Or is the right fix here to just disallow the `marketo` redirect altogether? Or do we whitelist `marketo` but disallow other redirects? …
> allow Qt 5.15.x redirects

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/EditSession.java
- src/gwt/test/test-multiline-expr.R
For each line in the document, Ace tracks the current "state" for highlight rules. This is either a string for a single state, or an array giving the set of states that are active for that line. This is typically used for e.g. multi-line strings, where the state tells us that we are (for example) in a double-quoted multiline string, identified by the `qqstring` state.
When rainbow parentheses are activated, we see two main issues:
1. getState() returns an array rather than a string;
2. A dummy `#tmp` state is placed at the front of the state array.
This PR handles the two above cases, by ensuring that `getState(row)` returns whatever the "primary" state is.
Test manually with the test cases in https://github.com/rstudio/rstudio/blob/master/src/gwt/test/test-multiline-expr.R, and ensure …
> handle state arrays in getState() method

- src/cpp/session/modules/connections/ConnectionHistory.cpp
Currently, attempting to remove a single connection from the Connections history actually removes _all_ connections from the Connections history. That seems bad. We should not do that.
The issue appears to arise in the way we try to modify the JSON Array when removing a connection.
If I understand correctly, we were using the [erase-remove idiom](https://en.wikipedia.org/wiki/Erase%E2%80%93remove_idiom) here to remove a range of elements from the array, but this seems to not do what we expect here. A safe fix for 1.4 is to just create a brand new JSON array and add JSON elements to that, except for the connection to be removed.
Follow @ronblum's excellent notes in https://github.com/rstudio/rstudio/issues/8204.
Closes https://github.com/rstudio/rstudio/issues/8204.
> fix issue with removal of connection entry

- src/cpp/session/modules/SessionEnvironment.R
Fixed #8209 
Fix the `edit` call so it doesn't overwrite files when writing to a file on Windows.
We need to recognize the user is requesting to edit a file by the name being missing **or** null. Previously, we were only checking if name was missing and interpreting NULL as a string to write to the file.
See original ticket.
> Add null check to prevent overwriting file with 'NULL'

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Normally, when the editing toolbar is initialized, changes are sequenced roughly as:
- manage UI elements
- do Shiny-specific things
When the `visualMode_` object is initialized, it also calls performs the 'manage UI elements' step, so we effectively have:
- manage UI elements
- do Shiny-specific things
- manage UI elements
and that extraneous attempt to manage UI elements stomps on the Shiny-specific actions we had taken.
Re-arrange initialization so that visual mode is initialized before we update the R Markdown format list.
Test via notes in https://github.com/rstudio/rstudio/issues/8213. It may also be worth verifying that other R Markdown runtimes (e.g. from https://rmarkdown.rstudio.com/authoring_shiny_prerendered.html; `runtime: shiny_prerendered`) are handled properly.
Closes …
> update format list after loading visual mode

- src/gwt/src/org/rstudio/studio/client/plumber/PlumberAPIPresenter.java
- src/gwt/src/org/rstudio/studio/client/shiny/ShinyApplicationPresenter.java
- When running a Plumber API or Shiny App in the IDE, with the results displayed in a window, closing that window should also stop the task in the Console
- Fixes #8176
- The "unload" event isn't being fired with Qt 5.15.1, preventing notification being sent to the main window
- Fix by adding a close handler to fire the same code for both Plumber APIs and Shiny Applications
- Test scenarios described in issue for macOS using Qt 5.15, plus also re-validate same scenario when run via RStudio Server, and on desktop platforms still using Qt 5.12
> With Qt 5.15 ensure that closing Plumber or Shiny window stops the task in Console

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBar.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
Hides the cursor position when visual mode is active. Fixes https://github.com/rstudio/rstudio/issues/8174.
Hide the cursor position widget when entering visual mode, and restore it on exit.
Test switching modes as well as documents that open initially in each mode.
> Hide cursor position in visual mode

- src/cpp/core/system/PosixOutputCapture.cpp
Whenever the read end of the dup fd pipe closes, we continuously try to write to the pipe, but it will never succeed again. We should stop attempting to write in this case, and only log an error once.
It is currently unknown how this situation can occur, but it is happening for a user of Slurm sessions: see Zendesk ticket _53571_.
If a pipe error (or FD is closed), stop trying to write to it. Only log the error once and explain that output will no longer be redirected.
Fixes #8082
We are unable to reproduce this as of yet. We should ask the customer in the Zendesk ticket to verify the fix.
> Do not attempt to continue logging session output dp fd writes if the read end of the pipe closes

- dependencies/common/install-qt.sh
- dependencies/osx/install-qt-macos
Pull over some generic improvements from the aborted Qt 5.15 branch. These are minor dependency installation script tweaks.
- update install-qt.sh with latest from Qt (https://code.qt.io/cgit/qbs/qbs.git/tree/scripts/install-qt.sh); nothing new specific to our current usage but might as well update it so it's one less thing to worry about if we end up having to update Qt for some other reason
- install-qt-macos displays warning that the scripted Qt installer is only intended for build machines, not dev machines
Nothing to test; purely dev-box/build-box impacting (and very minor at that).
> pull over small script tweaks from Qt 5.15 work

- src/gwt/test/autoindent_test_cpp.html
Shake the dust off of the C++ auto-indent tests.
- Don't try to include the now-removed `background_highlighter.js` (background highlighting is done in https://github.com/rstudio/rstudio/blob/bugfix/c++-autoindent-tests/src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java, and is not relevant for these tests)
- Skip a couple more tests that aren't relevant for the open brace indentation tests.
- Make it easier to find failed tests by appending `[FAIL]` to broken tests (so once can then just search for `[FAIL]` in the document)
Nothing for QA to test; this is mainly to ensure the C++ autoindent test suite runs without errors.
Closes https://github.com/rstudio/rstudio/issues/8229.
> fixups for C++ autoindent tests

- src/cpp/session/modules/rmarkdown/NotebookOutput.cpp
Fixes https://github.com/rstudio/rstudio/issues/8227, an issue in which newly created HTML widgets in R Notebooks break when switching from source to visual mode.
This problem arises from the fact that R Notebooks have separated "saved" and "unsaved" notebook caches (which is necessary so that any changes you make can discarded if you choose not to save). Switching into visual mode triggers a save as a side effect, which moves HTML widgets from the unsaved cache to the saved cache. The URL of the iframe, however, still refers to the unsaved cache.
This is the simplest fix I could find for the problem; the idea is that when an HTTP request arrives for a resource in the unsaved cache, we first check to see if it's in the saved cache before giving up. If it is, we serve it from the saved …
> Check saved cache for notebook output

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- Fixes #8230
- Make it easier to find the "Move Focus to Terminal" keyboard shortcut in the popup keyboard shortcut reference
- Moved it to display under the Terminal group instead of the much larger "Panes" group; this is consistent with the location in the static `keyboard.htm` file
Verify that the item has moved as described via Tools / Keyboard Shortcuts Help. Be sure screen-reader mode is OFF or you don't see this pane but instead the screen-reader friendly keyboard.htm.
> move Focus Terminal keyboard shortcut reference under Terminal group

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
Ensure that newly-opened R Markdown documents can be saved.
The `newDoc()` function tried to enable / disable the Save command depending on whether the IDE already had an active editor. However, creation of a new document (usually) implies that a new editor will be created and become active, so we should check that state only after the document has been created.
Test via notes in https://github.com/rstudio/rstudio/issues/8228.
Closes https://github.com/rstudio/rstudio/issues/8228.
> always enable save commands for new source docs

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Fixes #8235 
Fixes #8236 
When we call `activateSource` it should activate the active source column instead of defaulting to the main source pane. This is called when we exit a modal and need to reactivate a source element, run the commands `switchToTab`, `switchFocusSourceConsole`, and `activateSource`, and when an API call is received to open a new document with code. 
Retrieve the active column from the `SourceColumnManager` on activation instead of defaulting to the main source pane. 
We should test that the active source column remains the same when the events above happen.
Exit a modal
- Follow repro steps in #8235 
Run `switchToTab`
- Open several documents in a column. Navigate to the View Menu and select "Switch to Tab", then select a tab. 
Run `switchFocusSourceConsole`
- …
> Activate the active source column with activateSource()

- src/cpp/core/r_util/RProjectFile.cpp
- src/cpp/r/R/Api.R
- src/cpp/session/projects/SessionProjects.cpp
When creating projects, users might specify paths using characters not representable in the current locale. To properly handle such paths, we need to ensure the paths are UTF-8 encoded.
Mostly straightforward `asString()` -> `asUtf8String()`, as well as a workaround for the behavior of `list.files()` with UTF-8 paths.
Test via notes in https://github.com/rstudio/rstudio/issues/8225 and https://github.com/r-lib/usethis/issues/1231.
Closes https://github.com/rstudio/rstudio/issues/8225.
> handle UTF-8 paths when opening projects via API

- src/cpp/session/modules/SessionFind.cpp
Closes #7736 
We received a request to increase the length of lines we'll perform a replace on so I've increased it from 1000 to 3000. While increasing this I realized an issue affecting how the replaced word gets highlighted in the IDE so this includes that fix as well. 
Perform a global search and replace on a line between 1000 and 3000 characters.
> Fix issues with global replace on long lines

- src/gwt/src/org/rstudio/core/client/command/AppCommand.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceAppCommand.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
When focus is transferred between different source windows, the state for certain commands is not always updated. This PR ensures that save commands are enabled / disabled as appropriate when an RStudio window gains focus.
Use a Window focus handler to update save commands as appropriate.
Test via notes in https://github.com/rstudio/rstudio/issues/6475.
Closes https://github.com/rstudio/rstudio/issues/6475.
> update save commands on window focus

- src/cpp/session/modules/SessionFind.cpp
When determining which characters to highlight in the Find in Files pane we need to account for multibyte characters. 
When adjusting the output of long strings we determine which characters to remove from the front based on the utf8 character values rather than bytes. 
This issue only happens with search and replaces performed on lines with over 3000 characters that include a multibyte utf8 character e.g. Я
> Handle multibyte characters in long global replace previews

- src/cpp/session/modules/zotero/ZoteroBetterBibTeX.cpp
On windows, the short connection timeout could be triggered, causing the Better BibTex integration to fail. Increase the timeout.
fixes @rstudio/issues#8241
Resolve failure to connect to Better BixTeX on Windows.
The connection to the Better BibTeX localhost server was timing out. Increase the timeout.
> Increase Better BibTeX Timeout

- src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java
When Ctrl is held down, Qt gives us malformed key events which are not interpreted properly in some cases by the visual mode editor instance.
Detect undo specifically in this case, and do some gymnastics to re-fire an undo request.
Test via notes in https://github.com/rstudio/rstudio/issues/7960. Closes https://github.com/rstudio/rstudio/issues/7960.
> fix for undo on Windows w/Qt

- src/cpp/session/modules/SessionHelp.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpStrategy.java
When scrolling through an autocompletion list, RStudio always attempts to display help for a completion item. However, some completion types (e.g. files and directories) do not have any relevant completion items. Still, we request help for these as though they were R objects, and so sometimes we ended up providing irrelevant help. For example, from RStudio 1.2:
In older versions of RStudio, we "successfully" provided the wrong help topic; in the 1.4 dailies, we erred when reading this help.
Fix the underlying issue causing the R error to appear when requesting help, and disallow help requests for file / directory / string completion items.
Test via notes in https://github.com/rstudio/rstudio/issues/8260#issuecomment-720673265. In particular, with `|` denoting the cursor position:
``` …
```
> don't display help for file completion items

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
Fixes #8277 
`Save As` was disabled whenever `Save` was disabled preventing users from renaming documents.
This bug was introduced with #8250. As mentioned in that issue, even when Save As is set properly the client side can lose sync with the desktop side causing the command to appear disabled so we need to force any updates to the command's state. Previously we were using the same logic to determine whether Save and Save As should be enabled, this PR updates the check for Save As.
There are good repro steps in the original issue. Since this was introduced with a prior fix for #6475 we should test both issues.
> prevent Save As from incorrectly being disabled

- src/gwt/panmirror/src/editor/src/optional/ace/ace-render-queue.ts
Fixes https://github.com/rstudio/rstudio/issues/8291.
The source of this bug is a while loop that is intended to skip past editors that don't need to be rendered. In some pathological (and timing-dependent) situations, the entire remainder of the render queue consists of defunct editors. When this happens, the loop spins endlessly since `shift()` returns `undefined` on an empty array.
Ensure that there are items left in the render queue before we try to skip them. 
Reproducing this bug usually requires a number of tries.
> Avoid intermittent hang on visual editor close

- src/cpp/r/RSexp.cpp
- src/cpp/r/include/r/RSexp.hpp
- src/cpp/session/modules/SessionProfiler.R
- src/cpp/session/modules/SessionProfiler.cpp
Attempts to open projects with non-ASCII characters in the pathname could fail in some cases. This was caused by an attempt to create a directory associated with a mis-encoded path on startup, which (in some cases) could be an error rather than a warning.
Ensure that the profiler path is UTF-8 encoded, and also treat errors as warnings so they don't prohibit session start.
On Windows: test that projects with multibyte characters can be created / opened.
Closes https://github.com/rstudio/rstudio/issues/8256.
> ensure profiler resources path is UTF-8

- src/cpp/core/Database.cpp
- src/cpp/core/include/core/Database.hpp
Currently, database connections are not re-established if they go defunct, such as if the upstream PostgreSQL database stops or due to transient network failure. We should restart these connections automatically.
See #8266 for more detail.
Whenever a connection is requested from the pool, quickly check to see if the state is open by running a very simple efficient query. If not, attempt to re-establish this connection, but only once. If we do re-establish the connection, use it instead of the old connection.
Fixes #8266
See #8266
> Verify connection state of PostgreSQL connection pooled connection and re-establish if necessary

- src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeCommands.java
Add JSON to the status bar widget, so that files can be edited as JSON.
Simple modification of the status bar entry list.
Closes https://github.com/rstudio/rstudio/issues/8296.
> add JSON filetype to status bar

- src/gwt/src/org/rstudio/studio/client/common/CommandLineHistory.java
When attempting to access the most recent item in the command line history, we would (on occasion) read out of bounds of our history list, leading to a JS exception.
Clamp the history offset to the range of the history list.
Reproduce via notes in https://github.com/rstudio/rstudio/issues/8293.
Closes https://github.com/rstudio/rstudio/issues/8293.
> fix offset check when reading history

- src/gwt/panmirror/src/editor/src/optional/ace/ace.ts
When the Ace cursor is moved, we need to wait for Ace to render the updated cursor before it can be scrolled into view.
Scroll the cursor into view after render, rather than after execution of a command.
Test via notes in https://github.com/rstudio/rstudio/issues/8300.
Closes https://github.com/rstudio/rstudio/issues/8300.
> scroll cursor into view only after render

- src/gwt/acesupport/acemode/r_highlight_rules.js
- src/gwt/acesupport/acemode/rainbow_paren_highlight_rules.js
In our tokenizer, we keep track of both the rainbow parentheses count as well as the complement for a raw string (if any). Those were using the same indices into the state array, and so could stomp on each other in some cases.
(Note: I experimented with both using an object to keep track of this state, as well as a "named" array, but both seemed to have problems; likely based on how Ace uses + manipulates that array. We could fix it with an Ace patch, but that's definitely out of scope for 1.4)
Use a different index for raw strings.
Test via notes in https://github.com/rstudio/rstudio/issues/8302.
Closes https://github.com/rstudio/rstudio/issues/8302.
> avoid stomping on rainbow parens state with raw strings

- src/cpp/session/modules/SessionSpelling.R
As per https://github.com/rstudio/rstudio/issues/7218, we discovered a small set of dictionaries were encoded as UTF-8, but were not actually marked with `SET UTF-8` to indicate the files themselves are UTF-8 encoded. This caused issues with certain dictionaries.
Manually fix those dictionaries, and then upload the fixed dictionaries.
Test via notes in https://github.com/rstudio/rstudio/issues/7218.
Closes https://github.com/rstudio/rstudio/issues/7218.
> use dictionaries with encoding marked as UTF-8

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Fixes #8295 
Certain combinations of opening files with "dirty" files (requiring a prompt to save) prevent `Close All Except Current` from closing all columns. 
Previously we set the active editor to keep track of the editor to leave open and reset it when a change was triggered by the prompt to save other editors. We were only resetting the variable tracking the active editor and not which editor was actually active in `DocTabLayoutPanel`. This fix selects the active editor when it is set manually.
There was also an issue with multiple columns that left all the tabs open when the current editor was in the left most column due to columns being removed while iterating the column list. We now iterate over the list of column names rather than the columns themselves to make sure we reach each …
> Fix Close All Except Current with unsaved files

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/www/docs/keyboard.htm
Old key command had a conflict with nextTab.
Fixes https://github.com/rstudio/rstudio/issues/7717
Ensure new key command Ctrl+Shift+F8 works correctly.
> Change visual mode key command from ctrl+shift+F12 to ctrl+shift+F4

- src/cpp/core/r_util/RUserData.cpp
RStudio Desktop Pro defaults cause users to install our professional ODBC drivers into the user scratch path (`~/.rstudio-desktop/odbc` in prior versions). When we migrate those drivers to the new user scratch path in RStudio 1.4, it can break user code that contains references to the full path of the drivers in the old scratch path. The intent of this change is to avoid that problem.
This changes takes the conservative approach of excluding that specific folder (`odbc`) from migration. 
Ensure that the `odbc` folder is not migrated to the new scratch path (e.g. `~/.local/share/rstudio`) and that professional drivers installed by previous version of RStudio continue to work. 
Fixes https://github.com/rstudio/rstudio-pro/issues/2065.
> Avoid migrating ODBC drivers from scratch path

- src/gwt/panmirror/src/editor/src/editor/editor.ts
- src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorEditor.java
- src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
When we render R Markdown docs, we pass the location of the cursor, which is later used to infer a slide to navigate to when previewing presentations. However, the location of the cursor in source mode is used, so it doesn't reflect the user's cursor position if they're in visual mode, resulting in incorrect slide navigation. This change addresses that issue.
Fixes https://github.com/rstudio/rstudio/issues/8301. 
This is a relatively scoped fix meant to address this specific issue. Prior to rendering R Markdown docs, we now move the cursor in source mode to an approximation of where it is in visual mode (same outline item, which is all we need for slide selection). 
This change affects only R Markdown presentations (not R Presentations).
> sync editing outline location before R Markdown render

- dependencies/osx/install-dependencies-osx
Eliminate warning messages from `install-dependencies-osx`:
```
"Warning: Calling `brew list` to only list formulae is deprecated! Use `brew list --formula` instead."
```
Supply the switch suggested by the warning message.
Purely a dev and build environment thing. Nothing to test.
> specify formula switch in brew list invocations

- src/cpp/r/R/Api.R
The stored preference value for `ansi_console_mode` changed, but the R-level accessor did not. The R-level accessor should be updated.
Handle both the old version of the preference (just in case) as well as the new, current version.
Test via notes in https://github.com/rstudio/rstudio/issues/8323.
Closes https://github.com/rstudio/rstudio/issues/8323.
> support updated ansi_console_mode pref value

- src/cpp/r/R/Tools.R
- src/cpp/r/session/RInit.cpp
On Windows, users might be working within paths / projects that cannot actually be represented in the current locale. This can cause various issues.
Use UTF-8 paths instead.
Test that RStudio functions as expected (and you can save + load an R workspace) on Windows when the path contains non-ASCII characters; e.g. letters or words from a language not using the Latin alphabet.
Closes https://github.com/rstudio/rstudio/issues/8321.
> use UTF-8 path when restoring global environment

- src/cpp/core/r_util/RTokenizerTests.cpp
- src/cpp/session/modules/SessionDiagnosticsTests.cpp
- src/cpp/session/modules/SessionRParser.cpp
Certain tokens (strings, quoted identifiers) can span multiple lines. This can cause issues in some cases where our R parser fails to properly bind the binary operator to that token.
Properly handle multi-line tokens.
Test via notes in https://github.com/rstudio/rstudio/issues/8307.
Closes https://github.com/rstudio/rstudio/issues/8307.
> handle multiline tokens with binary ops

- src/cpp/session/modules/SessionPackages.R
When a package is unloaded and later re-installed, sometimes older pieces of the previously-loaded package can stick around. For registered S3 methods, these might be promises holding data relevant only to the previously-installed copy of that package. This can cause strange errors to be emitted to the R console, and that package to fail to load, when later loading that package.
Before unloading the package, force any existing promises, so they can evaluate in the right context (and be properly re-registered / replaced when the namespace is later reloaded).
Test via notes in https://github.com/rstudio/rstudio/issues/8265.
Closes https://github.com/rstudio/rstudio/issues/8265.
> force promises in S3 methods table on unload

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPaneBase.java
The handler here was being registered on the entire widget, making it active for both the textbox and the Select button. This was preventing the Select button from reacting to Enter keypresses. 
Scope the handler to the textbox only.
Test via notes in https://github.com/rstudio/rstudio/issues/8331.
Closes https://github.com/rstudio/rstudio/issues/8331.
> register Enter handler only on textbox

- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/insert_citation.tsx
- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/source_panels/insert_citation-source-panel-crossref.tsx
- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/source_panels/insert_citation-source-panel-datacite.tsx
- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/source_panels/insert_citation-source-panel-doi.tsx
- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/source_panels/insert_citation-source-panel-pubmed.tsx
- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/source_panels/insert_citation-source-panel.ts
When searching a third party resource, check the local bibligraphy to see whether we already have the item in the bibliography (using the DOI). If we do already have it, just return that item instead of the remote item.
Fixes @rstudio/rstudio#8335
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked …
> Use DOI to Not Insert Duplicate Citations

- src/gwt/panmirror/src/editor/src/optional/ace/ace.ts
This change addresses an issue in which clicking inside a large code chunk (when the cursor is offscreen) in the visual editor can generate unwanted scroll jumping/selection.
Fixes https://github.com/rstudio/rstudio/issues/8332. 
There are two small changes necessary to resolve this issue:
1. First, we were formerly obtaining the cursor geometry from the focused element, a hidden `<textarea>`. However, the cursor the user actually sees is a painted-on `ace_cursor` element, so now we get more accurate geometry from there.
2. Second, we were scrolling the document while Ace considered the mouse to be down. Ace treats this as a selection-generating event. We now avoid trying to auto-scroll the cursor into view while the mouse is down.
The code affected here is intended to help keep the …
> Fix jumpy scroll/cursor/selection action with large code chunks

- src/gwt/src/org/rstudio/studio/client/application/DesktopHooks.java
- src/gwt/src/org/rstudio/studio/client/application/events/MouseNavigateEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Make it possible to navigate backwards / forwards using mouse buttons.
Fairly straightforward implementation of mouse handlers + JS callbacks to power the feature.
Test that your mouse's side buttons allow you to navigate forwards / backwards within the Help pane.
Closes https://github.com/rstudio/rstudio/issues/8338.
Closes #7462.
> allow forward / back in Help pane with mouse side buttons

- src/cpp/core/r_util/RUserData.cpp
Fixes https://github.com/rstudio/rstudio-pro/issues/2065. 
The previous fix https://github.com/rstudio/rstudio/pull/8305 didn't work in all circumstances; we remove the entire `~/.rstudio-desktop` folder if we detect a fully successful migration. This fix treats the `odbc` folder skip as a failure so that the `odbc` and its parent are left behind after migration.
Test via notes in #2065
> Treat odbc migration skip as a failure

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
Closes #8353 
If a source columns with unsaved files is closed, the files are moved to the main source area. However, if the main source pane was minimized this wasn't apparent so we now pop it open. 
When a file is added to a pane, ensure the pane is visible. Also added text to the Global Options pane so that the behavior is clear to the user. Depending on feedback, we may change this behavior in 1.5.
Open several files in a new column and minimized the main source pane. Add text without saving to one of the files. Remove the column from the Global Options pane and confirm the unsaved file is now visible in the source pane.
> Ensure files moved to Source Pane are visible

- NEWS-1.4-juliet-rose.md
- src/cpp/session/SessionModuleContext.cpp
Avoid attempts to enque client callbacks from forked sessions. (Most commonly, these are package events from forked processes.)
Simple check of `wasForked()` flag.
Test via notes in https://github.com/rstudio/rstudio/issues/8361.
Closes https://github.com/rstudio/rstudio/issues/8361.
> don't enque client events from forked sessions

- src/cpp/session/modules/SessionHelp.R
- src/cpp/session/modules/SessionReticulate.R
- src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTargetWidget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/cpp/CppCompletionManager.java
<kbd>F1</kbd> was not properly triggered the 'go to help' command for Python code when triggered from the R console.
Unfortunately, it seems like the underlying bug lives in `reticulate`, and may be somewhat hairy to fix (it involves different help handler code that I'm not super familiar with). Until we have that sorted out, the simplest way forward is to just have our own patch in RStudio.
Verify that help for Python objects can be requested both in Python scripts and R scripts. For example, in R:
```
library(reticulate)
np <- import("numpy", convert = TRUE)
np$random
```
And in Python:
```
import numpy as np
np.random
```
Closes https://github.com/rstudio/rstudio/issues/5982.
> ensure F1 works for Python help when triggered from console

- src/gwt/src/org/rstudio/studio/client/workbench/views/history/History.java
When a console history file is loaded, we automatically raise + focus the History pane. This is a bit too aggressive, especially in the context of reticulate since we need to switch + maintain separate history files for R + Python.
Don't raise the History pane.
Test via notes in https://github.com/rstudio/rstudio/issues/5984.
Closes https://github.com/rstudio/rstudio/issues/5984.
> don't raise History pane on console reset

- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/ConsoleLanguageTracker.java
The RStudio front-end tries to keep track of the active language (Python vs. R). However, it was not properly tracking this state following a session restart.
Since the console will revert to R after a session restart, we should also reset the tracked language to R as well.
Test via notes in https://github.com/rstudio/rstudio/issues/8357.
Closes https://github.com/rstudio/rstudio/issues/8357.
> reset to R language after session restart

- src/cpp/core/r_util/RUserData.cpp
- Fixes https://github.com/rstudio/rstudio-pro/issues/2129
- Don't migrate verify file or license file to new XDG location; leave in same location for backwards/forwards compatibility
- See issue for more details
> don't migrate license metadata

- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java
When retrieving chunk option completions, we allowed for context-related completions as well. These completions aren't relevant / useful.
Don't use context completions for chunk option completions.
Validate that chunk option completions are the same regardless of source / visual mode. Compare with screencast in https://github.com/rstudio/rstudio/issues/7697#issuecomment-727040458.
Closes https://github.com/rstudio/rstudio/issues/7697.
> exclude context completions when retrieving chunk option completions

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceVimCommands.java
- Fixes #8388
- Refactoring during addition of source columns removed handling of the "interactive" flag (and accidentally interpreted it as the "don't close active file" flag
- Now "interactive" once again means a :qa or :qall vim command will prompt about unsaved changes, and ultimately close all files
- The original code that got removed can be seen here: https://github.com/rstudio/rstudio/blob/a865ba2b2e5b4daee39d0e94d0e42c7b6088054d/src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java#L892-L923
Validate scenario described in issue.
> fix vim close-all command

- src/cpp/session/modules/SessionSource.R
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Files navigated via `file.edit()` were no longer being focused after open. 
Mark such files with the `focus_after_navigate` flag. Also provide a better fix for focus-after-navigate for visual mode.
Test that `file.edit(<path>)` opens the file at `<path>`, and also focuses the source editor after the file has been opened. Verify this occurs both in regular source documents, as well as R Markdown documents open in visual mode.
Closes https://github.com/rstudio/rstudio/issues/7832.
> ensure focus set on file.edit call

- src/cpp/r/include/r/session/RSession.hpp
- src/cpp/r/session/graphics/RGraphicsDevDesc.cpp
- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/session-options.json
R's graphic engine v14 is layout-compatible with older versions of the graphics engine, so just bump the supported version.
Version bump.
Test that plots work as expected with the development version of R (4.1.0+).
Closes https://github.com/rstudio/rstudio/issues/8383.
> support graphics engine 14

- docker/jenkins/publish-daily-binary.sh
This change addresses an issue that could cause the daily build redirects (`/latest/`) to point to the wrong build. 
Fixes https://github.com/rstudio/rstudio/issues/8105.
The underlying problem is that the regex used to match the URL to update the `.htaccess` file isn't restrictive enough. This can cause an updated link for one platform to be applied to other platforms, and the fix is simply to amend the regex with some pieces of the download link so that doesn't happen.
As a side note, careful scrutiny will reveal that there's a potential for a variety of other problems with this way of updating the daily build links (e.g. race conditions when two concurrent builds finish at once). This system is old and should be replaced, but doing so is out of scope for 1.4
Test via notes in #8105. …
> Fix issue with daily build links

- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
A recent PR (https://github.com/rstudio/rstudio/pull/8053) made some changes to ensure the console prompt was properly reset after a session restart, to avoid the case where e.g. a Python prompt was preserved even after the session restart returned to R mode.
This had the unintended side effect of causing the next-executed command to be omitted from the console history. This was due to my misunderstanding of the `addHistory` flag; I thought "surely we do not want to add the prompt to the console history" but this actually sets a flag that controls whether the next-processed command is added to the console history.
We _do_ want the next-executed command to be added to the console history, so add it!
Test via notes in https://github.com/rstudio/rstudio/issues/8391.
Closes …
> fix usage of addHistory flag

- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/www/docs/keyboard.htm
- The Ctrl+F1 through Ctrl+F8 shortcuts have existing meanings on macOS and shouldn't be used by applications
- They are either not passed through to the application at all, or come through inconsistently especially in RStudio Desktop
- Fixes #8401
- On Mac change following shortcuts from Ctrl+FKey to Cmd+FKey:
- Cmd+F1 - activate VCS pane
- Cmd+F2 - activate Build pane
- Cmd+F6 - activate Find in Files pane
- Cmd+F7 - new source column
- On Mac, get rid of shortcut for Activate Connections altogether (was Ctrl+F5 which is reserved but Cmd+F5 is used for VoiceOver on macOS; given nobody has cared don't think eliminating it will be a big problem and users can always add their own mapping)
Test that these shortcuts now work on Mac and are unchanged on Windows/Linux.
> Stop using Ctrl+FKey shortcuts on macOS

- src/cpp/desktop/DesktopMainWindow.cpp
- src/cpp/desktop/DesktopMainWindow.hpp
On rare occasions, multiple `loadFinished()` signals will be sent to the main window when attempting to load RStudio, with the first of those signal(s) setting `ok = false` with the final setting `ok = true`. This causes issues for us on load as we expect to only ever receive a single `loadFinished()` signal.
Use a timer to collect and wait for other incoming `loadFinished()` signals, to see if we eventually receive a "success" signal.
Unfortunately not sure how to reproduce consistently, but users encountering this issue will hopefully be able to report back.
Closes https://github.com/rstudio/rstudio/issues/8270.
> use timer to collate multiple loadFinished calls

- src/cpp/session/modules/SessionReticulate.R
Closes https://github.com/rstudio/rstudio/issues/8413.
Previous versions of the IDE tried to ensure that our help + matplotlib hooks were only active with the Python REPL was active. This was considered confusing, since it meant those hooks were not active when interacting with the Python session from R via the `reticulate` functions directly.
Unfortunately, when that change was made I forgot to remove the old code that cleaned up the hooks in REPL teardown, which meant quitting the REPL implied clearing hooks that were set when Python was initialized.
Test via notes in https://github.com/rstudio/rstudio/issues/8413.
> don't remove reticulate hooks on REPL teardown

- src/gwt/src/org/rstudio/studio/client/panmirror/theme/PanmirrorThemeCreator.java
Closes https://github.com/rstudio/rstudio/issues/8409.
Not all Ace themes define a `color:` for the `ace_cursor` CSS style. Some themes style the cursor by instead coloring the cursor element's border, or via other means.
For such cases, it suffices just to use a better default cursor color (white for dark themes; black for light themes).
Test that the themes enumerated in https://github.com/rstudio/rstudio/issues/8409#issuecomment-729080945 have a visible cursor in visual mode.
> set default cursor color for visual mode

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumn.java
If an empty Source Pane is opened, it gets opened with an Untitled doc. There were some cases where two documents were being opened introduced with the multiple source column code. This fixes that issue.
Increment and decrement`newTabPending_` when calling the method that checks if the document needs to be created. 
See #8429 
Fixes #8429
> Prevent extra untitled doc

- src/cpp/r/R/Api.R
- src/cpp/session/SessionClientEvent.cpp
- src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp
- src/cpp/session/modules/SessionSource.cpp
- src/gwt/src/org/rstudio/studio/client/server/model/DocumentCloseAllNoSaveEvent.java
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- When authoring Selenium automation it can be helpful to close all existing sources tabs without worrying about saving
- Fixes #8425
- Invoke from console via `.rs.api.closeAllSourceBuffersWithoutSaving()`
- Made the name intentionally long and cumbersome to reduce likelihood of accidentally invoking it
- All code added will only be hit if this internal API is invoked from Console, so very safe
> provide an internal API for closing all source tabs without saving

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Closes https://github.com/rstudio/rstudio/issues/8198.
Use parentheses to properly guard against `null` position when accessing its values. (🤦 )
Test via @R-Hannibal's notes in https://github.com/rstudio/rstudio/issues/8198.
> fix precedence in null check

- src/cpp/r/RSexp.cpp
- src/cpp/r/include/r/RExec.hpp
- src/cpp/r/include/r/RSexp.hpp
- src/cpp/session/modules/SessionObjectExplorer.cpp
- src/cpp/session/modules/SessionRMarkdown.R
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
- src/cpp/session/projects/SessionProjects.cpp
While testing on a Windows account with a user with non-English letters, I noticed a couple more issues with handling of filenames:
```
Error in file.exists(index) : 
file name conversion problem -- name too long?
Error in file.exists(index) : 
file name conversion problem -- name too long?
Error in file.exists(index) : 
file name conversion problem -- name too long?
Warning message:
In list.files(cacheDir) :
unable to translate 'C:/Users/Cr<e8>me Br<fb>l<e9>e/Desktop/renv/.Rproj.user/24A05536/explorer-cache' to native encoding
```
From what I understand, this is caused by (failed?) attempts to convert UTF-8 strings to the native encoding, as opposed to just using the UTF-8 strings as-is.
Augment our `RFunction` class with a new `addUtf8Param()` function, which is used to add strings (or …
> use UTF-8 strings in a few more places

- src/cpp/session/modules/SessionRCompletions.R
Closes https://github.com/rstudio/rstudio/issues/8423.
A recent PR regressed this:
https://github.com/rstudio/rstudio/commit/7fd3ff2ba1b579952baceaddd6fcb2ca4c88d186#diff-f198a504f201904479c929e2e53ea3c82c2e83f60bad4dc7e518249fefc41938R598-R600
The `.rs.getAnywhere()` function actually does evaluate "safe" R statements; e.g. those of the form `foo$bar`, which is necessary when retrieving completions for e.g. R6 methods since we typically have calls of the form `object$method(...)`.
With `|` indicating the cursor position, test that autocompletion results are shown as expected here:
```
test <- function(x, y, z) {}
callbacks <- list(f = test)
callbacks$f(|)
```
> fix regression in completion of methods attached to list objects

- src/cpp/r/RSexp.cpp
- src/cpp/session/modules/rmarkdown/NotebookQueueUnit.cpp
This was discovered as part of fixing https://github.com/rstudio/rstudio/issues/8435, and reverts part of an older PR: https://github.com/rstudio/rstudio/pull/7263
In particular, as part of that PR, we made a change so that strings were ~converted~ marked as UTF-8 by default here:
https://github.com/rstudio/rstudio/commit/d1289249b11e0d12d2be12b3ceb701c41f110cec#diff-1c101207d4078bdd9f5c46490672cf8b04cbbad2db4b10671ab88906af5aee26R1041
In hindsight, this isn't a great choice because it breaks our own usages of the form:
```
RFunction(".rs.foo")
.addParam(string_utils::utf8ToSystem("string")))
```
because we effectively end up with a string in the native encoding, but we mark it as though it were UTF-8.
Until we can take the time to audit usages of `RFunction` + `systemToUtf8()` (and other …
> revert to creating strings in native encoding by default

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- Fixes #8425
- Original fix didn't handle unsaved but modified buffers properly and would still prompt
- use lower-level internal API that handles this case properly 
- a fix to the original PR here: #8432
> fix closeAllSourceBuffersWithoutSaving to silently close modified unsaved buffers

- src/cpp/session/modules/SessionReticulate.R
Closes https://github.com/rstudio/rstudio/issues/8414.
Ensure our `show()` hook is injected for both of `matplotlib.pyplot` and `matplotlib.pylab`.
Test via notes in https://github.com/rstudio/rstudio/issues/8414.
> set load hook for 'matplotlib.pylab'

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
Fix chunk output throwing errors in markdown files with virtualized console turned on.
Fixes #8418 
Fixes #8416 
Just had to disable Virtualization in the ChunkOutput.
Very simple change. Should stop errors being thrown when running a simple chunk in Rmd files.
> Disable virtualized console for chunk output in markdown files

- src/cpp/session/modules/SessionPackages.R
Closes https://github.com/rstudio/rstudio/issues/8435.
Mark UTF-8 string as UTF-8 in `.rs.rpc.package_skeleton` RPC method.
Test via comment in https://github.com/rstudio/rstudio/issues/8435#issuecomment-731284135.
> mark UTF-8 encoding in package_skeleton

- src/cpp/session/modules/rmarkdown/SessionBookdownXRefs.cpp
Closes https://github.com/rstudio/rstudio/issues/8453.
Pandoc will hang if we try to run it and give an empty string as input.
Test via notes in https://github.com/rstudio/rstudio/issues/8453.
> avoid running pandoc when we have empty .Rmd file

- src/gwt/src/org/rstudio/core/client/virtualscroller/virtualscroller.js
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkInlineOutput.java
Closes https://github.com/rstudio/rstudio/issues/8465.
Disable virtualized console for outputs generated from inline code chunks. Also add a safety fix in virtualscroller.js to ensure we do have a scroller element to inspect when adding output.
Test via notes in https://github.com/rstudio/rstudio/issues/8465.
> don't use virtual console for inline chunk output

- src/gwt/src/org/rstudio/studio/client/common/mathjax/MathJax.java
Fix #7947 
Make sure that `MathJax.endRender` is called before `MathJax.renderLatex` executes. The issue was pretty easy to track down once I had a good repro, thanks Karl!
Make sure that #7947 doesn't occur anymore using the repro that Karl posted at the bottom of the ticket.
> End previous mathjax renders before starting a new one

- dependencies/common/install-common
Makes it easier to bootstrap macOS dev machines by defaulting to installation of pre-built Crashpad binaries.
On MacOS, modify the common bootstrap script so that it uses pre-built binaries by default.
Dev-only change, no product impact.
> Default to pre-built macOS binaries on dev machines

- NEWS-1.4-juliet-rose.md
- package/win32/cmake/modules/NSIS.template.in
- Fixes #8421
- Targeting Juliet-Rose since this issue has been around forever
- Turn on NSIS Unicode support
- Try installing on Windows with the setup package in a folder containing characters not in the current system language (e.g. a folder named 鬼 on an English system)
- Can do this by creating a user with that username, but also simply by creating a folder with that name and moving the setup .exe into it before running
> Fix installation from Windows path containing multibyte chars not from system codepage

- src/gwt/acesupport/acemode/c_cpp_style_behaviour.js
Closes https://github.com/rstudio/rstudio/issues/8489.
Tweak the way we detect whether `/**` is "incomplete" and so we should complete the comment with `*/`. We now perform detection based on whether the next line already has a `*` comment marker on the next line.
Test via notes in https://github.com/rstudio/rstudio/issues/8489.
> fixup C++ multi-line comment behaviors

- src/cpp/desktop/DesktopMainWindow.cpp
Potential fix for https://github.com/rstudio/rstudio/issues/8270.
Wait a little longer for a successful loadFinished() signal.
Unfortunately still not sure how to reproduce; will request further community testing.
> bump up wait time for desktop load

- src/gwt/acesupport/acemode/r_scope_tree.js
Closes https://github.com/rstudio/rstudio/issues/8495.
Don't let Markdown-style headers close chunks. This is necessary since Markdown-style headers (through R sections) can now be present within R Markdown chunks.
Test via notes in https://github.com/rstudio/rstudio/issues/8495.
> markdown headers should not close chunks

- src/cpp/r/session/REmbeddedWin32.cpp
Allow RStudio to run with development builds of R build using the UCRT. Closes https://github.com/rstudio/rstudio/issues/8461.
Rather than try to set `R_max_memory` via `cmdlineoptions()`, set it by finding the `R_max_memory` symbol and setting it explicitly.
Test that RStudio works with the UCRT builds of R published here: https://www.r-project.org/nosvn/winutf8/R-devel-win.exe
Also check that `memory.limit()` reports something "sane" -- e.g. I see on a machine with 8GB on RAM:
```
> memory.limit()
[1] 8169
```
Note that, when launching RStudio, you can hold the `Ctrl` key down to tell RStudio you'd like to pick a specific version of R before launch.
> be compatible with UCRT builds of R

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HistoryCompletionManager.java
Closes https://github.com/rstudio/rstudio/issues/7682.
The history search offset was not being properly reset. Ensure we check for a search term change before updating `lastSearch_`.
Test via notes in https://github.com/rstudio/rstudio/issues/7682.
> clear history search offset on new search requests

- src/gwt/panmirror/src/editor/src/editor/editor.ts
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
Fix https://github.com/rstudio/rstudio/issues/8513
Catch exceptions which occur when restoring positions in visual mode (can result from attempting to restore an invalid position). Generally we'd like to diagnose and fix instances of this error in a more targeted fashion, however we are now at the point of v1.4 release and the error results in an inability to switch to visual mode, so we do more coarse grained error handling here
> Ignore range errors that occur when switching to visual mode

- src/gwt/panmirror/src/editor/src/api/basekeys.ts
Fix for https://github.com/rstudio/rstudio/issues/8474
Note that this behavior was introduced in July in an attempt to enable keyboard navigation to the various text popups we have in the visual editor (e.g. the popup for links or the popup for cross references): https://github.com/rstudio/rstudio/commit/3bfe98a7287effb4d52bc6adeaa2ac284db40480#
We now ignore the tab key, but this also means that tab can't focus the text popups (at least w/o some additional custom keyboard handling that is too risky/complex at this stage of the release) so these are no longer keyboard accessible. I think we'd need to address this either in a patch release or in the next release depending on our view on the risks of the change required.
> prevent navigation when hitting tab in visual mode

- src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java
- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/src/org/rstudio/core/client/virtualscroller/VirtualScrollerManager.java
- src/gwt/src/org/rstudio/core/client/virtualscroller/VirtualScrollerNative.java
- src/gwt/src/org/rstudio/core/client/virtualscroller/virtualscroller.js
Fixes #8428 
Most specifically, the original spirit of 8428 and not what it turned into further down the line: When hitting console clear ensure that everything is cleared.
This fixes some, but not all of the causes of 8428. There are some issues that can cause items to get added outside of the VirtualScroller buckets so the old "delete items in buckets" clear wasn't sufficient. I made the cleanup much more thorough to ensure that this doesn't happen again.
I also found a couple items that could cause this issue, specifically the over-aggressive pruning and the fact that `ensureStartingOnNewLine` was not compatible with the VirtualScroller by directly modifying the DOM outside of VirtualConsole so I didn't know what was even happening.
Ensure that clear console (Ctrl+L) always clears …
> Ensure that console clear command always cleans up everything

- NEWS.md
- src/cpp/desktop/DesktopGwtCallback.cpp
- RStudio fails to open external files with spaces in their filesnames and/or paths (PDFs, Word Docs, etc.) when clicked on in the Files pane on RStudio Desktop running on Big Sur
- Fixes #8506
- The fix was to have Mac desktop use the same code as other desktop platforms for opening files; namely, `QDesktopServices::openUrl()`
- This changes how PDFs are opening; instead of forcing them to always use Preview, they will now use whatever is registered in the system (e.g. Acrobat); there was a comment about problems with Acrobat 10, but Acrobat 10 is from 2010 and current version of Acrobat works fine
More details:
- On Mac desktop only, when opening an external file, RStudio has been creating a process to run "open filename"; other desktop platforms instead use QDesktopServices::openUrl() …
> fix opening external files on Big Sur with spaces in filename or path

- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/ConsolePreferencesPane.java
Fix https://github.com/rstudio/rstudio/issues/8511
What was happening is VirtualConsole was doing in-range insertions based on the original parent instead of always relative to the original range element (that will be inside a VirtualScroller bucket). Change the `insertAfter` functions to always be relative to the original range.
Make sure that the output in the test cases Kevin put in #8428 match with Limit Console Output turned on/off.
> Ensure that VirtualConsole ranges don't write outside of VirtualScroller buckets

- src/cpp/server/ServerMain.cpp
Check that `/etc/pam.d/rstudio` exists on rserver startup, and notify the developer if it is not available.
Simple checking + writing to stderr.
Developer only; no QA required.
> check for rstudio pam profile on load

- src/gwt/src/org/rstudio/studio/client/workbench/views/packages/Packages.java
Closes https://github.com/rstudio/rstudio/issues/8524.
Tweak wording to avoid overflowing dialog box used on Big Sur.
Test that the dialog box presented when running:
```
library(MASS)
install.packages("MASS")
```
does not overflow, as the one in https://github.com/rstudio/rstudio/issues/8524 does.
> avoid dialog overflow via word-smithing

- src/cpp/r/R/Tools.R
In some cases, RStudio might mis-detect a non-writable R library as writable. This PR intends to be a bit more robust to those cases.
Rather than trust the POSIX permissions, check that we can explicitly create and remove a dummy file within the library directory. (This is necessary since, in some cases, POSIX permissions might report that a directory is writable even if the user doesn't actually have write access to that directory.)
Unfortunately, not sure how to reproduce, but this was reported as occurring with an installation of R living on a NFS.
Closes https://github.com/rstudio/rstudio-pro/issues/2184.
> use more robust test for writable library

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
Addresses an issue in which clicking into a code chunk causes wild behavior in the visual editor on browsers other than Chrome.
Fixes https://github.com/rstudio/rstudio/issues/8518. 
The problem is that, on non-Chrome browsers, Ace has an epic hack it engages to keep the scroll position from jumping around when the editor is focused. This hack works by setting the property `ace_nocontext` on _every parent element_ of Ace's input element, setting focus, and then removing the property.
https://github.com/ajaxorg/ace/blob/e9f53ddf3c789f0042d83a0c9c3163021d028159/lib/ace/keyboard/textinput.js#L119-L135
Prosemirror picks up the DOM mutations created by all of these attribute additions, which happen on ~5 different elements under its surveillance. It doesn't recognize them, and winds up …
> Fix scroll/focus issue in visual editor in non-Chrome browsers

- src/cpp/core/include/core/r_util/RTokenizer.hpp
- src/cpp/core/r_util/RSourceIndex.cpp
- src/cpp/core/r_util/RTokenizer.cpp
- src/cpp/desktop/CMakeLists.txt
- src/cpp/desktop/DesktopPosixDetectRHome.cpp
- src/cpp/session/modules/SessionRParser.cpp
- src/gwt/acesupport/acemode/r_highlight_rules.js
The development builds of R include support for a couple new language items:
- The pipe operator, `|>`;
- Shorthand for anonymous functions, `\(x) x`.
This PR implements the support necessary for these in our tokenizers + diagnostics engines.
Relatively straight-forward wiring of handling `\` the same way the `function` keyword would be handled, as well as handling `|>` in the tokenizer.
Test that scripts using the function short-hand, as well as native pipes, do not produce false positives. For example:
```
foo <- \(x, y, z) {
x |> y() |> z()
}
```
> support lambda, pipe in upcoming r-devel

- src/gwt/src/org/rstudio/studio/client/common/crypto/RSAEncrypt.java
- Fixes https://github.com/rstudio/rstudio-pro/issues/2218
- Fixes https://github.com/rstudio/rstudio-pro/issues/2219
When deciding when to encrypt input for passwords, secrets, and RSA keys, only disable for desktop sessions, not for server-based remote sessions.
Test following operations both locally (desktop), pure server (RSP or open source), and remote session (RDP -> RSP):
1. `x <- rstudioapi::askForPassword()`
2. `y <- rstudioapi::askForSecret("tell me something")`
3. Create an RSA key with a passphrase from Global Options / Git/SVN / Create RSA Key, then verify you can use the resulting key with the passphrase (e.g. try `ssh-keygen -y`)
> encrypt passwords for remote desktop sessions

- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
Closes https://github.com/rstudio/rstudio/issues/8538.
Treat option completions as special, since options are returned with the format `<name> =` and so should not be quoted.
Test that completions are appropriately inserted in `options(<TAB>`.
> don't quote option completions

- src/cpp/desktop/DesktopMainWindow.cpp
- src/cpp/desktop/DesktopMainWindow.hpp
Fixes https://github.com/rstudio/rstudio/issues/8270.
When the Desktop page fails to load, try to reload the page a couple times on the off-chance that the error occurred because the `rsession` was not quite ready yet.
Unfortunately still not sure how to reproduce consistently; will rely on community feedback.
> try reloading the IDE main page if the first attempts fail

- NEWS-1.4-juliet-rose.md
- src/cpp/r/RExec.cpp
- src/cpp/r/RSourceManager.cpp
- src/cpp/r/RUtil.cpp
- src/cpp/r/include/r/RExec.hpp
- src/cpp/r/include/r/RUtil.hpp
- src/cpp/session/modules/NotebookConditions.R
- src/cpp/session/modules/SessionRUtil.cpp
- src/cpp/session/modules/rmarkdown/NotebookConditions.cpp
- src/cpp/session/modules/rmarkdown/NotebookExec.cpp
Closes https://github.com/rstudio/rstudio/issues/8546.
Ensure that condition messages, as captured when notebook mode is active, are converted to UTF-8.
Also refactor some of the global condition handling code. Rather than build a string to be executed at the top level, we instead use a regular R function to define the associated call, and then extract the body of that function and execute that at the top level. IMHO, this makes the implementation much easier to maintain and tweak.
Also add some helper functions, `nativeToUtf8()` + `utf8ToNative()`, to be used in the future when explicit conversion is required.
This should be tested on Windows, in an R Markdown document. First, instruct RStudio to translate messages to Korean with:
```
Sys.setlocale(locale = "Korean")
Sys.setenv(LANGUAGE …
```
> convert condition messages to UTF-8 when handling in notebook

- src/cpp/core/libclang/SourceIndex.cpp
- src/cpp/session/modules/clang/RCompilationDatabase.cpp
- src/cpp/session/modules/clang/RCompilationDatabase.hpp
For projects using C++ source files, RStudio maintains some internal state describing how files in that project should be compiled. This data was not being invalidated when the compiler was changed, leading to cases where a new compiler was being used with old compiler flags, which were not always compatible and lead to issues.
Include the compiler's `--version` output as part of the compilation database, and invalidate the database if that changes. (The compiler is queried from R via `R CMD config {CC/CXX}`. This check is not perfect, but should be "good enough" for 99% of users.)
This is a bit challenging to test. You will have to:
1. Create a project using C++ sources,
2. Edit some C++ files within the project, and confirm that C++ diagnostics are working as expected,
3. Change the …
> rebuild compilation database when compiler changes

- NEWS-1.4-juliet-rose.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
Respect the accessibility setting "Tab Key Always Moves Focus" in visual mode chunks. Fixes https://github.com/rstudio/rstudio/issues/8584.
This wasn't working because the code that tracks this pref is in the `AceEditorWidget` class. The Ace instance used in the visual editor is not wrapped in an `AceEditorWidget` and so it does not track the pref.
The fix is pretty simple: we just track the pref ourselves in the visual mode chunk. 
This should track the preference not only at startup but also as the preference is changed in real time (e.g., try changing the setting in Global Options and confirm that the open editors are affected).
> Respect "tab key always moves focus" pref in visual editor

- NEWS-1.4-juliet-rose.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
Adds a new user preference which can be used to make the *Insert Pipe Operator* command insert an R 4.1 native pipe, `|>`, rather than a magrittr style pipe, `%>%`. 
Closes https://github.com/rstudio/rstudio/issues/8534.
Add the pref and consult it before inserting a pipe. 
As usual, dialog space is an issue; there was no room for this in its natural location (under Editing), so the "Save when sourcing" pref was moved to the Saving tab (arguably a more natural home) to make room. 
At some point, we may want to add this pref to the computed layer, such that instead of always defaulting to magrittr style pipes, we automatically default to `|>` when R supports it. However, since compatibility with the tidyverse (and exact R version support) are still murky, this preference is currently only …
> Add preference governing pipe operator style

- src/cpp/conf/rdesktop-dev.conf
- src/cpp/desktop/DesktopMainWindow.cpp
- src/cpp/desktop/DesktopMainWindow.hpp
- src/cpp/desktop/DesktopPosixDetectRHome.cpp
- src/cpp/desktop/DesktopSessionLauncher.cpp
- src/cpp/desktop/html/loading.html
- src/cpp/r/CMakeLists.txt
- src/cpp/session/CMakeLists.txt
- src/cpp/session/SessionHttpMethods.cpp
- src/cpp/session/SessionMain.cpp
Fix an issue where the Desktop client would be ready and attempting to connect to R before R itself was ready to receive connections.
Similar to the last approach, retry attempts to connect to the R session a couple times. This PR also makes it easier to test this case, by allowing one to instruct the R session to sleep on startup for a brief period of time (effectively simulating a "slow" session startup).
On macOS, test with the following:
```
export RSTUDIO_SESSION_SLEEP_ON_STARTUP=5
/Applications/RStudio.app/Contents/MacOS/RStudio
```
You should see a temporary "initializing R" window first:
The session should later load successfully after a brief pause.
You can also test the extreme case, with:
```
export RSTUDIO_SESSION_SLEEP_ON_STARTUP=60 …
```
> try reloading main window if R not yet ready

- NEWS-1.4-juliet-rose.md
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunks.java
Makes the "Execute Previous Chunks" and "Execute Subsequent Chunks" commands work correctly in visual mode when the cursor is outside a code chunk. 
Fixes https://github.com/rstudio/rstudio/issues/8500
Fixes https://github.com/rstudio/rstudio/issues/8275
This fix is not trivial since a good deal of plumbing is required. In particular, these (and most other) code execution commands currently presume you're already in a code editor. So here's what we do now:
1. The code that synchronizes the current code editor position has been plumbed so that it now returns the position it found, or `null` when the position isn't inside a code editor.
2. If the Execute Next or Execute Previous commands are run when the position isn't inside a code editor, we find the nearest code editor (in the requested …
> Implement previous/following chunk execution commands outside chunks

- src/cpp/rstudio-tests.in
Ensure that `rsession` tests can still run even with the changes in #8614.
Make sure `R_HOME`, `R_DOC_DIR` and `R_LIB_DIR` are always defined. In addition, force `rsession` to use a version of `libR.dylib`, since we explicitly don't link directly to the R library (so users can choose different versions of R at runtime).
No QA; this is just to get tests up and running again.
> adapt test script to changes in #8614

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
Fix https://github.com/rstudio/rstudio/issues/8618, in which C/C++ code blocks don't work in the visual editor.
This happens because the completion context for C/C++ isn't initialized inside the code chunks in the visual editor. The fix is to forward the parent editor's completion context, which gives the completion manager access to information such as the path to the file being edited that isn't available in embedded editors. 
Test via notes in #8618.
> forward C++ completion context to embedded editor

- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/modules/build/SessionBuild.cpp
- src/cpp/session/modules/build/SessionBuildErrors.cpp
- src/cpp/session/modules/build/SessionBuildErrors.hpp
Parse messages generated by testthat 3.0.0, and populate the Issues view with the parsed error messages.
Create and use an appropriate regular expression, matching lines of output emitted by testthat when errors occur. Also fix up handling of ANSI escapes from the prior implementation -- the `\033` escape code was not properly captured, leading it to be included as part of the error message. (Since it's just rendered as an invisible character, there wasn't any actual user-facing issue -- this just makes the parser itself more "correct".)
Testing this requires you to think like an R package author, using `devtools` + `testthat` while authoring your package + tests. For an R package using testthat, containing tests + errors in those tests, from the Build pane, use More -> Test Package to …
> implement parser for testthat 3.0.0 message output

- src/cpp/rstudio-tests.in
- src/gwt/src/org/rstudio/core/client/virtualscroller/virtualscroller.js
- src/gwt/src/org/rstudio/core/client/widget/BottomScrollPanel.java
- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Fixes https://github.com/rstudio/rstudio/issues/8544
Fixes https://github.com/rstudio/rstudio/issues/8504
Fixes https://github.com/rstudio/rstudio/issues/8529
Fixes https://github.com/rstudio/rstudio/issues/8552
Wanted to get #8568 also in here but there's some weirdness related to GWT going on 😢 
The weird Tibble related bugs were due to how I was counting the number of items in a bucket. A super wide Tibble is a ton of unique `span` elements that can all be on a single line. This caused the calculation of how large a bucket is to be wildly inaccurate so it didn't know if it was scrolled all the way up or down. The `isBucketFull` function in `virtualscroller.js` solves this by just counting newlines in the `innerText` which seems to work pretty well for now, though I did notice a …
> Fix various virtualscroller autoscrolling bugs

- src/gwt/panmirror/src/editor/src/api/csl.ts
- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/source_panels/insert_citation-source-panel-pubmed.tsx
fixes @rstudio#8625
-> we were previously not santizing the CSL
-> pubmed is sending a license field which pandoc is choking on (and doesn’t appear to be expected in well formed csl json, see https://github.com/citation-style-language/schema)
-> If present, we now sanitize that field out before we send the CSL to the bibliography
Pubmed is including a 'license' field which doesn't appear to be an expected part of CSL Json. When we use Pandoc to read this CSL Json, it fails because of the presence of this field.
We already sanitize the CSL that we receive from some providers (who don't always return well formed CSL). Add stripping of the license field to this sanitization and use the sanitizer when we receive CSL from Pubmed.
Bug was a great catch. Because we generate CSL-JSON/CSL-YAML …
> Sanitize the CSL that we receive from Pubmed

- src/gwt/panmirror/src/editor/src/api/cite.ts
Addresses @rstudio@#8576
Formatting an empty array of authors into a string for display should be safe to call when the array of authors is empty (not just undefined).
I was already checking for an undefined authors array before formatting, but I wasn't handling the case where the array was empty. Check that too.
> Protect against attempting to format an empty array of authors

- NEWS.md
- src/cpp/core/ProgramOptions.cpp
- src/cpp/core/include/core/ProgramOptions.hpp
- src/cpp/server/ServerOptions.cpp
When installing on CentOS, configuration related error messages do not display during the installation. This is because stderr (where we log this information) is not connected to a terminal, so it is only logged to syslog. However, if we force write these to stderr, they will properly show up.
For these startup related errors, forcefully log them to both stderr and syslog even if stderr is not connected to a terminal. This ensures that the output can be seen by a user when starting the process via the installation.
For other code paths that report errors after startup (or daemonization), do not forcefully log to stderr - we want to make sure we aren't writing to a buffer that is never going to be read from (which could cause a hang).
(Also includes some code that should have been merged …
> Always report startup configuration related errors to stderr, even if not connected to a terminal

- docker/jenkins/publish-daily-binary.sh
Fixes https://github.com/rstudio/rstudio/issues/8633.
The macOS daily build links were not being updated since the S3 URL identifies the platform as `macos`, but the redirect URLs refer to the platform as `mac`, so the fix is to correct this mismatch in the script.
No product change; test via notes in #8633.
> Fix stale daily build links for MacOS

- NEWS-1.4-juliet-rose.md
- package/win32/cmake/modules/NSIS.template.in
- Fixes #8598
- On Windows, a non-elevated (per-user) install can be triggered via group policy or by running the installer as follows:
`cmd.exe /c "set __COMPAT_LAYER=RunAsInvoker && RStudio-1.4.1100.exe"`
- The installer chooses user's documents folder as the default location; this goes against modern Windows recommendation for a per-user install (and causes problems with sync clients)
- Use the %LocalAppData%\Programs folder as the default for a per-user install
- On a Windows machine without an existing RStudio install, run the installer as shown above to trigger a per-user install
- The default folder should now be in user's %appdata%\Local\Programs folder, not in Documents
- Note to uninstall a per-user install performed this way, you must run the uninstall.exe using the same trick …
> Fix default folder for per-user install on WIndows

- src/gwt/panmirror/src/editor/src/marks/underline.ts
Fixes https://github.com/rstudio/rstudio/issues/8656
Note that this keyboard shortcut had been disabled entirely (due to conflicts with the Ctrl+U shortcut for yank before cursor) however it continued working (to a point) on OS X desktop (presumably because the contentEditable implementation in WebKit chromium or base ProseMirror was handling the shortcut?).
Since the shortcut *sort of* works on the Mac even when we don't enable it, it's better to just explicitly enabled it (on Mac only, as the other platforms still have the Ctrl+U conflict). This makes the menu paint correctly and provides the expected toggle off behavior.
We could argue that we should introduce yet another shortcut key that doesn't conflict with Ctrl+U however I don't even think underline warrants a keyboard shortcut in …
> osx underline shortcut: display in menu and toggle off

- src/gwt/panmirror/src/editor/src/behaviors/find.ts
Fixes https://github.com/rstudio/rstudio/issues/8655
The cause of the problem was using normal regex character escapes (e.g. `\-`) in a unicode regex. See discussion here: https://esdiscuss.org/topic/why-is-regexp-u-a-syntax-error
The fix is to use full unicode escape sequences (e.g. `\u002d`) rather than simple ascii character based escapes.
@jmcphers Could you review to make sure there aren't any hidden gotchas w/ this approach?
> visual editor: correctly handle finding words w/ punctuation

- src/gwt/panmirror/src/editor/src/nodes/yaml_metadata/yaml_metadata.ts
This fixes a minor but nevertheless quite annoying defect: when creating front-matter in an empty document via omni-insert the cursor ended up positioned after the yaml block. This changes the offset to get it into the center of the block where it belongs.
> improve yaml cursor position after omni-insert

- src/cpp/rstudio-tests.in
- Fixes #8685
- Purely dev environment tweak, no impact on end-user code
- Have to pass along DYLD_INSERT_LIBRARIES when running rsession via the timeout command
- This worked as-is for at least one person, theory being that having SIP disabled is a factor
- Move along. Nothing to see here.
> fix running rsession unit tests on macos

- NEWS-1.4-juliet-rose.md
- src/cpp/session/modules/plumber/SessionPlumber.cpp
- Fixes #8118
Light-up IDE plumber integration when newer tags are seen, not just the original plumber tags.
Updated the regex based on list from plumber team.
Validate scenario as described in #8118
> detect newer plumber tags

- NEWS-1.4-juliet-rose.md
- src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java
- Fixes #8490
- Fixes #8491
- Ensure appropriate messages are handled so the tooltip can be updated, and that the underlying filename is updated in satellite windows
- Note that both of these issues have been around forever, just easier to notice now that there's a rename command on the tab context menu in v1.4-juliet-rose
- Test scenarios described in issues, both on desktop and server
- Note known quirk #8726; always been this way
> update filepath tooltip when renaming file in main or secondary window

- NEWS-1.4-juliet-rose.md
- src/gwt/src/org/rstudio/core/client/command/EditorCommandManager.java
- src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
- src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
- src/gwt/src/org/rstudio/studio/client/common/filetypes/events/CopySourcePathEvent.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/model/FilesServerOperations.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- Fixes #7289
- IDE's typically have a way to copy the path of an open file via context menu, now we do, too
- Also added to command palette as "Copy Document Path" for keyboard-only use
- Went for simplest approach, just copy the entire path, including filename, to the clipboard
- On Windows Desktop, a leading `~` will be resolved to a full path, since this isn't a native concept on Windows, but on Server, other desktop platforms, and RDP remote sessions, the `~` will be left as-is
- Test in source columns and in popped-out satellite source editors using both Command Palette and tab context menu
- Test in a variety of browsers; the code I'm using for copying came from [stackoverflow](https://stackoverflow.com/questions/400212/how-do-i-copy-to-the-clipboard-in-javascript) and seems to …
> Add Copy Path to editor tab context menu

- NEWS-1.4-juliet-rose.md
- src/cpp/session/modules/SessionRParser.cpp
- src/cpp/session/modules/SessionReticulate.R
When a session is restarted, it's possible that some R objects acting as proxies for Python objects are saved and then later restored as null pointers. We need to handle these specially to avoid errors on restart, as reported in https://github.com/rstudio/rstudio/issues/8185.
Check for null pointers up-front and handle them specifically.
Test via notes in https://github.com/rstudio/rstudio/issues/8185.
Closes https://github.com/rstudio/rstudio/issues/8185.
> properly handle Python null pointers when building Environment pane

- dependencies/common/install-common
Running `install-dependencies-osx` on Mac should successfully install the dependencies including pre-built crashpad. It does not and the attempt to build crashpad always fails.
This was partially fixed in #8467 but that didn't account for fact the install-dependencies-osx script invokes install-common with the --install-crashpad-sudo option
Added some basic command-line parsing to install-common for future expansion, and made it do the right thing.
Purely a dev / build environment thing, nothing to test.
> fix osx dependency script to correctly install prebuilt crashpad

- NEWS-1.4-juliet-rose.md
- src/gwt/src/org/rstudio/core/client/command/AppCommandBinding.java
- src/gwt/src/org/rstudio/core/client/command/KeyCommandBinding.java
- src/gwt/src/org/rstudio/core/client/command/KeyMap.java
- src/gwt/src/org/rstudio/core/client/command/ShortcutInfo.java
- src/gwt/src/org/rstudio/studio/client/palette/AppCommandPaletteSource.java
Addresses https://github.com/rstudio/rstudio/issues/8735, in which some commands in the Command Palette show the wrong shortcut if they have multiple shortcuts that depend on the editor mode. 
This bug exists because we look up all the key bindings for a command, but not all of them are necessarily active in the current mode. The fix is somewhat verbose but conceptually simple: we now plumb the command binding through to the command palette, and query it to see if it's enabled in the current mode before adding it to the palette. 
All shortcuts should now be correct; test via notes in #8735. Ensure that user-created shortcuts are still shown, ideally in preference to built-in shortcuts.
> Fix incorrect shortcuts for some commands in the Command Palette

- NEWS-1.4-juliet-rose.md
- src/cpp/session/modules/tex/SessionCompilePdf.cpp
Resolves https://github.com/rstudio/rstudio/issues/8725.
Avoid command line quoting / escaping issues by just writing the associated R code to a file, and then running that script via an R sub-process.
Test via notes in https://github.com/rstudio/rstudio/issues/8725.
> fix issue with rendering .tex documents with tinytex on Windows

- src/cpp/core/StringUtils.cpp
Ensure that unicode inputs are handled correctly when the Python REPL is active.
When escaping unicode text as console input, use an escaping format that is compatible with both the R and Python REPLs.
Test that the following can be run from a Python script on Windows:
```
print("안녕")
print("你好")
```
---
https://github.com/rstudio/rstudio/issues/8549.
> use Python-compatible unicode escapes

- dependencies/common/install-qt.sh
The official Qt download server is offline with a severe failure. Point our script at a mirror until that gets resolved.
Syncing the script with latest Qt version (not strictly necessary for what we care about but I already had that in place) and changed the server URL. Also stopped looking for Qt6 and older Qt5 paths to reduce server load and speed up timeouts.
Purely dev/build change. If we get builds, then this worked.
> point Qt download script at a mirror

- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java
Address issues:
#8740  
#8567
The focus bug was confusing me quite a bit. Turns out MacOS treats focus differently than Windows. Windows is very aggressive about making sure that the most obvious TextArea/Input will get focus even if you don't set it in the JS, MacOS is....much less forgiving. The fix was trivial, just allow the old focus code to run and only skip the "scroll to bottom" portion.
For the pruning issue I turned back on the code that I had removed when fixing the Clear Console issues. I think I was just a little too exuberant about removing code that didn't seem to be necessary.
The only potential problem area I see is possibly Clear Console getting into some funky states with the pruning put back in. I tested it in a handful of cases but I could have missed something.
For …
> VirtualScroller: prune fix, MacOS click focus fix

- src/cpp/desktop/DesktopMain.cpp
Hopefully ties off the rest of https://github.com/rstudio/rstudio/issues/8549#issuecomment-767174211.
> prefer UTF-8 IO for Python on Windows

- src/cpp/session/modules/SessionPythonEnvironments.R
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/python/PythonInterpreterSelectionDialog.java
Addresses https://github.com/rstudio/rstudio/issues/8551.
- Ensure Python path is UTF-8 encoded, as this is the expected encoding for our front-end UI.
- Don't display "invalid" interpreters in the dropdown list.
Test via notes in https://github.com/rstudio/rstudio/issues/8551.
> fixups for Python environments on Windows

- src/cpp/session/SessionConsoleProcessSocketTests.cpp
Boost 1.75 landed in Fedora rawhide, and apparently #8606 is not enough. As discussed there, we see
```
/builddir/build/BUILD/rstudio-1.4.1103/src/cpp/session/SessionConsoleProcessSocketTests.cpp: In member function 'bool rstudio::session::console_process::{anonymous}::SocketClient::connectToServer()':
/builddir/build/BUILD/rstudio-1.4.1103/src/cpp/session/SessionConsoleProcessSocketTests.cpp:249:55: error: '::_1' has not been declared
249 |                                           &client_, ::_1, ::_2));
```
That piece of code declares the use of websocketpp's placeholders and then avoids using them with `::_1` and `::_2`, and this is what fails in Fedora. This simple patch uses boost placeholders directly.
You can see a successful build here: …
> fix building with boost 1.75 (2)

- src/cpp/session/modules/SessionPythonEnvironments.R
- src/cpp/session/modules/SessionReticulate.R
- src/gwt/src/org/rstudio/studio/client/events/ReticulateEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/Console.java
This PR ensures that the Stop button is displayed in the Console Pane when the Python REPL is busy, and clicking that will interrupt the associated Python computation.
Addresses https://github.com/rstudio/rstudio/issues/8763.
Addresses https://github.com/rstudio/rstudio/issues/8785.
Listen for reticulate "busy" events, and use those to control the display + enabled-ness of the R interrupt command (which is handled appropriately when `reticulate` is running).
Note: requires the development version of `reticulate` for interrupt support. Install it with:
```
remotes::install_github("rstudio/reticulate")
```
Then, try running a Python script with the contents:
```
import time
time.sleep(30)
```
and check that the associated computation can be interrupted. …
> allow user to interrupt Python REPL

- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
- src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenu.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchTabPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/svn/SVNPane.java
The tab context menus don't have unique ids for automated testing. For example, this menu shown when I right-clicked on a tab in the editor region:
Added unique ids both for the context menus themselves, and for the commands in the menus. Only worrying about the commands on the new workbench tab context menus added in v1.4-juliet-rose, but I did add ids on the existing context menus for Git and SVN.
This is to facilitate implementing automated tests per https://github.com/rstudio/rstudio-ide-automation/issues/143.
Nothing to validate, I will be authoring automation to use these IDs.
> add unique IDs to workbench tab context menus and commands

- src/cpp/session/modules/SessionDiagnosticsTests.cpp
- src/cpp/session/modules/SessionRParser.cpp
Addresses https://github.com/rstudio/rstudio/issues/8822.
Don't warn when stepping over whitespace following a `{` or a `(`.
Addressed via automated tests for parser.
Verify via notes in https://github.com/rstudio/rstudio/issues/8822.
> be more permissive with whitespace for braces / parens

- NEWS.md
- src/gwt/acesupport/acemode/c_cpp_style_behaviour.js
Addresses https://github.com/rstudio/rstudio/issues/8770.
Fixed a regression caused by https://github.com/rstudio/rstudio/commit/fc8f151b583ae780610fe11d851b9aa6624ad4a0#diff-31013968227dcb90d3326f826589a8ebb0b4bc2e28c0591d4576ff0dc1d86e42 -- the access was accidentally renamed from `.column` to `.col`.
To be done later, filed here: https://github.com/rstudio/rstudio-ide-automation/issues/151
In a C++ file, try inserting `{` followed by a newline, and verify that:
(1) A closing `}` is inserted, and
(2) It is formatted appropriately.
https://user-images.githubusercontent.com/1976582/106065332-063b6b00-60b0-11eb-95a8-e133b9f496e3.mov
> properly access cursor column attribute

- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/tests/testthat/test-debugger.R
Addresses https://github.com/rstudio/rstudio/issues/5158.
Normally, deparsing a call is cheap, as the only things embedded in a call object are symbols, calls, and literals. However, some calls (notably, those generated when a function is invoked via `do.call()`), will be very expensive to deparse, as deparsing those implies also deparsing the objects embedded in those calls.
Similarly, the "expression" associated with the promise of such a call might not actually be an expression, as `do.call()` can force early evaluation of its arguments -- and so R generated a promise mapping to an already-evaluated expression; that is, the expression is just the requested value itself.
Detect and handle both of these cases when opening the debugger. …
> fix issue with debugger hang when using do.call()

- NEWS.md
- src/cpp/session/SessionConsoleInput.cpp
Unfortunately, 1.4 has a pretty ugly regression -- lines can be submitted out-of-order in some cases, if the user quickly submits multiple pieces of console input while the R console is busy. See https://github.com/rstudio/rstudio/issues/8837 for details.
This PR seeks to rectify that.
Addresses https://github.com/rstudio/rstudio/issues/8837.
When fixing up console input, we now:
1. Take the next console item at the front of the deque,
2. Create a vector of pending console items,
3. Replay those onto the front of the deque
thereby preserving the order of input in the console input queue even after splitting.
Tracked in https://github.com/rstudio/rstudio-ide-automation/issues/159.
Test via notes in https://github.com/rstudio/rstudio/issues/8837. A simple way to test is with this script -- …
> avoid rearranging console input when fixing newlines

- NEWS.md
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/widget/FormCheckBox.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/model/FindInFilesState.java
Adds a "Whole word" option to Find in Files to be consistent with our in-editor Find / Replace. This allows the user to search for a complete word or phrase.
Added a "Whole word" checkbox and field to the Find in Files state. When checked, the frontend passes the query to the backend as a regular expression padded with `\b` tags e.g. `\bsearchphrase\b`. The backend doesn't know the difference between a regular express and whole word query. 
For simplicity's sake the user cannot enter a regular expression when the Whole word box is checked to prevent unexpected results. The thought is that if the user has a more complicated query than they'd likely want to include the `\b` tags themselves. 
rstudio/rstudio-ide-automation#155 includes the infrastructure for testing the Find in Files Dialog …
> Add word option to Find in Files

- src/cpp/session/modules/NotebookConditions.R
Addresses https://github.com/rstudio/rstudio/issues/8834.
Because the code we execute when managing the handler stack runs in the global environment, we need to be careful to avoid defining any R variables.
https://github.com/rstudio/rstudio-ide-automation/issues/157
Create an R Markdown document, then run an R chunk with no code. Confirm that the Environment pane doesn't see `envir` or `handlers` variables added.
Note: this bug only exists in 1.4-JR (not part of 1.4) so doesn't need NEWS.
> avoid defining variables when manipulating handler stack

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
Addresses https://github.com/rstudio/rstudio/issues/8683.
Don't use the initial working directory from the sessionInfo object, as that might resolve to a project-specific path and hence become sticky globally.
Tracked in https://github.com/rstudio/rstudio-ide-automation/issues/165.
Following Jonathan's instructions in https://github.com/rstudio/rstudio/issues/8683#issuecomment-763191294 to reproduce, and check that the associated issue no longer manifests.
> don't read initial working directory from sessionInfo

- NEWS.md
- src/cpp/session/modules/SessionPythonEnvironments.R
Many users and system administrators will install multiple copies of Python into the `/opt` folder; e.g. as:
```
/opt/python/3.7.2/bin/python
```
This PR makes it possible for RStudio to discover Python installations in such paths.
Addresses https://github.com/rstudio/rstudio/issues/8852.
Relatively straightforward searching of `python` and `python3` executables within a set of common root paths.
None yet.
TODO: Need instructions for installing Python into locations like `/opt/python`.
> discover python installations in common locations

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/findreplace/FindReplaceBar.java
Requested in #7295
In RStudio 1.3 (and newer) I made most UI controls accessible via keyboard tab sequence, and accessibility rules are that the tab key should move through controls in the same order they are represented on screen.
Some users prefer the old behavior in the Find panel, where hitting tab when focus is on the "Find" text moves directly to the "Replace" text, skipping over the "Next/Prev/All" buttons. Currently you must tab through those controls (so 4 presses of tab key instead of one).
Added a user preference to reenable the old behavior and conditionally set the exact same behavior found in RStudio 1.2 and earlier. Preference is shown as "Tab key moves focus directly from find text to replace text in find panel" in the command palette. I did not add it to the Global …
> option to enable legacy tab key behavior in editor's Find panel

- src/gwt/src/org/rstudio/studio/client/workbench/ui/MainSplitPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneConfig.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
Address testing feedback from #8460.
The (sometimes) invisible Presentation tab caused the Pane Manager to act as if a tab was being displayed when one was not. I updated the code to consider a TabSet with only the Presentation Tab present while Presentation is not active to be empty. With additional testing, I realized minimizing panes to hide them wasn't sufficient when both sets were empty and in the same column so I updated the code to adjust the splitter in this case. 
rstudio/rstudio-ide-automation#150
> fix bugs when changes applied to Pane Layout

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/NotebookQueueState.java
Addresses #4238, in which chunks cannot be queued for execution if they have never before been executed. 
Every chunk has a unique ID, which it receives when it is executed for the first time. Queuing a chunk for execution involves placing its ID into the execution queue. However, if the chunk has never been run, it doesn't have an ID, and is not placed on the queue. The fix is to allocate an ID for the chunk so that it can be placed in the queue. 
This is a UI only change that cannot be covered by the current unit test infrastructure. 
The affected code runs only when you run a chunk while other chunks are executing; test the scenario in both visual and source mode as they're both affected.
> Allow never-executed chunks to be queued for execution

- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/files/filedialog/OpenProjectDialog.java
- src/gwt/src/org/rstudio/core/client/widget/CheckBoxHiddenLabel.java
- src/gwt/src/org/rstudio/core/client/widget/FormCheckBox.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilePathToolbar.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/ChooseEncodingDialog.java
Most checkboxes in the UI don't have unique IDs for automation. Recently added `FormCheckBox` class to make this easier; use it in a few more places to serve as example.
Gave a handful of checkboxes unique element IDs. Specifically:
Note that last dialog is only used from RSP with multi-session support enabled.
These will be used to author automation, don't require specific automation of their own.
Nothing to test here unless you want to view the HTML and confirm that these new IDs are assigned to the elements (which I've done with my own ad-hoc testing). Even if they weren't, somehow, nothing would currently break.
> add unique element IDs to some checkboxes

- src/cpp/session/modules/SessionSource.cpp
- src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
- src/gwt/src/org/rstudio/studio/client/server/model/DocumentCloseEvent.java
- src/gwt/src/org/rstudio/studio/client/server/model/RequestDocumentCloseEvent.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- Addresses #8856
- Fixed by connecting into message flow that more closely matches the existing "Close" action (via [x] or File / Close, etc)
- Backed out small addition I had made to RequestDocumentCloseEvent for this scenario now that I'm not using it
PR for Selenium test that fails due to this issue, and passes once this is in, here: https://github.com/rstudio/rstudio-ide-automation/pull/175
Try to close a modified source file via "Close" on context menu and ensure you are prompted to save the changes.
> ensure Close of modified file via context menu prompts to save

- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/tests/testthat/test-debugger.R
Addresses https://github.com/rstudio/rstudio/issues/8885.
Avoid mangling pairlists in calls, which are used specially in function calls and in printing.
testthat tests included with PR.
Validate via code example in https://github.com/rstudio/rstudio/issues/8885.
> avoid mangling function call expressions

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
- Addresses #8855
- Bug was triggered when last document (i.e. document that last had focus) was in different source column than the document whose tab context menu was used to invoke "close all others"
- As code looped through the columns and editors, the check to see if a given document was the one that wanted to stay open only worked if that document was in the same source column as the last active document
- We already passed in the column containing the given tab, so use it for the test in addition to the "active column" (note, I'm not 100% sure we need to do both, but taking the lowest risk approach here)
- https://github.com/rstudio/rstudio-ide-automation/issues/178
- Try various combinations of opening multiple documents in multiple source columns, then right-clicking on tab and …
> fix issue with "close all others" context menu sometimes closing everything

- src/gwt/src/org/rstudio/core/client/VirtualConsole.java
- src/gwt/src/org/rstudio/core/client/virtualscroller/VirtualScrollerManager.java
- src/gwt/src/org/rstudio/core/client/virtualscroller/VirtualScrollerNative.java
- src/gwt/src/org/rstudio/core/client/virtualscroller/virtualscroller.js
There are two different kinds of ways to add text to the console: adding new elements and appending to existing elements. Before this PR we only scrolled to the bottom in the first situation. The intent is to always scroll to the bottom now
Addresses: https://github.com/rstudio/rstudio/issues/8504
Always check the scroll status in the VirtualConsole.submit function and use a larger window for detecting whether we are near the bottom.
No automated tests added for this at the moment.
Verify that we always properly keep the scrolling at the bottom with all permutations of "Limit Console Visible" on and off with these two lines:
`while (TRUE) { message("polluting the console"); Sys.sleep(0.5) }`
`while (TRUE) { print("polluting the console"); Sys.sleep(0.5) }`
Also that it stops scrolling if …
> Better autoscrolling with Virtualized Console

- NEWS.md
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/ModuleTools.R
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/cpp/tests/testthat/test-environment.R
- src/cpp/tests/testthat/test-files.R
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
Addresses https://github.com/rstudio/rstudio/issues/8658, in which the file `.renvignore` needs to be shown in the Files pane (it is currently hidden). 
Technically we could have just added this to our growing hard-coded whitelist, but this change adds a little more flexibility. The list of files we always show and extensions we always show is now configurable (only via config files). This makes it possible for users or administrators to force specific files to show up in the Files pane. 
It is also now possible via configuration to make the Files pane just show all hidden files or none of them by using empty option values. In this way, it addresses https://github.com/rstudio/rstudio/issues/3221.
Of course we could have gone even further and added additional prefs/UI to make such …
> Make always-shown files and directories configurable

- NEWS.md
- src/cpp/session/modules/SessionRSConnect.R
- src/cpp/session/modules/SessionReticulate.R
- src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
- src/cpp/tests/testthat/test-reticulate.R
- src/cpp/tests/testthat/test-rsconnect.R
Addresses https://github.com/rstudio/rstudio/issues/8854, in which reticulated R Markdown files don't inherit the active Python version when knitting. 
As we do for published content (#8636), detect the active Python version and pass it as the environment variable `RETICULATE_PYTHON` to the clean R session that performs the knit.
No new tests, but this is a thin wrapper on an existing Python detection mechanism that does have a test. For clarity, this test and the underlying method have been moved the the Reticulate module (formerly was in the publish codepath which was kind of a weird spot for something that's now shared). 
Test via notes in #8854. Try switching Python versions (in Global Options or Project Options) and re-knitting to see changes.
> Use active Python version when knitting

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Addresses https://github.com/rstudio/rstudio/issues/6421.
When choosing whether we should continue a comment on a newline, we validate that the associated line is made up of only whitespace and comments. This catches the case where our comment pattern might match something (ie, a Markdown header) which isn't truly tokenized as a comment.
https://github.com/rstudio/rstudio-ide-automation/issues/181
Test via notes in https://github.com/rstudio/rstudio/issues/6421 -- this PR should be low risk.
> avoid continuing comment after Markdown header

- src/cpp/shared_core/json/JsonTests.cpp
Addresses https://github.com/rstudio/rstudio/issues/8891.
This code generates a noisy compiler warning. As far as I can tell, it is not needed since any self-assignment that would cause a bug would also trigger the same warning. 
This change removes an automated test that generates a compiler warning.
No product change; QA not needed.
> Remove self-assignment test (compiler warning)

- src/cpp/tests/testthat/run-tests.R
In the latest versions of testthat, the `test_dir()` function now emits an R error if any tests fail. Fortunately, this behavior can be configured.
Set `stop_on_failure` to `FALSE`, as we don't want an R error emitted in that case.
Developer only change.
None.
> adapt to changes in testthat 3.0.0

- NEWS.md
- src/cpp/session/modules/SessionRAddins.cpp
Addresses https://github.com/rstudio/rstudio/issues/8012, in which malformed R addins cause hard-to-diagnose errors at startup. 
Log the path to the addin that raised the parse error.
Note that #8012 also suggested that we log the path for a tutorial error, but that was already addressed by https://github.com/rstudio/rstudio/commit/0d075310a5350c4a083ec90e5599f672a7072a37.
This is an upgrade to a log message, which doesn't warrant a test.
Test via notes in #8012.
> Emit addin path where error occurred

- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java
Addresses https://github.com/rstudio/rstudio/issues/8769, in which the secondary toolbar in the Environment pane is a little out of alignment.
Nudge it with CSS. Now it lines up:
Style-only change, no change to logic.
Ensure that these elements align real nice now.
> Baseline align language selector

- NEWS.md
- src/gwt/panmirror/src/editor/src/optional/ace/ace.ts
Addresses https://github.com/rstudio/rstudio/issues/8883, in which executing a code chunk that is nested inside a list item can cause the visual editor to scroll up unpredictably (often to the very top of the document). 
The underlying issue is that the math that computes scrolling offsets (used to ensure that at least some of the code chunk output is visible after it runs) does not account for the fact that the parent of the code chunk might not be the document.
Before scrolling, walk up the DOM tree until we find the `pm-content` element, which represents the content that will ultimately be scrolled. 
There is currently no automation support for the visual editor. See https://github.com/rstudio/rstudio-ide-automation/issues/106. …
> Account for nested code chunks when scrolling visual editor

- src/cpp/r/R/Api.R
- src/cpp/session/modules/SessionSpelling.cpp
- src/cpp/session/modules/SessionSpelling.hpp
Addresses https://github.com/rstudio/rstudio/issues/7658.
See comments in https://github.com/rstudio/rstudio/issues/7658#issuecomment-774334584. This PR hence provides 3 new APIs:
- `.rs.api.bundledDictionariesPath()`: The path to the dictionaries bundled with RStudio.
- `.rs.api.extraDictionariesPath()`: The location where updated versions of the bundled dictionaries would be downloaded.
- `.rs.api.userDictionariesPath()`: The location where user-specific dictionaries should be placed.
I'm also not a fan of the name `.rs.api.extraDictionariesPath()`; let me know if you can think of more appropriate name. (`allDictionariesPath()` also doesn't feel quite right)
None yet.
Not sure if this requires QA verification? 
NOTE: intentionally not adding NEWS; updates would be made visible as part …
> provide APIs for accessing different dictionary paths

- src/cpp/core/include/core/http/AsyncServerImpl.hpp
Fixes a rare crash when stopping the async http server.
This appears to be caused by attempting to accept a TCP/IP connection after we have already stopped the acceptor service. The fix is to NOT attempt to accept more connections after we have stopped the acceptor (pending accept gets operation aborted error code).
This was noticed in the launcher unit tests, and tested this fix over the long weekend with no crashes (previously crashes every few hours).
None
None - primarily impacts unit tests.
> Fix segfault occuring when shutting down the async server in a small amount of cases

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/core/client/widget/Toolbar.java
- src/gwt/src/org/rstudio/core/client/widget/ToolbarButton.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java
This change makes the Environment pane respond gracefully to resizes, even at very narrow widths. Addresses https://github.com/rstudio/rstudio/issues/8959. 
The Environment pane now has a number of width breakpoints. At full width, it looks like it does today:
When it gets cramped, `Import Dataset` becomes simply `Import`.
At even narrower widths, the `Import` button loses its label entirely:
And at the most constrained, there's only one label; everything else is just buttons.
As a bonus, toolbars now emit resize events, making it easier to add graceful resize to other toolbars.
This change is purely visual (no impact on functionality or logic) and does not deserve automated testing.
Check that the toolbar shrinks as advertised above, and grows correctly in the opposite direction. 
No …
> Graceful resize for Environment pane toolbar

- NEWS.md
- src/cpp/desktop/DesktopInfo.cpp
Addresses https://github.com/rstudio/rstudio/issues/6894, in which you can't use the most popular coding fonts (e.g., Fira Code) on RStudio Desktop for Linux.
As noted by the original commenter, this is a consequence of way we form `fc-list` call we make to enumerate fonts on Linux. We need two `fc-list` calls to enumerate the fonts correctly. 
This one-line fix only applies to certain Linux system configurations and is not appropriate for a unit test.
Test via notes in https://github.com/rstudio/rstudio/issues/6894.
> Include dual cell coding fonts on Linux

- src/gwt/src/org/rstudio/core/client/RUtil.java
- src/gwt/src/org/rstudio/studio/client/common/ConsoleDispatcher.java
Addresses https://github.com/rstudio/rstudio/issues/6004.
Define and use a helper function for submitting something as an R string literal.
None yet; this is easily testable on the GWT side so I'll add those.
Test via notes in https://github.com/rstudio/rstudio/issues/6004 -- in particular, confirm from the main menu that `Session -> Set Working Directory -> ...` works as expected for paths containing quotes.
> use consistent escaping scheme for R string literals on front-end

- NEWS.md
- src/cpp/session/modules/SessionConnectionsInstaller.R
- src/cpp/tests/testthat/test-connections.R
Addresses https://github.com/rstudio/rstudio-pro/issues/2284.
Deal gracefully with the case where this file is missing; return empty data instead of an error.
Adds new unit tests which test parsing a basic `odbcinst.ini` file and check this specific failure case.
Test via notes in https://github.com/rstudio/rstudio-pro/issues/2284.
> Fix issue with driver installation when ~/odbcinst.ini is missing

- src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
- src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/dialog/HistoryPanel.css
Addresses https://github.com/rstudio/rstudio/issues/8983. 
Fix regression from https://github.com/rstudio/rstudio/pull/8964. It turns out that SimpleLayoutPanels don't fill their parent elements in the same way HTML panels do, due to their GWT implementation which includes yet another nested div. The fix is to add a couple of lines of CSS which make them space-filling in our usage.
CSS only change, automation not appropriate here.
This problem affects satellite toolbars generally (not just in the Git window) so take a tour of other satellite windows in the IDE and make sure their toolbars are showing up correctly too.
> Ensure toolbars have height in satellite windows

- NEWS.md
- src/gwt/src/org/rstudio/core/client/jsonrpc/RpcRequest.java
Addresses https://github.com/rstudio/rstudio-pro/issues/2248. 
Makes some improvements to the logging message:
- The name of the RPC is now included, so we know what exactly we were trying to do when the failure occurred
- The message now indicates the kind of failure more clearly
- The message is now specific to Server / Desktop and uses language that makes more sense in each case
The issue suggests that we might also log these RPC failures on the server. I didn't do this because in my experience 100% of RPC failures are due to a networking issue or failure between the client and server. In this case it is not possible for the client to tell the server to log an error, since the client can't reach the server in the first place. 
This is an improvement to the wording of a log message, …
> More verbose logging for RPC failures

- src/gwt/tools/build-gwt
When we make changes to our fork of GWT, the build script should enforce using JDK8, since that's what we've tested.
Tweak the script and give an error if a different (or no) JDK is found.
This is a manually executed and infrequently-used dev script.
This is a manually executed and infrequently-used dev script. Nothing to test.
> Check for JDK8 when building GWT

- NEWS.md
- src/cpp/r/R/Api.R
- src/cpp/session/SessionClientEvent.cpp
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp
- src/cpp/tests/testthat/test-api.R
- src/gwt/src/org/rstudio/core/client/command/ApplicationCommandManager.java
- src/gwt/src/org/rstudio/core/client/command/CommandCallbacksChangedEvent.java
- src/gwt/src/org/rstudio/studio/client/common/rstudioapi/model/RStudioAPIServerOperations.java
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
- src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
This change makes it possible for RStudio add-ins and other API consumers to run arbitrary R code when an RStudio command is executed, supporting a variety of extensibility scenarios. Addresses https://github.com/rstudio/rstudio-pro/issues/1846. 
This change implements only the RStudio side of the work; it adds command callbacks that function very similarly to the chunk callbacks already implemented in the API. There are two types of command callbacks supported:
1. A callback for a specific command, which will be executed when that specific command is invoked via any means (keyboard shortcut, menu, palette, etc.).
2. A callback for all commands (a "command stream" callback), which will be invoked when *any* command is executed. This callback will be given the ID of the command that was …
> Add rstudioapi support for command callbacks

- NEWS.md
- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionDependencies.cpp
- src/cpp/tests/testthat/test-codetools.R
Addresses https://github.com/rstudio/rstudio/issues/8946, in which non-CRAN repositories are not used when installing package dependencies. 
The primary change here is that we no longer pass the `repos` option to `install.packages` in the background job, instead relying on `options(repos)` set earlier in the script. 
However, there's a pathological situation in which setting `repos` might be necessary: if for some reason no CRAN repo is set in the parent R session, then we could formerly recover by picking up the CRAN repo from user preferences. This change handles that by extending the download options string generator so that it includes a CRAN repo from user prefs if one is not already set.
Test via notes in https://github.com/rstudio/rstudio/issues/8946. Note that …
> Respect repo options when installing R package dependencies

- src/cpp/session/modules/SessionThemes.cpp
- src/cpp/tests/testthat/test-themes.R
Fix variety of warnings in themes unit tests. Addresses https://github.com/rstudio/rstudio/issues/8937. Now all themes tests pass without emitting warnings:
Suppress R warnings that are not relevant to these tests; also skip empty themes when building installation lists since they aren't real themes and were triggering R session warnings.
Yes, this change is all about them.
Test change only, no QA needed.
> Fix some warnings in themes unit tests

- src/gwt/src/org/rstudio/core/client/ClassIds.java
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectList.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/MemUsageWidget.java
Add ids (element IDs and class IDs) for various elements of Environment Pane for automation.
This is part of the work for #9016 but not considering it completed. This has automation value on its own, and not sure when I'll get to the rest of it.
Added unique IDs for Environment Toolbar controls that didn't have them, plus one for the "Environment is empty" message as a way to quickly determine if pane is empty.
Also added classes to the List View headers to provide a place from which to navigate (via xpaths, etc.) to the following content. Ideally would have easier way to do this, but if you examine the HTML can deduce the table structure pretty easily.
None, this is for creating automated tests.
Verify IDs as shown when creating automation (no end-user impact). Note these will now show …
> add automation ids for parts of the environment pane

- CMakeGlobals.txt
Fixes this error when trying to build on dev environments:
```
-- Configured to build SERVER
-- Configured to build DESKTOP
-- Found R: C:/R/R-3.5.0
-- Found Qt: C:/Qt/Qt5.12.8/5.12.8/msvc2017_64/bin/qmake.exe
CMake Error at C:/Users/jmcphers/git/rstudio/cmake/modules/FindPAM.cmake:72 (message):
PAM was not found
Call Stack (most recent call first):
server/pam/CMakeLists.txt:22 (find_package)
```
This problem appears to have been introduced here:
https://github.com/rstudio/rstudio/commit/99dc1fcb7cbecff7753bef7a11fd98167058a4e7#diff-9a73edb1790d89f461c1cb78b348378215277f79e4d9fa7b94344d3c0227bca8L70
In dev configurations, desktop and server are both built by default -- except, formerly, on Windows. Attempting to build server on Windows results in CMake errors as above.
Don't attempt to …
> Don't build RSTUDIO_SERVER on win32

- src/cpp/rstudio-tests.in
Addresses https://github.com/rstudio/rstudio/issues/8871.
The R session in which the unit tests run can be affected by your own local config (state and preferences), which means the unit tests can fail (or even succeed) when they shouldn't. This change gives unit tests a blank config and state folder to start with, so that they are more reproducible. 
Yes, all of them. 
Unit test change only, no QA needed.
> Run tests with blank prefs/state

- NEWS.md
- src/cpp/session/SessionClientEvent.cpp
- src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp
- src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java
- src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
- src/gwt/src/org/rstudio/studio/client/tests/events/TestsCompletedEvent.java
- src/gwt/src/org/rstudio/studio/client/tests/events/TestsOutputEvent.java
- src/gwt/src/org/rstudio/studio/client/tests/events/TestsStartedEvent.java
- src/gwt/src/org/rstudio/studio/client/tests/model/TestsResult.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/ConsoleTabPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/tests/TestsOutputPresenter.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/output/tests/TestsOutputTab.java
Addresses https://github.com/rstudio/rstudio/issues/8775. 
This change just reverts https://github.com/rstudio/rstudio/pull/7756, which removed the Tests pane. 
None, this change restores the product to a previous state.
There are 3 main cases to consider here:
1. Sessions in which projects are not open
2. Project sessions without a Build pane (e.g. New Empty Project)
3. Project sessions with a Build pane (e.g. New Package Project)
The Tests pane should show up in cases (1) and (2). In case (3), tests should be run in the Build pane instead.
> Fix Run Tests button in non-project sessions

- NEWS.md
- src/gwt/panmirror/src/editor/src/api/command.ts
- src/gwt/panmirror/src/editor/src/behaviors/outline.ts
- src/gwt/src/org/rstudio/studio/client/panmirror/command/PanmirrorCommands.java
- src/gwt/src/org/rstudio/studio/client/panmirror/command/PanmirrorToolbarCommands.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java
Addresses https://github.com/rstudio/rstudio/issues/9005, in which a pair of chunk navigation commands do not work in visual mode.
Implement the commands, using a similar pattern (and most of the code) for previous/next section.
Currently no automation runs against the visual editor. See https://github.com/rstudio/rstudio-ide-automation/issues/106.
Note that this change also fixes a bug (that was never filed) in which the Previous Section / Next Section commands navigate to chunks in addition to sections. Test these commands as well; they should no longer navigate to chunks.
> Implement Go to Next Chunk / Go to Previous Chunk in visual editor

- src/gwt/src/org/rstudio/core/client/virtualscroller/virtualscroller.js
- src/gwt/src/org/rstudio/studio/client/common/debugging/ui/ConsoleError.java
- src/gwt/src/org/rstudio/studio/client/common/debugging/ui/ConsoleError.ui.xml
To address: https://github.com/rstudio/rstudio/issues/8940
I've had to rewrite the element manipulation to be compatible with raw Javascript. Unfortunately, when an element is added to the DOM through an external source, GWT loses the bindings are we aren't able to manipulate the elements through GWT variables anymore. I rewrote the functionality with plain DOM manipulation functions.
To address: https://github.com/rstudio/rstudio/issues/7918
I've added `[...]` to the top of the output to indicate that it has been truncated. I'm open to ideas for alternatives to put there but this is very similar to what Visual Studio does when outputting large collections. I don't think clearing the console cutting off everything (including the command prompt) like we do without the VirtualScroller is …
> VirtualScroller bugfix: truncation indication, ConsoleError interactivity

- src/cpp/r/R/Api.R
Addresses https://github.com/rstudio/rstudio/issues/9041.
Warning comes from sorting a list with `NULL` values, so use empty strings instead and remove them later. 
Only.
No QA necessary, internal testing change.
> Fix warning in unit tests

- src/gwt/src/org/rstudio/studio/client/common/filetypes/CppFileType.java
Allow the comment toggling shortcut (Ctrl + Shift + c) on `.c` files, just like it exists for `.h`, `.hpp`, and `.cpp` files. See issue #4109
C and CPP files are handled by the same java CppFiletype class. The option enabling comment toggling was only enabled for CPP files. Simply moving it out of a check for CPP-type (specifically `.h`, `.hpp`, `.cc`, and `.cpp` extensions) files allows comment toggling for both C and CPP files.
I also noticed an option for enabling comment reflow, and included that for C files as well, since functionally it would be the same for C and CPP files
N/A
N/A
> Allow comment toggling and comment reflow for C files

- NEWS.md
- src/gwt/panmirror/src/editor/src/api/bibliography/bibDB.ts
The ‘dataset’ CSL defintion really wants to have editors instead of authors, but author is frequently used instead. Allow that field to be processed
Fixes @rstudio/rstudio#9059
Resolves issue where dataset citation data imported from DOIs failed to include authors.
To minimize the impact (and not require changing the CSL schema definition from biblatex-csl-converter, I merely added a special case.
Does not include tests.
No other behavior change is expected other than authors being imported for datasets. Bug has good repro cases.
> Import Authors from Datasets

- NEWS.md
- src/gwt/panmirror/src/editor/src/behaviors/insert_citation/insert_citation.tsx
Typeahead searching would clear any selected citation because the function was capturing empty state and using that state when performing the search (rather than reflecting the correct up to date state).
Fixes @rstudio/rstudio#8521
Pass state rather than capturing it.
No tests
None
> Don’t lose citation state in debounced function

- src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
First non-prototype Electron commit!
During development of the Electron-based desktop, want the GWT code (i.e. the user interface) to detect and function with both the QtWebEngine-based desktop, and the Electron desktop.
Addresses #9082
Detect desktop mode both via the QtWebEngine user agent and the Electron user agent.
N/A
Test that the existing desktop app (Qt) still loads the desktop variation of the UI. Most obvious symptom is whether the main menu is displayed as part of the HTML (server) or the native menus are populated (desktop).
> make GWT detect both Electron and QtWebEngine desktop user agents

- NEWS.md
- src/cpp/server/ServerMain.cpp
Addresses https://github.com/rstudio/rstudio-pro/issues/2399. This issue appears to be at the root of a lot of the "verify-installation just exits without returning any output" reports we have gotten from customers.
When verify-installation encounters an error that causes it to exit `main()`, have it print that error to stderr before terminating.
None, this change just improves logging. 
Test via notes in https://github.com/rstudio/rstudio-pro/issues/2399.
> Report verify-installation failure to stderr

- src/cpp/r/R/Tools.R
- src/cpp/r/session/RInit.cpp
Fixes a [mojibake](https://en.wikipedia.org/wiki/Mojibake) on Windows when the current path uses non-ASCII characters.
Part of https://github.com/rstudio/rstudio/issues/8321.
`Rprintf()` and `REprintf()` expect their inputs to be in the native encoding, so prefer instead writing to `cout` and `cerr` directly.
None.
None.
> prefer cout, cerr when reporting messages

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/StanCompletionManager.java
Addresses https://github.com/rstudio/rstudio/issues/9106.
On save, completion handlers in Stan mode were being duplicated.
Unfortunate bug caused by our forgetting to call superclass method.
Not worth the effort for this fix.
Test via notes in https://github.com/rstudio/rstudio/issues/9106.
> fixup for detaching completion handlers in Stan mode

- NEWS.md
- src/cpp/core/MiscellaneousTests.cpp
- src/cpp/r/session/graphics/RGraphicsPlotManager.cpp
- src/cpp/shared_core/Error.cpp
- src/cpp/shared_core/include/shared_core/Error.hpp
Addresses https://github.com/rstudio/rstudio/issues/9113.
Give the default-constructed Error object an empty Impl.
Simple automated test verifying that we can indeed log such default-constructed error objects.
Since we haven't been able to reproduce this in the wild, I don't think there's any testing to be done. All testing is captured by the unit tests in this PR.
> avoid crashes when logging default-constructed error objects

- NEWS.md
- src/cpp/session/SessionMain.cpp
- src/cpp/session/SessionOptions.cpp
- src/cpp/session/include/session/SessionConstants.hpp
- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/session-options.json
Addresses https://github.com/rstudio/rstudio-pro/issues/2410.
Add a `--version` option that prints the version of the R session binary and exits.
None, this option is for validating config of standalone binaries. 
You can find the `rsession` binary in `/usr/lib/rstudio-server/bin`.
> Add option to report R session version

- src/cpp/core/r_util/RToolsInfo.cpp
- src/cpp/session/modules/clang/RCompilationDatabase.cpp
Addresses https://github.com/rstudio/rstudio/issues/4685.
When building projects using Rtools 4.0, we:
- Disable the inclusion of our default libclang headers;
- Fix up the headers includes for Rtools 4.0;
- Instruct libclang not to find and use headers bundled with Visual Studio.
None included -- since this is a Windows-only issue, we don't have infrastructure for testing it.
Test that C++ diagnostics, autocompletion etc. work as expected with the latest version of R as well as Rtools 4.0. (https://cran.r-project.org/bin/windows/Rtools/)
> fixups for Rtools 4.0

- .devcontainer/devcontainer.json
- .gitignore
- .vscode/extensions.json
- src/.gitignore
Recommend extensions when opening RStudio IDE project root in Visual Studio Code.
This should mostly match the list in the dev container specification (`.devcontainer/devcontainer.json`), but some extensions only make sense in one context or another.
Use a `.vscode/extensions.json` at the root of the project. Tweak `.gitignore` so this one file under `.vscode` is not ignored.
The recommended extensions are:
* ESLint (for JS/Typescript)
* EditorConfig (for basic editor settings)
* Docker (for managing docker containers, images, etc)
* Remote - Containers (for using devcontainers, other related scenarios)
* CMake Tools
* C/C++ IntelliSense, debugging, and code browsing
* CMake langage support for Visual Studio Code
* Java Extension Pack (for editing the GWT Java sources)
None, purely an …
> vscode extension recommendations

- NEWS.md
- src/cpp/r/include/r/session/RSession.hpp
- src/cpp/r/session/RSession.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/include/session/SessionConstants.hpp
- src/cpp/session/include/session/SessionOptions.gen.hpp
- src/cpp/session/session-options.json
Addresses https://github.com/rstudio/rstudio-pro/issues/1934, which is becoming a major issue for rstudio.cloud. 
The current behavior is very much intentional; we avoid suspending sessions wherein R is waiting for you to finish writing a statement because we can't restore that state. When we resume after suspend you will lose the partial statement and be returned to the R prompt. 
This PR makes the current behavior optional, trading the possibility for minor data loss (your partial statement) for more reliable suspension. 
None, suspension currently isn't testable.
Note that you can set sessions to suspend after 1 minute of inactivity to test this quickly. You will also notice that the partial statement entered prior to suspension will be lost; that's expected.
> Add session-suspend-on-incomplete-statement option

- NEWS.md
- src/gwt/src/org/rstudio/core/client/files/filedialog/FileDialog.java
- src/gwt/src/org/rstudio/core/client/files/filedialog/OpenFileDialog.java
When a user attempts to open a file by explicitly typing the name of that file (rather than selecting an entry from the file-list widget), the attempt to open that file fails. This PR intends to fix that.
Addresses https://github.com/rstudio/rstudio/issues/4059.
The underlying issue here is that there are two notions of the "active" file:
- The current selection, if any, in the Files list widget;
- What the user has typed in the filename at the top of the widget.
Because selecting an item always updates the filename at the top of the widget, that should be taken as the correct filename to open.
https://github.com/rstudio/rstudio-ide-automation/issues/279
Test via notes in https://github.com/rstudio/rstudio/issues/4059. The change should only effect RStudio Server, but it's worth verifying …
> fix issue with opening file with explicitly typed name

- NEWS.md
- src/cpp/core/FilePathTests.cpp
- src/cpp/core/system/Xdg.cpp
- src/cpp/shared_core/FilePath.cpp
- src/cpp/shared_core/include/shared_core/FilePath.hpp
Fix a regression in 1.4 that causes RStudio sessions to recursively `chown()` RStudio state folders at startup, resulting in performance and connectivity issues. Addresses https://github.com/rstudio/rstudio/issues/9152.
As noted in #9152 comments, the primary issue here is that we are trying to test a directory for writeability the wrong way, with the result that we never think it's writeable and always try to fix permissions. So the primary fix is to do the correct test for writeability.
To further reduce risk I've made two other changes:
- Documentation, an explicit error, and unit tests have been added to ensure that future usage of `testWritePermissions` against a directory doesn't occur.
- I have completely removed the recursive `chown()` to eliminate the possibility it will cause …
> Do not attempt to recursively chown() RStudio state folders

- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java
Addresses https://github.com/rstudio/rstudio/issues/9165.
Due to a recent change, all toolbars are capable of emitting resize events. However, due to the inscrutable ways of GWT, they now also must have a height assigned, so assign a height. 
None, style only change.
Visual change only.
No NEWS update since this is a regression in Juliet Rose.
> Set explicit height for column button toolbar

- src/cpp/session/modules/rmarkdown/NotebookExec.cpp
- src/cpp/session/modules/rmarkdown/NotebookExec.hpp
Addresses https://github.com/rstudio/rstudio/issues/9155. 
We don't have a repro for this issue, so this fix is speculative. It makes a stronger guarantee that the method that processes R output in notebooks cannot recurse indefinitely. The method can recurse in order to process previously queued output; we now avoid any further recursion by discarding pending output if we are already in the process of handling it. 
None, this change does not materially impact behavior.
Sanity test R console (plain text) output persistence in R notebooks. It'd be great if we could reproduce the original issue, too; there are some ideas on doing that in the original issue (i.e., deleting the notebook output directory during runtime).
> Add recursion guard for notebook console output

- Jenkinsfile.macos
- src/cpp/CMakeLists.txt
- src/cpp/rstudio-tests.in
- src/cpp/tests/testthat/run-tests.R
Addresses https://github.com/rstudio/rstudio/issues/6890.
Refactors the `rstudio-tests` script (for easier future maintenance), and re-enables all tests on Jenkins.
There are the automated tests. :-)
No QA required; this is just getting unit tests running on macOS CI.
> re-enable unit tests for macOS

- src/cpp/desktop/DesktopMain.cpp
I'm using vscode to work on IDE source (C++ and Java) in a single window, as part of that running cmake generation from root of repo versus our usual approach of running it in src/cpp.
Currently the Qt-based desktop fails to find the generated conf files (rdesktop-dev.conf, etc) in this arrangement, thus applies wrong logic to find "stuff" and fails to fully load. This makes it harder to debug the Qt desktop, which is handy to do occasionally when porting code over to Electron.
Add another "debug mode" detection step that handles this arrangement properly.
None, purely a dev environment thing (and we don't have tests for Qt desktop code, anyway).
Nothing to test other than making sure the IDE still launches.
> support running dev desktop build (qt) with cmake generation from repo root

- package/osx/cmake/fix-library-paths.cmake
- package/osx/fix-library-paths.sh
- src/cpp/diagnostics/CMakeLists.txt
- src/cpp/session/CMakeLists.txt
- src/cpp/session/postback/CMakeLists.txt
Addresses https://github.com/rstudio/rstudio/issues/9190.
Addresses https://github.com/rstudio/rstudio/issues/6890.
Previously, we were running `install_name_tool` for package builds at build time, rather than install time. This causes problems when we try to run unit tests with built-but-not-yet-installed RStudio components, as the processes will end up looking for libraries in the wrong locations.
This PR removes those build-time `install_name_tool` usages, and instead just fixes the library paths at install time for the requisite components.
Relatively straight-forward switch from using post-build CMake commands to install-time CMake commands (with existing tools).
These are the automated tests!
Nothing for QA.
> use install_name_tool to fix paths at install time

- src/cpp/desktop/DesktopSessionLauncher.cpp
Addresses https://github.com/rstudio/rstudio/issues/9223.
Launches our `rsession-arm64` binary via `arch -arm64`, so that the rest of the process context (including newly-launched child processes) are launched using arm64.
None added.
Test that `system("uname -m")` reports `arm64` when using an M1 macOS machine with an arm64 build of R.
> launch rsession-arm64 via /usr/bin/arch -arm64

- package/osx/fix-library-paths.sh
- package/osx/make-package
- src/cpp/desktop/DesktopSessionLauncher.cpp
Addreses https://github.com/rstudio/rstudio/issues/9223.
Launch `rsession-arm64` via `/usr/bin/arch`, explicitly setting `-arm64` and also passing along `DYLD_INSERT_LIBRARIES` explicitly.
None.
Test via notes in https://github.com/rstudio/rstudio/issues/9223.
> ensure DYLD_INSERT_LIBRARIES set in arch call

- NEWS.md
- src/cpp/session/modules/SessionFiles.cpp
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesUpload.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/model/FileUploadToken.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/model/PendingFileUpload.java
When uploading a zip archive, if unzip is not located on a user's PATH, offer to upload the zip archive without extracting instead of crashing or causing errors.
Addresses #9151 
This adds a couple features:
1. If unzip is not on PATH, try `/usr/bin/unzip` as well. Adding other paths to check is easy
2. If unzip cannot be found, display a message asking if uploading the archive, without extracting, is okay
3. Play nicely with the overwrite message, which will display normally if uploading the archive will overwrite an already existing archive in the same directory
I think some automated tests that do something like this would be more than enough:
- Sanity Check: 
- Uploading a zip archive when `unzip` is on PATH should upload and extract the zip normally
- Backup Path Check: 
- Uploading …
> Add option to upload an unzipped archive if unzip is not on PATH

- dependencies/windows/Install-RStudio-Prereqs.ps1
One of @AndrewMcClain or @cm421 mentioned this a couple weeks ago, can't remember who so including both as potential reviewers!
The Windows dev bootstrapper script installs an old version of R that can make it hard to work on Tidyverse tutorials and such. No particular reason for it installing such an old version other than wanting to have a reasonable baseline if dev hasn't already installed R.
Note that the official build uses a REALLY old version (3.0.3 currently) to ensure compatibility with oldest supported version, but this isn't necessary on a dev machine.
https://github.com/rstudio/rstudio/blob/19c6fe31d25b7b3cb8ec8f51be42cc7f2d21e4b5/docker/jenkins/Dockerfile.windows#L46
Increase to 3.6.3. Could have gone to a 4.x version, I suppose, but decided to be conservative and install …
> install R 3.6.3 (up from 3.5) via PowerShell bootstrapper

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Ensure that spellcheck (and linting in general) is done whenever the document gets focus.
Addresses #9074 
Just call the linter on focus.
Very minor change. Everything passes.
Just click from Visual back to Source and see that the squigglies are there immedaitely.
- [ x] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x ] This PR passes all local unit tests
> Rerun lint on doc blur

- scripts/clean-rstudio
The `rstudio/scripts/clean-rstudio` bash script is intended as a blunt instrument for resetting RStudio desktop and server to a clean state on Mac/Linux. Primarily intended for dev and testing. There's a corresponding `clean-rstudio.bat` for Windows, not changed as part of this PR.
Anyway, I noticed it was missing some folders.
Added those folders.
No automated tests, this is a utility script not used by the product in any way.
Nothing here requires testing; if you have your own copy of this script somewhere, you'll want to update it!
> clean-rstudio script missing some folders

- src/cpp/session/modules/SessionPythonEnvironments.R
- src/cpp/session/modules/SessionReticulate.R
RStudio could crash on load if the `reticulate` package was loaded too early. This was caused by us registering a package load hook that was run immediately, with that load hook also having been run _before_ our R FFI code had finished initialization -- that is, the code that registers the native R routines used by RStudio.
Addresses https://github.com/rstudio/rstudio/issues/9253.
Use the `.rs.reticulate.initialized()` hook to add this hook, since that hook will be run on deferred init appropriately:
https://github.com/rstudio/rstudio/blob/102989cb285ed1544d961d88ac011efcfb60db5f/src/cpp/session/modules/SessionReticulate.cpp#L58-L63
None included.
Test via notes in https://github.com/rstudio/rstudio/issues/9253.
> avoid executing reticulate package load hook too early

- src/cpp/core/r_util/REnvironmentPosix.cpp
Addresses https://github.com/rstudio/rstudio/issues/9265.
Add Homebrew R to the list of R installations that will be tried. Note that R should only exist in this location on M1 machines, hence why we don't try to further screen based on the host architecture.
None.
On an M1 macOS machine, install R via Homebrew, e.g.
```
brew install r
``` 
Then, try to launch RStudio. Assuming you don't already have a version of R installed at `/usr/bin/R`, `/usr/local/bin/R` or `/opt/local/bin/R`, then this version of R should be detected as the "default".
> include homebrew R in default script list

- NEWS-1.5-ghost-orchid
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileCommandToolbar.java
Adds a couple of small features to make managing the working directory more convenient. First, there's a new context menu option which gives one-click access to setting the working directory to that of the chosen tab (addresses #6781).
Second, there's a new option in the Files pane that causes it to automatically start tracking your working directory. When enabled, it will update the Files pane when you change the working directory in R (addresses #6781)
Very straightforward client-only changes. 
None, unit tests don't currently support front end changes driven by back end events.
1. The "Set Working Directory" command should update both the R working directory and the Files pane.
2. Turning on the "Synchronize Working Directory" setting should cause the working directory to synchronize …
> Add working directory/Files Pane conveniences

- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetSpelling.java
Addresses https://github.com/rstudio/rstudio/issues/9297.
Suspect call to `onResponseReceived()` had accidentally been placed in body of for loop; moved outside.
None included for this PR.
See https://github.com/rstudio/rstudio/issues/9297.
> fix call to onResponseReceived

- src/gwt/www/js/signin.js
Do not start a new poll until the previous one finishes
If request latencies are longer than 1 second, and the login page is
left idle for a few seconds, these requests can pile up and create
problems with the login.
Fixes intermittent problems when login-page has long-latencies. 
Only allow one login poll request at a time. 
Use chrome dev tools network throttling with long latency (5-15 secs)
> Allow only one login poll request at a time

- src/gwt/src/org/rstudio/studio/client/common/spelling/domain_specific_words.csv
Both _indexes_ and _indices_ are acceptable English pluralizations of index, but "[_indices_ is generally preferred in mathematical, financial, and technical contexts](https://grammarist.com/usage/indexes-indices/)," such as in, say, a statistical computing application.
> add "indices" to spellcheck domain wordlist

- src/cpp/r/RExec.cpp
- src/cpp/r/include/r/session/RSession.hpp
- src/cpp/r/session/RInit.cpp
- src/cpp/session/SessionMain.cpp
Addresses https://github.com/rstudio/rstudio/issues/9331.
Use a separate `runTests()` callback that can be triggered at an appropriate point after RStudio has finished initializing R.
Note that some parts of initialization (specifically, deferred init) is not run at this point -- should we consider running that for tests too?
N/A
N/A
> ensure R session is initialized before running tests

- src/cpp/desktop/resources/freedesktop/rstudio.desktop.in
**Problem:**
After installing RStudio Desktop 1.4.1106 for Ubuntu 18 from [here](https://www.rstudio.com/products/rstudio/download/) on Ubuntu 20.04, when other applications attempted to open HTTP and HTTPS URLs, the URLs would open in the RStudio Desktop IDE as editable files instead of being displayed in my default browser.
This came as a surprise :smile:
**One Possible Solution:**
I found that RStudio Desktop was advertising itself as being a handler for `text/html` in `/usr/share/applications/rstudio.desktop`.  After that removing that mime type from the list HTTP(s) URLs once again opened in my default browser.
**Notes:**
- I do not know what the intention behind advertising the RStudio Desktop IDE as a `text/html` mime type handler was (also the same with `text/css` and …
> Avoid setting mime type handler for text/html

- src/gwt/src/org/rstudio/studio/client/workbench/views/console/Console.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsolePane.java
Addresses https://github.com/rstudio/rstudio/issues/8838.
Let Console listen to reticulate events, and adapt view as appropriate.
None included.
When R is active, try executing `Sys.sleep(60)`, and verify that the Stop button shows "Interrupt R" on hover; when Python is active, try executing `import time; time.sleep(60)`, and verify that the Stop button shows "Interrupt Python" on hover.
> show "Interrupt Python" text for interrupt button when Python active

- NEWS.md
- src/cpp/r/RExec.cpp
Addresses https://github.com/rstudio/rstudio/issues/9307.
Currently, stack traces including functions called by RStudio are often large and ugly, including the deparsed representation of the function called by RStudio. This PR seeks to remedy that.
For the `RFunction` class, instead of explicitly resolving the R function class in the constructor, construct the equivalent R call to reference that function.
None included (R function evaluation is covered extensively by existing parts of unit tests / code base)
Execute the following code:
```
debugonce(.rs.rpc.get_completions)
```
Then, do something to trigger RStudio's R completions; e.g. type `mtcars$<TAB>`. The RStudio debugger should open. Then, try entering:
```
sys.calls()
```
You should see something like:
```
Browse[2]> sys.calls() …
```
> don't eagerly resolve R functions in RFunction

- cmake/modules/FindLibR.cmake
- dependencies/windows/install-boost.cmd
- dependencies/windows/install-crashpad.cmd
- dependencies/windows/install-openssl.cmd
- dependencies/windows/install-soci.cmd
- src/cpp/CMakeLists.txt
- src/cpp/core/r_util/REnvironmentPosix.cpp
- src/cpp/session/SessionAsyncRProcess.cpp
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/modules/SessionRPubs.cpp
- src/cpp/session/modules/SessionTests.cpp
- src/cpp/session/modules/SessionUpdates.cpp
- src/cpp/session/modules/build/SessionBuild.cpp
- src/cpp/session/modules/clang/RCompilationDatabase.cpp
- src/cpp/session/modules/connections/SessionConnections.cpp
- src/cpp/session/modules/presentation/SlideRequestHandler.cpp
- src/cpp/session/modules/tex/SessionRnwWeave.cpp
Prefer using `-s` as a backwards-compatible alias for the deprecated `--slave` flag (whose long form is now `--no-echo`). Note that because this doesn't change any externally-facing behavior I don't think it merits a NEWS update.
Straightforward find and replace.
N/A
N/A
> '--slave' => '-s'

- NEWS.md
- src/cpp/core/system/Process.cpp
- src/cpp/session/modules/build/SessionBuild.cpp
Addresses https://github.com/rstudio/rstudio/issues/5126 -- avoid issues with standard output + standard error being incorrectly interleaved in Build pane.
When running Build pane actions, redirect standard error to standard output. I believe this should be safe -- for Build actions (other than roxygenize), RStudio registers some filters on stdout / stderr, in order to figure out whether a Build action succeeded or failed. When such a filter is registered, it looks at both stdout and stderr without discriminating between each:
https://github.com/rstudio/rstudio/blob/495ce067873ffebaff44aef481dc4829b53fc84c/src/cpp/session/modules/build/SessionBuild.cpp#L1618-L1632
Technically, this is true of everything that goes through `buildPackage`, which appears to be everything except for a plain …
> redirect stderr to stdout for Build pane actions

- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/MemoryUsageSummary.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/MemoryUsageSummary.ui.xml
Addresses https://github.com/rstudio/rstudio/issues/9351.
Display memory in MiB instead of KiB.
None, display change only.
Test via notes in #9351.
> show memory usage as mebibytes

- NEWS.md
- src/cpp/core/StringUtils.cpp
- src/cpp/core/StringUtilsTests.cpp
- src/cpp/core/include/core/StringUtils.hpp
- src/cpp/session/modules/data/DataViewer.cpp
Addresses https://github.com/rstudio/rstudio/issues/9364.
Also adds in a simple `sprintf()` implementation, for cases where `boost::format` is too heavy-weight and we just want a quick format-to-string implementation.
Explicitly check the number of rows against the length of the vector being formatted; if the number of rows is less than the vector length, then format with `NA`.
TBA
Test via notes in https://github.com/rstudio/rstudio/issues/9364.
> improve handling of malformed data.frame in viewer

- NEWS.md
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
The auto-detect indentation feature has caused a fair amount of confusion, as it causes pre-existing documents to potentially be indented in a way different from the global / project settings. It would be better for us to have users opt-in to this behavior, since having them opt-in forces them to be cognizant of the consequences.
Addresses https://github.com/rstudio/rstudio/issues/9211.
Flipped the switch.
Not necessary for this PR.
Check via notes in https://github.com/rstudio/rstudio/issues/9211.
> don't auto-detect indentation by default

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
Addresses https://github.com/rstudio/rstudio/issues/8677.
Validate that the token preceding the newly-inserted `(` character is an identifier, not a string.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/8677.
> avoid showing tooltips in strings

- NEWS-v1.4-juliet-rose.md
- src/cpp/session/modules/SessionCodeTools.R
Addresses https://github.com/rstudio/rstudio/issues/9350.
Scope our fix to the versions of R affected by the associated bug.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/9350.
> scope Sys.setlocale() workaround to R < 3.5.2

- src/cpp/session/modules/SessionPythonEnvironments.R
Addresses https://github.com/rstudio/rstudio/issues/9379.
We had a routine intended to find "system" installations of Python, which lacked the Windows-specific pieces necessary. This PR adds those bits.
None included (no infrastructure for Windows tests yet).
Test via notes in https://github.com/rstudio/rstudio/issues/9379.
> find system Python installations on Windows

- NEWS-v1.4-juliet-rose.md
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
Disables the "Limit visible console output" setting by default. 
Addresses https://github.com/rstudio/rstudio/issues/9376. 
This setting is intended to improve performance of the console when it contains a lot of output, but empirically it has the exact opposite effect in some situations. Were we not literally days away from releasing, it would be worth trying to figure out whether this is something we could make a targeted fix for, but this code is very sensitive (see e.g., https://github.com/rstudio/rstudio/pull/8623), so it's safer to just make it opt-in, as it was in all previous releases. 
Set the default to false in the preference schema. 
None, schema default change only.
Ensure that:
1. The preference is now off by default in a fresh install, and
2. in a fresh install, issue …
> Disable console virtualization by default

- src/cpp/session/modules/SessionRCompletions.R
- src/gwt/acesupport/acemode/r_code_model.js
Addresses https://github.com/rstudio/rstudio/issues/9385.
Add support for the `|>` native pipe in places relevant to our autocompletion code.
None included.
Test via notes in https://github.com/rstudio/rstudio/issues/9385.
> support autocompletion for native pipe

- src/cpp/session/modules/SessionPythonEnvironments.R
Resolves https://github.com/rstudio/rstudio/issues/9379#issuecomment-847345034.
Ensure the list of Python interpreters returned is un-named, so that it's serialized as a Javascript array.
N/A (cannot yet test on Windows)
See https://github.com/rstudio/rstudio/issues/9379#issuecomment-847345034.
> ensure Python installations can be discovered when no Python on PATH

- src/cpp/session/resources/dependencies/r-packages.json
- src/cpp/session/resources/templates/plumber/plumber.R
Fixes #9399
cc @blairj09 . Any other changes we should make?
Plumber v1.0 deprecated the plumber tag `@png`. 
* IDE Issue: #9399 
* Code: https://github.com/rstudio/plumber/pull/630/files#diff-4d59d236d3957a592ddb7922b69f7b41dfacbe2f020f9fdf056c1e3151a5d370R130-R133
Changed from `@png` to `@serializer png`. This is the recommended approach from the warning.
> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests …
> Update plumber template

- src/cpp/session/modules/SessionReticulate.R
Addresses https://github.com/rstudio/rstudio/issues/9311.
Avoid using `reticulate::py_run_string(..., local = TRUE)`; instead, use the global version and then pick up after ourselves later.
None included.
Test via notes in https://github.com/rstudio/rstudio/issues/9311. Note that testing needs to be done with the current CRAN release of reticulate, 1.20.
> avoid using py_run_string(..., local = TRUE)

- src/gwt/src/org/rstudio/studio/client/workbench/Workbench.java
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
- src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
Small, non-NEWS worthy change that makes it possible to edit code snippets (a very nifty feature) using the Command Palette or the menus, without having to dig through the Preferences dialog and figure out where the entry point is. 
Create a new command, and put it in a menu slot next to Modify Keyboard Shortcuts. 
None, this only adds an entry point. Maybe helpful for automated tests of this dialog! 
N/A
> Add command for editing code snippets

- src/node/desktop/package.json
- src/node/desktop/src/main/main.ts
- src/node/desktop/tsconfig.json
The desktop IDE has always had a command-line argument (`--version`) to show the RStudio version. Extending that in Electron to include a new switch `--version-json` that shows versions of major components (electron, node, chrome, etc), returning results as JSON.
Also some unrelated no-op cleanup of tsconfig.json (removing comments and extra blank lines).
Use node's `process.version` to get json blob of version info and add rstudio version to it. Can use `yarn show-version` in a dev environment to run it.
```
$ yarn show-version
{
node: '14.16.0',
v8: '9.1.269.28-electron.0',
uv: '1.40.0',
zlib: '1.2.11',
brotli: '1.0.9',
ares: '1.16.1',
modules: '89',
nghttp2: '1.41.0',
napi: '7',
llhttp: '2.1.3',
openssl: '1.1.1',
icu: '68.1',
unicode: '13.0',
electron: '13.0.1',
chrome: '91.0.4472.69', …
```
> show component info when IDE launched with --version switch

- src/gwt/src/org/rstudio/studio/client/common/mirrors/ChooseMirrorDialog.java
- src/gwt/src/org/rstudio/studio/client/common/mirrors/model/CRANMirror.java
- src/gwt/src/org/rstudio/studio/client/common/repos/SecondaryReposDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
Update to CRANMirror that makes logic around how to display it to users, as well as whether it is a standard CRAN Mirror or if it is user defined by URL.  Change should not affect function, only make things more maintainable.  This was done while working on internationalizing RStudio and trying to simplify where hardcoded strings are located in the code.
CRANMirror implements a .getDisplay() method for showing a human readable representation of itself.  PackagesPreferencesPane.java …
> Update CRANMirror.CRANMirror to centralize display logic

- src/cpp/rstudio-tests.in
Unit tests run with `sudo` on CentOS 7 don't actually run and instead immediately exit. See the running Launcher tests for pro builds as an example.
Fix this. See https://github.com/rstudio/launcher/pull/100 for more details.
None necessary.
Launcher tests should start running for CentOS 7. Already verified in new Launcher repo.
> Fix issue where unit tests running as sudo will not run correctly on CentOS 7 due to weird sudo and escaping issue

- src/node/desktop/.eslintignore
- src/node/desktop/.eslintrc.js
- src/node/desktop/.npmrc
- src/node/desktop/.prettierrc
- src/node/desktop/package.json
- src/node/desktop/src/core/environment.ts
- src/node/desktop/src/core/file-path.ts
- src/node/desktop/src/core/log-options.ts
- src/node/desktop/src/core/system.ts
- src/node/desktop/src/core/user.ts
- src/node/desktop/src/core/xdg.ts
- src/node/desktop/src/main/app.ts
- src/node/desktop/src/main/desktop-utils.ts
- src/node/desktop/src/main/main.ts
- src/node/desktop/src/main/product-info.ts
- src/node/desktop/test/core/environment.spec.ts
- src/node/desktop/test/core/err.spec.ts
- src/node/desktop/test/core/file-path.spec.ts
- src/node/desktop/test/core/log.spec.ts
- src/node/desktop/test/core/system.spec.ts
- src/node/desktop/test/core/user.spec.ts
- src/node/desktop/test/core/xdg.spec.ts
- src/node/desktop/yarn.lock
We should leverage tooling to enforce some basic styles and best practices in our TypeScript.
- install [ESLint](https://eslint.org/) and related packages (via `yarn add`)
- create config for typescript by running `eslint --init` and answering questions
- tweak to match our target environment (node 14, which translates to es2020 / ecmaVersion11)
- set to indentation of two spaces
- pick single quotes as our preferred syntax for string literals, this seems most common in other TypeScript projects such as vscode; note can still use double quotes if string contains single quote(s)
- beyond those tweaks, we're using the "eslint:recommended" settings for TypeScript as our starting point; I'm sure we'll find something we agree to tweak as we write more code, but let's start here and see how …
> hookup eslint and fix all errors in Electron project sources

- src/node/desktop/NOTICE.electron
Electron desktop project incorporates new components requiring attribution in NOTICE. Until we decide which RStudio release will make the switchover from Qt to Electron, this is being tracked in `rstudio/src/node/desktop/NOTICE.electron`; once we have made the decision, it should be merged into `rstudio/NOTICE` then deleted (tracked by #9429)
Created Electron-specific NOTICE file.
None
> add NOTICE.electron to track new components added for Electron desktop

- src/cpp/rstudio-tests.bat.in
Unit-test running script on Windows isn't running the `shared_core` tests; these are run for Linux and Mac.
Add this to the script.
Existing unit tests for `shared_core` will now run on Windows during builds, and on Windows dev machines via `rstudio-tests.bat`
No code change, just running existing unit tests on Windows.
> execute shared_core unit tests on Windows via rstudio-tests.bat

- src/node/desktop/.eslintrc.js
- src/node/desktop/package.json
- src/node/desktop/src/core/file-path.ts
- src/node/desktop/src/core/system.ts
- src/node/desktop/src/core/xdg.ts
- src/node/desktop/src/main/desktop-utils.ts
- src/node/desktop/src/main/main.ts
- src/node/desktop/test/core/file-path.spec.ts
- src/node/desktop/test/core/xdg.spec.ts
- src/node/desktop/test/main/app.spec.ts
- src/node/desktop/test/main/desktop-utils.spec.ts
- src/node/desktop/test/main/main.spec.ts
- src/node/desktop/yarn.lock
Unit tests had numerous failures on Windows.
Fix them; mostly involved adding behavior to FilePath class to mimic the C++ behavior with regards to "native" versus "generic" paths.
Also created additional commands for yarn:
- `yarn test` runs all unit tests without producing coverage report
- `yarn testcover` runs all unit tests and gives a coverage report
- `yarn testwip` only runs tests containing `WIP` (case sensitive) in their description
This is work on automated tests.
Nothing to test here, just unit test fixes on Windows.
> Fix electron unit tests on Windows

- Jenkinsfile
Addresses https://github.com/rstudio/rstudio-pro/issues/2510.
Instead of simply marking the build as unstable, emit information about which test failed on which platform. 
None, not product code.
No QA necessary.
> Emit unit test failure details

- src/cpp/r/R/Options.R
- src/cpp/session/modules/SessionCodeTools.R
- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/tests/testthat/test-debugger.R
Currently, RStudio can hang when large call objects are defined in the global environment. This is caused by us attempting to deparse the call object, which can be excessively slow when that call contained large inlined R objects.
Addresses https://github.com/rstudio/rstudio/issues/5158.
This PR seeks to avoid IDE slowness when attempting to deparse excessively large calls -- especially, those with large inlined R objects.
Unit tests are included.
Test via notes in https://github.com/rstudio/rstudio/issues/5158.
> avoid deparsing excessively large calls

- NEWS.md
- src/cpp/session/SessionMain.cpp
- src/cpp/session/modules/SessionCRANMirrors.cpp
The Pro option `allow-cran-repos-edit` is intended to prevent users from changing the CRAN repo option away from one the admin has supplied through some other mechanism. It *does* make the UI non-editable, but doesn't actually prevent user preferences from taking precedence. This is a problem when e.g., many users have *already* changed their repo, after which admins setting `allow-cran-repos-edit=0` doesn't do much because it doesn't remove user settings. 
Addresses (part of) https://github.com/rstudio/rstudio-pro/issues/1301.
Ignore user preferences for CRAN settings when `allow-cran-repos-edit=0`. Also, add a new `INFO` level log statement explaining where the CRAN repo option is being set from.
None included.
Turning off CRAN repo editing will disable the UI, but you can still set the …
> Ignore user CRAN preference when allow-cran-repos-edit=0

- src/node/desktop/.mocharc.json
- src/node/desktop/package.json
- src/node/desktop/src/core/file-path.ts
- src/node/desktop/src/core/log-options.ts
- src/node/desktop/src/core/system.ts
- src/node/desktop/src/main/app.ts
- src/node/desktop/src/main/desktop-utils.ts
- src/node/desktop/src/main/init.ts
- src/node/desktop/src/main/main.ts
- src/node/desktop/test/core/environment.test.ts
- src/node/desktop/test/core/err.test.ts
- src/node/desktop/test/core/file-path.test.ts
- src/node/desktop/test/core/log.test.ts
- src/node/desktop/test/core/system.test.ts
- src/node/desktop/test/core/user.test.ts
- src/node/desktop/test/core/xdg.test.ts
- src/node/desktop/test/main/app.test.ts
- src/node/desktop/test/main/desktop-utils.test.ts
- src/node/desktop/test/main/init.test.ts
- src/node/desktop/test/main/main.test.ts
- src/node/desktop/yarn.lock
Assorted minor tweaks.
- renamed test files from `*.spec.ts` to `*.test.ts` to better match our usual scheme
- make `yarn eslint` run against both `src` and `test` sources
- cleanup all eslint warnings
- create and invoke `beforeAppReadyEvent()` for operations that can or must happen before app 'ready' event (one example is passing additional arguments to Chromium; according to docs this must happen before app 'ready'
- fix `augmentCommandLineArguments()`; discovered bug when writing unit test
- a few more unit tests
> Add additional information for QA on how to validate the …
> more tests, eslint cleanup

- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPreferencesDialog.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.java
Addresses #9345. The “Python" global and project options in the menu are moved up for increased prominence, under “R Markdown."
Move the references to the “Python” options.
Check that the Python options are still reachable.
1. Verify in Global Options that “Python” is between “R Markdown” and “Sweave.”
2. Verify in Project Options that “Python” is between “R Markdown” and “Sweave.”
3. Verify that the “Python” options continue to work.
> Moved location of Python global and project options to make it more prominent

- src/node/desktop/test/core/environment.test.ts
- src/node/desktop/test/core/err.test.ts
- src/node/desktop/test/core/file-path.test.ts
- src/node/desktop/test/core/log.test.ts
- src/node/desktop/test/core/system.test.ts
- src/node/desktop/test/core/user.test.ts
- src/node/desktop/test/core/xdg.test.ts
- src/node/desktop/test/main/main.test.ts
- src/node/desktop/test/main/utils.test.ts
Convert current node tests to use Chai's assert library. This is just the start, all tests will be converted to use assert.
N/A
N/A
N/A
> Start converting node desktop tests to Chai's assert

- CMakeGlobals.txt
Currently, the default development builds of RStudio on macOS fail as they try to pull in and build Launcher-specific bits. This PR ensures that we only build desktop components on macOS for Pro.
> detect pro builds in CMake; default to desktop for macOS pro

- src/node/desktop/.gitignore
- src/node/desktop/package.json
- src/node/desktop/src/main/main.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/test/main/utils.test.ts
- src/node/desktop/yarn.lock
Use `electron-packager` to produce a packaged build, via `yarn package`. Next small step towards making a real build.
Also fixed a unit test (on Windows).
Results go into `rstudio/src/node/desktop/package` folder. On Mac, this produces `RStudio.app`; on Windows and Linux it puts everything needed to run RStudio[.exe] in a folder. The app itself just  loads rstudio.com at the moment (as a placeholder).
This does not produce an installer for Windows, `.dmg` for Mac, or a `.desktop` file or appimage, etc. on Linux. For that, we'll need to incorporate additional packages (or pull in something like `electron-builder`).
Also not yet pulling in the native dependencies (rsession and friends). We need to figure out approach to blend the cmake-produced dependencies with the Electron ones.
Move …
> implement basic packaging of Electron app

- package/osx/make-package
This PR ensures that we set `JAVA_HOME` to the appropriate locations (primarily for use on our macOS build machine).
> force use of OpenJDK 11 for builds

- src/node/desktop/.mocharc.json
- src/node/desktop/package.json
- src/node/desktop/test/integration/mocharc.json
- src/node/desktop/test/integration/startup.int.ts
- src/node/desktop/test/unit/mocharc.json
- src/node/desktop/yarn.lock
Bootstrap creation of integration tests using Spectron and Mocha/Chai.
Added Spectron, create separate mocha configs for `unit` and `integration`, and a `yarn test-int` command that runs against the dev build (not the package build).
Wrote one proof-of-concept test that launches RStudio, confirms it displays a window, and exits.
Yes. Yes it is.
Nothing to test here yet; currently must run manually on a dev environment.
> Initial skeleton for Spectron-based integration tests

- src/cpp/session/modules/rmarkdown/NotebookQueue.cpp
@kevinushey I think this is the right approach to suppressing the banner, LMK what you think.
Perhaps as annoying is that a bunch of transient objects get printed in an "R Console" output block:
These do not get displayed when executed in JupyterLab:
We need to figure out the right logic for suppressing that output. It seems as if JupyterLab can and does print multiple set of output, but they have some criteria that allows them to exclude that output.
> don't allow repl_python banner to enter notebook output

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/rmarkdown/model/NotebookDocQueue.java
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/NotebookQueueState.java
Currently, when executing a Python chunk within an R Markdown document, we fail to check if the `reticulate` package is available, which is required in order to execute those chunks. This PR rectifies that.
Addresses https://github.com/rstudio/rstudio/issues/9471.
Add a helper function that tries to validate queue dependencies in the front-end before attempting execution of the queue.
https://github.com/rstudio/rstudio-ide-automation/issues/347
Test via notes in https://github.com/rstudio/rstudio/issues/9471.
> install reticulate before running Python chunks

- NEWS.md
- src/cpp/core/http/Keychain.mm
Addresses https://github.com/rstudio/rstudio-pro/issues/2651.
On macOS, the current `getKeychainCertificates()` implementation unfortunately does not read system root certificates, which implies that SSL connections (unless we get lucky and OpenSSL finds a `certs.pem` file) will fail to connect.
Explicitly include the root certificate keychain when searching for certificates, and disable the default OpenSSL `cert.pem` lookup on Windows + macOS (since it will point to a Homebrew-specific location that is not useful on these platforms).
Not included.
Test that RDP -> RSP connections work on macOS.
> read system root certificates from keychain for SSL connections

- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPreferencesDialog.java
Fix regression identified in #9490.
Fix project preferences tab enum to match visual order, and added comment mentioning that requirement.
None
Verify that the command works both from the Command Palette and the "More" dropdown in build pane.
> fix command for showing configure-build-tools pane

- src/gwt/.gitignore
- src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
- src/gwt/src/org/rstudio/studio/RStudioDesktopSuperDevMode.gwt.xml
- src/gwt/src/org/rstudio/studio/RStudioSuperDevMode.gwt.xml
- src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialog.java
- src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogConstants.java
- src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogConstants_en.properties
- src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogMessages.java
- src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogMessages_en.properties
- src/gwt/tools/i18n-helpers/README.md
- src/gwt/tools/i18n-helpers/create_dev_locale.sh
See #9083 for more context on i18n efforts.
This PR enables i18n in RStudio development and "translates" some content of the AboutDialog in a backwards compatable way.
* Enable i18n features by modifying RStudio.gwt.xml to accept only "en" locale and redirect all other locales to "en" by default.  This allows any available translations to be live without changing function for the user.  
* To make development easier, add "dev" locale to RStudioSuperDevMode.gwt.xml and RStudioDesktopSuperDevMode.gwt.xml.  This lets developers add `*_dev.properties` files with obvious changes to see if i18n changes worked without exposing them to and real users
* Add create_dev_locale.sh which creates a "dev" locale from any existing "en" properties files.  The "dev" locale is a copy of "en" properties …
> Add barebones internationalization support

- NEWS.md
- src/gwt/src/org/rstudio/core/client/BrowseCap.java
- src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchScreen.java
Adds high DPI plot support for RStudio Server; addresses https://github.com/rstudio/rstudio/issues/3896.
We've always had a way to test for high DPI support using `Window.devicePixelRatio`, but it was turned off since it wasn't widely supported. Fast-forward a bunch of years: now our desktop clients all use Chromium and all our supported browsers support it too, so we can feel good about relying on it.
https://caniuse.com/devicepixelratio
None, this doesn't add new code paths.
The macOS desktop is unaffected by this change, but high DPI plots should be tested on Linux and Windows desktops as well as RStudio Server.
> Add support for high DPI plots on RStudio Server

- NEWS.md
- src/cpp/r/include/r/session/RSession.hpp
- src/cpp/r/session/RInit.cpp
- src/cpp/r/session/RStdCallbacks.cpp
- src/cpp/session/SessionMain.cpp
- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionPythonEnvironments.R
- src/cpp/session/modules/SessionPythonEnvironments.cpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/core/client/ElementIds.java
- src/gwt/src/org/rstudio/core/client/widget/FileChooserTextBox.java
- src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java
- src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectPythonPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPane.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPaneBase.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/python/PythonInterpreterSelectionDialog.java
Addresses https://github.com/rstudio/rstudio/issues/9489.
This PR brings some enhancements to RStudio's Python integration, including:
- Projects containing a Python environment within the `.venv` directory will be automatically activated,
- Some minor UI enhancements to our Python selection dialog.
Hover text:
Relatively straight-forward implementation.
TBA
- In the Python selection dialog, double-clicking on a menu item suffices to select it (rather than just clicking the Select button),
- The 'Clear' button in the Python preferences pane resets the Python interpreter,
- If a project contains a Python environment in the `.venv` folder, then that version of Python is automatically placed on the PATH
(feel free to ask for more clarification if needed!)
> various enhancements to python integration

- dependencies/windows/install-soci/install-soci.R
We have a long-standing "weird" thing on Windows build where sometimes `soci.tar.gz` fails to extract, and from there the build ultimately fails. Replaying the build has never seemed to help.
See #9497 (not saying this fixes it, but might help understand what's going on)
Noticed that if you run `7z e soci.tar.gz` as the install-soci.R script does, and there's already an existing `soci.tar`, then 7z interactively asks if you want to overview, skip, etc. For example:
```bat
C:\Users\gtritchie\rstudio\dependencies\windows\install-soci>7z e soci.tar.gz
7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21
Scanning the drive for archives:
1 file, 60992753 bytes (59 MiB)
Extracting archive: soci.tar.gz
--
Path = soci.tar.gz
Type = gzip
Headers Size = 10
Would you like to replace …
```
> tell 7z to overwrite without prompting when extracting soci.tar.gz

- src/node/desktop/package.json
- src/node/desktop/src/core/environment.ts
- src/node/desktop/src/main/activation-overlay.ts
- src/node/desktop/src/main/app-state.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/desktop-callback.ts
- src/node/desktop/src/main/detect_r.ts
- src/node/desktop/src/main/main-window.ts
- src/node/desktop/src/main/menu-callback.ts
- src/node/desktop/src/main/pending-window.ts
- src/node/desktop/src/main/r-command-evaluator.ts
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
- src/node/desktop/src/renderer/desktop-info-bridge.ts
- src/node/desktop/src/renderer/menu-bridge.ts
- src/node/desktop/src/renderer/preload.ts
- src/node/desktop/yarn.lock
Be able to load the rsession and display the real UI, including menu population and some callbacks (essentially equivalent to where the prototype was but with somewhat less hardcoding).
Currently Posix (Mac/Linux) only, and only for dev builds; some additional Win32-specific work needed to get that standing up again, as well as work specific to package builds. 
Location of `src/cpp` build output (on a dev machine) must be specified in `RSTUDIO_CPP_BUILD_OUTPUT` environment variable. For example, `RSTUDIO_CPP_BUILD_OUTPUT=/Users/gary/rstudio/src/cpp/build`.
R detection (Posix only) is partially implemented (Kevin did some work on this in the prototype and I have pulled it over and tweaked it a bit. It should handle common cases).
First use of node.js events (replacing the Qt signal/slots …
> implement session startup (Posix-only)

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/shiny/ShinyApplication.java
- src/gwt/src/org/rstudio/studio/client/shiny/model/ShinyApplicationParams.java
Addresses a couple of Ghost Orchid issues that cause usability problems when running Shiny applications in the background. 
Addresses #8706
Addresses #6904
- Use the new job replay mechanism, introduced in https://github.com/rstudio/rstudio/pull/9393, when Shiny apps are reloaded. 
- Rework how we stop Shiny jobs so that they're also stopped when the Viewer pane is cleared. 
None included, it is not possible to run Shiny applications with the current unit test infrastructure.
In addition to ensuring that the bugs are addressed (relatively straightforward), check that stopping Shiny jobs when the associated window closes hasn't regressed.
> Avoid creating multiple background Shiny jobs

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/projects/Projects.java
- src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewDirectoryPage.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
Small housekeeping change to remove an unused pref and replace it with a more useful one.
Addresses https://github.com/rstudio/rstudio-pro/issues/2670
Addresses https://github.com/rstudio/rstudio-pro/issues/2671
- Remove the unused user preference `new_project_git_init`
- Add a useful user preference `new_proj_use_renv`
None, effectively a UI only change.
- It is not an error to have unrecognized keys in the preferences JSON file, so if the `new_project_git_init` preference was somehow written in the past, it will be silently ignored after this change.
- This change makes the "Use renv with this project" checkbox value sticky; that is, once you've checked it, it will stay checked for future projects until you uncheck it again.
> Clean up New Project preferences

- src/cpp/session/SessionClientInit.cpp
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/include/session/SessionModuleContext.hpp
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/include/session/projects/SessionProjects.hpp
- src/cpp/session/modules/SessionCodeSearch.cpp
- src/cpp/session/modules/SessionFind.cpp
- src/cpp/session/modules/SessionGit.cpp
- src/cpp/session/modules/SessionPythonEnvironments.R
- src/cpp/session/modules/quarto/SessionQuarto.cpp
- src/cpp/session/modules/quarto/SessionQuarto.hpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/projects/SessionProjectContext.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/quarto/model/QuartoConfig.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
I've been hashing out the project-specific virtual envs a bit and thinking more about directory naming. I noticed that VS Code will actually auto detect/activate any venv contained in a sub-directory with a pyvenv.cfg file. That's great flexibility, but at the same time I think we want to enforce some standards so that the IDE can depend on a predictable path (e.g. we need to screen files in the venv out of find in files results -- we  do that now for "renv" but need the analogous behavior for python envs; we also need to augment .gitignore with the venv directory).
I noted that the official python venv documentation (https://packaging.python.org/guides/installing-using-pip-and-virtual-environments/#creating-a-virtual-environment) use the convention of 'env' for project-specific …
> use `env` as the project python environment directory rather than `.venv`

- src/cpp/core/r_util/REnvironmentPosix.cpp
- src/cpp/core/r_util/RProjectFile.cpp
- src/cpp/desktop/DesktopSessionLauncher.cpp
- src/cpp/r/R/Tools.R
- src/cpp/session/SessionMain.cpp
- src/cpp/session/modules/SessionPythonEnvironments.R
- src/cpp/session/projects/SessionProjects.cpp
This PR contains two main changes:
1. If the project contains a Conda environment within the `.condaenv` directory, RStudio will now automatically activate that environment on startup.
2. Add some extra glue to ensure that `reticulate` can bind to Anaconda installations on macOS. See https://github.com/ContinuumIO/anaconda-issues/issues/12478 for more details.
The Anaconda glue is the more interesting part of the PR. Currently, Anaconda installations rely on the process rpath when discovering libraries. This unfortunately doesn't work for us, since we attempt to load Python as a library (and so don't have the rpath entries set that Anaconda is expecting).
The workaround is to set `DYLD_FALLBACK_LIBRARY_PATH` to include the Anaconda library path, but this is challenging for a couple …
> automatically activate .condaenv environments; fixes for reticulate binding to Anaconda

- src/node/desktop/src/core/console-logger.ts
- src/node/desktop/src/core/core-state.ts
- src/node/desktop/src/core/environment.ts
- src/node/desktop/src/core/file-path.ts
- src/node/desktop/src/core/logger.ts
- src/node/desktop/src/core/xdg.ts
- src/node/desktop/src/main/app-state.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/desktop-callback.ts
- src/node/desktop/src/main/detect_r.ts
- src/node/desktop/src/main/main-window.ts
- src/node/desktop/src/main/main.ts
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/test/unit/core/console-logger.test.ts
- src/node/desktop/test/unit/core/core-state.test.ts
- src/node/desktop/test/unit/core/file-path.test.ts
- src/node/desktop/test/unit/core/logger.test.ts
Provide a logging interface and an initial implementation that uses `console.log`. We can revisit logging in more detail "later", but in the meantime want something other than raw `console.log` calls throughout the code.
Create `Logger` interface with methods similar to our C++ LOG_ERROR-style macros, and an implementation in `ConsoleLogger`.
Give `core` a place to set and retrieve global state (`CoreState`), including the global logger.
Added unit tests for the new code.
Nothing specifically to test here even if you had a build.
> create basic interface for logging and a simple console logger

- src/node/desktop/src/core/console-logger.ts
- src/node/desktop/src/core/core-state.ts
- src/node/desktop/src/core/logger.ts
- src/node/desktop/src/main/main.ts
- src/node/desktop/test/unit/core/console-logger.test.ts
- src/node/desktop/test/unit/core/file-path.test.ts
Implement logging levels so logging verbosity can be controlled (Electron desktop).
Using same LogLevel enum as the C++ code (OFF | ERR | WARN | INFO | DEBUG), provided a way to set it, and made the various logError, logWarning, etc. methods pay attention to it.
The default setting is `LogLevel.ERR` same as the C++ desktop.
We may decide later to simplify this (maybe just ERR and DEBUG?), but for now matching the existing code.
Added/updated unit tests to cover this new scenario. Also used it to suppress logging of expected errors thrown inside the FilePath class during unit tests.
Internal functionality.
> implement basic support for LogLevels

- src/cpp/session/modules/SessionPythonEnvironments.R
- src/gwt/src/org/rstudio/core/client/widget/TextBoxWithButton.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPaneBase.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/python/PythonInterpreterListEntryUi.java
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/python/PythonInterpreterSelectionDialog.java
Improve the overall usability of the Python interpreter selection dialog.
Separate each Python "type" into its own tab, with tabs for system / virtual / conda environments.
Not included.
N/A
> use separate tabs for different Python types

- src/node/desktop/src/core/console-logger.ts
- src/node/desktop/src/core/core-state.ts
- src/node/desktop/src/core/logger.ts
- src/node/desktop/src/main/activation-overlay.ts
- src/node/desktop/src/main/application-launch.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/detect_r.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/gwt-window.ts
- src/node/desktop/src/main/main-window.ts
- src/node/desktop/src/main/rstudio-browser-window.ts
- src/node/desktop/src/main/satellite-window.ts
- src/node/desktop/src/main/secondary-window.ts
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/test/unit/core/console-logger.test.ts
- src/node/desktop/test/unit/core/file-path.test.ts
- src/node/desktop/test/unit/main/activation-overlay.test.ts
- src/node/desktop/test/unit/main/application-launch.test.ts
- src/node/desktop/test/unit/main/gwt-callback.test.ts
- src/node/desktop/test/unit/main/main-window.test.ts
- src/node/desktop/test/unit/main/menu-callback.test.ts
- src/node/desktop/test/unit/main/pending-window.test.ts
The diagnostics logging routines shouldn't display output on console unless the --run-diagnostics flag was provided.
Fixed that.
This also includes a bunch of additional work-in-progress on more detailed porting of the current window creation and session launching behavior, including stubs for the various window classes we have in the Qt app. Specifically, the Qt desktop has this class hierarchy (showing both the Qt classes and the RStudio classes):
For Electron, I'm currently leaning towards having the basic window class (`BrowserWindow` in Qt, but `RStudioBrowserWindow` in Electron) contain the Electron `BrowserWindow` instead of inheriting from it.
So added in stubs for this:
These diagrams are made with PlantUML, sources in the `docs` folder, along with a readme.
Added additional unit …
> fix diagnostics logging, other Electron WIP

- NEWS.md
- src/cpp/session/modules/SessionRCompletions.R
This PR refines the completion ordering used for packages within a `library()` call.
Addresses https://github.com/rstudio/rstudio/issues/9293.
The implementation here uses an indexed cache of packages; however, the ordering of that list does not seem to be defined. This leads to package completion results being in a seemingly random order; for example:
With this PR, completions are instead presented in alphabetical order.
In addition, when presenting completion results, exact matches are now preferred; for example:
which, most importantly, now matches the behavior of "fuzzy narrowing" when typing to narrow a completion list.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/9293.
> tweak ordering of library() completion results

- NEWS.md
- src/cpp/session/include/session/prefs/UserPrefValues.hpp
- src/cpp/session/modules/SessionEnvironment.R
- src/cpp/session/modules/quarto/SessionQuarto.cpp
- src/cpp/session/prefs/UserPrefValues.cpp
- src/cpp/session/resources/schema/user-prefs-schema.json
- src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
RStudio normally screens for objects containing null external pointers when building the Environment pane, primarily to fix crashes that occurred when introspecting certain objects in older versions of R.
This has caused a fair amount of user confusion, and in addition this workaround no longer appears to be necessary with the newer versions of R / igraph.
Addresses https://github.com/rstudio/rstudio/issues/5546.
We now no longer search for null external pointers by default, but allow users to opt-in via a user preference if necessary.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/5546#issuecomment-567646350. Also confirm that you can set the "Check Null External Pointers" preference to toggle the behavior.
> disable null external pointer checks for environment pane

- src/gwt/src/org/rstudio/studio/client/common/debugging/ui/ConsoleError.ui.xml
Currently, the multi-line output of an R Markdown document are placed on the same line.
With this pull request, the two lines of output are placed on separate lines.
As it is done in the R console.
Addresses #8992 
We now use `white-space` to handle the white space inside the element. 
From the [MDN Web Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/white-space): 
> With `pre-line` the sequences of white spaced are colapsed. Lines are broken at newline characters, at `<br>`, and as necessary to fill line boxes
N/A
Tested with running:
---
title: "Untitled"
---
```{r}
library(tidyverse)
mpg %>%
filter(cyl == 4) %>%
ggplot(mpg, aes(x = cty, y = hwy)) +
geom_point()
```
> fix separate console output in same line

- src/node/desktop/src/main/activation-overlay.ts
- src/node/desktop/src/main/desktop-browser-window.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/gwt-window.ts
- src/node/desktop/src/main/main-window.ts
- src/node/desktop/src/main/minimal-window.ts
- src/node/desktop/src/main/secondary-window.ts
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/src/main/window-tracker.ts
- src/node/desktop/test/unit/main/desktop-browser-window.test.ts
- src/node/desktop/test/unit/main/gwt-callback.test.ts
- src/node/desktop/test/unit/main/gwt-window.test.ts
- src/node/desktop/test/unit/main/menu-callback.test.ts
- src/node/desktop/test/unit/main/minimal-window.test.ts
- src/node/desktop/test/unit/main/satellite-window.test.ts
- src/node/desktop/test/unit/main/secondary-window.test.ts
- src/node/desktop/test/unit/main/window-tracker.test.ts
- src/node/desktop/test/unit/unit-utils.ts
- src/node/desktop/yarn.lock
The `MainWindow` class was standalone, but needs to be part of the class hierarchy (following design of the C++ version).
* MainWindow is now subclassed from GwtWindow. Also switched to passing URL as a string instead of via URL class. Might change mind on that later but it was causing problems.
* Fixed passing of callback sets to include to work with class hierachy.
* Fixed up references that referred to `this.window?.foo`; window is not optional so the `?` wasn't needed.
* Ran `yarn upgrade` to get latest packages
No new tests, but added `createSinonStubInstance` helper to enable creating stubs of classes with members annotated by TypeScript as private or protected.
Work in progress.
> wire MainWindow into window class hierarchy (Electron)

- src/node/desktop/src/main/app-state.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/main-window.ts
- src/node/desktop/src/main/satellite-window.ts
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
- src/node/desktop/test/unit/main/app-state.test.ts
- src/node/desktop/test/unit/main/minimal-window.test.ts
- src/node/desktop/test/unit/main/satellite-window.test.ts
- src/node/desktop/test/unit/main/session-launcher.test.ts
The GwtCallback in the main process has to be a singleton, and be able to map an event to the window that sent it (for some callbacks, at least, many don't actually care).
Hang GwtCallback off the global app state, initialized when the main window is created. Satellite Windows also register for GwtCallbacks when they are created (by notifying the GwtCallback instead of creating a new one per-window which is how I found the problem).
Various unit tests updated.
Internals
> make GwtCallback a singleton (Electron)

- src/node/desktop/package.json
- src/node/desktop/src/main/detect_r.ts
- src/node/desktop/test/unit/main/session-launcher.test.ts
- src/node/desktop/yarn.lock
Make the IDE runnable on Windows (for dev purposes). Currently can't because finding R is NYI on Win32.
Use RSTUDIO_WHICH_R env var. This is a temporary hack until we implement the real thing. Fixed a broken win32 unit test in the process.
Nothing new, but fixes on that was broken on Windows.
Development only.
> use RSTUDIO_WHICH_R to find R on windows (dev mode hack)

- src/node/desktop/NEWS-electron.md
- src/node/desktop/src/core/logger.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/desktop-browser-window.ts
- src/node/desktop/src/main/main-window.ts
- src/node/desktop/src/main/main.ts
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/test/unit/core/logger.test.ts
- src/node/desktop/test/unit/main/window-tracker.test.ts
The default logging level is ERR, but should have a way to select different logging level.
Added command-line switch, `--log-level=LEVEL`. The available levels (case insensitive) are:
- `NONE` (no messages will be logged)
- `ERR` (error messages will be logged)
- `WARN` (warning and error messages will be logged)
- `INFO` (info, warning, and error messages will be logged)
- `DEBUG` (all messages will be logged)
You can use this during development, e.g. `yarn start --log-level=DEBUG`.
Also created a global helper function for `executeJavaScript` (does DEBUG level logging), and a `executeJavaScript` helper in the window base class `RStudioBrowserWindow` which routes through that global helper.
Ported over most of `RStudioBrowserWindow.closeEvent()`.
Created `NEWS-electron.md` to capture …
> set logging level with command-line, other misc porting

- src/node/desktop/src/main/desktop-browser-window.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/minimal-window.ts
- src/node/desktop/test/unit/main/minimal-window.test.ts
Minimal windows should close with Ctrl+W (Cmd+W on Mac), and automatically close when the window that opened them closes.
Add keyboard support for closing, and an event handler to ensure closing when parent closes.
Updated existing unit tests.
Work in progress, getting close to full implementation of minimal windows, still some work to do on ensuring they are locked down in terms of what they are allowed to load.
> close minimal windows with keyboard and when parent closes

- src/node/desktop/src/core/array-utils.ts
- src/node/desktop/src/main/activation-overlay.ts
- src/node/desktop/src/main/desktop-browser-window.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/gwt-window.ts
- src/node/desktop/src/main/minimal-window.ts
- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/src/main/web-view.ts
- src/node/desktop/test/unit/core/array-utils.test.ts
- src/node/desktop/test/unit/main/web-view.test.ts
The `GwtWindow` base class mainly deals with zooming in and out, plus handling Cmd+W on Mac (for source windows and the main window, this shortcut should close source docs and only close the window itself if there are no docs to close).
Ported GwtWindow from the C++ code. Assorted other cleanup around events, and making the code align better with some C++-isms to make it easier to track what has or hasn't been ported yet.
Added unit tests to some areas.
Move along, nothing to see here yet.
> implement GwtWindow zooming (electron)

- src/node/desktop/src/core/err.ts
- src/node/desktop/src/core/file-path.ts
- src/node/desktop/src/main/app-state.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/gwt-callback.ts
- src/node/desktop/src/main/main-window.ts
- src/node/desktop/test/unit/core/err.test.ts
- src/node/desktop/test/unit/core/file-path.test.ts
- src/node/desktop/test/unit/main/application.test.ts
Reduce coupling (and follow C++ model) by having GwtCallback be an event emitter, starting with the workbench-initialized message.
Have GwtCallback emit event instead of directly invoking main-window, and so forth; now sets the scratch path received via that callback as in the C++ code (as another global appState property).
Other changes:
- helpers for testing success/failure of Err result (used in unit tests for readability)
- implement FilePath `remove`, `removeIfExists`, `removeSync`, and `removeIfExistsSync` plus unit tests
- other WIP, mostly some pasted in and commented out (with TODO) C++ code
New unit tests for FilePath methods, and for the global scratch path setter/getter.
NA
> gwtcallback emits event when workbench initialized

- src/cpp/shared_core/Logger.cpp
- src/cpp/shared_core/include/shared_core/Logger.hpp
For some of my debug logging changes, I'd like a way to avoid running some code when debug logging is not enabled.
I decided against adding a new trace level or the trace-feature-flags, at least for now, as I don't think the messages we need at this stage are noisy enough. 
Let me know if there's a better way to do this or if you can think of a better name. Thanks!
> Adds needsDebugLog() method for conditionally formatting LOG_DEBUG

- src/node/desktop/src/main/session-launcher.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/test/unit/main/application.test.ts
- src/node/desktop/test/unit/main/utils.test.ts
Currently the SessionLauncher class has two of the C++ methods (launchSession and launchProcess) smooshed into a single method. This came from the prototype. For easier porting and keeping in sync, should split back into two so more closely matches original.
Split back into two methods, implementing the Mac-only `fallbackLibraryPath` logic in the process.
Added unit tests for the fallback path generation routine.
Probably a B-flat, but that's because I play trumpet.
> port the session-launcher launchProcess method

- src/cpp/session/modules/quarto/SessionQuarto.cpp
Addresses https://github.com/rstudio/rstudio/issues/9563. 
Avoid logging path not found errors, which occur during the regular course of operations when testing for quarto installations. 
None, logging change only.
Test via notes in #9563.
> Ignore path not found when looking for quarto

- src/cpp/core/include/core/r_util/RTokenizer.hpp
- src/cpp/core/r_util/RTokenizer.cpp
- src/cpp/core/r_util/RTokenizerTests.cpp
- src/gwt/acesupport/acemode/r_highlight_rules.js
Addresses https://github.com/rstudio/rstudio/issues/9573.
Since R's quoted symbols are parsed the same as R strings, just with backtick delimiters, consolidate that code into a single block.
Test via notes in https://github.com/rstudio/rstudio/issues/9573.
> handle escapes in quoted symbols

- NEWS.md
- src/cpp/core/include/core/r_util/RTokenizer.hpp
- src/cpp/core/r_util/RTokenizer.cpp
- src/cpp/core/r_util/RTokenizerTests.cpp
- src/gwt/acesupport/acemode/r_highlight_rules.js
Addresses https://github.com/rstudio/rstudio/issues/9579.
Mostly straightforward addition of highlight rules for `<<label>>`.
Unit test included.
Test via notes in https://github.com/rstudio/rstudio/issues/9579. Confirm that R code diagnostics function even in the presence of knitr embedded chunks, e.g. `<<chunk>>`.
> support highlighting + syntax for knitr embedded chunks

- src/node/desktop/package.json
- src/node/desktop/test/int/mocharc.json
- src/node/desktop/test/int/startup.test.ts
- src/node/desktop/yarn.lock
After discovering Spectron is abandonware for Electron integration testing, was suggested to take a look at Playwright's experimental Electron support: https://playwright.dev/docs/api/class-electron
Wire up a simple test that launches the IDE, confirms there is a Console tab, and exits. Run via `yarn testint`.
This simple test confirms that we can launch the Electron IDE (at least from a dev config), and communicate both with the main process and the content of the web page (which we couldn't do with Spectron). Looks promising.
This is an automated test.
Proof-of-concept.
> proof-of-concept Electron integration test with Playwright

- src/node/desktop/scripts/mac-package
- src/node/desktop/src/main/detect_r.ts
- src/node/desktop/src/main/main.ts
Locally packaged RStudio.app (Electron) failing silently when launched from Finder (double-click the app), but working when run from terminal.
There was an uncaught exception trying to run `which R` but only from Finder; presumably a Mac entitlement issue. Also, I had the global "report uncaught exceptions" dialog suppressed in Package builds, making it harder to see what was happening.
Show the unhandled exceptions dialog even for package builds. Wrap the attempt to invoke `which R` in try/catch and carry on trying the other approaches if that happens.
Also tweaked the `mac-package` script to open the resulting folder in Finder for easier double-clicking.
No new tests.
Try using the `mac-package` script again, and see if you can launch RStudio.app from finder.
> catch exception thrown during startup from Finder

- NEWS.md
- src/cpp/session/modules/SessionRMarkdown.R
- src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
Addresses https://github.com/rstudio/rstudio/issues/9571. 
There were two small bugs here:
- A path intended for the client was not aliased, with the result that files selected by the user never looked like they were inside the path.
- The error message didn't extract the path correctly.
Test automation doesn't currently support publishing; see https://github.com/rstudio/rstudio-ide-automation/issues/131. 
Note that the self_published step of the repro is important (you can't choose additional files otherwise).
> Fix issue preventing adding files to static content

- src/node/desktop/scripts/update-yarn
- src/node/desktop/test/int/int-utils.ts
- src/node/desktop/test/int/startup.test.ts
We should enable running the integration tests (Playwright) against package builds, not just developer builds.
If a package build is found, run tests against it, otherwise run against the dev build. Presumably do something fancier later (e.g. to run in CI, etc).
Currently macOS only.
If you've done a package build using the `scripts/mac-package` script, running `yarn testint` will now run the massive test suite (one test) against it instead of the dev build.
This means if you've done a package build but want to run against dev, you'll need to delete the package build.
Also created a script, `scripts/update-yarn` to use instead of just `yarn` if you don't want the playwright install to suck in a whole bunch of browser components we don't need. They are harmless, but take time to download. …
> support running integration test against packaged build

- NEWS.md
- src/gwt/src/org/rstudio/studio/client/pdfviewer/PDFViewer.java
- src/gwt/src/org/rstudio/studio/client/pdfviewer/model/PdfJsWindow.java
Addresses part of https://github.com/rstudio/rstudio/issues/9603 (at least, for PDF documents).
We had some existing code to handle saving + loading the position with `pdf.js`. Unfortunately, when `pdf.js` was updated ~6 years ago (!) the API changed and we didn't make the changes required to adapt.
When the document has been loaded. `pdf.js` fires a `documentload` event. Use that to determine when we can try to restore the scroll position.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/9603.
> ensure scroll position preserved when re-rendering PDFs

- NEWS.md
- src/cpp/server_core/CMakeLists.txt
- src/cpp/server_core/ServerDatabase.cpp
- src/cpp/server_core/ServerLicense.cpp
- src/cpp/server_core/include/server_core/ServerLicense.hpp
Addresses [Pro #2725](https://github.com/rstudio/rstudio-pro/issues/2725).
To avoid any possible conflicts and reduce the testing matrix, we will store OS and Pro/Workbench in different schemas. I chose to keep Pro/Workbench in the existing `rstudio` schema, since it currently stores more information.
I will need to merge this PR  and a companion Workbench PR in sync to ensure Workbench keeps the `rstudio` schema.
Note: Should we implement something that moves existing revoked cookies from the `rstudio` schema into the `rstudio-os` schema?
There are already DB tests, and any OS Server automated tests around revoked cookies should cover this change.
We discovered the bug listed above during development, so don't have an active repro for it. The best way to verify that this works correctly …
> Use a different DB for OS

- src/cpp/core/Database.cpp
Fixes a bug where the create schema transaction is not committed.
Commit the transaction before returning success.
The RStudio server will not run correctly without this fix. All tests should cover it.
After this PR, the schema should be created in the sqlite/postgresql DB on server start.
> Fix a bug where the transaction that creates the schema is not committed

- src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
Addresses https://github.com/rstudio/rstudio/issues/9400.
Right now, R and Python use slightly different code paths towards updating the Environment pane. In particular, `reticulate` uses a centralized "environment changed" event:
https://github.com/rstudio/rstudio/blob/b80b77cf161c01e3a24cda3104f0d743fe3f689a/src/cpp/session/modules/SessionReticulate.R#L1859-L1863
https://github.com/rstudio/rstudio/blob/b80b77cf161c01e3a24cda3104f0d743fe3f689a/src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java#L258-L271
whereas R uses separate "object added" and "object removed" events. If we see that an R-related update path is being used while Python is active in the Environment pane, then we can drop the change request.
N/A …
> don't update R variables in Environment pane when Python active

- NEWS.md
- src/cpp/core/include/core/json/JsonRpc.hpp
- src/cpp/session/SessionModuleContext.cpp
- src/cpp/session/SessionRpc.cpp
Addresses https://github.com/rstudio/rstudio/issues/6907.
See https://github.com/rstudio/rstudio/issues/6907#issuecomment-881088465 for rationale.
N/A
Unfortunately, I don't have a clear way to reliably reproduce this issue.
> set events pending flag to false by default for async completions

- src/cpp/shared_core/FilePath.cpp
- src/cpp/shared_core/FilePathTests.cpp
- src/cpp/shared_core/include/shared_core/FilePath.hpp
Addresses https://github.com/rstudio/rstudio/issues/6486.
This fixes crashes that could result from undefined behavior when constructing an `std::string` from a null pointer during construction of a new `FilePath` object. The new behavior is that the following pattern:
```c
const char* empty = NULL;
FilePath path(empty);
```
will just create an empty FilePath (i.e. `FilePath::isEmpty()` will be true)  instead of possibly crashing. 
Unit tests covering the new behavior have been added.
This change is too low-level to test directly, and we don't have repro steps for any crashes suspected to be caused by it, so manual verification probably isn't warranted here.
> Create empty FilePaths from null paths

- src/node/desktop/src/main/main-window.ts
Save window geometry in closeEvent handler, mimicking the C++ code.
Added closeEvent override, put in code similar to the C++ (including some commented out code needing further investigation.).
Background: `closeEvent` is a QtWebEngine event, which gets invoked automatically if a class implements it. In Electron, I have this hooked up to 'close' in the desktop-browser-window base class, so if a class implements it, it will be called.
None yet.
Work in progress.
> Save main window geometry in same location as in the C++ code

- src/cpp/generate-options.R
With our docs now generated from Quarto, the tooling that generates our docs from our options needs to be updated to write docs in the new format.
Write Quarto header instead of R Markdown header. For an example of output, see:
https://github.com/rstudio/rstudio-pro/blob/main/docs/server/rstudio_server_configuration/rsession_conf.qmd
None, doc change only
None, dev tool only
> Generate quarto headers for docs

- src/cpp/server/ServerEnvVars.cpp
- src/cpp/server/ServerEnvVars.hpp
- src/cpp/server/ServerMain.cpp
A recent change (https://github.com/rstudio/rstudio-pro/pull/2611) introduced environment variables such as `RS_LOG_LEVEL` to control logging features. Unfortunately, setting those environment variables in `/etc/rstudio/env-vars` doesn't work, because logging is initialized very early, before the `env-vars` file is read.
Addresses https://github.com/rstudio/rstudio-pro/issues/2758. 
Read `env-vars` file before initializing logging. There's a bit of a chicken-and-egg problem here: we want to log the info/vars we read out of the file, but we can't do it because we need to read them before initialize the logging system. As a compromise, we now read the variables (w/o any kind of logging) at startup, then re-initialize them with logging later. 
None, this alters startup sequencing but is …
> Add early init of env vars (before logging)

- src/cpp/session/modules/SessionPythonEnvironments.R
- src/cpp/session/resources/terminal/hooks
- src/gwt/acesupport/acemode/r.js
- src/gwt/acesupport/acemode/r_highlight_rules.js
- src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Addresses https://github.com/rstudio/rstudio/issues/9618
- Support auto-activate for copies of Python on the PATH
- Support auto-activate for Anaconda installations
- Fix an issue that prevents `python` from being placed on the PATH when activating a base Conda installation
- Add in comment highlight rule + continue comment behaviors for `#|` chunk metadata comments.
N/A
N/A
> wrapping up IDE python integration items

- src/cpp/server/ServerPAMAuth.cpp
- src/cpp/server/auth/ServerAuthCommon.cpp
- src/cpp/server/include/server/auth/ServerAuthCommon.hpp
In the pro version, it seems increasingly common that the assertion the auth-system provides is either an email address, upper-case user-name, or other alias for the system username. Although they can login using these aliases, RSW passes the uid to the session launch that then gets the canonical username. This creates problems for the file-name of the unix socket  and is a blocker for two customers.
Addresses: https://github.com/rstudio/rstudio-pro/issues/2736
This PR takes the existing userIdentifierToLocalUsername function in ServerSAMLAuth.cpp and moves it into ServerAuthCommon.cpp so it can be used by all auth-handlers. Further it changes that method so it uses uid to fetch the username (since getpwnam can return the username it was passed, not the canonical one for that uid) 
A …
> Support userIdentifier to local userName mapping via uid

- src/node/desktop/src/main/menu-callback.ts
- src/node/desktop/test/int/mocharc.json
- src/node/desktop/test/int/startup-fail-session.test.ts
- src/node/desktop/test/int/startup.test.ts
Test that the top-level main menu has expected items on startup for Electron desktop.
Used Playwright's `evaluate` mechanism to run code in the main process. Had to assign stable IDs to the main menu, so using the labels minus any ampersand.
Also slightly restructured existing integration tests, working gradually towards a more coherent model. No doubt more refactoring will happen as we learn more. As part of this the Electron app will now shutdown if a test fails, previously you had to go kill it.
The new test starts the app, waits for the Console tab to appear (and clicks on it for good measure), then makes sure the top-level menu items exist.
You can try this by using the `scripts/mac-package` trick (be sure to install a very recent desktop build into Applications before running the …
> basic integration test for main menu (Electron)

- src/node/desktop/test/unit/main/desktop-options.test.ts
- src/node/desktop/test/unit/unit-utils.ts
Unit tests for #9645 had a couple instances of "as any" assertions and corresponding es-lint disables. We should try to avoid needing these. 
Add a variation of `createSinonStubInstance` helper named `createSinonStubInstanceForSandbox` that works with non-default sandbox. This helper uses some TypeScript magic to work around this problem (the line ` return stub as unknown as StubbedClass<T>;`).
Note, occasionally VSCode's TypeScript support loses its mind on this construct and will flag it as an error. If you close and restart VSCode it resolves. In any case TypeScript itself (and ESLint) are both happy with it.
This is some source code cleanup on unit tests, no change to product code.
NA
> eliminate "as any" and "eslint-disables" in restore window position unit tests

- src/node/desktop/src/core/expected.ts
- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/detect-r.ts
- src/node/desktop/src/main/detect_r.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/test/unit/main/detect-r.test.ts
- Support auto-discovery of R on Windows, using the most recently recorded version from the Windows registry.
- Also support auto-discovery of C++ build sources, for those of us too lazy to set `RSTUDIO_CPP_OUTPUT_FOLDER`.
- Use `reg query <...>` to find what version of R is recorded in the Windows registry. This approach was taken specifically because I was having trouble installing + building https://www.npmjs.com/package/windows-registry on Windows.
- Some other heuristics for locating C++ build artefacts in non-package builds.
Not yet implemented.
N/A
> support auto-discovery of R on Windows

- src/node/desktop/src/core/file-path.ts
- src/node/desktop/test/unit/core/file-path.test.ts
- src/node/desktop/test/unit/main/application.test.ts
- src/node/desktop/tsconfig.json
In the C++ code, `FilePath.exists()` is synchronous and returns a boolean. In our ported `FilePath` class, `exists()` is async and returns `Promise<boolean>`, and `existsSync()` returns a boolean. This makes it easy to accidentally create ported code with the pattern:
```ts
if (file.exists()) { doSomething(); }
```
That is incorrect, since it will always be `true`. It should be invoked either as:
```ts
if (await file.exists()) { doSomething(); }
```
or directly with Promises as:
```ts
if (file.exists().then((result) => { if (result) { doSomething(); }});
```
Rename to `existsAsync()`. Then code pasted in from the C++ requires a conscious decision about whether using async or sync.
Also put the test sources in scope for the top-level tsconfig; otherwise refactoring don't update that code. …
> rename FilePath.exists to FilePath.existsAsync (Electron)

- src/node/desktop/.eslintrc.js
- src/node/desktop/package.json
- src/node/desktop/src/main/gwt-window.ts
- src/node/desktop/src/main/menu-callback.ts
- src/node/desktop/src/main/utils.ts
- src/node/desktop/src/renderer/desktop-bridge.ts
- src/node/desktop/yarn.lock
Enable strict boolean checks in our Typescript code, catching some potentially unintended boolean conversions in if conditionals (among other places).
This should help in cases where we accidentally check the value of a promise in a conditional. For example:
See https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/strict-boolean-expressions.md for more details.
> enable strict boolean checks

- src/node/desktop/.eslintrc.js
- src/node/desktop/src/main/minimal-window.ts
- src/node/desktop/test/int/startup-fail-session.test.ts
- src/node/desktop/test/int/startup.test.ts
This PR adds a number of extra eslint rules. Note that these rules flag a number of existing usages; e.g.
```
kevinushey@cdrv-2:~/rstudio-v15/src/node/desktop [feature/eslint-extra-checks]
$ yarn lint
yarn run v1.22.4
$ eslint ./src ./test
/Users/kevinushey/rstudio-v15/src/node/desktop/src/core/file-path.ts
409:14  warning  Returning an awaited promise is not allowed in this context  @typescript-eslint/return-await
/Users/kevinushey/rstudio-v15/src/node/desktop/src/main/desktop-browser-window.ts
183:3  warning  Functions that return promises must be async                                                     @typescript-eslint/promise-function-async
197:5  warning  Promises must be handled appropriately or explicitly marked as ignored with the `void` operator …
```
> add a number of extra eslint rules

- cmake/modules/FindLibR.cmake
- src/cpp/tools/dll2lib.R
I just lost a couple hours trying to fix my Windows R installation, which was failing in cmake with this error:
```
CMake Error at cmake/modules/FindLibR.cmake:152 (message):
Failed to generate .lib files for R DLLs!
Call Stack (most recent call first):
src/cpp/CMakeLists.txt:590 (find_package)
```
Finally figured out the problem, which was that due to a registry issue (no theories about how it arose), it was getting the string `/registry` as the path to R. 
Add logging to CMake so it's clear when this happens. 
None, not a product change.
No QA required.
> Improve logging of the libR location

- src/node/desktop/src/main/application.ts
- src/node/desktop/src/main/detect-r.ts
- src/node/desktop/test/unit/core/expected.test.ts
`prepareEnvironment` doesn't need to return a value other than success/failure.
Switch it to return `Err` instead of `Expected`.
Added tests for `Expected<>` pattern.
Code internals.
> use Err instead of Expected for prepareEnvironment

- NEWS.md
- src/cpp/session/modules/SessionCodeTools.R
Addresses https://github.com/rstudio/rstudio-pro/issues/2680.
While we might not intend to support R 3.2.x going forward, I think this change is small / narrow enough to take.
Detect whether `envir` is accepted by the definition of `utils::getS3method()`, and pass it along only if it is.
N/A
Test via notes in https://github.com/rstudio/rstudio-pro/issues/2680.
> support older versions of getS3method

- src/node/desktop/src/main/detect-r.ts
- src/node/desktop/src/main/main.ts
This PR gets RStudio running with Electron on Linux.
Ensure we read and use the correct R environment variables, here by explicitly asking R where they are located. (R installations on Linux typically set `R_DOC_DIR` and friends to customize their locations; e.g. in `/etc` somewhere.)
This PR also brings in our very first GPU-related workaround (oh joy!). On my Linux VM, RStudio was rendering with a blank white screen when running with the default GPU renderer (ANGLE); fixed by defaulting to the 'desktop' renderer (but we'll want to ensure we respect the user choice via desktop options).
N/A; would be tested by "regular" integration tests on Linux.
N/A
> get RStudio running on Linux with Electron

- src/node/desktop/src/main/application.ts
- src/node/desktop/tsconfig.json
When I added the tests to the tsconfig.json (so vscode's refactoring tools would also "see" the tests sources), I broke the Electron integration tests (when run against a dev build; it did still work against a package build).
https://github.com/rstudio/rstudio/blob/fe920b839f632715eb9504255fbf7abfa373020d/src/node/desktop/tsconfig.json#L15
This was causing the ResourcePath to be returned incorrectly on a dev build, causing failure to load the pages used to show loading progress, load failure, etc. Fixed by adjusting the path for non-packaged case.
Unrelated, but also removed a line in tsconfig I had added while implementing the "clean" command, ended up not needing this line.
This fixes ability of dev build to load these resource pages again.
Note that the integration tests (`yarn …
> fix integration test in dev build
