NEWS.md
src/cpp/session/modules/SessionGit.cpp

Addresses https://github.com/rstudio/rstudio/issues/4137.
In a few places, RStudio was using `runCommand()` rather than `gitExec()` when attempting to execute some `git` commands. On Windows, RStudio explicitly uses `runProgram()` rather than `runCommand()` as the Windows shell (`cmd.exe`) does not support UNC paths. This PR ensures that those usages go through `gitExec()`.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/4137.

properly handle UNC paths with git on Windows

---

src/node/desktop/src/main/detect-r.ts
src/node/desktop/test/int/int-utils.ts
src/node/desktop/test/int/utility-window.test.ts

Write a test that displays a secondary window and detects it.
Triggers the `showGpuDiagnostics` command via the console, and checks that another window was displayed.
Yes it is.
Another small test to improve my understanding of what we can do (or not do) with Playwright and Electron. Don't like that I had to use a "sleep" to give the window time to appear, will look for a better way to do that but this works in the meantime.

simple test for showing secondary window (chome gpu diagnostics) in Electron

---

src/node/desktop/src/core/file-serializer.ts
src/node/desktop/src/main/session-launcher.ts
src/node/desktop/test/int/mocharc.json
src/node/desktop/test/unit/core/file-serializer.test.ts
src/node/desktop/test/unit/mocharc.json

We decided to take the approach where exported functions shouldn't throw (except, ideally, in truly exceptional cases such as programming errors). I had written `readStringArrayFromFile` using `throw` to indicate errors.
Switch to the `Expected<result, error>` pattern. Note there are some internal helpers in this scenario that do still throw, which we also agreed was OK (though that might bite us later if we export currently private things, so we should probably minimize that, too).
Updated tests. Also, bumped up the threshold for "slow" tests in both unit tests and integration tests to reduce scary-looking red text in test results.
Internal code change only, but test runs should now be much happier looking.

exported functions shouldn't throw (Electron)

---

src/node/desktop/src/core/err.ts
src/node/desktop/src/core/file-path.ts
src/node/desktop/src/main/detect-r.ts
src/node/desktop/src/main/session-launcher.ts
src/node/desktop/test/unit/core/err.test.ts

The `Success()` function doesn't follow standard naming (shouldn't be capitalized).
Rename and update usages.
Updated
Code internals

mechanical rename of Success() to success()

---

NEWS.md
src/gwt/src/org/rstudio/core/client/dom/DomUtils.java

Addresses https://github.com/rstudio/rstudio/issues/8696.
We normally only apply our fonts to `<pre>` elements, as per https://github.com/rstudio/rstudio/blob/bugfix/font-size-computation-custom-fonts/src/cpp/session/resources/themes/css/fonts.css. However, when computing the Console width, we were doing so with a `<div>` element, which wouldn't have the custom font applied.
Because we were computing the width using a different font from the actual Console font, it's possible for text to overflow if the user has configured RStudio to use a font that is wider than the default font. This is most common on Windows, where the default font (Calibri) is somewhat more narrow.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/8696.

ensure we use a pre element when computing console width

---

src/node/desktop/src/core/system.ts
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/test/unit/core/system.test.ts

Implement more GWT callbacks, in this case the `isMacOS` and `isCentOS` callbacks.
Trivial for isMacOS; for isCentOS ported the existing C++ code.
Added test for `isCentOS`.
Internals.

implement isMacOS and isCentOS desktop callbacks (Electron)

---

src/node/desktop/package.json
src/node/desktop/src/core/r-user-data.ts
src/node/desktop/src/main/detect-r.ts
src/node/desktop/src/main/main-window.ts
src/node/desktop/src/main/session-launcher.ts
src/node/desktop/src/main/utils.ts
src/node/desktop/test/int/console.ts
src/node/desktop/test/int/session-restart.test.ts
src/node/desktop/test/int/startup.test.ts
src/node/desktop/test/unit/main/utils.test.ts

The ability to `launchNextSession` was NYI, so the "Restart R Session" command didn't do anything.
Implement enough of `launchNextSession` for that command to work.
Wrote "most" of an integration test for this, including factoring out some console-helpers to a separate file. Still need to figure out how to detect that the console output contains a string so I can assert on that.
The Session / Restart R command should now work.

Implement "restart r session" for Electron

---

src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/utils.ts
src/node/desktop/test/unit/main/utils.test.ts

The callback for File Open dialogs wasn't completed implemented, it didn't support file-type filters or the focusOwner argument.
Implement, converting the QFileDialog format for specifying filters to the one expected by Electron.
Added unit tests for the filter conversion function.
Verify that opening a project (File / Open Project) filters down to .Rproj files, another good test is importing theme files (which has multiple extensions).

complete implementation of get_open_file_name callback

---

src/node/desktop/package.json
src/node/desktop/scripts/package-helper.ts
src/node/desktop/scripts/script-tools.ts
src/node/desktop/yarn.lock

Bootstrap package build for Windows, similar to what I did for Mac (temporary solution until full builds are ready).
Wrote a script, invoked via `yarn win-package` that cleans, builds, electron-packages, and copies in the necessary bits from the installed copy of RStudio (have a recent daily build installed before running this).
THE RESULTING PACKAGE BUILD IS NOT YET FULLY FUNCTIONAL; it starts but shows the session failed to launch error page. Very likely some additional path issues needing to be worked out, but won't get to it until I'm back.
None, temporary tool.
None.

WIP on package-helper script for building Win32 package

---

src/cpp/core/Database.cpp

Addresses [Pro #2790](https://github.com/rstudio/rstudio-pro/issues/2790)
Lower the log level from WARNING to DEBUG. This will ensure that these probably innocuous logs will not cause undue concern. The probably better long term solution here would be to have the installer remove the db/ files as a pre-install step, since all the needed files will be installed during the regular install step anyway.
N/A, logging change only.
The logs should not appear unless the admin has enabled debug logging. Here is what it looks like when that is enabled:

Lower log priority of unrecognized files in db folder

---

src/node/desktop/scripts/package-helper.ts

Make it possible to create a runnable package build of RStudio for Windows (Electron), using the binaries from the RStudio build installed in Program Files. This is an intermediate step towards real builds, enabling:
* determining file layout for a Windows package build
* enable creation and running of Electron build on Windows without needing a full dev environment (akin to what I created for Mac a while back)
Tweaks to the script I created before my week off. It wasn't quite right; now it produces a package build that runs.
None, this is an internal script.
To try this, follow steps here: https://github.com/rstudio/rstudio/wiki/Electron-Desktop/_edit#windows
(repeated)
* clone the rstudio repo (for this example, assuming to `~/rstudio`)
* install a recent daily build of `RStudio.exe` to …

Fix packaged Windows layout (Electron)

---

src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.java
src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.ui.xml

Addresses https://github.com/rstudio/rstudio-pro/issues/2860.
The reason this happens is that the CSS box that contains the product name has a fixed size; the position of the RStudio logo is also fixed. This makes it somewhat difficult to accommodate all the different product names and keep the name/logo centered. So I've make a somewhat larger change that uses Flexbox to lay these all out. Now the logo can move to help center the larger Workbench product name.
Server:
Workbench:
N/A, style change only
Test via notes in https://github.com/rstudio/rstudio-pro/issues/2860.

Fix wrapping for RStudio Workbench in About

---

src/cpp/core/system/PosixSystem.cpp
src/cpp/shared_core/FileLogDestination.cpp

As far as I can tell, this function is only called between fork and exec. In that case, we still have the parent's file destinations and yet end up changing the perms to the child's runAsUser.  So rserver.log ends up with the session user's ownership perms after a session launch in open source.  Looks like maybe this is needed for temporarilyDropPrivs, but not permanentlyDropPrivs?
Addresses [this issue](https://github.com/rstudio/rstudio/issues/9715)

Don't refresh log file destinations between fork and exec

---

src/cpp/server_core/ServerDatabase.cpp

Addresses https://github.com/rstudio/rstudio/issues/9715
The sqlite database requires that write perms be available for the directory. Other parts of the code do this for Workbench but OS is missing some code to try and do the chown of the directory so I added it. 
Not necessary
A clean install on a linux machine of the OS version should show /var/lib/rstudio-server owned and writable by rstudio-server
- [x ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [ x] This PR passes all local unit …

Fix permissions for /var/lib/rstudio-server directory for sqlite 

---

src/cpp/core/Database.cpp
src/cpp/core/include/core/Database.hpp

Addresses #9706
Backport @melissa-barca's fix for the same issue on Pro to OS (see this pull: https://github.com/rstudio/rstudio-pro/pull/2827)
Do we have automated integration tests that validate restarts? If not, can we?
* This issue affects OS on Centos/RHEL 7 only.
* Starting RStudio the first time works correctly.
* Restarting afterwards leads to DB errors and a failure to start.

Fix a bug on RHEL 7 caused by sqlite pragma query

---

src/cpp/shared_core/FileLogDestination.cpp

The following sequence of events will prevent the log file from being chowned:
1. Log file was previously created as root and was never chowned to service user.
2. Process starts up again at a later time and goes to drop privilege thus attempting to chown the log BEFORE attempting to write to the log file.
3. Log cannot be chowned because the LogFile variable is not properly initialized.
This is because initialization currently only occurs when the log file is attempted to be written to.
This change also makes sure that the initialization happens in the constructor as well as during calls to write, to ensure that the path of the log file is always properly initializated and up-to-date.
None
None - very specific failure sequence that is reproducible and verified on the Launcher

Fix logging bug where chowning the logfile before writing to it does not work

---

src/node/desktop/src/main/app-state.ts
src/node/desktop/src/main/application.ts
src/node/desktop/src/main/desktop-browser-window.ts
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/main-window.ts

Secondary windows (e.g. if you popup help into a separate window) should be able to launch system browser when user clicks on a link.
Moved handling of window-creation to root window class instead of main window class, more closely matching behavior of the Qt app. Make the "application" class be in charge of implementing most of this behavior.
None.
Bring up a secondary window, for example, show a help topic in the Help pane then display it in a window. Now click on links. Confirm that behavior matches that of current Qt desktop.

enable external links in secondary windows

---

src/node/desktop/src/main/app-state.ts
src/node/desktop/src/main/application.ts
src/node/desktop/src/main/desktop-browser-window.ts
src/node/desktop/src/main/gwt-window.ts
src/node/desktop/src/main/satellite-window.ts
src/node/desktop/src/main/secondary-window.ts
src/node/desktop/src/main/utils.ts
src/node/desktop/src/main/window-utils.ts
src/node/desktop/test/unit/main/utils.test.ts

RStudio creates additional windows for various operations, such as opening editor tabs in another window, the version control windows, and showing help content in another window (this isn't the full list).
Now implemented in the Electron app. Some rough edges to sand off, mainly unimplemented logic in `secondary-window.ts` and `satellite-window.ts` (for example, can't yet close the windows with Cmd+W on Mac), but overall they are fully functional.
The key "ah-hah" here was to use `nativeWindowOpen: true`; this causes windows opened by the main window (via `window.open`) to be created in the same renderer process. This is necessary because we rely on doing things with the pattern `window.opener.doSomething()` and that can't work if each window is in its own renderer process.
This has the …

Enable satellite windows in Electron desktop

---

src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/renderer/desktop-bridge.ts

Skip extension checks if defaultExtension is empty
Addresses #9720.
When saving a new, untitled document, the default save value should be `Untitled.R`, instead of the current `~.R` when on MacOS. On Windows and Linux the default save value is currently empty

Resolve aliased directory on file save

---

src/node/desktop/src/main/app-state.ts
src/node/desktop/src/main/application.ts
src/node/desktop/src/main/desktop-browser-window.ts
src/node/desktop/src/main/main-window.ts
src/node/desktop/src/main/satellite-window.ts
src/node/desktop/src/main/secondary-window.ts
src/node/desktop/src/main/window-utils.ts

Implement several more TODOs for satellite windows and secondary windows.
Ported code that sets size of secondary windows, fixed so Cmd+W on Mac closes documents (main window and satellites) then closes window when no docs are open, and prompts for saving in satellites containing modified/unsaved docs.
None
Try closing satellite windows (editor docs, Git, etc) or Main window with Cmd+W on Mac, should close documents if any are open, and only close the window if all docs are closed or it isn't a document window.
Also check that satellite windows with modified source docs will save prompt to save before the window closes.
Check that secondary windows (e.g. show Help pane in another window) has a reasonable default size and location.

misc features for secondary and satellite windows

---

src/node/desktop/src/main/gwt-callback.ts

When dragging and dropping editor tabs, callbacks are used to decide what to do upon release. These were NYI.
Implement `desktop_get_cursor_position` and `desktop_does_window_exist_at_cursor_position` callbacks.
None.
Scenarios with dragging editor tabs out of main window onto non-rstudio screen area, or onto existing editor satellite should now work, ditto for dragging tabs from satellite windows onto non-rstudio screen area or another editor satellite.

implement callbacks for cursor hit detection (Electron)

---

src/node/desktop/src/main/application.ts
src/node/desktop/src/main/utils.ts

When starting packaged Electron IDE on Mac, getting warning in R console:
```
Warning message:
Character set is not UTF-8; please change your locale 
```
For the August milestone, add a stub for `initializeLang()` that hardcodes to en_US.UTF-8, with a TODO comment for implementing the full Mac detection logic.
None
Try running a package build by double-clicking on the icon. Then hit <enter> in the R console and confirm that the above warning message is no longer present.

Set LANG/LC_CTYPE for Mac desktop (Electron)

---

src/node/desktop/src/main/desktop-browser-window.ts
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/utils.ts
src/node/desktop/src/main/window-utils.ts

Porting a couple smaller secondary-window behaviors:
1. On Mac, clicking an RStudio window that is currently inactivate should pass the click through to the underlying page, matching the current Qt behavior.
2. Support activating windows by name (e.g. have Git window open but behind main window, then click on "Diff" in the git pane in main window; Git window should come to front and get focus
Implement these.
None
Compare described behaviors to Qt-based desktop.

Electron: pass through activation click and implement activation callbacks

---

src/node/desktop/src/main/context-menu.ts
src/node/desktop/src/main/desktop-browser-window.ts

Implements the default right-click context menu for Electron. Was mostly straightforward via existing Electron APIs; just took a while to hunt things down and workaround a few issues.

implement default context menu for Electron

---

src/gwt/src/org/rstudio/studio/RStudio.gwt.xml
src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/renderer/desktop-bridge.ts

Use the existing GWT `promptForText()` functions when prompting for text in Electron.
Detect whether we're running within Electron, and if we are, use the web dialogs rather than desktop dialogs.
Should be covered by any existing automation that tests input prompts for RStudio Server.
N/A

use web dialogs for input prompts w/Electron

---

docker/jenkins/publish-daily-binary.sh

Adjust the latest download URL for the new version format.
Change the regex in the sed command for the new version scheme.
Tested this on the command line.
None.
It should be possible to download RStudio-latest.dmg et. al. and get the latest GO or PT daily.

update based on new vesrion format

---

src/gwt/acesupport/acemode/python_highlight_rules.js

Match special highlighting for YAML chunk options in R mode within Python mode.
Added a highlighting rule that runs before the default default highlighting rule for Python comments.

highlight color for yaml in python node

---

src/cpp/session/SessionModuleContext.cpp
src/cpp/session/modules/SessionCodeTools.R
src/cpp/session/modules/SessionHelp.R
src/cpp/tests/testthat/test-codetools.R

Addresses https://github.com/rstudio/rstudio-pro/issues/2943. 
Escape HTML entities in the custom HTTP handler.
Included.
Test via notes in https://github.com/rstudio/rstudio-pro/issues/2943.

Escape paths in custom HTTP handler

---

src/gwt/src/org/rstudio/studio/client/common/spelling/domain_specific_words.csv

Hi! I noticed the real time spell checker (which I LOVE, thank you!) flags `bivariate`.
so just a suggestion to add to the whitelist if you think appropriate.
Thanks!
A quick google of the word `bivariate` points to many resources including the [Bivariate analysis wikipedia entry](https://en.wikipedia.org/wiki/Bivariate_analysis), indicating that it is a mainstream term.
I emailed the signed individual_contributor_agreement.pdf to JJ as indicated.

add bivariate to whitelist spelling

---

src/node/desktop/.eslintignore
src/node/desktop/forge.config.js
src/node/desktop/package.json

Electron forge config currently in package.json, but will need in JavaScript format so I can use Forge's custom hooks during package builds.
Move into separate JS file and reference it. Also makes package.json less huge.
None. This is a build tooling thing.
NA

move forge config into separate JS file (Electron)

---

src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp

Addresses #9795
Here is a screenshot of part of a knitted RMD that includes the environment variables as output in a chunk:
* Make `RSTUDIO_VERSION` match the output of `RStudio.Version()$version`
* Add `RSTUDIO_LONG_VERSION`
N/A
* `package_version(Sys.getenv("RSTUDIO_VERSION"))` should succeed
* `package_version(Sys.getenv("RSTUDIO_LONG_VERSION"))` will not succeed
* These variables are only set in the context of a knitted R Markdown document - they do not appear in the terminal or the R console

Make RSTUDIO_VERSION parsable

---

src/gwt/panmirror/src/editor/src/nodes/table/table.ts
src/gwt/panmirror/src/editor/src/pandoc/pandoc_converter.ts

This commit encompasses several changes to the way we handle tables in the visual editor to hopefully provide more stable and predictable output:
-   We now actively prefer pipe tables to grid tables. This is because pipe tables will (mostly) allow HTML or LaTeX rendering engines to auto-size columns (unlike grid tables which fix column sizes based on markdown width, which can be very unreliable especially in the presence of links/images). Note that pipe tables will result in explicit column widths when the total markdown size is greater than `--columns` (which defaults to 80). You can work around this by specifying a very large value for `columns` (e.g. 10000). For quarto, you can do this with:
``` yaml
columns: 10000
```
For rmarkdown, you can do this with:
``` yaml
output: …
```

Improved handling of table markdown in visual editor

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModePanmirrorContext.java

Enables us to accurately detect https URLs on windows (formerly windows paths were getting recognized as URLs)

visual mode: check explicitly for http urls in dnd image resolver

---

docker/jenkins/notarize-release.sh

Add the server response to stdout in the event of a notarization failure
not already covered by other messaging.
In a series of notarization failures, no information about the failure was written to stdout, which would require a developer get on the build machine to get the server response. The server response should just be written to the stdout.
cat out the server response in the event of a notarization failue.
Includes no tests, not a code change.
build system only change.

Improve Logging of MacOS Notarization Failures

---

NEWS-2021.09-ghost-orchid.md
src/cpp/session/resources/dependencies/r-packages.json

Brings the internal dependency lists up to date with the R packages required by Shiny, LearnR, and R Markdown. The largest change here is a major bump in the required Shiny version (1.2 => 1.6). This is necessitated by a string of events that goes as follows:
- We must depend on a very new version of R Markdown to support changes made to the visual editor.
- Very new versions of R Markdown call `shiny::getCurrentTheme()` when running Shiny R Markdown documents. This function exists only in Shiny 1.6. https://github.com/rstudio/rmarkdown/commit/9dc5d971f686d4a64ee7579117f78e648ec17a1f
- Shiny 1.6 introduces a number of new R package dependencies that were not required by Shiny 1.2. 
Addresses https://github.com/rstudio/rstudio/issues/8703. 
Bump package versions and add new packages to our …

Update dependency graphs for Shiny, LearnR, R Markdown

---

NEWS.md
src/cpp/session/include/session/prefs/UserPrefValues.hpp
src/cpp/session/prefs/UserPrefValues.cpp
src/cpp/session/resources/schema/user-prefs-schema.json
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/RMarkdownPreferencesPane.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetPrefsHelper.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java

Addresses https://github.com/rstudio/rstudio/issues/9387.
Add a new option that toggles whether or not line numbers are shown for visual mode chunks; respect it. This option is separate from the option that toggles line numbers for the code editor in general. 
N/A
The option can be also be toggled in real time on the Command Palette. Note that line numbers start at 1 in each chunk.

Add option to show line numbers in visual mode chunks

---

src/cpp/core/StringUtils.cpp
src/cpp/core/StringUtilsTests.cpp
src/cpp/core/include/core/StringUtils.hpp
src/cpp/session/modules/SessionFiles.cpp
src/gwt/src/org/rstudio/core/client/jsonrpc/RpcRequest.java
src/gwt/src/org/rstudio/core/client/jsonrpc/RpcResponse.java
src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServerAuth.java
src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileUploadDialog.java

Addresses https://github.com/rstudio/rstudio-pro/issues/698.
This one's sort of a mess and has to do with the way GWT's `FormPanel` works (see original issue for discussion). It'd be nice to refactor this whole thing in such a way that the body doesn't get treated as `text/html`, but the issue doesn't warrant it. Instead:
- Ensure the special characters `<` and `>` are encoded with Unicode escape sequences in the response body. 
- As a further failsafe, don't fall back on `eval()` for JSON responses that might contain untrusted data. 
Adds a unit test.
Test with both file and path names containing HTML tags (see original issue).

Ensure HTML entities in filenames/paths are handled on upload

---

src/gwt/src/org/rstudio/studio/client/rmarkdown/model/YamlFrontMatter.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java

Fixes https://github.com/rstudio/rstudio/issues/9866.
Change https://github.com/rstudio/rstudio/commit/5adc32552110ad8b1db8a02768ddc28b9ec52355 introduced static initializers for the `RegExp` objects that extract front matter. However, these objects maintain state and should not be re-used. The fix is to make these local variables again, while keeping the regular expression patterns themselves static to avoid repeating them. 
Covered by automation, which found this issue.
In addition to the notes in #9866, test that the editor mode preference is respected in the YAML header (which was the new functionality introduced by the change).

Fix detection of R Markdown document types from YAML

---

src/cpp/core/LogOptions.cpp
src/cpp/core/include/core/LogOptions.hpp
src/cpp/core/include/core/system/System.hpp
src/cpp/core/system/System.cpp
src/cpp/shared_core/FileLogDestination.cpp
src/cpp/shared_core/include/shared_core/FileLogDestination.hpp

Connected rstudio/launcher#73.
When configured to log to `file` or `syslog` but running in a TTY, adds a log like the following:
> Logging configuration loaded from '[path to logging.conf]'. Logging to '[path to log file | "syslog"]'. Displaying this since a TTY was detected.
This was requested in rstudio/launcher#73 to clarify why you sometimes see STDERR logs even when configured to log to a file or syslog.
When initializing the main log writer, we check to see if we're running in a TTY and output a message to STDERR if (a) running in a TTY and (b) not configured to log to STDERR.
Unit tests didn't seem practical due to the complexity of mocking or simulating running in (or not in) a TTY. There are a couple of options, but none seem ideal, so I skipped unit tests:
* Update …

Explain TTY Logging on Startup

---

src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java

Make it harder to accidentally delete files by:
- Naming the file to be deleted, if only one is selected
- Providing a count of files to be deleted, if multiple files are selected
Change the message.
N/A, UI string change
Test deleting no files, 1 file, and more than 1 file.

Richer prompt for file deletion

---

src/gwt/CMakeLists.txt

Addresses: #7660
When doing a full build (e.g. package build), the GWT portion builds in parallel with the C++ code, and this can cause thrashing and resource exhaustion that leads to a GWT build failure. Our answer has been to constrain number of cores allowed for building (`-j#`), e.g. for Mac `make-package` we set `-j2` because of this.
Make the GWT code dependent (cmake-wise) on the major C++ components; rsession, rstudio (desktop), and/or rserver so it waits for them to complete, then can give Java all available resources.
Once this gets through a round of builds or two, I'll go back and bump up the `-j` value for Mac a bit (after finding out how many cores the builder actually has...).
None, purely a build-time thing.
I tested by doing a local Mac desktop build via make-package, and …

run GWT (Java) build step after C++ builds complete

---

package/osx/make-package

With work done in #9885 to let C++ build finish before starting the GWT build, should now be able to use all cores on the Mac builder machine.
Remove the hardcoded `-j2` we were setting on a Jenkins-driven build.
None, this is purely a build-time thing.

use all cores on Mac builder

---

NEWS.md
src/cpp/session/modules/rmarkdown/NotebookCache.cpp
src/cpp/session/modules/rmarkdown/NotebookCache.hpp
src/cpp/session/modules/rmarkdown/NotebookExec.cpp
src/cpp/session/modules/rmarkdown/NotebookExec.hpp
src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/DocUpdateSentinel.java

This fixes an intermittent error, arising from a race condition, that can occur when autosave is used with R Notebooks. 
The problem occurs when the notebook save trigger and chunk execution trigger are executed with exactly the wrong timing. This used to be rare, but is becoming common on rstudio.cloud due to a combination of longer save times (caused by the visual editor) combined with save on blur (which causes execution to trigger a save, so they run almost in parallel). Because saving a notebook moves the notebook's cache to a new location, code that is executing during save may no longer be able to write to the cache's old location. 
The change also fixes a second problem mentioned in the same issue, in which untitled documents don't get autosaved if autosave is set to *Commit*. …

Fix race condition in notebook autosave

---

NEWS.md
src/cpp/core/include/core/system/LibraryLoader.hpp
src/cpp/core/system/PosixLibraryLoader.cpp
src/cpp/r/include/r/session/RSession.hpp
src/cpp/r/session/RSession.cpp
src/cpp/session/SessionMain.cpp

Addresses https://github.com/rstudio/rstudio-pro/issues/2477 by adding a check on the `libR.so` that `rsession` believes it is running. If there are issues with loading that shared object, generate an error.
Note that this does not fix the problem. Instead it creates an error that can be used to find and fix the cause of the problem, which is a system environment issue
The linked issue describes the problem in detail, but essentially while linux is loading the `rsession` binary, if there's an issue with `libR.so`, it may load a different `libR.so` without `rsession`'s knowledge. To address this, we check for issues manually once `rsession` is fully loaded by calling `dload()` with `RTLD_NOLOAD`. Any issues Linux had with loading the shared object will become apparent with that call, and …

Add check for the LibR.so that rsession believes it's using

---

src/gwt/build.xml

Regression from #9336
Building GWT code directly via `ant` or `ant draft` (without using cmake to drive the operation) fails:
```
[exec] [10:02:00] Resolved 'ide-dist' after 15s 484ms
[java] Error: Could not find or load main class ${gwt.xmx}
[java] Caused by: java.lang.ClassNotFoundException: ${gwt.xmx}
```
On a dev environment it is common to build GWT directly with ant. Note that `ant devmode` and `ant desktop` do work.
Defaults for ant properties `gwt.xmx` and `gwt.xss` were being passed on command-line from the CMakeLists.txt but this doesn't help when using ant directly, so set defaults in build.xml. Note that properties specified on command-line will override those set via `property` in build.xml.
None, purely a dev environment thing.
None

set defaults for java Xmx and Xss in build.xml

---

NEWS.md
src/cpp/r/RCntxt.cpp

Fixes an issue in which the debugger constantly thinks the context stack has changed every time the console prompt appears, causing it to reset the IDE's active file unnecessarily. 
Addresses https://github.com/rstudio/rstudio/issues/9918. 
The equality test for context objects was too strict; it compares underlying pointers to R's context stack, but it turns out that it is possible (perhaps due to a change in R?) to get two different pointers on the context stack that actually refer to the same entry. 
The fix is to consider two context stack entries to be identical if they refer to exactly the same call object (S-expression) at the same evaluation depth. 
N/A
This is a pretty low-level change that affects building the debugger's stack. Ensure that the IDE returns focus to the …

Loosen equality check for context comparison

---

NEWS.md
src/cpp/session/modules/zotero/SessionZotero.cpp
src/cpp/session/modules/zotero/ZoteroCollections.cpp
src/cpp/session/modules/zotero/ZoteroCollections.hpp
src/cpp/session/modules/zotero/ZoteroCollectionsLocal.cpp
src/cpp/session/modules/zotero/ZoteroCollectionsWeb.cpp

The visual editor's Zotero integration caches data from the user's Zotero database (if configured). We were being very aggressive about the caching and often it would take 10-30 seconds for the cache to be invalidated when the zotero database was updated. In some cased, the cache would fail to be invalidated. This PR improves the cache behavior for Zotero data.
We use the 'version' of the Zotero Collection Spec to manage the caching behavior of items throughout the system. We had been using exclusively the `version` column of items to provide this value, but this had a couple of issues:
1) the version column is set by syncing to the server, which means that it will not be set if there is no sync, but even if there is sync, the version isn't set until the server has been updating (often …

Improved Zotero Caching

---

src/cpp/session/SessionClientInit.cpp

don't return unauthorized as that triggers a retry

Return an error that's displayed as an alert in the IDE for missing CSRF

---

NEWS-2021.09.1-ghost-orchid.md
src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PythonPreferencesPaneBase.java

NOTE: this is targeting the Ghost Orchid patch.
Adding assorted code reviewers since I'm one owner of this area, and Kevin is the other and is mostly OOO.
The setting in Python preferences entitled "Automatically activate project-local Python environments" was not being persisted when the options dialog was closed. This made it impossible to disable the new functionality that this setting was added for.
See related issue: #9952
When closing/applying preference changes, persist the setting if modified, and prompt for session restart. That is necessary for the setting to take effect.
None
Verify that this setting can be enabled/disabled, and the setting persists. Also verify that the scenario described in the related issue is now working (i.e. if you turn off this checkbox, the …

Persist modified python_project_environment_automatic_activate setting

---

NEWS.md
src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileCommandToolbar.java

See: https://github.com/rstudio/rstudio/issues/9870
When the file pane is resized to narrower than 540 px, the controls begin to become cutoff due to a lack of horizontal space. The purpose of this bugfix is to alter the titles of the buttons dynamically according to the width, so that every control remains visible*
\*At prohibitively-narrow widths of less than ~280px, controls will start to be cutoff again.
Full width:
Slightly narrower:
Fully narrow:
I copied the approach used for several other toolbars that resize their own content based on their width. 
~At very narrow widths, most of the controls have their names removed __except__ for "Rename," and this was because I felt that the iconography for the other controls was self-explanatory-enough that they can stand without names, …

File pane toolbar button titles react to pane width to remain accessible

---

NEWS.md
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputFrame.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java

See: https://github.com/rstudio/rstudio/issues/2202
Solve an annoying UX issue in which users scrolling through RMarkdown files with sub-content (like kables), will be be stopped once their mouse enters the content area.
The "real" solution would be to not use `<iframe/>` anymore, as `<iframe/>` can cause unpredictable behavior.
The solution is a hack using a native function - by default the rendered output `<iframe/>` elements are "disabled" from user interaction until the user moves their mouse inside the sub-content. This will "enable" the `<iframe/>`, and it will begin accepting pointer events. Moving the mouse out of the content "re-disables" user interaction so that scroll behavior becomes predictable again.
This makes it possible to scroll vertically through a document, …

Implement scroll workaround to RMD files using iframes to show content

---

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml

`Commands.cmd.xml` has two almost identical entries for `serveQuartoSite`. This hasn't been a problem (apparently) but some incoming work for adding localizability to commands and menus breaks if there are duplicates, so want this in before that.
The original is here:
https://github.com/rstudio/rstudio/blob/7dcb20a2cc2ca8ba2a83387e38e23f222d7d4db0/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L1122-L1125
The newer one here (only difference is addition of the "... in current directory" to the description):
https://github.com/rstudio/rstudio/blob/7dcb20a2cc2ca8ba2a83387e38e23f222d7d4db0/src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml#L2441-L2444
Kept the original, got rid of the newer one.
None, this should be a no-op from an end-user …

remove duplicate command for serveQuartoSite

---

src/cpp/core/include/core/r_util/RActiveSessionStorage.hpp
src/cpp/core/include/core/r_util/RActiveSessions.hpp
src/cpp/core/r_util/RActiveSessionStorage.cpp
src/cpp/core/r_util/RActiveSessions.cpp

RActiveSessionStorage was making assumptions about the context when a
ActiveSessionStorage was created, using our XDG to discover the storage
directory.
Launcher creates some sessions to do verification but the XDG is not
populated, so it was searching in the / of the filesystem.
Removing unused or easily substitutable constructors for ActiveSession
to increase clarity.
Switched to the FileActiveSessionStorage always taking a directory,
which will be the scratch path (session-<id>) path. Gets
FileActiveStorage out of the storage discovery game.
Removed unused factory methods, we can reintroduce them later, but they were leading us astray here.
The id will still be necessary for DB calls to read and write properties
Address issue [3084](https://github.com/rstudio/rstudio-pro/issues/3084) …

Fix for Verify Installation

---

.devcontainer/Dockerfile
dependencies/linux/install-dependencies-bionic
dependencies/linux/install-dependencies-focal
dependencies/linux/install-dependencies-stretch
dependencies/osx/install-dependencies-osx
dependencies/osx/install-dependencies-osx-arch
dependencies/windows/Install-RStudio-Prereqs.ps1
dependencies/windows/install-dependencies.cmd
dependencies/windows/tools/.gitignore
src/gwt/ant
src/gwt/build.xml
src/gwt/tools/i18n-helpers/.gitignore
src/gwt/tools/i18n-helpers/commands.cmd.xml/.gitignore
src/gwt/tools/i18n-helpers/python-check-version.py

Addresses: #10068 (which was caused by #9987)
Developers shouldn't have to do anything special to build GWT after modifying Commands.cmd.xml. Currently you have to ensure python3 is installed and create a virtual-environment and pip install and so forth.
Note the build machines don't have this requirement for python/venv, etc, only dev machines when making changes that impact localization.
For Mac and Linux, the standard dev-machine dependency scripts now ensure python3 is installed and the required packages are pip-installed into a virtual environment under `src/gwt/tools/i18n-helpers/VENV`.
On Windows, the PowerShell bootstrapper installs python, and install-dependencies.cmd will install the python packages into the VENV (if python is detected).
The GWT build (ant/build.xml) now …

Automate dependencies for i18n regeneration

---

NEWS.md
src/cpp/r/R/Tools.R
src/cpp/session/modules/SessionPlots.R

Addresses https://github.com/rstudio/rstudio/issues/2919.
When using `grDevices::replayPlot()`, one needs to ensure that an appropriate graphics device is already available for use. `replayPlot()` seems to make a best-effort to initialize the graphics device, but it seems to fail if the plot depends on (for example) the `grid` package.
This PR forces us to check and see whether the plot depends on `grid`, and explicitly creates a new page for the graphics device to draw in before calling `replayPlot()`.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/2919#issue-329523236.

ensure graphics device initialized when replaying plot

---

src/cpp/core/Log.cpp
src/cpp/core/LoggingTests.cpp
src/cpp/core/include/core/Log.hpp
src/cpp/server_core/SecureKeyFile.cpp
src/cpp/shared_core/Logger.cpp
src/cpp/shared_core/include/shared_core/Logger.hpp

JSON logging is currently supported but not very helpful, as one has to parse JSON-within-JSON or escaped strings to get any useful information from a log message. Adding structured log properties to log messages allows JSON logging tools (such as Kibana) to easily categorize and search the data, so these properties should be included as raw JSON somehow.
Another issue is that subprocess log streams are currently relogged like so:
> 2021-10-14T17:08:46.576749Z [rstudio-launcher] INFO Received stderr from plugin Kubernetes: 2021-10-14T17:08:46.576479Z [rstudio-kubernetes-launcher] DEBUG Received get collection response...
This makes parsing of this difficult as well. Ideally, the subprocess logs would be neatly folded into the log stream as-is (and filtered out as appropriate based on the …

Adds the ability to passthrough log messages and add structured data to log messages

---

NEWS.md
src/cpp/r/session/REmbeddedWin32.cpp
src/cpp/session/rsession.exe.manifest

Addresses https://github.com/rstudio/rstudio/issues/9824.
Addresses https://github.com/rstudio/rstudio/issues/9792.
- Don't set memory limits for new versions of R, as these are not supported. (https://github.com/wch/r-source/commit/a984cc29b9b8d8821f8eb2a1081d9e0d1d4df56e)
- Define an application manifest, indicating that we want a UTF-8 code page.
N/A
This would require a general QA run-through on Windows. I've at least confirmed that these builds of RStudio work with both UCRT R (where a UTF-8 code page is used) and older builds of R (where we fall back to the default ANSI code page)

use UTF-8 code page with UCRT builds of R

---

dependencies/tools/rstudio-tools.sh
package/osx/make-package
src/gwt/ant

We use Intel Java even when building on M1. Noticed while working on Electron build and documenting [how to setup a dev machine on M1 Mac](https://github.com/rstudio/rstudio/wiki/M1-Mac-Dev-Machine-Setup).
This works, but is slower than a native M1 Java when building GWT. On my M1 Mini, took 11 minutes for a full GWT build with Intel, down to 7 minutes with the M1 Java. Only tried once so not particularly scientific.
Homebrew doesn't install an M1 JDK, nor is it available (for JDK8 or 11, at least), directly via https://adoptium.net/ (formerly https://adoptopenjdk.net/). See also: https://github.com/AdoptOpenJDK/homebrew-openjdk/issues/530
Update make-package to prefer the `zulu-11` JDK if installed, otherwise use what it's currently using. Note that M1 Mac can use the M1 Java even when …

Use native M1 Java if available when building on M1 Mac

---

.devcontainer/Dockerfile
CMakeGlobals.txt
dependencies/common/install-crashpad
dependencies/common/install-npm-dependencies
dependencies/common/install-pandoc
dependencies/common/install-qt.sh
dependencies/common/install-quarto
dependencies/linux/install-dependencies-bionic
dependencies/linux/install-dependencies-debian
dependencies/linux/install-dependencies-focal
src/cpp/CMakeLists.txt

Make it possible to produce development builds of RStudio Server on aarch64 Linux. With this PR, one can generate builds of RStudio Server with something like:
```
cmake ../cpp -DRSTUDIO_DESKTOP=0
```
Note that we don't yet support the use of the visual editor as `curl` segfaults when trying to download the yarn installer.
Tweak and disable some dependency installer scripts for aarch64.
N/A
N/A

support server development builds on Linux aarch64

---

src/cpp/CMakeLists.txt

When working on RStudio Electron on an M1 Mac, the app will fail to launch if you generate the native code build using no explicit RSTUDIO_TARGET, e.g.:
`cmake ../cpp`
This fails because the config here becomes RSTUDIO_DEVELOPMENT but doesn't include RSTUDIO_DESKTOP (by design on an M1 Mac only), and the required `rdesktop-dev.conf` file is thus not generated.
It does work if you generate with `-DRSTUDIO_TARGET=Electron` but shouldn't really need to do that, just like you don't when working on Qt desktop.
Eventually, on Mac, we'll automatically set RSTUDIO_ELECTRON as the target when none is specified, but not ready for that just yet.
Generate this file even if only RSTUDIO_DEVELOPMENT target was enabled.
None, purely a dev machine thing.
None

generate rdesktop-dev.conf on M1 mac for dev builds

---

dependencies/osx/install-dependencies-osx
dependencies/tools/rstudio-tools.sh

Addresses #10094 (currently you have to manually create /opt/rstudio-tools before the dependency scripts will work when setting up an IDE dev machine).
Try to create folder without sudo, if that fails, use sudo.
None, dev machine scripting
Purely a dev machine thing

fix mac dependency scripts to create /opt/rstudio-tools via sudo if necessary

---

src/cpp/r/CMakeLists.txt
src/cpp/r/include/r/session/RBusy.hpp
src/cpp/r/session/RBusy.cpp
src/cpp/session/SessionSuspend.cpp

Addresses https://github.com/rstudio/rstudio/issues/10110.
Previously, we _always_ sent R an interrupt. This had the unfortunate side-effect of interrupting any potential future calls to `R_ProcessEvents()`, whose errors we also log. With this change, we only interrupt R if it appears to be busy (that is, has something on the stack that can be interrupted).
N/A
N/A

only interrupt R on suspend if it's busy

---

src/cpp/core/LogOptions.cpp

Fixes an issue where the logger would fail to initialize when RStudio Server was run as a non-root user. This also appeared to cascade in a strange way where session restarts would cause RStudio Server to "disconnect" from the session.
Note for review: would this change the existing behavior for existing users of RStudio Server (the open source version)?
When we're not root, prefer logging to a user-specific data log directory.
N/A
N/A

prefer user data directory for logs when not root

---

docker/jenkins/Dockerfile.bionic-amd64
docker/jenkins/Dockerfile.centos7-x86_64
docker/jenkins/Dockerfile.centos8-x86_64
docker/jenkins/Dockerfile.debian9-x86_64
docker/jenkins/Dockerfile.opensuse15-x86_64
package/linux/make-package

Build packages with Ninja on Linux to avoid hang potentially caused by cpack-ing with Unix Makefiles.
If ninja is present, use ninja. Otherwise, continue to use Unix Makefiles.
Install ninja in all linux docker images except SLES12, because it doesn't have the package available.
N/A - build system change only.
N/A - build system change only.

Build packages with Ninja on Linux

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunkRowState.java

Addresses https://github.com/rstudio/rstudio/issues/10156. 
Watch the document for changes made to the line containing the lint indicator in the gutter. When they occur, remove the indicator. If the user's changes don't address the issue, it'll come back when the chunk is re-linted later.
N/A, visual change to gutter indicator only.
Test via notes in 10156.

Remove lint indicator when associated line is edited in visual mode

---

package/linux/make-package

Desktop builds on linux are failing due to the `NOTICE` file being included twice. Rather than change the what's already working, this PR lowers the severity of the dupbuild flag from error to warning.
See intent.
N/A - builds only
N/A - builds only

Reduce duplicate file from error to warning for ninja

---

src/gwt/panmirror/src/editor/src/behaviors/insert_symbol/insert_symbol-plugin.tsx

Switch to onFocus events which have different event bubbling behavior in React 1.7.
- fixes #10176
Fixes issue with insert emoji and symbol dialog when launched from the insert menu.
Switch to different focus events due to behavior change in React 1.7.
N/A
N/A

React 1.7 Changes Focus Behavior

---

src/node/desktop/src/core/array-utils.ts
src/node/desktop/src/main/desktop-browser-window.ts
src/node/desktop/src/renderer/preload.ts
src/node/desktop/test/unit/core/array-utils.test.ts

Launching dev build of Electron on MS-Windows was giving a blank screen, with exceptions being thrown by GWT indicating the desktop hooks are undefined.
Preload code assumed that argument added via `additionalArguments` mechanism when creating `BrowserWindow` was guaranteed to be last item in `process.argv`; it was not on Windows. Webpack was appending `/prefetch:1`, and the code then tried to use this as the list of apiKeys to attach, thus attaching none of them.
Fixed by using a prefix `--apiKeys=` to identify this argument, and looking for that instead of assuming the position.
Added unit test for new routine `firstStartingWith`.
Can now launch Electron IDE on Windows and see... the IDE.

Fix Electron desktop on Windows (blank window)

---

package/osx/make-package

Addresses #10063 
I was expecting cpack to set the package name, but it happens in the make-package script. Now update the bundle name to be correct.
I will have to merge this to Pro and main/main-Pro
N/A - package file name
Mac OS dailies should have a `-` instead a `+`

Generate Mac OS packages with a `-` instead of a `+`

---

src/gwt/panmirror/src/editor/src/api/ui.ts
src/gwt/panmirror/src/editor/src/optional/ace/ace.ts
src/gwt/src/org/rstudio/studio/client/panmirror/ui/PanmirrorUIChunks.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/assist/RChunkHeaderParser.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunks.java

Addresses https://github.com/rstudio/rstudio/issues/9929.
The classes are already being parsed on the panmirror side, so this change does the following:
1. Forwards the set of classes on the chunk/node from Panmirror to GWT
2. Uses the chunk's class as its execution "engine" displayed in the summary if no knitr engine is specified
The visual editor does not currently have automated testing. See https://github.com/rstudio/rstudio-ide-automation/issues/106.
In addition to the scenario outlined in the bug, there are a number of ways of specifying classes for non-executable code; they all should work. See this doc for a list:
https://quarto.org/docs/getting-started/running-code.html#non-executable-blocks

Show class in collapsed chunk summary

---

src/gwt/panmirror/src/editor/src/behaviors/insert_citation/insert_citation.tsx
src/gwt/panmirror/src/editor/src/behaviors/insert_citation/source_panels/insert_citation-source-panel-doi.tsx

Improve the behavior of the Insert Citation panel, specifically the DOI panel, which currently doesn't allow the result to be unselected, once populated. 
(Addresses leftover in issue #9124)
The DOI panel used to force the result to always be selected. Instead, the global panel will default select a single result whenever any search returns a single result, then allow that single result to have normal selection behavior.
n/a
n/a

Automatically select result when there is only a single result

---

src/cpp/session/modules/zotero/ZoteroCollectionsLocal.cpp

We were not correctly finding the default Zotero profile on linux, and consequently we were not detecting whether Better BibTeX was installed (due to different folder structures between platforms). This change will correctly resolve relative paths against the profiles directory on linux.
Correct the path we inspect for resolving profiles on linux.
n/a
There should be no change of behavior on Mac or Window, though those are differing code paths.

Correct relative path resolution to Zotero profile on *nix

---

src/cpp/session/modules/zotero/ZoteroCollectionsLocal.cpp

Our Better BibTeX detection wasn't properly finding the default profile on Linux. Fix the path that paths are resolved to fix this.
Don't use the parent path on Linux.
N/A
Note that code paths for Win, MacOs, and Linux are each different in this case.

Fix BetterBibTeX detection on Linux

---

src/cpp/r/R/Api.R
src/cpp/r/R/Tools.R

This PR adds two functions, `.rs.bugReport()` and `.rs.api.bugReport()`, intended to be used both internally by us and by users to report bugs in the IDE. The goal is to automate some of the R + RStudio session information discovery, so bug reporters don't need to manually update the issue template for new bugs.
The internal version `.rs.bugReport()` is intended to be used by us, and can be used to report product bugs in both the open source and the Pro products.
Currently, the API function is only used for filing bugs on the open-source repository.
Addresses https://github.com/rstudio/rstudio/issues/10221.
N/A
Test that you can create a bug report using …

add API for bug reporting

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java

Addresses an unfinished part of https://github.com/rstudio/rstudio/issues/9929, in which zero-line chunks didn't have the right summary shown when collapsed. 
Read the class outside the loop that parses lines, since that loop doesn't run at all if there are no lines. 
No automation available for visual editor. 
See https://github.com/rstudio/rstudio/issues/9929.

Read class as engine for zero line chunks

---

src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesListDataGridStyle.css

Addresses https://github.com/rstudio/rstudio/issues/10219.
Restore some style rules that were over-aggressively removed when excising the Classic theme.
N/A, this is a pure CSS/visual change. 
This change only affects the Files pane.

Fix display of selected items in Files pane

---

src/cpp/r/RCntxt.cpp

Addresses https://github.com/rstudio/rstudio/issues/10045, a regression introduced by https://github.com/rstudio/rstudio/pull/9922. 
The original equality check in #9922 didn't check source references, so stepping linewise through a function (which changes the source references as you step) didn't register as an update. The fix is to add these to the equality check.
https://github.com/rstudio/rstudio-ide-automation/issues/497
There's a good repo case in https://github.com/rstudio/rstudio/issues/10045. The original issue that #9922 was intended to fix was https://github.com/rstudio/rstudio/issues/9918, so make sure that this change keeps that fix intact, too.

Ensure source ref change triggers context update

---

src/cpp/session/modules/ModuleTools.R

@mine-cetinkaya-rundel reported seeing a temp file left over after publishing a Quarto presentation to RPubs. I initially thought it was something Quarto specific but it looks to me as if whenever we call `.rs.pandocSelfContainedHtml` we don't remove the temp file. Here's the commit where creation of the temp file was introduced:
https://github.com/rstudio/rstudio/commit/364819687bf1498a27554056b25a170ce93de1c7
This fix just adds an `on.exit` handler that removes the temp file. @jmcphers asking for your review as a sanity check.

Remove temp file created as part of pandocSelfContainedHtml

---

src/cpp/r/R/Tools.R
src/cpp/session/CMakeLists.txt
src/cpp/session/SessionClientEvent.cpp
src/cpp/session/SessionMain.cpp
src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp
src/cpp/session/modules/SessionClipboard.cpp
src/cpp/session/modules/SessionClipboard.hpp
src/gwt/src/org/rstudio/core/client/command/EditorCommandManager.java
src/gwt/src/org/rstudio/core/client/dom/Clipboard.java
src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
src/gwt/src/org/rstudio/studio/client/application/Application.java
src/gwt/src/org/rstudio/studio/client/application/events/ApplicationEventHandlers.java
src/gwt/src/org/rstudio/studio/client/application/events/ClipboardActionEvent.java
src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialog.java
src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.ui.xml
src/gwt/src/org/rstudio/studio/client/quarto/ui/NewQuartoDocumentDialog.ui.xml
src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java
src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ConnectionsPresenter.java
src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java
src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/CallFramePanel.ui.xml
src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextToolbar.ui.xml

Addresses https://github.com/rstudio/rstudio/issues/10221.
Previously, we were relying on the `clipr` package being available to write to the clipboard; however, this can be unreliable if the command line tools it relies on aren't available.
This PR makes it possible for the session request the front-end write some text to the clipboard.
Fairly straightforward addition of a clipboard module + wiring.
N/A
Test that `.rs.bugReport()` works as expected on RStudio Desktop with Ubuntu 20.04.

allow session to copy text to clipboard

---

src/cpp/core/include/core/r_util/RActiveSessions.hpp
src/cpp/core/r_util/RActiveSessions.cpp

Empty Sessions should not have a storage backing, and this was causing
desktop to produce metadata files
Desktop uses an empty session, which should not be connected to s storage backend.
Drop the call to the scratchpath constructor for empty sessions.
None added.
Run a desktop session, then investigate your user directory, rstudion/sessions/active should contain no metadata files now.

Fix for Desktop Creating Metadata Files

---

src/cpp/session/modules/build/SessionBuild.cpp
src/cpp/session/modules/build/SessionBuildErrors.cpp
src/cpp/session/modules/build/SessionBuildErrors.hpp

closes #10252
Delaying retrieving the version of testthat until we know we need it, i.e. when this is a build of type "TestFile" or "TestPackage". Getting the version directly in `testthatErrorParser()` rather than pass it in `testthatErrorParser`
```cpp
CompileErrorParser testthatErrorParser(const FilePath& basePath)
{
core::Version testthatVersion;
module_context::packageVersion("testthat", &testthatVersion);
return boost::bind(parseTestThatErrors, basePath, _1, testthatVersion);
}
```
> Add additional information for QA on how to validate the change, paying special attention …

get testthat version only if TestFile/TestPackage

---

src/gwt/src/org/rstudio/core/client/ElementIds.java
src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobOutputPanel.java
src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsListViewImpl.java

Add element IDs for launcher UI to allow for automation of #3076
See Jeff's comment here for details:
https://github.com/rstudio/rstudio-pro/issues/3076#issuecomment-996402381
Create and assign element IDs to represent each job in the launcher view and to represent the job output pane.
N/A - these are to enable writing of automated tests
N/A - writing the tests will test this

Assign element ids to job launcher widgets

---

NEWS.md
src/cpp/r/include/r/session/RSession.hpp
src/cpp/r/session/graphics/RGraphicsDevDesc.cpp
src/cpp/r/session/graphics/RGraphicsDevDesc.hpp
src/cpp/r/session/graphics/RGraphicsDevDescVersions.hpp
src/cpp/session/include/session/SessionOptions.gen.hpp
src/cpp/session/session-options.json

IDE support for R graphics engine 15 used in R version 4.2 (not yet released -- latest devel build)
Addresses issue #10058.
This should be roughly similar to the [PR for graphics engine 14](https://github.com/rstudio/rstudio/pull/9283)
Followed approach outlined in [wiki](https://github.com/rstudio/rstudio-pro/wiki/RStudio-Graphics-Device)
None
TBD

support for R graphics engine 15 (#10058)

---

src/cpp/session/SessionConsoleProcess.cpp
src/cpp/session/resources/terminal/hooks

Addresses #10271.
If `CONDA_PREFIX` is set in the R session (normally done for project-local Conda environments), then forward that to Terminal sessions.
Also munge `PS1` to avoid an extra-long prefix for project-local environments.
N/A
Create an RStudio project, and then create a project-local Anaconda Python environment. You can do this with:
```
conda create -p /path/to/project/env
```
Then, within the R session, create a terminal instance and try installing a conda package, e.g.
```
conda install numpy
```
Verify that the package is installed into the project-local conda environment.

forward CONDA_PREFIX to terminal sessions

---

src/gwt/src/org/rstudio/core/client/files/filedialog/PathBreadcrumbWidget.java

Addresses #10092
Adds a hover title for the go to project directory button
There was an existing description set on the button but it needed to be set for the title.
none
Just a hover title added on the button

Add hover text to Project button

---

src/gwt/acesupport/acemode/sql_highlight_rules.js
src/gwt/test/highlight_test_sql.html

adds `#` highlighting to sql files #9578 
Added another regex rule to find `#` and include text to end of line in the highlight.
There appear to be some ace tests that are html files to execute the highlighting code. It doesn't appear to be part of any kind of test harness and is a manual test. I did create another one to show the token is detected as a comment.
Low risk. Adds highlighting using a similar rule to the `--` comment token.

Add sql hash comment highlighting

---

src/cpp/session/modules/SessionDataImportV2.R

Adresses (part of) #8945
Using `read_csv(guess_max = 50)` instead of `read_csv(n_max = 50)` for the preview gives better guess when the data is not too big. 
When it is too big, we end up with the bad guess we previously were getting, but then we could (not done here) have access to the `problems()` and then show it in the ui somehow. 
Generate some data: 
```r
library(readr)
temp_data <- function(file, n = 1e5) {
df = data.frame(col1=rep(NA, n), col2=rep(NA, n))
df$col1[1e2] = 1
df$col1[1e5] = 5000
write.csv(df, file, row.names=FALSE, na="")
invisible(NULL)
} 
tf5 <- …
```

using guess_max instead of n_max

---

src/node/desktop/src/main/desktop-browser-window.ts

Fix an issue that would make the cursor icon for when it was hovering separators, to appear differently than the ones used in the regular RStudio app.
Added a custom CSS styling for when the cursor was hovering the separator classes. This should also fix this issue in other platforms as well.
None
Run the electron app by running `yarn start` under `src/node/desktop` folder. Then check the cursor over the vertical and horizontal separators. It should match the ones on the regular RStudio app.
Addresses #9673

Added correct cursor icon for Vertical and Horizontal Separators

---

src/gwt/src/org/rstudio/core/client/widget/ProgressDialog.ui.xml
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/AppNameTextbox.ui.xml
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/AppNameTextboxAppNameTextboxUiBinderImplGenMessages_en.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/AppNameTextboxAppNameTextboxUiBinderImplGenMessages_fr.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishRPubs.ui.xml
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishRPubsPublishRPubsUiBinderImplGenMessages_en.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/PublishRPubsPublishRPubsUiBinderImplGenMessages_fr.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectAuthWait.ui.xml
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectAuthWaitRSConnectAuthWaitUiBinderImplGenMessages_en.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectAuthWaitRSConnectAuthWaitUiBinderImplGenMessages_fr.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectCloudAccount.ui.xml
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectCloudAccountRSConnectCloudAccountUiBinderImplGenMessages_en.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectCloudAccountRSConnectCloudAccountUiBinderImplGenMessages_fr.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.ui.xml
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeployRSConnectDeployUiBinderImplGenMessages_en.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeployRSConnectDeployUiBinderImplGenMessages_fr.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectLocalAccount.ui.xml
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectLocalAccountRSConnectLocalAccountUiBinderImplGenMessages_en.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectLocalAccountRSConnectLocalAccountUiBinderImplGenMessages_fr.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectNewAccount.ui.xml
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectNewAccountRSConnectNewAccountUiBinderImplGenMessages_en.properties
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectNewAccountRSConnectNewAccountUiBinderImplGenMessages_fr.properties

This PR tackles ui.xml files in studio.client.rsconnect.
Issue: https://github.com/StatCan/daaas/issues/755
@gtritchie I started i18n-ifying the ui.xml files under the rsconnect folder. I followed the [gwt i18n documentation on UiBinder](http://www.gwtproject.org/doc/latest/DevGuideUiBinderI18n.html) I was able to verify a few html pages in the Connect Account page. But for the other ui.xmls I was not sure where they existed in RStudio/how to access them. 
I used the ui:msg tags to …

feat(i18n): i18-nify RSConnect UIBinder files

---

src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PaneLayoutPreferencesPane.java

addresses #10213
I've tried to be minimal, as the "Presentation" item seems te be special somehow. The associated checkbox seems to be always hidden, in the `ModuleList` constructor: 
```java
ModuleList(String width)
{
checkBoxes_ = new ArrayList<>();
FlowPanel flowPanel = new FlowPanel();
for (String module : PaneConfig.getAllTabs())
{
CheckBox checkBox = new CheckBox(module, false);
checkBox.addValueChangeHandler(this);
checkBoxes_.add(checkBox);
flowPanel.add(checkBox);
if (module == "Presentation")
checkBox.setVisible(false);
}
ScrollPanel scrollPanel = new ScrollPanelWithClick();
scrollPanel.setStyleName(res_.styles().paneLayoutTable());
scrollPanel.setWidth(width);
scrollPanel.add(flowPanel);
initWidget(scrollPanel);
}
```
But still there however, this pr just skips it from …

Omit "Presentation" from labels

---

src/cpp/core/include/core/r_util/RActiveSessions.hpp
src/cpp/core/r_util/RActiveSessions.cpp
src/cpp/session/SessionClientInit.cpp
src/cpp/session/SessionSuspend.cpp

Improve session resumed message so only the most recent message appears on resume
Add timestamps when a client last connected to a session
Improve detecting of connecting to a running session vs. a suspended session
Remove parenthetical plural from mostSignificantTimeAgo()
Addresses https://github.com/rstudio/rstudio-pro/issues/3158. Also fixes https://github.com/rstudio/rstudio-pro/issues/3158
Added timestamps that record when a client connects to a session. This "resumed" timestamp, when used in conjunction with the "suspended" timestamp is used to determine if a client is connecting to a session that was awake (has a valid resumed timestamp, but an invalid suspended timestamp) or that was suspended (has a valid suspended timestamp).
Unfortunately, I couldn't come up with a way to …

Prevent session resume messages from appearing too often and persisting in console history

---

src/gwt/src/org/rstudio/core/client/widget/SmallButton.css
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/findreplace/FindReplaceBar.css
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/findreplace/FindReplaceBar.java

This fixes a visual regression caused by the removal of the classic theme in https://github.com/rstudio/rstudio/pull/10081. 
I noticed that the elements in the affected area had some alignment issues so I nudged some margins to improve those while I was in the code.
Before (Ghost Orchid):
After: 
Addresses https://github.com/rstudio/rstudio/issues/10316.
Just CSS tweaks.
NA, visual impact only.
NA, visual impact only.

Fix spacing around small buttons in find/replace

---

dependencies/common/install-yarn

This prior PR (#10159) changed dependency script behavior such that if yarn is already installed it no longer ran the "yarn install" step for the panmirror dependencies. Installing yarn vs. "yarn install" in `src/gwt/panmirror/src/editor` are separate things.
Without this it's easy to get into a situation (e.g. juggling multiple repos) where trying to build GWT will give:
```
panmirror:
[exec] internal/modules/cjs/loader.js:892
[exec]   throw err;
[exec]   ^
[exec]
[exec] Error: Cannot find module 'fuse-box/sparky'
[exec] Require stack:
[exec] - /Users/gary/alt/loc/rstudio/src/gwt/panmirror/src/editor/fuse.js
[exec]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
[exec]     at Function.Module._load (internal/modules/cjs/loader.js:745:27)
[exec]     at …
```

install panmirror node deps even if yarn already installed

---

NEWS.md
src/cpp/session/modules/NotebookPlots.R
src/cpp/session/modules/rmarkdown/NotebookExec.cpp
src/cpp/session/modules/rmarkdown/NotebookPlots.cpp
src/cpp/session/modules/rmarkdown/NotebookPlots.hpp

Address the issue in #9931. 
```
plot(1, main = "あいう ABC", xlab = "あいう ABC")
```
should be able to render properly with Japanese characters when ragg is the graphics device, whether the plot is being rendered in the console or inline as a notebook chunk.
`.rs.createNotebookGraphicsDevice` function should respect and pass along the graphics device type, if it has been set. We can read it in directly from `getOption("RStudioGD.backend")`. 
The user can set the default device by either adding `options(RStudioGD.backend='ragg')` to their .Rprofile, or in the IDE by going to Tools > Global Options > Graphics and selecting AGG under Backend (after installing `ragg`). 
If the device has been set in the knitr chunk options, it will render using that device when knit, but to render properly …

use graphics device backend type when set, to allow for ragg rendering of NB plot

---

NEWS.md
src/cpp/session/modules/SessionPackages.R

wininet for secure download is soft-deprecated in R 4.2. It was previously the default download method on Windows. Users would see a deprecation warning message whenever installing packages on Windows using R-devel (R 4.2+)
We are replacing wininet with libcurl as the default method for secure download for Windows where R is version 4.2+ and libcurl is available.
It deals with how Windows handles downloading any file from the internet (http or https), which most importantly is part of every call to install.packages
You will see that currently in the daily builds if you use R-devel (4.2) on Windows, and run `install.packages(pkg)` you will get a warning message
```
Warning in install.packages :
the 'wininet' method is deprecated for http:// and https:// URLs
```
And if you run …

use libcurl with windows and R 4.2+

---

src/gwt/acesupport/acemode/sql_highlight_rules.js

Compromise for MySQL comments and SQL Server temp table syntax. Without building vendor specific highlighting rules, this allows for comment highlighting when `#` is at the beginning of the line.
#9578
Change regex to match at the beginning of the line
None
SQL Server temp table creation syntax won't be highlighted. The comment highlighting only works when `#` is at the beginning of the line.

Change SQL comment highlight to line start

---

src/cpp/core/include/core/r_util/RActiveSessions.hpp

Improve error message, and reduce severity, when session property timestamps can't be read
When reading timestamps from a string/file, a valid value is `not-a-date-time`, which can be generated by `boost::posix_time::to_iso_extended_string`. However, the companion function `boost::posix_time::from_iso_extended_string` does not handle the `not-a-date-time` case and will throw an error:
```
2022-01-11T20:00:23.749984Z [rsession-rstudio] ERROR Failed to read property suspend_timestamp with value: 'not-a-date-time' error: bad lexical cast: source type value could not be interpreted as target; LOGGED FROM: rstudio_boost::posix_time::ptime rstudio::core::r_util::ActiveSession::ptimeTimestampProperty(const string&) const src/cpp/session/SessionSuspend.cpp:433
```
Added a check to handle the …

Add check for "not-a-date-time" values in session property timestamps

---

src/cpp/session/SessionOfflineService.cpp
src/cpp/session/http/SessionHttpConnectionListenerImpl.hpp

This fixes a problem that showed up when running the test suite
with session-handle-offline-timeout-ms=0 - basically, running all
offlineable requests on the offline thread. Every once and a while it
would try to run an offline request before the session was initialized.
That would initialize the session on the wrong thread, getting a ton of
errors and eventually a crash.
I don't think it's likely without that setting but just to
be safe I also added the session init test to the offline thread as well.
Part of the fix for: https://github.com/rstudio/rstudio/issues/9868
Check if session has been initialized before all "offlineable" request handling. 
Tested as part of #9868 
- [x ] If this PR adds a new feature, or fixes a bug in a previously released …

Avoid offline requests before the session is initialized

---

NEWS.md
src/cpp/session/modules/NotebookConditions.R

Addresses #9436. 
Handle message and warning chunk options with rs.notebookConditions.onWarning and rs.notebookConditions.onMessage handlers. These functions handle whether or not warnings and messages should be output to the console, but they weren't actually being called. Assigning the handler to a temporary variable in the global environment, rather than the rstudio::tools environment fixes the issue.
NA
Run the following notebook chunks inline and ensure warnings and messages are shown/not shown as expected.
~~~
---
title: "message"
---
```{r, message=FALSE}
message("You will NOT see the message.")
```
```{r}
message("You WILL see the message.")
```
```{r, message=TRUE}
message("You WILL see the message.")
```
```{r, warning=FALSE}
warning("You will NOT see the …
```

Ensure that onWarning onMessage handlers actually get respected during chunk execution

---

src/cpp/core/file_lock/FileLock.cpp
src/cpp/core/file_lock/LinkBasedFileLock.cpp
src/cpp/core/include/core/FileLock.hpp
src/cpp/session/SessionSourceDatabase.cpp
src/cpp/shared_core/FilePath.cpp

Related to https://github.com/rstudio/rstudio-pro/issues/2460.
Some network filesystems (notably, Amazon EFS) do not support hard links, which leads to file locking failures in those environments. This PR provides an alternative that uses symlinks rather than hardlinks, for users who find the advisory file locks are still unreliable in such an environment.
Add a new entry to `/etc/rstudio/file-locks`, which allows one to toggle between the use of symlinks vs. hard links when creating file locks. When enabled, we use `::symlink()` instead of `::link()` when creating a lock.
N/A
N/A

support use of symlinks for file locks

---

NEWS.md
docker/jenkins/Dockerfile.opensuse-x86_64

Our SLES 12 artifacts have been compiling against openssl 1.1 breaking compatibility for SLES 12 users.
Our docker build containers use LEAP 15 to build our SLES 12 artifacts, which accidentally introduced the openssl 1.0.2 -> 1.1 upgrade. I rolled back from 1.1, to 1.0.2 manually, and fixed some dependencies that got removed during the transition.
This is a build only change, requiring no tests. The build/artifact with test this.
SLES 12 builds should now run.

SLES 12 Downgrade From OpenSSL 1.1 to 1.0.2

---

src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/LintManager.java
src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/model/LintItem.java

Fixes #10062 
The changes for #9010 allows for ANSI codes to add in styling. This updates the gutter tooltip text to render the ASCII codes.
Use the VirtualConsole to render the text for the lint item. This converts the code, as is done for the source code markers, to HTML for the Ace annotation.
None
Specifying HTML in the source code marker is still escaped so no XSS is possible. The only HTML allowed is what the VirtualConsole renders.
```R
foo <- cli::bg_br_white(cli::col_red("I am red!<br/>"))
markers <- list(
list(
type = "error",
file = "html.R",
line = 2,
column = 1,
message = foo)
)
rstudioapi::sourceMarkers("custom markers", markers)
```

Render ANSI codes in gutter text

---

Jenkinsfile
Jenkinsfile.macos
docker/jenkins/sentry-upload.sh

(disabled the old retry logic in sentry-upload.sh)
this is primarily to get around the a problem when sentry can hang up the build indefinitely.  Note that previously we were retrying 5 times with 30 seconds of sleep in between. I just disabled that logic in favor of 2 retries with a timeout.

Add retry and timeout logic for sentry upload

---

NEWS.md
src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/export/SavePlotAsPdfDialog.java

Fixes #9185
Fix orientation to match portrait or landscape selection
Fix setting paper size name to custom when setting a custom size
It's confusing for a user to set a size where the dimensions create a landscape aspect ratio and the landscape option is set. It is assumed that the custom dimensions have a width less than the height (portrait). So setting custom dimensions where width is greater than height (landscape), results in a portrait output when landscape is selected.
This change is more intuitive for the user since it will export the plot according to the set orientation and use the dimensions as the paper size.
Also, the paper size name when setting a custom size has been fixed. It never updated the UI to `(Custom)` despite the model updating the available paper sizes.
If …

Export PDF option fixes

---

src/cpp/core/include/core/system/Process.hpp
src/cpp/core/system/PosixChildProcess.cpp
src/cpp/core/system/Process.cpp
src/cpp/core/system/Win32ChildProcess.cpp
src/cpp/session/SessionMain.cpp

companion to: https://github.com/rstudio/rstudio-pro/pull/3207
This one should have gone into OS first since almost all of the files touched are here. It was reviewed by Kevin in rstudio-pro.

OS companion commit to fix defaults for callbacksRequireMainThread for rsession

---

src/cpp/session/modules/SessionDataViewer.R
src/cpp/tests/testthat/test-dataviewer.R

deal with #10332
Improve `.rs.flattenFrame()` so that matrices are also flattened. 
```r
library(tibble)
set.seed(123)
my_matrix <- matrix(c(1:20, 1:20), ncol = 2)
df_col <- data.frame(x = 1:20, y = 1:20)
tbl <- tibble(x = letters[1:20], y = 1:20, mat_col = my_matrix, df_col = df_col)
View(tbl)
```
should display: 
filter and sort should work just fine.

rework `.rs.flattenFrame()` so that matrix columns are shown

---

src/gwt/src/org/rstudio/core/client/ElementIds.java
src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RmdFrontMatter.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetRMarkdownHelper.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ui/NewRMarkdownDialog.ui.xml

addresses #10328 and follow up #10152
Adding a Date field, with default to `` "`r  Sys.Date()`" ``
- `File > New File > R Markdown` 
- Leave default
- ok 
The front matter will look like this
```
---
title: "Untitled"
author: "me"
date: "`r Sys.Date()`"
---
```
- save to file
- knit
the rendered file should have today's date.

Add Date: field with default to `r Sys.Date()`

---

src/cpp/r/R/Api.R
src/cpp/r/include/r/session/RSession.hpp
src/cpp/session/SessionConsoleInput.cpp
src/gwt/src/org/rstudio/studio/client/workbench/views/console/events/ConsoleInputEvent.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/events/SendToConsoleEvent.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java

addresses #8884 
This uses the existing flag, with a new `kConsoleInputNoEcho` on the server side that cancels prompt and console input events. 
The flag is set on the client side when `echo` is set to FALSE. 

Support for `rs.api.sendToConsole(echo = FALSE)` and `animate=`

---

src/cpp/session/modules/SessionReticulate.R

Currently, the IDE calls Python's builtin `len()` on defined Python objects, and wraps the call in an R `tryCatch()` in case the object doesn't define a `__len__` method. While the exception is handled on the R side, it is unfortunately allowed to persist in the Python session, resulting in a less-than-useful value for `reticulate::py_last_error()` in interactive sessions.
Related: https://github.com/rstudio/reticulate/issues/1134, cc @kevinushey 
A recent patch to reticulate introduced the R function `py_len()`, which can optionally restore the state of the Python session exception global variables.
`py_len()` is tested in reticulate.

Use `reticulate::py_len()` instead of `builtins$len()`

---

NEWS.md
src/cpp/r/include/r/session/RSession.hpp
src/cpp/r/session/REmbedded.hpp
src/cpp/r/session/REmbeddedPosix.cpp
src/cpp/r/session/RSession.cpp
src/cpp/r/session/RStdCallbacks.cpp
src/cpp/r/session/RStdCallbacks.hpp
src/cpp/session/SessionMain.cpp

Addresses #3014
Stops further execution of selected code when encountering an error. The last output in the console will be the last statement executed so that it is easier to see what occurred during execution.
Add callback for console reset to clear console input. This appears to be called when an error occurs. Any pending input can be cleared. The callback is only set when executing a code selection. It is not used when submitting the entire script for execution.
None
This only addresses Linux/MacOS. R does not have a console reset callback for Windows.
The code selection sends each line of code as a separate console input. If executing one of the lines produces an error, subsequent lines should not execute. Below, the call to `stop` should be the end when executing these lines. The …

Discard pending input on error

---

docker/jenkins/Dockerfile.debian9-x86_64

Get our tests passing on debian 9 again
The version of R installed by default doesn't have test that any more. Bump the version of R to fix.
This is to fix them
Build change only

Bump R to 3.6.3

---

src/cpp/session/include/session/SessionOptions.gen.hpp
src/cpp/session/session-options.json

As a follow-up to #10380 (addressing #3572), we updated the installation path for grep (GNU grep 3.0) to `bin/grep/3.0`. Previously lived at `bin/grep`.  Forgot to update the default value of `gnugrepPath` in the previous PR, which is necessary for Find in Files functionality in Windows

Gnugreppath windows -- fix default path

---

NEWS.md
src/cpp/session/modules/SessionFind.cpp
src/cpp/session/modules/SessionFindTests.cpp
src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java

Addresses both #9344 and #9813. 
Apparently, `grep` flavor regexes within the `boost::regex_replace` function don't process `\b` as word boundaries, even though grep on the command line, which we use to find the matches in the first place, works just fine. [This page](https://www.boost.org/doc/libs/1_76_0/libs/regex/doc/html/boost_regex/syntax/basic_syntax.html) indicates that the `egrep` flavor which supports POSIX ERE, and is equivalent to `grep -E` in the command line, resolves the original issue.
By adding support for ERE, we have now changed which characters do and do not need to be escaped. In general, only escape sequences such as `\b` need to be escaped.  Characters with special regex meaning
```
.[{}()\*+?|^$
```
will now be treated as literals if escaped with a backslash, and …

Change regex flags and add unit tests for word boundaries

---

src/cpp/r/RSexp.cpp
src/cpp/session/modules/SessionPackrat.cpp
src/cpp/session/modules/SessionPlots.cpp
src/cpp/session/modules/data/DataViewer.cpp
src/cpp/session/modules/environment/SessionEnvironment.cpp

Addresses issue: https://github.com/rstudio/rstudio/issues/10424
- SessionEnvironment calls an internal R function and so should not run off the main thread
- SessionPlots uses the graphics display object and since we are only running offline RPCs
none of those operations will affect the plots or data viewer
- SessionPackrat need the main thread
Added asserts to the listEnvironments apis
Reproduced with the existing automated tests with this custom setting to ensure all offlineable code runs in a thread other than main:
--- /etc/rstudio/rsession.conf:
session-handle-offline-timeout-ms=0
Even with session-handle-offline-timeout-ms=0, this does not reproduce every time. When I run the test_VisualMarkdownEditor tests the "recursive gc invocation" error would show up in the console in one of …

Fixed main thread issues with onDetectChanges event

---

src/cpp/session/resources/templates/cpp11.cpp

typo in template used for cpp11 code. part of #10397 that was merged into spotted-wakerobin.

typo in cpp11 template

---

src/gwt/src/org/rstudio/studio/client/panmirror/dialogs/PanmirrorEditListDialog.ui.xml
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerCommon.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/DelegatingCompletionManager.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/StanCompletionManager.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.ui.xml
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/yaml/YamlCompletionManager.java

Fix a couple issues in the way CompletionManagerBase tried to delegate to the "active" completion manager in multi-mode documents, and use those fixes to tidy up YAML completion manager behaviors.
CompletionManagerBase can now request the "active" completion manager, which is provided for documents using the DelegatingCompletionManager. When no delegate is available, default implementations are used; otherwise, the methods on the active delegate are used instead.
This approach was taken mainly to avoid the need to re-implement or re-declare methods on all completion manager subclasses.
N/A
N/A

fixups for completion manager delegation

---

src/node/desktop/src/main/utils.ts

Running Electron in dev on M1 Macs exits with an error that it cannot find the rsession executable. When building arm64, it creates the binary named `rsession` but it is renamed in the packaging step to `rsession-arm64`. In dev, it's build and run (no packaging) so the binary is not named as expected.
Check if `app.isPackaged` in addition to arm64 before using `rsession-arm64` as the executable name.
None
This should affect development flows only. When packaged, it should always be using `rsession-arm64` on M1 Macs.

Fix `yarn start` for Electron

---

src/cpp/session/modules/SessionPythonEnvironments.R

Addresses #10103.
Take the error message from conda system command and send to console via stop. They might also hit this error via the UI (via Tools > Global Options > Python > Select python interpreter), so it could be worth showing the error in the UI as well instead of just
NA
Would be best to have a way to trigger an error upon running `conda env list --json --quiet` in the shell in order to be able to properly test the error handling

Error message propagate to console when conda cannot find environments

---

src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/buildtools/BuildToolsRoxygenOptionsDialogBinderImplGenMessages_fr.properties

Fixes failure to run `make-package` because an error when building GWT.
Escape the apostrophes in the string since it's a special character.
None
The breaking commit is not in `main` so this is only to fix `spotted-wakerobin`

Fix French strings

---

src/cpp/session/modules/SessionPythonEnvironments.R

Previously only checked if status was not equal to 0, however, if the command executes successfully, it will generally not have a status attribute. Followup to #10435 to fix that.

Properly handle successful conda execution, status attr will be NULL

---

src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/LintManager.java
src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/model/LintSource.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetLintSource.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunk.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeChunks.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeLintSource.java

Before this change, only the active chunk was linted when the document was saved in visual mode. After it, diagnostics are generated for the entire doc when it's saved.
Use the `LintSource` to select this behavior; turn off save-on-lint for individual visual chunks, and turn it on for the source editor when it's active in visual mode. The mechanism for forwarding lint results from the source editor already exists and works as-is with this change.
There's also a possible race condition here wherein the user (a) makes a change, (b) saves quickly, then (c) the background linter from the change (a) overwrites the lint results generated from the save (b). To address this, forcing lint results from the outer editor into the chunks now cancels any pending lint operations for that chunk.
N/A …

Lint entire visual editor doc on save

---

package/osx/.gitignore
src/node/desktop/test/int/int-utils.ts
src/node/desktop/test/int/utility-window.test.ts

Skip the failing utility window test and allow running the integration tests in a dev environment. It requires building Electron using `package/osx/make-package --rstudio-target=Electron`. The integration tests will launch RStudio using the build output.
I've also git ignored `package/osx/scripts/node_modules` that's generated during the packaged build.
Change the launch target in the test utils. Add a skip to the utility window test.
Integration tests should run 3 tests and 1 pending (the skipped one). `yarn testint`
No changes to shipped code and the test does not yet run in builds.

Fix Electron Mac integration tests

---

src/node/desktop/package.json
src/node/desktop/test/int/startup-fail-session.test.ts
src/node/desktop/yarn.lock

Upgrades Playwright to 1.18.1
`yarn upgrade playwright@^ --latest` and selected 1.18.1, which is the latest release.
Also, I added a wait on the session failed test since it's starting up so quickly that it sees the **Initializing R** screen! 😮 The test can properly verify if the error screen does not appear since the test will reach the timeout and fail.
Running `yarn testint` passes
Affects integration tests only

Upgrade Playwright for Electron integration tests

---

package/osx/scripts/codesign-package.sh
src/node/desktop/src/core/file-path.ts
src/node/desktop/src/main/session-launcher.ts
src/node/desktop/src/main/utils.ts

Port over x64 vs. arm64 detection code; ensure RStudio can launch x64 R sessions.
Use `/usr/bin/arch`; pass `DYLD_INSERT_LIBRARIES` to force the R library to be loaded on start.
N/A
Test that you can force RStudio to use an x64 R; e.g. with
```
RSTUDIO_WHICH_R=/path/to/R /Applications/RStudio.app/Contents/MacOS/RStudio
```

handle launch of x64 R when on arm64 macOS

---

src/node/desktop/src/core/logger.ts
src/node/desktop/src/core/winston-logger.ts
src/node/desktop/src/main/application.ts
src/node/desktop/src/main/desktop-browser-window.ts
src/node/desktop/src/main/desktop-options.ts

We should generally use the logging API in Electron desktop, not `console.log()`.
Converted several; there are still some instances of `console.log()` for code that might fail before logging is initialized.
Also added a logging method override for logging errors (exceptions) at a level other than 'error'.
No new tests.
Nothing specifically to test here. Internal cleanup.

use logging instead of console.log for Electron

---

src/node/desktop/src/main/detect-r.ts

Electron desktop should find M1 R installed by homebrew on M1 Mac.
Do same thing for Electron as was done for Qt desktop (https://github.com/rstudio/rstudio/pull/9272). Namely, add `/opt/homebrew/bin/R` to the list of locations searched for an R installation on Mac.
None
Try running Electron RStudio on an M1 Mac where the only R installation is native M1 R installed via homebrew to /opt/homebrew.

find M1 R installed by homebrew on Mac

---

NEWS.md
src/cpp/r/RSexp.cpp
src/cpp/r/include/r/RSexp.hpp
src/cpp/session/modules/SessionFiles.R
src/cpp/session/modules/SessionFiles.cpp
src/cpp/session/modules/SessionPatches.R
src/cpp/session/modules/SessionRUtil.R
src/cpp/tests/testthat/test-files.R

Addresses https://github.com/rstudio/rstudio/issues/10451. Alternate to https://github.com/rstudio/rstudio/pull/10464.
Implement our own file listing routines, using Boost.Filesystem. Might be worth discussing if we like this more than https://github.com/rstudio/rstudio/pull/10464.
Extensive tests are included.
Note that these changes should only effect Windows. Test something like the following:
```
.rs.files.restoreBindings()
lhs <- list.files("~", recursive = TRUE)
rhs <- list.files("~", recursive = TRUE)
all.equal(lhs, rhs)
```

implement own list.files list.dirs methods built on Boost.Filesystem

---

src/gwt/src/org/rstudio/studio/RStudioServer.gwt.xml
src/gwt/src/org/rstudio/studio/RStudioSuperDevMode.gwt.xml

Addresses https://github.com/rstudio/rstudio-pro/issues/3248.
Ensure that the server GWT module contains a copy of the desktop sources, so they can be served in remote desktop configurations.
N/A
N/A

ensure server GWT modules can serve desktop UI

---

package/win32/clean-build.bat
package/win32/make-install-win32.bat
package/win32/make-package.bat

Small tweaks to the make-package.bat (and related) scripts for building Windows packages. A prelude to work to enable building Electron packages on Windows.
- make-package.bat now shows usage via "/?", "--help", or "-h".
- added `nogwt` option to skip rebuilding GWT (handy for testing changes to make-package)
- added `electron` option to specify RSTUDIO_TARGET=Electron (actual build NYI)
- small tweaks to the clean-build.bat script to avoid a "The system cannot find the file specified." message if run on an already clean environment, and to restore the cwd when done
None, this is purely build stuff. I did run a local `make-package clean` and confirmed it worked.
Build tooling.

make-package.bat options cleanup

---

src/cpp/r/session/REmbeddedWin32.cpp

Addresses https://github.com/rstudio/rstudio/issues/10415.
Take advantage of newly-provided `R_ResetConsole` hook on Windows.
Would be worth testing output of the form:
```
x <- 1
stop("an error occurred")
x <- 2
```
and confirm that `x <- 2` is not executed. (Only works with recent versions of R-devel, which will be released as R 4.2.0).
See above.

support R_ResetConsole on Windows (R >= 4.2.0)

---

src/cpp/session/include/session/SessionModuleContext.hpp
src/cpp/session/modules/SessionDiagnostics.R
src/cpp/session/modules/SessionDiagnostics.cpp
src/cpp/session/modules/SessionMarkers.cpp
src/gwt/src/org/rstudio/core/client/VirtualConsole.java
src/gwt/src/org/rstudio/studio/client/common/sourcemarkers/SourceMarkerItemCodec.java
src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/LintManager.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetLintSource.java

Fixes #10430 and #10062
The gutter would show duplicate issues and the duplicate would be incorrectly formatted. RMarkdown files in visual mode literally rendered the HTML in the tooltip. The issues would manifest after code diagnostics had run and the R session was restarted.
For duplicate gutter issues, this came from adding the custom source markers to the gutter. Code diagnostics already had the issues and they would be added a second time to the lint result. Adding a flag to the marker set that it is a diagnostic issue allows a check to prevent adding it to lint items returned.
For the formatting issues with tooltips, a flag was added to `VirtualConsole` to render the text as HTML. This allowed the HTML entities to show up properly in the tooltips. If the source editor was in visual …

Fix source marker formatting

---

src/cpp/core/system/PosixSystem.cpp
src/cpp/core/system/PosixSystemTests.cpp

OS companion for https://github.com/rstudio/rstudio-pro/pull/3240
The OS side of the changes for the PR above.
There were changes automated
The feature is not directly used by Workbench at this point

Verify group membership before dropping privileges

---

src/node/desktop/src/main/menu-callback.ts
src/node/desktop/test/unit/main/menu-callback.test.ts

A couple of tests to cover that `menu-callback` can set the initial command visibility and that command properties are updated.
Moved the event handling code to its own function so it can be called in the unit test. This allows proper initialization of the menu so it can be updated.
Tests that a command can be added, visibility set, and updated.
Code was refactored so nothing different in behaviour.

Unit tests for Electron recent item menus

---

src/gwt/src/org/rstudio/studio/client/workbench/MRUList.java

Fix the changes committed for #10445 that prevented the server from initializing the menus.
Only use the `DesktopMenuCallback` if there's a desktop frame.
None
Electron still updates after opening files and projects. This change addresses how updating commands needs to rebuild the Electron menus.

Fix Electron recent menu items

---

src/cpp/session/modules/clang/RCompilationDatabase.cpp

Addresses https://github.com/rstudio/rstudio/issues/10514. Regressed in https://github.com/rstudio/rstudio/pull/10343.
Fixes a regression that unfortunately snuck in when I was working on getting Windows C++ autocompletion up and running. 
N/A
N/A

fix regression in C++ autocompletion

---

Jenkinsfile
src/cpp/session/rsession.exe.manifest

Addresses https://github.com/rstudio/rstudio/issues/10507. Either a candidate for a patch release for GO, or for PT.
Unfortunately, telling RStudio to use a UTF-8 code page doesn't work as expected with older versions of R, which only support non-UTF-8 code pages. We need to revert that change, and reconsider enabling it for a future release.
N/A
N/A

revert use of UTF-8 code page on Windows

---

CMakeCompiler.txt
src/cpp/CMakeLists.txt
src/cpp/core/include/core/system/LibraryLoader.hpp
src/cpp/r/session/REmbeddedWin32.cpp

R Core is currently exploring an alternate mechanism for introducing the R_ResetConsole hook on Windows; in particular, a change that would be binary-compatible with previous releases of R.
This PR supports the use of the `ptr_R_ResetConsole` hook when available on Windows.
It also bundles some changes to speed up incremental compilation of RStudio in development builds on Windows. In particular, linking to crashpad required compile time code generation, which precludes the use of incremental linking.
Because we can't rely on this hook being available with older versions of R, we instead dynamically load and set the symbol when initializing R.
N/A
N/A

alternate mechanism for R_ResetConsole on Windows

---

src/node/desktop/.eslintrc.js
src/node/desktop/src/main/menu-callback.ts
src/node/desktop/test/unit/main/menu-callback.test.ts

Addresses #9948 
Change the eslint config to address the errors about prettier at the top of every file.
This uses similar logic to how Electron handles menu separators. The difference is that Electron only removes separators if they are at the beginning/end or the previous item is also a separator. Our menus have many hidden items so check doesn't work for us. Even not adding the hidden items still means the separators have to be marked as hidden.
I've added in a check to not add hidden items to menus. The caveat is shortcuts won't work for that command. Although, I don't see that as an issue since the item is likely hidden for a reason. The second part of the fix is using the same logic as Electron to filter out unnecessary separators.
This also runs on MacOS but has no difference since …

Fix duplicate menu separators

---

src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.ui.xml
src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialogBinderImplGenMessages_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialogBinderImplGenMessages_fr.properties

Addresses #10469. Tweaked from "Common R source files" to "Common source files", replaced Rmd with Markdown (includes *.md, *.rmd, *.qmd), added yml/yaml and js as possible source files as well.

Add Qmd to list of Common R source files

---

Jenkinsfile.macos.electron

Added tests as a form of marking builds as UNSTABLE if they do fail
Added it as a step on the tests block for Jenkins
None
None
Addresses #10182

Added Tests on Electron Jenkins

---

src/cpp/session/include/session/SessionModuleContext.hpp

Addresses #10062 
Custom source markers wouldn't show in the editor's gutter.
The `isDiagnostics` flag wasn't initialized for `SourceMarkerSet` so some instances worked but others did not. Setting an initial value fixed the issue. I've also set an initial value for `isCustom` in `SourceMarker` where I had added a flag to distinguish customer source markers so that on the GWT side it can choose the correct way to render the content.
None
I was only able to reproduce using a packaged build and with x86 R.
* Clear any custom source marker sets
* Use RS API to add source markers
* Go to one of the files and allow the linter to run

Fix missing custom markers in gutter

---

src/cpp/session/modules/SessionTutorial.cpp
src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.css
src/gwt/src/org/rstudio/studio/client/workbench/views/tutorial/TutorialPane.java

adresses #10552
When an older shiny is available, the tutorial pane shows: 
The when clicked: 

Tutorials pane wants shiny >= 1.6.0

---

src/node/desktop/package.json
src/node/desktop/src/core/winston-logger.ts
src/node/desktop/yarn.lock

Addresses #10478 
Rotates logs daily and sets the log name to `rdesktop.2022-02-10.log`.
The `winston-daily-rotate-file` package has some quirks to it. It only seems to write the log files with the date in the name. So there's no option to have `rdesktop.log` unless we use the symlink option. But that didn't work on Windows and MacOS/Linux can't create the symlink if `rdesktop.log` already exists. I didn't see an option to auto-rotate with incremental filenames either.
Setting a file size limit also didn't play well with the filename. It would rotate but didn't replace the date pattern with the actual date.
So I've settled on these options for consistency across the platforms. No symlinks because it only works on MacOS/Linux with no existing logs. No max file size because there's a bug in …

Add log rotation for Electron

---

src/cpp/session/modules/SessionFind.cpp

Adresses #10529
Add `--exclude-dir=cloud.noindex` to the grep command. 
This is a bit brute force, but we don't think we would ever want to search in this directory. 

exclude directory `cloud.noindex` from search

---

src/cpp/session/resources/dependencies/r-packages.json

Addresses https://github.com/rstudio/rstudio/issues/10549. Also catches a case where the package name for theme conversion was misspelled.
Bring back package entries from https://github.com/rstudio/rstudio/commit/9e1d4997464716d2330a6b5aa25e0849fba0afa2 that were deleted.
N/A
N/A

add in missing tutorial dependencies

---

src/cpp/session/modules/SessionRUtil.R
src/cpp/session/modules/SessionRUtil.cpp

Adds a small helper so one can call `.rs.suspendSession()` from RStudio to suspend a session -- mainly useful internally when testing suspend + resume.

add session suspend helper (for debugging)

---

src/cpp/session/modules/SessionDataImportV2.R

Adresses #10543 
Replaces `read_table2()` with `read_table()` as `readr::read_table2()` is deprecated. 

use read_table() instead of read_table2()

---

src/cpp/session/modules/SessionFiles.cpp
src/cpp/tests/testthat/test-files.R

Addresses https://github.com/rstudio/rstudio/issues/10573.
Ensure that we don't mutate separators within the user-provided path prefix, and ensure we use forward-slashes for any path components constructed following the path prefix.
Automated tests updated.
Test via notes in:
https://github.com/rstudio/rstudio/issues/10573
https://github.com/rstudio/rstudio/issues/10591

ensure backslashes in prefix are preserved in list.files hook

---

src/gwt/src/org/rstudio/core/client/BrowseCap.java
src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.java

Addresses https://github.com/rstudio/rstudio/issues/10598.
Restore the `rstudio-themes-flat` class to the `<body>` tag. We can feel confident that this is safe since we removed all our own style rules and selectors that used this string. 
N/A, visual change that only affects 3rd party themes.
Test via notes in https://github.com/rstudio/rstudio/issues/10598.

Restore rstudio-themes-flat for 3rd party themes

---

src/cpp/session/include/session/prefs/UserPrefValues.hpp
src/cpp/session/modules/SessionDataViewer.R
src/cpp/session/prefs/UserPrefValues.cpp
src/cpp/session/resources/grid/dtstyles.css
src/cpp/session/resources/grid/dtviewer.js
src/cpp/session/resources/schema/user-prefs-schema.json
src/cpp/tests/testthat/test-dataviewer.R
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_fr.properties

addresses #5100, the example gives: 
Calling `as.character()` on a list column can quickly make big character vectors that make the ui struggle. This truncates them, adding `(...)` at the end. The data viewer ui picks up the suffix and displays it discretely. 
cc @jgutman as this is related to other data viewer work. 

Data viewer: truncate large list cells

---

src/cpp/tests/cpp/tests/vendor/catch.hpp

This fixes an issues with newer GCC versions, specifically https://github.com/catchorg/Catch2/issues/2178
The source was copied directly from https://github.com/catchorg/Catch2/blob/v2.13.8/single_include/catch2/catch.hpp
The change is covered by tests in catch/Catch2
Ensure that all current test cases pass

Update Catch2 to v2.13.8

---

src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.java

addresses #10191
`autoSizeCallFramePanel()` gets called on all `onResize()` but most of the time it exits early and does nothing. 

update the logic for resize call frame panel

---

src/cpp/session/resources/templates/shiny.qmd
src/cpp/session/resources/templates/shiny/app.R
src/cpp/session/resources/templates/shiny/server.R

Previously the Shiny template file included x-axis label and a title. That isn't included in the current version, and it makes the template example harder to work with, because 1) it's difficult to understand what the plot is about, because what the labels should be isn't immediately obvious and 2) it's a standard thing that people want to do, so it's nice to have an example of how it's done in the code. 
For the shiny/app.R, shiny/server.R and shiny.qmd files, I added in the code to add the x-axis label and title. 
I'm not sure how this works with automated tests. I did run locally and it worked fine. 
Those labels may have been removed for reasons I'm not aware of, including accessibility standards. If this is the case, that rationale likely supersedes template legibility. 
For purposes …

adding axis label and title to Shiny template files

---

src/cpp/session/modules/SessionFiles.cpp
src/cpp/tests/testthat/test-files.R

Fixes another issue regarding how trailing separators are handled by R with `list.files()` and `list.dirs()`.
Note: not crucial for the PT release; we could consider as part of the next patch release if we don't want to hold things up.
R is inconsistent in how trailing separators in the `path` argument are handled; this PR tweaks how we handle these to conform with R's implementation.
N/A

improve handling of trailing separator in prefix

---

CONTRIBUTING.md

Update links to contributor agreements to point to rstudio.com instead of wordpress site.
Change email address to be contribute@rstudio.com (the change is also made inside the PDFs, which are in the process of being updated on rstudio.com).
Addresses #10609

update links to contributor pdfs and email to use

---

src/node/desktop/.eslintrc.js
src/node/desktop/src/main/menu-callback.ts
src/node/desktop/test/unit/main/menu-callback.test.ts

Undo the damage from fixing the menu separators. This is a refactor of how the menus are constructed and the menu model. I took a quick peek at the menus and everything looked the same (as far as I can tell from my limited use of the IDE). Added a few unit tests to cover the scenarios where the menus are updated in different ways: changing a menu item label/visibility, full menu rebuild due to reloading the UI, and updating shortcuts.
I've also updated the lint warnings about unused variables. There's an ignore added so that variables prefixed with `_` are ignored for this rule.
Change the menu model as `MenuItemConstructorOptions`. This makes it easy to pass a template to `Menu.buildFromTemplate()` to create the application menu. The menu model is copied into a new template with …

Fix recent items breaking due to menu separators fix

---

dependencies/common/install-node
dependencies/common/install-npm-dependencies
dependencies/common/install-yarn
dependencies/osx/install-dependencies-osx-arch
dependencies/tools/rstudio-tools.sh
package/osx/cmake/merge-electron.cmake
package/osx/make-package
src/node/CMakeNodeTools.txt

We're building Mac (Electron) using multiple versions of node; in some places we use node 16.14 as installed by the dependency scripts, in other places we're using a newer node (17+) installed by "brew install node".
We should build everything with the same version.
- Stop installing node via homebrew.
- Install both x64 and M1 node (on an M1 Mac) via the dependency scripts, and update references to make sure the correct one is referenced either directly or is on the path when `yarn` is invoked.
- x64 node goes to the same place as before (`dependencies/common/node/16.14.0`) so GWT build.xml can find it, and M1 node goes into `dependencies/common/node/16.14.0-arm64`)
- Don't fallback to finding node on the path, only use the version we installed
- I tested by making sure I didn't have …

install x64 and M1 node via dependency scripts on MacOS

---

src/cpp/session/modules/SessionHelp.cpp
src/gwt/src/org/rstudio/core/client/BrowseCap.java
src/gwt/src/org/rstudio/core/client/Debug.java
src/gwt/src/org/rstudio/core/client/dom/EventProperty.java
src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java

Addresses https://github.com/rstudio/rstudio/issues/10501.
Straight-forward implementation of mouse handlers on the GWT side. Previously, these were implemented on the desktop side in https://github.com/rstudio/rstudio/blob/10d7d434c336c60c48c280f2dae9e94435f35cf6/src/cpp/desktop/DesktopWebView.cpp#L74-L105 to work around a Qt issue; now that this is no longer an issue, we can just implement it on the front-end ourselves.
Not included.
Test that back / forward mouse buttons navigate through the source history, rather than causing RStudio to "exit" (especially on back).

implement back / forward mouse handlers

---

NEWS.md
src/cpp/session/SessionClientInit.cpp
src/cpp/session/SessionConsoleProcess.cpp
src/cpp/session/modules/SessionPythonEnvironments.R
src/cpp/session/modules/SessionRSConnect.cpp
src/cpp/session/modules/SessionReticulate.R
src/cpp/session/modules/SessionReticulate.cpp
src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
src/cpp/session/resources/terminal/hooks

Addresses #9990, and reverts the hotfix implemented in #10000 as a temporary stopgap.
Rather than checking only for RETICULATE_PYTHON, and forcibly setting that variable if unset and we have inferred a version of Python, inferred Python paths should be forwarded to RETICULATE_PYTHON_FALLBACK, and we should check both variables for being set when we are looking for a version of Python.
Allow Python interpreters set via already-loaded reticulate or via the RStudio UI Options pane to take precedence over inferred Pythons in RETICULATE_PYTHON_FALLBACK
QA Notes:
1. Open a new RStudio session, with no active project.
2. In the Options pane, check the box for "Automatically activate project-local Python environments". Leave Python interpreter unset.
3. Make sure that RETICULATE_PYTHON is not set …

Use and access RETICULATE_PYTHON_FALLBACK

---

src/node/desktop/package-lock.json
src/node/desktop/package.json

Fix an issue that started to happen after the new updates for Electron: Node v14 to v16 and to use `npm` instead of `yarn`.
When removing the `package-lock.json`, an error was presented when installing `eslint` due to an incompatibility with `eslint-config-standard@16.0.3`.
Downgraded the `eslint` package and regenerated the `package-lock.json` file. As ESLint was worked with no issues on v8 with `yarn`, I decided to keep the notation to use the latest v7 for `eslint` (^7.12.1 notation).
None
None

Electron Packages Update

---

src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/menu-callback.ts

The undo/redo menu actions were being handled by Electron. Electron can perform these actions for input elements but not on the ACE editor. This allows editor actions to be undone/redone using the menu.
The menu actions are implemented without the `undo` and `redo` roles. Instead, they emit the event for GWT to handle. If GWT detects Electron then it handles the action differently. For focus on an ACE editor, it will invoke the ACE undo/redo. For everything else, it calls back to Electron where it will use `webContents.undo()`.
None
Technically, the menu and keyboard shortcut should be the same now that the shortcut is tied directly to the menu item.
The actions are the same in the editor and the console as both use ACE. Everywhere else should be handled by Electron calling …

Implement undo/redo menu actions in Electron

---

package/linux/make-package
package/osx/make-package
src/node/desktop/CMakeLists.txt
src/node/desktop/envvars.sh

`node-gyp` barfs if you try to build its targets in parallel.

unset MAKEFLAGS when running npm install

---

dependencies/windows/install-dependencies.cmd
docker/jenkins/Dockerfile.windows

Fixes build errors on Windows.
Re: https://build.rstudioservices.com/blue/organizations/jenkins/IDE%2Fopen-source-pipeline/detail/main/922/pipeline/1003
```
[](https://build.rstudioservices.com/blue/organizations/jenkins/IDE%2Fopen-source-pipeline/detail/main/922/pipeline/1003#step-1004-log-20)[](https://build.rstudioservices.com/blue/organizations/jenkins/IDE%2Fopen-source-pipeline/detail/main/922/pipeline/1003#step-1004-log-21)[](https://build.rstudioservices.com/blue/organizations/jenkins/IDE%2Fopen-source-pipeline/detail/main/922/pipeline/1003#step-1004-log-22)[](https://build.rstudioservices.com/blue/organizations/jenkins/IDE%2Fopen-source-pipeline/detail/main/922/pipeline/1003#step-1004-log-23)[](https://build.rstudioservices.com/blue/organizations/jenkins/IDE%2Fopen-source-pipeline/ …
```

install python for Windows Docker builds

---

src/node/desktop/src/main/desktop-browser-window.ts
src/node/desktop/src/main/gwt-window.ts
src/node/desktop/src/main/main-window.ts
src/node/desktop/src/main/minimal-window.ts
src/node/desktop/src/main/satellite-window.ts
src/node/desktop/src/main/secondary-window.ts
src/node/desktop/test/unit/main/desktop-browser-window.test.ts
src/node/desktop/test/unit/main/gwt-window.test.ts
src/node/desktop/test/unit/main/minimal-window.test.ts
src/node/desktop/test/unit/main/window-tracker.test.ts

Addresses #10610
Secondary windows such as popped-out-editors or the git window were showing the menubar on Windows and Linux, which they didn't do on the Qt desktop.
We load secondary windows in the same renderer process as the main window. This is for efficiency and also because we rely on the pattern `window.opener.doSomething()` and that can't work if each window is in its own renderer process.
As a result each window shares the same application menu. Using the autohide feature to hide the menu by default on secondary windows. It can still be displayed by tapping the Alt key.
This problem of having the menu on secondary windows is also true on Mac QtWebEngine desktop, so this actually isn't new. Just more noticable, perhaps, on Windows/Linux where menus are attached directly to the …

Hide menubar on secondary windows

---

src/node/desktop/src/main/desktop-browser-window.ts
src/node/desktop/src/main/gwt-window.ts
src/node/desktop/src/main/main-window.ts
src/node/desktop/src/main/minimal-window.ts
src/node/desktop/src/main/satellite-window.ts
src/node/desktop/src/main/secondary-window.ts
src/node/desktop/test/unit/main/desktop-browser-window.test.ts
src/node/desktop/test/unit/main/gwt-window.test.ts
src/node/desktop/test/unit/main/minimal-window.test.ts
src/node/desktop/test/unit/main/window-tracker.test.ts

The window classes ported straight from C++ include long list of constructor arguments, leading to things like:
```
const win = new DesktopBrowserWindow(false, false, false, 'some name');
```
Use a more TypeScripty object approach so arguments at call sites are more self-documenting, i.e.:
```
const win = new DesktopBrowserWindow({
showToolbar: false,
adjustTitle: false,
autohideMenu: false,
name: 'some name',
});
```
Still kinda ugly and could use more tidying / consolidation / defaults, but I think this is somewhat better.
Updated existing tests, no new tests.
Internal code cleanup, nothing specifically to test.

use objects as constructor args (electron)

---

src/node/desktop/.prettierrc
src/node/desktop/src/main/detect-r.ts

Part of https://github.com/rstudio/rstudio/issues/8815.
Also includes changes to prettierrc; the main change being `"endOfLine": "auto"` to avoid EOL warnings on Windows.
Include `C:\R`, `C:\Program Files\R`, and `C:\Program Files (x86)\R` in the set of candidate locations where we look for R installations.
N/A
Check that R installations in the aforementioned locations are visible; e.g.

detect R in common locations

---

Jenkinsfile
docker/jenkins/Dockerfile.centos7-x86_64
docker/jenkins/Dockerfile.opensuse15-x86_64

Build Electron desktop for Centos7 and OpenSuse15.
Addresses #10378
Add to Jenkinsfile, add python3 dependencies needed for building native node modules.
The builds are the test.
None

enable Electron builds for opensuse15 and centos7

---

src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants_fr.properties
src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
version/news/NEWS-2022.02.1-prairie-trillium.md

Addresses #10688 for Prairie-Trillium. The fix for `main` was in https://github.com/rstudio/rstudio/pull/10690.
Backported code plus created .1 news file.
None; purely a UI label.
Verify that the correct label is now being shown per the issue.

fix for preferences label

---

src/node/desktop/envvars.sh
src/node/desktop/src/main/gwt-callback.ts

Addresses https://github.com/rstudio/rstudio/issues/10684.
Make use of `resolveAliasedPath()` in more places where it's required.
Not included, but theoretically could.
Test that, when opening file dialogs on desktop which default to a path in the home directory, that the directory is actually used as the default path when the dialog is opened.

resolve aliased paths in file dialog APIs

---

NEWS.md
src/cpp/session/include/session/prefs/UserPrefValues.hpp
src/cpp/session/prefs/UserPrefValues.cpp
src/cpp/session/resources/schema/user-prefs-schema.json
src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/prefs/PrefsConstants_fr.properties
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetPrefsHelper.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java

Adds a new preference that causes the editor to show line numbers in the gutter relative to the cursor position, instead of relative to the top of the document. This is a model preferred by many people who use Vim mode since it makes it easier to specify jump targets and ranges. 
When the preference is enabled, the absolute line number is shown at the cursor, but all other line numbers are shown as an offset from the current line. 
Addresses https://github.com/rstudio/rstudio/issues/1774. 
This feature is already implemented in Ace; we're just exposing it. See https://github.com/ajaxorg/ace/issues/3461. 
The new preference can be set via the Command Palette and also gets a new entry next to "line numbers" in the preference UI. 
N/A, this change affects gutter rendering only.
Note that …

Add support for relative line numbers in the editor.

---

src/node/desktop/src/core/r-user-data.ts
src/node/desktop/src/main/application-launch.ts
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/main-window.ts

Addresses https://github.com/rstudio/rstudio/issues/10687.
Wire up existing skeleton for `launchRStudio`, making use of existing session facilities for selecting a project file / working directory on launch.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/10687.

wire up launching of separate RStudio instances

---

src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java

Addresses #10626.
When the previewReplace event fires (only when isRegex is True), the searchLabel is cleared (with stopAndClear) but not repopulated, as is done when the completeReplace event fires. Adding that bit when the RPC response is received appears to fix the clearing out of the search label in regex preview results
NA, just ran RStudio Desktop locally.
See example in the #10626. Run Find in Files, with "Regular expression" checked, and in the preview results, enter a replacement. The search label at the top of the Find in Files pane should update from `Replace results for /hello/` to `Replace results for /hello/ with /bye/` rather than clearing out.

update Search label on preview replace event

---

src/cpp/core/include/core/r_util/RTokenizer.hpp
src/cpp/core/r_util/RTokenizer.cpp
src/cpp/session/SessionOptions.cpp
src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp

Addresses https://github.com/rstudio/rstudio/issues/10674.
Tweaks to ensure pandoc and friends are solved to the right locations on Electron.
Not included; other unit tests would already cover this.
Test via notes in https://github.com/rstudio/rstudio/issues/10674.

fix path lookup for pandoc etc. in electron builds

---

src/cpp/session/modules/SessionCodeTools.R
src/cpp/session/modules/SessionRMarkdown.R

Addresses #7545 
Add the `eval.expr = TRUE`, especially in parsing the yaml front-matter
See #7545 reprex

Use eval.expr explicitly for YAML to prevent warnings and future deprecation

---

src/cpp/session/modules/clang/RCompilationDatabase.cpp

Was getting these errors when opening e.g. `cpp11` because it has no `src/`: 
````
2022-03-02T14:02:40.158499Z [rsession-romainfrancois] ERROR system error 2 (No such file or directory) [path: /Users/romainfrancois/git/cpp11/src]; OCCURRED AT rstudio::core::Error rstudio::core::FilePath::getChildren(std::vector<FilePath> &) const src/cpp/shared_core/FilePath.cpp:927; LOGGED FROM: bool rstudio::session::modules::clang::(anonymous namespace)::packageIsCpp(const std::string &, const rstudio::core::FilePath &) src/cpp/session/modules/clang/RCompilationDatabase.cpp:356
````

check that a potential cpp related project has a `src/` before scanning it

---

src/cpp/session/modules/SessionFiles.cpp
src/cpp/session/modules/SessionPatches.R
src/cpp/tests/testthat/test-files.R
version/news/NEWS-2022.02.1-prairie-trillium.md

Addresses https://github.com/rstudio/rstudio/issues/10679.
Addresses https://github.com/rstudio/rstudio/issues/10672.
Use R's own `grepl()` rather than `boost::regex`, to avoid incompatibilities between the two regular expression engines.
Also make sure we expand tilde-prefixed paths before attempting to list files. 😭 
Tests included and updated.
Test via notes in https://github.com/rstudio/rstudio/issues/10679.

fixups for list.files on Windows

---

src/gwt/src/org/rstudio/core/client/theme/ThemeFonts.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AceEditorPreview.java
src/node/desktop/src/main/gwt-callback.ts

Address #10463 
The editor preview wouldn't use the selected font when the appearance pane is first viewed. Switching to another font and back would show the correct font. I'm not sure when this broke but it's also an issue in Prairie Trillium.
Also, sets the MacOS default font to Menlo then Monaco if unavailable.
When retrieving the selected font, it comes back in quotes. This has `!important` and `monospace` appended before setting the style element. The problem was adding another set of quotes (`""Menlo", monospace" !important`) that resulted in an invalid font name. This will properly set the font attribute to `"Menlo", monospace !important`.
None
This fixes RStudio web, Qt, and Electron. Although, this was probably unnoticed since the invalid attribute meant falling back to Ace's …

Update initial editor preview with selected font

---

src/node/desktop/src/main/gwt-callback.ts

Resolve the monospace font loading issue on Windows
I didn't notice the `getAvailableFontsSync()` that doesn't require options. I guess a blank options object doesn't work well. It was only retrieving proportional fonts so the monospace list was blank.
None
Windows should load Lucida Console by default

Fix monospace font list on Electron Windows

---

src/cpp/core/system/PosixSystemTests.cpp
src/cpp/rstudio-tests.in

Addresses #10683
Unit tests assumed that the `nobody` user was in the `nogroup` group, but this isn't true on non-Debian platforms and the tests always failed. Also the tests weren't reporting errors correctly making it very difficult to figure out why it was failling.
Determine if we're on a `nogroup` platform, or a `nobody` platform. Also report failures.
Reenable the tests.
Yes. Yes they are.
Unit tests only.

Unit test fixes, accomodate nogroup vs nobody

---

src/node/desktop/package.json
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/gwt-window.ts
src/node/desktop/src/main/main-window.ts
src/node/desktop/src/main/preferences/desktop-options.ts
src/node/desktop/src/main/preferences/electron-desktop-options.ts
src/node/desktop/src/main/preferences/file-preferences.ts
src/node/desktop/src/main/preferences/preferences.ts
src/node/desktop/src/main/session-launcher.ts
src/node/desktop/test/unit/main/desktop-options.test.ts

Address saving font selection #10438
Saves the editor font selection to the electron-store. Reading will check electron-store first and fallback to the legacy option store. Cleaned up the way GWT gets the fixed font. It falls back to the default font list if both option stores return nothing.
Refactored the `preferenceManager` to be an interface. Rename the preference manager to `legacyPreferenceManager` since that should only be used for reading and handles platform specific storage. `DesktopOptions` has been renamed to `ElectronDesktopOptions` as it is specific to how Electron will be handling preferences (falling back to legacy options). `PlatformPreferences` is now the interface `DesktopOptions` so that it defines the options available. For now, it's just `fixedWidthFont` but others …

Electron preferences part 2: Writing to electron-store, reading from electron-store

---

src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
src/node/desktop/src/main/desktop-options.ts
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/main.ts
src/node/desktop/src/main/utils.ts

Part of https://github.com/rstudio/rstudio/issues/10695. This portion implements the desktop callbacks for saving / storing these as part of our desktop options.
Mostly straightforward porting of Qt goo to Electron goo.
Not included.
For testing:
- In Tools -> Global Options... -> Advanced, try changing the rendering engine.
- After applying the changes, close and restart RStudio.
- Return to Tools -> Global Options... -> Advanced, and confirm that the settings you applied from the first step are presented here.
- In Help -> Diagnostics -> Show GPU Diagnostics, confirm that most of the "Graphics Feature Status" are enabled when using auto / desktop, and are disabled (or have something like "Software only, hardware acceleration unavailable") when using software rendering.

implement handling for rendering engine prefs

---

docker/jenkins/Dockerfile.opensuse15-x86_64

Addresses: #10683 (take three)
The OpenSUSE15 build container doesn't have a nobody user or group, breaking some unit tests.
Create the nobody user and group via the Dockerfile. I tried this locally via Docker and was able to run the previously failing unit tests.
This is for the automated tests.
Build/unit test stuff.

create nobody user and group for unit tests

---

src/node/desktop/src/main/utils.ts

Addresses https://github.com/rstudio/rstudio/issues/10450.
Use the `defaults` command line utility to read (and respect) the various options as handled in Qt desktop.
Not included.
Run the following in the terminal:
```
defaults write org.R-project.R force.LANG C
```
Then, try starting RStudio. You should see a warning, e.g.
```
Warning: Character set is not UTF-8; please change your locale
```
and executing `Sys.getlocale()` should report a C locale:
```
> Sys.getlocale()
[1] "C"
```
Then, revert your options by running in the terminal:
```
defaults delete org.R-project.R force.LANG
```
and restart RStudio, and confirm the warning is gone.

initialize lang on macOS

---

src/cpp/core/system/PosixSystem.cpp
src/cpp/core/system/PosixSystemTests.cpp
src/cpp/server_core/include/server_core/ServerKeyObfuscation.hpp
src/cpp/session/modules/SessionFiles.cpp

Small changes to suppress some compiler warnings on macOS, e.g.
```
[125/535] Building CXX object core/CMakeFiles/rstudio-core.dir/system/PosixSystem.cpp.o
/Users/kevin/rstudio/src/cpp/core/system/PosixSystem.cpp:2576:10: warning: unused variable 's_privUid' [-Wunused-variable]
uid_t s_privUid;
^
1 warning generated.
[144/535] Building CXX object core/CMakeFiles/rstudio-core-tests.dir/system/PosixSystemTests.cpp.o
/Users/kevin/rstudio/src/cpp/core/system/PosixSystemTests.cpp:31:20: warning: unused function 'getNoGroupName' [-Wunused-function]
static std::string getNoGroupName()
^
1 warning generated.
[171/535] Building CXX object server_core/CMakeFiles/rstudio-server-core.dir/ServerDatabase.cpp.o
/Users/kevin/rstudio/src/cpp/server_core/ServerDatabase.cpp:190:21: warning: expression …
```

suppress a number of compiler warnings

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java

Addresses https://github.com/rstudio/rstudio/issues/10763.
Now that we have access to `window.print()`, we can re-use existing server implementation for Electron.
N/A
Try to print some source documents from the IDE; confirm that you get a printout of the code (e.g. as a PDF)

use server print impl when printing code

---

CMakeGlobals.txt
NEWS.md
dependencies/linux/README
docker/jenkins/Dockerfile.windows
src/cpp/CMakeLists.txt
src/cpp/session/modules/SessionThemes.R
vagrant/provision-multi-r.sh

Addresses [rstudio-pro#2887](https://github.com/rstudio/rstudio-pro/issues/2887).
Update minimum supported R version to 3.3.0 in all documentation. Fatal error if using < 3.3.0
Accompanying PRs in [rstudio-pro##3322](https://github.com/rstudio/rstudio-pro/pull/3322), [docs.rstudio.com#820](https://github.com/rstudio/docs.rstudio.com/pull/820), and [rstudio.com#504](https://github.com/rstudio/rstudio.com/pull/504)

Update minimum supported R version to 3.3.0

---

src/cpp/core/LogOptions.cpp
src/cpp/core/config.h.in
version/news/NEWS-2022.02.1-prairie-trillium.md

A change to support logging when RStudio Server open source is run as non-root caused logging to fail for some RSW binaries due to permission issues. That change was made here: https://github.com/rstudio/rstudio/pull/10126
Addresses https://github.com/rstudio/rstudio-pro/issues/3307
Addresses https://github.com/rstudio/rstudio-pro/issues/3318
When compiling for Pro (RSW), behave the way it was before the regression, but leave the new behaviour for open-source.
Note that binaries such as rsession and rworkspace, which run as non-root, do not rely on the default set in this code; they set their logging locations explicitely when initializing the logging subsystem.
Also, `RSTUDIO_PRO_BUILD` was already defined for pro-builds, just needed to configure that cmake variable into a header file. …

Fix logging regression for certain RSW binaries

---

Jenkinsfile

We don't currently upload debug symbols for Electron Windows build. This was showing as an empty stage in the pipeline display:
Put the stage inside the conditional so we don't get this.

avoid empty stage on windows electron build

---

src/cpp/session/modules/SessionThemes.R
src/cpp/tests/testthat/test-themes.R

Addresses #10744 . All unit tests in test-themes.R now passing, and fixed all warnings too.
Fixed warnings for elements with more than one style element by wrapping in `any`
Fixed failure to return full absolute path by using normalizePath to set Theme Locations
Fixed typo calling test with incorrect arguments
Fixed! 
NA

Fix failing unit tests and remove all warnings in test-themes

---

src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/export/DesktopExport.java
src/node/desktop/src/main/desktop-browser-window.ts
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/menu-callback.ts
src/node/desktop/src/main/preferences/desktop-options.ts
src/node/desktop/src/main/preferences/electron-desktop-options.ts
src/node/desktop/src/main/preferences/file-preferences.ts
src/node/desktop/src/main/preferences/mac-preferences.ts
src/node/desktop/src/main/preferences/preferences.ts
src/node/desktop/src/renderer/desktop-bridge.ts
src/node/desktop/src/renderer/desktop-info-bridge.ts
src/node/desktop/test/unit/main/desktop-options.test.ts

Address #10484
This switches from using Electron's zoom levels to our own zoom levels. The option is saved to `electron-store`. If there is no current value from the `electron-store` then it checks the `desktop.ini`. The legacy option is written to the `electron-store` so subsequent checks will read from there.
GWT has to handle Electron specifically and will call the desktop bridge instead of the desktop info bridge. The desktop info bridge is immutable and isn't set up for easily adding a callback. Eventually, I think most of desktop info bridge can be moved out of the preload since the immutability of it doesn't allow returning the current value. It's probably better changing desktop info bridge to be async calls since they'll likely read from disk to get these values.
Some work …

Electron zooming

---

docker/jenkins/Dockerfile.windows

The Windows dockerfile was trying to download `https://cran.rstudio.com/bin/windows/base/old/3.3.0/R-3.3.0-win.exe`. It does not exist. Change was made here: https://github.com/rstudio/rstudio/pull/10769
Use `https://cran-archive.r-project.org/bin/windows/base/old/3.3.0/R-3.3.0-win.exe` instead.
Build-stuff
Build-stuff

fix path to Windows install

---

src/cpp/r/RErrorCategory.cpp

Addresses #10443. Follow up from #10435, but allows any R code execution error messages to be accessible in the frontend.
Instead of using the 2-argument Error constructor `Error::Error(const boost::system::error_code& in_ec, const ErrorLocation& in_location)`, we should use the 3-argument Error constructor `Error::Error(const boost::system::error_code& in_ec, std::string in_message, const ErrorLocation& in_location)`, which already exists, when calling the `rCodeExecutionError` function. This means that instead of using `"R code execution error"` as the error message for all R code execution errors, and not passing any further detailed error messages to the frontend, the frontend will now have access to the actual content of the R error message, and developers can choose to display that …

Propagate R execution error messages in full

---

docker/jenkins/Dockerfile.windows

The location used by Dockerfile.windows to download R stopped working, so update to a working location. Same change was already made in `main` and worked.
Have to be careful merging PT into main, though, as the version installed in main is newer than PT.

Fix location for downloading R in Windows dockerfile (Prairie Trillium)

---

src/cpp/r/session/RSessionState.cpp
version/news/NEWS-2022.02.1-prairie-trillium.md

Handle PT resuming a session created with GO. Since Pandoc moved locations, the restored `RSTUDIO_PANDOC` location does not exist.
When restoring the `RSTUDIO_PANDOC` env var, use the value if the directory exists. Otherwise, use the system set location.
None
I have not been able to reproduce this in a dev environment so I cannot test if this actually works. I'm still working on reproducing so I can test this.

PT: Fix session restore when pandoc location does not exist

---

NEWS.md
dependencies/common/install-soci
dependencies/windows/.gitignore
dependencies/windows/install-soci/install-soci.R
src/cpp/CMakeLists.txt

Addresses #10792
Prompted by a newer macOS toolchain causing our older SOCI to stop building.
Update to latest 4.x SOCI, and make the installation versioned.
None specifically, this impacts the internal database.
I did apply and build Workbench with these changes and was able to use it with Postgres as the database as usual. Also did local test builds of desktop on Mac and Windows.
Nothing to specifically test, just general usage especially of features that leverage the internal database.

update to soci 4.0.3

---

Jenkinsfile
docker/jenkins/Dockerfile.centos7-x86_64
docker/jenkins/Dockerfile.rhel8-x86_64

Part of #10732
Install xvfb and enable Electron unit tests on rhel8 and centos7. Only opensuse15 remaining to enable.
Yes
Self-testing

enable electron unit tests on rhel8 and centos7

---

dependencies/windows/Install-RStudio-Prereqs.ps1
docker/jenkins/Dockerfile.windows

The choco package manager used to create an alias named "cpack" which clashes with cmake's cpack, so we would delete the alias when setting up the machine.
Windows docker image creation failing because recent version of choco no longer create that alias.
Fix by appending `-ea ig` (shorthand for `-ErrorAction Ignore`) to the command. We could eventually remove this command altogether but let's leave in for the moment in case some machines still pull an older choco.

build fix, accomodate choco's removal of cpack alias

---

src/cpp/session/modules/build/SessionBuild.cpp
src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
src/cpp/session/modules/rmarkdown/SessionRMarkdown.hpp

Addresses #9903, followup to PR #9796
PR 9796 fixed the values of environment variables RSTUDIO_VERSION and RSTUDIO_LONG_VERSION so they would be sent correctly to Rmarkdown when knitting. However, the same fix needed to also be applied when building an RMarkdown website using the Build pane. This applies the same approach and function used in the previous PR to get called with the build pane
None
See reprex in issue #9903

Extend fix from #9796 to also include building site, not only knitting

---

src/cpp/session/modules/SessionCodeTools.R
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetPackageDependencyHelper.java

Addresses #10767
Adds package install prompt for documents of type qmd -- previously checked only .R, .Rmd, and .Rnw filetypes
NA
Create new quarto document, add `library(pkg)` for some not currently installed package. Save file. Info bar should show up prompting for installation of missing package, same as it does for .R and .Rmd files

Add package install prompt for Quarto markdown filetype

---

NEWS.md
src/cpp/core/system/Win32System.cpp
src/cpp/core/system/Xdg.cpp
src/cpp/shared_core/include/shared_core/SafeConvert.hpp
src/cpp/shared_core/system/Win32User.cpp

> Fixed #10310. HRESULT error values are now logged in hexadecimal representation as specified by [this Microsoft reference](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/705fb797-2175-4a90-b5a3-3918024b10b8).
>
> Apologies for cluttering #10310 with multiple commits referencing that issue. I ran `git push --force` after discovering that I needed to make changes to a pushed commit. For example, adding an entry to the `Fixed` section of `News.md`. For future reference, would you prefer I add multiple commits or squash the commits into one using `git push --force`?
> Created a new function `safe_converter::numberToHexString(long, bool)` based on the previous function `safe_converter::numberToString(double, bool)`. Then replaced calls to the previous function with …

log HRESULT error values as hex instead of decimal

---

src/gwt/src/org/rstudio/core/client/BrowseCap.java
src/gwt/src/org/rstudio/core/client/widget/ThemedPopupPanel.css

Addresses https://github.com/rstudio/rstudio/issues/10821.
This is probably eligible for backporting; if so I'll re-target to PT.
Use a CSS hack to force Safari try to render / layout popup elements in a way that avoids the default buggy rendering behavior. There's a bit of justification for this technique in https://stackoverflow.com/questions/10814178/css-performance-relative-to-translatez0.
Not included; automated testing here is not really feasible.
Check that menu items are rendered properly. See https://github.com/rstudio/rstudio/issues/10821 for more details.

use CSS workaround for Safari rendering bug

---

src/gwt/src/org/rstudio/studio/client/workbench/views/help/model/HelpInfo.java

Addresses https://github.com/rstudio/rstudio/issues/10844.
With the new enhanced help system for R 4.2.0, the argument table is no longer given the attribute `summary="R argblock"`. However, because we know that the argument table must come after the "Arguments:" header, it's safe to just iterate forward over siblings and use the first table we find.
Should already be covered by existing Help pane tests.
Check that the Help popup tooltip displays R help appropriately.

be more permissive when finding the R help argument table

---

src/cpp/r/R/Api.R

```
Sys.setenv("_R_CHECK_LENGTH_1_LOGIC2_"="true")
rstudio::navigateToFile(letters)
```
gives an ugly error without this

validate assumption of length-1 input

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputFrame.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java

See: https://github.com/rstudio/rstudio/issues/10836
Fix an issue identified with multi-page rmarkdown chunk output in which iframe-based (HTML) content cannot be interacted with, and remains permanently greyed-out.
I have moved where the event listeners are added which are responsible for managing the interactivity of the iframes. This means we can maintain the desirable behavior of "smart" uninterrupted scrolling but also allow it to work for multi-output rmarkdown chunks, such as the case identified by the user.
I have also made all frame-based outputs show a very subtle, dashed border around their content to mark where the interactive zone triggers a response. This dashed border becomes solid when the frame becomes interactive.
Not interacting: 
Interacting:
There are no automated …

Move where events are added on chunks to maintain scrolling fix on pages

---

src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/renderer/desktop-bridge.ts

Address #7992
Implements the feature for Electron. This fixes the export to clipboard issue present in Qt builds when the zoom level has been changed.
From GWT, it can still do the same thing and the values can be used with Electron's API to call `capturePage`. The preview can be resized and the zoom level can be adjusted without affecting what is copied to the clipboard.
None
I discovered that in #7992 that the issue occurs when changing the zoom level before exporting the plot. This does not fix the issue in Qt but the Electron implementation fixes the issue.
Sample code to generate something in the Viewer pane:
```R
library(gt)
library(tidyverse)
library(glue)
start_date <- "2010-03-07"
end_date <- "2010-06-14"
sp500 %>%
filter(date >= start_date & date <= end_date) %>% …
```

Copy viewer plot to clipboard

---

src/gwt/acesupport/acemode/cpp_code_model.js
src/gwt/acesupport/acemode/markdown_highlight_rules.js
src/gwt/panmirror/src/editor/src/@types/prosemirror-view/index.d.ts
src/gwt/panmirror/src/editor/src/behaviors/completion/completion.ts
src/gwt/panmirror/src/editor/src/behaviors/spelling/spelling-interactive.ts
src/gwt/panmirror/src/editor/src/editor/editor.ts
src/gwt/panmirror/src/editor/src/marks/raw_inline/raw_tex.ts
src/gwt/panmirror/src/editor/src/pandoc/pandoc_converter.ts
src/gwt/panmirror/src/editor/tools/generate-symbols.ts
src/gwt/src/org/rstudio/core/client/IntervalTracker.java
src/gwt/src/org/rstudio/core/client/widget/ModifyKeyboardShortcutsWidget.java
src/gwt/src/org/rstudio/studio/client/workbench/commands/CmdConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
src/gwt/src/org/rstudio/studio/client/workbench/views/plots/PlotsPane.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/ace-uncompressed.js
src/gwt/test/highlight_test_cpp.html
src/gwt/test/highlight_test_sql.html
src/gwt/tools/build-xterm-README.md
src/gwt/tools/editor-settings/eclipse-templates.xml
src/gwt/tools/i18n-helpers/README.md

Fixes typos found within the source code which includes comments and documentation. Follow-up to fea9c7d  
Found using `codespell -q 3 -S *_fr.properties -L ba,enque,optionel,ot,parm,parms,pres,prevend,pevent,pevents,ptd,texline`
but then combing through results pruning upstream 3rd party deps etc...
This PR fixes typos. No unit tests needed.
N/A

Fix various typos in `src/gwt`

---

src/cpp/server/auth/ServerAuthHandler.cpp

Add some warning messages that would've been helpful in debugging a customer support issue. 
Log a warning when the server receives a message with a `user-id` cookie but an empty or invalid `user-list-id` cookie - when the server is using a named user license. Even though this code is in open source, it only will ever be reached by RSW users.
N/A
N/A
- [] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md`

Add warnings for missing cookie

---

NEWS.md
src/cpp/core/system/PosixSystem.cpp

fixes #10829  
First we try to use getgrouplist(3) to determine if one of the
user's groups is the target group. If not, then we fall back
to the legacy implementation, using getgrnam_r(3) to attempt
a group member lookup.
Covered by existing tests

Fix group member verification when group member lookup is disabled

---

src/node/desktop/src/main/menu-callback.ts

Fix an issue that made menus not be able to be checkable on Electron. Debug and Panes are now working as expected.
Added type `checkbox` to menus.
None
None
Addresses #10866

Menus are now checkable on Electron

---

src/cpp/session/modules/SessionCodeTools.R
src/cpp/tests/testthat/test-pkg-deps.R

Followup to #10864 which was merged yesterday and broke unit tests
- Add a new unit test for quarto
- Fix behavior of `.rs.parsePackageDependencies for non-qmd files (specifically Rmd) by continuing to parse even if there are no R code chunks, since for Rmd we need to make sure we still parse the yaml front matter
Updated to pass.  Ran locally and all good 👍 
NA, should be QA'd as part of previous issue, [pro 3310](https://github.com/rstudio/rstudio-pro/issues/3310). This specific PR just relates to the testthat failure

Added new unit test for qmd and fixed existing tests for Rmd

---

.gitignore
src/cpp/session/resources/schema/user-state-schema.json
src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
src/node/desktop/NOTICE.electron
src/node/desktop/package-lock.json
src/node/desktop/package.json
src/node/desktop/scripts/generate.ts
src/node/desktop/src/core/file-path.ts
src/node/desktop/src/main/application.ts
src/node/desktop/src/main/detect-r.ts
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/preferences/desktop-options.ts
src/node/desktop/src/main/preferences/electron-desktop-options.ts
src/node/desktop/src/main/preferences/file-preferences.ts
src/node/desktop/src/main/preferences/mac-preferences.ts
src/node/desktop/src/main/preferences/preferences.ts
src/node/desktop/src/renderer/desktop-bridge.ts
src/node/desktop/test/unit/main/desktop-options.test.ts

Address #10484
This sets the preference priority to Electron-store > legacy Qt > default value for zoom level, fixed font, and R path. All other preferences can follow these as examples for preference priority. There is now a generated type for the user state based on `user-state-schema.json`. The file is also included during the webpack so that default values are taken from there. Hard-coded defaults have now been removed.
There is a new step in `postinstall` to generate the type. So running `npm ci` or `npm install` will generate the necessary type for the user state schema. The default values are pulled in at runtime and directly read from `user-state-schema.json`.
The default values are taken directly from `user-state-schema.json` now and there is type validation when setting values. …

Electron preference defaults and legacy priority

---

src/node/desktop/forge.config.js
src/node/desktop/package-lock.json
src/node/desktop/package.json

We are building setup packages using same techniques we did for Qt, not using the electron-forge "makers" are I originally assumed we would. So we don't need to install those packages on dev / build machines.
Remove them.
None, dev/build-time stuff.

We don't use the electron-forge makers so remove them from package.json

---

src/node/desktop/NOTICE.electron
src/node/desktop/package-lock.json
src/node/desktop/package.json
src/node/desktop/src/main/args-manager.ts

Addresses #10794
The `yargs` package was messing up support for the `--version` switch. Since we weren't really using `yargs` to its full potential, I just removed it.
None
RStudio --version should now show the version.

Fix Electron --version switch

---

src/node/desktop/package-lock.json
src/node/desktop/package.json
src/node/desktop/src/main/desktop-browser-window.ts

Latest and greatest Electron build. This bumps us up to latest major version (17 to 18).
https://www.electronjs.org/blog/electron-18-0
Usual npm upgrade song & dance. Required a one-line code change to remove obsolete property. I built and ran dev build, and a full package build, on Mac.
Confirmed the unit tests and the integration tests pass (only tried on Mac, will let build pipeline exercise the rest).
Nothing specific to test.

Update to Electron 18.0.1

---

src/gwt/panmirror/src/editor/src/marks/cite/cite.ts

These punctuation characters (".", "?", and ":") are in fact allowed the pandoc spec:
> Unless a citation key start with a letter, digit, or `_`, and contains only alphanumerics and single internal punctuation characters (`:.#$%&-+?<>~/`), it must be surrounded by curly braces, which are not considered part of the key. In `@Foo_bar.baz.`, the key is `Foo_bar.baz` because the final period is not *internal* punctuation, so it is not included in
the key.  In `@{Foo_bar.baz.}`, the key is `Foo_bar.baz.`, including the final period. In `@Foo_bar--baz`, the key is `Foo_bar` because the repeated internal punctuation characters terminate the key. The curly braces are recommended if you use URLs as keys: `[@{https://example.com/bib?name=foobar&date=2000}, p.  33]`.
We have added them to our …

remove some punctuation exclusions from cite ids

---

CMakeGlobals.txt
src/cpp/session/CMakeLists.txt

Addresses #10871 
Quarto only searches for the `share` directory in specific locations. With the difference in Electron packaging, Quarto can't find `share` in `RStudio.app/Contents/Resources/app`. Calling Quarto normally is fine until the new file dialog calls `quarto capabilities` which can't find the `share` directory.
Move the Quarto `share` directory to root of `Resources` where Quarto can find it using the relative path check. This option was chosen since it keeps the Quarto `bin` with the other `bin` files while keeping the `share` out of it. I believe this is intended with how Mac apps, in general, are packaged. The alternative is placing both Quarto `bin` and `share` directories together.
None. Must be built to reproduce the error as dev environments use Quarto from your …

Fix File > New File > Quarto Document

---

src/cpp/core/include/core/Random.hpp
src/cpp/core/include/core/http/TcpIpSocketUtils.hpp
src/cpp/desktop/DesktopMain.cpp
src/cpp/desktop/DesktopOptions.cpp
src/cpp/session/http/SessionWin32HttpConnectionListener.cpp

Addresses https://github.com/rstudio/rstudio/issues/10488. Candidate for backport.
- Adjust the random seed used by our RNG, so that the process PID is included. This should help reduce the chance of collisions when multiple RStudio sessions are launched at the same time.
- Use a UUID for the desktop shared secret, rather than just the system RNG.
- Validate that the port we've selected is actually open via TCP, and use it only if it appears open.
Not included; this fix is hard to test via automation.
On Windows, in a command prompt, try launching RStudio in the following way:
```
REM Change path below with wherever you have RStudio installed.
cd "C:\Program Files\RStudio\bin"  
for %i in (1 2 3) do start /b rstudio.exe
```
You should see 3 separate instances of RStudio launched. Try to …

reduce chance of collisions when generating port for desktop <-> rsession communication

---

src/cpp/session/modules/SessionFind.cpp

Adresses #10884 
instead of replacing the leading `.`, replace the leading `./` so that directories starting with `.` are not mistreated. 
in a project, create a file in a directory that starts with ".", e.g. 
```r
dir.create(".ignore")
writeLines("blablabla", ".ignore/test.txt")
```
Then search for "blabla". The results will appear: 
especially: 
Things in the `.Rproj.user` directory, as in the issue #10884 are dealt with differently. They are ignored no matter if the checkbox is clicked or not, by the `shouldSkipFile()` method: 
```cpp
bool shouldSkipFile(std::string file)
{ …
```

Better handles search results in directory starting with `.`

---

src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/main.ts

Addresses #10895
Port the behaviour from Qt, namely, ensure the desktop setting is synchronized with the session setting, and use that value to decide if we should disable renderer accessibility at startup.
After changing the "screen reader support" toggle it is necessary to restart Electron for it to take effect, but the restart performed is insufficient. Same problem as described here for gpu settings: #10748
None
Verify that when screen reader support is off, Electron doesn't expose the accessibility tree. You can use a screen reader to tell, or more easily, look at the accessibility diagnostics once #10901 is merged.

disable chromium renderer a11y based on user setting

---

NOTICE
src/cpp/CMakeLists.txt
src/cpp/core/include/core/Log.hpp
src/cpp/ext/CMakeLists.txt
src/cpp/ext/fmt/CMakeLists.txt
src/cpp/session/modules/SessionPath.cpp

This PR adds [fmt](https://fmt.dev/latest/index.html) as a dependency, to be used for type-safe string formatting. The utility macros `DLOGF()` and friends are added to make it easier to build larger format strings made up of many component pieces.
This PR is mostly a draft for discussion -- we can discuss whether or not we're comfortable adding `fmt` as a dependency; IMHO having a type-safe and ergonomic way to format strings will be very useful. (We do technically have `boost::format()` but I prefer the ergonomics of `fmt`. In addition, it has some extra facilities for compile-time checking where supported by the compiler.)
Straightforward bundling + building of `fmt` components.
Not included.
Developer-only change.

add libfmt dependency; use for log macros

---

src/gwt/panmirror/src/editor/src/api/pandoc.ts
src/gwt/panmirror/src/editor/src/marks/cite/cite.ts
src/gwt/panmirror/src/editor/src/nodes/line_block.ts
src/gwt/panmirror/src/editor/src/pandoc/pandoc_from_prosemirror.ts

Addresses https://github.com/quarto-dev/quarto-cli/issues/543
Should be backported to PT patch once merged.
@dragonstyle Could you review this?

prevent brackets inside cite marks from being escaped

---

NEWS.md
src/cpp/core/include/core/FileSerializer.hpp
src/cpp/session/modules/SessionPath.cpp

Addresses https://github.com/rstudio/rstudio/issues/10551.
Rather than attempt to read the PATH via `/etc/paths` and `/etc/paths.d`, invoke the user's default shell as a login shell and ask that shell what the PATH is. This approach has the added bonus in that we can respect the user's configured PATH on Linux as well.
TODO
Test that the PATH entries within a new RStudio session match what you see in a new terminal session. That is,
```
Sys.getenv("PATH")
```
and
```
echo $PATH
```
should print the same things in an RStudio session and a terminal session (assuming you aren't modifying your PATH within `.Renviron` or `.Rprofile`).

read PATH from default shell on startup

---

src/node/desktop/src/renderer/desktop-bridge.ts

Addresses https://github.com/rstudio/rstudio/issues/10905.
Fixes an issue with computing the filename when the user doesn't provide a file extension in the save dialog box.
TBA
Test via notes in https://github.com/rstudio/rstudio/issues/10905.

fix issue when adding default extension

---

src/cpp/session/CMakeLists.txt
src/cpp/session/SessionOptions.cpp

The first fix had an issue with finding Quarto. This resolves the packaged location and how it is found.
The Electron binary path now checks the resources root folder as well now that all of Quarto is packaged there.
None.
Packaged locally and tested to check that the new Quarto document dialog works.

Fix Quarto location for Electron

---

src/cpp/core/LoggingTests.cpp
src/cpp/shared_core/Logger.cpp

Currently, log message properties that contain new lines will forward those new lines into the log. This is undesired because log lines themselves should not contain new lines, as that is the delimiter between log lines.
Also, the log location of a log statement is not currently being logged for JSON and should be added.
Filter out newlines for log message properties formatted via the pretty formatter. No changes need to be made to the JSON formatting because JSON already encodes newlines as literal `\n`.
If there is a log location associated with a log statement and we are using the JSON log format, simply format it for JSON and put it on the `location` property of the log line.
Added two new tests to ensure that newlines in log message properties are not logged.

Log message fixes

---

src/node/desktop/.eslintrc.js
src/node/desktop/src/core/expected.ts
src/node/desktop/src/core/file-path.ts
src/node/desktop/src/main/detect-r.ts
src/node/desktop/src/ui/widgets/choose-r.ts
src/node/desktop/src/ui/widgets/choose-r/preload.ts
src/node/desktop/src/ui/widgets/choose-r/ui.html

Improves handling of invalid R installations; in particular, this allows us to properly handle the case where no valid installation has been registered as the default.
Validate that the R installation referenced in the registry exists + is valid.
Should be covered by existing tests.
Using `regedit.exe`, try editing the InstallPath registry value here, and change it to an invalid value.
Then, try launching RStudio with Ctrl held down, to trigger the "Show R" prompt. You should see the top radio button now disabled:

improve handling of invalid R installations

---

src/node/desktop/src/main/menu-callback.ts

Remove `Launcher` item from `Tools` menu.
All menus with a present `submenu` object with no items are now hidden as it's supposed they are present due to a bug or unintendedly present.
None
Open the app and check `Tools -> Launcher`. This submenu should not show up
Addresses #10900

Not showing menus with empty submenu object

---

src/cpp/desktop/DesktopSessionLauncher.cpp
src/cpp/server/crash-handler-proxy/CrashHandlerProxyMain.cpp
src/gwt/src/org/rstudio/core/client/StringUtil.java
src/gwt/src/org/rstudio/studio/client/application/ApplicationInterrupt.java
src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java
src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
src/gwt/src/org/rstudio/studio/client/application/DesktopFrameHelper.java

Addresses https://github.com/rstudio/rstudio/issues/10962.
- Ensure that calls to `setPendingQuit()` are properly sequenced, so we can be sure that the desktop front-end has handled our message before actually attempting to quit.
- Revert https://github.com/rstudio/rstudio/commit/6a2e343a8de14ee4b47c7fbbf391258671875e8e.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/10962.

handle sequencing of setPendingQuit callback

---

Jenkinsfile
docker/jenkins/Dockerfile.debian10-x86_64

Addresses #10676
Create dockerfile for a debian10 build machine, and generate Debian builds of Electron Desktop on it.
I tested locally via Docker, and was able to produce an Electron build that installed and ran on a Debian 11 machine.
Because this is is only being used for Electron, the Dockerfile doesn't bother installing the Qt SDK.
Similarly, I didn't do changes that would be needed for building workbench/session bundles, etc. Those will continue on debian9 for the time being.
Build stuff.
The resulting builds should be usable on Debian 10 (Buster) or Debian 11 (Bullseye). I did not try on a Debian 9 machine (debian 9 is about to go out of support altogether so don't think we care for Electron).

build Electron on Debian10

---

docker/jenkins/Dockerfile.debian10-x86_64

Electron unit tests (will) fail on debian10 build because dockerfile didn't install xvfb.
Add xvfb to the dockerfile.
Metaphysical
Nothing to test directly

install xvfb for electron unit tests

---

src/node/desktop/src/main/detect-r.ts
src/node/desktop/src/main/session-launcher.ts

Addresses https://github.com/rstudio/rstudio/issues/10954.
Use 32-bit rsession.exe path when R declares itself to be 32bit.
N/A
N/A

support launching with 32bit R

---

src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/renderer/desktop-bridge.ts

Addresses https://github.com/rstudio/rstudio/issues/10969.
The Electron implementation for `setPendingQuit()` wasn't accepting (or invoking) a callback to signal when the IPC request had been handled; this PR brings that in.
N/A
N/A

ensure callback is invoked after setPendingQuit

---

src/cpp/rstudio-tests.in
src/cpp/server/ServerDatabaseMigrationTests.cpp

Sqlite tests are now run by default since they don't require additional
setup.
These tests run database upgrade tests
rstudio-tests now changes the cwd to server when running the rserver-tests.
Enable automatic use of databse test cases. SQLite only right now, as it won't add additional burden to the infrastructure.
The previously hidden sqlite tests have been unhidden, since the tests depend on files to create and upgrade the database, the working directory needs to be known before hand. The `rstudio-tests` now steps into the server directory before running the `rserver-tests`.
The postgresql tests remain hidden.
This enables automated tests.
If the automated build works, it passes. Should have little to no QA impact.

Enable sqlite testing by default

---

src/gwt/src/org/rstudio/core/client/theme/ThemeFonts.java

Fix the monospace fallback when selecting an invalid font. Addresses #10939  
As part of the Electron font selection work, this bit of code was removed but it's actually the fallback in case the specified font is invalid. It's likely that `Courier 10 Pitch` is an invalid font family and the monospace fallback was defaulting to a monospace font.
None
Selecting `Courier 10 Pitch` will have a fixed width font for the console but it may not actually be `Courier` but should be fixed width.

Undo font change to monospace fallback

---

src/cpp/core/http/SocketProxy.cpp
src/cpp/core/include/core/http/SocketProxy.hpp
src/cpp/server/ServerSessionProxy.cpp
src/cpp/server/auth/ServerAuthCommon.cpp
src/cpp/server/auth/ServerAuthHandler.cpp
src/cpp/server/auth/ServerSecureUriHandler.cpp
src/cpp/server/include/server/ServerSessionProxy.hpp
src/cpp/server/include/server/auth/ServerAuthCommon.hpp
src/cpp/server/include/server/auth/ServerAuthHandler.hpp
src/cpp/server/include/server/auth/ServerSecureUriHandler.hpp

Keep track of a UserSession to authorize reads from the client-side of a websocket so that signout closes these connections. 
Reviewed in the rstudio-pro PR:
https://github.com/rstudio/rstudio-pro/pull/3381

OS companion commit for socket security patch 2

---

src/node/desktop/test/unit/core/file-path.test.ts
src/node/desktop/test/unit/core/xdg.test.ts
src/node/desktop/test/unit/main/menu-callback.test.ts

Addresses #10946 (and also some other warnings not mentioned in an issue):
(node:22538) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
Release listeners attached by construction of MenuCallback after each test, and eliminate deprecation warnings by stopping use of the to-be-deprecated functions.
Same tests, less noisy warnings.

eliminate warnings from Electron unit tests

---

src/cpp/server/auth/ServerAuthCommon.cpp
src/cpp/server/auth/ServerAuthHandler.cpp
src/cpp/server_core/http/SecureCookie.cpp
src/cpp/server_core/include/server_core/http/SecureCookie.hpp

Before this change, the current cookie was not in the
UserSession, which meant that if two tabs were directly addressing
different servers in the cluster, using different server:port
(and thus different cookie domains), the most recent cookie in one cluster
would not get revoked if the other session was signed out.
It's safer to make sure all cookies used by a UserSession for one member in the
cluster get revoked when another server revokes a cookie (i.e. the user signs out from there)
Part of the fix for: https://github.com/rstudio/rstudio-pro/pull/3381
(BTW, I'm going to merge this before the review  to get the builds going).

Put all session cookies in the UserSession

---

src/cpp/server/auth/ServerAuthCommon.cpp

This is now done in invalidateUserSession for all cookies.
For postgres, the extra call causes an error in the logs on signout.
Another part of the fix for: https://github.com/rstudio/rstudio-pro/issues/3287
(This is another small change part of that previous fix so I'm going to merge before the review again...)

Removed redundant call to invalidateAuthCookie

---

src/cpp/server/auth/ServerAuthHandler.cpp

In a load balancing scenario, the UserSession from more than one server
may end up storing the session same session cookie. This is particularly
true when one rserver routes the request to another for load balancing...
in that case, both rservers will get the same auth cookie to represent
that session.
Now that we invalidate all auth cookies when a user signs out, on all
servers in the cluster, that means some of them will try to insert a
record into the DB that's already there. We just need to ignore those
specific errors.
Part of the fix for: https://github.com/rstudio/rstudio-pro/issues/3287

Ignore duplicate key errors for postgres and sqlite for revoked cookies

---

src/cpp/session/SessionOptions.cpp

Fix Qt accidentally using Resources/quarto as the quarto binary path. This caused the IDE to not show File > New File > Quarto Document/Presentation
Move the Electron path check to after Qt. It turns out that the Electron portion of the check would look in `app` for Quarto. In a Qt package, it looks in `Resources` which holds the Quarto `share` directory. The session ends up using that path and the Quarto checks for the menu items would see that Quarto is not available at that location so the items aren't shown.
The Electron path check was first but I don't think it has to be the first location to check for the binary.
None
I've locally patched a daily Qt build and local Electron build and it works now.

Move Electron path test to after Qt path test for Mac

---

src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java

Follow-up to #10814. 
Text and button on Global Preferences pane (Code tab) is only visible when a project is active
No active project: 
Active project:
N/A
Check Tools > Global Options > Code pane with and without a project active

Make project settings button visible only when a project is active

---

src/cpp/session/modules/build/SessionBuildErrors.cpp

addresses #11026
Improve the regex used by test that error parser so that it can remove the hyperlink escape codes syntax. 
On a package that has at least one failed expectation, e.g. 
```r
test_that("2+2", {
expect_identical(2+2, 5)
})
```
Running the tests should make the `Output | Issues` button couple visible: 
This needs dev `cli` and `testthat`
```r
pak::pak("r-lib/cli")
pak::pak("r-lib/testthat")
```
This should work with hyperlinks enabled (default) or disabled: 
```r
Sys.setenv("RSTUDIO_CLI_HYPERLINKS" = "false")
```

test that error parser compatible with hyperlinks

---

CMakeGlobals.txt
src/cpp/CMakeLists.txt
src/cpp/core/CMakeLists.txt
src/cpp/core/LogOptions.cpp
src/cpp/core/ProgramOptions.cpp
src/cpp/server_core/CMakeLists.txt
src/cpp/shared_core/CMakeLists.txt
src/cpp/shared_core/FileLogDestination.cpp
src/cpp/shared_core/config.h.in

Sync the C++ libraries between the rstudio and Launcher repos.
On our side, we will use some merge strategies to rewrite the histories of the rstudio-pro repo to extract out just the library code changes, and then pull them into the Launcher code base regularly (see https://github.com/rstudio/launcher/blob/6e2227de2e1e0939317740aee1ef503ecf17c230/sync-repo.sh). The changes made here sync up the two codebases to ensure that when a sync is done, nothing is overwritten in the Launcher repo.
Changes had to be made to unify things, such as the log location (which differed between the codebases). This is unified via a CMake variable which is set in files that are not shared within the libraries themselves.
Similarly, we do not support any database functionality as of yet, so we conditionally …

Sync cpp lib launcher

---

src/node/desktop/.gitignore
src/node/desktop/CMakeLists.txt
src/node/desktop/Info.plist.in
src/node/desktop/forge.config.js
src/node/desktop/src/main/application.ts
src/node/desktop/src/main/args-manager.ts
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/session-launcher.ts
src/node/desktop/src/renderer/desktop-bridge.ts

Addresses #10893
Allows opening associated files, dragging files on to the app icon, and command-line arguments
Feeds in the `Info.plist.in` template when building the app. This associates the files with MacOS.
Listens to the `open-file` event which triggers for associated file open events and dragging files on to the app icon. For project files, this sets the env var before the session is created so that the project is opened.
For command-line arguments, they are searched for unswitched options, checks if it's a valid file, and opens it.
An `initialized` property was added to the GWT callback so it can track when GWT has initialized the workbench. Responding to the app open event needs to know if the workbench is ready to call the open file action.
None
Main cases to test:
* dragging …

Electron Mac file associations

---

package/win32/CMakeLists.txt
package/win32/make-install-win32.bat
package/win32/make-package.bat
src/node/desktop/forge.config.js

Addresses https://github.com/rstudio/rstudio/issues/11035.
Some NSIS hacks to make sure that the application "friendly name" + copyright are set. (I couldn't find out where exactly Electron was choosing to use "rstudio" rather than "RStudio" here.)
N/A
- Check that the application copyright is properly set
- Check that the application name is presented as "RStudio" in right click open menus

add windows metadata to Electron installation

---

NEWS.md
src/cpp/core/include/core/r_util/RSourceIndex.hpp
src/cpp/core/r_util/RSourceIndex.cpp
src/cpp/session/modules/SessionCodeSearch.cpp
src/cpp/session/modules/clang/DefinitionIndex.cpp
src/cpp/session/modules/clang/DefinitionIndex.hpp
src/gwt/src/org/rstudio/studio/client/workbench/codesearch/CodeSearchOracle.java
src/gwt/src/org/rstudio/studio/client/workbench/codesearch/model/SourceItem.java

adresses #10912
For R files and c++ files: ignore items from files that have "do not edit by hand"

fuzzy finder: ignore things from "do not edit by hand" files

---

package/linux/install-dependencies

Addresses #10916
Picked 3.19.x because it isn't bleeding edge, but matches the highest minimum version we require (on osx, which doesn't use this script for installing cmake, but picked that just for consistency):
https://github.com/rstudio/rstudio/blob/ba0b1462a760b9bdde7d2250011ab50c86bbbac1/package/osx/cmake/codesign-package-electron.cmake#L16
My understanding is we have such an old version currently because some of the ancient distros we used to build on couldn't handle building anything much newer, but that was MANY years ago.
It's possible I'll discover that's still the case in which case I'll have to rinse and repeat with a lower version.
Build-time change only.
None

install cmake 3.19.8 on builders

---

Jenkinsfile
NEWS.md
docker/jenkins/Dockerfile.debian10-x86_64

Addresses open-source side of #10981, see https://github.com/rstudio/rstudio-pro/pull/3394 for full change.

open-source companion to Pro #3394

---

docker/jenkins/Dockerfile.debian10-x86_64

When I made the debian10 dockerfile I decided to install cmake using `apt` instead of building a specific version from source like we do on other platforms.
For consistency (and especially now that we're building a relatively new version of cmake) switch debian10 to same technique.
I will do the same for the monitor dockerfile (Pro) via separate PR.
Same approach as other dockerfiles.
None
Build mechanics, nothing to test.

install same cmake for debian10 used by other Linux builds

---

src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/LintManager.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java

Addresses part of https://github.com/rstudio/rstudio/issues/10967.
Use built-in Ace methods for converting between document indexes and positions.
Captured by existing tests.
Does not entirely fix https://github.com/rstudio/rstudio/issues/10967, but should at least make things better.

use Ace built-in methods for converting positions

---

src/node/desktop/forge.config.js

Closes https://github.com/rstudio/rstudio/issues/11071.

use RStudio executable name on macOS

---

Jenkinsfile

* Spotted-Wakerobin won't support debian9 (it goes out of support at end of June 2022), so stop building it.
* Debian10 build is redundant, the "bionic" build is already intended for use on debian10 (debian9 was a special-case due to libssl issues; why is it always libssl issues?)
* We no longer support opensuse, either, so stop building that
Delete lines in Jenkinsfile.
N/A
N/A

Stop building obsolete/unnecessary platforms

---

src/gwt/src/org/rstudio/core/client/VirtualConsole.java
src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java

adresses #9846
handle special case of right side (full) overlapping
Added a unit test inspired from the text of #9846. This could probably be simplified 🤷 
```java
public void testIssue9846()
{
PreElement ele = Document.get().createPreElement();
VirtualConsole vc = getVC(ele);
vc.submit("i Some intermediate step with a \033[32mfield\033[39m-----------------------\r+++++++++++++++++++++++++++++++++++++\r\033[33m!\033[39m An alert message which is long enough\ni Some intermediate step with a \033[32mfield\033[39m\n");
Assert.assertEquals("<span class=\"xtermColor3\">!</span><span> An alert message which is long enough</span><span>---------------------\ni Some intermediate step with a </span><span class=\"xtermColor2\">field</span><span>\n</span>", ele.getInnerHTML());
}
```
This code: 
```r …
```

Fix carriage return colour interaction

---

src/cpp/session/resources/schema/user-prefs-schema.json
src/gwt/src/org/rstudio/studio/client/common/StudioClientCommonConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java

Follow up to #8255 -- small tweaks to text based on feedback.
Separate question based on other feedback from the demo session last week:
There was feedback that it was difficult to visually distinguish the Project Preferences Note in order to realize it was not another setting. Do you think it's okay as is, or would you suggest any other visual changes? Perhaps a tad more padding at the top between Keybindings and the note? We could indent it as well but that would make it look like it was nested under keybindings. We could also put the whole note in parentheses, like the python note is. Or maybe you feel it's still fine as is

Small text tweaks based on feedback

---

src/node/desktop/src/main/gwt-callback.ts

Fix an issue that would make the `Choose R` popup on Windows not to display the correct language when opened from Global Options Window.
That popup now also handles the correct locale.
None
Info on #11079
Addresses #11079

Fix Translation on Choose R Popup from Global Options

---

src/cpp/session/modules/SessionFind.cpp
src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/model/FindInFilesServerOperations.java

Fix bugs described in #11041 and #11125
1. We previously added two new git grep related params to the begin Find RPC calls, but not to the preview Replace and complete Replace calls, leading to parameter mismatch errors when attempting to do replacements with regex selected (the replace methods are actually only called when regex is True)
2. We previously stripped off the leading `./` from non git grep search result paths, when instead we should have stripped only the `.`, which resulted in a missing separator `/` between the search directory and the result path
Will check existing tests
Find in Files search and replace with regex selected

Fix SW bugs in Find in Files path and find in files replacements

---

src/cpp/core/include/core/r_util/RActiveSessionStorage.hpp
src/cpp/core/include/core/r_util/RActiveSessions.hpp
src/cpp/core/r_util/RActiveSessionStorage.cpp

It's not needed, in any case, so we drop it.
Session ID made it into our storage interface, it's not needed.
Dropped the id from the interface
None needed
No further QA testing, compiling will demonstrate the changes work

Drop Session ID from interface

---

src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_fr.properties

Questions: 
- (technical) I see that sometimes double single quotes are used, e.g. `terminalPythonIntegrationTitle= Activer l''intégration Python du terminal` and so I tried `uiLanguageTitle= Langage de l''interface utilisateur·rice` but it showed up as two single quotes instead of one as expected. Is there anything I'm missing ?
- (cultural): Je suis parti sur de l'écriture inclusive avec point médian (interface utilisateur·rice). Qu'en pense d'autres francophones ? @cderv @maelle @ColinFay ...

`uiLanguage*` properties in fr

---

src/node/desktop/src/renderer/desktop-bridge.ts

Fix an issue that would make the Tab Title show  the full path instead of filename only on windows
Removed double slashes for when saving files on Windows.
None
Instructions on #11046
Addresses ##11046

Full Path on Tab Title When Saving New File on Windows

---

NEWS.md
src/cpp/session/modules/SessionRmdNotebook.R

Addresses #10645 so that YAML style chunk options are evaluating when executing a chunk
This PR includes only backend changes so the YAML chunk options are respected and combined with the standard chunk options when executing a chunk inline. This does not affect the UI of the ChunkOptionsPopupPanel -- however, upon investigation that would require a lot more lift for seemingly minimal benefit, and there is no clear way forward, as the LineWidget really only ever parses the first line of a chunk on the frontend. Given this, and given that only a very small set of chunk options are even considered in the PopupPanel (see below), I'm not sure the frontend changes are worth doing at this time. We can always revisit if this becomes important to users
None
Run chunks with both YAML and standard …

Fix backend yaml chunk evaluation of options

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java

addresses #10987 
Not quite sure about this; but the bug described in #10987 was happening with the `target_.setPreferredOutlineWidgetVisibility(destination != 0);` code in: 
```java
toggleDocOutlineButton_ = new LatchingToolbarButton(
ToolbarButton.NoText,
ToolbarButton.NoTitle,
false, /* textIndicatesState */
new ImageResource2x(StandardIcons.INSTANCE.outline2x()),
event -> {
final double initialSize = editorPanel_.getWidgetSize(docOutlineWidget_);
// Clicking the icon toggles the outline widget's visibility. The
// 'destination' below is the width we would like to set -- we
// animate to that position for a slightly nicer visual treatment.
final double destination = docOutlineWidget_.getOffsetWidth() > 5
? 0
: Math.min(editorPanel_.getOffsetWidth(), …
```

VisualMode only react to change in DOC_OUTLINE_VISIBLE if activated

---

NEWS.md
src/cpp/session/modules/SessionHelp.cpp
src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.java

Addresses https://github.com/rstudio/rstudio/issues/10142.
Addresses https://github.com/rstudio/rstudio/issues/11022.
Examples using `vignette("programming", package = "dplyr")`.
And also, from https://github.com/rstudio/rstudio/issues/11022, with no styling applied:
Replace the class names for highlighted source code with the corresponding Ace highlight CSS class.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/10142.

apply ace editor style to vignette code

---

NEWS.md
src/gwt/acesupport/acemode/r_highlight_rules.js
src/gwt/acesupport/acemode/rainbow_paren_highlight_rules.js

Addresses https://github.com/rstudio/rstudio/issues/11087.
Multi-mode documents embed the highlight rules of other languages by prepending the associated state names with a language-specific prefix. For example, R highlight rules are embedded for R Markdown documents here:
https://github.com/rstudio/rstudio/blob/0a4befe8ef2003ea69b554f1ae2280141f6f6aaa/src/gwt/acesupport/acemode/rmarkdown_highlight_rules.js#L58-L66
Importantly, this is done by giving each "state" name from that highlight group a unique prefix, so that the highlight definitions from one language don't collide with those from another. However, this implies that highlight rules in those languages need to be careful, since the "raw" state names might be transformed in such cases.
N/A …

properly handle R rawstring state in multimode docs

---

src/cpp/r/RCntxt.cpp
version/news/NEWS-2022.02.3-prairie-trillium.md

PRs #9922 and #10238 changed the definition of equality used by the debugger to check the context stack. However, this change introduced a new regression, described in #10664 . This small change fixes the original issues (#9918 and #10045) while also resolving the new regression (10664)
Add one more constraint to the equality test -- check if other isNull(). Original equality test was too strict, then it became too liberal, hoping it is now juuuuuust right
Needs PT backport
No new tests added. Will ensure that [ide-automation#497](https://github.com/rstudio/rstudio-ide-automation/issues/497) still passes.
Test the reprexes in all three linked issues:
#9918 
#10045
#10664

Check for nulls when testing equality

---

src/cpp/core/include/core/r_util/RActiveSessions.hpp
src/cpp/core/include/core/r_util/RSessionContext.hpp
src/cpp/core/r_util/RActiveSessions.cpp
src/cpp/core/r_util/RSessionContext.cpp
src/cpp/r/include/r/session/RSession.hpp
src/cpp/r/session/RInit.cpp
src/cpp/session/SessionMain.cpp

- editor, lastStateUpdated, and activityState properties to session metadata
- suspend/resume callbacks so the session can update the activity state at the right time
Reviewed in workbench PR: https://github.com/rstudio/rstudio-pro/pull/3408

Companion commit for server side of activity state changes

---

src/cpp/session/modules/SessionCodeTools.R

If `x` is a multibyte character, `charToRaw(x)` returns a vector longer than 1. Since R 4.2.0 or later, calling if() with a condition of length greater than 1 gives an **error** rather than a warning (https://cran.r-project.org/doc/manuals/r-release/NEWS.html), so the L1218 `else if (charToRaw(x) < 20)`  in `jsonEscapeString()` in SessionCodeTools.R should be corrected.
https://github.com/rstudio/rstudio/blob/438f4c08d77b1424a9b3bb193d16060cdae06aaa/src/cpp/session/modules/SessionCodeTools.R#L1211-L1226
In fact, due to this bug, R 4.2.0 sometimes fails to load R Notebooks (which are probably contain multibyte characters) with an error when opening them.
Evaluate whether `charToRaw(x)` is less than 20 only when the length of `x` is equal to 1.
> Indicate whether this change includes unit …

Fix jsonEscapeString() in SessionCodeTools.R

---

src/cpp/session/modules/SessionCodeTools.R
src/cpp/session/modules/SessionDiagnostics.R

I made a whoopsie! When I made [this change ](https://github.com/rstudio/rstudio/pull/10864), I filtered out empty lines because they were empty, so we don't need to check whether or not they contain R code. That was a mistake, because we DO need them in order to make sure the diagnostic source code markers in the gutter actually line up with the appropriate code line, which means they need to include the blank spaces. We should filter them out only later, when we are checking for the existence of R code, rather than in SessionDiagnostics.R
Remove 1 silly line of code so we don't filter out blanks. Filter out the newline characters later instead
> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. …

don't remove empty lines of code -- we need them for the source code markers

---

src/gwt/src/org/rstudio/studio/client/common/vcs/CreateKeyDialog.java

Follow up to #8255. Address issue that @romainfrancois raised during testing. There was previously no connection between the SSH key you just created, and the SSH key that would be chosen (based on the computed user preference) when you re-open the Global options pane. Update so that the key you just created takes precedence, no session restart necessary.
On successful response to RPC call creating the SSH key, reset the computed user preference to point to the new key.
None
Can follow Romain's test plan in the #8255 [comments](https://github.com/rstudio/rstudio/issues/8255#issuecomment-1117141856). 
Create new SSH key. Close and re-open Global options pane, check that SSH key path and View public key file point to the newly created key, and not the old one you had before.

Make newly created SSH key the preferred key

---

src/gwt/src/org/rstudio/studio/client/common/vcs/CreateKeyDialog.java

Follow up to #11182, adresses #8255
In #11182 we updated the "rsa_key_path" property, but we also need to update the "have_rsa_key", otherwise it's only set in `UserPrefsComputedLayer::readPrefs()`. 
This PR sets it to `true` 

Update the `have_rsa_key` to true property when a ssh key is created

---

src/gwt/src/org/rstudio/studio/RStudio.gwt.xml

Cleanup unused class replacements in RStudio.gwt.xml.
Confirmed the GWT codebase (including pro/workbench) doesn't include any of `WebCRANChooser`, `CRANChooser`, `DesktopCRANChooser `, `ActionsWidget `, `DesktopActionsWidget`, or `WebActionsWidget ` and removed from RStudio.gwt.xml.
N/A

remove unused gwt class replacements

---

NEWS.md
src/cpp/core/http/Request.cpp

Addresses: https://github.com/rstudio/rstudio/issues/11010
The first one in the comma separated list will be the first proxy in the chain, i.e. the
one that matches the browser's URL and the one we should use for redirects. 
This is a fairly easy fix and not that common so I propose we skip automation.
- [x ] If this PR adds a new feature, or fixes a bug in a previously released version, it includes an entry in `NEWS.md` 
- [x ] If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)
- [x ] A reviewer is assigned to this PR (if unsure who to assign, check Area Owners list)
- [x ] This PR passes all local unit tests

Fix to support a chain of proxy servers in front of RStudio server. 

---

src/cpp/core/include/core/r_util/RTokenizer.hpp
src/cpp/core/r_util/RTokenCursorTests.cpp
src/cpp/session/modules/SessionRParser.cpp

Addresses #10124
Do the same thing we do with the magrittr pipe, i.e. 1) update isPipeOperator to recognize `|>` as a valid pipe, 2) add to the list of unnamed arguments only if magrittr pipe is used without `.` or native pipe is used without `_`
Small tweaks to automated tests for isPipeOperator regex.
With diagnostics turned on for "Check arguments to R function calls"
```
c(1,2,3) %% length()            # EXPECTED: warning (missing arg, because not a pipe)
c(1,2,3) %>% length()          # EXPECTED: no warning
c(1,2,3) %>% length(.)         # EXPECTED: no warning
c(1,2,3) |> length(_)              # EXPECTED: no warning
c(1,2,3) |> length()                # EXPECTED: no warning
c(1,2,3) |> cor(y = c(1,2,3))  # EXPECTED: no warning
cor(y = c(1,2,3))                    # EXPECTED: warning …
```

Addresses handling of native pipe args with no placeholder

---

src/gwt/acesupport/acemode/r_code_model.js
src/gwt/acesupport/acemode/r_scope_tree.js
src/gwt/panmirror/src/editor/src/api/rmd.ts

addresses #10473
Improve `getChunkLabel()` so that it looks for `#| label:` after the opening of the scope. 
Open this quarto document: 
````
---
title: Test Quarto
---
```{r}
#| label: foo
1 + 1
```
```{r}
#| label: bar
2 + 3
```
````
The chunk labels should be displayed in the source and visual editors:

Outline uses quarto style labels, `#| label: <name>`

---

src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java

We already allow users to open these files from the File pane. We also already allow users to open these files from the Find in Files results pane in RStudio Server. We just haven't allowed users to open these from Find in Files results in RStudio Desktop. This seems to be overly strict.
Addresses #10741
Remove the Desktop/Server distinction and allow for normal opening of unknown text file types as plain text.
None
See #10741

Allow fallback unknown text file types to open in Desktop

---

src/cpp/core/include/core/system/Win32RuntimeLibrary.hpp
src/cpp/core/system/Win32RuntimeLibrary.cpp
src/cpp/session/SessionMain.cpp

Addresses https://github.com/rstudio/rstudio/issues/11206.
Newer versions of R will set errno in ucrtbase.dll, so read it from there instead of msvcrt.dll.
N/A
Given a file with the contents:
```
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
AAAAAAAAAAHHHHHHHHHHHHHHHHHHHH
```
(Screaming is an important part of the test procedure)
- Open a file test.R, and paste these contents in,
- Try to save the file,
- …

use ucrtbase.dll with R 4.2.0 or newer

---

Jenkinsfile

Open source merge for https://github.com/rstudio/rstudio-pro/pull/3450.

open-source merge for rstudio-pro/pull/3450 (fedora 36 builds)

---

NEWS.md
src/gwt/src/org/rstudio/studio/client/application/ui/RVersionSelectWidget.java

See: https://github.com/rstudio/rstudio-pro/issues/3451
- regression from 8cdb7ca
Fix a regression from a previous commit that inadvertently removed the (Use System Default) option from some R Version Selector drop downs.
Pass through all flags in the chained constructor to the next constructor.
N / A
Manually verify. Check that (Use System Default) is available in Tools > Global Options > General. See the pro issue for screenies.

Fix flags not being passed through constructor in R version selectors

---

NEWS.md
src/cpp/desktop/DesktopPosixApplication.cpp

Addresses [rstudio-pro#3291](https://github.com/rstudio/rstudio-pro/issues/3291) - specifically, if you have Mac Desktop Pro already running and you double-click on a `.rdprsp` file, it should now correctly open the remote session in a new RDP instance instead of just opening the file as a text file in the editor.
The cause: on macOS, if an application is already running and you double-click on a file that is set to open in that application, macOS sends the existing running application an event to open the file. This differs from Windows and Linux where a new instance is started directly when you double-click on a file.
This was reviewed via https://github.com/rstudio/rstudio-pro/pull/3457.
Apply the same technique already used for handling this scenario with project files to remote …

ensure new IDE instance is created when opening remote session file

---

CMakeGlobals.txt

Disable quarto on Centos7 to address https://github.com/rstudio/rstudio-pro/issues/3299
Set QUARTO_ENABLED to false in CMake. Will need to make an update in rstudio-ide-automation as well.
May want to make a change to UI so users are aware why Quarto does not appear as an option
Need to make an update to rstudio-ide-automation (per Maria's comment on  https://github.com/rstudio/rstudio-pro/issues/3299)
Test that user running on Centos7 does not have Quarto enabled and cannot create Quarto docs

Disable quarto on centos 7

---

src/cpp/rstudio-tests.in

Unit tests failing on fedora36 with:
[2022-05-17T17:31:47.429Z] ==> Running 'rsession' tests
[2022-05-17T17:31:47.685Z] 2022-05-17T17:31:47.612605Z [rsession-] ERROR system error 2 (No such file or directory) [path: /usr/share/doc/R]; OCCURRED AT rstudio::core::Error rstudio::r::session::discoverR(RLocations*) src/cpp/r/session/RDiscovery.cpp:69; LOGGED FROM: int main(int, char* const*) src/cpp/session/SessionMain.cpp:2384
The path reported by:
```R
R.home('doc')
```
in the docker container doesn't exist, and this breaks our tests.
We don't need anything to actually be there, just need the folder to exist. So create it if missing.
N/A
Unit test fixes.

fedora-36 specific unit test fix

---

NEWS.md
src/cpp/session/SessionAsyncRProcess.cpp
src/cpp/session/SessionConsoleProcess.cpp
src/cpp/session/SessionMain.cpp
src/cpp/session/modules/build/SessionBuild.cpp
src/cpp/session/modules/jobs/ScriptJob.cpp
src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
src/cpp/session/modules/shiny/ShinyAsyncJob.cpp

addresses #11024 
Define the `RSTUDIO_BUILD_PANE` environment variable in `Build::executeBuild()` which I believe is only called from `Build::start()` which sets the callbacks so that standard output goes through `Build::onStandardOutput()`, eventually picked up by the ui side by `void onBuildOutput(BuildOutputEvent event)` 

Indicate if R is running in the build pane

---

src/cpp/core/r_util/RToolsInfo.cpp
src/cpp/session/modules/SessionClang.R
src/cpp/session/modules/clang/RCompilationDatabase.cpp
src/cpp/session/modules/clang/RCompilationDatabase.hpp

Addresses https://github.com/rstudio/rstudio/issues/7554#issuecomment-1126513442.
The previous implementation tried to write the compiler definitions header to the R temporary directory. However, this path cannot be used for the base compilation arguments, as those get persisted as part of the compilation database, and so we end up persisting a transient path.
Instead, we use a stable scoped scratch path. We also ensure that the compiler definitions are re-generated if we need to re-generate the rest of the compilation database.
N/A
https://github.com/rstudio/rstudio/issues/7554#issuecomment-1126513442

tweak how compiler definitions are passed along to libclang

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java

Addresses edge case of #10645 found by @hadley where the YAML chunk options only work in inline chunk execution ("notebook mode"), not when chunks are executed in the console.
Ultimately, we need to revamp our definition of notebook mode a bit -- it seems too expansive, in that chunk execution is handled differently in many ways depending on whether chunk execution is set to inline or console. However, the immediate concern here is that when `#| eval: false` is provided as a chunk option, the chunk erroneously executes when in console mode. It correctly does not execute when in inline mode. We previously changed behavior on the backend to parse these new format chunk options. Here, we additionally update the frontend method `isExecutableChunk` so that it not only returns `false` when the …

change def of isExecutableChunk to recognize `#| eval: false`

---

dependencies/common/install-quarto
dependencies/windows/install-dependencies.cmd
dependencies/windows/install-quarto/get-quarto-version.ps1

Address #10920
Updates the dependency installer scripts to get Quarto directly from the latest GitHub release instead of AWS S3. This would be temporary until Spotted Wakerobin is ready to pin Quarto to the final release. The old code for retrieving a specific version from S3 remains so that we can upload the final Quarto release and go back to a pinned version.
The latest release version is retrieved from the GH REST API. It fetches the most recent release tag. Then it constructs the download link to the latest release. The version is required since the release assets include the version in the file name.
There is a version check in the source for the required and recommended minimum Quarto version but I don't think that needs to be updated right now.
None
Builds will be bundling a …

Build with latest quarto

---

src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileCommandToolbar.java

QA discovered that when Quarto is disabled, Quarto doc shows up in the Files pane under New blank file...
Check session Info to see if quarto is configured, and if not set the Quarto doc item to invisible
Also removes quarto file from the Command Palette
None
Will repeat QA testing on Centos 7 from https://github.com/rstudio/rstudio-pro/issues/3299

Hide blank quarto doc when quarto disabled

---

src/cpp/desktop/DesktopMenuCallback.cpp
src/cpp/desktop/DesktopMenuCallback.hpp

Addresses: #11189
The underlying issue is Qt's internal heuristics which move some menu items to the Mac Application menu based on the labels of the menu items. We do additional work to try and prevent this in some cases. All of this behaves badly when the UI strings aren't in English.
Given we are not officially supporting non-English UI in the upcoming release (it is labeled as "experimental"), and are retiring the Qt-based desktop after this release, I've made some horrible hacks to improve the situation in French, and not impact English in any way.
With this change, the main menu should not be any different than before in English. In French, I fixed the following:
* There is now a Windows menu between Tools and Help (this was missing because our code was looking specifically for …

fix some issues with Mac main menu in French (Qt)

---

src/node/desktop/package-lock.json
src/node/desktop/package.json

Upgrade electron to 18.2.4
This includes a fix for Linux that caused a crash at startup.
Updated package.json
None
`npm start` on Linux starts up properly and no longer has an error about missing libxkbcommon.

Upgrade electron to 18.2.4

---

src/node/desktop/src/main/gwt-callback.ts

Addresses #11142
Turn off menubar by default when creating window for GPU or Accessibilty diagnostics.
While I was there, also explicitely turn on sandbox and set the acceptFirstMouse to true so clicking on a button (e.g. copy to clipboard) in these windows on Mac will happen even if the window didn't have focus when clicked.
None
Needs to be tested on Windows and/or Linux.

hide menu bar on GPU and Accessibility diagnostic windows (Electron)

---

src/node/desktop/src/renderer/desktop-bridge.ts
src/node/desktop/src/ui/utils.ts

Fix an issue that would make duplicated files to appear on `Recent Files` submenu.
Replaced `home` path with `~`.
None.
Refer to #11150
Addresses #11150

Duplicated files on Recent Files fix - Electron

---

src/cpp/r/session/RSessionState.cpp
src/cpp/session/SessionAsyncRProcess.cpp
src/cpp/session/SessionConsoleProcess.cpp
src/cpp/session/SessionMain.cpp
src/cpp/session/modules/build/SessionBuild.cpp

Follow up to #11040, addresses #11276 
This sets `RSTUDIO_SESSION_PID` once, and makes sure it's not restored. This way we have a match in the console between `RSTUDIO_SESSION_PID` and `Sys.getpid()`. 

set `RSTUDIO_SESSION_PID` once, don't restore it

---

src/cpp/session/modules/SessionCodeSearch.cpp
src/cpp/session/resources/schema/user-prefs-schema.json
src/cpp/shared_core/FilePath.cpp
src/cpp/tests/testthat/test-files.R
src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java

addresses #11269
Add the `.lintr` extension to those that are always visible, mark `*.lintr` files as text files. 

Always show .lintr files

---

src/cpp/core/CMakeLists.txt
src/cpp/core/StringUtils.cpp
src/cpp/core/include/core/StringUtils.hpp
src/cpp/session/SessionMain.cpp
src/cpp/session/modules/SessionPath.cpp
src/cpp/session/modules/SessionThemes.cpp
src/cpp/shared_core/CMakeLists.txt

Speculatively addresses https://github.com/rstudio/rstudio/issues/11176. Unfortunately, I don't know the cause of the issue, but my guess is that the issue lies either in how we're lexically casting the associated string to a boolean, or in how regex matching is being done.
- Avoid using `boost::lexical_cast<>`; instead, check the possible set of valid values directly (via newly-added helpers).
- Avoid using temporary `boost::regex` objects. It's not clear this is actually an issue, but almost all examples I've seen online ensure the `boost::regex` pattern is constructed before it is used for searches / matches. (For example; https://github.com/boostorg/regex/tree/develop/example/snippets)
N/A; speculative fix.
Will need to rely on user testing.

tweaks for parsing rs-theme-is-dark field for themes

---

src/cpp/core/system/ProcessTests.cpp

This test is intermittently failing so allowing either exit code.

allow either 143 or 1 for process exit code for sigterm test

---

src/cpp/session/projects/SessionProjectContext.cpp

addresses #11284 
Adding `/` at the end of ignored `/.git/` so that `/.github` is not ignored by file monitor. 
e.g. in dplyr: 

ignore `/.git/` instead of `/.git`

---

src/cpp/tests/testthat/test-rsconnect.R

Follow up to changes in 39de73fd61812d and #11201.
If quarto has been disabled (due to OS) we don't want to run this test because it will fail, and doesn't make sense.

If Quarto has been disabled, then disable the quarto test

---

src/cpp/core/r_util/RToolsInfo.cpp
src/cpp/session/modules/build/SessionInstallRtools.cpp

Addresses #10361 
Since we are not expecting a stable CRAN url, one option is to extract the installer url from the Rtools 42 landing page. 
We can do this in `SessionInstallRtools` using a regex to parse the HTML

Get Cran URL for Rtools 42 windows installer

---

dependencies/osx/install-qt-macos

We've been using Qt 5.12.10 for our Mac Desktop releases for the past couple of releases. On other platforms we still use 5.12.8.
The dependency-installer script for Mac (only used on dev machines) was still looking for 5.12.8.
Bump script to look for 5.12.10.
N/A
Dev machine only thing.

use Qt 5.12.10 on MacOS

---

src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java

Addresses #11272 - additional message/button shown in Global Options / Code / Editing when there is a project open is making the pane contents too tall for some browsers.
When a project is open, hide the "General" section title to regain some vertical space and reduce likelyhood of the pane not fitting in the available space. The "General" title will still be shown when there is no project.
Original:
With this change:
When there is no project open:
N/A
Verify that when a project is open, the General title gets hidden as seen in screenshots above.

hide Code / Editing / General (options) section title when project is open

---

src/node/desktop/src/ui/widgets/choose-r/load.ts

Added ESC and Enter key recognition for Choose R window
Detected those key presses for that window.
None
Refer to #11098. Also, on QT RStudio, when the user presses `enter` when having the `Browse` button highlighted, the browse dialog would open instead of using the current selection. Also, when pressing `ESC` with the browse dialog open, the `Choose R Window` would not close, only the browse dialog.
Addresses #11098

Added ESC and Enter key recognition for Choose R window - Electron

---

src/node/desktop/src/core/file-path.ts
src/node/desktop/test/unit/core/file-path.test.ts

Fix an issue that would occur when trying to select a R Executable that was located on an unmounted Network Drive.
Previously, we were not enabling paths with duplicated slashes. By removing that and enabling users to have double slashes ( Ex: `\\TOWER\downloads\R-3.6.3\bin\x64\R.exe`), this issue was solved.
Added a few other tests case scenarios for normalizing paths.
Refer to #11247 
Addresses #11247

Fix issue when selecting a R Executable from a Network Path - Electron

---

src/gwt/src/org/rstudio/studio/client/common/satellite/Satellite.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindow.java

Addresses #10906
On Electron, when we close the satellite window the `unload` event isn't received, and we were relying on this to close the editor(s) in a satellite window when it closed. MDN does say the unload event is unreliable and recommends against using it and that appears to be a valid warning for Electron.
On Electron, directly invoke `notifyRStudioSatelliteClosed()` instead of doing it in response to the unload event.
None
In addition to the basic scenario outlined in the issue, also spot-check that that if you try to close a window containing modified (unsaved) buffers, you get prompted to save, etc.

close editors when satellite window closed (Electron)

---

package/osx/cmake/codesign-package-electron.cmake
package/osx/entitlements-electron.plist

Addresses #11309
Quarto uses WebAssembly for which Electron requires an entitlement that we were removing when we did package builds.
Copied the existing `entitlements.plist` to `entitlements-electron.plist`, added `com.apple.security.cs.allow-jit entitlement`, and tweaked script to use it for Electron build. I didn't want to mess with Qt entitlements.
None
This is Mac / M1 specific. See issue for repro steps.

Fix Electron renderer crash on macOS during Quarto editing

---

src/cpp/core/r_util/RProjectFile.cpp

follow up on #10432
the `PackageCleanBeforeInstall` only get added to the Rproj file if it's "No". This way when we open old project, the setting is silently set to "Yes" and the file is not modified. 
cc @hadley 
Tested with `multidplyr`. 

only have `PackageCleanBeforeInstall` in `.Rproj` if it's "No"

---

src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/ui/modal-dialog.ts
src/node/desktop/src/ui/widgets/choose-r.ts

Disable interaction with window behind Choose R Modal
Setting the main window as Choose R Modal parent Window.
None
Refer to #11097 
Addresses #11097

Disable interaction with window behind Choose R Modal

---

src/node/desktop/src/main/menu-callback.ts

Add Window Menu on OSX for Electron
Added Electron native Window Menu before the Help menu
None
Refer to #11238
Addresses #11238

Added Window Menu on OSX for Electron

---

src/cpp/server_core/ServerDatabase.cpp

When the sqlite database is created, it's set to RW for the owning user
only to prevent access from users
addresses rstudio/rstudio-pro#2692
No pro specific PR required
close up a security issue by ensuring the sqlite database files are only read/writable by the owning user
After the server creates the rstudio.sqlite file, we now manually change the file mode to 600
No automated testing added, trivial to manually test and exceptionally low probability of unintentionally breaking in the future.
From an rstudio session, execute
```
library(connections)
library(RSQLite)
con <- connection_open(SQLite(), "/var/lib/rstudio-server/rstudio-os.sqlite")
```
You'll be greeted by 
```
Error: Could not connect to database:
unable to open database file
```
and no new connection will be added to the …

Ensure that sqlite database RW for user only

---

src/cpp/session/SessionOptionsOverlay.cpp
src/cpp/session/include/session/SessionOptions.hpp
src/cpp/session/projects/SessionProjects.cpp

Currently desktop users are getting files username-d.ctx created due to this file being added for project sharing when there's no sessionScope(). 
Requires a companion commit to implement supportsProjectSharing() that will look like:
```
bool Options::supportsProjectSharing() const
{
return projectSharingEnabled() && programMode() == kSessionProgramModeServer;
}```
Although we have options().projectSharingEnabled() it's used all over
the place and is true even for desktop/server so I'm reluctant to change it
to return false for OS.
Instead I'm adding a new supportProjectSharing() that will only be true
when projectSharingEnabled() is true and the environment supports sharing.
None required.  
Just need to verify that the username-d.ctx file is only created in …

Don't create user-d.ctx file unless project sharing is enabled

---

Jenkinsfile.macos
Jenkinsfile.macos.electron

Mac Unit tests have been failing with messages like these:
```
[2022-06-03T16:36:06.111Z] ==> Running 'core' tests
[2022-06-03T16:36:06.111Z] dyld[79930]: terminating because inserted dylib '/Users/user193109/homebrew/x86_64/Cellar/r/4.1.0/lib/R/lib/libR.dylib' could not be loaded: tried: '/Users/user193109/homebrew/x86_64/Cellar/r/4.1.0/lib/R/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no such file)
[2022-06-03T16:36:06.111Z] dyld[79930]: tried: '/Users/user193109/homebrew/x86_64/Cellar/r/4.1.0/lib/R/lib/libR.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libR.dylib' (no such file), '/usr/lib/libR.dylib' (no …
```

run mac unit tests in x64 terminal

---

NEWS.md
src/cpp/r/R/Tools.R
src/cpp/session/SessionClientInit.cpp
src/cpp/session/modules/SessionPlots.cpp
src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java
src/gwt/src/org/rstudio/studio/client/workbench/views/plots/model/PlotsServerOperations.java
src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/export/SavePlotAsPdfDialog.java

Addresses https://github.com/rstudio/rstudio/issues/1905.
Rather than reading and caching the R temporary directory when the client connects, use an RPC to read the current temporary directory value (as that could change over the lifetime of the session).
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/1905.

fix issue when previewing plot after session restart

---

src/cpp/core/system/ProcessTests.cpp

Addresses #11351
All our build images (dockerfiles) install `python3`, so use that instead of the increasingly obsolete (or absent in the case of latest macOS) `python`.
This is to fix automated tests on dev machines.
No product code changes, just test code.

using python3 in unit test

---

src/cpp/core/include/core/r_util/RActiveSessions.hpp

Fixes crash on Desktop and rworkspaces - both of which attempt to
get properties from an empty session, expecting to return nothing back.
I don't think the empty() test in validate() is strictly necessary as the only places we call it we already have called empty() but maybe this will save us from another confusing crash in the future :)

Don't deref storage_ for empty sessions since it's not set

---

docker/jenkins/Dockerfile.bionic-amd64
docker/jenkins/Dockerfile.centos7-x86_64
docker/jenkins/Dockerfile.fedora36-x86_64
docker/jenkins/Dockerfile.jammy-amd64
docker/jenkins/Dockerfile.opensuse15-x86_64
docker/jenkins/Dockerfile.rhel8-x86_64

Address #10920  for linux platforms
Cache bust the docker layer by checking the Quarto release. The layer never changes because the install script doesn't change. This queries the GH API to get the Quarto release list and adds it as a file to the docker image. If the file contents has changed then there has been a new Quarto release. The file changing invalidates future layers and will run the Quarto install script.
This will likely be temporary until the final Quarto release. Then it will go back to the old way with specifying a specific version. At that time, it's probably best to add an argument to the Dockerfile and specify the Quarto version there.
None
Tested locally with a test Dockerfile. The `ADD` is cached if the release list hasn't changed. When it changes, the subsequent …

Force install quarto from latest

---

src/cpp/core/r_util/RActiveSessions.cpp

We might later want to fix this to support either format and
create new sessions with the new format.  This might break the database tests until we resolve this discrepancy 
Get the daily builds working again
Clients expect the lastUsed() method to return a number so if we store in iso time, we need to convert to iso time and support the old format for compatibility

Use old millis-since-epoch time format in properites files

---

src/cpp/session/SessionOptions.cpp
src/cpp/session/SessionOptionsOverlay.cpp

SessionOptionsOverlay.cpp isn't included in the pro-desktop build, I assume for a good reason. Need to resort to the #ifdef approach for this one. I'm going to merge this to get the build working but happy to fix it another way later.

Fix pro desktop build

---

src/node/desktop/src/renderer/desktop-bridge.ts
src/node/desktop/tsconfig.json

Files were failing to open from Windows Explorer, giving an error message and leaving the editor region blank.
Addresses #11369. Originally logged as part of #11251 but pulled into a separate (smaller) issue for targeted fix.
Reimplement this bit of code from the Qt implementation:
https://github.com/rstudio/rstudio/blob/df26d2643ffecc0b1f4b5c8e99bb6dc1a81d30a8/src/cpp/desktop/DesktopMainWindow.cpp#L570-L572
Uses the JavaScript `replaceAll` method new to ES2021. Electron/Chromium supports it but did need to bump up the target in tsconfig from es2020 to es2021 to avoid warnings.
None
Fix is specific to Windows-formatted paths (backslashes instead of forward slashes).

Fix path encoding when opening files on Windows (Electron)

---

src/cpp/core/system/LinuxResources.cpp

Address #11235 
Change the log level to info
None
A fresh install of Ubuntu 22 would previously show a warning about no memory cgroup when logging in to rserver. This is caused by Ubuntu 22 incorporating cgroup v2, which organizes the cgroup differently.

Change no mem cgroup message to info

---

src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/renderer/desktop-bridge.ts

The `devicePixelRatio()` gwt callback is never used. It isn't even exposed on the GWT side.
Presumably a remnant of ye olde days; the code now uses the `devicePixelRatio` property from the window object here:
https://github.com/rstudio/rstudio/blob/8272ed629be0d542352c3308e4f6f5ed8e21448a/src/gwt/src/org/rstudio/core/client/BrowseCap.java#L197-L210
Deleted the partially implemented Electron callback. I didn't bother deleting the Qt implementation, though it is also unused.
For historical purposes, the Qt implementation returned 1.0 for Windows and Linux, and for Mac did this:
```
NSWindow* pWindow = nsWindowForMainWindow(pMainWindow);
if ([pWindow respondsToSelector:@selector(backingScaleFactor)])
{
return [pWindow backingScaleFactor];
}
```
N/A
Dead code removal, nothing to specifically …

delete unused devicePixelRatio gwt callback

---

src/cpp/desktop/DesktopGwtCallback.cpp
src/cpp/desktop/DesktopGwtCallback.hpp
src/cpp/desktop/DesktopUtils.hpp
src/cpp/desktop/DesktopUtilsMac.mm
src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/renderer/desktop-bridge.ts

- removed from Qt and Electron
- also removed underpinnings of the unused devicePixelRatio callback

remove unused closeNamedWindow GWT callback

---

src/cpp/generate-options.R
src/cpp/server/include/server/ServerOptions.gen.hpp
src/cpp/session/SessionOptions.cpp
src/cpp/session/include/session/SessionOptions.gen.hpp
src/cpp/session/include/session/SessionOptions.hpp

Addresses https://github.com/rstudio/rstudio-pro/issues/3509.
Restores the options overlay pattern originally introduced in https://github.com/rstudio/rstudio/commit/707d5c29680970f1b0259ea9ae15a69f0a8ddc65, but inadvertently removed in https://github.com/rstudio/rstudio/commit/a9bb34c8c75302ad7a378129ce8dab27ee92a5cd. 
Also adds some explicit warnings at startup when the overlay changes option values; in previous versions these changes occurred silently. 
N/A, except for logging improvements this only touches a code generator (and resultant output)
- Test both open source and Pro versions with this change; i.e. that these options are both correctly ignored (with a warning) in open source, and correctly respected in Pro
- A comprehensive list of affected options can be found in the …

Restore option allow-overlay pattern

---

dependencies/common/install-quarto
dependencies/windows/install-quarto/get-quarto-version.ps1
docker/jenkins/Dockerfile.bionic-amd64
docker/jenkins/Dockerfile.centos7-x86_64
docker/jenkins/Dockerfile.fedora36-x86_64
docker/jenkins/Dockerfile.jammy-amd64
docker/jenkins/Dockerfile.opensuse15-x86_64
docker/jenkins/Dockerfile.rhel8-x86_64

Too many builds run concurrently for all the platforms which causes the build agents to exceed the GitHub API limit. This fixes the issue in case too many builds start within an hour.
Uses the download metadata from quarto.org instead of GitHub to check which release to use for the build. This changes the Dockerfiles for Linux and the installer scripts for Linux/Mac/Windows. Mac and Windows always run the dependency install.
None
None

Fix build time quarto version check

---

src/cpp/session/projects/SessionProjects.cpp

Fixes a bug the cloud team found with `server-multiple-sessions=0` and project sharing (a feature just added in this release)
* Need to create the project id with the path chosen above as the active session's project (session.project() is not set until later)
* Need to use createAliasedPath() so that ~/ is managed consistently
or you can have two different project ids for the same path

Fix bug with single-session mode and project sharing

---

src/gwt/src/org/rstudio/core/client/hyperlink/Hyperlink.java
src/gwt/src/org/rstudio/core/client/hyperlink/HyperlinkPopupPanel.java
src/gwt/src/org/rstudio/core/client/hyperlink/RunHyperlink.java

Follow up for #11273
Instead of having the popup disappear on mouse out, hide it on: 
- mouse down anywhere else
- escape
But making sure there is only one hyperlink popup showing at a time. 
In addition, pressing F1 on `:run:` hyperlink will show the help page. 

More hyperlink tweaks

---

src/cpp/core/include/core/http/AsyncClient.hpp
src/cpp/core/include/core/http/LocalStreamAsyncClient.hpp
src/cpp/core/include/core/http/SocketUtils.hpp
src/cpp/core/include/core/http/TcpIpAsyncClient.hpp
src/cpp/core/include/core/http/TcpIpAsyncClientSsl.hpp

Fixes https://github.com/rstudio/rstudio-pro/issues/3454
Also hides "ssl short read" errors by default, that I've seen a lot in customer logs that are using SSL servers. Those happen when the browser closes the connection mid-stream, as happens pretty regularly in our streaming connections. 
Our errors get handled in the abstract base class so I added a method in each subclass to modify the error with details. 
Not necessary
Aside from our existing automation, I don't think this needs additional testing but you can easily see these errors by mis-configuring one of the many ports or addresses in our configuration. For local streams, you should see the stream-path that helps identify the server. For Tcp, you see the address/port of the server in the connection. For both, you see the uri …

Provide connection address/port, uri, stream file in connection error

---

src/cpp/core/r_util/RActiveSessionsStorage.cpp
src/cpp/r/RJson.cpp
src/cpp/server/session/ServerSessionMetadataRpc.cpp

- size_t != uint64_t (it seems?) so add some explicit cases
- warning for comparing int against uint (remove the "max test" because a sized int can never be larger than umax int)
- don't use readObject directly with size_t as it leads to an undefined method

Fixed 2 compile errors and one warning on Mac OS build

---

src/cpp/core/include/core/r_util/RActiveSessions.hpp
src/cpp/core/include/core/r_util/RActiveSessionsStorage.hpp
src/cpp/core/r_util/RActiveSessionsStorage.cpp
src/cpp/server/DBActiveSessionsStorage.cpp
src/cpp/server/include/server/DBActiveSessionsStorage.hpp

The last part of [Pro #3094](https://github.com/rstudio/rstudio-pro/issues/3094) - migrating file based session to the database.
When we list sessions, migrate if we haven't already. Best effort only, don't do it twice.
There are none at the moment, this would be difficult to automate due to the config change requirement.
We should start some session in the old way and then set `session-use-file-storage=0` and see that there are no errors in the logs and things still work (in pro as especially).

Migrate file sessions to DB

---

package/osx/entitlements-electron.plist
package/osx/entitlements.plist
src/node/desktop/resources/electron-entitlements.mac.plist

We can't use `lldb` on RStudio's `rsession` process currently, because it does not have the `get-task-allow` entitlement. The original R executable has this entitlement now, since R 4.2.0. More info on that here: https://stat.ethz.ch/pipermail/r-sig-mac/2022-April/014377.html
It would be great to add this entitlement to `rsession` and `rsession-arm64` as well, so we can debug compiled code in RStudio.
Straightforward, mostly. It seems that currently all executables are signed with …

Allow lldb debugging of compiled code in R and R packages

---

src/cpp/session/modules/SessionFind.cpp

Addresses #11348 part 1 -- prevent RStudio crashes
So it turns out that system grep doesn't actually crash when you search for `()` or `[]` or other bad regexes, even though it doesn't really match any content. We give our Find in Files an escape hatch, where if the grep command has completed without error and returns actual output, but the matchOn/matchOff array is empty (this doesn't happen with true no results, where grep stdout is empty) we skip ahead to the next match. 
Essentially this gives us (No results found) when searching for regexes like `()`, but appropriate results when searching for `\(\)`. True no matches (ie searching for `shdjshfdsjgfsjkd`) continue to behave as usual, since the grep onStdOut callback is not triggered when grep finds no matches.
This is because grep …

Prevent crashes with malformed regex which match all lines of content

---

src/cpp/session/SessionMain.cpp

Addresses the remaining aspect of: https://github.com/rstudio/rstudio-pro/issues/2641
Should I log PATH for windows?
We already have debug logs beginning the R session, before and after resuming the session, and when
listening. This adds a message right when the session starts (after logging has been initialized), and prints the dyn library path value for linux and mac.
None required
Enable debug logging and hopefully get improved timing info on session start.

Add 'starting' debug log right after log is initialized

---

src/gwt/src/org/rstudio/core/client/hyperlink/hyperlinkStyles.css

making the link inside the popup for `ide:(help|run)` links unclickable and same style as the rest of the text. 

fix styles for hyperlink help preview popup

---

src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanel.css
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanel.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanelResources.java

addresses #7839
add a Label for the title, in bold: 
Also rendered the links unclickable and same color as the rest, because they were not linking to the correct location anyway. 

add title label to help info popup

---

src/cpp/server/DBActiveSessionsStorage.cpp

Fix a bug @astayleraz and I just found while over-viewing the session metadata feature.
Actually return the count variable.
Our tests will run against the sessions that use this call.
`.rs.invokeServerRpc` with `operation = "count"` should return a non-zero value.

Fix bug with counting sessions

---

src/cpp/core/Database.cpp
src/cpp/core/include/core/Database.hpp
src/cpp/core/include/core/r_util/RActiveSessions.hpp
src/cpp/core/r_util/RActiveSessionStorage.cpp
src/cpp/core/r_util/RActiveSessions.cpp
src/cpp/server/DBActiveSessionStorage.cpp
src/cpp/server/session/ServerSessionMetadataRpc.cpp

No pressure to review this weekend :)   I may merge this myself in a bit so I can flush out build problems, and do more testing on the official build. 
Addresses: https://github.com/rstudio/rstudio-pro/issues/3566
- don't ensureDirectory for scratch path in ActiveSession since that code runs on the server scratchPath is not accessible. This is already done by the File storage implementation when it's required and so is not necessary here.
- Similarly don't check for scratchPath existing in ActiveSession::validate since that check is in file storage.isValid called by empty()
- Similarly for ActiveSessions and rootStoragePath
- fixes for editor/workbench renaming, consistently map and unmap columnName/propertyName for each property in the list
- diagnostics for destroySession when row does …

Fixes a few db/rpc session problems found in testing

---

src/cpp/server/session/ServerSessionManager.cpp
src/cpp/session/SessionMain.cpp

Initialize the socket rpc before the session scope is initialized
in the options so the initial "validate" works.
We pass the server's rpc secret key to the session already for OS/Server but we don't for non-launcher sessions.

For non-launcher sessions, need to pass the server rpc key

---

package/linux/CMakeLists.txt

AppArmor functionality was removed in e939585a19e9d98722328a0bac82619b0750aa3b as part of the work to create Launcher (in 2018), but it looks like the Debian package dependency on `libapparmor` was never removed. I noticed this while trying to reconstruct what dependencies the session components have from the main Debian package's metadata.
I do not know what existing tests cover packaging-related changes. But since this is a system library dependency, probably "the binary starts on a Debian-based distro" should be sufficient.
Unknown, please advise.

Remove the unused libapparmor1 dependency for Debian-based distros

---

src/cpp/core/include/core/r_util/RActiveSessions.hpp
src/cpp/core/r_util/RActiveSessions.cpp
src/cpp/server/session/ServerSessionMetadataRpc.cpp
src/cpp/session/SessionModuleContext.cpp

** Note - requires a companion commit in pro to add the new validate
parameter to list() in a few places. Let me do the merge so I can coordinate.
Addresses: https://github.com/rstudio/rstudio/issues/11446
Add a new 'validate' param to list that is passed as 'false' in `rserver` so it doesn't try to remove the session if it can't validate it. Also should be passing homePath, not userDataDir to list in that case so fixed the code but it won't matter since we don't use that parameter when validate=false.  These are the safe parts of the fix.
I also changed the code so that when initializing an rsession without a specific session id (i.e. non-multiple sessions case in the pro or OS), if there is more than one active session, use the most recent one
rather than creating a new one each time. …

Fix problems with list() method and single-session mode resume

---

package/linux/CMakeLists.txt

An explicit dependency on `libedit2` was originally added in 2e7e7ab03c797f39d64097090ca3cc4fe8e710f8 to support the bundled libclang (since libedit is a dependency of LLVM). However, since 543edee3924e843fdad936e2d19e7c2efe088d38 we depend on the system `libclang-dev` on Debian-based distros, which appears to have been part of the move away from using the bundled libclang on Linux (#2892).
Since `libedit2` is a dependency of `libclang-dev` on all supported Debian-based distros, we can safely remove this explicit dependency.
To verify that `libedit2` is a transitive dependency of `libclang-dev`, you can check the following:
$ apt-cache depends --installed --recurse -i libclang-dev | \
grep 'Depends: libedit2'
(I also checked this against Debian's online package search for older versions …

Remove the redundant libedit2 dependency for Debian packages

---

src/cpp/core/include/core/libclang/LibClang.hpp
src/cpp/core/libclang/LibClang.cpp
src/cpp/session/modules/clang/SessionClang.cpp
src/cpp/session/modules/clang/SessionClang.hpp

Addresses https://github.com/rstudio/rstudio/issues/11452.
Disentangles the relationship between the embedded version of libclang (relevant only on Windows), and the minimum-supported version of libclang (relevant everywhere).
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/11452. You might also be able to reproduce this issue on older versions of Ubuntu (where the versions of LLVM / libclang provided by the package manager would be older).

avoid conflating minimum-supported libclang version with embedded version

---

src/cpp/desktop/DesktopSessionLauncher.cpp

Addresses https://github.com/rstudio/rstudio/issues/9543.
Don't set `DYLD_INSERT_LIBRARIES` if we're running `rsession` through `/usr/bin/arch`, as doing so tries to force macOS to load the R library into _the /usr/bin/arch process_, rather than the `rsession` process! I still don't quite understand why this only fails sometimes, but I'm pretty confident this is the underlying issue (as I was finally able to reproduce locally).
N/A
Test that RStudio can run with both x86_64 and arm64 R installations on M1 macOS machines.

only set DYLD_INSERT_LIBRARIES if running rsession directly

---

NEWS.md
src/gwt/panmirror/src/editor/src/api/node.ts

Address #11410
Sets the option to descend into child nodes to find R chunks.
None
This only occurs in visual mode. The code chunk can be named or unnamed.

Fix showing nested R chunks in document outline

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java

adresses #11123, #10077, #11124
- add `rawstring` in `if (state == "qstring" || state == "qqstring" || state == "rawstring")`
- better handle the situation where end of row is a multiline string, but there is something else before

Fixes with multi line statement in `Cmd` + `Enter`

---

src/cpp/session/modules/SessionCodeTools.R

`get_args()` rpc recognize the `<pkg>::<fun>` notation. 
This e.g. extracts the right formals when hovering in the editor: 
instead of the `(...)` fallback: 

get_args() rpc extract src from the <pkg>::<fun> notation

---

NEWS.md
src/cpp/session/modules/rmarkdown/NotebookQueue.cpp
src/cpp/session/modules/rmarkdown/NotebookQueueUnit.cpp
src/cpp/session/modules/rmarkdown/NotebookQueueUnit.hpp
src/gwt/src/org/rstudio/core/client/JsVector.java
src/gwt/src/org/rstudio/core/client/JsVectorBoolean.java
src/gwt/src/org/rstudio/core/client/JsVectorInteger.java
src/gwt/src/org/rstudio/core/client/JsVectorNumber.java
src/gwt/src/org/rstudio/core/client/JsVectorString.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/NotebookQueueState.java

Addresses https://github.com/rstudio/rstudio/issues/10632.
Use UTF-8 strings on the server side, and compute execution ranges are UTF-8 byte offsets on the client side. Use the `TextEncoder` helper class to convert text in the editor document to a UTF-8 byte array, and compute offsets from that array size.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/10632.

use UTF-8 byte offsets for code execution

---

src/node/desktop/src/assets/locales/en.json
src/node/desktop/src/assets/locales/fr.json
src/node/desktop/src/main/application.ts

Added the `New RStudio Window` button for when clicking with the right button over the Dock Icon as it used to happen in QT version.
Created and added that menu.
None
Refer to #11387
Addresses #11387

New RStudio Window Button on Dock for OSX Electron

---

src/gwt/src/org/rstudio/core/client/WordWrap.java

addresses #5886
after wrapping a long line with `processLine()`, finish with `appendRawWithIndent()` only if there is more content to append. Otherwise this leaves a superfluous empty line with the indent string. 

Reflow not adding superfluous new lines  after wrapping

---

src/cpp/core/include/core/rapidxml/rapidxml.hpp
src/cpp/core/markdown/sundown/markdown.h
src/cpp/core/r_util/RActiveSessionStorage.cpp
src/cpp/server/DBActiveSessionStorageTests.cpp
src/cpp/server/DBActiveSessionsStorage.cpp
src/cpp/server/ServerDatabaseMigrationTests.cpp
src/cpp/server/auth/ServerAuthCommon.cpp
src/cpp/server/auth/ServerSecureUriHandler.cpp
src/cpp/server/db/CreateTables.postgresql
src/cpp/server/db/CreateTables.sqlite
src/cpp/session/modules/SessionRParser.cpp
src/cpp/shared_core/json/JsonTests.cpp
src/cpp/tests/testthat/themes/tmThemes/Brilliance Black.tmTheme
src/cpp/tests/testthat/themes/tmThemes/Brilliance Dull.tmTheme
src/node/desktop/src/main/i18n-manager.ts
src/node/desktop/src/main/preferences/mac-preferences.ts

Fixes various typos found via `codespell -q 3 -S *_fr.properties,./src/gwt -L ba,enque,optionel,ot,parm,parms,pres,prevend,pevent,pevents,ptd,texline`
n/a
n/a

Fix typos in various subdirs within src/

---

src/node/desktop/src/renderer/desktop-bridge.ts

Address #11515 - File cannot be saved on Windows
In dev, `process.env.HOME` returns the user's home path. In a build, it returns `undefined`. The error is caused by normalizing the home path.
There was another bug uncovered as well where we are assuming the save path is somewhere in the user's home. So this only performs the home alias replacement if the save path starts with the home path. It is a similar check as the CPP code.
None
This only affected Windows but would be good to test the change on Linux or Mac (tested in dev on Mac and Windows). A network path is likely the use case where a user would save outside of their home directory.

Fix path normalization when saving file

---

src/gwt/acesupport/acemode/cpp_code_model.js
src/gwt/test/autoindent_test_cpp.html

addresses #8417
Tweak the rules so that modifiers on their own line (e.g. `static`) don't cause indent. 
Added some tests in `autoindent_test_cpp.html`

No indent in C++ mode for `static` and `inline`

---

src/node/desktop/src/main/gwt-callback.ts

check for the primary display's dpi, which is used on windows only to determine if display is high dpi
using electron primary display's scaling factor * 92. scaling factor of 1 = 92 dpi
None
Needs to be tested on windows with high dpi display, not entirely clear how to test but could literally just check if `windows-highdpi` is added to the CSS (not sure what else to be looking for)

get dpi from primary display electron

---

NEWS.md
src/node/desktop/src/main/gwt-callback.ts

Addresses #11407
Originally, this was implemented for Windows only as it could set the window order. Electron doesn't have any kind of window ordering mechanism. So the workaround is focusing the main window and then back to the active one. This may cause a slight flicker on some platforms. I only noticed this on Windows and it didn't occur if the main window was already directly underneath the secondary window. Other Linux distros may differ depending on window managers but Ubuntu 22 seemed good.
None
This is new to Linux and Mac but existed before on Windows. It can be triggered by a few different commands:
* Test Package
* Check Package
* Build package documentation
* Run Shiny Application in New Pane
* Run Shiny Application in RStudio Viewer
* Run Shiny Application in Web Browser
* …

Allows background commands to surface the main window under the active one

---

src/cpp/core/system/Win32System.cpp
src/cpp/session/SessionMain.cpp

Addresses https://github.com/rstudio/rstudio/issues/11487.
On Windows, we use job objects to ensure that child processes are cleaned up when a parent process exits. However, node creates processes with `JOB_OBJECT_LIMIT_SILENT_BREAKAWAY_OK`, which effectively prevents new processes from being added to an existing job object.
This PR resolves the issue by allowing the R session to create its own job object, so that the lifetime of child processes created by the session is limited by the lifetime of the session itself.
Some open questions...
- Is there a way for us to pass the desktop's job object handle down to the session, when it is initialized? Is this worth doing?
- Can we convince ourselves that node will appropriately kill the session process if the desktop process dies in this case? …

let session create its own job object

---

src/gwt/CMakeLists.txt

The issue was introduced in #10446. In particular, this glob https://github.com/rstudio/rstudio/blob/203675a9f3e21db36cf224b7dc1c5c056e0b067b/src/gwt/CMakeLists.txt#L74 makes cmake find glob mismatches at install time, and compilation of dependencies starts over.
This patch limits the glob to Java files, so mismatches don't happen anymore independently of other files that may have been generated there.
No tests added. With this change, compilation runs once during the build stage, and no recompilation occurs during the install stage.
No issues expected.

Specify the extension when globbing

---

src/cpp/session/modules/SessionDataImport.R

Fixes #11510 
Fixes #11510, using the hints provided by @kevinushey
In R-4.2.0 `default.stringsAsFactors` was deprecated.  When importing data using `read.csv()` from `base`, check for `getRversion() >= '4.2.0' and use an approprate default.
None
To test, use any downloaded CSV file and import data using `read.csv()`

Remove stringsAsFactors default for R-4.2.0 and later when importing data

---

src/node/desktop/src/main/detect-r.ts

Addresses #11567 to at least mimic the old Qt desktop behavior for Macs
Qt desktop code took [1 approach for Mac](https://github.com/rstudio/rstudio/blob/8df7e8c7c6b7727779786613a9089ba14e0c4a68/src/cpp/core/r_util/REnvironmentPosix.cpp#L106-L147) and a[ different approach for Linux](https://github.com/rstudio/rstudio/blob/8df7e8c7c6b7727779786613a9089ba14e0c4a68/src/cpp/core/r_util/REnvironmentPosix.cpp#L203-L244) in terms of finding the right R executable. Electron code was essentially applying the Linux logic to both platforms, and then falling back to the Mac logic, leading to funny behavior on Mac. 
Overall, it would probably be ideal to launch a terminal process in the user's default shell to pick up any profile modifications to the RSTUDIO_WHICH_R and/or PATH variables, since we …

Copy behavior from Qt desktop for Mac -- check fallback list of R

---

src/node/desktop/src/main/application.ts
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/window-utils.ts

Address #11581
Implements a workaround to call Electron's `selectAll()` on the focused web view. I'm not sure what is overriding the Cmd+A but it eats the keyboard event. This seems to get around that and results in the same behaviour as Qt (even down to pressing Tab to focus on a button and it selects UI text). We could refine this behaviour by executing Javascript and querying the `document.activeElement` for the active element but this seems cleaner and easier to understand.
I've refactored the wrapper method on `getFocusedWebContents()` since it could be useful in other places.
None
Any text input field would have been affected by this bug. It should also work on editors that have been popped out to its own window.

Fix select all in text input fields

---

src/gwt/src/org/rstudio/core/client/dom/ElementEx.java
src/gwt/src/org/rstudio/studio/client/workbench/exportplot/clipboard/CopyPlotToClipboardDesktopDialog.java
src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/export/PlotsPanePreviewer.java
src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/export/DesktopExport.java

Fixes an issue where calls to `getClientLeft()` and `getClientTop()` would seemingly fail to resolve when using GWT devmode.
Rename the methods to `clientLeft()` / `clientTop()`.
N/A
N/A

avoid getClientLeft() / getClientTop()

---

NEWS-2021.09.4-ghost-orchid.md
src/cpp/core/Database.cpp
src/cpp/core/DatabaseTests.cpp

Now assumes that any unknown flower version is a later rather than prior
version
Add test coverage to ensure the comparisons are correct.
Addresses rstudio/rstudio-pro#3572
When a user downgrades the previous version was squashing the db schema, preventing later upgrades from being successful due to a mismatch between the actual schema and the reported schema of the database.
Previously unknown flower versions were assumed to be prior versions, unknown flowers are now presumed to be later versions
Automated test coverage added to assert the comparisons between the versions, and empty version, unknown version.
This specifically addresses a scenario in which an installation is downgraded, and then upgraded again.
Previously downgrading would cause the SchemaVersion of the DB to be updated. …

Change SchemaVersion Comparison Logic

---

src/cpp/core/Backtrace.cpp
src/cpp/core/CMakeLists.txt
src/cpp/core/config.h.in
src/cpp/core/r_util/RSessionContext.cpp

Folks trying to build RStudio on FreeBSD and Musl-based distributions like Alpine or Void Linux both encounter two assumptions that we make:
1. `group_member()` is available on non-macOS platforms. But `group_member()` is a Glibc extension, so this is not actually true.
2. `backtrace()` and `backtrace_symbols()` from `execinfo.h` are always provided by the system's libc. But they *happen* to be provided by Glibc and macOS's libc; on FreeBSD these are in a separate library, and Musl doesn't implement them at all.
Both of these can be fixed by adding more careful checks for these features in our CMake configuration. I've also found numerous other major projects that have near-identical CMake checks for these two features; it's clearly a common problem.
This commit also adds a fallback …

Check for group_member() and execinfo.h via CMake

---

src/node/desktop/src/main/gwt-callback.ts

There was an issue showing a minimized window when Jon tested this initially. #11407 
`show()` will raise and focus the window. The secondary window is then focused to bring it back to the top. I tried `showInactive()` which seems to imply that it will raise but not focus the window but it always focused the window for me on Mac.
None
None

Fix showing a minimized main window

---

NEWS.md
src/cpp/session/SessionClientInit.cpp
src/cpp/session/SessionConsoleProcess.cpp
src/cpp/session/modules/SessionPythonEnvironments.R
src/cpp/session/modules/SessionRSConnect.cpp
src/cpp/session/modules/SessionRUtil.R
src/cpp/session/modules/SessionReticulate.R
src/cpp/session/modules/SessionReticulate.cpp
src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
src/cpp/session/resources/terminal/hooks

Addresses #9990 by unreverting the original code, and adding additional code to `src/cpp/session/modules/SessionRUtil.R` and `src/cpp/session/modules/SessionReticulate.R` to avoid the issue of reticulate automatically being loaded into the user's namespace at startup, as detailed in #11566
- Update the .rs.executeFunctionInChildProcess() function to handle return values
- Use .rs.executeFunctionInChildProcess() in .rs.inferReticulatePython so we can run `reticulate::py_discover_config()` without loading reticulate + friends into the namespace
None
See both #9990 and #11566 for details

Reticulate -- revert revert changes to reticulate python fallback without preloading

---

NEWS.md
src/cpp/session/modules/SessionCodeTools.R

Addresses #11552 
Before calling `requireNamespace()` which loads the package, we check that packages are not already loading. Not sure if we want to specifically check that rmarkdown/yaml aren't already loading? But this appears to fix the error message, and the appropriate packages (e.g. rmarkdown, yaml, rlang) all get loaded into the namespace
None
R version shouldn't matter. rlang version for testing must be >= 1.03, as the issue only exists in very recent rlang releases. Must have at least 2 Rmd files open. Check that rmarkdown, yaml, and any packages references in the open Rmd files end up in `loadedNamespaces()` at project startup.

Don't reload rmarkdown/yaml if already loading

---

src/cpp/core/include/core/r_util/RActiveSessions.hpp

Added lastStateUpdated() and fixes createdTime() to return ptime version
Reviewed in: https://github.com/rstudio/rstudio-pro/pull/3649

Companion commit to session-state-updates

---

NEWS.md
src/gwt/src/org/rstudio/core/client/RegexUtil.java

> Fix the issue I raised regarding autocompletion (#11689).
> Fix up the regex that determines if backticks should be used or not.
> N/A
> I don't believe anything could go wrong but I don't really know how everything fits together.
----
Sorry I am new to this and got rid of your boiler plate text initially. But I think this is more informative than the above.
I don't know much about Java or pull requests or very much at all for that matter (I am but a humble R user) but one thing I do know is that RStudio auto-complete has a slight bug in it, so I thought I'd have a crack at fixing it.
In $ autocompletion, if I was to create the following list, say:
```r
x <- list("_0" = NA)
```
and then attempt to autocomplete with `x$`, I obtain this:
```
x$_0
#> Error: unexpected input in "x$_"
``` …

Fix $ autocompletion of underscores followed by a number

---

src/node/desktop/src/main/gwt-callback.ts

desktop_show_file callback doesn't have same behavior as behavior. Used to open the file in a default system viewer, now it just opens a finder/explorer window with the file in question highlighted. This is generally not helpful. Blocks #11392

consolidate callbacks, fix desktop_show_file logic

---

src/cpp/session/modules/viewer/SessionViewer.cpp
src/node/desktop/src/main/gwt-callback.ts

Addresses #11392 
follow up to #11705, can be merged first (this PR contains those changes as well)
Change supported file formats for viewer export to remove TIFF export option on Macs, keep BMP option for non Macs
Implement viewer callback in electron native image API

Viewer pane save as image - Electron

---

NOTICE
src/node/desktop/package-lock.json
src/node/desktop/package.json
src/node/desktop/src/main/app-state.ts
src/node/desktop/src/main/application.ts
src/node/desktop/src/main/args-manager.ts

Implement single instance logic when opening a file at startup.
Addresses part of #11251 
Before attempting to open a file at startup, request the instance lock. If obtained, the instance is the primary instance and should open the file. If not, it exits and the request would send an event to the primary instance that will open the file.
This brings in `net-ipc` to communicate locally among the instances using a Unix/Windows socket. This notifies other instances when the primary instance exits and allows one of the other instances to request the lock. It will then take over opening files that come from `Open With`.
If we do need more IPC events, this will provide everything that's necessary to communicate with the primary instance.
This may or may not fix it on Linux but I would expect it …

Electron instance handling with file open events

---

src/cpp/session/SessionConsoleInput.cpp
src/cpp/session/modules/rmarkdown/NotebookQueue.cpp
src/cpp/session/modules/rmarkdown/NotebookQueueUnit.cpp
src/cpp/session/modules/rmarkdown/NotebookQueueUnit.hpp

Addresses #11665. 
Instead of sending python chunks to the executor one line at a time, as we do with R chunks, send all lines at once. This will ensure the preprocessing that already happens for non markdown python code gets applied to python code in chunks, instead of applying the preprocessing one line at a time
Sends full function body to the console, and adds a newline to terminate the function definition
None
See issue

Fix python chunk execution with blank lines

---

src/cpp/core/system/Crypto.cpp
src/cpp/core/system/CryptoTests.cpp

On a system with OpenSSL 3, we see the following build warnings:
./rstudio/src/cpp/core/system/Crypto.cpp: In function ‘rstudio::core::Error rstudio::core::system::crypto::sha256(const string&, std::string*)’:
./rstudio/src/cpp/core/system/Crypto.cpp:120:25: warning: ‘int SHA256_Init(SHA256_CTX*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
120 |    int ret = SHA256_Init(&shaCtx);
|              ~~~~~~~~~~~^~~~~~~~~
In file included from /usr/include/openssl/x509.h:41,
from /usr/include/openssl/pem.h:23,
from ./rstudio/src/cpp/core/system/Crypto.cpp:32:
/usr/include/openssl/sha.h:73:27: note: declared here
73 | OSSL_DEPRECATEDIN_3_0 int SHA256_Init(SHA256_CTX *c);
|                           ^~~~~~~~~~~
./rstudio/src/cpp/core/system/Crypto.cpp:124:23: warning: ‘int …

Fix deprecation warnings for `SHA256_*` functions under OpenSSL 3

---

src/cpp/core/system/Crypto.cpp
src/cpp/core/system/CryptoTests.cpp

On a system with OpenSSL 3, APIs that use `RSA` pointers directly are all marked as deprecated, resulting in warnings like the following:
<details>
<summary>Compiler warnings</summary>
./rstudio/src/cpp/core/system/Crypto.cpp: In function ‘rstudio::core::Error rstudio::core::system::crypto::rsaSign(const string&, const string&, std::string*)’:
./rstudio/src/cpp/core/system/Crypto.cpp:141:35: warning: ‘void RSA_free(RSA*)’ is deprecated: Since OpenSSL 3.0 [-Wdeprecated-declarations]
141 |    std::unique_ptr<RSA, decltype(&RSA_free)> pRsa(PEM_read_bio_RSAPrivateKey(pKeyBuff.get(), nullptr, nullptr, nullptr),
|                                   ^~~~~~~~
In file included from /usr/include/openssl/x509.h:36,
from /usr/include/openssl/pem.h:23,
from ./rstudio/src/cpp/core/system/Crypto.cpp:32: …

Fix deprecation warnings for RSA sign/verify on OpenSSL 3

---

src/node/desktop/src/assets/locales/en.json
src/node/desktop/src/main/application.ts

Addresses #11438 
Current window 
If you click Yes, a tab opens in your default system browser which points to the R-project website to download/install R
If you click No, the dialog will exit, and RStudio will not start
(see linked issue for [old UI](https://user-images.githubusercontent.com/10569626/173932441-0d1b5f22-d784-4177-8305-7bdbc3448015.png). )
Test on a Windows machine with no R installation (or put R somewhere sneaky we can't find it)

Update window for no R installation found on Windows Electron

---

Jenkinsfile
Jenkinsfile.macos
dependencies/linux/install-qt-linux
dependencies/linux/install-qt-sdk
dependencies/osx/install-qt-macos
docker/jenkins/Dockerfile.bionic-amd64
docker/jenkins/Dockerfile.centos7-x86_64
docker/jenkins/Dockerfile.fedora36-x86_64
docker/jenkins/Dockerfile.jammy-amd64
docker/jenkins/Dockerfile.opensuse15-x86_64
docker/jenkins/Dockerfile.rhel8-x86_64
docker/jenkins/Dockerfile.windows

Open-source side of addressing https://github.com/rstudio/rstudio-pro/issues/3701.
Puts back installation of Qt SDK on build machines. This is groundwork to re-enable building the Qt flavor of Desktop Pro. There should be no impact on the open-source builds (other than the docker images rebuilding to pull in Qt).
I considered adding conditional logic so open-source docker images would skip installing Qt, but decided that's not worth the complexity.
N/A
Nothing should change as a result of this PR. Once this gets merged into pro repo, then I'll do additional work there to finish the task.

Put back Qt dependency installer goo

---

dependencies/windows/install-soci/install-soci.R
dependencies/windows/tools.R
src/cpp/r/session/REmbeddedWin32.cpp
src/cpp/session/modules/SessionRUtil.R
src/cpp/session/modules/SessionRUtil.cpp
src/cpp/shared_core/system/Win32User.cpp

Addresses https://github.com/rstudio/rstudio/issues/11721.
May also address https://github.com/rstudio/rstudio/issues/11717.
When using the UCRT runtime, environment variables are expected to be encoded as UTF-8, so don't try to convert from UTF-8 to the system encoding here.
N/A
Test that, when using RStudio + R 4.2.x on Windows, no warnings are printed to the console on startup.

keep user home / rhome as UTF-8 with R 4.2.x

---

src/cpp/session/modules/SessionRUtil.R

Addresses https://github.com/rstudio/rstudio/issues/11766.
When running code within an R sub-process, ensure that any output is written to `output.rds` at the expected location.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/11766.

ensure 'output.rds' written to expected location

---

Jenkinsfile
docker/docker-compile.sh
docker/jenkins/Dockerfile.bionic
docker/jenkins/Dockerfile.centos7
docker/jenkins/Dockerfile.fedora36
docker/jenkins/Dockerfile.jammy
docker/jenkins/Dockerfile.opensuse15
docker/jenkins/Dockerfile.rhel8
docker/jenkins/Dockerfile.rhel9
docker/jenkins/publish-build.ps1
docker/jenkins/publish-build.sh
src/cpp/rstudio-tests.in

Adds arm64 builds of RStudio and RStudio Server. Also, replaces Fedora 36 with Rocky Linux 9 since I was in the Dockerfile anyway. 
Addresses https://github.com/rstudio/rstudio/issues/11758
Addresses (most of) https://github.com/rstudio/rstudio/issues/8809
- Parameterize all our Dockerfiles with an `ARCH` build argument so that they are switchable between architectures.
- Update dev docker compilation scripts so they can be used to build against either architecture
- Update `Jenkinsfile` to add RStudio and RStudio Server builds for arm64 on the two most modern distributions: Ubuntu 22 (Jammy) and RedHat Linux 9. Tried to extend support further back, but had a rough go of it with dependencies. If demand is high we might consider adding an Ubuntu 20 (Focal) build since Ubuntu 18 (Bionic) …

Add arm64 builds of RStudio Server

---

docker/jenkins/Dockerfile.rhel9

rhel9 builds are currently failing due to a bug in Rocky Linux 9's `file` utility. 
Work around the bug by creating a wrapper script in `/usr/local/bin` that wraps `file` in most cases, but assumes all `.wasm` files to be WebAssembly. 
N/A, build fix
N/A, build fix

Fix rhel9 builds

---

src/cpp/session/SessionMain.cpp

Addresses: https://github.com/rstudio/rstudio/issues/11717
Fixes a regression where the socket rpc initialize error was ignored and the crashpad handler error caused the session to exit.

Fix session exit error so it applies to socket rpc again

---

src/cpp/core/CrashHandler.cpp

Addresses #11717, followup to #11788 
#11788  makes it so an error in the crash handler doesn't bring down the r session. This PR addresses the actual error so it doesn't get thrown in the first place. 
None yet
- Use Windows, R 3.6.3
- Create a user with an accented character (e.g. umlaut) in the user name
- Install daily as usual, ensure RStudio starts without crashing

 don't re-encode to utf8

---

src/cpp/core/FileUtils.cpp
src/cpp/core/include/core/FileUtils.hpp
src/cpp/session/include/session/SessionQuarto.hpp
src/cpp/session/modules/quarto/SessionQuarto.cpp
src/cpp/session/modules/quarto/SessionQuartoJob.cpp

Addresses https://github.com/rstudio/rstudio/issues/11779.
Use a short path name when trying to run Quarto.
N/A (Windows only)
Test via notes in https://github.com/rstudio/rstudio/issues/11779.

use short path name when running quarto

---

src/node/desktop/src/core/user.ts
src/node/desktop/src/native/desktop.node.d.ts
src/node/desktop/src/native/desktop/desktop.cc

Address implementation of `~` on Windows in #11635 and #11712
Port over `currentCSIDLPersonalHomePath` and `defaultCSIDLPersonalHomePath` as native modules and use those when both R_USER and HOME are unset and platform is Windows
None

Fix windows home path ~ implementation

---

src/cpp/session/modules/SessionObjectExplorer.R
src/cpp/session/modules/SessionObjectExplorer.cpp
src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/ObjectExplorerEditingTarget.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/ObjectExplorerPresenter.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/events/ObjectExplorerEvent.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/events/RefreshObjectExplorerEvent.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/model/ObjectExplorerHandle.java

part of #1994 
Make sure a `View(x)` when called a second time updates the view, and removes the entry from `.rs.explorer.cache`. 
In a new session, type: 
```r
f <- function() {
x <- list(a = runif(1))
View(x)
}
ls.str(.rs.explorer.cache)
f()
```
`x` is viewed with some number: 
`.rs.explorer.cache` is empty before the `f()` call: 
Then it has one entry after the call to `f()`: 
Call `f()` a second time, the view is replaced: 
`.rs.explorer.cache` still has only one entry, a new one: 
Without this change, `x` was not updated in the view, and entries were accumulating in …

Live updates for object explorer

---

src/cpp/session/http/SessionHttpConnectionListenerImpl.hpp
src/cpp/session/http/SessionLocalStreamHttpConnectionListener.hpp
src/cpp/session/http/SessionTcpIpHttpConnectionListener.hpp

Follow on fix for: http://github.com/rstudio/rstudio-pro/issues/3674 
Use the existing authenticate() hook for the verifyRequestSignature. We could remove all of the other calls to verifyRequestSignature as they are now redundant but am thinking to leave them in for this patch.
See the original PR for testing.

Moved verifyRequestSignature call into authenticate

---

src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java

addresses #11591
add the case to `quoteIfNotSyntacticNameCompletion()` 

don't quote around `RCompletionType.FUNCTION` types

---

docker/jenkins/Dockerfile.rhel8

The official RockyLinux docker image is `rockylinux`
The `rockylinux/rockylinux` image is not the official docker image.
Changed base image to use official `rockylinux` image
This will update the image used in Jenkins

Use rockylinux base image, was rockylinux/rockylinux

---

src/node/desktop/src/main/menu-callback.ts

Addresses #11827  
Remove the key accelerator (Opt+Cmd+I or Ctrl+Shift+I) for toggling developer tools
None
I could only reproduce the issue in a non-markdown file like an R code file. It may differ according to platform but the key conflict exists and may prevent the insert code chunk action from working.

Fix toggle developer tools/insert code chunk accelerator conflict

---

NEWS.md
src/cpp/session/modules/SessionFind.cpp

Addresses https://github.com/rstudio/rstudio/issues/11822.
`git grep` is recursive by default, and some version of `git` don't support the `--recursive` (`-r`) flag. So, don't set it. See: https://git-scm.com/docs/git-grep#Documentation/git-grep.txt--r
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/11822.

don't set '-r' in git grep invocation

---

src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/renderer/desktop-bridge.ts

More work for #11252 
Implement the `setPresentationUrl` call in the desktop bridge. This allows navigation to the presentation url when rendering to the Presentation Pane.
None
Render preview to pane will work now.

Implement set presentation url

---

src/node/desktop/src/main/application-launch.ts
src/node/desktop/src/main/args-manager.ts

Address #[#11778](https://github.com/rstudio/rstudio/issues/11778), at least on Windows and Linux. May need some additional handling for Mac to process double-click on Finder events, but will leave to subsequent PR.
Set the RS_INITIAL_WD environment variable, used by the C++ session code, in pre-launch Electron code
None
Will need to be tested on at least Windows and Mac -- see notes in issue.

Electron - open file in working directory when launching RStudio with a file arg

---

src/gwt/src/org/rstudio/studio/client/projects/ui/newproject/NewQuartoProjectPage.java
src/gwt/src/org/rstudio/studio/client/quarto/ui/NewQuartoDocumentDialog.java

Addresses https://github.com/rstudio/rstudio/issues/11769.
We don't have an exact repro for this bug, but it has been reported a number of times on the community forum and in support tickets. In each case, the problem is that creating a new project fails with a JavaScript error referring to `python`. 
Analyzing the code reveals that the problem is almost certainly related to Quarto capabilities. These can be `NULL` when Quarto is disabled (for any reason), but one of the pages in the New Project wizard reads the `.python` member without a null guard (while fetching the set of Jupyter kernels). 
The fix is speculative; it just adds null guards to places where we were presuming the capability set to be non-null. 
N/A; we don't have a real repro for this.
Test project creation in …

Add null guards for Quarto capabilities

---

src/gwt/src/org/rstudio/core/client/widget/RStudioFrame.java

Fixes previewing HTML files for RStudio server and Qt builds.
The `allowNavigation` was only implemented for Electron to get around the lack of a `will-frame-navigate` event.
This will fix an automated test
None

Fix HTML preview

---

src/cpp/session/prefs/PrefLayer.cpp

Addresses https://github.com/rstudio/rstudio/issues/11802.
Copies the existing formula for checking for unset preference layers here:
https://github.com/rstudio/rstudio/blob/11579f2d472ea9a6f677efafcce33c6a26e9dcd9/src/cpp/session/include/session/prefs/PrefLayer.hpp#L54-L59
Not included as this is mostly a speculative fix.
N/A

add null checks to cache_ when reading pref values

---

src/cpp/session/SessionRpc.cpp

Addresses https://github.com/rstudio/rstudio/issues/11841.
In handling a potentially null pointer, rather than defining a separate "safe" reference variable, just set the pointer binding to a valid reference.
Not sure how to test (theoretically, would be covered by existing tests?)
N/A

tweak handling for potentially null response values

---

src/cpp/session/modules/SessionFiles.R
src/gwt/src/org/rstudio/core/client/MessageDisplay.java
src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
src/gwt/src/org/rstudio/studio/client/workbench/views/files/model/FilesServerOperations.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/views/source/ViewsSourceConstants_fr.properties
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorBackgroundLinkHighlighter.css
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorBackgroundLinkHighlighter.java

addresses #11840
Treat `(#[0-9]+)` as issue (or pr) links, e.g. 
```r
test_that("can use freshly create variables (#138)", {
df <- tibble(x = 1:10)
out <- summarise(df, y = mean(x), z = y + 1)
expect_equal(out$y, 5.5)
expect_equal(out$z, 6.5)
})
```
Extend `AceEditorBackgroundLinkHighlighter` to recognize the pattern. 

recognize (#[0-9]+) as links to issues

---

src/node/desktop/src/main/url-utils.ts
src/node/desktop/test/unit/main/url-utils.test.ts

Knitting a markdown file would show an error message after the preview displays in the pane.
Added a try/catch to `getAuthority` since it can throw when constructing a bad url. The default base url is set to localhost to handle the preview setting the URL as `rmd_output/0`. What we really want to do with the authority is to make sure that the host and port match our list of URL's that a pane might be set to. If the URL is completely invalid, an empty string is used.
Unit test added to check a bad url or a path.
Knitting a markdown file will not show an error message.

Fix markdown preview setting the pane url as a path

---

src/cpp/core/libclang/SourceIndex.cpp
src/cpp/session/modules/clang/RCompilationDatabase.cpp

Addresses https://github.com/rstudio/rstudio/issues/11852.
- Try to fix up `-std` flags before compiling translation units, just in case.
- Ignore that `rlang-rcc.cpp` file when deciding if a project is primarily C or C++.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/11852.

handle C projects using rlang-rcc.cpp

---

src/cpp/core/FileUtils.cpp
src/cpp/core/include/core/FileUtils.hpp
src/cpp/session/modules/clang/RCompilationDatabase.cpp

addresses #6384
hack the files `Makevars` and `Makeovers.win` before they get copied to temp directory so that the line `OBJECTS = ` has no effect. 

change OBJECTS = to zzzOBJECTS = in Makevars and Makevars.win

---

src/cpp/session/modules/clang/RCompilationDatabase.cpp

Follow up to #11864 
This bumps `kCompilationDatabaseVersion` to 2 so that we don't restore compilation setting from previous versions. 

bump `RCompilationDatabase :: kCompilationDatabaseVersion` 

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorBackgroundLinkHighlighter.java

- Avoid registering the preference handler in `refreshHighlighers()`, as that implies the handler will be re-registered (and not removed!) each time highlighters are refreshed.
- Because the `webLinkHighlighter()` function returns a new highlighter object, we can't use that to try to remove an old instance (if it exists). Instead, the simplest fix is to just refresh highlighters when that preference changes.

avoid potential duplicate web link highlighters

---

src/node/desktop/src/main/application.ts

Second part of [#11778](https://github.com/rstudio/rstudio/issues/11778) for Macs
set the initial working directory in the `open-file` event used when double clicking file from the Finder window.

Add Finder handling for Mac setting initial working directory

---

src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetThemeHelper.java

Addresses https://github.com/rstudio/rstudio/issues/11868.
Addresses https://github.com/rstudio/rstudio/issues/11422.
Delay synchronization of CSS styles with editor theme, so that the browser has a chance to render these themes first.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/11868 (perhaps an update to Chrome is causing this to be more easily triggered?)

delay sync of document outline styles

---

src/node/desktop/src/native/desktop/desktop.cc

Resolves this warning:
```
CXX(target) Release/obj.target/desktop/src/native/desktop/desktop.o
../src/native/desktop/desktop.cc:218:11: warning: address of stack memory associated with local variable 'homePath' returned [-Wreturn-stack-address]
return homePath;
^~~~~~~~
../src/native/desktop/desktop.cc:249:11: warning: address of stack memory associated with local variable 'homePath' returned [-Wreturn-stack-address]
return homePath;
^~~~~~~~
2 warnings generated.
```

avoid returning pointers to stack memory

---

src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackageLibraryUtils.java

Addresses https://github.com/rstudio/rstudio/issues/11847.
Normalize slashes in the path provided by `R_LIBS_USER` before comparing the paths.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/11847.

normalize R_LIBS_USER before checking library type

---

src/cpp/session/modules/clang/RCompilationDatabase.cpp
src/cpp/session/modules/clang/RCompilationDatabase.hpp

Another followup on #6384 
`--dry-run` on the same directory, using `--output=<non existing so>` and `--always-make`

use `--always-make` in addition to `--dry-run`

---

src/node/desktop/src/core/winston-logger.ts
src/node/desktop/src/main/main-window.ts
src/node/desktop/src/main/url-utils.ts
src/node/desktop/src/main/utils.ts
src/node/desktop/test/unit/main/browser-window.test.ts

Addresses https://github.com/rstudio/rstudio/issues/11611.
Ensure that `did-fail-load` events from sub-frames don't force the main frame to attempt to reload the main page.
In addition, try to make sure that attempts to navigate to external URLs from within the iframe open externally. (Implementation is sub-optimal; we need 'will-frame-navigate' to get it right.)
Not included.
Test that navigating a link as in https://github.com/rstudio/rstudio/issues/11611 merely fails in the Viewer pane, but nothing bad happens to the IDE.

ignore 'did-fail-load' events from subframes

---

dependencies/common/.gitignore
src/cpp/core/include/core/r_util/RToolsInfo.hpp
src/cpp/core/libclang/SourceIndex.cpp
src/cpp/core/r_util/RToolsInfo.cpp
src/cpp/session/modules/clang/RCompilationDatabase.cpp
src/cpp/session/modules/clang/RCompilationDatabase.hpp

Addresses #6384.
- Ensure `R CMD SHLIB` runs in the package `src/` directory directly.
- Sneak in the `--always-make` argument into the `R CMD SHLIB` invocation.
N/A
N/A

sneak '--always-make' into R CMD SHLIB invocation

---

src/cpp/core/http/Util.cpp
src/cpp/core/include/core/http/Util.hpp

Add a new util function to identify certificate verify ssl errors for linux
Reviewed in: https://github.com/rstudio/rstudio-pro/pull/3778

Companion to session ssl load-balancing bug fix

---

src/cpp/core/include/core/Log.hpp
src/cpp/session/modules/SessionDataViewer.R
src/cpp/session/modules/SessionObjectExplorer.R
src/cpp/session/modules/SessionObjectExplorer.cpp
src/cpp/session/modules/data/DataViewer.cpp
src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceColumnManager.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/data/DataEditingTarget.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/ObjectExplorerPresenter.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/events/CloseObjectExplorerEvent.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/CloseDataEvent.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/DataViewChangedEvent.java

Addresses #1994 (follow up after comment https://github.com/rstudio/rstudio/issues/1994#issuecomment-1234386524)
The refresh code for both explorer and data viewer makes sure these are still the best way to `View()` the objects, if not then their tab is closed and `View()` is called again. 
For example (needs to be executed line by line): 
```r
x <- list(a = 1)
View(x)             # object explorer view
x <- cars           # after this the `x` View uses data viewer
x <- rnorm        # then function viewer
```
The data frame view is replaced by an object explorer view: 
then the function viewer: 
Similarly, the data view gets replaced by an explorer view here:
```r
y <- cars
View(y)             # data view
y <- list(a = 2)  # object explorer view
y <- rnorm        # function view
```
> …

switch from data viewer and object  explorer viewer if object type changes

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetThemeHelper.java

Follow up to #11422 because problem still exist after #11876
use a 100ms timer instead of `Scheduler.get().scheduleDeferred` so that there's more time to apply the styles. Presumably `Scheduler.get().scheduleDeferred()` was too early. 
Although I'm not sure because I could not reproduce the problem as in https://github.com/rstudio/rstudio/issues/11422#issuecomment-1242511691
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information …

use Timer instead of `Scheduler.get().scheduleDeferred()`

---

src/cpp/r/R/Tools.R
src/cpp/r/session/RSearchPath.cpp

addresses #11527
only add the lib (coming from the `path` attribute of the `as.environment()` result) if it has the package as an installed package. 
i.e. not those that have been `load_all()` and are only source packages which will make `library()` fail. 

only add lib if it has the package as an installed package

---

src/node/desktop/src/main/detect-r.ts

Addresses edge case in #11438 (when Rtools is installed)
The current way we check the registry for anything from R-Core means it will detect RTools installation as well as R itself. While it's highly unlikely a user would have Rtools installed, but R not installed, it could happen if they uninstalled R and forgot to reinstall, and this came up in QA. Also we don't want to log errors relating to not finding a particular entry in the registry; these are expected and already handled.

Ignore registry entries for Rtools

---

src/cpp/session/modules/build/SessionBuild.cpp

addresses #11706
only add the `cleanup = FALSE` argument when it is available in devtools (before version 2.4.4). 

only add cleanup = FALSE when devtools < 2.4.4

---

src/cpp/core/CMakeLists.txt
src/cpp/core/Timer.cpp
src/cpp/core/include/core/Timer.hpp

This allows code that needs to test timeout functionality the ability to mock the timer to allow you to have control over when the timer is actually invoked, making this very useful for unit testing.
This has already been proven out in the Launcher codebase.

Add Timer class and ITimer interface to core library.

---

src/gwt/src/org/rstudio/studio/client/workbench/snippets/SnippetHelper.java

addresses #11951
update `transformMacros()` so that `$$` is only replaced if not preceded by `\` so that `\$$` is legit

replace `$$` in snippet only if not preceded by`\`

---

src/cpp/core/system/Crypto.cpp

This commit initialises the `siglen` parameter as required by [the OpenSSL docs for `EVP_PKEY_sign()`](https://www.openssl.org/docs/manmaster/man3/EVP_PKEY_sign.html#DESCRIPTION):
> If sig is not NULL then before the call the siglen parameter should contain the length of the sig buffer, if the call is successful the signature is written to sig and the amount of data written to siglen.
The previous code worked against the OpenSSL 3 library I QA'd it against and in unit tests (which have small payloads), but @colearendt [reported that it failed in real-world usage](https://rstudio.slack.com/archives/C7HT9GDB9/p1661873074996499) on a Ubuntu 18.04 environment:
2022-08-30T15:23:32.112970Z [rserver] ERROR system error 74 (Bad message) [description: error:0608C09B:digital envelope …

Fix RSA signature buffer initialisation for old versions of OpenSSL

---

src/node/desktop/forge.config.js
src/node/desktop/src/main/application-launch.ts
src/node/desktop/src/main/application.ts

Address part of #11604 
Request instance lock after app is ready to prevent pause until user focuses window. Electron docs show to request before the app is ready but this doesn't seem to make any difference on Linux and Windows. MacOS does briefly show the dock icon since that shows when the app is ready. These seems to be a good compromise to waiting for focus when requesting the instance lock.
I don't know if this addresses the long start up though. It still seems to be long on Windows but that's using an Amazon Workspace, which is already quite slow.
None
This does not necessarily address the long startup for a second window. It does remove the need to focus the second window so that it finishes start up.

Workaround to Electron second instance hang

---

src/cpp/core/include/core/system/Xdg.hpp
src/cpp/core/system/Xdg.cpp
src/cpp/server_core/SecureKeyFile.cpp

Addresses https://github.com/rstudio/rstudio/issues/11828. 
When running in low privilege mode, do not use a hard-coded secure cookie key path in the global folder `/tmp/rstudio-server`. Instead, since we know we are running as a low privilege user, put the secure cookie key in their per-user cache, following the XDG specification for user-level cache data.
N/A, automated tests do not currently have the ability to run in low privilege mode AFAIK.
The secure cookie key is used for login cookies, so testing login/logout in low privilege mode should validate the change. Set the log level to `INFO` or higher to confirm; you should see a message like this:
```
INFO Running without privilege; using secure key at /Users/jmcphers/.cache/rstudio/session-rpc-key
```
See here for more info on low …

Use XDG_CACHE_HOME for secure cookie key in low privilege mode

---

src/cpp/shared_core/FilePath.cpp
src/gwt/src/org/rstudio/core/client/files/FileSystemItem.java
src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java

Add basic support for nextflow language (*.nf) files. Partially adresses https://github.com/rstudio/rstudio/issues/11677
Based on https://github.com/rstudio/rstudio/commit/59cab5bba624acd1574b144ab828d14728b70561
Nextflow is a DSL in groovy, so adding groovy syntax highligting is appropriate. THis will not include nextflow specific syntax highlighing (e.g. `process`, `workflow` etc)
Not done.
Singed contributors agreement

Nextflow filetype support

---

src/cpp/core/include/core/http/Socket.hpp

Updates `src/cpp/include/core/http/socket.hpp` with a small casing fix. Any parameter variables should not be title case by default, and we refer to similar variables as the lowercase `handler` as well.
This should be a no-op, nowhere do we ever name this argument when making calls to `asyncWrite()`.
If we introduced any bugs our compiler should catch them, given we're just renaming a couple variables.
- [ x If this PR adds or changes UI, the updated UI meets [accessibility standards](https://github.com/rstudio/rstudio/wiki/Accessibility)

Nit: standardize arg names to lowercase in Socket.hpp

---

src/cpp/core/include/core/libclang/SourceIndex.hpp
src/cpp/core/libclang/SourceIndex.cpp
src/cpp/session/modules/SessionCodeSearch.cpp
src/cpp/session/modules/clang/DefinitionIndex.cpp
src/cpp/session/modules/clang/DefinitionIndex.hpp
src/cpp/session/modules/clang/FindReferences.cpp
src/gwt/src/org/rstudio/studio/client/workbench/codesearch/CodeSearchSuggestion.java
src/gwt/src/org/rstudio/studio/client/workbench/codesearch/model/SourceItem.java

addresses #11981
use `CXTranslationUnit_DetailedPreprocessingRecord` to get macro definition. 

fuzzy finder showing C(++) macros

---

NEWS.md
src/cpp/session/modules/SessionGit.cpp

Addresses https://github.com/rstudio/rstudio/issues/10150 (plus another log warning oddity I saw).

fix issue with diff of merge commits

---

NEWS.md
src/cpp/r/include/r/session/RSession.hpp
src/cpp/r/include/r/session/RSessionUtils.hpp
src/cpp/r/session/RInit.cpp
src/cpp/r/session/RSession.cpp
src/cpp/r/session/RSessionState.cpp
src/cpp/r/session/RSuspend.cpp
src/cpp/r/session/RSuspend.hpp
src/cpp/session/SessionMain.cpp
src/cpp/session/SessionSuspend.cpp

Addresses https://github.com/rstudio/rstudio/issues/11960.
If the working directory associated with a suspended session doesn't exist, prefer using the project directory instead.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/11960.

default to project directory when restoring suspended session

---

NEWS.md
src/cpp/session/SessionMain.cpp
src/cpp/session/SessionOptions.cpp

and fix path for development builds on all platforms
Addresses #11693 
support correct pathing to rpostback binary on Mac/Windows/Linux and Qt/Electron as well as development builds
Correct bundled paths:
~/rstudio/src/build/session/postback/postback/rpostback  development build - Mac
/Volumes/RStudio-99.9.9/RStudio.app/Contents/Resources/app/bin/rpostback Electron - package build - Mac
/Volumes/RStudio-99.9.9 1/RStudio.app/Contents/MacOS/rpostback Qt - package build - Mac
~/rstudio/src/build/session/postback/postback/rpostback development build - Windows
C:/Program Files/RStudio/resources/app/bin/rpostback Electron - package build - Windows
C:/Program Files/RStudio/bin/rpostback Qt - package build - Windows
/usr/lib/rstudio/resources/app/bin/rpostback Electron - package build - Ubuntu …

Add correct path for rpostback mac electron (no need to hoist) 

---

NEWS.md
src/cpp/core/system/Win32ChildProcess.cpp

Addresses https://github.com/rstudio/rstudio/issues/11736.
When a process exits, we need to check stdout + stderr once more in case any more output was produced in the interval between our last poll and when the exit happened.
Deserves a sanity check because if this is really the issue it's stunning that this is the first time we're encountering it!
Also, if so, then arguably we should be doing the same thing in PosixChildProcess.cpp:
https://github.com/rstudio/rstudio/blob/main/src/cpp/core/system/PosixChildProcess.cpp#L1126-L1165
N/A
N/A

read rest of stdout / stderr on process exit

---

src/cpp/session/modules/SessionRmdNotebook.R
src/cpp/tests/testthat/test-notebook.R

addresses #11606
Remove the `#|` comments before the code is executed in the alternative engine

remove `#|` comments before executing alternative engine

---

src/gwt/acesupport/acemode/c_cpp_highlight_rules.js
src/gwt/acesupport/acemode/r_code_model.js
src/gwt/acesupport/acemode/r_highlight_rules.js

addresses #12023 
Call it "rdoc" instead of "rd" because ace actually ships snippets for `rdoc`: 
```js
define("ace/snippets/rdoc",["require","exports","module"], function(require, exports, module) {
"use strict";
exports.snippetText =undefined;
exports.scope = "rdoc";
});
```
They are empty, but at least they exist. We could create some useful Rd specific snippets, e.g. `\item{}{}`, primarily I suppose to use in roxygen comments. 
Alternatively, we could subsitute `rd` for `rdoc` in `loadSnippetsForMode()` if we wanted to keep using "rd"
> Add additional information for QA on …

use `rdoc-` instead of `rd-`

---

src/cpp/core/include/core/http/TcpIpAsyncConnector.hpp

Using a call to is_open() before calling cancel.  This allows us to finish the cleanup in that method and call the error handler for the connection.  This is a speculative fix we'd like to get into a build for a customer to try. I think it's pretty safe because the only place that code is used is the connection timeout error handler and it's a simple change. 
Addresses: https://github.com/rstudio/rstudio-pro/issues/3812
I don't think we have a way to test connection timeouts currently but we might want to investigate a "network fuzzer" or something so we can run load tests with flaky connectivity in a load balancing scenario.

Avoid error when calling socket.cancel() method if the socket is not open

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualMode.java

Addresses https://github.com/rstudio/rstudio/issues/12021. 
This issue is caused by behavior in the visual editor that causes code chunks (`RmdChunk`) to appear multiple times in the internal outline when they are indented. Because there are multiple representations of the same code chunk, the algorithm that synchronizes the code chunks between visual mode and source mode cannot run properly.
When receiving the list of chunk locations from the visual editor, discard adjacent duplicates.
It might also be worth investigating why we are getting multiple `RmdChunk` entries; this is possibly new or buggy behavior, and likely the source of the regression. However, changing the code upstream is much higher risk, and this change is correct either way.
N/A; unfortunately unit tests cannot …

Discard duplicate RmdChunk entries from visual editor

---

src/cpp/session/modules/SessionPackages.R

addresses #12034 
`utils::install.packages()` uses whether `repos` was specified: 
```r
if (length(pkgs) == 1L && missing(repos) && missing(contriburl)) {
if ((type == "source" && any(grepl("[.]tar[.](gz|bz2|xz)$", 
pkgs))) || (type %in% "win.binary" && endsWith(pkgs, 
".zip")) || (startsWith(type, "mac.binary") && endsWith(pkgs, 
".tgz"))) {
repos <- NULL
message("inferring 'repos = NULL' from 'pkgs'")
}
```
So making sure the shim don't specify to the original if it had not been given. I think the `repos` promise is resolved by the `if (!is.null(repos) && !packratMode && .rs.loadedPackageUpdates(pkgs)) {` 
> Indicate whether this change includes unit tests or integration tests, or link a work item or pull request to add those tests to another repo. If the change cannot or will not be …

handle `missing(repos)` in `install.packages()` shim

---

src/gwt/src/org/rstudio/studio/client/dataviewer/DataTable.java

Addresses https://github.com/rstudio/rstudio/issues/12029.
Because the main menu callbacks are visible to Electron even if a subframe has focus, the DataTable iframe no longer needs to forward keypresses to the ShortcutManager on Electron.
Not included.
Test via notes in https://github.com/rstudio/rstudio/issues/12029.

don't forward to ShortcutManager on Electron

---

src/gwt/www/rstudio.css

See: https://github.com/rstudio/rstudio-pro/issues/3846
OS-PR, but when this merges to Pro it will fix Pro / RDP.
Fix the login page not being centered in RDP, which is caused by an unsupported CSS shorthand.
Instead of `inset`, use `top`-`right`-`bottom`-`left` for absolute positioning. `inset` is a shorthand introduced in 2020 which is _after_ we stopped updating the QT versions.
This does not require automated tests. It's a layout-specific issue that only requires a one-time fix.
I verified that this was working in actual RDP.

Do not use "inset" -- too recent of a css property for QT

---

Jenkinsfile

Adds `aarch64` builds for RedHat 8 based Linux distributions such as Oracle Linux 8. See one example of a request for this on the community forum:
> I checked the arm version from your link but it doesn't have RedHat 8 version which I think I'm running on (Mine is Oracle Linux 8 which appears to be a modified version of RedHat 8).
https://community.rstudio.com/t/rstudio-server-compile-error-on-arm64-machine/148190/
Add builds to the matrix. I have confirmed with a local Docker build.
N/A, build script change only.
Note that we will only add arm64 for rhel8 to our open source releases. Our licensing system does not have rhel8-arm64 compatible binaries, so we can't make a viable Workbench build for this platform.

Add rhel8-arm64 builds

---

NEWS.md
src/cpp/CMakeLists.txt
src/cpp/core/include/core/http/AsyncConnection.hpp
src/cpp/core/include/core/http/AsyncConnectionImpl.hpp
src/cpp/core/include/core/http/Socket.hpp
src/cpp/core/r_util/RSessionContext.cpp
src/cpp/server/session/ServerSessionProxy.cpp
src/cpp/server/url-ports/CMakeLists.txt
src/cpp/server/url-ports/TestMain.cpp
src/cpp/server/url-ports/UrlPortsMain.cpp
src/cpp/server/url-ports/UrlPortsMainTests.cpp
src/cpp/server/url-ports/include/url-ports/UrlPorts.hpp
src/cpp/session/CMakeLists.txt
src/cpp/session/SessionClientInit.cpp
src/cpp/session/SessionMain.cpp
src/cpp/session/SessionUrlPorts.cpp
src/cpp/session/include/session/SessionConstants.hpp
src/cpp/session/include/session/SessionUrlPorts.hpp
src/cpp/session/modules/SessionWorkbench.cpp
src/cpp/session/modules/shiny/SessionPyShiny.cpp
src/cpp/session/modules/shiny/SessionPyShiny.hpp
src/cpp/session/postback/CMakeLists.txt
src/cpp/session/postback/rpostback-browser
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/SourceDocument.java

* Add a button for "Run App" for PyShiny apps
* Fix some issues with localhost port proxying that were exposed by PyShiny (specifically: chunked HTTP responses were being corrupted 100% of the time, and proxied WebSockets had a race condition that caused them to close 10% of the time).
To see this feature in action
1. Grab an example from https://shinylive.io/py/examples/, and save it as an `app.py` file.
2. Open that file in RStudio, and hit the "Run App" button to see it launch in a new window.
3. Arrange the app window and the RStudio window so that you can see them both, and make a trivial change to app.py. When you hit Save, you should see the app window reload itself.
The intent was to do the "simplest possible" integration, unfortunately that ended up still being a bit complicated. …

PyShiny Run App support

---

CONTRIBUTING.md
docs/user/rstudio/ide/guide/code/console.qmd
docs/user/rstudio/ide/guide/ui/ui-panes.qmd
docs/user/rstudio/index.qmd
src/cpp/session/resources/help_resources/index.htm
src/gwt/src/org/rstudio/studio/client/workbench/commands/CmdConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/commands/CmdConstants_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml

See: https://github.com/rstudio/rstudio-pro/issues/3830
OS PR
I want to wait until we merge OS to pro and then follow up with a pro-pr that will continue with more replacements.
Visual references to "RStudio Support" should be replaced with "Posit Support."
Find and replace operation with discretion. Some instances of "RStudio" are left as-is in context. I think every instance of "RStudio Support" has been covered.
I have made an effort to preserve the formatting in GWT's menus, so that the quick keys will still work.
N / A
This hits docs and several files within the IDE. @gtritchie our french-speaking friends should also have a look.

Rename instances of "RStudio Support" to "Posit Support"

---

src/cpp/r/include/r/session/RSession.hpp
src/cpp/r/session/RInit.cpp
src/cpp/session/SessionInit.cpp
src/cpp/session/SessionInit.hpp
src/cpp/session/SessionOfflineService.cpp
src/cpp/session/http/SessionHttpConnectionListenerImpl.hpp

Addresses: https://github.com/rstudio/rstudio-pro/issues/3870
Added a new method used by the two places we handle requests in the offline thread to be sure there's not a pending deferred session deserialization. Otherwise, we can end up running that R code off the main thread. 
See the issue for a test case that I found attached to this issue fixed a couple of years ago: https://github.com/rstudio/rstudio/issues/4178
Given that it's reproduced two bugs, it would be a good one for our regression suite.

Make sure session has been restored before running requests offline

---

src/gwt/src/org/rstudio/studio/client/common/filetypes/DocumentMode.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java

handles part of #8378
handle <TAB> specifically so that we can factor where the code starts (after `#' `) etc ...

only allow roxygen completion after a `@`

---

NEWS.md
src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java

Addresses https://github.com/rstudio/rstudio/issues/1638.
Ignore the next focus event after a blur.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/1638.

don't scroll into view when focus returns after window blur

---

NEWS.md
src/cpp/session/modules/SessionRMarkdown.R

Part of https://github.com/rstudio/rstudio/issues/9184.
Check and see if the `knitr` root.dir knit option is set; if so, use it.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/9184#issuecomment-1258873085.

use knitr 'root.dir' for completions as fallback

---

src/cpp/server/ServerMain.cpp
src/cpp/session/SessionMain.cpp

The goal here is to work more nicely with supervisors like `systemd` without requiring a custom shutdown script or other unit customization. It is possible that ignoring SigTerm on Desktop alters some other implicit functionality, but we thought this would be preferable and more explicit.
open source companion to rstudio/rstudio-pro#3811

handle SigTerm just like SigUsr2

---

src/gwt/src/org/rstudio/studio/client/common/filetypes/DocumentMode.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java

addresses #12070 
only insert the spaces on explicit completions (when `<TAB>` was indeed pressed). 

`beginsuggest()` only include spaces on explicit completions in roxygen `@examples` 

---

src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionPopupPanel.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanel.java

addresses #11973
Use `getWidget().getOffsetWidth()` instead of `getOffsetWidth()`. 

better position help info second popups

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorMonitor.java

Fix for set scroll speed errors
Check if `editor_` is null before trying to set the scroll speed. I'm not sure how to get into this state since the UI is single-threaded. The `endMonitoring()` call would completely execute before the UI thread can run the `monitor()` code and vice versa.
None
None

Check editor existence before setting scroll

---

src/cpp/session/SessionClientEventQueue.cpp
src/cpp/session/SessionClientEventQueue.hpp
src/cpp/session/SessionClientEventService.cpp
src/gwt/build.xml
src/gwt/src/org/rstudio/core/client/StringUtil.java
src/gwt/src/org/rstudio/core/client/dom/DomUtils.java
src/gwt/src/org/rstudio/studio/client/common/compile/CompileOutput.java
src/gwt/src/org/rstudio/studio/client/common/compile/CompileOutputBuffer.java
src/gwt/src/org/rstudio/studio/client/common/compile/CompileOutputBufferWithHighlight.java
src/gwt/src/org/rstudio/studio/client/common/compile/CompileOutputDisplay.java
src/gwt/src/org/rstudio/studio/client/common/compile/CompilePanel.java
src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java

Part of https://github.com/rstudio/rstudio/issues/12059.
This PR bundles a number of changes that should improve the responsiveness of both the Console pane and the Build pane, in the cases where we're receiving a very large amount of text.
1. We now bundle output on `stderr` in the same way we bundle `stdout`. This is necessary as R users may produce output on `stderr` via the `message()` function, so it can become overloaded in the same way that `stdout` might.
2. We also now truncate output shown in the Build pane. This is especially important for projects that compile C / C++ code, as the Build pane can become overwhelmed by warning output from the compiler.
Just to drive the second point home, this is what I see if I compile the `rstan` package with `-Weverything`:
``` …
```

optimize handling of console output / errors

---

src/gwt/src/org/rstudio/core/client/hyperlink/FileHyperlink.java
src/gwt/src/org/rstudio/core/client/hyperlink/Hyperlink.java

addresses #12086 
regex fu, when the url has fragment, this takes priority over the `[params]` 

`file://` hyperlinks can handle `#123` and `#123:4` fragments

---

src/gwt/src/org/rstudio/core/client/hyperlink/HelpHyperlink.java
src/gwt/src/org/rstudio/core/client/hyperlink/RunHyperlink.java
src/gwt/src/org/rstudio/core/client/hyperlink/VignetteHyperlink.java

addresses #12084 
Allow the `x-r-*` prefixes in addition to `ide:*` and `rstudio:*`. 

`x-r-help:`, `x-r-run:`, and `x-r-vignette:` schemes

---

src/cpp/session/modules/SessionRCompletions.R
src/gwt/acesupport/acemode/r_code_model.js

addresses #12067
mark the completions that have been deduced from a `dplyr`  chain as `COLUMN`, put them on top, and hint about the modification with `[mtcars %>% ...]`

completion with pipe chains also displayed as `COLUMN` type. 

---

src/cpp/session/modules/SessionRCompletions.R
src/gwt/src/org/rstudio/studio/client/common/codetools/Completions.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionCache.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/yaml/YamlCompletionManager.java

addresses #12091 
send back the completion context (from `.rs.acContextTypes` as part of the completion result, to eventually make the `QualifiedName` object. 
Then update `quoteIfNotSyntacticNameCompletion()` so that it quotes non syntactic functions, and keywords (but only in `::`, `:::`, `$`, and `@` contexts. 
In addition to the example in #12091, we should also consider if there is a regression of https://github.com/rstudio/rstudio/issues/11503 and https://github.com/rstudio/rstudio/issues/11591

completions after `::` or `:::` may need to be backticked

---

src/cpp/session/modules/SessionFind.cpp

Addresses https://github.com/rstudio/rstudio/issues/12082.
Explicitly handle absolute vs. `./`-prefixed vs. relative paths from grep.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/12082.

handle grep results without `./` prefix

---

src/cpp/server/extras/admin/rstudio-server.in
src/cpp/server/extras/admin/rstudio-server.mac.in
src/cpp/server/extras/systemd/rstudio-server.redhat.service.in
src/cpp/server/extras/systemd/rstudio-server.service.in

Now that we have #12074 , we can relax our `KillMode=none` restriction and the extra `killall USR2` that we send to `rsession` and `rworkspaces`, trusting that they will get cleaned up properly by the process tree / supervisor.
Aside: `KillMode=none` is expressly discouraged in [the systemd docs](https://www.freedesktop.org/software/systemd/man/systemd.kill.html)
> If set to none, no process is killed (strongly recommended against!). In this case, only the stop command will be executed on unit stop, but no process will be killed otherwise. Processes remaining alive after stop are left in their control group and the control group continues to exist after stop unless empty.
Another note from `launchctl` docs at launchd.info:
> Stopping a job will send the signal SIGTERM to the process.
- …

alter systemd configuration to avoid KillMode=none

---

src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/StanCompletionManager.java

addresses #11503 after regression caused by #12102
Make sure the `context` is propagated to `QualifiedName` objects created from completion results. 

Make sure to propagate context in `QualifiedName` constructor

---

src/node/desktop/src/main/main-window.ts

Address #12106 
Use `allowNavigation` check which also checks against the safe external URL list. This allows the video to embed without navigating to the video in the default browser.
None
See the issue for reprex. Requires Quarto 1.2 which is now packaged with RStudio.

Allow embedded youtube videos in Quarto preview

---

src/gwt/src/org/rstudio/core/client/hyperlink/Hyperlink.java
src/gwt/src/org/rstudio/core/client/hyperlink/LibraryHyperlink.java
src/gwt/src/org/rstudio/core/client/hyperlink/RunHyperlink.java

addresses #12114 
Allowing the url pattern : `x-r-run:library(pkg)`. The popup then shows the `pkg-package` help rather than help about the `library()` function. 
```r
cli::style_hyperlink("library(data.table)", "x-r-run:library(data.table)")
```

special case `x-r-run:library(<...>)` hyperlinks

---

CMakeGlobals.txt
NEWS.md
dependencies/common/install-quarto
dependencies/linux/install-dependencies-centos7
docker/jenkins/Dockerfile.centos7

Address rstudio/rstudio-pro#3804
Check `OS_DISTRO` and if equals `centos7` then download the specific archive for the platform.
Updates the dev dependency installer (new Centos7 script that calls the existing yum script after setting `OS_DISTRO`) and the Dockerfile for the build (sets `OS_DISTRO`).
None
Quarto will be enabled for the RHEL7/CentOS7 build. The menu option to create a .qmd file will be available. Also addresses missing Pandoc when working with RMarkdown files.

Add Quarto to RHEL7/CentOS7

---

src/node/desktop/src/main/desktop-browser-window.ts
src/node/desktop/test/unit/main/desktop-browser-window.test.ts

Address security for #10719 
I found this when reviewing the [Electron security guidelines](https://www.electronjs.org/docs/latest/tutorial/security). Most of it is preventing navigating to unintended URLs. We allow specific local URLs and some specific safe hosts. GWT has to set specific local URLs for some panes like viewer, presentation, and tutorial as well as Shiny.
Since Electron has to make available a way for GWT to set this in the main process, this is exposed in the renderer process through the preload scripts. This PR ensures setting these  URLs are local to prevent an attack through the preload. Without this, the IDE could be set to load an arbitrary URL. Normally, we anything disallowed in the IDE is opened externally.
Some unit tests to ensure `allowNavigation` returns false …

Ensure setting urls are local

---

NEWS.md
src/cpp/r/include/r/session/RClientState.hpp
src/cpp/r/session/RClientState.cpp
src/cpp/session/modules/SessionThemes.cpp
src/gwt/src/org/rstudio/studio/client/application/ApplicationThemes.java
src/gwt/src/org/rstudio/studio/client/workbench/ClientStateUpdater.java
src/gwt/src/org/rstudio/studio/client/workbench/events/PushClientStateEvent.java
src/gwt/src/org/rstudio/studio/client/workbench/model/helper/ClientStateValue.java
src/gwt/src/org/rstudio/studio/client/workbench/model/helper/JSObjectStateValue.java

Addresses https://github.com/rstudio/rstudio-pro/issues/3943.
Rather than use a WaitForMethod client event (which requires an actual client!), persist the theme information as client state on the session side in a way that's easily accessible to the session.
N/A
Test via notes in https://github.com/rstudio/rstudio-pro/issues/3943.

use persisted client state for theme info

---

src/node/desktop/src/main/session-launcher.ts

Address automation issue and unit test failure for #11604 
Add a `RS_NO_SPLASH` environment variable check. If set to anything, the splash will not be created.
Only creates the window for the splash if the delay is greater than 0.
Also disables the splash if running unit tests.
None
Setting `RS_NO_SPLASH` to any value will not create a splash at all. Hopefully this resolves running automation. @jonvanausdeln

Add no splash check

---

CMakeGlobals.txt
NEWS.md
dependencies/windows/.gitignore
dependencies/windows/install-dependencies.cmd
package/win32/cmake/modules/NSIS.template.in.electron

Address #10588 to detect if RStudio is running when installer is run
Detects if RStudio is running by process name. This detects Qt and Electron since it is checking for a `rstudio.exe` process. The error message remains the same and the installer exits when it sees RStudio is running.
The NSIS plugin has been uploaded to the `rstudio-buildtools` S3 with read permissions set. It's v1.6 and the unicode DLL was used. The zip was repackaged so only the include and DLL are in the archive.
`install-dependencies.cmd` will be called in the Jenkins build to install the NSIS plugin.
None
Running the Windows installer with either Qt or Electron version running will be detected by the installer.

Update Electron Windows installer with running instance check

---

src/cpp/session/modules/SessionGit.cpp
src/cpp/session/modules/SessionSVN.cpp

Addresses #11693 for password-protected authentication specifically 
We used to assume that the postback directory containing `rpostback-askpass` is the parent of the directory containing the actual rpostback executable. But this is no longer true.
In package builds, for both Qt and Electron, we have the `rpostback` binary in the same level as the `postback` directory containing the `rpostback-askpass` executable. The `rpostback` binary doesn't live in the postback directory with `rpostback-askpass` itself, except for in development builds.
This should be retested on both Mac and Windows with both password-protected and non-password protected SSH keys. Previous testing failed to catch an issue with password-protected keys

Fix for rpostback-askpass (follow up)

---

src/cpp/session/modules/SessionHelp.R
src/cpp/session/modules/SessionRCompletions.R

addresses #12140 
`.rs.getCompletionsLibraryContext()` uses `::` instead of `|||`. It matters because these are now displayed as part of the completion list: 
Also, the way `.rs.getRCompletions()` works, it gets argument completion both from `.rs.getCompletionsLibraryContext()` and `.rs.getCompletionsFunction()`. We prefer those from `.rs.getCompletionsLibraryContext()` because the  `packages=` include the package and the function, e.g. `rlang::quos` instead of just the function. 
> Add additional information for QA on how to validate the change, paying special attention to the …

`.rs.getCompletionsLibraryContext()` uses `::` instead of `|||`

---

src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/model/LintItem.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java

addresses #11306 
Fix `LintItem.create()` so that the object has `"raw"` as well as `"text"`. 
I haven'nt figure out how what part of ace brings the tooltip, so that change at least puts back the word: 

Spellcheck tooltip

---

src/cpp/session/modules/SessionHelp.R

addresses #12145
update the regex

only split `from::what` when there is a `what`

---

src/cpp/session/modules/SessionHelp.R

addresses #12147
When the `<pkg>-package` topic does not exist, use information from the `DESCRIPTION` instead. 

`.rs.getHelpPackage()` fallback to use information from `utils::packageDescription()`

---

src/cpp/core/include/core/r_util/RSourceIndex.hpp
src/cpp/core/r_util/RSourceIndex.cpp
src/cpp/session/modules/SessionCodeSearch.cpp
src/gwt/src/org/rstudio/studio/client/workbench/codesearch/ui/CodeSearch.css

addresses #12149 
And showing the title as extra information. 

fuzzy only shows `@name` completions that have a title

---

src/cpp/shared_core/FileLogDestination.cpp
src/cpp/shared_core/FilePath.cpp
src/cpp/shared_core/include/shared_core/FilePath.hpp

Fix https://github.com/rstudio/rstudio/issues/12167
This is because the call to `FilePath::getLastWriteTime` can fail and end up emitting a log line, which causes recursion in the logging code leading to attempting to re-acquire a mutex that was already acquired.
The fix is to make sure we aren't logging by adding a new method overload that returns the error instead of logging it.
Existing unit tests still pass.
Check with @MariaSemple for better repro steps. Only repros in certain environments.

Fixed bug where failing to delete a rotated log file could cause a log line to be emitted, causing deadlock.

---

src/gwt/src/org/rstudio/core/client/files/FileSystemItem.java
src/gwt/src/org/rstudio/studio/client/projects/Projects.java
src/node/desktop/src/main/gwt-callback.ts

also normalize client paths on Windows automatically
Addresses #11824
- Extract project name (directory name) from absolute directory path to avoid path duplication
- Normalize path separators on Windows
No
See issue reprex

Fix new proj from existing directory on Windows

---

src/gwt/acesupport/loader.js

addresses #12127 
`reindent()` also skips indenting when in "rawstring" state. 

not reindenting raw strings

---

src/cpp/core/zlib/zlib.cpp
src/cpp/core/zlib/zlibTests.cpp

In some cases, zlib can indicate that no progress has been made and no progress will ever be made again as there is no more data in the buffer to process.
In this case, we should error out.
Addresses https://github.com/rstudio/launcher/issues/497.
Added new zlib unit test to test this specific case.
N/A - covered by unit tests.

Fix bug where zlib decompression can hang on certain invalid string sequences

---

src/cpp/session/modules/SessionReticulate.R

Addresses https://github.com/rstudio/rstudio/issues/12053.
Try to be a little more careful when checking for the load of `matplotlib.pyplot` and `matplotlib.pylab`.
N/A
Test via notes in https://github.com/rstudio/rstudio/issues/12053#issuecomment-1282924186.

tweak matplotlib load hooks

---

src/cpp/core/include/core/r_util/RSourceIndex.hpp
src/cpp/core/r_util/RSourceIndex.cpp
src/cpp/session/modules/SessionCodeSearch.cpp
src/gwt/src/org/rstudio/studio/client/workbench/codesearch/CodeSearchSuggestion.java
src/gwt/src/org/rstudio/studio/client/workbench/codesearch/model/SourceItem.java

follow up for #12149, #12150
- Also show strings for roxygen before strings completion, and special case the `"_PACKAGE"` case:
It could be useful to also follow the `@rdname` so that `band_instruments` and `band_instruments2` would have extra info, maybe in a follow up. 
- Also handle explicit `@title` instead of first line of roxygen chunk: 
gives: 
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the …

Refinements for roxygen fuzzy

---

src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java

Addresses #11811 forcing unnecessary UI reload anytime any General Pref is changed in Electron
Fix logic error
No
Toggle on/off Soft wrap in General Preferences > Code. There should be no UI reload or session restart

Fix decision about UI refreshing when checking web vs native dialog

---

src/cpp/core/LogOptions.cpp
src/cpp/core/r_util/REnvironmentPosix.cpp
src/cpp/core/system/PosixParentProcessMonitor.cpp
src/cpp/desktop/DesktopOptions.cpp
src/cpp/session/SessionAsyncDownloadFile.cpp
src/cpp/session/modules/SessionPath.cpp

Some of the headers are missing when using non-default Boost versions. Add them for compatibility.
I'm not certain about contributor agreements if we have this signed. This is just a trivial patch and you can use it under whatever license.

Fix compilation across different Boost versions

---

src/cpp/session/modules/quarto/SessionQuarto.cpp

Addresses #12169 in case of missing embedded Quarto (such as in shipping distro of OpenSUSE)

exit early when embedded quarto is missing

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModePanmirrorContext.java

Address #11845 (part 2)
Part of this issue was previously addressed by JJ. However, in testing the issue we noticed that relative links to files in Visual Mode don't work -- clicking on the link does not navigate to the file in question. This is because the navigateToFile lambda is explicitly disabled for everything but Quarto website projects in Visual mode. Not sure if there is a good reason for this restriction or a more nuanced solution is needed, but in this case simply removing this check gives the file navigation behavior in visual mode the same capability as in source mode
None
See issue

Remove restriction on navigation that limits to website quarto

---

src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java
src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.java
src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsXls.java

addresses #3955
Only change the column definitions if this is a change of sheet, or a change of range. 

import excel: only update column definitions if change of sheet or range

---

src/cpp/session/modules/SessionCodeTools.R
src/cpp/session/modules/SessionRCompletions.R
src/gwt/src/org/rstudio/studio/client/common/codetools/RCompletionType.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java

addresses #11629
special case `.rs.getRChainCompletions()` 
```r
library(arrow)
library(dplyr)
tf <- tempfile()
data <- dplyr::group_by(mtcars, cyl)
write_dataset(data, tf)
ds <- open_dataset(tf)
tab <- arrow_table(mtcars)
ds %>% filter(<TAB> )
tab %>% filter(<TAB> )
```
give: 
cc @nealrichardson

completion for arrow tables and datasets

---

src/cpp/core/include/core/WeakCallback.hpp

Note that these macros are not currently used in the IDE or Workbench at present, but only in Launcher.
These macros are documented in the original comments and commit as "only working on GCC", but that no longer seems to be the case -- I've observed that they work fine on recent Clang compilers on macOS.
This change won't affect any automated tests, because this code is unused in this repo.
N/A

Allow the use of the weak callback macros under Clang

---

src/cpp/session/modules/SessionGit.cpp
src/cpp/session/modules/SessionSVN.cpp

Addresses #11693
For Mac Electron package builds, the path to the rpostback executable is: `RStudio.app/Contents/Resources/app/bin/rpostback`
However the path to the rpostback-askpass executable is:
`RStudio.app/Contents/Resources/app/bin/postback/rpostback-askpass`
Similarly, for Windows Electron package builds, the path to the rpostback executable is:
`C:/Program Files/RStudio/resources/app/bin/rpostback`
However the path to the rpostback-askpass executable is:
`C:/Program Files/RStudio/resources/app/bin/postback/rpostback-askpass`
So what we need to do is fix the path for `rpostback-askpass` relative to `rpostback` in non-development builds.
We do this by taking the rpostback path, getting its parent, adding the `/postback` to that parent path, and adding that directory to the path. …

go into postback folder to find rpostback-askpass

---

src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PublishingPreferencesPane.java

Addresses #12206 
Hosted team originally requested the Disconnect button be disabled for rstudio.cloud accounts, but they changed their minds and now want it unconditionally enabled for these accounts until further notice.

Re-enable the Disconnect button for all rstudio.cloud accounts

---

src/node/desktop/src/main/session-launcher.ts
src/node/desktop/src/ui/splash/splash.html

Resize the splash screen and allow dragging it
Set to 250px square so it doesn't overwhelm lower resolution screens. Set the drag attribute and allow dragging from anywhere on the splash.
None
`--startup-delay` can be set to the number of seconds to show the splash

Resize splash and allow dragging

---

NEWS.md
src/cpp/session/modules/NotebookData.R

R package developers use the [vctrs package](https://vctrs.r-lib.org) to implement custom vector data types with dedicated `format()` methods. These new vector types can be stored in a data frame just like atomic vector types. This PR enables their custom formatting methods to be called when generating the chunk output for a data frame.
Fixes #6878. This is a follow-up (and simplification) to #10777 by @markromanmiller. Also related: https://github.com/r-lib/vctrs/issues/1212.
Many of these vctrs-based classes ultimately derive from lists (e.g., those based on `vctrs_list_of` and `vctrs_rcrd`), such that `is.list()` returns TRUE. Unfortunately, this means the chunk output formats them using `obj_sum()` instead of their custom `format()` method.
This PR checks prevents calling `obj_sum()` …

Chunk output calls `format()` for vctrs classes

---

src/gwt/panmirror/src/editor/src/nodes/image/image-events.ts
src/node/desktop/src/core/file-path.ts
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/test/unit/core/file-path.test.ts
src/node/desktop/test/unit/core/file-serializer.test.ts
src/node/desktop/test/unit/unit-utils.ts

Address #11783 
Add Electron specific clipboard check in image paste event handling. Qt adds images to the clipboard event as `application/qt-image`. Electron seems to add images as `image/png` to data items, which can be checked if it is an `image/png`.
The random string code was removed from a unit test util. There's a random string util in the core code that is identical. So some unit test refactoring was done to fix the imports.
This will work on all platforms. It does not address the server issue.

Fix Electron clipboard image paste

---

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java

Partially address #12130 
Lower the max line count for the console output queue. This seems to not crash the render thread.
Electron seems to process the R console output callbacks a lot faster than Qt. I don't know if the rsession is faster at processing or if there's less overhead with Electron allowing GWT to queue the messages faster. In any case, the renderer is overwhelmed by the output and the many updates to the DOM. It keeps updating the one node until it becomes too large for the renderer. This lower limit results in a smaller node and prevents the render thread from crashing.
None
This is the same issue as reported in #5518 but with a lower limit.

Lower limit for max line console queue

---

src/cpp/tests/testthat/test-api.R

Prevent unstable builds caused by unit test warnings in a few environments:
```
[2022-11-02T03:53:25.365Z] Warning message:
[2022-11-02T03:53:25.365Z] Character set is not UTF-8; please change your locale 
[2022-11-02T03:53:25.365Z] v | F W S  OK | Context
[2022-11-02T03:53:25.365Z] 
/ |         0 | api                                                             
/ |         0 | rstudioapi                                                      
v |   2     6 | rstudioapi [0.1s]
[2022-11-02T03:53:25.365Z] --------------------------------------------------------------------------------
[2022-11-02T03:53:25.365Z] Warning (ine<c2><a0>=<c2><a0>41:col<c2><a0>=<c2><a0>1;file:///var/lib/jenkins/workspace/IDE/open-source-pipeline/main/src/cpp/tests/testthat/test-api.Rtest-api.R:41ommand callbacks …
```

Prevent intermittent test failures

---

src/node/desktop/src/main/desktop-browser-window.ts
src/node/desktop/test/unit/main/desktop-browser-window.test.ts

Address #12256 
When the R session restarts, it creates a new URL for the Viewer pane. GWT does set the viewer URL correctly so it is fine to load. However, the pane loads the old URL one last time just as the DOM changes the iframe to the new URL. This triggers an `allowNavigation` check, which fails. The failure causes the URL to open in an external browser.
This is a pretty quick fix to the issue but it might be simpler to allow all localhost URLs at this point. Or figure out why the old URL is loaded one last time (actually multiple times because multiple tabs open).
If Electron ever supports `will-frame-navigate` then the localhost check can be done only for iframes. I think it's still important to check the base URL's port to prevent a different UI running locally to be loaded in …

Electron allowNavigation browser spawn fix

---

NEWS.md
src/cpp/server/extras/systemd/rstudio-server.redhat.service.in
src/cpp/server/extras/systemd/rstudio-server.service.in

Open source / `rstudio-server` companion to https://github.com/rstudio/rstudio-pro/pull/4002 and https://github.com/rstudio/rstudio-pro/issues/2585
The intent is to use `systemd`'s default shutdown behavior (kill the main service PID) and make `systemctl reload` a possibility by sending `SIGHUP` to the main service process. I have also added a `NEWS.md` entry to reflect this work.
As discussed more thoroughly in https://github.com/rstudio/rstudio-pro/issues/3748 and https://github.com/rstudio/rstudio-pro/issues/3749
N/A.  No automated tests of init mechanisms
Ensure that `rstudio-server` scripts work as expected and `systemctl stop/start/restart/reload` work as expected.

RStudio Server lifecycle improvements for systemd

---

src/node/desktop/test/unit/main/browser-window.test.ts

The `browser-window-test` was failing on RHEL9 arm64 since it doesn't have python 2 on it. Python 3 is there but probably requires calling `python3`. This should fix it for that platform and hopefully address the intermittent failures on other platforms if the server doesn't come up fast enough.
Use node's http module to create a listen server. No need to spawn another thread so it will be ready to accept requests when trying to load the URL.
The chosen port also happens to be the same as the GWT dev server. So it would seem that it passes every time if you have it running and wouldn't encounter an intermittent failure if the Python server didn't come up fast enough. It's been changed to avoid the conflict.
Unit test passes locally
n/a

Remove python dependency from electron test

---

src/cpp/server/url-ports/UrlPortsMain.cpp

Addresses rstudio/rstudio-pro#3912
`rserver-url -l {port}` concatenates `$RS_SERVER_URL` and `$RS_SESSION_URL`, which can lead to a the URL output including a double slash:
```
$ echo $RS_SERVER_URL; echo $RS_SESSION_URL
https://dev1.rstudio.internal/
/s/4566a3c9ab5a75ae3a3d3/
$ /usr/lib/rstudio-server/bin/rserver-url -l 8050
https://dev1.rstudio.internal//s/4566a3c9ab5a75ae3a3d3/p/3393aabd/
```
This causes issues running applications in proxied environments with prefixes like `/rstudio` in their session ID. 
`$RS_SESSION_URL` will always begin with a leading `/` so if we find a trailing `/` in `$RS_SERVER_URL`, we remove it before concatenating the output.
The recently added FastAPI automation will fail in our proxy fuzzbucket environment. This should resolve that.

Prevent double slash in rserver-url -l output

---

src/node/desktop/src/main/application.ts

Address #12247
Electron 20 adds support for theming the title bar. Until Electron is upgraded, it looks more consistent to have the theme set to `light` on Windows. Then the menu bar and title bar will have consistent theming. Linux (Ubuntu 22) and Mac do not have this issue.
With Electron 20, we can then add in event hooks to adjust the `nativeTheme` and maybe even match it to the options that are selected in the Appearance options.
None
It is noticeable on Windows when setting the system theme to dark.
Mac does not have this issue since the menu bar is always at the top and is themed according to the system.
Linux appeared fine on Ubuntu 22 but may vary depending on the windowing environment.

Use light theme on Windows

---

dependencies/common/install-soci

Addresses ##12288
A recent change in homebrew's Postgres formula made it keg-only. This prevented the SOCI build (done when installing rstudio build dependencies) from finding the Postgres libs. SOCI still builds, just without Postgres support. That then breaks the rstudio IDE build when cmake fails to find the SOCI Postgres libs.
This manifests on recently configured Mac dev machines, but not on ones set up before this change (unless an explicit `brew update` was performed recently AND the SOCI libs rebuilt). The Mac official build machine is never `brew updated`, so it hasn't hit this problem.
When building SOCI on a Mac, set the environment variable `POSTGRESQL_ROOT` to the location of the homebrew postgres files. This environment variable is documented in the cmake module for postgres …

fix building on Macs with up-to-date brew dependencies (postgres)

---

src/cpp/session/modules/SessionRCompletions.R
src/gwt/acesupport/acemode/r_code_model.js

addresses #9786
R code model was under the impression it would get two `:` tokens, when in fact `::` is tokenized as once entity. 
In addition to #9786, this gets arguments correctly (with dispatch) when the function is prefixed with package name:

column name chain completions with prefixed function, e.g. `dplyr::mutate()`

---

src/cpp/session/modules/data/DataViewer.cpp

addresses #12296
careful not to call `Rf_inherits()` on a `nullptr`. 
when the object is not found in the environment, `findInNamedEnvir()` returns a `nullptr`: 
- still emit a client event to close the View
- don't try to call View again

not callling `Rf_inherits(sexp` if `sexp` is `nullptr`

---

NEWS.md

There are a handful of Pro PRs that needed follow-up NEWS.md entries.
One open question - the NEWS.md entry (line 41):
```
Handles `SIGTERM` signals to shut down more gracefully, for better interaction with service managers like `systemd`. (rstudio/rstudio-pro#2585)
```
is a bit redundant with some `Fixed` news entries below (lines 96 and 97) - is this concerning? Helpful because it is in two different places with slightly different details?

add news entries for a handful of pro PRs

---

src/cpp/rstudio-tests.in

I was only able to reproduce the below failures by moving `lsof`. I tried a `which lsof` in the Jenkinsfile before the tests run, but it came up okay.
Add a `which lsof` call in the test script to try to see if `lsof` is missing from the path in the script context.
Trying to fix them
Build system only

Add an echo to investigate some test failures

---

src/cpp/session/modules/SessionRCompletions.R
src/gwt/acesupport/acemode/r_code_model.js

addresses #9612
`getDataFromInfixChain()` sets `name` to the full evaluation context, rather than only the token before the first pipe. 
```r
library(tidyverse)
outer_lst <- list(
lvl1_lst =list(
inner_df = data.frame(inner_col_1 = 1:2, inner_col_2 = 3:4),
inneer_x = 42
),
lvl1_df = data.frame(lvl1_col_1 = 1:2, lvl1_col_2 = 3:4)
)
```
`outer_lst$lvl1_lst$inner_df %>% filter(` <kbd>TAB</kbd>
`outer_lst$lvl1_lst[[1]] %>% filter(` <kbd>TAB</kbd>
`outer_lst$lvl1_df %>% filter(` <kbd>TAB</kbd>
`outer_lst[[2]] %>% filter(` <kbd>TAB</kbd>
The `chainObjectName` e.g. `outer_lst$lvl1_lst$inner_df` goes  through `.rs.getAnywhere()` which I believe is ok, since other paths retrieve completions, e.g. 
> Indicate whether this change includes unit tests or integration tests, or link a work item or pull …

Chain completions with more complex `chainObjectName`

---

src/cpp/core/system/PosixSystemTests.cpp
src/cpp/rstudio-tests.in

Continue investigating failing tests
Try checking for LSOF from inside the actual test binary.
Trying to fix them.
Test only change.

More LSOF failure investigation

---

src/cpp/session/include/session/prefs/UserPrefValues.hpp
src/cpp/session/include/session/prefs/UserStateValues.hpp
src/cpp/session/prefs/UserPrefValues.cpp
src/cpp/session/prefs/UserStateValues.cpp
src/cpp/session/resources/schema/user-prefs-schema.json
src/cpp/session/resources/schema/user-state-schema.json
src/gwt/src/org/rstudio/studio/client/rsconnect/RSConnect.java
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSAccountConnector.java
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectPublishButton.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessor.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserPrefsAccessorConstants_fr.properties
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessor.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessorConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UserStateAccessorConstants_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PublishingPreferencesPane.java

I create the `enable_cloud_publish_ui` in Global Options -> Publishing as a user state, based on the way the similar option was configured for RS Connect. Unfortunately, if we want admins to be able to set the default preference in a file (`rstudio-prefs.json`) then I think it has to be a user preference, not a user state. This is necessary because we want this option to be off by default in RStudio Desktop/other IDE products, but allow the Cloud-hosted instance of the IDE to turn it on by default. Migrating this to User Prefs so the Hosted team can manage that via file on their end.

Change enable_cloud_publish from a user state to a user pref

---

dependencies/common/install-quarto
dependencies/windows/install-dependencies.cmd
dependencies/windows/install-quarto/get-quarto-version.ps1
docker/jenkins/Dockerfile.bionic
docker/jenkins/Dockerfile.centos7
docker/jenkins/Dockerfile.jammy
docker/jenkins/Dockerfile.opensuse15
docker/jenkins/Dockerfile.rhel8
docker/jenkins/Dockerfile.rhel9

Pins Quarto to 1.2.269, the current latest release.
Moved some lines around to group the version settings together. Changed the URL version check to use the release versions as well so that patch releases will use those instead of prerelease.
`install-quarto` and `install-dependencies.cmd` are the scripts that download and unpack quarto and are called from the Dockerfiles for the build.
Ran on Windows and Mac to confirm 1.2.269 is installed
None

Pin Quarto 1.2.269

---

src/cpp/session/modules/SessionRCompletions.R
src/cpp/tests/testthat/test-auto-completion.R
src/gwt/src/org/rstudio/studio/client/common/codetools/Completions.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionCache.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/yaml/YamlCompletionManager.java

addresses #12326
`.rs.matchCall()` uses `numCommas` (as identified by the client) to decide whether to keep unnamed arguments. 
unit tests: https://github.com/rstudio/rstudio/blob/bf7a8c97300729e555146465ffe006aaab75ecb8/src/cpp/tests/testthat/test-auto-completion.R

Adjust `.rs.matchCall()` to keep unnamed arguments only before the cursor

---

src/gwt/src/org/rstudio/studio/client/common/compile/CompileOutputBufferWithHighlight.java

Address #12354
Periodically flush the saved output so the user can see build progress. I don't think this would have an adverse effect on the ability to display the output since the `onCompileCompleted()` would submit everything that was saved.
None
Building the Quarto book mentioned in #12354 has enough output to display a message that output would be buffered.

Flush build pane buffer periodically

---

src/cpp/session/modules/SessionHelp.R
src/cpp/session/modules/SessionRCompletions.R
src/gwt/src/org/rstudio/studio/client/common/codetools/Completions.java
src/gwt/src/org/rstudio/studio/client/common/codetools/RCompletionType.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionCache.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpStrategy.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java

addresses #12356
Make the completions in the `group_by()` special case `COLUMN` completion types. 
This also thinks about order of completions being first driven by the types, and then later by `scoreMatch()` so that we can make sure we get the completions in the preferred order (arguments, column, ...). This might need more work/discussion. 
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in the linked …

Improve `group_by()` specific completions

---

src/gwt/www/rstudio.css

See: https://github.com/rstudio/rstudio/issues/12362
If long static pages are loaded, which is usually just `keyboard.htm`, then there is no scrolling enabled. This is due to a change to the css file that fixes the viewport to the window boundaries. We do not want to hide overflowing content if it exceeds the limits of the page.
Add `overflow: auto` to the `html, body` section so that overflowing content will receive scrollbars. The only page this really affects is the `keyboard.htm` page, as the others are already laid out relative to the viewport boundaries. I already verified the other static files by loading them in a browser to check that they were not going to be broken by this change.
N / A - visual pass only. I verified this in Firefox, Chrome, and Safari

Fix scrolling on html pages that are much larger than the viewport

---

docs/user/rstudio/ide/guide/accessibility/screen-reader.qmd

The move to Electron opens up the ability for Desktop to support screen-reader software, so update the documentation.
Updated the user guide and the equivalent support article (https://support.posit.co/hc/en-us/articles/360045612413-RStudio-Screen-Reader-Support) to mention the following:
* 2022.12 and newer (Desktop open source) now support screen-readers
* RStudio Desktop Pro does not at this time
* the keyboard shortcut on Mac for enabling screen-reader support has changed in Elsbeth
Docs-only changes
Check user guide and the support article (already updated).

update docs to mention Electron screen-reader support

---

src/cpp/server/extras/systemd/rstudio-server.redhat.service.in
src/cpp/server/extras/systemd/rstudio-server.service.in

Address #12371 
Use an absolute path when invoking `kill`. It used to call `killall` and it was an absolute path.
None
I don't have Ubuntu 18 so I tried this on Ubuntu 22 as a sanity check.

Use absolute path in rserver-service

---

src/cpp/server/extras/systemd/rstudio-server.service.in

Address #12371 
`/usr/bin/kill` may not be present on all platforms and `/bin/kill` appears to be available.
None
Jeff and I checked these platforms for the existence of `/bin/kill`. It is available on:
* RHEL 7/8 
* CentOS 7
* SLES 12.5
* OpenSUSE 15.2
* Ubuntu 18/22

Fix service reload Ubuntu 18

---

src/cpp/session/modules/SessionRCompletions.R
src/cpp/tests/testthat/test-auto-completion.R

Support the optional element `suggestOnAccept` in server side completions. This will be useful when e.g. we do: 
we accept `.by = ` and the server side "knows" there are possible completions for `.by = `
Added support in `.rs.makeCompletions()`, `.rs.subsetCompletions()` and `.rs.appendCompletions()`
added tests in `test-auto-completion.R`

Support optional `$suggestOnAccept` in server side completions

---

src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java

addresses #8675
More `\\` are needed in `quoteIfNotSyntacticNameCompletion()`
https://user-images.githubusercontent.com/2625526/205659154-7670b4e8-3ad1-481d-93f6-e92873e35041.mov
it seems the other issue from #8675 is already fixed:

`quoteIfNotSyntacticNameCompletion()` needs more backslash

---

NEWS.md
src/gwt/src/org/rstudio/studio/client/common/compile/CompileOutputBuffer.java
src/gwt/src/org/rstudio/studio/client/common/compile/CompileOutputBufferWithHighlight.java
src/gwt/src/org/rstudio/studio/client/common/compile/CompileOutputDisplay.java
src/gwt/src/org/rstudio/studio/client/common/compile/CompilePanel.java
src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobOutputPanel.java
src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsDisplayImpl.java
src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsPaneOperations.java
src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsPaneWidgets.java
src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/LauncherJobsPaneWidgets.java

Address #12389 
Call `compileCompleted()` once the job finishes or when the output is shown to ensure the output buffer is flushed. Added a check for changing stop button visibility since it isn't available when viewing the background jobs list.
None
The output buffer will be flushed when:
* watching the output as the background job runs 
* selecting a finished background job

Call completion event for background jobs

---

src/cpp/r/RSexp.cpp
src/cpp/r/include/r/RSexp.hpp
src/cpp/session/modules/SessionEnvironment.R
src/cpp/session/modules/environment/EnvironmentMonitor.cpp
src/cpp/session/modules/environment/SessionEnvironment.cpp
src/cpp/tests/testthat/test-environment.R

addresses #12328 
based on @kevinushey suggestion. `listEnvironment()` loses its `pProtect` argument, and no longer protects individual objects from the environment, because they are already defacto protected by the environment. 
The caveat the environment that is traversed by `listEnvironment()` needs to remain protected for as long as `pVariables` is in use. 
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present …

`listEnvironment()` no longer protecting the values

---

Jenkinsfile
Jenkinsfile.macos.electron
dependencies/common/install-yarn
src/gwt/build.xml

Fix panmirror building in Jenkins
Install `yarn` using `npm` instead of downloading the script. This is how it is done in Linux aarch64 and ensures the Node install has Yarn.
The panmirror location is in a separate location from the source checkout. So Jenkins specifically needs a different location to check when building GWT.
None
None

Fix yarn and panmirror location

---

src/cpp/session/modules/NotebookPlots.R

This change looks a bit strange, because GitHub doesn't visualize non-breaking spaces (so it looks like there is no change). Nonetheless, this fixes a non-breaking space that was introduced in `NotebookPlots.R` and replaces it with a normal whitespace character, which should fix the failing 'R' tests that was occurring on certain [Jenkins pipelines](https://build.posit.it/blue/organizations/jenkins/IDE%2Fopen-source-pipeline/detail/main/1956/pipeline/2063).
N/A
N/A
Change will be validated when unit tests all pass on the open-source and pro pipelines.

Fix non-breaking space in NotebookPlots.R

---

src/cpp/session/modules/build/SessionBuildErrors.cpp

bring back the [Output | Issues] in testthat output:
regex update

update the testthat > 3 error regex

---

src/cpp/r/RSexp.cpp
src/cpp/r/include/r/RSexp.hpp
src/cpp/session/modules/SessionEnvironment.R
src/cpp/session/modules/environment/SessionEnvironment.cpp
src/cpp/tests/testthat/test-environment.R

related to #12328 (somewhat orthogonal to #12399)
Rework the internals of `hasExternalPtr` to more efficiently traverse, i.e. without relying on `listEnvironment`. 
With the code from #12328 that essentially just creates a big environment: 
```
> h <- hash::hash(1:120000, 1:120000)
> system.time(.Call("rs_hasExternalPointer", globalenv(), FALSE, PACKAGE = "(embedding)"))
user  system elapsed 
0.071   0.005   0.078 
```
where the same code on #12399 (which addresses the issue of #12328 without changing the traversing approach):
```
> h <- hash::hash(1:120000, 1:120000)
> system.time(.Call("rs_hasExternalPointer", globalenv(), FALSE, PACKAGE = "(embedding)"))
user  system elapsed 
0.414   0.030   0.465 
```
That half of a second is noticeable when this is called each time `canSuspend()` is …

rework `hasExternalPointer` internals

---

docker/jenkins/Dockerfile.bionic
docker/jenkins/Dockerfile.centos7
docker/jenkins/Dockerfile.jammy
docker/jenkins/Dockerfile.opensuse15
docker/jenkins/Dockerfile.rhel8
docker/jenkins/Dockerfile.rhel9

Getting ahead of the builds since a change just went in that changes where to look for the `panmirror` source. The Docker images won't update the image layer to pull the new `panmirror` code. This change ensures the changes are pulled in so the builds will continue to work.
Grabs the latest commit SHA for the repo where `panmirror` lives and will break the image layer cache if it changes.
None
Ran the docker build locally and it detects a commit change. A second run uses the cache.

Break image layer cache if panmirror source is updated

---

src/cpp/session/modules/environment/SessionEnvironment.cpp

Followup to #12408, dealing with https://github.com/rstudio/rstudio/commit/b735c1582c8088cc8939c93131573e238808f985#commitcomment-93066075
This initially came up because of deferred strings, i.e. made by this function in `altclasses.c`: 
```c
attribute_hidden SEXP R_deferred_coerceToString(SEXP v, SEXP info)
{
SEXP ans = R_NilValue;
switch (TYPEOF(v)) {
case INTSXP:
case REALSXP:
PROTECT(v); /* may not be needed, but to be safe ... */
if (info == NULL) {
PrintDefaults(); /* to set R_print from options */
info = ScalarInteger(R_print.scipen);
if (strcmp(OutDec, ".")) {
/* non-default OutDec setting -- attach as an attribute */
PROTECT(info);
if (R_OutDecSym == NULL)
R_OutDecSym = install("OutDec");
setAttrib(info, R_OutDecSym, GetOption1(R_OutDecSym));
UNPROTECT(1); /* info */
}
} …
```

deal with dotted pairs in `.rs.hasExternalPointer()`

---

src/node/desktop/src/main/detect-r.ts
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/ui/widgets/choose-r.ts

Partially but sadly not at all fully address #12452
For one user, this failed because C:\Windows\System32 wasn't on their path, so we use the absolute path to `reg.exe` rather than the shorthand `reg` to query the registry. For all other users, we haven't figured out exactly what the error is yet. Partly because logging is currently mostly useless. Adding a bunch more error logging here so we can at least get some useful feedback from users who do encounter this issue, now and in the future

Add logging for windows registry query / R installation search; plus fix system32 path issue

---

docker/jenkins/Dockerfile.rhel9

Instead of `curl` to remove conflict with `curl-minimal` dependency of `RPM`.
Change rhel9 docker images to use `curl-minimal` instead of `curl` to remove conflict with `RPM`'s dependencies. Keep `libcurl-devel` unchanged, however.
For a while now the rhel9 docker images have failed during `PullBuildPush` with the following error while `yum install`-ing dependencies:
```
Error: 
[2022-12-22T00:40:14.597Z]  Problem: problem with installed package curl-minimal-7.76.1-19.el9.aarch64
[2022-12-22T00:40:14.597Z]   - package curl-minimal-7.76.1-19.el9.aarch64 conflicts with curl provided by curl-7.76.1-19.el9.aarch64
[2022-12-22T00:40:14.597Z]   - conflicting requests
```
`curl-minimum` is a dependency of `RPM`, so pretty hard to get around. The automatic suggested fixes: …

Use `curl-minimal` in rhel9 docker image

---

src/node/desktop/src/ui/modal-dialog.ts

Address #12487 
The Electron update defaults the `nodeIntegration` browser window preference to false, which prevents the preload script from running. The preload is necessary to hook up the UI listeners and populate the R versions. No other dialogs use a preload script so this is the only one affected.
None
The choose R dialog is available in the preferences in the General section. This is the only dialog affected.

Fix unpopulated choose R dialog

---

dependencies/common/install-sccache

This is a temporary fix to prevent the sccache install script from running on macOS until rstudio/rstudio#12532 is implemented.
Instead of moving the script, we can just prevent the install from running for now.

Prevent sccache install script on macOS

---

src/cpp/r/R/Api.R
src/cpp/session/modules/SessionDiagnostics.R
src/cpp/session/modules/SessionMarkers.cpp
src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/DiagnosticsBackgroundPopup.java
src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/LintMarkers.java
src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/model/AceAnnotation.java
src/gwt/src/org/rstudio/studio/client/workbench/views/output/lint/model/LintItem.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetLintSource.java

addresses #12425 
Avoid to create an `AceAnnotation` with both `.text` and `.html` because otherwise `.text` is prefered as per this code in ace: 
```js
var annoText = annotation.text;
annoText = annoText ? lang.escapeHTML(annoText) : annotation.html || "";
```
_Alternatively, the ace code could use `annotation.html ?` instead of `annotation.text ?` so that the html version would have priority._ 
Save this file as `test.R` in the current working directory: 
```r
tmpfile <- "test.R"
foo <- cli::bg_br_white(cli::col_red("I am red!"))
bar <- cli::bg_br_yellow(cli::col_cyan("I am …
```

ansi escapes in custom source markers

---

src/cpp/core/include/core/system/System.hpp
src/cpp/core/system/PosixSystem.cpp

We have an existing utility to look up the creation time of a process, but the only implementation is for Linux. This has been fine so far, as Launcher seems to be the only consumer of this API, but the compile-time guard is now generating issues for us when trying to build that project on macOS.
So this commit stubs out a macOS implementation that returns an error. Ideally, we'd actually implement this for macOS, but doing so [turns out to be nontrivial](https://stackoverflow.com/questions/31603885/get-process-creation-date-time-in-osx-with-c-c) so I don't think it's worth pursing at this time.
This should supersede https://github.com/rstudio/rstudio-pro/pull/3964. 
This change is a stub to avoid linker issues, so I don't think it needs any automated tests beyond "it compiles on macOS …

Stub out a process creation time lookup for macOS

---

utils.groovy

This change updates the addRemoteRef utility for Jenkinsfiles to use credentials when performing a git fetch, which is needed for private repositories such as our pro repo. This should fix the currently failing builds for PRs in the pro repo.
We can use a `withCredentials` block so the git commands have the proper credentials for the fetch command
N/A
N/A
N/A

Update addRemoteRef to use credentials for fetch

---

dependencies/common/install-sccache
package/osx/make-package

Adresses #12532. Add ssccache support for macOS builds.
Updated the sccache install script to support installing on macOS, and update the osx/make-package script to use sccache if the SCCACHE_ENABLED environment variable is set. I tested this on arm64 macOS the build seemed to succeed.
N/A
N/A
N/A

Update install-sccache with macOS support

---

Jenkinsfile.pull-request

This commit updates the Jenkinsfile.pull-request file to use the docker image tagging scheme that utilizes the version flower name. Since #12535 was merged, all jobs should be using the new flower name scheme for docker image tags. I also updated to use environment variables rather than globals.
N/A
N/A
N/A
N/A

Update PR Jenkinsfile to use flower image

---

Jenkinsfile

OS Mac Builds weren't being triggered because we moved the folder containing our non mac builds.
Fixed by adding the folder name to the conditional triggering the mac builds
Get Mac builds triggering again
Added full path to the conditional that triggers the mac builds
The display name and 'real' name of the `Open Source Builds` folder differ, I double checked in several build's outputs to directly read the JOB_NAME env variable to confirm the path.
None, build only change
None build only change
None build only change

Fix OS Mac Builds

---

NOTICE
package/win32/make-package.bat
src/cpp/diagnostics/DiagnosticsMain.cpp
src/cpp/r/R/Diagnostics.R
src/node/desktop/package-lock.json
src/node/desktop/package.json
src/node/desktop/src/core/logger.ts
src/node/desktop/src/core/winston-logger.ts
src/node/desktop/src/main/session-launcher.ts

Fix some issues with the Electron logging and diagnostics features to help with troubleshooting.
NOTE I am targeting Elsbeth branch.
Addresses #12556 (and several other issues described below)
* stopped using and removed the `winston-daily-rotate-file` package (it never created `rdesktop.log`, only numbered log files, breaking the assumption in our diagnostics flow to always look for `rdesktop.log`)
* use the built-in log rotation feature of winston which does create/use `rdesktop.log`; set it to match the defaults of a max of 100 rotated logs and max log size of 2 MB (we don't currently obey `logging.conf` for these settings on desktop, but according to the Workbench docs those are the defaults)
* don't log from diagnostics[.exe]; it was emitting non-useful logging statements into the …

Assorted desktop logging fixes (electron)

---

NEWS.md
src/cpp/server/ServerLoginPages.cpp

Easy accessibility fix.
Addresses https://github.com/rstudio/rstudio-pro/issues/4096 (Sign-in page logo has incorrect / inadequate alt-text).
Issue was opened in rstudio-pro repo but also applies to open-source server.
Change the alt-text from "RStudio Server Logo (goes to external site)" to "Posit Software PBC (goes to external site)" to better represent what the link is for.
Also updated the target from "https://www.rstudio.com" to "https://posit.co".
None
With a screen reader running, either use Tab/Shift+Tab to move focus to the image, or the screen-reader cursor, and confirm that the alt text has been updated. Also try clicking the link to ensure it goes to posit.co.
N/A

adjust sign-in page logo text and link

---

Jenkinsfile

Remove the Windows dependency install stage (#2212)
The Windows builds are already using the new dependency location so the dependency stage can be removed.
None
None
None

Remove dependency stage from Windows build

---

src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPaneEditorStyles.css

Addresses the code background color bug in #11520.
Sets the `background-colour` of the `div.sourceCode` to the light or dark code background color, depending on the active theme. The `border-radius` is also set to the same value as `pre`, otherwise the code box loses the rounded corners.
**Note:** The code background grey color is defined in `HelpPaneEditorStyles.css` and there is one grey used for all dark themes and another grey used for all light themes. It's possible the grey could be incompatible with some of the dark or light themes from an accessibility standpoint. Should a code background color be …

Fix help pane scrollbar code background color

---

Jenkinsfile
Jenkinsfile.macos
Jenkinsfile.macos.electron

Addresses https://github.com/rstudio/rstudio-pro/issues/3022.
The `jenkins-aws` credential will be turned off by CI at the end of the day today. We've removed it as part of our Jenkins restructuring, but those changes are sitting in an epic branch and it won't be merged into `main` for at least a week, so fixing this now.
Switch to `ide-build` or `aws-build-role` instead
N/A. Build system change
N/A Build system Change
N/A Build system change

Remove `jenkins-aws` credentials

---

src/cpp/r/RSexp.cpp
src/cpp/r/include/r/RSexp.hpp
src/cpp/session/modules/environment/SessionEnvironment.cpp

addresses #12591
Define and use the `r::sexp::getExternalPtrProtected()` and `r::sexp::getExternalPtrTag()` functions. 

not using `EXTPTR_PROT` and `EXTPTR_TAG`

---

src/cpp/core/Database.cpp

Right now we don't have much load on the database, but recent scalability testing surfaced many `database is locked` errors from the login flow in the logs. In some cases these errors are merely advisory, but in others they propagate up into issues in the UI.
Currently, we run the SQLite database in the default "rollback journal mode". The most common advice for addressing `database is locked` issues is to instead enable WAL mode, which allows readers and writers to operate concurrently, and offers much better performance in general.
So this commit enables WAL mode on our database.
Note that locking issue are not completely eliminated. From SQLite's [documentation on WAL mode](https://sqlite.org/wal.html#sometimes_queries_return_sqlite_busy_in_wal_mode):
> [An advantage] of WAL-mode is …

Enable WAL mode and set a busy timeout for SQLite connections

---

src/cpp/core/http/Message.cpp
src/cpp/core/http/Util.cpp
src/cpp/core/include/core/http/Message.hpp
src/cpp/core/include/core/http/Response.hpp

At present, we compress static files at runtime to reduce the bandwidth cost of sending them over the network. Unfortunately, this compression is by no means free, and we incur significant CPU overhead to serve files this way (not to mention the latency added while we do so).
This has an especially large performance impact for the large Javascript/CSS assets on the Workbench Homepage, which are static files that never change.
It's common practice to avoid the runtime compression cost for static assets by precompressing the files beforehand, either with Gzip or, more commonly these days, with Brotli.
This commit modifies the static file handler to substitute in precompressed files when they exist, much like NGINX's popular `gzip_static` and `brotli_static` directives.
Note that this patch …

Add support for serving static files precompressed with Gzip/Brotli

---

src/cpp/session/modules/environment/SessionEnvironment.cpp

addresses #12456
Based on: 
```c
#define BNDCELL_TAG(e)	((e)->sxpinfo.extra)
static R_INLINE SEXP BINDING_VALUE(SEXP b)
{
if (BNDCELL_TAG(b)) {
R_expand_binding_value(b);
return CAR0(b);
}
if (IS_ACTIVE_BINDING(b)) return getActiveValue(CAR(b));
else return CAR(b);
}
```
> Specify which documentation has been added or modified and why (User …

immediate bindings don't have external pointers

---

NEWS.md
src/cpp/session/SessionSuspend.cpp

Large sessions can be CPU-intensive to serialize, and customers have often reported mysterious CPU spikes that were tracked down to session suspension. This CPU spike can be particularly inconvenient when it is caused by previously-dormant sessions that time out and are auto-suspended by Workbench on a busy system.
Recently, [a customer asked](https://app.prodpad.com/feedback/874d975e-9b8c-11ed-a544-2a7db0eb1d9c/canvas) if we could lower the session process's nice value right before suspending it. This seemed like a good idea to me, so this commit implements this for macOS and Linux. We could also do it on Windows with `SetPriorityClass()`, but on that OS the likelihood of being a multi-user system is much lower.
This change doesn't eliminate the CPU required to suspend, of course, (or …

Lower CPU priority during session suspend

---

NEWS.md
src/cpp/session/SessionHttpMethods.cpp
src/cpp/session/SessionSuspend.cpp

Users sometimes raise concerns about the number of nonzero exit codes they see from Workbench sessions on Slurm and Kubernetes (see one [recent example](https://rstudio.slack.com/archives/C7312LBPY/p1670494955085729)). This is because we use exit code 101 and 103 to signify switching between projects and suspending, respectively, both of which are common operations in these environments.
This only affects Workbench. I extracted my original patch from that repo because it only affects the open-source codebase.
It seems that we don't rely on the exit code when running sessions under Launcher at all, so this is an easy change to make.
I don't think there are any automated tests for this. In my manual testing, switching between projects and suspending sessions continues to work just fine with …

Avoid non-zero exit codes when running sessions under Launcher

---

src/gwt/acesupport/acemode/dcf_highlight_rules.js

Small feature-let to support highlight of DCF field names containing slashes.
Straightforward update of Ace highlight rules.
N/A
N/A
None required.

allow slashes in DCF field names

---

src/gwt/src/org/rstudio/studio/client/workbench/views/help/model/HelpInfo.java

address #12568 as a followup to #10844
Make `parseArguments` more forgiving of free form `Arguments` section such as those when documenting R6 objects with `\section{Arguments}` ...

forgiving parsing free form Arguments section

---

NEWS.md
src/node/desktop/src/main/desktop-browser-window.ts

To address #12494 and #12413, this PR removes code that can lead to urls being opened multiple times.
`allowNavigation()` checks if navigation should be allowed, but in the final `else` case, it also opens the specified url via `shell.openExternal()`.
This side effect of opening the url should be removed from the function because the function should only serve a single purpose: to check if navigation should be allowed.
Other code which calls `allowNavigation()` uses the boolean result to determine if the url should be opened or not (and opens the url accordingly), which seems to be why multiple opens are getting triggered (`allowNavigation()` may open a url and the calling code may open the url again).
N/A
- Follow steps from issue description #12494 and #12413
- Test on both Chrome and …

remove `openExternal` call from `allowNavigation` check 

---

NEWS.md
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/satellite-window.ts

Addresses #12468 and #12569.
Catches the error causing the gwt callback to fail partway through opening up data viewer files and shiny apps in a satellite window.
The underlying issue appears to be that some satellite windows are not unregistered once they are returned to the main window. As a result, when we iterate through the list of owners to find the `GwtWindow` that sent the "Open in new window" event, we hit some objects that have been destroyed (`TypeError: Object has been destroyed`), but not removed from the list of owners. Since the gwt callback errors out, we don't end up populating the window with the data being popped out from the main window.
This PR is stopgap fix to catch the error and continue iterating through the loop to find the correct owner. The data is then …

Fix blank satellite window for data viewer and shiny apps

---

src/node/desktop/src/main/application.ts

Closes https://github.com/rstudio/rstudio/issues/12580.
Use XDG data directory.
N/A
Test that RStudio no longer creates a file called `~/rstudio`.
N/A

use user data dir for message server socket

---

dependencies/tools/upload-quarto.sh

Part of #12697 
Upload the linux rhel7 quarto builds to the S3 bucket. The initial build after merging rstudio/rstudio-pro#4303 failed because the rhel7 build of quarto wasn't available in the S3 bucket: https://build.posit.it/blue/organizations/jenkins/IDE%2FOS-Builds%2Fopen-source-pipeline/detail/main/2049/pipeline. I manually uploaded the tarball to resolve the build issue, but this PR adds the rhel7 build to our upload script. 
> Add additional …

add rhel7 builds to quarto upload script

---

NEWS.md
src/node/desktop/src/main/main-window.ts

A follow-up to PR #12660 to address the iframe (subframe) external browser navigation bug for issues https://github.com/rstudio/rstudio/issues/12494 and https://github.com/rstudio/rstudio/issues/12413.
In this PR, I narrow the scope of which iframe requests should have their urls opened externally (basically we want to avoid requests where the iframe src url is being requested).
Note: we should refactor this code once the [`will-frame-navigate` event is available](https://github.com/electron/electron/pull/34418).
To specifically target iframes which trigger navigation to external urls, we need to check that `details.frame?.url` exists. Otherwise, we end up opening external browser windows for requests to load the url for iframe `src`'s. 
Thank you @kevinushey for the extra context you …

Avoid external browser navigation when loading iframe src

---

src/cpp/session/modules/SessionRCompletions.R

Followup on #12678 
#12709 introduced a bug because it started to make use of the `$context` in completions, but it was not properly handled in `.rs.subsetCompletions()` and `.rs.appendCompletions()` so we sometimes had a smaller `$context` compared to the `$type` which was the cause for https://github.com/rstudio/rstudio/issues/12678#issuecomment-1433466281
> Add additional information for QA on how to validate the change, paying special attention to the level of risk, adjacent areas that could be affected by the change, and any important contextual information not present in …

handle "context" in .rs.sortCompletions() and .rs.appendCompletions()

---

src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/ui/modal-dialog.ts
src/node/desktop/src/ui/widgets/choose-r.ts
src/node/desktop/src/ui/widgets/choose-r/preload.ts

Addresses #12487, more specifically https://github.com/rstudio/rstudio/pull/12518#issuecomment-1371221990
Disable node integration from preload and renderer scripts. Electron 20 limited Node.js modules allowed in preload scripts to `events`, `timers`, and `url` so this PR refactors calls to `fs` and `path` to the main process.
N/A - no noticeable user change. 
This change should be invisible from the user's perspective. On Windows, the choose R modal should continue to load, populated with the available R versions.
N/A - no new functionality

Remove node from choose R modal

---

package/linux/rpm-script/postinst-desktop.sh.in
package/linux/rpm-script/postinst-electron.sh.in

Addresses #12614 
Fedora 37 installs of rstudio displayed the following error, but appeared to work as expected:
```
ln: failed to create symbolic link '/usr/lib/rstudio/bin/libssl.so.1.0.0': No such file or directory
ln: failed to create symbolic link '/usr/lib/rstudio/bin/libcrypto.so.1.0.0': No such file or directory
```
This was failing because `/usr/lib/rstudio/bin` didn't yet exist. Creating the directory before the symlinks resolves the issue. 
N/A
The product should install without error.
N/A - install bug fix

Fix fedora 37 symlink bug

---

src/cpp/session/modules/SessionQuarto.R
src/gwt/src/org/rstudio/studio/client/panmirror/PanmirrorWriterReferencesOptions.java
src/gwt/src/org/rstudio/studio/client/panmirror/command/PanmirrorCommands.java
src/gwt/src/org/rstudio/studio/client/panmirror/command/PanmirrorToolbarCommands.java
src/gwt/src/org/rstudio/studio/client/panmirror/uitools/PanmirrorPandocFormatConfig.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/visualmode/VisualModeMarkdownWriter.java

@timtmok This is a change intended to support the visual editor's new `editor: markdown: references: links` option (as described here: https://quarto.org/docs/visual-editor/vscode/#links)
My Homebrew installation on my dev Mac has become corrupted so I'm not actually able to compile/test this! In any case we should pair program on landing the change so you know what's going on. Message me when a good time to do this next week might be (I'll mark this PR as a draft in the meantime).

support for visual editor reference links option

---

src/cpp/core/SocketRpc.cpp
src/cpp/core/include/core/http/Response.hpp
src/cpp/core/include/core/json/JsonRpc.hpp
src/cpp/core/json/JsonRpc.cpp
src/gwt/src/org/rstudio/core/client/jsonrpc/RpcError.java
src/gwt/src/org/rstudio/studio/client/server/ServerError.java
src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServerError.java

This puts in place the necessary pieces to show an error to the user in the event that a workbench job submission returns a redirect, which we currently don't support
Open source portion to address rstudio/rstudio-pro#2423
In the event that a workbench session issues a redirect, the user can be notified of the issue and recommendations given to fix the most common problem.
Instead of simply returning true or false, the error is also propagated back up through the session to the ui.
Messaging changes, low risk.
See workbench pr
Documentation is not updated for this.

Open Source Portion of 2423 User Warning Effort

---

dependencies/common/install-panmirror

The visual editor dependency has a `release/rstudio-cherry-blossom` branch now (https://github.com/quarto-dev/quarto/commits/release/rstudio-cherry-blossom). This will only get bug fixes from `main`.
Update dependency installer scripts to checkout the `release/rstudio-cherry-blossom` branch or switch to it if the repository has already been cloned.
n/a
This pulls commits from the branch link above. There may be changes from `quarto-dev/quarto` `main` that won't be included since the last build because the `main` branch has already diverged.

Switch visual editor to cherry blossom branch

---

NEWS.md
src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
src/gwt/src/org/rstudio/studio/client/workbench/exportplot/clipboard/CopyPlotToClipboardDesktopDialog.java
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/renderer/desktop-bridge.ts

Addresses #12466. Avoids the "shifted" screen capture when copying a plot to the clipboard using `Export > Copy to Clipboard... > Copy Plot (Bitmap)` from the `Plots` pane. Note that this only seems to occur on Windows.
<details>
<summary>sample images before/after</summary>
- some parts of the RStudio UI are getting captured and the some of the plot is missing
- only the plot is captured and no parts of the plot are missing
</details>
As a note, I was running into [this issue](https://github.com/rstudio/rstudio/issues/11739) when debugging and building this fix.
Instead of drawing a rectangle around the plot image and using a page capture method to "screenshot" the plot and copy it to the clipboard, this PR uses Electron's `webContents.copyImageAt()`, which locates the `img` element at …

Fix incorrect bitmap plot image copying

---

NEWS.md
src/cpp/core/r_util/RToolsInfo.cpp
src/cpp/session/modules/build/SessionInstallRtools.R
src/cpp/session/modules/build/SessionInstallRtools.cpp

Address #12528 
Update the logic to also check for RTools 4.3 if using R 4.3.x. Renamed `findRtools42Installer` since it can be used for 4.3 (and maybe >4.3).
A companion change for the fallback link redirect: https://github.com/rstudio/rstudio-web/pull/41
I think the code could also be refactored so there's less copy/paste if we're confident that the RTools release will be hosted the same way for versions >4.3.
None
This required R 4.3, which is currently available in dev builds. https://cran.r-project.org/bin/windows/base/rdevel.html
`.rs.findRtoolsInstaller("https://cran.rstudio.com/bin/windows/Rtools/rtools43/rtools.html", "some fallback link to rtools")` could be called to ensure it finds the link to the RTools installer. I don't think this is used anywhere else but the function used …

Support rtools 4.3

---

package/win32/make-package.bat

Addresses #12684 
Unintentionally introduced a space at the end of "Electron " in the Windows make-package batch file, which caused comparisons to "Electron" to fail, thus electron-specific build steps weren't happening.
As a result the build version wasn't being stamped into the Electron app and `rstudio --version` would return 99.9.9.
It also failed to embed the .rproj icon.
Tweaked the batch file to fix this, also added a bit of documentation on setting version environment vars to the `make-package --help` output.
None
Verify that running rstudio.exe --version shows the version number (and not 99.9.9), and that .rproj icons are back again in Windows Explorer.
None

Fix version stamping and rproj icon for Windows

---

src/cpp/core/include/core/Thread.hpp
src/cpp/shared_core/include/shared_core/system/Crypto.hpp

RStudio fails to build with gcc13 due to a couple of missing headers from the STL.
Here I add them as suggested by gcc's own error messages. One is for uint types, the other is for sets.
No additional tests.
The change is simple enough. No risks identified.
No additional docs.

add missing headers for gcc13

---

dependencies/windows/install-panmirror/clone-quarto-repo.cmd

My original PR to get the visual editor on the `release/rstudio-cherry-blossom` branch didn't include Windows. This changes the checkout to get only changes intended for the Cherry Blossom release.
Modify the git script that handles the visual editor
I've run the dependency installer on Windows with and without the repo cloned to test a repo update and clone.
None 
None

Use cherry blossom visual editor for Windows

---

dependencies/common/install-panmirror
dependencies/common/install-quarto
dependencies/windows/install-dependencies.cmd
dependencies/windows/install-panmirror/clone-quarto-repo.cmd
dependencies/windows/install-quarto/get-quarto-version.ps1

Move back to using the 1.3 pre-release for Quarto and the `main` branch for the visual editor. 1.3 should be ready by April.
Modify dependency scripts to use pre-release and `main`. The visual editor script does a checkout of `main` now to handle being on another branch.
None
None
We can update the README with the Quarto version when the version is pinned for the Mountain Hydrangea release.

Use latest quarto and visual editor

---

Jenkinsfile.pull-request
jenkins/Jenkinsfile.linux
jenkins/Jenkinsfile.nightly

This change contains a variety of updates for the Linux pipeline. 
I've added `deleteDir` as a post step to the agents that actually do the building. I think the last post step with `deleteDir` will only clean up the workspace on the top-level agent. 
I removed `reuseNode true` from the docker block since we are actually grabbing the linux agent for the matrix build and running within docker from the same step. 
I've also added `bionic` and `rhel8` to the `arm64` exclude list, which should fix the license-manager activation linker errors on the pro pipeline. The old pipeline didn't produce `bionic` and `rhel8` `arm64` builds.

Updates to Linux Pipeline

---

dependencies/common/install-sentry-cli

Fix failing pro builds.
Sometimes `/usr/local/bin` is available. In that case, we don't set an install dir, and the last line fails because `/sentry-cli` doesn't exist. This attempts to fix that by setting a `SENTRY_PATH` variable which is either `sentry-cli` or `${INSTALL_DIR}/sentry-cli`.
Another way we could fix it is to always install sentry to `${INSTALL_DIR}`.
Build system failure.
Build system failure.
None, build system failure.

fix a bug when /usr/local/bin is available

---

NEWS.md
src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java

Addresses #12741, #10600.
I also adjusted the NEWS.md structure to match what we did for Cherry Blossom.
When entering the Help pane via <kbd>Ctrl+3</kbd> ("Show Help Pane"), <kbd>F6</kbd> ("Focus Next Pane") or <kbd>Shift+F6</kbd> ("Focus Previous Pane"), place keyboard focus on the help content instead of the search box. This allows immediate scrolling of the content via the keyboard instead of hitting the tab key several times first.
When showing help from the Console (e.g. `?length`) keep the focus on the Console. This is how it used to behave (several versions ago).
More details:
* Removed the call to `setFocus()` from the end of HelpPane's `onSelected()` because it was causing the undesired focus switch when using `?foo` from the console. Having this call was unnecessary because the …

Fixes to Help Pane keyboard focus behaviour

---

src/cpp/session/modules/SessionFind.cpp
version/news/NEWS-2023.03.0-cherry-blossom.md

Addresses #11822 
Fix find in files when using older versions of git. 
Remove passing the `-C` argument to the `grep` command since we're already running the command from the working directory. See https://github.com/rstudio/rstudio/issues/11822#issuecomment-1452650385
I ran the existing unit tests and they continue to pass. 
This was broken on CentOS7 which has an older system version of git. It only affects git projects that have the "Exclude files matched by .gitignore" selection checked in the Find in Files pane:
Functionality should continue to work as expected with Find In Files and newer versions of git.
N/A - bugfix

Fix find in files with older versions of git

---

jenkins/Jenkinsfile.linux
utils.groovy

Add a build trigger for the QA Open Source Automation job after a linux build has finished
Tweak uploads to be consistent with the paths we use
Successful OpenSource build (this one only built `bionic` to speed up the build. previous full builds were also successful): https://build.posit.it/blue/organizations/jenkins/IDE%2FOS-Builds%2FPlatforms%2Flinux-pipeline/detail/jenkins-trigger-qa-automation/8/pipeline/1574/
Successful QA Build: https://build.posit.it/blue/organizations/jenkins/IDE%2Fqa-opensource-automation/detail/qa-opensource-automation/1779/pipeline
The QA job _won't_ be triggered for the following linux builds:
- Hourly Builds
- Builds that aren't published
- Builds on the `v1.4-juliet-rose` or `release-ghost-orchid` branches, because they don't have corresponding branches on …

Jenkins trigger qa automation

---

jenkins/Jenkinsfile.linux
jenkins/Jenkinsfile.macos
jenkins/Jenkinsfile.windows

Edit: timeout changed to 2 hours after feedback
[This build](https://build.posit.it/blue/organizations/jenkins/IDE%2FPro-Builds%2FPlatforms%2Flinux-pipeline/detail/epic-4140-jenkinsfile-restructure/38/pipeline/1468/) sat "in the queue" for 3 days before I noticed it. That absolutely should not happen. 
Rather than cap the build time at some high number (3-5 hours), we can opt to have builds timeout after not making any progress (no changes to a build's logs). I think 30 minutes seems a reasonable amount of time of inactivity to be confident that a build is stuck
Adds a `timeout` block to the Windows/Mac/Linux Jenkinsfiles. I _think_ that adding the timeout inside individual matrix builds in the Linux builds will only timeout that particular OS/ARCH/FLAVOR combination, rather than fail the …

Add timeout option to builds

---

NEWS.md
src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java

Addresses [Font size for help pane is misplaced in settings #12816](https://github.com/rstudio/rstudio/issues/12816)
Moved the setting where it belongs. Essentially cut and pasted code from one place to another; should be very low risk ("never say that out loud").
I _suspect_ it was added to General / Advanced because at the time the Global Options dialog was shorter, and the Appearances pane didn't have sufficient vertical space.
The Options dialog has since been made taller, and now has room for this control.
None; I did run existing gwt unit tests.
Verify that the setting functions correctly in the new location.
None

move help font size setting to appearance pane

---

NEWS.md
src/gwt/src/org/rstudio/core/client/theme/PrimaryWindowFrame.java
src/gwt/src/org/rstudio/studio/client/application/AriaLiveService.java
src/gwt/src/org/rstudio/studio/client/workbench/ui/ConsoleTabPanel.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleInterpreterVersion.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsolePane.java
src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleSuspendBlockedIcon.java

Addresses:
* [Invalid role on Console session suspend status icons #12449](https://github.com/rstudio/rstudio/issues/12449)
* [No-tabs console toolbar always visible to screen reader #12825](https://github.com/rstudio/rstudio/issues/12825)
- removed the role="alert" from the suspend and unable-to-suspend icons; we already issue a notification when a session suspends ("Backing up R session"), so having another one wasn't necessary
- also added alt-text to the icons (matching the titles): the titles are what you see if you hover over icons with the mouse; the alt-text is read when you navigate to the image with a screen reader
- marked the "dot" separator in toolbar as aria-hidden so it is ignored by screen reader (it is purely cosmetic)
- when the Console region has tabs, apply …

Accessibility fixes to Console region

---

jenkins/Jenkinsfile.linux

I mistakenly included the rstudio repo commit in the job trigger for the qa automation job, which doesn't make sense because that commit wouldn't exist in the qa automation repo so the QA job has been failing: https://build.posit.it/job/IDE/job/qa-opensource-automation/1787/parameters/
Don't send commit info to QA automation job trigger
N/A
N/A
N/A

Don't send unrelated and unneeded git commit info to QA automation

---

NEWS.md
src/gwt/www/rstudio.css
src/gwt/www/signin.css
src/gwt/www/templates/encrypted-sign-in.htm

Addresses [Low contrast focus rectangle on Sign In button (server login page) and other misc. A11y #12846](https://github.com/rstudio/rstudio/issues/12846)
- used same focus-visible styling as the workbench home page; add a tiny extra top margin to the input fields so the thicker focus rectangle doesn't bump up against the label
- removed use of the `focus-visible` polyfill from sign-in page, and just use native `focus-visible` now that it is supported by all browsers we support (the IDE itself is still using this polyfill so can't remove it altogether yet)
- removed skip-nav link from the sign-in page (and the associated styles; this was the only place using this); see the associated issue for why I'm removing it
- added `aria-required="true"` to the input fields
The button focused …

Accessibility tweaks to sign-in page

---

docs/news/index.qmd

Update release notes for IDE / Workbench 2023.03.0+386.pro1 release.
This change has been generated by the release script. Content is generated based on `version/news/NEWS-2023.03.0-cherry-blossom.md`. If this file was not in sync with Pro or did not include items from other sources (i.e. the vscode extension), then some items may be missing.  Please verify content/formatting is correct and make changes if necessary.

Update release notes for 2023.03.0+386.pro1

---

jenkins/Jenkinsfile.linux

The automated tests require version/RELEASE to be uploaded to generate Jenkinsfiles: https://github.com/rstudio/rstudio-ide-automation/blob/033abd769083dfd61e6eeebd8735d4cf1caf1179/Jenkins/fuzzbucket-template.Jenkinsfile#L43
Since all the generated templates are for linux builds, I've uploaded the artifact from the linux pipeline
Upload the version/RELEASE file from the linux pipeline
N/A build fix
The jenkins template job will need to be updated to pull artifacts from `IDE/OS-Builds/Platforms/linux-pipeline`
N/A

Archive version/RELEASE in linux builds for automated tests

---

docker/jenkins/Dockerfile.opensuse15

We've been building opensuse images on 15.1 for the last 4 years. This bumps the docker image to use the 15.4 base image.
Changes/removes packages to match 15.4 packages
Fixed `OPERATING_SYSTEM` env variable typo
Once approved I'll merge `rel-cherry-blossom` forward into main
Version bump
N/A Build change
N/A Build change
N/A Build change

Bump opensuse docker version to 15.4 and update packages

---

src/node/desktop/CMakeLists.txt
src/node/desktop/mac-terminal.in

Remove the unused `mac-terminal` script from Electron desktop. This was only used for the Tools / Shell command, which I removed from Electron in https://github.com/rstudio/rstudio/pull/11465.
Very safe; it wasn't even being included in the built RStudio.app (and the callback that used it was never implemented in Electron).
Delete delete delete
N/A
Nothing to test, deleting something that never made it into the product.
N/A

remove unused mac-terminal script

---

docker/jenkins/Dockerfile.opensuse15

15.4 doesn't have `libuser` and there are currently no community packages available. Switch to using 15.3 for our builds. We just switched to 15.4 from 15.1 here: https://github.com/rstudio/rstudio/pull/12890

Build on OpenSuse15.3 to use libuser package

---

src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java

Addresses https://github.com/rstudio/rstudio/issues/12874#issuecomment-1481867462 -- "Remind Later" doesn't make sense to show for an ignored update unless we want users to un-ignore versions.
Original PR: #12869.
Hide the "Remind Later" button when manually checking for an update and the newest update version is an ignored version.
N/A
See testing notes from #12874 and #12869.
<details>
<summary>extra notes when building and testing this locally</summary>
you might need to make the following change to `CMakeGlobals.txt` so that RStudio considers your local build out-of-date
```
set(CPACK_PACKAGE_VERSION_MAJOR "1000")
```
</details>
Steps
1. Upon RStudio startup, ignore the newest RStudio version update
2. Manually check for update using Help > Check for Updates
3. Dialog does not show …

hide remind later for manual ignored version check

---

NEWS.md
src/node/desktop/src/main/application.ts
src/node/desktop/src/main/gwt-callback.ts

Addresses [The title bar above the menu bar is light even in the dark theme (in daily builds) #12247](https://github.com/rstudio/rstudio/issues/12247)
Now that we're using a new-enough build of Electron, implement the callback to set the app's theme to match the RStudio theme (dark vs. light).
With this in place, the title bar, menu bar (on Windows) and system-supplied dialogs such as File Open will have their theme controlled by whether the RStudio theme is dark or light, not the operating system settings.
RStudio with dark theme on Windows:
Light theme:
N/A
Ideally, test on both Windows-10 and 11 and macOS. Could also spot-check on some Linux distros to see what the behaviour is (the Electron docs don't say much about this).
N/A

Sync electron theme (dark/light) with RStudio theme

---

NEWS.md
src/gwt/src/org/rstudio/studio/client/application/DesktopHooks.java
src/gwt/src/org/rstudio/studio/client/application/events/DesktopMouseNavigateEvent.java
src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java

Addresses https://github.com/rstudio/rstudio/issues/12932.
Electron appears to handle back / forward mouse buttons natively within iframes, so suppress the extra mouse handling we try to use in the iframe for Electron.
N/A
Test that mouse back / forward buttons work as expected when the mouse lies over:
- The Source pane (should navigate back and forward through Source locations);
- The Help pane (should navigate back and forward through Help locations);
- Other locations (should do nothing)
You can create multiple documents with e.g. Cmd + Shift + N to test the back + forward behavior in the Source pane, and use something like:
```
help(rnorm)
help(c)
help(help)
```
to open some Help topics to test back / forward navigation in the Help pane.
NOTE: This change should only effect the …

resolve issues with mouse back / forward navigation in Electron

---

NEWS.md
src/node/desktop/src/main/args-manager.ts

Addresses [rstudio fails to open projects using relative path from command line #12495](https://github.com/rstudio/rstudio/issues/12495) and [RStudio fails to open working directories using the command line #12563](https://github.com/rstudio/rstudio/issues/12563)
Three closely-related fixes:
(1) Resolve relative paths received on command-line to fully qualified paths (as was done in the Qt desktop)
(2) If a folder is passed on command line (i.e. no file), look for an .rproj in that folder and open that if present, otherwise just set the working directory to that folder (Qt desktop does this)
(3) in case 2, when an .rproj wasn't found, don't try to open the folder as a file (resulted in an error message and a blank editor pane)
Would be nice.
This isn't specific to Ubuntu 22 (as the issue …

fixes for opening files and projects using relative paths from command-line

---

src/cpp/session/SessionConsoleInput.cpp

Addresses https://github.com/rstudio/rstudio/issues/12908.
Addresses https://github.com/rstudio/rstudio/issues/12923.
If we want to reintroduce this as an always-on feature, I think we need to be more targeted in terms of what R objects we choose to scan for null pointers. IIRC we did this in the past because certain R objects would cause a session crash when trying to examine those objects (due to internal null pointers) but it might be better to just explicitly filter those objects out in the cases where examining those objects cause a crash.
I vaguely recall https://cran.r-project.org/web/packages/ff/index.html being one culprit but unfortunately don't have a reproducible example.

don't scan global environment for null pointers by default

---

dependencies/osx/install-dependencies-osx

`jq` needs to be on the PATH for macOS build agents in order to parse responses from GitHub when uploading to latest-builds
> Specify which documentation has been added or modified and why (User Guide? Admin Guide?). …

Add jq to macOS agent PATH

---

NEWS.md
src/node/desktop/src/main/preferences/electron-desktop-options.ts
src/node/desktop/src/ui/widgets/choose-r.ts

Addresses [RStudio (Windows Electron) fails to start session if certain R.exe selected by user #12969](https://github.com/rstudio/rstudio/issues/12969)
After user picks a custom R via browsing, perform fixups. Also do these fixups when loading the path from preferences to handle incorrect paths from earlier versions.
* if they chose `bin\R.exe` change that to `bin\x64\R.exe` (if they are on a 64-bit machine) or `bin\i386\R.exe` if on a 32-bit machine (if a user on a 64-bit machine wants to use 32-bit R, they'll have to browse specifically to it in the i386 folder)
* if they chose something other than R.exe, such as Rscript.exe, substitute R.exe (in addition to the path fixup)
Also, the file chooser dialog now prepopulates `R.exe` in the filename field, giving a hint about what they should …

Improve robustness of chosing custom R version via browsing on Windows (Electron)

---

src/node/desktop/src/main/detect-r.ts
src/node/desktop/src/main/preferences/electron-desktop-options.ts
src/node/desktop/src/ui/modal-dialog.ts
src/node/desktop/src/ui/utils.ts
src/node/desktop/src/ui/widgets/choose-r.ts
src/node/desktop/src/ui/widgets/choose-r/preload.ts

Addresses [RStudio failing to query R for path locations using R.exe on Windows but RTerm.exe works #12984](https://github.com/rstudio/rstudio/issues/12984)
On Windows, when checking if an R installation is valid (and when querying an R installation for various paths) use `Rterm.exe` instead of `R.exe`. Haven't isolated why, but on some customer configurations `Rterm.exe` works and `R.exe` does not. The R documentation suggests `Rterm.exe` is preferred on Windows (though it doesn't say why), and we used `RTerm.exe` in the Qt desktop for a similar exercise, so this seems like the "right thing".
Additionally, when checking the default 32/64-bit R installations found in the registry, check using the architecture-specific Rterm.exe instead of the generic `bin\R.exe`.
Added another diagnostic …

use Rterm.exe instead of R.exe on Windows when checking R installation status

---

src/cpp/server_core/ServerDatabase.cpp

Ensure we never check the database.conf settings without reading it at the configured location.
Only read the config file once by separating the function that checks the driver type and passing the existing config object.
I don't think we have anything around this. It was caught by @kevinushey when he tried to start a dev rstudio-server instance on MacOS. We could test by configuring an alternate path in one or more of our fuzzbucket environments.
If we configure an alternate database.conf location, we should get the settings it has, not the defaults. 
No documentation - we already document how to change the location, this just ensures it will work.

Always use the configured database.conf file

---

NEWS.md
src/node/desktop/src/main/args-manager.ts

Addresses [Poor experience starting RStudio desktop if user-state folder inaccessible #12988](https://github.com/rstudio/rstudio/issues/12988)
Our logging package (Winston) was throwing an uncaught exception, preventing a bunch of initialization code from running. Fixed by catching the exception and writing to stderr. This permits startup to continue so the window appears and existing error-handling code can report the problem.
Not pretty (especially on Windows), but at least it doesn't make it appear nothing happened, and the user can close RStudio instead of accumulating processes in the background.
None
On Mac and Linux, the main window should now appear and show basic error information.
The experience on Windows is still somewhat gruesome. R shows a modal dialog box with an error, …

Don't fail silently at startup when user state folder inaccessible

---

NEWS.md
src/node/desktop/src/renderer/desktop-bridge.ts
src/node/desktop/src/ui/utils.ts

Addresses [Can't save to scripts to UNC path from RStudio 2023.03.0 #12935](https://github.com/rstudio/rstudio/issues/12935) and [Saving New Scripts Or Changes to Existing Scripts Produces File Not Found Error #12652](https://github.com/rstudio/rstudio/issues/12652)
Code was incorrectly removing one of the leading backslashes from a UNC path.
Also noticed and corrected logging calls in the desktop-bridge.
None
Sanity test saving files to both UNC paths and regular paths with Windows Desktop (Electron). Note that any recent files entries created before this fix will be wrong, but new ones added with the fix should be correct.
N/A

Fix saving to UNC paths on Windows

---

src/cpp/r/include/r/session/RSessionState.hpp
src/cpp/r/session/RSessionState.cpp
src/cpp/r/session/RSuspend.cpp

For internal use; allows developers to set an environment variable to disable saving / restoring of workspace during suspend. This has been requested internally by some who find the slowness from RStudio's attempts to save + restore the workspace frustrating.
We might want to consider exposing this publicly in the future as a number of users find it frustrating when overly-large workspaces are saved and restored, as this attempt can fail if objects are too large (and some users might be comfortable just throwing it away)

add internal toggle for saving workspace

---

src/cpp/session/modules/SessionEnvironment.R
src/cpp/session/modules/environment/SessionEnvironment.cpp

Uses an alternate implementation to check whether a session is suspendable, using some heuristics to avoid overly-expensive lookups.
See PR.
N/A
N/A
N/A

alternate implementation for suspendable environment

---

NEWS.md
src/cpp/session/SessionConsoleInput.cpp
src/cpp/session/include/session/SessionOptions.gen.hpp
src/cpp/session/session-options.json

Adds two boolean session options:
- `session-connections-block-suspend`
- `session-external-pointers-block-suspend`
to control whether the above two things are checked when checking if a session is suspendable.
Straightforward update + generation of options.
N/A
Test that these settings do (or don't) block suspend as described. 
TODO

allow admin to control suspend behavior for connections / external pointers

---

src/node/desktop/src/main/utils.ts
src/node/desktop/test/unit/core/system.test.ts

Fixes for the following tests:
- System test `fixupExecutablePath adds missing exe extension on Windows`
- Utils test `findComponents returns session and scripts paths`
- The test previously used an incomplete file path that would cause the test to always fail on Windows
- Test was modified to check the extension matches `.exe` for Windows, and doesn't match for non-Windows
- enhancement on `findBuildRootImpl` in utils to only use package build dirs if the app is a package build
Fixes the scenario I was experiencing:
- Run a package build (doesn't have to be successful, you can cancel it partway through)
- Run electron unit tests (`npm test`)
- Will use the package build dir since it's the most recently modified build dir, but the test isn't running a package build and there may not be an …

fix windows-path-related test failures

---

src/node/desktop/src/main/utils.ts

Fixes https://github.com/rstudio/rstudio-pro/issues/4579
Might not be a coincidence after all! Seems like this issue started happening in a build that contained #13000.
Don't conditionally exclude the package directories from the possible build dir candidates. Just include them by default. (this was the behaviour before #13000).
The `findComponents` Electron unit test should pass on all platforms now.
1. Ensure you don't have any `build*` directories in `src/cpp`
2. Create a package build
3. In `src/node/desktop`, run `npm test`
4. `findComponents` test should now pass
N/A
~- [ ] If this PR adds or changes UI, the updated UI meets [accessibility …

fix `findComponents` test failure

---

NEWS.md
src/gwt/src/org/rstudio/studio/client/application/Application.java
src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java
src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants.java
src/gwt/src/org/rstudio/studio/client/application/StudioClientApplicationConstants_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/commands/CmdConstants.java
src/gwt/src/org/rstudio/studio/client/workbench/commands/CmdConstants_en.properties
src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml.MD5
src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
src/gwt/test/org/rstudio/studio/client/workbench/commands/DummyCommands.java
src/node/desktop/src/main/crash-handler.ts
src/node/desktop/src/main/gwt-callback.ts
src/node/desktop/src/main/main.ts
src/node/desktop/src/renderer/desktop-bridge.ts

Addresses [Add ability to opt-in Electron crash handling via environment variable #13025](https://github.com/rstudio/rstudio/issues/13025)
Set the environment variable `RSTUDIO_ENABLE_CRASHPAD` to "1" or "true", then start RStudio Desktop (Electron-only). This will enable the electron [crashReporter feature](https://www.electronjs.org/docs/latest/api/crash-reporter), but only in local mode (it won't try to upload). If you run RStudio from a command line, you'll also see a message such as: `Starting crash logging to C:\Users\username\AppData\Roaming\RStudio\Crashpad`.
This is an interim step on the way to fully implementing Electron crash handling (tracked in https://github.com/rstudio/rstudio/issues/13022). Not comfortable enabling this by default without further testing and research, but …

Add opt-in via environment variable for Electron crash dump generation

---

NEWS.md
src/node/desktop/package-lock.json
src/node/desktop/package.json

Addresses [Update to latest Electron 23 patch #13030](https://github.com/rstudio/rstudio/issues/13030)
Also curious if this has any impact on [R Studio suddenly does nothing on launch, Win 10, R 4.2.3, various RStudio versions #13007](https://github.com/rstudio/rstudio/issues/13007)
Bump version, build and ensure it starts, and Electron unit tests still pass.
Nothing specific to Electron version
Nothing is expected to change except all the bugs have been fixed so nothing will ever break again. Signed, Gary's Dad.
N/A

update to Electron 23.2.4

---

src/cpp/core/http/Util.cpp

and locale/facet objects are referenced counted and shared like shared_ptr so should be threadsafe (and we already use time_facet that way in httpDate)
Reviewed in PR: https://github.com/rstudio/rstudio-pro/pull/4555

Creating time_date_facet is expensive

---

src/node/desktop/src/main/desktop-browser-window.ts
src/node/desktop/src/main/window-utils.ts

Addresses [JavaScript exception when restoring window on Ubuntu 22 #13027](https://github.com/rstudio/rstudio/issues/13027)
On this platform (and possibly other Linux desktops; I only tried Ubuntu 22), when a window is unmaximized, and the handler code adjusts the window size, it triggers a recursive flurry of new "unmaximized" events, leading to a stack overflow.
Fixed by adding a debounce of 75ms. For extra safety, I also added a try/catch to log an error instead of showing the generic exception dialog should this happen despite the debounce on some platforms.
None
Test maximize and restore on Ubuntu 22. A sanity test of the same on Windows and Mac wouldn't hurt (hopefully).
N/A

debounce unmaximize handling

---

src/node/desktop/src/assets/locales/en.json
src/node/desktop/webpack.renderer.config.js

open source companion to rstudio/rstudio-pro#4570
- update some i18n strings
- copy assets to renderer webpack directory
<!-- Note for community contributors: Please sign our contributor agreement as described in CONTRIBUTING.md and note that you've done so in this space. Very much appreciate your contributions and support!

open source companion to rstudio/rstudio-pro#4570

---

docker/jenkins/publish-build.sh

Minor change to address #13005
Now defaults to a 0 byte size for an unknown file, leading to valid json, even if the build is missing.
Windows ps already returns a 0 for a missing file, so this isn't a problem there
Uses bash file existence test to either get the file size, or set size to 0
No automated tests, build is the test
No qa needed
No docs

Use a 0 size for missing file metadata

---

dependencies/common/install-panmirror

Resolves an error (`error: pathspec 'release/rstudio-mountain-hydrangea' did not match any file(s) known to git`) when installing dependencies, where we try to checkout a new quarto branch that is unknown because we haven't fetched the latest changes from the repo.
Uncomment the `git fetch` command.
N/A
dependency install scripts should now run successfully without hitting this error: `error: pathspec 'release/rstudio-mountain-hydrangea' did not match any file(s) known to git`
N/A

Uncomment `git fetch` in install-panmirror

---

NEWS.md
src/gwt/src/org/rstudio/core/client/command/ShortcutInfo.java
src/gwt/src/org/rstudio/core/client/widget/ShortcutInfoPanel.java

Addresses [Keyboard shortcut help not displaying #11376](https://github.com/rstudio/rstudio/issues/11376)
Commands that are Emacs-only or Sublime-text only were causing a variable to be null that the code assumed was not null triggering exceptions (in GWT code). Added checks.
Given the timing of when this broke, I suspect this change came with the localization work, but I didn't dive into the gory details to see why.
None
Test display of keyboard shortcut help in all editor modes (default, vim, emacs, sublime), using the keyboard shortcut, the menu, and the command palette.
If you are ambitious you could spot-check that the shortcuts being displayed match expectations (e.g. for commands that differ depending on editor mode). Probably easiest to do this by comparing with 2021.09.4-403, the …

fix keyboard shortcut help not displaying when editor in Emacs or Sublime Text mode

---

src/node/desktop/src/main/detect-r.ts

Remove some experimental code I had added while trying to understand issues that were causing some users problems starting RStudio on Windows.
Specifically, I was unsetting the three Windows temp-dir environment variables before starting RTerm.exe as part of R discovery. I did not do the same before we start the rsession itself, so that in itself could be problematic (one scenario might work and the other won't), but in general, we shouldn't be tampering with these variables.
See https://github.com/rstudio/rstudio/issues/13012 for more discussion.
Delete the code.
None.
The scenario that this code breaks:
* Windows-specific
* Username has a space in it (e.g. `C:\Users\some person\` is the home directory)
* The filesystem is configured to NOT generate 8.3 filenames (this can be done via …

remove unsetting of Windows tempdir env vars when detecting R

---

src/cpp/session/modules/quarto/SessionQuartoXRefs.cpp

Address #12882 for newly saved files 
Fixing another issue from a newly saved file. The cross reference index is generated for a rendered file after the file is saved without performing the indexing. The newer rendered index is preferred over performing the index on the saved file causing no cross references.
Since the rendered cross reference index is not populated with data, it can be size checked to determine if the saved file needs the cross references indexed. For a file that actually has no cross references, this rendered index would have a non-zero file size.
Reordered the index check to short circuit the expression check in this order: rendered index does not exist, rendered index has no content, file index is newer than rendered index
None
Steps to reproduce:
1. Create a Quarto …

Fix missing cross references on newly saved file

---

NEWS.md
src/node/desktop/package-lock.json
src/node/desktop/package.json

Noticed this new release came out and has a fix to an API (shell.openExternal) that is causing us trouble so I tried it out. Didn't solve our problem (not a surprise) but still should take the latest.
Release notes: https://releases.electronjs.org/release/v23.3.0
Bump version, `npm i`, test that app still starts and unit tests pass.
N/A - this is a minor Electron update so major version of Chromium won't change.
Nothing to specifically test.
N/A

Bump Electron to latest v23 release (23.3.0)

---

NEWS.md
src/cpp/session/modules/SessionFind.cpp
src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindInFilesDialog.java
src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/model/FindInFilesServerOperations.java

Addresses https://github.com/rstudio/rstudio/issues/13017.
Rather than adorn the search query with `\\b` word boundaries, use the `-w` flag which is supported both by all common implementations of `grep`, as well as `git grep`.
Hopefully covered by existing tests.
Test via notes in #13017.
N/A

use '-w' flag for whole word

---

src/node/desktop/src/main/main-window.ts

Addresses [Pressing Alt kills RStudio #12983](https://github.com/rstudio/rstudio/issues/12983)
We were doing setApplicationMenu twice during startup, and this was (somehow) causing a dangling pointer inside Electron's accelerator key handling code. By removing the redundant call to setApplicationMenu, the issue appears resolved.
None
Other than verifying that holding <kbd>Alt</kbd> doesn't crash the IDE on Windows, make sure the main menu is appearing and working correctly on all three desktop platforms (Mac, Windows, Linux). Quick sanity check should be sufficient.
None

remove redundant call to setApplicationMenu to avoid crash when holding Alt key

---

src/node/desktop/.eslintrc.js

Enhancement to `eslint` settings to permit strings and template literals to exceed the maximum line length. Splitting up strings and template literals can be left up to the developer to decide how the string/template literal should be split onto multiple lines for readability.
Use `es-lint` `max-len` rules `ignoreStrings` and `ignoreTemplateLiterals`. See https://eslint.org/docs/latest/rules/max-len.
Tested by adding the following changes and running `eslint`:
```js
console.log('LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOONG STRING',);
console.log(`LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO …
```

ignore `max-len` for strings and template literals

---

src/cpp/session/modules/SessionReticulate.R

closes https://github.com/rstudio/reticulate/issues/710
Issue: when a reticulate python object is automatically loaded from a previous R session `.RData` file, the IDE causes reticulate to initialize python while the IDE is generating the object summary for presentation in the env pane.    
Add an early return in `rs.describeObject()` that checks for the case of the object being a reticulate null ptr, this avoids running code that otherwise assumes python is already initialized (e.g., `reticulate::import_builtins()`). Reticulate objects loaded from `.RData` will always be null ptrs.
NA
To test locally:
1. create a .RData containing an R object
```r
x = reticulate::py_eval("1", convert = FALSE)
save.image()
``` 
2. Start a fresh R session and restore `.RData`
```r
load(".RData")
if …
```

don't initialize python from restored env null ptr

---

jenkins/Jenkinsfile.macos

Backport #13064. I didn't realize that the build urls are based on the Jenkinsfiles in the corresponding release branches, so the Mac S3 urls were still being constructed incorrectly for Cherry Blossom builds (pro builds specifically).
Cherry-picked the change from `main`.
N/A
Any builds generated after this PR goes in should have the correct url. Test by clicking on the Filename at https://dailies.rstudio.com/rstudio/cherry-blossom/desktop-pro/macos/ and https://dailies.rstudio.com/rstudio/cherry-blossom/electron-pro/macos/. No errors should occur.
N/A
~- [ ] If this PR adds or changes UI, the updated UI meets [accessibility …

Backport fix macos s3 package upload path (#13064)

---

src/cpp/session/modules/SessionRCompletions.R
src/gwt/src/org/rstudio/studio/client/common/codetools/RCompletionType.java

addresses (partially maybe) #4414
`.rs.getCompletionsSearchPath()`  check if a binding is active before calling `get()`. 

not triggering active binding on completion

---

docs/news/index.qmd

Update release notes for IDE / Workbench 2023.03.1+446.pro1 release.
This change has been generated by the release script. Content is generated based on `version/news/NEWS-2023.03.1-cherry-blossom.md`. If this file was not in sync with Pro or did not include items from other sources (i.e. the vscode extension), then some items may be missing.  Please verify content/formatting is correct and make changes if necessary.

Update release notes for 2023.03.1+446.pro1
