src/gwt/src/org/rstudio/core/client/MouseTracker.java
The issue here is a bit fiddly, so I'll try to explain what's going on...
With Safari WebKit, when a modifier key is pressed, the mouse cursor position is updated (the cursor is shown) and associated mouse events are emitted. This can cause a problem while typing in a textbox that has an associated completion list popup (e.g. Find in Files, C++ autocompletion popups) -- if the mouse cursor happens to lie over the generated popup, pressing a modifier key effectively moves focus to that menu item. (You can imagine trying to type a capital letter, and then seeing the mouse suddenly appear and set the selection / steal focus away from where you are typing.)
This PR attempts to resolve that issue by attempting to detect those synthesized events, and suppress them. If the last event was a key …
=> suppress synthesized mouse events on modifier keys

src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionsPane.java
The connections toolbar is not being refreshed when the active list of connections changes and the user is viewing the active connection. With this fix we recreate the toolbar whenever the connection list changes, usually while connecting or disconnecting from connections.
=> Fix connections toolbar not refreshing in connection view

src/cpp/session/resources/grid/gridstyles.css, src/cpp/session/resources/grid/gridviewer.js, src/gwt/src/org/rstudio/studio/client/common/shell/ShellDisplay.java, src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleResources.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/consoleStyles.css, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionListPopupPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HistoryCompletionManager.java
This change implements reverse incremental searching at the R console, a common request made by users who are used to this feature in bash and other Unix shells. 
The reverse incremental mode differs from the existing Cmd+Up behavior in that it doesn't self-dismiss once you add characters; instead, it stays up and filters in real time as you type. Just as in bash, it's toggled by pressing Ctrl+R (the existing Cmd+Up behavior has not changed).
=> Implement readline-like "reverse-i-search" for R console

src/cpp/session/modules/SessionDataImportV2.R, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsv.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsvLocale.ui.xml
Users have reported the old import dialog allowed them to import tables like:
```
Column_1     Column_2     Column_3
1            A            X
2            B            Y
```
Which is currently not possible, but could be implemented using `readr::read_table`. Therefore, this PR:
1. Replaces "Whitespace" delimiter to use `readr::read_table`
2. Adds new `Other...` option for other characters and for those users that might want to use `read_read_delim` with a space.
Notice that other users have reported that they would like to use `read.table` to avoid installing `readr`, this is being tracked as a separate issue to consider separately.
=> Add support to import white space delimited tables in data import

src/cpp/core/include/core/libclang/LibClang.hpp, src/cpp/core/include/core/r_util/RVersionInfo.hpp, src/cpp/core/r_util/RVersionsPosix.cpp
On some systems, the `<sys/types.h>` header exports two function macros, `major()` and `minor()`. This can cause issues in translation units that attempt to use these as function, or variable, names. Unfortunately, it's not easy to see how this header can sneak in -- e.g. on some systems, attempting to include the `<iterator>` header pulls that in. 
This PR attempts to rename any usages of `major` or `minor` as `versionMajor` and `versionMinor`, respectively.
The overarching goal here is to ensure that RStudio can build on FreeBSD (as requested by some users).
=> avoid collisions with 'major', 'minor' macro leakage

src/cpp/session/modules/SessionCodeSearch.cpp, src/cpp/session/modules/SessionDataViewer.R, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/codesearch/model/CodeSearchServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/codesearch/model/DataDefinition.java, src/gwt/src/org/rstudio/studio/client/workbench/codesearch/model/FileFunctionDefinition.java, src/gwt/src/org/rstudio/studio/client/workbench/codesearch/model/ObjectDefinition.java, src/gwt/src/org/rstudio/studio/client/workbench/codesearch/model/SearchPathFunctionDefinition.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
This change implements a suggestion to allow F2 to open data frames in addition to functions. It is designed for use in traditional R scripts wherein the data is present in the global environment, and invokes `View()` on the data if found (just like clicking on it in the Environment pane).
=> Allow F2 to open data frames

NEWS.md, src/cpp/r/RCntxt.cpp, src/cpp/r/RCntxtUtils.cpp, src/cpp/r/include/r/RCntxtUtils.hpp, src/cpp/r/include/r/RInterface.hpp
RStudio's debugger relies on knowledge of the layout of the `RCNTXT` structure in memory. Unfortunately, this will change again in R 3.3.3. This change adds the new layout, and uses it if the R version is >= 3.3.3.
=> Add support for RCNTXT layout changes in R 3.3.3

src/cpp/core/system/PosixChildProcess.cpp, src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java
Having Ctrl+L clear the terminal when focus is in the terminal was suggested/requested by Hadley and Darby.
For Ctrl+W, which deletes previous word in bash, I'm letting terminal have it instead of closing active document (again, when focus is in terminal).
Finally, turn off xon/xoff flow control in terminal so Ctrl+S doesn't freeze the terminal. Rarely useful, and could be triggered by a user hitting "save" when there was nothing needing saving.
=> Special cases for keyboard shortcuts and the terminal

src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenu.java, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentTab.java
From user feedback, bringing back the `utils` package `read.table` import dialog:
=> Adds dataimport menu entries for csv using base

src/cpp/desktop/DesktopInputDialog.cpp, src/cpp/desktop/DesktopInputDialog.hpp
This was a discrepancy between the web text entry dialog implementation, and the desktop/Qt one. Case 5415.
=> InputDialog not checking for zero-length input like web/Mac do.

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
This change fixes an issue wherein rendering an R Markdown document would save it unnecessarily, which is annoying for users who use external editors with RStudio (as the external editors then warn that the file has been changed when it hasn't).
=> Don't save before knitting/rendering unless document is dirty

src/cpp/r/R/Tools.R, src/cpp/session/CMakeLists.txt, src/cpp/session/SessionMain.cpp, src/cpp/session/include/session/SessionModuleContext.hpp, src/cpp/session/include/session/SessionPackageProvidedExtension.hpp, src/cpp/session/modules/SessionLibPathsIndexer.cpp, src/cpp/session/modules/SessionLibPathsIndexer.hpp, src/cpp/session/modules/SessionPackageProvidedExtension.cpp, src/cpp/session/modules/SessionPackages.cpp, src/cpp/session/modules/SessionRCompletions.R, src/cpp/session/modules/SessionRCompletions.cpp
This PR avoids using `list.dirs()` when retrieving package completions, as that call can be surprisingly expensive (especially on networked file systems). Even on my Macbook Pro (with an SSD), I see:
```
> system.time(list.files(.libPaths()))
user  system elapsed 
0.000   0.001   0.001 
> system.time(list.dirs(.libPaths()))
user  system elapsed 
0.067   0.135   0.202 
```
I'm not sure why `list.dirs` would be so much slower here, but we should avoid using it regardless.
=> avoid using 'list.dirs' (performance)

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/spelling/CheckSpelling.java
This PR should resolve an issue where attempting to replace a misspelled word with that same word + punctuation would cause a stack overflow.
Note that the stack overflow leaves the editor unusable (it seems to no longer responds to any input).
The fix ensures that the next spellcheck check starts after the replaced word, rather than with the replaced word.
=> avoid spellcheck overflow when adding puncutation

src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteApplication.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/HTMLPreviewApplication.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/RmdOutputSatellite.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/shiny/ShinyApplicationSatellite.java, src/gwt/src/org/rstudio/studio/client/vcs/VCSApplication.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceSatellite.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkSatellite.java
Implemented request logs in satellite windows to narrow down a concurrent issue in satellite chunks:
=> enable request log (ctrl+tick) in satellite windows

src/cpp/session/modules/rmarkdown/SessionRmdNotebook.cpp
This PR fixes cache entries that were errantly written with leading spaces, rather than leading zeroes, by an older version of the IDE. This can cause a couple issues:
1. Notebook outputs are not populated in the generated `.nb.html` file when the name is incorrectly written in this way;
2. The IDE can actually crash if it attempts to construct a link to a non-existent cache resource; e.g. for `.png`s in the cache. (This is likely a toolchain interaction issue; if we attempt to serve content that doesn't exist, this causes a Qt exception that crashes)
This PR fixes up all file entries in the cache on init -- basically crawling for files whose names start with spaces, and changing those to be `0`s instead.
Note that the issue that could cause these incorrect cache entries to be generated …
=> fix up chunks with leading spaces in name

NEWS.md, src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp, src/gwt/src/org/rstudio/studio/client/rmarkdown/RmdOutput.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/events/RenderRmdEvent.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RMarkdownServerOperations.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RmdEditorOptions.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RmdRenderResult.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/model/YamlTree.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetRMarkdownHelper.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
This change adds a mechanism for controlling some RStudio behavior declaratively, using the YAML front matter in the document. The two options added in this change request are shown here:
---
editor_options:
chunk_output_type: console
publish_output: false
---
The `chunk_output_type` option controls whether R Markdown chunk output is directed to the console or to the editor. It mirrors, and is synchronized with, a document preference of the same name. The option exists as a result of feedback from instructors who wanted to be able to dictate whether an R Markdown document opens in notebook mode.
The `publish_output` option controls whether the output of the document should be published. When set to `false`, only the document's source code is published. This makes it …
=> Add editor options in YAML front matter

src/gwt/src/org/rstudio/core/client/widget/FastSelectTable.java, src/gwt/src/org/rstudio/studio/client/common/sourcemarkers/SourceMarkerList.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/WorkbenchTabPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/Console.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/markers/MarkersOutputPane.java
This PR will ensure that e.g. `Ctrl + 2` activates the active tab in the Console pane, rather than always activating the Console 'tab' in the console pane. The intention here is to allow `Ctrl + 2` to focus the terminal, if that is what is currently active + visible to the user.
This PR also adds a secondary behavior -- pressing `Ctrl + 2` multiple times now toggles through the active tabs in the Console pane; this can be useful when e.g. using 'Find in Files' output. One can now type `Ctrl + 2` to focus that pane, then use the keyboard to navigate through + select entries in that pane.
=> allow 'Activate Console' to activate active tab

NEWS.md, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcessInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
When session restarted, a reconnecting terminal (TerminalSession.connect) was telling the server to use 80x25 dimensions, no matter what the actual size was. Now remember the size, and send that instead of the hardcoded values.
=> fix bug where terminal was showing as 80x25 after session restart

src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcess.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
Prior to this, a terminal clear or terminate while session was suspended didn't work. It was a no-op for terminate, and for clear it would clear client-side buffer but not server-side buffer.
=> fix: terminal clear and terminate commands when session suspended

NEWS.md, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
This change implements a common (on forums and in person!) user request: the ability to execute a region of lines bounded by blank lines, or a "paragraph". 
data(cars)
summary(cars)
There is now a new option to execute paragraphs rather than statements with the Run Selection command.
Finally, the change adds three commands which, regardless of the current selection or user preference, always execute a line, statement, or paragraph. This makes it possible for power users to create key bindings so they can mix and match execution behaviors; for instance, users might wish Ctrl+Enter to normally execute a paragraph, but also bind a key to step one line at a time, or the reverse.
=> Implement paragraph-style code execution

src/cpp/core/include/core/r_util/REnvironment.hpp, src/cpp/core/r_util/REnvironmentPosix.cpp, src/cpp/core/r_util/RVersionsPosix.cpp
This change fixes an issue experienced by an RStudio Server Pro user who was using a version of R not compiled with the system's default gcc. This version of R needed a special `LD_LIBRARY_PATH`  to run. Since we don't supply this when querying R for its version, RSP failed to determine the R version.
The fix is twofold:
1. Supply `LD_LIBRARY_PATH` to the R process when querying its version.
2. Log the output from standard error when we fail to determine R's version. (This would have made diagnosing the above issue dramatically simpler!)
=> Provide LD_LIBRARY_PATH when querying R for its version

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
This fixes an issue whereby the Run Document button's ancillary menu was showing by default in R scripts (first referenced here: https://github.com/rstudio/rstudio/pull/1019 ). It looks like all state is managed correctly for the button, but I had neglected to hide it by default at the outset.
=> Hide run document menu button by default

src/cpp/core/StringUtils.cpp, src/cpp/core/include/core/StringUtils.hpp, src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/cpp/session/modules/SessionGit.cpp, src/gwt/src/org/rstudio/core/client/Functional.java, src/gwt/src/org/rstudio/core/client/ListUtil.java, src/gwt/src/org/rstudio/core/client/widget/ProgressDialog.java, src/gwt/src/org/rstudio/core/client/widget/SelectWidget.java, src/gwt/src/org/rstudio/studio/client/common/vcs/GitServerOperations.java, src/gwt/src/org/rstudio/studio/client/common/vcs/RemotesInfo.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/AddRemoteDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/CreateBranchDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/CreateBranchToolbarButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ConsoleProgressDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/GitPane.java
Note: not ready for merge, pending UI feedback.
---
This PR adds a simple 'create branch' dialog, intended to make it possible to create and checkout a new branch without popping into the shell. A quick preview of what the UI looks like so far:
When a branch of the same name already exists, we prompt the user as to whether they'd like to check out that branch, or overwrite it with a fresh branch from their current checkout.
Should we allow the user to set an upstream remote as well? E.g. with a dialog like:
```
Create Branch: < ___ >
Set Upstream: < ___ >
[ ] Push to remote
```
I'm trying to imagine a workflow where we attempt to set an upstream remote (if one exists); otherwise, we automatically push the repository to the remote and automatically set the upstream. Does something like …
=> Add a 'create branch' dialog

src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
Some users prefer tab navigation commands to wrap around, by e.g. selecting the first tab if they invoke Next Tab with the last tab selected. This capability already exists; this change simply exposes it in a UI pref, preserving the existing default.
=> Add UI pref to control tab wraparound behavior

src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/SessionConsoleProcessInfo.cpp, src/cpp/session/SessionConsoleProcessInfoTests.cpp, src/cpp/session/SessionConsoleProcessPersist.cpp, src/cpp/session/SessionConsoleProcessPersistTests.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/cpp/session/include/session/SessionConsoleProcessInfo.hpp, src/cpp/session/include/session/SessionConsoleProcessPersist.hpp, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcess.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/model/ConsoleServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/model/ProcessBufferChunk.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
Client now gets back chunks, with a flag telling it when it needs to fetch another chunk. This is to avoid overwhelming the client with a single massive data return when restoring terminals. We already trim the buffer to match the maximum number of lines supported by xterm, but if the buffer contained very long lines we could still be swamping it.
=> Resolve a Terminal TODO - break up buffer fetch into chunks

src/cpp/session/SessionClientInit.cpp, src/cpp/session/include/session/SessionPackageProvidedExtension.hpp, src/cpp/session/modules/SessionPackageProvidedExtension.cpp, src/gwt/src/org/rstudio/studio/client/projects/events/PackageExtensionIndexingCompletedEvent.java, src/gwt/src/org/rstudio/studio/client/projects/model/PackageProvidedExtensions.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java, src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/Packages.java
This PR should hopefully resolve a bug spotted by @yihui where the set of 'New Project' entries may not be populated when connecting to an existing R session.
We resolve the issue by saving the JSON payload in memory, and passing that along as part of the session init bundle. If the indexer has not yet finished running, that payload will be empty, but a later incoming event would then provide the set of extensions (as per https://github.com/rstudio/rstudio/blob/1fcd843d8ab9ae9204674b69cb3d07bcb55fea64/src/cpp/session/modules/SessionPackageProvidedExtension.cpp#L174-L177).
Side note: is `SessionInitEvent` the correct thing to be attaching to / listening on here?
=> ensure package extensions provided on init

src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionNavigationPage.css, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionNavigationPage.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionWizard.css
Top border dividing wizard caption is missing in connections dialog.
=> Missing top border in connections dialog wizard

src/cpp/session/SessionClientInit.cpp, src/cpp/session/include/session/SessionPackageProvidedExtension.hpp, src/cpp/session/modules/SessionPackageProvidedExtension.cpp, src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java, src/gwt/src/org/rstudio/studio/client/packages/events/PackageExtensionIndexingCompletedEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/Packages.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackageProvidedExtensions.java
This is a second stab at ensuring package provided extensions are provided on session init.
Unfortunately, the previous PR had an issue -- the Packages tab is initialized lazily, and so the event handlers registered therein wouldn't actually receive the event unless the Packages tab was focused + initialized.
The fix here is to just use an eager singleton to register the necessary event handlers.
=> ensure extensions are discovered on init

src/cpp/session/modules/SessionGit.cpp, src/gwt/src/org/rstudio/core/client/Functional.java, src/gwt/src/org/rstudio/studio/client/common/dialog/DialogBuilderBase.java, src/gwt/src/org/rstudio/studio/client/common/vcs/GitServerOperations.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/CreateBranchToolbarButton.java
This PR adds handling for the case where the user tries to create a branch `branch`, but a remote branch called `branch` already exists.
Right now, the only actions made available to the user in this case is to check out that remote branch. We might also want to allow the user to explicitly create and overwrite the remote branch, but because this is a destructive operation I leave this unimplemented for now.
=> handle conflict w/remote when creating branch

src/cpp/session/modules/NotebookData.R, src/cpp/session/modules/SessionRmdNotebook.R
SQL chunks support referencing connection by object and name, as in ` ```{r options=db}` or ` ```{r options="db"}`. However, we currently only support setting this through `knitr::opts_chunk$set` as `knitr::opts_chunk$set(connection="db")`. The cause, I believe, is that we internally serialize the options when we prepare the setup chunk and when running the data chunk, the `connection` is no longer a default.
Repro:
```{r setup}
library(DBI)
db <- dbConnect(RSQLite::SQLite(), dbname = "sql.sqlite")
knitr::opts_chunk$set(connection = db)
```
```{sql}
SELECT 1
````
Instead of failing, this fix checks the cached version of the options `.rs.knitr.chunkOptions` before failing.
=> support setting sql connection with knitr options

src/cpp/desktop-mac/GwtCallbacks.mm, src/cpp/session/SessionHttpMethods.cpp, src/cpp/session/projects/SessionProjects.cpp, src/gwt/src/org/rstudio/core/client/files/filedialog/FileBrowserWidget.java, src/gwt/src/org/rstudio/core/client/files/filedialog/FileDialog.java, src/gwt/src/org/rstudio/core/client/files/filedialog/OpenFileDialog.java, src/gwt/src/org/rstudio/core/client/files/filedialog/OpenProjectDialog.java, src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java, src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java, src/gwt/src/org/rstudio/studio/client/common/FileDialogs.java, src/gwt/src/org/rstudio/studio/client/common/impl/DesktopFileDialogs.java, src/gwt/src/org/rstudio/studio/client/common/impl/WebFileDialogs.java, src/gwt/src/org/rstudio/studio/client/projects/ProjectOpener.java, src/gwt/src/org/rstudio/studio/client/projects/model/ProjectsServerOperations.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/www/webkit.nocache.html
This PR makes it possible to open a directory as an RStudio project within the `Open Project` dialog, thereby making it possible to open directories as projects even if they do not have a `.Rproj` file yet.
The behavior in RStudio Server (ie, from a browser) is basically that explicitly clicking the `Open` button when a directory is selected will open that directory, while double-clicking on a directory will still navigate into that directory. I think this is inline with user expectations.
This is currently only implemented for RStudio Server + macOS Desktop. I'm not yet sure if it's possible to tell a QFileDialog to accept both directories and single files. (It's probably possible to do by e.g. subclassing `QFileDialog` and implementing behaviors as necessary; I'm going to explore that a …
=> allow directory in Open Project dialog

src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java, src/gwt/src/org/rstudio/studio/client/projects/ProjectOpener.java
This should hopefully resolve build errors on RStudio Pro -- the issue, if I understand correctly, is that `ProjectOpener` is rebound to a separate class `ProjectOpenerPro` and so the typical injection fails there.
=> avoid injection within ProjectOpener class

src/cpp/r/R/Tools.R, src/cpp/session/modules/SessionHistory.cpp
Two fixes for `timestamp()`:
1. Avoid crashing while using the namespace `utils::timestamp`
2. Add missing support for `stamp`, `prefix`, `suffix` and `quiet` parameters.
Somewhat related to: https://github.com/rstudio/rstudio/pull/1029
=> Fix timestamp crash and signature in Windows

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
Injecting this message into xterm.js gets it out of sync with winpty's buffer.
=> don't display welcome message in new terminal

src/cpp/core/system/Win32ChildProcess.cpp, src/cpp/core/system/Win32Pty.cpp, src/cpp/core/system/Win32Pty.hpp, src/cpp/core/system/Win32PtyTests.cpp
Moved details of reading/writing to the pty into the wrapper class. Updated unit test.
The named pipes opened by the winpty agent process use FILE_FLAG_OVERLAPPED. Per MSDN, you should match this behavior when attaching to and using the pipes, and pass the OVERLAPPED structure when making read/write calls. Otherwise ReadFile/WriteFile can return inconsistent results.
I had hoped this might help with the intermittent "typing is out of order" glitch I'm seeing. It may have improved it a bit, but definitely didn't eliminate it.
=> Use matching I/O pattern for reads/writes of the winpty pipes

src/cpp/core/include/core/system/Process.hpp, src/cpp/core/include/core/system/System.hpp, src/cpp/core/system/RegistryKey.cpp, src/cpp/core/system/Win32ChildProcess.cpp, src/cpp/core/system/Win32Pty.cpp, src/cpp/core/system/Win32Pty.hpp, src/cpp/core/system/Win32PtyTests.cpp, src/cpp/core/system/Win32System.cpp, src/cpp/core/system/Win32SystemTests.cpp, src/cpp/session/SessionConsoleProcess.cpp
Simplified the public interface of WinPty class to hide the steps involved in starting a pty (init/run agent/start process), making it a single "start" call. Easier usage, and easier to test.
Added some winpty diagnostic-related environment variables, one allows specifying a custom command to run when starting terminal (e.g. to try out different shell programs, like git-bash). Another turns on the winpty conerr channel, which I've yet to find a use for but was taking a stab in the dark that it might help with some issues I'm seeing, doesn't seem to be the case.
Pulled out some shared code for expanding Windows environment variables and made it a public function, wrote a couple of tests on that.
Wrote a test for WinPty that sends it a character at a time (with small pause between them) and …
=> refactoring, testing and diagnostics on winpty code

src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/SessionConsoleProcessTests.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/gwt/src/org/rstudio/studio/client/common/shell/ShellInput.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
Have only seen this happening on Windows IDE, where it is very easy to repro and user input is often messed up (e.g. echo shows up as ehco).
Each writeStandardInput call from the client now includes a sequence count (per terminal instance) which increments with each call. The server uses this to notice out-of-order messages, and waits until the gaps are filled before it releases the input from its queue.
For other existing use cases, a flag is sent for the sequence which triggers the original behavior with pure FIFO.
Watch for overflow of int on Java side, and send a flag telling server to flush and restart the expected sequence (highly unlikely, requires 2 billion+ keystrokes, but hey, who knows). On server, also prevent locking up the queue if an expected sequence never arrives, and …
=> Handle out-of-order RPC calls for terminal input messages

src/cpp/core/include/core/system/System.hpp, src/cpp/core/system/Win32ChildProcess.cpp, src/cpp/core/system/Win32System.cpp, src/cpp/core/system/Win32SystemTests.cpp, src/cpp/session/CMakeLists.txt, src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/modules/SessionTerminalShell.cpp, src/cpp/session/modules/SessionTerminalShell.hpp, src/cpp/session/modules/SessionTerminalShellTests.cpp, src/cpp/session/modules/SessionWorkbench.cpp
New rpc, get_terminal_shells, returns list of detected shells on Windows; not being used yet; client will invoke to populate list of available shells in preferences, menus, etc.
=> shell detection for win32 terminal

src/cpp/session/SessionConsoleProcessTests.cpp, src/cpp/session/modules/SessionTerminalShell.cpp, src/cpp/session/modules/SessionTerminalShell.hpp, src/cpp/session/modules/SessionTerminalShellTests.cpp
Mostly several signed/unsigned issues, an unused-code warning, and an actual bug with no return from getGitBashShell( ) when git not found.
=> Fix compiler warnings on non-Windows build

src/cpp/session/modules/SessionRMarkdown.R
Currently, R Markdown templates look for a template YAML file called `template.yaml`. This PR allows users to define either `template.yml` or `template.yaml` for R Markdown templates.
The main motivation for this:
1. We've mainly standardized on using `.yml` as the extension for YAML files (e.g. `config.yml`, `_site.yml`)
2. The default extension used by RStudio for YAML files is `.yml`, making it somewhat easier to create a skeleton YAML file with the wrong extension.
=> allow both 'template.yml', 'template.yaml' for R Markdown templates

NEWS.md, src/cpp/session/SessionConsoleProcessInfo.cpp, src/cpp/session/SessionConsoleProcessInfoTests.cpp
When returning terminal buffer, it is supposed to be trimming down to the max lines supported by the terminal (currently 1000 lines). I introduced a (silly) regression with  https://github.com/rstudio/rstudio/pull/1023 in which the trimming didn't happen properly. 
Easy fix, and added a unit test that would have caught this.
=> Fix regression with terminal buffer trimming

src/gwt/src/org/rstudio/core/client/command/AppCommand.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java
@kevinushey thanks for noticing this:
Without PR:
With PR:
Tried with 4px adjustment but then some icons feel a bit low, so I rather keep them up. Feedback welcomed.
=> Adjust 3px menu icon vertical space

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorCommandDispatcher.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorCommandEvent.java
This PR fixes an issue where Ace commands (e.g. 'kill line', `Ctrl + K`) don't work in satellite windows.
@jmcphers, can you sanity check?
=> ensure Ace commands work in satellites

src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
It looks like `formatR` is no longer required by `rmarkdown`; this PR removes it from the dependency list.
=> 'formatR' no longer required by rmarkdown

src/cpp/core/system/PosixSystem.cpp, src/cpp/core/system/PosixSystemTests.cpp
On systems with /proc, use that to detect subprocesses instead of shelling out to pgrep. Improve unit test for "no subprocess" case. Tested on Mac and Linux.
=> Subprocess detection using procfs

src/cpp/session/SessionModuleContext.cpp, src/cpp/session/modules/build/SessionBuild.cpp
This PR ensures that stale `00LOCK` directories are cleaned up after an abnormally terminated build (e.g. if a package build is interrupted, it's possible that this `00LOCK` directory will be left behind).
It also fixes a bug whereby the `module_context::getLibPaths()` function would return a number of empty file paths -- whoops!
=> clean up left-behind 00LOCK directories

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/ResizeTerminalEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/TerminalDataInputEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/XTermTitleEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
Pull out terminal session I/O into TerminalSessionSocket class, which currently encapulates the RPC-based input/output, but will be extended to also attempt the websocket connection and route through that if successful. 
Random whitespace/commenting tweaks.
=> Client-side terminal refactoring prep for websockets

src/gwt/src/org/rstudio/core/client/Stopwatch.java, src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java
To help evaluate ongoing terminal-typing performance work. Enable with .rs.writeUiPref("enable_report_terminal_lag", TRUE) and restart. Console will show time in milliseconds between dispatching a keystroke and seeing it echoed, and a running average.
=> ability to display terminal type/display lag in JavaScript console

src/cpp/core/file_lock/AdvisoryFileLock.cpp, src/cpp/core/file_lock/FileLock.cpp, src/cpp/core/file_lock/LinkBasedFileLock.cpp, src/cpp/core/include/core/FileLock.hpp
This PR adds the `log-file` parameter to `/etc/rstudio/file-locks`, allowing users to customize where lockfile logging entries are sent.
=> allow users to customize where lockfile log output is sent

src/cpp/session/SessionConsoleProcessInfo.cpp, src/cpp/session/SessionConsoleProcessInfoTests.cpp, src/cpp/session/SessionConsoleProcessPersist.cpp, src/cpp/session/SessionConsoleProcessTests.cpp, src/cpp/session/include/session/SessionConsoleProcessInfo.hpp, src/cpp/session/modules/SessionWorkbench.cpp, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcessInfo.java
ConsoleProcessInfo fields to indicate which type of connection a terminal instance is configured for on the server-side; still hardcoded to RPC. Working on websockets; not currently planning to do named pipes, but threw in a constant for it.
=> ConsoleProcess metadata plumbing for non-RPC terminal channel

src/cpp/r/include/r/session/RSession.hpp, src/cpp/r/session/graphics/RGraphicsDevDesc.cpp, src/cpp/r/session/graphics/RGraphicsDevDesc.hpp, src/cpp/r/session/graphics/RGraphicsDevice.cpp, src/cpp/r/session/graphics/RGraphicsUtils.cpp, src/cpp/r/session/graphics/RShadowPngGraphicsHandler.cpp, src/cpp/session/SessionOptions.cpp
This PR adds support for version 12 of the R graphics engine, as will be used with R 3.4.0.
=> support R graphics engine v12

dependencies/windows/README, src/gwt/tools/editor-settings/codetemplates.xml, src/gwt/tools/editor-settings/eclipse-templates.xml
Broken link to Qt download, and out-of-date instructions on manually installing RTools.
=> tweak Windows dependency README to match Wiki

src/cpp/session/modules/SessionRmdNotebook.R
This is a speculative change that attempts to address a frequently reported issue in which error messages like the below appear when attempting to save a notebook:
Warning message:
In file(con, "rb") :
cannot open file 'C:/Users/<username>/AppData/Local/RStudio-Desktop/notebooks/2F38416F-<project>/1/s/cplf5ref33onf/temp': Permission denied
I was not able to reproduce the problem, but I did find that
- this `temp` folder is created when plots are resized inside the chunk popout window;
- users who remove the folder don't see the error any more; and
- the code here attempts to read everything inside the chunk folder as though it were a regular file, which seems like a candidate for raising an R error such as the above.
@javierluraschi is there some mechanism that should be cleaning up the …
=> Ignore subdirectories inside chunk data folders

src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleOutputEvent.java, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcess.java, src/gwt/src/org/rstudio/studio/client/common/console/ServerConsoleOutputEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
Noticed while working on other stuff.
=> remove unused error parameter from ConsoleProcessOutput client event

src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp
If you closed a session with a busy terminal (i.e. ignoring the warning), the terminal processes are killed (they die with the session) but metadata was still tracking the last-known busy state.
On restarting that session, the previous state was being reported, so you could get warned about terminal being busy even if you didn't have the terminal tab showing at all, or if you hadn't yet clicked on the tab and reopened the associated terminal session (which would spin up processes which would then update the busy-state flag).
=> Bug fix, non-busy terminals were reporting as busy in certain restart scenarios

src/cpp/session/modules/SessionConnections.R
Avoid duplicate drivers when the `ODBCINST` has multiple entries, `odbc::list_drivers()` returns a table of properties not a table of drivers.
=> Avoid duplicate drivers when description specified

src/cpp/core/include/core/type_traits/TypeTraits.hpp, src/cpp/r/RCntxt.cpp, src/cpp/r/RCntxtUtils.cpp, src/cpp/r/include/r/RCntxtUtils.hpp, src/cpp/r/include/r/RIntCntxt.hpp, src/cpp/r/include/r/RInterface.hpp, src/cpp/session/modules/environment/EnvironmentUtils.cpp, src/cpp/session/modules/environment/SessionEnvironment.cpp
This PR tweaks the type used for the `nodestack` member of the RCNTXT struct, as per https://github.com/wch/r-source/blob/4a536ef5bcad75125fe3bab86e8db9d777d62dc8/src/include/Defn.h#L483-L511.
=> support debugger with R 3.4.0

dependencies/common/install-boost, dependencies/windows/install-boost/install-boost.R
This PR ensures that we build Boost without Python, to ensure installation succeeds on build machines that don't have a non-minimal Python installation available.
=> build boost without python

src/cpp/session/modules/SessionGit.cpp
This PR should resolve a bug spotted by Darby, whereby paths containing non-ASCII characters would be quoted with Git's so-called quoted octal notation. (I previously thought this issue was unique to Windows, but it actually seems to occur everywhere except macOS!)
It should be safe to just unilaterally force `core.quotepath=off`, to ensure Git returns us UTF-8 paths all the time.
=> always use 'core.quotepath=off' with git

src/cpp/core/file_lock/LinkBasedFileLock.cpp
This PR allows us to check whether a link-based lockfile is orphaned; that is, generated by an `rsession` process that no longer exists. (This typically occurs when an `rsession` process crashes, and hence is unable to clean up the lockfile on exit.)
We accomplish this by writing the process ID of the active R session to the generated lockfile, and allowing other processes to check the PID in that lockfile when determining whether the lockfile is active or stale / orphaned.
This PR should ensure that users who see their R session crash are able to promptly reconnect to the previous session, and in particular should fix bogus 'File not found' errors that can pop up during file autosave when this underlying 'session disconnect' has occurred.
Currently, the PR is relatively conservative …
=> improve RStudio's ability to recover crashed sessions

src/cpp/session/modules/SessionConnections.R, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionSnippetHost.java
`odbc-install` installs the code snippets withing the driver folder under a `snippets` folder. Notice that currently `connections-path` and the `/etc/rstudio/connections/` location take precedence over the drivers `snippets` folder so one can easily override the ones provided by default.
Also, a minor fix to `snippets` syntax to allow explicit empty default values.
=> Support ODBC snippets provided by odbc-install

src/cpp/core/VersionTests.cpp, src/cpp/core/include/core/Version.hpp, src/cpp/r/include/r/session/RSessionState.hpp, src/cpp/r/session/RRestartContext.cpp, src/cpp/r/session/RSearchPath.cpp, src/cpp/r/session/RSearchPath.hpp, src/cpp/r/session/RSession.cpp, src/cpp/r/session/RSessionState.cpp, src/cpp/session/SessionMain.cpp
NOTE: not quite ready for merge; likely needs some tweaking re: how the message is reported to the user.
This PR fixes an issue where R could crash on startup when attempting to restore an workspace associated with a different version of R than the currently active version of R.
The fix is mostly straightforward -- on suspend, we now write the R version to a file; on restore, we validate against that version, and abort the restore if either the major or minor versions differ.
This should hopefully reduce some headaches that we might see with the introduction of R 3.4.0.
Right now, the error message is just plainly reported to the console:
but we might want to tweak this (e.g. just change the error message, or provide a modal dialog information the user, or otherwise)
=> guard against incompatible R versions on restore

src/cpp/CMakeLists.txt, src/cpp/core/include/core/Thread.hpp, src/cpp/core/include/core/system/Process.hpp, src/cpp/session/CMakeLists.txt, src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/SessionConsoleProcessSocket.cpp, src/cpp/session/SessionConsoleProcessSocketTests.cpp, src/cpp/session/SessionConsoleProcessTests.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/cpp/session/include/session/SessionConsoleProcessSocket.hpp, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcess.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/model/ConsoleServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java
RSession starts a thread running a websocket server, and terminal sessions use the websocket for sending input to the server, and receiving output from the server.
If unable to connect, the connection falls back to RPC.
Seeing a nice bump in responsiveness from the terminals with this approach. Typical response time between hitting key and getting it echo'd back was about 130ms (on a Mac dev setup); with changes this is about 30ms.
=> Use websocket for terminal i/o between client and server

src/cpp/session/SessionClientInit.cpp, src/cpp/session/include/session/SessionOptions.hpp, src/cpp/session/modules/SessionConnections.R, src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/model/NewConnectionContext.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionNavigationPage.java
This work allows driver providers to filter out drivers from RStudio by including a `license.lock` file in their driver distribution.
=> Filter drivers that are marked as licensed

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java
If enable_report_terminal_lag is set to TRUE and client refreshed, some info about the connection (whether websocket or rpc was used) will be sent into the xterm display during connection attempt.
Same setting that is already used to dump typing latency info to javascript console.
`.rs.writeUiPref("enable_report_terminal_lag", TRUE)`
=> dump basic terminal connection info via enable_report_terminal_lag

src/cpp/session/modules/SessionGit.cpp
This PR should help alleviate an issue where git commands could fail (especially on networked filesystems) due to the presence of an `index.lock` file when attempting to run Git.
We accomplish this by polling on the presence of the `index.lock` file for one second (once every `100ms`). Although this won't be bullet-proof, it should still catch the vast majority of our git timing issues.
=> wait for 'index.lock' when running git commands

src/cpp/r/session/REmbeddedWin32.cpp
Looks like I forgot to send a PR for this one. In windows, bringToTop() crashes.
=> Make bringtotop unsupported in windows

src/gwt/src/org/rstudio/studio/client/workbench/ui/ConsoleTabPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/Console.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleClearButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsolePane.java
See case 6690.
Fix: Keep the clear console toolbar button always visible instead of fading it in when stop button fades out, and have it fixed to the right-side of toolbar.
By having clear button always visible, position stays fixed and the stop button fades in to its left, avoiding this issue of stop button moving around.
The clear console command is usable even when console is busy, so having the button fade out when stop appears wasn't necessary.
=> Fix: New clear console icon makes code hard to interrupt

src/cpp/session/SessionOptions.cpp, src/cpp/session/include/session/SessionOptions.hpp, src/cpp/session/modules/SessionWorkbench.cpp
New session setting, determines if websockets will be tried for connecting to terminals. Default is true (1).
session-use-terminal-websockets=0  -- client will only use rpc to talk to terminals, won't even try websockets
=> session-use-terminal-websockets to control use of websockets

src/cpp/session/modules/SessionPackages.R
This is a fix for the bug originally reported at https://support.rstudio.com/hc/communities/public/questions/203052576-setting-libpath-in-Rstudio
To replicate the error, use:
```r
loc <- normalizePath(tempdir())
assign(".lib.loc", loc, envir = environment(.libPaths))
```
The resulting error message is:
```
Error in pkgs.name[[i]] : subscript out of bounds
```
This happens because the code simplifies the result of `installed.packages()`, and if the library contains zero or one row, the simplification results in a vector, not a data frame.
The fix is to set `drop=FALSE` when returning columns of the data frame.
This bug manifests in the [`checkpoint` package on CRAN](https://cran.r-project.org/package=checkpoint). In the package is a workaround to fix this bug, and this has been working …
=> Fix bug that assumes all libraries have at least two packages

src/cpp/r/RRoutines.cpp, src/cpp/r/include/r/RRoutines.hpp
This PR removes our unused C method registration (we don't have any `.C` methods registered). This also has the fortunate side effect of ensuring we compile cleanly against R 3.4.0.
=> remove unused C method registration

src/cpp/core/system/ChildProcess.hpp, src/cpp/core/system/PosixChildProcess.cpp, src/cpp/core/system/Process.cpp, src/cpp/core/system/Win32ChildProcess.cpp
The terminal websocket activity won't reset session timer, so if all you are doing is working in the terminal (but not doing a full-screen thing to make it "busy"), the session suspend timer will run out and sadness will occur.
Fixed to have output in a terminal treated as activity (at least, for a second), which will contribute to keeping the session alive.
Also put this in the Win32 implementation, just to keep symmetry with Posix code.
=> Terminal input/output via websockets not keeping session alive

src/cpp/session/modules/SessionPackages.R
I'm hitting this error when restarting the r session (which also makes the packages pane unusable for me):
```
ERROR r error 4 (R code execution error) [errormsg=Error in x[, 1] : 
incorrect number of dimensions
]; OCCURRED AT: rstudio::core::Error rstudio::r::exec::(anonymous 
namespace)::evaluateExpressionsUnsafe(SEXP, SEXP, SEXP *, 
sexp::Protect *, rstudio::r::exec::(anonymous namespace)::EvalType) 
/Users/javierluraschi/RStudio/rstudio/src/cpp/r/RExec.cpp:159; 
LOGGED FROM: rstudio::core::Error rstudio::session::modules::packages::
(anonymous namespace)::getPackageState(const json::JsonRpcRequest &, 
json::JsonRpcResponse *) 
/Users/javierluraschi/RStudio/rstudio/src/cpp/session/modules/SessionPackages.cpp:538
```
Seems caused by https://github.com/rstudio/rstudio/pull/1108.
For …
=> Use dataframe in listInstalledPackages 0c2c109

src/cpp/session/SessionConsoleProcessSocketTests.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/cpp/session/include/session/SessionConsoleProcessSocket.hpp
Created test harness for the server websocket used by terminal feature, and write some tests.
These are fairly heavyweight as unit-tests go, creating multiple threads, watching network ports, etc. Should pay off in reducing risks of modifying this fairly complex code, stress-testing it (the tests rapidly create and destroy instances of the tested class a lot more than the server typically does), and in validating new drops of websocketpp, should we ever do that.
It also exercises the client-side of websocketpp a bit, which we don't currently use in the production code, only in these tests.
=> Unit test terminal websocket class

src/cpp/session/SessionConsoleProcessSocket.cpp, src/cpp/session/SessionConsoleProcessSocketTests.cpp
Running unit tests on Windows revealed an issue not found on Mac; needed to use shared_ptr when binding unit-test specific callbacks or they could be called after deletion. On Linux, found an order-of-operation issue in shutting down websocket server class; fixed and reverified on all 3 platforms.
=> Fix websocket unit tests on Windows and Linux

src/cpp/session/modules/SessionRCompletions.R, src/gwt/src/org/rstudio/studio/client/common/codetools/CodeToolsServerOperations.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionRequester.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
This PR augments RStudio's completion system such that it delegates to the `custom.completer` R function when available.
=> delegate to custom completer when available

src/cpp/session/modules/SessionRSConnect.R, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/DirEntryCheckBox.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.css, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
This change addresses a frequently reported usability issue in the publish dialog; namely, that when publishing apps that have a lot of files, the list of files displayed to deploy is too long and awkward.
There are two components to the change:
1. Any subdirectory which contains more than 5 files (recursive total) has its full file list hidden and replaced with simply the name of the directory. 
2. To help distinguish directories from ordinary files (as the dialog can now contain both), file type icons have been added to the dialog.
The result:
=> Roll up large directories in publish dialog

src/cpp/session/modules/SessionConnections.R, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionSnippetHost.java
Implement DSNs for new connections wizard:
This assuming the `ODBC.ini` file is configured as:
```
[Customers]
Description     = Test to Postgres
Driver          = PostgreSQL
[Supliers]
Description     = Test to Postgres
Driver          = PostgreSQL
[Invoices]
Description     = Test to Postgres
Driver          = PostgreSQL
```
=> Implements DSNs for new connections wizard

Jenkinsfile
The centos5 containers will need to be modified in order to continue functioning now that centos5 is EOL and the repos have removed update/extra content. Until that time, this disables the centos5 builds so the jenkins builds go back to passing.
=> temporarily disable centos5 builds

src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
Follow up to https://github.com/rstudio/rstudio/commit/0c49308e68e6d8a4f612cb8e73320dcd91363a1b, need to delay ready the uiPrefs to prevent hangs in desktop versions.
=> Delay read of uiprefs for desktop application header

NEWS.md, src/cpp/session/SessionOptions.cpp
Oops, meant that to be xterm-256color, not vt100-256color.
=> Fix TERM setting for console, add to NEWS

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/AnsiCode.java, src/gwt/test/org/rstudio/studio/client/VirtualConsoleTests.java
If attempt is made to specify color via RGB (ESC[38;2;r;g;b), I was bailing and ignoring all attributes in the sequence. Now I parse over these and still apply supported attributes.
Unit tests for this, and some other scenarios.
=> skip over unsupported RGB color command, more unit tests

src/gwt/src/org/rstudio/core/client/StringSink.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/AnsiCode.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalLocalEcho.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java, src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java, src/gwt/test/org/rstudio/studio/client/workbench/views/terminal/AnsiCodeTests.java, src/gwt/test/org/rstudio/studio/client/workbench/views/terminal/TerminalLocalEchoTests.java
Local-echo was confused by embedded escape sequences and control characters, causing it to fail on matching output that had already been echoed. Most obvious symptom was doing lots of typing and backspacing then finding characters that can't be deleted, though they aren't really there if you press Enter.
Make matching smarter, causing it to recognize and step over ANSI escape sequences (but still write them out), as well as common control characters DEL, BS, BEL, NL, CR.
Also added a unit test source file for the AnsiCode class, but only a simple test so far.
=> Bug fixes for terminal local-echo matching

src/cpp/session/modules/SessionDataImportV2.R
This fixes an issue blocking users to import CSVs, the issue was that `maxCols` was removed from the data viewer but still used by the data viewer hosted in the import dialog.
=> Filter columns in data import instead of data viewer 87aacd3

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
Code tabs in options dialog require subclassing for flat theme to look properly.
=> Flat theme for code tabs in options dialog

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/Wizard.css
My original plan was to remove shadow, gradients and use css borders. However, not having a shadow made the UI look off, instead, I'm reducing the shadow effect significantly but enough to add volume to the dialog.
=> Flat dialogs for flat theme

src/gwt/src/org/rstudio/core/client/AnsiCode.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermNative.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
- Disable local-echo if not typing at the end of a line.  
- Disable local-echo if terminal is showing the full-screen alt-buffer (in case "busy" state hasn't updated yet)
- Fix a missing case in ANSI code detection regex (wasn't catching ESC[1@ for inserting a character)
=> disable local echo when not typing at the end of current line

NEWS.md, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
Terminal was hardcoded to have a blinking cursor. Now I use the existing Global Options/Code/Display/Blinking Cursor setting to determine if xterm blinks its cursor.
Existing terminals won't change until they are reloaded (setting "blink" is done during construction of xterm.js), but if someone hates blinking cursors, then this at least gives them a way to turn it off in new terminals.
=> Make new terminal instances obey the existing "blinking cursor" setting

src/cpp/session/modules/SessionConnections.R
Code snippets from bundled ODBC drivers not displaying in Linux, since Linux is case sensitive and OS X is not. Fix is, like the rest of the code in this function, make the driver lowercase.
=> Case sensitivity in linux requires tolower snippets

src/cpp/core/include/core/system/PosixSystem.hpp, src/cpp/core/system/PosixSystem.cpp, src/cpp/core/system/PosixSystemTests.cpp
Found a way to detect child processes on Mac without having to shell out to pgrep. Built and ran tests on Mac/Windows/Linux.
=> detect subprocesses on Mac with proc_listchildpids

src/cpp/core/CMakeLists.txt, src/cpp/core/system/ChildProcessSubprocPoll.cpp, src/cpp/core/system/ChildProcessSubprocPoll.hpp, src/cpp/core/system/ChildProcessSubprocPollTests.cpp, src/cpp/core/system/PosixChildProcess.cpp, src/cpp/core/system/Win32ChildProcess.cpp, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalLocalEcho.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java, src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java, src/gwt/test/org/rstudio/studio/client/workbench/views/terminal/TerminalLocalEchoTests.java, src/gwt/test/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocketTests.java
- factored out some common (and confusing) duplicate code from `PosixChildProcess` and `Win32ChildProcess` into a shared `ChildProcessSubprocPoll` class; still find it a bit confusing but at least the confusion is now encapsulated and has some tests
- this class tracks how often to check for subprocesses, and whether there has been recent terminal output
- new behavior: when there is no recent output, frequency of subprocess checks is reduced
- new behavior: hide the _local echo_ preference UI on Windows, which doesn't support local-echo
- new behavior: if Local Echo sees the literal text **Password:** written to the terminal, it briefly suspends local-echo, to reduce the chance of user's password local-echoing before local-echo is stopped by server reporting back that terminal is busy
- …
=> Terminal local-echo tweaks and fixes

src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/modules/SessionWorkbench.cpp
- unset TERM for the Win32 terminal subprocess; it was previously unset (before I started setting it for the R Session for color console) and that's how git-bash likes it; with TERM set git-bash and/or winpty does weird stuff; verified change with git-bash, cmd, powershell, and WSL
- remove redundant settings of TERM in SessionWorkbench.cpp::startTerminal, as ConsoleProcess also sets it; verified on Mac that TERM is still set as-expected in terminal shell
=> fix git-bash in Windows terminal

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalLocalEcho.java
Darby sees issues with local-echo that I haven't been able to repro; putting in code that dumps the key info to the Javascript console to help identity what's going on. Expect to generate a forehead-slap "Oh, that's what's different on your machine" kinda thing.
Marked with a TODO and will remove when I make the actual fix.
=> local-echo mismatch diagnostics

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
I was trying to fix this 1px off issue in the workbench panels under flat theme:
After investigating, found this happens to be a chromium issue (no repro in other browsers), opened an issue for them: https://bugs.chromium.org/p/chromium/issues/detail?id=714247
The workaround is to not use bottom borders, which is also consistent with dialogs in the latest design.
=> Fix border rendering issue in flat theme

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/studio/client/workbench/codesearch/ui/CodeSearch.css, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectGrid.css, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/PackagesDataGridCommon.css
Couple (easy this time) 1px off fixes, flattening the environment/packages grid and the search boxes:
=> Flat theme for object grids and search boxes

src/gwt/src/org/rstudio/core/client/widget/ThemedPopupPanel.css
Menu and popup-menu shadows are now rendered using CSS. Also, subtle dimming of shadows for flat theme. Default theme:
Flat theme:
=> Flat menus and pupop-menus under flat theme

src/gwt/src/org/rstudio/core/client/theme/RStudioDataGridStyle.css, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.css
A few more flat theme improvements.
1. Support for satellite windows:
2. Fix minimized panel tabs:
3. 2x css triangle for file list grid:
4. Adjust dialog shadow:
and fix to git commit button.
=> Enable flat theme in satellite windows and imrpvements

src/cpp/core/CMakeLists.txt, src/cpp/core/include/core/text/AnsiCodeParser.hpp, src/cpp/core/text/AnsiCodeParser.cpp, src/cpp/core/text/AnsiCodeParserTests.cpp, src/cpp/session/SessionMain.cpp, src/cpp/session/SessionUserSettings.cpp, src/cpp/session/include/session/SessionUserSettings.hpp, src/gwt/src/org/rstudio/core/client/VirtualConsole.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java
New user preference to control Console's handling of ANSI escape characters. I'm not happy with the wording of these in the UI, so suggestions welcome as always:
1. Show ANSI Colors -- this is new default (at least at the moment) and converts ANSI style codes for colors, bold, etc. on Console output
2. Remove ANSI codes -- this still parses the ANSI codes, if present, but discards them rather than applying any styles
3. Ignore ANSI codes -- this is how RStudio 1.0 behaves; if ANSI codes are output to the console, they will be displayed as codes and not interpreted at all
Switching between these doesn't change anything already displayed, you need to refresh the IDE to have that happen, but will impact new output without refreshing.
Also added stub for server-side ANSI code processing; …
=> global option for console ANSI code behavior

src/cpp/session/SessionClientInit.cpp, src/cpp/session/SessionOptions.cpp, src/cpp/session/include/session/SessionOptions.hpp, src/cpp/session/modules/SessionWorkbench.cpp, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/model/WorkbenchServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/TerminalPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
- Add user preference for turning off websockets when connecting terminals
- Add feature limit (allow-terminal-websockets) for server-wide disabling of websockets
- User preference checkbox hidden if websockets are disabled on server
=> user option and feature limit for terminal websockets vs. RPC

src/gwt/src/org/rstudio/core/client/BrowseCap.java, src/gwt/src/org/rstudio/core/client/StringUtil.java, src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalLocalEcho.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalShellInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTab.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java
Created a modal info dialog to show various diagnostics about current terminal. This should be helpful in understanding issues customers might encounter (as well as current issues still under investigation). Put it all in a text field for easy copy/paste.
In addition to various settings and platform info, also shows if websocket connection was successful, and if local-echo matching failures are happening.
=> diagnostics dialog for terminal

Jenkinsfile, dependencies/linux/install-qt-sdk, docker-compile.sh, docker/docker-compile.sh, docker/jenkins/Dockerfile.centos7-i386, docker/jenkins/Dockerfile.centos7-x86_64, docker/jenkins/Dockerfile.precise-amd64, docker/jenkins/Dockerfile.precise-i386, docker/jenkins/Dockerfile.xenial-amd64, docker/jenkins/Dockerfile.xenial-i386, src/cpp/desktop/CMakeLists.txt
This change has three distinct parts:
It's not straightforward to install RStudio on systems based on Debian Stretch and Ubuntu Xenial, due to the introduction of new, incompatible system libraries on these distributions. This change adds a server build; when we're able to resolve dependencies in Qt we'll add a desktop build as well.
There's a new `docker-compile.sh` tool included here that's designed to make it easy for developers to simulate the builds that occur in the lab on their local machines, without installing Jenkins (or really any local software other than Docker itself).  
Formerly, Qt was downloaded every time we built RStudio in a container. We now download Qt and install it to `/opt` as part of the container's build process, so it can be cached.
=> Add Ubuntu Xenial builds

src/gwt/src/org/rstudio/core/client/files/filedialog/FileDialogStyles.css, src/gwt/src/org/rstudio/core/client/files/filedialog/PathBreadcrumbWidget.java, src/gwt/src/org/rstudio/core/client/theme/RStudioDataGridStyle.css, src/gwt/src/org/rstudio/core/client/theme/ThemeColors.java, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/application/ui/RStudioThemes.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/header/HeaderPanel.css, src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteManager.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectGrid.css, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectGrid.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/PackagesDataGrid.css, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/PackagesDataGridCommon.css, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/status/StatusBarWidget.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ChangelistTableCellTableStyle.css
More work remaining (mostly to sync ACE colors with other panes, say the packages or files pane), but a good chunk of the functionality is made available with this change:
Currently, there is a dropdown to select the theme, this will probably change soon:
=> Initial support for dark theme

src/cpp/core/system/PosixCrypto.cpp
This PR should enable building RStudio with OpenSSL <= 1.1 (at least it works with OpenSSL 1.1). I could not yet check this actual PR but a similar version located in my Arch Linux PKBGUILD [1]. To be completely able to build RStudio with OpenSSL 1.1 you are still required to patch around the missing `SSL_R_SHORT_READ`. Locally I use a modified version of #1063. 
Possibly this requires further tweaking and I feel a bit uneasy messing around with ssl. For now it is just what works in my non public environment. 
[1] https://github.com/JanMarvin/rstudio-archlinuxpkg/blob/master/rstudio-server/openssl11.diff
=> Allow building with OpenSSL 1.1

src/cpp/session/modules/SessionDataImportV2.R, src/gwt/src/org/rstudio/core/client/widget/ModalDialog.java, src/gwt/src/org/rstudio/core/client/widget/Wizard.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionWizard.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUi.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiCsv.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiSav.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiXls.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsXls.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/model/DataImportAssembleResponse.java
This PR adds support for `n_max` and `range` fields available now in `readxl 1.0`, disabled unsupported fields for older version of `readxl `. Refactored help links from `Wizard` to `ModalBase` and added links as follows:
- Reading Excel files using readxl -> http://readxl.tidyverse.org/
- Reading rectangular data using readr -> http://readr.tidyverse.org/
- Reading statistical data using haven -> http://haven.tidyverse.org/
@jennybc Feel free to post feedback on this PR or after trying this out in tomorrows build, thanks!
`n_max` and `skip` get disabled when `range` is specified.
`n_max` and `range` are disabled when `readxl < 1.0` is installed.
=> Support new readxl features and help links

src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/gwt/src/org/rstudio/studio/client/application/events/ThemeChangedEvent.java, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcess.java, src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteManager.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/model/ConsoleServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportDialog.java
On the server, the table of ConsoleProcess objects (s_procs) is used to map incoming console-process RPC calls to the appropriate metadata. If an RPC is made with a handle that's not in the server-side table, an error is shown. This table is used to track both terminal sessions, and non-terminal processes such as git commands, etc.
The client tries to bring up a ConsoleProgressDialog during session-init, if it sees one that isn't a terminal, and has output to show. The console-proc list on the client can get out of sync with the server, especially in cases such as closing or refreshing a window (main or satellite) containing an existing ConsoleProgressDialog modal dialog. This causes an error to be shown of the form "Error: Invalid argument." See attached animation for an example …
=> Stale ConsoleProcess handles on client cause error messages

src/cpp/session/modules/SessionRmdNotebook.R
This PR augments the RStudio-supplied `output_source` function with a `pre_knit` attribute, which is used to inject `knitr` chunk options as gleaned from the setup chunk.
See https://github.com/rstudio/rmarkdown/pull/1036.
=> supply 'pre_knit' hook with output_source

NEWS.md, src/cpp/desktop-mac/DockTileView.h, src/cpp/desktop-mac/DockTileView.mm, src/cpp/desktop-mac/MainFrameController.mm
Formerly we wouldn't show the label if there was only one instance of the IDE open. However, it's still useful to know which project you have open with a single IDE instance. This change just removes the check for a single instance and always shows the label.
=> Always show dock tile project label

src/cpp/r/R/Api.R, src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp
Made `clearTerminal` and `sendToTerminal` APIs operate on the server, instead of making client-calls.
Change `getTerminalContext` to only return info on one terminal at a time instead of a nested list.
After this, should only be additional testing and bug fixes on the API.
=> final tweaks to terminal APIs

src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
This small change fixes an issue in which opening multiple files at once in RStudio causes them to load in an apparently random order. The reason this happens is that opening a file involves a series of RPCs; these RPCs are all made at once and compete with each other. 
The fix is to apply some simple queuing behavior to the two RPCs which are invoked when opening a  file, so that we don't have more than one of each in flight at once.
=> Serialize RPCs so that files open in a predictable order

src/cpp/server/ServerMain.cpp, src/cpp/session/modules/SessionProfiler.cpp, src/cpp/session/resources/profiler/profiler.css, src/gwt/src/org/rstudio/core/client/theme/DocTabLayoutPanel.java, src/gwt/src/org/rstudio/core/client/theme/ThemeColors.java, src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/RStudioFrame.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionsPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsoleClearButton.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/ConsolePane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectList.css, src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FileCommandToolbar.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/plots/ui/PlotsToolbar.java, src/gwt/src/org/rstudio/studio/client/workbench/views/presentation/PresentationPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
- Applies themes to profiler (expect flamegraph which is rendered with SVG)
- Applies themes to toolbar icons to make to subtly reduce brightness
=> Apply themes to profiler and toolbar icons

src/cpp/session/modules/SessionHistory.cpp, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HistoryCompletionManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/history/model/HistoryServerOperations.java
This change makes two improvements to Ctrl+R reverse incremental search:
- The scope of the search is now limited to the current project's console history (it does not search the entire history archive). This makes it much faster to find and to re-use commands inside the same project, at the expense of making it more difficult to re-use commands from other projects.
- The search results now exclude obvious duplicates (i.e. identical, consecutive commands).
=> Limit reverse-i-search to current project; exclude obvious dupes

src/cpp/core/r_util/REnvironmentPosix.cpp, src/cpp/desktop-mac/AppDelegate.mm, src/cpp/session/CMakeLists.txt, src/cpp/session/r-ldpath.in
This PR fixes an issue where `rJava` can fail to load when running with R 3.4.0 under RStudio on macOS.
Although this issue was originally reported by a Homebrew R user, one can actually reproduce this with R 3.4.0 installed from CRAN, using the CRAN `rJava` binary as well. Compare:
```
kevin@cdrv:~/Library/R/3.4/library/rJava/libs
$ otool -L rJava.so
rJava.so:
rJava.so (compatibility version 0.0.0, current version 0.0.0)
@rpath/libjvm.dylib (compatibility version 1.0.0, current version 1.0.0)
/Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libR.dylib (compatibility version 3.4.0, current version 3.4.0)
/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1259.0.0)
/usr/lib/libSystem.B.dylib (compatibility …
```
=> use 'etc/ldpaths' for rJava on macOS as well

package/linux/debian-control/postinst-desktop.in, package/linux/debian-control/postinst.in, package/linux/debian-control/postrm-desktop.in, package/linux/debian-control/postrm.in
This change removes `sudo` from the debian pre/post install scripts, based on the following customer feedback:
1. `sudo` is not available on some minimal Debian-based distributions, so we need to add a dependency on it if we're going to use it in pre/post install scripts.
2. It should not generally be necessary to use `sudo` in these scripts because installers already run privileged.
As far as I can tell it is indeed unnecessary to use `sudo` here (an installer I built without them seems to work correctly), but usage of `sudo` goes back to the very first commit so I'm not sure why we use it. @jjallaire do you recall what the motivation was?
=> Remove sudo command from Debian pre/post install scripts

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
When using an editor theme with dark background, and the classic style, the panel that holds the terminal widgets had no styles applied and would flash white everytime you switched to terminal tab from console, find, etc.
Fixed by applying same styles used by terminal itself.
=> fix flashing when switching to terminal in dark editor themes

src/cpp/session/modules/SessionPackages.R
As discussed on https://github.com/edzer/sfr/issues/262, it seems that not a few people get confused by 404 errors when they click NEWS icons in "Check for Package Updates...".
I guess there are no perfect way to determine the right URL of NEWS file in a package, except for actually accessing the package page on CRAN. That said, we can check if "NEWS" is included in `system.file` of a package. If the package doesn't have "NEWS", we'd better try "news.html" rather than letting 404 error by doing nothing. So, this PR does not fix the issue completely, but reduces the errors to some extent.
=> Reduce 404 errors with NEWS

src/cpp/session/SessionConsoleProcessSocketTests.cpp
otherwise gcc complains ambiguity between std::make_shared() and boost::make_shared().
I'm pretty sure there are better ways, but this worked on my system (Ubuntu 16.10, stock gcc).
Related: http://stackoverflow.com/q/8356618/946850
=> Explicitly qualify make_shared()

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.java, src/gwt/src/org/rstudio/studio/client/application/ui/RStudioThemes.java
- OS X supports an "When scrolling" scrollbar option that this PR detects on boot. Detecting the state change of this property would require a timer that I believe makes sense to avoid since I don't see users changing this option continuously.
- Avoid changing `width`/`height` of scrollbars since data grids perform scrollbars computation that is not compatible with CSS styling of scrollbars; instead, added border and color changes to match the dark theme.
=> Apply theme to scrollbars with "when scrolling" check in OS X

src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/RMarkdownPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceBackgroundHighlighter.java
This PR allows users to toggle background highlighting for code chunks on / off as desired.
The primary motivation for this feature is diagnostics -- a number of users are reporting editor sluggishness when editing in large documents; this PR is mainly added to help evaluate / diagnose that sluggishness.
If preferred, we can keep this as a 'hidden' preference and not expose to the user; let me know what you think.
=> ui preference for chunk background highlighting

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/CallFramePanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/history/view/HistoryPane.java
Classic theme regression fixes:
- Fix environment pane spacing.
- Fix colors under call-stack and history.
- Fix severe performance degradation in rmarkdown under windows. Found this is somewhat related with applying `border-radius` with `overflow: hidden`. Setting `overflow` to `visible` seems to fix this, notice that scrollbars are not present since other elements will clip this anyways.
=> Classic theme regression fixes

src/cpp/session/modules/SessionFind.cpp
This PR fixes an issue where e.g. 'Find in Files' did not work on Windows when executed within a path containing non-ASCII characters. (Note that this implies that 'Find in Files' will still not work when in a path that's not representable in the system encoding, but that's a bigger bugfix).
Let me know if this feels like too broad a fix and it would be better to target the 'Find in Files' code directly.
=> convert paths to system encoding for shell commands

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
Regression I introduced fixing issue 6837, terminal flashes when switching tabs with dark background. Easy to fix, remove unnecessary setStyleName, leaving the addClassName that actually fixed the issue.
=> fix issue 6854, terminal clipped at bottom

src/cpp/session/resources/profiler/profiler.css, src/gwt/src/org/rstudio/core/client/layout/AnimationHelper.java, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTargetWidget.java
- Panel animations were lost under themes, this was caused by applying a background under themes that is not compatible with the way animations work (they change the parent `z-index` to `-10` which would leave them under the background).
- A few profiler color tweaks.
=> Restore panel animations under themes

src/gwt/src/org/rstudio/core/client/layout/DualWindowLayoutPanel.java
1. Boot RStudio for the first time or close all documents.
2. Create a new notebook, console gets minimized.
3. Clicking restore console won't work.
The problem is that we eagerly update `normalHeight_` when we are saving the client state. In general, preserving the window state should not have a side effect to the panels state which currently does in some situations, like the one mentioned above.
This behavior has been this was since the first commit so worth waiting for feedback from @jjallaire before the merge.
Already performed some light testing with different panel configurations validating the panels change and the state is preserved.
=> Fix console being stuck minimized after creating new notebook.

src/cpp/r/R/Tools.R
This PR suppresses warnings emitted by our `install.packages` hook of the form:
```
Warning in install.packages :
cannot open URL 'https://cran.rstudio.com/bin/macosx/el-capitan/contrib/3.4/PACKAGES.rds': HTTP status was '404 Not Found'
```
Within `utils::install.packages()`, R attempts to silence warnings using `options(warn = -1L)`; however, this does not deactivate any existing warning handlers, which we do attach in all of our hooked functions.
The solution here is fortunately simple -- we just need to check the `warn` option in our handler, and only forward the warning when the value of that option is positive.
=> suppress warnings emitted during package install

src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/SessionConsoleProcessApi.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/cpp/session/include/session/SessionConsoleProcessInfo.hpp, src/cpp/session/include/session/SessionTerminalShell.hpp, src/cpp/session/modules/SessionTerminalShell.cpp, src/cpp/session/modules/SessionWorkbench.cpp
When creating a terminal, the shell type is specified as `default` and the code picks the appropriate shell type (currently always bash on everything but Windows, but could be extended in the future on all platforms, e.g. to support custom user-shells, or shells that automatically launch Python, and so on).
Need to know what shell was actually selected by the code so I can display it via the API, implement some shell-type specific logic at runtime (needed to fix some shell-specific Windows issues, NYI), and support other future scenarios.
=> capture concrete terminal type in ConsoleProcessInfo

src/gwt/src/org/rstudio/core/client/widget/ModifyKeyboardShortcutsWidget.css, src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.css, src/gwt/src/org/rstudio/studio/client/workbench/BrowseAddinsDialog.java
Minor tweaks to dialogs hosting grids under modern theme. They were missing backgrounds, borders and correct separators:
=> Apply flat theme to dialog grids

src/cpp/session/modules/SessionConnections.R
Minor bug in New Connections dialog: We suggest `sparklyr` and `odbc` when no connections are available; however, once installed, we were filtering based on name not on package/version.
=> Avoid suggesting already-installed package connections

src/cpp/session/SessionUserSettings.cpp, src/cpp/session/modules/ModuleTools.R
Implements `.rs.removeUiPref` to remove a UI prefs programmatically, we can close this PR if there is already an easy way to accomplish this, but there is not to my knowledge.
=> Implement .rs.removeUiPref to remove ui prefs

src/gwt/src/org/rstudio/core/client/layout/DualWindowLayoutPanel.java, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.css, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialogResources.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/MainSplitPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java
Currently (and also in Classic themes), the splitters are only `3px` wide; under the Modern theme, this is a bit worse since there is more space between the panels but only `3px` are draggable, this change increases this size to fully contain the spacing. However, since `SplitLayoutPanel` only allows setting the thickness during construction of this widget, this change requires closing/reopening the IDE for the change to take effect.
=> Make panel splitters fully draggable

src/cpp/session/SessionConsoleProcess.cpp, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
Reloading buffer into a new Command Prompt or PowerShell session in Windows terminal causes WinPty and the underlying console to get confused. Per discussion a while back, I'm just disabling buffer reload into these terminal types.
=> Stop buffer reload for Windows cmd and powershell

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
Under dark themes, checkboxes are missing the background. Under linux with highDPI, checkboxes render at half the size. Looks to be the case that we would be better of drawing checkboxes everywhere; can we think of cases where we wouldn't want this?
OS X (retina):
Linux (HighDPI):
=> Use custom checkboxes under themes to enforce same rendering

src/gwt/src/org/rstudio/core/client/events/MouseDragHandler.java, src/gwt/src/org/rstudio/studio/client/ResizableHeader.css, src/gwt/src/org/rstudio/studio/client/ResizableHeader.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/view/ObjectExplorerDataGrid.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
This PR makes it possible to resize columns within the object explorer, and also provides a `ResizableHeader` class that can be used with other DataGrid objects.
This is accomplished by drawing 'splitter' divs that intentionally overflow over the table header's borders, and attaches click handlers to those elements that can be used to update the column width. For users that accidentally drag themselves into a weird state, the 'refresh' button restores the default column widths (used when the table was initialized).
=> implement column resize for object explorer

src/cpp/session/SessionClientEvent.cpp, src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/TerminalCwdEvent.java
Previous preserve terminal cwd work missed the case where the UI isn't restarted but R session restarts; this was due to client not being notified of changes in cwd by server, so had stale metadata. Now that server listens to what directory the client wants to use, it started terminal with the old one.
Previous fix covered cases such as refreshing browser while a terminal was running, etc. Those queried the server for the metadata versus using the client-side metadata.
This covers all scenarios I've been able to find.
=> Preserve terminal cwd after an R restart

src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/application/ui/RStudioThemes.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
This PR makes the "modern" theme the default theme for all users, opt-out by switching back to "Classic" theme from appearance preferences dialog.
We can use this PR to discuss the right time to make this the default and merge afterwards.
=> Set modern theme as default theme

src/gwt/src/org/rstudio/core/client/dom/DomUtils.java, src/gwt/src/org/rstudio/core/client/widget/Toolbar.java
This PR removes a Safari workaround for the positioning of toolbar items, whereby the positioning of these icons was not consistent across different file types.
This should also resolve an issue wherein the pillbox associated with the 'Compile PDF' output was not visible. Because that pane toggled the visibility of separators + widgets manually, but not through `manageSeparators()`, the requisite update of the display of table cells never happened and so the table cells remained hidden even after compile finished.
(Note: `isSafari()` is a bit of a misnomer; it should really be `isAppleWebKit()` or `isSafariWebKit()` as those styles apply to our Desktop products, which use a fork of Apple WebKit and so do report `safari` in their user agent)
Note: this is a candidate for the patch release; …
=> remove old Safari workarounds

src/cpp/session/modules/SessionPackages.R
Related to this PR (https://github.com/RcppCore/Rcpp/pull/694) and new CRAN requirements for registration of native routines.
This should also be backported.
=> Add .registration=TRUE to useDynLib when Rcpp >= 0.12.11

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/LeftRightToggleButton.css
This PR works around a Safari bug whereby empty table cells with `padding: 0` will affect the sizing + layout of other table cells contained within that table.
[Click here](https://output.jsbin.com/faxulaluxa) to see an example `jsbin` demonstrating the behavior, and compare the appearance with e.g. Chrome vs. Safari.
Safari: ![screen shot 2017-05-22 at 4 28 22 pm](https://cloud.githubusercontent.com/assets/1976582/26332487/bd2372c4-3f0b-11e7-8a79-2e85b7035bc4.png), Chrome: ![screen shot 2017-05-22 at 4 28 27 pm](https://cloud.githubusercontent.com/assets/1976582/26332488/bd25450e-3f0b-11e7-8bd9-8b7b66e08f4f.png)
Somewhat fortuitously, setting a very small, fractional padding seems to work around this particular issue.
=> workaround Safari bug re: sizing of empty table cells

src/gwt/src/org/rstudio/core/client/theme/ModuleTabLayoutPanel.java, src/gwt/src/org/rstudio/core/client/theme/RStudioDataGridStyle.css, src/gwt/src/org/rstudio/core/client/theme/ThemeColors.java, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/ProgressSpinner.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectGrid.css, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/common/ChangelistTableCellTableStyle.css
A few more improvements under themes:
- Fixed regression in headers height caused by checkboxes change.
- Add canvas based progress in document tab.
- Change colors of git row selectors to match themes.
=> Grid header height, tab progress and git selectors under themes

Jenkinsfile
This will actually hold the job completion until the docs build is complete (~1min extra).
=> trigger downstream docs build if pro build

src/cpp/core/include/core/r_util/RProjectFile.hpp, src/cpp/core/include/core/system/PosixSystem.hpp, src/cpp/core/include/core/system/System.hpp, src/cpp/core/r_util/RProjectFile.cpp, src/cpp/core/system/PosixSystem.cpp, src/cpp/core/system/Win32System.cpp, src/cpp/session/SessionClientInit.cpp, src/cpp/session/SessionMain.cpp, src/cpp/session/SessionOptions.cpp, src/cpp/session/http/SessionHttpConnectionUtils.cpp, src/cpp/session/include/session/SessionMain.hpp, src/cpp/session/include/session/SessionOptions.hpp, src/cpp/session/projects/SessionProjects.cpp, src/gwt/src/org/rstudio/studio/client/projects/model/RProjectConfig.java, src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectGeneralPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java
This pull request adds a new feature than can be toggled on or off to control whether or not child processes of the session are closed when the session is exited.  The default setting is false. It can be set as a session-wide setting in rsession.conf, and can be overridden in each project via a project setting.
A few tweaks were made to PosixSystem to get additional process info I needed, such as the ppid and pgrp.
=> Feature: Close child processes on exit

NEWS.md, src/cpp/session/modules/NotebookData.R, src/cpp/session/resources/pagedtable/pagedtable.js, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/ChunkOptionsPopupPanel.java
1. Porting two fixes performed already in `rmarkdown` see https://github.com/rstudio/rmarkdown/pull/1056
2. Adds "Use paged tables" to chunk options popup. While paged tables have been working correctly in most cases, for cases like (1), users can be completely blocked from viewing data unless they know about the `paged.print=FALSE` option, which is unlikely.
=> Two paged table fixes from rmarkdown and "Use paged table" option

src/gwt/src/org/rstudio/core/client/StringUtil.java, src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/test/org/rstudio/core/client/StringUtilTests.java
Previously when refreshing UI, we played the ConsoleActions back in reverse order, until our maximum number of console lines was displayed. Server keeps up to 1000 console actions, but each console action can generate multiple lines of output, this is why it was done this way.
This reverse playback made client Ansi parsing more difficult, often breaking reload of console with Ansi color output, and the resulting DOM had many more nodes than the DOM created during regular usage of the console, impacting performance. Another consequence was any special parsing done on console DOM had to account for both possible structures (regular and reloaded). There are some bugs in that area, and wanted to do this change before getting to those.
Now we do an initial pass through the ConsoleActions in …
=> Play console actions back in regular order

src/gwt/src/org/rstudio/core/client/VirtualConsole.java, src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputStream.java
The enhanced error widget was eating the previous span, which could contain not only the previous error, but additional errors before it. This is due to optimizations made in VirtualConsole to combine ranges with the same style.
Fix is to not do this for errors; always start a new output range for an error message (but still combine a single multi-line error message into a single span).
This does **not** fix several issues with Ansi codes in error messages, both in the console and in the error widget. That is tracked with a separate bug case.
=> Fix issue with traceback widget eating preceding console output

src/cpp/core/r_util/RProjectFile.cpp
This is consistent with the behavior of other project options we've introduced outside of the core ones.
The rationale is that if allow new values to be written then user's .Rproj files are constantly getting diffs when they upgrade versions. This might be okay in some cases, but for options like this one which are advanced and disabled by default it will likely just stir up questions / support incidents.
=> Only write QuitChildProcessesOnExit when it's not "Default"

Jenkinsfile, dependencies/linux/install-dependencies-zypper, docker/docker-compile.sh, docker/jenkins/Dockerfile.opensuse-x86_64
Prior to this change, we built RStudio Server for SLES by re-using the CentOS 6 image. The resultant RPMs turned out not to be usable on SLES due to differences in the OpenSSL libraries we linked against. 
Rather than try to coerce the CentOS images to produce a binary that works on SLES, this change adds a new image which builds on openSuSE itself.
=> Add openSuSE docker builder; replaces cross-building on CentOS

src/gwt/src/org/rstudio/core/client/AnsiCode.java, src/gwt/src/org/rstudio/core/client/VirtualConsole.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilePathToolbar.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditorWidget.java, src/gwt/test/org/rstudio/core/client/AnsiCodeTests.java
- Added unit tests for ansi parsing (client-side)
- Added parsing for Ansi font escape sequences, but not using them for anything (idea was to support font9 to change line-height; not going to work on that anytime soon, probably not for 1.1, but had already done the parsing so getting it in). Note that line-height would have to apply on a block level, not on a span level, so ansi parsing now differentiates between inline and block styles.
- Fixed some Eclipse "unused" warnings
=> unit tests for ansi parsing, fix eclipse warnings, font code parsing

src/gwt/src/org/rstudio/core/client/VirtualConsole.java, src/gwt/test/org/rstudio/studio/client/VirtualConsoleTests.java
A couple of closely related VirtualConsole fixes. These were found by mixing \r and Ansi color codes. Added unit tests to catch/test these cases. Visual examples of fixes attached.
=> virtual console fixes related to \r and complex styles

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/Renderer.java
This PR fixes an issue where the cursor would start blinking after highlighting a region of text using the mouse, even if the user had opted in to using no blinking cursor.
The `$cursorLayer` APIs are somewhat private (and toggled internally by Ace during mouse drag events); the suggested mechanism for controlling this is through an editor option.
=> use Ace public API for non-blinking cursor

src/gwt/src/org/rstudio/core/client/command/AppCommand.java, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/CheckableMenuItem.java, src/gwt/src/org/rstudio/studio/client/application/ui/RStudioThemes.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionPopupPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanel.css, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTargetWidget.css
Invert submenu checks under dark menus:
=> Submenus under dark themes show dark checkbox

src/cpp/core/system/PosixSystem.cpp
On the Mac some child processes exist as a side effect of the call to getChildProcesses (sh, ps, awk). This results in a regular stream of error messages at the dev console, so we suppress that particular error to prevent bogus error states.
While this could prevent our seeing a legitimate error, it will also prevent "log chatter" which can obstruct seeing real errors (i.e. we become so used to seeing errors logged that we start generally ignoring them). The latter is viewed a bigger problem than the former, especially given how unlikely it is in this case that we are masking a legit error condition.
We could further scope this check to development mode, however I think keeping "expected" errors out of production logs is also a good thing.
More intrusive and complex fixes are possible …
=> Prevent log chatter from terminateChildProcesses

src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImportOptionsUiSav.ui.xml
The dropdown for SPSS was too tall and the data viewer checkbox not padded...
=> Data import SPSS dropdown too big

src/cpp/session/modules/SessionCodeSearch.cpp, src/cpp/session/modules/SessionCodeTools.R
This PR ensures that function lookup succeeds in cases e.g.
```
library(shiny)
runApp()
```
where the user attempts to look up the definition of `runApp()`, when the `shiny` package is not actually loaded. Because we cache information about packages and the symbols they export as a background task, we can use that database to inform RStudio that we can successfully look this function up.
=> look up function definitions in completion database

src/cpp/session/SessionClientInit.cpp, src/cpp/session/SessionOptions.cpp, src/cpp/session/include/session/SessionOptions.hpp, src/cpp/session/modules/SessionGit.cpp, src/gwt/src/org/rstudio/core/client/MessageDisplay.java, src/gwt/src/org/rstudio/studio/client/common/vcs/StatusAndPathInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPresenter.java
This PR shows the user a warning dialog when attempting to commit large files (> 10 megabytes in size), e.g.
Typically, once a large file has entered a Git repository, that repository will balloon in size and it can be quite difficult to remove that file + prune the repository (especially if more commits are made after the fact). This should hopefully act as a shield against the accidental commit of large files.
=> warn when attempting to commit large files

src/cpp/session/modules/SessionGit.cpp, src/gwt/src/org/rstudio/studio/client/common/vcs/GitServerOperations.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.css, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPanel.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/git/dialog/GitReviewPresenter.java
This PR adds an 'Ignore Whitespace' checkbox to the Git diff view, allowing users to toggle off / on whitespace-only diffs. Compare e.g.
=> add 'ignore whitespace' checkbox for git diff

src/gwt/src/org/rstudio/core/client/ConsoleOutputWriter.java, src/gwt/src/org/rstudio/studio/client/common/shell/ShellWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionPopupPanel.java, src/gwt/test/org/rstudio/core/client/ConsoleOutputWriterTests.java, src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java, src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java
There have been quite a few regressions in the console behavior, both from the VirtualConsole performance improvements a while back, and the addition of Ansi codes (and enabling those codes within error messages).
As I work on fixing them, I've been building up a set of test cases (via R), and manually running and eyeballing the results in the IDE.
In this PR I've ported them to be unit tests, by pulling out logic from `ShellWidget` into a more unit-testable `ConsoleOutputWriter` class. This allows testing of the interactions between regular and error outputs, in the presence of ansi codes, multi-line output, etc. The resulting DOM is checked against what is expected, including color styles, order and number of created spans, and capability to get the set of nodes representing the last …
=> unit testing for console behaviors

src/cpp/r/R/Api.R, src/cpp/session/SessionConsoleProcessApi.cpp
Renamed all the terminal APIs to have a common prefix.
activateTerminal ->  terminalActivate
clearTerminal -> terminalClear       
createTerminal -> terminalCreate
getAllTerminals -> terminalList
getTerminalBuffer -> terminalBuffer
getTerminalContext -> terminalContext
getVisibleTerminal -> terminalVisible
isTerminalBusy -> terminalBusy
isTerminalRunning -> terminalRunning
killTerminal -> terminalKill
sendToTerminal -> terminalSend
=> rename terminal APIs with common prefix

dependencies/windows/install-dependencies.cmd, src/cpp/CMakeLists.txt
Integrate WinPty 0.4.3. Relatively minor bug-fix release with no API signature changes. New package is up on rstudio-buildtools on AWS. Windows build machine requires updated dependencies.
Doing additional sanity testing now, including a 32-bit build.
**Don't merge until I give thumbs-up.**
https://github.com/rprichard/winpty/releases/tag/0.4.3
=> Update to WinPty 0.4.3

src/cpp/session/modules/SessionCodeTools.R
As mentioned in `?formals` the formals of primitive functions can be
retrieved with `formals(args(.))`.
The previous behavior caused an unfortunate interaction between
RStudio's completion engine and the [lookup
package](https://github.com/jimhester/lookup), which uses a custom
`print.function` when **lookup** is attached, and was being
inadvertently called during argument completion.
Fixes https://github.com/jimhester/lookup/issues/14
I think the `tryCatch()` could probably be removed as well, `formals(args(fun))` should work for all primitive functions as far as I am aware. 
I did not build the IDE to test this change.
=> Simplify extraction of formals from primitive functions

src/gwt/src/org/rstudio/core/client/command/BaseMenuBar.java, src/gwt/src/org/rstudio/core/client/dom/DomUtils.java, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/CustomMenuItemSeparator.java, src/gwt/src/org/rstudio/core/client/widget/ScrollableToolbarPopupMenu.java, src/gwt/src/org/rstudio/core/client/widget/SearchWidget.java, src/gwt/src/org/rstudio/core/client/widget/ToolbarPopupMenu.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/BranchToolbarButton.css, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/BranchToolbarButton.java
This PR implements filtering of toolbar menus, and uses it with the Git branch toolbar menu to allow for quick search + selection of Git branches. I'm hoping this will become handy for other various toolbar menus we show where there are a large number of items to be displayed.
Feedback is welcome, especially what we can do to improve discoverability of this feature. Note that currently the search bar is activated simply by typing after the menu has been opened.
I'll also need to make sure we appropriately theme + style the search widget here.
=> implement filtering of toolbar menus

src/cpp/session/SessionUserSettings.cpp, src/cpp/session/include/session/SessionTerminalShell.hpp, src/cpp/session/include/session/SessionUserSettings.hpp, src/cpp/session/modules/SessionTerminalShell.cpp, src/cpp/session/modules/SessionWorkbench.cpp, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/TerminalPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalShellInfo.java
Provide option for user to customize the shell program launched by the terminal. There were already several options on Windows (git-bash, cmd, powershell, etc.), but previously only the default Bash on Mac/Linux/Server. Now that preferences dropdown is visible on non-Windows and includes a new "Custom" option which lets user specify a command and command-line arguments for that command.
For example, normal shell setting on non-Windows:
And a custom setting:
=> Custom shell setting for terminal

src/gwt/src/org/rstudio/core/client/widget/BottomScrollPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/history/History.java, src/gwt/src/org/rstudio/studio/client/workbench/views/history/view/HistoryPane.java
This PR does a couple things:
1) Fixes the behavior of `Enter`, `Shift + Enter` when the History pane is focused through e.g. `Ctrl + 4`. Previously, `Shift + Enter` would still send code to the console rather than the source window.
2) Ensures that the vertical scroll position is not changed when activating the History pane. (Previously, pressing `Ctrl + 4` would always scroll the history output to the bottom, which was typically undesired)
=> tweak keyboard handling with History pane

src/cpp/session/modules/SessionTerminalShell.cpp, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java
Use a textbox for entry of custom terminal shell. This is an advanced feature, and file pickers can make it hard to navigate to Unix-y paths (especially on Mac file picker), and may not deal well with soft-links.
Also turned off custom shell option for Windows. Not tested, and likely not very useful. Can reconsider if we get feedback on the subject.
=> use textbox instead of file picker for custom shell selection

src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.java, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/application/ui/RStudioThemes.java, src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteManager.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
Themes under sky and dark editor do not look good; instead, use dark-grey theme for ace themes regardless of the rstudio theme selection.
=> Feature dark theme for sky theme

src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/SessionConsoleProcessInfo.cpp, src/cpp/session/SessionConsoleProcessInfoTests.cpp, src/cpp/session/SessionConsoleProcessPersist.cpp, src/cpp/session/SessionConsoleProcessTests.cpp, src/cpp/session/SessionUserSettings.cpp, src/cpp/session/include/session/SessionConsoleProcessInfo.hpp, src/cpp/session/include/session/SessionUserSettings.hpp, src/cpp/session/modules/SessionWorkbench.cpp, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcessInfo.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/model/WorkbenchServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java
Added plumbing and user option to keep terminal panes open after process exits. This will make it easier to add capability to run a command in a terminal pane, without a shell, and keep pane around to show the results (this will be via a new rstudioapi, NYI).
FYI, this change added new ConsoleProcessInfo metadata, so I bumped up the storage revision number for saving open processes (console05); first time running this build you will lose any previously created terminals.
As a side effect, found and fixed a bug that had been seen occasionally before, where trying to close a terminal tab gave an error. Cause was websocket connection closing but terminal remaining open, which is much easier to get into with this work. Fix was to not dereference a null websocket object in the client.
=> Add option to keep terminal pane open after process exits

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
Dark themes render incorrectly in firefox, this is a regression from the scrollbars change since the property gets ignored in firefox and colors cascade down to the wrong elements.
=> Fix dark theme under Firefox

src/gwt/build.xml, src/gwt/src/org/rstudio/studio/RStudioDesktopSuperDevMode.gwt.xml
There might be a reason why we didn't add this in the first place, but as far as I can see, this works (at least on macOS) for a devmode experience with the desktop product. With this PR, we can use
ant desktop
to build the desktop version of the sources in the regular devmode configuration. One just needs to run a debug build of the desktop product, and things appear to work as expected.
=> add desktop devmode

src/gwt/src/org/rstudio/studio/client/application/ui/RStudioThemes.java
In the weekend builds, when a dark editor theme is selected, reverting to classic mode is not supported. The workaround is to use non-dark editor theme until build 1.1.269 is out.
=> Fix to allow classic theme under dark editor

src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcessInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
Wanted to do this refactoring for a while, should make longer-term maintenance of the feature easier.
TerminalList has a private class, TerminalMetadata, which holds a subset of the metadata of ConsoleProcessInfo, and is used to track all known terminals, whether or not they have been connected or displayed in the current session.
This led to a bunch of parameter-laden constructors/methods for various scenarios, in both TerminalList and TerminalSession classes, such that adding one field to ConsoleProcessInfo ended up requiring modifications in a BUNCH of places.
Now I've added the necessary "create" calls to ConsoleProcessInfo itself, and pass instances of that class around instead.
Not perfect, there is still some duplication of metadata in TerminalSession, but I don't want to mess with …
=> replace TerminalList.TerminalMetadata with ConsoleProcessInfo

src/gwt/src/org/rstudio/core/client/widget/ThemedPopupPanel.css
Suggestions popup was missing to be flat and selection hover was not working under dark theme:
=> Make search suggestions flat and usable in dark theme

Jenkinsfile, Jenkinsfile.macos, package/osx/CMakeLists.txt
Using a separate pipeline file for now (macos can't be dockerized and the differences are a bit awkward to introduce to the main build file at this time).
This is a reasonable example of the new declarative pipeline syntax which keeps things a bit cleaner and more readable -- but loses some of that groovy ✨
=> Add macos jenkins pipeline

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/ThemedPopupPanel.java, src/gwt/src/org/rstudio/studio/client/application/ui/RStudioThemes.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanel.css, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanel.java
Add support for dark scrollbars within autocomplete popups (otherwise they render light grey/default):
=> Support dark scrollbars in autocomplete popups

src/cpp/session/resources/R.css, src/cpp/session/resources/grid/gridstyles.css, src/gwt/src/org/rstudio/core/client/widget/InfoBar.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanel.css, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/pastel_on_dark.css, src/gwt/tools/compile-themes.R
- Warning bars under dark theme
- Help titles
- Selection under help and data viewer
- Apply existing "pastel on dark" color tweak to help
- Autocomplete help links
=> A handful of minor flat theme dark improvements

src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/SessionConsoleProcessApi.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/model/ConsoleServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
Some lingering issues with terminal when doing `build and reload` and `restart R` where made very obvious (and much worse) with the changes I added to support keeping terminal panes open after the process exited (`zombie terminals`).
First, during an R restart, the server was notifying the client that the terminal processes had died, and the client was closing the client-side pane and then trying to reap those ConsoleProcs (a call back to the server). This was wrong, because we don't want to reap the consoleProcs in that case; we want to keep them around so the terminals could be reconnected. This wasn't much of an issue on server, it seems, as communication was cut-off before these events got propagated. On desktop IDEs, the events would get through, at least partially, leading to a …
=> Fix terminal issues with build and reload, restart R

src/cpp/session/SessionConsoleProcessPersistTests.cpp
When building debug client IDE on Ubuntu 16, get a bunch of warnings about "suggest parentheses" in one of the unit tests. Fixed.
=> Fix "suggest parentheses" compiler warnings in a unit test

src/cpp/session/SessionConsoleProcessPersist.cpp
@kevinushey saw message below in his server log, it would happen when recreating a terminal after a restart if the terminal's buffer file didn't exist (as happens after a Ctrl+L, for example). Fix is to short-circuit if the file doesn't exist rather than trying to do stuff with it.
`07 Jun 2017 23:13:22 [rsession-kevin] ERROR system error 2 (No such file or directory) [path=/Users/kevin/rstudio/.Rproj.user/4F86FB9D/console04/D3EC94E9]; OCCURRED AT: rstudio::core::Error rstudio::core::FilePath::open_r(boost::shared_ptr<std::istream> *) const /Users/kevin/rstudio/src/cpp/core/FilePath.cpp:1109; LOGGED FROM: void rstudio::session::console_process::console_persist::deleteLogFile(const std::string &, bool) /Users/kevin/rstudio/src/cpp/session/SessionConsoleProcessPersist.cpp:214`
=> Don't try to trim terminal log file if it doesn't exist

dependencies/common/install-pandoc, dependencies/common/rstudio-tools
This PR uses Gabor's universal pandoc binary for 64bit Linux builds.
I also ported some of the old Bash helper functions from the old PR (just so we have it if we need it in the future) but note that most of that is unused in this PR.
=> use Gabor's universal pandoc binary on Linux

src/cpp/session/modules/SessionGit.cpp
This PR fixes a bug where paths containing backslashes would not be handled correctly in the RStudio Git interface.
`git` documents `core.quotepath` as (https://www.kernel.org/pub/software/scm/git/docs/git-config.html), emphasis mine:
> Commands that output paths (e.g. ls-files, diff), will quote "unusual" characters in the pathname by enclosing the pathname in double-quotes and escaping those characters with backslashes in the same way C escapes control characters (e.g. \t for TAB, \n for LF, \\ for backslash) or bytes with values larger than 0x80 (e.g. octal \302\265 for "micro" in UTF-8). If this variable is set to false, bytes higher than 0x80 are not considered "unusual" any more. **Double-quotes, backslash and control characters are always escaped regardless of the setting of this …
=> use '-z' for machine-parsable git status output

src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RmdTemplateData.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RmdTemplateFormatOption.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetRMarkdownHelper.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/ChunkContextUi.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/ChunkOptionsPopupPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/CustomEngineChunkOptionsPopupPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/DefaultChunkOptionsPopupPanel.java
A few paged table fixes and improvements:
1. Make paged tables the default option while knitting to html. Otherwise, notebooks preview does not match html output since we use paged tables in notebooks by default.
2. Add `df_print` option to notebook settings to allow users to switch to and away from `paged` with ease.
3. Made "Use paged tables" option under chunk settings opoup only visible under r chunks.
4. Fix to `rmarkdown` to support row names in the same way as notebooks. https://github.com/rstudio/rmarkdown/pull/1086
5. Improvements to `rmarkdown.rstudio.com` to show all options and demonstrate paged tables in the actual section. https://github.com/rstudio/rmarkdown/pull/1087
=> Paged table improvements and bug fix

src/cpp/session/SessionHttpMethods.cpp
This fixes an issue wherein input handlers registered by the `later` package are never processed by RStudio. This PR deserves some extra scrutiny since it changes how often we process R events in server configurations, and there may be pitfalls in doing so.
@jjallaire, do you by any chance have any context for why we were only pumping events in desktop mode? From what I gather from hunting through the R sources, much of this was done primarily to ensure that events were processed while e.g. graphics devices are running, but it may well be fine just to ensure eager event processing in server configurations as well.
=> process events in both server, desktop configurations

dependencies/common/install-packages, src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/NotebookHtmlRenderer.java
And stop bundling the `rmarkdown` package. (we should wait until the binaries have been built and propagated on the CRAN machines before merging)
As an aside, it looks like we're also bundling the `rsconnect` package -- do we want to continue bundling that, or can we depend CRAN release as well?
```
src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
155:      deps.add(Dependency.embeddedPackage("rsconnect"));
```
=> depend on rmarkdown from CRAN

src/cpp/session/SessionConsoleProcessTests.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp
Warnings noticed during a build on Linux.
=> Fix size/unsigned comparison warnings on Linux build.

src/cpp/r/R/Api.R, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java
This PR allows for API calls of the form:
.rs.api.navigateToFile("file", -1L, -1L)
to preserve the preserve cursor position when the file "file" is opened. A corresponding change in the `rstudioapi` package will be made to take advantage of this behavior.
https://github.com/rstudio/rstudioapi/pull/48
=> allow 'navigateToFile' to preserve position

src/cpp/r/R/Api.R
See associated implementation of `rs_restartR` at:
https://github.com/rstudio/rstudio/blob/eecd9388c4e97f4bf1867c80b33ef1042b038b5a/src/cpp/session/SessionModuleContext.cpp#L352-L360
We actually already export this function's use through the `restart` R option as well:
https://github.com/rstudio/rstudio/blob/eecd9388c4e97f4bf1867c80b33ef1042b038b5a/src/cpp/r/R/Options.R#L76-L77
but this makes it more explicitly available + makes it possible to use through `rstudioapi`.
=> provide API for restarting R

src/cpp/session/SessionConsoleProcessInfoTests.cpp
Failure in win32 unit test because `FilePath` class does some platform-specific normalization, and hardcoded paths in test were Posix-ish instead of Windows-ish. Paths don't actually have to exist for tests to pass, just behave consistently inside of `FilePath`.
=> fix win32-specific rsession unit test failure

src/gwt/src/org/rstudio/core/client/widget/ModalDialogBase.java, src/gwt/src/org/rstudio/studio/client/application/ui/RStudioThemes.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/InstallPackageDialog.java
Dark suggestions are being displayed in packages dialog, disable dark menus for this dialog.
=> Do not apply dark themes to install packages

src/cpp/r/R/Api.R, src/cpp/session/SessionClientEvent.cpp, src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp, src/cpp/session/modules/SessionCodeTools.R, src/cpp/session/projects/SessionProjects.cpp, src/gwt/src/org/rstudio/studio/client/projects/Projects.java, src/gwt/src/org/rstudio/studio/client/projects/events/RequestOpenProjectEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java
This PR adds the `openProject()` API to RStudio, which allows users to open an existing project (when provided a `.Rproj` file), or create a new project (when provided a directory containing no `.Rproj` file).
Is it worth separating this into two functions (`createProject()`, `openProject()`)? Or is it fine to have `openProject()` handling the responsibilities of both 'create a new project and open it' vs. 'open an existing project'?
=> provide APIs for creating / opening RStudio projects

src/cpp/session/SessionConsoleProcessPersist.cpp
Change root of terminal metadata storage to `scopedScratchPath` instead of `sessionScratchPath`. Net result is to make terminal storage be in the same location it was before this change: 04106703a0f9500d132a9d461273a649296478bf
Additional terminal persistence changes will be needed due to discoveries made in conversations after that change: RSP with multiple sessions, and desktop IDE with multiple windows open on the same project. Those scenarios can result in real-time sharing of the terminal metadata (which the code doesn't support).
=> Change root folder for terminal metadata

src/gwt/src/org/rstudio/core/client/Stopwatch.java, src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java
I already had code to compute typing lag in terminal, hidden behind an undocumented user preference and reporting to Javascript console. Got rid of preference, and just show the value in Terminal Diagnostics.
Also removed some unused imports reported by Eclipse.
=> Show terminal typing lag in diagnostics dialog

docker/jenkins/Dockerfile.windows
missed this tweak when swapping between my dev environment and the windows env!
=> use windows 7.1 sdk in docker build

src/cpp/session/SessionModuleContext.cpp
The macOS High Sierra beta has changed the behavior of the `file` command when invoked with the `--mime` argument, such that it does not actually produce the understood mime-type of the file. (Instead, it seems to produce the 'human readable' output; e.g. `regular file` for `DESCRIPTION` files).
The result is that text files without a known mime-type encoded directly in RStudio cannot be opened under macOS High Sierra; e.g.
While it's possible that Apple will fix this bug before they ship macOS High Sierra, this PR should guard us in case that behavior leaks into Apple's next OS release.
(note: this PR would be a candidate for the patch release)
https://github.com/lionheart/openradar-mirror/issues/17559
=> work around change in 'file' output

src/cpp/session/SessionConsoleProcess.cpp, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
When terminals are restarting (especially when opening a project's previous terminal instances) they often display with no prompt. Hitting <enter> will generate a prompt, but still looks bad.
Caused by a previous fix to reduce duplicate prompts piling up when doing builds or R restarts (https://github.com/rstudio/rstudio/pull/1206). Fix is to accumulate terminal output when restoring the buffer, then play it back when reloading is completed. Otherwise the real prompt can be deleted by `writeRestartSequence` depending on timing.
While I was at it, noticed the `restarted` flag on ConsoleProcessInfo wasn't accurate; it was intended to only be `true` if this terminal instance was a reload of a previous terminal session that was killed, versus a brand new terminal session. Fixed, and also now …
=> Fix: reloaded terminals not showing a prompt

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermNative.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
If a full-screen program is running and the terminal is killed on the server (e.g. R restart), the client terminal emulator keeps showing the alt-buffer when it is restarted. Fixed by detecting this condition and forcing terminal back to primary buffer via esc sequences.
=> Fix: terminal stuck in alt-buffer after forced restart

src/cpp/desktop-mac/GwtCallbacks.mm, src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/cpp/r/R/Api.R, src/cpp/session/SessionClientEvent.cpp, src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp, src/cpp/session/modules/RStudioAPI.cpp, src/gwt/src/org/rstudio/core/client/files/filedialog/ChooseFolderDialog2.java, src/gwt/src/org/rstudio/core/client/files/filedialog/OpenFileDialog.java, src/gwt/src/org/rstudio/core/client/files/filedialog/SaveFileDialog.java, src/gwt/src/org/rstudio/core/client/files/filedialog/events/OpenFileDialogEvent.java, src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java, src/gwt/src/org/rstudio/studio/client/common/FileDialogs.java, src/gwt/src/org/rstudio/studio/client/common/impl/DesktopFileDialogs.java, src/gwt/src/org/rstudio/studio/client/common/impl/WebFileDialogs.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/Workbench.java, src/gwt/src/org/rstudio/studio/client/workbench/model/WorkbenchServerOperations.java
This PR exposes three file dialogs, eventually to be used as part of the `rstudioapi` package. The three APIs provided:
1. `openFile()` -- select an existing file on the filesystem
1. `openFolder()` -- select an existing folder on the filesystem
1. `saveFile()` -- select a file to be used for an upcoming save operation
The names are sort of misnomers, since calling those functions does not actually open or save a file; rather, they just return the path to a file. Any thoughts on how the names here could be improved? Maybe just `show*Dialog()` or similar?
=> provide API for interacting with file dialogs

src/cpp/session/modules/SessionConnections.R
unixODBC has a bug that SQLDrivers does not properly return driver
information if it is specified in the user configuration file
`~/.odbcinst` rather than the system wide configuration file. This
behavior was reported upstream and should be fixed in the next unixODBC
release (2.3.5).
As a result of this bug drivers specified in `~/.odbcinst` will have
`NA` values when returned by `odbc::odbcListDrivers()`, causing a number
of Warnings and empty entries added to the connection Dialog. See
<https://www.dropbox.com/s/wx64d9e6frtvbk3/snippetsFile.gif?dl=0> for an
example of the current behavior.
To fix this we can simply filter out NA entries from the dialog,
avoiding the issue.
cc/ @javierluraschi, this fixes the behavior I mentioned to you on slack.
=> Filter NA attributes from driver enumeration in the odbc connection pane

src/cpp/session/SessionModuleContext.cpp
Revert part of the change in 04106703a0f9500d132a9d461273a649296478bf, but only for desktop mode. Concern is there may be unanticipated side effects, so we'll take a look at "unreverting" this in 1.2 when we have more time to evaluate.
=> Revert session storage behavior for desktop mode

src/cpp/session/SessionUserSettings.cpp, src/cpp/session/include/session/SessionUserSettings.hpp, src/cpp/session/modules/SessionWorkbench.cpp, src/gwt/src/org/rstudio/studio/client/workbench/Workbench.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/SourceControlPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/SourceControlPreferencesPane.java
Removed the Windows-only "Use Git-bash as shell for Git project" preferences checkbox. Now the shell will launch the default terminal as set on the Terminal Pane.
Doesn't change if a Git project is currently open or not, which was called out as a source of confusion.
=> Make Tools/Shell use default terminal on Windows

src/cpp/session/modules/SessionCodeSearch.cpp
This PR ensures we don't index sub-directories within the `revdep` folder of a package project (FR from @hadley).
=> don't index revdep subdirectories

src/cpp/core/terminal/PrivateCommand.cpp, src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/modules/SessionWorkbench.cpp, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/model/WorkbenchServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
JJ noticed that the "hidden" command for environment capture shows up in shell history. Very irritating in that they run after each user-entered command.
Fixed that by setting HISTCONTROL=ignoreboth to not add commands starting with a space to shell history (and to not add duplicate commands to history); then added a space to start of the "hidden" command.
Added a user preference to terminal options to enable/disable the environment capture feature altogether. This feature is sensitive to the shell being used, so with the custom shell capability, you can get into scenarios where you'd want to disable it (csh, for example, is unhappy with environment capture feature; does anybody still use csh as an interactive terminal?).
=> Tweaks to terminal environment capture

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java
During some unrelated debugging, got into a state where terminal websocket was disconnected and the null socket was being referenced, leading to an exception. Add a check, and log a message to the terminal diagnostics and the console.
Not sure how or if this can happen in normal usage, but best to avoid the exception and log the fact this happened.
=> Avoid Javascript exception due to null websocket

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/view/ObjectExplorerDataGrid.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/view/ObjectExplorerEditingTargetStatusBar.css, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/view/ObjectExplorerEditingTargetStatusBar.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/view/ObjectExplorerEditingTargetWidget.java
This PR implements a simple status bar for the object explorer, showing the R code that can be used to extract the currently selected node. `user-select` is explicitly set so that users can copy + paste the text as desired (in case the button for running the active code is not discoverable).
=> implement a simple status bar for explorer

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
This PR scopes the behaviors that allow yanks to interact with the system clipboard to Emacs-mode only. (Some users with default Ace keybindings found it confusing that these commands could interact with the system clipboard)
=> scope yank + clipboard interactions to emacs

src/cpp/session/modules/SessionConnections.R, src/cpp/session/modules/connections/ConnectionsIndexer.cpp, src/cpp/session/modules/connections/ConnectionsIndexer.hpp, src/cpp/session/modules/connections/SessionConnections.cpp, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/model/ConnectionsServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionInstallPackagePage.java
- `ODBC` and `sparklyr` are both now on CRAN; therefore, we can enable the Connections pane.
- "Create Connection" followed by ODBC or sparklyr triggers the installation page; however, package indexing does not trigger fast enough and the dialog was not opening with the new connections, fixed.
=> Enable connections pane and trigger immediate indexing in dialog

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermNative.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
Fix: when a full-screen program is running in a terminal, and you refresh the browser, that terminal started showing the full-screen program in the regular buffer. If you then exited the full-screen program, you didn't see what you expected. Fixed by detecting this and sending the sequence to switch back to alt-buffer after reloading the regular buffer.
Fix: when session suspended, trying to show the terminal diagnostics dialog was a no-op due to an exception. Fixed by making `TerminalSession` object more consistent in how it extracts and stores metadata for the suspended/disconnected case
Tweak: in Terminal Diagnostics dialog, show both the last-known server state for alt-buffer flag, as well as the current client-side alt-buffer flag
Tweak: rename `XTermWidget.altBufferActive` method to …
=> Assorted terminal fixes and cleanup

src/cpp/session/SessionConsoleProcessApi.cpp, src/gwt/src/org/rstudio/core/client/AnsiCode.java, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcess.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/model/ConsoleServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTab.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java
Terminal dropdown menu now has command "Copy Terminal to New Editor Tab" which sends entire content of current terminal's buffer to a new editor buffer.
This is mainly a workaround for xterm.js lack of scrolling mouse select (i.e. selecting more than will fit on visible display) and lack of Select All / Copy.
Ansi codes are stripped out of the resulting editor buffer. At the moment backspaces are not, so you'll see some red dots in the editor. I'll look at cleaning this up separately.
Also added button to Terminal Diagnostics dialog to append the buffer to the diagnostics text, with Ansi codes preserved (and some pretty-print done, such as <ESC> for raw esc characters).
=> New command sends entire terminal buffer to new editor buffer

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTab.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java
When terminal tab is closed and you restart the UI, `TerminalTabPresenter` and `TerminalPane` should not be constructed. Discovered that they were, even though they are not visible. This adds unnecessary overhead and defeats the purpose of the` DelayLoadWorkbenchTab`.
One problem is that the TerminalTab constructor was calling a do-nothing `initialize` method on the shim, triggering creation of the Presenter and Pane. Easy to fix, get rid of it.
Other problem is that the TerminalTabPresenter was handling SessionInit, which is always broadcast during startup, again leading to creation of the Presenter and Pane. Fix is to move handling up to the `TerminalTab` and have it only call the shim if there are terminals sent by the server.
=> Fix delayload of terminal presenter and pane

src/cpp/desktop-mac/GwtCallbacks.mm, src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
This PR adds `getClipboardText()`, `setClipboardText()` APIs for interacting with the system clipboard.
This is added primarily to better handle the 'yank before' and 'yank after' commands -- currently, because yanks are implemented in this way:
1. Select a range,
2. Invoke the system cut command
there is the potential for a perceptible delay between steps 1. and 2. above, causing a brief selection 'flash' during the yank attempt. This PR removes that selection flash by sending the yanked text to the server, and only deleting text on the client side (rather than selecting and then later deleting)
=> APIs for getting, setting clipboard contents

src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java, src/gwt/src/org/rstudio/studio/client/workbench/WorkbenchContext.java, src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalHelper.java
There was no warning before killing busy terminals via "Restart R", "Build and Reload", or "Clean and  Rebuild".
Received enough feedback to suggest users are quite surprised that these operations kill the terminal processes, and I'm worried they could lose work in the form of long-running jobs, so added warnings.
=> Warn before killing active terminals

src/cpp/session/SessionClientEvent.cpp, src/cpp/session/SessionConsoleProcessApi.cpp, src/cpp/session/SessionConsoleProcessInfo.cpp, src/cpp/session/SessionConsoleProcessTable.cpp, src/cpp/session/SessionConsoleProcessTable.hpp, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/SessionUserSettings.cpp, src/cpp/session/include/session/SessionConsoleProcessInfo.hpp, src/cpp/session/include/session/SessionUserSettings.hpp, src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp, src/cpp/session/modules/SessionWorkbench.cpp, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcessInfo.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTab.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/AddTerminalEvent.java
Make the R API `rs_terminalCreate` independent of the client when starting up a terminal. Prior to this there was a gap between this API returning and the terminal being available for the other APIs to call.
Now you can, for example, immediately send a command to a created terminal (this would have failed before these changes):
`terminalSend(terminalCreate(), "ls -l\n")`
Also fix a potential scenario where multiple terminals could be created with the same "unique" identifier due to duplicate logic on client and server; now server-only.
**Details:**
1. Moved `getTerminalShells` and `startTerminal` RPC API implementations from SessionWorkbench.cpp to SessionConsoleProcessApi.cpp.
2. Pulled out the non-RPC-specific logic of `startTerminal` into `createTerminalConsoleProc` function which is …
=> Fix terminalCreate R API to return a ready-to-use terminal

src/cpp/session/modules/SessionRMarkdown.R
This PR should resolve an issue reported at https://github.com/rstudio/packrat/issues/382, where attempts to publish R Markdown documents containing multibyte characters within the YAML header to RStudio Connect would fail. Note that this issue primarily affects Windows users.
The issue here: users were saving documents with UTF-8 encoding; however, when reading that document back in, we were not re-marking the encoding as UTF-8 and so ended up with a UTF-8 document that we believed to be in the system encoding. Unfortunately, this causes the `yaml` package to barf when parsing the document.
=> mark encoding before parsing YAML

src/cpp/session/resources/profiler/profiler.css
Profiler colors are broken under dark-themes for desktop builds...
fixed...
=> Fix profiler colors under desktop and dark-themes

src/cpp/r/R/Api.R
This PR completes work from https://github.com/rstudio/rstudioapi/pull/47 by moving logic to RStudio to support a new `rstudioapi::getThemeInfo()` call that will provide users with information on the theme.
=> Add .rs.api.getThemeInfo for rstudioapi pr

src/cpp/session/resources/grid/gridstyles.css, src/gwt/src/org/rstudio/core/client/theme/ThemeColors.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/consoleStyles.css, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.css
A few dark-theme fixes for search results...
=> Fix search results background under dar theme

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/InfoBar.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/CallFramePanel.css, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/CallFramePanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/CallFramePanelStyle.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectList.css, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjects.css
A few tweaks to the debugger traceback pane to improve its visuals...
=> Improve debugger traceback pane visuals

src/cpp/core/system/PosixChildProcess.cpp, src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/SessionConsoleProcessApi.cpp, src/cpp/session/SessionConsoleProcessTable.cpp, src/cpp/session/SessionConsoleProcessTable.hpp, src/cpp/session/include/session/SessionTerminalShell.hpp, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcessInfo.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/model/ConsoleServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
Some minor refactoring made during other work. Doing it separately to make it clearer.
The `zombie` flag (a terminal exited but buffer stays visible) is set when a process exits on server, based on the ConsoleProc's settings and the user preference. Mainly intended for use by `terminalExecute` R API (the "other work") but can be enabled for all terminals via user preference.
Was catching this in client onExit handler, then sending the server an RPC to set the state, but this is unnecessary as the server already has the info to set this directly when a process exits. Eliminate the RPC and set it directly.
Also some other minor cleanup.
=> Set terminal zombie flag directly on server, not via RPC

src/cpp/session/modules/SessionCodeTools.R
This PR fixes an issue where attempts to request completions within certain primitive functions (primarily those powering control flow) would emit a warning of the form
Warning in formals(fun) : argument is not a function
One can reproduce by typing e.g. `return(<TAB>)`.
=> fix warning when requesting completions in e.g. 'return()'

src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/SessionConsoleProcessApi.cpp, src/cpp/session/SessionConsoleProcessInfo.cpp, src/cpp/session/SessionConsoleProcessTable.cpp, src/cpp/session/SessionConsoleProcessTable.hpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/gwt/src/org/rstudio/studio/client/common/console/ConsoleProcessInfo.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/model/WorkbenchServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalInfoDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
Been wanting to do this for a while and it's getting late, but think it's worth it for maintainability.
The ConsoleProcessInfo (CPI) object contains metadata about terminals. For whatever reason, early on I started passing and storing subsets of this around in various locations in the client-code. Then it was passed to the server as a bunch of arguments to terminalStart RPC call. This resulted int a bunch of places where I needed to ensure I was building/un-building CPI objects consistently, and keeping things in sync, and lots of little consistency errors crept in which I'm still finding.
I had cleaned some of this up a while ago, but the part I didn't get to is the `TerminalSession` which is constructed with a CPI, yet immediately tears it apart and stores the fields in separate …
=> Cleanup argument passing for terminal metadata

src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java, src/gwt/src/org/rstudio/studio/client/workbench/ui/PaneManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/output/renderrmd/RenderRmdOutputPresenter.java
This PR re-zooms the Source window after a successful document knit.
The mechanism by which I provide access to the `PaneManager` feels 'wrong', but I don't see a simpler way forward without effectively duplicating a whole bunch of code in a separate class. (Let me know if I'm missing something obvious!)
=> re-focus source window if zoomed after render

src/cpp/core/include/core/r_util/RProjectFile.hpp, src/cpp/core/r_util/RProjectFile.cpp, src/cpp/session/modules/SessionSource.cpp, src/gwt/src/org/rstudio/studio/client/common/viewfile/ViewFilePanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/ProjectConfig.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/SourceDocument.java
This PR ensures that files inherit indentation settings from their 'owning' project (when available), rather than the 'active' project. This should help in cases where one attempts to edit files from multiple projects within the same IDE session.
We also inherit save settings associated with a project (this should help ensure we don't e.g. trim trailing whitespace unintentionally and create noisy diffs)
=> inherit indentation settings from parent project

dependencies/linux/install-dependencies-debian
When errexit is set, a bash script will halt as soon as any command has
a non-zero exit status. So the checks here were just halting the script.
=> Avoid terminating installation script

src/cpp/session/modules/SessionTerminalShell.cpp
When specifying a custom terminal shell, the arguments are supplied as a single string in the UI but need to be split into separate arguments when passed to exec. Added simple space-separated split. With this fix in place, can do fun stuff like specify a custom script to run when starting a terminal to (for example) auto-launch/attach to tmux.
=> allow multiple arguments to custom shell

src/cpp/session/modules/SessionPackrat.cpp
Minor bug fix -- it looks like we accidentally used `hasPendingRestoreActions` twice in the check here. (bumped into this while playing with some static analysis tools, although I suppose this codepath is effectively unused now)
=> fix check for pending actions

src/cpp/session/SessionConsoleProcessApi.cpp
When you send the terminal buffer to editor, it was showing backspaces and the characters they had erased, as well as `<BEL>` characters. These control characters show as red dots in the editor.
Fix by removing `<BEL>` characters and processing the backspaces.
=> cleanup terminal buffer sent to editor

src/cpp/session/modules/SessionRCompletions.R, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/RCompletionManager.java
This PR fixes a couple small bugs in Roxygen completion:
---
Roxygen completion now works when the cursor is flush against the roxygen comment marker, e.g.:
#'|
Pressing <TAB> with the cursor at the `|` position now successfully autocompletes.
---
We no longer noisily attempt completions when there is no token at the cursor position, except when the cursor lies immediately after the Roxygen comment (+ whitespace). This should resolve issues where the autocompletion dialog would somewhat annoyingly re-show itself while typing on a comment line.
=> tweaks for roxygen completion

src/cpp/session/SessionConsoleProcess.cpp
When a terminal is created, it is identified internally by a handle (8-char uuid). There is also a sequence number used to generate unique default captions e.g. "4" for Terminal 4. The handle is unique, the sequence number could be reused if you've closed some terminals and created new ones within the same session.
Set the RSTUDIO_TERM environment variable to the handle, instead of the integer sequence number. This could be used, for example, to give a tmux session a terminal-session-specific name when launching/creating via a custom terminal startup script.
=> Set $RSTUDIO_TERM to handle, not sequence number

package/linux/debian-control/postinst.in, package/linux/debian-control/postrm.in, package/linux/rpm-script/postinst.sh.in, package/linux/rpm-script/postrm.sh.in
this includes better detection of which init system is in use (from Connect team), and therefore upstart is being properly NOT detected on docker platforms (and thus the regular service command is used, which is available on docker)
=> fixed initctl errors on docker builds when installing rstudio server

package/linux/rpm-script/postinst-desktop.sh.in, package/linux/rpm-script/postrm-desktop.sh.in
similar to what we do for open suse.
Still waiting for an update on https://github.com/rstudio/shiny/issues/1796 to see if this fixes the problem that's being seen in the wild.
=> added softlinks for openssl libraries for Fedora 2

src/cpp/core/include/core/system/PosixSystem.hpp, src/cpp/core/include/core/system/Process.hpp, src/cpp/core/include/core/system/System.hpp, src/cpp/core/system/ChildProcess.hpp, src/cpp/core/system/ChildProcessSubprocPoll.cpp, src/cpp/core/system/ChildProcessSubprocPoll.hpp, src/cpp/core/system/ChildProcessSubprocPollTests.cpp, src/cpp/core/system/PosixChildProcess.cpp, src/cpp/core/system/PosixSystem.cpp, src/cpp/core/system/PosixSystemTests.cpp, src/cpp/core/system/Process.cpp, src/cpp/core/system/Win32ChildProcess.cpp, src/cpp/core/system/Win32System.cpp, src/cpp/core/system/Win32SystemTests.cpp, src/cpp/session/SessionConsoleProcess.cpp, src/cpp/session/SessionConsoleProcessInfoTests.cpp, src/cpp/session/SessionConsoleProcessPersistTests.cpp, src/cpp/session/SessionUserSettings.cpp, src/cpp/session/include/session/SessionConsoleProcess.hpp, src/cpp/session/include/session/SessionUserSettings.hpp, src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/TerminalPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalHelper.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermNative.java
When you do something that kills the rsession (such as Restart R, or Build and Reload), any running terminal processes will be killed, so there are warnings about this. This change adds a user preference to control this behavior (Mac and Linux only, though I modified the underlying Win32 system code signatures to match the Mac/Linux code): Three choices:
**Always** (default) - current behavior; if shell has any subprocesses, you will be warned when doing something that will kill those processes.
**Never** - no warnings when killing terminal processes
**Always except for whitelist** - same as always' except it will not warn if the child processes match the user-editable whitelist (which contains `tmux` and `screen` by default)
**Separate bug-fix included in this PR**: XtermNative.java …
=> Option to control warnings when killing terminal processes

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
On Windows IDE, a new terminal was coming up blank, just a blinking cursor. The buffer was being populated (confirmed by looking in the server log), typing was working (could enter 'exit' and terminal stopped), but nothing ever displayed.
This bug also caused a case Javier saw where starting a terminal in RStudio Server provisioned in Amazon EMR displayed the initial output twice.
It was a regression where a terminal was not being set to "new terminal" mode. This used to be identified by handle being null, but some changes I made also required checking for empty string.
On Windows, it thought the new terminal was a restarted terminal and was waiting to reload the buffer (which doesn't happen on Win32), so it kept accumulating all the terminal output in a string which is sent when terminal …
=> Bug where Windows terminal is blank or double-output shows (non-Windows)

src/cpp/desktop/DesktopMainWindow.cpp
When I use a Linux theme with light text color and dark background, the menu text is invisible.
This fixes it.
An alternative fix would be to just leave the background color for the QMainWindow alone. (Remove the line I changed here)
=> Fix contrast for light-on-dark color themes

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AceEditorPreview.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
This small change adds support for ligature "coding fonts" such as [Fira Code](https://github.com/tonsky/FiraCode) in RStudio for Windows and Linux (they already work out of the box on MacOS). Checking the new *Use ligatures* box next to *Editor font* turns on ligatures if the font has them (notice e.g. the assignment arrow, ellipsis, and && operator):
Inspired by motivated users who had taken to hacking in the relevant CSS class by [editing RStudio resources directly](https://stackoverflow.com/questions/34548194/rstudio-how-to-enable-font-ligatures-in-rstudio/34714296#34714296). :-)
Off by default to match existing behavior, and since the relevant CSS property may carry a [performance penalty](https://developer.mozilla.org/en-US/docs/Web/CSS/text-rendering).
=> Add support for ligatures in Qt-based desktop clients

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
=> Checkboxes in windows are not properly adjusted under flat themes

src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionSnippetHost.java
New connections dialog renders the "test" button in the middle of the row when no fields are available, before:
After:
=> Adjust new connections dialog for empty fields

src/gwt/src/org/rstudio/core/client/widget/ProgressPanel.java, src/gwt/src/org/rstudio/core/client/widget/ProgressSpinner.java
This https://github.com/rstudio/rstudio/pull/1178 switched progress panes to be rendered using the canvas to support better theming; however, while hidden, computations were still running causing CPU to be higher than usual while idle.
=> Prevent computations while spinner is not visible

src/cpp/core/json/JsonRpc.cpp
This PR tags the JSON return value passed back to the client with the error location, when available. This should help when attempting to debug errors that aren't logged session-side but do show up in the client-side logs.
=> record error location for failed RPCs

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css
Regression from https://github.com/rstudio/rstudio/pull/1371, before...
After...
=> Fix menu search boxes as regression from recent 1px up search box change

src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
=> Fix help headers under dark theme

src/cpp/session/SessionConsoleProcessPersist.cpp
On multi-session server, the terminal metadata should be strictly per-session. Previously it was per project meaning it was stomping over itself if opening multiple sessions on one project.
Now it uses the session scratch path for multi-session, meaning each new session will start clean (no existing terminals). So, unlike single-session server, if you close a project and reopen, you will not get back the previous set of terminals.
=> Fix terminal metadata storage on multi-session

src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTargetWidget.java
Before...
After...
@jmcphers can you think of other common uses of `UrlContentEditingTargetWidget`appart from `vignettes()`?
=> Support for dark themed iframes in url content tabs

src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java
If focus is in terminal, pressing shortcut for `Run Selected Lines` command (Cmd+Enter on Mac) does a regular enter within the terminal.
This change causes the command to run, instead, which will bring the console to the front and execute selected lines from the editor, if any, making it consistent with focus being on other locations in the IDE.
=> Allow Run Selected Lines shortcut to work when terminal has focus

src/cpp/session/modules/SessionConnections.R
When a custom `script.R` connection is added, other connections using shiny connections get the incorrect packages, for instance, `sparklyr` connections stop rendering.
The issue is with the compares while filtering...
```
Filter(
function(e) e$package == "sparklyr" & e$name == "Spark",
list(
list(package = NULL, name = "Test"),
list(package = "sparklyr", name = "Livy"),
list(package = "sparklyr", name = "Spark")))
```
returns "Livy" while "Spark" would be expected.
This is caused by a package beding NULL, which mekes `package = NULL` becomes `logical(0)`, since Filter is implemented as:
```
ind <- as.logical(unlist(lapply(x, f)))
x[which(ind)]
```
The `logical(0)` is omitted from `unlist` and the incorrect filter is returned.
=> Avoid incorrect connections in new connections list

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalLocalEcho.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
On Windows, the RPC messages for terminal keyboard input would often arrive out of sequence, so I had implemented a sequence number used to reassemble the order on the server and made it Windows desktop only.
I've found that although much less common, it can also happen on Mac desktop IDE. Haven't check on Linux IDE, but I'm turning on that handling for all desktop builds.
=> Enforce input sequence on desktop terminals using RPC

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermNative.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
I've rewritten this method a couple of times; not currently used but provides dump of of local xterm.js buffer when debugging. Production code uses the server-side buffer cache (for things like send terminal to editor, getting buffer via API, and dumping buffer in the diagnostics dialog). Comparing the two is helpful on occasion.
=> Helpful diagnostic method to see xterm buffer

src/cpp/session/SessionConsoleProcess.cpp
In 1.0 we set GIT_EDITOR and SVN_EDITOR to rpostback-editfile on Server, so the shell dialog could be used for source-control operations.
Now that terminal supports full-screen programs like vim, we won't set these environment variables.
=> Don't set GIT_EDITOR or SVN_EDITOR in terminal environment

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.java, src/gwt/src/org/rstudio/studio/client/application/ui/RStudioThemes.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanel.css, src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
Two issues, 
1) On windows:
The problem here is that `useScrollbars()` was setting the scrollbars CSS when it was only intended for dark themes. However, since...
2) While changing between dark and light themes scrollbars don't change and require an rstudio restart.
The fix for (1) and (2) is to rather make scrollbars dynamic based on `rstudio-dark-theme` CSS property.
This works for the most part, except for a Safari bug (https://stackoverflow.com/questions/3485365/how-can-i-force-webkit-to-redraw-repaint-to-propagate-style-changes) which prevents scrollbars from changing colors based on CSS changes. The workaround is to set a parent div to `display: none` and then `display: auto`. However, I'm hesitant to implement this workaround since it could cause unintended consequences. Instead, …
=> Avoid dark scrollbars on non-osx systems under popups

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceShim.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceVimCommands.java
This PR adds a small extension to our Vim integration that allows `]f` to open the next file on the filesystem, and `[f` to open the previous file on the filesystem (relative to the currently active open file). (Inspired by [vim-unimpaired](https://github.com/tpope/vim-unimpaired))
Users who want to use these commands outside of Vim mode can do so by rebinding them to separate shortcut keys.
=> vim extension: open adjacent files on filesystem

src/gwt/src/org/rstudio/studio/client/common/filetypes/ObjectExplorerFileType.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/ObjectExplorerEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java
This PR fixes an issue where attempts to invoke the viewer with the same object intended for the object explorer, e.g.
View(as.list(mtcars))
View(as.list(mtcars))
would open two separate tabs rather than re-activating an existing tab.
=> properly handle re-opening object explorer tabs

src/cpp/desktop-mac/GwtCallbacks.mm
This PR fixes an issue where 'Export to Image' would fail on macOS when attempting to export Viewer content (e.g. HTML widgets).
It looks like newer versions of WebKit no longer return an `NSBitmapImageRep` as the first element of the possible image representations here -- rather, it returns an `NSCGImageSnapshotRep`, which AFAICS is not a publicly exported type. However, we can still get the bitmap image data through a separate set of APIs, which I believe should be backwards-compatible with older WebKit as well.
This may be a candidate for the patch release, since the current release of RStudio is affected by this as well.
=> fix 'Export to Image' for macOS desktop

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
Scenario: with a terminal open and using RPC (vs. Websockets) restart R. Then try to execute a command in the terminal and you can't until you've entered at least 20 characters.
I recently made some logic that was previously Windows-only apply on all platform desktop IDEs and Darby quickly found a bug. Problem was there all along on Windows.
Introduced by Change 3a955c7.
=> Fix inability to execute command until 20 characters have been typed

src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionsPane.java
I kept seeing this in the javascript console when working on other issues and found an old bug on it (case 6681) that had been closed, but I can repro 100% so reopened.
To repro, open RStudio (Mac development server). No existing connections.
In Javascript debugger, open ConnectionsPane.java, put breakpoint in onActiveConnectionsChanged() at the call to installConnectionExplorerToolbar.
Do Session->Restart R, repeat.
Breakpoint is hit, and installConnectionExplorerToolbar is called with a null connection, which leads to exceptions.
Added a check to prevent exception. Someone familiar with the connections feature should check that this is a reasonable fix.
=> Stop javascript exception after restarting session

src/cpp/core/system/PosixChildProcess.cpp
When closing a terminal with running processes (e.g. sleep, vim, so on), on Linux, the processes weren't going away (but the UI was, so little hint that there's a problem).
Fixed by making some existing code not be OSX-specific. This isn't code I wrote or modified for terminal, just used as I found it. This will impact killing all PosixChildProcesses, not just the Terminal scenario. If this is a concern, I could scope this to only the terminal scenario.
=> (linux) Terminal processes not being killed when closing terminals

src/cpp/session/resources/profiler/profiler.css
Profiler menu was rendering with white backgorund, fixed:
=> Fix profiler menu under dark theme

src/cpp/session/CMakeLists.txt
The profiler resources are not being copied in builds. I haven't spotted this since I've been using dev builds for the most part which serve resources directly from the build directory.
Before:
After:
=> Include profiler resources in build file

src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/PopupPositioner.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/r/RCompletionToolTip.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/r/SignatureToolTipManager.java
This PR fixes an issue where the tooltip signature was not properly truncated when shown through a mouse idle, and also improves the general positioning behavior (better avoiding right-overflow when the browser width is small).
=> fixups for tooltip positioning + sizing

src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java
Of various package build commands, only the build-all and rebuild-all commands restart the R session. Other build commands don't.
=> Don't give terminal busy warning when not needed

src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/ScriptFileType.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/CreateTerminalEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/SendToTerminalEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/SwitchToTerminalEvent.java
When editing a script file (.sh), the **Run** button/command is enabled and sends the current selection/line to the current terminal (e.g. via Cmd+Enter on Mac). Focus always goes to the terminal after issuing the command; making focus optional like it is for sending to Console was too invasive and fragile. The terminal _likes_ to get focus when activated and I don't want to mess with it now.
Also added a new `Send to Terminal` command on Code menu for all text file types EXCEPT shell scripts. This enables sending the current editor selection to the terminal from all other text file types. **I didn't assign a keyboard shortcut; any suggestions?**
The latter allows you (for example) to manually open a terminal and start Python, then send stuff from a .py file to it. Not a full-fledged repl …
=> Send-to-terminal support for .sh files and other text files

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Cmd+Alt+Enter on Mac, Ctrl+Alt+Enter on Windows and Linux.
=> keyboard shortcut for send-to-terminal command

src/gwt/src/org/rstudio/studio/client/application/ui/appended/ApplicationEndedPopupPanel.java
This PR resolves an issue where attempting to re-launch a session after a crash (by mashing on the 'Start New Session' button) could launch multiple new R sessions, and lead to a 'No locks available' error due to the multiple competing `rsession`s attempting to acquire a source database lock.
=> only allow single attempt to reload session

src/gwt/src/org/rstudio/core/client/widget/ProgressPanel.java, src/gwt/src/org/rstudio/core/client/widget/SimplePanelWithProgress.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ConnectionsPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionExplorer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionsPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ObjectBrowser.java
Prior to this change, the Connections Pane was blank while the list of objects was loaded. 
Consequently, if there are a lot of objects, or the server is slow, navigating to the connection goes to a blank page indefinitely, and you might be forgiven for thinking that there were no objects in your connection, or that something was broken.
This change adds a progress spinner while the pane is loading the object list, along with some descriptive text.
=> Connections Pane: Show status while fetching object list

src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionSnippetHost.java
There is on snippet file case that must have exactly the following fields which should work but doesn't:
```r
library(DBI)
con <- dbConnect(odbc::odbc(),
Driver="{hive}",
Host = "${1:Host}",
Port = "${1:Port=234234}", 
UID = "${2:User}",
PWD = rstudioapi::askForPassword("Password"),
SchemaM = "${3:Schema}")
```
The problem is that with exactly 4 fields and a header, we try to create an array for the advanced fields that is off by one and throws an exception.
The fix is to get the `min()` to ensure we are within of the acceptable range while creating this array.
=> Fix rendering of connections with exactly 4 params and header field

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/SendToTerminalEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
For .sh files executing in terminal, focus now stays in editor if the "Focus console after executing from source" option is false.
Also the cursor advances to next non-blank line (unless text was selected, same behavior as console).
One known issue, if sending text via Cmd+Enter requires the terminal to be created or re-attached, the terminal will take focus that one time. After that it is fine. I'll open a separate issue on that.
=> Fix focus and auto-advance for send-to-terminal from .sh

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
When single-stepping a .sh via Cmd+Enter, we advance cursor to next non-blank line. This is fine in .sh files, but when doing the same in (for example) Python via Cmd+Alt+Enter, skipping blank lines is a problem due to the blank-line rule in the Python command-line REPL, which needs those blank lines to terminate scopes.
So I've changed to only skip blanks in the .sh (Cmd+Enter) case, the Cmd+Alt+Enter command will not skip blank lines when advancing the cursor.
=> Don't skip blank lines when sending non-.sh to terminal

Jenkinsfile
needs to land after https://github.com/rstudio/jenkins-pipeline-libraries/pull/6
uses a new jenkins-pipeline-library that launches spot instances to our jenkins cluster to support the influx of ide builds. This should actually allow (potentially after a round of debugging) the jenkins agents to handle a full set of builds 24/7, rather than just the nightlies.
=> launch instances to handle ide build scale

src/cpp/session/modules/SessionConnections.R, src/cpp/session/modules/connections/SessionConnections.cpp
Need to map URLs using ports to get shiny-based connections to work in RStudio server, otherwise:
=> Enable shiny-connections to render in non-local servers by using proxy urls

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
https://support.rstudio.com/hc/en-us/community/posts/115007238727-Icons-in-R-Markdown-Notebook-result-window-are-almost-invisible-RStudio-preview-release-1-1-329-
Fixed...
=> Make chunk icons visible under dark classic themes

src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefs.java
Changing preferences in one windows partially changes themes in the other one leaving us in this situation:
=> Propagate uiprefs while changing theme

src/cpp/r/R/Options.R, src/cpp/session/SessionClientEvent.cpp, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp, src/cpp/session/modules/SessionHTMLPreview.cpp, src/gwt/src/org/rstudio/studio/client/htmlpreview/HTMLPreview.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/events/ShowPageViewerEvent.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/events/ShowPageViewerHandler.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/model/HTMLPreviewParams.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/model/HTMLPreviewResult.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewApplicationWindow.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewPanel.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java, src/gwt/src/org/rstudio/studio/client/workbench/Workbench.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
This PR introduces a full page HTML viewer to compliment the existing RStudio Viewer which displays HTML in an embedded pane. It can be accessed as follows:
```r
page_viewer <- getOption("page_viewer")
page_viewer("document.html")
```
The implementation re-uses the HTMLPreviewPanel which is currently used only for previewing R Markdown v1 documents as well as straight HTML files within the IDE. This makes the implementation straightforward and low-risk, however does result in the limitation that only HTML files can be viewed (the embedded RStudio Viewer can also view localhost URLs).
The main motivation for this feature is to enable packages to display full-page HTML reports. This is currently possible using browseURL however has a couple of problems:
1) It can potentially result in a …
=> full page html viewer

src/cpp/r/R/Options.R, src/cpp/session/modules/SessionHTMLPreview.cpp
Since self_contained requires rmarkdown we default this to FALSE. If TRUE is specified and rmarkdown is not available then an error is thrown.
=> add self_contained option to page_viewer

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/RemoveTerminalEvent.java
The modified code is only hit when using rstudioapi::terminalKill / .Options$terminal.manager$terminalKill.
The client wasn't fully cleaning up. It needed to switch to a different terminal iff the killed terminal was the current selection, and to remove the TerminalSession (the actual widget) from the TerminalPane iff it had been loaded.
=> Terminal API: Fixes to rstudioapi::terminalKill

NEWS.md, src/cpp/r/R/Options.R, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/modules/ModuleTools.R, src/cpp/session/modules/SessionHTMLPreview.cpp, src/gwt/src/org/rstudio/studio/client/htmlpreview/HTMLPreview.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/HTMLPreviewPresenter.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/model/HTMLPreviewParams.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/model/HTMLPreviewResult.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewApplicationWindow.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/Workbench.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Several additional enhancements:
1) Ability to specify a window title for the page viewer
2) Self-contained HTML is now created directly with pandoc rather than calling the rmarkdown package (this means that all static HTML files are savable and publishable).
3) Some refactoring to give the page viewer it's own server-side codepath (previously it was masquerading as an HTML preview which worked but was fragile and hard to reason about)
4) Support for localhost URLs. This combined with processx makes it possible for packages to create add-ons that extend the API with arbitrary web apps running in other processes (shiny or otherwise)
Not as straightforward a change as the first one, however I still think it's quite safe given that it only touches the codepath dedicated to R Markdown v1 and …
=> additional enhancements to page viewer

Jenkinsfile
* temporary measure until we limit opsworks registration issue
* just below two hours to ensure we aren't needlessly consuming 3h of cost.
=> set spot duration to  ~2h

src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
When running a full-screen program pass Ctrl+L keystroke to it instead of interpreting that as "clear terminal buffer" command. Among other things, this lets Ctrl+L clear the current tmux pane, instead of messing up the entire display.
=> Pass Ctrl+L through to full-screen terminal programs

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
@kevinushey discovered the previous shortcut clashed with Test Package (on client IDEs) so changing to Ctrl+Alt+2, which makes it nicely symmetric with the Ctrl+2 for sending focus to the Console.
=> Change shortcut for moving focus to terminal

src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/HelpInfoPopupPanel.css
=> Fix span tag under help popup in dark themes

src/cpp/core/terminal/PrivateCommand.cpp
Intermittent reports of extra prompts showing up in terminals, often after a few seconds delay. This goes away when environment capture is turned off. 
Logging a message in the failure case I suspect is causing this.
When terminal is doing environment capture, it fires a hidden command (/usr/bin/env followed by a sentinel, essentially) then parses the result and saves it, but there is a timeout which will issue a ptyInterrupt if the private command hasn't completed. This is likely what triggers another prompt.
Could be a race condition (multithreading and a mutex is in the picture with WebSockets), or some other timing-related window. At least knowing if it's hitting this error would be useful data.
=> Add logging to environment capture failure case

src/cpp/session/modules/SessionConnections.R, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/model/NewConnectionContext.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionNavigationPage.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionShinyPage.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionSnippetPage.java
Help users understand where the connections come from by adding meaningful on-hover behavior:
=> Show connection source on hover

src/cpp/session/SessionModuleContext.cpp, src/cpp/session/include/session/SessionModuleContext.hpp, src/cpp/session/modules/SessionHTMLPreview.cpp
This PR makes a couple of changes to the page_viewer:
1) It uses the R help server rather than the custom html viewer http handler to serve the page_viewer. As you'll see this ends up eliminating a new "state" that was introduced with the original PR (i.e. net reduction in risk/complexity).
2) If a file is provided to it that is already contained within the session temp dir it is served in place (previously it make another temp dir and created self contained html within it). This enables clients to provision their own temp directory and write files to it while the page_viewer is running (i.e. realtime updates based on polling).
=> use help server for page viewer

src/cpp/core/r_util/REnvironmentPosix.cpp
I don't think the `prelaunchScript` needs to be used for anything on Mac desktop or open-source dev server but @kfeinauer should confirm.
=> Fix 1.2 Mac build break

src/cpp/session/modules/SessionCodeTools.R, src/cpp/session/modules/SessionEnvironment.R, src/cpp/session/modules/SessionObjectExplorer.R
This PR fixes an issue where classed external pointers were not properly detected as external pointers by RStudio in some code paths. The main issue here is that:
inherits(object, "externalptr")
returns `FALSE` for classed external pointers. The safest way to detect these is check `typeof()` directly.
=> handle classed external pointers

src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java
Most web content sets their `<body>` to the desired bg-color; however, `RMD` files did not and therefore, we attempted to change the colors to match the dark theme. This is hard to support for blog content (say the RStudio blog) and even a bit confusing while knitting files since one would expect to see the final output. This is the case also with the plot pane which will render white by default unless the content creator is aware of themes and implements support for this.
The pane will now render as:
=> Disable dark theme in viewer pane while rendering content

src/cpp/core/include/core/http/AsyncServer.hpp, src/cpp/core/include/core/http/AsyncServerImpl.hpp, src/cpp/core/include/core/http/AsyncUriHandler.hpp, src/cpp/server/ServerMain.cpp, src/cpp/server/include/server/ServerUriHandlers.hpp
proxy handlers will be unrestricted (since they should proxy all traffic)
=> now restricting http methods in server implementation to PUT, POST, and GET unless the handler is a proxy handler

src/cpp/core/file_lock/LinkBasedFileLock.cpp
(note: if this PR feels misguided I think we can just close)
This PR implements a 'second attempt' mechanism for link-based file locking. If the `::link()` system call fails for some reason, we then instead try to write the lockfile using `::open()`, `::write()` and `::close()` system calls.
By calling `::open(O_CREAT | O_EXCL)`, we ensure that the call only succeeds if the process that attempts to create the file truly was the one that created the file and acquired the file descriptor. (Not all NFS support these semantics, but for the ones that do but don't support hard links, this would be a way out)
=> backup attempt for file locking

src/cpp/core/include/core/terminal/PrivateCommand.hpp, src/cpp/core/terminal/PrivateCommand.cpp, src/cpp/core/terminal/PrivateCommandTests.cpp
Typical repro is to hold down enter key a few seconds, then hit Ctrl+L, then a couple more enters. Wait a few seconds, then you'd get another prompt. Sometimes this would continue every few seconds, sometimes just once.
Easier to repro on Mac with newer bash (e.g. brew install bash) than the standard Mac one but I did repro with the stock bash as well.
Problem is that private command capture stops suppressing output when it gets its expected EOM marker, and if the new prompt triggered by the hidden command didn't arrive in same chunk of output as the EOM, then it's going to be displayed. Something about the way newer bash does its I/O seems to make this very common. If timing is just right, then that new prompt could trigger another round of environment capture, and so on.
Fixed by adding …
=> Fix extra prompts caused by environment capture

src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionInstallPackagePage.java
Multiple reconnects trigger from wizard and connections pane after using the wizard dialog. The problem is that one of the wizard pages contains a reference to the `ConnectionsPresenter` which `GWT` injects each time that the connection enters and an event to trigger the connection is performed for each time the class is injected.
Fix is to use an even to reopen the connections wizard rather than a references to the `ConnectionsPresenter`
=> Avoid duplicate reconnects in connections feature

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
The shortcut `Ctrl+Alt+2` for `View/Move focus to terminal` prevented users from entering the "@" character on Italian keyboards.
Changed `Move focus to terminal` to use `Alt+Shift+T`, formerly the shortcut for `New Terminal`. 
Guessing `Move focus to terminal` is the most commonly desired operation given it shows the terminal pane, creates a terminal if there isn't one, and gives it focus.
`New Terminal` now uses `Alt+Shift+R`, which was the shortcut for `Rename Terminal`, which now doesn't have a shortcut. Assuming `Alt+Shift+T` is the most memorable terminal shortcut, better it doesn't cause users to create a bunch of terminals when they just want to keep using the same one.
At least this gives some symmetry to shortcuts for New Terminal / Move Focus to terminal, and Rename Terminal …
=> Tweak terminal shortcuts

Jenkinsfile
this should allow multibranch pipelining (currently restricted to just the `v1.2` branch) to produce different build numbers
=> set build_number as patch version

src/cpp/desktop-mac/GwtCallbacks.mm, src/cpp/session/modules/SessionHTMLPreview.cpp, src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPresenter.java
NOTE: not yet ready for merge -- Requires some additional testing on (3) as described below.
1) Go back to always creating a new temp file for html files (previously we used an existing html file in place so long as it was in the session temp dir). We do ths so that htmlwidgets that elect into the page_viewer can always be published (they write their html as non self-contained so rely on the viewer to make it self-contained.
2) Return the path to the viewer html file in the session temp directory from the page_viewer function. This accomplshes the same objective as the "in place" behavior we removed in this commit: allowing the calling R code to know the path to the html file displayed in the viewer (so that it can write e.g. JSON files along side it that are polled by the main html …
=> additional improvements to page viewer

src/gwt/src/org/rstudio/core/client/StringUtil.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java
Send to terminal with multiple lines selected should act like typing each line and hitting Enter in the terminal. On Windows Desktop IDE, this wasn't working as expected in Command Prompt and PowerShell. Fixed by changing line endings to CR when sending to those shells on Windows. Verified that behavior of Git Bash and WSL are not changed.
With this selected in editor:
```
echo hello 001
echo hello 002
echo hello 003
echo hello 004
echo hello 005
echo hello 006
echo hello 007
echo hello 008
echo hello 009
```
**Before and after with Command Prompt**
**Before and after with PowerShell**
=> multi-line send-to-terminal not behaving correctly on Windows

src/cpp/session/modules/build/SessionBuild.cpp, src/cpp/session/modules/clang/RCompilationDatabase.cpp
This PR ensures that we use the actual path to the R binary when invoking `R CMD SHLIB`. This should fix issues detecting build tools when R is not on the PATH.
=> use shell command when checking for build tools

src/cpp/core/include/core/r_util/RProjectFile.hpp, src/cpp/core/r_util/RProjectFile.cpp, src/cpp/r/include/r/session/RSession.hpp, src/cpp/r/session/RSession.cpp, src/cpp/session/SessionMain.cpp, src/cpp/session/modules/SessionPackrat.cpp, src/cpp/session/projects/SessionProjects.cpp, src/gwt/src/org/rstudio/studio/client/projects/model/RProjectConfig.java, src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectGeneralPreferencesPane.java
This adds a new project option to toggle whether or not .Rprofile should be run when a new session is started in a project. It also interacts with the existing option to run the Rprofile on resume - if that is set, it will use the behavior specified in this new project option.
=> Added option to toggle whether .Rprofile is run when starting a session in a project

src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
Coverage of some additional behaviors I was looking when investigate destructive vs. non-destructive backspace in Console.
Conclusion: destructive is more standard (despite being different than RStudio 1.0), and we'll stick with it.
=> add additional unit test cases for Virtual Console

src/cpp/session/SessionClientInit.cpp, src/cpp/session/SessionOptions.cpp, src/cpp/session/include/session/SessionOptions.hpp, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/application/ui/GlobalToolbar.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java
New overlay option, `allow-full-ui`, when set to 0, hides Project menu items and user-identity menu items. Will eventually also hide the logo, but there are existing bugs in logo display I'd like resolved before I mess with it.
File menu with default behavior:
File menu with allow-full-ui=0:
Right-hand toolbar with default behavior:
Right-hand toolbar with allow-full-ui=0:
=> Reduced ui-mode setting (cloud work)

src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java
This PR fixes an `rstudioapi` issue where attempting to call e.g.
```R
rstudioapi::insertText("text", id = "<id>")
```
where `<id>` is the id of a document belonging to a different source window would fail.
@jmcphers, there's likely a better way to ensure that an event is broadcasted to all windows (both main window + source window) -- let me know if you think there's a cleaner way to accomplish this.
=> broadcast rstudioapi events to all windows

src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/header/MenubarPanel.css
The feature was NYI for flat themes, before:
after:
=> Add support for themes under hidden header

src/gwt/src/org/rstudio/core/client/theme/res/ThemeStyles.java, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/studio/client/application/ui/impl/WebApplicationHeader.java
With reduced UI mode (allow-full-ui=0), hide the R logo in menu/toobar area, with or without toolbar showing.
**Regular mode (unchanged by this PR):**
**No logo**
=> Hide R logo in reduced UI mode

src/gwt/src/org/rstudio/studio/client/application/Application.java
Another removal requested by cloud team; gets rid of `Quit Session` on File and Session menus.
=> Remove Quit Session from hosted UI mode

src/cpp/session/SessionConsoleProcessApi.cpp
Issue that Darby was hitting. He'd create a terminal with `rstudioapi::terminalCreate("My Terminal")`, and it would come up, but always show as (busy) even though at command prompt. Terminal worked otherwise.
I couldn't repro, but very consistent for Darby.
This fix is very tightly scoped, only touching the codepath used by `rstudioapi::terminalCreate`. Darby tried it on his system and it stopped the problem from happening.
**More details**
The terminalCreate API spins up the terminal process on the server, then queues client message to tell the UI to load up the elements to connect that terminal session with the IDE; that involves a chain of calls on the client that go back to the server and wait for the response to fire the next call.
The ConsoleProcessInfo constructor on the server …
=> fix terminal created via rstudioapi stuck at busy

src/cpp/session/resources/roxygen_help.html
Also document `\preformatted{}` alongside `\code{}` in the Roxygen quick help.
=> document \preformatted{} Rd markup

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
I had done this work a few weeks ago then stashed it. Bringing back to get feedback:
When sending text to terminal, and there is no "running" terminal (either due to previous session suspend, or no terminals currently open at all), the text isn't sent after creating/activating a terminal. After that the send-to's will work (but if doing line-by-line, the cursor has already advanced).
Also, focus is given to the terminal when it is created; this change does not address that (I tried, but xterm.js has an issue where it takes focus when created, even if you set its flag telling it not to, and I'm not cracking open xterm for 1.1).
With this fix, the text is sent after the terminal is shown/activated/created (but then the terminal has focus).
**Not sure this is much of an improvement (or worth …
=> Send-to-terminal startup fixes

src/cpp/session/resources/markdown_help.html
Scoping this change to markdown quick reference since it changes the backgorund color without setting the color
Before,
After,
This is the classic mode version, which is also affected with this change but shouldn't cause a regression since the color was already implicitly black.
=> fix font color in markdown quick reference

src/cpp/CMakeLists.txt
Rsession crashes in certain paste/sent-to-terminal situations were caused by the websocketpp library relying on undefined, platform-specific C++ behavior.
Discussion of the issue, and the ultimate resolution: https://github.com/zaphoyd/websocketpp/issues/395
Confirmed the crash was happening in the code described in that issue, and that our version of websocketpp was earlier than 0.7, where the fix was made by removing the troublesome code altogether.
This could be a crashing issue on all platforms, even though so far we've only heard about it on Windows, so making the change to the safer code for all platforms.
=> Fix rsession websocket crashes

src/cpp/session/modules/SessionBreakpoints.R
This change should fix this bug https://support.rstudio.com/hc/en-us/community/posts/210535867-debugSource-doesn-t-work-with-utf-8-characters-with-umlauts-
It seems that RStudio debugger currently uses only system encoding ingoring `encoding` argument. This lead to problems on Windows debugging UTF-8 files.
For example, these lines with cyrillic characters
```r
print("якорь")
print("тест")
```
are currently looking like this using RStudio ver. 1.0.153 debugger:
```r
> debugSource('D:/R code/ts.test/utf8_test.R', encoding = 'UTF-8', echo=TRUE)
Called from: eval(expr, envir, enclos)
Browse[1]> n
debug at D:/R code/ts.test/utf8_test.R#1: print("СЏРєРѕСЂСЊ")
Browse[2]> n
[1] "СЏРєРѕСЂСЊ"
debug at D:/R code/ts.test/utf8_test.R#3: print("С‚РµСЃС‚")
```
Should I really sign your contributor …
=> Correctly set encoding in RStudio debugger

src/cpp/session/modules/NotebookData.R
After running a notebook chunk, `print.knitr_kable` was left in the `tools:rstudio` environment, so `knitr::kable()` objects didn't print properly in the console.  See https://stackoverflow.com/questions/45884403/knitrkable-does-not-pretty-print-after-running-an-r-chunk for details.
It might be better to fix `initDataCapture` instead, putting the `print.knitr_kable` in the same way as the other print overrides, but I don't understand that code well enough to know if there's some reason it was handled differently.
=> Remove print.knitr_kable override

src/cpp/session/modules/SessionRCompletions.R
Without this change the type is assumed to be `.rs.acCompletionTypes$UNKNOWN`, which the IDE will use backticks to quote if it contains non-syntastic characters. This allows custom completions to pass a type along to the IDE if desired and along with https://github.com/jimhester/completeme/commit/60a46e9786ab4e39ef3399cd96927366b3079183 makes custom completions work well in the IDE for (https://github.com/hadley/emo/pull/32, https://github.com/hadley/devtools/pull/1595).
It would be nice to have this change in the 1.1 release, but understandable if it is not possible.
=> Add type if the custom results contain the attribute

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java
Bug: When creating a new terminal via `rstudioapi::terminalCreate` or `rstudioapi::terminalExecute`, the created terminal isn't always switched-to in the UI (another terminal is shown).
Fix only touches code hit via `rstudioapi` for terminal.
To repro, there must be at least one terminal already created, the session must have been stopped or suspended, then reloaded, but the terminal tab has not yet been activated so the existing terminals are not loaded.
Problem happens because triggering display of terminal tab will asynchronously load and show the first terminal in the list (which won't be the one being created via the API if there are already terminals). This finishes after the call to select the newly created terminal.
Fix: trigger `onActivateTerminal()` first (thus selecting the …
=> Terminal API fix, created terminal not always shown

src/cpp/core/include/core/Algorithm.hpp, src/cpp/core/include/core/r_util/RFunctionInformation.hpp, src/cpp/session/modules/SessionAsyncPackageInformation.cpp, src/cpp/session/modules/SessionCodeTools.R, src/cpp/session/modules/SessionDiagnostics.cpp, src/cpp/session/modules/SessionRCompletions.R, src/cpp/session/modules/SessionRCompletions.cpp
This PR fixes a couple issues in the completion + diagnostic engines. In a document with the contents:
```R
library(nycflights13)
print(flights)
```
Firstly, RStudio would fail to detect that the `flights` object is made available by this package, e.g.
Secondly, the dataset would not be reported as part of the completion list:
Note that both of these issues are resolved by explicitly loading the `nycflights13` package (recall that RStudio has a system for asynchronously building a completion list for packages that are used, but not loaded, in the current session).
=> properly handle datasets in completions, diagnostics

src/gwt/src/org/rstudio/core/client/widget/BottomScrollPanel.java
With Windows display zooming at a variety of settings (> 100% - 225%) I observed a frequent off-by-one in the values returned by `ScrollPanel` used to determine if it is scrolled to the bottom.
So for Windows, I allow a fudge-factor of 1 pixel to prevent auto-scrolling from getting stuck.
=> Fix stuck console scrolling on high-dpi Windows

src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java
From [dark theme blog post](https://blog.rstudio.com/2017/08/30/rstudio-dark-theme/), suggestion to mark what the default theme is. I remember wondering also how to revert to the default myself.
=> Mark TextMate theme as the default un UI

src/cpp/core/include/core/terminal/PrivateCommand.hpp, src/cpp/core/terminal/PrivateCommand.cpp, src/cpp/core/terminal/PrivateCommandTests.cpp
Terminal environment capture relies on **$HISTCONTROL** being **ignoreboth** or **ignorespace**, otherwise the "hidden" commands will show up in terminal history, essentially one after every user command.
RStudio does set **$HISTCONTROL=ignoreboth** when launching a terminal, but shell config can override it (often to ignoredups).
This PR detects this and disables further "hidden commands" for the duration of the session, leaving only a single weird command in the shell history. It also logs a warning.
=> (1.2) Stop environment capture when wrong HISTCONTROL found

src/cpp/session/resources/grid/gridviewer.js
This was because the back-end uri decodes the payload, but the front-end client was not sending the query as uri encoded.
=> Fixed bug where you could not filter on certain special characters such as + in data viewer

src/cpp/rstudio-tests.in
After a Mac IDE desktop debug build, the `rstudio-tests` script wouldn't work without manual tweaks. Fix to handle both cases.
=> (1.2) Fix rstudio-tests script for Mac IDE build

src/cpp/session/modules/SessionGit.cpp
This PR fixes an issue where attempts to commit from the RStudio UI could occasionally fail (especially when using NFS) with an error message like:
fatal: Unable to create '<project>/.git/index.lock': File exists.
This was effectively caused by us creating a race condition between a `git status` call and a separate `git commit` call. (It's worth noting that some read-only operations, e.g `git status`, still require a lock on the index)
Because we used a `RefreshOnExitScope` in these routines where we created console processes, we ended up with the following sequence of events:
1. A `RefreshOnExitScope` object is created,
2. A console process that will attempt to call e.g. `git commit` is created,
3. The routine exits, and the destructor of the `RefreshOnExitScope` is called,
4. We now …
=> don't refresh if running w/console proc

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermNative.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermWidget.java
Translate the older `mousewheel` events sent by Qt into the standard `wheel` events expected by xterm.js.
Also added additional comments calling out where code relies on xterm.js internals.
=> (1.1) Fix mouse-wheel scrolling on Windows/Linux desktop

src/cpp/server/extras/launchd/com.rstudio.launchd.rserver.plist.in
On macOS, the locale was only set for desktop GUI. For rstudio server, we need to hard code it in the launch script.
=> set the default LANG to en_US.UTF-8

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java
This addresses two issues with the terminal API, both related to code relying on order-of-operation that isn't consistent at runtime.
I will definitely put this in 1.2, question is whether issues matter enough to take for 1.1.
**Issue 1**: When creating the first terminal with `rstudioapi::terminalCreate`, two terminals would be created (the one you wanted, plus an extra one).
**Issue 2**: When creating or selecting a terminal via the API, the wrong terminal would often be selected (i.e. not the one you just created, or not the one you told the API to select).
**WORKAROUNDS**: You can mostly mitigate these problems by making sure the terminal tab has been viewed during this rsession, and at least one terminal exists. It should be sufficient to do an `rstudioapi::terminalActivate()` call …
=> Fix issues with terminal creation/selection via API

cmake/modules/FindLibR.cmake
I am on macOS 10.12 and R was installed via homebrew. Since it was not installed as a framework, `LIBR_LIBRARIES` returns `/usr/local/lib/libR.dylib` instead of `/<path to framework>/R.framework`. 
This PR extends `FindLibR.cmake` to find such R installation.
=> allow non-framework R installation

src/cpp/session/SessionOptions.cpp
We don't need to adjust these directories for rstudio server on MacOS.
=> adjust directories only on MacOS desktop

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/events/SwitchToTerminalEvent.java
When a terminal is created via the API, it is started up on the server-side, then the client is told to connect to it. The client then loads the buffer from the server into the terminal.
For Command Prompt and PowerShell, buffers aren't loaded from the server due to issues with those shells and WinPty if text is injected directly into xterm.js.
So any output that was generated before the client/server connection was established is never shown, i.e. the initial shell message and prompt. Results vary based on timing of the different steps.
This change special cases it so the buffer is loaded when a Command-Prompt or PowerShell terminal is first being created and connected via the API. This prevents the blank screen, but can introduce some of the issues with WinPty.
Example would be a …
=> FIx blank Windows terminal created with api

src/cpp/session/modules/SessionGit.cpp
This PR allows us to intercept SSH_ASKPASS on macOS, as `ssh-askpass` is no longer provided by default.
=> intercept SSH_ASKPASS on macOS

src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesListDataGridStyle.css
Missed to apply saturation in the file list to even rows.
=> Fix odd row saturation in files under flat themes

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/chaos.css, src/gwt/tools/compile-themes.R
THe chaos theme uses `border 1px` instead of `width 1px` like the other themes for their code margin, not entirely sure why this theme behaves in this way but seems safe enough to reduce the width to make it render similar to the other themes, with this change:
=> Fix code margin overlapping chunk under 'chaos' editor theme

src/cpp/r/R/Options.R, src/cpp/session/modules/SessionHTMLPreview.cpp, src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewPanel.java
- Allow callers to indicate that they've already created self_contained html (major performance boost for larger pages)
- Use 200ms rather than 500ms delay for event delivery
- Use setUrl rather than navigate when loading a new URL (deals with same origin policy restrictions)
Should carry zero risk for codepaths outside of page_viewer so very low risk (the use of setUrl rather than navigate is the only change that would affect other scenarios, however we also do this in several other previewers e.g. shiny app viewer so it should be safe).
=> page viewer improvements

src/cpp/core/Trace.cpp, src/cpp/session/modules/SessionSVN.cpp
I have just successfully built rstudio with boost 1.65 rather than 1.63. Two necessary changes are needed,
1. the `include <iostream>` is needed for `std:cerr`. May be because `boost/utility.hpp` doesn't include `iostream` now!?
2. instead of `boost::posix_time::time_duration::sec_type`, use `boost::uint64_t` to avoid ambiguous conversion in boost 1.65.
=> build with boost 1.65

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java
When sending multiple lines of text to terminal (Windows-specific, Command Prompt or PowerShell only) the wrong line endings were sent and the input was smushed together in one command instead of multiple commands.
This was partially fixed by https://github.com/rstudio/rstudio/pull/1463, but it didn't handle the case where (1) there was no existing terminal so one had to be created and started or (2) the first terminal had not yet been shown (i.e. after closing and restarting RStudio, but not clicking on the Terminal tab), so it had to be started before sending text. Good catch by @ronblum.
Simple change to use the helper I created for the mainline scenario (sending text to a "live" terminal instance).
`receivedSendToTerminal` just passes through to `receivedInput` unless running Windows …
=> Fix send-to-terminal line endings on terminal startup

src/cpp/r/R/Diagnostics.R
This fixes an issue in which `--run-diagnostics` shows an error caused by attempting to `cat()` the uninitialized `diag` variable.
=> Avoid use of uninitialized 'diag' variable

src/cpp/session/SessionMain.cpp, src/cpp/session/modules/SessionPatches.R
This PR fixes an issue in rstudioapi 0.7 (which unfortunately just hit CRAN) wherein we accidentally delegated `selectDirectory()` to `selectFile()` instead.
This PR allows us to fix the issue on the RStudio side without necessitating a patch release of the `rstudioapi` package. (@jjallaire, let me know if you'd prefer if we just submit a patch release instead)
=> patch 'selectDirectory()' for rstudioapi 0.7

src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ConnectionExplorer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/ObjectBrowserModel.java
This change fixes a bug in which the list of tables in the Connections pane is sometimes not fetched when initially connected. The fix is in two parts:
1. If we have a connection and enter the connected state, refresh the list of objects.
2. Because of this change (and some other codepaths around connection state changes), it is possible in some circumstances that two or more requests will be made for the list of tables concurrently. This can be an expensive call for some large databases, so if a request for the object list is made while we are currently waiting for one to return, we now stack the requests and fulfill both with the single pending RPC.
=> Ensure tables refreshed on connected state

src/cpp/desktop-mac/GwtCallbacks.mm, src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/cpp/session/modules/SessionWorkbench.cpp, src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java, src/gwt/src/org/rstudio/studio/client/workbench/Workbench.java, src/gwt/src/org/rstudio/studio/client/workbench/model/TerminalOptions.java
Regressions/issues from this change back in June to **Make Tools/Shell use default terminal on Windows**: https://github.com/rstudio/rstudio/pull/1326
* PowerShell wasn't launching successfully; window would appear then go away; caused by passing `--login` and `--i` command line arguments, which should only be passed to Posix-y shells
* Native Windows shells (cmd, and newly added PowerShell) weren't getting `HOME` set to `USERPROFILE`, as they had been in 1.0.
To fix, I now pass the shell-type constant up to the code that launches the system terminal, and based on that can decide which behaviors to perform.
=> Fixes to launching native shells on Windows (1.1)

src/cpp/session/modules/SessionCodeTools.R
This PR updates the non-standard evaluation detection system to better understand S3 dispatch + `rlang` idioms for non-standard evaluation. This should fix spurious warnings seen with the latest versions of `dplyr` + other packages using `tidyselect` when diagnostics are all enabled.
In other words, we should no longer see false positives like the following:
=> improve NSE detection for dplyr

src/cpp/session/modules/SessionGit.cpp, src/gwt/src/org/rstudio/studio/client/common/vcs/RemotesInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/CreateBranchDialog.java
This PR tries harder to select an appropriate remote in the 'Create Branch' dialog:
1. If the current branch has a tracking remote, then we'll select that as the remote to use in the create branch dialog.
2. If the active branch has no tracking remote, then we'll default to a remote called `origin` (if it exists).
3. All else fails, we'll just use the first remote in the list (the current behavior).
=> work harder to infer desired remote

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/Help.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpTab.java
See also: https://github.com/rstudio/rstudio-web/pull/11
This PR adds a link to the `purrr` cheat sheet, and also a general `Browse Cheatsheets...` link to open the set of cheat sheets available at https://www.rstudio.com/resources/cheatsheets/.
=> add 'purrr' cheat sheet

src/cpp/desktop-mac/GwtCallbacks.mm
This PR should resolve an issue where the Xcode 9.0 update (which cases command line tools to become missing) would cause issues with the Git pane showing up. With this, RStudio should appropriately detect the `/usr/bin/git` 'stub' on newer macOS platforms and prompt for installation of build tools.
=> detect 'mavericks or greater'

src/gwt/src/org/rstudio/core/client/widget/MessageDialog.java
My devmode setup was throwing an exception at startup, and the resulting attempt to show error dialog was also throwing exception leaving a grey screen after the progress spinner dismissed.
Console had one of these from each attempt to reload.
`26 Sep 2017 18:34:47 [rserver] CLIENT EXCEPTION (rsession-gary): (TypeError) : Cannot read property 'replace' of undefined;`
There was an RPC parsing exception being thrown, with a null message in the exception, which led the DomUtils.textToHtml being called on a null string while building the error dialog.
This change prevents that null exception and allows the dialog to be shown, albeit without a message in it, versus a grey screen.
As soon as I fixed this the UI launched successfully, which seems rather odd, as I was expecting to see the error …
=> Prevent blank startup screen when exception thrown at startup

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalTabPresenter.java
Converted some terminal anonymous classes to lambdas to get a feel for the syntax.
One thing I noticed, breakpoints in Chrome debugger get trickier with the more compact syntax. For example, put breakpoints on each of these lines in TerminalPane.java, inside `sendToTerminal` function:
```
activateTerminal(() -> { // breakpoint one
ensureTerminal(text); // breakpoint two
Scheduler.get().scheduleDeferred(() -> suppressAutoFocus_ = false); // bp three
});
```
The first will fire when the app is starting up (the containing function `sendToTerminal` **doesn't** execute during startup).
When you do the UI action to trigger a call to `sendToTerminal`, the second breakpoint fires as expected, when `activateTerminal` invokes the passed callback lambda. Note that the first breakpoint does not fire …
=> Lambda-ify some terminal code to get a feel for it

src/cpp/session/modules/SessionRmdNotebook.R
This change fixes a problem reported here, in which executing a chunk with a malformed header can lead to a crash:
https://community.rstudio.com/t/quick-way-to-crash-rstudio/1358
The actual problem is somewhat deep, and has to do with how error conditions affect notebook chunk execution. In this case, the ordering is such that the chunk's execution context is connected, but never disconnected, and so it keeps receiving console input events when no longer on the heap, leading (predictably) to a crash. This shouldn't be possible.
However, this warrants fixing for 1.1, so I'm proposing this more targeted fix to begin with, which simply eliminates the source of this specific error so that it can't set off the dominos.
=> fix crash when executing certain malformed chunk headers

src/cpp/desktop/DesktopApplicationLaunch.hpp, src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopMainWindow.hpp, src/cpp/desktop/DesktopPosixApplication.cpp, src/cpp/desktop/DesktopPosixApplication.hpp, src/cpp/desktop/DesktopPosixApplicationLaunch.cpp, src/cpp/desktop/DesktopSessionLauncher.cpp, src/cpp/desktop/DesktopUtils.cpp, src/cpp/desktop/DesktopUtils.hpp, src/cpp/desktop/DesktopWin32ApplicationLaunch.cpp
This change fixes a problem in all RStudio Desktop releases on Ubuntu Xenial in which no commands that start a new session (open project in new session, etc.) work.
The underlying issue is that the desktop release of Xenial comes with its own version of Qt. When RStudio is first launched, this isn't a problem, as its `RPATH` causes the RStudio version of Qt to be used. However, during startup, RStudio invokes `prepareEnvironment`, which in turn sets `LD_LIBRARY_PATH` to include the system library folders. Now subsequent launches of RStudio don't work because they inherit this `LD_LIBRARY_PATH`, which overrides the `RPATH` and causes the nascent RStudio process to load the wrong Qt libraries and fail to start. 
The fix is to cache the `LD_LIBRARY_PATH` that's used when RStudio starts, and …
=> Cache and replay app launch environment

src/cpp/session/modules/SessionProjectTemplate.cpp
This PR should fix an issue where crashes were seen when the project template indexer was running on R libraries containing a large number of R packages.
The crash was occurring because we were trying to construct a `boost::cref()` based on an object on the stack, and that object would already be out of scope by the time the continuation was to be executed. The fix is to simply pass in the continuation by value, since it (as it's just a `boost::function`) is copyable already.
=> pass continuation by value, rather than reference

src/cpp/session/modules/SessionSource.cpp
This PR should fix an issue where attempts to set some editor settings (e.g. tab width) would not be respected when no project was open.
Because this code path did not properly verify that we were within a project, we ended up propagating the 'default' project configuration options, and using those to override whatever global settings that might've already been set by the user.
Should be a candidate for v1.1 backport.
=> ensure we're in a project before trying to use project config

src/gwt/src/org/rstudio/core/client/MathUtil.java, src/gwt/src/org/rstudio/core/client/StringUtil.java, src/gwt/src/org/rstudio/studio/client/common/r/RTokenizer.java, src/gwt/test/org/rstudio/studio/client/common/r/RTokenizerTests.java
This change fixes a unit test failure with GWT 2.8. In particular, the identifier which begins with a Unicode letter `\u00C1qc1` is no longer recognized as an identifier and instead causes an error in the tokenizer.
https://github.com/rstudio/rstudio/blob/master/src/gwt/test/org/rstudio/studio/client/common/r/RTokenizerTests.java#L109
It turns out that the `isLetter()` function in GWT does not support non-ASCII characters, even though Java is supposed to do so; see this GWT issue for details: https://github.com/gwtproject/gwt/issues/1989
Since `isLetter()` doesn't do the right thing here, the fix is to use our own `isLetter()` which is unicode-aware.
=> Use unicode-aware isLetter function in R tokenizer

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkDataWidget.java
From http://www.gwtproject.org/javadoc/latest/com/google/gwt/core/client/ScriptInjector.FromUrl.html:
```
Warning: This class does not control whether or not a URL has already been injected into the document. The client of this class has the responsibility of keeping score of the injected JavaScript files.
```
=> Remove multiple instances of pagedtable.js

NOTICE, dependencies/windows/.gitignore, dependencies/windows/install-dependencies.cmd, src/cpp/CMakeLists.txt, src/cpp/core/CMakeLists.txt, src/cpp/core/system/Crypto.cpp
**Requires rerunning `install-dependencies` and `cmake`.**
This seeds openssl for Windows for other ongoing work not included in this PR, I have confirmed it is working as expected in that other branch.
The openssl package was built via cross-compilation using MinGW on Linux. See README inside the downloaded package for full details.
=> Add openssl support to Windows build environment

src/gwt/src/org/rstudio/core/client/files/filedialog/OpenFileDialog.java
This PR fixes a small issue in the web file dialogs wherein clicking on a directory, and then pressing the `Open` button, would not navigate into that directory.
=> allow 'Open' to navigate into selected directory

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTargetCodeExecution.java
This PR tweaks how we trim executed code -- in particular, we no longer trim leading whitespace from the first line, which should improve the display of executed code. See e.g.
=> tweak trimming of executed code

src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
See https://github.com/rstudio/rstudio/issues/1582, improve help highlight contrast under dark theme, as in:
=> Improve search highlight under dark theme to fix #1582

src/gwt/acesupport/acemode/python.js, src/gwt/acesupport/acemode/python_highlight_rules.js, src/gwt/src/org/rstudio/studio/client/common/reditor/EditorLanguage.java
This PR forks Ace's Python highlight rules, in preparation for future improved editor support. We also implement a bit of extra highlighting, to better match how we highlight in R modes. (e.g. we now highlight brackets and `.`)
=> fork python highlight rules

src/cpp/session/resources/help_resources/index.htm, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
This change adds a link to the [RStudio Community Forum](https://community.rstudio.com/c/rstudio-ide) to the IDE's help menu.
In RStudio Open Source, this link replaces the link to RStudio Support; in Pro, both links are shown. 
Practically speaking, very little peer-to-peer support occurs on the "support forum"; most questions take a long time to appear (~1 day), and have no responses or only a single response from the IDE team. In contrast, the community forum (though new) is much more user-friendly and has more active peer support. The downside, of course, is that it doesn't have the long tail of searchable content, so there's undoubtedly a tradeoff here.
=> Add community forum link

src/cpp/desktop/DesktopGwtCallback.cpp
=> avoid querying clipboard while modal active

src/gwt/src/org/rstudio/studio/client/workbench/views/environment/dataimport/DataImport.java
It is possible that a response will come out of order in the data import dialog while assembling preview, for instance, as report by @jennybc:
and a request log showing:
Fix is to discard old assemble responses coming into this dialog.
=> Discard old data import assemble responses

src/cpp/session/modules/SessionRCompletions.R
=> handle autocompletion of C++Object

src/cpp/conf/rserver-dev.conf, src/cpp/conf/rsession-dev.conf, src/cpp/server/ServerSessionManager.cpp, src/cpp/session/include/session/SessionOptions.hpp
Normally running with `--server-daemonize=0` causes errors to be sent to stderr. If the `allow-full-ui` option is off (only available in RSP) override this behavior so the errors aren't showing up in the R Console in a containerized situation.
=> Don't turn on log-stderr just because server-daemonize is off

src/cpp/session/modules/SessionWorkbench.cpp
This PR fixes an issue where users who have e.g. Git or SVN binaries installed into a sub-directory of home (which is somewhat common for portable Git installations on Windows) would find that their binaries were not properly detected / used. This would manifest as e.g. the Git tab not showing up, despite having pointed RStudio to an existing git executable.
=> resolve aliased vcs paths from client

Jenkinsfile, dependencies/common/install-gwt, docker/jenkins/Dockerfile.centos6-x86_64, docker/jenkins/Dockerfile.centos7-x86_64, docker/jenkins/Dockerfile.debian9-x86_64, docker/jenkins/Dockerfile.precise-amd64, src/gwt/CMakeLists.txt, src/gwt/build.xml, src/gwt/gwt-unit-tests.sh.in
This change makes a number of improvements to the GWT build process.
- **GWT, GIN, and other libraries can now be stored outside the source tree**. Formerly, these libraries were presumed to exist at a hardcoded location inside the source tree. This change allows us to cache them in the Docker build containers, resulting in faster, less network-reliant builds.
- **Build output can now be placed in the binary directory**. Formerly, build output only went to the source directory. Using the binary directory prepares us for an upcoming change in which builds will happen outside the source tree.
- **Unit tests are run as part the build process**, using a unit test script generated at compile time with the appropriate folders.
None of these changes disturb the workflow we already use; the …
=> Improvements to GWT build & test

src/cpp/core/system/Crypto.cpp, src/cpp/core/system/CryptoTests.cpp
In addition to a previous pull request of mine.
I assume this part of code was introduced after the release of 1.1. I use this to build locally for a while. Once this gets merged https://github.com/JanMarvin/rstudio-archlinuxpkg/blob/master/rstudio/openssl11.diff is the only pending change required to build with OpenSSL 1.1.0
Sincerely,
Marvin
=> Update EVP to work with OpenSSL1.1.0

src/cpp/desktop/CMakeLists.txt, src/cpp/desktop/DesktopUtilsMac.mm
Bare minimum fixes to make Mac once again buildable with Qt. This doesn't enable it, just makes it work if you enable by modifying `src/cpp/CMakeLists.txt` delete the special case where APPLE uses `desktop-mac` instead of `desktop`. Must also install `Qt 5.4.2` sdk.
This was the bare minimum; I confirmed it builds and launches. I almost immediately found an issue, where Ctrl+L doesn't clear the console; didn't investigate any further.
=> Fixes to make Mac Desktop buildable with Qt

src/cpp/r/RSexp.cpp, src/cpp/r/include/r/RSexp.hpp, src/cpp/session/SessionConsoleInput.cpp, src/cpp/session/modules/SessionEnvironment.R, src/cpp/session/modules/environment/SessionEnvironment.cpp, src/cpp/session/modules/environment/SessionEnvironment.hpp
This change prevents sessions from suspending when they have active external pointer objects.
This more or less duplicates some existing R code which looked for the opposite case (`NULL` external pointers). This has been rewritten in C for efficiency, and updated to search inside environments as well as S4 objects.
=> Don't suspend sessions with external pointers (fixes #1696)

src/cpp/session/modules/SessionDataViewer.R
This PR should vastly improve the data viewer performance when attempting to view large datasets (>10M rows). We avoid accidentally synthesizing a character vector equal to the number of rows of the dataset, when the row names are stored in a so-called compact representation.
I believe this will close #1705. While this does fix one kind of data viewer slowness, I unfortunately don't think it'll fix the issue seen by users when attempting to View datasets when their home directory lives on a network drive (that is still a separate issue).
=> improve Viewer performance w/large datasets

src/cpp/r/R/Api.R
`rstudioapi::getThemeInfo()` returns `dark = FALSE` under classic mode but since Hadley is using this to match console colors, changing this to be enabled under classic themes.
=> Change rstudioapi getthemeinfo to mark themes dark in classic mode

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/xterm/XTermNative.java
Broken by update to xterm.js 2.9.2 internals, which I took late in 1.1 cycle. So close to getting away with it relatively unscathed! :-(
Resolves #1725 
Regression caused Ctrl+L to clear entire terminal even when running a full-screen program such as tmux, which does its own handling of Ctrl+L to clear the current pane, instead. Essentially, Ctrl+L messes up full-screen programs and prevents them from doing what they want with Ctrl+L.
Also messed up which commands display in upper-right of Terminal toolbar (stop and clear should be hidden when running full-screen program, but they aren't).
=> Fix client-side terminal alt-buffer detection

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
Resolves #1723 
Don't need a special "clear terminal" shortcut key, as we use Ctrl+L for that when terminal is showing, and Ctrl+Shift+L is used by Load All.
=> Stop terminal from hijacking Ctrl+Shift+L shortcut

src/cpp/r/R/Api.R
See https://github.com/rstudio/rstudioapi/issues/73
Under default settings, `rstudioapi::getThemeInfo()` returns:
```r
$editor
NULL
$global
[1] "Modern"
$dark
[1] NA
```
but defaults should be provided
=> Support retrieving default for editor in getThemeInfo()

src/cpp/session/SessionConsoleProcessInfo.cpp, src/cpp/session/include/session/SessionConsoleProcessInfo.hpp
Use default member initialization to make the `ConsoleProcessInfo` constructors somewhat less repetitive, hideous, and error-prone.
=> Use class member init on ConsoleProcessInfo class

src/cpp/core/include/core/r_util/RProjectFile.hpp, src/cpp/core/r_util/RProjectFile.cpp, src/cpp/session/modules/SessionSource.cpp
This is a candidate fix for the slowness observed by some Windows users running on networked filesystems, re: https://github.com/rstudio/rstudio/issues/1592.
In v1.1, we introduced a feature that attempts to respect a parent project configuration when opening a file located outside of the current project. We do this by looking up the filesystem for files with the extension `.Rproj`, which implies recursively listing the contents of directories until a directory is found.
Unfortunately, there were two problems:
1) Newly-created documents don't have a path; calling `resolveAliasedPath()` on those returns the home directory;
2) We never anchored the lookup to a suitable path (ie, the user's home directory, or the parent of that directory)
This meant that opening a new file would trigger a …
=> candidate fix for slowness on NFS

src/cpp/session/modules/SessionRCompletions.cpp
While the performance impact is likely minimal the switch is also a little safer.
In this case there were two '*' cases in the original code, which caused a compiler error when using the switch.
Interestingly with -O3 clang 5.0.0 does this same optimization automatically (https://godbolt.org/g/Eji22K)
=> Use a switch instead of nested conditionals

src/cpp/desktop-mac/CMakeLists.txt, src/cpp/session/CMakeLists.txt
Fixes #1600.
RStudio 1.1 was built on a Mac Mini running Mavericks. Apple included an (old) copy of OpenSSL with Mavericks, with the accompanying headers. It continues to ship that very old copy of OpenSSL today in MacOS, presumably for compatibility with apps built on older MacOS (like ours) but no longer includes headers.
When Apple formally removed all the OpenSSL development headers in El Capitan (in favor of the [LibreSSL](http://www.libressl.org/) fork), we kept RStudio building on our development machines by building and linking against a non-Apple OpenSSL. 
https://github.com/rstudio/rstudio/blob/34755a49383433202e758e1cd1f3a49ff0220e2d/src/cpp/core/CMakeLists.txt#L185-L203
Now that we're building Mac releases on newer machines, we can no longer build our release against OpenSSL …
=> Bundle OpenSSL on MacOS

src/cpp/session/modules/SessionSource.cpp
Part of https://github.com/rstudio/rstudio/issues/1552; eligible for backport to v1.1-patch.
=> inherit project config from non-active projects only

src/cpp/session/SessionSourceDatabaseSupervisor.cpp
This should resolve https://github.com/rstudio/rstudio/issues/1690. Note that the comment above this routine seems to indicate that this is the expected behavior: if we fail to lock an older, orphaned source database, that should not be fatal.
=> failure to lock source database should not be fatal

src/cpp/desktop/resources/freedesktop/rstudio.desktop.in
https://en.opensuse.org/openSUSE:Packaging_desktop_menu_categories#Development according to the FreeDesktop standards. Some Linux distributions are rather strict about it.
=> Added a sub category for the .desktop file

src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java
Fixes #1844
If the terminal websocket gets closed (seeing this happen in container scenarios), mark the terminal as disconnected so the reconnection logic kicks in. For example, terminal should reconnect if the user types in the disconnected terminal.
Prior to this fix, the terminal would remain inactive and ignore input in this scenario.
=> Reconnect terminal if websocket was closed

src/cpp/session/SessionModuleContext.cpp, src/cpp/session/modules/ModuleTools.R, src/cpp/session/resources/pandoc_template.html, src/cpp/session/resources/plot_publish.html
This change makes the minimal changes necessary to make `pandocSelfContainedHtml` work under Pandoc 2, in the case wherein `RSTUDIO_PANDOC` has been set to use Pandoc 2. In particular, it adapts to the following breaking changes in Pandoc 2:
1. The `<!DOCTYPE html>` header was treated as HTML and passed through, unmodified, in Pandoc 1. In Pandoc 2, it is treated as Markdown and escaped.
2. In Pandoc 2, the HTML converter warns loudly if no title is present in the metadata. 
To address these, respectively:
1. We now use an HTML template that includes the `DOCTYPE` header. If the `DOCTYPE` header is also present in the input HTML, it is removed. 
2. We pass a dummy title metadata field into the converter. It is not used in the template, so it isn't present in the output. 
These changes are …
=> Make self-contained output compatible with Pandoc 2

src/cpp/core/include/core/system/ShellUtils.hpp, src/cpp/core/system/ShellUtils.cpp, src/cpp/core/system/Win32ChildProcess.cpp, src/cpp/session/modules/SessionGit.cpp
This PR fixes an issue where attempts to stage a path whose filename is not representable in the active system encoding could fail. We accomplish this by:
- Adding a switch, allowing the `ShellArgs` class to avoid conversion of file paths to the system encoding;
- Using the wide API for creating a system process, and ensuring all the bits passed in are 'wide' (UTF-16) strings.
This PR deserves extra scrutiny since it exercises a heavily used codepath (Windows process creation). Fortunately, the changes are relatively straightforward -- we use `utf8ToWide()` to construct wide strings, and pass those on to the wide Windows APIs as needed.
=> git: improve handling of multibyte paths

src/cpp/core/BoostErrors.cpp, src/cpp/core/Error.cpp, src/cpp/core/FilePath.cpp, src/cpp/core/include/core/http/AsyncServerImpl.hpp, src/cpp/core/include/core/http/NamedPipeAsyncClient.hpp, src/cpp/core/include/core/http/SocketUtils.hpp, src/cpp/core/system/Win32OutputCapture.cpp, src/cpp/server/ServerSessionProxy.cpp
as the function was deprecated: www.boost.org/doc/libs/1_54_0/libs/system/doc/reference.html
Fixes https://github.com/rstudio/rstudio/issues/1891.
=> Replaced get_system_category() with system_category()

src/cpp/core/http/SocketProxy.cpp
re: https://github.com/rstudio/rstudio/issues/1891
This should help ensure that RStudio can compile against both older and newer variants of OpenSSL / Boost. This is based on the upstream Boost change, https://github.com/chriskohlhoff/asio/commit/92bfc623e6a71353dd2c783f4c9fef5591ac550d.
cc: @Mailaender
=> compile with newer OpenSSL variants

src/cpp/session/SessionMain.cpp, src/cpp/session/SessionRpc.cpp, src/cpp/session/SessionRpc.hpp
This avoids issues where the destructor could be run during an abnormal
process termination, leaving the R session pegging the CPU at 100%.
Closes https://github.com/rstudio/rstudio/issues/1881.
=> explicitly allocate JSON methods map on heap

src/cpp/CMakeLists.txt, src/cpp/core/system/ChildProcessSubprocPollTests.cpp
The first issue prevented one of the unit tests from building due to include order due to inclusion of Boost Deadline Timer, but this was fixed by simply changing the wait method to a simple thread sleep. Second issue occurred because building a package build for Win64 was not linking the correct x64 OpenSSL lib.
Let me know if there was a reason the OPENSSL_ARCH was not being set by default for x64 - perhaps I am missing something.
=> Fixed Windows unit tests building

src/cpp/session/SessionSourceDatabase.cpp
This should resolve https://github.com/rstudio/rstudio/issues/1623. I believe this is a candidate for the patch release. Copying motivation from that thread:
---
I was able to reproduce this issue in the following way.
1. Create an RStudio project,
1. Open that project with RStudio v1.0,
1. Open a few files in that project,
1. Shut down the IDE,
1. Open the project with RStudio v1.1,
1. Try editing one of the open files,
1. Close and re-open RStudio v1.1,
1. Notice that the open document is empty.
I think this is because we don't fully migrate to the new format on the first transfer of files. On the first open of RStudio v1.1, the sources folder looks like this:
```
$ tree
.
├── per
│   ├── t
│   └── u
├── prop
│   ├── 2646FB5C
│   ├── 28A9DEA3
│   ├── DC6A99FB
│   └── INDEX
└── …
```
=> migrate contents file on first properties access

src/cpp/core/http/SocketProxy.cpp
see https://github.com/rstudio/rstudio/pull/1894#commitcomment-26605603
=> use correct path for boost SSL error

src/cpp/session/modules/SessionFiles.cpp, src/gwt/src/org/rstudio/core/client/files/FileSystemItem.java, src/gwt/src/org/rstudio/studio/client/server/VoidServerRequestCallback.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java
This PR ensures that case-only renamings, e.g.
.rprofile -> .Rprofile
can succeed when executed through the `renameFile` command.
=> allow case-only renames (closes #1886)

src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.R, src/cpp/session/modules/rmarkdown/NotebookAlternateEngines.cpp, src/cpp/session/modules/rmarkdown/NotebookOutput.cpp, src/cpp/session/modules/rmarkdown/NotebookOutput.hpp, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkPlotPage.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkPlotWidget.java
This PR (alongside https://github.com/rstudio/reticulate/pull/143) provides initial support for Python plot output within R Notebooks.
Requires https://github.com/rstudio/reticulate/pull/143.
There's still some more work to be done to take this over the finish line, e.g.
- Re-draw the plot when the editor surface is resized,
- Tweak the padding around images generated from Python,
but this is a good start.
=> support reticulate engine in R Notebooks

src/gwt/src/org/rstudio/core/client/StringUtil.java
Fixes #1910. Rather than hex-escaping character literals, we just allow plain old UTF-8 literals as those work as expected with R >= 3.0.0 (which we now require for newer versions of RStudio)
=> allow UTF-8 R literals

src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/application/ApplicationQuit.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/projects/Projects.java
When I added `allowCancel` to `prepareForQuit`, I changed the meaning of the existing three-argument constructor, such that the bool parameter switched from `forceSaveAll` to `allowCancel`.
Failed to update some uses, so they started setting `allowCancel` to false, when they thought they were setting `forceSaveAll` to false. Thus the cancel button vanished in those cases,
Cleaned up by eliminating the three-argument constructor, going back to one with default behavior for both `forceSaveAll` and `allowCancel`, and another constructor where both must be supplied.
Resolves #1934
=> Fix argument mismatches in prepareForQuit

src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/gwt/src/org/rstudio/studio/client/common/impl/DesktopTextInput.java
Two issues:
1. Mismatch in the signature of promptForText: the Javascript was passing one more argument than the native side was taking (okButtonCaption).
2. The New Folder codepath, and probably others, were passing null strings, which the QWebEngine doesn't handle; make sure those are mapped to empty strings, instead, when calling.
I will look closer and see if there are other places we need to do this, or maybe come up with a more elegant general solution, but want to get this issue fixed.
resolves #1956
=> Fix New Folder button in File Pane (QtWebEngine)

src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/common/DefaultGlobalDisplay.java, src/gwt/src/org/rstudio/studio/client/common/dialog/DesktopDialogBuilderFactory.java, src/gwt/src/org/rstudio/studio/client/common/impl/DesktopFileDialogs.java, src/gwt/src/org/rstudio/studio/client/common/impl/DesktopWindowOpener.java, src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteManager.java, src/gwt/src/org/rstudio/studio/client/common/synctex/Synctex.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/ui/HTMLPreviewPanel.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/RmdOutput.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/NewRSConnectAuthPage.java, src/gwt/src/org/rstudio/studio/client/shiny/ui/ShinyGadgetDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/Workbench.java, src/gwt/src/org/rstudio/studio/client/workbench/WorkbenchNewSession.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionShinyHost.java, src/gwt/src/org/rstudio/studio/client/workbench/views/presentation/Presentation.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/export/ViewerPaneSaveAsImageDesktopOperation.java
The qtwebchannel doesn't support passing null strings, so run them through StringUtil.notNull.
I had previously fixed a known problem in #1964; this change is just a blanket application to all desktop frame APIs.
=> Don't pass null string to desktop frame functions

src/cpp/r/session/REmbeddedPosix.cpp
This resolves #1970, resolves #1957 and backs-out 2a131ea9.
We need to open issues for the fixes undone by this; these predate our move to GitHub issue so need to be created.
=> Fix issue with RPC delivery when R is busy

src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/model/VirtualHistory.java
Save the scroll position as part of the virtual history used by the Help
pane.
Closes #1919.
=> save / restore help pane position

package/linux/install-dependencies
This PR installs `patchelf` for package builds (only if it hasn't already been installed through some other mechanism).
=> install patchelf for package builds

src/gwt/build.xml, src/gwt/src/org/rstudio/core/client/StringUtil.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalList.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalLocalEcho.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalPopupMenu.java, src/gwt/test/org/rstudio/core/client/StringUtilTests.java
Per a recent conversation, we decided to steer in the direction of using Java-compatible string comparision conventions, even though GWT output makes str1 == str2 an ok way to compare contents of strings (unlike Java).
For cases where null is a factor, added `StringUtil.equals(str1, str2)`. This defers to the newer Java `Objects.compare(str1, str2)`` method, but has the added benefit of compile-type type-safety (and gives a place to change our approach, should we need to).
For comparisions where we know the strings are not-null, then continued use of `str1.compare(str2)`` is the way to go, avoiding the slight performance penalty of the null checks inside Objects.compare.
Also discovered that the core/client unit tests (such as for StringUtil) were not being run. Modified build.xml to …
=> Add StringUtil.equals method for null-safe string comparison

src/cpp/desktop/DesktopSessionLauncher.cpp, src/cpp/desktop/DesktopUtils.cpp, src/cpp/desktop/DesktopUtils.hpp, src/cpp/desktop/DesktopUtilsMac.mm, src/cpp/desktop/Info.plist.in, src/cpp/session/projects/SessionProjects.cpp
This was lost in the move back to Qt. Resolves #2004.
=> Reimplement Mac Dock menu for opening new RStudio window

src/cpp/desktop/DesktopMenuCallback.cpp
`QKeySequence` renders Ctrl using the macOS "command" icon. However, we want menu shortcuts to show the literal Ctrl symbol (^); this change replaces Ctrl with Meta on macOS when populating menus.
http://doc.qt.io/qt-5/qkeysequence.html
=> Render ctrl+based shortcuts in menus correctly on macOS

src/cpp/desktop/CMakeLists.txt, src/cpp/desktop/DesktopActivationOverlay.hpp, src/cpp/desktop/DesktopApplicationLaunch.hpp, src/cpp/desktop/DesktopBrowserWindow.hpp, src/cpp/desktop/DesktopChooseRHome.hpp, src/cpp/desktop/DesktopDownloadHelper.hpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/cpp/desktop/DesktopGwtWindow.hpp, src/cpp/desktop/DesktopMainWindow.hpp, src/cpp/desktop/DesktopMenuCallback.hpp, src/cpp/desktop/DesktopPosixApplication.hpp, src/cpp/desktop/DesktopSatelliteWindow.hpp, src/cpp/desktop/DesktopSecondaryWindow.hpp, src/cpp/desktop/DesktopSessionLauncher.hpp, src/cpp/desktop/DesktopSlotBinders.hpp, src/cpp/desktop/DesktopSubMenu.hpp, src/cpp/desktop/DesktopSynctex.hpp, src/cpp/desktop/DesktopURLDownloader.hpp, src/cpp/desktop/DesktopWebPage.hpp, src/cpp/desktop/DesktopWebView.hpp, src/cpp/desktop/DesktopWindowTracker.hpp, src/cpp/desktop/synctex/evince/EvinceSynctex.hpp
This is mainly to allow us to use `boost::signals` more easily within the desktop sources. (We don't use `boost::signals` there currently but they may still be useful for 'long-range' communication between objects)
=> use Q_SIGNALS / Q_SLOTS (avoid collisions with boost)

src/cpp/r/RSexp.cpp, src/cpp/r/include/r/RSexp.hpp, src/cpp/session/modules/environment/SessionEnvironment.cpp
This change fixes a regression from https://github.com/rstudio/rstudio/commit/645a63cc072444a36da0783b4054225b24576a21, in which environment pane introspection can cause errors to be emitted at the console when reference objects are present. 
The problem is that reference objects subclass environments (`isEnvironment`), but they cannot be listed using `listEnvironment` because they are not primitive environments. The fix here is to convert the reference object into a primitive environment for introspection.
=> Convert refclasses to environments before finding nulls

cmake/modules/RStudioCMakeUtils.cmake, package/linux/make-package, src/cpp/desktop/CMakeLists.txt, src/cpp/desktop/install/LinuxInstallQt.sh.in
This PR introduces our own standalone Bash script for bundling Qt components as necessary with a Linux installation.
Don't merge quite yet; need to test on our Linux machines + Docker images.
=> use standalone script for installing Qt components

src/cpp/desktop/DesktopMenuCallback.cpp
Resolves #1955, including **Window -> Bring All to Front** menu and clicking on a single window in the Window menu.
=> Fix Bring All to Front on Mac QtWebEngine

src/cpp/desktop/CMakeLists.txt, src/cpp/desktop/DesktopUtilsMac.mm, src/cpp/desktop/DockMenu.cpp, src/cpp/desktop/DockMenu.hpp
This was lost when we switched back to Qt for Mac. Implemented using very similar code to how the Window menu's list of windows is populated.
So, the dock menu once again lists the RStudio windows, and clicking on one gives it focus and brings it forward.
Did not implement the generic window icons seen on the original; some programs have it, some don't. XCode itself, for example, doesn't show icons for its open windows on the dock menu (surprisingly). Neither does Qt Creator.
Also RStudio dock menu doesn't show the diamond symbol next to minimized windows. Qt Creator is the same in this regard; this isn't something you get automatically from a Qt app on the Mac.
Resolves #2005
=> Add RStudio windows to Mac dock context menu

src/cpp/desktop/DesktopWebPage.cpp, src/cpp/desktop/DesktopWebPage.hpp
This PR fixes an issue where, upon launch of RStudio, some satellite windows launched may be launched as 'secondary' windows rather than 'satellite' windows, hence inheriting a funky scrollbar.
On initialization, satellite windows from the previous session are prepared and launched asynchronously, at the same time. Because of this, it's possible that multiple windows could be prepared at once, and then later launched. Prior to this PR, we only had space for one pending window, so attempts to prepare more than one pending window would overwrite any pre-existing pending windows, leading to funkiness when the windows are later launched.
=> use queue for pending windows

src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java
On Chrome (Windows and Linux, not Mac) hitting Ctrl+L in the RStudio terminal clears the terminal (as it should), but then puts focus in the browser address bar. This is quite painful, especially if you are a fast typist, hit Ctrl+L in terminal, then type a command and hit enter; now the browser is going somewhere you don't want it to.
Resolves #1636.
=> Stop Ctrl+L from sending focus to browser address when in Terminal

src/cpp/desktop/DesktopMain.cpp
Closes https://github.com/rstudio/rstudio/issues/1990 -- see the associated issue for my investigation.
Let me know if this is too broad and we should scope this particular change to just e.g. macOS, or macOS + user has `Magnet` running.
=> disable accessibility rendering on macos

src/cpp/desktop/DesktopInfo.cpp, src/cpp/desktop/DesktopInfo.hpp, src/cpp/desktop/DesktopMain.cpp, src/gwt/src/org/rstudio/studio/client/application/DesktopInfo.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java
This PR allows us to select a random port for the Chromium Devtools server -- ensuring that multiple instances of RStudio can each launch their own Devtools server as required (and also selecting an open port in the case that 59009 is occupied)
=> select random port for chromium devtools server

src/cpp/desktop/DesktopMainWindow.cpp, src/gwt/src/org/rstudio/studio/client/RStudio.java
This PR fixes an issue where an attempt to load GWT before QWebChannel had been initialized could cause the IDE to fail to load on startup.
Effectively, QWebChannel is loaded asynchronously -- we create the channel object, and we provide an initialization function that gets called with channel data when it is available. This implies a JSON-RPC roundtrip over the Qt WebChannel, which may not always finish before the request to load GWT is made.
This is now handled in the following way:
1. If QWebChannel loads first, it will set a flag letting our module code know that GWT can be initialized 'eagerly'.
2. If GWT tries to load first, but sees QWebChannel is not ready, it will expose a `delayLoadApplication()` hook on the `window` object, which our QWebChannel initialization code will call …
=> orchestrate initialization of QWebChannel + GWT

src/cpp/core/r_util/RProjectFile.cpp, src/cpp/session/projects/SessionProjects.cpp, src/gwt/src/org/rstudio/studio/client/projects/Projects.java, src/gwt/src/org/rstudio/studio/client/projects/model/NewProjectResult.java, src/gwt/src/org/rstudio/studio/client/projects/model/ProjectsServerOperations.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java
Resolves #1581 
When creating a project in an existing directory (or cloning a repo), if there's an existing .Rproj with a different name than the folder, another .Rproj matching the folder name is created and opened.
E.g. Have /foo/bar.Rproj and try to create a project in /foo, RStudio creates /foo/foo.Rproj and opens it.
Uses existing `r_util:: projectFromDirectory` to search the folder for an existing .Rproj. The logic is:
(1) matching parent folder, case sensitive (/foo/foo.Rproj)
(2) matching parent folder, case insensitive (/foo/Foo.Rproj)
(3) single .Rproj in folder
(4) most recently modified .Rproj
If found, use it, otherwise create the one matching the directory name.
In `SessionProjects.cpp` I broke out the guts of the RPC handler `findProjectInFolder` to a shared function …
=> Stop createProject from making another .Rproj if one already exists

src/cpp/session/modules/SessionDataViewer.R
This PR fixes an issue where attempts to `View()` a matrix with no column names would lead to a 'squished' header with no present column names.
=> generate names when viewing matrix

src/cpp/desktop-mac/MainFrameController.mm
This PR removes our old attempt to de-register an observer that we never actually register.
@jmcphers, do you think this meets the bar for a patch release? If we plan to publish another patch release, we might want to wait until the end of rstudio::conf just to shake out any other issues that users bring to us.
=> don't attempt to de-register non-existent observer

src/cpp/core/FilePath.cpp, src/cpp/session/modules/SessionSource.cpp, src/gwt/src/org/rstudio/core/client/files/FileSystemItem.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/FileTypeRegistry.java, src/gwt/src/org/rstudio/studio/client/common/reditor/EditorLanguage.java
This PR adds the `.ini` file type to RStudio (which Ace fortuitously provides a highlight mode that we already bundle).
=> register '.ini' file type

src/cpp/desktop/DesktopGwtWindow.cpp, src/cpp/desktop/DesktopGwtWindow.hpp, src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopMenuCallback.cpp, src/cpp/desktop/DesktopMenuCallback.hpp, src/cpp/desktop/DesktopSatelliteWindow.cpp, src/gwt/src/org/rstudio/studio/client/application/Application.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java
Does what it says on the tin -- makes it possible to zoom / unzoom the IDE on all platforms, without needing a reload of the whole UI.
=> zoom without reloading RStudio UI

src/cpp/desktop/DesktopGwtWindow.cpp, src/cpp/desktop/DesktopGwtWindow.hpp, src/cpp/desktop/DesktopMenuCallback.cpp
This PR works around what appears to be a Qt bug by discarding duplicated zoom requests.
Closes https://github.com/rstudio/rstudio/issues/2126.
Reported upstream at https://bugreports.qt.io/browse/QTBUG-66207 (was able to reproduce using the Qt 'minimal' example)
=> discard duplicated zoom requests

package/linux/rpm-script/postinst.sh.in
This PR attempts to search the most common library directories for `libssl`, rather than attempting to hardcode the library path based on the version of SUSE used.
=> be more permissive in search for libssl

src/cpp/core/system/file_monitor/Win32FileMonitor.cpp
This PR seeks to resolve an issue where attempts to launch the IDE could fail if the `.git` folder was not marked as hidden. Effectively, the IDE would get deadlocked between the file monitor scanning for changes to the `.git/index.lock` file, and attempts to call `git status` to populate the Git pane.
Resolves #2141.
@jjallaire, let me know if this feels like the right change or if there's a more appropriate place for this fix to live.
Do we want to be resilient against other hidden folders that may become unhidden (e.g. the `.Rproj.user` folder)?
=> explicitly ignore '.git' folder on Windows

CMakeGlobals.txt, Jenkinsfile, dependencies/common/install-gwt, dependencies/common/install-pandoc, dependencies/common/rstudio-tools, docker/docker-compile.sh, docker/jenkins/Dockerfile.centos6-x86_64, docker/jenkins/Dockerfile.centos7-x86_64, docker/jenkins/Dockerfile.debian9-x86_64, docker/jenkins/Dockerfile.precise-amd64, docker/jenkins/Dockerfile.trusty-amd64, src/gwt/CMakeLists.txt
Currently, RStudio builds (in Docker containers) always begin with a clean `rstudio` source folder, into which common dependencies like Pandoc, clang, and mathjax are downloaded and installed to `rstudio/dependencies/common`. This uses up a lot of unnecessarily time and bandwidth. 
This change does the following for common dependencies:
- Installs dependencies to `/opt/rstudio-tools/dependencies` when building in containers.
- Reads dependencies from this folder when building, if it is present, rather than the source folder.
- Removes the code which re-installed dependencies on every build. 
Paths for local development are fully unaffected; this change only affects the paths used when building in dedicated containers.
Partially resolves #1614.
=> Make common RStudio dependencies cacheable

src/cpp/core/FilePath.cpp, src/cpp/core/StringUtils.cpp, src/cpp/core/Win32StringUtils.cpp, src/cpp/core/include/core/Error.hpp, src/cpp/core/include/core/http/NamedPipeAsyncClient.hpp, src/cpp/core/system/Win32ChildProcess.cpp, src/cpp/core/system/Win32Environment.cpp, src/cpp/core/system/Win32LibraryLoader.cpp, src/cpp/core/system/Win32OutputCapture.cpp, src/cpp/core/system/Win32Pty.cpp, src/cpp/core/system/Win32System.cpp, src/cpp/core/system/file_monitor/Win32FileMonitor.cpp, src/cpp/desktop/DesktopWin32DetectRHome.cpp, src/cpp/desktop/DesktopWin32ProgressActivator.cpp, src/cpp/session/http/SessionNamedPipeHttpConnectionListener.hpp
On Win32 debug, the following pattern doesn't work:
```
Win32 call that sets an error (SetLastError)
Error error = systemError(::GetLastError(), ERROR_LOCATION);
```
The order of argument evaluation is not defined in C++ and on Win32 debug, at least, by the time ::GetLastError is called, the Win32 error code has been reset to zero, so the resulting `error` is set to an error code of zero (no-error). This leads to a variety of problems at runtime, including crashing failure of the rsession unit tests.
I opted to just manually change the calls to first store ::GetLastError in a variable which is then passed to systemError.
Doing it inside a new utility function would lose useful diagnostic information (ERROR_LOCATION would resolve to that function instead of the calling site), and a …
=> fix error handling on Win32 debug builds

src/cpp/desktop/DesktopMain.cpp
As per https://github.com/rstudio/rstudio/issues/1539, it looks like the issue with accessibility-aware rendering in Chromium causing lagginess in the IDE affects a number of users. Because of this, we should consider disabling this by default, but allowing users who require this functionality to re-enable it (by setting the `RSTUDIO_ACCESSIBILITY` environment variable)
=> disable accessibility by default

src/cpp/core/FilePath.cpp, src/cpp/core/r_util/RProjectFile.cpp, src/cpp/core/r_util/RToolsInfo.cpp, src/cpp/core/system/Win32System.cpp, src/cpp/core/system/file_monitor/FileMonitor.cpp, src/cpp/session/SessionClientEventService.cpp, src/cpp/session/SessionConsoleProcessSocketTests.cpp, src/cpp/session/SessionUserSettings.cpp, src/cpp/session/include/session/SessionConsoleProcessInfo.hpp, src/cpp/session/modules/SessionAsyncPackageInformation.cpp
MSVC build emits several hundred warnings. Fixing a few of them, just to start chipping away at the mountain. Mainly some type issues, and a few unused arguments in catches.
=> Fix a handful of build warnings on Windows

CMakeCompiler.txt
This warning complains about implicit casts to bool saying it has performance implications. It generated over 100 build warnings in our code, I previously fixed the handful that were genuine issues (barely), none of the rest are concerning. Microsoft removed this warning altogether in Visual C++ 2017, so I'm disabling it. This cuts about a third of our MSVC build warnings.
=> Disable MSVC C4800 warning

src/cpp/core/FileLockTests.cpp, src/cpp/core/FilePath.cpp, src/cpp/core/FilePathTests.cpp
This PR resolves an issue wherein, within the Files pane, the symlink target was shown rather than the symlink name itself.
This was a v1.2 regression caused by the Boost upgrade, wherein I switched our previous implementation of `relativePath()` to use the new `boost::filesystem::relative()` API. This was primarily prompted by our old implementation failing with gcc-5 and above. Unfortunately, `boost::filesystem::relative()` does a bit too much -- it also normalizes paths and resolves symlinks -- which is undesired in our usages of this function.
Resolves https://github.com/rstudio/rstudio/issues/2147.
=> avoid resolving symlinks in 'relativePath'

src/cpp/diagnostics/CMakeLists.txt
=> Fixup libssl linking of diagnostics on Mac desktop

src/cpp/core/system/Win32System.cpp
`GetVersionEx` is considered deprecated in Windows, replace with the new greatness (which is much tidier).
=> fix a couple deprecation warnings for Win build

src/cpp/session/modules/SessionRCompletions.R
This PR fixes an issue where we erroneously duplicated the contents of a completion vector, when its length had already been appropriately extended.
=> fix formation of completion vector (#2236)

src/cpp/session/modules/SessionRCompletions.R
When pressing `F1` to retrieve help for a topic, RStudio attempts to evaluate an R expression of the form:
help(topic = <topic>, package = <package>)
However, because we were not pairing help topics with their package when retrieving help autocompletion results, we were effectively attempting to evaluate
help(topic = <topic>, package = "")
Fixes https://github.com/rstudio/rstudio/issues/2261.
=> include package providing help topic

src/gwt/src/org/rstudio/core/client/MessageDisplay.java, src/gwt/src/org/rstudio/studio/client/common/DefaultGlobalDisplay.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/events/RenameSourceFileEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/Files.java, src/gwt/src/org/rstudio/studio/client/workbench/views/files/FilesTab.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
This small change makes it simple to rename the currently open file in the editor. The command for doing this is currently on the File menu, but could be moved to a document tab context menu if and when we implement one (see #1664). 
Closes #2199.
=> Implement rename in File menu

package/osx/make-package
This change makes two small improvements to building on macOS:
1. The GWT compiled sources are now stored in the build folder rather than the source folder. This means that it is possible to run a `make-package` build without stomping on an active `ant devmode`.
2. It is now possible to run `make-package` from any directory to produce a build in that directory; you can build outside the source tree (as is already possible on Linux).
=> Allow building macOS package outside build folder

src/cpp/desktop/CMakeLists.txt, src/cpp/session/CMakeLists.txt
Fixes #2197
Use CMake `InstallRequiredSystemLibraries` to bundle 32-bit and 64-bit runtime DLLs with RStudio.
This embeds the DLLs right in the package, versus separately installing and running `vcredist_x64.exe` and `vcredist_x86.exe`. So, we know the versions being shipped are the ones we built with, but we don't get automatic updates of these DLL's via windows-update. Pros and cons to that.
=> Include MSVC runtimes with RStudio

src/cpp/session/CMakeLists.txt
Fixes https://github.com/rstudio/rstudio/issues/2313.
I tried to see if there was some way to link to `libR.dylib` without actually having that library (+ its path) show up as a dependency on the `rsession` executable, but didn't have any luck.
=> force rsession to look in dummy path for libR

src/cpp/RScriptCallbacks.hpp, src/cpp/r/CMakeLists.txt, src/cpp/r/include/r/session/RSession.hpp, src/cpp/r/include/r/session/RSessionUtils.hpp, src/cpp/r/session/RInit.cpp, src/cpp/r/session/RInit.hpp, src/cpp/r/session/RQuit.cpp, src/cpp/r/session/RQuit.hpp, src/cpp/r/session/RScriptCallbacks.cpp, src/cpp/r/session/RScriptCallbacks.hpp, src/cpp/r/session/RSession.cpp, src/cpp/r/session/RStdCallbacks.cpp, src/cpp/r/session/RStdCallbacks.hpp, src/cpp/r/session/RSuspend.cpp, src/cpp/r/session/RSuspend.hpp, src/cpp/rstudio-tests.in, src/cpp/session/SessionMain.cpp, src/cpp/session/SessionOptions.cpp, src/cpp/session/include/session/SessionConstants.hpp, src/cpp/session/include/session/SessionOptions.hpp, src/cpp/session/modules/SessionConsole.cpp, src/cpp/tests/testthat/test-lists.R
This change was made in order to support testing on a new 1.2 feature. It makes it possible to run tests against the R session executable, `rsession`, using the R package testthat.
The new tests complement the existing C++ unit tests (written in Catch). They are most useful for the following:
- Testing the .R code which supports the various session modules.
- Testing the R session from outside, as a black box in real-world conditions.
- Writing test scripts in R.
To make this possible, the R session gains a new parameter, `--run-script`. This new parameter causes the R session to behave very much like R does with `-e`; that is, it starts up normally, runs the R code given, and exits. In this mode, it also outputs to stdout rather than emitting console events. 
After this change, the R …
=> Expose R session to testthat

src/cpp/desktop/DesktopActivationOverlay.cpp, src/cpp/desktop/DesktopActivationOverlay.hpp, src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopSessionLauncher.cpp
Add method to return name of product shown in title bar and error message titles. This will be overridden in Pro desktop.
There is already an "editionName" in the GWT code, available via `ProductEditionInfo.editionName`, but we needed a native desktop variant (we show UI needing this string before loading the GWT frame, so can't ask via Javascript).
=> Centralize source of desktop product name string

src/gwt/src/org/rstudio/core/client/AnsiCode.java, src/gwt/src/org/rstudio/core/client/VirtualConsole.java, src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
Fixes #2248
The RStudio console only supports color/font/appearance ANSI codes (SGR codes), and if other ANSI codes are sent to the console, it swallows all the output while waiting for those codes to somehow become SGR codes. Which they won't.
Fix by more specifically detecting SGR codes, and handling them, while discarding unsupported codes.
Added unit tests for this scenario.
=> Strip unsupported ANSI codes from Console output

src/cpp/desktop/DesktopMain.cpp
Fixes for #2203 and #2205. Project code assumes the last argument is the project name; therefore, this fix avoids appending more arguments at the very end. Somewhat related to https://github.com/rstudio/rstudio/commit/4350d5ea81c64b9d3f35d6a1deb9f42ee1f5012b but hard to catch since the relationship to the position was non-trivial.
=> Fix opening project file in osx to fix #2203 and fix #2238

src/cpp/core/FileSerializer.cpp, src/cpp/core/FileUtils.cpp, src/cpp/core/StringUtils.cpp, src/cpp/core/Win32StringUtils.cpp, src/cpp/core/http/Request.cpp, src/cpp/core/http/Response.cpp, src/cpp/core/http/Util.cpp, src/cpp/core/include/core/http/Response.hpp, src/cpp/core/include/core/libclang/UnsavedFiles.hpp, src/cpp/core/include/core/r_util/RSourceIndex.hpp, src/cpp/core/libclang/SourceIndex.cpp, src/cpp/core/libclang/UnsavedFiles.cpp, src/cpp/core/system/Crypto.cpp, src/cpp/core/system/RegistryKey.cpp, src/cpp/core/tex/TexLogParser.cpp, src/cpp/r/include/r/session/RConsoleHistory.hpp, src/cpp/session/SessionConsoleProcessPersist.cpp, src/cpp/session/SessionConsoleProcessSocket.cpp, src/cpp/session/modules/SessionCodeSearch.cpp, src/cpp/session/modules/SessionRCompletions.cpp, src/cpp/session/modules/SessionSource.cpp, src/cpp/session/modules/build/SessionBuild.cpp, src/cpp/session/modules/rmarkdown/NotebookDocQueue.cpp, src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp, src/cpp/session/modules/tex/SessionSynctex.cpp, src/cpp/session/modules/viewer/ViewerHistory.cpp
64-bit MSVC rsession build was generating 2000+ warnings. This change gets it down to around 300-ish, largely due to fixes in headers.
As before, mainly static_casts to make implicit conversions explicit (conversions with theoretical data loss, typically size_t to int). Too much work to evaluate switching to size_t types vs ints, but also don't want to turn off the warning as it can catch real problems.
=> Fix win32 warnings (64-bit build)

src/cpp/session/CMakeLists.txt, src/cpp/session/SessionClientInit.cpp, src/cpp/session/SessionConsoleProcessSocket.cpp, src/cpp/session/SessionConsoleProcessSocketPacket.cpp, src/cpp/session/SessionOptions.cpp, src/cpp/session/include/session/SessionConsoleProcessSocket.hpp, src/cpp/session/include/session/SessionConsoleProcessSocketPacket.hpp, src/cpp/session/include/session/SessionConstants.hpp, src/cpp/session/include/session/SessionOptions.hpp, src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSession.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSessionSocket.java, src/gwt/src/org/rstudio/studio/client/workbench/views/terminal/TerminalSocketPacket.java
Proxies can be configured to close inactivate websocket connections. This can lead to error messages showing in the console (in the case of .cloud), and possibly other issues.
Now Terminal websockets will send a 1 character "ping" followed by the server sending back a 1 character "pong", to reassure proxies that the websocket is still in use. Both directions, as proxies can be configured to pay attention to one or both directions.
Default interval is 10 seconds (per each terminal connection). Can be changed or disabled with `websocket-ping-seconds=n`. Only done for Terminal websockets, but concept (and the setting) could be extended to other uses of WebSockets in the product.
Using a super-sophisticated packet format, to keep overhead minimal. If the first character of a terminal …
=> WebSocket keep-alive pings for terminal

src/cpp/desktop/DesktopMain.cpp
This is a regression in Qt 5.10.1. The temporary workaround is to include --no-sandbox argument.
Fixes #2378 
Fix checked in to Qt 5.11 and 5.9.5, but no word yet if it will be fixed for 5.10.1. See this bug to track that:
https://bugreports.qt.io/browse/QTBUG-66346
=> Fix for Qt 5.10.1 bug where RStudio crashes on startup on Linux

src/cpp/session/modules/SessionWorkbench.hpp
All other uses of msysSshPath() were inside #ifdef _WIN32 except this one.
Fixes #2352
=> Don't add Win32-specific msys-ssh to subprocess paths

src/gwt/src/org/rstudio/studio/client/workbench/views/environment/EnvironmentPresenter.java
Upon opening a .RData file, my student (a beginner in R) was
presented with the question "Do you want to load the R data file
into the global environment?" and understood it to mean that the
data would be uploaded to a public data repository.
By changing "the global environment" to "your global environment",
such confusion can hopefully be avoided. Further, the change from
"the" to "your" is consistent with the previous phrase in the
dialog, which was "your workspace". I believe the main intent of
db72a278 was to change "workspace" to "environment".
Thanks to Riley Bailey for the report and suggestion.
An alternative phrasing could be "your session's global environment".
=> Rephrase a dialog for better clarity to beginners

src/cpp/core/CMakeLists.txt, src/cpp/core/include/core/system/Win32RuntimeLibrary.hpp, src/cpp/core/system/Win32RuntimeLibrary.cpp, src/cpp/r/RUtil.cpp, src/cpp/r/include/r/RUtil.hpp, src/cpp/session/modules/SessionRUtil.cpp, src/cpp/session/modules/SessionSource.cpp
This should fix #2315.
---
Some background: it looks like `Riconv.dll` imports `msvcrt.dll`, and uses `_errno` from there. On the other hand, `rsession` is getting it from a different runtime altogether: `api-ms-win-crt-runtime-l1-1-0.dll`, which I believe is required for applications built with MSVC 2015 + Qt.
One alternative way of approaching this would be to attempt to link directly with `msvcrt.dll`, but I'm not sure if this would work with MSVC + Qt (although this may be worth exploring if we're not a fan of this solution).
We might want to wrap this up into something cleaner, and make it clear that when calling R APIs that set `errno` we need to explicitly grab it from `msvcrt.dll`.
=> ensure errno loaded from msvcrt when checking iconv success

src/cpp/desktop/DesktopMain.cpp, src/cpp/desktop/DesktopWebPage.cpp
This change fixes #1953, in which auto-hide scrollbars don't actually auto-hide on macOS (they are always visible).
The actual issue is fairly deep inside Chromium. Overlay scrollbars are painted on a second painting pass so that they're painted on top of other UI. However, this second pass does not occur when using the compositor, because the compositor defines a separate layer for scrollbar painting. Unfortunately the alpha animation that shows and hides the scrollbar is only painted during this 2nd pass, so using the compositor causes the animation to run but not paint, with the result that the scrollbar gets stuck in the fully opaque state.
The fix here is more of a workaround. Chromium has a preference which allows you to choose whether you'd prefer better text rendering (LCD text …
=> Fix issue with persistent scrollbars on macOS

src/cpp/desktop/DesktopOptions.cpp, src/gwt/src/org/rstudio/core/client/theme/ThemeFonts.java
This PR should fix https://github.com/rstudio/rstudio/issues/2266, and should also help ensure that, in the case where a user has specified a font that may no longer exist or is not loadable for another reason, we fall back to an appropriate font.
=> provide fallback fonts

src/cpp/CMakeLists.txt
Closes #2346. Will be useful when Ubuntu 18.04 is released and compilation is attempted there (e.g. for dev machines)
=> enable more warnings with new gcc

src/cpp/rstudio-tests.in
On my Mac, with stock bash (4.4.12), `rstudio-tests --help` gave this error:
```
gary@Garys-MacBook-Pro:~/rstudio/build$ ./rstudio-tests --help
Runs RStudio unit tests. Available flags:
./rstudio-tests: line 32: printf: --: invalid option
printf: usage: printf [-v var] format [arguments]
./rstudio-tests: line 33: printf: --: invalid option
printf: usage: printf [-v var] format [arguments]
./rstudio-tests: line 34: printf: --: invalid option
printf: usage: printf [-v var] format [arguments]
```
=> fix rstudio-tests script so --help works

src/gwt/src/org/rstudio/studio/client/common/filetypes/PythonFileType.java
In at least one instance this actually breaks the code by overindenting if statements (possibly a bug in the Ace Python autoindenter?): https://raw.githubusercontent.com/datalogue/keras-attention/master/models/tdd.py
Note that there are other code oriented commands that should probably also be disabled for Python files:
@kevinushey
=> don't reindent python code on paste

src/cpp/core/GitGraph.cpp, src/cpp/core/HtmlUtils.cpp, src/cpp/core/ProgramOptions.cpp, src/cpp/core/include/core/GitGraph.hpp, src/cpp/core/system/ChildProcessSubprocPoll.cpp, src/cpp/core/system/Environment.cpp, src/cpp/session/modules/SessionTerminalShell.cpp
- replace BOOST_FOREACH's with range-based for (they burn my eyes but will wait for start of 1.3 for a global replacement of these)
- remove unnecessary #includes
- in ChildProcessSubprocPoll, use const& iterators in whitelist checking to reduce object copies in nested loop
- auto for some iterator variables
- raw string literal for a regex string
- NULL to nullptr
- emplace_back to construct strings in place when adding "..." to a vector<string>
=> Minor mechanical C++11-isms on a handful of source files

src/gwt/src/org/rstudio/core/client/VirtualConsole.java, src/gwt/test/org/rstudio/core/client/VirtualConsoleTests.java
Fixes #2387
Off-by-one boundary issue with VirtualConsole will create empty spans in this situation, which prevents proper handling of \r.
This is finicky code, but lots of unit-test coverage, and I added more for this scenario.
FYI @gaborcsardi
=> Fix issue with console carriage-return processing mixed with ANSI codes

src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/cpp/session/SessionClientInit.cpp, src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/model/SessionInfo.java
This PR commits one of the cardinal sins: it teaches the client-side what the user's home path is. In this case, it's necessary to do so as otherwise we're stuck threading through a lot of asynchronous code into codepaths that are otherwise synchronous, or we take on the task of figuring out a way to thread client-side aliased paths into window opening APIs (which feels rather dicey).
Teaching the client-side the user's home directory for this particular usage seemed like the lowest-friction way of resolving.
Fixes https://github.com/rstudio/rstudio/issues/2440, https://github.com/rstudio/rstudio/issues/2156.
=> fix opening of files on desktop

src/cpp/desktop/DesktopWebView.cpp
This PR ensures that we always show Cut / Copy / Paste in the context menu, but toggle the command enabled-ness based on whether there is some selected text (and that text is writable), or whether there is anything paste-able on the clipboard.
I think this is better than simply hiding the commands as it keeps the size + structure of the context menu more consistent, and the Paste command looks rather lonely when it's the only entry in the context menu.
Note that 'Reload' and 'Inspect Element' are still only shown in development configurations.
=> toggle enabledness of cut/copy/paste according to context

src/cpp/session/modules/build/SessionBuildErrors.cpp
Fix for https://github.com/rstudio/rstudio/issues/2483 to support warnings and infos as well:
=> Use appropriate source markers for different test results

src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.css, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java
This PR ensures that the dialog elements for the RStudio Connect dialog are nicely aligned.
Before:
After:
=> tweak rsc deploy dialog for desktop

src/cpp/desktop/DesktopGwtWindow.cpp, src/cpp/desktop/DesktopGwtWindow.hpp, src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopMainWindow.hpp, src/cpp/desktop/DesktopSatelliteWindow.cpp, src/cpp/desktop/DesktopSatelliteWindow.hpp, src/cpp/desktop/DesktopWebView.cpp, src/cpp/session/SessionHttpMethods.cpp, src/gwt/src/org/rstudio/core/client/command/AppCommand.java, src/gwt/src/org/rstudio/studio/client/application/Desktop.java
On macOS, Cmd+W is overloaded. In the main window and source windows, it closes source documents. In other windows, *and* in the main window/source window when no docs are open, it closes the whole window.
This has been broken since the QtWebEngine transition. Fixing it turned out to involve solving three problems.
Because our `WebView::event` override delegates directly to `QtWebEngineView`, our `keyEvent` handler never gets called. Now, we check for an override event, and on macOS we take the opportunity to implement our own Qt key handling.
We use `isDesktop()` all over the place, but it relies on `window.desktop` being present. In QtWebEngine, that object is now injected asynchronously and may not be available during GWT startup. Consequently, some code that runs on startup thinks …
=> Fix issues with Cmd+W on macOS

src/cpp/desktop/DesktopWin32ApplicationLaunch.cpp
Fixes https://github.com/rstudio/rstudio/issues/2502.
I have to admit I don't quite understand the mechanics around application / window launching on Windows -- hopefully someone else would be able to explain the whole ApplicationLaunch mechanism used here?
=> ensure RStudio window activated on launch

src/cpp/core/include/core/system/System.hpp, src/cpp/core/system/PosixChildProcess.cpp, src/cpp/core/system/PosixSystem.cpp
Fixes #2470.
Now only explicitly closing the files that are open in the child process instead of attempting to close all of them up to max fd. This is accomplished in a signal-safe way by having the parent process gather the actual pids, then sending them via pipe to the child (::read is signal safe). The unsafe implementation simply fetches the fds itself instead of relying on the parent to deliver them.
=> Fix slow forking when ulimit for open files is high

src/cpp/desktop/DesktopGwtCallback.cpp
Closes #2137.
With Qt Webkit, we were able to rely on the `onCloseRequested()` slot for web views (or so it seems? I can't actually find that documented anywhere, now...).
Fortunately, we can still signal the request for the window to close by just hooking up the parent window's `destroyed()` signal to a close call.
=> ensure minimal windows closed when parent window closes

src/cpp/desktop/DesktopBrowserWindow.cpp, src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtWindow.cpp, src/cpp/desktop/DesktopGwtWindow.hpp, src/cpp/desktop/DesktopInfo.cpp, src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopMainWindow.hpp, src/cpp/desktop/DesktopWebView.cpp, src/cpp/desktop/DesktopWebView.hpp
Fixes #2523.
Note that I removed some of the 'DPI-aware zoom factor' bits as this should no longer be necessary with QtWebengine (this was a workaround for DPI-related behaviors in Webkit)
=> ensure zoom factor synchronized after zoom

src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
While connecting with `odbc` we recommend using `rstudioapi::askForPassword()`; however, we don't really prompt users to install `rstudioapi` from the connection dialog. While we don't want to force a particular version of rstudioapi, we should at least recommend installing the same version we recommend for shiny addins and rsconnect which is version `0.5`.
`askForPassword()` was added back in version `0.4`, https://github.com/rstudio/rstudioapi/commit/e2c20ef8c3b810ff43c7bf86562f7f0294098334.
CC: @ronblum
=> Add rstudioapi as a dependency for odbc connections

src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java
This makes the help pane's "Show in new window" button work like it did in 1.1 and open in a minimal Qt browser window. Each time you click it a new instance is created, hence the name+counter; otherwise it would just reactivate the same window on subsequent clicks.
Fixes #2117
=> Fix Help pane popout button on desktop

src/cpp/desktop/DesktopBrowserWindow.cpp, src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopSatelliteWindow.cpp, src/gwt/src/org/rstudio/core/client/command/AppCommand.java, src/gwt/src/org/rstudio/core/client/command/impl/DesktopMenuCallback.java, src/gwt/src/org/rstudio/core/client/dom/WindowEx.java, src/gwt/src/org/rstudio/studio/client/application/Desktop.java, src/gwt/src/org/rstudio/studio/client/common/satellite/Satellite.java, src/gwt/src/org/rstudio/studio/client/workbench/MainWindowObject.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/SourceWindowManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
This PR fixes a few issues:
1. Rather than having a single web channel on the main window that all windows share, each window now gets its own web channel that it can use to communicate with the Qt backend. This ensures that attempts to show dialogs (e.g. message boxes) can show with the window from which they were requested, thereby fixing https://github.com/rstudio/rstudio/issues/2516.
2. On macOS, when a command is invoked from the main menu, it is always invoked from the main window. However, we typically want to target the behavior to the last active (or currently active) window; e.g. for source editor commands that should operate on the current window. We hence also allow the main menu to request that satellites execute a command.
3. We also need to more aggressively manage commands …
=> ensure commands are fired to associated window

src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/ConsoleLanguageTracker.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
This fixes an issue where attempts to execute a chunk while the `reticulate` REPL is active could fail (as the process believes the R session is otherwise busy and just hangs waiting for R to return to the top level)
=> ensure reticulate REPL deactivated when executing notebook chunks

package/linux/rpm-script/postinst.sh.in
This PR seeks to resolve https://github.com/rstudio/rstudio/issues/2139. We source the contents of `/etc/os-release`, and use the `VERSION_ID` variable to detect OpenSUSE + its version.
=> use /etc/os-release when available on OpenSUSE

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkOutputWidget.java
Closes https://github.com/rstudio/rstudio/issues/2174.
Note that this does tweak the scroll behavior for HTML widgets in Notebooks: widgets no longer unilaterally propagate wheel events; rather, they only propagate them when they have reached their scroll bounds and cannot be scrolled anymore.
(I initially wanted to test this by looking at e.g. the height of the iframe, but that was always reported as 0 -- or perhaps I'm misunderstanding some interplay between how an iframe's scroll position is reported)
=> clamp htmlwidget height; tweak propagation of wheel events

src/cpp/core/CMakeLists.txt, src/cpp/server/CMakeLists.txt
A solution for #2558.
`-I/opt/local/include` gets passed correctly and results in a successful build.
```
[ 54%] Building CXX object src/cpp/core/CMakeFiles/rstudio-core.dir/http/SocketProxy.cpp.o
cd /Users/kiwiroy/code/rstudio/compilation-dir/src/cpp/core && /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DBOOST_ASIO_DISABLE_KQUEUE -DBOOST_ENABLE_ASSERT_HANDLER -DBOOST_SIGNALS_NO_DEPRECATION_WARNING -DRSTUDIO_BOOST_NAMESPACE=rstudio_boost -DWEBSOCKETPP_STRICT_MASKING -D_WEBSOCKETPP_NO_CPP11_MEMORY_=1 -isystem /opt/rstudio-tools/boost/boost_1_63_0/include -I/opt/local/include -I/Users/kiwiroy/code/rstudio/src/cpp/core/include -I/Users/kiwiroy/code/rstudio/compilation-dir/src/cpp/core -I/Users/kiwiroy/code/rstudio/src/cpp/tests/cpp  -std=c++0x …
```
=> Cure for macOS build using macports openssl 1.0.2n

src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopSessionLauncher.cpp, src/cpp/desktop/DesktopUtils.cpp
Fixes #2570 
I had removed these on the native Pro dialogs, but missed these open-source variants.
=> Hide context help control on Windows dialogs

src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java, src/gwt/src/org/rstudio/studio/client/application/ui/RStudioThemes.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
This PR alleviates the issue described in https://github.com/rstudio/rstudio/issues/2150, so that the default background color is set during resize.
=> match background color to theme (closes #2572)

src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/EditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/profiler/ProfilerEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/urlcontent/UrlContentEditingTarget.java
In order to default to source on save for d3 scripts I added an EditingTarget method to set the property. For whatever reason in the editing target I had to set both the view and the model (perhaps b/c the view event listener that normally syncs to the model isn't yet active?).
This seems to work fine, but it mildly bugs me that I have to set both the model and view. I don't think it's worth a refactor to improve this, but I'm wondering if I missed something and there is a simpler solution. @jmcphers Let me know what you think.
=> default to source on save for d3 scripts

src/cpp/session/modules/SessionRMarkdown.R, src/cpp/session/modules/rmarkdown/RMarkdownTemplates.cpp
This change fixes an issue wherein every session of RStudio has the `yaml` package loaded (even if the user has just restarted R and has done nothing related to R Markdown or yaml).
The `yaml` package is loaded to parse R Markdown template metadata in each installed package. We have a lazy indexer which looks for these files at startup, parses them, and adds them to a global cache. This is necessary because some pathological setups have thousands of packages installed, so without some prefetching it takes unacceptably long to retrieve the set of templates.
To avoid loading the `yaml` package on startup, this is now a two-phase step:
1. The indexer no longer parses YAML; its job is only to *locate* the YAML files. On pathological configurations this is the slow phase.
2. When R Markdown …
=> Avoid loading the 'yaml' package on boot

src/cpp/session/modules/SessionAskSecret.R
Need a workaround for https://github.com/r-lib/keyring/issues/48 until we get an update on CRAN. Currently, `askForSecret()` does not remember secrets under Windows.
=> Keyring workaround for Windows

src/cpp/session/modules/SessionRMarkdown.R, src/cpp/session/modules/SessionRmdNotebook.R
We would like to support `data` expressions in alternate engines to match `knitr` behavior, as in:
``````
```{d3 data=c(10,20,30), options='orange'}
svg.selectAll('rect')
.data(data)
.enter()
.append('rect')
.attr('width', function(d) { return d * 10; })
.attr('height', '20px')
.attr('y', function(d, i) { return i * 22; })
.attr('fill', options);
```
``````
See also: https://github.com/rstudio/r2d3/issues/5
=> Add support for expressions in alternate notebook engines

src/cpp/session/modules/SessionConnections.R
Some ODBC drivers might need to trigger OS specific warnings to install specific components, this adds this functionality by adding to the DCF:
```
Warning.windows: Install additional windows components.
Warning.unix: Install additional unix components.
```
=> Add support for os specific odbc installer warnings

src/cpp/r/R/Api.R
While working with `D3`, would be nice to support rendering visualizations based on editor themes by using a header similar to:
```
// !preview r2d3 data=read.csv(system.file("samples/bubbles/flare.csv", package = "r2d3")), d3_version=4, options=rstudioapi::getThemeInfo(), sizing=htmlwidgets::sizingPolicy(padding=0)
```
=> Add colors to getThemeInfo api to support better visualizations

src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java
Follow up to https://github.com/rstudio/rstudio/pull/2653 to:
1) Support signaling viewers that the `openfile` message is available.
2) As part of signaling, give the origin domain to allow cross-site message from a different domain/port hosting the widget.
=> Support signaling viewer pane for openfile message

src/gwt/src/org/rstudio/core/client/CodeNavigationListener.java, src/gwt/src/org/rstudio/studio/client/RStudioGinModule.java, src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java, src/gwt/src/org/rstudio/studio/client/htmlpreview/HTMLPreviewPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/ViewerPresenter.java
`htmlwidgets` just added support with [/htmlwidgets/pull/308](https://github.com/ramnathv/htmlwidgets/pull/308) to open widgets in their own window, which we would also like to support in D3. This PR refactores the open file message functionality from the Viewer Pane and makes it available in HTML preview windows as well.
=> Support opening errors from D3 from external window

src/gwt/src/org/rstudio/core/client/HtmlMessageListener.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkHtmlPage.java
Themes can also change in notebooks in which case we need to notify all the frames of the theme update for all D3 renderings to update correctly.
=> Support changing d3 themes in notebooks

src/cpp/session/modules/build/SessionBuild.cpp
While testing a single `testthat` file under a project, `testthat::test_file()` works but the UI entry in the file does not. Previous testing of this feature was performed outside a project where one is expected to manually include the library, this fix parses the project only for `testthat` files and fixes an old merge conflict.
=> Attempt to parse package from testthat file

src/cpp/session/modules/SessionTests.cpp
The following pattern not recognized by `testthat` files...
```r
context("render")
source("utils.R")
render_r2d3_barchart <- function(...) {
r2d3(data=c(0.3, 0.6, 0.8, 0.95, 0.40, 0.20), script = "barchart.js", ...)
}
test_succeeds("r2d3 can render visualizations", {
render_r2d3_barchart()
})
```
Mostly, since `test_that(` is used indirectly through a `test_succeeds` helper function. However, using `context("` at the very top and `test_` methods is a common pattern we can use to identify use cases like this one.
=> Support for additional testthat file detection patterns

src/cpp/desktop/CMakeLists.txt, src/cpp/desktop/DesktopComUtils.cpp, src/cpp/desktop/DesktopComUtils.hpp, src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/cpp/desktop/DesktopGwtCallbackMac.mm, src/cpp/desktop/DesktopOfficeViewer.cpp, src/cpp/desktop/DesktopOfficeViewer.hpp, src/cpp/desktop/DesktopPowerpointViewer.cpp, src/cpp/desktop/DesktopPowerpointViewer.hpp, src/cpp/desktop/DesktopWordViewer.cpp, src/cpp/desktop/DesktopWordViewer.hpp
This change makes it easier to use R Markdown to iterate on Powerpoint slide decks. When a Powerpoint document is re-rendered, the selected slide is saved, the deck is reopened, and the slide is selected again. It's thus possible to iterate on changes to a single slide, even one many slides into the deck, by re-rendering the document.
The change is not quite as large as it looks; most of the churn is caused by some refactoring of the Windows version of the change, as 80% of the code that syncs the Word scroll position is reusable for syncing the Powerpoint slide selection.
=> Implement iterative Powerpoint workflow

src/gwt/src/org/rstudio/studio/client/htmlpreview/HTMLPreview.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RmdPreviewParams.java
Screen and web pages have become wider since we set this default
=> Change Rmd preview to 1180px by default (was 1100px)

src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionShinyHost.java
Avoids package creators to have to hardcode fonts for shiny-based connection extensions.
=> Inject fonts and basic styles to shiny connections

dependencies/linux/install-dependencies-debian, dependencies/linux/install-dependencies-yum, docker/jenkins/Dockerfile.centos6-x86_64, docker/jenkins/Dockerfile.debian9-x86_64, docker/jenkins/Dockerfile.trusty-amd64, package/linux/CMakeLists.txt
QtWebKit, our browser engine in RStudio 1.1, depended on `libgstreamer`. (This was very inconvenient and eventually required us to produce a custom Qt build against `libgstreamer-1.0` as newer Linux distributions didn't provide a package for `libgstreamer-0.10`, against which Qt had been built originally.) 
Thankfully, QtWebEngine does not depend on this library, so we no longer require it at build time or runtime. This change removes it from our setup scripts, Docker build containers, and package dependencies. 
Closes #2716.
=> Remove build and runtime requirements for libgstreamer

src/cpp/desktop/DesktopUtilsMac.mm
Early in the move back to Qt on the Mac, was getting View menu items
related to native Mac tab support; this call was hiding those. The
property, however, was added in 10.12, so prevented building on 10.11.
Looking now, it seems the newer version of Qt we're using has fixed this
for us, so removing the call altogether.
Fixes #2693
=> remove unnecessary call to macOS 10.12 plus API

src/cpp/session/SessionOptions.cpp, src/cpp/session/include/session/SessionOptions.hpp, src/cpp/session/modules/SessionPackages.R, src/gwt/src/org/rstudio/studio/client/common/repos/SecondaryReposDialog.java, src/gwt/src/org/rstudio/studio/client/common/repos/SecondaryReposWidget.java, src/gwt/src/org/rstudio/studio/client/common/repos/model/SecondaryReposServerOperations.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
Notes:
- Some CRAN mirrors do not support `/package=name` URL. I found out the major mirrors do support this URL. As a CRAN mirror, you probably want to support this path anyways since it's recommended by CRAN, but not all mirrors do. I was considering a workaround for this, but seems this behavior it's fine.
=> Various fixes for package management feature

src/cpp/r/R/Tools.R, src/cpp/r/session/RSession.cpp, src/cpp/session/modules/SessionPackages.R
Some systems might not resolve relative URLs correctly while downloading files, instead, use C++ URL helper class to clean up URLs before downloading the secondary repos file in R.
=> Avoid relative urls while downloading secondary repos file to fix #2776

src/gwt/src/org/rstudio/studio/client/common/repos/SecondaryReposDialog.java
Minor fix for #2775 to avoid suggesting the primary repo in the secondary repos list.
=> Avoid suggesting the primary repo in secondary repos list to fix #2775

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
I'm guessing we screened out this option for Windows just because `bash` isn't available by default, but I think it makes sense to enable it.
I think most Windows users who will want to run `bash` chunks will do so with Git for Windows installed + its associated tools on the PATH.
=> allow insertion of Bash chunks on Windows (closes #2727)

src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
This PR allows users to enable / disable the restoration of the last known cursor position when source documents are opened.
=> allow users to toggle save/load of cursor pos (#2778)

src/cpp/r/R/Api.R, src/cpp/session/SessionClientEvent.cpp, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp, src/cpp/session/modules/SessionDataImportV2.R, src/cpp/session/modules/SessionDataPreview.R, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetSqlHelper.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/NewDocumentWithCodeEvent.java
This PR adds support for packages providing connection extensions to provide a custom action that creates and previews a SQL statement. For instance, one can use the `documentNew()` API to create a package with a new `SQL` action:
Which, when the action is triggered opens a SQL script document with the cursor on a given table for easy editing:
and automatically opens the SQL Results on the console pane:
=> Enable connection extensions to create SQL documents

src/cpp/session/modules/rmarkdown/SessionExecuteChunkOperation.hpp
This PR fixes an issue where attempting to run Bash chunks when using the Windows Subsystem for Linux could fail. This is effectively because WSL bash uses the prefix `/mnt/c/` for paths rather than `C:/`, and does not attempt to translate paths from `C:/` to the expected counterpart. (Note that Git Bash _does_ do this transformation)
We work around this by asking `bash.exe` what it believes the current path is from within the R temporary directory, and use that to construct a path that the particular flavor of `bash.exe` will understand.
Closes #2724.
=> make it possible to run bash chunks on Windows

package/win32/make-install-win64.bat, package/win32/make-package.bat
This PR places a Windows toolkit on the PATH for package builds, so that `rc.exe` can be easily discovered and things otherwise work as expected.
=> helper for package builds on Windows

src/cpp/core/system/Win32Pty.cpp, src/cpp/core/system/Win32System.cpp, src/cpp/session/SessionOptions.cpp
Fixes #2817
This has been somewhat non-deterministic. I'm seeing cases where Win32 `executablePath()` returns an empty string, leading to mistakes in locating the winpty.dll (and presumably other problems). Also problems running terminal with 64-bit rsession build in dev environment; hadn't tried that before, always used 32-bit.
Found some mention online that using `_pgmptr` for getting at full path of current executable can have issues if used early in startup, but it is safe to use `GetModuleFileName` early. So switched to that approach.
Added an error log if there is a failure to find winpty.dll.
Made the decision on using 32-bit or 64-bit winpty.dll a compile-time thing instead of runtime, since it's already known by virtue of which rsession.exe is being built.
=> Fix some issues with running terminal on 64-bit rsession (Windows)

src/gwt/src/org/rstudio/core/client/widget/DynamicIFrame.java
With `1.2.657` and heavy use of D3 chunks, satellite windows and a [chunk-piled bug now fixed](https://github.com/rstudio/rstudio/pull/2843), it was possible for the R2D3 widgets to hand the rsession; the UI was also hanging but not related to the rsession hand but rather for eagerly waiting for the htmlwidgets to load, this is probably worse with many D3 widgets but still, the `50ms` wait time was too fast. This change increases the wait time to `500ms` over the first couple seconds linearly to mitigate this hang.
=> Avoid eager wait hang when htmlwidgets fail to load

src/cpp/core/include/core/r_util/RProjectFile.hpp, src/cpp/core/r_util/RProjectFile.cpp, src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
The previous fix only handled files that were in website projects. However, it's possible (and even likely) that users will be authoring articles in subdirectories with their own projects which didn't work correctly prior to this fix.
=> correctly handing for files not in website projects

src/cpp/session/resources/templates/query.sql
After a session restart, first time a sample SQL script is run, it fails with error:
Problem is that `DBI` expect most connections to look like:
```r
conn <- DBI::dbConnect(RSQLite::SQLite())
DBI::dbSendQuery(conn = conn, "SELECT 1")
```
For the S3 methods to register properly, instead, this changes avoids lazy initialization in the connection using `force()`.
=> Support running sample sql query immediately after session restart

dependencies/common/.gitignore, dependencies/common/install-packages, dependencies/common/install-packages.cmd, src/cpp/session/CMakeLists.txt, src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
Remove r2d3 as embedded package, use CRAN package instead. Need to wait for r2d3 to be available in CRAN:
=> Use r2d3 from CRAN

src/cpp/core/include/core/r_util/RActiveSessions.hpp, src/cpp/session/SessionDirs.cpp, src/cpp/session/SessionMain.cpp
The issue was occurring because by default, sessions are not created to respect the directory override (by not setting the initial flag), and because the initial flag is cleared before client_init (fixed by setting working dir in SessionMain). Fixes #2861.
=> Reworked session default working directory logic to make it work properly across desktop, server, and server pro

src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp
Websites with an `output_dir` that wasn't `"."` were not previewing correctly. This PR uses `module_context::websiteOutputDir()` to apply the offset required for previews to work.
=> offset website preview dir using output_dir

src/gwt/src/org/rstudio/core/client/html/HTMLAttributesParser.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ImagePreviewer.java
Closes #2887. Previously, we never attempted to parse classes or identifiers in Markdown headers; attempts to parse those would throw a JavaScript exception. We implement that and we now also apply the parsed identifier + CSS class.
=> implement parsing for markdown classes, id

src/cpp/session/SessionMain.cpp, src/cpp/session/SessionUserSettings.cpp
This is older issue that reproes in RStudio Server 1.1 see #2864 and https://github.com/rstudio/rstudio-pro/issues/434
When the `r-cran-repos` option is set, `SessionUserSettings.cpp` still defaults to RStudio's CRAN repo, this is harmless in many cases. However,  as shown in #2864 and https://github.com/rstudio/rstudio-pro/issues/434, whenever the user preferences get refreshed, say by OKing the Global Preferences dialog, opening a new terminal or changing R versions, etc, we change the CRAN repo to the user settings value. This yields inconsistent behavior since some r sessions might start with some CRAN repo and some with other depending on when the terminal gets created or which operation is triggered in the r session.
The fix in `SessionUserSettings.cpp` is to prevent setting the …
=> Make r-cran-repos and user setting consistent

src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopMainWindow.hpp
This PR attaches a Windows event handler, listening for dialogs created by the `rsession` process. When such a dialog is created, we ensure that window is activated and brought to the front.
Fixes #2901. One thing worth discussing is whether we need to be more careful about which dialogs that R might create need to be brought to the front; I think it's okay to assume that all dialogs created from R are modal and require immediate user attention but perhaps I'm missing some cases where that might not be true (download dialogs?)
=> ensure dialogs created by R shown on top

src/cpp/session/SessionMain.cpp, src/cpp/session/SessionUserSettings.cpp, src/cpp/session/include/session/SessionUserSettings.hpp, src/cpp/session/modules/SessionWorkbench.cpp, src/gwt/src/org/rstudio/studio/client/common/mirrors/model/CRANMirror.java, src/gwt/src/org/rstudio/studio/client/common/repos/SecondaryReposWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.css, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialogResources.java
While https://github.com/rstudio/rstudio/pull/2754 added support to set CRAN settings from the preferences pane or with admin settings like `r-cran-repos` and `repos.conf`, it was lacking support for use cases where admin settings are applied and also preferences need to be changed.
The behavior of this PR was to show inconsistent settings in the UI when the admin settings where set, usually, displaying the default CRAN repo or the user selection (which was made consistent with https://github.com/rstudio/rstudio/pull/2891 but was not showing what the final CRAN setting was).
This PR makes the system defaults visible by showing them in the preferences pane.
This PR also fixes one regression:
- Ability to change order in secondary CRAN repos from the UI
and a bug fix:
- Allow admins to …
=> Support package manager admins setting preferences

src/cpp/r/RSexp.cpp, src/cpp/r/include/r/RSexp.hpp, src/cpp/session/modules/SessionRUtil.cpp, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
`.rs.readIniFile()` was missing to support nested structures to be properly called an `ini` file parser; while this feature is not required by the package management feature, better add support for this now that this is being heavily tested in case `.rs.readIniFile()` gets reused in the future.
Also fixing a repos preferences issue with reprex:
- Set `repos.conf`
- Clear user settings
- Restart session
- From preferences UI, remove secondary repos and revert to RStudio CDN
- Apply changes
Actual: Changes don't take effect until next session restart.
Expected: Changes to take effect.
=> Fix to package repos and support parsing inis with headers

src/cpp/session/modules/SessionConnectionsInstaller.R
Fix for https://github.com/rstudio/rstudio-pro/issues/443
=> Ignore errors in first regedit attempt in windows since it's expected to fail

src/cpp/r/R/Api.R, src/cpp/session/SessionConsoleProcessApi.cpp, src/cpp/session/include/session/SessionTerminalShell.hpp, src/cpp/session/modules/SessionTerminalShell.cpp
Optional `shellType` argument to specify shell type via `terminalCreate`. The `rstudioapi` package will be updated to support this.
The shellType argument is a string and can be:
- **NULL** (default, uses shell type selected in Global Options, i.e. current behavior)
- **"default"**, same as NULL
- **"custom"**, Mac, Linux, Server: use "custom" shell specified in Global Options
- **"win-cmd"**, 64-bit Windows Command Prompt
- **"win-ps"**, 64-bit Windows PowerShell
- **"win-git-bash"** (Windows-only)
- **"win-wsl-bash"** (Windows-only)
Fixes #2903
If you request a shell type that isn't available, the default is used.
Example via rstudioapi and same thing using built-in RStudio syntax:
- `rstudioapi::terminalCreate(caption = "My Terminal", show = TRUE, shellType = "win-cmd")`
- …
=> Specify shell type via terminalCreate API

src/cpp/core/Settings.cpp, src/cpp/session/include/session/SessionUserSettings.hpp
This was being seen in both a Linux desktop build and a Windows desktop build.
Core problem was an uninitialized structure member `changed`; exception was from using lexical_cast without dealing with possibility of exception due to invalid input. Fixed to use our preferred core::safe_convert methods.
=> Fix "bad lexical cast" exception

src/cpp/core/http/Util.cpp, src/cpp/core/include/core/http/AsyncClient.hpp, src/cpp/core/include/core/http/Util.hpp, src/cpp/server/ServerSessionProxy.cpp
There were several places where we expected the websocket connection upgrade header `Connection` to have the exact value `Upgrade`. 
The standard, however, requires only that the header *include* the token `Upgrade`, and Firefox includes other values in the header (see #2940 for @jcheng5 's explanation of why this is a problem). 
This change brings the implementation in line with the standard.
Fixes #2940.
=> Tolerate other tokens in Connection header when upgrading to a websocket

CMakeGlobals.txt
CMake will let you compile RStudio against very old versions of R we no longer support; this ensures compilation is happening with at least R 3.0.1.
=> Update minimum R version

src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildPresenter.java, src/gwt/src/org/rstudio/studio/client/workbench/views/buildtools/BuildTab.java
Found out that the first time running after opening a project and not clicking the build pane, testing a file did not work since the build pane is not loaded yet and the test data is discarded.
CC: @ronblum
=> Fix testing a file after opening a project

dependencies/linux/install-qt-sdk, dependencies/osx/install-qt-sdk-osx
The online Qt installer puts Qt under `~/Qt/5.10.1`, but the dependency scripts for Mac and Linux were only checking for the offline installer location (`~/Qt5.10.1`). Fix to check for the same variations that the Windows dependency script already supports.
=> Prevent redundant Qt install on Mac / Linux

Jenkinsfile, docker/jenkins/Dockerfile.opensuse15-x86_64
OpenSUSE 15 was [released a few weeks ago](https://itsfoss.com/opensuse-leap-15/). It's not currently possible to run RStudio on OpenSUSE 15 without compiling from sources, primarily due to OpenSSL locations and versions. 
We formerly had an RPATH-based system to symlink libssl on SuSE, but that system hadn't adapted to the way the version is declared in OpenSUSE 15. Even if it had, symlinking wouldn't work -- OpenSUSE 15 bundles only libssl 1.1, which is [very, very ABI incompatible](https://abi-laboratory.pro/tracker/timeline/openssl/) with libssl 1.0, which is what most of our builders use. 
This change adds an OpenSUSE 15-specific build to our matrix. 
Closes #2606.
=> Start producing RStudio builds for OpenSUSE 15

src/cpp/r/include/r/RRoutines.hpp
This PR uses C++11 features to automatically deduce the number of functions accepted by a function, for use with call method registration. This should allow us to avoid bugs that result when the number of arguments in the registered function changes but the associated registration change is missed.
=> automatically deduce number of arguments when registering methods

src/cpp/session/modules/SessionDataPreview.R, src/cpp/session/resources/templates/query.sql, src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java
Fix for https://github.com/rstudio/rstudio/issues/2956 to support SQL preview in ODBC connections and avoid using `force()` in sample SQL code but rather implement this in the `previewSql` API.
=> Use odbc package version with SQL preview support

src/gwt/src/org/rstudio/studio/client/common/rstudioapi/ui/AskSecretDialog.java
Fix for https://github.com/rstudio/rstudio/issues/2906 by clearing the keyring password field on keydown to fix and also select all by default to indicate value will be overridden.
=> Clear keyring password field on keydown to fix #2906

src/cpp/r/R/Tools.R, src/cpp/r/include/r/session/RSession.hpp, src/cpp/r/include/r/session/RSessionUtils.hpp, src/cpp/r/session/RInit.cpp, src/cpp/r/session/RSession.cpp, src/cpp/session/SessionMain.cpp, src/cpp/session/SessionOptions.cpp, src/cpp/session/SessionUserSettings.cpp, src/cpp/session/include/session/SessionOptions.hpp, src/cpp/session/include/session/SessionUserSettings.hpp, src/cpp/session/modules/SessionPackages.cpp, src/cpp/session/modules/SessionWorkbench.cpp, src/cpp/session/modules/build/SessionInstallRtools.cpp, src/gwt/src/org/rstudio/studio/client/common/mirrors/model/CRANMirror.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
Fix for https://github.com/rstudio/rstudio/issues/2978.
Previously, we upgraded the `URL` user setting to store the CRAN repo and secondary repos. While this works fine in 1.2, RStudio 1.1 tries to read this `URL` which is not understandable. The fix is to leave the `cranMirrorUrl` field as it was, but introduce a new `cranMirrorRepos` user setting to store only the secondary repos.
There is also code to upgrade the RStudio 1.2 release bits that make use of the enhanced URL field.
=> Store repos in repos setting to allow rstudio 1.1 to open cran settings to fix #2978

src/cpp/desktop/DesktopWebPage.cpp, src/cpp/desktop/DesktopWebPage.hpp, src/cpp/desktop/DesktopWebProfile.cpp, src/cpp/desktop/DesktopWebProfile.hpp
This is a second attempt at fixing #2756. The main difference here is that we're now careful to make sure the last intercepted URL is indeed associated with the attempted URL for navigation, and we deny attempts to load external URLs in iframes.
=> disallow attempts to open external URLs in iframes (closes #2756)

src/cpp/session/modules/SessionJobs.R, src/cpp/session/modules/jobs/Job.cpp, src/cpp/session/modules/jobs/Job.hpp, src/cpp/session/modules/jobs/JobsApi.cpp, src/cpp/session/modules/jobs/JobsApi.hpp, src/cpp/session/modules/jobs/ScriptJob.cpp, src/cpp/session/modules/jobs/SessionJobs.cpp, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/model/Job.java, src/gwt/src/org/rstudio/studio/client/workbench/views/jobs/view/JobsPane.java
Implement suggestion in https://github.com/rstudio/rstudio/issues/2985, what do you think, @jmcphers?
=> Add support for `show` parameter in jobs API to fix #2985

src/cpp/session/modules/SessionRCompletions.R, src/cpp/session/modules/SessionRMarkdown.R
This PR ensures that we re-mark the encoding of the document contents before passing it down to `knitr::knit_params()`. This fixes issues that occur when the document params cannot be represented in the current encoding.
(Some additional work is required in `knitr` to ensure arbitrary UTF-8 content can be handled on Windows)
=> mark UTF-8 encoding when extracting params

src/cpp/desktop/DesktopPosixApplicationLaunch.cpp, src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java, src/gwt/src/org/rstudio/core/rebind/command/ShortcutsEmitter.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
This PR fixes an issue where attempts to use <kbd>Shift + Tab</kbd> to shift focus to the previous element could fail. This was because the `insertSnippet` command was being handled within `AceEditorCommandDispatcher`, and since the `ShortcutManager` saw that the keypress had been dispatched to a command, it stopped propagation of the event and prevented the browser default behavior.
This PR also works around a Qt bug whereby its attempts to dispatch `Qt::Key_Backtab` events to Chromium would fail; we accommodate this by manually translating these back to regular shift-tabs.
Closes #2991.
=> fix handling of Shift+Tab keypress

src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopSatelliteWindow.cpp, src/cpp/desktop/DesktopSecondaryWindow.cpp
This PR ensures that a close of a secondary window, if it is the final RStudio window opened, also quits the application.
=> ensure RStudio exits after last window closed

NEWS.md, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Small enhancement that helps avoid the somewhat surprising behavior wherein a missing trailing newline in an R startup file can cause the final R expression in that file to be lost.
=> ensure startup files have trailing newline (closes #3029)

src/cpp/core/include/core/r_util/RToolsInfo.hpp, src/cpp/core/r_util/RToolsInfo.cpp, src/cpp/session/modules/build/SessionBuild.cpp, src/cpp/session/modules/build/SessionBuildEnvironment.cpp, src/cpp/session/modules/clang/RCompilationDatabase.cpp
If I understand correctly, RStudio currently only detects versions of Rtools based on the contents of the registry. However, when Rtools is installed one can select whether or not the registry is updated after install. If the registry is not updated, then RStudio will fail to detect that install.
To complicate things a bit, when RStudio installs Rtools automatically / programmatically, it seems that the last-used preference for an Rtools installer is used. If the user opted out of updating the registry with an interactive installer, that same preference will be re-used on further installation attempts -- hence necessitating our folder-based lookup.
Fixes https://github.com/rstudio/rstudio/issues/3016.
=> scan RBuildTools folder for Rtools

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/EditSession.java
This PR fixes an issue where attempts to paste could incorrectly re-indent string selections in rare instances.
The ultimate cause of this issue was a race condition in the tokenizer. To avoid latency, the document is tokenized on a background timer that normally runs eagerly for the current line changed, but lazily for lines that follow that may need to be re-tokenized.
In this particular case, the attempt to paste was being handled _before_ the tokenizer could run. The re-indent logic we have relies on the tokenizer to communicate some state (e.g. "am I within a string right now?") and if the tokenizer had not yet run on the pasted text, an incorrect state would be computed for the line to be indented.
Closes #3036.
=> resolve race condition in tokenizer on paste

NEWS.md, src/cpp/session/SessionUserSettings.cpp, src/cpp/session/include/session/SessionUserSettings.hpp, src/cpp/session/modules/SessionRSConnect.cpp, src/gwt/src/org/rstudio/studio/client/rsconnect/model/RSConnectPublishSettings.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/NewRSConnectAuthPage.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSAccountConnector.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PublishingPreferencesPane.java
This change contains three smaller changes which make it possible to authenticate and publish to RStudio Connect servers that use custom or self-signed SSL certificates using only the RStudio IDE (it was formerly necessary to use a series of `rsconnect` commands to make this work). 
They are as follows:
1. **Allow specifying a path to a custom CA bundle**. This path can also be set in an environment variable, or an R option; setting it in RStudio is a convenience for setting the R option, which is also reflected in the child precess that performs the deploy.
2. **Always use the system browser to authenticate**. We formerly used a window hosted by RStudio itself on the desktop; this improves window management but has caused a number of problems in edge cases, which range from difficult to …
=> Enable auth and publish workflows with Connect servers requiring custom SSL settings

src/gwt/src/org/rstudio/studio/client/RStudio.java
This PR provides the main RStudio window with a name. This can occasionally be useful for actions taken on a satellite window that require a named reference to the parent window; e.g. this gives a mechanism for https://github.com/rstudio/rstudio/issues/2921 to allow a Shiny application running in an external window to focus the main window.
=> provide name for RStudio window

src/cpp/session/resources/grid/dtstyles.css, src/cpp/session/resources/grid/dtviewer.js
This PR makes a number of changes intended at improving the performance of the Data Viewer:
1. Rather than attempting to draw a resizer for each cell in the table, we only draw it for the table header. This implies that now the table can only be resized by clicking and dragging from the header, but it is consistent with other tables with resizable columns (e.g. in the Files pane). (It was observed that drawing and positioning the resizer for each cell independently was very expensive)
2. Given that we're no longer drawing a resize element for each cell, it suffices to just use a simple `<span>` element without any class styling (used just so we can attach the `title` element).
In my tests with a 100x100 table of numbers, layout changes require ~70ms to redraw versus ~170ms in the current …
=> tweaks for data viewer performance

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AceEditorPreview.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
In RStudio 1.1 on Windows and Linux, we had a Use Ligatures checkbox in the Appearances preference pane. This added a CSS class which was required to enable ligatures in QtWebKit.
In RStudio 1.2 this checkbox doesn't work because QtWebEngine uses ligatures by default.
It's technically possible make the option work again by having it forcibly *disable* ligatures in CSS using [font-variant-ligatures](https://developer.mozilla.org/en-US/docs/Web/CSS/font-variant-ligatures), but little evidence anyone would actually find this useful, so I'm removing it entirely.
=> Remove obsolete ligature setting in Appearance

src/gwt/src/org/rstudio/studio/client/common/mirrors/ChooseMirrorDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetSqlHelper.java
This change resolves some Java warnings about unused variable values (i.e. values that are written but never read) and functions.
@javierluraschi This should be very safe to merge since the code is demonstrably unable to affect runtime, but wanted a second set of eyes on it in case one or more of these paths was intended to be used.
=> Remove dead code in client-side repository/sql paths

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/SourceDocument.java
Due to the way Plumber APIs are executed, breakpoints set in the IDE will never be hit when calling the APIs. This change disallows setting breakpoints in R source files containing Plumber annotations. Attempting to do so shows a warning bar:
- fixes #3059
=> don't set breakpoints in Plumber API source files

src/gwt/src/org/rstudio/studio/client/workbench/views/output/find/FindOutputPresenter.java
This PR ensures that the path uses for Find in Files is project-relative (when appropriate), ensuring that relocated projects don't persist a 'stale' reference to the old project.
Closes https://github.com/rstudio/rstudio/issues/3053.
=> save Find in Files path as project-relative

src/gwt/src/org/rstudio/core/client/dom/DomUtils.java, src/gwt/src/org/rstudio/core/client/widget/RStudioDataGrid.java, src/gwt/src/org/rstudio/core/client/widget/VirtualizedDataGrid.java, src/gwt/src/org/rstudio/studio/client/workbench/views/environment/view/EnvironmentObjectList.css, src/gwt/src/org/rstudio/studio/client/workbench/views/files/ui/FilesList.java
On MacOS, horizontal overlay scrollbars often flash in unpredictable locations when DataGrids appear and when they're resized. Via @hadley: 
The cause of the problem turns out to be some internal elements created in GWT's `DataGrid` implementation. For reasons which are wholly unclear, Chrome draws horizontal overlay scrollbars for these elements when their widths are increased, even though they are not visible (i.e. have `visibility: hidden`). 
In a shameless removal of [Chesterson's Fence](https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence), this change keeps the scrollbars concealed on these elements by scanning the DOM for them once, when the DataGrid is attached, and  turning off scrolling for the elements' contents.
Fixes #2808.
=> Avoid flashing overlay scrollbars when showing/resizing DataGrids

src/gwt/src/org/rstudio/core/client/dom/DomUtils.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/explorer/view/ObjectExplorerDataGrid.java
GWT's DataGrid class attempts to draw its own specialized scrollbars, by placing an absolutely-positioned div of appropriate height with a slight blur to make the scrollbar transparent. Unfortunately, as a side effect of how GWT draws the scrollbar, it's possible to obscure the actual content in the associated table. This is especially an issue as in #3085 the scrollbar can effectively obscure buttons that we attempt to draw in the table.
The fix here is to delete the specialized GWT scrollbar element, and allow the browser to draw the scrollbar as appropriate. This also allows the browser to resize the table according to whether an overlay scrollbar is drawn, versus a regular space-occupying scrollbar.
Closes #3085.
=> remove specialized scrollbars from Packages pane

src/cpp/session/modules/SessionCodeTools.R, src/cpp/session/modules/SessionRCompletions.R
This PR attempts to mitigate issues that can occur if multiple copies of `tools:rstudio` end up on the search path.
Having multiple versions of `tools:rstudio` on the search path is almost certainly a bug in our initialization code somewhere; however, [users have run into this issue before](https://support.rstudio.com/hc/en-us/community/posts/115007560148-The-R-session-had-a-fatal-error-), and @MariaSemple has also bumped into this with some of the theme testing code.
The attempts to use `which(search() == "tools:rstudio")` were a bit misguided when `as.environment("tools:rstudio")` works fine and also succeeds when multiple copies of that environment end up on the search path.
=> mitigate issue with multiple 'tools:rstudio' on search path

src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPaneEditorStyles.css
This PR improves the theming for vignettes as rendered in the help pane when a dark theme is active. Examples of before and after with a sample vignette:
Before:
After:
Closes #2551.
=> improve themeing for vignettes in dark themes

src/cpp/session/modules/SessionPackages.R, src/gwt/src/org/rstudio/core/client/cellview/ImageButtonColumn.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/Packages.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackageInfo.java
This PR augments the Packages pane's browse button in a number of ways:
1. We use information from the package's DESCRIPTION file to better select a URL. This is necessary for packages that were installed from Bioconductor, and helpful for packages that have their own dedicated website (e.g. `ggplot2` has `http://ggplot2.tidyverse.org`). We also navigate to the GitHub repository associated with a package for packages installed directly from GitHub.
2. Because base R packages don't have an external URL, we no longer draw a browse icon for these packages. Similarly, one shouldn't ever attempt to uninstall a base R package, so we also omit the remove package icon in that case as well.
Note that because this PR involves a rewrite of `.rs.listInstalledPackages()` some extra scrutiny is …
=> choose appropriate package URL based on installed package type

src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/cpp/desktop/DesktopGwtCallbackMac.mm, src/cpp/desktop/DesktopMainWindow.cpp
This PR is an attempt to resolve #2443. We attach our own Cocoa key handler, detect attempts to press <kbd>Command + Shift + /</kbd>, and then re-route that command to reflow comments explicitly.
TODO: I plan to investigate whether we can just route this to the ShortcutManager to execute whatever command is associated with this key combination (in case the user has rebound commands)
=> disable macOS-specific Cmd+Shift+/ handling (closes #2443)

src/cpp/r/R/Api.R
This fixes an issue where attempts to generate RStudio dialogs using the default values for e.g. url, ok, cancel could introduce `NA` values into the generated UI, e.g.
---
The ultimate cause here is an impedance mismatch between RStudio and rstudioapi: the defaults for these arguments in `rstudioapi` are `NULL`, but the default conversion of `NULL` objects by RStudio when converting to strings is (surprisingly) the string "NA" rather than an empty string.
=> provide better defaults for API-created dialogs

src/cpp/session/modules/SessionCodeTools.R, src/cpp/session/modules/SessionPackages.R, src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/Packages.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackageUpdate.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackagesServerOperations.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/ui/CheckForUpdatesDialog.java
This PR improves our ability to navigate to the CRAN NEWS file associated with a currently installed package.
Effectively, RStudio now tries multiple sets of links until it discovers one that does not 404; after discovering such a link it opens that link in the browser.
Note that with this change, we always show a NEWS link icon, but provide an error message to the user if we failed to figure out what the correct NEWS link is.
Closes #3082.
=> improve handling of NEWS navigation

src/gwt/src/org/rstudio/studio/client/pdfviewer/model/PdfJsWindow.java
In the macOS dailies, I was seeing `pdf.js` windows initialized twice. This had the side-effect of unnecessarily drawing a synctex button, as the associated code that hides the button when disabled was getting overridden by the newly-created button on the second initialization attempt.
This PR just introduces a flag to ensure initialization only happens once. In theory, it might be preferable to reason through the various codepaths that request window initialization and ensure only one is called, but making this routine idempotent seems sensible.
=> avoid double init of pdf.js window UI

src/cpp/session/modules/SessionPackages.R, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/Packages.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesDisplayObserver.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/PackagesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/packages/model/PackageInfo.java
This PR tries to avoid generating R code that can run afoul of a strange R bug -- attempting to load `tidyverse` when using an aliased path for the library location can cause downstream errors when attempting to use sub-packages, e.g. `readr`. See https://github.com/tidyverse/tidyverse/issues/46 for more details.
Now, when attempting to load an R package from the default user library, RStudio omits `lib.loc` (as R will by default load the package from the first library in `.libPaths()`). If we do need to explicitly specify a library path, we use the absolute path to that library rather than an aliased path.
Closes #3130.
=> omit library path when un-needed; use absolute library path otherwise

docker/jenkins/Dockerfile.windows, docker/jenkins/windows/qt-noninteractive-install-win.qs, docker/win-docker-compile.cmd
During Qt 5.11 work I changed `Dockerfile.windows` to assume docker build context is root of rstudio repo, but [Jenkins  build script](https://github.com/rstudio/aws/blob/master/ElasticComputeCloud/launch-scripts/jenkins-swarm-windows.ps1) assumes root is docker/jenkins.
Changed dockerfile to match Jenkins assumption in finding the Qt installation script, and duplicate the script from dependencies\windows.
Haven't tested this directly, going to let the build pipeline test it.
=> change Dockerfile.windows build context dir to match Jenkins assumption

src/cpp/desktop/DesktopMain.cpp, src/cpp/desktop/DesktopWebView.cpp
This PR makes use of Qt 5.11's embedded Chromium DevTools, and also implements the `Inspect Element` behavior we know and love from RStudio v1.1 -- spawning and focusing a new DevTools window as required, and then focusing the active element within.
=> use embedded devtools for Qt 5.11

src/gwt/src/org/rstudio/studio/client/common/mirrors/ChooseMirrorDialog.java, src/gwt/src/org/rstudio/studio/client/common/repos/SecondaryReposDialog.java, src/gwt/src/org/rstudio/studio/client/common/repos/SecondaryReposWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
This is a small tweak that uses 'repository' rather than 'repo' within the UI dialogs.
=> prefer 'repository' to 'repos'

src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java, src/gwt/src/org/rstudio/studio/client/workbench/exportplot/clipboard/CopyPlotToClipboardDesktopDialog.java, src/gwt/src/org/rstudio/studio/client/workbench/views/viewer/export/CopyViewerPlotToClipboardDesktopDialog.java
Closes https://github.com/rstudio/rstudio/issues/2831.
The implementation of `copyImageToClipboard()` had effectively been stubbed out, due to changes in the Qt APIs in the WebKit -> Chromium changes. I erroneously thought things were working because the Copy Plot functionality worked on macOS, but we actually have a separate implementation for that altogether.
Qt also documents the `CopyImageToClipboard` action as only working in response to clicks; that is, the documentation purports that it is used to copy the clicked image to the clipboard. Since we don't have an actual click event here (although I suppose we could synthesize one if we really needed to?) the event is not processed as we would normally expect.
Because `copyImageToClipboard()` is no longer reliable, I've just removed …
=> copy page region when exporting plot to clipboard

src/cpp/core/include/core/r_util/RPackageInfo.hpp, src/cpp/core/r_util/RPackageInfo.cpp, src/cpp/session/SessionOptions.cpp, src/cpp/session/include/session/SessionConstants.hpp, src/cpp/session/include/session/SessionOptions.hpp, src/cpp/session/modules/SessionGit.cpp, src/cpp/session/modules/build/SessionBuild.cpp, src/cpp/session/projects/SessionProjectContext.cpp
Normally the `Check Package`, `Build Source Package`, and `Build Binary Package` commands write to the parent folder of the package itself. So for `/home/me/mypackage`, files are written to `/home/me`.
This change supports writing these files inside the package folder itself, for a case where users don't have write access to the folder containing the package project. This was requested by the cloud team (see https://github.com/rstudio/rstudio-pro/issues/482). Implementing in open-source server.
This can be enabled in `rsession.conf` by adding:
`package-output-to-package-folder=1`
Note: this only works if package operations are being done via devtools package; if they are being done directly via R CMD check/install/build, this setting will not change the output location.
In addition to …
=> Add config option to send package build output to package folder

src/gwt/src/org/rstudio/studio/client/RStudio.java
I suspect some users are having an RStudio failure to launch due to the front-end attempting initialization before Qt is ready, e.g.
https://community.rstudio.com/t/rstudio-daily-build-never-loads/7972/30
This PR increases the initial wait delay to 1 minute, and also logs when we do this sort of un-synchronized launch.
=> warn when attempting to launch before ready

src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
Fixed by moving Home Page-related items to Advanced tab.
Note, this only manifests on RStudio Server Pro but fix is in shared code.
See https://github.com/rstudio/rstudio-pro/issues/522
=> Content doesn't fit on General Prefs pane, pushing some off bottom (Pro server only)

docker/jenkins/Dockerfile.opensuse15-x86_64
This change adds gpg 1.4 on the OpenSUSE 15 container. We use gpg to sign releases, but don't support gpg 2 since it's not nearly as amenable to scripting. 
Unfortunately OpenSUSE 15 does not provide a package for gpg 1, so this change builds it from source as part of the Docker image.
=> Install gpg 1.4 from source on OpenSUSE 15

src/cpp/session/modules/SessionDataViewer.R
This small change prevents us from trying to draw histograms with numeric-like values, such as the those from the `integer64` class. 
We can often work with these values while their associated package is loaded (for instance, `as.numeric` works on `integer64` objects while `bit64` is loaded), but the data viewer needs to be able to run without package prerequisites since it persists across sessions.
=> Require real numeric values for histograms

src/cpp/session/SessionClientEvent.cpp, src/cpp/session/SessionModuleContext.cpp, src/cpp/session/include/session/worker_safe/session/SessionClientEvent.hpp, src/cpp/session/modules/SessionCodeTools.R, src/cpp/session/modules/SessionPackages.R, src/cpp/session/modules/SessionRUtil.R, src/cpp/session/modules/SessionRUtil.cpp, src/cpp/session/modules/SessionSource.cpp, src/gwt/src/org/rstudio/core/client/SingleShotTimer.java, src/gwt/src/org/rstudio/core/client/widget/InfoBar.java, src/gwt/src/org/rstudio/studio/client/RStudioGinjector.java, src/gwt/src/org/rstudio/studio/client/application/events/EventBus.java, src/gwt/src/org/rstudio/studio/client/common/dependencies/DependencyManager.java, src/gwt/src/org/rstudio/studio/client/common/dependencies/model/Dependency.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEvent.java, src/gwt/src/org/rstudio/studio/client/server/remote/ClientEventDispatcher.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/codebrowser/CodeBrowserEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetPackageDependencyHelper.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/events/AvailablePackagesReadyEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/model/SourceServerOperations.java
NOTE: not quite ready for merge.
I realize this PR is coming in quite late but this is something that we originally wanted to get in for v1.2 and the nonstop deluge of WebEngine bugs was starting to drive me insane :-)
This PR implements automatic R package dependency discovery in R source documents, and prompts the user to install any missing packages with a warning bar when necessary.
Clicking the <kbd>Install</kbd> button here opens the typical dependency manager installer, and attempts to install all packages from CRAN.
=> discover required dependencies and prompt user

src/gwt/src/org/rstudio/studio/client/common/vcs/SshKeyWidget.java, src/gwt/src/org/rstudio/studio/client/projects/ui/prefs/ProjectCompilePdfPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/CompilePdfPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/RMarkdownPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/SourceControlPreferencesPane.java
This PR makes some minor tweaks to the text used within the Global + Project Options dialogs, mainly for consistency in use of spaces, trailing colons for text box labels, and so on.
I changed a couple labels in the Sweave dialog since I think it's (mostly) well understood that Global Options are global, and Project Options are scoped to the project.
=> tweaks to text within Global, Project Option dialogs

src/gwt/src/org/rstudio/studio/client/common/satellite/SatelliteWindow.java
Fix for https://github.com/rstudio/rstudio/issues/3153
@MariaSemple, would you mind code reviewing this change?
I didn't mean to take this issue from your plate, it's just that @kevinykuo mentioned this to me and it felt like and old bug, which it seems to be, it's just that recent changes in how UIPrefs propagate and other events might uncover this.
=> Only initialize satellite dark themes when satellite supports this

src/cpp/session/modules/SessionRAddins.cpp, src/gwt/src/org/rstudio/studio/client/application/ui/addins/AddinsToolbarButton.java, src/gwt/src/org/rstudio/studio/client/workbench/addins/Addins.java
This PR ensures that addins are displayed in the same order as defined within a package's `addins.dcf`.
Closes https://github.com/rstudio/rstudio/issues/3174.
=> preserve addin ordering in display

src/cpp/desktop/DesktopOptions.cpp
This PR fixes a long-standing issue reported by a sparse set of users where RStudio would incorrectly begin using serif fonts where a sans-serif or monospace font would be more appropriate.
The underlying issue was caused by us incorrectly quoting the fallback font; it seems that browsers understand that `sans-serif` means use the system default sans-serif font whereas `"sans-serif"` means "attempt to find a font called "sans-serif" and use it if available".
Ironically discovered because an in-house Windows 10 laptop for some reason started exhibiting this issue, so it became easier to debug.
=> fix bug where fallback font would not be successfully used

src/gwt/src/org/rstudio/core/client/widget/Toggle.java, src/gwt/src/org/rstudio/core/client/widget/Toggle.ui.xml, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/ChunkOptionsPopupPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/display/SetupChunkOptionsPopupPanel.java
This PR implements a new tri-state toggle for the chunk options popup panel (hat tip to @nwstephens)
The intention of this toggle is to make it more clear to the user that three possible states are supported by the toggle, and make it a bit more clear what the 'indeterminate' state is. Compare with the old treatment:
I think the new UI is overall an improvement, although I'm somewhat torn as to whether we should use color or greyscale here. Example of what that might look like:
Also wonder if it's worth increasing the contrast a bit on the 'knob' to make it stand out a bit more.
=> implement tri-state toggle

src/gwt/src/org/rstudio/core/client/StringUtil.java, src/gwt/src/org/rstudio/core/client/URIUtils.java, src/gwt/src/org/rstudio/core/client/dom/DomUtils.java, src/gwt/src/org/rstudio/studio/client/plumber/ui/PlumberAPIPanel.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdOutputFramePane.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdOutputPanel.java, src/gwt/src/org/rstudio/studio/client/rmarkdown/ui/RmdOutputPresenter.java, src/gwt/src/org/rstudio/studio/client/shiny/ui/ShinyApplicationPanel.java, src/gwt/src/org/rstudio/studio/client/workbench/views/connections/ui/NewConnectionShinyHost.java, src/gwt/test/org/rstudio/core/client/dom/DomUtilsTests.java
This change fixes a bug observed by rstudio.cloud in which an R Markdown document URL had too many slashes. 
The problem is string math in `StringUtil.makeAbsoluteUrl()`, which incorrectly presumes that `window.location.pathname` doesn't start with a `/`. This causes it to produce URLs that have two consecutive slashes, which isn't usually an issue but causes a problem on rstudio.cloud. 
Instead of trying to manipulate URLs with string math (which is demonstrably error-prone), this change uses the browser itself to resolve relative URLs to absolute ones, by creating a dummy `<a>` tag and having the browser resolve its `href`.
=> Resolve absolute URLs using the browser

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetWidget.java
Supercedes https://github.com/rstudio/rstudio/pull/2169.
With this PR:
1. We always use hard tabs in `.tsv` files, and
2. We make the 'Show whitespace characters' preference more user-accessible for `.csv` and `.tsv` files (for easier inspection of where rogue whitespace might have sneaked into a particular file)
=> enforce tabs in tsv; show whitespace for csv + tsv

src/cpp/desktop/DesktopMainWindow.cpp, src/cpp/desktop/DesktopSatelliteWindow.cpp
We're now manually closing all satellites on application quit (see https://github.com/rstudio/rstudio/commit/a9b27f65c705c95de95b3d4694258e58c077acc3#diff-ad46e0cfc533781d577d1f2e13754c14). However, we're doing this *before* the user has confirmed quit, with the result that every satellite thinks it's being closed manually by the user. That's a problem in source satellites since we generally want unsaved file prompting to be coordinated by the main window.
The fix is to:
1. have the source satellites respond only to spontaneous closure, and
2. don't close all satellites after returning from `quitR()` (this function returns before the user has confirmed quit)
Fixes #3210.
=> Let main window handle closure of source windows

src/cpp/session/modules/SessionThemes.R, src/cpp/session/modules/SessionThemes.cpp, src/cpp/tests/testthat/test-themes.R
Fixes #3179.
This bug was caused by the client requesting themes from absolute paths instead of relative paths. The fix was verified with a server running behind a proxy that was configured to server RStudio from a custom path (e.g. `<host>/rstudio`).
=> Use correct relative theme URLs

src/cpp/session/CMakeLists.txt, src/cpp/session/modules/SessionThemes.R
Closes #3247.
Also adds a `getThemes` api function.
=> add missing compile-themes.R to installer.

src/cpp/core/file_lock/AdvisoryFileLock.cpp, src/cpp/core/file_lock/LinkBasedFileLock.cpp
Errors were inconsistently tagged with the `lock-file` parameter, which makes diagnosing certain lock errors more difficult. This ensures all errors are tagged with `lock-file` so we can figure out which file we attempted to lock more directly.
=> always tag lockfile errors with 'lock-file' path

src/gwt/src/org/rstudio/studio/client/workbench/views/help/HelpPaneEditorStyles.css
Closes #3258.
It adds `color: white !important;` to all the elements that should have been white that weren't. I think this is more explicit than what we had before ee68a86, so it's possible that there's something going wrong with style inheritance, but this change does replicate what we had in 1.1 and doesn't seem to impact any other elements.
=> adding css rules to fix the text colouring problems in the help pane.

src/cpp/session/modules/SessionRMarkdown.R, src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RmdOutputInfo.java, src/gwt/src/org/rstudio/studio/client/rsconnect/RSConnect.java, src/gwt/src/org/rstudio/studio/client/rsconnect/model/RSConnectPublishInput.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectDeploy.java, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectPublishButton.java
In RStudio 1.0 you could publish rendered content from the Source pane. The IDE would auto-run rendering before showing the publishing wizard (if current output was missing or out-of-date) to ensure it was available if user went down a publish-wizard path that needed it. However, publishing source to Connect does not need it, and often rendering on the client is not going to work at all for Connect users, so it was confusing and time-consuming.
RStudio 1.1 removed the ability to publish rendered content from the Source pane. It would only publish source from editor (i.e. publish source to Connect). To publish rendered content, had to use the Publish button on the rendered preview in viewer/window. Though this is logical, many users were used to using the editor's publish button and …
=> Allow publishing rendered content from the Source pane

src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/cpp/desktop/DesktopMain.cpp, src/cpp/desktop/DesktopOptions.cpp, src/cpp/desktop/DesktopOptions.hpp, src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/GeneralPreferencesPane.java
This PR allows user to select an alternate rendering engine with RStudio Desktop. This is primarily intended to be an escape hatch for users who are bumping into rendering problems or crashes when using the default hardware accelerated renderer.
At least in my own local testing, ANGLE + Software are much slower than regular desktop rendering. However, I no longer see crashes or hangs when using the software renderer in my virtual machine, so there is additional evidence that this will help users avoid some classes of issues.
=> provide ability to change rendering engine

src/gwt/src/org/rstudio/core/client/theme/res/themeStyles.css, src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.css, src/gwt/src/org/rstudio/core/client/widget/RStudioThemedFrame.java
Closes #3272.
Worth noting: our Safari-specific styling now evidently also applies on Windows. (These styles are applied within an ` @if user.agent safari { ... }` block)
=> enforce scrollbar widths on Windows

src/cpp/session/modules/SessionGit.cpp
This is primarily a debugging convenience. By setting the RSTUDIO_GIT_LOG environment variable, we can have RStudio dump all of the commands it's executing to stdout (which typically means it's routed to the R console output).
=> log git commands with RSTUDIO_GIT_LOG envvar

src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml
The spellcheck button was missing a description (for e.g. mouse hover); this PR adds it back in.
Before:
After:
=> ensure spellcheck label

src/cpp/desktop/DesktopGwtCallback.cpp
Closes #3309.
Qt has in the changelog for Qt 5.8.0:
>  - [QTBUG-53833] QProcess::startDetached() changed behavior on Windows:
>    it no longer creates a new console window unconditionally, instead it
>    passes the same creation flags to CreateProcess as QProcess::start().
So we need to explicitly request a console window when launching e.g. Git Bash.
=> accommodate changes in QProcess API on Windows

src/cpp/session/resources/templates/shiny/app.R, src/cpp/session/resources/templates/shiny/server.R, src/cpp/session/resources/templates/shiny/ui.R
Just a minor thing, but I noticed that the shiny template has superfluous whitespaces when I added it to git.
Disclaimer: I used the web interface of Github to make the changes, so I haven't build RStudio and tested it. I also could not figure out how to add multiple files to a single commit, so I created three commits with the same message. Needs squashing :)
=> Remove superfluous whitespaces in shiny template 

dependencies/windows/Install-RStudio-Prereqs.ps1
When R was bumped from 3.5.0 to 3.5.1, the URL for downloading latest build changed. Tweak script to pin to 3.5.0 now that it's an older build.
=> Fix windows-dependency script to install R 3.5.0

src/cpp/CMakeLists.txt, src/cpp/desktop/DesktopOptions.cpp
This should fix issues where light vs. dark stylesheets fail to apply on Windows. Log entries of the form:
> 17 Aug 2018 16:25:25 [rdesktop] ERROR system error 3 (The system cannot find the path specified) [path=C:/Program Files/RStudio/bin/resources/stylesheets/rstudio-windows-dark.qss]; OCCURRED AT: auto __cdecl rstudio::core::FilePath::open_r::<lambda_d4246793555dd4e209de8cc0cf7ef3ce>::operator ()(void) const c:\jenkins\workspace\ide\windows\src\cpp\core\filepath.cpp:1072; LOGGED FROM: void __cdecl rstudio::desktop::applyDesktopTheme(class QWidget *,bool) c:\jenkins\workspace\ide\windows\src\cpp\desktop\desktoputils.cpp:145
are emitted to the logs.
The issue here is that on Windows, folders exist _both_ at `<root>/bin/resources` and `<root>/resources`; the prior logic attempting to …
=> properly compute resources path for dev vs. pkg build

src/gwt/acesupport/acemode/markdown_highlight_rules.js, src/gwt/src/org/rstudio/studio/client/common/filetypes/TextFileType.java
Bugfix for: https://github.com/rstudio/rstudio/issues/1588
Previously spellchecking an R markdown document would only check tokens labeled with the "text" type. Due to how highlighting is set up many tokens that are actually text types have other classes such as "constant" and "numeric". This PR adds the "text" type to existing types as well as adds "string" and "header" as valid types to check.
=> Improve spellcheck markdown coverage

src/cpp/session/modules/SessionRSConnect.cpp, src/gwt/src/org/rstudio/studio/client/rsconnect/model/RSConnectPublishSource.java
With the reintroduction of publishing rendered static content from editor via #3266, request was made to also support publishing other static types to Connect directly from the IDE instead of having to manually run `rsconnect::deployDoc`.
Can now publish PDF, Word (.docx, .rtf, .odt), and PPT (.pptx) files to Connect. This doesn't change the Connect-side behavior for rendering these types, so that will depend what the browser and/or Connect is capable of showing. On my Mac/Chrome, PDFs show in the browser, but Word and PPT files show a download link.
Fixes #3265 
FYI @nwstephens
=> Publish static assets such as PPT, PDF, Word Files from RStudio to Connect

src/gwt/src/org/rstudio/studio/client/rmarkdown/model/RmdPreviewParams.java
Build an R Markdown website project from the Build Tab, then publish to Connect (with source code), from the Publish Button in the viewer. The resulting Connect artifact had the wrong type set (document instead of site), and had broken links and other problems.
Super-simple fix to a typo(ish) error in the original source (though took me quite a while to find it); was broken since website publishing support was added in IDE v0.99.
Fixes #3345
=> Fix publishing RMD website with source from viewer to Connect

src/cpp/desktop/DesktopWebPage.cpp, src/cpp/desktop/DesktopWebPage.hpp
This PR fixes a regression from https://github.com/rstudio/rstudio/pull/2987, which had sought to fix https://bugreports.qt.io/browse/QTBUG-56805.
For some reason, link clicks in QtWebEngine are interpreted as attempts to load subframes. Since we were screening out non-local subframes before, the navigation attempt was blocked and nothing happened on the link click.
This PR works around the issue by tracking the currently hovered URL. If QtWebEngine happens to attempt to navigate to a URL that the mouse is currently hovering over, we surmise that the user must have clicked that URL (ie: it must not be a non-interactive subframe load in a page) and allow that page to be navigated to.
=> ensure link clicks successfully open URLs (closes #3359)

src/cpp/session/modules/SessionGit.cpp
If `.Rproj.user/` exists in .gitignore, don't add `.Rproj.user` to .gitignore.
Closes #3326.
Individual contributor agreement sent to jj@rstudio.com.
=> Ignore .Rproj.user directory

src/cpp/desktop/DesktopGwtCallback.cpp, src/cpp/desktop/DesktopGwtCallback.hpp, src/cpp/desktop/DesktopGwtCallbackMac.mm
Demo:
[Wombat](https://github.com/randy3k/dotfiles/blob/master/.R/rstudio/themes/Wombat.rstheme) is a customized theme with a different dark background other than the default blue.
=> Adaptive macOS Title Bar Color

src/cpp/desktop/DesktopGwtCallbackMac.mm
Fix a bug spotted by @kevinushey 
> I tried playing with this a bit but I'm seeing something odd: the text color in the title bar changes when I move the window around. Initially, when the window is focused, the color is closer to white; if I move the window around or interact with the window a bit; the text changes to a more grey color.
Solution inspired by https://forums.xamarin.com/discussion/99677/nswindow-titlebarappearstransparent-titlebar-corner-does-not-change-color
Additionally, use white background instead of `clearColor` because otherwise, the title bar would become transparent.
=> set wantsLayer properpty of NSView

src/cpp/r/session/RStdCallbacks.cpp
This fixes an issue seen with the `later` package where sending an interrupt would cause RStudio to re-evaluate the last-processed console input a second time.
Closes #3394.
=> console input buffer not ready after interrupt

src/cpp/session/SessionModuleContext.cpp
GitHub seems to be a first-class citizen, relegating GitLab into the void. This PR adds an `else` section to at least enable selecting and editing of gitlab CI yaml files without having to go the route of opening a file dialog manually, un-hiding dot files and selecting the gitlab CI yml file.
=> Enable editing of GitLab CI files in RStudio by not hiding them from the file pane

src/cpp/core/CMakeLists.txt, src/cpp/core/include/core/system/Interrupts.hpp, src/cpp/core/include/core/system/Process.hpp, src/cpp/core/system/PosixInterrupts.cpp, src/cpp/core/system/Win32ChildProcess.cpp, src/cpp/core/system/Win32Interrupts.cpp, src/cpp/desktop/DesktopSessionLauncher.cpp, src/cpp/session/SessionMain.cpp, src/cpp/session/http/SessionHttpConnectionListenerImpl.hpp, src/cpp/session/http/SessionHttpConnectionUtils.cpp, src/cpp/session/http/SessionHttpConnectionUtils.hpp, src/cpp/session/http/SessionNamedPipeHttpConnectionListener.hpp, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/Shell.java
Currently, in RStudio, it is not possible to interrupt R when a sub-process is being executed, e.g. via a `system()` call. This is because the R session receives the interrupt RPC request, enqueues it, and then only processes it later when R is ready to process events -- and this doesn't occur until the sub-process has finished executing. Furthermore, for interrupts, we only set the interrupt flag on the R session itself, whereas in cases where R is run in a terminal, pressing <kbd>Ctrl + C</kbd> would signal all processes in that (terminal) process group.
This PR alleviates this issue by responding to the interrupt RPC requests directly, rather than enqueueing them. To make sure that the interrupt is properly handled and propagated, we use two different solutions:
1) On POSIX systems, we …
=> allow interrupt of sub-processes launched by R

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceTheme.java
When using a proxy with a custom path (e.g. <hostname>/rstudio is the home page) the default theme cannot be loaded because it was using an absolute path. This PR changes the default theme to use a relative path.
=> Fix a bug where the default theme cannot be loaded when using certain configurations.

src/cpp/session/modules/SessionConnections.R
fixes #3400 
Don't apply the second test if the first if FALSE because it throws an error if sparklyr not installed in the environment .
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/rstudio/rstudio/3401)
=> Use a shinyapp in connection pane without having sparklyr on the system

src/cpp/r/session/graphics/RGraphicsDevice.cpp
This PR works around an issue noted in https://github.com/tidyverse/ggplot2/issues/2252. Reproducible example adapted from https://gist.github.com/dpseidel/322db7110b8590d77ba20f3db8f399fc; should reproduce on macOS:
```R
library(ggplot2)
blank_base <- ggplot(data.frame(), aes(1, 1)) +
theme(
axis.title.y = element_blank(),
axis.title.x = element_blank(),
axis.text.y = element_blank(),
axis.ticks = element_blank(),
panel.background = element_blank(),
panel.grid = element_blank()
)
q <- blank_base + scale_x_continuous(labels = c(
expr(10 ^ 1), expr(10 ^ 2),
expr(10 ^ 3), expr(10 ^ 4),
expr(10 ^ 5)
)) 
repeat print(q)
```
It _seems_ like there is some sort of race condition here -- the errors occur when a metric info request comes immediately after the device in deactivated and then later …
=> avoid race condition (?) in metric info request

src/cpp/r/RJson.cpp
This PR fixes a small issue caught by ASAN where we would accidentally perform an out-of-bounds read when attempting to convert an empty `data.frame` to JSON. (See the call to `int values = Rf_length(VECTOR_ELT(listSEXP, 0));` below)
=> avoid out-of-bounds read in empty data.frames

src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServerEventListener.java
This PR fixes an issue where the R banner would occasionally be printed twice on startup, primarily on Windows.
The ultimate issue is that we end up making two `get_events` requests with the same event ID `-1`. Here's my understanding as to how we get there:
1. An initial `get_events` call with id `-1` is made. The `console_output` event (alongside some other events) is returned to the client, and that output is sent to the console.
2. A number of other interleaving JSON RPCs are made during initialization. Some of these don't set any response. When this occurs, we assume (as a default) that more pending events are on the way, and so as a side-effect launch a watchdog timer that double-checks that we receive a `get_events` response in a timely manner. …
=> fix issue with double-printing of R banner on Windows

src/cpp/session/CMakeLists.txt, src/cpp/session/SessionMain.cpp, src/cpp/session/modules/SessionCodeTools.R, src/cpp/session/modules/sql/SessionSql.R, src/cpp/session/modules/sql/SessionSql.cpp, src/cpp/session/modules/sql/SessionSql.hpp, src/gwt/acesupport/acemixins/token_iterator.js, src/gwt/acesupport/acemode/rmarkdown.js, src/gwt/acesupport/acemode/sql_highlight_rules.js, src/gwt/build.xml, src/gwt/src/org/rstudio/core/client/js/JsMapString.java, src/gwt/src/org/rstudio/core/client/js/JsObject.java, src/gwt/src/org/rstudio/studio/client/common/JSONArrayBuilder.java, src/gwt/src/org/rstudio/studio/client/common/codetools/CodeToolsServerOperations.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/DocumentMode.java, src/gwt/src/org/rstudio/studio/client/common/filetypes/FileType.java, src/gwt/src/org/rstudio/studio/client/common/reditor/EditorLanguage.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/CompletionManagerBase.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/SqlCompletionManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/SqlCompletionParseContext.java, src/gwt/src/org/rstudio/studio/client/workbench/views/console/shell/assist/StanCompletionManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/Token.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/TokenIterator.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/assist/RChunkHeaderParser.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/r/SignatureToolTipManager.java, src/gwt/test/org/rstudio/studio/client/RStudioUnitTestSuite.java, src/gwt/test/org/rstudio/studio/client/workbench/views/source/editors/text/assist/RChunkHeaderParserTests.java
NOTE: Not quite ready for merge (still needs refinement) but putting up for some discussion.
---
This PR implements a completion engine for SQL code:
In particular, we provide completions for:
1. SQL keywords,
2. Tables associated with the current connection,
3. Fields associated with all tables on the current connection.
Note: I'm guessing that (2) and (3) could be quite expensive, so I'm curious if there's a way we could more intelligently populate and / or cache these -- suggestions are welcome. Some thoughts:
1. We could enumerate the context wherein a table name is expected, and only provide the table names there;
2. In other contexts, we could draw field names from the set of tables that have been specified thus far.
=> improve completions for SQL chunks / code

src/cpp/session/SessionMain.cpp
This PR ensures that functions `contributors()` and friends work as expected in the case where the temporary directory is actually within the user's home directory.
=> check whether file lives within tempdir before home (closes #3333)

src/cpp/desktop/DesktopUtils.cpp, src/cpp/desktop/DesktopUtils.hpp, src/cpp/desktop/DesktopWebPage.cpp
This PR ensures that attempts to download `.pdf` files will download those files to a temporary directory and immediately open them, rather than prompting the user to download those files to a particular directory. This ensures that attempts to open vignettes from the help page work as expected, and brings us back in line with v1.1 behavior.
=> ensure vignettes are opened on request (closes #3443)

src/gwt/src/org/rstudio/studio/client/application/ui/AboutDialogContents.ui.xml
This small change makes it possible to select the text naming RStudio's version, build, and user agent string (for convenient copy/paste). 
We formerly made the entire dialog selectable, but did so with a deprecated CSS selector (for QtWebKit); we now make just the interesting regions selectable, and do so with a non-prefixed selector.
=> Allow selecting version, build id, and user agent

src/gwt/src/org/rstudio/core/client/JsVector.java, src/gwt/src/org/rstudio/core/client/JsVectorBoolean.java, src/gwt/src/org/rstudio/core/client/JsVectorInteger.java, src/gwt/src/org/rstudio/core/client/JsVectorNumber.java, src/gwt/src/org/rstudio/core/client/JsVectorString.java, src/gwt/src/org/rstudio/studio/client/workbench/views/vcs/BranchToolbarButton.java
When the RStudio window is focused, we attempt to refresh Git-related state to ensure that elements in the Git pane are up to date. This includes rebuilding the Git branch menu. Unfortunately, this operation can be very slow when there are a large number of branches, as we don't make any effort to truncate the list of branch menu items when populating that list. This can cause an IDE pause (~1 second or more) for projects with a lot of branches (RStudio itself being one).
This PR mitigates the issue in a couple ways:
1. We re-populate the branch menu on-demand; that is, we wait until the user actually clicks on the git branch toolbar button and actually requests the menu (no need to build the menu before we show it to the user),
2. We cache the last-used set of branches, and only update …
=> lazily refresh Git branch menu

src/gwt/src/org/rstudio/core/client/command/KeyboardShortcut.java, src/gwt/src/org/rstudio/core/client/command/ShortcutManager.java, src/gwt/src/org/rstudio/core/rebind/command/ShortcutsEmitter.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefs.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/EditingPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/Source.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/DocDisplay.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorCommandDispatcher.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorCommandEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ace/AceEditorNative.java
I am trying to add Sublime Text key bindings to RStudio and I got some partial success. Just to make sure I am doing things legitimately, I want to get some feedback from RStudio developers before I implement all the features. If they give me a green light, I'd map out the rest of the other keys.
What implemented so far:
In mac, a beep sound may occur. Atom has the same issue and it is a known mac issue: https://apple.stackexchange.com/questions/23981/command-control-arrow-beeps-plays-alert-sound-in-lion
close #3341
=> Sublime Text key bindings

dependencies/windows/install-boost/install-boost.R, dependencies/windows/tools.R
Modified scripts to patch the two issues that are throwing several hundred warnings during build of IDE on Windows. I chose to make these small tweaks on the current version of Boost we are using, and not upgrading. Safer to upgrade Boost early in 1.3.
One fix is to comment out pragma message complaining about unknown compiler version; this is what newer Boost does (literally comments this line out rather than continuing to track MSVC versions).
Other fix ia a pre-proc tweak to prevent use of a non-standard STL method in iostreams that recent MSVC warns about.
Between these, on my machine, a release build of the IDE goes from 816 warnings to 402. The remainder are more significant (size_t vs. int, that sort of thing, and will be easier to look at them when we decide to work on this).
Note …
=> rebuild boost to fix warnings with newer MSVC

src/cpp/r/RExec.cpp
On occasion, R code executed by RStudio behind the scenes will emit an error that is then printed to the console for the user. Debugging such errors can be frustrating, as the regular R tools for debugging these (e.g. installing an error handler) are explicitly disabled while we evaluate such code (of course, this is for good reason -- we don't want user-defined error handlers that might require user input, e.g. `utils::recover()`, to run if an R error is emitted)
This PR adds an R option, `rstudio.errors.suppressed`, which can be toggled to enable / disable suppression of these errors, so that one can install e.g. a traceback handler if so desired.
=> allow user error handlers to run during RStudio R code exec if requested

src/cpp/r/R/Tools.R, src/cpp/session/modules/SessionRmdNotebook.R
This PR seeks to resolve an issue where 'call' / 'symbol' objects within a chunk header could cause notebook generation to fail, e.g. as in https://github.com/rstudio/rstudio/issues/3259.
The underlying issue here is that `knitr` will attempt to evaluate non-literal chunk options; e.g. in the chunk:
`````
```{r, echo=var}
```
`````
`knitr` will attempt to evaluate the variable `var` in determining the value of the `echo` option. This is more commonly seen in SQL chunks as the connection object is typically part of the chunk header, e.g.
`````
```{r, connection=conn}
```
`````
but that connection object `conn` won't exist during notebook creation.
Since we typically don't want this behavior within R Notebooks (we never evaluate code during notebook generation), the solution here is to just …
=> suppress errors during chunk option evaluation

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTargetCommentHeaderHelper.java
Follow up on https://github.com/rstudio/rstudio/pull/3301 with fix for https://github.com/rstudio/rstudio/issues/3518, we want to also support custom source comments that don't include any parameters, as in:
```r
```
and
```r
```
=> Support to sources header comments with no parameters

src/cpp/core/StringUtils.cpp, src/cpp/r/RUtil.cpp, src/cpp/r/include/r/RUtil.hpp, src/cpp/r/session/RStdCallbacks.cpp
=> bring back v1.1-style transliteration during encoding

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Currently, R scripts are only sourced on save if they have a custom source command. This change restores ordinary `source()` behavior for ordinary R scripts. 
Fixes https://github.com/rstudio/rstudio/issues/3566.
=> Fix Source on Save for R scripts

src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/RMarkdownPreferencesPane.java
Closes https://github.com/rstudio/rstudio/issues/2837.
(This feature had already been implemented for quite a while; however, we never exposed the UI preference to users in the past.)
=> allow users to toggle chunk background highlighter

src/cpp/session/modules/SessionPackages.R, src/gwt/src/org/rstudio/studio/client/common/mirrors/model/MirrorsServerOperations.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PreferencesDialog.css
Fix for https://github.com/rstudio/rstudio/issues/3523. CC: @ronblum @kevinushey 
Some Linux distributions ship R with an override to `options(repos = list(CRAN = "url")` hardcoded which makes the preferences dialog not usable by "design".
An easier way to repro this is to simple run:
```{r}
options(repos = list(CRAN = "https://abc.com")
```
and then open the packages preferences dialog, this PR adds the following warning when the option and our preferences are out of sync.
See https://github.com/rstudio/rstudio/issues/3224
=> Show warning when package repos modified outside preferences

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/TextEditingTarget.java
Note that an external edit check is always triggered when the window is focused, so effectively this PR ensures that 'file changed' events are only shown to the user after they re-focus the IDE instance.
=> only trigger external edit checks when focused (closes #3554)

src/cpp/session/modules/SessionCodeTools.R
Note that `shQuote()` also takes care of escaping embedded quotes as necessary, something not done by the previous implementation.
=> properly quote repository names/values (closes #3560)

src/cpp/session/modules/SessionThemes.R, src/cpp/session/modules/SessionThemes.cpp, src/gwt/src/org/rstudio/core/client/files/filedialog/FileSystemDialog.java, src/gwt/src/org/rstudio/studio/client/server/remote/RemoteServer.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/AppearancePreferencesPane.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceTheme.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/model/ThemeServerOperations.java
The API will now return an error if a theme with the same name is added to the same location (e.g. local vs. global). The API will emit a warning if a theme with the same name is added to a different location.
The UI will post an error asking the user to confirm that they wish to delete in the original theme when a theme with the same name is added to the same location. The UI will post a warning indicating that while the existing theme will be overridden, no loss will actually occur and asking for confirmation when a theme with the same name is added to a different location.
=> Add better handling when adding a duplicate theme 

src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkSatelliteWindow.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/ChunkWindowManager.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/events/ChunkSatelliteWindowRegisteredEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/rmd/TextEditingTargetNotebook.java
@MariaSemple and I troubleshooted this one, couple issues:
1. We recently enabled proper theming in satellite chunks but we missed to also mark the window as themeable.
2. At launch, the satellite chunk would not get the right theme. The problem here is that we were listening for the same event in the SatelliteChunkManager and the text editor which would cause us at times to send an event to a window that was not registered. Fixed this by separating the events to ensure the SatelliteChunkManager processes first chunk registration.
=> Fix themes under satellite chunks

src/gwt/src/org/rstudio/studio/client/application/DesktopFrame.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/themes/AceThemes.java
Follow up to PR (pointed out by @kevinushey): https://github.com/rstudio/rstudio/pull/3365
I just upgraded to Mojave, my first impression felt like the dark theme was a bit broken, since the color cuts between the window and the menu:
I experimented with setting the menu bar to be the same as the background to match the title, but feels a bit weird since there is no color distinction. @kevinushey suggested matching the title with the menu, which I think it works well, but certainly open to other suggestions:
Default theme is left unchanged, even though the change is also applied. Seems to me like Mojave only applies title colors that are dark?
Before:
After:
=> Make title window color to match menu color not backgorund color

src/cpp/desktop/DesktopUtilsMac.mm
Mojave can report nonsensical locales in certain configurations. For example, on my machine, after switching to an Italian locale I see:
```R
$ defaults read NSGlobalDomain AppleLocale
en_IT
```
and because no locale called `en_IT.UTF-8` exists on the system, when RStudio is launched a number of warnings are emitted, and R's unicode support fails in general:
```
Warning: Setting LC_CTYPE failed, using "C"
Warning: Setting LC_COLLATE failed, using "C"
Warning: Setting LC_TIME failed, using "C"
Warning: Setting LC_MESSAGES failed, using "C"
Warning: Setting LC_MONETARY failed, using "C"
```
Note: we should consider backporting this to v1.1.
See also:
https://community.rstudio.com/t/strange-locale-problems-in-r-after-update-to-mojave/15533
=> implement fallback + validation for locale detection on macOS

src/gwt/src/org/rstudio/core/rebind/command/ShortcutsEmitter.java, src/gwt/src/org/rstudio/studio/client/KeyboardMonitor.java, src/gwt/src/org/rstudio/studio/client/application/ui/impl/DesktopApplicationHeader.java, src/gwt/src/org/rstudio/studio/client/events/EditEvent.java, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.cmd.xml, src/gwt/src/org/rstudio/studio/client/workbench/commands/Commands.java, src/gwt/src/org/rstudio/studio/client/workbench/prefs/model/UIPrefsAccessor.java, src/gwt/src/org/rstudio/studio/client/workbench/views/source/editors/text/AceEditor.java
This PR provides for separate [Paste] and [Paste and Reindent] commands. With the PR, <kbd>Ctrl + V</kbd> pastes without indent, while <kbd>Ctrl + Shift + V</kbd> pastes and reindents. The implementation works with both RStudio Server and RStudio Desktop.
Some open questions if we take this PR:
1. Do we want to change the default behavior so that <kbd>Ctrl + V</kbd> no longer reindents by default?
2. Should we keep the 'reindent on paste' UI preference, or instead document that one should use <kbd>Ctrl + Shift + V</kbd> if they do want to reindent after pasting?
=> provide separate paste, paste and indent commands

src/cpp/session/modules/SessionRMarkdown.R, src/cpp/session/modules/rmarkdown/SessionRMarkdown.cpp, src/gwt/src/org/rstudio/studio/client/rsconnect/ui/RSConnectPublishButton.java
- detect rendered files for website project in correct location (e.g. _site)
- remove old code that stripped out previous static website publishes from dropdown
- removed unnecessary arguments to private helper `fireDeployDocEvent()`; no need to pass it member variables
Fixes #3430 
Note: this was a scenario missed when implementing #3266
=> enable publish/republish of rendered websites from editor publish button

src/cpp/desktop/rstudio.exe.manifest, src/cpp/desktop/synctex/rsinverse/rsinverse.exe.manifest, src/cpp/desktop/urlopener/urlopener.exe.manifest, src/cpp/diagnostics/diagnostics.exe.manifest, src/cpp/session/consoleio/consoleio.exe.manifest, src/cpp/session/rsession.exe.manifest
fixes #2899 
Use same Windows version list in the application manifest as used by R GUI (adding 8, 8.1, and 10 in addition to existing Vista and Win-7 GUIDs).
On Windows 8.1+ this causes the RStudio processes (including rstudio.exe and rsession.exe) to run in the actual operating system context, instead of the downlevel context.
More specifically, causes `win.version()` to return the actual Windows build instead of being stuck on showing build 9200.
This seems worth taking for 1.2 because it makes RStudio behavior match R GUI in this regard, and is "only" a metadata update (i.e. we can easily remove this if we discover any issues). That said, if we'd rather wait for 1.3, I'd understand.
https://docs.microsoft.com/en-us/windows/desktop/sbscs/application-manifests
=> update win32 manifests to state support for 8, 8.1, 10

src/cpp/session/modules/build/SessionBuild.cpp
When testing `testthat` tests with a package that matches the folder, this works just fine. However, testing a file does not work if the package folder does not match the package name.
Repro:
- Clone https://github.com/rstudio/sparklyr or https://github.com/apache/arrow.
- Rename sparklyr folder to `sparklyr2` or use `arrow/r` path.
- Run test `test-config.R` or `test-RecordBatch.R`.
Actual:
```
==> Testing R file using 'testthat'
Error: Can't find 'arrow'.
Execution halted
Exited with status 1.
```
Expected, test file to run properly.
The problem is that `devtools::load_all()` expects a package name or a package object, which we can retrieve with `devtools::as.package()`.
=> Support for testing testthat files with any package dir name

src/cpp/r/R/Tools.R, src/gwt/src/org/rstudio/studio/client/workbench/prefs/views/PackagesPreferencesPane.java
Fix for https://github.com/rstudio/rstudio/issues/3621
When changing secondary repos, if all are removed changes do not take effect for the secondary repos. This has always been the case, to my knowledge since we were only modifying repos when secondaries where non-empty.
The fix is to always is the secondaries field; however, `setCRANRepos()` is only called if `.rs.isCRANReposFromSettings()` and `!cranMirrorConfigured` which checks the repos for the special `RStudio` attribute to ensure we don't modify CRAN settings set through the RProfile or in other ways, we simply never modify repos that were not set by RStudio.
Also fixes this:
To...
=> Allow secondary repos to be completely removed

src/cpp/session/modules/SessionConnections.R
It is possible to disable ODBC installer connections with:
```
options("connections-installer" = "")
```
However, a warning triggers that is not desirable.
=> Allow disabling connection installers without warnings

src/cpp/session/modules/SessionThemes.R, src/cpp/session/modules/SessionThemes.cpp, src/cpp/tests/testthat/test-themes.R
This PR fixes a number of bugs:
* An issue on windows where a theme file would end up with random numbers after the extension due to the usage of temporary files.
* An issue on windows when paths contain non-ascii characters.
* Safer handling of open files in R code (i.e. ensuring they will always be closed).
* A bug caused by a missing parameter when checking if a theme duplicates an existing theme.
* A bug where newly added `rsthemes` would get a second `.rstheme` extension.
This PR closes #3623 and #3617.
=> Fix themeing's incorrect handling of paths containing non-ascii characters
